- content/en/releases/release-managers.md
In content/en/releases/release-managers.md,
* Add @jrsapi and @jeremyrickard to release manager associate list (https://github.com/kubernetes/sig-release/issues/1965)
/kind documentation
/assign @justaugustus @cpanato @puerco
/hold explicitly for subproject owner approval 
Signed-off-by: Jeremy Rickard <jeremyrrickard@gmail.com>
> releng: Update release managers page for new RMA

- content/en/docs/tutorials/security/seccomp.md
We're now rephrasing those two paragraphs to avoid confusing readers.
Follow-up on https://github.com/kubernetes/website/pull/34640#discussion_r917492894
> Improve 'Seccomp defaulting' feature name

- content/en/docs/contribute/review/reviewing-prs.md
This PR proposes an update to the PR review guidelines. The proposed change is about the use of the "Request changes" or the "Approve" option when finishing a PR review. Neither of these two options should be encouraged. We may want to encourage reviewers to always use "Comment", because:
- "Request changes" status is sticky and unnecessary. Placing a "/hold" should be okay because we do respect opinions from all reviewers/approvers.
The "Request changes" status can only be discarded by people with privileges.
We see quite a few cases where the reviewer left a "Request changes" mark and forgot to revisit a PR.
Such a sticky status is not friendly to contributors or peer reviewers.
- The "Approve" option is confusing. It is not considered by the prow as an approval IIUC. The PR has to be …
> Improve reviewing PRs guide

- content/zh-cn/docs/concepts/security/pod-security-standards.md
Update dead link
```markdown
字段[对 Windows 不起作用](/zh-cn/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#v1-podsecuritycontext)。
```
And re-sync the document with minimal changes.
> [zh] Update pod-security-standards.md

- content/zh-cn/docs/concepts/security/controlling-access.md
Resync with the en version: [/docs/concepts/security/controlling-access](https://kubernetes.io/docs/concepts/security/controlling-access/).
Preview: https://deploy-preview-35169--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/controlling-access/
> [zh-cn] resync /concepts/security/controlling-access.md

- content/de/docs/concepts/containers/images.md
This PR changes the German description of the flag `IsNotPresent` to be more concise. See the discussion in #34978.
> [de] concepts/containers/images: Improve description of IsNotPresent

- content/ko/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive.html
- content/ko/docs/tutorials/configuration/configure-redis-using-configmap.md
- content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/update/update-interactive.html
- content/ko/docs/tutorials/security/cluster-level-pss.md
- content/ko/docs/tutorials/services/source-ip.md
- content/ko/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
- content/ko/docs/tutorials/stateful-application/zookeeper.md
M105 ~ M117 까지, tutorials 와 관련된 변경사항들을 반영하였습니다!
- Related issue : #34903 **(dev-1.24-ko.1)**
> ### 13 files to be modified
>
> 105. [ ]  M105.  `content/en/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive.html`  | 1(+XS) 1(-)
> 106. [ ]  M106.  `content/en/docs/tutorials/configuration/configure-redis-using-configmap.md`  | 3(+XS) 3(-)
> 107. [ ]  M107.  `content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html`  | 1(+XS) 1(-)
> 108. [ ]  M108.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html`  | 1(+XS) 1(-)
> 109. [ ]  M109.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html`  | 1(+XS) 1(-)
> 110. [ ]  M110. …
> [ko] Update outdated files in dev-1.24-ko.2 (M105-M117)

- content/en/docs/concepts/configuration/overview.md
- content/en/docs/concepts/services-networking/dual-stack.md
- content/en/docs/concepts/services-networking/service-traffic-policy.md
- content/en/docs/concepts/services-networking/service.md
- content/en/docs/concepts/workloads/pods/init-containers.md
- content/en/docs/tasks/debug/debug-application/debug-statefulset.md
- content/en/docs/tasks/network/validate-dual-stack.md
- content/en/docs/tasks/run-application/delete-stateful-set.md
- content/en/examples/service/networking/dual-stack-default-svc.yaml
- content/en/examples/service/networking/dual-stack-ipfamilies-ipv6.yaml
- content/en/examples/service/networking/dual-stack-ipv6-svc.yaml
- content/en/examples/service/networking/dual-stack-prefer-ipv6-lb-svc.yaml
- content/en/examples/service/networking/dual-stack-preferred-ipfamilies-svc.yaml
- content/en/examples/service/networking/dual-stack-preferred-svc.yaml
Updates docs to use kubernetes recommended labels
as outlined in the documentation.
- [en] update en docs to use recommended labels
Closes #34115
> update docs labels

- content/en/docs/concepts/containers/runtime-class.md
- content/en/docs/setup/production-environment/container-runtimes.md
containerd config link is pointing to the archived containerd/cri repository
[containerd/cri](https://github.com/containerd/cri) has been merged into [containerd/containerd](https://github.com/containerd/containerd) so nothing should be pointing to containerd/cri repository
> [en] Fix containerd config link

- content/en/docs/reference/glossary/api-eviction.md
The original link https://kubernetes.io/docs/concepts/scheduling-eviction/eviction/#kubelet-eviction is not exists.
It's https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/ with the right name and path.
> Fix link in glossary/api-eviction.md

- content/zh-cn/docs/concepts/containers/runtime-class.md
- content/zh-cn/docs/setup/production-environment/container-runtimes.md
Fix links by following the en revision of #35216.
Preview: https://deploy-preview-35238--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/containers/runtime-class/
> [zh-cn] Fix containerd config link

- content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
Resync this page by following #34740.
```
```
Preview: https://deploy-preview-35236--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers/
> [zh-cn] resync /access-authn-authz/extensible-admission-controllers.md

- content/pt-br/docs/reference/glossary/sig.md
Added translate content/pt-br/docs/reference/glossary/sig.md
> Add content/pt-br/docs/reference/glossary/sig.md

- content/en/docs/tasks/tls/managing-tls-in-a-cluster.md
This PR fixed the links for both custom CA and dedicated CA to redirect the correct section of the [Manage TLS Certificates in a Cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/) task page.
Fixes: #35190
> Fixed Hyperlinks for custom CA and dedicated CA.

- content/zh-cn/docs/concepts/services-networking/service.md
Updated this page with en version and changed some typo and links.
```
```
Preview: https://deploy-preview-35281--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/service/
> [zh-cn] updated /concepts/services-networking/service.md

- content/zh-cn/docs/concepts/configuration/secret.md
This topic has good text in zh-cn. Mainly updated links and format.
```
```
Preview: https://deploy-preview-35284--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/configuration/secret/
> [zh-cn] updated /concepts/configuration/secret.md

- content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
Fix some typos and add `-` in the blank cells of table.
Preview: https://deploy-preview-35089--kubernetes-io-main-staging.netlify.app/docs/concepts/scheduling-eviction/node-pressure-eviction/
> [en] updated /node-pressure-eviction.md

- content/zh-cn/docs/tasks/network/validate-dual-stack.md
Resync with the  en version:
```
content/zh-cn/docs/tasks/network/validate-dual-stack.md
```
Preview: https://deploy-preview-35306--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/network/validate-dual-stack/
> [zh-cn] resync /tasks/network/validate-dual-stack.md

- content/zh-cn/docs/concepts/scheduling-eviction/_index.md
Updated this page with the en version: 
```
content/zh-cn/docs/concepts/scheduling-eviction/_index.md
```
> [zh-cn] resync /concepts/scheduling-eviction/_index.md

- content/ja/docs/reference/using-api/_index.md
- content/ja/docs/setup/release/version-skew-policy.md
`https://git.k8s.io/community/contributors/design-proposals` no longer exists. So change the URL to be the same as https://github.com/kubernetes/website/pull/34976
This PR is a split of https://github.com/kubernetes/website/pull/34948.
> [ja] Fix links in release versioning

- content/zh-cn/blog/_posts/2022-07-13-gateway-api-in-beta.md
Localized this blog:
```
content/blog/_posts/2022-07-13-gateway-api-in-beta.md
```
Fixes #35267 
Preview: https://deploy-preview-35272--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/07/13/gateway-api-graduates-to-beta/
> [zh-cn] sync /blog/_posts/2022-07-13-gateway-api-in-beta.md

- content/zh-cn/blog/_posts/2018-10-10-runtimeclass.md
- content/zh-cn/docs/concepts/containers/runtime-class.md
Change invalid [old link](https://kubernetes.io/zh-cn/docs/concepts/configuration/assign-pod-node/) to the [new link](https://kubernetes.io/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node/) and fix some format.
```diff
例如，要对具有支持不同运行时间的异构节点的集群实施调度程序支持，我们可以在 RuntimeClass 定义中添加
-[NodeAffinity](/zh-cn/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)条件。
+[NodeAffinity](/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)条件。
另一个需要解决的领域是管理可变资源需求以运行不同运行时的 Pod。
```
> [zh-cn] Fix link for runtime-class

- content/ko/examples/application/mysql/mysql-configmap.yaml
- content/ko/examples/application/mysql/mysql-services.yaml
- content/ko/examples/application/mysql/mysql-statefulset.yaml
- content/ko/examples/controllers/job.yaml
- content/ko/examples/pods/pod-with-affinity-anti-affinity.yaml
- content/ko/includes/task-tutorial-prereqs.md
- content/ko/releases/_index.md
- content/ko/releases/version-skew-policy.md
M118~M125 변경사항을 반영한 2차 작업입니다.
Related issue: https://github.com/kubernetes/website/issues/34903
8 files to be modified
M125. content/en/releases/version-skew-policy.md
아래 skew 명칭 변경은 영문 문서 참고하여 전체 적용했습니다.
latestVersion->currentVersion
prevMinorVersion->currentVersionAddMinor -1
skew oldestMinorVersion->currentVersionAddMinor -2
/language ko
> [ko] Update outdated files in dev-1.24-ko.2 'M118-M125'

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
Current:
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity-weight
"If there are two possible nodes that match the **requiredDuringSchedulingIgnoredDuringExecution** rule, one with the label-1:key-1 label and another with the label-2:key-2 label, the scheduler considers the weight of each node and adds the weight to the other scores for that node, and schedules the Pod onto the node with the highest final score."
Change:
If there are two possible nodes that match the **preferredDuringSchedulingIgnoredDuringExecution** rule, one with the label-1:key-1 label and another with the label-2:key-2 label, the scheduler considers the weight of each node and adds the weight to the other scores for that node, and schedules the Pod onto the node with the highest …
> Updates to Node affinity weight section

- content/en/docs/contribute/style/style-guide.md
This PR adds a new section under Documentation formatting standards called "Referring to Kubernetes API resources" which clarifies guidelines about using API resources throughout the documentation.
Closes #34666
> Add clarification about API resources to the Style Guide

- content/en/docs/tasks/tools/install-kubectl-linux.md
Remove dummy package `apt-transport-https` from linux kubectl install instructions
Added note for users using Debian 9 or earlier
Fixes #34275
> Omit `apt-transport-https` from install

- content/en/docs/reference/_index.md
Updated [Reference](https://kubernetes.io/docs/reference/) page.
broken link : [kube-apiserver event rate limit (v1alpha1)](https://kubernetes.io/docs/reference/config-api/apiserver-eventratelimit.v1/)
updated link : [kube-apiserver event rate limit (v1alpha1)](https://kubernetes.io/docs/reference/config-api/apiserver-eventratelimit.v1alpha1/)
/language en
> [en] Fix broken link apiserver-eventratelimit.v1alpha1

- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
the commas caused kubelet service to fail to start. should be omitted.
> Remove commas from kubelet configuration example

- content/en/docs/concepts/security/pod-security-policy.md
- content/en/docs/reference/labels-annotations-taints/_index.md
Solves #30578 according to that comment https://github.com/kubernetes/website/issues/30578#issuecomment-974691745.
I took the liberty to change a command in the tutorial as well because I added a step to check that annotation.
```diff
- kubectl-admin create -f example-psp.yaml
+ kubectl-admin create -f https://k8s.io/examples/policy/example-psp.yaml
```
> Document the deprecated kubernetes.io/psp annotation

- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
Resync with the en version:
```
```
Preview: https://deploy-preview-35328--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node/
> [zh-cn] resync /concepts/scheduling-eviction/assign-pod-node.md

- content/zh-cn/docs/concepts/overview/working-with-objects/names.md
The [old link](https://kubernetes.io/zh-cn/docs/concepts/working-with-objects/labels) is invalid, change to the [new link](https://kubernetes.io/zh-cn/docs/concepts/overview/working-with-objects/labels/). (And it's updated in upstream.)
```diff
-[标签（Labels）](/zh-cn/docs/concepts/working-with-objects/labels)和
+[标签（Labels）](/zh-cn/docs/concepts/overview/working-with-objects/labels/)和
```
> [zh-cn] Sync working-with-objects/names.md

- content/en/docs/tasks/configure-pod-container/configure-service-account.md
I noticed that some of the headings on this page contain periods while others do not. To adhere to the overall convention, I suggest to remove these periods.
> Remove periods from headings

- content/ko/docs/tasks/tls/certificate-rotation.md
- content/ko/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
- content/ko/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
- content/ko/docs/tasks/tools/install-kubectl-linux.md
M101 ~ M104 까지의 변경사항들을 반영하였습니다!
- Related issue : #34903 **(dev-1.24-ko.1)**
> ### 4 files to be modified
>
> 101. [ ] M101. `content/en/docs/tasks/tls/certificate-rotation.md` | 1(+XS) 1(-)
> 101. [ ] M102. `content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md` | 1(+XS) 1(-)
> 101. [ ] M103. `content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md` | 1(+XS) 1(-)
> 101. [ ] M104. `content/en/docs/tasks/tools/install-kubectl-linux.md` | 1(+XS) 2(-)
/language ko
> [ko] Update outdated files in dev-1.24-ko.2 (M101-M104)

- content/ko/docs/reference/access-authn-authz/authorization.md
Fix: #34909
Note: The 2nd change has been applied. The first change has been in separate PR(https://github.com/kubernetes/website/pull/35085)
> Minor typo in korean docs fixed: Fix 02

- content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
html label err, this cause description of namespace in PolicyRule did not appear in right place
Signed-off-by: liulijin <253954033@qq.com>
> [zh-cn]fix err in content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md

- content/ko/docs/setup/_index.md
- content/ko/docs/setup/best-practices/certificates.md
- content/ko/docs/setup/production-environment/_index.md
- content/ko/docs/setup/production-environment/container-runtimes.md
- content/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/ko/docs/setup/production-environment/tools/kubespray.md
M65 ~ M70 까지, setup 페이지와 관련된 변경사항들을 반영하였습니다!
https://github.com/kubernetes/website/pull/34385#discussion_r910614215 에 댓글 남겨주신 내용 참고하여 영문 문서와 라인 수를 동일하게 맞추었습니다!
- Related Issue : #34903 
> ### 6 files to be modified
> 65. [ ]  M65.  `content/en/docs/setup/_index.md`  | 9(+XS) 1(-)
> 66. [ ]  M66.  `content/en/docs/setup/best-practices/certificates.md`  | 1(+XS) 1(-)
> 67. [ ]  **M67.**  `content/en/docs/setup/production-environment/_index.md`  | **157(+L) 141(-)**
> 68. [ ]  M68.  `content/en/docs/setup/production-environment/container-runtimes.md`  | 92(+M) 35(-)
> 69. [ ]  M69.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 1(+XS) 22(-)
> 70. [ ]  M70.  `content/en/docs/setup/production-environment/tools/kubespray.md`  | 2(+XS) 2(-)
/language ko
> [ko] Update outdated files in dev-1.24-ko.2 (M65-M70)

- content/en/docs/concepts/storage/dynamic-provisioning.md
Fixes: #34887 
This PR add hyperlink of `storageclass.kubernetes.io/is-default-class` annotation .
> Add hyperlink to is-default-class annotation

- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
Reverts kubernetes/website#35095
I merged this by mistake without actually checking whether the suggestion by Tim was incorporated or not. The suggested changes for #35095 have now been applied correctly in this PR.
> Remove commas from kubelet configuration example and add suggested changes.

- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
Move exiting content on optional ConfigMaps into the "Understanding ConfigMaps and Pods" section to make it more generic (was a sub-section within "Add ConfigMap data to a Volume" and re-worded it slightly.
Also added in content from https://github.com/kubernetes/website/pull/2334, which was removed in https://github.com/kubernetes/website/pull/2568.
Resolves #9829
> Edit and redo ConfigMap docs

- content/zh-cn/docs/concepts/storage/volume-snapshots.md
Mainly provide a consistent term about `provision` as `制备` in a topic from:
- 提供
- 供应
- 配置
and remove the outdated info by following the en version:
```
content/zh-cn/docs/concepts/storage/volume-snapshots.md
```
> [zh-cn] updated /concepts/storage/volume-snapshots.md

- content/en/docs/tasks/administer-cluster/access-cluster-api.md
Follow up on https://github.com/kubernetes/website/issues/35224
Updated on page [Access Clusters Using the Kubernetes API](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/)
> Fix broken link on Access Clusters Using the Kubernetes API page.

- content/ko/docs/concepts/configuration/organize-cluster-access-kubeconfig.md
- content/ko/docs/concepts/configuration/secret.md
- content/ko/docs/concepts/extend-kubernetes/_index.md
- content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/ko/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
- content/ko/docs/concepts/extend-kubernetes/operator.md
- content/ko/docs/concepts/overview/kubernetes-api.md
- content/ko/docs/concepts/overview/working-with-objects/names.md
M11-M20 변경사항들을 반영하였습니다.
- From #34903 
특이사항으로 M13, M19는 변경 필요사항들이 이미 반영되어있어 수정하지 않았습니다.
---
> ## Updated 
> M11.  `content/en/docs/concepts/configuration/organize-cluster-access-kubeconfig.md`  | 5(+XS) 6(-)
> M12.  `content/en/docs/concepts/configuration/secret.md`  | 28(+S) 17(-)
> M13.  `content/en/docs/concepts/containers/runtime-class.md`  | 1(+XS) 1(-)
> **M14.**  `content/en/docs/concepts/extend-kubernetes/_index.md`  | **108(+L) 48(-)**
> M15.  `content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md`  | 1(+XS) 1(-)
> M16.  `content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md`  | 25(+S) 16(-)
> M17.  `content/en/docs/concepts/extend-kubernetes/operator.md`  | 2(+XS) 0(-)
> M18. …
> [ko] Update outdated files dev-1.24-ko.2 (M11-M20)

- content/zh-cn/docs/reference/glossary/event.md
Fix typos:
```
content/zh-cn/docs/reference/glossary/event.md
```
> [zh-cn] updated /docs/reference/glossary/event.md

- .gitignore
This PR is to add `.hugo_build.lock` to `.gitignore`.
In my recent PR(#35273), I was told that unnecessary file, `.hugo_build.lock`  was added in my commit. This `hugo_build.lock` file is automatically generated during local hugo build from hugo v0.89.0([https://gohugo.io/news/0.89.0-relnotes/#notes](https://gohugo.io/news/0.89.0-relnotes/#notes)) and should not be included in the commit.
Thus, it would be great if we could add `.hugo_build.lock` to `.gitignore` so that others will not make mistake like me.
Also, I double-confirmed that there is no duplicated PR(both open & closed PRs). This suggestion was already made in previous PR(#31721) but it hasn’t been applied yet(since there is no open/closed PR related to this, I guess the author of #31721 forgot to seperate PR).
> Add .hugo_build.lock file to .gitignore

- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
Resync with the en version.
```
content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
```
Preview: https://deploy-preview-35402--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/
> [zh-cn] Resync /migrating-from-dockershim/change-runtime-containerd.md

- content/en/_index.html
Fixing broken KubeCon/CloudNativeCon Europe link.
This PR is for the English version of the website.
> Change KubeCon/CloudNativeCon Europe link

- content/zh-cn/docs/concepts/workloads/pods/init-containers.md
Updated with the en version:
```
```
Preview: https://deploy-preview-35467--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/init-containers/
> [zh-cn] resync /concepts/workloads/pods/init-containers.md

- content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md
- content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
Replaces #34856
This PR makes a series of updates to the Managing Secrets using a Configuration File topic:
- Improve wording for accuracy, especially related to referring to API object definition and creation
- Use the imperative form for steps
- Add numbers to steps
- Consolidate info about stringdata field away from the task flow
- Replace the verify step, which uses kubectl, with a link to the same steps in the Managing Secrets using kubectl topic
Reviewers: please review each of the six commits. I haven't squashed on purpose, to split the changes into independent chunks.
/sig docs
/language en
> Improve Managing Secrets using a Configuration File

- content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
try to improve content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
The original file is: https://kubernetes.io/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration/
> [zh-cn] try to improve content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md

- content/zh-cn/docs/tasks/configmap-secret/managing-secret-using-config-file.md
Preview:
https://github.com/kubernetes/website/pull/35311/files?short_path=499f7d0#diff-499f7d055c08d6f0180acac3bcd266159a8cddd7b5ef0c58d34e54d69346f896
> [zh-cn]sync managing-secret-using-config-file.md

- content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
I have intended to read the explanation of field `spec.ports.targetPort` just now,  but it was missing, so I resync the whole page and found some nits.
> [zh]resync k8s.io/core/v1/service for kubernetes API

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
This PR fixes a code block that has not been closed in [Upgrading kubeadm clusters](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/).
/language en
> [en] Fix unclosed code block

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
This PR is to add some clarification on container restart behavior if Readiness and Liveness Probes fails.  
Fixes #32446
> Add clarity on restart behavior of Readiness and Liveness Probes

- content/en/docs/tasks/tools/install-kubectl-linux.md
This PR fixed the markdown in tabs that are not working under [Install using native package management](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management) 
Fixes: #35482
> Fixed markdown in tabs.

- content/pt-br/includes/task-tutorial-prereqs.md
Fix the Katacoda link by #34428
Original page: [Task Tutorial Prerequisites](https://github.com/kubernetes/website/blob/main/content/pt-br/includes/task-tutorial-prereqs.md) 
> The en PR #34429  is merged.
> [pt-br] fix link about Katacoda

- content/zh-cn/blog/_posts/2022-02-17-updated-dockershim-faq.md
- content/zh-cn/docs/reference/glossary/dockershim.md
- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
For English, `/dockershim` is redirected to `/blog/2022/02/17/dockershim-faq/`.
For Chinese, `/zh-cn/dockershim` is broken and opens a 404 page.
Fix links in 3 files below:
```
content/zh-cn/docs/reference/glossary/dockershim.md
content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
```
Preview: https://deploy-preview-35543--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
Solution: changed the aliases in [content/zh-cn/blog/_posts/2022-02-17-updated-dockershim-faq.md](https://kubernetes.io/zh-cn/blog/2022/02/17/dockershim-faq/)
> [zh-cn] updated /migrate-dockershim-dockerd.md

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Updating the probe level termination grace period notes added as part of https://github.com/kubernetes/website/pull/28930
From the [KEP-2238](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2238-liveness-probe-grace-period#beta-122) page, it was probably intended to say `API server ignores the Probe-level terminationGracePeriodSeconds field` in the docs, but instead said `API server ignores the Pod-level terminationGracePeriodSeconds field` which seems incorrect. 
> Ensure that when feature gate is off in API server, probe-level TerminationGracePeriodSeconds is blanked out.
> Fix text around liveness probe probe-level grace period behavior

- content/id/docs/reference/access-authn-authz/rbac.md
fix capitalized namespace attribute that cause manifest failed to apply
> [id] fix capitalized namespace attribute

- content/en/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
Ref https://github.com/tektoncd/pipeline/issues/4808
cc @vdemeester
> Document per-container termination message limits

- content/ko/docs/concepts/storage/ephemeral-volumes.md
- content/ko/docs/concepts/storage/persistent-volumes.md
- content/ko/docs/concepts/storage/storage-classes.md
- content/ko/docs/concepts/storage/volumes.md
M36 ~ M39의 변경사항들을 업데이트하였습니다 :)
- Related Issue: https://github.com/kubernetes/website/issues/34903
> - [ ] M36. `content/en/docs/concepts/storage/ephemeral-volumes.md` | 1(+XS) 1(-)
> - [ ] M37. `content/en/docs/concepts/storage/persistent-volumes.md` | 11(+S) 2(-)
> - [ ] M38. `content/en/docs/concepts/storage/storage-classes.md` | 1(+XS) 1(-)
> - [ ] M39. `content/en/docs/concepts/storage/volumes.md` | 55(+M) 15(-)
/language ko
> [ko]Fix outdated files in dev-1.24-ko.2 (M36-M39)

- content/ko/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md
- content/ko/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md
M90 ~ M93 까지의 변경사항들을 반영하였습니다( M90 띄어쓰기 변경이므로, 수정사항 없음 )
* Related issue : https://github.com/kubernetes/website/issues/34903 (dev-1.24-ko.1)
> - [ ] M90. content/en/docs/tasks/debug/debug-application/debug-pods.md | 2(+XS) 2(-)
> - [ ] M91. content/en/docs/tasks/debug/debug-cluster/_index.md | 61(+M) 48(-)
> - [ ] M92. content/en/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md | 2(+XS) 2(-)
> - [ ] M93. content/en/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md | 5(+XS) 2(-)
/language ko
> [ko] update outdated korean files in dev-1.24-ko.2 (M90-M93)

- content/en/docs/tasks/administer-cluster/kms-provider.md
Follow up on #35449
Updated page [Using a KMS provider for data encryption](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider)
> Fix broken links on Using a KMS provider for data encryption page

- content/en/docs/concepts/workloads/controllers/job.md
Fix typo:    
containarized -> containerized
> Fix typo "containarized" -> "containerized"

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
minor text changes.
```
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
```
> [zh-cn] updated /kubeadm/kubeadm-init-phase.md

- content/zh-cn/docs/contribute/localization_zh.md
Added two terms:
1. authn (authenticate)
2. authz (authorizer)
Preview: https://deploy-preview-35625--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/localization_zh/
Fixes #35584
> [zh-cn] added terms to glossary

- content/ko/docs/tasks/access-application-cluster/access-cluster-services.md
- content/ko/docs/tasks/access-application-cluster/access-cluster.md
- content/ko/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
- content/ko/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
Related [#34903](https://github.com/kubernetes/website/issues/34903)
M71. access-cluster-services.md
- 104.197.5.247 -> 192.0.2.1 주소 변경
M72
- 변경사항 없음
M73
- https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/   -> /blog/2015/06/the-distributed-system-toolkit-patterns/ 로 변경되었으나 404오류로 변경 보류
M74
- shell script 변경
M75
- indent 4 -> 3
> [ko] outdated korean contents [M71~M75]

- content/zh-cn/docs/tasks/administer-cluster/kms-provider.md
Fix the citation format of some proper nouns and the translation of some Chinese links,eg: kube-apiserver to  `kube-apiserver`  so that it is consistent with the title of the jumped page
> [zh-cn]Sync kms-provider.md

- content/en/releases/version-skew-policy.md
Fixes #12323 
Adds a sentence to say that there's no specific upgrade order required for `kube-controller-manager`, `kube-scheduler`, and `cloud-controller-manager` as long as `kube-apiserver` is upgraded first.
/sig docs
/language en
/cc @liggitt @lavalamp
> Clarify lack of upgrade order for components

- content/en/docs/tasks/debug/debug-cluster/windows.md
In content/en/docs/tasks/debug/debug-cluster/windows.md, there is an orphan link is point to a non-exist anchor(`#dns-limitations`).
According to #31852([comment](https://github.com/kubernetes/website/pull/31852#issuecomment-1049132306), [content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md](https://github.com/kubernetes/website/pull/31852/commits/6568ecfcbfdd38a1ddf35a4f7429ba74185ac7c9#diff-29fa69c79ca964d4cc4a971d7eadbcfdfe203f97bff1a25057771c7444b147c9) L671) , it should point to [this](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#dns-windows).
> fix an orphan link

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
All cniVersion mentioned in the issue is changed into latest "0.4.0"
It is required that minimal "0.4.0" cniVersion latest but in two json file there was cniVersion "0.3.0"
> Bump all cniVersion mentions to at least 0.4.0

- content/en/releases/release-managers.md
Follow up on #35604
Updated the page [Release Managers](https://kubernetes.io/releases/release-managers/)
> Updated link on Release Managers page

- content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
~~The first commit do the minimal reformat for `implementation-details.md` file. (Only adjust spaces)~~ (It's done by #34381)
The second commit replaced two invalid links for TLS Bootstrapping. (ref: PR #33130)
Checked visually the same (with intended space changes).
Preview: https://deploy-preview-34722--kubernetes-io-main-staging.netlify.app/docs/reference/setup-tools/kubeadm/implementation-details/
Production: https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/
/kind cleanup
/label tide/merge-method-squash
> Fix link for TLS bootstrapping

- content/ko/docs/reference/glossary/cidr.md
> [ko] Translate the glossary term 'CIDR' into Korean

- content/de/docs/setup/release/building-from-source.md
The documentation contains lot of dead links in the DE language.
I have noticed that the `{{< param "githubbranch" >}}` was in other portions of the doc, and seems outdated.
I have replaced every occurrence with "master".
> Fix broken link in de

- OWNERS_ALIASES
The PR proposes some changes to the zh-cn localization team.
Based on contributions during the past few months, we'd like to invite
'Sea-n' to our approvers team and 'Winsonsea' to our reviewers team.
At the same time, we will *suspend* the membership of some existing
members who are no longer active in the community by commenting out
their IDs so that PRs are no longer assigned to them. We are not
removing those IDs in hope they will join us when their "conditions"
become "Ready".
> Add/remove zh-cn reviewers

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
Updated by following the upstream en version.
```
content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
```
Preview: https://deploy-preview-35661--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
> [zh-cn] updated network-plugins.md

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability.md
Updated with the en version.
```
content/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability.md
```
Preview: https://deploy-preview-35529--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability/
> [zh-cn] resync /tools/kubeadm/high-availability.md

- content/ko/docs/reference/glossary/sig.md
Resolves #35460 
[SIG Docs에 참여하기](https://kubernetes.io/ko/docs/contribute/participate/)를 참조하여 제목인 SIG를 분과회로 번역할지도 생각해보았는데,
SIG 라는 표현을 유지하는 것이 더 의미가 잘 통하지 않을까 싶어서 제목은 그대로 가고 본문에서 괄호로 넣었습니다!
/language ko
> [ko] Translate the glossary term "SIG"

- content/ko/docs/reference/glossary/ephemeral-container.md
> [ko] Translate the glossary term 'Ephemeral Container' into Korean

- content/ko/docs/reference/glossary/code-contributor.md
> [ko] Translate the glossary term 'Code Contributor' into Korean

- content/ko/docs/reference/glossary/dockershim.md
- content/ko/docs/reference/glossary/helm-chart.md
- content/ko/docs/reference/glossary/host-aliases.md
- content/ko/docs/reference/glossary/kubeadm.md
#35342 
reproducible > ko/docs/reference/tool/_index.md 의 Helm에서 반복 가능한으로 번역되었고, 의미상 통한다고 생각하여 같이 사용하였습니다.
> [ko] Translate the glossary term 'Dockershim, Helm Chart, HostAliases ... etc' into Korean

- content/zh-cn/blog/_posts/2021-04-16-volume-health-monitoring-alpha.md
Fixes: https://github.com/kubernetes/website/issues/35650
2021-04-16-volume-health-monitoring-alpha.md does not have chinese version: https://kubernetes.io/blog/2021/04/16/volume-health-monitoring-alpha-update/
so need to translate it into Chinese
> [zh] Translate 2021-04-16-volume-health-monitoring-alpha.md into Chinese

- content/ko/docs/reference/glossary/horizontal-pod-autoscaler.md
Resolves [#35352](https://github.com/kubernetes/website/issues/35352)
/language ko
> [ko]Translate website/content/en/docs/reference/glossary/horizontal-pod-autoscaler.md into Korean

- content/it/docs/concepts/containers/container-environment.md
The documentation contains lot of dead links in the IT language.
I have noticed that the `{{< param "githubbranch" >}}` was in other portions of the doc, and seems outdated.
I have replaced every occurrence with "master".
> Fix broken link in it

- content/en/blog/_posts/2022-08-04-kubernetes-1.24-deprecations-and-removals.md
Adding the v1.25 mid-cycle blog, which in this case is Removals and Major Changes rather than Removals and Deprecations. A separate article dedicated specifically to the removal of PSP is in the works.
> Add v1.25 deprecation and removal blog article

- content/ko/docs/tasks/configure-pod-container/assign-memory-resource.md
- content/ko/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
- content/ko/docs/tasks/configure-pod-container/configure-runasusername.md
- content/ko/docs/tasks/configure-pod-container/static-pod.md
M84 ~ M89의 변경사항들을 업데이트하였습니다.
- M85의 경우, 업데이트 사항이 영문 오타수정으로 한글에는 변경사항이 없습니다.
- M87의 경우, 변경사항이 문서 가장 마지막의 공백 라인 수의 변경이었는데 이런 변경사항의 경우에도 반영을 하는 것이 맞을까요(이번 커밋에는 원문과 동일하게 문서 마지막의 공백라인수를 맞춰서 변경하였습니다)?
- M89의 경우, 한글화 정기회의에서 논의한 바와 같이 reviewer란을 기존의 공백 대신, 관련 라인들을 모두 주석 처리하는 것으로 변경하였습니다(M84~M88은 원문에 리뷰어가 기재되어있지 않은 상황).
- Related Issue: https://github.com/kubernetes/website/issues/34903
> - [ ]  M84. `content/en/docs/tasks/configure-pod-container/assign-memory-resource.md` | 4(+XS) 4(-)
> - [ ]  M85. `content/en/docs/tasks/configure-pod-container/assign-pods-nodes.md` | 1(+XS) 1(-)
> - [ ]  M86. `content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md` | 2(+XS) 2(-)
> - [ ]  M87. `content/en/docs/tasks/configure-pod-container/configure-pod-initialization.md` | 1(+XS) …
> [ko] update outdated korean contents dev-1.24-ko.1(M84-M89)

- content/zh-cn/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
The English page has changed a lot, and this current page has not been updated for a long time, so that the English and Chinese are synchronized;
eg: [`DownwardAPIVolumeFile`](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/#downwardapivolumefile-v1-core)         to     [`downwardAPI` 卷](/zh-cn/docs/concepts/storage/volumes/#downwardapi)
> [zh-cn]Update downward-api-volume-expose-pod-information.md

- content/en/releases/version-skew-policy.md
Fixes #12324
Add paragraph to recommend that you use the most recent patch version of the minor version that you're upgrading from, and upgrade to the most recent patch version of the target minor version.
/sig docs
/language en
/cc @liggitt @sftim
> Add recommendation to use most recent patch versions of minors

- content/en/docs/concepts/workloads/controllers/job.md
Hi All,
Hope you're doing well.  I was experimenting with the job suspension functionality detailed as follows in the [documentation](https://kubernetes.io/docs/concepts/workloads/controllers/job/#suspending-a-job).
It was not clear (at least, for myself) that the reference to the suspension of "active" Pods, refers to Pods that are in a Non-Completed state.
I've added context to specifically highlight this and hopefully this change will help new users who are navigating this functionality.  This simple differentiator provides a distinct separator that aligns to the Pod status (Completed) and Job terminology (i.e. Completion).
For example -
1. I am running a job that requires 20 Completions (as per spec.completions) and I'm using parallelism of 5
2. I've successfully achieved 10 …
> Added supporting context for job suspension functionality

- content/ko/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
- content/ko/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
- content/ko/docs/tasks/job/automated-tasks-with-cron-jobs.md
Related [#34903](https://github.com/kubernetes/website/issues/34903)
M94. content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md 
- 변경 사항 없음.
M95. content/en/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
- DownwardAPIVolumeFile -> downward API 볼륨으로 변경
- configuration file -> manifest 변경
M96. content/en/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
- M95과 동일
M97. content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
- cron job -> cronJob 변경 
/language ko
> [ko] outdated korean contents [M94~M97]

- content/ko/docs/reference/glossary/proxy.md
Signed-off-by: BrendenHJH <brenden0730@gmail.com>
fix #35494
> [ko] Translate the glossary term Proxy into Korean

- content/ko/docs/tasks/administer-cluster/certificates.md
- content/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
- content/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/ko/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
M76 ~ M79 까지, tasks/administer-cluster 아래 페이지와 관련된 변경사항들을 반영하였습니다!
Related Issue : #34903 
> ### 4 files to be modified
>
> 76. [ ]  **M76.**  `content/en/docs/tasks/administer-cluster/certificates.md`  | **252(+L) 200(-)**
> 77. [ ]  M77.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md`  | 2(+XS) 2(-)
> 78. [ ]  **M78.**  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md`  | **155(+L) 138(-)**
> 79. [ ]  M79.  `content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md`  | 15(+S) 10(-)
/language ko
> [ko] Update outdated files in dev-1.24-ko.2 (M76-M79)

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Clean up the diff found by `./scripts/lsync.sh`, most of which do not affect the zh-cn text, not sure necessary or not.
```
```
Preview: https://deploy-preview-35744--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init/
> [zh-cn] updated /kubeadm/kubeadm-init.md

- content/zh-cn/blog/_posts/2022-05-25-contextual-logging/index.md
translate content/zh-cn/blog/_posts/2022-05-25-contextual-logging/index.md into Chinese
fixes https://github.com/kubernetes/website/issues/35161
> translate content/zh-cn/blog/_posts/2022-05-25-contextual-logging/index.md into Chinese

- content/en/docs/reference/labels-annotations-taints/_index.md
- Cherry-pick 2 commits that mention the `kubernetes.io/psp` annotation
-  After the next merge of _main_ into _dev-1.25_, I can rebase those out.
- Write about the `kubernetes.io/psp` annotation in the past tense.
/language en
/sig auth
/milestone 1.25
Relevant to https://github.com/kubernetes/enhancements/issues/5
> Update PodSecurityPolicy annotation details for v1.25

- content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md
Fix minor errors.
```
content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md
```
Preview: https://deploy-preview-35562--kubernetes-io-main-staging.netlify.app/docs/tasks/configmap-secret/managing-secret-using-config-file/
> Fix some errors in “Managing Secrets using Configuration File”

- content/ko/docs/concepts/workloads/pods/init-containers.md
- content/ko/docs/concepts/workloads/pods/pod-topology-spread-constraints.md
M42 ~ M43 까지, workloads/pods 아래 페이지와 관련된 변경사항들을 반영하였습니다.
M42. content/en/docs/concepts/workloads/pods/init-containers.md | 1(+XS) 0(-)
M43. content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md | 9(+XS) 8(-)
지난 PR이 베이스 브랜치가 잘못 설정되어있었어서 클로즈 후 재 오픈한 PR입니다.
> [ko] Update outdated files in dev-1.24-ko.2 (M42-M43)

- OWNERS_ALIASES
Added myself to sig-docs-ko-owners.
[[Requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-2)]
- Reviewer of the codebase for at least 3 months - I have been a ko-reviewer since [Jan 14, 2021](https://github.com/kubernetes/website/pull/25850#issuecomment-760226352).
- Primary reviewer for at least 10 substantial PRs to the codebase - [is:pr assignee:yoonian](https://github.com/kubernetes/website/pulls?q=is%3Apr+assignee%3Ayoonian)
- Reviewed or merged at least 30 PRs to the codebase
- Reviewed: [is:pr reviewed-by:yoonian](https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Ayoonian)
- Merged: [is:pr is:merged author:yoonian](https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Ayoonian)
/cc …
> Add yoonian to sig-docs-ko-owners

- content/fr/includes/partner-script.js
Fix `Kubernets` to `Kubernetes`
> [fr] Fix `Kubernetes` typo

- content/fr/docs/concepts/services-networking/service.md
- content/fr/docs/concepts/workloads/pods/init-containers.md
Updates docs to use [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) as outlined in the documentation.
Initially included in https://github.com/kubernetes/website/pull/34116 but broken out into a separate PR per https://github.com/kubernetes/website/pull/34116#issuecomment-1145603856 from @Sea-n
> [fr] update fr docs to use recommended labels

- config.toml
According to https://gohugo.io/getting-started/configuration/#timeout, the timeout value should be a duration (e.g. `100s`) or number of milliseconds. Current value of 3000 translates to 3 seconds.
This PR updates the timeout in hope it resolves the netlify preview issues that show up frequently during past weeks.
> Update hugo build timeout

- content/zh-cn/blog/_posts/2022-08-04-kubernetes-1.25-deprecations-and-removals.md
Added zh-cn text for https://kubernetes.io/blog/2022/08/04/upcoming-changes-in-kubernetes-1-25/
```
content/zh-cn/blog/_posts/2022-08-04-kubernetes-1.25-deprecations-and-removals.md
```
Preview: https://deploy-preview-35737--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/08/04/upcoming-changes-in-kubernetes-1-25/
Fixes #35736
> [zh-cn] sync 2022-08-04-kubernetes-1.25-deprecations-and-removals.md

- content/ja/includes/task-tutorial-prereqs.md
Fix the Katacoda link by #34428 
Original page: https://github.com/kubernetes/website/blob/main/content/ja/includes/task-tutorial-prereqs.md
> The en PR #34429  is merged.
> [ja] fix link about Katacoda

- content/en/blog/_posts/2022-08-04-kubernetes-1.25-deprecations-and-removals.md
This PR is a followup PR to address comments and suggestions to the 1.25 deprecations blog https://github.com/kubernetes/website/pull/35426
- https://github.com/kubernetes/website/pull/35426#issuecomment-1202703229
- https://github.com/kubernetes/website/pull/35426#discussion_r937970425
- https://github.com/kubernetes/website/pull/35426#discussion_r937971645
- https://github.com/kubernetes/website/pull/35426#discussion_r937972475
- https://github.com/kubernetes/website/pull/35426#discussion_r937974126
- https://github.com/kubernetes/website/pull/35426#discussion_r937974239
- https://github.com/kubernetes/website/pull/35426#discussion_r937975378
- https://github.com/kubernetes/website/pull/35426#discussion_r937976298
- https://github.com/kubernetes/website/pull/35426#discussion_r937978602 …
> Followup to 1.25 deprecations blog to address comments

- content/en/docs/concepts/cluster-administration/proxies.md
Small fix: on [Proxies in Kubernetes](https://kubernetes.io/docs/concepts/cluster-administration/proxies), "2. The apiserver proxy" links to an anchor `#discovering-builtin-services` which is on `access-cluster-services`, not `access-cluster`.
See correct link [here](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/access-cluster.md?plain=1#L236).
> Fix link on "Proxies in Kubernetes"

- content/en/docs/reference/kubernetes-api/workload-resources/pod-v1.md
Corrected the text link  for [health-cheking.md](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) under grpc.service
> Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).
> 
> If this is not specified, the default behavior is defined by gRPC.
> Updated the health checking link

- config.toml
- content/en/docs/reference/issues-security/issues.md
- content/en/docs/reference/issues-security/official-cve-feed.md
- data/i18n/en/en.toml
- layouts/_default/cve-feed.json
- layouts/shortcodes/cve-feed.html
- Pull JSON blob from queried issues
- Use layout output formats + templates to generate HTML table and JSON blob
- Add localized strings and caption for CVE feed
- Add a new page to describe details about CVE feed and how to use it
- Update existing pages and link the official CVE feed from it
- Not all fields stored in the bucket are needed 
- JSON download directly to a file with Hugo data templates is not possible
- Gives us better control and ability to add extra fields as needed
- Pulling data through hugo data templates allow us to reuse built-in caching mechanisms
To avoid multiple sources of truth. The content in the bucket will remain the only source of truth as the JSON blob is constructed from GitHub issues with label `official-cve-feed` (See this for more info: …
> [KEP-3203] Fetch and Render CVE JSON Feed

- content/en/docs/reference/access-authn-authz/authentication.md
`--service-account-key-file` flag to the `kube-apiserver` is used to verify ServiceAccount tokens (and not to sign them).
`--service-account-signing-key-file` is the [`kube-apiserver` flag](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) that's used to sign ServiceAccount tokens (short-lived ones).
`--service-account-private-key-file` is the [`kube-controller-manager` flag](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) that's used to sign ServiceAccount tokens (long-lived ones).
cc @liggitt
> Fix --service-account-key-file description

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
We plan to graduate minDomains feature to beta in 1.25.
This PR is to update the doc for preparing it.
Part of: https://github.com/kubernetes/enhancements/issues/3022
> Update the doc for minDomains to graduate minDomains to beta

- content/en/docs/concepts/architecture/garbage-collection.md
- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
to be more accurate. It currently says failed,
but then following paragraph includes `Succeeded`.
It seems like replacing "failed" with "terminated" is more accurate.
> Update Pod Lifecycle doc section header

- .gitignore
resolves #35487 
Fixed not only `public` and `resources` in Hugo but also `functions` in Netlify - somebody might also wants content directory name function.
I have checked that the Netlify build uses `functions` on the top level as default.
Comment me if I am wrong!! 🥺 🙇
> Anchor several .gitignore paths

- content/zh-cn/docs/concepts/architecture/garbage-collection.md
- content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
to be more accurate. It currently says failed,
but then following paragraph includes `Succeeded`.
It seems like replacing "failed" with "terminated" is more accurate.
> zh-cn: update Pod Lifecycle doc section header

- content/zh-cn/docs/contribute/style/page-content-types.md
- content/zh-cn/docs/contribute/style/style-guide.md
Updated two files:
```
content/zh-cn/docs/contribute/style/page-content-types.md
```
Preview: https://deploy-preview-35782--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/style/page-content-types/
> [zh-cn] updated style-guide & page-content-types

- content/en/docs/concepts/services-networking/endpoint-slices.md
This PR fixed the FEATURE STATE of `Serving` and `Terminating` in [EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/).
Fixes: #35631
> Updated the Feature state of Serving and Terminating.

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
The Hugo warning message:
```
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.`
```
During investigation, we found that it is caused by `{{< table >}}` without caption.
This fix can only be verify locally since Netlify bot didn't have verbose output.
```bash
git switch main
hugo server --watch=false --debug | grep -B1 WARNING
```
```bash
git fetch upstream pull/35813/head:sean-hugo-fix
git switch sean-hugo-fix
hugo server --watch=false --debug | grep -B1 WARNING
```
There are three occurrence in this repo:
```bash
$ grep -Rl '< table >' content
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md …
```
> Clear some IsSet warnings for Hugo build

- content/en/docs/tasks/administer-cluster/cpu-management-policies.md
This PR updates website for CPU Manager policy option `align-by-socket`  added via KEP-3327
Issue link: https://github.com/kubernetes/enhancements/issues/3327
MR link: https://github.com/kubernetes/kubernetes/pull/111278
> Add docs for KEP-3327 Add CPUManager policy option to align CPUs by Socket instead of by NUMA node

- content/en/releases/download.md
This patch fixes the SBOM documentation section.
- replace reference to "SBOM" with "SPDX", as the former is not a format
- add a link to the SPDX specifications
- correct the "awk" command to reference registry.k8s.io
> Correct download.md's SBOM section

- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
This PR corrects the `param shortcode`  in [Upgrading Windows nodes](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/) task.
Fixes: #35686
> Corrected param shortcode.

- content/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Adapt small change from PR #35813.
- #35813
Checked with `lsync.sh` script.
```bash
./scripts/lsync.sh content/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
```
> [ko] Clear some IsSet warnings for Hugo build

- content/en/docs/concepts/containers/container-lifecycle-hooks.md
This commits substitutes the event name `FailedPreStopHook` with `FailedPostStartHook` to
make instructions consistent according to the example. In the instructions provided, it says 
`FailedPreStopHook` while it leads to the generation of a `FailedPostStartHook`, and that is
what is shown in the corresponding example.
> Fix wrong event name

- content/de/docs/concepts/workloads/pods/_index.md
Changed several occurances of "Pod Vorlage" to the more correct and better to read Pod-Vorlage. 
In german there are two possible options: Podvorlage or Pod-Vorlage, due to readability the version with "-" seems preferable.  
Fixed some typos and duplications
> Fix typo and grammar in german docs

- content/de/docs/concepts/_index.md
Minor typo "bestehet" fixed, added one space for readability and replaced semicolon with dot as those two sentences do not need to be interconnected with semicolon. Dot is more common and usually better to read.
> Fix minor typo in german docs

- content/zh-cn/blog/_posts/2022-08-04-kubernetes-1.25-deprecations-and-removals.md
Updated the zh-cn text by following the en upstream #35789.
```
content/zh-cn/blog/_posts/2022-08-04-kubernetes-1.25-deprecations-and-removals.md
```
Preview: https://deploy-preview-35818--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/08/04/upcoming-changes-in-kubernetes-1-25/
> [zh-cn] resync 2022-08-04-kubernetes-1.25-deprecations-and-removals.md

- content/en/docs/tasks/administer-cluster/sysctl-cluster.md
We now update the documentation to reflect the current state of the feature.
```
In Kubernetes version 1.25, Pod SecurityContext supports slash as sysctl separator
```
Refers to: https://github.com/kubernetes/kubernetes/issues/102373
k/k PR: 
- https://github.com/kubernetes/kubernetes/pull/102393
- https://github.com/kubernetes/kubernetes/pull/106834
> Update docs for setting Sysctls for a Pod and PodSecurityPolicy features to support setting sysctls with slashes.

- content/en/docs/concepts/storage/volume-pvc-datasource.md
Fixes: #35629 
This PR improves documentation on defining cloning support for different `storageclass`  
xref: https://github.com/kubernetes-csi/external-provisioner/pull/699
> improve documentation for Cloning support for  different storage classes 

- content/en/docs/concepts/cluster-administration/proxies.md
- content/en/docs/concepts/containers/images.md
- content/en/docs/concepts/services-networking/connect-applications-service.md
- content/en/docs/concepts/services-networking/dns-pod-service.md
- content/en/docs/concepts/workloads/controllers/deployment.md
- content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
- content/en/docs/setup/production-environment/tools/kubeadm/high-availability.md
- content/en/docs/tasks/access-application-cluster/access-cluster.md
- content/en/docs/tasks/administer-cluster/access-cluster-api.md
- content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
- content/en/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
- content/en/docs/tasks/extend-kubernetes/setup-extension-api-server.md
- content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
- content/en/docs/tasks/tls/managing-tls-in-a-cluster.md
- content/en/docs/tutorials/security/apparmor.md
- content/en/examples/admin/cloud/ccm-example.yaml
This PR fixes some grammatical mistakes in the English documentation where the noun "setup" is used where the correct verb is the two-word phrasal verb "set up".
This PR does not change incorrect usage in blog posts.
( See this page for more explanation: https://grammarist.com/spelling/set-up-vs-setup/ )
> Fix the grammar by using the verb "set up" where appropriate instead of the noun "setup"

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
There are a paragraph deleted in upstream but not synced yet.
Solve `IsSet with "invalid" (<nil>)` warning (2 of 3)
- #35813
---
~~Put comment into `{{< table >}}` shortcode, not sure it will work or not.~~
The Preview seems looks good:
https://deploy-preview-35831--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
> [zh-cn] Sync install-kubeadm.md

- content/en/docs/contribute/new-content/blogs-case-studies.md
The file named `communication/marketing-team/blog-guidelines.md` is moved to `communication/marketing-team/storytelling-resources/blog-guidelines.md` in this [PR](https://github.com/kubernetes/community/pull/5989)
The link to blog-guidelines is updated in the page: https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/
> Updated the blog guidelines link

- content/en/docs/concepts/storage/volumes.md
Update volume migration requirement for in-tree vSphere volume on Kubernetes 1.25 release.
cc: @xing-yang
> update migration requirement for in-tree vSphere volumes

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
When I was reading the network plugin page, I found this translation difficult to understand, which was a little different from the original English meaning.
page: https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
The difference is not very obvious, but when I read it for the first time, I really couldn't understand it. I only knew the meaning after reading the original English text.
Preview page: https://deploy-preview-35869--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
> [zh-cn] Improve network-plugins page

- content/en/docs/concepts/services-networking/network-policies.md
- content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
- content/en/docs/tasks/administer-cluster/cluster-upgrade.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- content/en/docs/tasks/tools/install-kubectl-linux.md
- content/en/docs/tasks/tools/install-kubectl-macos.md
- content/en/docs/tasks/tools/install-kubectl-windows.md
- content/en/releases/notes.md
- content/en/releases/version-skew-policy.md
- This PR is a backport of the PR #34189.
- Closes #31551.
> Fix incorrectly displayed K8s minor versions for `release-1.21` branch

- content/en/docs/concepts/storage/ephemeral-volumes.md
- content/en/docs/concepts/storage/volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
This updates the references to CSIInlineVolume, targeting GA in 1.25.
Enhancement: https://github.com/kubernetes/enhancements/issues/596
Feature gate PR: https://github.com/kubernetes/kubernetes/pull/111258
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/596-csi-inline-volumes/README.md
/hold for feature gate PR to merge
> KEP-596: Move CSIInlineVolume to GA

- content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
This reverts commit b9da040a08373cf764f4e93df32df182bbd8a835 / PR https://github.com/kubernetes/website/pull/30348. That PR documented a bug in Kustomize as though it were a feature, and unfortunately nobody from the Kustomize team saw the PR. 
The bug in question dates back to the origins of Kustomize, when some of the original code was [copied out](https://github.com/kubernetes/kubectl/pull/198/files#diff-3b07013480d8cba7d964080b404d5714115f7225e9d299c86d681ce90727fd5dR67) of kubectl, and this undesirable behaviour (for kustomize, not kubectl) went unnoticed in the adaptation. That explains why the code (written for kubectl) had comments that made it seem like the behaviour was intentional.
This behaviour is a clear violation of one of Kustomize's core principles, as documented in our …
> Revert documentation of Kustomize bug as a feature

- content/pt-br/partners/_index.html
Fixed the broken link on the [partners page](https://kubernetes.io/pt-br/partners/#kcsp) by resyncing with en, de, ko, and zh-cn.
Preview: https://deploy-preview-34963--kubernetes-io-main-staging.netlify.app/pt-br/partners/
> [pt-br] resync /partners/_index.html

- content/en/releases/_index.md
- content/en/releases/version-skew-policy.md
This is a backport of these suggestions: [1](https://github.com/kubernetes/website/pull/34349#pullrequestreview-1010185820), [2](https://github.com/kubernetes/website/pull/34349#pullrequestreview-1010187903), and [3](https://github.com/kubernetes/website/pull/34349#pullrequestreview-1010188253).
[[As-is](https://v1-23.docs.kubernetes.io/releases/version-skew-policy/#:~:text=three%20minor%20releases%20(-,1.23%2C%201.22%2C%201.21,-).%20Kubernetes%201.19%20and)]
[To-be]
[Related issues/PRs]
- #31551
- #34349
- #34346
- #35913
- #35914 (`main` branch)
- ...
[CC]
- @sftim (from [#34349](https://github.com/kubernetes/website/pull/34349))
- @tengqm (from [#34346](https://github.com/kubernetes/website/pull/34346))
> Revert wrong K8s minor version displays in v1.23 docs

- content/en/docs/setup/release/version-skew-policy.md
This is a backport of [this suggestion](https://github.com/kubernetes/website/pull/34349#pullrequestreview-1010188253).
[[As-is](https://v1-20.docs.kubernetes.io/docs/setup/release/version-skew-policy/#:~:text=three%20minor%20releases%20(-,1.20%2C%201.19%2C%201.18,-).%20Kubernetes%201.19%20and)]
[To-be]
[Related issues/PRs]
- #31551
- #34349
- #34346
- ...
[CC]
- @sftim (from [#34349](https://github.com/kubernetes/website/pull/34349))
- @tengqm (from [#34346](https://github.com/kubernetes/website/pull/34346))
> Revert wrong K8s minor version displays in v1.20 docs

- content/en/docs/tutorials/security/seccomp.md
Mainly removed an extra `{` on line 66.
```
content/en/docs/tutorials/security/seccomp.md
```
Preview: https://deploy-preview-35902--kubernetes-io-main-staging.netlify.app/docs/tutorials/security/seccomp/
> updated /tutorials/security/seccomp.md

- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
adds docs for StatefulSet MinReadySeconds GA promotion
- https://github.com/kubernetes/enhancements/issues/2599
- https://github.com/kubernetes/kubernetes/pull/110896
> Promote StatefulSet MinReadySeconds to GA

- OWNERS_ALIASES
Adds [Garima Negi](https://github.com/Garima-Negi) as a reviewer and removes @mittalyashu (inactivity for long term) for Hindi l10n as discussed on [Slack](https://kubernetes.slack.com/archives/CJ14B9BDJ/p1655230491320389)
Ref: https://github.com/kubernetes/org/pull/3559
> Update reviewer for Hindi l10n

- content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
Fix up https://github.com/kubernetes/website/pull/35758
plus, some further tweaks to https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#generate-static-pod-manifest-for-local-etcd that seemed reasonable to make.
/milestone 1.25
This is probably easiest to review commit-by-commit.
> Fix bad merge for kubeadm etcd static pod 

- content/en/docs/concepts/security/pod-security-admission.md
Update the PSA docs for stable release in v1.25
Includes:
- Update feature state references, remove feature gate reference.
- Remove references to PSP (note this conflicts with https://github.com/kubernetes/website/pull/33512)
- Remove webhook instructions, as the built-in controller is now widely available, and the webhook is not well supported.
/assign @liggitt
> Update Pod Security Admission docs for graduation to stable

- content/en/docs/concepts/overview/kubernetes-api.md
- content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
The invalid syntax will make GitHub Markdown parser broken. It caused us hard to review by GitHub webpage.
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/overview/kubernetes-api.md?plain=1#L96
https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md?plain=1#L143
> Fix JSON syntax

- content/zh-cn/docs/concepts/overview/kubernetes-api.md
Updated the text by following the en upstream.
```
content/zh-cn/docs/concepts/overview/kubernetes-api.md
```
Preview: https://deploy-preview-35965--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/overview/kubernetes-api
> [zh-cn] resync /concepts/overview/kubernetes-api.md

- content/en/docs/contribute/style/hugo-shortcodes/index.md
- content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
- content/en/docs/tutorials/security/seccomp.md
Delete the extra `{` and `}` according to [this PR](https://github.com/kubernetes/website/pull/35902), I found that other files also have issues, and propose to correct them together.
Listed below:
```
1. content/en/docs/contribute/style/hugo-shortcodes/index.md
2. content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
3. content/en/docs/tutorials/security/seccomp.md
```
> Fix the extra '{' or '}'  in different files

- content/en/docs/concepts/services-networking/network-policies.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
This PR updates docs for the NetworkPolicy port range enhancement that is graduating to stable in 1.25 by the following:
- updates the feature state on the [Targeting a Range of Ports section on the Network Policies page](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports) to 1.25
- updates the Feature Gates page for _NetworkPolicyEndPort_ and moves entries from _Feature gates for Alpha or Beta features_ section to the _Feature gates for graduated or deprecated features_ section and adding an entry for 1.25 to GA 
Enhancement issue: https://github.com/kubernetes/enhancements/issues/2079
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2079-network-policy-port-range
/sig network
/milestone 1.25
/assign @kcmartin …
> Update docs for NetworkPolicy port range to GA for 1.25

- content/en/docs/concepts/configuration/manage-resources-containers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
> Update LocalStorageCapacityIsolation GA

- content/en/docs/reference/labels-annotations-taints/_index.md
- content/en/docs/tutorials/security/seccomp.md
From the release notes of https://github.com/kubernetes/kubernetes/pull/109819, we have to update according to the following situation:
```
Action required: support for the alpha seccomp annotations
`seccomp.security.alpha.kubernetes.io/pod` and
`container.seccomp.security.alpha.kubernetes.io`, deprecated since
v1.19, has been partially removed. Kubelets no longer support the
annotations, use of the annotations in static pods is no longer
supported, and the seccomp annotations are no longer auto-populated when
pods with seccomp fields are created. Auto-population of the seccomp
fields from the annotations is planned to be removed in 1.27. Pods
should use the corresponding pod or container
`securityContext.seccompProfile` field instead.
```
Refers to …
> Partly remove support for seccomp annotations

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/concepts/workloads/pods/disruptions.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/job/pod-failure-policy.md
- content/en/examples/controllers/job-pod-failure-policy-example.yaml
- content/en/examples/controllers/job-pod-failure-policy-failjob.yaml
- content/en/examples/controllers/job-pod-failure-policy-ignore.yaml
> Add docs for KEP-3329 Retriable and non-retriable Pod failures for Jobs

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/using-api/api-concepts.md
Docs for https://github.com/kubernetes/enhancements/issues/2885
> Field Validation API Concepts

- content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
Updates the doc for enabling bash autocompletion in current session.
Fixes https://github.com/kubernetes/website/issues/35931
https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/#bash
No
> Enable AutoCompletion in Current Session of Bash

- content/zh-cn/docs/tasks/configure-pod-container/quality-service-pod.md
Updated the code to create pod by following en upstream, and added anchors. When I updated #35992, found the anchor below doesn't work:
```
[Guaranteed 的 Pod](/zh-cn/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed)
```
Current file path is:
```
content/zh-cn/docs/tasks/configure-pod-container/quality-service-pod.md
```
Preview: https://deploy-preview-35993--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/quality-service-pod/
> [zh-cn] updated quality-service-pod.md

- content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
- content/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
- content/zh-cn/docs/tutorials/security/seccomp.md
Update page of 'Custom Hugo Shortcodes'.
```
1. content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
2. content/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
3. content/zh-cn/docs/tutorials/security/seccomp.md
```
* Fix the extra '{' or '}' in different files https://github.com/kubernetes/website/pull/35952
* [Add the Anchor](https://github.com/kubernetes/website/pull/35952)
> [zh] Update (localized) style guide page on Hugo shortcodes

- content/en/docs/concepts/workloads/pods/disruptions.md
Cleanup after: https://github.com/kubernetes/website/pull/35219
> Docs cleanup for "KEP-3329 Retriable and non-retriable Pod failures for Jobs"

- content/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
Capitalized the words `shell` and `bash` in the localized desc text. Not sure my changes are correct or not.
```
content/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
```
Preview: https://deploy-preview-36008--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/
> [zh-cn] resync optional-kubectl-configs-bash-linux.md

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/concepts/storage/storage-classes.md
- content/en/docs/concepts/storage/volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
This PR updates CSI migration status for various plugins and also remove some plugins that are no longer supported.
KEP: https://github.com/kubernetes/enhancements/issues/625
> Update CSI migration feature status, and remove docs for unsupported plugins

- content/en/docs/concepts/workloads/controllers/job.md
Cleanup after: https://github.com/kubernetes/website/pull/35219
> Fix link for "KEP-3329 Retriable and non-retriable Pod failures for Jobs"

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
In v1.25, the ProbeTerminationGracePeriod feature gate will be on by default. This PR updates the feature gate docs with this information.
xref https://github.com/kubernetes/enhancements/issues/2238
> [dev-1.25] Update feature gate docs for probe-level termination grace period

- content/en/docs/concepts/cluster-administration/system-traces.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
> Add docs for KubeletTracing feature gate 1.25

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
The feature has been promoted to beta in Kubernetes 1.25. Here is the doc update.
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2876-crd-validation-expression-language/README.md
> Promoting feature CustomResourceValidationExpressions to beta

- content/zh-cn/docs/reference/access-authn-authz/rbac.md
Removed a sentence by following the en upstream #35918.
```
```
Preview: https://deploy-preview-36031--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/rbac/
> [zh-cn] resync /access-authn-authz/rbac.md

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Signed-off-by: kerthcet <kerthcet@gmail.com>
Ref: https://github.com/kubernetes/enhancements/issues/3094
> Document the new NodeInclusionPolicyInPodTopologySpread feature gate

- content/en/docs/concepts/containers/images.md
This PR updates the Images page to mention the types for `imagePullSecrets` which are accepted.
Fixes: #35154
> Add the accepted types for `imagePullSecrets`

- content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
- content/en/examples/application/php-apache.yaml
This PR removes unnecessary instructions while demonstrating HorizontalPodAutoscaler.
Fixes: #34317
> Remove unnecessary instructions for HPA task

- content/en/docs/tasks/debug/debug-cluster/crictl.md
Fix JSON definition of pod sandbox in debugging cluster with crictl page.
It currently has one line from YAML that has camel case notation instead of snake case which makes crictl ignore unrecognized field and container subsequently created in the pod sandbox cannot produce logs because logs directory is not set for Pod sandbox.
Second definition of pod on the same page has log_directory correctly spelled in JSON notation, but with mismatching name of the sandbox.
> Fix Pod spec in debugging crictl

- content/en/docs/concepts/windows/intro.md
- content/en/docs/concepts/windows/user-guide.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
xref: https://github.com/kubernetes/enhancements/issues/2802
> Promote PodOS field to GA

- content/en/docs/reference/access-authn-authz/admission-controllers.md
This PR updates the admission controllers page by:
- removing two plugins which have been removed since 1.18
- removing text about ancient history
- removing shortcode about plugins that graduated into GA a long time ago;
> Update admission controllers page

- content/en/docs/concepts/workloads/pods/ephemeral-containers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/debug/debug-application/debug-running-pod.md
This PR updates the website to reflect ephemeral containers graduating to GA.
Checklist before review:
> Mark EphemeralContainers as GA in 1.25

- content/zh-cn/docs/tasks/debug/debug-cluster/crictl.md
Updated by following the en version #35871.
```
content/zh-cn/docs/tasks/debug/debug-cluster/crictl.md
```
Preview: https://deploy-preview-36055--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-cluster/crictl/
> [zh-cn] resync /debug/debug-cluster/crictl.md

- content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
- content/zh-cn/examples/application/php-apache.yaml
updated text by followng en verson #35745.
```
content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
content/zh-cn/examples/application/php-apache.yaml
```
Preview: https://deploy-preview-36056--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
> [zh-cn] resync horizontal-pod-autoscale-walkthrough.md

- content/en/docs/concepts/workloads/pods/user-namespaces.md
- content/en/docs/tasks/configure-pod-container/user-namespaces.md
- content/en/examples/pods/user-namespaces-stateless.yaml
Draft PR for user namespaces support in pods, phase 1 (KEP-127).
KEP issue: https://github.com/kubernetes/enhancements/issues/127
cc @giuseppe
> Add docs for user namespaces in pods - phase 1 (KEP-127)

- OWNERS
- OWNERS_ALIASES
I found it strange to see the bot add @celestehorgan as an approver for a previous PR since she has moved on. Maybe she's still contributing to the k8s docs, but I don't think so. I followed Zach's example in #27637.
/cc @nate-double-u @jimangel @sftim
> Remove celestehorgan as approver

- content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
Updated text by following the en version #36018.
```
```
Preview: https://deploy-preview-36070--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/admission-controllers/
> [zh-cn] resync /access-authn-authz/admission-controllers.md

- content/en/docs/reference/labels-annotations-taints/_index.md
This PR Registered and documented the cluster-autoscaler.kubernetes.io/enable-ds-eviction annotation under [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/).
Fixes: #35851
> Added Documents for cluster-autoscaler.kubernetes.io/enable-ds-eviction annotation.

- content/en/docs/contribute/participate/_index.md
Although `(owners, reviews)` is weird to me, it's the current group name.
- sig-docs-leads
- sig-docs-en-owners
- sig-docs-en-reviews
- sig-docs-zh-owners
- sig-docs-zh-reviews
- sig-docs-leads
- sig-docs-en-owners
- sig-docs-en-reviews
- sig-docs-zh-owners
- sig-docs-zh-reviews
- sig-docs-blog-owners
- sig-docs-blog-reviewers
> Change sig-docs-xx-reviewers to -reviews in docs

- content/zh-cn/docs/tasks/tls/manual-rotation-of-ca-certificates.md
Updated text by following the en version https://github.com/kubernetes/website/pull/32942.
Location: https://github.com/kubernetes/website/blob/main/content/zh-cn/docs/tasks/tls/manual-rotation-of-ca-certificates.md?plain=1#L101-L135
> [zh-cn] resync /tls/manual-rotation-of-ca-certificates.md

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
This file is out of sync with the English upstream, and the script can no longer check for unsynchronized areas.
I re-checked the whole file manually and it was a particularly bad experience, it took me almost 2 hours. (╯︵╰)
Fixes https://github.com/kubernetes/website/issues/36064
> [zh-cn] Resync manage-resources-containers page

- content/zh-cn/docs/concepts/cluster-administration/flow-control.md
Updated text by following the en version #35791.
```
```
Preview: https://deploy-preview-36069--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/flow-control/
> [zh-cn] resync /cluster-administration/flow-control.md

- content/en/docs/tutorials/services/source-ip.md
In this page https://kubernetes.io/docs/tutorials/services/source-ip/
for this command 
```bash
kubectl get pod -o wide -l run=source-ip-app
```
according to the pod labels it should be 
```bash
kubectl get pod -o wide -l app=source-ip-app
```
> `run=source-ip-app` is changed into `app=source-ip-app`

- content/zh-cn/blog/_posts/2022-04-07-Kubernetes-1-24-removals-and-deprecations.md
Updated the text by following en upstream #36081.
```
content/zh-cn/blog/_posts/2022-04-07-Kubernetes-1-24-removals-and-deprecations.md
```
Preview: https://deploy-preview-36116--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/
> [zh-cn] resync 2022-04-07-Kubernetes-1-24-removals-and-deprecations.md

- content/zh-cn/docs/concepts/extend-kubernetes/operator.md
Updated the zh-cn text after reading #35753.
```
content/zh-cn/docs/concepts/extend-kubernetes/operator.md
```
Preview: https://deploy-preview-36091--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/extend-kubernetes/operator/
> [zh-cn] updated extend-kubernetes/operator.md

- content/zh-cn/docs/tutorials/services/source-ip.md
Updated text by following the en upstream #36096.
```
content/zh-cn/docs/tutorials/services/source-ip.md
```
Preview: https://deploy-preview-36140--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/services/source-ip/
> [zh-cn] resync /services/source-ip.md

- content/uk/docs/setup/production-environment/_index.md
- content/uk/docs/setup/production-environment/on-premises-vm/_index.md
- content/uk/docs/setup/production-environment/turnkey/_index.md
- content/uk/docs/setup/production-environment/windows/_index.md
- content/uk/docs/tutorials/kubernetes-basics/_index.html
This PR is about the netlify preview issues. Based on some initial experiments (e.g. #36103), the netlify preview build often stuck at generating `/uk/docs/setup/production-environment/index.html` or `/uk/docs/tutorials/kubernetes-basics/update/index.html`.
This PR attempts to change these pages without disrupting any existing efforts in UK localizations.
Some outdated placeholders are removed to make sure the docs build.
> [uk] Cleanup some UK pages

- content/en/docs/concepts/security/pod-security-standards.md
xref:  https://github.com/kubernetes/enhancements/issues/2802
> Update pod security standards to use PodOS field

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/node/kubelet-checkpoint-api.md
Pull request for KEP 2008:
* https://github.com/kubernetes/enhancements/pull/1990
* https://github.com/kubernetes/enhancements/issues/2008
* https://github.com/kubernetes/kubernetes/pull/104907
* https://github.com/kubernetes/website/pull/31753 (previous PR for 1.24 (not merged))
CC: @sftim (you reviewed my previous 1.24 attempt of this documentation PR)
> Add documentation for container checkpointing feature (KEP 2008)

- content/en/docs/concepts/workloads/pods/_index.md
Include Pod OS field in the pod concepts.
> Include Pod OS field

- content/zh-cn/docs/concepts/security/pod-security-policy.md
- content/zh-cn/docs/reference/glossary/host-aliases.md
- content/zh-cn/docs/reference/glossary/kubelet.md
1. Update out-of-sync content in English
2. Fix 404 links.
3. Fix fail render.
As follows:
```
1. content/zh-cn/docs/concepts/security/pod-security-policy.md
2. content/zh-cn/docs/reference/glossary/host-aliases.md
3. content/zh-cn/docs/reference/glossary/kubelet.md
```
> [zh] Fix some 404 links

- content/en/docs/reference/labels-annotations-taints/_index.md
Similar to APIs, we don't delete legacy taints and labels from the page, we leave them there and mark them as deprecated.
Reinstate taint `node-role.kubernetes.io/master` (was removed in PR https://github.com/kubernetes/website/pull/33834).
[Preview](https://deploy-preview-36173--kubernetes-io-vnext-staging.netlify.app/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-master-taint)
> Reinstate legacy taint for control plane nodes

- content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
Updated the zh-cn text by following en upstream #35856.
```
content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
```
Preview: https://deploy-preview-36175--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-application/debug-running-pod/
> [zh-cn] resync debug-running-pod.md

- config.toml
update release-1.21 config.toml for new release 1.25
Version were updated according to [latest patch releases](https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md)
/cc @kcmartin @didicodes @sethmccombs @krol3 @reylejano
> update release-1.21 config.toml for release 1.25

- config.toml
update release-1.22 config.toml for new release 1.25
Version were updated according to [latest patch releases](https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md)
/cc @kcmartin @didicodes @sethmccombs @krol3 @reylejano
> update release-1.22 config.toml for release 1.25

- config.toml
update release-1.23 config.toml for new release 1.25
Version were updated according to [latest patch releases](https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md)
replaces https://github.com/kubernetes/website/pull/36178
> Update config.toml for release-1.23

- config.toml
This PR fixes the config.toml for the release-1.21 branch
The 1.24 version pointed to the 1.25 (kubernetes.io) docs instead of v1-24.docs.kubernetes.io
> Fix config.toml for release-1.21 branch

- config.toml
This PR fixes the config.toml for the release-1.22 branch
The 1.24 version pointed to the 1.25 (kubernetes.io) docs instead of v1-24.docs.kubernetes.io
> Fix release-1.22 config.toml

- content/zh-cn/docs/concepts/workloads/controllers/statefulset.md
Clean up the difference found by `./scripts/lsync.sh`.
```
content/zh-cn/docs/concepts/workloads/controllers/statefulset.md
```
Preview: https://deploy-preview-36161--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/statefulset/
> [zh-cn] resync /controllers/statefulset.md

- content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md
Description:
Deploy and Access the Kubernetes Dashboard should use v2.6.0 yaml file
Proposed Solution:
Updated Yaml version from 2.5 to 2.6
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui
fixes: #35766
> Updated the web-ui-dasboard.md

- content/en/blog/_posts/2022-08-16-csi-inline-volumes-ga.md
- content/en/blog/_posts/2022-08-29-csi-inline-volumes-ga.md
Add blog entry about CSI Inline Volumes graduating to GA
Enhancement: https://github.com/kubernetes/enhancements/issues/596
Feature gate PR: https://github.com/kubernetes/kubernetes/pull/111258
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/596-csi-inline-volumes/README.md
> Add blog about CSI Inline Volumes GA

- content/en/docs/concepts/services-networking/connect-applications-service.md
Fixes #34388 
I have changed this command `kubectl get pods -l run=my-nginx -o yaml | grep podIP
`
with this command `kubectl get pods -l run=my-nginx -o custom-columns=POD_IP:.status.podIPs`.
> updated grep with custom-columns=POD_IP:.status.podIPs

- content/zh-cn/docs/concepts/configuration/secret.md
Main change is from `k8s.gcr.io` to `registry.k8s.io`.
```
```
Preview: https://deploy-preview-36219--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/configuration/secret/
> [zh-cn] sync1.25 /configuration/secret.md

- content/zh-cn/docs/concepts/storage/storage-classes.md
Removed text about Quobyte, ScaleIO, and StorageOS.
```
content/zh-cn/docs/concepts/storage/storage-classes.md
```
Preview: https://deploy-preview-36223--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/storage-classes/
> [zh-cn] sync1.25 /storage/storage-classes.md

- content/ko/examples/pods/pod-with-affinity-anti-affinity.yaml
- content/ko/examples/pods/pod-with-node-affinity.yaml
- content/ko/examples/service/networking/dual-stack-default-svc.yaml
- content/ko/examples/service/networking/dual-stack-ipfamilies-ipv6.yaml
- content/ko/examples/service/networking/dual-stack-ipv6-svc.yaml
- content/ko/examples/service/networking/dual-stack-prefer-ipv6-lb-svc.yaml
- content/ko/examples/service/networking/dual-stack-preferred-ipfamilies-svc.yaml
- content/ko/examples/service/networking/dual-stack-preferred-svc.yaml
- content/ko/releases/version-skew-policy.md
M66-M76 변경사항을 반영하였습니다.
- From #35802 
M66, M67은 변경 필요사항이 이미 반영되어 있어 수정하지 않았습니다.
> M66. content/en/examples/admin/konnectivity/egress-selector-configuration.yaml | 1(+XS) 1(-)
> M67. content/en/examples/controllers/job.yaml | 1(+XS) 1(-)
> M68. content/en/examples/pods/pod-with-affinity-anti-affinity.yaml | 2(+XS) 3(-)
> M69. content/en/examples/pods/pod-with-node-affinity.yaml | 3(+XS) 2(-)
> M70. content/en/examples/service/networking/dual-stack-default-svc.yaml | 2(+XS) 2(-)
> M71. content/en/examples/service/networking/dual-stack-ipfamilies-ipv6.yaml | 2(+XS) 2(-)
> M72. content/en/examples/service/networking/dual-stack-ipv6-svc.yaml | 2(+XS) 2(-)
> M73. content/en/examples/service/networking/dual-stack-prefer-ipv6-lb-svc.yaml | 2(+XS) 2(-)
> M74. …
> [ko] Update outdated files dev-1.24-ko.3 (M66-M76)

- content/ko/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
- content/ko/docs/concepts/services-networking/dual-stack.md
- content/ko/docs/concepts/services-networking/service-traffic-policy.md
- content/ko/docs/concepts/services-networking/service.md
M8, M19-21의 변경사항을 반영하였습니다 :) M8의 경우, 리뷰어 주석을 추가하였습니다.
- Related issue: https://github.com/kubernetes/website/issues/35802
> - [ ]  M9. `content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md` | 24(+S) 10(-)
> - [ ]  M19. `content/en/docs/concepts/services-networking/dual-stack.md` | 9(+XS) 9(-)
> - [ ]  M20. `content/en/docs/concepts/services-networking/service-traffic-policy.md` | 1(+XS) 1(-)
> - [ ]  M21. `content/en/docs/concepts/services-networking/service.md` | 101(+L) 57(-)
> [ko]Update outdated korean contents in the dev-1.24-ko.3 (M8, M19-21)

- content/en/docs/reference/access-authn-authz/abac.md
- content/en/docs/reference/access-authn-authz/admission-controllers.md
Fix minor typos in:
```
content/en/docs/reference/access-authn-authz/abac.md
content/en/docs/reference/access-authn-authz/admission-controllers.md
```
> Fix typos on /access-authn-authz

- config.toml
- layouts/partials/head.html
- Contributes to #35299
Preparatory step:
> Google analytics: use GA4 site tag

- content/en/docs/reference/glossary/sig.md
Updated [SIG](https://kubernetes.io/docs/reference/glossary/?all=true#term-sig) in glossary.
broken anchor : [sig-list.md#master-sig-list](https://github.com/kubernetes/community/blob/master/sig-list.md#master-sig-list)
updated anchor : [sig-list.md#special-interest-groups](https://github.com/kubernetes/community/blob/master/sig-list.md#special-interest-groups)
/language en
> [en] Fix missing anchor to SIG list

- content/en/docs/concepts/storage/storage-classes.md
Fixes #36079
Updated page [Storage Classes](https://kubernetes.io/docs/concepts/storage/storage-classes/).
> Modify link context on Storage Classes page

- content/en/docs/reference/using-api/api-concepts.md
This tiny PR adds `remainingItemCount` to the example response from a GET call to list items with a limit as I think it makes sense in the context of `remainingItemCount` [being mentioned after the example output](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes:~:text=remainingItemCount%20is%20the%20number%20of%20subsequent%20items%20in%20the%20collection%20that%20are%20not%20included%20in%20this%20response.%20If)
Signed-off-by: irbekrm <irbekrm@gmail.com>
> Adds remainingItemCount to HTTP response

- content/zh-cn/docs/concepts/cluster-administration/system-traces.md
Added new localized text.
```
content/zh-cn/docs/concepts/cluster-administration/system-traces.md
```
Preview: https://deploy-preview-36220--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/system-traces/
> [zh-cn] sync1.25 /cluster-administration/system-traces.md

- content/zh-cn/docs/reference/glossary/addons.md
- content/zh-cn/docs/reference/glossary/admission-controller.md
- content/zh-cn/docs/reference/glossary/affinity.md
- content/zh-cn/docs/reference/glossary/aggregation-layer.md
- content/zh-cn/docs/reference/glossary/annotation.md
Update about reference/glossary,this chapter is often used, so make adjustments.
the following
```
content/zh-cn/docs/reference/glossary/addons.md
content/zh-cn/docs/reference/glossary/admission-controller.md
content/zh-cn/docs/reference/glossary/affinity.md
content/zh-cn/docs/reference/glossary/aggregation-layer.md
content/zh-cn/docs/reference/glossary/annotation.md
```
> [zh] Update reference\glossary (1)

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Fixes #36202
Updated page [Extend the Kubernetes API with CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)
> Fixing hyperlink on Extend the Kubernetes API with CustomResourceDefinitions Page

- content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
Typo in this [`documentation`](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-strategic-merge-patch-to-update-a-deployment-using-the-retainkeys-strategy)
the command 
```go
kubectl patch deployment retainkeys-demo --type merge --patch-file patch-file-retainkeys.yaml
```
should be 
```go
kubectl patch deployment retainkeys-demo --type strategic --patch-file patch-file-retainkeys.yaml
```
> Typo fixed in documentation for Use strategic merge

- content/zh-cn/docs/concepts/services-networking/network-policies.md
Updated by the en upstream.
```
```
Preview: https://deploy-preview-36255--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/network-policies/
> [zh-cn] sync1.25 network-policies.md

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/zh-cn/docs/tutorials/services/source-ip.md
- content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md
Sync 1.25 `k8s.gcr.io` to `registry.k8s.io`
```yaml
```
```yaml
content/zh-cn/docs/tutorials/services/source-ip.md
```
```yaml
```
> [zh-cn]Sync 1.25 k8s.gcr.io to registry.k8s.io

- content/en/blog/_posts/2022-08-25-pod-security/index.md
Blog post for v1.25 Pod Security Admission (PSA) graduating to Stable
Topics:
- Reference 1.23 blog post (not much has changed): https://kubernetes.io/blog/2021/12/09/pod-security-admission-beta/
- PSP deletion
- Highlight PSP migration guide & tooling
- Highlight Pod OS changes (and talk about profile versioning)
/cc @katcosgrove
> Blog post about Pod Security admission graduating to stable

- content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md
The documentation for the `scoringStrategy` field when performing bin-packing in the scheduler refers to a `requestedToCapacityRatioParam` parameter. This is in fact the *type* of the field, as referenced in the [`ScoringStrategy`](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta3/#kubescheduler-config-k8s-io-v1beta3-ScoringStrategy) documentation; the field name is actually just `requestedToCapacityRatio`.
I discovered this while trying to add scheduler profiles on my microk8s cluster - `kube-scheduler` was failing to parse the YAML with `requestedToCapacityRatioParam`.
> Fix field in ScoringStrategy for scheduler resource bin-packing

- content/zh-cn/docs/reference/issues-security/official-cve-feed.md
Added the zh-cn text to:
```
content/zh-cn/docs/reference/issues-security/official-cve-feed.md
```
Preview: https://deploy-preview-36259--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/issues-security/official-cve-feed/
> [zh-cn] Localize 1.25 issues-security/official-cve-feed.md

- content/en/blog/_posts/2022-09-12-Announcing-the-Auto-Refreshing-Official-CVE-Feed/index.md
KEP: https://github.com/kubernetes/enhancements/issues/3203
Tracker: https://github.com/kubernetes/sig-security/issues/1
Preview: https://deploy-preview-35608--kubernetes-io-main-staging.netlify.app/blog/2022/09/12/k8s-cve-feed-alpha/
/hold for https://github.com/kubernetes/contributor-site/pull/330
/sig security docs testing k8s-infra
/milestone v1.25
/area security blog
> Announce (auto-refreshing) Official CVE Feed alpha

- content/en/blog/_posts/2022-08-23-kubernetes-1.25-blog.md
I believe it is the v1.25 release cycle and not the 1.24th
> Fix release cycle version on 2022-08-23-kubernetes-1.25-blog.md

- content/en/blog/_posts/2022-08-23-kubernetes-1.25-blog.md
Updating the release blog to include that kube-proxy images are now based in distroless, as the changelog is also being updated.
> Updates Major Themes to include kube-proxy change

- content/en/docs/reference/node/kubelet-checkpoint-api.md
Fixes https://github.com/kubernetes/website/issues/36296
Preview page: https://deploy-preview-36303--kubernetes-io-main-staging.netlify.app/docs/reference/node/kubelet-checkpoint-api/
> Fix Kubelet authentication/authorization reference link in kubelet-checkpoint-api page

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
This PR reformats the CRD task file where line wrappings are expected or proper indentations are needed. It also fixes the syntax code for some code snippets, especially those that look like YAML but are actually not YAML.
Those snippets are some YAML plus some dots. They cannot be used in place of a valid YAML file. We don't need to syntax highlight them as YAML. Just rendering them as plain code would suffice.
> Style tweak the crd task file

- content/en/docs/concepts/services-networking/connect-applications-service.md
Updates command in the "Connecting Applications with Services" page to only show the `my-nginx` podIp
Fixes #34389
> Update command in "Connecting Applications with Services" and separate out a command

- Makefile
Changes to the `Makefile`:
- Adds `--cleanDestinationDir` to all `hugo` build commands
- ~Defines a default value for `DEPLOY_PRIME_URL`, when unset~
Both of these changes are in support of local development.
/cc @nate-double-u @sftim
> Makefile: add --cleanDestinationDir flag to hugo cmd invocations

- content/pt-br/docs/concepts/cluster-administration/flow-control.md
- content/pt-br/examples/priority-and-fairness/health-for-strangers.yaml
- Brazilian portuguese translation for the [Flow Control](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/). page
> adding pt-br translate for flow-control page

- content/en/docs/reference/issues-security/official-cve-feed.md
Without the `-L` flag `curl` will only report there's a redirect. `L` will follow redirects all the way to the destination.
> Fix bug in curl command to fetch official CVE feed

- content/zh-cn/docs/concepts/workloads/pods/disruptions.md
> [zh-cn] sync1.25 disruptions.md

- content/zh-cn/docs/reference/kubernetes-api/common-definitions/quantity.md
- Remove redundant info
- Add changes from 1.25
- Localize punctuations `中文句点落在（括号）后。`
```
content/zh-cn/docs/reference/kubernetes-api/common-definitions/quantity.md
```
Preview: https://deploy-preview-36331--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/common-definitions/quantity/
> [zh] Sync1.25 /kubernetes-api/common-definitions/quantity.md

- layouts/partials/head.html
- Contributes to #35299
- ~This PR assumes that release-doc subdomains are handled from the same Netlify account. @onlydole, might you be able to confirm that?~ Edit: I've "hard-coded" the GA4 ID.
/cc @nate-double-u
> Google analytics: use GA4 site tag for v1.24

- content/zh-cn/includes/user-guide-content-moved.md
This PR converts the EOL style from DOS to UNIX.
> [zh] Fix EOL style for user guide content moved page

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
Added text for .125.
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
```
Preview: https://deploy-preview-36332--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1/
> [zh] Sync1.25 /config-and-storage-resources/csi-driver-v1.md

- content/zh-cn/releases/_index.md
- content/zh-cn/releases/release-managers.md
- content/zh-cn/releases/release.md
- content/zh-cn/search.md
Update this page to upstream and fix 404 link
list below:
```
1. content/zh-cn/releases/_index.md
2. content/zh-cn/releases/release-managers.md
3. content/zh-cn/releases/release.md
4. content/zh-cn/search.md
```
1. Update out-of-sync content in English
2. Improve the description.
3. Add the anchor for link.
4. Fix 404 links for `Pruning`
5. Fix fail render in `handbooks page`
> [zh] Update releases page and fix the 404 link

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs.md
This PR converts the kubeadm_certs reference page to UNIX EOL style.
> [zh] Convert kubeadm_certs from DOS to UNIX format

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_generate-csr.md
This PR converts the EOL style from DOS to UNIX.
> [zh] Convert kubeadm-certs-gen page to UNIX format

- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Sync the upstream:
```yaml
```
> [zh-cn] Sync 1.25/configure-liveness-readiness-startup-probes.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/cluster-cidr-v1alpha1.md
Newly added the zh-cn text to:
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/cluster-cidr-v1alpha1.md
```
Preview: https://deploy-preview-36282--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/cluster-cidr-v1alpha1/
> [zh-cn] sync1.25 cluster-cidr-v1alpha1.md

- content/vi/docs/concepts/containers/container-environment-variables.md
The documentation contains lot of dead links in the VI language.
I have noticed that the `{{< param "githubbranch" >}}` was in other portions of the doc, and seems outdated.
I have replaced every occurrence with "master".
> Fix broken link in vi

- content/en/blog/_posts/2022-08-04-cgroupv2-ga.md
- content/en/blog/_posts/2022-08-31-cgroupv2-ga.md
Add blog post for cgroupv2 1.25 GA 
Enhancement issue: https://github.com/kubernetes/enhancements/issues/2254
See the PR for the cgroup v2 docs here - https://github.com/kubernetes/website/pull/35180
Signed-off-by: David Porter <david@porter.me>
> CGroupV2 1.25 GA blog post

- content/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
The English sentence
```
A Kubernetes cluster (...) should have a minimum of three nodes because (...) and redundancy is compromised.
```
was ungramatically translated which misses the point.
> fix translation to make it grammatically correct

- content/en/docs/reference/glossary/cni.md
The reason for the update is as follows:
1. Remove redundant description:
The two links are the same, and the descriptions are similar, I think readers will be confused by this.
```
* For information on Kubernetes and CNI refer to [this](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni).
* For information on Kubernetes and CNI, see ["Network plugins"](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni).
```
2. Fix the title and the anchor:
In the title and anchor of the link, it does not match the original
* original title: Network Plugins
* original anchor : There is no anchor for this XXX
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
> Remove redundant description in glossary/cni

- CONTRIBUTING.md
Fixes https://github.com/kubernetes/website/issues/36288
Updated page [Contributing to Kubernetes Documentation](https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md) of kubernetes / website github repository page
Previous PR #36289
> Fixing link on Contributing to Kubernetes Documentation in kubernetes / website github repository page

- content/zh-cn/docs/reference/node/kubelet-checkpoint-api.md
Newly added the zh-cn text to:
```
content/zh-cn/docs/reference/node/kubelet-checkpoint-api.md
```
Preview: https://deploy-preview-36279--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/node/kubelet-checkpoint-api/
> [zh-cn] sync1.25 kubelet-checkpoint-api.md

- content/zh-cn/docs/tutorials/hello-minikube.md
- Updated text from 1.25
- Modified the UI text that shall be English, kept 'as is', and un-localized
- Add anchors
```
content/zh-cn/docs/tutorials/hello-minikube.md
```
Preview: https://deploy-preview-36387--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/hello-minikube/
> [zh] Sync1.25 /tutorials/hello-minikube.md

- content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
> [zh] sync admission-controllers.md

- content/en/examples/admin/konnectivity/konnectivity-server.yaml
Closes #36420.
Starting from Kubernetes 1.25, the new repository `registry.k8s.io` has been introduced, and new versions of the Konnectivity addon have been released.
I just double-checked the parameters for Konnectivity and they are correct, as well as the existence of the container image.
> Updating konnectivity container image registry and tag

- content/zh-cn/docs/reference/node/kubelet-checkpoint-api.md
Sync upstream change,this is a small change
`/zh-cn/docs/reference/command-line-tools-reference/kubelet-authentication-authorization)` to `/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz)`
```yaml
content/zh-cn/docs/reference/node/kubelet-checkpoint-api.md
```
> [zh-cn]fix a old link in kubelet-checkpoint-api.md

- content/zh-cn/examples/admin/cloud/ccm-example.yaml
- content/zh-cn/examples/admin/dns/dns-horizontal-autoscaler.yaml
- content/zh-cn/examples/admin/dns/dnsutils.yaml
- content/zh-cn/examples/admin/konnectivity/konnectivity-server.yaml
- content/zh-cn/examples/admin/logging/two-files-counter-pod-agent-sidecar.yaml
Mainly replace `k8s.gcr.io` with `registry.k8s.io` in the /admin folder:
```
content/zh-cn/examples/admin/cloud/ccm-example.yaml
content/zh-cn/examples/admin/dns/dns-horizontal-autoscaler.yaml
content/zh-cn/examples/admin/dns/dnsutils.yaml
content/zh-cn/examples/admin/konnectivity/konnectivity-server.yaml
content/zh-cn/examples/admin/logging/two-files-counter-pod-agent-sidecar.yaml
```
> [zh] updated 5 YAML examples

- content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
[The original English text](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/controllers/replicaset.md) says
> This feature is beta and enabled by default. You can disable it using the [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) PodDeletionCost in both kube-apiserver and kube-controller-manager.
The original translation about `enable` and `disable` is inversed and this PR fixed this typo.
> [zh-cn] Improve workloads/controllers/replicaset.md

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
We now bump the used CNI plugins version to v1.1.1 and cri-tools to v1.25.0. I also reworked the scripts to be more consistent when it comes to using double quotes.
Refers to https://github.com/kubernetes/release/pull/2647 and https://github.com/kubernetes/release/pull/2650
A bit to https://github.com/kubernetes/website/issues/35921
> Update CNI plugins and cri-tools for kubeadm docs

- data/i18n/en/en.toml
- layouts/shortcodes/release-data.html
Partially fixes https://github.com/kubernetes/website/issues/35932.
Notes:
- This PR,  #36375, relates to @Sea-n 's PR: https://github.com/kubernetes/website/pull/35950, but is not git based on it.
- This PR,  #36375, supersedes my previous PR, https://github.com/kubernetes/website/pull/36359, which I closed because it was based on `zh-cn` (via Sea-n's on https://github.com/kubernetes/website/pull/35950). 
- To merge with `main`, this branch/PR must be based on `main`.
> Fix release-data i18n

- content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md
fixed: #36476
Translate Chinese version for kube-scheduler-config.v1.md
Preview: https://deploy-preview-36490--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/kube-scheduler-config.v1/
> [zh-cn] Add kube-scheduler-config.v1.md chinese version

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
- remove extra line when two consecutive blank lines exist
- change some links to `/zh-cn`
- a para about 1.25
- update `daemon set` based on [/concepts/workloads/controllers/daemonset/](https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/daemonset/)
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
```
Preview: https://deploy-preview-36496--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/
> [zh] Sync1.25 /kubernetes-api/workload-resources/daemon-set-v1.md

- content/en/docs/concepts/security/security-checklist.md
Addresses issue [Create a security checklist for deploying a cluster #28](https://github.com/kubernetes/sig-security/issues/28) in k/sig-security repository. [[preview](https://deploy-preview-33992--kubernetes-io-main-staging.netlify.app/docs/concepts/security/security-checklist/)]
Draft for the security checklist guide from the collaborative document with @savitharaghunathan, @Skybound1, and @p4ck3t0. Many people participated in this list via this PR, thanks everyone ☺️!
This is a document in the form of a checklist with paragraphs that further describe some items. The goal is to centralize many security concerns and form a central place to redirect to other documentation or guide.
This checklist is meant to evolve in the future, as the participation on the PR proved, people provided …
> Add a security checklist for clusters

- content/zh-cn/docs/reference/glossary/code-contributor.md
- content/zh-cn/docs/reference/glossary/configmap.md
- content/zh-cn/docs/reference/glossary/container-env-variables.md
- content/zh-cn/docs/reference/glossary/container-lifecycle-hooks.md
Update about reference/glossary,this chapter is often used, so make adjustments,and ensure all these files were still in sync with English upstream now.
the following
```
content/zh-cn/docs/reference/glossary/code-contributor.md
content/zh-cn/docs/reference/glossary/configmap.md
content/zh-cn/docs/reference/glossary/container-env-variables.md
content/zh-cn/docs/reference/glossary/container-lifecycle-hooks.md
```
> [zh] Update reference\glossary (6)

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Fixed links from [Traces for Kubernetes System Components](/docs/concepts/cluster-administration/traces-for-kubernetes-system-components) to `/docs/concepts/cluster-administration/system-traces`
```
content/en/docs/reference/command-line-tools-reference/feature-gates.md
```
Preview: https://deploy-preview-36315--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/
Fixes #36280
> Fixed links in feature-gates.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
- Updated para from 1.25
- Removed a blank line when two consecutive blank lines exist
- Fixed other minor errors
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
```
Preview: https://deploy-preview-36497--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1/
> [zh] Sync1.25 /kubernetes-api/workload-resources/cron-job-v1.md

- content/en/docs/concepts/overview/working-with-objects/common-labels.md
- content/en/docs/reference/labels-annotations-taints/_index.md
**Why this change?**
This changes removes the `created-by` annotation given that it has been deprecated since 1.9, see [Kubernetes PR# 54445](https://github.com/kubernetes/kubernetes/pull/54445).
This deprecation was announced in the following release notes:
- [Change log Kubernetes 1.8 - Deprecations](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.8.md#deprecations)
- [Change log Kubernetes 1.8 - Other notable changes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.9.md#other-notable-changes-14)
> Removing created-by label deprecated since 1.9

- content/en/docs/concepts/storage/volume-snapshots.md
Add a note on the pre-provisioned snapshot scenario
I found it confusing when filling a non-existing
volumeSnapshotRef when creating a VolumeSnapshotContent
in the pre-provisioned mode. I hope this note can clear
up some confusion.
Signed-off-by: John Lin <johnlinp@gmail.com>
> Add a note on the pre-provisioned snapshot scenario

- content/en/docs/concepts/security/api-server-bypass-risks.md
This is a new documentation page for the Security Concepts section, looking at the risks of attackers bypassing the Kubernetes API server.
We've been working on this in Kubernetes SIG-Security docs (issue [here](https://github.com/kubernetes/sig-security/issues/42))
cc @savitharaghunathan @sftim
> New Docs page for API Server Bypass Risks

- content/en/docs/concepts/architecture/cgroups.md
The spelling of the management i.e mangement is wrong, now it has been corrected.
Fixes: #36528
> Fix typo on cgroups page

- content/en/docs/concepts/security/api-server-bypass-risks.md
First I would like to congratulate raesene on merging the API Server Bypass Risks page! 🎉
Just made this nits PR to bring my suggestion for fixing some minor typos to reflect this comment https://github.com/kubernetes/website/pull/35908#pullrequestreview-1094865675 where I wrote:
> I really love this addition to the security doc, especially the static pod and kubelet thing that are as not as widely known as the rest. They were a bit in a "secret knowledge" state at the moment, only discussed in some issues or talks!
> 
> Thanks, @raesene for the work, this is well organized and pleasant to read! I would love to add a reference to it from the security checklist!
> Fix some mini typos in the API bypass security page

- content/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
path：
```
content/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
```
> [zh] sync optional-kubectl-configs-bash-linux.m

- content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Clear difference from `./scripts/lsync.sh`:
```
```
Preview: https://deploy-preview-36419--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
> [zh] Updated /custom-resources/custom-resource-definitions.md

- static/_redirects
The back-and-forth refactoring for Windows contents has left some bad
entries in the redirection records where A is redirected to B and B is
redirected to C. We want A to be redirected to C rather than forcing the
browser to fetch these redirections twice.
> Optimize some redirection entries

- content/en/blog/_posts/2020-05-27-An-Introduction-to-the-K8s-Infrastructure-Working-Group.md
This PR reverts part of PR [36270](https://github.com/kubernetes/website/pull/36270) that updated a blog from 2020 and adds a note to the blog that the container registry is updated
> Revert blog update in PR 36270 and add note about updated container registry

- content/zh-cn/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md
Chage `github.com/kubernetes` to `git.k8s.io`
Preview:
https://deploy-preview-36583--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-cluster/resource-metrics-pipeline
```yaml
content/zh-cn/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md
```
> [zh-cn]Fix layout of resource-metrics-pipeline.md

- content/zh-cn/docs/reference/glossary/cri.md
- content/zh-cn/docs/reference/glossary/cronjob.md
- content/zh-cn/docs/reference/glossary/csi.md
- content/zh-cn/docs/reference/glossary/customresourcedefinition.md
Update about reference/glossary,this chapter is often used, so make adjustments,and ensure all these files were still in sync with English upstream now.
the following
```
content/zh-cn/docs/reference/glossary/cri.md
content/zh-cn/docs/reference/glossary/cronjob.md
content/zh-cn/docs/reference/glossary/csi.md
content/zh-cn/docs/reference/glossary/customresourcedefinition.md
```
> [zh] Update reference\glossary (9)

- content/id/includes/task-tutorial-prereqs.md
Fix the Katacoda link by #34428 
Original page: [Task Tutorial Prerequisites](https://github.com/kubernetes/website/blob/main/content/id/includes/task-tutorial-prereqs.md)
> The en PR #34429  is merged.
> [id] fix link about katacoda

- content/en/blog/_posts/2022-09-07-iptables-chains.md
As part of [KEP-3178](https://github.com/kubernetes/enhancements/issues/3178) we want to do a blog post to warn authors of third-party components about the upcoming changes, so any affected components have plenty of time to adjust (if needed).
> Add blog post about KEP-3178 iptables cleanup

- content/en/blog/_posts/2022-09-14-pod-has-network-condition.md
Blog post for PodHasNetwork condition feature [https://github.com/kubernetes/enhancements/issues/3085]
Supersedes https://github.com/kubernetes/website/pull/35645
> Add blog post for PodHasNetwork condition

- content/en/docs/concepts/services-networking/service.md
The service documentation was missing a 'how' in one of its sentences. Added.
> Update service.md to include a missing word

- content/zh-cn/docs/reference/glossary/downstream.md
- content/zh-cn/docs/reference/glossary/downward-api.md
- content/zh-cn/docs/reference/glossary/dynamic-volume-provisioning.md
- content/zh-cn/docs/reference/glossary/endpoint-slice.md
- content/zh-cn/docs/reference/glossary/endpoint.md
- content/zh-cn/docs/reference/glossary/ephemeral-container.md
Update about reference/glossary,this chapter is often used, so make adjustments,and ensure all these files were still in sync with English upstream now.
the following
```
content/zh-cn/docs/reference/glossary/downstream.md
content/zh-cn/docs/reference/glossary/downward-api.md
content/zh-cn/docs/reference/glossary/dynamic-volume-provisioning.md
content/zh-cn/docs/reference/glossary/endpoint-slice.md
content/zh-cn/docs/reference/glossary/endpoint.md
content/zh-cn/docs/reference/glossary/ephemeral-container.md
```
> [zh] Update reference\glossary (12)

- content/en/docs/concepts/storage/persistent-volumes.md
- changed the feature state shortcode from `beta` to `stable` since the feature as stable for v1.24
- **page updated** :- https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims
> Fix incorrect feature state for PVC expansion

- content/en/docs/reference/access-authn-authz/admission-controllers.md
Fix note typo from `{{ note }}` to `{{< note >}}`
Updated page: 
- https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#request-payloads
> fix note typo

- content/en/docs/tasks/job/pod-failure-policy.md
Mainly fix the text layout under the ordered list 1-2-3-4-5 by giving 3 spaces.
```
content/en/docs/tasks/job/pod-failure-policy.md
```
Preview: https://deploy-preview-36620--kubernetes-io-main-staging.netlify.app/docs/tasks/job/pod-failure-policy/
> Fix layout of pod-failure-policy.md

- content/en/blog/_posts/2022-09-21-csi-nodeexpandsecret.md
Ref# KEP: https://github.com/kubernetes/enhancements/pull/3173/
Implementation: https://github.com/kubernetes/kubernetes/pull/105963
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>
> Add blog article to announce Secret references in NodeExpandVolume

- content/en/docs/concepts/configuration/manage-resources-containers.md
https://github.com/kubernetes/kubernetes/issues/111965 brings up a concern about ephemeral storage calculations. I took the concern to Sig-Node and the collective thought is that mounting disks to /var/lib/kubelet and /var/lib/containers is not necessarily supported, and definitely not supported with ephemeral storage calculations.
This PR adds a blurb that ephemeral storage is not reported correctly in this instance.
> add new note for ephemeral storage calculations

- content/en/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md
Updates to https://kubernetes.io/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes/
- Add the new reference link.
- Kubernetes blog: [Dockershim Removal FAQ]
- The title of the hyperlink is consistent with the title of the original article.
- Kubernetes blog: [Updated: Dockershim Removal FAQ]
- Kubernetes documentation: [Container Runtimes]
- Amazon Web Services EKS documentation: [Amazon EKS is ending support for Dockershim]
- Add the published date
- Tripwire: [How Dockershim’s Forthcoming Deprecation Affects Your Kubernetes]
- Add the GitHub issue number
- You can provide feedback via the GitHub issue [**Dockershim removal feedback & issues**]
author:
/cc @rolfedh
/cc @sftim
> Update  dockershim removal article list

- content/en/docs/concepts/security/rbac-good-practices.md
Add an explanation that workload creation permissions effectively grant impersonation permissions on service accounts in that namespace, along with a recommendation to avoid subdividing access within a namespace. Also remove PSP reference.
/sig auth security
> Update RBAC best practices for workload creation

- content/en/docs/concepts/workloads/controllers/deployment.md
The RS name is always derived from the hash of the pod template and
it's not random.
> Fix note about ReplicaSet names

- content/en/docs/reference/access-authn-authz/rbac.md
Fixes #28580
Adds some content about how wildcards (and other ways to include "everything" or "anything") work in Roles/ClusterRoles.
Includes a caution as this could be a dangerous approach.
> Mention wildcard for RBAC resources and names

- content/en/docs/concepts/configuration/manage-resources-containers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
PR is reverting : https://github.com/kubernetes/website/pull/35653/
This feature has been reverted to alpha in master and 1.25.
Related-to: https://github.com/kubernetes/kubernetes/pull/112076
Related-to: https://github.com/kubernetes/kubernetes/pull/112078
Related-to: https://github.com/kubernetes/enhancements/issues/1029
> Revert: promote LocalStorageCapacityIsolationFSQuotaMonitoring to beta

- content/en/docs/concepts/services-networking/service.md
Within the Service concept, avoid writing “master”. Use “primary” instead. [[preview](https://deploy-preview-36668--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/#environment-variables)]
> Redo naming in Service concept

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/concepts/workloads/pods/disruptions.md
- content/en/docs/tasks/job/pod-failure-policy.md
Fix typo by replacing PodDisruptionsCondition -> PodDisruptionConditions.
> Fix typo in docs referring to the PodDisruptionConditions feature gate

- content/zh-cn/docs/concepts/services-networking/dns-pod-service.md
- content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
- content/zh-cn/docs/tasks/network/validate-dual-stack.md
Sync PR: https://github.com/kubernetes/website/pull/36683
```
content/zh-cn/docs/tasks/network/validate-dual-stack.md
```
> [zh-cn] Sync use IPv6 Address Prefix Reserved for Documentation

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md
- sync with en upstream #36401 
- change `约束值` and `约束` to `限制` by following [glossary](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7)
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md
```
Preview: https://deploy-preview-36679--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/configuration/manage-resources-containers/
> [zh] Resync manage-resources-containers.md and feature-gates.md

- content/en/docs/tasks/inject-data-application/define-command-argument-container.md
- content/en/docs/tasks/inject-data-application/define-environment-variable-container.md
- content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md
- content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
Excess space was removed:
```yaml
content/en/docs/tasks/inject-data-application/define-command-argument-container.md
```
```yaml
content/en/docs/tasks/inject-data-application/define-environment-variable-container.md
```
```yaml
content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md
```
```yaml
content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
```
> [en]fix some layout of /docs/tasks/inject-data-application

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/node/kubelet-checkpoint-api.md
Fixes https://github.com/kubernetes/website/issues/36705
The feature gate name is `ContainerCheckpoint ` according to https://github.com/kubernetes/kubernetes/pull/104907
https://github.com/kubernetes/kubernetes/blob/d569886a234cb65cb1ec777b7ab2e5b9a35d7145/pkg/features/kube_features.go#L189-L194
**BTW**
[reorder feature gates for alphabet order](https://github.com/kubernetes/website/pull/36699/commits/f6cdf2fa48d9c29b186759dbbc21ca8950d8afc2)
The order is wrong for some feature gates and I find a dup and removed it.
> correct CheckpointContainer to ContainerCheckpoint

- content/zh-cn/docs/tasks/extend-kubernetes/socks5-proxy-access-api.md
Sync upstream of change `https://localhost/api` to `https://localhost:6443/api`
```yaml
content/zh-cn/docs/tasks/extend-kubernetes/socks5-proxy-access-api.md
```
> [zh-cn]Sync socks5-proxy-access-api.md

- content/zh-cn/docs/reference/glossary/finalizer.md
- content/zh-cn/docs/reference/glossary/flexvolume.md
- content/zh-cn/docs/reference/glossary/garbage-collection.md
- content/zh-cn/docs/reference/glossary/helm-chart.md
- content/zh-cn/docs/reference/glossary/horizontal-pod-autoscaler.md
Update about reference/glossary,this chapter is often used, so make adjustments,and ensure all these files were still in sync with English upstream now.
the following
```
content/zh-cn/docs/reference/glossary/finalizer.md
content/zh-cn/docs/reference/glossary/flexvolume.md
content/zh-cn/docs/reference/glossary/garbage-collection.md
content/zh-cn/docs/reference/glossary/helm-chart.md
content/zh-cn/docs/reference/glossary/horizontal-pod-autoscaler.md
```
> [zh] Update reference\glossary (14)

- content/en/docs/concepts/services-networking/connect-applications-service.md
- content/en/docs/reference/access-authn-authz/authentication.md
- content/en/docs/tasks/configure-pod-container/configure-service-account.md
* Make example service account output match 1.24+ output with auto-generated tokens omitted
* Prefer `kubectl create token` as token creation mechanism
/sig auth
> Update service account token documentation

- content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md
- Sync with en upstream #36660
- Replace `帐户` and  `账户` with `账号` by following [glossary](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7)
```
content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md
```
Preview: https://deploy-preview-36747--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-service-account/
> [zh] Resync configure-service-account.md

- content/zh-cn/docs/concepts/workloads/controllers/job.md
- content/zh-cn/examples/controllers/job-pod-failure-policy-example.yaml
Updated text.
```
```
```
content/zh-cn/examples/controllers/job-pod-failure-policy-example.yaml
```
```
content/zh-cn/examples/controllers/job-pod-failure-policy-failjob.yaml
```
```
content/zh-cn/examples/controllers/job-pod-failure-policy-ignore.yaml
```
> [zh-cn] sync1.25 job.md

- content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md
My team just ran into an ordering bug with dependent environment variables.
The original [docs PR](https://github.com/kubernetes/website/pull/21811) demonstrated the bug exactly, but I wasn't immediately able to tell from the example's description that ordering was the source of the bug.
Hopefully this language will help folks quickly understand that order is significant for dependent environment variables.
> clarify that order matters in dependent environment variables

- OWNERS_ALIASES
* I commented out instead of remove because they are 'pausing' but a long time has passed
* @inductor and I were in both owner and reviewer because there were a few members but we have enough members for now (actually I recently haven't made `/lgtm` comments)
> Remove docs-ja owners from reviews and remove commented reviewers

- content/zh-cn/docs/reference/access-authn-authz/authentication.md
Sync with the en upstream #36660 
```
```
Preview: https://deploy-preview-36740--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/authentication/
> [zh] Resync /access-authn-authz/authentication.md

- content/en/blog/_posts/2022-09-12-Announcing-the-Auto-Refreshing-Official-CVE-Feed/index.md
After https://github.com/kubernetes/website/pull/35608 merged, I made commit 3403ffa7b5545958ea745fde546c67fe0a3be41c to omit a link that wouldn't be live when @PushkarJ's blog article publishes.
The link won't work until we manually unhold https://github.com/kubernetes/contributor-site/pull/330 
Once the related implementation details article is published, we can reinstate the paragraph that hyperlinks to that article. This commit does that.
/area blog
/language en
/hold
until https://github.com/kubernetes/contributor-site/pull/330 is merged
> Reinstate implementation details for CVE feed announcement

- content/ko/docs/tasks/administer-cluster/limit-storage-consumption.md
> [ko]Translate docs/tasks/administer-cluster/limit-storage-consumption into Korean

- content/ko/docs/tasks/extend-kubernetes/socks5-proxy-access-api.md
issues: https://github.com/kubernetes/website/issues/35437
위 이슈를 진행하였습니다.
> [ko] Translate /docs/tasks/extend-kubernetes/socks5-proxy-access-api into Korean

- content/en/docs/reference/labels-annotations-taints/_index.md
Fixes #35821
/language en
/kind bug
/sig autoscaling
> Register and document cluster-autoscaler `safe-to-evict` annotation

- OWNERS_ALIASES
As part of the assorted admin needed for the Localization subproject, I'm adding an alias that includes all SIG Docs chairs and tech leads, alongside subproject owners @bradtopol and @a-mccarthy.
This completes the final TODO in our [tracked issue](https://github.com/kubernetes/website/issues/31955).
Abbie has already created [the corresponding PR](https://github.com/kubernetes/community/pull/6769
) to update our community docs.
Alongside these changes, I've also cleaned up the website approvers list, as per [this Slack update](https://kubernetes.slack.com/archives/C1J0BPD2M/p1648568995444079?thread_ts=1648568436.074959&cid=C1J0BPD2M). @reylejano was missing from our English PR reviewers alias, so he has been added.
> Adding localization alias, cleaning up approvers

- content/ko/docs/contribute/localization_ko.md
from #36622 
---
As suggested in the issue, I added words that are not in the Korean localization glossary from the recently contributed documents.
이슈에서 제안주신대로 최근 기여된 문서들에서 한글화 용어집에 없는 단어들도 함께 추가하였습니다.
> [ko] add words to Korean localization glossary

- content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
kube-proxy is part of the Kubernetes node components not control plane. I think it's a typo.
ref: https://kubernetes.io/docs/concepts/overview/components/#node-components
>  kube-proxy is part of the Kubernetes node components

- content/en/docs/concepts/workloads/controllers/daemonset.md
- content/en/docs/concepts/workloads/controllers/replicationcontroller.md
- content/en/docs/concepts/workloads/pods/_index.md
- content/en/docs/concepts/workloads/pods/init-containers.md
- content/en/examples/controllers/daemonset.yaml
**Issue being addressed** - Fixes #30965
- Removed the usage of "docker" in [daemonsets](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#init-scripts). The code sample was tested on contianerd runtime
- Updated the phrasing used in [replicationcontroller](https://k8s.io/docs/concepts/workloads/controllers/replicationcontroller) and removed the usage of "or Docker"
- Removed usage of "docker" in [pods](https://k8s.io/docs/concepts/workloads/pods/)
- The output for [init-containers](https://k8s.io/docs/concepts/workloads/pods/init-containers) was captured when using containerd runtime.
> Removed usage of docker from replicationControllers, containers, pods and daemonsets

- content/en/blog/_posts/2022-07-27-sig-apps-GA-1.25/index.md
- content/en/blog/_posts/2022-09-15-sig-apps-GA-1.25/index.md
sig-apps is excited to promote 2 features to GA this release:
- minReadySeconds for StatefulSets
- maxSurge for DS pods
This is a continuation of https://github.com/kubernetes/website/pull/35440 as I have agreed with @ravisantoshgudimetla that we should finish this soon.
> Add blog article about minReadySeconds for StatefulSets and maxSurge for DaemonSets

- content/en/docs/concepts/services-networking/topology-aware-hints.md
Ref: https://github.com/kubernetes/website/issues/36825
Fixed Incorrect feature state in Topology Aware hints documentation.
I'm currently unsure, maybe it will be better to completely remove this note or make `enabled` word not bold. Which style will be preferable in this case?
> fix: Fix incorrect feature state in Topology Aware hints page

- content/zh-cn/docs/concepts/workloads/controllers/replicationcontroller.md
- Sync with the en upstream
- Changes for consistency
- Add anchors
```
content/zh-cn/docs/concepts/workloads/controllers/replicationcontroller.md
```
Preview: https://deploy-preview-36847--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/replicationcontroller/
> [zh]Sync replicationcontroller.md

- content/zh-cn/docs/tasks/administer-cluster/declare-network-policy.md
In Chinese documents under [Declare Network Policy](https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/declare-network-policy/) and [Test the service by its function from another Pod](https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/declare-network-policy/#%E9%80%9A%E8%BF%87%E4%BB%8E-pod-%E8%AE%BF%E9%97%AE%E6%9C%8D%E5%8A%A1%E5%AF%B9%E5%85%B6%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95), there is an extra character 's'.
Signed-off-by: qi.han <qi.han@daocloud.io>
> [bugfix/fix-declare-network-policy-word] fix🐛:  Remove the extra char

- content/en/docs/tasks/administer-cluster/use-cascading-deletion.md
- content/zh-cn/docs/tasks/administer-cluster/use-cascading-deletion.md
From the source code and PR https://github.com/kubernetes/kubernetes/pull/93384 we can see that:
```
version < v1.20.x: the flag to orphan dependents is `--cascade=true`
version >= v1.20.x: the flag to orphan dependents is `--cascade=orphan`
```
But we should actually drop the tab for v1.20 and earlier - see https://kubernetes.io/docs/home/supported-doc-versions/
> Drop doc tab `prior to v1.20` about cascading deletion

- content/zh-cn/docs/reference/labels-annotations-taints/_index.md
Sync with #35846 and clear difference found by `./scripts/lsync.sh`
```
```
Preview: https://deploy-preview-36792--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/labels-annotations-taints/
> [zh]Sync labels-annotations-taints/_index.md

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
The feature gates was not well sync'ed with the upstream implementation.  This PR resynchronizes the tables based on cross-verification against upstream source code. It also fixes some nits such as a feature was not placed in the right table or the entries are not strictly sorted.
> Update feature gates page

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
This PR fixes broken link to CustomResourceDefinition on [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/) Page
Fixes #36715
> Fix Broken Link to CustomResourceDefinition

- data/releases/schedule.yaml
Fix for note in https://kubernetes.io/releases/patch-releases/
“Out-of-band” is correct here; use that.
/language en
> Fix spelling for patch release detail

- content/zh-cn/blog/_posts/2022-09-14-pod-has-network-condition.md
Sync with the en source #36710 
```
content/zh-cn/blog/_posts/2022-09-14-pod-has-network-condition.md
```
Preview: https://deploy-preview-36862--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/09/14/pod-has-network-condition/
> [zh]Sync blog: 2022-09-14-pod-has-network-condition.md

- content/en/docs/setup/production-environment/tools/kubespray.md
Update `production-environment/tools/kubespray.md` docs  based on the official documentation on kubespray.io
Sync Supported Linux Distributions with [Kubespray - Supported Linux Distributions](https://github.com/kubernetes-sigs/kubespray#supported-linux-distributions)
```
- **Flatcar Container Linux by Kinvolk**
- **Debian** Bullseye, Buster, Jessie, Stretch
- **Ubuntu** 16.04, 18.04, 20.04, 22.04
- **CentOS/RHEL** 7, 8, 9
- **Fedora** 35, 36
- **Fedora CoreOS**
- **openSUSE** Leap 15.x/Tumbleweed
- **Oracle Linux** 7, 8, 9
- **Alma Linux** 8, 9
- **Rocky Linux** 8, 9
- **Kylin Linux Advanced Server V10** 
- **Amazon Linux 2** 
```
> Updated Supported Linux Distributions in kubespray.md

- content/en/docs/tutorials/security/ns-level-pss.md
Was running through Namespace-level Pod Security Standards tutorial and noticed the error in the cluster clean up command: https://kubernetes.io/docs/tutorials/security/ns-level-pss/
> Fix cluster cleanup command

- content/en/docs/concepts/security/overview.md
Mainly provide a consistent look for the links, which are validated one by one and are effective currently.
```
content/en/docs/concepts/security/overview.md
```
Preview: https://deploy-preview-36562--kubernetes-io-main-staging.netlify.app/docs/concepts/security/overview/
> Fix typo and consistency: /security/overview.md

- content/en/blog/_posts/2022-09-19-local-storage-capacity-isolation-ga.md
blog for GA feature local storage capacity isolation
> Blog for local storage capacity isolation GA

- content/en/docs/reference/glossary/code-contributor.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #35642 
*What I did?*
Me and @mtardy did discussion on this issue. So I gone through all the possible aspects of this issue.
- basically this page  [developer.md](https://github.com/kubernetes/website/blob/3ca34b9a3be454055ba234f1d2ff7d55809b5040/content/en/docs/reference/glossary/developer.md) has issue but I have updated the [code-contributor.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/code-contributor.md).
*why I did this?* 
- Because when user click on `Code Contributor` then this page redirected to the [code-contributor.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/code-contributor.md) because it used term-id as `code-contributor`.
- But …
> code-contributor.md updated with full path

- content/en/docs/contribute/new-content/blogs-case-studies.md
- content/en/docs/contribute/new-content/new-features.md
- content/en/docs/contribute/review/for-approvers.md
The link anchor was [broken](https://kubernetes.io/docs/contribute/review/for-approvers/#commit-into-another-persons-pr), replaced with the [correct one](https://kubernetes.io/docs/contribute/review/for-approvers/#commit-into-another-person-s-pr).
For Prow command reference, add k/website parameter.
The permission of `/assign` and `/close` command is outdated.
> Update some contributor page

- content/en/blog/_posts/2022-07-27-crd-validation-rules-graduate-to-beta.md
- content/en/blog/_posts/2022-09-23-crd-validation-rules-graduate-to-beta.md
https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2876-crd-validation-expression-language#beta
Blog post will explain the core capabilities of the feature, touch on some of the properties of the CEL expression language that was introduced by this feawture, explain what has changed in beta, and also describe new ways that CEL may be used in Kubernetes in the future.
> Add CRD Validation Rules to Beta blog post

- content/en/blog/_posts/2022-09-19-local-storage-capacity-isolation-ga.md
Fix link in blog titled "Kubernetes 1.25: Local Storage Capacity Isolation Reaches GA"
/area blog
> Fix link in local storage capacity isolation blog

- content/en/docs/concepts/storage/volumes.md
The existing documentation for NFS volumes was missing an example for mounting NFS volumes directly in Pods. The linked example only shows how to mount NFS volumes via PersistentVolumes.
I've added a Pod-based example. 
I've also added a note about how you cannot specify mount options inside a Pod spec (like you can in a PersistentVolume) and listed some alternatives since there is no plan to support a new `mountOptions` setting in Pods: https://github.com/kubernetes/design-proposals-archive/blob/main/storage/mount-options.md#preventing-users-from-specifying-mount-options-in-inline-volume-specs-of-pod
Other relevant issues:
* https://github.com/kubernetes/kubernetes/issues/96284
* https://github.com/kubernetes/kubernetes/pull/107240
* https://github.com/kubernetes/kubernetes/issues/60729 …
> Add a Pod-based example for NFS volumes

- data/announcements/scheduled.yaml
Follow up to https://github.com/kubernetes/website/pull/36107
The CNCF has asked if we can show the KubeCon 2022 NA banner sooner than was initially set. Showing the banner for a few weeks ahead of KubeCon would help a lot with awareness and attendance.
/committee steering
/cc @reylejano @natalisucks @sftim @mrbobbytables @dims @liggitt @cblecker
> Setting Kubecon 2022 NA banner to show on 2022-09-23

- content/en/docs/concepts/policy/_index.md
Link from [Policies](https://kubernetes.io/docs/concepts/policy/) concept to [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) page. [[preview](https://deploy-preview-36670--kubernetes-io-main-staging.netlify.app/docs/concepts/policy/)]
> Link from Policies concept to NetworkPolicy page

- content/en/docs/concepts/cluster-administration/logging.md
Revise [Logging Architecture](https://kubernetes.io/docs/concepts/cluster-administration/logging/) [[preview](https://deploy-preview-33876--kubernetes-io-main-staging.netlify.app/docs/concepts/cluster-administration/logging/)]
- Drop mention of Docker
- Mention more about log rotation (there's room for even more)
/sig node
> Revise “Logging Architecture” topic

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
clarify topologyinfo registration logic in device plugins. The behavior how TopologyInfo
is interpreted was not well defined and lead to https://github.com/kubernetes/kubernetes/issues/112234.
https://github.com/kubernetes/kubernetes/pull/112387 proposes a fix and this PR is the 
corresponding documentation update.
Depends: https://github.com/kubernetes/kubernetes/pull/112387
> clarify topologyinfo registration logic in device plugins

- content/en/docs/setup/production-environment/_index.md
This PR updates the link to the etcd faq from 3.4 to 3.5 on the [Production Environment page](https://kubernetes.io/docs/setup/production-environment/)
Kubernetes 1.25 uses etcd 3.5.4
From https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md
> Etcd: Update to v3.5.4 (https://github.com/kubernetes/kubernetes/pull/110033, [@mk46](https://github.com/mk46)) [SIG API Machinery, Cloud Provider, Cluster Lifecycle and Testing]
> Update link to etcd faq to etcd 3.5 on setting up prod env page

- content/en/docs/setup/best-practices/enforcing-pod-security-standards.md
Fixes #36929 
Updated page [Enforcing Pod Security Standards](https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/)
> Fix broken link on Enforcing Pod Security Standards page

- content/en/docs/concepts/cluster-administration/networking.md
- content/en/docs/concepts/services-networking/_index.md
- content/en/docs/concepts/services-networking/connect-applications-service.md
- content/en/docs/concepts/services-networking/dns-pod-service.md
- content/en/docs/concepts/services-networking/dual-stack.md
- content/en/docs/concepts/services-networking/endpoint-slices.md
- content/en/docs/concepts/services-networking/ingress-controllers.md
- content/en/docs/concepts/services-networking/ingress.md
- content/en/docs/concepts/services-networking/network-policies.md
- content/en/docs/concepts/services-networking/service-traffic-policy.md
- content/en/docs/concepts/services-networking/service.md
- content/en/docs/concepts/services-networking/topology-aware-hints.md
- Add descriptions to pages
- Change page weights - the aim is to have the concepts flow in an order that makes better sense to the reader
> Reorganize “Services, Load Balancing, and Networking” concept

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/en/docs/tasks/tools/install-kubectl-linux.md
fixes https://github.com/kubernetes/website/issues/36111
microdnf is having issues with the repo gpgkey that was previously used
however the repogpgcheck was removed in
https://github.com/kubernetes/website/pull/34546 so the gpgkey for the
repo can be removed as well.
> remove unused repo gpgkey for yum repo

- content/zh-cn/docs/concepts/overview/components.md
Signed-off-by: Xieql <xieqianglong@huawei.com>
redundant image and text display appear on
`content/zh-cn/docs/concepts/overview/components.md`
Preview: https://kubernetes.io/zh-cn/docs/concepts/overview/components/
> [zh-cn]Fix redundant picture text display of components.md

- content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
Sync with the en version
```
content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
```
https://deploy-preview-36944--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller/
> [zh]Sync enforce-standards-admission-controller.md

- content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
There's documentation on the Dynamic Provisioning feature now, so we can remove the link to the 2016 blog (which is probably outdated)
> Update link to Dynamic Provisioning doc instead of blog

- content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
Fix some typos and layout:
```
content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
```
Preview: https://deploy-preview-36604--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/translate-compose-kubernetes/
> Fix typos and layout: translate-compose-kubernetes.md

- content/en/docs/concepts/extend-kubernetes/_index.md
- content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
- content/en/docs/concepts/extend-kubernetes/compute-storage-net/_index.md
- Rework [section index page](https://kubernetes.io/docs/concepts/extend-kubernetes/) [[preview](https://deploy-preview-34734--kubernetes-io-main-staging.netlify.app/docs/concepts/extend-kubernetes/)]
- Use more glossary tooltips
- Mention APIService more clearly
- Shift CRD note to the overview page for API extensions
- Also add text to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/  [[preview](https://deploy-preview-34734--kubernetes-io-main-staging.netlify.app/docs/concepts/extend-kubernetes/compute-storage-net/)]
> Update “Extend Kubernetes” concept overview

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
The syntax of the restore command at line 348 is problematic (doesn't work) or might have issues with a certain versions of Kubernetes (tried on version 1.23.0), doesn't work.
Also included export of the ECTDCTL_API=3 variable `export ECTDCTL_API=3`
> Update to etcdctl restore command syntax

- content/zh-cn/docs/concepts/cluster-administration/networking.md
- content/zh-cn/docs/concepts/services-networking/_index.md
- content/zh-cn/docs/concepts/services-networking/dns-pod-service.md
- content/zh-cn/docs/concepts/services-networking/dual-stack.md
- content/zh-cn/docs/concepts/services-networking/endpoint-slices.md
- content/zh-cn/docs/concepts/services-networking/ingress-controllers.md
- content/zh-cn/docs/concepts/services-networking/ingress.md
Sync with the en version #36671 
```
content/zh-cn/docs/concepts/cluster-administration/networking.md
content/zh-cn/docs/concepts/services-networking/_index.md
content/zh-cn/docs/concepts/services-networking/dual-stack.md
content/zh-cn/docs/concepts/services-networking/endpoint-slices.md
content/zh-cn/docs/concepts/services-networking/ingress-controllers.md
content/zh-cn/docs/concepts/services-networking/ingress.md
```
> [zh]sync networking.md and services-networking files

- content/en/docs/concepts/windows/intro.md
Add reference to HostProcess containers when describing lack of privileged containers support on Windows
> Add reference to HostProcess containers in windows documentation

- content/en/docs/setup/best-practices/enforcing-pod-security-standards.md
Fix the issue raised in this comment https://github.com/kubernetes/website/pull/36930#issuecomment-1253188956.
[Preview here](https://deploy-preview-36966--kubernetes-io-main-staging.netlify.app/docs/setup/best-practices/enforcing-pod-security-standards/)
> Bump pod security admission feature to stable in "Enforcing Pod Security Standards" page

- content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
The `kube-dns` option has been deprecated since 1.18 and no longer supported. The support to `kube-dns` has been removed from kubeadm since 1.21. This PR tweaks the DNS customization page to remove the outdated contents and also reformat the paragraphs where appropriate.
> Tweak DNS customization page

- content/zh-cn/docs/reference/glossary/dynamic-volume-provisioning.md
- content/zh-cn/docs/reference/glossary/endpoint-slice.md
- content/zh-cn/docs/reference/glossary/etcd.md
- content/zh-cn/docs/reference/glossary/event.md
- content/zh-cn/docs/reference/glossary/eviction.md
- content/zh-cn/docs/reference/glossary/extensions.md
Update about `reference/glossary`,this chapter is often used, so make adjustments,and ensure all these files were still in sync with English upstream now.
the following
```
content/zh-cn/docs/reference/glossary/dynamic-volume-provisioning.md
content/zh-cn/docs/reference/glossary/endpoint-slice.md
content/zh-cn/docs/reference/glossary/etcd.md
content/zh-cn/docs/reference/glossary/event.md
content/zh-cn/docs/reference/glossary/eviction.md
content/zh-cn/docs/reference/glossary/extensions.md
```
> [zh] Update reference\glossary (13)

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md
- Sync with the en version
- Change the term `job` from `作业` to `任务` by following [glossary job](https://kubernetes.io/zh-cn/docs/reference/glossary/?fundamental=true#term-job)
```
```
Preview: https://deploy-preview-37010--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1/
> [zh]sync /kubernetes-api/workload-resources/job-v1.md

- data/releases/schedule.yaml
This PR adds September's regular and out-of-band releases to the schedule.
/assign @cpanato @palnabarun @Verolop @puerco 
cc @kubernetes/release-engineering 
/hold
until the out-of-bound releases are not out
> releng: Add September's regular and out-of-band releases

- content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
Do not imply that node eviction can occur based on CPU. This isn't possible AFAIK.
> Remove misleading word from node eviction docs

- content/en/blog/_posts/2022-08-16-PSP-historical-context/index.md
Mark [PodSecurityPolicy: The Historical Context](https://kubernetes.io/blog/2022/08/23/podsecuritypolicy-the-historical-context/) as evergreen.
This means a stale content message doesn't show, ever. I think this article will be relevant for years to come.
Improvement for https://github.com/kubernetes/website/pull/36021
/language en
/area blog
> Mark “PodSecurityPolicy: The Historical Context” article as evergreen

- content/en/docs/tasks/configure-pod-container/user-namespaces.md
Translating user-namespaces.md into Korean,
I found an error.
` ``` `was missing, so I added it.
link : https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/
Signed-off-by: WESTZERO115 [psy7361c@gmail.com]
> Fix Markdown Error in user-namespaces.md

- content/en/docs/tasks/administer-cluster/certificates.md
The flag -sha256 is not set and hence the certs are SHA1 based and this is being disabled. Fixed the openssl command for server crt
> Document generating SHA256 CA certificate

- content/en/docs/concepts/configuration/secret.md
- content/en/docs/concepts/security/multi-tenancy.md
- content/en/docs/concepts/security/secrets-good-practices.md
- content/en/docs/reference/glossary/secret.md
Original PR for overhauled Secrets concept end state: #34168
This PR updates the glossary term for Secrets and adds a new page for Secrets good practices. 
This is part of a larger change to overhaul our Secrets docs. 
The scope of work is defined in [this Google doc](https://docs.google.com/document/d/1VQ8UFux1HifjXo9rRwm2-mOoUOzmMF7zGf-C0BhurdQ/edit#heading=h.nq4idzs84lru).
Preview: https://deploy-preview-34291--kubernetes-io-main-staging.netlify.app/docs/concepts/security/secrets-good-practices/
/sig docs
/language en
/cc @sftim
> Add good practices page for secrets

- content/zh-cn/docs/reference/glossary/secret.md
```
content/zh-cn/docs/reference/glossary/secret.md
```
> [zh] Sync /glossary/secret.md

- content/ko/docs/tasks/access-application-cluster/web-ui-dashboard.md
- content/ko/docs/tasks/administer-cluster/namespaces.md
- content/ko/docs/tasks/administer-cluster/sysctl-cluster.md
- content/ko/docs/tasks/configure-pod-container/static-pod.md
- content/ko/docs/tasks/debug/debug-application/debug-running-pod.md
- content/ko/docs/tasks/extend-kubernetes/setup-extension-api-server.md
- content/ko/docs/tasks/inject-data-application/define-command-argument-container.md
- content/ko/docs/tasks/inject-data-application/define-environment-variable-container.md
- content/ko/docs/tasks/inject-data-application/define-interdependent-environment-variables.md
- content/ko/docs/tasks/inject-data-application/distribute-credentials-secure.md
- content/ko/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
Related Issue : #36863 
74. [ ]  M74.  `content/en/docs/tasks/access-application-cluster/access-cluster.md`  | 2(+XS) 2(-)
75. [ ]  M75.  `content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md`  | 1(+XS) 1(-)
76. [ ]  M76.  `content/en/docs/tasks/administer-cluster/access-cluster-api.md`  | 1(+XS) 1(-)
77. [ ]  M77.  `content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md`  | 3(+XS) 3(-)
78. [ ]  M78.  `content/en/docs/tasks/administer-cluster/namespaces.md`  | 2(+XS) 2(-)
79. [ ]  M79.  `content/en/docs/tasks/administer-cluster/sysctl-cluster.md`  | 2(+XS) 55(-)
80. [ ]  M80.  `content/en/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md`  | 1(+XS) 1(-)
81. [ ]  M81. …
> [ko] Update outdate files in dev-1.25-ko.1 (M74-M89)

- content/en/docs/concepts/overview/kubernetes-api.md
- content/en/docs/reference/using-api/_index.md
- content/en/docs/reference/using-api/deprecation-policy.md
Update deprecation policy and API overview and guidelines for 
* https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/3136-beta-apis-off-by-default
* https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/1635-prevent-permabeta
* https://github.com/kubernetes/website/pull/31389
/sig architecture
cc @deads2k @kubernetes/api-approvers @kubernetes/sig-architecture-pr-reviews
> Clarify API version stability and guidelines

- content/zh-cn/docs/reference/using-api/_index.md
- Sync with the en version
- Fix minor errors about newline chars
```
content/zh-cn/docs/reference/using-api/_index.md
```
Preview: https://deploy-preview-37074--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/using-api/
> [zh] Sync /reference/using-api/_index.md

- .gitignore
It can be useful, for debugging purposes for `/public` to be a symlink to a Git repo, which is used to diff generated site files. This rule pattern change in this PR supports this use case.
/cc @nate-double-u @sftim
> Gitignore /public even if it's a symlink

- content/en/docs/reference/kubectl/_index.md
This PR updates the resource types table for the Kubernetes v1.24.3 release.
Closes: #35206
> Update Resource Types table for 1.25

- content/zh-cn/docs/tasks/job/pod-failure-policy.md
```
content/zh-cn/docs/tasks/job/pod-failure-policy.md
```
> [zh] Sync job/pod-failure-policy.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
```
Preview: https://deploy-preview-37080--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list/
> [zh] Sync kubeadm_config_images_list.md

- content/en/docs/contribute/review/reviewing-prs.md
Update https://kubernetes.io/docs/contribute/review/reviewing-prs/#review-process [[preview](https://deploy-preview-37060--kubernetes-io-main-staging.netlify.app/docs/contribute/review/reviewing-prs/#review-process)]
- Mention trivial edits
- It's OK if an author leaves in an existing grammar or spelling error that is not related to the issue they are fixing / the change they are making.
> Revise PR review guidelines

- content/en/docs/reference/using-api/server-side-apply.md
@justinsb told me he wasn't sure what permissions were needed to use server-side apply, and we're not doing a great job explaining this today so I added that sub-section about it. I think that's the right location since we also explain that ssa is a patch at that location. I also noticed a caution block that is obsolete since GA. And while I was editing this file, I just normalized every instances to `Server-Side Apply`.
> Various Server-Side Apply improvements

- content/en/docs/tasks/configure-pod-container/security-context.md
Hello!
Removed the duplicated Words in security-context.md. This will make the changes on the kubernetes website as well.
Solving the issue #37046
> Removed Duplicated words in Security-Context

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Configure Probes section does not mention startup probes. 
I just tried to check, what the default options for a startupProbe are and stumbled the second time over this. I think it would be benefitial to make it clear, that these probe options also apply to the startupProbe.
> Make scope for `Configure Probes` more clear (add startupProbe)

- data/i18n/en/en.toml
- layouts/docs/baseof.html
- layouts/partials/docs/auto-generated-pageinfo.html
- layouts/partials/page-meta-links.html
Tell the reader when they're viewing an autogenerated page, in case they want to report an issue - it should help make reports about autogenerated content stand out.
[Example](https://deploy-preview-36952--kubernetes-io-main-staging.netlify.app/docs/reference/kubernetes-api/workload-resources/)
> Emphasize auto-generated pages

- content/en/blog/_posts/2022-09-19-local-storage-capacity-isolation-ga.md
Fix PR fixes formatting in "[Kubernetes 1.25: Local Storage Capacity Isolation Reaches GA](https://kubernetes.io/blog/2022/09/19/local-storage-capacity-isolation-ga/)" blog post.
> Fix formatting in local storage capacity isolation blog post

- data/i18n/en/en.toml
- layouts/partials/navbar-version-selector.html
Fixes: https://github.com/kubernetes/website/issues/36903
Updates Release Information link in navbar-version-selector.html to point to the correct localization, instead of always redirecting to the English docs. 
This also updates the link text to make it so localization teams can translate Release Information.
> Fix URL in navbar-version-selector.html to point to correct localization

- layouts/partials/sidebar-tree.html
Fixes #28616 
In localization we noticed an issue displaying sub-items in the side nav when only the _index.md page was translated. Specifically, this was noticed when comparing the Kubeadm reference docs when all sub-items under kubeadm show in English, but are missing in the Korean docs. The sub items appear correctly in the French docs, where more sub pages have been translated.
* English: https://kubernetes.io/docs/reference/setup-tools/kubeadm/
* Korean: https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/
* French: https://kubernetes.io/fr/docs/reference/setup-tools/kubeadm/
The side nav should show any untranslated page as a link to the english docs. This is an attempt to correct this behavior and have all sub-items listed, even when pages aren't translated. 
More details …
> Make sub-items visible in localizations

- content/en/docs/concepts/security/multi-tenancy.md
In a multi-tenant environment, certain use case might requires traffic to be allowed between tenant owned namespaces, be very mindful to avoid any use of empty label selector {} for namespaceSelector field in network policy definition and strictly stick with specific labels which is set to namespaces.
if you think about consequences of using empty selector mistakenly for namespaceSelector field..It indeed matches all the available namespaces leading to condition where it will open communication from all other available namespace which will violate network isolation. So i think it would be right choice to make user aware of this as a recommendation.
> Adding recommendation for network isolation

- content/en/docs/reference/access-authn-authz/authentication.md
Updates the documentation to mention the `oidc-signing-algs` which was not referenced anywhere and is especially useful to configure because its default value is still `RS256` rather than `RS512`.
Somehow related to https://github.com/kubernetes/kubernetes/issues/104073 which made me aware of this configuration!
> docs: update OIDC documentation to mention the signing algorithms configuration

- content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
Sync with the en version
```
```
Preview: https://deploy-preview-37040--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints/
> [zh] Sync topology-spread-constraints.md

- content/en/docs/tasks/manage-gpus/scheduling-gpus.md
This change might mean that the changes proposed in https://github.com/kubernetes/website/pull/36982 are no longer needed.
Relevant to https://github.com/kubernetes/website/issues/36983
Fixes #36983
> Omit vendor install docs from scheduling task

- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- Sync with the en version
- Keep consistent for the term `liveness` as `存活` on a page
```
```
Preview: https://deploy-preview-37104--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
> [zh] Sync configure-liveness-readiness-startup-probes.md

- content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
- sync with the en version
- add anchors
```
content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
```
> [zh] Sync cpu-management-policies.md

- content/zh-cn/docs/concepts/security/multi-tenancy.md
- sync with the en version
- minor changes
```
content/zh-cn/docs/concepts/security/multi-tenancy.md
```
Preview: https://deploy-preview-37118--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/multi-tenancy/
> [zh] Sync multi-tenancy.md

- content/zh-cn/docs/reference/access-authn-authz/authentication.md
- Sync with the en version
- Minor changes
```
```
Preview: https://deploy-preview-37117--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/authentication/
> [zh] Sync /access-authn-authz/authentication.md

- content/zh-cn/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
- Sync with the en version.
- Add anchors and fix typos.
```
content/zh-cn/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
```
Preview: https://deploy-preview-37105--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-application/determine-reason-pod-failure/
> [zh] Sync determine-reason-pod-failure.md

- content/zh-cn/docs/reference/glossary/code-contributor.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #36910
> [zh-cn] Fixes Broken Link

- content/en/docs/tasks/administer-cluster/nodelocaldns.md
In this page https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/ of V1.25
in the `If kube-proxy is running in IPVS mode:` section command a `,` is missing between `s/` and `__PILLAR__DNS__SERVER__//g;`
```bash
sed -i "s/__PILLAR__LOCAL__DNS__/$localdns/g; s/__PILLAR__DNS__DOMAIN__/$domain/g; s/__PILLAR__DNS__SERVER__//g; s/__PILLAR__CLUSTER__DNS__/$kubedns/g" nodelocaldns.yaml
```
whereas in other versions a `,` is there. I think for which cluster got crashed error is coming.
> Fix command in task “Using NodeLocal DNSCache in Kubernetes Clusters”

- content/en/docs/reference/labels-annotations-taints/_index.md
Registers and documents the `scheduler.alpha.kubernetes.io/defaultTolerations` annotation 
**Updated pages:**
https://kubernetes.io/docs/reference/labels-annotations-taints/
Fixes #34212
/cc @sftim 
/sig docs
> Register and document scheduler.alpha.kubernetes.io/defaultTolerations annotation

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
This PR makes the following changes to the “without a package manager” section of [Installing kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/):
- Install kubeadm, kubelet through dl.k8s.io
- Separate out kubectl installation and redirect users to https://kubernetes.io/docs/tasks/tools/#kubectl
As suggested I also wanted to remove the part including fetching the latest release version via HTTP, however, should I also remove it from other pages like https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/ here?
Fixes #33228
> Install kubeadm, kubelet through dl.k8s.io and separate out kubectl installation

- content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
fix: https://github.com/kubernetes/website/issues/27805
**The retainKeys strategy only works in the strategic merge patch**
The error is reported in the https://github.com/kubernetes/website/issues/27805 because the strategic merge patch does not support custom resources.
And there are different errors depending on whether it is dry-run or not
```bash
root@caiwei-1:~# ./kubectl patch clusterimportpolicies secret  --patch-file patch-file-retainkeys.yaml
Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
root@caiwei-1:~# ./kubectl patch clusterimportpolicies secret  --patch-file patch-file-retainkeys.yaml --dry-run=client
error: …
```
> the retainKeys strategy only works in the strategic merge patch

- .github/workflows/netlify-periodic-build.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
As the upstream code evolves, many feature gates (deprecated or GA'ed) are removed. That means they are no longer recognized by the Kubernetes components. This PR moves such feature gates into a dedicated page for reference so that we won't bother revisit them again for future releases.
> Create new page for feature gates that were removed

- content/en/docs/reference/_index.md
> Add kube-scheduler config v1 to reference index

- content/ja/docs/concepts/containers/runtime-class.md
Fixed content/ja/docs/concepts/containers/runtime-class.md according to the English text, because it is outdated.
Fixes #36821
> [ja] Update content/ja/docs/concepts/containers/runtime-class.md to the latest.

- content/en/blog/_posts/2022-10-05-current-state-2019-third-party-audit.md
Fixes https://github.com/kubernetes/sig-security/issues/56
Preview: https://deploy-preview-36971--kubernetes-io-main-staging.netlify.app/blog/2022/10/05/current-state-2019-third-party-audit/
/cc @raesene @cailynse @reylejano @cji 
/committee security-response
> Blog: Current State of 2019 Third Party Kubernetes Audit

- content/en/docs/contribute/new-content/new-features.md
This PR is a follow-up to PR https://github.com/kubernetes/website/pull/36876 which moved the GA or removed features table to a new page
This PR updates instructions to add GA'd or removed features to the new page
> Update new-features page as follow-up to PR 36876 for GA or removed features page

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
A suggestion to 
https://github.com/kubernetes/website/issues/37157
Just mentioned the warning from kubectl when trying to force terminate a pod.
> added warning about indefinitely running resources

- OWNERS_ALIASES
This PR does the following:
- cleanup after the 1.25 release cycle and remove the 1.25 release docs lead from [sig-docs-en-owners](https://github.com/orgs/kubernetes/teams/sig-docs-en-owners) see https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#clean-up-access
- add @nate-double-u as a SIG Docs reviewer, @nate-double-u is already an existing blog reviewer
> Cleanup after 1.25 release and add nate-double-u as reviewer

- content/en/releases/release-managers.md
I'm not in the DEB/RPM rotation at Google anymore after switching teams earlier this year.
Juan Escobar is not in the rotation anymore.
Ben Kazemi is.
cc @justaugustus @MushuEE @BenjaminKazemi
> update release managers

- content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
- Sync with the en version #37158 
- Modify the position of newline chars
```
```
Preview: https://deploy-preview-37161--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/pod-lifecycle/
> [zh] Sync /workloads/pods/pod-lifecycle.md

- content/en/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
Signed-off-by: sky li (李少凯)-浪潮数据 <lishaokai1995@126.com>
English custom-resource-definition-v1.md has invalid link, I fixed it
> Fix the link failure in the English custom-resource-definition-v1.md

- netlify.toml
- The default branch name was updated from `master` to `main` via #30790, and you can see this change in `netlify.toml` line 25.
- It seems that the one occurrence of the name was missed in a comment -- this PR fixes that.
> Fix default branch name in comment of netlify.toml

- content/en/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
This PR fixes the long lines found in the apiserver-aggregation.md page.
> Tweak line wrapping in the apiserver aggregation page

- content/en/docs/concepts/policy/limit-range.md
- content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
- content/en/examples/concepts/policy/limit-range/example-conflict-with-limitrange-cpu.yaml
- content/en/examples/concepts/policy/limit-range/example-no-conflict-with-limitrange-cpu.yaml
- content/en/examples/concepts/policy/limit-range/problematic-limit-range.yaml
This is not the first time issue with `LimitRanger` behavior understanding comes up: https://github.com/kubernetes/kubernetes/issues/112835 A few people failed to understand the problem looking at limit ranger and pod spec during our triage session, which shows that it is not trivial.
This PR adds clarification to `LimitRanger` description.
/kind cleanup
/kind documentation
/sig node
/priority backlog
Related to:
- https://github.com/kubernetes/kubernetes/issues/112835
- https://github.com/kubernetes/kubernetes/issues/79988
> Revise and update LimitRange concept

- content/zh-cn/docs/concepts/security/pod-security-standards.md
```
content/zh-cn/docs/concepts/security/pod-security-standards.md
```
Preview: https://deploy-preview-37205--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/pod-security-standards/
> [zh] sync /pod-security-standards.md

- content/en/docs/tasks/administer-cluster/cpu-management-policies.md
Noticed a typo in the full-pcpus-only option when I copied and pasted from the documentation. Here is a fix.
> Fix typo in full-pcpus-only option

- content/en/docs/concepts/storage/storage-classes.md
Just fixing a simple typo, a missing close parenthesis in the storage class docs.
> adding missing close parenthesis

- content/fr/releases/_index.md
- data/i18n/fr/fr.toml
Fixes [[fr] Releases page in French is blank #35207](https://github.com/kubernetes/website/issues/35207).
I'm not really into localization but an actual [addition to the releases subfolder](https://github.com/kubernetes/website/pull/30233) introduced an issue and it was a shame to remove it so I just translated the release page for the French localization. I had to also add some localized data for the release structure to be localized as well.
> [fr] Add the localized French release version page

- content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md
Umbrella issue: https://github.com/kubernetes/website/issues/4491
Replaces https://github.com/kubernetes/website/pull/34856
This PR adds the steps to edit an existing Secret using a configuration file. It includes the merge commits from PR #35383 which make additional improvements to the page, however, only commit aae550f needs a review in this PR.
(I might not be doing this stacking PRs this correctly so I'm open to suggestions, like removing the merge commit altogether)
/sig docs
/language en
> Add Edit Secret step to Managing Secrets Using a Configuration File

- content/en/releases/patch-releases.md
- data/releases/schedule.yaml
This PR:
* Adds October and upcoming November patch releases to the patch releases list
* Moves November releases a week earlier (to 2022-11-09)
* Proposes dates for January and February patch releases
The original date for November releases is 2022-11-16 which is a week before Thanksgiving. Considering that some folks might take PTO around that time, we decided to move November releases a week earlier to avoid any potential staffing issues.
/assign @saschagrunert @cpanato @puerco @Verolop 
> Add October patch releases and update release dates

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
The feature is GAed in https://github.com/kubernetes/kubernetes/pull/110940.
It seems to be a typo from #36835.
> DisableAcceleratorUsageMetrics was GAed in v1.25

- README-zh.md
golang.org->golang.google.cn(official website in China address link)
I'm not sure if this should be changed to the official website of mainland China？
> [zh-cn]sync readme.md --Update GO address link

- content/ja/docs/concepts/workloads/controllers/job.md
This PR updates some links in ja docs to proper en pages.
related to: #37247 
If #37247 is merged, we need to update some links to those pages.
1. change link `ja/docs/reference/command-line-tools-reference/kube-apiserver` to `docs/reference/command-line-tools-reference/kube-apiserver`
2. change link `ja/docs/reference/config-api/apiserver-audit.v1` to `docs/reference/config-api/apiserver-audit.v1` 
I found 1 page for being changed by grep command.
```
$ grep "ja/docs/reference/command-line-tools-reference/kube-apiserver" -r ./ja -l                                            
./ja/docs/concepts/workloads/controllers/job.md  #<-- just 1 file is matched
$ grep "ja/docs/reference/config-api/apiserver-audit.v1" -r ./ja -l
```
That's why I updated …
> Change some links in ja to proper en pages

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
Hi, I just stumbled upon a link that got renamed in the target repository.
The term "fpga" is not present anymore in the latest version of the FPGA_as_a_Service repository due to a the top-level directory that got renamed.
> fix(device-plugins): update FPGA device link

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
Follow up on https://github.com/kubernetes/website/issues/35643
Updated page [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints)
Previous PR #35644
> Fix hyperlink on Pod Topology Spread Constraints page

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
When syncing with this file:
```
content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
```
find an alignment is incorrect.
Preview: https://deploy-preview-37373--kubernetes-io-main-staging.netlify.app/docs/concepts/scheduling-eviction/topology-spread-constraints/
> fix alignment in topology-spread-constraints.md

- content/en/docs/concepts/architecture/cloud-controller.md
- content/en/docs/concepts/overview/components.md
- content/en/docs/concepts/services-networking/connect-applications-service.md
- content/en/docs/concepts/services-networking/dns-pod-service.md
- content/en/docs/concepts/services-networking/endpoint-slices.md
- content/en/docs/concepts/services-networking/service.md
- content/en/docs/concepts/services-networking/topology-aware-hints.md
- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
- content/en/docs/reference/access-authn-authz/rbac.md
- content/en/docs/reference/labels-annotations-taints/_index.md
- content/en/docs/tasks/administer-cluster/nodelocaldns.md
- content/en/examples/access/endpoints-aggregated.yaml
Document EndpointSlice as the preferred and most appropriate mechanism to record the backing endpoints of a Service.
/sig network
> Favor EndpointSlice over Endpoints

- content/en/docs/tutorials/security/apparmor.md
This PR updates an example `kubectl exec` command to avoid warnings.
Running `kubectl exec <pod_name> <command>` is deprecated:
```
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead
```
It should be: `kubectl exec <pod_name> -- <command>`
The change can be previewed here:
https://deploy-preview-37221--kubernetes-io-main-staging.netlify.app/docs/tutorials/security/apparmor/#securing-a-pod
> Update deprecated kubectl command in apparmor doc

- content/en/docs/contribute/new-content/blogs-case-studies.md
Fixes https://github.com/kubernetes/website/issues/37365
Updated page [Submitting blog posts and case studies](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/)
I was facing issues while committing so raised another PR.
old PR #37366 is closed.
> Fix broken link on Submitting blog posts and case studies page

- layouts/blog/baseof.html
To help search engines, make the canonical URL appear near the start of the `<head>` HTML element. This improves the chance of a search engine paying attention; some indexers only read part of the page and ignore information that appears later within the `<head>` element.
This is mainly useful for blog articles that we mirror from another site, such as https://k8s.dev/blog/
> Move canonical link earlier in metadata

- content/en/docs/concepts/services-networking/service.md
The existing text implied that creating a node port or load balanced Service would actually add an extra Service object that you could see in the Kubernetes API. This isn't true, so avoid implying that it is.
/sig network
> Avoid misleading text in Service concept

- content/en/docs/concepts/services-networking/dns-pod-service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
This adds DNS search domain list limits and removes the resolved DNS issue.
PRs:
kubernetes/kubernetes#112824
KEP:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2595-expanded-dns-config
Enhancement issue:
https://github.com/kubernetes/enhancements/issues/2595
> Add DNS search domain list limits and remove resolved DNS issue

- content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
This PR fixes a small typo in the HorizontalPodAutoscaler docs.
> docs(HPA): typo "if it's unready and transitioned to unready"

- content/en/docs/contribute/style/style-guide.md
Update the style guide to add guidance for title case in page titles
/sig docs
/language en
/cc @sftim
> Add title case style guideline

- content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md
- sync with en
- other changes about newline, bold, plural
```
content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md
```
Preview: https://deploy-preview-37454--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale/
> [zh] sync horizontal-pod-autoscale.md

- content/en/docs/concepts/workloads/controllers/statefulset.md
The word "controller" has been written with a lowercase c in the entire documentation. Only here I could find an upercase C. So I changed it to match the rest of the documentation.
> Update statefulset.md - Matching lowercase c in Controller to the rest of the documentation

- content/en/docs/concepts/containers/container-lifecycle-hooks.md
- content/en/docs/concepts/containers/runtime-class.md
updating page weights for content/en/docs/concepts/containers
contributes to https://github.com/kubernetes/website/issues/35093
@reylejano @natalisucks @bradtopol 
updating page weights for content/en/docs/concepts/containers
Confirmation that pages haven't changed order:
> updating page weights for content/en/docs/concepts/containers

- OWNERS_ALIASES
As Nate is a blog approver and will now be doing PR Wrangling, he needs to be added to our approver list to unlock this work.
Congratulations, Nate! 🎉 
@reylejano @sftim @divya-mohan0209
> Add Nate Waddington as an approver for docs

- content/en/docs/concepts/workloads/pods/downward-api.md
This PR adds a missing weight to the `Downward API` subsection of Concepts/Workloads. This will allow consistent sorting for localization. 
Related # https://github.com/kubernetes/website/issues/35093
> KubeCon Docs Sprint: Added Missing Weight for Concepts/Workloads/Pods

- content/en/docs/concepts/overview/working-with-objects/annotations.md
- content/en/docs/concepts/overview/working-with-objects/common-labels.md
- content/en/docs/concepts/overview/working-with-objects/field-selectors.md
- content/en/docs/concepts/overview/working-with-objects/finalizers.md
- content/en/docs/concepts/overview/working-with-objects/names.md
- content/en/docs/concepts/overview/working-with-objects/namespaces.md
- content/en/docs/concepts/overview/working-with-objects/object-management.md
- content/en/docs/concepts/overview/working-with-objects/owners-dependents.md
This PR updates the page weights for concepts/overview/working-with-objects
for the 2022 Docs Sprint at Contributor Summit
Related to https://github.com/kubernetes/website/issues/35093
/assign @natalisucks
> Update page weights for concepts/overview/working-with-objects

- content/en/docs/tasks/access-application-cluster/service-access-application-cluster.md
All supported Kubernetes versions let you access Services within your cluster, so there is no special need to check what version you're running.
Omit the check.
> Don't check Kubernetes version for using Service API

- assets/scss/_custom.scss
Removes `overflow: hidden` from markdown yaml code blocks to prevent the content from being cut off.
Resolves https://github.com/kubernetes/website/issues/37419
| Before      | After |
| ----------- | ----------- |
| ![before](https://user-images.githubusercontent.com/17005849/197350405-0f397acd-c7ad-401a-8a2d-a2fc3cee1555.png)      | ![after](https://user-images.githubusercontent.com/17005849/197350381-32e72b21-d7a3-4ae9-b80f-59aeaf71cb7b.gif)       |
The horizontal scroll behaviour was removed some days ago probably to adjust the right padding, that was being affected by the overflowing text...
But I believe that the overflowing text is a "feature" on this context, because we need to give the user a hint that this content is horizontally scrollable:
In the example above, we can see that …
> Fixes horizontal scroll on yaml code blocks

- content/en/docs/tutorials/services/source-ip.md
Update page weights for pages in content/en/docs/tutorials/services
Partially fix https://github.com/kubernetes/website/issues/35093
@reylejano @natalisucks @bradtopol 
Updating page weights for content/en/docs/tutorials/*
> KubeCon Docs Sprint: Update page weights for pages in content/en/docs/tutorials/services

- content/en/docs/contribute/localization.md
Fixes https://github.com/kubernetes/website/issues/36786
* Retitled "Language specific style guide and glossary" section to "Language-specific localization guide" and updated its contents.
* Made minor revisions for style and grammar throughout.
* Reflowed the line breaks throughout. They were inconsistent and caused "jagged-looking" content.
> Expand the "Language specific style guide and glossary" section

- content/en/docs/concepts/security/api-server-bypass-risks.md
- content/en/docs/concepts/security/security-checklist.md
Adding page weights to two security pages that are missing them. This is done to help make the order more consistent when the docs are produced for different localizations, per [Issue #35093](https://github.com/kubernetes/website/issues/35093).
> Add page weights to concepts -> security pages

- content/en/docs/concepts/scheduling-eviction/api-eviction.md
- content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
- content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md
- content/en/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
- content/en/docs/concepts/scheduling-eviction/scheduling-framework.md
- content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
Updates page weights on concepts/scheduling-eviction pages. In this case, they are hard-coded into the _index.md file. So the weights I added were done to match the order included in that file:
```
kube-scheduler.md:weight: 10
assign-pod-node.md:weight: 20
pod-overhead.md:weight: 30
topology-spread-constraints.md:weight: 40
taint-and-toleration.md:weight: 50
scheduling-framework.md:weight: 60
scheduler-perf-tuning.md:weight: 70
resource-bin-packing.md:weight: 80
pod-priority-preemption.md:weight: 90
node-pressure-eviction.md:weight: 100
api-eviction.md:weight: 110
```
See [PR #35093](https://github.com/kubernetes/website/issues/35093).
@natalisucks
> Add page weights to concepts -> scheduling-eviction pages

- content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
- content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
- content/zh-cn/docs/concepts/scheduling-eviction/pod-priority-preemption.md
- content/zh-cn/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
- content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md
- content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
- content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
- Sync with en #37511 
- Checked each file with `./scripts/lsync.sh` and cleared all differences in this folder
```
kube-scheduler.md:weight: 10
assign-pod-node.md:weight: 20
pod-overhead.md:weight: 30
topology-spread-constraints.md:weight: 40
taint-and-toleration.md:weight: 50
scheduling-framework.md:weight: 60
scheduler-perf-tuning.md:weight: 70
resource-bin-packing.md:weight: 80
pod-priority-preemption.md:weight: 90
node-pressure-eviction.md:weight: 100
api-eviction.md:weight: 110
```
Preview: https://deploy-preview-37526--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints/
> [zh] sync folder: /concepts/scheduling-eviction/

- content/en/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md
A comment in the service file was missing a leading # -- when copied and pasted people would not realize and the service fails to start with an error. Added a # to comment out the line.
> Fix incorrect comment in sample systemd unit file

- content/zh-cn/docs/reference/access-authn-authz/rbac.md
Sync with en.
```
```
Preview: https://deploy-preview-37424--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/rbac/
> [zh] sync /access-authn-authz/rbac.md

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md
Sync with en.
```
content/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md
```
Preview: https://deploy-preview-37548--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration/
> [zh] sync kubelet-integration.md

- OWNERS_ALIASES
Mauren has been doing an amazing work reviewing pt_BR Docs.
I would like to propose her promotion as a sig-docs pt_BR project approver/lead. Promotion Mauren will help unstuck some PRs that today depends on few other approvers, and also raise pt_BR projects to another level.
Thanks for all the effort you've been doing so far @stormqueen1990 
/cc @divya-mohan0209 @jimangel @edsoncelio 
/assign @divya-mohan0209 @jimangel @edsoncelio
> Promote Mauren to pt approvers

- content/zh-cn/docs/concepts/cluster-administration/_index.md
- content/zh-cn/docs/concepts/extend-kubernetes/_index.md
- content/zh-cn/docs/concepts/services-networking/topology-aware-hints.md
- content/zh-cn/docs/concepts/workloads/pods/_index.md
- content/zh-cn/docs/tasks/access-application-cluster/web-ui-dashboard.md
In this Markdown parser, the format `中文**字串（English）**中文` will not parsed as bold.
In `web-ui-dashboard.md`, `**CPU 需求（核数）**和**内存需求（MiB）**` is parsed as `<b>CPU 需求（核數）<b>和</b>記憶體需求（MiB）</b>`.
> [zh-cn] Fix bold format

- content/en/docs/concepts/overview/_index.md
A colon is better suited for this sentence rather than a comma, since we are illustrating an example.
> Use colon instead of comma when giving an example

- content/en/examples/admin/dns/dnsutils.yaml
This changes the default example to prevent unnecessary restarts.
> Update dnsutils.yaml example to prevent constant restarts

- content/en/docs/tasks/administer-cluster/namespaces-walkthrough.md
- content/en/examples/admin/namespace-dev.yaml
- content/en/examples/admin/namespace-prod.yaml
Signed-off-by: Bishal Das <bishalhnj127@gmail.com>
Fixes :- #37160
Closes:- #37160
`Json` manifest has changed into `yaml` manifest in namespace walkthrough
Filelink:- https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/#create-new-namespaces
> For namespace walkthrough, switch example manifests to YAML

- content/en/docs/contribute/generate-ref-docs/quickstart.md
No need to mention the quickstart twice, so don't.
Existing page: https://kubernetes.io/docs/contribute/generate-ref-docs/quickstart/
> Tweak reference docs section index

- content/en/docs/concepts/configuration/configmap.md
- content/en/examples/configmap/configure-pod.yaml
This PR works on:
- update the example to configure pods from the configmap
- Use the `codenew` shortcode instead of directly code
Closes #36650
> Update example to configure pods from configmap

- content/en/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
This change updates the structure of the Kustomize Manage Secrets page:
1. Update original section title to Create a secret
2. Add tabs for using string literals and using files
3. Add a section for editing an existing secret (mentioning that kustomize creates a new Secret instead of replacing the old one)
4. Update cleanup section to be a delete task
The biggest source of diff here is the addition of tabs.
This is one of three PRs that will make the "Manage Secrets using X" topics consistent to provide Create, Edit, and Delete steps for kubectl, config files, and kustomize. Original, larger PR showing the end state: #34674
This PR is part of a much larger overhaul of the Secrets documentation. The tracking issue is #4491.
/sig docs
/language en
/do-not-merge work-in-progress
/cc @tengqm
> Add create and edit to kustomize steps

- content/ja/docs/concepts/architecture/garbage-collection.md
- content/ja/docs/concepts/workloads/pods/pod-lifecycle.md
Fixed content/ja/docs/concepts/architecture/garbage-collection.md to the English text, because it is outdated.
I found the following PRs for English page. This PR fixed them for Japanese page.
* https://github.com/kubernetes/website/pull/35742
* https://github.com/kubernetes/website/pull/32578 -> This had been fixed on Japanese page.
* https://github.com/kubernetes/website/pull/31181
Fixes #36852
> [ja] content/ja/docs/concepts/architecture/garbage-collection.md to the latest.

- content/ja/docs/concepts/services-networking/dns-pod-service.md
- content/ja/docs/tasks/network/validate-dual-stack.md
Sync PR: https://github.com/kubernetes/website/pull/36683
```
content/ja/docs/concepts/services-networking/dns-pod-service.md
content/ja/docs/tasks/network/validate-dual-stack.md
```
> [ja] Sync use IPv6 Address Prefix Reserved for Documentation

- content/en/docs/concepts/storage/dynamic-provisioning.md
- content/en/docs/concepts/storage/storage-capacity.md
- content/en/docs/concepts/storage/storage-classes.md
- content/en/docs/concepts/storage/storage-limits.md
- content/en/docs/concepts/storage/volume-health-monitoring.md
- content/en/docs/concepts/storage/volume-pvc-datasource.md
- content/en/docs/concepts/storage/volume-snapshot-classes.md
- content/en/docs/concepts/storage/volume-snapshots.md
- content/en/docs/concepts/storage/windows-storage.md
contributes to https://github.com/kubernetes/website/issues/35093
Updates page weights in content/en/docs/concepts/storage
Before my changes:
After my changes:
> KubeCon Docs Sprint: Update page weights for content/en/docs/concepts/storage

- content/zh-cn/docs/reference/kubectl/cheatsheet.md
Sync with en #35732 
```
content/zh-cn/docs/reference/kubectl/cheatsheet.md
```
Preview: https://deploy-preview-37610--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubectl/cheatsheet/
> [zh] sync /kubectl/cheatsheet.md

- content/en/blog/_posts/2022-10-27-live-and-let-live-with-kluctl-and-ssa.md
- content/en/blog/_posts/2022-11-04-live-and-let-live-with-kluctl-and-ssa.md
This PR proposes a blog post about the use of SSA in Kluctl. Creating this post was suggested to me when I contacted #sig-api-machinery after reading the recent "Server Side Apply Is Great And You Should Be Using It" blog post.
I hope this post is of some value for the Kubernetes blog. I'm not sure how reviews are usually performed here and hope that it's ok that I used this early draft to directly create the PR. If preferred, I can also copy this into a Google Doc and let review happen there first.
The post also contains a link to the podtato-head repository. This link is currently dead as it refers to a directory that did not get merged yet. The PR for this can be found [here](https://github.com/podtato-head/podtato-head/pull/178). Until then, you can check …
> Add a blog post about Kluctl and its use of SSA

- content/en/docs/setup/best-practices/certificates.md
- content/en/docs/setup/best-practices/cluster-large.md
- content/en/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md
- content/en/docs/setup/production-environment/turnkey-solutions.md
This PR updates duplicated weights in the setup folder and it sub folders.
Related # https://github.com/kubernetes/website/issues/35093
> KubeCon Docs Sprint: Update Weights for Setup and Subfolders

- content/en/docs/concepts/storage/volumes.md
- content/en/docs/concepts/storage/windows-storage.md
All these links with
```
/docs/concepts/storage/volumes/#flexvolume
```
are broken due to changes in `volumes.md`
The solution is to add an anchor `{#flexvolume}` similar to other 22 anchors in:
```
content/en/docs/concepts/storage/volumes.md
```
Related PRs are #37606 and #37608 and issues:
Fixes #37605 
Fixes #37607
> Fix links about flexvolume

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
Fixes:- #37517 
Closes:- #37517
The command before 
```bash
kubectl uncordon <node-to-drain>
```
updated to 
```bash
kubectl uncordon <node-to-uncordon>
```
as it is already in drained state!
> Updated `<node-to-drain>` to `<node-to-uncordon>` in kubeadm-upgrade

- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
- content/en/docs/reference/access-authn-authz/kubelet-authn-authz.md
- content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
- content/en/docs/reference/access-authn-authz/webhook.md
contributes to https://github.com/kubernetes/website/issues/35093
@reylejano @natalisucks @bradtopol
Updating section to have distinct page weight. (these do not appear to be auto-generated pages in the reference section)
> Update page weights in API Access Control reference section

- content/zh-cn/docs/concepts/architecture/cri.md
- sync with en weight
- try to improve something
```
content/zh-cn/docs/concepts/architecture/cri.md
```
Preview: https://deploy-preview-37680--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/cri/
> [zh] sync /architecture/cri.md

- content/en/docs/concepts/services-networking/service-topology.md
Follow up to https://github.com/kubernetes/website/pull/37494; contributes to https://github.com/kubernetes/website/issues/35093
Updating service topology to a higher weight than any other page in its section as it is a deprecated feature.
/cc @haosdent @sftim
> Updating service topology to a higher weight due to deprecation

- content/en/docs/contribute/style/write-new-topic.md
Fixes #37605
Updated page [Writing a new topic](https://kubernetes.io/docs/contribute/style/write-new-topic/#embedding-code-in-your-topic)
> Fix broken link on Writing a new topic Page

- content/en/docs/contribute/localization.md
When syncing with this file
```
content/en/docs/contribute/localization.md
```
find the list and table are incorrectly aligned.
Corrected preview: https://deploy-preview-37510--kubernetes-io-main-staging.netlify.app/docs/contribute/localization/
> Fix bullet alignment errors in localization.md

- layouts/partials/head.html
- Contributes to #35299
- v1.21 counterpart to, for example, #36322
- Note that v1.21 is the oldest release for which we'll update the analytics ID.
/cc @nate-double-u @sftim @reylejano
> Use Google Analytics 4 (GA4) site tag for v1.21

- content/en/docs/reference/using-api/client-libraries.md
Current version of the [documentation page](https://kubernetes.io/docs/reference/using-api/client-libraries/) for the client libraries has a wrong link for Java examples, which points to the installation section instead of the real examples.
> Update link for Java Client Library examples

- content/en/docs/tasks/extend-kubernetes/setup-konnectivity.md
This cleans up the command to generate the certificate signin request for the Konnectivity server, by removing a duplicated openssl CLI option for the output file.
Signed-off-by: Massimiliano Giovagnoli me@maxgio.it
> docs(setup-konnectivity.md): remove duplicate openssl option

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
The feature gate MixedProtocolLBService moves to GA state in 1.26. The documentation of the support of different protocols in the same LB Service is updated.
k/k PR: https://github.com/kubernetes/kubernetes/pull/112895
k/enhancement issue: https://github.com/kubernetes/enhancements/issues/1435
> Update docs given that Services with type=LoadBalancer is stable

- content/en/docs/concepts/scheduling-eviction/_index.md
- content/en/docs/concepts/security/_index.md
- content/en/docs/concepts/workloads/_index.md
Changes the page weights of the index files for folders in the /docs/concepts folder. There were some overlapping weights and weights that were close together.
A part of the work to close https://github.com/kubernetes/website/issues/35093. Remaining work from the docs sprint at Kubecon NA last week
> Adjust page weights for /docs/concepts section

- content/en/docs/reference/access-authn-authz/_index.md
- content/en/docs/reference/command-line-tools-reference/_index.md
- content/en/docs/reference/command-line-tools-reference/kubelet.md
- content/en/docs/reference/config-api/_index.md
- content/en/docs/reference/instrumentation/_index.md
- content/en/docs/reference/issues-security/_index.md
- content/en/docs/reference/kubectl/_index.md
- content/en/docs/reference/kubectl/conventions.md
- content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
- content/en/docs/reference/kubectl/jsonpath.md
- content/en/docs/reference/kubernetes-api/_index.md
- content/en/docs/reference/labels-annotations-taints/_index.md
- content/en/docs/reference/labels-annotations-taints/audit-annotations.md
- content/en/docs/reference/node/_index.md
- content/en/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md
- content/en/docs/reference/ports-and-protocols.md
- content/en/docs/reference/scheduling/_index.md
- content/en/docs/reference/scheduling/policies.md
- content/en/docs/reference/setup-tools/_index.md
- content/en/docs/reference/tools/_index.md
- content/en/docs/reference/tools/map-crictl-dockercli.md
- content/en/docs/reference/using-api/_index.md
Some of these pages in the reference section are autogenerated, but not all. This PR updates the pages and folders that are not autogenerated within the docs/en/reference section. Please let me know if i've accidentally included a fix to an autogenerated page :) 
Related to #35093 and cleanup work from the Kubecon NA docs sprint.
related to #37486 as this PR updates all the non-autogenerated pages within the reference section.
> Updates page weights in reference docs section

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
```
```
Preview: https://deploy-preview-37371--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/
> [zh] sync /compute-storage-net/device-plugins.md

- content/zh-cn/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Sync with the en version #37339 
```
content/zh-cn/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
```
Preview: https://deploy-preview-37396--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/access-application-cluster/configure-access-multiple-clusters/
> [zh] sync configure-access-multiple-clusters.md

- content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
- Sync with the en version.
- Keep consistent style with note and caution blocks 
```
```
Preview: https://deploy-preview-37410--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/pod-lifecycle/
> [zh] sync pod-lifecycle.md

- content/zh-cn/docs/concepts/services-networking/dns-pod-service.md
```
```
Preview: https://deploy-preview-37397--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/dns-pod-service/
> [zh] sync dns-pod-service.md

- content/en/docs/reference/access-authn-authz/admission-controllers.md
- Improve page title
- Update page to match style guide
- Wording and correctness tweaks
[Preview](https://deploy-preview-37734--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/admission-controllers/) vs [original](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/)
> Tweak reference for admission controllers

- content/zh-cn/community/code-of-conduct.md
> fix: zh-cn code of conduct css

- content/zh-cn/docs/concepts/security/api-server-bypass-risks.md
fixed: https://github.com/kubernetes/website/issues/37689
Translate Chinese version for api-server-bypass-risks.md
[Preview](https://deploy-preview-37724--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/api-server-bypass-risks/)
> [zh-cn] Translate /docs/concepts/security/api-server-bypass-risks.md to Chinese

- content/en/docs/concepts/storage/dynamic-provisioning.md
1. Give an accurate link text
2. A redirected link works not very well if directly localized such as `/zh-cn/docs/setup/multiple-zones` and more langs
3. Remove the newline char between link text
```
content/en/docs/concepts/storage/dynamic-provisioning.md
```
Preview: https://deploy-preview-37704--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/dynamic-provisioning/
> Optimize link text in /dynamic-provisioning.md

- content/en/docs/concepts/configuration/manage-resources-containers.md
- content/en/docs/concepts/storage/volumes.md
The sizeLimit parameter to emptyDirs is not documented outside of the API reference. In addition, its relation to node ephemeral storage is complicated and so could stand to be refined.
/assign @msau42 
/assign @jingxu97
> Clarify emptyDir sizeLimit

- content/en/docs/concepts/storage/volumes.md
`Pod.spec.volumes.nfs.readOnly` was subtly misspelled `readonly`, which was breaking the example.
```
$ k explain Pod.spec.volumes.nfs.readonly
error: field "readonly" does not exist
$ k explain Pod.spec.volumes.nfs.readOnly
KIND:     Pod
VERSION:  v1
FIELD:    readOnly <boolean>
...
```
> Fix tiny typo in NFS Volume example.

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Refer to https://github.com/kubernetes/enhancements/issues/3094
> Graduate scheduler nodeInclusionPolicy to beta

- content/en/docs/concepts/storage/projected-volumes.md
**Problem:**
Projected Volumes have special handling for `serviceAccountTokens` that causes them to disregard `defaultMode` when all containers in a pod have the same `runAsUser`. This undocumented behavior led to a bug report in kubernetes/kubernetes#106365
**Proposed Solution:**
Update projected volumes doc to explain special behavior:
- When all containers specified at pod creation have the same `runAsUser`, the `serviceAccountToken` will use this user as the file owner and set mode `0600`.
- Ephemeral containers are never present at pod creation, so ephemeralContainer `runAsUser` aren't considered in this behavior.
**Page to Update:**
https://kubernetes.io/docs/concepts/storage/projected-volumes/
Fixes: #32351
Supersedes: #32354
> Clarify handling of projected SA token permissions

- content/en/docs/concepts/security/pod-security-policy.md
Update https://kubernetes.io/docs/concepts/security/pod-security-policy/ [[preview](https://deploy-preview-37731--kubernetes-io-main-staging.netlify.app/docs/concepts/security/pod-security-policy/)]
- Use semi-custom Docsy callout to note the removal
- (this is not our first use of Docsy's built-in callouts)
- Stop stating that the API is deprecated; it's now actually removed.
and
- Remove reviewers (feature was removed)
> Tweak page about PodSecurityPolicy removal

- content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
This change updates the structure of the kubectl Manage Secrets page:
1. Reduce wording about secret usage
2. Add headings for using literals and files to create secrets
3. In the subheadings, moved existing wording from other parts of the doc into the tabs and cleaned up
4. Cleaned up style for simplicity
5. Add an edit secret step
6. Add a caution about decoding secret data in the terminal
7. Update cleanup section to be a delete task
The commit messages for each commit have full details about what changed
This is one of three PRs that will make the "Manage Secrets using X" topics consistent to provide Create, Edit, and Delete steps for kubectl, config files, and kustomize. Original, larger PR showing the end state: https://github.com/kubernetes/website/pull/34674
This PR is part of a …
> Add create and edit to kubectl secrets

- content/en/blog/_posts/2021-12-07-kubernetes-release-1.23.md
Minor typo correction to the [Kubernetes 1.23 release announcement blog](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/) on the `HorizontalPodAutoscaler` section.
> docs(hpa): fix typo in 1.23 blog announcement

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
- content/en/docs/tasks/configure-pod-container/configure-service-account.md
- content/en/examples/secret/serviceaccount/mysecretname.yaml
- Account for TokenRequest API now being the default
- [example](https://deploy-preview-33654--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount)
- [example](https://deploy-preview-33654--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/service-accounts-admin/#control-plane-details)
- [example](https://deploy-preview-33654--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts)
- General rewording
This adapts and supersedes PR #14681.
Fixes https://github.com/kubernetes/website/issues/37181
/sig auth
> Reword tasks relating to ServiceAccounts

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
This PR fixes the line wrapping problems found in the network-plugins.md page.
> Tweak line wrappings in the network-plugins page

- content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
This PR fixes the long line problems found in the custom-resources.md concept page. Saddly, there are some markdown tables we cannot fix yet in this PR. Maybe a HTML table is a better alternative.
> Tweak line wrapping in the custom-resource concept page

- content/en/docs/concepts/cluster-administration/system-logs.md
This PR fixes the line wrapping problems found in the system-logs.md file.
> Tweak line wrapping in the system-logs page

- content/en/docs/concepts/configuration/overview.md
This PR wrapps the long lines found in the configuration/overview.md page.
> Tweak line wrapping for configuration overview page

- content/en/docs/concepts/storage/volume-snapshots.md
Performed two actions to this file:
1. Run `npx prettier --w`
2. Manually check and wrap long lines around col 80
No any other content change.
```
content/en/docs/concepts/storage/volume-snapshots.md
```
> Tweak line wrappings in /volume-snapshots.md

- content/en/docs/tasks/tools/install-kubectl-windows.md
The powershell command needs an ending mark of \``` that is accidentally deleted in #36854 
```
content/en/docs/tasks/tools/install-kubectl-windows.md
```
[This codeblock](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/) looks not very good now:
> Add the ending mark of codeblock in install-kubectl-windows.md

- content/en/docs/concepts/services-networking/_index.md
- content/en/docs/concepts/services-networking/endpoint-slices.md
- content/en/docs/concepts/services-networking/service-traffic-policy.md
- content/en/docs/concepts/services-networking/service.md
- content/en/docs/concepts/services-networking/topology-aware-hints.md
- content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md
- content/en/docs/tasks/access-application-cluster/service-access-application-cluster.md
- content/en/docs/tasks/administer-cluster/enabling-service-topology.md
- content/en/docs/tutorials/_index.md
- content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
- content/en/docs/tutorials/services/connect-applications-service.md
- content/en/docs/tutorials/services/source-ip.md
- content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
- content/en/docs/tutorials/stateless-application/guestbook.md
- static/_redirects
Move [Connecting Applications with Services](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/) to tutorials section: it's a tutorial.
[[preview](https://deploy-preview-36669--kubernetes-io-main-staging.netlify.app/docs/tutorials/services/connect-applications-service/)]
_This_ PR is the move. After this merges, I hope to file an issue about further cleanup to the page in its new home.
/label refactor
> Move "Connecting Applications with Services" to tutorials section

- content/zh-cn/docs/tutorials/configuration/configure-redis-using-configmap.md
English Doc: The key and path under spec.volumes[1].items[0] exposes the redis-config key from the example-redis-config ConfigMap as a file named redis.conf on the config volume.
Chinese Doc: spec.volumes[1].items[0] 下的 key 和 path 会将来自 example-redis-config ConfigMap 中的 redis-config 密钥公开在 config 卷上一个名为 redis-config 的文件中。
> [zh] Update configure-redis-using-configmap.md

- content/ko/docs/concepts/scheduling-eviction/pod-priority-preemption.md
Closes #37740
Removed the line `the scheduler always tries the "nominated Node" before iterating over any other nodes`
> [ko] remove extra line from `pod-priority-preemption.md`

- layouts/partials/head.html
This logic is copied from the way that the [Docsy code](https://github.com/google/docsy/blob/v0.2.0/layouts/partials/head.html#L8-L13) handles this.
Before this change, crawlers were indexing the print versions of pages, which is not what we want to happen.
> Tell crawlers not to index print pages

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/cpu-management-policies.md
Docs update for Kubelet CPU Manager GA graduation.
Issue: https://github.com/kubernetes/enhancements/issues/3570
Replaces https://github.com/kubernetes/website/pull/37288 which was mistakenly filed against `main` branch
Signed-off-by: Francesco Romani <fromani@redhat.com>
> node: cpumgr: docs: Kubelet CPU Manager GA graduation

- content/en/docs/concepts/overview/working-with-objects/names.md
Seems like annotations was missing in the what's next section . So, added reference for same in the section as well.
Updated page : https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
> Adding annotations reference in names.md

- content/en/docs/concepts/overview/working-with-objects/namespaces.md
- Move the list of default namespaces earlier in https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/  [[preview](https://deploy-preview-37739--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/working-with-objects/namespaces/)]
- Sort that alphabetically
- Use a description list
> Improve list of default namespaces

- content/en/docs/concepts/storage/projected-volumes.md
Closes #37790
Removed _When the TokenRequestProjection feature is enabled_ because `TokenRequestProjection` has graduated and is always enabled.
> docs: Update projected-volumes.md

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
As the `CSRDuration` feature gate was graduated to GA in 1.24 and it has been removed in k8s v1.26, here is the PR which will remove it in the upcoming release k8s v1.26 [k8s/k8s #112386](https://github.com/kubernetes/kubernetes/pull/112386). so as a reference to it, this PR  removes the `CSRDuration` feature gate from Feature Gates docs.
> Moved Feature Gate CSRDuration under Feature Gates (removed) Page

- content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
- content/zh-cn/examples/secret/serviceaccount/mysecretname.yaml
Sync with en #33654 
```
```
Preview: https://deploy-preview-37836--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/service-accounts-admin/
> [zh] sync /service-accounts-admin.md

- content/en/docs/concepts/containers/_index.md
- content/en/docs/concepts/containers/images.md
- content/en/docs/concepts/containers/runtime-class.md
Update https://kubernetes.io/docs/concepts/containers/ [[preview](https://deploy-preview-37594--kubernetes-io-main-staging.netlify.app/docs/concepts/containers/)]
- outline what [RuntimeClass](https://kubernetes.io/docs/concepts/containers/runtime-class/) is for
- omit container image and runtimeclass from links as they are already mentioned explicitly
> Redo index for Containers concept

- content/en/docs/concepts/workloads/controllers/replicaset.md
- content/en/docs/concepts/workloads/controllers/replicationcontroller.md
Update https://kubernetes.io/#features [[preview](https://deploy-preview-37591--kubernetes-io-main-staging.netlify.app/#features)]
Don't highlight the legacy ReplicationController API when talking about Kubernetes' ability to self-heal. Instead, link to ReplicaSet (with similar text).
> Switch self-healing feature to ReplicaSet

- content/zh-cn/docs/reference/glossary/kube-proxy.md
https://kubernetes.io/zh-cn/docs/concepts/overview/components/#kube-proxy
before: kube-proxy 是集群中每个节点（node）**所上**运行的网络代理
after : kube-proxy 是集群中每个节点（node）**上所**运行的网络代理
> fix text order

- content/en/releases/patch-releases.md
- data/releases/schedule.yaml
* Add November and upcoming December patch releases to the patch releases list
* Move December patch releases for a week earlier (2022-12-07): https://groups.google.com/a/kubernetes.io/g/dev/c/GDkqm5JtiNg/m/_OHgqDgWBQAJ
/assign @saschagrunert @cpanato @puerco @Verolop 
> Add November patch releases and mark 1.22 release as End-of-Life (EOL)

- content/en/docs/reference/glossary/etcd.md
This PR rephrasing the ETCD definition under [Glossary](https://kubernetes.io/docs/reference/glossary/?all=true#term-etcd)  which is reflecting on[ Kubernetes components](https://kubernetes.io/docs/concepts/overview/components/#etcd).
Fixes #37409
> Rephrasing the definition of etcd under Glossary

- content/en/docs/tutorials/hello-minikube.md
Should fixes https://github.com/kubernetes/website/issues/36732 and https://github.com/kubernetes/website/pull/37361.
Preview available [here](https://deploy-preview-37383--kubernetes-io-main-staging.netlify.app/docs/tutorials/hello-minikube/#create-a-deployment).
I took the liberty to open a new PR because the author of [the one we worked on](https://github.com/kubernetes/website/pull/36731) was not answering anymore.
The previous version of the image did not support arm64. This one supports amd64, arm, arm64, ppc64le, s390x on Linux, and amd64 on multiple Windows versions.
More information and context in this PR https://github.com/kubernetes/website/pull/36731 and the discussion that lead to this solution [available here](https://kubernetes.slack.com/archives/CCK68P2Q2/p1666183862561759) …
> Update echoserver image in "Hello Minikube" tutorial for multiarch

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
Fix typo MinDomainsInPodToplogySpread -> MinDomainsInPodTopologySpread
> Fix typo in Pod Topology Spread Constraints concept

- content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md
- Use relative URL in the reference links
- Keep consistent capitalization style for headings
```
content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md
```
> Use a consistent style of URLs and headings in /kubernetes-objects.md

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
```
content/en/docs/reference/access-authn-authz/service-accounts-admin.md
```
Preview: https://deploy-preview-37844--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/service-accounts-admin/
> Fix typos in /service-accounts-admin.md

- content/en/docs/concepts/configuration/secret.md
This change wraps up the work done in the following PRs, which added create and edit steps for Secrets to relevant task pages:
* #35383 and #35384
* #34855 
* #34853 
This PR removes edit steps from the main Secret concept and redirects to the relevant task pages. Additionally, it cleans up the links in the Create Secret section to flow better and be more succinct.
/sig docs
/language en
> Remove edit steps from concept page

- content/pt-br/docs/reference/access-authn-authz/authorization.md
This PR translates the 'content/en/docs/reference/access-authn-authz/authorization.md' page to PT-BR. 
Some links might be broken given the referenced pages have not been translated yet. For that matter: should the link be kept to the 'EN' doc until the translated links are available ? 
Thanks!
> Adding the translation to brazilian portuguese for authorization

- content/en/docs/concepts/services-networking/service-traffic-policy.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Update feature gate references for ServiceInternalTrafficPolicy.
Docs added when the feature went to Beta seems sufficient, only references to the feature gate need updating.   
https://github.com/kubernetes/enhancements/issues/2086
> KEP-2086: update docs for ServiceInternalTrafficPolicy

- content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
Provide a consistent style, including:
- punctuations
- text spelling
```
content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
```
Preview: https://deploy-preview-37951--kubernetes-io-main-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
> Provide a consistent style in setup-ha-etcd-with-kubeadm.md

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/labels-annotations-taints/_index.md
Mark JobTrackingWithFinalizers as stable.
Mark job-tracking annotation as deprecated.
Add alculquicondor to reviewers.
> Graduate JobTrackingWithFinalizers to stable

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/concepts/workloads/pods/disruptions.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/job/pod-failure-policy.md
> Promote "Retriable and non-retriable pod failures for Jobs" to Beta

- content/en/docs/concepts/overview/working-with-objects/namespaces.md
Added hyperlink for persistentVolumes in section [Not all objects are in a namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#not-all-objects-are-in-a-namespace) in the [Namespaces](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/) page.
Fixes #37890
> added hyperlink for persistentVolumes in Namespaces page

- content/en/blog/_posts/2022-10-18-kubernetes-1.26-deprecations-and-removals.md
Fix two Markdown errors in blog post [Kubernetes Removals, Deprecations, and Major Changes in 1.26](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/).
Preview: https://deploy-preview-37964--kubernetes-io-main-staging.netlify.app/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/
> Blog post: fix markdown links

- content/en/docs/concepts/workloads/controllers/cron-jobs.md
Fix some typos in 
```
content/en/docs/concepts/workloads/controllers/cron-jobs.md
```
Preview: https://deploy-preview-37957--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/cron-jobs
> Fix typos in cron-jobs.md

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Clarifying that the feature is disabled in 1.23 and 1.24, even though it's still a beta feature.
> JobTrackingWithFinalizers disabled in 1.23, 1.24

- content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
The current Cilium installation output is a bit outdated as it is of version "v1.10.0" while Cilium is currently in "v1.12.1".
This change updates it to be consistent with what users will see when they run the "cilium install" command after installing the latest version of Cilium as in the previous steps.
Signed-off-by: Divine Odazie <dodazie@gmail.com>
> Update Cilium's Installation Output

- content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
- content/en/docs/tasks/job/fine-parallel-processing-work-queue.md
- content/en/docs/tasks/job/indexed-parallel-processing-static.md
No need to poll: there's a subcommand for that.
Use `kubectl wait` rather than asking the reader to wait for a bit then check.
> Use kubectl to wait for Jobs to succeed

- content/en/docs/tasks/administer-cluster/certificates.md
Adding links of easyrsa, openssl and cfssl in [generate certificates manually](https://kubernetes.io/docs/tasks/administer-cluster/certificates/) for better user experience and more information regarding the same.
/sig docs
> adding links to easy-rsa, cfssl and openssl in certificates.md

- content/it/partners/_index.html
Fixed the broken link on the [partners page](https://kubernetes.io/it/partners/#kcsp) by resyncing with en, de, ko, and zh-cn.
Preview: https://deploy-preview-34960--kubernetes-io-main-staging.netlify.app/it/partners/
> [it] resync /partners/_index.html

- content/en/docs/concepts/services-networking/endpoint-slices.md
- add links to API references
- tweak initial text
> Improve EndpointSlice concept

- content/en/examples/application/deployment-scale.yaml
following examples https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/#scaling-the-application-by-increasing-the-replica-count If you update replicas from 2 to 4 using the last deployment yaml, nginx version was 1.16.1, so 2 containers were already created and 2 new ones (that's why the table referenced as "The output is similar to this" shows AGE as 25s and 2m). If this deployment has nginx version 1.14.2, all containers will be recreated instead of just adding 2, so it can be confusing for the newcomers
> updated nginx version to follow examples correctly

- data/canonical-tags/architecture.yaml
- data/canonical-tags/community.yaml
- data/canonical-tags/core-object.yaml
- data/canonical-tags/extension.yaml
- data/canonical-tags/fundamental.yaml
- data/canonical-tags/networking.yaml
- data/canonical-tags/operation.yaml
- data/canonical-tags/security.yaml
- data/canonical-tags/storage.yaml
- data/canonical-tags/tool.yaml
- data/canonical-tags/user-type.yaml
- data/canonical-tags/workload.yaml
- data/i18n/en/en.toml
- layouts/docs/glossary.html
* First attempt at localizing glossary tag display names.
* Kept the original YAML files for canonical tags to serve as a template, as it is the easiest way to iterate over terms in a Hugo template.
* Added new keys to the original YAML files for canonical tags, indicating under which keys in the translations the localized terms can be found.
* Changed the template in `layout/docs/glossary.html` to get localized terms based on the new keys in the YAML files for canonical tags.
* Is it acceptable to sort by the new `.nameKey` field?
This page originally had alphabetical order sorting. Some characteristics of having the tags be sorted on this field include the original order being maintained, as well as keeping the same ordering regardless of localization.
* Should the original names and …
> Localization for glossary tag display names

- content/en/docs/concepts/workloads/pods/ephemeral-containers.md
- content/en/docs/reference/glossary/ephemeral-container.md
- content/en/docs/reference/glossary/static-pod.md
- content/en/docs/tasks/configure-pod-container/static-pod.md
updated docs regarding ephemeral pods not being supported by static pods kubernetes/kubernetes#113935
> Document that static pods can't have ephemeral containers

- content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
- Fix an indentation
- Modify some typos
```
content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
```
Preview: https://deploy-preview-37987--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/
> Fix indentation and typos in kubelet-tls-bootstrapping.md

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/configure-pod-container/security-context.md
`DelegateFSGroupToCSIDriver` is graduating to GA in 1.26.
Enhancement: https://github.com/kubernetes/enhancements/issues/2317
k/k PR: https://github.com/kubernetes/kubernetes/pull/113225
> DelegateFSGroupToCSIDriver is GA in 1.26

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Feature state should be changed for RetroactiveDefaultStorageClass since it graduated to beta in 1.26: https://github.com/kubernetes/kubernetes/pull/113329
> RetroactiveDefaultStorageClass is beta in 1.26

- content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
Based on the description in the previous section the example is supposed to:
> ... create a Secret that stores the username `admin` and the password `S!B\*d$zDsb=`
... but this was not the case. It was using the `devuser` username instead of `admin`. I have changed the example to be actually doing the task that it is supposed to be doing.
> Create Secret / Fixed the raw data example

- OWNERS_ALIASES
ref: https://github.com/kubernetes/steering/issues/260
Signed-off-by: Stephen Augustus <foo@auggie.dev>
/assign @parispittman @cpanato @mrbobbytables @cblecker 
cc: @kubernetes/steering-committee
> steering: Paris to Emeritus, add Carlos

- content/ja/examples/application/mysql/mysql-statefulset.yaml
en PR https://github.com/kubernetes/website/pull/36596/files
> [ja] use $HOSTNAME env variable instead of hostname command

- content/zh-cn/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md
Mainly fix this alignment issue:
in 
```
content/zh-cn/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md
```
Preview: https://deploy-preview-37984--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy/
> [zh] sync calico-network-policy.md

- static/_redirects
https://kubernetes.io/zh-cn/docs/setup/learning-environment/, align with EN version
Before:
No redirect
After:
Will redirect to https://kubernetes.io/zh-cn/docs/tasks/tools/
> fix: zh-cn learning environment page redirect

- content/ja/docs/contribute/_index.md
Since the "participating" in current path does not seem to exist, modified it to "participate".
I linked to the Japanese page, but there were some places in contribute/_index.md where the links were to the English version of the page.
I changed all the links to the Japanese version for the consistency.
How do you think?
> [ja]Fix an invalid link in contribute/_index.md

- content/en/docs/concepts/services-networking/dns-pod-service.md
A debugging rabbit hole lead me to digging around kublet's behavior regarding certain DNS Policies.
This commit updates some potentially misleading wordings to more correctly convey kubelet's behavior which was discovered after some rabbit hole debugging of DNS Policies.
The ClusterFirst policy documentation would imply that the resolve.conf of a Pod would contain a fallback to the Node's nameserver. This is not the cause, [kubelet explicitly mentions](https://github.com/kubernetes/kubernetes/blob/4276ed36282405d026d8072e0ebed4f1da49070d/pkg/kubelet/network/dns/dns.go#L403-L407) that the fallback is handled by whatever system is running kube-dns or coredns which dramatically changes the behavior of the system when the cluster's DNS is unavailable.
The ClusterFirstWithHostNet policy is …
> Correct misleading wording in Pod DNS Policies

- content/en/docs/tasks/administer-cluster/encrypt-data.md
* Add a simple best practice to manually verify that the key used in etcd and the key stored on disk are indeed the same.
Fixes https://github.com/kubernetes/website/issues/37651
> Verify key name in API Server and in etcd

- content/zh-cn/docs/concepts/storage/volume-snapshots.md
Sync with en and clean up differences found by `./scripts/lsync.sh`
```
content/zh-cn/docs/concepts/storage/volume-snapshots.md
```
Preview: https://deploy-preview-37970--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/volume-snapshots/
> [zh] sync /storage/volume-snapshots.md

- content/hi/docs/reference/glossary/limitrange.md
Signed-off-by: Chirayu Kapoor <dev.csociety@gmail.com>
Localized the content of `content/en/docs/reference/glossary/limitrange.md` into Hindi language in the file `content/hi/docs/reference/glossary/limitrange.md`
Fixes https://github.com/kubernetes/website/issues/37856 and https://github.com/kubernetes/website/issues/35600
> [hi] localize content/en/docs/reference/glossary/limitrange.md

- content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md
- content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
- content/en/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
The long console output cannot be display in current [version](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/#verify-the-secret).
```
NAME                  TYPE                                  DATA  ...
db-user-pass          Opaque                                2     ...
```
Change it to shorter version:
```
NAME              TYPE       DATA      AGE
db-user-pass      Opaque     2         51s
```
And sync footer format for three related files.
Preview: https://deploy-preview-37864--kubernetes-io-main-staging.netlify.app/docs/tasks/configmap-secret/managing-secret-using-kubectl/
> Tweak tasks/configmap-secret

- content/en/docs/tasks/configure-pod-container/configure-service-account.md
1. Run `prettier --w`
2. Tweak long lines manually
```
content/en/docs/tasks/configure-pod-container/configure-service-account.md
```
Preview: https://deploy-preview-37847--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/configure-service-account/
> Tweak line wrappings in /configure-service-account.md

- content/en/blog/_posts/2022-05-27-maxunavailable-for-statefulset.md
Absolute numbers for disruption budgets are calculated from percentages by rounding up, not down. As confirmed here: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#rounding-logic-when-specifying-percentages
> Fix incorrect information on disruption budgets

- content/en/docs/setup/_index.md
Added glossary tooltip for `kube-apiserver` and `kube-proxy` in [Getting started](https://kubernetes.io/docs/setup/) page.
Fixes #37948 , #37949
> Added glossary tooltip to kube-apiserver and kube-prox

- content/en/docs/concepts/workloads/controllers/job.md
Add a note to document changes in https://github.com/kubernetes/kubernetes/pull/113860
> Document for "Wait for Pods to finish before considering Failed in Job"

- OWNERS_ALIASES
- content/en/releases/release-managers.md
Part of https://github.com/kubernetes/sig-release/issues/2099.
Signed-off-by: Stephen Augustus <foo@auggie.dev>
/assign @saschagrunert @cpanato @puerco
cc: @kubernetes/sig-release-leads @jeremyrickard @Verolop
> sig-release: Promote Verónica (Tech Lead) and Jeremy (Chair)

- content/zh-cn/blog/_posts/2018-08-29-kubernetes-testing-ci-automating-contributor-experience.md
error display:
Incorrect spaces maybe caused by `tab` spaces.
page: https://kubernetes.io/zh-cn/blog/2019/08/29/the-machines-can-do-the-work-a-story-of-kubernetes-testing-ci-and-automating-the-contributor-experience/
preview page: https://deploy-preview-38061--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2019/08/29/the-machines-can-do-the-work-a-story-of-kubernetes-testing-ci-and-automating-the-contributor-experience/
> [zh-cn] Fix incorrect spaces causing the list to display an error in blog

- content/en/docs/reference/instrumentation/metrics.md
Closes #37922
- Revert PR that bumped the document (https://kubernetes.io/docs/reference/instrumentation/metrics/) 
/assign @sftim
> Revert PR that bumped the instrumentation/metrics/ documents metrics to`v1.26`

- content/en/docs/reference/kubectl/cheatsheet.md
Fix some types and keep heading pattern consistent.
```
content/en/docs/reference/kubectl/cheatsheet.md
```
Preview: https://deploy-preview-38013--kubernetes-io-main-staging.netlify.app/docs/reference/kubectl/cheatsheet/
> Fix typos and consistency in cheatsheet.md

- content/en/docs/reference/access-authn-authz/rbac.md
Added caution note Add caution note about rules field override in aggregated ClusterRoles. 
rel #34816 
The text that was proposed by @shannonxtreme perfectly fits as I guess.
> feat: Add caution note about rules field override

- content/en/docs/concepts/workloads/controllers/deployment.md
As I've previously understood it:
- A Deployment is an abstraction that creates and scales ReplicaSets
- ReplicaSets manage replica pods
The docs currently appear to be saying that a Deployment creates replica pods. If my understanding is correct, I'd make the role of ReplicaSet as the middleman a bit more explicit in the docs.
> Clarify that a Deployment doesn't manage Pods

- content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
An image on the [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) page looks not good enough. 
Have a try to replace it with mermaid that may be easy to read, change, and localize.
Preview: https://deploy-preview-38086--kubernetes-io-main-staging.netlify.app/docs/tasks/run-application/horizontal-pod-autoscale/
> Replace an image with mermaid

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/configure-pod-container/create-hostprocess-pod.md
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
> Updates for WindowsHostProcessContainers going to stable

- content/en/docs/concepts/scheduling-eviction/_index.md
- content/en/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/examples/pods/pod-with-scheduling-gates.yaml
- content/en/examples/pods/pod-without-scheduling-gates.yaml
Part of https://github.com/kubernetes/enhancements/issues/3521
> Doc for Alpha feature PodSchedulingReadiness

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Signed-off-by: Harshal Patil <harpatil@redhat.com>
Add EventedPLEG to FeatureGates doc. 
Corresponding PR - https://github.com/kubernetes/kubernetes/pull/111384
Enhancement - https://github.com/kubernetes/enhancements/issues/3386
> Add EventedPLEG to FeatureGates doc

- content/en/docs/reference/access-authn-authz/authentication.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> Add doc about how to get self subject attributes

- content/en/docs/concepts/policy/resource-quotas.md
Fixes: #https://github.com/kubernetes/kubernetes/issues/110956
This PR document `ResourceQuota` behaviour on `BestEffort` Pod a namespace.
/language en
> Document special case of ResourceQuota for cpu and memory

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/topology-manager.md
Enhancement link: https://github.com/kubernetes/enhancements/issues/3545
Implementation link: https://github.com/kubernetes/kubernetes/pull/112914
> topologymanager: document topology manager policy options

- content/en/docs/concepts/workloads/pods/disruptions.md
- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
> Extend documentation on PodGC focusing on PodDisruptionConditions enabled

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Add document for Provision volumes from cross namespace data sources
■KEP
Please see [CrossNamespaceVolumeDataSource](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3294-provision-volumes-from-cross-namespace-snapshots)
■API Change (Merge)
https://github.com/kubernetes/kubernetes/pull/113186
■Controller (Under Review)
https://github.com/kubernetes-csi/external-provisioner/pull/805
> Add document for Provision volumes from cross namespace data sources

- content/en/blog/_posts/2021-04-06-PodSecurityPolicy-Past-Present-and-Future.md
Fix: #36199
**Note**: Once the changes get approved, the localization team has to perform the task to update the blog in their respective language as well.
> Revise PSP deprecation blog article to note that PSP is now removed

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/labels-annotations-taints/_index.md
this label is added from feature `LegacyServiceAccountTokenTracking`
ref: https://github.com/kubernetes/enhancements/issues/2799
> update doc of KEP-2799

- SECURITY_CONTACTS
Adding all current chairs and tech leads from SIG Docs to the SECURITY_CONTACTS file, and removing Jim as he prepares to step into an Emeritus role.
This general update will be added to our list of tasks for onboarding/offboarding chairs and TLs for SIG Docs overall (cc. @a-mccarthy).
> Add all chairs/TLs to SECURITY_CONTACTS

- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
This PR added the shell (```shell) instead of only triple backticks(```)  for the commands `kubectl get csr myuser -o jsonpath='{.status.certificate}'| base64 -d > myuser.crt` mention under the[ Get the certificate](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#get-the-certificate) because we can't able to move the code snippet to see the full command with triple backticks.
Current (```):
After adding shell(```shell)
> Append triple backticks with shell for code snippet

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
Updating feature gates doc for KMSv2: https://github.com/kubernetes/enhancements/issues/3299. `KMSv2` feature gate was introduced in Kubernetes v1.25 and is still Alpha as of v1.26.
> Update docs for KMSv2 Alpha

- content/en/docs/tasks/configure-pod-container/configure-service-account.md
This PR fixed the link for token projection in the [Configure Service Accounts for Pods](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) task.
Fixes:#38151
> Improvement: Corrected the link for token projection.

- content/en/blog/_posts/2022-10-18-kubernetes-1.26-deprecations-and-removals.md
- Fix typos
- Use relative links
```
content/en/blog/_posts/2022-10-18-kubernetes-1.26-deprecations-and-removals.md
```
> Fix typos in 2022-10-18-kubernetes-1.26-deprecations-and-removals

- content/zh-cn/docs/concepts/cluster-administration/system-logs.md
- Clear difference found by `./scripts/lsync.sh`
- Add anchors
```
content/zh-cn/docs/concepts/cluster-administration/system-logs.md
```
Preview: https://deploy-preview-38154--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/system-logs/
> [zh] sync cluster-administration/system-logs.md

- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tutorials/stateful-application/basic-stateful-set.md
Add documentation for StatefulSetSlice feature targeting Kubernetes alpha in 1.26
* KEP-3335 Enhancement: https://github.com/kubernetes/enhancements/pull/3336
* KEP-3335 Implementation: https://github.com/kubernetes/kubernetes/pull/112744
> Add initial documentation for StatefulSetSlice feature

- content/en/docs/reference/kubectl/_index.md
- content/en/docs/reference/kubectl/cheatsheet.md
- content/en/docs/reference/kubectl/kubectl.md
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1440
Kubernetes PRs:
- https://github.com/kubernetes/kubernetes/pull/113819
- https://github.com/kubernetes/kubernetes/pull/110007
- https://github.com/kubernetes/kubernetes/pull/110766
- https://github.com/kubernetes/kubernetes/pull/111855
> Events beta docs update

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/en/docs/tasks/tools/install-kubectl-linux.md
Fixes: #38053 
This PR modify path from `/usr` to `/etc` while manually managed key for apt repositories
> Modify manually managed  key for apt repositories

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
Fixes #31769
I don't think there was anything wrong with the existing wording, but it was confusing. It was not clear whether it was referring to the mentions of the field or the items within the field.
Also replace @bsalamat with @alculquicondor, as a SIG Scheduling TL
> Clarify node affinity API

- content/en/blog/_posts/2022-05-03-kubernetes-release-1.24.md
- content/en/docs/concepts/services-networking/cluster-ip-allocation.md
- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
The ServiceIPStaticSubrange feature gate, that allows to change the IP allocation algorithm used for Service.ClusterIPs, is graduating to GA.
> graduate ServiceIPStaticSubrange to GA

- content/en/docs/reference/instrumentation/node-metrics.md
- content/en/docs/reference/node/_index.md
- content/en/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md
Split https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/#summary-api-source away from https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/ and into a new page within the reference section.
Also, reinstate some details about `PodAndContainerStatsFromCRI`.
/sig node
/sig instrumentation
/language en
/label refactor
> Split out kubelet instrumentation details into reference page

- content/en/docs/concepts/cluster-administration/flow-control.md
This PR updates the description of API Priority and Fairness to track the recent introduction (to first appear in release 1.26) of concurrency borrowing between priority levels.
> Update APF doc to track introduction of borrowing

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
Adding a link to the KMS docs for KMSv2 feature gate.
ref: https://github.com/kubernetes/website/pull/38145#discussion_r1034704499
/sig auth
/cc @enj @ritazh
> Update docs for KMSv2 Alpha (part 2) - add reference links

- content/zh-cn/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md
Sync with en.
```
content/zh-cn/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md
```
Preview: https://deploy-preview-38178--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/
> [zh] sync resource-metrics-pipeline.md

- content/en/docs/concepts/architecture/leases.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Signed-off-by: Andrew Sy Kim <andrewsy@google.com>
Update feature gate reference for APIServerIdentity. Currently on the fence about whether we want more comprehensive documentation for this feature. In it's current state it is mainly going to be used for internal optimizations (i.e. StorageVersion API) and likely won't see too much use from users.
> kep-1965: update doc references for APIServerIdentity

- content/en/docs/tasks/job/job-with-pod-to-pod-communication.md
> Fix format by removing erroneous ticks

- content/en/docs/tasks/job/job-with-pod-to-pod-communication.md
https://github.com/kubernetes/website/pull/37771 was just merged with an extra "```" line included below a shell block, which results in some slightly funky formatting at the bottom of the page (a shell/code block with a "Note" template inside of it). 
See: https://kubernetes.io/docs/tasks/job/job-with-pod-to-pod-communication/ (scroll to the bottom)
This PR removes the extra "```" and fixes the formatting. Confirmed this by running `make container-serve` locally and verifying the formatting in my browser.
> Fix shell block on Job task page

- content/ja/docs/reference/tools.md
Fix a link that causes 404 now: https://kubernetes.io/ja/docs/reference/tools/
```
content/ja/docs/reference/tools.md
```
Preview: https://deploy-preview-38076--kubernetes-io-main-staging.netlify.app/ja/docs/reference/tools/
> [ja] fix a link in tools.md

- content/ja/docs/concepts/scheduling-eviction/pod-overhead.md
Sync with en.
```
content/ja/docs/concepts/scheduling-eviction/pod-overhead.md
```
Preview: https://deploy-preview-38077--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/scheduling-eviction/pod-overhead/
> [ja] sync pod-overhead.md

- content/en/docs/reference/access-authn-authz/admission-controllers.md
- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Adding doc for CEL in Admission Control on KEP: https://github.com/kubernetes/enhancements/issues/3488
Co-author: @jiahuif @DangerOnTheRanger
> Documentation for CEL in Admission Control

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/concepts/storage/storage-classes.md
- content/en/docs/concepts/storage/volumes.md
- content/en/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
- content/en/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
we have removed glusterfs in-tree driver in this release (v1.26) via https://github.com/kubernetes/kubernetes/pull/112749 .
This PR remove the references from the docs.
> remove glusterfs references from the docs 

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
issue #37316 identifies typo in Features gate (removed) for RootCAConfigMap (GA), the feature gate was removed in v1.22 but this was mistakenly typed as 1.12
> Fix typo in Feature Gates (removed)

- data/releases/schedule.yaml
This PR updates the target date for the December patch releases to Thursday, December 8, 2022.
The idea is to delay the December patch releases for one day so that we have enough time to incorporate the upcoming Go security patch releases.
Slack discussion: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1669990966899019
/assign @saschagrunert @cpanato @puerco @jeremyrickard 
> Update target date for December patch releases

- content/en/blog/_posts/2022-12-05-forensic-container-checkpointing/index.md
This adds a blog article how to use forensic container checkpointing which was merged in Kubernetes v1.25.
https://github.com/kubernetes/enhancements/issues/2008
> Add blog post about forensic container checkpointing

- content/zh-cn/docs/concepts/containers/runtime-class.md
- Sync with en
- Fix some typos
```
content/zh-cn/docs/concepts/containers/runtime-class.md
```
Preview: https://deploy-preview-38214--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/containers/runtime-class/
> [zh] sync /containers/runtime-class.md

- content/ko/docs/tutorials/security/apparmor.md
This updates example `kubectl exec` commands to avoid warnings. It is a follow-up change to kubernetes#37221.
Running `kubectl exec <pod_name> <command>` is deprecated:
```
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead
```
It should be: `kubectl exec <pod_name> -- <command>`
> [ko] Update deprecated kubectl command in apparmor doc

- content/en/releases/patch-releases.md
This is a follow-up on #38233 -- I updated `data/releases/schedule.yaml`, but I forgot to update the patch releases page (`content/en/releases/patch-releases.md`).
/assign @cpanato @saschagrunert @ameukam 
> Update target date for December in patch releases document

- Makefile
- cloudbuild.yaml
For users of m1, the current `make container-serve` is very slow on newer Macs with arm64 architectures. Let's build a multi-arch image using `docker buildx` in a new target. 
We should also switch the cloudbuild.yaml to the new target as well. 
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Build and push multi-arch images using docker buildx

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
Fixes a misspelling (partilar -> particular) in concepts/extend-kubernetes/compute-storage-net/device-plugins.md
> [en] fix spelling error in Device Plugins concept page

- cloudbuild.yaml
`buildx` is not available in the environment, let's just go back to the older make target and we can try this again after 1.26 release is over
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Switch back to older push target for hugo

- content/en/docs/concepts/architecture/leases.md
Signed-off-by: Andrew Sy Kim <andrewsy@google.com>
Follow-up to https://github.com/kubernetes/website/pull/37921#discussion_r1036046029
> leases: add more details on API Server Identity

- content/zh-cn/docs/reference/glossary/dynamic-volume-provisioning.md
Mainly modified from `供应` to `制备` for `provisioning`
```
content/zh-cn/docs/reference/glossary/dynamic-volume-provisioning.md
```
> [zh] updated /glossary/dynamic-volume-provisioning.md

- content/en/docs/concepts/services-networking/service.md
This PR fixed the link of  `Virtual IPs and Service Proxies` under the[ Service](https://kubernetes.io/docs/concepts/services-networking/service/) concept page.
Fixes #38187
> Fixed the link of Virtual IPs and Service Proxies.

- content/en/docs/tasks/administer-cluster/encrypt-data.md
- content/en/docs/tasks/administer-cluster/kms-provider.md
kms: updates website to document --encryption-provider-config-automatic-reload api server flag and healthcheck endpoint behavior
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
fixes: https://github.com/kubernetes/kubernetes/issues/113631
> kms: updates website to document encryption config hot reload changes

- content/zh-cn/docs/reference/glossary/taint.md
Find some typos in:
```
content/zh-cn/docs/reference/glossary/taint.md
```
> [zh] Fix typo in /glossary/taint.md

- content/en/releases/release-managers.md
Follow up on https://github.com/kubernetes/release/pull/2773
We now reflect the latest changes to the SIG Release OWNERS_ALIASES: https://github.com/kubernetes/release/blob/3ee765b9f1ee1a56fc72a775d0253e25abcec8ce/OWNERS_ALIASES#L11-L25
/sig release
cc @kubernetes/release-managers @kubernetes/sig-release-leads
> Update Release Manager (Associates)

- content/en/docs/reference/kubectl/kubectl.md
re: https://github.com/kubernetes/enhancements/issues/3515
this enhancement changes the data backing for `kubectl explain` to use OpenAPIv3 instead of v2 as earlier. It is toggled by en environment variable `KUBECTL_EXPLAIN_OPENAPIV3=true`.
> document kubectl explain openapi v3

- content/en/docs/reference/networking/service-protocols.md
- content/en/docs/reference/networking/virtual-ips.md
- content/en/docs/tasks/debug/debug-application/debug-service.md
While belatedly looking at #36675 I saw that we still talk about the userspace proxy in a bunch of places, but it's gone in 1.26 (https://github.com/kubernetes/kubernetes/pull/112133).
I didn't remove `static/images/docs/services-userspace-overview.{svg,png}` because it's referenced by the translations of `service.md` too.
/cc @sftim
> Remove references to userspace proxy

- content/en/examples/secret/serviceaccount/mysecretname.yaml
> The provided example is invalid because in the example, `annotations:` is a sequence.
> 
> Annotations are mappings, as explained [in the documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set).
> 
> A reviewer can check for themselves that the provided example doesn't work (if they try to `kubectl apply -f` the provided YAML) while the fixed one does.
> Annotations are mappings, not sequences

- data/releases/schedule.yaml
This PR adds 1.26 to the releases schedule for the 1.26.0 release. Following instruction [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-releases-page-the-week-before-the-release)
/milestone 1.26
/cc @reylejano @divya-mohan0209 @onlydole
>  Add release schedule for 1.26 release

- config.toml
Updated config.toml for release v1.26
Versions were updated based on [latest patch releases](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)
Following the instruction of handbook [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-the-site-configuration-files-for-previous-releases)
/hold until 1.26 release day
cc: @reylejano  @onlydole @divya-mohan0209
> chore:  update release-1.25 config.toml for release 1.26

- config.toml
Updated config.toml for release v1.26
Versions were updated based on [latest patch releases](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)
Following the instruction of handbook [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-the-site-configuration-files-for-previous-releases)
/hold until 1.26 release day
cc: @reylejano  @onlydole @divya-mohan0209
> chore: update release-1.24 config.toml for release 1.26

- config.toml
Updated config.toml for release v1.26
Versions were updated based on [latest patch releases](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)
Following the instruction of handbook [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-the-site-configuration-files-for-previous-releases)
/hold until 1.26 release day
cc: @reylejano  @onlydole @divya-mohan0209
> Update release 1.23 config.toml for release 1.26

- config.toml
Updated config.toml for release v1.26
Versions were updated based on [latest patch releases](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)
Following the instruction of handbook [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-the-site-configuration-files-for-previous-releases)
/hold until 1.26 release day
cc: @reylejano  @onlydole @divya-mohan0209
> chore: update-1.22 config.tml for release 1.26

- content/en/docs/reference/using-api/deprecation-guide.md
This adds info about APIs shipped in 1.26 and updates language about the 1.25 and 1.26 releases
/hold for 1.26.0 release
> Update API deprecation page for 1.26

- content/en/blog/_posts/2022-12-12-kubernetes-release-artifact-signing.md
Adding the placeholder PR for the feature blog post.
Refers to https://github.com/kubernetes/enhancements/issues/3031
> Add blog post about binary artifact signing

- content/en/docs/concepts/services-networking/ingress-controllers.md
Adds a closing parenthesis in the ingress controllers page
Reference:
https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/#using-multiple-ingress-controllers
> [en] add missing closing parenthesis in ingress controllers page

- content/en/blog/_posts/2022-12-15-dynamic-resource-allocation-alpha/index.md
~Assuming that the feature goes into 1.26 as alpha, this will become a blog post about it.~
https://github.com/kubernetes/enhancements/issues/3063
> blog: add dynamic resource allocation feature blog post

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
Replace the current multi-step extraction of the `kubeconfig` field from the `cluster-info` ConfigMap with the use of `kubectl -o jsonpath`.
Fixes #38402
> [en] Update ConfigMap data extraction to use jsonpath instead of grep/sed

- content/ja/docs/tasks/debug/debug-application/_index.md
fixes #37349
Translate an overview part in https://kubernetes.io/ja/docs/tasks/debug/debug-application/.
By translating the contents of `content/ja/docs/tasks/debug/debug-application/_index.md`, this part will be in Japanese.
Preview:
https://deploy-preview-38275--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/debug/debug-application/
> [ja] Translate content/ja/docs/tasks/debug/debug-application/_index.md into Japanese

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
To ensure that this page is rendered correctly on the Kubernetes website, the caution tag needs to be closed.
This was missed during the doc write up and review process of https://github.com/kubernetes/website/pull/37273.
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>
> device-mgr-doc: Add caution closing tag
