kubernetes/website

- content/ja/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Add description of startupProbe successThreshold limitation corresponding to the English page.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
close #38170
Preview: https://deploy-preview-38171--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
> [ja] add startupProbe successThreshold limitation

- content/en/docs/tasks/tools/install-kubectl-windows.md
Make the verification command cleaner by using only PS cmdlets. certutil.exe returns 3 lines which need to be split to the hash, as opposed to `Get-FileHash` that returns an object with `.Hash`
Fixes #30833
> improvement: kubectl install on windows verify command

- content/en/docs/concepts/security/multi-tenancy.md
EDITED: Fixes a <strike>misplaced and</strike> miss-formatted quotation mark in the multi-tenancy page. 
Reference: https://kubernetes.io/docs/concepts/security/multi-tenancy/#multiple-customers
> [en] fix quotation mark in multi-tenancy page

- content/en/blog/_posts/2022-12-27-cpumanager-goes-GA.md
Assuming that the feature goes into 1.26 as GA, this will become a blog post about it.
Enhancement: https://github.com/kubernetes/enhancements/issues/3570
Signed-off-by: Francesco Romani <fromani@redhat.com>
> blog: node: cpumanager goes GA

- content/en/blog/_posts/2023-01-02-cross-namespace-data-sources-alpha.md
Add blog for Provision volumes from cross namespace data sources
■KEP
Please see [CrossNamespaceVolumeDataSource](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3294-provision-volumes-from-cross-namespace-snapshots)
■API Change (Merge)
https://github.com/kubernetes/kubernetes/pull/113186
■Controller (Under Review)
https://github.com/kubernetes-csi/external-provisioner/pull/805
> Add blog post for Provision volumes from cross namespace data sources

- content/en/blog/_posts/2022-12-20-validating-admission-policies-alpha/index.md
PR for feature blog on KEP: https://github.com/kubernetes/enhancements/issues/3488
> Add feature blog for CEL for Admission Control

- content/en/blog/_posts/2022-12-23-fsgroup-on-mount.md
Blog post for https://github.com/kubernetes/enhancements/issues/2317.
> Add blog post for FSGroup on mount

- content/pt-br/docs/reference/glossary/code-contributor.md
Added translation for portuguese of the glossary term code-contributor.
> Add pt-br/docs/reference/glossary/code-contributor.md

- content/ja/docs/setup/best-practices/node-conformance.md
Sync with en.
```
content/ja/docs/setup/best-practices/node-conformance.md
```
Preview: https://deploy-preview-38395--kubernetes-io-main-staging.netlify.app/ja/docs/setup/best-practices/node-conformance/
> [ja] sync node-conformance.md

- content/en/docs/concepts/policy/pid-limiting.md
This PR removed the Feature Gate reference from `SupportNodePidsLimit` and `SupportPodPidsLimit`, as these are gratuated and removed.
Fixes #38118
> Removed Reference from the removed Feature Gates.

- content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
Here is the current doc:
However, the output of `bash-completion` has been updated:
https://github.com/Homebrew/homebrew-core/blob/a844122643dcf8c2e74144bfb3dc18844db4e458/Formula/bash-completion%402.rb#L49-L54
So, the `export` is unnecessary( moved since [this commit](https://github.com/Homebrew/homebrew-core/commit/d89d20efe3432a90212ef909db46bcd36d554323) in Homebrew Formula)
https://github.com/Homebrew/homebrew-core/blob/a844122643dcf8c2e74144bfb3dc18844db4e458/Formula/bash-completion%402.rb#L52
As you can see, the path of `etc` is `#{etc}`, not always be `/usr/local/etc/`.
And here is the information of **how homebrew generate #{etc}**:
(link: https://docs.brew.sh/Formula-Cookbook#variables-for-directory-locations)
> [en] Fix homebrew prefix error in bash-completion of kubectl

- content/zh-cn/docs/concepts/workloads/pods/disruptions.md
Sync with en.
```
```
Preview: https://deploy-preview-38450--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/disruptions/
> [zh] sync /pods/disruptions.md

- data/i18n/pt/pt-br.toml
* Add translations for glossary tag display names in Brazilian Portuguese, as enabled through #37966.
/language pt
/cc @edsoncelio @MrErlison @rikatz
> [pt-br] Translate glossary tag display names

- content/en/docs/tasks/administer-cluster/enable-disable-api.md
On [https://kubernetes.io/docs/tasks/administer-cluster/enable-disable-api/](https://kubernetes.io/docs/tasks/administer-cluster/enable-disable-api/) there is a typo at the line 
"For example, **to turning off** all API versions except v1"
This above typo has been fixed to
"For example, **to turn off** all API versions except v1"
Fixes [#38502 ](https://github.com/kubernetes/website/issues/38502)
> Fixed typo in documentation

- content/en/docs/tasks/tools/included/optional-kubectl-configs-fish.md
Spent some time wondering why the recommended command did not worked and found https://github.com/kubernetes/website/pull/33972.
Suggestions have been applied but I took the liberty to put the note at the top of the page.
Preview link: https://deploy-preview-38302--kubernetes-io-main-staging.netlify.app/docs/tasks/tools/included/optional-kubectl-configs-fish/
Reference: https://github.com/kubernetes/kubectl/issues/1189
> add version support to `fish` auto-completion

- content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
/kind cleanup
Documentation may be improved. For now I simply fixed factual issue as config based configuration is recommended and feature gate mentioned was already removed.
/sig node
/sig auth
References:
- https://github.com/kubernetes/kubernetes/pull/96532 (feature gate removed)
- https://github.com/kubernetes/kubernetes/pull/63912 (flag moved to kubelet config)
- https://github.com/kubernetes/kubernetes/pull/62352 (flag serverTLSBootstrap is introduced)
> fix documentation for RotateKubeletClientCertificate

- content/zh-cn/blog/_posts/2022-10-18-kubernetes-1.26-deprecations-and-removals.md
Added zh text to:
```
content/zh-cn/blog/_posts/2022-10-18-kubernetes-1.26-deprecations-and-removals.md
```
Preview: https://deploy-preview-38274--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/
> [zh] sync 2022-10-18-kubernetes-1.26-deprecations-and-removals.md

- content/zh-cn/docs/concepts/architecture/nodes.md
Sync with en.
```
```
Preview: https://deploy-preview-38370--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/nodes/
> [zh] sync /architecture/nodes.md

- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
there were some incorrect examples, more info here #38495
> Fix 38495 incorrect ValidationAdmissionPolicyBindings

- config.toml
The link in the 1.23 doc is updated to https://v1-25.docs.kubernetes.io/docs/home/supported-doc-versions/
#38457
> Broken link to v1.25 docs fixed for the branch release-1.23

- config.toml
The link in the 1.24 doc is updated to https://v1-25.docs.kubernetes.io/docs/home/supported-doc-versions/ 
#38512
> Broken link to v1.25 docs fixed for the branch release-1.24

- content/en/docs/concepts/workloads/controllers/cron-jobs.md
- content/en/docs/concepts/workloads/controllers/deployment.md
- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/concepts/workloads/controllers/replicaset.md
- content/en/docs/concepts/workloads/controllers/replicationcontroller.md
- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/concepts/workloads/pods/_index.md
@sftim - you suggested this in https://github.com/kubernetes/kubernetes/pull/114412#issuecomment-1352350183 - help me craft wording?  Once we are happy with words I will apply the same pattern to other types.
> Recommend DNS Labels for workload controller names

- content/pt-br/docs/reference/glossary/taint.md
This PR adds Portuguese translation to the glossary term taint.
Signed-off-by: Rodrigo V. Del Monte <rvdelmonte@gmail.com>
> Add pt-br/docs/reference/glossary/taint.md

- content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
Sync with en.
```
deleted:    content/zh-cn/docs/tasks/kubelet-credential-provider/kubelet-credential-provider.md
moved to:   content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
```
Not sure about two links at bottom, both are 404 now:
```
/docs/reference/config-api/kubelet-config.v1/
/docs/reference/config-api/kubelet-credentialprovider.v1/
```
> [zh] sync kubelet-credential-provider.md

- content/en/blog/_posts/2022-12-19-devicemanager-ga.md/index.md
The blog post about device manager GA published on Dec 19th has a broken URL (pointing to a PR of something else). This fixes it.
/cc @swatisehgal
> blog: fix KEP URL in 2022-12-19-devicemanager-ga.md

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Move volume expansion feature gates to removed feature gates list
The volume expansion feature gates were GAed in Kubernetes v1.24 and removed in 1.27.
- ExpandCSIVolumes
- ExpandInUsePersistentVolumes
- ExpandPersistentVolumes
Ref https://github.com/kubernetes/kubernetes/pull/113942
> Move volume expansion feature gates to removed feature gates list

- content/en/releases/patch-releases.md
- data/releases/eol.yaml
- data/releases/schedule.yaml
- Add December 2022 patch releases to `schedule.yaml` (and the patch release page)
- Propose tentative release dates for March and April 2023 patch releases
/assign @puerco @palnabarun @Verolop 
> Add December 2022 patch releases and tentative release dates for March and April 2023

- content/zh-cn/docs/setup/best-practices/certificates.md
Sync with en.
```
content/zh-cn/docs/setup/best-practices/certificates.md
```
Preview: https://deploy-preview-38537--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/best-practices/certificates/
> [zh] sync /best-practices/certificates.md

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
- content/en/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors.md
Looking at the online portmap doc, this seems to be
the recommended configuration for k8s + portmap
https://www.cni.dev/plugins/current/meta/portmap/
> Add externalSetMarkChain to portmap config

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
- Use "stored version" consistently, rather than "persisted version"
- Describe what happens in the general case of stored version != served version.
- Make an explicit distinction between (conceptually immutable on reads) persisted object and the served representation, rather to try and describe both in one go.
- Warn that differing schemas without a conversion webhook is not likely to end well.
/cc @sftim 
Fixes: #27534
> Improve CRD version conversion description

- config.toml
- layouts/partials/head.html
- Contributes to #35299
- This is take 2 of #37669
- Applies the same solution (hard-coded GA4 ID) as for all other older releases (from 1.21 to 1.24).
/cc @nate-double-u @sftim @reylejano @a-mccarthy
> Use Google Analytics 4 (GA4) site tag for v1.25

- content/en/docs/tasks/configure-pod-container/configure-volume-storage.md
By following [style guide](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/style/style-guide.md#separate-commands-from-output), changed those `shell` to `console`.
```
content/en/docs/tasks/configure-pod-container/configure-volume-storage.md
```
> Change shell to console for code snippet in configure-volume-storage.md

- content/en/docs/tasks/administer-cluster/encrypt-data.md
- remove some punctuations `.` `:` from headings
- add \``` to a command for easy copy and paste
- other minor changes
```
content/en/docs/tasks/administer-cluster/encrypt-data.md
```
> Fix punctuations in headings of encrypt-data.md

- content/en/docs/concepts/services-networking/service.md
Tencent Kubernetes Engine does not have an in-tree or in-project integration with the Service API, so we wouldn't document it.
This PR removes the third party documentation there. See issue #20232.
(in case anyone's wondering, the AWS integration is done using code that is part of the Kubernetes project)
> Remove details for out-of-tree Service integration (TKE)

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
This PR consists of two commits.
- The first commit replaces a reference to Go source code by a reference to the corresponding config API;
- The second commit wraps the long lines found in the kubeadm-certs page for ease of change tracking.
> Improve the kubeadm-certs page

- content/en/docs/setup/production-environment/container-runtimes.md
The steps mentioned under the topic _[Forwarding IPv4 and letting iptables see bridged traffic](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic)_ were not clear.
I have updated the steps to be more understandble and easy to follow.
Previously mentioned steps were suggesting it as an example even-though it should have been the exact steps to be followed in case the verification of modules and system variables fail.
Thank you.
> Updated the steps to verify the modules and system variables

- data/i18n/en/en.toml
Removed `release_complete` string as discussed in https://github.com/kubernetes/website/issues/36839
> fix: Remove release_complete string since it's unused

- content/en/docs/reference/_index.md
- content/en/docs/reference/config-api/kubeconfig.v1.md
The file added is generated using kubernetes-sigs/reference-docs/genref tool, with logics and configs improved by
https://github.com/kubernetes-sigs/reference-docs/pull/309 and https://github.com/kubernetes-sigs/reference-docs/pull/310.
related: #38478
> Add Config API reference for kubeconfig

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
- Fix a link
- Give a consistent alignment for order list prefixed with 3 spaces
```
content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
```
> Fix link and bullets in custom-resource-definition-versioning

- content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
Sync with en #37267 
```
content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
```
> [zh] sync custom-resource-definition-versioning.md

- content/hi/docs/reference/glossary/etcd.md
Signed-off-by: Amol Mote <amolmote201@gmail.com>
Fixes https://github.com/kubernetes/website/issues/35600 Localize content/en/docs/reference/glossary/etcd.md into content/hi/docs/reference/glossary/etcd.md
For Reviewers: These changes are already reviewed in another PR ( #36351)but due to some complications I am opening this new PR.
> [hi] Localize content/hi/docs/reference/glossary/etcd.md

- content/en/examples/application/php-apache.yaml
The php-apache.yaml file deploys a sample application which is used as part of the [HPA walkthrough guide](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/). This PR removes the `spec.replicas` count from the Deployment manifest because if this is set when HPA is enabled, when a change to the deployment manifest is applied Kubernetes will scale the current number of pods to the the value of `spec.replicas` in the deployment manifest. This could result in pods terminating, which could impact the performance of a scaled workload were `spec.replicas` is less than the HPA `spec.maxReplicas`.
More information can be found in the Kubernetes [documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-st …
> Removed spec.Replicas from example application deployment manifest for HPA scaling walkthrough

- content/zh-cn/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
Updated example of reading secret values from a file so that it doesn't base64 the contents in the file before kubectl reads it.
This is the same as the change made in English in #38375.
I have used Google Translate for the small translation change, I hope this is okay. Apologies in advance if it isn't accurate or if this isn't the recommended approach.
> Remove Base64'ing of file contents (Chinese)

- content/en/docs/concepts/services-networking/network-policies.md
- content/en/examples/examples_test.go
- content/en/examples/service/networking/networkpolicy-multiport-egress.yaml
closes: #38596 
The problem reported by the issue can be easily detected if the manifest is extracted to a standalone YAML file, which then can be validated using the example test cases.
This PR contains two commits. The first commit improves the network-policies.md file by splitting out an example into an out-of-band example file (bugs in it fixed and validated using `go test k8s.io/website/content/en/examples`). The second commit reformats the concept pages for long lines that are supposed to be wrapped when appropriate. No substantial changes are introduced in the second commit.
> Tweak network policies

- content/en/docs/reference/networking/virtual-ips.md
This adds some basic documentation about the kube-proxy iptables `syncPeriod` and `minSyncPeriod` config options, and how `MinimizeIPTablesRestore` in 1.26 changes that.
spun off from #37649 which got auto-closed when `dev-1.26` was deleted, but we wanted to change the focus of the documentation anyway, as discussed in https://github.com/kubernetes/website/pull/37649#discussion_r1043685474
/cc @sftim
> add kube-proxy iptables performance optimization notes

- content/ja/docs/concepts/workloads/pods/pod-lifecycle.md
Fixed content/ja/docs/concepts/workloads/pods/pod-lifecycle.md according to the English text, because it is outdated.
It was translated up to 1eef7424651bdc681711572e1042169faebe8e81 of content/en/docs/concepts/workloads/pods/pod-lifecycle.md.
Fixes #37394
> [ja] content/ja/docs/concepts/workloads/pods/pod-lifecycle.md to the latest

- content/en/docs/concepts/architecture/nodes.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1939A6OrOuzVNkJg9cq3OSCExQAZLqP0o%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2IPH8G8)
Fix: https://github.com/kubernetes/website/issues/38426
https://kubernetes.io/docs/concepts/architecture/nodes/#pod-priority-graceful-node-shutdown is in the wrong place: it should be part of the Graceful node shutdown heading, but it's actually under the Non-graceful node shutdown section.
> resolved node concept mixes up graceful and non graceful node shutdown

- content/ja/docs/tasks/debug/_index.md
fixes #37347
Update https://kubernetes.io/ja/docs/tasks/debug/ page in accordance with the following PR updates.
- https://github.com/kubernetes/website/pull/29847
- https://github.com/kubernetes/website/pull/31307
- https://github.com/kubernetes/website/pull/31875
Preview:
https://deploy-preview-38466--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/debug/
en:
https://kubernetes.io/docs/tasks/debug/
> [ja] Update content/ja/docs/tasks/debug/_index.md

- content/en/docs/concepts/services-networking/service.md
This was dropped in 1eef7424651bdc681711572e1042169faebe8e81 - I am sure it was an accident.
Originally added in https://github.com/kubernetes/website/pull/29752
Fixes https://github.com/kubernetes/kubernetes/issues/114670
> Restore an important note about API proxy

- content/zh-cn/docs/reference/glossary/ephemeral-container.md
Remove an extra `{` and give a blank line to keep consistent with en.
```
content/zh-cn/docs/reference/glossary/ephemeral-container.md
```
> [zh] updated glossary/ephemeral-container.md

- content/pt-br/docs/concepts/scheduling-eviction/_index.md
- content/pt-br/docs/reference/glossary/pod-disruption.md
Hello everyone,
Brazilian portuguese translation for the [Scheduling, Preemption and Eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/) page. There was already a page in Brazilian Portuguese but it's outdated [Escalonamento](https://kubernetes.io/pt-br/docs/concepts/scheduling-eviction/).
Related issues: #13939
> [pt-br] Update docs/concepts/scheduling-eviction/_index.md

- content/en/docs/tasks/administer-cluster/reserve-compute-resources.md
I made a mistake in https://github.com/kubernetes/kubernetes/issues/114673.
In KubeletConfiguration, it is `reservedSystemCpus` and not `reservedCpus` for `--reserved-cpus`
> We should note the command line option name is different from the configuration file key: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L621
> Add reservedSystemCpus in KubeletConfiguration as the flag is not the same style

- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
update `kubeadmin init` to `kubeadm init`
fixes #38646
> fixed typo in the docs

- content/en/docs/contribute/new-content/open-a-pr.md
Improved the **step 1 for opening a PR using GitHub**, by **more accurately pointing** the **location of the 'Edit this page' option**.
This is to **fix the issue**: https://github.com/kubernetes/website/issues/38650
> Fix advice about opening a pull request

- assets/scss/_base.scss
It seems in a Docsy/Hugo update that some CSS values changed and modified the look of the tabs.
If you look at the left side of the tabs (and right on mouse hover) you can see they're not connected to the container and are floating above. 
**Before:**
**After:**
> Fix tabs shortcode CSS

- content/en/docs/reference/_index.md
- content/en/docs/reference/config-api/_index.md
- content/en/docs/reference/config-api/apiserver-audit.v1.md
- content/en/docs/reference/config-api/client-authentication.v1.md
- content/en/docs/reference/config-api/client-authentication.v1beta1.md
- content/en/docs/reference/config-api/imagepolicy.v1alpha1.md
- content/en/docs/reference/config-api/kube-proxy-config.v1alpha1.md
- content/en/docs/reference/config-api/kube-scheduler-config.v1.md
- content/en/docs/reference/config-api/kube-scheduler-config.v1beta2.md
- content/en/docs/reference/config-api/kube-scheduler-config.v1beta3.md
- content/en/docs/reference/config-api/kubeadm-config.v1beta2.md
- content/en/docs/reference/config-api/kubeadm-config.v1beta3.md
- content/en/docs/reference/config-api/kubelet-config.v1.md
- content/en/docs/reference/config-api/kubelet-config.v1beta1.md
- content/en/docs/reference/config-api/kubelet-credentialprovider.v1.md
This PR updates the Config API references that are generated using the kubernetes-sigs/reference-docs/genref tool.
The tool has been updated to use the latest sources released with 1.26.
> Config API update for 1.26

- content/zh-cn/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- Add anchors
- Fix a rendering issue about mermaid in [/docs/concepts/scheduling-eviction/pod-scheduling-readiness/](https://kubernetes.io/zh-cn/docs/concepts/scheduling-eviction/pod-scheduling-readiness/)
> [zh] Fix rendering issues in pod-scheduling-readiness.md

- content/en/examples/concepts/policy/limit-range/problematic-limit-range.yaml
- content/zh-cn/examples/concepts/policy/limit-range/problematic-limit-range.yaml
~~Closes~~
Relates #38705
With this fix, ~~these commands~~ this command shall not claim the validation error anymore.
```
kubectl create -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/concepts/policy/limit-range/problematic-limit-range.yaml
```
<details>
<summary>Content before EDIT</summary>
```
kubectl create -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/concepts/policy/limit-range/problematic-limit-range.yaml
kubectl create -f https://raw.githubusercontent.com/kubernetes/website/main/content/zh-cn/examples/concepts/policy/limit-range/problematic-limit-range.yaml
```
</details>
> [en] Add missing required `type` field to LimitRange example

- content/zh-cn/docs/tasks/debug/debug-application/debug-service.md
Sync with en.
```
content/zh-cn/docs/tasks/debug/debug-application/debug-service.md
```
Preview: https://deploy-preview-38710--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-application/debug-service/
> [zh] sync /debug-application/debug-service.md

- content/en/docs/reference/_index.md
- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
- content/en/docs/reference/config-api/apiserver-admission.v1.md
**Rationale**:
The `admission.k8s.io/v1` API group is not generated into the v2/v3 OpenAPI specification as part of Kubernetes API because it is not officially "served". However, the structs in the API group are used in other APIs that are user-facing.
This PR addes the reference API and fixes references to it.
**Organization**:
This PR has two commits, one is about the introduction of the `admission.k8s.io/v1` API group. A follow-up commit reformats the validating-admission-policy reference page since it doesn't deserve a separate PR. No contents is changed, just long line wrapping.
closes: #38518
> Add admission config API and fixes references to the API

- content/zh-cn/docs/reference/config-api/kube-proxy-config.v1alpha1.md
Sync with en.
```
```
Preview: https://deploy-preview-38707--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/kube-proxy-config.v1alpha1/
> [zh] sync /config-api/kube-proxy-config.v1alpha1.md

- content/id/docs/tasks/job/automated-tasks-with-cron-jobs.md
successfulJobHistoryLimit and failedJobHistoryLimit should be successfulJobsHistoryLimit and failedJobsHistoryLimit
> [id] Fix successfulJobsHistoryLimit and failedJobHistoryLimit fields in CronJob tasks

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed.md
- Sync with en
- Use a consistent `服务账号` for `service account` by following [localization glossary](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/)
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed.md
```
> [zh] sync feature-gates-removed.md

- content/fr/docs/concepts/workloads/controllers/replicaset.md
--cascade=false is deprecated (boolean value) and can be replaced with --cascade=orphan
> Update cascade flag value to orphan

- content/zh-cn/docs/reference/config-api/client-authentication.v1.md
- content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
Sync 2 files with en.
```
content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
```
Preview: https://deploy-preview-38704--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/client-authentication.v1/
> [zh] sync /config-api/client-authentication.v1.md

- content/en/docs/reference/using-api/api-concepts.md
resolves https://github.com/kubernetes/website/issues/35381
added note about core resources using /api instead of /apis and added path examples
> added note about core resources using /api and added path examples

- content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md
Find some typos in 
```
content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md
```
> Fix typos in 2022-05-13-grpc-probes-in-beta.md

- content/en/docs/reference/labels-annotations-taints/_index.md
Code from the Kubernetes project sets (or previously did set) a label, kube-aggregator.kubernetes.io/automanaged
This looks intended, but https://kubernetes.io/docs/reference/labels-annotations-taints/ doesn't document that label.
This PR document & register the label .
https://kubernetes.io/docs/reference/labels-annotations-taints/
#38126
> adding annotation for kube-aggregator automanaged in labels-md

- README.md
A command inside Readme.md was missing for starting of local docker container
Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>
> Added make module-init command in Readme

- content/zh-cn/examples/concepts/policy/limit-range/problematic-limit-range.yaml
Porting PR https://github.com/kubernetes/website/pull/38706 as Issue https://github.com/kubernetes/website/issues/38705 also affects zh-cn.
> [zh-cn] Add missing required `type` field to LimitRange example

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
The `ComponentSLIs` feature gate is an interesting one introduced in v1.26. Because it was introduced in the `k8s.io/component-base` package, we failed to track it before.
This PR adds it for user awareness.
> Add ComponentSLIs feature gate

- data/releases/schedule.yaml
@xmudrii mentioned that the EOL dates were wrong and followed (kind of) the old rules for choosing such dates.
In https://github.com/kubernetes/sig-release/pull/2134 I have already adjusted the rules and this PR will fix the dates for 1.25 and 1.26 accordingly.
> Fix EOL dates for 1.25 and 1.26

- content/en/docs/reference/labels-annotations-taints/_index.md
Fixes #36656 
This PR registered `volumes.kubernetes.io/controller-managed-attach-detach` annotation.
> Register and document volumes.kubernetes.io/controller-managed-attach-detach annotation

- content/en/docs/setup/best-practices/cluster-large.md
This PR corrects the format of What's next section under [cluster-large.md](https://kubernetes.io/docs/setup/best-practices/cluster-large/) file.
Fixes #38021.
> updated the format of What's next section in cluster-large.md file

- content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
I've noticed that "has" is used instead of "have" with plural "API resources".
Additionally, "which has `status` or `scale` subresource" is restrictive / defining clause, so "that" should be used instead of "which".
Links:
- https://www.dictionary.com/e/that-vs-which/
- https://www.grammarly.com/blog/which-vs-that/
> Small grammar fix

- content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
Updated example of reading secret values from a file so that it doesn't base64 the contents in the file before `kubectl` reads it.
Otherwise, if a user follows this guide they will end up with a Secret containing double Base64 encoded credentials, which means that when accessed from a Pod they will get the Base64 encoding of the credential they actually want.
This is also the case for one of the localised versions but I will PR for that separately.
> Remove Base64'ing of file contents

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
I'm fairly sure the final step outline for [ServiceAccount admission controller](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller) is meant to state that imagePullSecrets are added if the pod _doesn't_ already contain then. 
I believe the current text is a typo but please correct me if I am wrong.
> Fix typo in SA admission controller steps

- content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md
> [zh] sync kube-scheduler-config.v1.md

- content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md
Fix links for k/design-proposals-archive
The contributors/design-proposals in k/community was removed. It's only
available in k/design-proposals-archive repo now.
Sync with `content/en/docs/tasks/run-application/horizontal-pod-autoscale.md`
> [zh-cn] Fix links for k/design-proposals-archive

- content/en/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
enhancement: https://github.com/kubernetes/enhancements/issues/3017
API changes + feature gate: https://github.com/kubernetes/kubernetes/pull/113375
> Feature blog for KEP-3017: Unhealthy Pod Eviction Policy for PDBs

- content/en/docs/concepts/workloads/controllers/cron-jobs.md
- content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md
Relevant to #4500
- move most conceptual contents to concepts topic (I believe have CronJob spec explanations in `tasks/job/automated-tasks-with-cron-jobs.md` is confusing)
- remove an outdated section (CronJobControllerV2 feature gate already removed)
- other minor sentence decorations.
> CronJob topics improvement

- content/zh-cn/docs/tasks/job/automated-tasks-with-cron-jobs.md
Sync with en. Some content is moved to the concept page that will be included in another PR.
```
content/zh-cn/docs/tasks/job/automated-tasks-with-cron-jobs.md
```
> [zh] sync automated-tasks-with-cron-jobs.md

- assets/scss/_custom.scss
- layouts/partials/navbar.html
Fixed overlap of the navigation bar links with, the kubernetes logo and the title description.
This fixes the issue: https://github.com/kubernetes/website/issues/38739
> Fixed overlap of nav-links with other content in certain screen sizes

- layouts/partials/blog-meta-links.html
**Blog Meta Links Opening in Same Tab**
Changed the target attribute of the links in the blog section to "_blank" to make them open in a new tab when clicked. 
This helps improve the user experience by keeping the user on the current page while still allowing them to access the linked content. 
Closes #38818
> Updated to open blog meta links in new tab

- content/en/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
3 links are incorrect in an already published blog post
followup to https://github.com/kubernetes/website/pull/37627
> fix links in blog post: Eviction policy for unhealthy Pods guarded by PDBs

- content/zh-cn/docs/setup/production-environment/container-runtimes.md
1. sync  `content/zh-cn/docs/setup/production-environment/container-runtimes.md` with `content/en/docs/setup/production-environment/container-runtimes.md`
2. format some lines to make files diff clear
> [zh-cn]sync container-runtime.md with en page

- OWNERS
- OWNERS_ALIASES
- content/en/docs/contribute/advanced.md
**TL;DR:** This PR removes myself as an approver/reviewer in SIG Docs.
Related PRs:
- https://github.com/kubernetes/org/pull/3931
- https://github.com/kubernetes/community/pull/7035
After [stepping down](https://groups.google.com/g/kubernetes-sig-docs/c/hspG6mzgkrs) as co-chair in early 2022, I welcomed my first child into the world and did my best "homer fade away" for about 6 months while I discovered fatherhood.
It took a bit longer for me to finally get around to removing the permissions (this PR) and I want to apologize to the community for leaving my dormant permissions in place. Having a non-active approver / reviewer does not help the community thrive.
I've always said that I write the documentation that I wish existed when I needed it. That includes docs around moving to …
> Jim Angel going emeritus

- content/en/docs/tutorials/security/apparmor.md
- content/en/docs/tutorials/security/ns-level-pss.md
- content/en/docs/tutorials/security/seccomp.md
This PR updates the page weights for the tutorial/security section, https://kubernetes.io/docs/tutorials/security/. It is part of our larger effort to update the page weights in the english docs, as described in https://github.com/kubernetes/website/issues/35093. To summarize, when page weights are missing or duplicated the site will default sort the page in alphabetical order based on page title. This causes problems in localized content because the page titles are different, making the page order different between the english and localized content. 
https://github.com/kubernetes/website/issues/38850 was filed recently calling out a problem with the page weights in the tutorial/security section.
> Update page weights in tutorial/security section

- content/en/blog/_posts/2022-12-13-host-process-containers-ga/index.md
- Removed `https://kubernetes.io`
- Changed from `(docs/...` to `(/docs/...`
> Fix two URLs in blog: Windows HostProcess

- content/en/docs/concepts/overview/working-with-objects/namespaces.md
Fixing this [namespace doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#automatic-labelling) to be consistent about the Automatic labelling on namespaces stable since 1.22 information like made on [this other page](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-namespace-by-its-name) by https://github.com/kubernetes/website/pull/32122.
> Mark automatic labelling on namespaces as stable since 1.22

- content/en/docs/tasks/configure-pod-container/static-pod.md
No log observation method is mentioned in the Observe static pod behavior section
The what's next section can have some useful additional references.
- Add a reference link directing to https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#get-a-container-s-logs in the aforementioned section
- Add more references to `whats next` section
https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/
Fixes: #38218
> Adding log info in static pod, adding references in whats next section

- content/en/docs/reference/labels-annotations-taints/_index.md
Kubernetes uses an annotation, pv.kubernetes.io/migrated-to. However, this annotation is not registered in https://kubernetes.io/docs/reference/labels-annotations-taints/
Changes done:
- Registered all `pv.kubernetes.io` annotations in the [labels-annotations-taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) page.
Resolves #37814 
/sig storage
/kind bug
> Adding pv.kubernetes.io annotations in labels-annotations-taints

- content/en/docs/reference/networking/virtual-ips.md
Hello! here is a PR for just removing a space between back and end.
.. the back end Pods for ... -> ... the backend Pods for ...
markdown : [virtual-ips.md](https://github.com/kubernetes/website/tree/main/content/en/docs/reference/networking/virtual-ips.md)
kubernetes.io : [virtual-ips](https://kubernetes.io/docs/reference/networking/virtual-ips/)
> remove unnecessary space between back and end

- content/fr/docs/concepts/configuration/secret.md
Hi!
For some configmap and secret documentation pages, links to the KubeletConfiguration struct are broken.
It's due to the usage of the docsbranch parameter which is evaluated to main. But the main branch doesn't exist in the [kubernetes](https://github.com/kubernetes/kubernetes) repo.
This PR replaces the parameter to an hardcoded value: master.
You can check that the link is currently broken here:
https://kubernetes.io/fr/docs/concepts/configuration/secret/#les-secrets-mont%C3%A9s-sont-mis-%C3%A0-jour-automatiquement (latest version)
https://v1-23.docs.kubernetes.io/fr/docs/concepts/configuration/secret/#les-secrets-mont%C3%A9s-sont-mis-%C3%A0-jour-automatiquement (v1.23 version)
This PR is a split of #34902
> [FR] Fix fix broken links for KubeletConfiguration struct

- content/pt-br/docs/reference/glossary/cronjob.md
Added translation for portuguese of the glossary term cronjob.
> [pt-br] Add /docs/reference/glossary/cronjob.md

- content/ja/docs/tasks/debug/debug-application/get-shell-running-container.md
#38655
We need to update `content/ja/docs/tasks/debug/debug-application/get-shell-running-container.md` according to the English text, because it is outdated.
1. Delete {{< version-check >}}
```text
{{< include "task-tutorial-prereqs.md" >}} {{< version-check >}}
↓
{{< include "task-tutorial-prereqs.md" >}}
```
2.  Updated note
```text
{{< note >}}
ダブルダッシュの記号 `--` はコマンドに渡す引数とkubectlの引数を分離します。
{{< /note >}}
↓
{{< note >}}
ダブルダッシュ(`--`)のセパレーターは、コマンドに渡す引数とkubectlの引数を分離します。
{{< /note >}}
```
> Deleted {{< version-check >}} & Updated note

- content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Signed-off-by: lonelyCZ <chengzhe@zju.edu.cn>
Fix index misspelling of custom-resource-definitions.md
https://kubernetes.io/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#efaulting
> [zh] Fix index misspelling of custom-resource-definitions.md

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Removes ambiguity concerning `failureThreshold` documentation.
Solves https://github.com/kubernetes/website/issues/37414
> Improve explanation of failureThreshold for Pod probes

- content/en/docs/concepts/extend-kubernetes/operator.md
#37354 - link to mast Operator
This change adds a link to Mast, which gives the option to use Declarative and Dynamic definitions to build operators that utilize Ansible.
> Add mast operator to list

- content/en/blog/_posts/2023-01-05-retroactive-default-storage-class.md
Looks not neat enough. Check [preview](https://deploy-preview-38940--kubernetes-io-main-staging.netlify.app/blog/2023/01/05/retroactive-default-storage-class/) please.
> Modify alignment of bullet items in 0105 blog

- content/en/docs/concepts/architecture/nodes.md
This PR added few glossary tooltips and updated What's next section in Nodes page.
This will fix #38072.
> Added glossary tooltip and references in the Nodes page

- content/en/docs/tasks/administer-cluster/cluster-upgrade.md
This PR fixed the links for **API compatibility** and **Kubelet Device Manager API Versions**  in [Upgrade A Cluster](https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/) task.
Fixes #38858
> Fixed the Link for API compatibility and Kubelet Device Manager API Versions.

- content/en/_index.html
It's time to make the KubeCon dates relevant for this year on the index page.
By the way, shouldn't we use the full event name (_"Attend KubeCon + CloudNativeCon Europe on [this-date]"_ instead of _"Attend KubeCon Europe on [this-date]"_) or such simplification is acceptable?
> Update KubeCon dates for 2023

- content/en/docs/concepts/storage/volumes.md
This PR fixed the missing content for the glusterfs volume type.
Fixes #38968
> Fix glusterfs details in Volumes concept page

- content/ru/_index.html
Updating KubeCon events links for the Russian website index page — propagating the changes from #38862.
> [ru] Update KubeCon dates for 2023

- content/ja/docs/reference/_index.md
- content/ja/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
This PR adds heading slash "/" on ja content link.
The link is (mainly) 404 without heading slash, that's why I create this commit.
The link is expanded as followings if we use `[something](ja/docs/something)` style:
https://kubernetes.io/ja/docs/reference/ja/docs/reference/setup-tools/kubeadm/ (<-Double "ja" in URL.)
The target pages on preview site:
- https://deploy-preview-38911--kubernetes-io-main-staging.netlify.app/ja/docs/reference/#cli%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9
- https://deploy-preview-38911--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#%E6%AC%A1%E3%81%AE%E9%A0%85%E7%9B%AE
> [ja] Fix broken links to localized pages

- content/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
As reverted in 8830000, switching to iptables-legacy is no longer required.
> [ja] Remove instruction to use iptables-legacy

- content/ja/docs/concepts/configuration/configmap.md
- content/ja/docs/concepts/configuration/secret.md
Hi!
For some configmap and secret documentation pages, links to the KubeletConfiguration struct are broken.
It's due to the usage of the docsbranch parameter which is evaluated to main. But the main branch doesn't exist in the [kubernetes](https://github.com/kubernetes/kubernetes) repo.
This PR replaces the parameter to an hardcoded value: master.
You can check that the link is currently broken here:
https://kubernetes.io/fr/docs/concepts/configuration/secret/#les-secrets-mont%C3%A9s-sont-mis-%C3%A0-jour-automatiquement (latest version)
https://v1-23.docs.kubernetes.io/fr/docs/concepts/configuration/secret/#les-secrets-mont%C3%A9s-sont-mis-%C3%A0-jour-automatiquement (v1.23 version)
This PR is a split of https://github.com/kubernetes/website/pull/34902
> [JA] Fix broken links for KubeletConfiguration struct

- content/ja/docs/concepts/architecture/nodes.md
We would like to use `#heartbeats`, `#node-controller`, and so on as in-page link to Japanese Nodes page.
This page may be refered from many pages with in-page link.
So it's better to set English IDs for all Japanese headings in `nodes.md`.
The purpose of this PR only sets IDs, not updating the contents and the heading names.
en:
https://kubernetes.io/docs/concepts/architecture/nodes/
> [ja] Set heading IDs content/ja/docs/concepts/architecture/nodes.md

- content/id/docs/concepts/configuration/secret.md
Hi!
For some configmap and secret documentation pages, links to the KubeletConfiguration struct are broken.
It's due to the usage of the docsbranch parameter which is evaluated to main. But the main branch doesn't exist in the [kubernetes](https://github.com/kubernetes/kubernetes) repo.
This PR replaces the parameter to an hardcoded value: master.
You can check that the link is currently broken here:
https://kubernetes.io/fr/docs/concepts/configuration/secret/#les-secrets-mont%C3%A9s-sont-mis-%C3%A0-jour-automatiquement (latest version)
https://v1-23.docs.kubernetes.io/fr/docs/concepts/configuration/secret/#les-secrets-mont%C3%A9s-sont-mis-%C3%A0-jour-automatiquement (v1.23 version)
This PR is a split of https://github.com/kubernetes/website/pull/34902
> [ID] Fix broken links for KubeletConfiguration struct

- content/en/blog/_posts/2023-01-12-protect-mission-critical-pods-priorityclass/index.md
Correcting indentation error in the blog post; not sure when this was introduced; correcting this out so that people don't face issues while applying the YAML files.
URL: [https://kubernetes.io/blog/2023/01/12/protect-mission-critical-pods-priorityclass/](https://kubernetes.io/blog/2023/01/12/protect-mission-critical-pods-priorityclass/)
> Correcting indentation errors in the blog post

- content/en/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
We cannot use `kubectl apply` to apply it to the cluster.
Doing that gives the following error:
no matches for kind "AdmissionConfiguration" in version "apiserver.config.k8s.io/v1"
---
/assign @tallclair
/assign @liggitt
> AdmissionConfiguration is a static configuration to the apiserver

- content/en/docs/tasks/administer-cluster/safely-drain-node.md
In most cases `kubectl drain` gets used with `--ignore-daemonsets`. The docs should reflect that.
The explanation text of the PR is from the reference:
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain
> Add `--ignore-daemonsets` to docs of `kubectl drain`

- content/zh-cn/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Add curly brackets to make the shell execute correctly
> [zh-cn] fix the shell of appending kubeconfig

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
Sync with en.
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
```
Preview: https://deploy-preview-38993--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1/
> [zh] sync /config-and-storage-resources/persistent-volume-v1.md

- content/zh-cn/docs/tasks/access-application-cluster/list-all-running-container-images.md
Sync `content/zh-cn/docs/tasks/access-application-cluster/list-all-running-container-images.md` with en page.
> [zh-cn]sync list-all-running-container-images.md

- content/en/docs/concepts/security/rbac-good-practices.md
The docs previously referred to the reader to the now defunct PodSecurityPolicy page to explain how PersistentVolumes can be a path of privilege escalation, burrying the lede.
Now that PodSecurityPolicy is gone, update this bit to actually explain that it it is unfettered access to creating hostPath-typed PersistentVolumes that are a problem. Some words lifted from the 1.24 PodSecurityPolicy docs.
Signed-off-by: Mike Waychison <mike@waychison.com>
> Update RBAC Good Practices for PersistentVolumes

- content/en/docs/tasks/administer-cluster/kubelet-credential-provider.md
Fixes: #38465 
This PR update the correct name of the field to `matchImages`.
> Modify correct name of the field  to matchImages

- data/releases/schedule.yaml
This PR adds minor (`.0`) releases to the patch releases calendar. This is based on the Slack discussion: https://kubernetes.slack.com/archives/C2C40FMNF/p1674214109801969
We think it would be very useful to show release dates for the minor (`.0`) releases. Right now, this information is only available in the:
* `schedule.yaml` file
* sig-release repo
Neither of those places is easily accessible by maintainers and end users. The purpose of this change is to make this information easily accessible and discoverable.
I thought about two approaches for implementing this, described below.
This is my favorite approach because we keep the flow. At the top we show the latest patch release, going to the bottom where we show the first (`.0`) release. However, this approach has a problem:
I don't …
> Show minor (`.0`) releases in the patch releases calendar

- content/en/docs/tutorials/security/cluster-level-pss.md
Some bulleted content looks not good enough. See [preview](https://deploy-preview-39103--kubernetes-io-main-staging.netlify.app/docs/tutorials/security/cluster-level-pss/).
- Fixed incorrect indentations
- Changed all 4 spaces to 3 spaces as suggested
> Fix indentations in cluster-level-pss.md

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
In the `feature-gates.md` documentation there are 2 entries for SELinuxMountReadWriteOncePod. Although they have different descriptions, the most recent one seems to summarize the previous one.
> Remove duplicate entry for SELinuxMountReadWriteOncePod

- content/en/docs/concepts/workloads/pods/disruptions.md
This is a follow-up of https://github.com/kubernetes/kubernetes/pull/114623 where we reached a consensus the change the literal `PreemptionByKubeScheduler` to `PreemptionByScheduler`, so it reads better to adapt to both default and custom schedulers.
Additional notes:
- I raised this PR against `dev-1.27` b/c the changes in k/k will land on 1.27. Please correct me if it needs to target `master`
- I also made the tweak in ko and cn folders
> Rename 'PreemptionByKubeScheduler' to 'PreemptionByScheduler'

- content/en/docs/concepts/cluster-administration/manage-deployment.md
This PR wraps the long lines in the manage-deployment.md page.
> Tweak line wrapping for manage-deployment page

- content/zh-cn/docs/concepts/security/rbac-good-practices.md
Sync with en.
```
content/zh-cn/docs/concepts/security/rbac-good-practices.md
```
Preview: https://deploy-preview-39076--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/rbac-good-practices/
> [zh] sync rbac-good-practices.md

- content/en/blog/_posts/2019-04-04-local-persistent-volumes-ga.md
- content/en/blog/_posts/2020-05-27-An-Introduction-to-the-K8s-Infrastructure-Working-Group.md
- content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md
- content/en/blog/_posts/2022-05-27-maxunavailable-for-statefulset.md
I'm not sure if this was discussed before, I didn't find an issue tracking this work. 
Context: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/
/sig release
/sig node
/kind cleanup
/priority important-longterm
CC @BenTheElder
> registry change in docs (k8s.gcr.io -> registry.k8s.io)

- content/pt-br/docs/tasks/access-application-cluster/configure-dns-cluster.md
Brazilian portuguese translation of the [Configure DNS for a Cluster](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md)
This document, configure DNS for a cluster, does a reference to another document that I am translating too but it is a WIP at the moment.
https://github.com/kubernetes/website/pull/38481
https://github.com/kubernetes/website/issues/13939
> [pt-br] Add docs/tasks/access-application-cluster/configure-dns-cluster.md

- content/en/docs/concepts/workloads/controllers/ttlafterfinished.md
Currently, two links point to an invalid anchor in
```
content/en/docs/concepts/workloads/controllers/ttlafterfinished.md
```
See [Preview](https://deploy-preview-39136--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/ttlafterfinished/) please.
> Fix links to mutatingadmissionwebhook

- content/zh-cn/blog/_posts/2022-12-27-cpumanager-goes-GA.md
```
content/zh-cn/blog/_posts/2022-12-27-cpumanager-goes-GA.md
```
Preview: https://deploy-preview-38972--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/12/27/cpumanager-ga/
> [zh] sync blog: 2022-12-27-cpumanager-goes-GA.md

- content/en/docs/reference/access-authn-authz/admission-controllers.md
This is the first action item of https://github.com/kubernetes/kubernetes/issues/111516
Preview [here](https://deploy-preview-39131--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny).
Note the shortcomings of the implementation of the `SecurityContextDeny` admission plugin.
/sig security
/sig auth
> Update doc of admission plugin `SecurityContextDeny` to note shortcomings

- content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
This pr removes redundant English documentation and fixs a link in custom-resource-definition-versioning page.
> [zh-cn] Cleanup custom-resource-definition-versioning page

- content/zh-cn/docs/concepts/workloads/controllers/ttlafterfinished.md
Sync with en #37595. See [preview](https://deploy-preview-39133--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/ttlafterfinished/).
```
content/zh-cn/docs/concepts/workloads/controllers/ttlafterfinished.md
```
> [zh] sync ttlafterfinished.md

- content/en/docs/reference/access-authn-authz/admission-controllers.md
Change for consistency:
- Add a space after `:` in json
- Indent 2 spaces in yaml
> Add spaces in code snippets for consistency

- content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
Sync with en.
```
content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
```
Preview: https://deploy-preview-39019--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller/
> [zh] sync enforce-standards-admission-controller.md

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
Sync with en.
```
content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
```
Preview: https://deploy-preview-38999--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/
> [zh] Sync pod-disruption-budget-v1.md

- content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
1. Resync with en page
2. Removed redundant blank space
3. Use the number one (`1.`) for ordered lists.
> [zh] Sync certificate-signing-requests.md

- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
Sync `content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md` with en page.
> [zh-cn] Sync cpu-default-namespace.md

- content/en/docs/reference/using-api/client-libraries.md
The Rust client library's URL redirects to a new location.  This change updates the URL to match where it redirects.
Old URL: https://github.com/clux/kube-rs
New URL: https://github.com/kube-rs/kube
> Update Rust client library from clux/kube-rs to kube-rs/kube

- content/en/docs/concepts/services-networking/service.md
Fix the current `Ingress` 404 link, to make the doc better.
> Fix broken link in Service concept page

- content/zh-cn/blog/_posts/2022-12-26-pod-scheduling-readiness.md
fixed: #39156
Translate Chinese version for 2022-12-26-pod-scheduling-readiness.md
Preview：https://deploy-preview-39177--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/12/26/pod-scheduling-readiness-alpha/
> [zh-cn] add 2022-12-26-pod-scheduling-readiness.md chinese version

- content/zh-cn/docs/reference/using-api/client-libraries.md
Sync with en.
```
content/zh-cn/docs/reference/using-api/client-libraries.md
```
> [zh] sync /using-api/client-libraries.md

- content/zh-cn/docs/tasks/administer-cluster/safely-drain-node.md
Sync with en.
```
content/zh-cn/docs/tasks/administer-cluster/safely-drain-node.md
```
Preview: https://deploy-preview-39018--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/safely-drain-node/
> [zh] sync safely-drain-node.md

- content/ko/examples/service/access/backend-deployment.yaml
'website/content/ko/examples/service/access/backend-deployment.yaml' different from   
'website/content/en/examples/service/access/backend-deployment.yaml'
It should be modified to 3 depending on the context.
[check here](https://github.com/kubernetes/website/edit/main/content/ko/docs/tasks/access-application-cluster/connecting-frontend-backend.md)
첫 pull request 로 일전에 main 에서 분기하여 main 에 병합요청 넣었던 것을 바로 잡아주셔서 감사합니다 😂
> [ko] Fix typo, It should be modified to 'replicas: 3'

- content/ja/docs/concepts/containers/runtime-class.md
- content/ja/docs/concepts/workloads/pods/ephemeral-containers.md
- content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
- content/ja/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
Signed-off-by: Shogo Hida <shogo.hida@gmail.com>
Fixes #38797 
This PR changes the paths of debug pages. The example shown on the issue is below.
- Only add "/ja"
- e.g.: /docs/tasks/debug/debug-cluster/audit/ -> /ja/docs/tasks/debug/debug-cluster/audit/
> [ja] Add ja to the paths of debug pages

- content/ja/docs/concepts/overview/kubernetes-api.md
This PR updates the page weights under content/ja/docs/concepts/overview.
This will update the page order to the same order as en.
Related: #37479
* kubernetes-api.md : Fix in this PR
* components.md : Fixed in #38547
* working-with-objects/field-selectors.md : Fix in #38913
* working-with-objects/namespaces.md : Fix in #38913
> [ja] Update page weights under content/ja/docs/concepts/overview.

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node.md
Sync with en.
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node.md
```
See [preview](https://deploy-preview-39220--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node/).
> [zh] sync kubeadm_reset_phase_cleanup-node.md

- content/en/docs/tasks/tools/_index.md
Fixes #39134
Updated page [Install Tools](https://kubernetes.io/docs/tasks/tools/)
> Fix broken link on Install Tools page

- content/en/docs/tasks/configure-pod-container/quality-service-pod.md
/sig node
/kind cleanup
/priority backlog
small note based on this question: https://github.com/kubernetes/kubernetes/pull/115458/files#r1093894333
> ephemeral containers are not accounted for Guaranteed QoS class

- content/en/docs/tasks/tools/install-kubectl-macos.md
Expands on the fixes for https://github.com/kubernetes/website/issues/38702
Modifying the kubectl install docs for MacOS per this https://github.com/kubernetes/website/issues/38702.
Gives instructions about how to delete static files that will no longer be used after the installation is complete.
> Add cleanup commands to kubectl MacOS install

- content/en/blog/_posts/2023-02-03-sig-instrumentation-spotlight.md
Correct a minor capitalization issue in upcoming article https://blog.k8s.io/2023/02/03/sig-instrumentation-spotlight-2023/
(fixing up https://github.com/kubernetes/website/pull/39204)
Equivalent to https://github.com/kubernetes/contributor-site/pull/372
> Fix up 2023 SIG Instrumentation spotlight article

- content/en/docs/concepts/services-networking/ingress.md
Changed name of the branch in github link to ingress-nginx repository from master to main since the default branch of this repository has changed from `master` to `main`.
> Update branch name in ingress-nginx github link

- content/en/docs/concepts/workloads/pods/downward-api.md
Fixes: #38361 
This PR Modify spec and status downward API fields to  only available as environment variables not as files.
> Document spec and status downward API fields  only available as environment variables

- config.toml
Fixes https://github.com/kubernetes/website/issues/38412
This PR updates the config.toml in the release-1.25 branch to change the deprecated field from false to true.
This will add a banner/box for users viewing the 1.25 docs that the 1.25 docs are no longer maintained.
At this time, the current release is 1.26
> Update config.toml in release-1.25 branch to change deprecated to true

- content/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
The ports for kube-scheduler and kube-controller-manager built with kubeadm are different from the doc.
I think https://kubernetes.io/docs/reference/networking/ports-and-protocols/ is correct, so I have modified it to match.
> Modify kube-scheduler/controller-manager port in jp install-kubeadm.md

- content/ko/docs/tasks/run-application/run-replicated-stateful-application.md
Translated [Run a Replicated Stateful Application](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/) in Korean
쿠버네티스 문서/태스크/애플리케이션 실행 항목의 미번역된 [Run a Replicated Stateful Application](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/)을 한국어로 번역하였습니다.
> [ko] Tranlsate run-replicated-stateful-application.md into Korean

- content/en/docs/concepts/cluster-administration/flow-control.md
This PR adds overlooked details to the Observability section of the description of API Priority and Fairness.
- Remarks on server logging are added.
- Remarks on HTTP response headers are added.
- An overlooked metric is added.
> Extend APF Observability with logging and response headers

- content/zh-cn/docs/concepts/scheduling-eviction/pod-overhead.md
Resync `content/zh-cn/docs/concepts/scheduling-eviction/pod-overhead.md` with en page.
> [zh] Resync pod-overhead.md

- content/zh-cn/docs/concepts/workloads/pods/downward-api.md
Sync with en. See [preview](https://deploy-preview-39252--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/downward-api/).
```
content/zh-cn/docs/concepts/workloads/pods/downward-api.md
```
> [zh] sync downward-api.md

- content/en/docs/tasks/tools/install-kubectl-macos.md
`whatsnext` does not belong to `The following methods exist for installing kubectl on macOS`.
> Remove what-next in install-kubectl-macos.md

- content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
1. Resync `content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md` with en page
2. Remove extra spaces
> [zh] Resync topology-spread-constraints.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/stateful-set-v1.md
Sync with en. See [preview](https://deploy-preview-39264--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/).
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/stateful-set-v1.md
```
> [zh] sync stateful-set-v1.md

- content/fr/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
- content/fr/examples/pods/storage/pv-claim.yaml
- content/fr/examples/pods/storage/pv-duplicate.yaml
- content/fr/examples/pods/storage/pv-pod.yaml
- content/fr/examples/pods/storage/pv-volume.yaml
Hi, 
This adds the French translation for the task "Configure a Pod to Use a PersistentVolume for Storage", from the Configure Pods and containers section. This is the [reference document](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/)
It might need some tweaks here and there regarding the translation of some concepts, but the bulk of the task is done :)
> [fr] add translation for task "Configure a Pod to Use a PersistentVolume for Storage"

- content/en/blog/_posts/2023-02-03-sig-instrumentation-spotlight.md
Only tweak long lines in this blog without any other change:
```
content/en/blog/_posts/2023-02-03-sig-instrumentation-spotlight.md
```
See [preview](https://deploy-preview-39293--kubernetes-io-main-staging.netlify.app/blog/2023/02/03/sig-instrumentation-spotlight-2023/).
> Tweak line wrappings in blog sig-instrumentation-spotlight

- layouts/partials/blog-meta-links.html
The link's text "Overflow" should be the site's full name, "Stack Overflow".
> update blog-meta-link for correct "Overflow"

- content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md
As discussed on https://github.com/kubernetes/website/pull/39304 we should make it clear that the example only matches resources, not subresources
> Specify that subresources excluded from mutating webhook example

- content/en/docs/tasks/debug/debug-application/debug-running-pod.md
Commit b60aa414a0b updated the command output samples, but explanations for the output of `kubectl describe pod` seems not to be updated.
> Update the explanation for `kubectl describe pod`.

- content/en/docs/concepts/configuration/manage-resources-containers.md
This PR fixed the broken link for `Quality of Service classes` for Pods in [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
Fixes  #39312
> Fixed the Broken Link for Quality of Service classes for Pods.

- content/en/docs/concepts/workloads/pods/_index.md
Updates reference information to reflect that WindowsHostProcessContainers feature has gone GA.
#38433
> Update privileged pod documentation to reflect GA feature

- content/en/docs/reference/networking/virtual-ips.md
> Added the glossary tooltips to Virtual IPs and Service Proxies

- content/en/docs/tasks/administer-cluster/verify-signed-artifacts.md
Fixes https://github.com/kubernetes/website/issues/38473
> Mentioned required cosign version for the `--certificate` flag

- content/en/docs/concepts/services-networking/dns-pod-service.md
- content/en/examples/service/networking/custom-dns.yaml
Fix https://github.com/kubernetes/website/issues/39166
Problem:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config uses 1.2.3.4 as the example DNS server. It's better to use an [IP address reserved for documentation](https://www.rfc-editor.org/rfc/rfc5737.html).
Proposed Solution:
Change the example manifest and web page to use IP address 192.0.2.1 ( from the 192.0.2.0/24 block)
> updating Pod DNS config example to use documentation IP address

- content/en/docs/concepts/workloads/controllers/replicaset.md
1. The syntax highlighting can be turned off in part of command output. I remove the `shell` syntax tag.
2. When I copy the `curl` command, I also need to delete marker `>` to make the command execute successfully, so I removed `>`.
3. By the way, clean up the extra spaces in the page.
> Cleanup page replicaset

- assets/scss/_custom.scss
resolves #21924
You can show Bing search results by setting the cookie `is_china` to `True` on Dev Tool (the below is Google Chrome example):
> Adjust CSS for Bing search result page

- content/en/docs/concepts/workloads/pods/_index.md
This PR is a follow-up to PR https://github.com/kubernetes/website/pull/38673
Addresses the following comments:
- https://github.com/kubernetes/website/pull/38673/files#r1098354034
-  Have clearer subheadings to prevent any confusion on the feature/enhancement that went stable in 1.26
See the KEP for Windows privileged container support: https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support
- https://github.com/kubernetes/website/pull/38673/files#r1068961877
- add a space between a feature gate and a link
Preview of updated page: https://deploy-preview-39324--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/pods/
> Updated concepts/workloads/pods/_index.html as followup to PR 38673

- content/en/releases/download.md
On the releases/downloads page the text was changed from k8s.gcr.io to registry.k8s.io in a previous PR but they still link to https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/
See Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1675720286842709
/sig release
/kind cleanup
Original: https://kubernetes.io/releases/download/
Preview: https://deploy-preview-39342--kubernetes-io-main-staging.netlify.app/releases/download/
> Remove links to images on gcr on releases/download page

- content/zh-cn/docs/concepts/workloads/pods/_index.md
Sync with en #38673 and #39324 . 
See [preview](https://deploy-preview-39323--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/).
```
```
> [zh] sync /workloads/pods/_index.md

- content/en/docs/concepts/services-networking/service.md
Updated service page with following:
1. Changed a reference link text from `DNS Pods and Services` to `DNS for Services and Pods` same as reference page title to avoid confusion.
2. Updated what's next section.
`Page updated:` https://kubernetes.io/docs/concepts/services-networking/service/#dns
Fixes #38205.
> Tweak wording for Service concept

- content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
Reverts kubernetes/website#36114
`source` executes a command in the **current** shell, and returns the status to the current shell.
`exec` closes the current shell and for a new shell with the same PID. The system call behind the `exec` command replaces the current process using a `exec*()`. The code, data and stack of the process are all replaced. The `exec` approach is much heavier than the `source` command.
If we google how to make some user land environment changes, we always prefer `source`.
> Revert "Updated kubectl completion configuration"

- content/en/docs/concepts/windows/intro.md
Correct the Pod security context section to reflect the fields that are supported on Windows.
> windows: Correct Pod security context section

- content/en/releases/download.md
This updates the download links to use registry.k8s.io instead of the old k8s.gcr.io.
This effectively backports the download link changes from aaceeb69513c53b6fb861886ae86e8bf58506268.
> Update download.md for registry.k8s.io

- content/en/blog/_posts/2022-07-13-gateway-api-in-beta.md
Fixes #39373
Updated page [Kubernetes Gateway API Graduates to Beta](https://kubernetes.io/blog/2022/07/13/gateway-api-graduates-to-beta/)
> Fix broken link on Kubernetes Gateway API Graduates to Beta page

- content/en/docs/tutorials/services/source-ip.md
[/docs/.../service#proxy-mode-iptables](https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-iptables) no longer links to an anchored section of the `service` documentation page. Corrected the link.
> Fix Anchor Link

- content/en/docs/tasks/tools/install-kubectl-windows.md
Expands on the fixes for https://github.com/kubernetes/website/issues/38702
Modifying the kubectl install docs for Windows per this issue: https://github.com/kubernetes/website/issues/38702.
Gives instructions about how to delete static files that will no longer be used after the installation is complete.
> Add cleanup commands to kubectl Windows install

- content/zh-cn/blog/_posts/2023-02-06-k8s-gcr-io-freeze-announcement.md
Fix #39381
```
content/zh-cn/blog/_posts/2023-02-06-k8s-gcr-io-freeze-announcement.md
```
See [preview](https://deploy-preview-39382--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/02/06/k8s-gcr-io-freeze-announcement/).
> [zh] sync 2023-02-06-k8s-gcr-io-freeze-announcement.md

- content/en/docs/concepts/storage/volume-snapshots.md
- content/en/docs/reference/labels-annotations-taints/_index.md
This PR updates the volume snapshot documentation to account for the change in annotation name to allow volume mode changes in a provision operation. KEP - https://github.com/kubernetes/enhancements/issues/3141
PR that changed the annotation name - https://github.com/kubernetes-csi/external-provisioner/pull/791
> Update volume mode change annotation in documentation

- content/en/docs/concepts/storage/volumes.md
Evidences:
- kubelet translates `core/v1.MountPropagationNone` to `runtimeapi.MountPropagation_PROPAGATION_PRIVATE`:
- https://github.com/kubernetes/kubernetes/blob/v1.26.1/pkg/kubelet/kubelet_pods.go#L298
- CRI runtimes translate `runtimeapi.MountPropagation_PROPAGATION_PRIVATE` to OCI mount option `"rprivate"`:
- https://github.com/containerd/containerd/blob/v1.6.16/pkg/cri/opts/spec_linux.go#L181
- https://github.com/cri-o/cri-o/blob/v1.26.1/server/container_create_linux.go#L982
- - -
This commit also replaces the link to https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt with https://man7.org/linux/man-pages/man8/mount.8.html , as the former one does not mention `rprivate` .
> `mountPropagation: None` equates to `rprivate`, not `private`

- content/en/docs/tasks/configure-pod-container/migrate-from-psp.md
https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/#before-you-begin
> Add markup to fix skew output in documentation

- content/pt-br/docs/tasks/debug/debug-application/debug-init-containers.md
Hello everyone, 
Brazilian portuguese translation for the [Debug Init Containers Page](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug/debug-application/debug-init-containers.md).
> [pt-br] Add docs/tasks/debug/debug-application/debug-init-containers.md

- content/en/docs/concepts/security/service-accounts.md
- content/en/docs/reference/glossary/jwt.md
Add a new concept page for Service Accounts in k8s
This PR focuses only on adding the new page, based on the draft doc [here](https://docs.google.com/document/d/1UcEFreczITmFhcHAgZkIpuEJD4m1AraiRQAtzpNIRaE/edit#). It covers key topics like use cases, defaults, and authentication. 
Some additional work after this:
1. Clean up existing pages to remove duplicate info if exists.
1. Link from how-tos back to the concept
1. Move information about ServiceAccount automation from https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#control-plane-details to this page
Preview: https://deploy-preview-38289--kubernetes-io-main-staging.netlify.app/docs/concepts/security/service-accounts/
Issue: #31847
/sig docs
/language en
> Add a new concept page for service accounts

- content/en/docs/concepts/security/service-accounts.md
Cleanup fix for an incorrectly rendered anchor in the [ServiceAccount concept](https://kubernetes.io/docs/concepts/security/service-accounts/#authenticating-service-account-credentials-in-your-own-code-authenticating-in-code)
/sig-docs
> Add a missing anchor pound sign

- content/zh-cn/docs/concepts/architecture/leases.md
Sync with en #38307. See [preview](https://deploy-preview-39428--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/leases/) please.
```
content/zh-cn/docs/concepts/architecture/leases.md
```
> [zh] sync /concepts/architecture/leases.md

- content/es/docs/concepts/security/pod-security-policy.md
Related the issue https://github.com/kubernetes/website/issues/13948
cc: @electrocucaracha
> [es] Add content/es/docs/concepts/security/pod-security-policy.md

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
Add a node indicating that node affinity or a node selector is the preferred way to assign a pod to a node if you aren't trying to bypass the scheduler.  Using nodeName can cause issues that can be otherwise avoided entirely:
- https://github.com/kubernetes/kubernetes/issues/114005
- https://github.com/kubernetes/kubernetes/issues/113907
> Add a note indicating when nodeName should be used

- content/en/docs/concepts/security/pod-security-admission.md
- content/en/docs/reference/access-authn-authz/admission-controllers.md
- content/en/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
- content/en/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
Really mark PSP as removed.
- cut out some references to PSP
- treat PSA as stable (but hint that older releases might provide it - which they do, in beta)
1. [original](https://k8s.io/docs/concepts/security/pod-security-admission/) / [preview](https://deploy-preview-37733--kubernetes-io-vnext-staging.netlify.app/docs/concepts/security/pod-security-admission/)
1. [original](https://k8s.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/) / [preview](https://deploy-preview-37733--kubernetes-io-vnext-staging.netlify.app/docs/tasks/configure-pod-container/enforce-standards-admission-controller/)
1. [original](https://k8s.io/docs/reference/access-authn-authz/admission-controllers/) / [preview](https://deploy-preview-37733--kubernetes-io-vnext-staging.netlify.app/docs/ …
> Update documentation for PodSecurityPolicy removal

- content/en/docs/concepts/security/service-accounts.md
Fixups for PR #38289
Fixes #28285 
Page changed: https://kubernetes.io/docs/concepts/security/service-accounts/
> Fix wording, punctuation and Markdown for ServiceAccount concept page

- content/zh-cn/blog/_posts/2022-05-27-maxunavailable-for-statefulset.md
Part of https://github.com/kubernetes/website/issues/39417
Here is the [preview page](https://deploy-preview-39420--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/05/13/grpc-probes-now-in-beta/).
> [zh-cn] Resync 2022-05-27-maxunavailable-for-statefulset.md

- content/zh-cn/blog/_posts/free-katacoda-kubernetes-tutorials-are-shutting-down.md
Fix #39465. See [preview](https://deploy-preview-39466--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
```
content/zh-cn/blog/_posts/free-katacoda-kubernetes-tutorials-are-shutting-down.md
```
> [zh] Sync blog: free-katacoda-kubernetes-tutorials-are-shutting-down

- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
Sync with en #39452
```
```
See [preview](https://deploy-preview-39459--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node/)
> [zh] sync /scheduling-eviction/assign-pod-node.md

- content/en/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
- Fix a typo
- Put `{{% version-check %}}` in a new line, to keep consistent with other pages
> Fix typo and add blank lines in enforce-standards-admission-controller

- content/en/docs/concepts/workloads/controllers/daemonset.md
Rewrite "How Daemon Pods are scheduled" section of the DaemonSet guide to align with the current state and be more clear.
Issues #39358, #4513.
Signed-off-by: Grigoris Thanasoulas <gregth@arrikto.com>
> Update DaemonSet guide

- content/fr/docs/tasks/inject-data-application/_index.md
- content/fr/docs/tasks/inject-data-application/define-command-argument-container.md
- content/fr/examples/pods/commands.yaml
Hi,
This adds the French translation for the task "Define a Command and Arguments for a Container", from the "Inject Data Into Applications" section. This is the [reference document](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/)
I've also included the example yaml file and updated the section's description to match the English reference, as this is the first task from this section to be translated in French.
Thx,
> [fr] add french translation for task inject-data-application/define-command-argument-container.md

- content/en/docs/concepts/configuration/secret.md
This PR cleans up the "Using secrets as files" section as follows:
1. Add a link to the relevant task section in [Distribute Credentials Securely Using Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume) (Line 204/205)
1. Remove the "Mounted secrets are updated automatically" heading; the content flowed organically from its parent section so the heading is unnecessary.
1. Move the note about SA token secrets to the relevant section as-is, no text changes.
1. In the SA token section, remove a paragraph that was made obsolete by the content of the note. 
/sig docs
/language en
> Clean up using secrets as files section

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
1. Provide a consistent indentation for ordered list preceded with 3 spaces
2. Remove extra spaces
3. Removed redundant blank lines
> Clean up page device-plugins

- content/zh-cn/docs/concepts/workloads/controllers/daemonset.md
Sync with en #39392. See [preview](https://deploy-preview-39491--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/daemonset).
```
content/zh-cn/docs/concepts/workloads/controllers/daemonset.md
```
> [zh] sync /controllers/daemonset.md

- content/en/docs/concepts/cluster-administration/flow-control.md
To address issue https://github.com/kubernetes/website/issues/39512:  track update to APF debug endpoint.
closes: #39512
> update output for APF dump_priority_levels endpoint

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
This PR cleans up the page `content/en/docs/concepts/scheduling-eviction/assign-pod-node.md`.
1. The indentation of list items should be 2 spaces for unordered lists
2. Provide a consistent indentation for ordered list preceded with 3 spaces
> Clean up page assign-pod-node

- content/zh-cn/docs/concepts/cluster-administration/flow-control.md
- change anchors with lower-case letters for consistency with [localization style guide](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E9%93%BE%E6%8E%A5%E9%94%9A%E7%82%B9)
- Remove anchors if the heading has only English text
- Sync with en #39518
```
```
> [zh] sync /cluster-administration/flow-control.md

- content/zh-cn/docs/contribute/localization_zh.md
Try to add anchors to headings in this page. It will be easy to share the localization_zh url.
Before change
```
https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E9%93%BE%E6%8E%A5%E9%94%9A%E7%82%B9
```
After change
```
https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#anchors
```
> [zh] Add anchors to /localization_zh.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_remove-etcd-member.md
Sync with en.
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_remove-etcd-member.md
```
> [zh] sync kubeadm_reset_phase_remove-etcd-member.md

- content/en/examples/examples_test.go
The newly changed `my-scheduler.yaml` breaks the test case. This PR fixes it.
> Fix examples test for newly changed example manifest

- content/zh-cn/blog/_posts/2023-01-05-retroactive-default-storage-class.md
```
content/zh-cn/blog/_posts/2023-01-05-retroactive-default-storage-class.md
```
Preview: https://deploy-preview-38916--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/01/05/retroactive-default-storage-class/
> [zh] sync blog: 2023-01-05-retroactive-default-storage-class

- content/en/docs/concepts/overview/working-with-objects/annotations.md
- content/en/docs/concepts/overview/working-with-objects/labels.md
Tidying for the [Annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/), [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
1. call a manifest a manifest
2. format YAML segment
3. remove extra lines
> Tidy concepts pages within Label and Annotation

- content/en/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md
- Original wording seemed to be tacitly encouraging Prometheus as the preferred monitoring solution, and was confusing to non-native speakers as written.
- Remove direct references to Prometheus.
- Emphasize that the Kubernetes docs are not in the business of telling you how to monitor Kubernetes.
- Note that any monitoring should understand OpenMetrics.
- Link to the CNCF landscape site, picking out the options for anyone who isn't sure what options they have
- Note that the specific choice is part of the overall design of the infrastructure platform.
> 31483: clarify monitoring language

- content/en/docs/tasks/administer-cluster/sysctl-cluster.md
Section called "Enabling Unsafe Sysctls" sounds dangerous, when trying to tell someone that `net.ipv4.ip_unprivileged_port_start` is considered a _safe_ sysctl in current Kubernetes versions.
The generic explanation of "safe and unsafe sysctls" should be renamed more generic, and later subsection about how to actually enable unsafes can retain the pre-existing section name.
> Rename "Enabling Unsafe Sysctls" section

- content/en/docs/tasks/tools/install-kubectl-linux.md
- content/en/docs/tasks/tools/install-kubectl-macos.md
- content/en/docs/tasks/tools/install-kubectl-windows.md
In "Test to ensure the version you installed is up-to-date:", the command "kubectl version --client" is given but on running it on my system it says "This version information is deprecated and will be replaced with the output from kubectl version --short". So I thought it would be best to update in the docs as well.
> Add note about checking kubectl version

- content/en/docs/concepts/services-networking/service.md
These are some miscellaneous changes that I recommend making but that don't really fit in to any other PR.
[preview](https://deploy-preview-39499--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/) / [original](https://k8s.io/docs/concepts/services-networking/service/)
View that PR to see these changes in context.
These changes come after what you can see in #38562, and should not conflict with the changes I'm recommending in #38563.
>  Revise Service concept, part 14

- content/en/docs/concepts/services-networking/service.md
View that PR to see these changes in context.
- revise a section of the Service concept [[preview](https://deploy-preview-38562--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/); [original](https://k8s.io/docs/concepts/services-networking/service/)]
PR #38563 has changes that come in where this PR ends.
> Revise introduction to Service page

- content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
This PR fixes the 'Introduction to Cilium' link in [Use Cilium for NetworkPolicy](https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy/) page.
Fixes: #39606
> Fix Introduction to Cilium link

- content/en/docs/tasks/access-application-cluster/service-access-application-cluster.md
Performed 2 actions:
- Run `npx prettier -w` to remove extra blank lines or add a blank line between paras
- Add a code mark `none` if it is an output
> Clean up /service-access-application-cluster.md

- content/en/docs/tasks/tools/install-kubectl-linux.md
- content/en/docs/tasks/tools/install-kubectl-macos.md
Update kubectl-convert plugin installation.
- Add a missing section for removing the leftover files for linux setup
- Fix typos in macos setup
> Update kubectl install documentation

- content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md
When I resync this page to Chinese content, I found that the indentation of unordered list items is 3 spaces, which should be 2 spaces.
So I clean up the page.
> Clean up page distribute-credentials-secure

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
- content/en/docs/reference/glossary/kubeadm.md
- static/_redirects
The redirection entries in `static/_redirects` contains some very old data.
This PR is part of a series of actions to clean it up.
> Remove redirect entries for docs/admin/... pages

- content/en/docs/contribute/localization.md
* Add a brief explanation of when country codes are being used along with the language codes in Kubernetes documentation.
Fixes #38451 
/cc @a-mccarthy
> [en] Document when country codes are used in the Kubernetes documentation

- content/en/docs/reference/labels-annotations-taints/_index.md
- content/en/docs/tutorials/security/seccomp.md
seccomp annotation will become non-functional in v1.27, which will be now reflected in the documentation as well.
Ref: https://github.com/kubernetes/kubernetes/pull/114947, https://github.com/kubernetes/enhancements/issues/135, https://github.com/kubernetes/kubernetes/issues/91286
cc @kubernetes/sig-node-pr-reviews @liggitt
> Update seccomp docs for v1.27

- content/en/docs/concepts/architecture/cloud-controller.md
This PR wraps the long lines in the cloud-controller page where appropriate. It also removes some useless empty lines, fixes a numbered list by removing explicit numbering.
> Normalize cloud-controller concept page

- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
- wrap text
- don't check whether Kubernetes supports this; it just does
- emphasize optional ConfigMap references
- other tidying (see 2nd commit)
> Revise “Configure a Pod to Use a ConfigMap” task

- content/ko/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
Translated [Translate a Docker Compose File to Kubernetes Resources](https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/) in Korean.
쿠버네티스 문서/태스크/파드와 컨테이너 설정 항목의 미번역된 [Translate a Docker Compose File to Kubernetes Resources](https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/)를 한국어로 번역하였습니다.
> [ko] Translate tasks-translate-compose-kubernetes.md into Korean

- content/ko/docs/concepts/services-networking/cluster-ip-allocation.md
Translate [Service ClusterIP allocation](https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/) in Korean.
쿠버네티스 문서/개념/서비스, 로드밸런싱, 네트워크 항목의 미번역된 [Service ClusterIP allocation](https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/)을 한국어로 번역하였습니다.
> [ko] Translate concepts-services-networkings-cluster-ip-allocation.md into Korean

- content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md
This PR adds maximum and minimum permitted values for PriorityClass
Fixes: #35640
  **_Additional Info_**
   **Q) How the specified values were derived?**
      A) Int32 has value range of  −2,147,483,648 to 2,147,483,647 (i.e. −(2^31) to 2^31 − 1)
That makes the permitted values for PriorityClass from −2,147,483,648 to 1,000,000,000
> Add minimum and maximum values for PriorityClass

- content/ko/docs/tasks/configure-pod-container/assign-cpu-resource.md
- content/ko/examples/pods/resource/cpu-request-limit-2.yaml
- content/ko/examples/pods/resource/cpu-request-limit.yaml
Translated [Assign CPU Resources to Containers and Pods](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/) in Korean.
Also added two example resources for document examples.
쿠버네티스 문서/태스크/파드와 컨테이너 설정 항목의 미번역된 [Assign CPU Resources to Containers and Pods](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/)을 한국어로 번역하였습니다.
추가적으로 문서의 예시를 위해 2개의 예시 리소스 파일을 추가하였습니다.
> [ko] Translate task-assign-cpu-resource.md into Korean

- content/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure.md
This pr resyncs page distribute-credentials-secure with upstream en page.
By the way, the indentation of list items should be 2 spaces for unordered lists.
> [zh] Resync page distribute-credentials-secure

- content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
This PR fixes the 'Cilium Kubernetes Installation Guide' link in Deploying Cilium for Production Use [section](https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy/#deploying-cilium-for-production-use).
Fixes: #39627
> Fix Cilium Kubernetes Installation Guide link

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/glossary/service.md
View that PR to see these changes in context.
- improve glossary entry for Service [[preview](https://deploy-preview-38054--kubernetes-io-main-staging.netlify.app/docs/reference/glossary/?fundamental=true&networking=true#term-service)]
> Revise glossary entry for Service

- content/en/blog/_posts/2022-12-12-kubernetes-release-artifact-signing.md
- content/en/docs/tasks/administer-cluster/certificates.md
Don't rely on using https://storage.googleapis.com/kubernetes-release/ - use the redirector service instead.
This fixes recent blog articles and the English docs. Helps with https://github.com/kubernetes/kubernetes/issues/116019.
> Use https://dl.k8s.io/

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
Part of: https://github.com/kubernetes/website/issues/39417
The preview pages:
- https://deploy-preview-39646--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver/
- https://deploy-preview-39646--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager/
> [zh-cn] Resync kubeadm reference page

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
- content/en/docs/reference/glossary/kubeadm.md
- content/en/docs/reference/glossary/kubectl.md
- content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
- static/_redirects
This is the second PR for cleaning up old redirection entries that are more than 4 years old. The `docs/user-guide` directory was removed in June, 2018. It should be okay to remove these entries since those old bookmarks are no longer useful anyway.
> Clean up redirects for 'docs/user-guide/...' entries

- content/en/docs/concepts/workloads/controllers/deployment.md
This PR cleans up page `content/en/docs/concepts/workloads/controllers/deployment.md`.
The indentation of list items should be 2 spaces for unordered lists.
> Clean up page deployment

- content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
- content/en/docs/tasks/configure-pod-container/configure-pod-initialization.md
This PR do these things:
1. Add code block in pages
2. Fix typo in page `content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md`
3. Removed redundant blank lines
4. Wrap the long lines manually for future  change tracking
5. Format YAML section
> Add code block in page configure-persistent-volume-storage, configure-pod-configmap.md, configure-pod-initialization

- content/en/docs/contribute/style/style-guide.md
The subsection Headings and Titles of this document contains a dos and don'ts table that is not rendering correctly do to a few surplus line breaks inside the Markdown for the table, causing a single cell to render into several different cells instead. This PR removes these spaces so the table renders correctly.
> [en] Remove excessive line breaks from table in docs/contribute/style/style-guide.md

- content/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
In Japanese page,it says old method  ```curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -``` .   
But,recent versions of Ubuntu,they shows warning about apt-key add .  
and I also see English page, it says newer method.   
so I copied English page's code and translate some comments in Japanese.
> [ja] Update install-kubeadm.md

- content/en/docs/concepts/windows/intro.md
- Related Issue : #39616 
Some links are accessible only with subsection ID, not full link.
They exist in same page.
> Update to use subsectionID instead of full-link in "Windows containers in Kubernetes" page.

- content/zh-cn/docs/tasks/access-application-cluster/connecting-frontend-backend.md
- content/zh-cn/docs/tasks/access-application-cluster/create-external-load-balancer.md
- content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
- content/zh-cn/docs/tasks/access-application-cluster/service-access-application-cluster.md
- content/zh-cn/docs/tasks/access-application-cluster/web-ui-dashboard.md
This PR resyncs these page:
- `content/zh-cn/docs/tasks/access-application-cluster/connecting-frontend-backend.md`
-  `content/zh-cn/docs/tasks/access-application-cluster/create-external-load-balancer.md`
-  `content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md`
-  `content/zh-cn/docs/tasks/access-application-cluster/service-access-application-cluster.md`
-  `content/zh-cn/docs/tasks/access-application-cluster/web-ui-dashboard.md`
The diferences between the zh and en files are small, so I commit them using one PR.
> [zh] resync page in tasks/access-application-cluster

- content/en/docs/concepts/workloads/pods/_index.md
Replaces `priviledged` with `privileged`.
> Fix misspelling on Pods page

- content/zh-cn/docs/concepts/architecture/cloud-controller.md
This PR resynced page `content/zh-cn/docs/concepts/architecture/cloud-controller.md` according to the upstream page.
> [zh] resync page cloud-controller

- content/zh-cn/docs/concepts/scheduling-eviction/_index.md
- content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/zh-cn/docs/concepts/scheduling-eviction/resource-bin-packing.md
This PR resyncs these pages:
- `content/zh-cn/docs/concepts/scheduling-eviction/_index.md`
- `content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md`
- `content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md`
- `content/zh-cn/docs/concepts/scheduling-eviction/resource-bin-packing.md`
> [zh] resync page in scheduling-eviction (Part II)

- data/i18n/en/en.toml
- layouts/shortcodes/cve-feed.html
This PR fixes the two issues discussed in https://github.com/kubernetes/website/pull/38579, see the following list:
- **Discussion**: https://github.com/kubernetes/website/pull/38579#discussion_r1116992896, 
**Commit**: https://github.com/kubernetes/website/commit/3d850f6b9a79115ca5db3c5dea0a67882b17e268
- **Discussion**: https://github.com/kubernetes/website/pull/38579#discussion_r1116996184
**Commit**: https://github.com/kubernetes/website/commit/aa9f17ed0a83dceefacd2be6347348b9d661052c
/cc @kbhawkey
/cc @PushkarJ @nehaLohia27 
/kind cleanup
/sig security
> CVE feed cleanup on i18n data and shortcode compliance check

- content/en/docs/reference/labels-annotations-taints/_index.md
Documented `volume.beta.kubernetes.io/storage-class` annotation.
Fixes #39704 
> Add volume.beta.kubernetes.io/storage-class annotation

- content/fr/docs/tasks/inject-data-application/distribute-credentials-secure.md
- content/fr/examples/pods/inject/pod-multiple-secret-env-variable.yaml
- content/fr/examples/pods/inject/pod-secret-envFrom.yaml
- content/fr/examples/pods/inject/pod-single-secret-env-variable.yaml
- content/fr/examples/pods/inject/secret-envars-pod.yaml
- content/fr/examples/pods/inject/secret-pod.yaml
- content/fr/examples/pods/inject/secret.yaml
Hi,
This adds the French translation for the task "Distribute Credentials Securely Using Secrets", from the "Inject Data Into Applications" section. This is the [reference English document](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/). 
It includes the necessary example files (in content/fr/examples/pods/inject/) for that particular task.
Thx,
> [fr] add french translation for task inject-data-application/distribute-credentials-secure.md

- content/en/docs/tutorials/security/cluster-level-pss.md
- content/en/docs/tutorials/security/ns-level-pss.md
- content/en/examples/security/example-baseline-pod.yaml
- content/en/examples/security/kind-with-cluster-level-baseline-pod-security.sh
- content/en/examples/security/kind-with-namespace-level-baseline-pod-security.sh
Update [Apply Pod Security Standards at the Cluster Level](k8s.io/docs/tutorials/security/cluster-level-pss/) and [Apply Pod Security Standards at the Namespace Level](https://k8s.io/docs/tutorials/security/ns-level-pss/) along with supporting content.
- assume that kind deploys a cluster with PSA support
- don't make a manifest in `/tmp`; write it through a pipe or fetch it via HTTP
- make it clear that the PSA example Pods start OK, just with a warning
- other tidying
and
- change the scripted versions to clean up afterwards
Previews: https://deploy-preview-37587--kubernetes-io-main-staging.netlify.app/docs/tutorials/security/
/sig auth
> Revise tutorials for Pod Security Admission

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/controller-manager-leader-migration.md
See https://github.com/kubernetes/website/pull/37667
This should be merged after https://github.com/kubernetes/kubernetes/pull/113534.
- This was merged in v1.27 release cycle.
- The KEP link: https://github.com/kubernetes/enhancements/issues/2436
> removed ControllerManagerLeaderMigration in v1.27

- README.md
**Changes :**
Update Swagger specification to `Swagger specification(currently known as OpenAPI specification) ` in README.md file for more clarity.
> [en] Update outdated update-readme-doc

- content/en/docs/concepts/workloads/pods/pod-qos.md
The "Pod Quality of Service Classes" page contained a word two times in a row, where it should only have existed once.
> Removed duplicate word

- content/fr/docs/tasks/access-application-cluster/web-ui-dashboard.md
Description:
Update Deploying the Dashboard UI in Deploy and Access the Kubernetes Dashboard (Tableau de bord (Dashboard)) with the new link.
Proposed Solution:
Updated link from 
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml`
to
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/charts/recommended.yaml`
https://kubernetes.io/fr/docs/tasks/access-application-cluster/web-ui-dashboard/#d%C3%A9ploiement-du-tableau-de-bord
> [fr] Replace old link with new link in deploying the dashboard ui doc

- content/en/blog/_posts/2023-03-10-forensic-container-analysis/index.md
This adds a blog article how to use to do forensic analysis on a container checkpoint.
https://github.com/kubernetes/enhancements/issues/2008
> Add blog post about forensic container analysis

- content/ja/blog/_index.md
Improvement suggestions for the following
- Blogs --> Kubernetesブログ
- The preview page: [Link](https://deploy-preview-39650--kubernetes-io-main-staging.netlify.app/ja/blog/)
> [ja] Translate title and linkTitle for Blogs page

- content/ja/docs/concepts/cluster-administration/cluster-administration-overview.md
- content/ja/docs/concepts/cluster-administration/manage-deployment.md
- content/ja/docs/concepts/configuration/manage-resources-containers.md
- content/ja/docs/reference/command-line-tools-reference/feature-gates.md
- content/ja/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
- content/ja/docs/tasks/debug/debug-cluster/local-debugging.md
- content/ja/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md
Fixes https://github.com/kubernetes/website/issues/38797
This PR changes the paths of debug pages. The example shown on the issue is below.
- Change path and add "/ja"
- e.g.: /docs/tasks/debug-application-cluster/resource-usage-monitoring/ -> /ja/docs/tasks/debug/debug-cluster/resource-usage-monitoring/
> [ja] Change paths of debug pages (case 3)

- content/en/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/examples/pods/pod-with-scheduling-gates.yaml
Ref https://github.com/kubernetes/enhancements/issues/3521.
> Doc for Beta feature PodSchedulingReadiness

- content/en/docs/concepts/services-networking/service.md
as per the [docs](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/services-networking/service.md?plain=1#L697) this is no longer an alpha feature, but stable.
Either that or I don't understand it well as a k8s noobie and it should be clarified 😄
> adjust docs for feature maturity

- content/es/docs/concepts/configuration/manage-resources-containers.md
- content/es/docs/concepts/configuration/secret.md
- content/es/docs/concepts/overview/working-with-objects/labels.md
- content/es/docs/concepts/storage/volumes.md
- content/es/docs/concepts/workloads/controllers/statefulset.md
- content/es/docs/tutorials/hello-minikube.md
> Replace k8s.gcr.io references with registry.k8s.io for es

- content/en/blog/_posts/2022-12-05-forensic-container-checkpointing/index.md
This adds a link to the follow-up article "Forensic Container Analysis" to the already existing article "Forensic Container Checkpointing".
/hold
See #39759
> Add link to checkpointing follow-up article

- content/ja/docs/concepts/workloads/controllers/daemonset.md
- content/ja/docs/tasks/configure-pod-container/assign-pods-nodes.md
Related PR: https://github.com/kubernetes/website/pull/38800
We would like to use English heading IDs to link the following pages.
https://kubernetes.io/ja/docs/concepts/workloads/controllers/daemonset/
https://kubernetes.io/ja/docs/tasks/configure-pod-container/assign-pods-nodes/
In this PR, I set English IDs for all Japanese headings in the target pages.
The purpose of this PR only sets IDs, not updating the contents and the heading names.
en:
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/
> [ja] Set heading IDs in daemonset.md and assign-pods-nodes.md

- content/ja/docs/concepts/architecture/cri.md
- content/ja/docs/concepts/architecture/garbage-collection.md
- content/ja/docs/concepts/cluster-administration/addons.md
- content/ja/docs/concepts/cluster-administration/proxies.md
- content/ja/docs/concepts/cluster-administration/system-logs.md
- content/ja/docs/concepts/containers/container-lifecycle-hooks.md
- content/ja/docs/concepts/containers/runtime-class.md
- content/ja/docs/concepts/extend-kubernetes/api-extension/_index.md
- content/ja/docs/concepts/policy/resource-quotas.md
This PR updates the page weights under the 5 sections in concepts.
This pr will be the last for the update of page weights under the ja/docs/concepts.
- content/ja/docs/concepts/extend-kubernetes
- content/ja/docs/concepts/containers
- content/ja/docs/concepts/architecture
- content/ja/docs/concepts/cluster-administration
- content/ja/docs/concepts/policy
This updates the page order.
Related: #37470 #37471 #37473 #37484 #23929
The files under policy were updated long ago in en.
> [ja] Update page weights under 5 sections of concepts

- data/announcements/scheduled.yaml
This replaces the k8s.gcr.io freeze announcement with a k8s.gcr.io redirect announcement ref https://github.com/kubernetes/website/pull/39895
Holding for approval from other steering members and reviews from everyone
/hold
> preempt registry freeze announcement with redirect announcement

- content/zh-cn/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
- content/zh-cn/docs/tutorials/stateful-application/cassandra.md
Hugo v0.111.x will throw an error if shortcodes are not correctly closed. (https://github.com/gohugoio/hugo/issues/10675)
This PR brings fixes this issue for the zh-ch locale.
> [zh-cn] Shortcode fixes

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
Just replaced #scheduled-by-default-scheduler with #how-daemon-pods-are-scheduled as stated in issue #39864
> fixed the outdated link

- content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
Documentation prose refers to the file named `.properties`, the correct file name is `application.properties`.
> Fix reference to file name in generated configMap

- content/en/blog/_posts/2021-04-20-annotating-k8s-for-humans.md
- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/using-api/cel.md
- content/en/docs/tasks/administer-cluster/encrypt-data.md
Hugo v0.111.x will throw an error if shortcodes are not correctly closed. (https://github.com/gohugoio/hugo/issues/10675)
This PR brings fixes this issue for the en locale.
> [en] Shortcode fixes

- content/en/docs/concepts/policy/resource-quotas.md
- content/zh-cn/docs/concepts/policy/resource-quotas.md
Quota the variable `<storage-class-name>` for better readability.
> Quote a variable for readability

- OWNERS_ALIASES
I started contributing to the k8s-website almost a year ago and have been amazed by the k8s workflow. I've learned a lot from the contributors here 😄 , and I would like to contribute even more in the future and help guide new contributors.
Would it be possible for me to be approved to approve zh docs? Here are some statistics of my contributions to the website:
- [PRs I authored](https://github.com/kubernetes/website/pulls/windsonsea): 600+, including [58 PRs](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Awindsonsea+label%3Alanguage%2Fen+is%3Aclosed) related to English source
- [PRs I reviewed](https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3A%40me): 250+
- [16 Issues I authored](https://github.com/kubernetes/website/issues?q=is%3Aissue+author% …
> Add windonsea to sig-docs-zh-owners

- content/en/docs/reference/issues-security/official-cve-feed.md
- layouts/_default/cve-feed.rss.xml
This PR fixes https://github.com/kubernetes/sig-security/issues/77.
~~It's based on the commits of this PR https://github.com/kubernetes/website/pull/38579 and thus should be merged after. Only the last commit is unique.~~
~~/hold~~
I choose the value of the fields based on this spec https://validator.w3.org/feed/docs/rss2.html, maybe some choices can be discussed (like `guid`).
Here is an extract of what it looks like:
```xml
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>Auto-refreshing Official CVE Feed</title>
<link>http://localhost:1313/docs/reference/issues-security/official-cve-feed/</link>
<description>Auto-refreshing official CVE feed for Kubernetes repository</description>
<generator>Hugo -- gohugo.io</generator>
<language>en-US</language> …
```
> CVE feed: add RSS feed format

- content/de/docs/setup/_index.md
Hugo v0.111.x will throw an error if shortcodes are not correctly closed. (https://github.com/gohugoio/hugo/issues/10675)
This PR brings fixes this issue for the de locale.
> [de] Shortcode fixes

- content/zh-cn/docs/concepts/services-networking/endpoint-slices.md
- content/zh-cn/docs/concepts/services-networking/topology-aware-hints.md
- content/zh-cn/docs/concepts/storage/persistent-volumes.md
Related to task-3 of issue https://github.com/kubernetes/website/issues/39985.
content/en/docs/concepts/services-networking/endpoint-slices.md
content/en/docs/concepts/services-networking/topology-aware-hints.md
> [zh] sync endpoint-slices,persistent-volumes,topology-aware-hints

- content/en/blog/_posts/2023-03-10-image-registry-change.md
Fixes issue Broken link in blog: k8s.gcr.io Redirect to registry.k8s.io - What You Need to Know #40071
> Fix broken link in blog: k8s.gcr.io Redirect to registry.k8s.io - What You Need to Know

- content/en/docs/tasks/manage-gpus/scheduling-gpus.md
I found this typo just when I was about to sync this page for localization.
> Fix a minor typo in scheduling-gpus.md

- content/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure.md
Sync text with en:
```
content/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure.md
```
related: https://github.com/kubernetes/website/issues/39983
> [zh-cn] sync distribute-credentials-secure.md

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
The API group was bumped to make some incompatible internal changes and the user-visible renaming of PodScheduling to PodSchedulingContext.
> dynamic resource allocation: update for 1.27

- content/fr/docs/tasks/inject-data-application/define-interdependent-environment-variables.md
- content/fr/examples/pods/inject/dependent-envars.yaml
Hi,
This adds the French translation for the task 'Define Dependent Environment Variables', from the "Inject Data Into Applications" section. This is the [reference document](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/).
I also copied the example yaml file over from the reference English example folder.
This completes the French translation of the 'Inject Data Into Applications' section.
> [fr] add french translation for task 'inject-data-application/define-interdependent-environment-variables.md'

- content/ja/docs/contribute/localization.md
- content/ja/docs/contribute/style/hugo-shortcodes/index.md
This updates the page weights under content/ja/docs/contribute and the pages are shown with new order.
Related: #37480, #19576
The localization.md was updated long ago in en.
Though the page is made for Japanese translation and it is different from en, I thought that the weight should be the same as en.
> [ja] Update page weights under content/ja/docs/contribute

- content/ja/docs/contribute/review/for-approvers.md
Fixed for-approvers.md to be the same as en.
Related en's updates
- https://github.com/kubernetes/website/pull/34721/files#diff-35a71f7ed28fe8556c24de2f2eb155f7a149fc70bfe6dfa5a06e6c823097ffdf
- https://github.com/kubernetes/website/pull/36899/files#diff-35a71f7ed28fe8556c24de2f2eb155f7a149fc70bfe6dfa5a06e6c823097ffdf
I have confirmed that older en's PRs have already been applied into ja.
> [ja] Update content/ja/docs/contribute/review/for-approvers.md.

- content/ja/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
fix skew shortcode, typo and syntax error
> [ja] fix kubeadm-cert.md

- content/ja/docs/reference/glossary/kubectl.md
This PR fixed the link of kubectl tooltip from en to ja.
In currently, link to https://kubernetes.io/docs/reference/kubectl/.
After fix, link to https://kubernetes.io/ja/docs/reference/kubectl/.
Example:
- Click "kubectl" at the following page:
https://deploy-preview-39991--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/architecture/nodes/#manual-node-administration
- Jump to Japanese page:
https://deploy-preview-39991--kubernetes-io-main-staging.netlify.app/ja/docs/reference/kubectl/
Fixes: #39990
> [ja] update the link from kubectl tooltip

- content/en/blog/_posts/2023-03-17-kubernetes-1.27-deprecations-and-removals.md
Only tweak long lines, without any other changes.
```
content/en/blog/_posts/2023-03-17-kubernetes-1.27-deprecations-and-removals.md
```
> Tweak line wrappings in blog 03-17

- content/zh-cn/blog/_posts/2023-03-17-kubernetes-1.27-deprecations-and-removals.md
```
content/zh-cn/blog/_posts/2023-03-17-kubernetes-1.27-deprecations-and-removals.md
```
Fixes #40120
> [zh] sync blog: kubernetes-1.27-deprecations-and-removals.md

- content/ko/docs/setup/_index.md
- content/ko/docs/setup/best-practices/certificates.md
- content/ko/docs/setup/best-practices/cluster-large.md
- content/ko/docs/setup/best-practices/enforcing-pod-security-standards.md
- content/ko/docs/setup/production-environment/_index.md
- content/ko/docs/setup/production-environment/tools/kops.md
- content/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/ko/docs/setup/production-environment/tools/kubespray.md
- content/ko/docs/setup/production-environment/turnkey-solutions.md
Related Issue: #38458
Updated outdated files in `content/en/docs/setup/`.
**9 files to be modified**
> [ko] Update outdated files in dev-1.26-ko.1 (M134-M142)

- content/ko/docs/concepts/services-networking/dns-pod-service.md
- Related issue: https://github.com/kubernetes/website/issues/38458
- 일부 매끄럽지 못한 번역을 수정했습니다. Related https://github.com/kubernetes/website/issues/38458#issuecomment-1437736503
> -  [ ] M59. content/en/docs/concepts/services-networking/dns-pod-service.md | 79(+M) 61(-)
> [ko] Update outdated files in dev-1.26-ko.1 (M59)

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/configure-pod-container/security-context.md
> Update ReadWriteOncePod feature to beta

- content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
Related to `task-29` of issue #39987 
```
content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
```
See [preview](https://deploy-preview-40139--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver/) please.
> [zh] sync /command-line-tools-reference/kube-apiserver.md

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
In the English version, we have the following:
```
ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks
```
but in the Chinese version, it is translated to:
```
ValidatingAdmissionWebhooks 和 ValidatingAdmissionWebhooks
```
the PR will fix this.
> fix translations in mutating-webhook-configuration-v1.md

- content/en/blog/_posts/2023-03-17-kubernetes-1.27-deprecations-and-removals.md
To include https://github.com/kubernetes/kubernetes/pull/114017 in the kubernetes-1.27-deprecations-and-removals blog.
> blog update: add removal of --container-runtime of kubelet

- content/en/docs/tutorials/services/pods-and-endpoint-termination-flow.md
Duplicate paragraphs in tutorials/services/pods-and-endpoint-termination-flow
Under the "**Termination process for Pods and their endpoints**"  section of the page https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/ .This tutorial explains the flow of Pod termination in connection with the corresponding endpoint state and removal._" repeats in the end of the first and the beginning of the second paragraph. This was raised in #40127. This PR is intended to close the issue #40127
> Remove duplicate paragraph

- content/ko/docs/tasks/configure-pod-container/extended-resource.md
- content/ko/examples/pods/resource/extended-resource-pod-2.yaml
- content/ko/examples/pods/resource/extended-resource-pod.yaml
Translated [Assign Extended Resources to a Container](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/) in Korean.
쿠버네티스 문서/태스크/파드와 컨테이너 설정 항목의 미번역된 [Assign Extended Resources to a Container](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/)를 한국어로 번역하였습니다.
> [ko] translate extended-resource.md into Korean

- content/en/docs/concepts/security/service-accounts.md
As per the following [discussion](https://kubernetes.slack.com/archives/C0EN96KUY/p1676957078025019) under the sig-auth slack channel. Added the word `External applications` under the [Service Account Token Secrets](https://kubernetes.io/docs/concepts/security/service-accounts/#get-a-token)
> Improvement: Added the Note for External applications.

- content/en/docs/concepts/architecture/cloud-controller.md
What's next section in the [cloud-controller.md](https://kubernetes.io/docs/concepts/architecture/cloud-controller/) has wrong format as well as changing some text to brief one.
Resolves : #38128
> Correcting format of cloud-controller-md What's Next section

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
add doc for KEP 3668 https://github.com/kubernetes/enhancements/issues/3668
add doc in service concepts page to describes the behavior of the new Feature ServiceNodePortStaticSubrange, and the problems it solves
> add doc for ServiceNodePortStaticSubrange

- content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
- content/ja/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
Hugo v0.111.x will throw an error if calling a shortcode within a fenced code block. (https://github.com/gohugoio/hugo/issues/10819)
This PR brings fixes this issue for the ja locale.
> [ja] Shortcode fixes

- content/ja/docs/setup/best-practices/certificates.md
- content/ja/docs/setup/best-practices/cluster-large.md
- content/ja/docs/setup/best-practices/multiple-zones.md
- content/ja/docs/tutorials/services/source-ip.md
This updates the page weights under the following.
- content/ja/docs/setup
- content/ja/docs/tutorials
Related: #37482, #37488, #23498
The en's multiple-zones.md was updated long ago at #23498.
> [ja] Update page weights under setup and tutorials

- content/ja/docs/concepts/architecture/garbage-collection.md
- content/ja/docs/reference/glossary/garbage-collection.md
This PR adds the garbage-collection in glossary of ja.
It is also used in content/ja/docs/concepts/architecture/garbage-collection.md.
Target pages
- https://deploy-preview-39948--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/architecture/garbage-collection/
- https://deploy-preview-39948--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?fundamental=true#term-garbage-collection
> [ja] add garbage-collection in glossary.

- content/en/docs/reference/networking/virtual-ips.md
This is an update for a feature going to beta, so I assume it belongs on `dev-1.27`, but that branch doesn't seem to be up-to-date? In particular, it doesn't have #38435, which this rewrites.
(I moved the feature-specific section because it seemed to make more sense to talk about that first now, since it's enabled by default.)
/cc @sftim @aojea
> Update iptables perf / KEP-3453 discussion for 1.27

- content/zh-cn/docs/concepts/scheduling-eviction/kube-scheduler.md
- content/zh-cn/docs/concepts/scheduling-eviction/pod-priority-preemption.md
- content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
SInce the PR changed a lot of files, I seperate them into two PR, the other one is #39677.
This PR resync these pages:
- `content/zh-cn/docs/concepts/scheduling-eviction/kube-scheduler.md`
- `content/zh-cn/docs/concepts/scheduling-eviction/pod-priority-preemption.md`
- `content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md`
> [zh] resync page in scheduling-eviction

- content/zh-cn/blog/_posts/2022-05-23-service-ip-dynamic-and-static-allocation.md
- content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
For fluent Chiness reading
modified:   content/zh-cn/blog/_posts/2022-05-23-service-ip-dynamic-and-static-allocation.md
modified:   content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
Thanks
> [zh] for fluent Chiness reading(content/zh-cn/docs/reference/kubernetes-api/extend-resources)

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/using-api/api-concepts.md
Replaces #39195
Update docs for Server Side Field Validation graduation to GA
KEP: https://github.com/kubernetes/enhancements/issues/2885
So far, it's merely a rebase of the other PR.
/assign @sftim
> docs for field validation GA #39715

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/concepts/workloads/pods/disruptions.md
- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
- content/en/docs/tasks/job/pod-failure-policy.md
- content/en/examples/controllers/job-pod-failure-policy-config-issue.yaml
Updates the documentation about the fix for Kubelet in 1.27 to transition all deleted pods into a terminal phase: https://github.com/kubernetes/kubernetes/pull/115331.
In particular, this solves the known issue for Jobs using pod failure policy in 1.26, that deleted pods could get stuck in the pending phase: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures#proposed-solution-for-the-3rd-scenario.
> Update docs for KEP3329: "Retriable and non-retriable Pod failures for jobs

- content/en/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive.html
- content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
- content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
- content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
- content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html
- data/i18n/en/en.toml
- layouts/shortcodes/katacoda-removal.html
Since we [aren't having a sitewide banner](https://github.com/kubernetes/website/pull/39257#issuecomment-1441430171), I've added a note on pages with interactive tutorials on them. Based on [this list](https://github.com/kubernetes/website/issues/33936) @reylejano put together.
The copy is from @sftim's PR https://github.com/kubernetes/website/pull/39257.
> Adding katacoda removal notices on pages with interactive tutorials

- data/i18n/bn/bn.toml
Localizes `data/i18n/bn/bn.toml` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/kubernetes/website/issues/31677
> [bn] Localizes data/i18n/bn/bn.toml

- content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
The current instructions assume tee creates a file with global read permission. This may not always be the case, and we may ends up creating a bash completion file that is only usable by the root user
Adding a line to add the relevant file permission
> Fix kubectl auto complete not usable by non-root user sometimes

- content/en/docs/concepts/services-networking/service.md
Redo headings for port definitions
> Tweak headings for port definitions within Service concept

- content/en/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
Remove typo (i.e., replace full stop `.` with a comma `,`) in [document](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#nodeselectorrequirement-v1-core).
> Remove typo in documentation

- content/ja/docs/concepts/scheduling-eviction/assign-pod-node.md
Fix for the following commit :
- [fixed the outdated link](https://github.com/kubernetes/website/pull/39936/commits/64af02f2817d5103fb3d2a35d032781af2548889)
Deploy preview:
- https://deploy-preview-40124--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/scheduling-eviction/assign-pod-node/
> [ja] fixed the outdated link 

- content/en/docs/tasks/administer-cluster/sysctl-cluster.md
Non-init net namespaces are no longer allowed to change `net.netfilter.nf_conntrack_max` and `net.netfilter.nf_conntrack_expect_max`, as addressed in this [patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2671fa4). Fix the doc to reflect this.
> Fix docs around nf_conntrack sysctl

- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
Info about  `Mounted ConfigMaps are updated automatically` is added twice at these two places
1. https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically
2. https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically-1
deleted the second occurrence.
> Deleted duplicate info in configure-pod-configmap

- content/zh-cn/docs/concepts/architecture/cloud-controller.md
- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/concepts/services-networking/endpoint-slices.md
This PR resync these pages under `/concepts` referring to upstream en page: 
```
content/zh-cn/docs/concepts/architecture/cloud-controller.md
content/zh-cn/docs/concepts/services-networking/endpoint-slices.md
```
> [zh]sync pages cloud-controller,manage-resources-containers,endpoint-slices

- content/zh-cn/docs/reference/kubernetes-api/other-resources/_index.md
- content/zh-cn/docs/reference/kubernetes-api/other-resources/validating-admission-policy-binding-list-v1alpha1.md
Add two zh pages by syncing with en version:
```
content/zh-cn/docs/reference/kubernetes-api/other-resources/_index.md
content/zh-cn/docs/reference/kubernetes-api/other-resources/validating-admission-policy-binding-list-v1alpha1.md
```
See [preview](https://deploy-preview-40322--kubernetes-io-main-staging.netlify.app//zh-cn/docs/reference/kubernetes-api/other-resources/).
> [zh] sync /kubernetes-api/other-resources/

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_all.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_show-join-command.md
Sync two files:
- One is the first file listed in `task-16` of issue #39987, 
which is missing in PR #40244
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_all.md
```
- The other is a new zh page:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_show-join-command.md
```
> [zh] sync kubeadm_init_phase_show-join-command.md

- content/en/docs/tasks/configure-pod-container/user-namespaces.md
This PR fixes the issue noticed by @sftim here: https://github.com/kubernetes/website/pull/40264#discussion_r1147974619.
While we are there, we also change pod.spec to pod spec.
Opening in a new PR as @sftim seems to prefer that, let's see if these PRs not create conflicts with each other... :crossed_fingers:
> Remove "new" word in userns documentation

- content/en/docs/contribute/review/for-approvers.md
Fixes https://github.com/kubernetes/website/issues/36294
> Add guidance for reviewers about squashing commits

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/using-api/api-concepts.md
Ref https://github.com/kubernetes/enhancements/issues/3157
> Streaming lists documentation

- content/en/docs/concepts/cluster-administration/flow-control.md
In the "API Priority and Fairness" documentation, the "cancelled" reason for rejection is not documented. This PR adds this to the documentation.
Closes #36894
> Add the "cancelled" reason for rejection in docs

- content/ja/docs/concepts/workloads/controllers/daemonset.md
[pod-selector](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#pod-selector) is represented as follow:
> The .spec.selector must match the .spec.template.metadata.labels. Config with these two not matching will be rejected by the API.
> [ja] Remove stale information about pod selector

- content/ja/docs/reference/kubectl/_index.md
This PR updates content/ja/docs/reference/kubectl/_index.md.
Update Summary:
- "In-cluster authentication and namespace overrides" section is added.
- The position is changed in operations table.
- The resource types table is updated.
Fixes: #40136
> [ja] update kubectl index

- content/en/docs/reference/_index.md
- content/en/docs/reference/config-api/apiserver-config.v1beta1.md
This PR adds the configuration API reference for `apiserver.config.k8s.io/v1beta1`.
Note this configuration API is targeting main. We will need to refresh it after 1.27 is out.
Related: #40320
> Add apiserver v1beta1

- content/zh-cn/docs/setup/production-environment/tools/kubespray.md
fix url 404
https://github.com/kubernetes-sigs/kubespray/tree/master/contrib/terraform/metal
to
https://github.com/kubernetes-sigs/kubespray/tree/master/contrib/terraform/equinix
under this page
https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubespray/
> [zh-cn] fix Equinix Metal url 404

- data/announcements/scheduled.yaml
Really we probably should have shown this starting on the 20th or so, and there is no EU 2023 banner ...
And EU 2023 is sold out anyhow.
If we need to add an EU banner, we can, but in the meantime we should keep running a banner for the registry redirect.
> show redirect-after banner now

- OWNERS_ALIASES
This PRs adds reviewers and approvers for the sig-docs-es aliases. All of new people are already added to the GitHub org.
/cc @92nqb @krol3 
/assign @electrocucaracha @raelga
> Add more owners and approvers to sig-docs-es aliases

- content/en/blog/_posts/2023-03-23-kubescape-validating-admission-policy-library.md
- content/en/blog/_posts/2023-04-05-kubescape-validating-admission-policy-library.md
This blog post introduces a library of Validating Admission Policies built by converting Kubescape controls from Rego to CEL.
> Add blog about CEL admission control library

- Makefile
`make container-serve` fails with `Error: open : no such file or directory` on SELinux enabled systems. Fix this by adding the `ro,Z` suffix to the volume mount to label the content with a read only private unshared label.
> Fix container-serve on SELinux systems

- content/en/docs/concepts/overview/working-with-objects/finalizers.md
Remove redundant information about finalizers on the finalizers page within the "working with objects" section.
The same description of finalizers is imported directly from the glossary, so previous to this commit a nearly identical paragraph is repeated.
For reference, the text imported from the glossasry is
> You can use finalizers to control garbage collection of resources.
> For example, you can define a finalizer to clean up related resources
> or infrastructure before the controller deletes the target resource.
while the text being removed in this commit is:
> You can use finalizers to control garbage collection of resources
> by alerting controllers to perform specific cleanup tasks before
> deleting the target resource.
> Remove redundant description of finalizers

- content/en/docs/reference/access-authn-authz/authentication.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
Documentation for:
* KEP (k/enhancements) update PR(s): https://github.com/kubernetes/enhancements/pull/3772
* Code (k/k) update PR(s): https://github.com/kubernetes/kubernetes/pull/116274
* Docs (k/website) update PR(s): https://github.com/kubernetes/website/pull/39794
> KEP-3325: Promote SelfSubjectReview to Beta

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tutorials/security/seccomp.md
PR for https://github.com/kubernetes/enhancements/issues/2413
> [KEP-2413] Add docs for SeccompDefault graduation

- content/en/docs/tasks/configure-pod-container/assign-cpu-resource.md
- content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
- content/en/docs/tasks/configure-pod-container/resize-container-resources.md
- content/en/examples/pods/qos/qos-pod-5.yaml
Documentation for in-place pod resize feature. Ref: https://github.com/kubernetes/kubernetes/pull/102884
> Documentation for in-place pod resize feature

- content/en/docs/concepts/workloads/pods/user-namespaces.md
- content/en/docs/tasks/configure-pod-container/user-namespaces.md
Placeholder PR to document the changes in Kubernetes v1.27 for user namespaces (KEP-127) 
cc @giuseppe
> Document user namespace changes in v1.27 (KEP-127)

- content/en/docs/concepts/storage/volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/command-line-tools-reference/kubelet.md
KEP-3107 update docs for csiNodeExpand secret support
This feature has moved to Beta in this release. The documentation
has been updated to reflect the same.
> KEP-3107 update docs for csiNodeExpand secret support

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
This is the docs PR for the `messageExpression` [update](https://github.com/kubernetes/enhancements/pull/3747) to [KEP-2876](https://github.com/kubernetes/enhancements/issues/2876) that was implemented by https://github.com/kubernetes/kubernetes/pull/115969.
> Documentation for messageExpression update to KEP-2876

- content/en/docs/concepts/overview/kubernetes-api.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
https://github.com/kubernetes/enhancements/issues/3352
> Doc update for KEP-3352 Aggregated Discovery

- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/concepts/services-networking/dual-stack.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
While trying to figure out where to document this, I noticed that we document single-stack `--node-ip` in the node docs, and dual-stack `--node-ip` only in the dual-stack docs. Given the existing docs, it seemed to make the most sense to add the cloud dual-stack note to the dual-stack docs, but I also added a link from the node docs. (I did this as a separate commit since it makes sense independently of the KEP-3705 documentation, but feel free to squash.)
Might need better explanation of enabling the feature gate?
> Add docs for CloudDualStackNodeIPs docs (KEP-3705)

- content/en/docs/contribute/style/style-guide.md
- content/en/docs/tasks/access-application-cluster/ingress-minikube.md
- content/en/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive.html
- content/en/docs/tutorials/hello-minikube.md
- content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
- content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
- content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
- content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html
- content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
- content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
- content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
- content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
- content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html
- content/en/docs/tutorials/kubernetes-basics/update/update-intro.html
Prompted by https://github.com/kubernetes/website/issues/33936
Follows https://github.com/kubernetes/website/pull/40292
Remove pages where we don't have a replacement online, interactive tutorial mechanism, changing them to an apology message
(aside: we don't have an _easy_ way to serve 410 Gone responses)
Update pages where we have an way to let people run the tutorial locally.
/hold
We should not make this change until the end of March 2023.
> Drop or adapt tutorials that rely on Katacoda

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/reference/labels-annotations-taints/_index.md
With https://github.com/kubernetes/kubernetes/issues/113714 we are deprecated the unprefixed labels for the job controller. We should add a deprecated note in the website and update examples with the new labels.
> labels and job updates to mention new labels

- content/en/docs/reference/kubectl/cheatsheet.md
Remove the unnecessary cat command.
> Simplify kubectl heredoc usage in cheatsheet

- content/ko/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
- content/ko/examples/admin/dns/dns-horizontal-autoscaler.yaml
from #38891
Reopened from [PR](https://github.com/kubernetes/website/pull/38906).
> [ko] Translate tasks/administer-cluster/dns-horizontal-autoscaling in Korean

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
Fix ServiceAccount admission controller link
The existing link for ServiceAccount admission controller is broken and doesn't work. This commit will fix the link and redirect it correctly.
> Fix ServiceAccount admission controller link

- content/ja/docs/tasks/administer-cluster/certificates.md
- content/ja/docs/tasks/administer-cluster/declare-network-policy.md
- content/ja/docs/tasks/administer-cluster/extended-resource-node.md
- content/ja/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
- content/ja/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/ja/docs/tasks/administer-cluster/manage-resources/_index.md
- content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
- content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-removal-affects-you.md
- content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
- content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
- content/ja/docs/tasks/administer-cluster/nodelocaldns.md
- content/ja/docs/tasks/administer-cluster/running-cloud-controller.md
- content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
- content/ja/docs/tasks/administer-cluster/topology-manager.md
This updates the page weights under content/ja/docs/tasks/administer-cluster and the pages are shown with new order.
The weight values are same as the weight values in en.
Related: #38887
> [ja] update page weights in /tasks/administer-cluster

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Add docs for `NewVolumeManagerReconstruction` feature gate. This feature *should* be invisible to users - kubelet does the same thing as before, only in a different order at the startup. It's behind a feature gate to allow opt-out in case it's buggy.
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3756-volume-reconstruction
Enhancement issue: https://github.com/kubernetes/enhancements/issues/3756
> Add docs for VolumeManager reconstruction after kubelet restart

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/configure-pod-container/security-context.md
`SELinuxMountReadWriteOncePod` graduates to beta in v1.27. I reshuffled the doc to accommodate more in-tree volume plugins. Most of the other "interesting" volume plugins are migrated to CSI in v1.27 or don't support SELinux easily.
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1710
> Update docs for  SELinuxMountReadWriteOncePod Beta

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/switch-to-evented-pleg.md
Signed-off-by: Harshal Patil [harpatil@redhat.com](mailto:harpatil@redhat.com)
Add EventedPLEG to FeatureGates doc.
Corresponding PR - https://github.com/kubernetes/kubernetes/pull/115967
Enhancement - https://github.com/kubernetes/enhancements/issues/3386
> Graduate Evented PLEG to Beta

- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
pod-eviction-timeout has been removed from v1.27, update the docs to to reference the taint based eviction that is now the default and only mechanism.
Fixes #39101
> remove pod-eviction-timeout documentation

- content/en/docs/concepts/security/security-checklist.md
It's best to disable this API, which is already deprecated. When it's enabled, a user with access can query `/logs` on an API server to read the contents of `/var/log`.
More context: https://groups.google.com/a/kubernetes.io/g/dev/c/OkSc6KLmD0Q
/sig security
> Add /logs API to security checklist

- content/zh-cn/blog/_posts/2023-01-05-retroactive-default-storage-class.md
* The version notation for Kubernetes  should be consistent.
* Change the command line kc to kubectl.
> [zh-cn]Update blog: Kubernetes v1.26: Retroactive Default StorageClass

- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
- content/en/examples/access/deployment-replicas-policy.yaml
This PR covers the following new features of ValidatingAdmissionPolicy
This PR is ready for review.
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3488-cel-admission-control
> KEP-3488 ValidatingAdmissionPolicy post-1.27 update

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Bumps terminationGracePeriodSeconds to stable for 1.27.
Reference:  https://github.com/kubernetes/enhancements/issues/2238
cc @mickeyboxell
> terminationGracePeriodSeconds: stable in 1.27

- content/en/docs/concepts/workloads/pods/user-namespaces.md
- content/en/docs/tasks/configure-pod-container/user-namespaces.md
containerd 1.7 was just released with user namespaces support. Let's mention this.
Also, let's emphasize in the task page that only supported runtimes work with user namespaces.
Fixes: #40233 
@sftim doing only one PR against main is enough for this to show for 1.25 and 1.26? Let me know if I should open another PR for the other branch or what
cc @SergeyKanzhelev
> content: Mention containerd 1.7 supports user namespaces

- content/en/docs/concepts/workloads/pods/disruptions.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/safely-drain-node.md
- content/en/docs/tasks/run-application/configure-pdb.md
Add documentation for the beta promotion:
- https://github.com/kubernetes/enhancements/issues/3017
- https://github.com/kubernetes/kubernetes/pull/115363
> Update docs for PodDisruptionBudget unhealthy pod eviction policy promotion to Beta

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/reference/networking/virtual-ips.md
The KEP-1880 introduces two new types: IPAddress and ServiceCIDR.
KEP-1880 is meant to address the main problems with the IP allocation on Services.
During the implementation. phase, we realized the need to align the use of ServiceCIDR with the other KEP that is introducing multiple ClusterCIDR as a new type https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2593-multiple-cluster-cidrs.
This is required because otherwise users can cause networking problems due to misconfigurations in their cluster.
Because of that, in this first iteration of the KEP-1880, only the new IPAddress object and its ClusterIP allocator is introduced.
https://github.com/kubernetes/enhancements/issues/1880
> KEP-1880 alpha: IPAddresses

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Placeholder for the KEP-3695: extend pod resource API to for DRA 
https://github.com/kubernetes/enhancements/pull/3738
> Extend PodResources API for Dynamic Resource Allocation

- content/fr/docs/tasks/access-application-cluster/list-all-running-container-images.md
The old link cannot be accessed, so I update the link.
`https://golang.org/pkg/text/template` =>  `https://pkg.go.dev/text/template`
> [fr] update link of text/template

- content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1.md
Add zh text to this reference page:
```
content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1.md
```
See [preview](https://deploy-preview-40387--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1/) please.
> [zh] sync kubelet-credentialprovider.v1.md

- content/en/docs/reference/kubectl/kubectl.md
This PR adds document for the alpha stage of https://github.com/kubernetes/enhancements/issues/3638
> document plugin resolution as subcommand for builtin commands

- content/en/docs/tasks/access-application-cluster/list-all-running-container-images.md
- content/en/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
The old link cannot be accessed, so I update the link.
`https://golang.org/pkg/text/template` =>  `https://pkg.go.dev/text/template`
> update link of go package text/template

- content/en/docs/reference/access-authn-authz/rbac.md
Look at the source code, apiGroups is an empty set and not all are allowed, you need to use * to be able to, if it is an empty set if the resource does not have apiGroups then it will not be accessible
Refer to：
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/rbac/v1/evaluation_helpers.go#L85 https://github.com/kubernetes/api/blob/master/rbac/v1/types.go#L29
> about apiGroups

- content/zh-cn/docs/tasks/access-application-cluster/list-all-running-container-images.md
The old link cannot be accessed,update the link.
https://golang.org/pkg/text/template ——>  https://pkg.go.dev/text/template
> Fix the links

- content/en/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
- content/en/blog/_posts/2023-04-14-improving-support-go-updates.md
Blog post about https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/3744-stay-on-supported-go-versions
Preview at https://deploy-preview-39840--kubernetes-io-main-staging.netlify.app/blog/2023/04/06/keeping-kubernetes-secure-with-updated-go-versions/
> Blog post for KEP 3744

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
We fixed a bug in matchLableKeys in https://github.com/kubernetes/kubernetes/pull/116535 and need to update the doc.
> doc: forbid to set matchLabelKeys when labelSelector isn’t set in topologySpreadConstraints

- content/en/docs/reference/access-authn-authz/rbac.md
This PR fixes two problems in the `access-authn-authz/rbac` page,
1. The indentation of list items should be 2 spaces for unordered lists, or 3 spaces for ordered lists.
2. Wrap long lines for future change tracking.
/kind cleanup
> Cleanup page rbac

- content/en/examples/priority-and-fairness/health-for-strangers.yaml
Title: Migrated to use the v1beta3 API version of FlowSchema.
As per the Kubernetes API deprecation-guide, the flowcontrol.apiserver.k8s.io/v1beta2 API version of FlowSchema will no longer be served in v1.29.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/
I'm issuing this PR so that the example in the official Kubernetes documentation refers to the flowcontrol.apiserver.k8s.io/v1beta3 API version, available since v1.26
> Migrated to use the v1beta3 API version of FlowSchema

- content/en/docs/concepts/architecture/garbage-collection.md
This PR removed the `beta`  word for the TTLAfterFinished  in the [Garbage Collection](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#what-s-next) docs
Fixes #40521
> Removed beta stage for TTLAfterFinished.

- content/id/docs/tasks/access-application-cluster/list-all-running-container-images.md
The old link cannot be accessed, so I update the link.
`https://golang.org/pkg/text/template` =>  `https://pkg.go.dev/text/template`
> [id] update link of go package text/template

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/topology-manager.md
Docs update for Kubelet Topology Manager graduation to GA.
Issue: https://github.com/kubernetes/enhancements/issues/693#issuecomment-1401799352
> node: topologymgr: docs: Kubelet Topology Manager graduation to GA

- content/en/docs/reference/kubectl/conventions.md
Ref: https://github.com/kubernetes/enhancements/issues/2590
/sig cli
/cc @nikhita
> reference/kubectl: Update docs for moving kubectl subresource to beta

- data/i18n/de/de.toml
On the main page, the word **you** is translated in two ways.
In the feature blocks, **du** is used. 
In the registration section for the KubeWeekly newsletter, **Sie** is used.
This PR changes the registration section, so that **du** is used.
> [de] Make meaning of "you" on the main page consistent

- content/en/examples/admin/konnectivity/konnectivity-agent.yaml
- content/en/examples/admin/konnectivity/konnectivity-server.yaml
- Delete UDS file if exists (common pain point).
- Make server and agent images consistent (and include latest memory leak fixes).
Relevant discussion: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/476
> Konnectivity example refresh.

- content/en/docs/concepts/services-networking/service-topology.md
- content/en/docs/concepts/services-networking/topology-aware-routing.md
- static/_redirects
This updates documentation for the Topology Aware Hints KEP https://github.com/kubernetes/enhancements/issues/2433. Notably, as the updates in 1.27 have made "Hints" an optional implementation detail of Topology Aware Routing Heuristics, I'm working on a broader overall of the documentation. 
/sig network
> Updating documentation for Topology Aware Routing in 1.27

- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
This is my take on PR #40065.
Rather than mention trust bundles as a subtopic of certificate signing requests (which is what #40065 would do if merged), reshape the page so that:
- it's clear that CSRs are **stable** but ClusterTrustBundles are **alpha**
- the task for issuing a certificate to a user stands separately from the concepts explained elsewhere in the page
- it's clear that signers are relevant to both CSRs and ClusterTrustBundles
Because this is a mix of changes to the existing text and new content, I recommend reviewing it by commit to see the net-new section and then looking at the second commit locally using `git diff --color-moved`.
You should also look at a local preview or [Netlify deploy preview](https://deploy-preview-40578--kubernetes-io-vnext-staging.netlify.app/docs/ …
> Document ClusterTrustBundles

- content/en/blog/_posts/2023-04-20-read-write-once-pod-access-mode-beta.md
This is a placeholder for the ReadWriteOncePod beta graduation blog post.
See the [alpha blog post](https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/) for more context.
/sig storage
CC @msau42
> Feature blog for ReadWriteOncePod beta graduation

- content/en/blog/_posts/2023-05-11-nodeport-dynamic-and-static-allocation.md
add blog for KEP 3668 https://github.com/kubernetes/enhancements/issues/3668
this blog describes the behavior of the new Feature ServiceNodePortStaticSubrange, and the problems it solves, and shows some examples
> add blog for feature ServiceNodePortStaticSubrange

- content/en/blog/_posts/2023-05-11-nodeport-dynamic-and-static-allocation.md
fix a typo mentioned in https://github.com/kubernetes/website/pull/40204
> fix typo for blog ServiceNodePortStaticSubrange

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
```
```
See [preview](https://deploy-preview-40648--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) please.
> [zh] sync 1.27 device-plugins.md

- content/zh-cn/docs/concepts/cluster-administration/system-traces.md
```
content/zh-cn/docs/concepts/cluster-administration/system-traces.md
```
See [preview](https://deploy-preview-40633--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/system-traces/) please.
> [zh] sync 1.27 system-traces.md

- content/zh-cn/docs/concepts/cluster-administration/system-logs.md
```
content/zh-cn/docs/concepts/cluster-administration/system-logs.md
```
See [preview](https://deploy-preview-40629--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/system-logs/) please.
> [zh] sync 1.27 system-logs.md

- content/en/docs/concepts/overview/working-with-objects/owners-dependents.md
This PR updated `Owners and Dependents` page by adding few glossary tooltips and reference links to the terms which were not having previously. Also updated what's next section.
Fixes #38136.
> Updated Owners and Dependents page with glossary tooltip and reference links

- content/en/blog/_posts/2023-04-11-kubernetes-1.27-blog.md
Correct typo in 1.27 announcement blog post
Kuber**en**tes -> Kuber**ne**tes
Thanks for what you do 🫡
> [en] Fix typo in 1.27 blog post

- content/en/blog/_posts/2023-04-11-topology-spread-features.md
- content/en/blog/_posts/2023-04-17-topology-spread-features.md
We added some features in recent releases and those are now graduated to beta by 1.27. 
- https://github.com/kubernetes/enhancements/issues/3022
- https://github.com/kubernetes/enhancements/issues/3094
- https://github.com/kubernetes/enhancements/issues/3243
We'd like to have a blog post for all of these features.
/cc @kerthcet @denkensk
> Pod Topology Spread blog post (KEP-3022 KEP-3094 KEP-3243)

- content/en/releases/version-skew-policy.md
Discussed in SIG Network today; the docs claim that kubelet and kube-proxy must be the same version, but we had actually forgotten that, and the last time this was actually even theoretically true was 1.19. SIG Network will be making sure there are no "kubelet and kube-proxy must be the same version" problems in the future. (https://github.com/kubernetes/kubernetes/pull/117307 adds some clarification about that.)
(KEP-3178 involves an n-2 skew constraint between kube-proxy and kubelet, but that already exists transitively via apiserver skew constraints without needing a specific kube-proxy/kubelet skew rule: kube-proxy 1.27 doesn't work with kubelet 1.24, but (a) kube-proxy 1.27 requires kube-apiserver >= 1.27, and (b) kubelet 1.24 only supports kube-apiserver <= 1.26.)
cc @thockin @aojea
> Drop kube-proxy/kubelet skew requirement

- content/zh-cn/docs/reference/kubernetes-api/authentication-resources/self-subject-review-v1beta1.md
```
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/self-subject-review-v1beta1.md
```
See [preview](https://deploy-preview-40665--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/authentication-resources/self-subject-review-v1beta1/) please.
> [zh] sync self-subject-review-v1beta1.md

- content/zh-cn/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
Sync 2 files with en text:
```
content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
content/zh-cn/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
```
See [preview](https://deploy-preview-40649--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration/) please.
> [zh] sync pod-scheduling-readiness.md and taint-and-toleration.md

- content/en/docs/concepts/services-networking/service.md
Fixes: #39743 
Added note to mention deprecation of Service.spec.loadBalancerIP.
Page to be changed: 
https://kubernetes.io/docs/concepts/services-networking/service/
> Deprecation Note added for loadbalancerIP

- static/_redirects
Signed-off-by: Asif Zubayer Palak asifpalak@gmail.com
Adds entries to `static/_redirects` for Bengali localization
This is an initial PR as may need some improvements!
Tracking issue: #31677
> [bn] Add entries into static/_redirects for Bengali localization

- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
On the certificates page, document how to use service account impersonation to list ClusterTrustBundles in case an application developer doesn't have cluster-wide access to list ClusterTrustBundles.
> ClusterTrustBundles: Document service account impersonation

- content/zh-cn/docs/concepts/workloads/controllers/cron-jobs.md
```
```
See [preview](https://deploy-preview-40656--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/cron-jobs/) please.
> [zh] sync /controllers/cron-jobs.md

- content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
This PR replaces k8s.gcr.io with registry.k8s.io in a reference document related to kubeadm.
xref https://github.com/kubernetes/website/issues/39353
xref https://github.com/kubernetes/k8s.io/issues/4738
> [pt-br] Replace k8s.gcr.io with registry.k8s.io in reference doc

- content/pt-br/docs/tasks/configure-pod-container/_index.md
index.md is missing on a task page, making it kind of messy on pt-br translation.
> Add missing index on pt-br tasks

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
```
See [preview](https://deploy-preview-40680--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1/) please.
> [zh] sync csi-driver-v1.md

- content/en/docs/tasks/configure-pod-container/migrate-from-psp.md
fix typo permision -> permission
> Fix spelling error in “Migrate from PodSecurityPolicy to the Built-In PodSecurity Admission Controller”

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1.md
- Remove redundant blank lines
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1.md
```
See [preview](https://deploy-preview-40743--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1/) please.
> [zh] sync /kubernetes-api/cluster-resources/lease-v1.md

- content/zh-cn/docs/tutorials/security/seccomp.md
```
content/zh-cn/docs/tutorials/security/seccomp.md
```
See [preview](https://deploy-preview-40748--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/security/seccomp/) please.
> [zh] sync /tutorials/security/seccomp.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md
- Remove redundant blank lines
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md
```
See [preview](https://deploy-preview-40744--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1/) please.
> [zh] sync /kubernetes-api/cluster-resources/node-v1.md

- content/de/docs/tasks/tools/_index.md
This PR adds a German translation for "Install Tools".
When this PR gets merged, we can create a link  between **Getting started/Learning environment** and **Install Tools**, like in the English version.
> [de] Add German translation for "Install tools"

- content/en/docs/reference/glossary/etcd.md
Microscopic fix in the `etcd` glossary entry. The use of `the` rather than `those` data makes more sense, as in this context `data` is a single object. 
Thank you!
> Improve grammar in etcd glossary

- content/en/docs/tasks/manage-kubernetes-objects/declarative-config.md
Performed several actions:
- Remove redundant blank lines and spaces
- Replace `<directory>/` and `<directory/>` with `<directory>` for consistency
See [preview](https://deploy-preview-40807--kubernetes-io-main-staging.netlify.app/docs/tasks/manage-kubernetes-objects/declarative-config/) please.
> tweak line wrappings in declarative-config.md

- content/ko/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- content/ko/examples/pods/pod-with-scheduling-gates.yaml
- content/ko/examples/pods/pod-without-scheduling-gates.yaml
Translated [Pod Scheduling Readiness](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/) in Korean.
Also added two example resources for document examples.
쿠버네티스 문서/개념/스케줄링, 선점(Preemption), 축출(Eviction) 항목의 미번역된 [Pod Scheduling Readiness](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/)를 한국어로 번역하였습니다.
추가적으로 문서의 예시를 위해 2개의 예시 리소스 파일을 추가하였습니다.
> [ko] translate pod-scheduling-readiness.md into Korean

- content/ko/docs/concepts/cluster-administration/networking.md
- content/ko/docs/concepts/cluster-administration/proxies.md
- content/ko/docs/concepts/cluster-administration/system-logs.md
- content/ko/docs/concepts/cluster-administration/system-metrics.md
Related Issue: #38458
Updated outdated files in content/en/docs/concepts/cluster-administration/.
> ### 4 files to be modified
> [ko] Update outdated files in dev-1.26-ko.1 (M10-M13)

- content/en/blog/_posts/2023-04-24-openapi-v3-field-validation-ga.md
Blog post for https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2896-openapi-v3/README.md and https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2885-server-side-unknown-field-validation/README.md
We will be combining them into one blog post.
> Blog post for KEP-2896 and KEP-2885

- content/en/blog/_posts/2023-05-09-Safer-More-Performant-Pruning-in-kubectl-apply.md
Feature blog post for KEP 3659: https://git.k8s.io/enhancements/keps/sig-cli/3659-kubectl-apply-prune.
KEP issue: https://github.com/kubernetes/enhancements/issues/3659
Extracted from https://github.com/kubernetes/website/pull/39818, which I opened on Mar 6 but mistakenly put both the blog post placeholder and the docs placeholder in the same PR. Sorry! 🤦‍♀️  Thanks @sftim for setting me straight.
> Add blog post to announce ApplySet-based pruning in kubectl

- content/en/docs/reference/scheduling/config.md
ref: https://github.com/kubernetes/kubernetes/issues/117556
We've already announced that v1beta3 is deprecated from v1.26 and remove it in v1.29 via log.
We should reflect this on the website.
Also, we haven't removed v1beta2 yet, will remove it in v1.28.
> Add the deprecation notice of KubeSchedulerConfiguration v1beta3

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
3.3 is end of life.
There is also a data inconsistency issue in 3.4.21 and 3.5.5, so 3.4.22+ and 3.5.6+ are the minimum recommended etcd versions. Please read
https://groups.google.com/g/etcd-dev/c/8S7u6NqW6C4
> Update the minimum recommended etcd versions to run in production to `3.4.22+` and `3.5.6+`

- content/en/blog/_posts/2022-12-16-statefulset-migration.md
- content/en/blog/_posts/2023-04-28-statefulset-migration.md
Initial placeholder commit for KEP-3335 blog post
* KEP: https://github.com/kubernetes/enhancements/issues/3336
/sig apps
> Add 1.27 feature blog article about StatefulSet Start Ordinals (KEP-3335)

- content/en/releases/patch-releases.md
- data/releases/schedule.yaml
Add release data for the April 2023 patches:
* v1.24.13
* v1.25.9
* v1.26.4
Additionally:
* v1.27.1
I also removed April 2023 from the upcoming patch calendar since it already happened.
Note that I left `cherryPickDeadline` blank on v1.27.1 because I wasn't sure what made sense for that (afaik it was an out-of-band release due to regression in v1.27.0)
> Update data/releases/schedule.yaml for April 2023 patches

- content/fr/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
- content/fr/examples/pods/inject/dapi-envars-container.yaml
- content/fr/examples/pods/inject/dapi-envars-pod.yaml
Hi,
This adds the French translation for the task "Expose Pod Information to Containers Through Environment Variables", from the "Inject Data Into Applications" section, including the example yaml files.
This is the [reference document](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/).
Thx 😄
> [fr] add french translation for task inject-data-application/environment-variable-expose-pod-information.md

- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
> Fix typo in "Configure a Pod to Use a ConfigMap"

- Dockerfile
This may help to fix an issue where local builds could time out without succeeding. Prompted by https://github.com/kubernetes/website/issues/35780#issuecomment-1526778482
> Bump Go version for local preview container image

- content/en/docs/tasks/administer-cluster/switch-to-evented-pleg.md
See [preview](https://deploy-preview-40890--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/switch-to-evented-pleg/).
- replace `https://kubernetes.io/docs/*` with `/docs/*` in url
- remove redundant blank lines and add blank lines to make prettier
- fix minor grammar issues
- fix an issue caused by incorrect indentations and `tab` tags as below:
> Fix tab tags and indentations in switch-to-evented-pleg.md

- assets/scss/_custom.scss
- content/en/docs/tasks/administer-cluster/encrypt-data.md
Replace the existing Markdown table with a more complex table that is not easy to express in Markdown - and for that reason, use HTML.
This relies on custom style support to render well (see the first commit) but can work OK even with default Docsy styling.
Split out from PR https://github.com/kubernetes/website/pull/33285.
> Revise table for API encryption at rest task

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
```
content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
```
See [preview](https://deploy-preview-40891--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1/) please.
> [zh] sync network-policy-v1.md

- content/zh-cn/blog/_posts/2023-05-15-kubernetes-1-27-updates-on-speeding-up-pod-startup.md
```
content/zh-cn/blog/_posts/2023-05-15-kubernetes-1-27-updates-on-speeding-up-pod-startup.md
```
> [zh] sync blog: updates-on-speeding-up-pod-startup.md

- content/fr/docs/tasks/run-application/_index.md
- content/fr/docs/tasks/run-application/access-api-from-pod.md
Hi,
This adds the French translation for the task 'Accessing the Kubernetes API from a Pod', from the "Run Applications" section. This is the [reference document](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/).
As this is the first document for the section, I added the description in the index file to match the English ref.
> [fr] translate task run-application/access-api-from-pod.md

- content/fr/docs/tasks/run-application/run-stateless-application-deployment.md
- content/fr/examples/application/deployment-scale.yaml
- content/fr/examples/application/deployment-update.yaml
Hi,
This adds the French translation for the task 'Run a Stateless Application Using a Deployment, from the "Run Applications" section. This is the [reference document](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/).
I added the missing examples files, and overwritten `examples/application/deployment.yaml` with the English reference as the one already present was different.
> [fr] translate task run-application/run-stateless-application-deployment.md

- content/en/docs/tasks/tools/install-kubectl-linux.md
Adds missing curl download options for Linux on arm64 arch. Fixes #31699
> Add curl download options for linux on arm64

- content/en/docs/concepts/configuration/manage-resources-containers.md
this seems to have been missed during the GA promotion in https://github.com/kubernetes/website/pull/35989
> remove beta reference from LocalStorageCapacityIsolation GA promotion

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Versions of cri-tools and cni-plugins in kubeadm-install docs updated from:
`CNI_PLUGINS_VERSION="v1.1.0"`
`CRICTL_VERSION="v1.25.0"`
to
`CNI_PLUGINS_VERSION="v1.2.0"`
`CRICTL_VERSION="v1.26.0"`
This PR fixes: #40655
> Updated cri-tools and cni-plugins versions in kubeadm install docs 

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
An etcd cluster needs periodic maintenance to remain reliable, so added one more section `Maintaining etcd clusters`.
Note etcd defragmentation is an expensive operation, so it should be executed as infrequent as possible. On the other hand, it's also necessary to make sure any etcd member will not run out of the storage quota. It's recommended to run defragmentation using [etcd-defrag](https://github.com/ahrtr/etcd-defrag), which is an easier to use and smarter etcd defragmentation tool.
> Add section “Maintaining etcd clusters” into “Operating etcd clusters for Kubernetes”

- content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md
This is a small clarification suggestion.
The note on caBundle field description mentions it is PEM encoded, but the actual field value is then encoded into Base64, which is worth mentioning.
> Note on caBundle encoding in extensible-admission-controllers.md

- content/en/blog/_posts/2023-04-13-hpa-container-resource-metric.md
- content/en/blog/_posts/2023-05-02-hpa-container-resource-metric.md
The container resource metrics is planning to get graduated to beta in v1.27. So, the feature will be available for many people by default. 
It’s worth sharing this feature and the motivation for people since this feature is very important to configure safe HPAs for Pod with multiple containers.
---
ref: https://github.com/kubernetes/enhancements/issues/1610
> Add the blog post for the beta graduation of HPA ContainerResource type metric

- content/en/blog/_posts/2023-05-04-statefulset-autodelete.md
See the [alpha blog post](https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/) for content.
> Feature blog for StatefulSet Autodelete beta graduation

- content/en/docs/concepts/containers/container-environment.md
- content/en/docs/reference/access-authn-authz/abac.md
- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/en/docs/tasks/administer-cluster/verify-signed-artifacts.md
- content/en/docs/tasks/tools/install-kubectl-linux.md
- content/en/docs/tasks/tools/install-kubectl-macos.md
- content/en/docs/tasks/tools/install-kubectl-windows.md
- content/en/docs/tutorials/security/cluster-level-pss.md
- content/en/docs/tutorials/security/ns-level-pss.md
- content/en/docs/tutorials/services/connect-applications-service.md
- content/en/releases/download.md
- data/releases/schedule.yaml
- hugo.toml
- layouts/shortcodes/skew.html
Before this PR, the way we represented patch versions in docs was to hard code the `.0` patch release. The site actually had a facility to update the patch version, Hugo param `fullversion`, but access to update that is limited just to website maintainers, because access there also lets you reconfigure the Hugo static site generator.
_However_ we also have the patch information available in `data/releases/schedule.yaml`, and SIG Release do update that during the lifecycle of a release.
So: use it. Switch the English localization to use an updated `skew` shortcode, and deprecate the `fullversion` param.
~Note to reviewers: this does work, but to satisfy yourself that it's correct you might need to locally update `data/releases/schedule.yaml` with the actually information for the v1.27.1 …
> Use release data to calculate latest patch version

- content/fr/docs/tasks/run-application/run-single-instance-stateful-application.md
- content/fr/examples/application/mysql/mysql-deployment.yaml
- content/fr/examples/application/mysql/mysql-pv.yaml
Hi,
This adds the French translation for the task 'Run a Single-Instance Stateful Application', from the "Run Applications" section. This is the [reference document](https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/).
I added the missing examples files for the task.
> [fr] translate task run-application/run-single-instance-stateful-application.md

- content/en/docs/tasks/administer-cluster/sysctl-cluster.md
This change adds a note clarifying that `net.*` sysctls are not allowed when host networking is enabled, even though they are listed in the "safe set".
Additionally, the namespaced `net.*` sysctls are reworded to read more easily, with regards to the container networking namespace mention.
> Clarify `net.*` sysctl safety

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v1.md
This PR resyncs page `horizontal-pod-autoscaler-v1` referring to en upstram.
By the way, I removed some `response` sections which are not changed while translating.
> [zh] resync page horizontal-pod-autoscaler-v1

- content/en/docs/concepts/workloads/controllers/job.md
This feature gate is actually disabled  by default in v1.23. Please see https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ for confirmation.
> Update 1.23 job documentation for JobTrackingWithFinalizers

- content/ko/blog/_posts/2022-05-13-grpc-probes-in-beta.md
This PR replaces a reference to k8s.gcr.io with registry.k8s.io in a Korean blog post translation.
xref https://github.com/kubernetes/website/issues/39353
xref https://github.com/kubernetes/k8s.io/issues/4738
> [ko] Replace k8s.gcr.io with registry.k8s.io in blog

- content/en/blog/_posts/2015-10-00-Some-Things-You-Didnt-Know-About-Kubectl_28.md
The old [article](https://kubernetes.io/blog/2015/10/some-things-you-didnt-know-about-kubectl_28/) is still found in search results, so I'm updating it to use better Markdown.
/area blog
/cc @brendandburns
> Revise (dated) article about kubectl

- content/ja/docs/concepts/_index.md
After https://github.com/kubernetes/website/pull/17596, the link of the PLEG design doc is moved to https://github.com/kubernetes/design-proposals-archive/blob/main/node/pod-lifecycle-event-generator.md. Therefore, currently it is outdated and it returns a 404.
This PR updates that link and fixes it for Japanese localization.
> Update design doc reference link of PLEG for ja

- content/en/docs/concepts/workloads/controllers/deployment.md
This PR fixes issue #40751 
Change the output of `pod-template-hash` label in `kubectl get pods --show-labels` from `pod-template-hash=3123191453` to `pod-template-hash=75675f5897`.
> [en] fix incorrect pod-template-hash labels in deployment.md

- content/en/docs/concepts/services-networking/ingress-controllers.md
ngrok has released a new kubernetes ingress controller. This PR adds that controller in alphabetical order to the list of existing ingress controllers for kubernetes. 
for more information, see https://github.com/ngrok/kubernetes-ingress-controller
thank you!
> feat: Add ngrok k8s ingress controller to the list of Ingress Controllers

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md
This PR resync page `content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md`.
1. Remove extra blanks.
2. Move section `body` to the comment section for future change tracking.
3. Sync 1.27.
> [zh] resync page horizontal-pod-autoscaler-v2

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
There is no well-known label `topology.kubernetes.io/hostname`, but there is `kubernetes.io/hostname`. I suppose it's just a typo, as there are other well-known labels with a `topology.` prefix, such as `topology.kubernetes.io/zone`.
> Fix well-known label name

- content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
This PR cleans up the page `expose-external-ip-address`:
- The indentation of list items should be 2 spaces for unordered lists or 3 spaces for ordered lists.
> Cleanup page expose-external-ip-address

- content/en/docs/tasks/debug/_index.md
The Slack channel #kubernetes-dev has been moved/renamed to the #kubernetes-contributors channel.
This PR changes reference and link from #kubernetes-dev to #kubernetes-contributors.
> docs: update Slack link to #kubernetes-contributors

- content/zh-cn/docs/tasks/debug/_index.md
The Slack channel #kubernetes-dev has been moved/renamed to the #kubernetes-contributors channel for zh-cn language.
This PR changes reference and link from #kubernetes-dev to #kubernetes-contributors.
> docs: update Slack channel link to #kubernetes-contributors for zh

- content/en/docs/reference/kubectl/cheatsheet.md
Adds a comment to the kubectl cheat sheet that indicates that this is relevant for the current version of Kubernetes. Fixes #40582
> Add Kubernetes version information to the kubectl cheat sheet

- content/en/blog/_posts/2022-08-31-cgroupv2-ga.md
- content/en/docs/concepts/architecture/cgroups.md
* The previous statement was missing HotSpot 8 which had cgroupsV2 support [backported](https://bugs.openjdk.org/browse/JDK-8230305).
* The previous statement was ambiguous as different JVM implementations added and backported cgroupsV2 at different times. The [linked](https://bugs.openjdk.org/browse/JDK-8230305) bug report was specifically for the HotSpot JVM.
* This PR adds additional JVM vendors (specifically IBM/Eclipse OpenJ9, and others can be added by other vendors).
* Note that there is a translation at `content/zh-cn/blog/_posts/2022-08-31-cgroupv2-ga.md` which would be nice to update as well.
Although this is an older blog post, people still use and reference it.
> Clarify cgroupsV2 Java statements

- content/en/docs/reference/config-api/apiserver-encryption.v1.md
There are limitations in the generator when parsing ambiguous strings such as `*`, `<` etc. `*` is used in Markdown for emphasis, but some comments are using the literal '*' without properly escaping it. `<` and `>` are not allowed in Markdown parser. The generated content for this is at best some warning strings.
This PR fixes this issue manually.
An ideal fix would be proposed to the upstream source code wherever these happen.
Related: #41018
> Fix generated config API for API server encryption

- content/zh-cn/docs/concepts/overview/components.md
I just added a space here to prevent shortcode parsing.
Fixes: https://github.com/kubernetes/website/issues/40984
Introduced PR: https://github.com/kubernetes/website/pull/39516
See the [preview](https://deploy-preview-41051--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/overview/components/) page.
> [zh-cn] Fix redundant picture text display of components.md

- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
Fix https://github.com/kubernetes/website/issues/40950
Got  `error: json: unknown field "labels"` when applying ./kustomization.yaml written in https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#generate-configmaps-from-files
> Fix: unknown field "labels" in configMapGenerator

- scripts/README.md
- scripts/ja/OWNERS
- scripts/ja/verify-spelling.sh
We have the translation guideline as [1], and that contains what are valid Japanese words for the corresponding English words. This adds a script to verify those words based on the guideline.
[1]: https://kubernetes.io/ja/docs/contribute/localization/
> Add verify-spelling.sh for ja content

- content/en/docs/reference/config-api/apiserver-audit.v1.md
- content/en/docs/reference/config-api/kubelet-config.v1.md
- content/en/docs/reference/config-api/kubelet-config.v1beta1.md
- content/en/docs/reference/config-api/kubelet-credentialprovider.v1.md
- content/en/docs/reference/config-api/kubelet-credentialprovider.v1alpha1.md
- content/en/docs/reference/config-api/kubelet-credentialprovider.v1beta1.md
This PR fixes some issues caused by the bad format in source code comments that confuse the reference generator. Problems are related to the use of `*` in comment text as literal string rather than emphasis.
Related: #41035
> Fix issues in generated config API references

- content/en/docs/reference/command-line-tools-reference/kubelet.md
I fixed data type of the kubelet `--seccomp-default` flag.
> Fix data type of the kubelet `--seccomp-default` flag

- content/en/docs/concepts/services-networking/service.md
I added a new description for `appProtocol` field in KEP-3726 for 1.27. 
https://github.com/kubernetes/enhancements/issues/3726
The issue was not tracked for 1.27 release for some reason and I missed updating the docs.
This PR updates the doc to reflect the new description.  Should it stay on main branch or I should move it to a different branch?
Also, feedback is most welcomed.
FYI @aojea @robscott
> new description for appProtocol docs to reflect KEP-3726

- content/en/docs/tasks/administer-cluster/verify-signed-artifacts.md
Cosign 2.0 introduced significant command syntax changes to verify images and blobs. Fixes #39775
> Update cosign verify instructions for 2.0

- content/en/docs/tasks/administer-cluster/safely-drain-node.md
Removes the "Your Kubernetes server must be at or later than version 1.5." from the prerequisites. Fixes #40453
> Remove minimum Kubernetes version requirement from prerequisites

- content/ko/docs/concepts/security/pod-security-admission.md
Translated [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) in Korean.
쿠버네티스 문서/개념/보안 항목의 미번역된 [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/)를 한국어로 번역.
> [ko] Translate pod-security-admission.md into Korean

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
This is a Bug Report
Problem:
On:
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/feature-gates.md?plain=1#L204
StatefulSetAutoDeletePVC is listed as being introduced in 1.22, however it was introduced in 1.23: https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/
Proposed Solution:
Update it to 1.23
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
> Fix version number for StatefulSetAutoDeletePVC feature introduction

- content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
Kustomize has deprecated the use of `bases` in `kustomization.yaml` files. This PR updates all references to `bases` in the docs to use the newer `resources`, which is [the suggested alternative](https://github.com/kubernetes-sigs/kustomize/issues/2243).
> docs: Update kustomize examples to use non-deprecated resources key (English)

- content/en/docs/concepts/architecture/garbage-collection.md
- content/en/docs/concepts/architecture/nodes.md
This PR fixes two problems in the `garbage-collection` and `nodes` page:
1. The indentation of list items should be 2 spaces for unordered lists, or 3 spaces for ordered lists. We should avoid using 4 spaces as indentation because 4-spaces indentation has special meaning in markdown.
2. Remove extra spaces.
> Cleanup page garbage-collection and nodes

- content/en/docs/tasks/administer-cluster/safely-drain-node.md
Clarify that `nodeName` still places Pods on nodes with `SchedulingDisabled` status. Please check issue [117843](https://github.com/kubernetes/kubernetes/issues/117843) for more info.
> Add note about `nodeName` ignoring a drained node

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-binding-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/replica-set-v1.md
> [zh-cn] sync some docs for kubernetes-api

- content/ko/docs/tasks/job/job-with-pod-to-pod-communication.md
closes #40946
Translated [Job with Pod-to-Pod Communication](https://kubernetes.io/docs/tasks/job/job-with-pod-to-pod-communication/) into Korean.
> [ko] Translate docs/tasks/job/job-with-pod-to-pod-communication into Korean

- content/ko/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
- content/ko/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
Related Issue : https://github.com/kubernetes/website/issues/38458
I have updated some of the outdated contents in dev-1.26-ko.1 branch.
Full changes in the original english content can be checked with this [comparison](https://github.com/kubernetes/website/compare/dev-1.25-ko.1...dev-1.26-ko.1)
> [ko] Update outdated korean contents in dev-1.26-ko.1 (M156-157)

- content/ko/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
Related Issue : [#38458](https://github.com/kubernetes/website/issues/38458)
I have updated some of the outdated contents in `dev-1.26-ko.1` branch.
Full changes in the original english content can be checked with this [comparison](https://github.com/kubernetes/website/compare/dev-1.25-ko.1...dev-1.26-ko.1)
> [ko] Update outdated korean contents in dev-1.26-ko.1 (M163)

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1.md
This PR resync page `content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1.md` referring to en upstream. Btw, I cleanup the page.
> [zh] 1.27 sync config-map-v1

- content/en/docs/concepts/services-networking/network-policies.md
Adds a new section with an example showing the use of  multiple namespaceSelector for an Egress policy. Fixes #40858
> Add namespaceSelector:matchLabels example

- content/en/docs/concepts/architecture/nodes.md
We never documented the Pod admission failures and Not Ready status. See https://github.com/kubernetes/enhancements/blob/80e76860ab0c9faa53fe833150091c15c5855ded/keps/sig-node/2000-graceful-node-shutdown/README.md?plain=1#L368-L371
/sig node
/assign @bobbypage 
/kind cleanup
> Clarify pod scheduling during node graceful termination

- content/en/docs/concepts/security/security-checklist.md
- content/en/docs/tasks/administer-cluster/securing-a-cluster.md
Link documents [Securing a Cluster](https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/) (task) with [Security Checklist](https://kubernetes.io/docs/concepts/security/security-checklist/) (concept) for alignment. Fixes #37738
> Add links between Securing a Cluster and Security Checklist for alignment

- content/es/docs/reference/glossary/container-runtime-interface.md
This PRs localizes the `content/en/docs/reference/glossary/container-runtime-interface.md` term to Spanish.
closes https://github.com/kubernetes/website/issues/40964
> [es] localize docs/reference/glossary/container-runtime-interface.md

- content/es/docs/tasks/tools/included/install-kubectl-linux.md
- content/es/docs/tasks/tools/included/install-kubectl-macos.md
- content/es/docs/tasks/tools/included/install-kubectl-windows.md
Use `{{% skew currentPatchVersion %}}` shortcode instead.
Fixes #41063
> [es] Replace use of deprecated fullversion param

- content/en/docs/concepts/services-networking/service.md
View that PR to see these changes in context.
- revise a section of the Service concept [[preview](https://deploy-preview-38563--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/); [original](https://k8s.io/docs/concepts/services-networking/service/)]
These changes reorganize the structure of the page to provide a new focus on the 4 types of Service. These changes are the ones that come after what you can see in #38562.
> Revise Service concept, part 13

- content/ko/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
- content/ko/docs/tasks/configure-pod-container/configure-volume-storage.md
- content/ko/docs/tasks/configure-pod-container/pull-image-private-registry.md
- content/ko/docs/tasks/configure-pod-container/static-pod.md
Related Issue : https://github.com/kubernetes/website/issues/38458
I have updated some of the outdated contents in dev-1.26-ko.1 branch.
Full changes in the original english content can be checked with this [comparison](https://github.com/kubernetes/website/compare/dev-1.25-ko.1...dev-1.26-ko.1)
M162는 이미 변경 사항이 적용되어 있어서 따로 수정하지 않았습니다.
> [ko] Update outdated korean contents in dev-1.26-ko.1 (M158-162)

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
This PR added the note in the kubeadm join [docs](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#file-or-https-based-discovery)  about the use of `Custom kubelet credentials` and `skipping client TLS bootstrap with CSRs`.
Fixes #40874
> Added the Paragraph: Use of Custom kubelet credentials with the kubeadm join.

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
This PR cleans up page `content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md`.
In particular, I also added line breaks into some comments.
Usually, I diff the en page with cn page to get the changes. But the diff was confusing.
See the following pictures:
Before adding line breaks:
After adding line breaks:
We can see that the diff will be more accurate. And the future tracking will also be easier.
So I think, we should not remove some line breaks in comments.
> [zh] cleanup page persistent-volume-v1

- content/en/docs/tutorials/security/apparmor.md
Removed invalid link in Restrict a container 
**Under** 
**Securing a Pod**  in `note` [Upgrade path to GA](https://kubernetes.io/docs/tutorials/security/apparmor/#upgrade-path-to-general-availability)
There is no valid link that can be replaced with it
> removed hyperlink in restrict a container

- content/en/blog/_posts/2020-01-15-Kubernetes-on-MIPS.md
- content/en/blog/_posts/2022-12-22-kubelet-credential-providers/index.md
This PR replaces k8s.gcr.io with registry.k8s.io in two blog posts where I think it kinda makes sense to do so:
- 2020-01-15-Kubernetes-on-MIPS.md: this blog post talks about what images they built, but both k8s.gcr.io images are available in the registry, so I think updating makes sense
- 2022-12-22-kubelet-credential-providers/index.md: was referencing k8s.gcr.io, I added registry.k8s.io as well
xref https://github.com/kubernetes/website/issues/39353
xref https://github.com/kubernetes/k8s.io/issues/4738
> [en] Replace k8s.gcr.io with registry.k8s.io in blogs

- content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
Removing the repeated word 'phase' in kubeadm-implementation page under [Mark the node as control-plane
](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#mark-the-node-as-control-plane) section.
> remove word 'phase' as it repeated twice

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
due to https://github.com/kubernetes/kubernetes/pull/117656
> remove featuregate DevicePlugins

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-binding-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/deployment-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-template-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/stateful-set-v1.md
> [zh-cn] sync cluster-role-binding stateful-set priority-class-v1 pod-emplate-v1 deploy

- content/en/docs/concepts/overview/working-with-objects/_index.md
Adds Server Side Field Validation section to [Objects In Kubernetes](/docs/concepts/overview/working-with-objects/). Fixes #39212
> Add server side field validation section

- content/en/docs/tasks/administer-cluster/encrypt-data.md
Plain comments work just as well. A small change that forms part of PR #33285.
> Replace ASCII art arrows in comments

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
This PR does nothing but cleans up page `content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md`.
> [zh] cleanup page pod-disruption-budget-v1

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
This PR do nothing but cleans up page `content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md`.
> [zh] cleanup page network-policy-v1

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/limit-range-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
- content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1.md
This PR resync pages in floder `policy resources` and page `content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1.md` referring to upstream en page.
> [zh] resync 1.27 policy resources/ & endpoint-slice-v1.md

- content/en/blog/_posts/2023-05-18-seccomp-profiles-edge.md
Perform actions below:
- Add a period `.` that is missing
- Add `console` to 3 code snippets by following the context nearby
> add code symbols and a period in seccomp blog

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-node-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1.md
This PR resync page `content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-node-v1.md` and `content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1.md`.
Some extra blanks is removed by the way.
> [zh] resync page csi-node-v1 & secret-v1

- content/en/docs/reference/networking/virtual-ips.md
There's no documentation for kube-proxy's `kernelspace` mode. Add some.
**This isn't complete**; however, Kubernetes v1.26 is ~due out this month~ released and that ~removes~ removed the userspace mode. I'd like to provide at least basic documentation to show that Services can work OK on clusters that include Windows nodes.
/sig windows
/sig network
If someone'd like to take this work and extend it into a bigger PR that really documents how Windows kube-proxy works, great. Technically, the deadline for documenting that was a few releases back when the support was added. ~I assume that we'll get more documentation only after v1.26 has come out.~
> Document Windows kernelspace mode for kube-proxy

- content/en/docs/concepts/storage/volumes.md
The default behavior for volumes is mount with `readOnly` as false. This is not the case for Secret and ConfigMap volumes, which mount by default as ReadOnly volumes.
This change adds the documentation to the main english website under each volume category, and notes the exception for these two volumes on the `readOnly` configuration flag. In addition, there were inconsistencies around using multiple bullet points within a note vs using multiple notes. Given the similarity in the notes for configmaps and secrets, I condensed the secrets notes into a single bulleted note over two separate note blocks for consistency.
https://github.com/kubernetes/website/issues/41103
> Clarify documentation around default mount permissions for Secrets and ConfigMaps

- content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md
This PR resync page `content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md` referring to 1.27 en page.
> [zh] 1.27 resync page kube-scheduler

- content/ko/docs/tasks/administer-cluster/cluster-upgrade.md
- content/ko/docs/tasks/administer-cluster/dns-custom-nameservers.md
- content/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
- content/ko/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
- content/ko/docs/tasks/administer-cluster/use-cascading-deletion.md
- content/ko/docs/tasks/configmap-secret/managing-secret-using-config-file.md
Related Issue: #[38458](https://github.com/kubernetes/website/issues/38458#issuecomment-1512426915)
Updated outdated files in content/en/docs/tasks/.
> ### 7 files to be modified
> [ko] Update outdated files in dev-1.26.-ko.1 [M149-155]

- content/en/docs/setup/production-environment/container-runtimes.md
Add links that reference other documents to make more clear the configuration of the cgroupDriver. Fixes #37108
> Add references to kubelet kubeadm and cgroupDriver

- content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
Add links to explain the differences between the kubelet's and kubeadm default cgroupDriver. Fixes #36492
> Clarify kubelet vs kubeadm default cgroupDriver options

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
The section [_Installing kubeadm, kubelet and kubectl : Without a package manager_ ](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) in the _Installing Kubeadm_ doc contains outdated versions. The following has been edited:
- [containernetworking/plugins](https://github.com/containernetworking/plugins/releases) updated to `v1.3.0` from `v1.2.0`
- [kubernetes-sigs/cri-tools](https://github.com/kubernetes-sigs/cri-tools/releases) updated to `v1.27.0` from `v1.26.0`
- [kubernetes/release](https://github.com/kubernetes/release/releases) (Kubelet systemd) to `v0.15.1` from `v0.4.0` (from Aug 10, 2020 - almost 3 years old!)
Other than that, the new changes have been tested multiple times inside Debian 11 and Ubuntu …
> Kubeadm without a package manager: Update cni, crictl and systemd versions

- content/zh-cn/docs/setup/production-environment/container-runtimes.md
- content/zh-cn/docs/tutorials/configuration/_index.md
- content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/_index.md
- content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/_index.md
- content/zh-cn/docs/tutorials/kubernetes-basics/explore/_index.md
- content/zh-cn/docs/tutorials/kubernetes-basics/expose/_index.md
- content/zh-cn/docs/tutorials/kubernetes-basics/scale/_index.md
- content/zh-cn/docs/tutorials/kubernetes-basics/update/_index.md
- content/zh-cn/docs/tutorials/security/_index.md
- content/zh-cn/docs/tutorials/services/_index.md
- content/zh-cn/docs/tutorials/stateful-application/_index.md
- content/zh-cn/docs/tutorials/stateless-application/_index.md
- content/zh-cn/docs/tutorials/stateless-application/expose-external-ip-address.md
```
content/zh-cn/docs/setup/production-environment/container-runtimes.md
content/zh-cn/docs/tutorials/configuration/_index.md
content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/_index.md
content/zh-cn/docs/tutorials/kubernetes-basics/explore/_index.md
content/zh-cn/docs/tutorials/kubernetes-basics/expose/_index.md
content/zh-cn/docs/tutorials/kubernetes-basics/scale/_index.md
content/zh-cn/docs/tutorials/kubernetes-basics/update/_index.md
content/zh-cn/docs/tutorials/security/_index.md
content/zh-cn/docs/tutorials/services/_index.md
content/zh-cn/docs/tutorials/stateful-application/_index.md
content/zh-cn/docs/tutorials/stateless-application/_index.md
```
> [zh] sync container-runtimes.md and front matters in tutorials

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha2.md
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha2.md
```
See [preview](https://deploy-preview-41228--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha2/) please.
> [zh] sync pod-scheduling-context-v1alpha2.md

- content/de/docs/tasks/tools/install-kubectl.md
Since `apt-key` [is deprecated](https://manpages.debian.org/testing/apt/apt-key.8.en.html), I changed the install instructions over to store the key under `/usr/share/keyrings/` via gpg.
> Update install-kubectl.md since apt-key is deprecated now

- content/en/docs/concepts/windows/user-guide.md
Fix a broken step 1-2-3 due to incorrect indentations in:
```
content/en/docs/concepts/windows/user-guide.md
```
> Fix step indentations in windows user guide

- content/ja/docs/concepts/cluster-administration/certificates.md
- content/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/ja/docs/tasks/tools/install-kubectl.md
Fixes: https://github.com/kubernetes/website/issues/41069
> [ja] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

- content/en/docs/reference/labels-annotations-taints/_index.md
Documented the EndpointSlice controller ignores nodes with the following labels node-role.kubernetes.io/control-plane or node-role.kubernetes.io/master
Fixes #40602
> Revise details for control plane taints / labels

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
This PR adds a section in the [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) page in the docs explaining the different operators. I have added a common section in the bottom and mentioned this in both the `nodeAffinity` and `podAffinity` section where the operators are mentioned.
Closes #33323 and #39256
> Added section on operators for `nodeAffinity` and `podAffinity`

- content/ja/docs/tasks/debug/_index.md
The Slack channel #kubernetes-dev has been moved/renamed to the #kubernetes-contributors channel for ja language.
This PR changes reference and link from #kubernetes-dev to #kubernetes-contributors.
> [ja] update Slack channel link to #kubernetes-contributors

- Makefile
Copy the approach that we already use for Netlify deploy previews (added in PR https://github.com/kubernetes/website/pull/41142).
It would be OK to drop this once Golang is better able to work with CFS, or if Hugo includes detection for the cgroup CPU limit.
> When building for deploy, limit GOMAXPROCS

- content/en/blog/_posts/2022-12-12-kubernetes-release-artifact-signing.md
Fixed provenance url to match the correct bucket.
/kind cleanup
> Fix broken link in “Kubernetes 1.26: We're now signing our binary release artifacts!”

- content/fr/docs/tasks/tools/install-kubectl.md
The inner curl (stable.txt) needs a -L to follow location.
> Use curl follow location for downloading stable.txt

- content/en/docs/reference/using-api/cel.md
Per https://github.com/kubernetes/website/pull/39642#issuecomment-1451598146 we waited till after 1.27 was released to add this documentation.
> Add authz library details to CEL documentation

- content/en/docs/concepts/containers/images.md
Reinstate the kubelet's built-in pull credentials provider mechanism info that was unintentionally deleted. Fixes #32047
> Reinstate kubelet's pull credentials provider mechanism info

- content/zh-cn/docs/tasks/manage-kubernetes-objects/kustomization.md
Kustomize has deprecated the use of bases in kustomization.yaml files. This PR updates all references to bases in the ko docs to use the newer resources, which is https://github.com/kubernetes-sigs/kustomize/issues/2243.
Original English PR: https://github.com/kubernetes/website/pull/40761
> docs: Update kustomize examples to use non-deprecated resources key (zn-cn lang)

- content/ko/docs/concepts/extend-kubernetes/_index.md
- content/ko/docs/tasks/extend-kubernetes/configure-multiple-schedulers.md
from https://github.com/kubernetes/website/issues/38458
I have updated one of the outdated files in dev-1.26-ko.1 branch.
Full changes in the original english content can be checked with this [comparison](https://github.com/kubernetes/website/compare/dev-1.25-ko.1...dev-1.26-ko.1).
It's one page, but it contains a lot of change in content, so it might be take some time to review.
> [ko] Update outdated files in dev-1.26.-ko.1 [M23]

- content/zh-cn/docs/concepts/security/pod-security-admission.md
Bold symbols need to add an extra space when encountering Chinese symbols
> [zh] Fix bold symbol in pod-security-admission.md

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
This PR fixed the link for Service Proxies under the [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/) docs.
Fixes #41317
> Updated the link for Service Proxies.

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
The plain google signing key for apt does not work anymore. It needs to be "deamord" using gpg.
> Update apt keyring installation

- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_validate.md
- content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
Include the command in kubeadm-config.md.
The generated file is a placeholder and will be updated before 1.28 releases.
PR is targeting the 1.28 branch.
xref https://github.com/kubernetes/kubeadm/issues/2871
> kubeadm: add the "config validate" command as placeholder

- content/en/docs/reference/using-api/api-concepts.md
API reference: Document APIResponseCompression feature gate. Fixes #30639
> Document APIResponseCompression feature gate

- content/zh-cn/docs/reference/using-api/api-concepts.md
- content/zh-cn/docs/reference/using-api/cel.md
Performe actions below:
- `api-concepts.md` has 11 `名字空间` and 6 `命名空间` now, all changed to `名字空间` on a single page for consistency
- `cel.md` is synced again with new english text added
```
content/zh-cn/docs/reference/using-api/cel.md
```
> [zh] sync /using-api/cel.md and api-concepts.md

- content/en/docs/setup/production-environment/container-runtimes.md
- scripts/README.md
- scripts/linkchecker.py
When an absolute link is missing the leading slash (it starts with "docs/foo" instead of "/docs/foo/), print a more specific error instead of the generic catch-all warning.
Without the leading slash, these are treated as relative paths and so lead to non-existing pages.
Also, while we're at it, fix all the instances it detects.
--
For one example, see the `default cgroup driver in the kubelet` here:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroupfs-cgroup-driver
It leads to a page that doesn't exist:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/docs/reference/config-api/kubelet-config.v1beta1
Instead of the intended target:
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
> linkchecker: detect absolute links with missing leading slash

- content/ko/docs/concepts/cluster-administration/system-traces.md
- content/ko/docs/concepts/configuration/configmap.md
- content/ko/docs/concepts/configuration/manage-resources-containers.md
- content/ko/docs/concepts/configuration/overview.md
- content/ko/examples/configmap/configure-pod.yaml
from https://github.com/kubernetes/website/issues/38458
I have updated some of the outdated contents in dev-1.26-ko.1 branch.
I also fixed a url fragment that stopped working because of changing [this header](https://github.com/bugoverdose/website/blob/ac4b1cc1926aa5bea5c1b3efef534e40d8431116/content/ko/docs/concepts/workloads/pods/pod-lifecycle.md?plain=1#L142). https://github.com/kubernetes/website/commit/9758c9b1443dbcdfe741c136228d7767afcb0019
- Before, `#재시작-정책` fragment worked because the header name was `재시작 정책`
- But we have to use `#restart-policy` now.
- Let me know if you want me to make a different PR for this work.
You can check the full comparison [here](https://github.com/kubernetes/website/compare/dev-1.25-ko.1...dev-1.26-ko.1).
> [ko] Update outdated files in dev-1.26.-ko.1 [M14-17]

- content/ko/docs/concepts/configuration/secret.md
- content/ko/docs/concepts/containers/_index.md
- content/ko/docs/concepts/containers/container-lifecycle-hooks.md
- content/ko/docs/concepts/containers/images.md
- content/ko/docs/concepts/containers/runtime-class.md
from https://github.com/kubernetes/website/issues/38458
I have updated some of the outdated contents in dev-1.26-ko.1 branch.
You can check the full comparison [here](https://github.com/kubernetes/website/compare/dev-1.25-ko.1...dev-1.26-ko.1).
> [ko] Update outdated files in dev-1.26.-ko.1 [M18-22]

- content/en/docs/concepts/overview/working-with-objects/labels.md
Fixed a typo in labels.md:
`Labels selectors` -> `Label selectors`.
> Fix typo in labels.md

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
Part of:
#41373
#41374
#41375
#41376
See #41307
> The plain google signing key for apt does not work anymore. It needs to be "deamord" using gpg.
Replaces #41349
> Update apt keyring installation (Chinese)

- content/pt-br/docs/tasks/tools/install-kubectl-linux.md
Part of:
#41373
#41374
#41375
#41376
See #41307
> The plain google signing key for apt does not work anymore. It needs to be "deamord" using gpg.
Replaces #41349
> [pt-br] Update apt keyring installation

- content/en/docs/concepts/overview/components.md
Add CNI plugin entry to list of Addons. Fixes #24627
> Add CNI plugin to list of Addons

- content/en/docs/reference/networking/virtual-ips.md
This PR updated the FEATURE STATE of `ServiceIPStaticSubrange` and `ServiceInternalTrafficPolicy` under the [Virtual IPs and Service Proxies](https://kubernetes.io/docs/reference/networking/virtual-ips/) docs.
Fixes #41379
> Fix feature state for ServiceIPStaticSubrange and ServiceInternalTrafficPolicy

- content/en/docs/concepts/workloads/controllers/job.md
Add note to clarify what happens when multiple pods are started for the same index. Ref #31719
> Add note for when multiple pods are started for the same job index

- content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md
修复{#manually-create-a-long-lived-api-token-for-a-serviceaccount}在页面显示的bug
preview in  https://deploy-preview-41387--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount
> 修复{#manually-create-a-long-lived-api-token-for-a-serviceaccount}在页面显示的bug

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
This PR promotes [KEP-3668: ServiceNodePortStaticSubrange](https://github.com/kubernetes/enhancements/issues/3668) to beta
> KEP-3668: promote ServiceNodePortStaticSubrange to beta

- content/en/docs/concepts/services-networking/dns-pod-service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
/sig network
This updates ExpandedDNSConfig docs for GA.
KEP: https://github.com/kubernetes/enhancements/issues/2595
/hold
this should be merged after [k/k PR](https://github.com/kubernetes/kubernetes/pull/116741)
> Update ExpandedDNSConfig docs for GA

- hugo.toml
> Updated `hugo.toml` for 1.28 release

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
PR: https://github.com/kubernetes/kubernetes/pull/115554
Issue: https://github.com/kubernetes/enhancements/issues/2799
> Add LegacyServiceAccountTokenCleanUp feature in alpha; move LegacyServiceAccountTokenTracking to GA

- content/ja/docs/reference/_index.md
This PR updates Japanese translation of https://kubernetes.io/ja/docs/reference/_index
Fixes #41134
(表現に関わるため、この翻訳についてのデイスカッションは日本語を希望します。)
- sync with English content.
> [ja] update Japanese translation for ja/docs/reference/ index

- hugo.toml
Resolves #41399
This PR modifies the `hugo.toml` file in the **release-1.26** branch to update the `deprecated` field from false to true. This change will activate a deprecation banner in the 1.26 documentation, informing users that the 1.26 version is no longer supported. 
Please note that the current latest release is version 1.27.
> Fix v1.26 docs incorrectly not marked as stale

- content/en/docs/concepts/policy/_index.md
Update [policies](https://kubernetes.io/docs/concepts/policy/) section to describe what a policy is, what types of policies Kubernetes offers, and provide details and links for each.
Fixes https://github.com/kubernetes/website/issues/40970
(Please see prior PR https://github.com/kubernetes/website/pull/40969 for comment history and updates - I closed that due to a `git rebase` error.)
> update policies concepts page

- content/en/docs/concepts/storage/volume-health-monitoring.md
- content/en/docs/concepts/storage/volume-pvc-datasource.md
- content/en/docs/concepts/storage/volume-snapshot-classes.md
Tweaked long lines in 3 files, without any other text change:
```
content/en/docs/concepts/storage/volume-health-monitoring.md
content/en/docs/concepts/storage/volume-pvc-datasource.md
content/en/docs/concepts/storage/volume-snapshot-classes.md
```
> tweak line wrappings in concepts/storage/

- content/en/docs/concepts/security/controlling-access.md
- content/en/docs/concepts/services-networking/ingress.md
- content/en/docs/concepts/services-networking/service-topology.md
Performed actions below in 3 files:
- remove redundant blank lines
```
content/en/docs/concepts/security/controlling-access.md
content/en/docs/concepts/services-networking/ingress.md
content/en/docs/concepts/services-networking/service-topology.md
```
> Tweak line wrappings in /services-networking/

- content/en/docs/contribute/style/content-guide.md
- content/en/docs/contribute/style/content-organization.md
- content/en/docs/contribute/style/style-guide.md
Performed actions below in 3 files:
- remove redundant blank lines
```
content/en/docs/contribute/style/content-guide.md
content/en/docs/contribute/style/content-organization.md
content/en/docs/contribute/style/style-guide.md
```
> Tweak line wrappings in /contribute/style

- content/en/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md
Seem a `(` is missing, which is not a pair currently.
> Added `(` to complete a pair of parentheses in kubelet-integration.md

- layouts/partials/hooks/body-end.html
- layouts/shortcodes/codenew.html
fixes: #37206
also closes: #34736
The key change is to use `textContent` instead of `innerText` of the element we want to copy text from. The reason is that `innerText` will take CSS styles into account, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext). While `textContent` only considers text. The side effect is that spaces and newlines inside the element `<div class="includecode"...>` matters. So we need to eliminate them when rendering the template.
Another change is that `document.execCommand("copy")` API is deprecated, so I changed it to a more [modern API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText).
> fix: eliminate extra lines when copying to clipboard

- content/en/docs/concepts/windows/intro.md
- content/en/docs/concepts/workloads/pods/user-namespaces.md
Have attempted to pick and replace `{{< skew currentVersion >}}` with `{{< skew currentPatchVersion >}}` in the concepts folder.
> replace `currentVersion` with `currentPatchVersion` in concepts

- content/ja/_index.html
This PR updates Japanese translation of https://kubernetes.io/ja
Fixes #41130
(表現に関わるため、この翻訳についてのデイスカッションは日本語を希望します)
- added download link
- updated events info
> [ja] update Japanese translation for https://kubernetes.io/ja

- content/en/docs/concepts/architecture/cri.md
- content/en/docs/reference/command-line-tools-reference/kubelet.md
- content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
- content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
- content/en/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
Fixes #41401
https://github.com/kubernetes/kubernetes/pull/114017 removed the comment in v1.27.
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ is not re-generated. This is a little confusing to me.
> Container runtime cleanup

- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
- **EN upstream**: `content/en/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md`
- **Sync to**: `content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
diff --git a/content/en/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md b/content/en/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
index 8e04dd7a6c..f6f3db70dd 100644
--- a/content/en/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
+++ …
```
> [zh] sync migrating-from-dockershim/find-out-runtime-you-use.md

- content/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Part of:
#41373
#41374
#41375
#41376
See #41307
> The plain google signing key for apt does not work anymore. It needs to be "deamord" using gpg.
Replaces #41349
> Update apt keyring installation (Japanese)

- content/en/docs/concepts/services-networking/service.md
In the External IPs section, the text mentions a couple of paths from the Service manifest that determine how clients can access the service. Those paths are misspelled, and this PR fixes that.
> Fix referenced paths in Service page

- content/zh-cn/docs/concepts/scheduling-eviction/kube-scheduler.md
Related issues: #41537 
Correcting link ` [Pod 拓扑分布约束](/docs/concepts/scheduling-eviction/topology-spread-constraints/)`  to `[Pod 拓扑分布约束](/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints/)`
> [zh] fix kube-scheduler page error link

- content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
- **EN upstream**: `content/en/docs/concepts/workloads/pods/pod-lifecycle.md`
- **Sync to**: `content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md`
- **Updates**:
- Sync'ed a new caution to pod-lifecycle.md from the EN upstream.
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
diff --git a/content/en/docs/concepts/workloads/pods/pod-lifecycle.md b/content/en/docs/concepts/workloads/pods/pod-lifecycle.md
index b209a6a65f..1636fe3a9d 100644
--- a/content/en/docs/concepts/workloads/pods/pod-lifecycle.md
+++ b/content/en/docs/concepts/workloads/pods/pod-lifecycle.md
@@ -316,6 +316,10 @@ Each probe must define exactly one of these four mechanisms:
the port is open. If the remote system (the …
```
> [zh] sync workloads/pods/pod-lifecycle.md

- content/en/docs/concepts/cluster-administration/flow-control.md
There's a small typo in the `PriorityLevelConfiguration` section where the leading `c` is missing from the word `concurrency`.  This PR fixes the typo.
> Fixes a typo for "concurrency" in PriorityLevelConfiguration section

- content/ko/docs/concepts/architecture/leases.md
Translated [Leases](https://kubernetes.io/docs/concepts/architecture/leases/) in Korean.
쿠버네티스 문서/개념/클러스터 아키텍처 항목의 미번역된 [Leases](https://kubernetes.io/docs/concepts/architecture/leases/)를 한국어로 번역하였습니다.
> [ko] translate leases.md into Korean

- content/zh-cn/docs/concepts/cluster-administration/flow-control.md
- **EN upstream**: `content/en/docs/concepts/cluster-administration/flow-control.md`
- **Sync to**: `content/zh-cn/docs/concepts/cluster-administration/flow-control.md`
- **Updates**:
- Sync'ed a spelling error fix from EN upstream
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/cluster-administration/flow-control.md
diff --git a/content/en/docs/concepts/cluster-administration/flow-control.md b/content/en/docs/concepts/cluster-administration/flow-control.md
index 1a1438c5c0..9e61c95d8b 100644
--- a/content/en/docs/concepts/cluster-administration/flow-control.md
+++ b/content/en/docs/concepts/cluster-administration/flow-control.md
@@ -193,7 +193,7 @@ A PriorityLevelConfiguration represents a single priority level. Each …
```
> [zh] sync concepts/cluster-administration/flow-control.md

- content/zh-cn/docs/concepts/services-networking/ingress-controllers.md
- **EN upstream**: `content/en/docs/concepts/services-networking/ingress-controllers.md`
- **Sync to**: `content/zh-cn/docs/concepts/services-networking/ingress-controllers.md`
- **Updates**:
- Sync'ed 2 new ingress controller (`FortiADC Ingress Controller` and `ngrok Kubernetes Ingress Controller`) to ingress-controllers.md from the EN upstream.
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/services-networking/ingress-controllers.md
diff --git a/content/en/docs/concepts/services-networking/ingress-controllers.md b/content/en/docs/concepts/services-networking/ingress-controllers.md
index 7391839f85..fc19265b39 100644
--- a/content/en/docs/concepts/services-networking/ingress-controllers.md
+++ …
```
> [zh] sync concepts/service-networking/ingress-controllers.md

- content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
- content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
- content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
- content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html
Remove a dangling </div> element that is causing the following pages to break rendering:
* `tutorials/kubernetes-basics/create-cluster/cluster-interactive.html`
* `tutorials/kubernetes-basics/deploy-app/deploy-interactive.html`
* `tutorials/kubernetes-basics/explore/explore-interactive.html`
* `tutorials/kubernetes-basics/expose/expose-interactive.html`
* `tutorials/kubernetes-basics/scale/scale-interactive.html`
* `tutorials/kubernetes-basics/update/update-interactive.html`
/cc @sftim
> [en] Remove dangling </div> from interactive tutorials pages

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- **EN upstream**: `content/en/docs/concepts/configuration/manage-resources-containers.md`
- **Sync to**: `content/zh-cn/docs/concepts/configuration/manage-resources-containers.md`
- **Updates**:
- Sync'ed a new `NOTE` to manage-resources-containers.md from the EN upstream.
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
diff --git a/content/en/docs/concepts/configuration/manage-resources-containers.md b/content/en/docs/concepts/configuration/manage-resources-containers.md
index 45686178d6..f5ec08df70 100644
--- a/content/en/docs/concepts/configuration/manage-resources-containers.md
+++ b/content/en/docs/concepts/configuration/manage-resources-containers.md
@@ -256,6 +256,18 @@ Your …
```
> [zh] sync concepts/configuration/manage-resources-containers

- content/en/docs/tasks/administer-cluster/ip-masq-agent.md
This PR fixed the line wrappings and some trivial bugs of the [IP Masquerade Agent User Guide](https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/) task page.
> Improvement: Tweak line wrapping for the ip-masq-agent task page.

- content/ko/docs/tasks/debug/_index.md
The Slack channel #kubernetes-dev has been moved/renamed to the #kubernetes-contributors channel for ko language.
This PR changes reference and link from #kubernetes-dev to #kubernetes-contributors.
> [ko] update Slack channel link to #kubernetes-contributors

- content/ko/docs/tasks/manage-kubernetes-objects/kustomization.md
Kustomize has deprecated the use of bases in kustomization.yaml files. This PR updates all references to bases in the ko docs to use the newer resources, which is https://github.com/kubernetes-sigs/kustomize/issues/2243.
Original English PR: https://github.com/kubernetes/website/pull/40761
> docs: Update kustomize examples to use non-deprecated resources key (ko lang)

- content/en/blog/_posts/2023-05-24-oci-security-profiles.md
Removed **Bundle Bar**  registry from blog 2023 oci-security-profiles
As the **Bundle Bar** registry is not working
Remove link : [Bundle Bar](https://bundle.bar/docs/supported-clients/oras)
> Remove Bundle Bar registry link

- content/en/docs/tasks/configure-pod-container/configure-gmsa.md
Performed two actions:
- Add a space after the `#` symbol when using it for code comments
> Tweak line wrappings in configure-gmsa.md

- content/pt-br/docs/contribute/style/style-guide.md
- content/pt-br/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/pt-br/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/pt-br/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
- content/pt-br/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
- content/pt-br/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
* Remove references to Katacoda from the style guide.
* Disable interactive tutorials that relied on Katacoda.
/cc @edsoncelio @devlware
Fixes #41456
> [pt-br] Remove Katacoda references and tutorials

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
As part of the sandbox KEP there was a request to rename `PodHasNetwork` to `PodReadyToStartContainers`. 
We have a PR for the code changes and we should update the website with the changes also.  
Some questions:
Do we change the blog post on 1.25 for PodHasNetwork to use the new Conditions?  
Are the feature toggle tables autogenerated?  I did not change the references for that as it doesn't look to be human written.  
PR: https://github.com/kubernetes/kubernetes/pull/117702
> rename PodHasNetwork to PodReadyToStartContainers

- content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md
The nodescore calculation formula misses parentheses causing it confusing to understand.
> Fix node score calculation in resource-bin-packing.md

- content/pt-br/docs/contribute/style/content-guide.md
- data/i18n/pt-br/pt-br.toml
* Synchronize the internationalization string list to add the new strings from the English version.
* Reorder strings in the `pt-br.toml` file to alphabetical order.
* Add anchor to the content guide in Portuguese so that the notices link to the right place.
> [pt-br] Sync Brazilian Portuguese internationalization strings

- content/en/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
- content/en/examples/application/wordpress/mysql-deployment.yaml
- content/en/examples/application/wordpress/wordpress-deployment.yaml
Updated the Wordpress Stateful example to use MySQL 8. This change allows users on Arm architecture to use the example as there does not appear to be a MySQL 5.6 image for Arm chips. I upgraded Wordpress as well to be compatible with MySQL8. 
The new images support the creation of named users and databases, this allows us to use non-root users for the example.
> Update Wordpress stateful example to use MySQL8 and Wordpress 6.2. Improved database setup.

- content/en/docs/reference/using-api/api-concepts.md
fixed issue #40892 
fixed the syntactical error in the link `/docs/reference/generated/kubernetes-api/v{{ skew currentVersion >}}/#listmeta-v1-meta` and `/docs/reference/generated/kubernetes-api/v{{ skew currentVersion >}}/#objectmeta-v1-meta` in the https://github.com/kubernetes/website/blob/main/content/en/docs/reference/using-api/api-concepts.md file.
> fixed the error in the syntax of the metadata link

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
This PR fixes the indentation and wrapping issues in the probes task page.
> Tidy up the probes task page

- content/zh-cn/blog/_posts/2020-01-15-Kubernetes-on-MIPS.md
This is a follow up on #40585 to replace k8s.gcr.io with registry.k8s.io in a Chinese translation of Kubernetes on MIPS blog post.
xref https://github.com/kubernetes/website/issues/39353
xref https://github.com/kubernetes/k8s.io/issues/4738
/hold
for #40585 to get merged first
> [zh-cn] Replace k8s.gcr.io with registry.k8s.io in blog

- content/zh-cn/docs/concepts/services-networking/service.md
当你的 Pod **具有**访问某 Service，并且你在使用环境变量方法将端口和集群 IP 发布到客户端 Pod 时，必须在客户端 Pod 出现之前创建该 Service。
更改为:
当你的 Pod **需要**访问某 Service，并且你在使用环境变量方法将端口和集群 IP 发布到客户端 Pod 时，必须在客户端 Pod 出现之前创建该 Service。
> "具有"更改为“需要”

- content/ja/docs/home/supported-doc-versions.md
This PR updates Japanese translation of https://kubernetes.io/ja/docs/home/supported-doc-versions/
Fixes #41580 
(表現に関わるため、この翻訳についてのデイスカッションは日本語を希望します。)
> [ja] update Japanese translation /docs/home/supported-doc-versions

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-v1alpha2.md
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-v1alpha2.md
```
see [preview](https://deploy-preview-41696--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-v1alpha2/) please.
> [zh] sync /kubernetes-api/resource-claim-v1alpha2.md

- content/en/docs/contribute/style/style-guide.md
fixed Buggy example for note shortcode. by removing **Backticks** from the example.
> {{< note >}}Grease the pan for best results.{{< /note >}}
**Page**: https://kubernetes.io/docs/contribute/style/style-guide/#common-shortcode-issues
> fixed buggy example note shortcode

- content/en/releases/patch-releases.md
- data/releases/schedule.yaml
Update the release page with June patch releases, remove May and June from the upcoming list, and add tentative dates for September.  I left 1.24 in and included a next release for it because it will be ahead of the EOL date, but maybe that should be empty?
/sig release
/kind cleanup
/assign @xmudrii @saschagrunert @puerco
> update to reflect june patches

- content/zh-cn/blog/_posts/2023-05-11-nodeport-dynamic-and-static-allocation.md
Sync with en blog:
```
content/zh-cn/blog/_posts/2023-05-11-nodeport-dynamic-and-static-allocation.md
```
See [preview](https://deploy-preview-40673--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/05/11/nodeport-dynamic-and-static-allocation/) please.
> [zh] sync blog: nodeport-dynamic-and-static-allocation

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
kubeadm: add docs for UpgradeAddonsBeforeControlPlane feature gate
Ref kubernetes/kubeadm#2346
> kubeadm: add docs for UpgradeAddonsBeforeControlPlane feature gate

- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
sync content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> [zh-cn] sync configure-liveness-readiness-startup-probes.md

- content/ja/docs/concepts/architecture/cgroups.md
- **EN upstream**: `content/en/docs/concepts/architecture/cgroups.md`
- **Sync to**: `content/ja/docs/concepts/architecture/cgroups.md`
- **Updates**:
- Sync'ed upstream cases for `JDKを利用している場合`
```diff
$ scripts/lsync.sh content/ja/docs/concepts/architecture/cgroups.md
diff --git a/content/en/docs/concepts/architecture/cgroups.md b/content/en/docs/concepts/architecture/cgroups.md
index 377c073b42..b0a98af660 100644
--- a/content/en/docs/concepts/architecture/cgroups.md
+++ b/content/en/docs/concepts/architecture/cgroups.md
@@ -102,7 +102,12 @@ updated to newer versions that support cgroup v2. For example:
Update these agents to versions that support cgroup v2.
* If you run [cAdvisor](https://github.com/google/cadvisor) as a stand-alone …
```
> [ja] sync concepts/architecture/cgroups.md

- content/ja/docs/tutorials/_index.md
This PR updates Japanese translation of https://kubernetes.io/docs/tutorials/_index
Fixes #40543
(表現に関わるため、この翻訳についてのデイスカッションは日本語を希望します。
英語の更新に同期し、各リンクの見出しは日本語記事の見出しに合わせました)
> [ja] update Japanese translation for /docs/tutorials/_index

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Graduate the kubelet podresources endpoint to GA
KEP: https://github.com/kubernetes/enhancements/issues/606
enhancement: https://github.com/kubernetes/enhancements/issues/3743
reopen https://github.com/kubernetes/website/pull/39959 for 1.28
> node: graduate the podresources API endpoint to GA

- content/zh-cn/docs/tasks/debug/debug-cluster/audit.md
Fix [#41704](https://github.com/kubernetes/website/issues/41704)
This PR added two space, one is in front of "审计（Auditing）" to ensure there is a space between Chinese and English, one is behind "审计（Auditing）" to make the bold effective.
> [zh-cn] fix the bold effect at 审计（Auditing）

- content/en/docs/reference/using-api/deprecation-guide.md
Performed 2 actions:
- indent by 2 spaces to keep consistency in context
in
```
content/en/docs/reference/using-api/deprecation-guide.md
```
/kind cleanup
> Indent consistently and wrap long lines in deprecation-guide.md

- content/ja/docs/concepts/architecture/control-plane-node-communication.md
- **EN upstream**: `content/en/docs/concepts/architecture/control-plane-node-communication.md`
- **Sync to**: `content/ja/docs/concepts/architecture/control-plane-node-communication.md`
- **Updates**:
- Sync'ed upstream `glossary_tooltip`s.
- Sync'ed upstream `What Next`.
```diff
$ scripts/lsync.sh content/ja/docs/concepts/architecture/control-plane-node-communication.md
diff --git a/content/en/docs/concepts/architecture/control-plane-node-communication.md b/content/en/docs/concepts/architecture/control-plane-node-communication.md
index 785040cda3..2cfa37d5c5 100644
--- a/content/en/docs/concepts/architecture/control-plane-node-communication.md
+++ b/content/en/docs/concepts/architecture/control-plane-node-communication.md
@@ -11,7 +11,8 …
```
> [ja] sync concepts/architecture/control-plane-node-communication.md

- content/ko/examples/admin/konnectivity/konnectivity-agent.yaml
- content/ko/examples/admin/konnectivity/konnectivity-server.yaml
- content/ko/examples/admin/sched/my-scheduler.yaml
- content/ko/examples/application/php-apache.yaml
- content/ko/examples/concepts/policy/limit-range/problematic-limit-range.yaml
- content/ko/examples/pods/inject/secret-pod.yaml
- content/ko/examples/pods/pod-with-scheduling-gates.yaml
- content/ko/examples/security/kind-with-cluster-level-baseline-pod-security.sh
- content/ko/examples/security/kind-with-namespace-level-baseline-pod-security.sh
- content/ko/examples/service/networking/custom-dns.yaml
Related Issue: #41631
Updated outdated files in `content/ko/examples/`.
**10 files to be modified**
> [ko] Update outdated files in dev-1.27-ko.1 (M244-M253)

- content/ko/docs/tasks/administer-cluster/safely-drain-node.md
Translated [Safely Drain a Node](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/) in Korean.
쿠버네티스 문서/개념/보안 항목의 미번역된 [Safely Drain a Node](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)를 한국어로 번역.
Issued in #41275
> [ko] Translate safely-drain-node.md into Korean

- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
Fix key usage permitted by `kubernetes.io/kubelet-serving` signer.
rel: https://github.com/kubernetes/website/pull/40968
> Fix permitted key usages

- content/zh-cn/docs/reference/using-api/deprecation-guide.md
Sync with en #41758
```
content/zh-cn/docs/reference/using-api/deprecation-guide.md
```
See [preview](https://deploy-preview-41762--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/using-api/deprecation-guide/) please.
> [zh] sync /using-api/deprecation-guide.md

- content/ko/docs/concepts/scheduling-eviction/kube-scheduler.md
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/kube-scheduler/#kube-scheduler-implementation
이 페이지에서 '스케줄링 정책'의 바로가기 링크에 '스케줄링 프로파일' 링크로 잘못 붙어 있어서 수정했습니다.
> [ko] Update content/ko/docs/concepts/scheduling-eviction/kube-scheduler.md

- content/ja/docs/tutorials/security/cluster-level-pss.md
This PR adds Japanese translation of https://kubernetes.io/docs/tutorials/security/cluster-level-pss
Fixes #40693
(表現に関わるため、この翻訳についてのデイスカッションは日本語を希望します。)
- This translation depends on the translation terms of #40542
> [ja] add Japanese translation for /docs/tutorials/security/cluster-level-pss

- content/ko/docs/concepts/configuration/configmap.md
- content/ko/docs/concepts/configuration/manage-resources-containers.md
- content/ko/docs/concepts/configuration/overview.md
- content/ko/docs/concepts/configuration/secret.md
- content/ko/docs/concepts/containers/container-environment.md
Related Issue : https://github.com/kubernetes/website/issues/41631
M20 : 문서의 변동사항이 없어 수정하지 않았습니다.
> [ko] Update outdated files in dev-1.27-ko.1 [M16-21]

- content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Stresses that behavior controls define limits to scaling (what at most can happen) and not the size of scaling actions verbatim. This is currently being repeatedly misunderstood by users.
> Clarify horizontal pod autoscaler docs on scaling behavior

- content/ja/docs/setup/_index.md
This PR updates Japanese translation of https://kubernetes.io/ja/docs/setup/
Fixes #41582
(表現に関わるため、この翻訳についてのデイスカッションは日本語を希望します。)
This PR is just rebased version of #41583, so review was done by @t-inu.
> [ja] update Japanese translation for /docs/setup/_index

- OWNERS_ALIASES
- Based on the consensus to appoint @seokho-son as co-lead for the Localization subproject of SIG Docs,
this PR update OWNERS_ALIASES by adding `seokho-son` to sig-docs-localization-owners
- https://groups.google.com/g/kubernetes-sig-docs/c/mx1fd_WizX4/m/P1tGHol4BAAJ
> Hello SIG Docs community,
> 
> After having formalized the [Localization subproject](https://kubernetes.io/docs/contribute/localization/) some time ago, we've been able to help several localization teams across SIG Docs with their translation work, alongside bootstrapping new languages and supporting new localization contributors. Brad Topol recently stepped down as a co-lead for the subproject, and we've had Seokho Son step up to support Abbie (Localization Lead) in continuing the localization mission for the SIG.
> 
> …
> Add `seokho-son` to sig-docs-localization-owners

- content/fr/docs/setup/learning-environment/minikube.md
- content/fr/docs/tasks/tools/install-kubectl.md
Use `{{% skew currentPatchVersion %}}` shortcode instead.
Fixes https://github.com/kubernetes/website/issues/41290
/cc @sftim @feloy
> [fr] Replace use of deprecated `fullversion` param

- content/en/docs/reference/access-authn-authz/admission-controllers.md
This is the third step of https://github.com/kubernetes/kubernetes/issues/111516.
Preview [here](https://deploy-preview-40166--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/admission-controllers/#securitycontextdeny).
This is the documentation side of this PR https://github.com/kubernetes/kubernetes/pull/115879.
I was too slow and the feature gate was documented by https://github.com/kubernetes/website/pull/40623. So this PR is just more documentation on the deprecation of the admission controller.
> Update scdeny plugin documentation for deprecation

- OWNERS_ALIASES
Per #41598 , we're housekeeping the Hindi reviewers to ensure better management of the Hindi localization. These are the members that have been housekept since they have not voiced any opposition to their inactivity:
- Kunal Verma
- Garima Negi
> Housekeeping inactive Hindi reviewers

- content/en/docs/reference/access-authn-authz/abac.md
This PR cleans up page `abac`:
1. The indentation of list items should be 2 spaces for unordered lists, or 3 spaces for ordered lists.
2. Wrap long lines.
3. Add shell code block for `kubectl --v=8 version`.
> cleanup page abac

- content/de/docs/concepts/architecture/_index.md
Fix the translation[de] error for word  "Architekur" to "Architektur"
On path  /de/docs/concepts/architecture.
> Fix incorrect translation[de] for word ''Architekur'' to  "Architektur"

- content/en/blog/_posts/2017-11-00-Autoscaling-In-Kubernetes.md
Since https://kubernetes.io/blog/2017/11/autoscaling-in-kubernetes/ was published, we've somehow lost the link to the YouTube video.
Put it back ([preview](https://deploy-preview-40975--kubernetes-io-main-staging.netlify.app/blog/2017/11/autoscaling-in-kubernetes))
/area blog
> Fix 2017 autoscaling blog article

- content/en/docs/concepts/services-networking/service.md
> Document detail about headless Services

- content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
The kubelet is run in standalone mode and these fields are required
so that the config is accepted. In this guide the kubelet
is only used as a service manager. Note that while the authz
mode is AlwaysAllow, anonymous and webhook authn are disabled.
/kind cleanup
> setup-ha-etcd-with-kubeadm.md: add missing authn/authz fields

- content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
```
```
See [preview 1](https://deploy-preview-41815--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/admission-controllers/) and [preview 2](https://deploy-preview-41815--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) please.
> [zh] sync admission-controllers.md and configure-liveness-readiness-startup-probes.md

- content/zh-cn/docs/concepts/overview/working-with-objects/namespaces.md
- **EN upstream**: `content/en/docs/concepts/overview/working-with-objects/namespaces.md`
- **Sync to**: `content/zh-cn/docs/concepts/overview/working-with-objects/namespaces.md`
```diff
$ ./scripts/lsync.sh content/zh-cn/docs/concepts/overview/working-with-objects/namespaces.md
diff --git a/content/en/docs/concepts/overview/working-with-objects/namespaces.md b/content/en/docs/concepts/overview/working-with-objects/namespaces.md
index a1865b5ced..29d9ff857c 100644
--- a/content/en/docs/concepts/overview/working-with-objects/namespaces.md
+++ b/content/en/docs/concepts/overview/working-with-objects/namespaces.md
@@ -150,8 +150,7 @@ kubectl api-resources --namespaced=false
{{< feature-state for_k8s_version="1.22" state="stable" >}}
The …
```
> [zh] sync concepts/overview/working-with-objects/namespaces.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
1. `CNI_PLUGINS_VERSION`, `CRICTL_VERSION` and `RELEASE_VERSION`
update tool version in install-kubeadm without package manager case (https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl)
comparison:
(outdated in Chinese)
(latest changes in English)
---
2. `alpha` -> `beta`
change statement, `alpha` -> `beta` in kubeadm-init config-file part (https://kubernetes.io/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file)
comparison:
(outdated in Chinese)
(latest changes in English)
> [zh] Update outdated version in `install-kubeadm` and `kubeadm-init`

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
followup to https://github.com/kubernetes/website/pull/41506#pullrequestreview-1485713121
we fix the release state of the podresources API (related to device monitoring)
KEP: https://github.com/kubernetes/enhancements/issues/606
enhancement: https://github.com/kubernetes/enhancements/issues/3743
> node: fix release state for podresources API

- content/en/docs/reference/labels-annotations-taints/_index.md
This well known value is a label, and has always been so. This fixes a typo where it was defined as an annotation
See; https://github.com/kubernetes/kubernetes/blob/v1.27.0/pkg/controller/statefulset/stateful_set_utils.go#L137
> Update statefulset pod name docs stating its a label

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
The `AdvancedAuditing` feature gate was graduated to GA in 1.12 and it has been removed in k8s v1.28. Here is the following PR which will remove this feature gate from k8s: [k8s/k8s #118763](https://github.com/kubernetes/kubernetes/pull/118763).  So as a reference to it, this PR moves the `AdvancedAuditing` feature gate from **Feature Gates** to **Feature Gates (removed)**  docs for the k8s v1.28.
> Move Feature Gate AdvancedAuditing to Feature Gates (removed) Page

- content/en/docs/tutorials/services/connect-applications-service.md
This PR fixed the link for the `service proxy` under the [Connecting Applications with Services](https://kubernetes.io/docs/tutorials/services/connect-applications-service/) docs.
Fixes #41891
> Fix broken link to kube-proxy details page

- content/en/docs/tasks/tools/install-kubectl-macos.md
Documented the steps for deleting kubectl on macOS and solving the issue #41149
> Document steps for deleting kubectl on macOS

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
This PR clarifies that the `preStop` hook won't be invoked if the termination grace period is set to 0. Another commit attempts to tidy up the page for paragraphs and indentations.
> Clarify prestop hook invocation condition

- content/en/docs/concepts/cluster-administration/logging.md
- content/en/docs/concepts/cluster-administration/system-logs.md
There are some logging options already dropped in v1.26.
This PR clarifies this fact.
The second commit applies some line-wrapping cleanup, without changing the text.
> Improve sys logs page by clarifying options dropped

- content/en/docs/concepts/workloads/pods/init-containers.md
Fix https://github.com/kubernetes/website/issues/41144 
Ref Link: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#examples
Because `dig myservice` always returns true "0" regardless of whether the name resolves.
To wait for the service to be created, we can replace dig with `nslookup` since "nslookup returns with an exit status of 1 if any query failed, and 0 otherwise."
> Fix a shell command in examples of "Init Containers" page

- content/en/docs/tutorials/services/connect-applications-service.md
Without --rm this creates a pod in the default namespace named `curl` and does not delete on exit. It seems better to remove it on exit.
> Add --rm for temporary pod command

- content/en/docs/concepts/storage/storage-classes.md
Add a section to Storage Classes briefly describing the default StorageClass
- I was looking to add this to the docs myself, but then saw that #15575 had added this section and went through a few review cycles but was never completed and merged
- So initially based it off that, rebasing and addressing all the feedback therein ([these](https://github.com/kubernetes/website/pull/15575#discussion_r317714805) [two](https://github.com/kubernetes/website/pull/15575#pullrequestreview-279732022) points specifically). I ended up rewriting significant chunks as part of the feedback as well as after generally reviewing the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/) and style of the existing doc, trying to more closely match those.
- the PVC docs reference this and there …
> docs(storage-classes): add section on default `StorageClass`

- content/fr/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
- content/fr/examples/application/php-apache.yaml
Hi,
This adds the French translation for the task 'HorizontalPodAutoscaler Walkthrough', from the "Run Applications" section. This is the [reference document](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/).
I also added the missing example file for the task.
> [fr] translate task run-application/horizontal-pod-autoscale-walkthrough.md

- content/zh-cn/docs/concepts/cluster-administration/logging.md
- content/zh-cn/docs/concepts/cluster-administration/system-logs.md
- content/zh-cn/docs/test.md
Sync 3 files with en #41395 and #41863
```
content/zh-cn/docs/concepts/cluster-administration/logging.md
content/zh-cn/docs/concepts/cluster-administration/system-logs.md
content/zh-cn/docs/test.md
```
See previews:
- [logging.md](https://deploy-preview-41900--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/logging/)
- [system-logs.md](https://deploy-preview-41900--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/system-logs/)
- [test.md](https://deploy-preview-41900--kubernetes-io-main-staging.netlify.app/zh-cn/docs/test/)
> [zh] sync logging.md, system-logs.md, and test.md
