kubernetes/website

- content/zh-cn/docs/tasks/configure-pod-container/assign-cpu-resource.md
> [zh-cn] sync assign-cpu-resource.md

- assets/scss/_base.scss
#40793 
Changed selection color on site to kubernetes blue (also changes text color to white for clarity)
> Change selection color to kubernetes blue

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> [zh-cn] sync install-kubeadm.md

- content/hi/docs/contribute/_index.md
Related to https://kubernetes.slack.com/archives/C0191RDKHU1/p1680549820387879
> [hi] Mention kubernetes/websites everywhere in the same way

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
> Update feature gates for v1.27

- content/zh-cn/docs/tasks/configure-pod-container/assign-memory-resource.md
- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- content/zh-cn/docs/tasks/configure-pod-container/security-context.md
> [zh-cn] sync configure-liveness-readiness-startup-probes.md security-context.md and assign-memory-resource.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md
```
```
See [preview](https://deploy-preview-40799--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1/) please.
> [zh] sync /workload-resources/job-v1.md

- content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
[zh] sync 1.27 custom-resource-definitions
> [zh] sync 1.27 custom-resource-definitions

- content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
[zh] sync 1.27 extensible-admission-controllers
> [zh] sync 1.27 extensible admission controllers

- content/zh-cn/docs/reference/glossary/etcd.md
> [zh-cn] sync etcd.md

- content/ru/docs/tasks/administer-cluster/certificates.md
> [ru] update curl command

- content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
sync client-authentication.v1beta1.md
> [zh-cn] sync client-authentication.v1beta1.md

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-review-v1alpha1.md
sync self-subject-review-v1alpha1.md
> [zh-cn] sync self-subject-review-v1alpha1.md

- content/en/blog/_posts/2022-12-27-cpumanager-goes-GA.md
Fixed issue : Broken Link in Blog 2022  #40660
> Fixed broken link blog 2022

- OWNERS_ALIASES
I would like to step down as a Portuguese approvers/reviewers. I've not been able recently to focus on it. @stormqueen1990 @devlware @edsoncelio and @MrErlison are doing a great work here, and I hope they can keep doing this amazing work.
Thank you all for the trust, I am still around if you need something from me
/cc @divya-mohan0209 @natalisucks @jimangel
> rkatz stepping down from pt approvers

- content/zh-cn/docs/concepts/services-networking/service-topology.md
> [zh-cn] sync service-topology.md

- content/zh-cn/docs/reference/kubernetes-api/common-definitions/status.md
> [zh-cn] sync status.md

- content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
This PR syncs extensible-admission-controllers for 1.27
> [zh] sync 1.27 extensible-admission-controllers

- content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
This PR resyncs `content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver`.
> [zh] resync 1.27 kube-apiserver

- content/zh-cn/blog/_posts/2022-12-27-cpumanager-goes-GA.md
The file `\blog\_posts\2022-12-27-cpumanager-goes-GA.md` has been updated in this PR (https://github.com/kubernetes/website/pull/40663) ,so we will synchronize the localization.
> [zh] sync blog\_posts\2022-12-27-cpumanager-goes-GA.md

- content/zh-cn/docs/tasks/administer-cluster/safely-drain-node.md
> [zh-cn] sync safely-drain-node

- data/i18n/de/de.toml
this is my first PR and while reading through the docs, i saw this misspelled word.
> [de] corrected misspelled word

- content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
sync configure-upgrade-etcd.md
> [zh-cn] sync configure-upgrade-etcd.md

- content/en/blog/_posts/2021-12-17-security-profiles-operator-v0.4.0/index.md
> Fix link for AppArmorProfile in blog

- content/en/docs/tasks/tools/install-kubectl-windows.md
fixed:   #40187
Deleting the uneccessary lines according to #40187 issue.
Changes made at:  https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/
> update changes: kubernetes.io/docs/tasks/tools/install-kubectl-windows/

- content/en/blog/_posts/2020-08-14-introducing-hierarchical-namespaces.md
This PR was raised in order to upgrade the links to HNC since it was migfrated to a new repo.
> update links to hnc

- content/en/docs/reference/kubectl/cheatsheet.md
Remove annotation from pod. 
The command will help reader to understand how to remove annotation from pod.
> Add cheat sheet entry: remove annotation from pod

- content/ko/docs/concepts/services-networking/dual-stack.md
- content/ko/docs/concepts/services-networking/topology-aware-hints.md
- content/ko/docs/concepts/services-networking/windows-networking.md
- Related issue: https://github.com/kubernetes/website/issues/38458
- Files to be modified
> [ko] Update outdated files in dev-1.26-ko.1 (M60, M68, M69)

- content/zh-cn/docs/reference/using-api/deprecation-policy.md
> [zh-cn] sync deprecation-policy.md

- content/en/docs/concepts/cluster-administration/addons.md
Only tweaked long lines in this file, without any other changes:
```
content/en/docs/concepts/cluster-administration/addons.md
```
See [preview](https://deploy-preview-40872--kubernetes-io-main-staging.netlify.app/docs/concepts/cluster-administration/addons/) please.
> tweak line wrappings in addons.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/component-status-v1.md
> [zh-cn] sync component-status-v1.md

- content/en/docs/tasks/debug/debug-application/debug-running-pod.md
> Further clarify documented privileges of kubectl debug node

- content/en/docs/concepts/storage/volumes.md
> stated 2 problems in a better way for volumes

- content/it/docs/concepts/cluster-administration/certificates.md
> [it] update curl command

- content/en/docs/tasks/administer-cluster/running-cloud-controller.md
Tweak long lines in this file, no any other changes:
```
content/en/docs/tasks/administer-cluster/running-cloud-controller.md
```
> tweak line wrappings in running-cloud-controller.md

- content/zh-cn/docs/concepts/cluster-administration/addons.md
```
content/zh-cn/docs/concepts/cluster-administration/addons.md
```
> [zh] sync /cluster-administration/addons.md

- content/pt-br/docs/concepts/cluster-administration/certificates.md
> [pt] update curl command

- content/zh-cn/blog/_posts/2023-04-24-openapi-v3-field-validation-ga.md
```
content/zh-cn/blog/_posts/2023-04-24-openapi-v3-field-validation-ga.md
```
See [preview](https://deploy-preview-40819--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/04/24/openapi-v3-field-validation-ga/) please.
> [zh] sync 2023-04-24-openapi-v3-field-validation-ga.md

- content/en/docs/concepts/security/pod-security-standards.md
Fixed Broken Link in Security Pod Security Standard #40867
> Fix broken link in Pod Security Standards

- content/en/blog/_posts/2023-05-08-volume-group-snapshot-alpha.md
This PR fixes a typo in the blog.
> Fix a typo in the blog

- content/en/docs/reference/access-authn-authz/rbac.md
Some unknown symbol is being used currently.
> Fix the comma symbol

- content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
~~merge when https://github.com/kubernetes/kubernetes/pull/117521 is merged~~
https://github.com/kubernetes/kubernetes/pull/117521 is merged
> remove nodes resource from CoreDNS rbac

- content/en/docs/reference/using-api/cel.md
> [en] remove duplicate cel.md

- content/en/releases/version-skew-policy.md
xref https://github.com/kubernetes/enhancements/pull/3936#discussion_r1182649999
/assign @danwinship 
/sig network
> Clarify kube-proxy skew docs

- content/en/blog/_posts/2023-03-10-image-registry-change.md
> [en] remove duplicate "the"

- content/zh-cn/docs/tutorials/security/ns-level-pss.md
> [zh-cn] sync ns-level-pss.md

- content/en/docs/tutorials/kubernetes-basics/update/update-intro.html
> [en] remove duplicate intro html

- content/en/docs/reference/access-authn-authz/authentication.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
> KEP-3325: Promote SelfSubjectReview to GA

- content/zh-cn/docs/concepts/containers/container-environment.md
> [zh-cn] sync container-environment.md

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
Fixed wording in documentation.
> Small wording change

- content/zh-cn/docs/concepts/services-networking/service.md
Related issue: https://github.com/kubernetes/website/issues/40976
Move comment block out of tag block
Before:
After:
> [zh] fix service page `loadbalancer` section display error

- content/ja/docs/concepts/storage/volume-snapshots.md
en PR https://github.com/kubernetes/website/pull/39367/files
> [ja] Update volume mode change annotation in documentation

- content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
sync service-accounts-admin.md
> [zh-cn] sync service-accounts-admin.md

- content/en/docs/concepts/security/pod-security-standards.md
- content/en/docs/concepts/workloads/pods/_index.md
> clarify Windows privileged containers feature enablement

- content/zh-cn/blog/_posts/2023-05-02-hpa-container-resource-metric.md
```
content/zh-cn/blog/_posts/2023-05-02-hpa-container-resource-metric.md
```
See [preview](https://deploy-preview-40941--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/05/02/hpa-container-resource-metric/) please.
> [zh] sync blog: hpa-container-resource-metric.md

- content/zh-cn/docs/concepts/workloads/controllers/job.md
This PR resyncs page `content/zh-cn/docs/concepts/workloads/controllers/job.md`.
> [zh] resync 1.27 job

- content/zh-cn/docs/reference/using-api/api-concepts.md
This PR resyncs page `content/zh-cn/docs/reference/using-api/api-concepts.md`.
> [zh] resync 1.27 api-concepts

- content/zh-cn/docs/tasks/administer-cluster/running-cloud-controller.md
content/zh-cn/docs/tasks/administer-cluster/running-cloud-controller.md
> [zh-cn] sync running-cloud-controller.md

- content/en/docs/reference/config-api/kubelet-config.v1.md
- content/en/docs/reference/config-api/kubelet-config.v1beta1.md
There are some format problems in the generated reference. These problems aren't easy to solve if not fixing the format of the upstream source code comments. This PR fixes them manually.
> Manually tune kubelet configuration reference

- content/zh-cn/docs/reference/config-api/kubelet-config.v1beta1.md
This PR resyncs page `kubelet-config.v1beta1`.
> [zh] resync page kubelet-config.v1beta1

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
- content/zh-cn/docs/tasks/tools/install-kubectl-macos.md
- content/zh-cn/docs/tasks/tools/install-kubectl-windows.md
> [zh-cn] sync install-kubectl-*.md upgrading-windows-nodes.md

- content/zh-cn/blog/_posts/2023-04-17-topology-spread-features.md
```
content/zh-cn/blog/_posts/2023-04-17-topology-spread-features.md
```
See [preview](https://deploy-preview-40986--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/04/17/fine-grained-pod-topology-spread-features-beta/) please.
> [zh] sync blog: 2023-04-17-topology-spread-features.md

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
change `enpoint` to `endpoint`
> Fix: word spelling

- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
- content/zh-cn/docs/concepts/workloads/pods/_index.md
content/zh-cn/docs/concepts/workloads/controllers/deployment.md
> [zh-cn] sync workloads/deployment.md workloads/pods

- content/ja/docs/concepts/services-networking/ingress-controllers.md
Sync docs/concepts/services-networking/ingress-controllers
Edited Page on Deploy Preview: 
https://deploy-preview-40422--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/services-networking/ingress-controllers/
> [ja] Sync docs/concepts/services-networking/ingress-controllers

- content/ja/docs/tasks/administer-cluster/certificates.md
> [ja] update curl command

- content/en/blog/_posts/2023-05-09-Safer-More-Performant-Pruning-in-kubectl-apply.md
> Update employer for ApplySet blog post

- content/en/docs/concepts/windows/user-guide.md
This document is a mix of documentation styles, which would be good to fix long term.
Do some basic cleanup. Split off from https://github.com/kubernetes/website/pull/39578
/sig windows
> Revise Windows container guide

- content/en/docs/concepts/cluster-administration/system-metrics.md
> docs: correcting article usage 

- content/en/docs/concepts/configuration/configmap.md
> Fix a typo in the configmap concept page

- content/en/docs/contribute/new-content/open-a-pr.md
Fix https://github.com/kubernetes/website/issues/41010
> Fix: Wrong git clone URL

- content/en/docs/concepts/extend-kubernetes/_index.md
- content/en/docs/concepts/windows/_index.md
Revise overview for [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/) [[preview](https://deploy-preview-39578--kubernetes-io-main-staging.netlify.app/docs/concepts/windows/)]
- ~Move tutorial into tutorials section~
- Link to other pages from [`/docs/concepts/windows/`](https://k8s.io/docs/concepts/windows/)
- ~Revise guide for scheduling Windows pods~ See PR #40285
/sig windows
> Revise windows in kubernetes section

- content/en/docs/concepts/storage/volumes.md
Fixes Adding navigational link to the [Ephemeral volume] and [persistent volume] #40778
> Added navigational link for ephemeral and persistent volume

- content/zh-cn/docs/concepts/workloads/controllers/job.md
> [zh-cn]sync controllers/job.md

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
rebase the change for the zh-cn version after en version is merged; see PR #41003
> [zh-cn] sync word spelling in chinese

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/zh-cn/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
- content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
M       content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
M       content/zh-cn/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
M       content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
> [zh-cn] sync configure-access-multiple-clusters debug-running-pod install-kubeadm

- content/zh-cn/docs/tutorials/services/connect-applications-service.md
sync connect-applications-service.md
> [zh-cn] sync connect-applications-service.md

- content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
- content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md
M       content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
M       content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md
> [zh-cn] rsync dns-debugging-resolution verify-signed-artifacts

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/concepts/configuration/secret.md
- content/zh-cn/docs/concepts/security/pod-security-standards.md
M       content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
M       content/zh-cn/docs/concepts/configuration/secret.md
M       content/zh-cn/docs/concepts/security/pod-security-standards.md
> [zh-cn]sync manage-resources-containers secret pod-security-standards

- content/zh-cn/docs/concepts/overview/working-with-objects/owners-dependents.md
- content/zh-cn/docs/concepts/windows/intro.md
- content/zh-cn/docs/concepts/windows/user-guide.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/controller-revision-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/replication-controller-v1.md
- content/zh-cn/docs/tutorials/hello-minikube.md
- content/zh-cn/docs/tutorials/security/cluster-level-pss.md
> [zh-cn] sync some en docs

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed.md
This PR resyncs page feature-gates-removed.
> [zh] resync page feature-gates-removed

- content/zh-cn/docs/concepts/overview/components.md
[zh-cn] sync concepts/overview/components.md
> [zh-cn] sync concepts/overview/components.md

- content/id/docs/concepts/cluster-administration/certificates.md
> [id] update curl command

- content/pt-br/blog/_posts/2023-03-10-image-registry-change.md
en PR https://github.com/kubernetes/website/pull/40082/files
> [pt] Fix broken link

- content/en/docs/tasks/administer-cluster/encrypt-data.md
Revise [Encrypting Secret Data at Rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) [[preview](https://deploy-preview-41055--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/encrypt-data/)]
- Change page title (you can encrypt more than Secrets)
- Revise prerequisites
Split out from #33285
> Revise API resource encryption at rest: introduction

- content/ko/docs/tasks/debug/debug-application/debug-service.md
> [ko] Translate tasks/debug/debug-application/debug-service in Korean

- content/en/docs/concepts/configuration/secret.md
> Updated the page in correct format

- content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
> [zh-cn] sync system-metrics.md

- content/zh-cn/docs/concepts/extend-kubernetes/_index.md
sync sync extend-kubernetes/_index.md
> [zh-cn] sync sync extend-kubernetes/_index.md

- content/de/docs/tasks/tools/install-kubectl.md
> [de] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

- content/vi/docs/tasks/tools/install-kubectl.md
> [vi] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

- content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> [pt-br] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

- content/zh-cn/docs/concepts/configuration/configmap.md
- content/zh-cn/docs/contribute/new-content/open-a-pr.md
- content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md
M       content/zh-cn/docs/concepts/configuration/configmap.md
M       content/zh-cn/docs/contribute/new-content/open-a-pr.md
M       content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md
> [zh-cn] sync configmap open-a-pr configure-pod-configmap

- content/ru/docs/tasks/tools/install-kubectl.md
> [ru] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

- content/zh-cn/docs/concepts/overview/working-with-objects/field-selectors.md
- content/zh-cn/docs/concepts/overview/working-with-objects/finalizers.md
- content/zh-cn/docs/concepts/overview/working-with-objects/names.md
- content/zh-cn/docs/concepts/services-networking/dual-stack.md
- content/zh-cn/docs/concepts/windows/_index.md
> [zh-cn] sync windows/_index.md dual-stack.md field-selectors.md finalizers.md names.md

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
due to https://github.com/kubernetes/kubernetes/pull/117655
> move DelegateFSGroupToCSIDriver featuregate

- content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
- content/zh-cn/releases/version-skew-policy.md
sync version-skew-policy.md and configure-upgrade-etcd.md
> [zh-cn] sync version-skew-policy.md and configure-upgrade-etcd.md

- content/zh-cn/docs/reference/kubernetes-api/service-resources/ingress-v1.md
This PR resyncs page `content/zh-cn/docs/reference/kubernetes-api/service-resources/ingress-v1.md`.
> [zh] resync page ingress-v1

- content/zh-cn/blog/_posts/2023-05-09-Safer-More-Performant-Pruning-in-kubectl-apply.md
```
content/zh-cn/blog/_posts/2023-05-09-Safer-More-Performant-Pruning-in-kubectl-apply.md
```
> [zh] sync 2023-05-09-Safer-More-Performant-Pruning-in-kubectl-apply.md

- content/fr/docs/concepts/overview/what-is-kubernetes.md
This pull request corrects a typo on french documentation.
> Fix typo on a word on french documentation

- content/pt-br/docs/reference/glossary/ingress.md
* Update the glossary entry for Ingress to reflect the current English version.
/cc @MrErlison @edsoncelio
Fixes #40122
> [pt-br] Update glossary entry for Ingress

- content/es/docs/concepts/configuration/manage-resources-containers.md
en PR https://github.com/kubernetes/website/pull/39462/files
/assign @electrocucaracha
> [es] Fix link

- content/zh-cn/blog/_posts/2023-05-04-statefulset-autodelete.md
sync 2023-05-04-statefulset-autodelete.md
#41110
> [zh-cn] sync blog 2023-05-04-statefulset-autodelete.md

- content/ko/docs/concepts/containers/container-environment.md
- content/ko/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/ko/docs/tasks/tools/install-kubectl-linux.md
- content/ko/docs/tasks/tools/install-kubectl-macos.md
- content/ko/docs/tasks/tools/install-kubectl-windows.md
- content/ko/docs/tutorials/services/connect-applications-service.md
This PR is to handle the sub-task for Korean in #41005
> [ko] Replace deprecated `fullversion` shortcode for Korean

- content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
- content/zh-cn/docs/reference/kubernetes-api/service-resources/ingress-class-v1.md
content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
content/zh-cn/docs/reference/kubernetes-api/service-resources/ingress-class-v1.md
> [zh-cn] sync endpoints-v1.md and ingress-class-v1.md

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
> [zh-cn]sync extend-resources/mutating-webhook-configuration-v1.md

- content/zh-cn/blog/_posts/2023-05-16-kmsv2-beta.md
localize blog: 2023-05-16-kmsv2-beta.md
Fix https://github.com/kubernetes/website/issues/41106
> [zh-cn] localize blog: 2023-05-16-kmsv2-beta.md

- content/en/docs/concepts/workloads/controllers/deployment.md
Add improvement for documentation per [issue](https://github.com/kubernetes/website/issues/28427)
> add improvement as per issue 28427

- content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
This PR resync page `content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md`.
> [zh]resync page kubeadm-config.v1beta3

- content/pt-br/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
en PR  https://github.com/kubernetes/website/pull/37368/files
> [pt] Fix kubectl auto complete

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1alpha2.md
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1alpha2.md
```
> [zh] sync resource-claim-template-v1alpha2.md

- content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
```
content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
```
See [preview](https://deploy-preview-41133--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/overview/working-with-objects/) please.
> [zh] sync working-with-objects/_index.md

- content/zh-cn/docs/concepts/overview/working-with-objects/annotations.md
- content/zh-cn/docs/concepts/overview/working-with-objects/labels.md
- content/zh-cn/docs/concepts/overview/working-with-objects/object-management.md
- content/zh-cn/docs/concepts/overview/working-with-objects/owners-dependents.md
modified:   content/zh-cn/docs/concepts/overview/working-with-objects/annotations.md
modified:   content/zh-cn/docs/concepts/overview/working-with-objects/labels.md
modified:   content/zh-cn/docs/concepts/overview/working-with-objects/object-management.md
modified:   content/zh-cn/docs/concepts/overview/working-with-objects/owners-dependents.md
> [zh-cn] sync annotations labels owners-dependents

- content/zh-cn/docs/concepts/cluster-administration/flow-control.md
This PR  resyncs page `content/zh-cn/docs/concepts/cluster-administration/flow-control.md`.
> [zh] resync page flow-control

- content/zh-cn/docs/concepts/overview/working-with-objects/namespaces.md
Sync working-with-objects/namespaces.md
> [zh-cn] sync working-with-objects/namespaces.md

- content/zh-cn/docs/reference/access-authn-authz/authentication.md
sync content/zh-cn/docs/reference/access-authn-authz/authentication.md
> [zh-cn] sync reference/access-authn-authz/authentication.md

- content/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1.md
```
content/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1.md
```
See [preview](https://deploy-preview-41141--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1/) please.
> [zh] sync apiserver-config.v1alpha1.md

- content/zh-cn/docs/contribute/review/for-approvers.md
Sync this page with en:
```
content/zh-cn/docs/contribute/review/for-approvers.md
```
See [preview](https://deploy-preview-40358--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/review/for-approvers/).
> [zh] sync /review/for-approvers.md

- content/zh-cn/docs/tasks/configure-pod-container/resize-container-resources.md
- content/zh-cn/examples/pods/qos/qos-pod-5.yaml
```
content/zh-cn/docs/tasks/configure-pod-container/resize-container-resources.md
```
See [preview](https://deploy-preview-41147--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/resize-container-resources/) please.
> [zh] sync resize-container-resources.md

- content/en/docs/concepts/services-networking/service.md
Made changes as per requirement.
Fixes #41067
> Updated Internal Load Balancer annotation for GCP

- content/en/docs/tasks/administer-cluster/switch-to-evented-pleg.md
There are typos and inaccuracies in the current page. This PR fixes them.
> Fix nits in the Evented PLEG page

- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
This PR  resyncs page encrypt-data.
> [zh] resync page encrypt-data

- content/en/docs/reference/command-line-tools-reference/kubelet.md
The `kubelet` reference is maintained manually. This PR syncs the content of the reference to the output from `kubelet --help`.
> Update kubelet reference

- content/zh-cn/docs/tasks/manage-daemon/pods-some-nodes.md
- content/zh-cn/examples/controllers/daemonset-label-selector.yaml
```
content/zh-cn/docs/tasks/manage-daemon/pods-some-nodes.md
```
> [zh] sync tasks/manage-daemon/pods-some-nodes.md

- content/zh-cn/blog/_posts/2023-03-10-image-registry-change.md
Fixes #40202 
```
content/zh-cn/blog/_posts/2023-03-10-image-registry-change.md
```
See [preview](https://deploy-preview-40206--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/03/10/image-registry-redirect/) please.
> [zh] sync 2023-03-10-image-registry-change.md

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/concepts/configuration/secret.md
> [zh-cn] sync manage-resources-containers secret

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attachment-v1.md
This PR  resyncs page `volume-attachment-v1` referring to en upstream.
> [zh] resync page volume-attachment-v1

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md
This PR resync page `content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md`.
> [zh]resync feature-gates in CLI

- content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md
content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md
> [zh-cn] administer-cluster/verify-signed-artifacts.md

- content/en/blog/_posts/2023-05-18-seccomp-profiles-edge.md
PTAL @jhrozek @JAORMX @pjbgf @ccojocar 
Targeted for April 6.
> Add blog post about recording seccomp profiles in edge scenarios

- content/en/docs/reference/access-authn-authz/authentication.md
- content/en/docs/reference/access-authn-authz/node.md
- content/en/docs/tasks/debug/debug-cluster/audit.md
- content/ko/docs/tasks/debug/debug-cluster/audit.md
- content/zh-cn/docs/reference/access-authn-authz/authentication.md
- content/zh-cn/docs/reference/access-authn-authz/node.md
- content/zh-cn/docs/tasks/debug/debug-cluster/audit.md
Hey! I haven't contributed to Kubernetes in a while, but still get pinged by review automation. Removing myself from these lists to save my inbox a few threads :)
> remove ericchiang from reviewers

- OWNERS_ALIASES
As the 1.28 Release Docs lead, I would like to add myself to the approver list for dev-1.28 branch.
/cc @gracenng 
/cc @leonardpahlke
> Approver permissions for 1.28 Release

- content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md
[zh] sync docs/reference/config-api/apiserver-config.v1beta1.md
> [zh] sync docs/reference/config-api/apiserver-config.v1beta1.md

- content/zh-cn/docs/concepts/architecture/controller.md
- content/zh-cn/docs/concepts/architecture/garbage-collection.md
content/zh-cn/docs/concepts/architecture/controller.md
> [zh-cn] sync controller.md garbage-collection.md

- content/en/docs/tasks/administer-cluster/encrypt-data.md
A small change that forms part of PR https://github.com/kubernetes/website/pull/33285.
> Split out advice about config reloads for encryption at rest

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md
This PR resyncs and cleans up page `content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md`.
> [zh] resync & cleanup page persistent-volume-claim-v1

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1.md
/hold untile #41127 is merged.
> [zh] resync page persistent-volume-v1 & storage-class-v1.md

- content/zh-cn/blog/_posts/2023-04-21-node-log-query-alpha.md
> [zh-cn]sync blog: 2023-04-21-node-log-query-alpha.md

- content/zh-cn/docs/concepts/architecture/nodes.md
> [zh-cn] sync architecture/nodes.md

- content/zh-cn/docs/concepts/services-networking/network-policies.md
- content/zh-cn/docs/concepts/storage/volumes.md
> [zh-cn] sync network-policies.md and volumes.md

- content/zh-cn/docs/tasks/administer-cluster/kms-provider.md
```
content/zh-cn/docs/tasks/administer-cluster/kms-provider.md
```
See [preview](https://deploy-preview-41185--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/kms-provider) please.
> [zh] sync /administer-cluster/kms-provider.md

- content/zh-cn/docs/concepts/services-networking/cluster-ip-allocation.md
Fix incorrect IP address description
> Update cluster-ip-allocation.md to fix incorrect IP address description

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1.md
This PR resyncs page `content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1.md`.
> [zh] resync page csi-storage-capacity-v1

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
This PR resyncs and cleanup page `config-and-storage-resources/volume.md`.
> [zh]resync &  cleanup page config-and-storage-resources/volume.md

- content/pt-br/docs/contribute/style/content-guide.md
* Add the Brazilian Portuguese translation for the content guide.
> [pt-br] Add docs/contribute/style/content-guide.md

- content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md
This PR resyncs page `content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md`.
> [zh] 1.27 resync page kube-proxy

- content/zh-cn/docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authentication-resources/service-account-v1.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/flow-schema-v1beta3.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/namespace-v1.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/runtime-class-v1.md
> [zh-cn] sync cluster-resources authentication-resources

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/api-service-v1.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta3.md
M       content/zh-cn/docs/reference/kubernetes-api/cluster-resources/api-service-v1.md
M       content/zh-cn/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta3.md
> [zh-cn] sync api-service-v1.md priority-level-configuration-v1beta3.md

- content/zh-cn/blog/_posts/2023-05-18-seccomp-profiles-edge.md
```
content/zh-cn/blog/_posts/2023-05-18-seccomp-profiles-edge.md
```
See [preview](https://deploy-preview-41202--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/05/18/seccomp-profiles-edge/) please.
> [zh] sync 2023-05-18-seccomp-profiles-edge.md

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1.md
Formtmismatch: shoud be like this 
but got this
> [zh-cn] Update subject-access-review-v1.md

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1.md
> [zh-cn] Update self-subject-access-review-v1.md

- content/id/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/id/docs/tasks/tools/install-kubectl.md
> [ID] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
- content/zh-cn/docs/tasks/administer-cluster/safely-drain-node.md
Sync 2 files with en text:
```
content/zh-cn/docs/tasks/administer-cluster/safely-drain-node.md
```
> [zh] sync encrypt-data.md and safely-drain-node.md

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1.md
> [zh] fix indentation issues for two API references

- content/pt-br/docs/tasks/tools/_index.md
Add translation to Brazilian Portuguese:
- pt-br/docs/tasks/tools/_index.md
/cc @stormqueen1990 @devlware @edsoncelio
> [pt-br] Add docs/tasks/tools/_index

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/_index.md
- content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
- content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
Sync 3 files with en:
```
content/zh-cn/docs/reference/kubernetes-api/extend-resources/_index.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
```
> [zh] sync custom-resource-definition-v1.md

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
Performed these changes:
- change unordered bullets to numbered steps
- remove unnecessary numbering and bullets
- remove unecessary spaces
in
```
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
```
> Fix bullets and step numbers in kubeadm-upgrade.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/event-v1.md
- content/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters.md
> [zh-cn] sync common-parameters.md event-v1.md

- content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
> [zh-cn] sync config-api/apiserver-audit.v1.md

- content/en/blog/_posts/2023-05-24-oci-security-profiles.md
PTAL @jhrozek @JAORMX @pjbgf @ccojocar 
Targeted for May 24.
> Add blog post about OCI security profiles

- content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md
This PR resyncs page `content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md`.
> [zh] 1.27 resync page kubelet

- content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1beta3.md
content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1beta3.md
> [zh-cn] sync kube-scheduler-config.v1beta3.md

- data/releases/schedule.yaml
Update schedule.yaml in include the May patch releases and the June patch release info.
> Update schedule.yaml with May patch release info

- content/zh-cn/docs/reference/using-api/cel.md
- content/zh-cn/docs/reference/using-api/server-side-apply.md
content/zh-cn/docs/reference/using-api/cel.md
content/zh-cn/docs/reference/using-api/server-side-apply.md
> [zh-cn] sync cel.md server-side-apply.md

- content/zh-cn/docs/setup/production-environment/_index.md
```
content/zh-cn/docs/setup/production-environment/_index.md
```
> [zh] sync /setup/production-environment/_index.md

- content/zh-cn/blog/_posts/2023-05-08-volume-group-snapshot-alpha.md
sync 2023-05-08-volume-group-snapshot-alpha.md
#41238
> [zh-cn] sync blog 2023-05-08-volume-group-snapshot-alpha.md

- content/zh-cn/examples/priority-and-fairness/health-for-strangers.yaml
en PR https://github.com/kubernetes/website/pull/40514/files
> [zh] Migrated to use the v1beta3 API version of FlowSchema

- content/en/docs/reference/using-api/api-concepts.md
fixed invalid link of object metadata #40892
> Fixed invalid link for object metadata

- content/en/docs/concepts/workloads/controllers/deployment.md
This PR updated what's next section under deployment page by adding 2 necessary points.
Fixes #38159.
> Added more points to what's next section under deployment page

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-class-v1alpha2.md
Add zh text to this reference page:
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-class-v1alpha2.md
```
See [preview](https://deploy-preview-41272--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-class-v1alpha2/) please.
> [zh] sync resource-class-v1alpha2.md

- content/fr/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/fr/docs/tasks/tools/install-kubectl.md
fixes: https://github.com/kubernetes/website/issues/41069 in France
> [FR] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

- content/en/docs/tasks/administer-cluster/namespaces.md
This page can use more tweaks in addition to the ones proposed in this PR. This PR focuses on line wrappings, empty lines, inappropriate lists, and inappropriate indentations.
> Reformat paragraphs in the namespaces task page

- content/en/docs/reference/config-api/apiserver-admission.v1.md
Fixes: #41098 
Upstream generator fix: kubernetes/website/#322
> Fix generated Admission config API

- content/en/docs/tasks/administer-cluster/cpu-management-policies.md
Add reference link to Resource Management for Pods and Containers. Fixes #33925
> Add link to resource management concepts

- content/en/docs/concepts/services-networking/ingress-controllers.md
> Add FortiADC Ingress controller

- content/en/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
For some unknown reason, the API group wasn't parsed correctly.
> Fix errors in the kcm config API

- content/zh-cn/docs/tasks/administer-cluster/namespaces.md
Sync with en format:
```
content/zh-cn/docs/tasks/administer-cluster/namespaces.md
```
See [preview](https://deploy-preview-41293--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/namespaces/) please.
> [zh] sync /administer-cluster/namespaces.md

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
Sync with en #41262 
```
content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
```
> [zh] sync upgrading-linux-nodes.md

- content/ru/examples/priority-and-fairness/health-for-strangers.yaml
en PR https://github.com/kubernetes/website/pull/40514/files
> [ru] Migrated to use the v1beta3 API version of FlowSchema

- content/ja/docs/tasks/access-application-cluster/list-all-running-container-images.md
- content/ja/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
en PR https://github.com/kubernetes/website/pull/40508/files
> [ja] update link of go package text/template

- content/en/docs/concepts/architecture/nodes.md
Redundant spaces results in a break of new line.
> Fix unintended hard line break

- content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md
This PR resyncs page `content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md`.
> [zh] 1.27 resync page kube-controller-manager

- content/pt-br/examples/priority-and-fairness/health-for-strangers.yaml
en PR https://github.com/kubernetes/website/pull/40514/files
> [pt] Migrated to use the v1beta3 API version of FlowSchema

- content/en/docs/concepts/containers/images.md
Spotted typo in recently updated text
> Fix Kubernetes typo

- content/zh-cn/blog/_posts/2022-12-12-kubernetes-release-artifact-signing.md
Fixed broken link to the release bucket.
/kind cleanup
> [zh-cn] Update 2022-12-12-kubernetes-release-artifact-signing.md

- content/zh-cn/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md
sync resource-usage-monitoring.md
> [zh-cn] sync resource-usage-monitoring.md

- content/pt-br/docs/reference/issues-security/official-cve-feed.md
en PR https://github.com/kubernetes/website/pull/40621/files
> [pt] Make the switch from alpha -> beta

- content/zh-cn/docs/tasks/administer-cluster/switch-to-evented-pleg.md
Add zh text to this file:
```
content/zh-cn/docs/tasks/administer-cluster/switch-to-evented-pleg.md
```
See [preview](https://deploy-preview-40889--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/switch-to-evented-pleg/) please.
> [zh] sync switch-to-evented-pleg.md

- content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
Sync 2 files:
```
content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
```
> [zh] assign-pod-node.md and api-eviction.md

- content/zh-cn/blog/_posts/2021-12-17-security-profiles-operator-v0.4.0/index.md
en PR https://github.com/kubernetes/website/pull/40871/files
> [zh] Fix link for AppArmorProfile in blog

- content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
sync configure-cgroup-driver.md and cpu-management-policies.md
> [zh-cn] sync configure-cgroup-driver.md and cpu-management-policies.md

- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
- content/zh-cn/examples/access/deployment-replicas-policy.yaml
- content/zh-cn/examples/access/validating-admission-policy-audit-annotation.yaml
- content/zh-cn/examples/access/validating-admission-policy-match-conditions.yaml
This PR resync page `content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md`.
> [zh] 1.27 resync validating-admission-policy

- content/es/docs/contribute/start.md
> [es] fix typo

- content/en/docs/tasks/tools/install-kubectl-linux.md
>  Resolve GPG Key issue preventing kubectl installation

- content/zh-cn/docs/concepts/containers/images.md
> [zh-cn]sync containers/images.md

- content/zh-cn/docs/reference/access-authn-authz/abac.md
- content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
- content/zh-cn/docs/reference/kubectl/cheatsheet.md
sync cheatsheet.md and extensible-admission-controllers.md and abac.md
> [zh-cn] sync cheatsheet.md and extensible-admission-controllers.md and abac.md

- content/zh-cn/docs/tasks/manage-kubernetes-objects/kustomization.md
- content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
```
M       content/zh-cn/docs/tasks/manage-kubernetes-objects/kustomization.md
M       content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
```
> [zh-cn]sync install-kubectl-linux kustomization

- content/en/docs/reference/tools/map-crictl-dockercli.md
Could we keep this page to continue to help people to ramp up on crictl commands?
> Retain page “Mapping from dockercli to crictl” (cancel planned removal)

- content/en/docs/concepts/extend-kubernetes/_index.md
Document the kubelet image credential provider extension concept. Fixes #32048
> Document kubelet image credential provider extension concept

- content/id/docs/concepts/workloads/controllers/deployment.md
en PR https://github.com/kubernetes/website/pull/40752/files
/assign @ariscahyadi
> [id] fix incorrect pod-template-hash labels

- content/en/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> fixed correct instructions on the version of control plane nodes

- content/zh-cn/docs/concepts/storage/volumes.md
> [zh] sync storage/volumes

- content/fr/docs/concepts/workloads/controllers/deployment.md
en PR https://github.com/kubernetes/website/pull/40752/files
> [fr] fix incorrect pod-template-hash labels

- data/i18n/en/en.toml
- data/i18n/ko/ko.toml
- layouts/shortcodes/cve-feed.html
메모 및 정보 공유 차원에서 적어 봅니다. ㅎㅎ
이슈: PR #41321 에서 `dev-1.26-ko.1` → `main` merge 하려고 하는데, conflict가 존재합니다.
(저를 포함하여) k/w repo에 write access 가 없는 사람은: 어떤 파일에 어떤 conflict가 있는지 GitHub UI 에서는 확인할 수 없고,
자신의 fork에서 동일한 PR(예: https://github.com/jihoon-seo/k8s-website/pull/1 )을 열어 보면 어떤 파일에 어떤 conflict가 있는지 GitHub UI 에서 확인할 수 있습니다.
확인해 보니,
- `data/i18n/en/en.toml`
- `layouts/shortcodes/cve-feed.html`
파일에 conflict가 있네요.
Resolve conflict 페이지로 가 보면
"Incoming change" 와 "Current change" 가 있는데
"Incoming change" 는 `dev-1.26-ko.1` 에 속하는 change 이고
"Current change" 는 `main` 에 속하는 change 로 보입니다.
저희는 `main` 에 속하는 change를 수용해야 하므로
"Current change" 를 모두 수용하여 커밋을 생성하면 되구요.
CLI 로도 동일 작업을 수행할 수 있습니다.
PR에 conflict가 있는 상태에서 merge 버튼 부근을 보면 찾을 수 있는데요
아마
- `dev-1.26-ko.1` 및 `main` 을 최신으로 업데이트
- `git checkout main`
- `git …
> [ko] Resolve merge conflicts between `dev-1.26-ko.1` & `main`

- content/pt-br/docs/reference/glossary/garbage-collection.md
Add
- pt-br/docs/reference/glossary/garbage-collection.md
> [pt-br] Add docs/reference/glossary/garbage-collection.md

- content/zh-cn/docs/concepts/services-networking/service.md
> [zh-cn] sync services-networking/service.md

- content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md
> [zh] Fix errors in kubelet reference

- content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
- content/zh-cn/docs/tasks/administer-cluster/securing-a-cluster.md
M       content/zh-cn/docs/concepts/storage/volumes.md
M       content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
M       content/zh-cn/docs/tasks/administer-cluster/securing-a-cluster.md
> [zh-cn] sync kubelet-credential-provider securing-a-cluster

- content/zh-cn/docs/contribute/style/style-guide.md
> [zh] sync /style/style-guide.md

- content/zh-cn/docs/tasks/administer-cluster/controller-manager-leader-migration.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/reserve-compute-resources.md
sync cpu-default-namespace reserve-compute-resources controller-manager-leader-migration
> [zh-cn] sync cpu-default-namespace reserve-compute-resources controller-manager-leader-migration

- content/zh-cn/docs/concepts/policy/_index.md
Sync with en #41351:
```
content/zh-cn/docs/concepts/policy/_index.md
```
See [preview](https://deploy-preview-41422--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/policy/) please.
> [zh] sync /concepts/policy/_index.md

- content/zh-cn/docs/concepts/services-networking/topology-aware-routing.md
```
content/zh-cn/docs/concepts/services-networking/topology-aware-routing.md
```
See [preview](https://deploy-preview-41378--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/topology-aware-routing/) please.
> [zh] sync topology-aware-routing.md

- content/ja/docs/setup/production-environment/tools/kubespray.md
en PR https://github.com/kubernetes/website/pull/40318/files
> [ja] fix Equinix Metal url

- content/ja/docs/tutorials/stateful-application/basic-stateful-set.md
en PR https://github.com/kubernetes/website/pull/40180/files
> [ja] fix markdown format

- content/en/docs/concepts/architecture/garbage-collection.md
- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/concepts/cluster-administration/logging.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
> Removing redundant #selector in url and adding line-wrapping cleanup

- content/en/docs/reference/labels-annotations-taints/_index.md
This PR document nfd annotations to https://kubernetes.io/docs/reference/labels-annotations-taints/ document,
referring to comment [here](https://github.com/kubernetes/website/issues/31612#issuecomment-1491997100)
Fixes: #31612
> Document node discovery annotations

- content/zh-cn/docs/tutorials/kubernetes-basics/_index.html
the description before is confused
> [zh-cn] Update kubernetes-basics

- content/zh-cn/docs/concepts/security/controlling-access.md
- content/zh-cn/docs/concepts/services-networking/ingress.md
> [zh-cn] sync ingress.md controlling-access.md

- content/zh-cn/docs/concepts/services-networking/service.md
IPv6 record type within DNS is AAAA other than AAA.
> [zh] Update service.md

- content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
replace master with control plane
synchorize with the English version
> [zh-cn] update cluster-intro

- content/zh-cn/docs/contribute/style/content-guide.md
- content/zh-cn/docs/contribute/style/content-organization.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
```
M       content/zh-cn/docs/contribute/style/content-guide.md
M       content/zh-cn/docs/contribute/style/content-organization.md
M       content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
```
> [zh-cn] sync content-guide content-organization kubeadm-certs

- content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
> [zh] Improve translation of apiserver reference

- content/zh-cn/docs/concepts/overview/working-with-objects/labels.md
found the same as mentioned in #41355
> Typo fix: labels.md

- content/zh-cn/docs/concepts/architecture/garbage-collection.md
- content/zh-cn/docs/concepts/architecture/nodes.md
- content/zh-cn/docs/concepts/cluster-administration/logging.md
- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/concepts/workloads/controllers/job.md
- content/zh-cn/docs/reference/tools/map-crictl-dockercli.md
> [zh-cn]sync manage-resources-containers garbage-collection nodes logging

- content/zh-cn/docs/tasks/manage-gpus/scheduling-gpus.md
Modify the directory hierarchy to be consistent with the English version
preview  in  [Modify the directory hierarchy to be consistent with the English version](https://deploy-preview-41464--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/manage-gpus/scheduling-gpus/#using-device-plugins)
> modify directory hierarchy

- content/zh-cn/docs/reference/networking/virtual-ips.md
sync reference/networking/virtual-ips.md
> [zh-cn] sync reference/networking/virtual-ips.md

- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
- content/zh-cn/docs/reference/instrumentation/slis.md
sync slis.md and deployment.md
> [zh-cn] sync slis.md and deployment.md

- content/zh-cn/docs/concepts/architecture/cri.md
> [zh] sync architecture/cri

- content/es/docs/concepts/workloads/controllers/deployment.md
en PR https://github.com/kubernetes/website/pull/40752/files
/assign @electrocucaracha
> [es] fix incorrect pod-template-hash labels

- content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
```
content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
```
See [preview](https://deploy-preview-41462--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests/) please.
> [zh] sync certificate-signing-requests.md

- content/de/docs/tasks/tools/install-kubectl-linux.md
- content/de/docs/tasks/tools/install-kubectl-macos.md
- content/de/docs/tasks/tools/install-kubectl.md
Fixes https://github.com/kubernetes/website/issues/41490
> [de] Replace deprecated fullversion shortcode

- content/ja/docs/setup/production-environment/turnkey-solutions.md
Translate production-environment/turnkey-solutions.md into ja.
Translated page on Deploy Preview: 
https://deploy-preview-40714--kubernetes-io-main-staging.netlify.app/ja/docs/setup/production-environment/turnkey-solutions/
> [ja] translate production-environment/turnkey-solutions.md

- content/pt-br/docs/tutorials/hello-minikube.md
* Synchronize the hello-minikube tutorial with the latest English version to remove Katacoda references.
/cc @MrErlison @jcjesus
> [pt-br] Update hello-minikube.md to remove Katacoda

- content/ko/docs/reference/node/kubelet-checkpoint-api.md
> [ko] Translate reference/node/kubelet-checkpoint-api in Korean

- content/ko/docs/reference/access-authn-authz/service-accounts-admin.md
- content/ko/docs/reference/command-line-tools-reference/_index.md
- content/ko/examples/secret/serviceaccount/mysecretname.yaml
- Related Issue : #38458 
109. [ ]  **M109.**  `content/en/docs/reference/access-authn-authz/service-accounts-admin.md`  | **328(+L) 90(-)**
110. [ ]  M110.  `content/en/docs/reference/command-line-tools-reference/_index.md`  | 1(+XS) 1(-)
> [ko] Update outdated files in dev-1.26-ko.1 (M109-M110)

- content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
Synced with en text:
```
content/en/docs/concepts/overview/working-with-objects/_index.md
```
> [zh] sync /overview/working-with-objects/_index.md

- content/en/blog/_posts/2023-06-09-dl-adopt-cdn.md
Add blog article on the upcoming change in dl.k8s.io IP addresses and use of CDN.
> Add dl.k8s.io CDN change blog article

- content/es/docs/tasks/tools/included/install-kubectl-linux.md
en PR https://github.com/kubernetes/website/pull/40183/files
/assign @electrocucaracha
> [es] Update install-kubectl-linux.md

- content/en/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
Fixes:#34761
**How the website looks after these changes:**
> Hyperlinked to mention information about accessing services

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
- content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
```
M       content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
M       content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
M       content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
```
> [zh-cn] sync setup-ha-etcd-with-kubeadm change-runtime-containerd configure-aggregation-layer

- content/zh-cn/docs/concepts/containers/container-environment.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
Fixes https://github.com/kubernetes/website/issues/41005
cc: @seokho-son 
Related to https://github.com/kubernetes/website/issues/41005
> [zh-cn] Replace deprecated fullversion shortcode

- content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md
> [zh] Improve translation of kubelet reference

- content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md
- content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1.md
- content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1alpha1.md
sync kubelet-credentialprovider.v1alpha1 kubelet-credentialprovider kube-scheduler-config.v1
> [zh-cn] sync kubelet-credentialprovider.v1alpha1 kubelet-credentialprovider kube-scheduler-config.v1

- content/en/docs/concepts/storage/storage-classes.md
This PR adds a link to the "reclaiming" section in the persistent volumes page.
Fixes: #41089
> Add link to reclaiming policy

- content/en/docs/tasks/administer-cluster/controller-manager-leader-migration.md
This PR changes nothing besides the line wrappings.
> Tweak line wrapping for leader migration task page

- data/i18n/nl/nl.toml
> Fixed typo in nl.toml

- content/pt-br/docs/tasks/tools/install-kubectl-linux.md
en PR https://github.com/kubernetes/website/pull/40183/files
> [pt] Update install-kubectl-linux.md

- content/en/blog/_posts/2023-06-09-dl-adopt-cdn.md
Fix author @haubles affiliation in the upcoming article.
> Fix author affiliation for CDN change article

- content/zh-cn/docs/concepts/storage/storage-classes.md
- content/zh-cn/docs/concepts/storage/volume-health-monitoring.md
This PR resync page `volume-health-monitoring` and `starage-classes`.
> [zh] resync volume-health-monitoring & storage-classes

- content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md
- content/zh-cn/docs/reference/glossary/object.md
- content/zh-cn/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
sync kubelet object environment-variable-expose-pod-information
> [zh-cn] sync kubelet object environment-variable-expose-pod-information

- content/ko/docs/tasks/administer-cluster/kubelet-config-file.md
> [ko]Translate docs/tasks/administer-cluster/kubelet-config-file into Korean

- content/pt-br/docs/tutorials/_index.md
- content/pt-br/docs/tutorials/kubernetes-basics/_index.html
* Update `tutorials/_index.html` to reflect latest English version.
* Update `tutorials/kubernetes-basics/_index.html` to address Katacoda shutdown and fix wording.
> [pt-br] Update the tutorials index pages

- content/en/docs/reference/labels-annotations-taints/_index.md
The page is currently a mixture of labels, annotations and taints. The line wrappings are terrible. This PR attempts to refactor the page against the style guide.
> Refactor the label-annotation-taints page

- content/zh-cn/docs/tasks/manage-kubernetes-objects/kustomization.md
en PR https://github.com/kubernetes/website/pull/40761/files
> [zh] Update kustomize examples to use non-deprecated resources key

- content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md
- content/zh-cn/docs/reference/config-api/kube-proxy-config.v1alpha1.md
content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md
> [zh-cn] sync imagepolicy.v1alpha1 kube-proxy-config.v1alpha1

- content/zh-cn/docs/concepts/services-networking/service.md
- content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
- content/zh-cn/docs/tasks/administer-cluster/controller-manager-leader-migration.md
content/zh-cn/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> [zh-cn] sync service user-namespaces controller-manager-leader-migration

- content/zh-cn/blog/_posts/2023-06-09-dl-adopt-cdn.md
Fix https://github.com/kubernetes/website/issues/41543
> sync blog: 2023-06-09-dl-adopt-cdn.md

- content/zh-cn/docs/concepts/windows/intro.md
- content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1beta1.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md
sync intro implementation-details kubelet-credentialprovider.v1beta1
> [zh-cn] sync intro implementation-details kubelet-credentialprovider.v1beta1

- content/pt-br/docs/tutorials/kubernetes-basics/explore/explore-intro.html
* Update the explore-intro tutorial in Brazilian Portuguese to remove the Katacoda references.
> [pt-br] Update tutorials/kubernetes-basics/explore/explore-intro.html

- content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/ko/docs/reference/command-line-tools-reference/feature-gates-removed.md
fix build error
when build website,it shows :
10:42:06 PM: Error: Error building site: "/opt/build/repo/content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md:175:1": failed to extract shortcode: shortcode "caution" must be closed or self-closed
> [ko][en] fix build error

- content/zh-cn/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
- content/zh-cn/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
- content/zh-cn/docs/tasks/administer-cluster/ip-masq-agent.md
Sync 3 files:
```
content/zh-cn/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
content/zh-cn/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
content/zh-cn/docs/tasks/administer-cluster/ip-masq-agent.md
```
> [zh] sync developing-cloud-controller-manager, ip-masq-agent, and guaranteed-scheduling-pods

- content/en/docs/tasks/administer-cluster/ip-masq-agent.md
- remove unecessary bold, `**`, from a heading 3
- add `:` to terms description
> improve ip-masq-agent.md slightly

- content/ru/docs/concepts/containers/container-environment.md
- content/ru/docs/setup/learning-environment/minikube.md
- content/ru/docs/tasks/tools/install-kubectl.md
Fixes https://github.com/kubernetes/website/issues/41487 on the `main` branch.
> [ru] *main* Replace deprecated fullversion shortcode

- content/pt-br/docs/tutorials/kubernetes-basics/create-cluster/_index.md
- content/pt-br/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
* Update the cluster-intro tutorial to reflect the latest English version and remove Katacoda references.
* Update the create-cluster/_index.md page to reflect the latest English version.
> [pt-br] Update tutorials/kubernetes-basics/create-cluster

- content/zh-cn/docs/tasks/administer-cluster/ip-masq-agent.md
- content/zh-cn/docs/tasks/debug/debug-cluster/audit.md
- content/zh-cn/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md
> [zh-cn] sync and improve resource-usage-monitoring ip-masq-agent audit

- content/zh-cn/docs/tasks/configure-pod-container/configure-gmsa.md
- 同步了注释掉的英文
- 调整了一些中文的折行问题
```
content/zh-cn/docs/tasks/configure-pod-container/configure-gmsa.md
```
See [preview](https://deploy-preview-41632--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-gmsa) please.
> [zh] sync configure-gmsa.md

- content/pt-br/docs/concepts/storage/volumes.md
Fixes #41502 
This PR aims to update the Portuguese version of the volumes page, by marking the deprecated volume types.
> [pt-br] Update docs/concepts/storage/volumes.md

- content/pt-br/docs/tutorials/hello-minikube.md
Minor fixes in hello-minikube.md for readability and standardization.
> [pt-br] Update docs/tutorials/hello-minikube.md

- content/zh-cn/docs/concepts/workloads/pods/init-containers.md
> [zh-cn] sync init-containers

- content/zh-cn/docs/reference/access-authn-authz/rbac.md
- **EN upstream**: `/content/en/docs/reference/access-authn-authz/rbac.md`
- **Sync to**: `/content/zh-cn/docs/reference/access-authn-authz/rbac.md`
- **Updates**:
- Sync'ed a `glossary_tooltip` from the EN upstream.
```diff
$ scripts/lsync.sh /content/zh-cn/docs/reference/access-authn-authz/rbac.md
diff --git a/content/en/docs/reference/access-authn-authz/rbac.md b/content/en/docs/reference/access-authn-authz/rbac.md
index 26440edfdb..ab6fd40ffb 100644
--- a/content/en/docs/reference/access-authn-authz/rbac.md
+++ b/content/en/docs/reference/access-authn-authz/rbac.md
@@ -29,9 +29,9 @@ kube-apiserver --authorization-mode=Example,RBAC --other-options --more-options
The RBAC API declares four kinds of Kubernetes object: _Role_, …
```
> [zh] sync reference/access-authn-authz/rbac.md

- content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
Signed-off-by: Gao Qian <gaoq.jy@fujitsu.com>
> [zh-cn] enforce-standards-admission-controller.md

- content/fr/docs/concepts/services-networking/service.md
en PR https://github.com/kubernetes/website/pull/41091/files
/assign @remyleone
> [fr] Updated Internal Load Balancer annotation for GCP

- content/en/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
> Tweak line wrappings in configure-aggregation-layer.md

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
- content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
- content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
> [zh-cn] sync setup-ha-etcd-with-kubeadm configure-upgrade-etcd configure-aggregation-layer

- content/zh-cn/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
- content/zh-cn/docs/reference/access-authn-authz/rbac.md
- content/zh-cn/docs/tasks/debug/_index.md
> [zh-cn] sync rbac apiserver-aggregation debug/_index.md

- content/zh-cn/docs/concepts/scheduling-eviction/resource-bin-packing.md
> [zh-cn] sync resource-bin-packing

- content/pt-br/releases/_index.md
Add the translated version of the releases page to the Brazilian Portuguese localization.
> [pt-br] Add releases/_index.md

- OWNERS_ALIASES
I want to applied to join sig-docs-zh-owners
Application related links: https://github.com/kubernetes/org/pull/4303
Thanks!
/cc @windsonsea @tengqm
> Add my-git9 to sig-docs-zh-owners

- content/zh-cn/includes/task-tutorial-prereqs.md
> [zh-cn] sync task-tutorial-prereqs

- content/ja/docs/concepts/services-networking/service-topology.md
- content/ja/docs/concepts/services-networking/topology-aware-routing.md
This PR updates ja's documents for Topology Aware Routing.
Fixes: #41361
Related: #40069
> [ja] Updating documentation for Topology Aware Routing

- content/ja/docs/concepts/services-networking/service.md
en PR https://github.com/kubernetes/website/pull/41091/files
> [ja] Updated Internal Load Balancer annotation for GCP

- content/pt-br/docs/tutorials/kubernetes-basics/expose/expose-intro.html
Update the tutorial on how to expose a service outside the cluster to remove Katacoda references.
> [pt-br] Update tutorials/kubernetes-basics/expose/expose-intro.html

- content/zh-cn/blog/_posts/2023-05-24-oci-security-profiles.md
en PR https://github.com/kubernetes/website/pull/41533/files
> [zh] Remove Bundle Bar registry link

- content/zh-cn/blog/_posts/2023-02-03-sig-instrumentation-spotlight.md
Fix [#39770](https://github.com/kubernetes/website/issues/39770)
> [zh-cn] sync blog: 2023-02-03-sig-instrumentation-spotlight.md

- content/zh-cn/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
- content/zh-cn/examples/application/wordpress/mysql-deployment.yaml
- content/zh-cn/examples/application/wordpress/wordpress-deployment.yaml
sync wordpress-deployment mysql-deployment mysql-wordpress-persistent-volume
> [zh-cn] sync wordpress-deployment mysql-deployment mysql-wordpress-persistent-volume

- content/zh-cn/docs/images/kubeadm-ha-topology-external-etcd.svg
- content/zh-cn/docs/images/kubeadm-ha-topology-stacked-etcd.svg
- content/zh-cn/docs/setup/production-environment/tools/kubeadm/ha-topology.md
- sync two images
- minor changes
in https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/ha-topology/
See [preview](https://deploy-preview-41683--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/ha-topology/) please.
> [zh] sync /kubeadm/ha-topology.md

- OWNERS_ALIASES
I want to applied to join sig-docs-zh-reviews.
Application related links: https://github.com/kubernetes/org/pull/4304
Thank you!
/cc @tengqm @windsonsea
> Add asa3311 to sig-docs-zh-reviews

- content/es/docs/concepts/services-networking/service.md
en PR https://github.com/kubernetes/website/pull/41091/files
/assign @electrocucaracha
> [es] Updated Internal Load Balancer annotation for GCP

- content/es/docs/concepts/storage/storage-classes.md
Se añadió la documentación en español para 
content/es/docs/concepts/storage/storage-classes.md
Agradecería puedan revisarlo y darme feedback.
Gracias! :)
> [es] Add content/es/docs/concepts/storage/storage-classes.md

- content/zh-cn/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
modify Chinese document: "Contaier" to "Container"
> modify Chinese document: "Contaier" to "Container"

- content/zh-cn/docs/concepts/services-networking/service.md
- content/zh-cn/docs/tasks/debug/debug-cluster/local-debugging.md
> [zh-cn]sync service local-debugging

- content/zh-cn/docs/tasks/debug/debug-application/debug-pods.md
```
content/zh-cn/docs/tasks/debug/debug-application/debug-pods.md
```
See [preview](https://deploy-preview-41705--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-application/debug-pods/) please.
> [zh] sync /debug-application/debug-pods.md

- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use.md
Delete the duplicate cri-dockerd description at the end of the article。
> [zh-cn] find-out-runtime-you-use

- content/zh-cn/docs/reference/access-authn-authz/abac.md
Sycn with en text:
```
content/zh-cn/docs/reference/access-authn-authz/abac.md
```
> [zh] sync /access-authn-authz/abac.md

- content/pt-br/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
* Update the deploy intro tutorial to both reflect the latest English version and remove references to Katacoda.
> [pt-br] Update deploy-intro tutorial

- content/zh-cn/blog/_posts/2023-05-12-in-place-pod-resize/index.md
I started a PR to translate https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/ into Chinese.
> Add zh translation for blog VPA v1.27

- content/vi/docs/tasks/tools/install-kubectl.md
Fixes https://github.com/kubernetes/website/issues/41488
> [vi] Replace deprecated fullversion shortcode

- content/hi/docs/tasks/tools/install-kubectl-linux.md
en PR https://github.com/kubernetes/website/pull/40183/files
/assign @divya-mohan0209
> [hi] Update install-kubectl-linux.md

- content/ja/docs/concepts/scheduling-eviction/resource-bin-packing.md
en PR https://github.com/kubernetes/website/pull/41639/files
> [ja] Fix node score calculation

- content/ja/docs/reference/using-api/_index.md
Fixes https://github.com/kubernetes/website/issues/41674
> [ja] update outdated links in content/ja/docs/reference/using-api/_index.md

- content/id/docs/concepts/scheduling-eviction/resource-bin-packing.md
en PR https://github.com/kubernetes/website/pull/41639/files
> [id] Fix node score calculation

- content/zh-cn/blog/_posts/2022-12-05-forensic-container-checkpointing/index.md
- content/zh-cn/blog/_posts/2023-03-10-forensic-container-analysis/index.md
1. `content/zh-cn/blog/_posts/2022-12-05-forensic-container-checkpointing/index.md` is copied from https://mp.weixin.qq.com/s/qA0AtdsYGgMk2IJ5dVxUlQ.
2. `content/zh-cn/blog/_posts/2023-03-10-forensic-container-analysis/index.md` is translated by me.
> add Chinese translate for Forensic container checkpointing

- content/de/includes/task-tutorial-prereqs.md
> [de] update labs link

- content/id/docs/tasks/manage-kubernetes-objects/kustomization.md
en PR https://github.com/kubernetes/website/pull/40761/files
> [id] Update kustomize examples to use non-deprecated resources key

- content/ko/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
> [ko] Translate configure-cgroup-driver.md into Korean

- content/ko/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
- content/ko/examples/pods/lifecycle-events.yaml
from #41561 
continue #41563 
@jihoon-seo
> [ko] Translate attach-handler-lifecycle-event.md into Korean

- content/ja/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md
fixes https://github.com/kubernetes/website/issues/41716
> [ja] Update of the Japanese page of the resource metrics pipeline.

- content/ja/docs/concepts/workloads/controllers/deployment.md
ren PR https://github.com/kubernetes/website/pull/40752/files
> [ja] fix incorrect pod-template-hash labels

- content/ru/includes/task-tutorial-prereqs.md
> [ru] update labs link

- content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
sync certificate-signing-requests
> [zh-cn] sync certificate-signing-requests

- content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/zh-cn/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
- content/zh-cn/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
- content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
Umbrella issue: #41496
Sync with the latest en version.
> [zh] remove katacoda tutorials

- content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
- Add commented text
- Minor changes on zh text
```
content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
```
> [zh] sync tutorial: /create-cluster/cluster-intro.html

- content/en/docs/concepts/overview/working-with-objects/namespaces.md
> fix: unclear documentation on NamespaceDefaultLabelName feature gate

- content/ja/docs/concepts/workloads/controllers/deployment.md
en PR https://github.com/kubernetes/website/pull/23270
> [ja] Remove the unessary code typ

- content/ja/docs/concepts/storage/persistent-volumes.md
This PR fixes a broken link in the Japanese persistent-volumes document.
> [ja] Fix broken links in persistent-volumes

- content/es/docs/concepts/workloads/controllers/deployment.md
en PR https://github.com/kubernetes/website/pull/23270/files
> [es] Remove the unessary code typ

- content/ja/docs/concepts/workloads/controllers/job.md
- content/ja/examples/controllers/job-pod-failure-policy-example.yaml
こちらのIssueを対応しました。https://github.com/kubernetes/website/issues/41364
差分多いですがレビューおねがいします 🙇
> [ja] Sync the Japanese Job page with the latest version

- content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
> Fixed typo for taint-and-toleration.md

- content/zh-cn/docs/concepts/containers/images.md
- content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
sync taint-and-toleration images
> [zh-cn] sync taint-and-toleration images

- content/zh-cn/docs/tutorials/kubernetes-basics/explore/explore-intro.html
```
content/zh-cn/docs/tutorials/kubernetes-basics/explore/explore-intro.html
```
See [preview](https://deploy-preview-41794--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/kubernetes-basics/explore/explore-intro/) please.
> [zh] sync tutorial: /explore/explore-intro.html

- content/en/docs/tutorials/hello-minikube.md
Resolves #41837  [[Preview](https://deploy-preview-41842--kubernetes-io-main-staging.netlify.app/docs/tutorials/hello-minikube/)]
> Link from Minikube tutorial to "Deploy an App" tutorial page 

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
> fix broken link[avoiding-collisions]

- content/fr/includes/task-tutorial-prereqs.md
> [fr] Fix link to labs.play-with-k8s.com

- content/zh-cn/docs/test.md
- Applied the style mentioned in this topic to this page
- Add anchors to heading 2 and 3
- Remove unnecessary spaces caused by incorrect newline char
See [preview](https://deploy-preview-41862--kubernetes-io-main-staging.netlify.app/zh-cn/docs/test/) please.
> [zh] sync /docs/test.md

- content/en/docs/test.md
Have a try to improve the consistency and some text.
> polish text and indentations in test.md

- content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
- content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md
sync service-accounts-admin horizontal-pod-autoscale
> [zh-cn] sync service-accounts-admin horizontal-pod-autoscale

- content/en/docs/concepts/workloads/pods/_index.md
fix typo words in pod describe.
> Fix typo words in pod describe

- content/es/includes/task-tutorial-prereqs.md
> [es] Fix labs.play-with-k8s.com

- content/en/docs/tasks/administer-cluster/encrypt-data.md
Revise [Encrypting Secret Data at Rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) [[preview](https://deploy-preview-41574--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/encrypt-data/)]
Split off from PR #33285
Tweak the manifests and other documents for more comments, easier reading, etc.
> Update example YAML in encryption-at-rest topic

- content/zh-cn/docs/concepts/workloads/pods/_index.md
- content/zh-cn/docs/concepts/workloads/pods/init-containers.md
sync /pods/_index  init-container
> [zh-cn] sync /pods/_index  init-container 

- content/zh-cn/docs/reference/labels-annotations-taints/_index.md
sync docs/reference/labels-annotations-taints/_index.md
> [zh] sync docs/reference/labels-annotations-taints/_index.md

- content/pt-br/docs/reference/access-authn-authz/abac.md
Translate the ABAC page to PT-BR.
> [pt-br] Add docs/reference/access-authn-authz/abac.md

- content/pt-br/includes/task-tutorial-prereqs.md
> [pt] Fix labs.play-with-k8s.com

- content/en/docs/setup/production-environment/tools/kops.md
- content/en/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md
- content/en/docs/setup/production-environment/tools/kubespray.md
Tweaked long lines in 3 files, without any changes:
```
content/en/docs/setup/production-environment/tools/kops.md
content/en/docs/setup/production-environment/tools/kubespray.md
content/en/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md
```
> Tweak line wrappings in kops, kubespray, and dual-stack-support

- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
> Fix bullets in validating-admission-policy

- content/pt-br/docs/concepts/services-networking/ingress.md
Correção de concordância verbal
> [pt-br] Update docs/concepts/services-networking/ingress.md

- content/en/docs/tutorials/security/_index.md
Added the lines as suggested in the issue https://github.com/kubernetes/website/issues/39249
> Improvement for the security docs

- content/zh-cn/docs/concepts/storage/ephemeral-volumes.md
- content/zh-cn/docs/concepts/storage/storage-classes.md
- content/zh-cn/docs/tutorials/services/connect-applications-service.md
sync ephemeral-volumes.md,storage-classes.md,connect-applications-service.md.
> [zh-cn] sync ephemeral-volumes storage-classes connect-applications-service

- content/id/docs/concepts/workloads/pods/init-containers.md
en PR https://github.com/kubernetes/website/pull/41157/files
> [id] Fix a shell command

- content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
Added a step to uncordon the node since it was drained at the beginning of this process.
> Add uncordon step to containerd migration doc

- content/pt-br/docs/concepts/cluster-administration/cluster-administration-overview.md
- content/pt-br/docs/concepts/cluster-administration/kubelet-garbage-collection.md
- content/pt-br/docs/concepts/cluster-administration/logging.md
- content/pt-br/docs/concepts/containers/images.md
- content/pt-br/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
- content/pt-br/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
- content/pt-br/docs/tasks/configure-pod-container/share-process-namespace.md
- content/pt-br/docs/tasks/configure-pod-container/static-pod.md
* Remove empty reviewers sections and reviewers sections that contain reviewers who are not reviewers for the Portuguese localization.
/cc @jcjesus @edsoncelio @devlware
/kind cleanup
> [pt-br] Cleanup Portuguese localization reviewers sections

- content/es/docs/concepts/workloads/pods/init-containers.md
en PR https://github.com/kubernetes/website/pull/41157/files
> [es] Fix a shell command

- content/zh-cn/docs/reference/using-api/api-concepts.md
api server没有中文目录下的list。
目前访问"https://kubernetes.io/zh-cn/docs/reference/generated/kubernetes-api/v1.27/#listmeta-v1-meta "会报404，所以改到"https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#listmeta-v1-meta" 这个地址。
> [zh-cn] Update content/zh-cn/docs/reference/using-api/api-concepts.md

- content/hi/includes/task-tutorial-prereqs.md
> [hi] Fix labs.play-with-k8s.com

- content/pt-br/docs/home/supported-doc-versions.md
Update docs/home/supported-doc-versions.md
/cc @devlware @stormqueen1990
> [pt-br] Update docs/home/supported-doc-versions.md

- content/zh-cn/docs/concepts/workloads/pods/_index.md
/kind cleanup
As [en-docs](https://github.com/kubernetes/website/pull/41845/files) merged.
So raise this for zh-cn.
> [zh-cn] Sync concepts/workloads/pods/_index.md

- content/fr/docs/concepts/workloads/pods/init-containers.md
en PR https://github.com/kubernetes/website/pull/41157/files
/assign @remyleone
> [fr] Fix a shell command

- content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md
Fix to the article, as suggested here https://github.com/kubernetes/website/pull/41973#discussion_r1262935245
> Add canonicalUrl to SIG CLI Spotlight

- content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md
Sync with en #40811 
```
content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md
```
See [preview](https://deploy-preview-42033--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/command-line-tools-reference/kubelet/) please.
> [zh] sync /command-line-tools-reference/kubelet.md

- content/pl/docs/contribute/_index.md
Related to https://kubernetes.slack.com/archives/C0191RDKHU1/p1680549820387879
> [pl] Mention kubernetes/websites everywhere in the same way

- content/en/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
Just a couple of nitpicks. Sorry. 😀
> grammar fixes for guaranteed-scheduling-critical-addon-pods.md

- content/en/docs/tasks/inject-data-application/define-environment-variable-container.md
> Improvement for 'Using environment variables inside of your config'

- content/en/docs/concepts/configuration/secret.md
Made secrets page description more self-explanatory by moving types of secrets section above working with secrets which makes it simpiler to explain the commands present in working with secrets section 
This PR solves the issue #41083
> A more clear description for commands in working with secrets section

- content/id/docs/concepts/services-networking/connect-applications-service.md
en PR https://github.com/kubernetes/website/pull/41820/files
> [id] Add --rm for temporary pod command

- content/id/includes/task-tutorial-prereqs.md
> [id] Fix labs.play-with-k8s.com

- content/zh-cn/blog/_posts/2023-06-29-container-image-signature-verification/flow.svg
Sync an image with some text in this blog:
https://kubernetes.io/zh-cn/blog/2023/06/29/container-image-signature-verification/
> [zh] sync a svg in blog of container image signature verification

- content/zh-cn/docs/concepts/architecture/garbage-collection.md
- content/zh-cn/docs/concepts/overview/components.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/zh-cn/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
- content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Sync：
/docs/concepts/architecture/garbage-collection.md；
/docs/concepts/overview/components.md；
/docs/reference/command-line-tools-reference/feature-gates-removed.md；
/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md；
/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md；
> [zh] sync garbage-collection components feature-gates-removed guaranteed-scheduling-critical-addon-pods custom-resource-definitions

- content/zh-cn/docs/concepts/storage/persistent-volumes.md
- content/zh-cn/docs/concepts/workloads/controllers/cron-jobs.md
- content/zh-cn/docs/tasks/tools/_index.md
- content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
- content/zh-cn/docs/tasks/tools/install-kubectl-macos.md
sync：
content/zh-cn/docs/tasks/tools/_index.md
content/zh-cn/docs/tasks/tools/install-kubectl-macos.md
> [zh] sync persistent-volumes cron-jobs /tools/_index install-kubectl-linux install-kubectl-macos

- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
sync content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
> [zh-cn] sync change-runtime-containerd.md

- content/zh-cn/blog/_posts/2023-07-20-sig-cli-spotlight.md
sync blog 2023-07-20-sig-cli-spotlight.md
> [zh-cn] sync blog 2023-07-20-sig-cli-spotlight.md

- content/ja/includes/task-tutorial-prereqs.md
> [ja] Fix labs.play-with-k8s.com

- content/de/docs/tasks/tools/install-kubectl-linux.md
en PR https://github.com/kubernetes/website/pull/40437/files
> [de] Fix wrong code highlighting

- content/pt-br/docs/tasks/tools/install-kubectl-linux.md
en PR https://github.com/kubernetes/website/pull/40437/files
> [pt] Fix wrong code highlighting

- content/zh-cn/blog/_posts/2023-07-06-confidential-kubernetes.md
> [zh-cn] sync blog 2023-07-06-confidential-kubernetes

- content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
Fix the description of the access pattern restrictions of the newly created PVC in the example.
> Fix description of RWO

- content/en/docs/concepts/scheduling-eviction/_index.md
> Add link for descheduler

- README.md
> Fix line number for HUGO_VERSION link

- content/ja/docs/concepts/containers/container-environment.md
- content/ja/docs/concepts/services-networking/connect-applications-service.md
- content/ja/docs/concepts/services-networking/service.md
- content/ja/docs/setup/learning-environment/minikube.md
- content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
- content/ja/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/ja/docs/tasks/tools/install-kubectl.md
fixes https://github.com/kubernetes/website/issues/41486
Related to https://github.com/kubernetes/website/issues/41005
> [ja] Replace deprecated fullversion shortcode

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Update apt repo GPG key URL to redirect. Fixes #42144
> Update apt repo GPG key URL

- content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
Sync content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
> [zh-cn] sync user-namespace

- content/ko/docs/tasks/tools/install-kubectl-windows.md
[Korean Docs Localization]
Correcting a typo caused by a Git conflict
> [ko] Update install-kubectl-windows.md

- content/ko/docs/tasks/tools/install-kubectl-windows.md
Fix a bad merge. Helps with https://github.com/kubernetes/website/issues/41005 (but doesn't close it).
> [ko] Fix a bad merge into kubectl install task

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
The file `tools\kubeadm\install-kubeadm.md` has been updated in this PR (https://github.com/kubernetes/website/pull/42156) ,so we will synchronize the localization.
**EN upstream:** content\en\docs\setup\production-environment\tools\kubeadm\install-kubeadm.md
**Sync to:** content\zh-cn\docs\setup\production-environment\tools\kubeadm\install-kubeadm.md
> [zh] sync tools\kubeadm\install-kubeadm.md

- content/pt-br/docs/concepts/cluster-administration/flow-control.md
- content/pt-br/docs/concepts/cluster-administration/logging.md
- content/pt-br/docs/concepts/overview/working-with-objects/kubernetes-objects.md
- content/pt-br/docs/concepts/policy/resource-quotas.md
- content/pt-br/docs/concepts/scheduling-eviction/taint-and-toleration.md
- content/pt-br/docs/concepts/services-networking/ingress.md
- content/pt-br/docs/concepts/services-networking/network-policies.md
- content/pt-br/docs/concepts/workloads/controllers/cron-jobs.md
- content/pt-br/docs/concepts/workloads/controllers/replicaset.md
- content/pt-br/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.md
- content/pt-br/docs/tasks/access-application-cluster/connecting-frontend-backend.md
- content/pt-br/docs/tasks/configure-pod-container/assign-pods-nodes.md
- content/pt-br/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
- content/pt-br/docs/tasks/configure-pod-container/configure-pod-configmap.md
- content/pt-br/docs/tasks/configure-pod-container/configure-runasusername.md
- content/pt-br/docs/tasks/configure-pod-container/configure-volume-storage.md
- content/pt-br/docs/tasks/configure-pod-container/extended-resource.md
- content/pt-br/docs/tasks/configure-pod-container/quality-service-pod.md
- content/pt-br/docs/tasks/configure-pod-container/share-process-namespace.md
This is a continuation of PR https://github.com/kubernetes/website/pull/42180 (Replace {{< codenew ... >}} with {{% codenew ... %}})
Fixes https://github.com/kubernetes/website/issues/42179 (Copy To Clipboard breaks YAML format)
> [pt-br] replaced {{< codenew ... >}} with {{% codenew ... %}}

- content/en/docs/concepts/security/rbac-good-practices.md
- content/en/docs/concepts/security/service-accounts.md
- Indent the bullets using a multiple of 2 spaces
- Remove tailing spaces
/kind cleanup
> Provide a consistent appearance to bullets in service-accounts and rbac

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md
- content/zh-cn/docs/setup/production-environment/tools/kubespray.md
Sync with en #41942 
```
modified:   content/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md
modified:   content/zh-cn/docs/setup/production-environment/tools/kubespray.md
```
> [zh] sync dual-stack-support.md and kubespray.md

- content/en/docs/reference/instrumentation/metrics.md
Update documented metrics for v1.28 (after code freeze).
> Autogen documented metrics for v1.28

- content/en/docs/concepts/architecture/mixed-version-proxy.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
enhancement issue: https://github.com/kubernetes/enhancements/issues/4020
> Add MVP documentation

- content/zh-cn/docs/concepts/extend-kubernetes/operator.md
如果生态系统中没可以实现你目标的 Operator，你可以自己编写代码
修改为=>
如果生态系统中没有可以实现你目标的 Operator，你可以自己编写代码
> [zh-cn]Fixed：Modify an incoherent statement

- content/en/docs/concepts/services-networking/dual-stack.md
> Fix note about .spec.ipFamilies

- content/en/docs/tasks/administer-cluster/encrypt-data.md
Split out from PR #33285
- document that you can encrypt more than Secrets
- make it clear that this _isn't_ the page for you if you want to encrypt storage volumes
/sig security
/sig auth
> Revise API encryption at resk task intro

- content/zh-cn/docs/tasks/run-application/configure-pdb.md
- content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
- content/zh-cn/docs/tasks/run-application/run-replicated-stateful-application.md
- content/zh-cn/docs/tasks/run-application/run-single-instance-stateful-application.md
- content/zh-cn/docs/tasks/run-application/run-stateless-application-deployment.md
Changes to be committed:
```
```
> [zh-cn] sync run-application/*

- content/ko/docs/tasks/administer-cluster/configure-upgrade-etcd.md
> [ko] Translate configure-upgrade-etcd.md into Korean

- content/pt-br/docs/concepts/architecture/nodes.md
en PR https://github.com/kubernetes/website/pull/41927/files
> [pt] Fix wrong feature state

- content/en/docs/concepts/services-networking/topology-aware-routing.md
> Updated topology-aware-routing.md

- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
> [zh-cn] sync manage-resources/* adn encrypt-data

- content/zh-cn/blog/_posts/2019-04-24-Hardware-Accelerated-SSLTLS-Termination-in-Ingress-Controllers-using-Kubernetes-Device-Plugins-and-RuntimeClass.md
…rated-ssl/tls-termination-in-ingress-controllers-using-kubernetes-device-plugins-and-runtimeclass
> [zh] sync a blog: 2019/04/24 tls-termination-in-ingress-controllers

- content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
The file tools\kubeadm\install-kubeadm.md has been updated in this PR (https://github.com/kubernetes/website/pull/42172) ,so we will synchronize the localization.
**EN upstream**: content\en\docs\tasks\tools\install-kubectl-linux.md
**Sync to**: content\zh-cn\docs\tasks\tools\install-kubectl-linux.md
> [zh] sync tasks\tools\install-kubectl-linux.md

- content/zh-cn/docs/concepts/architecture/leases.md
The file `concepts\architecture\leases.md` has been updated in this PR (https://github.com/kubernetes/website/pull/42086) ,so we will synchronize the localization.
**EN upstream**: content\en\docs\concepts\architecture\leases.md
**Sync to**: content\zh-cn\docs\concepts\architecture\leases.md
> [zh] sync concepts\architecture\leases

- content/zh-cn/docs/tasks/administer-cluster/ip-masq-agent.md
The file `tasks\administer-cluster\ip-masq-agent.md` has been updated in this PR (https://github.com/kubernetes/website/pull/42297) ,so we will synchronize the localization.
**EN upstream**: content\en\docs\tasks\administer-cluster\ip-masq-agent.md
**Sync to**: content\zh-cn\docs\tasks\administer-cluster\ip-masq-agent.md
> [zh] sync tasks\administer-cluster\ip-masq-agent.md

- content/en/docs/concepts/workloads/controllers/deployment.md
> Update [Creating a Deployment] section

- content/en/docs/reference/config-api/kubelet-config.v1beta1.md
Add spaces to fix format error
> Add spaces to fix format error

- content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
```
content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
```
See [preview](https://deploy-preview-41791--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/) please.
> [zh] sync tutorial: deploy-app/deploy-intro.html

- content/zh-cn/docs/contribute/localization.md
```
```
See [preview](https://deploy-preview-42040--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/localization/) please.
> [zh] sync /contribute/localization.md

- content/zh-cn/docs/concepts/workloads/controllers/_index.md
```
content/zh-cn/docs/concepts/workloads/controllers/_index.md
```
See [preview](https://deploy-preview-42004--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/) please.
> [zh] sync /workloads/controllers/_index.md

- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
- content/zh-cn/docs/reference/using-api/deprecation-guide.md
Sync 2 files:
```
content/zh-cn/docs/reference/using-api/deprecation-guide.md
```
See [preview](https://deploy-preview-42239--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/using-api/deprecation-guide/) please.
> [zh] sync deprecation-guide.md and validating-admission-policy.md

- content/en/_index.html
- layouts/shortcodes/site-searchbar.html
Closes https://github.com/kubernetes/website/issues/21867
Deploy Preview: [deploy-preview-42299--kubernetes-io](https://deploy-preview-42299--kubernetes-io-main-staging.netlify.app/)
> Add site search to home page

- content/en/docs/tasks/tools/install-kubectl-linux.md
Add missing command for debian instructions
> Add command for creating missing keyring dir

- content/en/docs/concepts/security/overview.md
Fixes #42285 
Replaced with correct English link
> attached  correct link to the documentation

- content/en/docs/reference/kubectl/jsonpath.md
Fixes: https://github.com/kubernetes/website/issues/42251
> Fix inconsistent command in the JSONPath Support page

- content/en/docs/tasks/administer-cluster/namespaces.md
add kube-node-lease namespace to keep pace with https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/overview/working-with-objects/namespaces.md
> Mention kube-node-lease namespace in Namespaces concept

- content/zh-cn/docs/reference/node/node-labels.md
- content/zh-cn/docs/tasks/administer-cluster/namespaces.md
- content/zh-cn/docs/tasks/configure-pod-container/assign-cpu-resource.md
- content/zh-cn/docs/tasks/configure-pod-container/security-context.md
> [zh-cn] sync node-labels namepaces security-context assign-cpu-resource

- content/en/docs/concepts/cluster-administration/addons.md
This fixes #37748
Reference: https://www.weave.works/blog/weave-cloud-end-of-service
> Remove Weave Cloud

- content/zh-cn/docs/reference/config-api/kubelet-config.v1.md
Polish a config-api page:
```
content/zh-cn/docs/reference/config-api/kubelet-config.v1.md
```
See [preview](https://deploy-preview-42367--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/kubelet-config.v1/) here.
> [zh] polish /config-api/kubelet-config.v1.md

- content/en/blog/_posts/2023-08-15-non-graceful-node-shutdown-to-ga.md
Placeholder blog PR for https://github.com/kubernetes/enhancements/issues/2268
> Add blog for non-graceful node shutdown

- content/en/docs/concepts/storage/persistent-volumes.md
KEP: https://github.com/kubernetes/enhancements/pull/3796
Code: https://github.com/kubernetes/kubernetes/pull/116469
> Add docs for PersistentVolume last phase transition time

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
en PR https://github.com/kubernetes/website/pull/42128/files
> [zh] Remove obsolete references

- content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html
The app is listening on port 8080 so that must be included otherwise port 80 (default) is used and the curl request will fail.
Issue: 41259
> Fixed "Show the app in the terminal" URL (en)

- content/ja/docs/concepts/services-networking/connect-applications-service.md
en PR https://github.com/kubernetes/website/pull/41820/files
> [ja] Add --rm for temporary pod command

- content/ja/docs/concepts/workloads/pods/init-containers.md
en PR https://github.com/kubernetes/website/pull/41157/files
> [ja] Fix a shell command

- data/i18n/ja/ja.toml
issue: https://github.com/kubernetes/website/issues/42107
> [ja] Translate Japanese i18n 'outdated_content_message'

- content/zh-cn/docs/concepts/cluster-administration/addons.md
The file `concepts\cluster-administration\addons.md` has been updated in this PR (https://github.com/kubernetes/website/pull/42352) ,so we will synchronize the localization.
**EN upstream**: content\en\docs\concepts\cluster-administration\addons.md
**Sync to**: content\zh-cn\docs\concepts\cluster-administration\addons.md
> [zh] sync concepts\cluster-administration\addons.md

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
PodReplacementPolicy updates as part of https://github.com/kubernetes/enhancements/issues/3939
> Add information about PodReplacementPolicy in Job API

- content/en/docs/concepts/storage/persistent-volumes.md
Updated docs for https://github.com/kubernetes/enhancements/issues/1790
> Remove references to older alpha field

- content/en/docs/concepts/workloads/pods/downward-api.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
ref: https://github.com/kubernetes/enhancements/issues/2681
> KEP-2681: Docs update for Alpha PodHostIPs

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
Enhancement link: https://github.com/kubernetes/enhancements/issues/3545
Implementation link:  https://github.com/kubernetes/kubernetes/pull/118816
> topologymanager: Update feature-gates availibilty for TopologyManagerPolicyOptions beta graduation

- data/i18n/hi/hi.toml
> Modified hi.toml to adopt new localization string for release page

- content/zh-cn/blog/_posts/2023-05-15-kubernetes-1-27-updates-on-speeding-up-pod-startup.md
sync blog/_posts/2023-05-15-kubernetes-1-27-updates-on-speeding-up-pod-startup.md
> [zh-cn] sync blog/_posts/2023-05-15-kubernetes-1-27-updates-on-speeding-up-pod-startup.md

- content/zh-cn/docs/concepts/configuration/configmap.md
sync concepts/configuration/configmap.md
> [zh-cn] sync concepts/configuration/configmap.md

- content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
sync concepts/overview/working-with-objects/_index.md
> [zh-cn] sync concepts/overview/working-with-objects/_index.md

- content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
sync contribute/style/hugo-shortcodes/index.md
> [zh-cn] sync contribute/style/hugo-shortcodes/index.md

- content/zh-cn/docs/tutorials/stateless-application/guestbook.md
sync tutorials/stateless-application/guestbook.md
> [zh-cn] sync tutorials/stateless-application/guestbook.md

- content/zh-cn/docs/concepts/policy/limit-range.md
sync concepts/policy/limit-range.md
> [zh-cn] sync concepts/policy/limit-range.md

- content/zh-cn/docs/concepts/services-networking/dns-pod-service.md
sync concepts/services-networking/dns-pod-service.md
> [zh-cn] sync concepts/services-networking/dns-pod-service.md

- content/en/docs/reference/kubectl/kubectl.md
This PR adds document for the alpha stage of https://github.com/kubernetes/enhancements/issues/3895
> document kubectl delete --interactive flag

- content/zh-cn/blog/_posts/2023-08-15-non-graceful-node-shutdown-to-ga.md
Sync 2023-08-15-non-graceful-node-shutdown-to-ga.md
> [zh-cn] sync 2023-08-15-non-graceful-node-shutdown-to-ga.md

- assets/scss/_custom.scss
Addressing issue #42342, Improved the current styling of the metrics table.
> Improved the current styling of the metrics table

- content/zh-cn/docs/concepts/services-networking/dual-stack.md
sync content/zh-cn/docs/concepts/services-networking/dual-stack.md
> [zh-cn] sync content/zh-cn/docs/concepts/services-networking/dual-stack.md

- content/zh-cn/docs/concepts/services-networking/ingress.md
sync content/zh-cn/docs/concepts/services-networking/ingress.md
> [zh-cn] sync content/zh-cn/docs/concepts/services-networking/ingress.md

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
This is a follow-up to https://github.com/kubernetes/website/pull/41856 with the suggested enhancements.
/cc @sftim
> dra: cleanup of Kubernetes 1.28 update

- content/en/docs/reference/config-api/kubeadm-config.v1beta3.md
This is a fix version of closed pr #42421. 
now I only fix the EN version first, and firstly did a fix on upstream, so now this is an auto generate version
> Fix a small error of example config

- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
- content/en/examples/access/image-matches-namespace-environment.policy.yaml
xref:
https://github.com/kubernetes/enhancements/issues/3488
> Document ValidatingAdmissionPolicy variable composition and namespaceObject

- content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
> [zh-cn]sync pr #42449

- content/zh-cn/docs/tutorials/services/connect-applications-service.md
- content/zh-cn/docs/tutorials/services/pods-and-endpoint-termination-flow.md
- content/zh-cn/docs/tutorials/services/source-ip.md
- content/zh-cn/examples/service/explore-graceful-termination-nginx.yaml
Sync 3 files in this folder:
```
content/zh-cn/docs/tutorials/services/connect-applications-service.md
content/zh-cn/docs/tutorials/services/pods-and-endpoint-termination-flow.md
content/zh-cn/docs/tutorials/services/source-ip.md
```
See [preview](https://deploy-preview-42464--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/services/pods-and-endpoint-termination-flow/) please.
> [zh] sync pods-and-endpoint-termination-flow.md and 2 service tutorials

- content/id/docs/concepts/security/overview.md
en PR https://github.com/kubernetes/website/pull/42353/files
> [id] Fix link to Huawei cloud provider security

- content/id/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
en PR https://github.com/kubernetes/website/pull/42128/files
> [id] Remove obsolete references

- content/en/docs/concepts/workloads/pods/_index.md
- content/en/docs/concepts/workloads/pods/init-containers.md
> nit edits for Sidecar containers

- content/zh-cn/docs/tasks/tools/install-kubectl-windows.md
- Remove a duplicated and commented text
- Fix 3 alignment issues like:
> [zh] Fix issues in install-kubectl-windows.md

- content/pt-br/docs/concepts/security/overview.md
en PR https://github.com/kubernetes/website/pull/42353/files
> [pt] attached correct link

- content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/examples/access/validating-webhook-configuration-match-conditions.yaml
This PR updates the kubernetes documentation to state that `AdmissionWebhookMatchConditions` is currently in Beta stage.
Graduation PR: https://github.com/kubernetes/kubernetes/pull/119380
> Graduate AdmissionWebhookMatchConditions to beta

- content/en/docs/reference/command-line-tools-reference/feature-gates.md
- content/en/docs/tasks/administer-cluster/encrypt-data.md
- content/en/docs/tasks/administer-cluster/kms-provider.md
ref: https://github.com/kubernetes/enhancements/issues/3299
/milestone v1.28
/sig auth
> KMS doc updates for v1.28

- content/en/docs/contribute/style/style-guide.md
> added .editorconfig

- content/en/docs/concepts/workloads/controllers/job.md
@atiratree pointed out a few typos on a #41745.
This PR fixes these.
> fix a typo for podReplacementPolicy

- hugo.toml
Updating the supported releases for version 1.28.
> Update config 1.28 for 1.28 release

- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/tutorials/kubernetes-basics/_index.html
> Removed the Katacoda shutdown notice

- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
> Update documentation to reflect kubelet.conf.d changes for k8s 1.28

- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
sync cpu-constraint-namespace memory-default-namespace quota-memory-cpu-namespace quota-pod-namespace
> [zh-cn] sync cpu-constraint-namespace memory-default-namespace quota-memory-cpu-namespace quota-pod-namespace

- content/zh-cn/docs/tasks/administer-cluster/declare-network-policy.md
- content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
- content/zh-cn/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
- content/zh-cn/docs/tasks/administer-cluster/namespaces-walkthrough.md
- content/zh-cn/docs/tasks/administer-cluster/quota-api-object.md
- content/zh-cn/docs/tasks/administer-cluster/running-cloud-controller.md
> [zh-cn] sync administer-cluster/*

- content/zh-cn/docs/tutorials/kubernetes-basics/explore/explore-intro.html
en PR https://github.com/kubernetes/website/pull/41929/files
> [zh] Fixed "Show the app in the terminal" URL

- content/en/docs/concepts/architecture/mixed-version-proxy.md
- content/en/docs/reference/glossary/mixed-version-proxy.md
This PR adds a hyperlink to `feature gates` in the glossary entry for MVP
> update glossary entry for MVP 

- content/zh-cn/docs/concepts/workloads/pods/pod-qos.md
en PR https://github.com/kubernetes/website/pull/42517/files
> [zh] Update pod-qos.md to fix typo

- content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> [zh-cn] sync deploy-app/deploy-intro.html

- data/releases/schedule.yaml
This PR adds 1.28 to the releases schedule for the 1.28.0 release
> Add 1.28 to release schedule for 1.28 release

- config.toml
Updating the supported releases for version 1.28.
/hold
> Update config.toml 1.25 for 1.28 release

- hugo.toml
Updating the supported releases for version 1.28.
/hold
> Update config.toml 1.26 for 1.28 release

- config.toml
Updating the supported releases for version 1.28.
/hold
> Update config.toml 1.24 for 1.28 release

- content/en/blog/_posts/2023-08-15-kubernetes-1.28-blog.md
/assign @gracenng @reylejano @sftim
> Update release blog for cel section

- OWNERS_ALIASES
This PR removes myself from the owners.
> Remove 1.28 docs lead from owners

- content/en/docs/concepts/cluster-administration/_index.md
- content/en/docs/concepts/containers/_index.md
- content/en/docs/concepts/overview/_index.md
- content/en/docs/concepts/overview/components.md
- content/en/docs/concepts/workloads/_index.md
- content/en/docs/concepts/workloads/pods/_index.md
- content/en/docs/contribute/style/page-content-types.md
- content/en/docs/contribute/suggesting-improvements.md
- content/en/docs/home/_index.md
- content/en/docs/reference/kubectl/_index.md
- content/en/docs/reference/kubectl/cheatsheet.md
- content/en/docs/reference/kubernetes-api/_index.md
- content/en/docs/reference/labels-annotations-taints/_index.md
- content/en/docs/reference/setup-tools/kubeadm/_index.md
- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
- content/en/docs/tasks/debug/_index.md
- content/en/docs/tasks/tools/_index.md
- content/en/docs/tasks/tools/install-kubectl-linux.md
- content/en/docs/tasks/tools/install-kubectl-macos.md
- content/en/docs/tasks/tools/install-kubectl-windows.md
Reorder and replace cards to better (I hope!) serve our readers.
Old: https://k8s.io/docs/home/
Proposed: https://deploy-preview-41987--kubernetes-io-main-staging.netlify.app/docs/home/
> Revise docs home page

- content/en/blog/_posts/2023-08-18-retroactive-default-storage-class-ga.md
KEP: https://github.com/kubernetes/enhancements/issues/3333
/sig storage
> Add blog for Retroactive Default StorageClass move to GA

- content/zh-cn/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
> [zh] update system:bootstrappers group name

- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_migrate.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_reset-defaults.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_all.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_coredns.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
> Update kubeadm reference for 1.28

- content/en/docs/concepts/workloads/pods/init-containers.md
Remove an unnecessary asterisk (*) at the bottom of the page.
> remove an extra asterisk in init-containers

- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
Seems the `*` is missing in this code comment, which is not consistent with the command below.
> Fix a typo * in upgrading-linux-nodes.md

- content/en/docs/concepts/storage/persistent-volumes.md
This follows PR https://github.com/kubernetes/website/pull/42008
> Tweak docs about PersistentVolume phase

- content/en/docs/concepts/storage/persistent-volumes.md
Drop mentions of deprecated / removed storage integrations.
> Revise summary card for storage

- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/reference/node/_index.md
- content/en/docs/reference/node/node-status.md
- Created a new page in architecture in node for the status
- Removed the current node status from concepts and moved it there
> Refactoring node status to new page

- content/en/docs/concepts/overview/working-with-objects/finalizers.md
Fixes: #39490 
Page updated: https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/
> Updating Finalizers information 

- content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
- content/en/docs/reference/command-line-tools-reference/feature-gates.md
This PR fixes the feature gate status for v1.28.
> Fix feature gates for v1.28

- content/en/docs/concepts/architecture/mixed-version-proxy.md
- content/en/docs/concepts/architecture/nodes.md
> Clean up mixed-version-proxy.md and nodes.md

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
> [zh-cn] sync policy-resources/network-policy-v1.md

- content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
PR related to https://github.com/kubernetes/website/pull/39695
> Clarify which node component(s) contact control plane

- content/en/docs/reference/node/node-status.md
For the first para:
- Add `is` and `.`
/kind cleanup
> Clean up the first para in node-status

- content/zh-cn/docs/concepts/architecture/mixed-version-proxy.md
```
content/zh-cn/docs/concepts/architecture/mixed-version-proxy.md
```
See [preview](https://deploy-preview-42555--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/mixed-version-proxy/) please.
> [zh] sync mixed-version-proxy.md

- content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
```
```
See [preview](https://deploy-preview-42559--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/tools/install-kubectl-linux/) please.
> [zh] sync install-kubectl-linux.md

- content/en/case-studies/amadeus/index.html
resolve https://github.com/kubernetes/website/issues/42638
> [en] update case-studies/amadeus folder links

- content/zh-cn/case-studies/amadeus/index.html
en PR https://github.com/kubernetes/website/pull/42639/files
> [zh] update case-studies/amadeus folder links

- content/zh-cn/docs/reference/node/node-status.md
```
content/zh-cn/docs/reference/node/node-status.md
```
See [preview](https://deploy-preview-42640--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/node/node-status/) please.
> [zh] sync /reference/node/node-status.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md
> [zh] sync api reference: job-v1.md

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md
Sync with en upstream:
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md
```
See [preview](https://deploy-preview-42633--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/) please.
> [zh] sync api: persistent-volume-claim-v1.md

- content/en/docs/tasks/configure-pod-container/resize-container-resources.md
change memory resize memory -> resizing memory
> Remove redundant word in resize-container-resources.md

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
Sync 2 files:
```
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
```
See [preview](https://deploy-preview-42583--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) please.
> [zh] sync kubeadm-upgrade.md and upgrading-linux-nodes.md

- content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
en PR https://github.com/kubernetes/website/pull/42128/files
> [ja] Remove obsolete references

- data/releases/schedule.yaml
Update 1.28 maintenance mode date
Fixes issue https://github.com/kubernetes/website/issues/42659
> Update 1.28 maintenance mode date in schedule.yaml

- content/ja/docs/concepts/security/overview.md
en PR https://github.com/kubernetes/website/pull/42353/files
> [ja] attached correct link

- content/es/docs/concepts/security/overview.md
en PR https://github.com/kubernetes/website/pull/42353/files
> [es] attached correct link

- content/zh-cn/blog/_posts/2023-08-21-job-update-post.md
> [zh-cn] sync blog: 2023-08-21-job-update-post.md

- scripts/releng/update-release-info.sh
Related to https://kubernetes.slack.com/archives/C0191RDKHU1/p1680549820387879
> [releng] Mention kubernetes/websites everywhere in the same way

- content/zh-cn/docs/tasks/job/automated-tasks-with-cron-jobs.md
- content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md
- content/zh-cn/docs/tasks/job/fine-parallel-processing-work-queue.md
- content/zh-cn/docs/tasks/job/indexed-parallel-processing-static.md
- content/zh-cn/docs/tasks/job/parallel-processing-expansion.md
- content/zh-cn/docs/tasks/job/pod-failure-policy.md
Sync 
/zh-cn/docs/tasks/job/automated-tasks-with-cron-jobs.md
/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md
/zh-cn/docs/tasks/job/fine-parallel-processing-work-queue.md
/zh-cn/docs/tasks/job/indexed-parallel-processing-static.md
/zh-cn/docs/tasks/job/parallel-processing-expansion.md
/zh-cn/docs/tasks/job/pod-failure-policy.md
> [zh] Replace codenew with code for 6 files in content/zh-cn/docs/tasks/job/

- content/zh-cn/blog/_posts/2023-09-12-comparing-local-kubernetes-development-tools.md
Fix #42683 
Add zh text to this new blog.
See [preview](https://deploy-preview-42684--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/09/12/local-k8s-development-tools/) please.
> [zh] sync 2023-09-12-comparing-local-kubernetes-development-tools

- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
- content/zh-cn/examples/access/image-matches-namespace-environment.policy.yaml
- content/zh-cn/examples/access/validating-webhook-configuration-match-conditions.yaml
- content/zh-cn/examples/validatingadmissionpolicy/basic-example-binding.yaml
- content/zh-cn/examples/validatingadmissionpolicy/basic-example-policy.yaml
- content/zh-cn/examples/validatingadmissionpolicy/binding-with-param-prod.yaml
- content/zh-cn/examples/validatingadmissionpolicy/binding-with-param.yaml
- content/zh-cn/examples/validatingadmissionpolicy/failure-policy-ignore.yaml
- content/zh-cn/examples/validatingadmissionpolicy/policy-with-param.yaml
- content/zh-cn/examples/validatingadmissionpolicy/replicalimit-param-prod.yaml
- content/zh-cn/examples/validatingadmissionpolicy/replicalimit-param.yaml
- content/zh-cn/examples/validatingadmissionpolicy/typechecking-multiple-match.yaml
- content/zh-cn/examples/validatingadmissionpolicy/typechecking.yaml
> [zh-cn] sync access-authn-authz/validating-admission-policy.md

- content/en/docs/concepts/storage/ephemeral-volumes.md
- content/en/docs/concepts/storage/persistent-volumes.md
I found multiple trivial errors in the Concepts/Storage section of the documentation, which I fixed.
> Make 3 edits within Storage concepts

- content/en/docs/contribute/new-content/blogs-case-studies.md
The storytelling-resources directory does not exist
> Fix contributor comms blog guidelines link in blogs-case-studies.md

- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- content/zh-cn/docs/tasks/tools/install-kubectl-linux.md
> [zh-cn] sync configure-liveness-readiness-startup-probes install-kubectl-linux

- content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
```
content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
```
> [zh] sync command-line-tools-reference/kube-apiserver.md

- content/zh-cn/docs/home/_index.md
> [zh-cn] sync home/_index.md

- content/zh-cn/docs/concepts/configuration/secret.md
> [zh-cn] sync configuration/secret.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_validate.md
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_validate.md
```
> [zh] sync kubeadm_config_validate.md

- content/zh-cn/docs/contribute/new-content/blogs-case-studies.md
en PR https://github.com/kubernetes/website/pull/42711/files
> [zh] Fix contributor comms blog guidelines link

- content/zh-cn/docs/contribute/_index.md
- content/zh-cn/docs/contribute/style/page-content-types.md
- content/zh-cn/docs/contribute/style/style-guide.md
- content/zh-cn/docs/contribute/style/write-new-topic.md
- content/zh-cn/docs/contribute/suggesting-improvements.md
- content/zh-cn/docs/setup/production-environment/container-runtimes.md
> [zh-cn] sync contribute/* container-runtimes

- content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md
> [zh-cn] sync kube-scheduler-config.v1.md

- content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
- content/zh-cn/docs/reference/config-api/apiserver-encryption.v1.md
- content/zh-cn/docs/reference/config-api/client-authentication.v1.md
- content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
- content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md
> [zh-cn] sync  config-api/apiserver-* client-* imagepolicy

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta3.md
Sync with en text.
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta3.md
```
See [preview](https://deploy-preview-42688--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta3/) please.
> [zh] sync k8s-api: priority-level-configuration-v1beta3.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
- Indent 2 spaces for a special bullet `: `
```
```
> [zh] Sync /kubeadm/kubeadm-init.md

- content/zh-cn/docs/concepts/configuration/configmap.md
en PR https://github.com/kubernetes/website/pull/42710/files
> [zh] Highlighting an important point regarding ConfigMaps

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_migrate.md
- Remove the `auto-generated` notes at top
- Add some periods, remove redundant blank lines
> [zh] Sync kubeadm_config files

- content/en/docs/reference/using-api/deprecation-policy.md
Add some information on what is acceptable in terms of graduating metrics.
/assign @dgrisonnet
> amend deprecation policy on stability framework

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/_index.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_certificate-key.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_check-expiration.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_generate-csr.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_admin.conf.md
- Remove the `auto-generated` notes from top
- Some changes for consistent style
> [zh] sync kubeadm_certs files

- content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
- Fix and improve some words
- Ident 3 spaces for the ordered lists wrapped in tabs
/kind cleanup
> Clean up change-package-repository.md

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
```
content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
```
See [preview](https://deploy-preview-42769--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository/) please.
> [zh] sync change-package-repository.md

- content/zh-cn/docs/concepts/services-networking/ingress-controllers.md
en PR https://github.com/kubernetes/website/pull/42749/files
> [zh] fix: Wrong hyperlink of FortiADC Ingress Controller

- content/zh-cn/docs/concepts/security/rbac-good-practices.md
- content/zh-cn/docs/concepts/security/secrets-good-practices.md
content/zh-cn/docs/concepts/security/rbac-good-practices.md
content/zh-cn/docs/concepts/security/secrets-good-practices.md
> [zh-cn] sync rbac-good-practices.md secrets-good-practices.md

- content/zh-cn/blog/_posts/2023-08-25-sidecar-kep.md
> [zh-cn] sync blog native-sidecar

- content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
en PR https://github.com/kubernetes/website/pull/42627/files
> [zh] replicaset: fix ownerReferences link

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_preflight.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_remove-etcd-member.md
Sync 4 files:
```
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_preflight.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_remove-etcd-member.md
```
> [zh] sync kubeadm_reset files

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_kubelet-start.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_preflight.md
Sync 4 files:
```
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_kubelet-start.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_preflight.md
```
> [zh] sync kubeadm_join files

- content/ja/docs/tasks/run-application/horizontal-pod-autoscale.md
HPAのページの日本語訳ページを新規で作成しました。(https://github.com/kubernetes/website/issues/41756)
レビューお願い致します 🙇
> [ja] Translate tasks/run-application/horizontal-pod-autoscale into Japanese

- content/ja/docs/tutorials/stateless-application/guestbook.md
fix command in tutorial.
- EN upstream: content/en/docs/tutorials/stateless-application/guestbook.md
- Sync to: content/ja/docs/tutorials/stateless-application/guestbook.md
> [ja] fix command in tutorials/stateles-applicatoin/guestbook.md

- content/ja/docs/reference/kubectl/jsonpath.md
en PR https://github.com/kubernetes/website/pull/42263/files
> [ja] Fix inconsistent command in the JSONPath Support page

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_diff.md
Sync 3 files:
```
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_diff.md
```
> [zh] sync kubeadm_upgrade 3 files

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_kubelet-config.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_preflight.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
Sync 5 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_kubelet-config.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_preflight.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
```
> [zh] sync kubeadm_upgrade 5 files

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md
Use a same style by following our localization guide:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md
```
> [zh] Update kubeadm_upgrade_node_phase_control-plane

- content/en/docs/concepts/workloads/controllers/deployment.md
* fix the number of replicas in an example as 3 instead of 2
* remove irrelevant ReplicaSet
* format the name of ReplicaSet
> fix the number of replicas in an example

- content/es/docs/concepts/services-networking/network-policies.md
> [es] Correción documentación Network Policy

- content/en/docs/reference/using-api/server-side-apply.md
> Fix patchStrategy marker

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> [zh-cn] sync kubeadm/kubeadm-init.md

- content/en/docs/concepts/security/pod-security-admission.md
Signed-off-by: Ugur Can Ozturk [ugurozturk918@gmail.com](mailto:ugurozturk918@gmail.com)
I added psa metrics to the document. They might be useful to monitor psa activities.
> List metrics that relate to Pod security admission

- content/fr/docs/tasks/configure-pod-container/configure-pod-configmap.md
> [fr] Update configure-pod-configmap.md

- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
> [zh-cn] sync administer-cluster/encrypt-data.md

- content/zh-cn/docs/concepts/architecture/mixed-version-proxy.md
content/zh-cn/docs/concepts/architecture/mixed-version-proxy.md
> [zh-cn] sync architecture/mixed-version-proxy.md

- content/en/docs/concepts/cluster-administration/flow-control.md
- Provide a consistent look for bullets in context
/kind cleanup
> Clean up flow-control.md

- content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md
Follow-up on https://github.com/kubernetes/website/pull/42863
> Use diagram-large class for package deprecation flowchart

- content/zh-cn/docs/concepts/services-networking/ingress.md
> [zh] Tune translation for the Ingress page

- content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md
> [zh] Update configure-pod-configmap.md

- content/en/docs/tasks/administer-cluster/encrypt-data.md
These changes are split out from PR #33285
- Clarify how to ensure objects are encrypted
>   Update encryption-at-rest task page

- content/zh-cn/blog/_posts/2023-08-28-a-new-alpha-mechanism-for-safer-cluster-upgrades.md
> [zh-cn] sync blog:2023-08-28-a-new-alpha-mechanism-for-safer-cluster-upgrades.md

- README-pt.md
- Update README-pt.md following the latest english version.
- fix typos
> [pt-br] Update README-pt.md

- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
Sync with en:
```
```
See [preview](https://deploy-preview-42887--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/encrypt-data/) please.
> [zh] sync encrypt-data.md

- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
content/zh-cn/docs/concepts/workloads/controllers/deployment.md
> [zh-cn] sync controllers/deployment.md

- content/zh-cn/releases/patch-releases.md
content/zh-cn/releases/patch-releases.md
> [zh-cn] sync releases/patch-releases.md

- content/zh-cn/blog/_posts/2023-04-18-efficient-selinux-relabeling-beta.md
- content/zh-cn/blog/_posts/2023-08-25-sidecar-kep.md
Improve blog translation of Sidecar feature
> [zh] Improve blog translation of Sidecar feature

- content/zh-cn/docs/concepts/services-networking/service.md
> [zh] Tune translation of Service concept

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
```
See [preview](https://deploy-preview-42903--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1/) please.
> [zh] Sync k8s-api: /workload-resources/pod-v1.md

- content/en/docs/tasks/administer-cluster/encrypt-data.md
These changes are split out from PR #33285
- List available API encryption providers
- The heading makes it clear you have a choice as a cluster operator about which to use
- Provide better context about which to pick
- Promote creating the encryption configuration file to have its own page heading (and section)
> Update encryption-at-rest task page

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
The commit from #40134 but in a new PR. This one might pass CI/CD tests.
> Add pod affinity note

- content/zh-cn/blog/_posts/2023-04-18-efficient-selinux-relabeling-beta.md
Sync Kubernetes 1.27: Efficient SELinux volume relabeling (Beta) blog into Chinese:
```
content/zh-cn/blog/_posts/2023-04-18-efficient-selinux-relabeling-beta.md
```
> [zh] Sync Kubernetes 1.27: Efficient SELinux volume relabeling (Beta) blog into Chinese

- content/en/blog/_posts/2023-09-20-happy-7th-birthday-kubeadm.md
- content/en/blog/_posts/2023-09-26-happy-7th-birthday-kubeadm.md
Thanks to @sftim who proposed the idea, this post is celebrating kubeadm's 7th birthday
/cc @sftim @pacoxu @neolit123
> Happy 7th birthday kubeadm!

- content/zh-cn/docs/concepts/configuration/overview.md
- content/zh-cn/docs/tutorials/stateless-application/guestbook.md
Sync with en #42818 :
```
content/zh-cn/docs/concepts/configuration/overview.md
content/zh-cn/docs/tutorials/stateless-application/guestbook.md
```
> [zh] Sync guestbook.md and overview.md

- content/zh-cn/blog/_posts/2023-08-29-Gateway-API-v080.md
content/zh-cn/blog/2023-08-29-Gateway-API-v080.md
> [zh-cn] sync blog:2023-08-29-Gateway-API-v080.md

- content/en/blog/_posts/2023-09-26-happy-7th-birthday-kubeadm.md
Add a slug in the front matter to keep consistent with other blogs, and provide convenience to localization.
> Add a slug to the blog of 7th birthday kubeadm

- content/en/docs/concepts/overview/working-with-objects/_index.md
> Tweak Objects In Kubernetes concept

- layouts/docs/baseof.html
- layouts/partials/css.html
- layouts/partials/scripts.html
This PR fixes #42921 and #42947
> Fix docs mobile layout

- content/es/docs/concepts/workloads/pods/disruptions.md
Corrección de ortografía y gramática en el archivo de documentación.
Realicé correcciones de ortografía y gramática en el archivo de documentación para mejorar su claridad y legibilidad. No se realizaron cambios en el contenido ni en la estructura del documento.
Cambios detallados:
- Corregí errores de ortografía y puntuación en todo el documento.
- Alineé los términos técnicos con la terminología estándar.
- Aseguré la coherencia en el uso de mayúsculas y minúsculas.
Estos cambios no afectan el contenido ni la intención original del documento. Por favor, revisa y aprueba los cambios. ¡Gracias!
> [ES] Fix typos and grammar issues in disruptions file

- content/zh-cn/blog/_posts/2023-08-23-kubelet-podresources-api-ga.md
Sync blog 2023-08-23-kubelet-podresources-api-ga.md
> [zh] Sync blog 2023-08-23-kubelet-podresources-api-ga.md

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Sync with en v1.28 
`setup/production-environment/tools/kubeadm/install-kubeadm.md`
> [zh] Sync setup: install-kubeadm.md

- content/zh-cn/docs/concepts/cluster-administration/logging.md
- content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/zh-cn/docs/concepts/services-networking/ingress.md
- content/zh-cn/docs/concepts/services-networking/network-policies.md
> [zh-cn]sync system-metrics logging device-plugins ingress network-policies

- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
- content/zh-cn/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
- content/zh-cn/docs/tasks/configure-pod-container/assign-cpu-resource.md
- content/zh-cn/docs/tasks/configure-pod-container/assign-memory-resource.md
- content/zh-cn/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md
- content/zh-cn/docs/tasks/configure-pod-container/assign-pods-nodes.md
> [zh-cn] sync managing-secret-using-kustomize manage-resources/assign-* configure-pod-container/memory-*|cpu-*

- content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
- content/zh-cn/docs/reference/access-authn-authz/rbac.md
- content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
- content/zh-cn/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.md
- content/zh-cn/docs/tasks/access-application-cluster/connecting-frontend-backend.md
- content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
- content/zh-cn/docs/tasks/access-application-cluster/service-access-application-cluster.md
- content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
- content/zh-cn/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
- content/zh-cn/docs/tasks/debug/debug-application/get-shell-running-container.md
- content/zh-cn/docs/tasks/debug/debug-cluster/audit.md
- content/zh-cn/docs/tasks/debug/debug-cluster/monitor-node-health.md
> [zh-cn]sync access-application-cluster/* debug/* access-authn-authz/*

- content/zh-cn/blog/_posts/2023-09-26-happy-7th-birthday-kubeadm.md
```
content/zh-cn/blog/_posts/2023-09-26-happy-7th-birthday-kubeadm.md
```
See [preview](https://deploy-preview-42949--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/09/26/happy-7th-birthday-kubeadm/) please.
> [zh] sync 2023-09-26-happy-7th-birthday-kubeadm.md

- content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
sync content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> [zh-cn] sync scheduling-eviction/node-pressure-eviction.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_all.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_mark-control-plane.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_update-status.md
Clean up 5 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_mark-control-plane.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_update-status.md
```
> [zh] Clean up kubeadm_join_phase files

- content/zh-cn/docs/concepts/workloads/controllers/cron-jobs.md
- content/zh-cn/docs/concepts/workloads/controllers/daemonset.md
- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
- content/zh-cn/docs/concepts/workloads/controllers/job.md
- content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
- content/zh-cn/docs/concepts/workloads/controllers/replicationcontroller.md
- content/zh-cn/docs/concepts/workloads/pods/_index.md
- content/zh-cn/docs/concepts/workloads/pods/init-containers.md
> [zh-cn] sync concepts/workloads/*

- content/pt-br/docs/tasks/configure-pod-container/configure-pod-configmap.md
> [pt] Update configure-pod-configmap.md

- content/zh-cn/docs/reference/glossary/container-runtime.md
- content/zh-cn/docs/reference/scheduling/config.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-config.md
sync container-runtime config kubeadm-config
> [zh] sync container-runtime config kubeadm-config

- content/en/blog/_posts/2023-09-13-userns-stateful-pods/index.md
Hi!
We were talking in sig-node and we would like to post this. We know the deadlines for the 1.28 highlights are long gone now, we don't need to post this as a highlight. It can be a regular blog post.
Thanks!
cc @giuseppe @saschagrunert @mrunalp @SergeyKanzhelev
> blog: Add post about userns for stateful pods

- content/en/docs/tasks/administer-cluster/verify-signed-artifacts.md
It's possible to verify the SBOM after the modification if sbom.k8s.io in: https://github.com/kubernetes/k8s.io/pull/5763
How to do that is now documented as part of the "Verify Signed Artifacts" page.
cc @kubernetes/release-managers @justinsb 
Refers to https://github.com/kubernetes/release/issues/3222
> Add SBOM verification to docs

- content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
> [zh-cn] sync style/hugo-shortcodes/index

- content/zh-cn/docs/concepts/architecture/nodes.md
en PR https://github.com/kubernetes/website/pull/42901/files
> [zh] fix:Reference of Blog in Nodes

- content/zh-cn/docs/tasks/administer-cluster/declare-network-policy.md
- content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
- content/zh-cn/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
- content/zh-cn/docs/tasks/administer-cluster/namespaces-walkthrough.md
- content/zh-cn/docs/tasks/administer-cluster/quota-api-object.md
- content/zh-cn/docs/tasks/administer-cluster/running-cloud-controller.md
- content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md
> [zh-cn] sync tasks/administer-cluster/*

- content/en/docs/setup/best-practices/node-conformance.md
Validate node setup page mentions Docker as a container runtime.
> "Validate node setup page mentions Docker as a container runtime"

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> Fix for cgroup driver link issue

- content/zh-cn/docs/concepts/security/overview.md
en PR https://github.com/kubernetes/website/pull/42933/files
> [zh] fixes broken link to OWASP Zed Attack proxy

- content/zh-cn/blog/_posts/2023-08-24-swap-beta1-graduation.md
Sync blog 2023-08-24-swap-beta1-graduation.md into Chinese:
```
content/zh-cn/blog/_posts/2023-08-24-swap-beta1-graduation.md
```
> [zh] Sync blog 2023-08-24-swap-beta1-graduation.md into Chinese

- README.md
Earlier the resources (2 links) provided were just making user/dev land to that website, and then user have to figure out from there like where is actual solution listed in whole website? I faced this same issue a few minutes ago, while going through this documentation. But now these minor changes in resources (Updation of 2 links) will point user/dev to the right page/resource that will solve their problem.
Fixes Part1: #42845
> Updated resources of README.md

- content/en/docs/reference/networking/virtual-ips.md
This PR fixes the IPVS scheduler name list by adding schedulers that were missing and adding some descriptions (copied for source code comments) for each.
> Amend the list of ipvs schedulers with descriptions

- content/en/docs/home/_index.md
> Footer Home label now reads Documentation

- static/css/community.css
Fixed issue https://github.com/kubernetes/website/issues/42750
> Fixed added hover effect on the video link.

- content/en/releases/_index.md
- data/i18n/en/en.toml
- layouts/docs/release-info.html
Addressing issue #42812
Copied layouts/docs/release-info.html from main branch to update release-1.25 docs
Initial PR to add the layout: #41370
PR to refine the layout: #42835
> Backport "layouts/docs/release-info.html" to release-1.25

- content/en/releases/_index.md
- data/i18n/en/en.toml
- layouts/docs/release-info.html
Addressing issue #42812
Copied layouts/docs/release-info.html from main branch to update release-1.26 docs
Initial PR to add the layout: #41370
PR to refine the layout: #42835
> Backport "layouts/docs/release-info.html" to release-1.26

- content/zh-cn/docs/concepts/cluster-administration/flow-control.md
Sync with en #42075:
```
```
Two new files are synced in #43058
> [zh] sync /cluster-administration/flow-control.md

- README.md
> Updated cmds for Window users at README.md

- content/zh-cn/docs/reference/access-authn-authz/rbac.md
> fix: Correct typos

- content/en/releases/_index.md
- data/i18n/en/en.toml
- layouts/docs/release-info.html
Addressing issue #42812
Copied layouts/docs/release-info.html from main branch to update release-1.24 docs
Initial PR to add the layout: #41370
PR to refine the layout: #42835
> Backport "layouts/docs/release-info.html" to release-1.24

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_create.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_delete.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_generate.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md
Update 5 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_create.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_delete.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_generate.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md
```
> [zh] Clean up kubeadm_token files

- OWNERS_ALIASES
Hey y'all,
I am requesting that I be temporarily added as an approver while I am the docs lead for the v1.29 release cycle.
cc: @reylejano
> [1.29] Docs Lead Owner Approval

- content/es/docs/concepts/security/overview.md
resolve https://github.com/kubernetes/website/pull/42933/files
> [es] fixes broken link to OWASP Zed Attack proxy

- content/zh-cn/docs/reference/debug-cluster/_index.md
- content/zh-cn/docs/reference/debug-cluster/flow-control.md
Add zh text to 2 files:
```
content/zh-cn/docs/reference/debug-cluster/_index.md
content/zh-cn/docs/reference/debug-cluster/flow-control.md
```
See [preview](https://deploy-preview-43058--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/debug-cluster/flow-control/) please.
> [zh] Sync /reference/debug-cluster/

- content/en/docs/reference/kubectl/_index.md
> Improvements in kubectl reference

- content/zh-cn/docs/tasks/administer-cluster/decrypt-data.md
```
content/zh-cn/docs/tasks/administer-cluster/decrypt-data.md
```
See [preview](https://deploy-preview-43101--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/decrypt-data/) please.
> [zh] Sync decrypt-data.md

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
There are some text useful before v1.23 release, but no longer supported. 
Now we are moving on to v1.28 as the lastest version, these contents become obsolete and confusing. We'd better remove them because docs related to pre-1.24 releases are no longer supported.
> Remove deprecated text from probes task

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig_user.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node.md
Update 4 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig_user.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase.md
```
> [zh] Clean up kubeadm_kubeconfig files

- hugo.toml
Updating the hugo.toml for v1.29
> Updates hugo.toml for 1.29 release

- content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
en PR https://github.com/kubernetes/website/pull/42822
> [zh] update the range of pod-deletion-cost

- content/en/releases/patch-releases.md
- data/releases/schedule.yaml
Add October patch releases to the releases calendar
> Add October patch releases to the releases calendar

- content/pt-br/docs/concepts/security/overview.md
en PR https://github.com/kubernetes/website/pull/42933/files
> [pt] fixes broken link to OWASP Zed Attack proxy

- content/ko/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
> [ko] Translate docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd into Korean

- content/ko/docs/tasks/manage-daemon/pods-some-nodes.md
- content/ko/examples/controllers/daemonset-label-selector.yaml
> [ko] Translate content\en\docs\tasks\manage-daemon\pods-some-nodes into Korean

- content/ko/docs/tutorials/hello-minikube.md
- content/ko/docs/tutorials/kubernetes-basics/_index.html
- content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
- content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
- content/ko/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
- content/ko/docs/tutorials/kubernetes-basics/explore/explore-intro.html
Related comment: https://github.com/kubernetes/website/issues/41631#issuecomment-1608836600
[x] M222. content/en/docs/tutorials/hello-minikube.md | 41(+M) 37(-)
[x] M223. content/en/docs/tutorials/kubernetes-basics/_index.html | 3(+XS) 1(-)
[x] M224. content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html | 17(+S) 19(-)
[x] M225. content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html | 11(+S) 9(-)
[x] M226. content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html | 17(+S) 33(-)
[x] M227. content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html | 67(+M) 14(-)
[x] M228. content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html | 17(+S) 25(-)
[x] M229. …
> [ko] Update outdated files in dev-1.27-ko.1 (M222-M229)

- content/ko/docs/tasks/administer-cluster/network-policy-provider/_index.md
- content/ko/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md
- content/ko/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
- content/ko/docs/tasks/administer-cluster/network-policy-provider/kube-router-network-policy.md
- content/ko/docs/tasks/administer-cluster/network-policy-provider/romana-network-policy.md
- content/ko/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy.md
Related Issue: #41631
Updated outdated files in `content/en/docs/tasks/administer-cluster/network-policy-provider/`.
**6 files to be modified**
> [ko] Update outdated files in dev-1.27-ko.1 (M150-M155)

- content/zh-cn/blog/_posts/2023-09-13-userns-stateful-pods/index.md
content/zh-cn/blog/_posts/2023-09-13-userns-stateful-pods/index.md
> [zh-cn] sync blog: 2023-09-13-userns-stateful-pods
