content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
content/zh-cn/docs/tasks/tools/install-kubectl-macos.md

Sync with en #41300 and #41574 
```
content/zh-cn/docs/tasks/tools/install-kubectl-macos.md
```
See [preview encrpt-data](https://deploy-preview-41901--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/encrypt-data/) and [preview install-kubectl-macos](https://deploy-preview-41901--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/tools/install-kubectl-macos/).

[zh] sync encrypt-data.md and install-kubectl-macos.md

---

content/en/docs/concepts/services-networking/windows-networking.md

This PR fix the link for `IPv4/IPv6 dual-stack` in [Networking on windows](https://kubernetes.io/docs/concepts/services-networking/windows-networking/).  
Fixes #41905

Fix broken link for IPv4/IPv6 dual-stack (Windows)

---

content/en/docs/concepts/workloads/pods/user-namespaces.md

The variable expansion is wrong: it currently expands to 1.27.3 on the rendered website. Furthermore, we don't want this to be expanded to other versions when the current k8s release is 1.30.
So, let's just use the plain versions, as that is what we really want.

content: Clarify version requirements for userns and other minor fixes

---

content/en/docs/concepts/workloads/pods/_index.md

Rewrite current note on container runtimes that incorrectly highlights Docker as a K8s runtime. Fixes #36450

Pods - rewrite note on container runtimes

---

content/zh-cn/docs/concepts/services-networking/windows-networking.md

- **EN upstream**: `content/en/docs/concepts/services-networking/windows-networking.md`
- **Sync to**: `content/zh-cn/docs/concepts/services-networking/windows-networking.md`
```diff
$ ./scripts/lsync.sh content/zh-cn/docs/concepts/services-networking/windows-networking.md
diff --git a/content/en/docs/concepts/services-networking/windows-networking.md b/content/en/docs/concepts/services-networking/windows-networking.md
index e0e34c133b..4e987aaed3 100644
--- a/content/en/docs/concepts/services-networking/windows-networking.md
+++ b/content/en/docs/concepts/services-networking/windows-networking.md
@@ -117,7 +117,7 @@ balancing behavior:
| Session affinity | Ensures that connections from a particular client are passed to the same Pod each …
```

[zh] sync concepts/services-networking/windows-networking

---

content/en/docs/concepts/architecture/nodes.md

Fixed Feature Gate state for "Pod Priority based graceful node shutdown" in "Nodes" page
FEATURE STATE: Kubernetes v1.23 [alpha]  -> FEATURE STATE: Kubernetes v1.24 [beta]
https://kubernetes.io/docs/concepts/architecture/nodes/#pod-priority-graceful-node-shutdown
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
Fixes #41874

Fix wrong feature state

---

content/en/docs/reference/labels-annotations-taints/_index.md

- fix typos
-  add necessary blank lines
- fix anchors
```
content/en/docs/reference/labels-annotations-taints/_index.md
```

Fix typos in labels-annotations-taints

---

content/en/blog/_posts/2023-04-18-efficient-selinux-relabeling-beta.md

Normally a blog has a single heading 1 in the front matter, but this blog is special with multiple.
```
content/en/blog/_posts/2023-04-18-efficient-selinux-relabeling-beta.md
```
See [preview](https://deploy-preview-41554--kubernetes-io-main-staging.netlify.app/blog/2023/04/18/kubernetes-1-27-efficient-selinux-relabeling-beta/).

modify heading levels in blog: efficient-selinux-relabeling-beta

---

content/en/docs/concepts/services-networking/service.md

This PR updated the FEATURE STATE of `MixedProtocolLBService` under the [Service](https://kubernetes.io/docs/concepts/services-networking/service/) docs.
Fixes #41965

Fix feature state for MixedProtocolLBService

---

content/en/docs/tasks/tools/_index.md

Update Kind install prerequisites to include podman as an option, besides docker. Fixes #36159

update kind install prereqs to include podman

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

We discussed it on Slack that we want to delay July 2023 patch release for a week (to July 19) as we still have some important PRs to merge (such as bump to Go 1.20) and we want to give enough time for tests results to soak in.
I also postponed the cherry-pick deadline as we plan on merging additional PRs.
Reference: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1689013512945219
/assign @cpanato @Verolop @jeremyrickard 
cc @kubernetes/release-engineering 
/hold
we're still waiting a confirmation from Google Build Admins

Delay July 2023 patch releases for July 19

---

content/id/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
content/id/docs/tasks/tools/install-kubectl.md

Fixes https://github.com/kubernetes/website/issues/41485
There doesn't seem to be a localization branch for `in`, so I'm using `main` instead.
Related to https://github.com/kubernetes/website/issues/41005

[id] Replace deprecated fullversion shortcode #41485

---

content/en/docs/concepts/storage/windows-storage.md

This PR fix the link for `Kubernetes Volume Plugin ` in [Windows Storage](https://kubernetes.io/docs/concepts/storage/windows-storage/). 
Fixes #41990

Fix the broken link for Kubernetes Volume Plugin

---

static/_redirects

Add redirection for https://kubernetes.io/ja/docs/setup/learning-environment/ to behave the same way as EN version
Fixes https://github.com/kubernetes/website/issues/41724
Before:
No redirect
After:
Redirection to https://kubernetes.io/ja/docs/tasks/tools/

Add ja redirect for learning environment

---

content/en/docs/concepts/workloads/_index.md
content/en/docs/concepts/workloads/controllers/_index.md
content/en/docs/concepts/workloads/controllers/cron-jobs.md
content/en/docs/concepts/workloads/controllers/daemonset.md
content/en/docs/concepts/workloads/controllers/deployment.md
content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/concepts/workloads/controllers/replicaset.md
content/en/docs/concepts/workloads/controllers/replicationcontroller.md
content/en/docs/concepts/workloads/controllers/statefulset.md

Change https://kubernetes.io/docs/concepts/workloads/controllers/ from a bare list of topics to something with more text in it.
[[preview](https://deploy-preview-37593--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/)]

Improve overview for workload APIs

---

content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md

Hi!
This PR aims to fix #41896.
Currently, the 'FailedToRetrieveImagePullSecret' event is logged when a pod references a secret containing registry credentials and the secret doesn't exist. The documentation doesn't mention this event in any of its pages.
This PR aims to amend that by adding examples of what happens in such a case.

Add 'FailedToRetrieveImagePullSecret' event examples

---

content/en/docs/concepts/services-networking/service.md

Mention default type of Service in “Defining a Service” section

---

content/en/docs/concepts/storage/storage-classes.md

See https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1005 for the context. This change clarifies how zonal provisioning will error depending on the state of CSI migration.
/cc @msau42 
/cc @jsafrane

Detail zonal provisioning for GCE PD

---

content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md

SIG CLI Spotlight article.
Initial review is done in the contributor-site: https://github.com/kubernetes/contributor-site/pull/411
The final version there will be copied here, with any necessary adjustments, like the date.

Add SIG CLI Spotlight article

---

scripts/README.md
scripts/linkchecker.py

Add a new flag `-w` to enable experimental in-place substitutions for Markdown links only.
This is intended to reduce the amount of repetitive work required to update out-of-date links.

Add in-place substitution option for linkchecker.py

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md

This change fixes a typo in the feature gate name.
This PR is limited to English docs. A separate one for `zh-cn` fill follow after this one is merged.

Fix StableLoadBalancerNodeSet feature gate name

---

content/fr/docs/reference/glossary/selector.md
content/fr/docs/tasks/access-application-cluster/connecting-frontend-backend.md
content/fr/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
content/fr/docs/tasks/access-application-cluster/service-access-application-cluster.md
content/fr/examples/service/access/backend-deployment.yaml
content/fr/examples/service/access/backend-service.yaml
content/fr/examples/service/access/frontend-deployment.yaml
content/fr/examples/service/access/frontend-nginx.conf
content/fr/examples/service/access/frontend-service.yaml
content/fr/examples/service/access/hello-application.yaml

Hi,
This adds the French translation for the following tasks from the  "Access Applications in a Cluster" section:
- Connect a Frontend to a Backend Using Services ([reference document](https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/))
- Use Port Forwarding to Access Applications in a Cluster ([reference document](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/))
- Use a Service to Access an Application in a Cluster ([reference document](https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/))
I also added the example files and referenced glossary entries for the tasks.

[fr] translate tasks from section "access-application-cluster"

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Document that CRD authors have to implement the optional field `status.labelSelectorPath` in the `/scale` subresource if they want VPA support for their custom resource.

Add that VPA also requires scale subresource labelSelectorPath

---

content/en/docs/concepts/overview/components.md

This PR is intended to fix [Issue 41864](https://github.com/kubernetes/website/issues/41864)
Clarified that the number of examples of controllers provided in [https://kubernetes.io/docs/concepts/overview/components/#kube-controller-manager](https://kubernetes.io/docs/concepts/overview/components/#kube-controller-manager) is not exhaustive.

Clarifying number of examples of controllers

---

content/en/docs/concepts/security/security-checklist.md

Reword the seccomp paragraph to remove the outdated alpha feature reference. Fixes #40855

Reword seccomp paragraph to remove alpha feature reference

---

data/i18n/en/en.toml
layouts/docs/baseof.html
layouts/partials/docs/outdated_content.html

I have implemented a notification on the localization page to alert users that information may be out of date.
issue: https://github.com/kubernetes/website/issues/41519
This function is implemented with the following logic
1. get the `Lastmod` of the currently opened page.
2. get the `Lastmod` of the English version of the page.
3. compare 1 and 2 and display a notification if 1 is older.
I am a Japanese speaker and could not configure non-English i18n settings.
If this implementation details are ok, I would appreciate it if you could work with me to come up with messages in other languages :)
https://github.com/kubernetes/website/assets/24271557/6d2fc27a-64af-4e16-881d-d9ccf85bbb8f

Provide a per-page outdated notification for localized content

---

content/en/docs/contribute/localization.md

This pull request introduces a new subsection in the localization guide that provides instructions and guidelines for translating SVG images used in the Docs. The guide aims to assist new contributors in understanding the process of translating text within SVG images and outlines the community rules and best practices to follow.
The purpose of this guide is to ensure consistency and accuracy in translated images across different languages, making Kubernetes documentation more accessible to a wider audience.
This PR is associated with the tracking issue: #41603

Add guide for translating SVG images

---

content/en/docs/reference/using-api/deprecation-guide.md
content/zh-cn/docs/reference/using-api/deprecation-guide.md

Add link to `kubectl convert` installation instructions and deprecation notes.
More info here:
https://github.com/kubernetes/website/issues/28724#issuecomment-1511916788

Add link to `kubectl convert`

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/networking/virtual-ips.md

(The fact that it looks like we missed adding a Beta feature-gates line for 1.27 is an artifact of the current state of the `dev-1.28` branch. The line exists in `main`.)

KEP-3453 to GA

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

This PR fixed the hyper links for `OpenAPI validation schemas are also published` and `Validation Schema Publishing` in the [Extend the Kubernetes API with CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) task page
Fixes #42049

Fix broken hyperlinks to “Extend the Kubernetes API with CustomResource Definitions” task page

---

content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md

use  “并且”(and) install of  "或者"(or)

fix expression err in content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md

---

content/en/docs/concepts/configuration/overview.md
content/en/docs/concepts/overview/working-with-objects/_index.md

Add warning note that documents Issue 34146, which addresses YAML 1.1/1.2 compatibility issues in Kubernetes.
Fixes #36526

Add note that documents YAML compatibility bug

---

content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

fix the missing < character  in configure-liveness-readiness-startup-probes.md.

[zh] fix the missing < character  in configure-liveness-readiness-startup-probes.md

---

content/zh-cn/docs/concepts/configuration/overview.md

- **EN upstream**: `content/en/docs/concepts/configuration/overview.md`
- **Sync to**: `content/zh-cn/docs/concepts/configuration/overview.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/configuration/overview.md
diff --git a/content/en/docs/concepts/configuration/overview.md b/content/en/docs/concepts/configuration/overview.md
index 7266f2b7eb..a040990cd8 100644
--- a/content/en/docs/concepts/configuration/overview.md
+++ b/content/en/docs/concepts/configuration/overview.md
@@ -37,6 +37,23 @@ to others, please don't hesitate to file an issue or submit a PR.
- Put object descriptions in annotations, to allow better introspection.
+{{< note >}}
+There is a breaking change introduced in the [YAML …
```

[zh] sync concepts/configuration/overview.md

---

content/en/docs/tasks/administer-cluster/topology-manager.md

Enhancement link: https://github.com/kubernetes/enhancements/issues/3545
Implementation link:  https://github.com/kubernetes/kubernetes/pull/118816

topologymanager: document topology manager policy options promotion to beta 

---

content/zh-cn/docs/concepts/security/security-checklist.md

- **EN upstream**: `content/en/docs/concepts/security/security-checklist.md`
- **Sync to**: `content/zh-cn/docs/concepts/security/security-checklist.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/security/security-checklist.md
diff --git a/content/en/docs/concepts/security/security-checklist.md b/content/en/docs/concepts/security/security-checklist.md
index 99ad8b6180..ce96812567 100644
--- a/content/en/docs/concepts/security/security-checklist.md
+++ b/content/en/docs/concepts/security/security-checklist.md
@@ -97,6 +97,7 @@ For restricted LoadBalancer and ExternalIPs use, see
[CVE-2020-8554: Man in the middle using LoadBalancer or ExternalIPs](https://github.com/kubernetes/kubernetes/issues/97076)
and the …
```

[zh] sync concepts/security/security-checklist.md

---

content/en/docs/concepts/workloads/controllers/_index.md

Using indefinite article for 'create a workload object'

Fix grammatical issue with 'create workload object'

---

content/zh-cn/docs/setup/production-environment/tools/kops.md
content/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry.md

Sync 2 files with en:
```
content/zh-cn/docs/setup/production-environment/tools/kops.md
content/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry.md
```
Also replaced `凭证` with `凭据` by following [glossary](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#glossary).
See [preview kops](https://deploy-preview-42006--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kops/) and [preview pull-image-private-registry](https://deploy-preview-42006--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry/) please.

[zh] sync pull-image-private-registry.md and kops.md

---

content/en/blog/_posts/2022-09-14-pod-has-network-condition.md

We renamed the PodHasNetwork condition to PodReadyToStartContainers condition in 1.28.  
We want to keep the recent blog post up to date.

rename PodHasNetwork to PodReadyToStartContainers as part of rename

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Graduate RetroactiveDefaultStorageClass featrue to GA in 1.28.
KEP: https://github.com/kubernetes/enhancements/issues/3333
KEP 1.28: https://github.com/kubernetes/enhancements/pull/4021
k/k: https://github.com/kubernetes/kubernetes/pull/118102

graduate RetroactiveDefaultStorageClass feature to GA in 1.28

---

content/uk/docs/tutorials/hello-minikube.md

This is a continuation of PR https://github.com/kubernetes/website/pull/42180 (Replace {{< codenew ... >}} with {{% codenew ... %}})
Fixes https://github.com/kubernetes/website/issues/42179 (Copy To Clipboard breaks YAML format)

[uk] replaced {{< codenew ... >}} with {{% codenew ... %}}

---

content/zh-cn/docs/concepts/workloads/controllers/daemonset.md
content/zh-cn/docs/concepts/workloads/controllers/deployment.md
content/zh-cn/docs/concepts/workloads/controllers/job.md
content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
content/zh-cn/docs/concepts/workloads/controllers/statefulset.md

One observation we can make is that the file `content/zh-cn/docs/concepts/workloads/controllers/_index.md` contains a header attributtion `simple_list: true`. This attribution is used to detect the header attribution `hide_summary: true | false` on the child pages within the `content/zh-cn/docs/concepts/workloads/controllers` folder. Its purpose is to determine whether to display these child pages at the end of `content/zh-cn/docs/concepts/workloads/controllers/_index.md`.
Considering this, it would be prudent to synchronize all the pages' headers in the `content/zh-cn/docs/concepts/workloads/controllers` folder to ensure that the sub-page list matches the one on the English upstream page in PR #42004.
Thanks to the reviewers in advance.
Best Regards,
Kivinsae Fang

[zh] sync workloads/controllers/*.md headers for #42004

---

content/es/docs/concepts/overview/working-with-objects/kubernetes-objects.md
content/es/docs/concepts/services-networking/network-policies.md
content/es/docs/concepts/workloads/controllers/daemonset.md
content/es/docs/concepts/workloads/controllers/deployment.md
content/es/docs/concepts/workloads/controllers/garbage-collection.md
content/es/docs/concepts/workloads/controllers/jobs-run-to-completion.md
content/es/docs/concepts/workloads/controllers/replicaset.md
content/es/docs/concepts/workloads/controllers/replicationcontroller.md
content/es/docs/tasks/configure-pod-container/configure-volume-storage.md
content/es/docs/tasks/debug-application-cluster/audit.md
content/es/docs/tasks/manage-kubernetes-objects/declarative-config.md
content/es/docs/tasks/run-application/run-stateless-application-deployment.md
content/es/docs/tutorials/hello-minikube.md

This is a continuation of PR https://github.com/kubernetes/website/pull/42180 (Replace {{< codenew ... >}} with {{% codenew ... %}})
Fixes https://github.com/kubernetes/website/issues/42179 (Copy To Clipboard breaks YAML format)

[es] replaced {{< codenew ... >}} with {{% codenew ... %}}

---

content/en/docs/concepts/services-networking/dns-pod-service.md

This PR updates `ExpandedDNSConfig` feature to stable. This is the missing part of the https://github.com/kubernetes/website/pull/40639.

Mark ExpandedDNSConfig feature to stable

---

OWNERS_ALIASES

[ydFu](https://github.com/ydFu) has been an active contributor to k/website over the past few years. He has contributed greatly by reviewing [more than 300 PRs](https://github.com/kubernetes/website/pulls/assigned/ydFu) in both English and Chinese. 
As discussed on Slack, I would like to sponsor ydFu as a zh-docs approver. This role will involve reviewing and approving PRs specifically related to the Chinese documentation.
cc @tengqm @howieyuen @my-git9 @mengjiao-liu

add ydFu to zh-owner

---

content/en/docs/concepts/workloads/pods/_index.md

Page updated: [kubernetes.io/docs/concepts/workloads/pods/#static-pods](https://kubernetes.io/docs/concepts/workloads/pods/#static-pods)
Changd [kubernetes.io/docs/concepts/workloads/pods/#static-pods](https://kubernetes.io/docs/concepts/workloads/pods/#static-pods) to link to [kubernetes.io/docs/tasks/configure-pod-container/static-pod](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/)
Resolves: https://github.com/kubernetes/website/issues/42195

Link Static Pod Task page with Static Pod Concept

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/networking/virtual-ips.md

Update references to feature gate ProxyTerminatingEndpoints which went GA in 1.28. 
https://github.com/kubernetes/enhancements/issues/1669

update feature gate references for ProxyTerminatingEndpoint in 1.28

---

content/en/docs/concepts/services-networking/ingress-controllers.md

Adding the reference to the OCI Native Ingress Controller to the public documentation.
https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/

Update ingress-controllers.md with OCI Native Ingress Controller

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

The Kubernetes patch releases scheduled for July went out yesterday so this PR updates the release calendar.
Patch release dates for October and November will be added as part of #42108
/assign @saschagrunert @cpanato @puerco @jeremyrickard 

Update patch releases calendar after July releases

---

content/en/docs/reference/labels-annotations-taints/_index.md

The annotation is alpha, so record that detail.

Mark alpha.kubernetes.io/provided-node-ip as alpha

---

content/en/docs/tasks/tools/install-kubectl-linux.md

Use the `skew` shortcode instead. Helps with #41005 (but doesn't close it).

Remove a deprecated param

---

content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

This closes #42111
Added: The value of `periodSeconds` must be less than or equal to 1800(half an hour).

Add threshold value for 'periodSeconds'

---

content/en/docs/tasks/configure-pod-container/security-context.md

The link to an article discussing Docker and SELinux has been replaced with a link to a CRI Plugin configuration guide, which includes configuration items related to AppArmor and SELinux.
However the link still has the original title ("Tuning Docker with the newest security enhancements"). This change updates the title to match the title of the current target article.

Correct link title in security-context.md.

---

content/zh-cn/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md

While browsing through the metrics-server related documentation, an error was found.
The specific application name `metrics-server` should not be translated.

Fix incorrect translation for resource-metrics-pipeline.md

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md

- Keep consistent style for localization
```
content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
```
See [preview](https://deploy-preview-41853--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) please.

[zh] sync setup-ha-etcd-with-kubeadm.md and troubleshooting-kubeadm.md

---

content/en/docs/contribute/style/hugo-shortcodes/index.md
layouts/partials/hooks/body-end.html
layouts/shortcodes/code.html

Part of https://github.com/kubernetes/website/issues/42203
This PR is dedicated to doing the following:
- Make a new shortcode named `code` that does exactly what `codenew` does
Here is the [preview page](https://deploy-preview-42242--kubernetes-io-main-staging.netlify.app//docs/contribute/style/hugo-shortcodes/#source-code-files).

Add code shortcode to replace codenew

---

content/en/docs/tasks/administer-cluster/ip-masq-agent.md

This PR:
Updates a typo by adding in a missing `/` splitting network prefix and host identifier in the CIDR notation of "IP Masquerade Agent User Guide" here https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent

Fix missing "/" in CIDR netblock

---

content/en/docs/concepts/architecture/leases.md

This fixes #41881
Corrected the incorrect(old) label in kubectl command for inspecting Leases for kube-apiserver.

Correct the incorrect label in kubectl command for inspecting Leases for kube-apiserver

---

content/zh-cn/docs/concepts/services-networking/topology-aware-routing.md

- **EN upstream**: `content/en/docs/concepts/services-networking/topology-aware-routing.md`
- **Sync to**: `content/zh-cn/docs/concepts/services-networking/topology-aware-routing.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/services-networking/topology-aware-routing.md
diff --git a/content/en/docs/concepts/services-networking/topology-aware-routing.md b/content/en/docs/concepts/services-networking/topology-aware-routing.md
index 1977f199d0..7092946e85 100644
--- a/content/en/docs/concepts/services-networking/topology-aware-routing.md
+++ b/content/en/docs/concepts/services-networking/topology-aware-routing.md
@@ -154,10 +154,9 @@ zone.
-* Topology Aware Hints are not used when either `externalTrafficPolicy` or
- …
```

[zh] sync concepts\services-networking\topology-aware-routing.md

---

content/en/docs/tutorials/configuration/configure-redis-using-configmap.md
content/en/docs/tutorials/security/apparmor.md
content/en/docs/tutorials/security/seccomp.md
content/en/docs/tutorials/services/connect-applications-service.md
content/en/docs/tutorials/services/pods-and-endpoint-termination-flow.md
content/en/docs/tutorials/stateful-application/basic-stateful-set.md
content/en/docs/tutorials/stateful-application/cassandra.md
content/en/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
content/en/docs/tutorials/stateful-application/zookeeper.md
content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
content/en/docs/tutorials/stateless-application/guestbook.md

Replace legacy `{{% codenew file="…" %}}` shortcode with `{{% code file="…" %}}` shortcode.
Part of https://github.com/kubernetes/website/issues/42203
This covers the Tutorials section of the English docs.
/language en
/kind cleanup

Use code shortcode for Tutorials section

---

content/zh-cn/docs/tasks/administer-cluster/topology-manager.md

Fix a typo in the page [topology-manager/#policy-single-numa-node](https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/topology-manager/#policy-single-numa-node).

[zh-cn] Fix typo in zh-cn/docs/tasks/administer-cluster/topology-manager.md

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/concepts/workloads/controllers/statefulset.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/labels-annotations-taints/_index.md

The purpose of these changes are to add documentation for the new pod index label being added for StatefulSets and Indexed Jobs (see [KEP-4017](https://github.com/kubernetes/enhancements/pull/4019)).

Add docs for KEP-4017 (pod index label)

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

/sig node
/kind cleanup
Good link for some context: https://forums.developer.nvidia.com/t/refresh-docker-mount-for-tmp-argus-socket/214682/5

added a note about mounting pod-resources instead of kubelet.sock

---

content/en/docs/concepts/containers/images.md

/sig node
See https://github.com/kubernetes/enhancements/issues/3673#issuecomment-1632759221
This is promoting the feature to beta. This feature has no feature gates, see https://github.com/kubernetes/kubernetes/pull/115220

Promote parallel image pulls to beta

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Update doc for KEP 2876

---

content/en/releases/version-skew-policy.md

This updates the skew policy for n-3 node support, starting with 1.28 control planes / 1.25 nodes.
See https://github.com/kubernetes/enhancements/issues/3935 and https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/3935-oldest-node-newest-control-plane for details.
I opened this against the dev-1.28 branch since the published policy should not be updated until we actually have 1.28 control planes that would support n-3 skew.
Preview at https://deploy-preview-42218--kubernetes-io-vnext-staging.netlify.app/releases/version-skew-policy/
/assign @dims
/sig architecture

Update skew policy for n-3 nodes for 1.28/1.25+

---

content/en/docs/concepts/architecture/nodes.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Upstream: https://github.com/kubernetes/kubernetes/pull/118228
KEP: https://github.com/kubernetes/enhancements/pull/4029

NodeOutOfServiceVolumeDetach feature update to GA

---

content/en/docs/contribute/generate-ref-docs/contribute-upstream.md

While reviewing the PR https://github.com/kubernetes/kubernetes/pull/119575#discussion_r1275170601
, I noticed that some of the scripts that generate the OpenAPI had changed.
The following scripts have been removed in Kubernetes upstream.
```
hack/update-generated-swagger-docs.sh
hack/update-generated-protobuf.sh
hack/update-api-reference-docs.sh
```
`hack/update-generated-swagger-docs.sh` and `hack/update-generated-protobuf.sh` were removed.
- https://github.com/kubernetes/kubernetes/pull/115246/ 
`hack/update-api-reference-docs.sh` was removed.
- https://github.com/kubernetes/kubernetes/pull/72924/
xref:
- https://github.com/kubernetes/website/pull/28087

Update outdated scripts for generating the OpenAPI spec

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

It looks like 'kubeadm alpha kubeconfig' was deprecated as of 1.21 and removed as of 1.22.
This PR fixes the references to that command in the creating a cluster with kubeadm documentation. 
Removed in 1.22
https://github.com/kubernetes/kubernetes/pull/101938
Deprecated in 1.21
https://github.com/kubernetes/kubernetes/pull/97583

Remove obsolete references to 'kubeadm alpha kubeconfig' command

---

content/en/docs/reference/kubernetes-api/workload-resources/job-v1.md

Update the docs as podFailurePolicy is now Beta, see: https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-failure-policy
We may need to cherry-pick it as it is Beta since 1.26.

Bump API level in docs for the podFailurePolicy field (manual bump)

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/storage-classes.md
content/en/docs/concepts/storage/volumes.md
content/en/docs/concepts/storage/windows-storage.md

Fixes: https://github.com/kubernetes/website/issues/42256
Checked kubernetes upstream PRs：
plugin | deprecated| removed
-- | -- | --
AWSElasticBlockStore | 1.19 | 1.27 https://github.com/kubernetes/kubernetes/pull/115838
AzureDisk | 1.19 | 1.27 https://github.com/kubernetes/kubernetes/pull/116301 
OpenStack Cinder | 1.11  https://github.com/kubernetes/kubernetes/pull/63524  <br>The deprecated version of [previous PR](https://github.com/kubernetes/website/pull/32924#discussion_r850223194) update was incorrect| 1.26 https://github.com/kubernetes/kubernetes/pull/67782
GCEPersistentDisk|1.17|1.28 https://github.com/kubernetes/kubernetes/pull/117055
Preview pages:
- [persistent-volumes](https://deploy-preview-42302--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/persistent-volumes …

Update In-tree storage driver status

---

content/en/docs/reference/access-authn-authz/admission-controllers.md

Recently I have been asked which built-in Admission controllers are validating and which ones are mutating. Upon checking the documentation I noticed that this information is provided only in the source code, so I went ahead and documented this.

admission controllers: document types

---

content/en/docs/contribute/style/hugo-shortcodes/index.md

For https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#source-code-files
- fix heading level (it shouldn't be part of the section about tabs)
- tweak the note about the old `{{% codenew %}}` shortcode - and move it to come last

Fix explanation of custom code shortcode

---

content/en/docs/concepts/architecture/nodes.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Edit `content/en/docs/concepts/architecture/nodes.md` that's outdated.
Also, update feature gates docs to reflect that.
For more info, see: https://github.com/kubernetes/enhancements/issues/4128

Swap graduates to Beta1: add documentation and update feature gates

---

content/en/releases/patch-releases.md

As a follow up on #42106, this PR adds patch release dates for October and December 2023.
As discussed in this PR, we decided to skip patch releases in November because of overlap with KubeCon and lack of availability of Release Managers and Google Build Admins.
/hold
for discussion and to check availability of Google Build Admins
/assign @saschagrunert @cpanato @jeremyrickard @puerco @Verolop 

Add patch releases dates for October and November 2023

---

content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
content/ja/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
content/ja/docs/tutorials/services/connect-applications-service.md

Fixup for PR #41527
I haven't brought these pages up to date; some are stale. The only change is to swap to using `skew`.

[ja] Switch out deprecated fullversion param

---

content/zh-cn/docs/concepts/workloads/pods/_index.md

The file `tasks\administer-cluster\ip-masq-agent.md` has been updated in this PR (https://github.com/kubernetes/website/pull/42234) ,so we will synchronize the localization.
**EN upstream**: content\en\docs\concepts\workloads\pods\_index.md
**Sync to**: content\zh-cn\docs\concepts\workloads\pods\_index.md

[zh] sync workloads\pods\_index.md

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

document that the `GetAllocatableResources` podresources API endpoint is GA in 1.28
enh: https://github.com/kubernetes/enhancements/issues/2403

node: podresources: GetAllocatable API is GA

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

KEP-3178 IPTablesOwnershipCleanup is going GA, so update the feature gate list.

update feature gate list for KEP-3178 to GA

---

content/en/docs/reference/glossary/mixed-version-proxy.md

Add an entry in glossary for MVP

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/storage-classes.md
content/en/docs/concepts/storage/volumes.md

Ceph RBD driver is in deprecation path :
https://github.com/kubernetes/kubernetes/pull/118552
CephFS driver is in deprecation path: 
https://github.com/kubernetes/kubernetes/pull/118143

Mention CephFS and RBD in-tree storage driver deprecation

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/setup/production-environment/container-runtimes.md
content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md

Documentation for KEP-4033.
Document the KubeletCgroupDriverFromCRI feature gate. Also, add notes of this feature in parts of the documentation that describe cgroup driver configuration.
Refs:
- [KEP-4033](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4033-group-driver-detection-over-cri) (issue https://github.com/kubernetes/enhancements/issues/4033)
- k/k PRs:
- https://github.com/kubernetes/kubernetes/pull/118770
- https://github.com/kubernetes/kubernetes/pull/119441
> **NOTE:** no container runtime supports this new feature, yet, so we cannot refer to specific versions of runtimes (yet)
> **NOTE:** replaces/re-submits #42091 which was unwittingly submitted against the main branch

docs: document kubelet cgroup driver detection from the runtime

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

This change expands the documentation for the Device Plugin to include
the addition of support for CDI Device Names as a feature-gated feature
in the 1.28 release as part of KEP-4009.
* KEP tracking issue: https://github.com/kubernetes/enhancements/issues/4009
* Implementation PR: https://github.com/kubernetes/kubernetes/pull/118254

Add CDI Devices to Device Plugin API

---

content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md

docs:  Correct the wrong description about the type of volumeMounts.subPath in the Chinese document
There is a wrong description about the type of volumeMounts.subPath in the Chinese document ，type is string in the English document but boolean in the Chinese document.

[zh] Correct the wrong description about the type of volumeMounts.subPath

---

content/en/docs/concepts/configuration/configmap.md

The feature gate "ImmutableEphemeralVolumes" is among the [removed features](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), so now there's no way to switch it — it's always on.
https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

remove optional ImmutableEphemeralVolumes feature gate

---

content/en/docs/concepts/storage/volume-snapshot-classes.md

This PR added the hyperlink for [delete section](https://kubernetes.io/docs/concepts/storage/volume-snapshots/#delete) to the [DeletionPolicy](https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/#deletionpolicy) under the Volume Snapshot Classes.
Fixes #28728

Add hyperlink to DeletionPolicy

---

content/en/docs/concepts/storage/ephemeral-volumes.md

Fixes: https://github.com/kubernetes/website/issues/42259
`GenericEphemeralVolume`feature gate  is removed in k8s v1.25 https://github.com/kubernetes/kubernetes/pull/109435
`CSIInlineVolume` feature gate is removed in k8s v1.27 https://github.com/kubernetes/kubernetes/pull/114410
see the [preview page](https://deploy-preview-42317--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/ephemeral-volumes/).

Update ephemeral volumes feature state

---

content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md

Related-to: https://github.com/kubernetes/enhancements/issues/3063
Fixes: https://github.com/kubernetes/website/issues/38841

dra: update for Kubernetes 1.28

---

content/en/docs/concepts/storage/volumes.md

This PR fixes: #42127
This PR only fixes the typos in the issue defined.
- The description of "nodeExpandSecretRef" field does not start with a new line in the list.
https://kubernetes.io/docs/concepts/storage/volumes/#csi
- The double word "node".
For Linux worker nodes, containerized CSI node node plugins are typically deployed as privileged containers.
https://kubernetes.io/docs/concepts/storage/volumes/#windows-csi-proxy

Fixes typos in doc

---

content/en/docs/concepts/services-networking/network-policies.md

As the feature gate NamespaceDefaultLabelName is removed as per [feature-gates-removed](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/), we should update docs [targeting-a-namespace-by-its-name](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-namespace-by-its-name).

Remove "NamespaceDefaultLabelName" feature gate from the Network Policies page

---

content/pt-br/docs/tutorials/kubernetes-basics/explore/explore-intro.html

The app is listening on port 8080 so that must be included otherwise port 80 (default) is used and the curl request will fail.
Issue: 41259

[pt-br] Fixed "Show the app in the terminal" URL

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/reference/labels-annotations-taints/_index.md

In Kubernetes 1.27, we made tracking with finalizers always enabled, even for Jobs created before tracking with finalizers was enabled.
As part of this, we also removed the use of `bactch.kubernetes.io/job-tracking` as an annotation for the Job.
This was documented in the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2307-job-tracking-without-lingering-pods#deprecation
and in https://kubernetes.io/docs/reference/labels-annotations-taints/#batch-kubernetes-io-job-tracking

Mark Job tracking with finalizers as always enabled

---

content/en/docs/tutorials/services/pods-and-endpoint-termination-flow.md
content/en/examples/service/explore-graceful-termination-nginx.yaml

- Removed the duplicated ```service/pod-with-graceful-termination.yaml``` example from page https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/.
- Added ```service/explore-graceful-termination-nginx.yaml``` ```codenew``` shortcode to cover the Service example.
- Demonstrated ```kubectl apply``` command to deploy Pod and service.
closes #40224

removed duplicated examples

---

content/en/docs/concepts/workloads/pods/user-namespaces.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/tasks/configure-pod-container/user-namespaces.md

Commits 1-3 are ports of what we just merged in main, for 1.27. They improve the wording, fix a typo and use a timeless way for some sentences.
On top of that is the new commit that just removes mentiones to stateless pods, as we support all pods (stateful and stateless) now.

Doc update for userns in 1.28

---

content/en/docs/tutorials/services/pods-and-endpoint-termination-flow.md

Use a consistent style `{{% code file="*.yaml" %}}` to reference code blocks in such a close context.
The current is:
```
{{% code file="service/pod-with-graceful-termination.yaml" %}}
{{< codenew file="service/explore-graceful-termination-nginx.yaml" >}}
```

Use a consistent code reference in pods-and-endpoint-termination-flow

---

content/en/blog/_posts/2023-08-16-non-graceful-node-shutdown-to-ga.md

Update the publication date for a 1.28 feature blog for non graceful node shutdown from August 15 (scheduled 1.28 release date) to August 16 per [1.28 enhancements tracking sheet](https://github.com/orgs/kubernetes/projects/140/views/6)
/assign @bradmccoydev 
cc: @krol3 @mashby2022 @ramrodo @thschue

Update blog publish date for 1.28 feature blog for non graceful node shutdown to GA

---

hugo.toml

A new shortcode (added in PR https://github.com/kubernetes/website/pull/40692) looks up the correct patch version from data maintained by the release team.
/kind cleanup

Stop setting deprecated fullversion param

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

The August patch releases will be delayed until August 23rd, so this PR updates the calendar to reflect this
/assign @saschagrunert @cpanato @jeremyrickard @puerco @Verolop
cc https://github.com/orgs/kubernetes/teams/release-engineering

delay august patch releases

---

content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md

- Added a blank line between paragraphs
- Tweaked long lines
- Used a consistent text statement like `The output is similar to:` in context
- Used the same indentations from top to bottom on a single page
See [preview](https://deploy-preview-42479--kubernetes-io-main-staging.netlify.app/docs/tasks/inject-data-application/distribute-credentials-secure/) please.

Clean up distribute-credentials-secure.md

---

content/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure.md

Sync with en text and apply changes in en #42479.
```
content/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure.md
```
See [preview](https://deploy-preview-42478--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure/) please.

[zh] sync distribute-credentials-secure.md

---

content/en/docs/reference/labels-annotations-taints/_index.md

Fixes: https://github.com/kubernetes/website/issues/36830

docs: service.kubernetes.io/topology-aware-hints

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
content/en/docs/tasks/tools/install-kubectl-linux.md

This PR documents usage of the community-hosted repositories, implemented as part of [KEP-1731](https://github.com/kubernetes/enhancements/issues/1731).
All documents that mention the deprecated Google-hosted repository are updated to:
- Highlight that the Google-hosted repository is deprecated and that using the community-hosted repositories is strongly recommended
- Highlight the most important differences between the Google-hosted repository and the community-hosted repositories
- Show how to setup both the community-hosted repositories and the Google-hosted repository
I decided to go with `Google-hosted repository` and `Community-hosted repositories` for wording to distinct between repositories hosted on Google and our infra.
It's important to note that the infrastructure and …

Update package manager instructions with community-hosted repos

---

content/en/docs/concepts/workloads/controllers/job.md

Fixes the non-working link from the bottom of this section: https://deploy-preview-41165--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/job/#pod-failure-policy.
Alternative solution would be to fix the link to `#delayed-creation-of-replacement-pods`, but it feels beneficial to make the link independent from the title.
It is also needed for the links to work in https://github.com/kubernetes/website/pull/41924

Fix pod replacement policy link

---

content/zh-cn/docs/concepts/services-networking/ingress-controllers.md

- **EN upstream**: `content/en/docs/concepts/services-networking/ingress-controllers.md`
- **Sync to**: `content/zh-cn/docs/concepts/services-networking/ingress-controllers.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/services-networking/ingress-controllers.md
diff --git a/content/en/docs/concepts/services-networking/ingress-controllers.md b/content/en/docs/concepts/services-networking/ingress-controllers.md
index fc19265b39..2a5dcbd225 100644
--- a/content/en/docs/concepts/services-networking/ingress-controllers.md
+++ b/content/en/docs/concepts/services-networking/ingress-controllers.md
@@ -56,6 +56,7 @@ Kubernetes as a project supports and maintains [AWS](https://github.com/kubernet
* The [NGINX Ingress Controller for …
```

[zh] sync concepts/services-networking/ingress-controllers.md

---

static/_redirects

As per [comments](https://github.com/kubernetes/website/pull/42498#issuecomment-1674422605) in #42498, add a redirect link for the blog: [Consider All Microservices Vulnerable — And Monitor Their Behavior](https://kubernetes.io/blog/2023/01/20/security-behavior-analysis/).

add a redirect link for security behavior blog

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html

While working on the localization of tutorials intro pages, I noticed a few nits, such as consistent naming (i.e. _deployment_ vs. _Deployment_), "online terminal" mentions (while we don't have it anymore), missing internal links, and extra spaces. Fixing them in this PR.

Tiny fixes for deploy & scale tutorials

---

content/en/blog/_posts/2015-12-00-Creating-Raspberry-Pi-Cluster-Running.md
content/en/blog/_posts/2019-03-28-running-kubernetes-locally-on-linux-with-minikube.md

Replace all references to storage.googleapis.com/kubernetes-release with dl.k8s.io

---

OWNERS_ALIASES

I am interested in joining the English reviewers.
As an existing K8s org member for sometime, I have actively participated in reviewing, working, and engaging with incoming issues and pull requests in k/website repo. 
- [Reviewed PRs](https://github.com/kubernetes/website/pulls?q=is%3Aissue+involves%3Adipesh-rawat+label%3Alanguage%2Fen+) with `language/en` label: **200+** 
- The number of [issues engaged with](https://github.com/kubernetes/website/issues?q=is%3Aissue+involves%3Adipesh-rawat+): **150+**
- [sig-doc devstats contributions](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=SIG%20Docs&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All)
Search for PRs involving …

Add dipesh to en-localization reviewers

---

content/en/docs/concepts/workloads/pods/pod-qos.md

This PR fixes a small typo in `pod-qos-md`. The word "Pods" should be "Pod" in the following excerpt of the first paragraph (emphasis added):
> This page introduces Quality of Service (QoS) classes in Kubernetes, and explains how Kubernetes assigns a QoS class to each **Pods** as a consequence of the resource constraints that you specify for the containers in that Pod.

Update pod-qos.md to fix typo

---

content/en/blog/_posts/2023-08-14-sig-contribex-spotlight.md

Add SIG Contribex Spotligh blog article, written by @fykaa .
Initial review being done here https://github.com/kubernetes/contributor-site/pull/418 , will update the commit with the final version when done.

Add SIG ContribEx spotlight blog article

---

content/id/docs/tasks/manage-kubernetes-objects/kustomization.md

Kustomize has deprecated the use of bases in kustomization.yaml files. This PR updates all references to bases in the id docs to use the newer resources, which is https://github.com/kubernetes-sigs/kustomize/issues/2243.
Original English PR: https://github.com/kubernetes/website/pull/40761

docs: Update kustomize examples to use non-deprecated resources key (ID lang)

---

content/en/docs/concepts/containers/images.md

Beta
This reverts commit a0a473ba710d3251ce927792190c6746e764e2d0. The feature is not promoted to Beta.

Revert "promoted parallel image pulls", the feature is not promoted to

---

content/zh-cn/blog/_posts/2023-03-30-kubescape-validating-admission-policy-library.md

fixed: https://github.com/kubernetes/website/issues/42480
Translate Chinese version for blog：kubescape-validating-admission-policy-library.md
Preview：https://deploy-preview-42485--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/03/30/kubescape-validating-admission-policy-library/

[zh-cn] add kubescape-validating-admission-policy-library.md chinese version

---

content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md

This PR adds the announcement blog post for the Kubernetes community-owned package repositories (`pkgs.k8s.io`) as part of [KEP-1731](https://github.com/kubernetes/enhancements/issues/1731).
The blog post already went through the review process from SIG Release and SIG K8s Infra leads, as well as, from the 1.28 comms team (@ramrodo).
I scheduled it for 2023-08-15 as we want to announce the new package repositories along with 1.28.0 release. It's important to merge this at **[edit: just after]** the time of release because this blog post is referenced from docs introduced in #42022

Add "pkgs.k8s.io: Introducing Kubernetes community-owned package repositories" blog post

---

content/en/blog/_posts/2023-08-23-kubelet-podresources-api-ga.md

I'm intentionally covering multiple related enhancements with a single blog post.
Enhancements:
- https://github.com/kubernetes/enhancements/issues/606
- https://github.com/kubernetes/enhancements/issues/2403
- https://github.com/kubernetes/enhancements/issues/3743

Add post-release blog article about changes to Pod resources API

---

content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

This fixes the documentation to reflect 1.28 has the terminationGracePeriodSeconds for probes feature.
1.27 reverted the feature due to missing a PR, and 1.28 contains the feature.

change terminationGracePeriodSeconds for pods to 1.28

---

content/en/docs/reference/labels-annotations-taints/_index.md
content/en/docs/reference/using-api/api-concepts.md
content/en/docs/reference/using-api/server-side-apply.md

- ~Reorganize [Working with Kubernetes Objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/) section [[preview](https://deploy-preview-31261--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/working-with-objects/)]~
- ~move [Understanding Kubernetes Objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/) to be section overview~
- ~other tidying~
- ~Signpost readers to more pages about Kubernetes objects~ _Now part of PR #42117_
---
- Improve docs relating to patching [[preview](https://deploy-preview-31261--kubernetes-io-main-staging.netlify.app/docs/reference/using-api/api-concepts/#patch-and-apply)] and SSA [[preview](https://deploy-preview-31261--kubernetes-io-main-staging.netlify.app/docs/reference/using-api/se …

Improve documentation about Kubernetes objects & managing them

---

content/en/docs/tasks/tools/install-kubectl-linux.md
content/en/docs/tasks/tools/install-kubectl-macos.md
content/en/docs/tasks/tools/install-kubectl-windows.md

> **This is a Bug Report**
> 
> **Problem:**
> 
> * https://k8.io/docs/tasks/tools/install-kubectl-linux/
> * https://k8s.io/docs/tasks/tools/install-kubectl-macos/
> * https://k8s.io/docs/tasks/tools/install-kubectl-windows/
> 
> each tell readers about a warning message:
> 
> > The above command will generate a warning:
> > > **WARNING**: This version information is deprecated and will be replaced with the output from `kubectl version --short`.
> > 
> > 
> > You can ignore this warning. You are only checking the version of kubectl that you have installed.
> 
> However, `kubectl` from Kubernetes v1.28.0 doesn't show that warning.
> 
> **Proposed Solution:**
> 
> * Find the text “_This version information is deprecated and will be replaced with the output from_” in the website source.
> * …

“Install and Set Up kubectl…” tasks mention fixed bug

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md

This PR adds an undocumented detail about how kill execution sequence works in runtime manager for better understanding the _TERM_ order and relation between each container during Pod termination.
Proof: https://github.com/kubernetes/kubernetes/blob/fc8b5668f506b6d71ddc5243a21f5d0c5f8271d3/pkg/kubelet/kuberuntime/kuberuntime_container.go#L731-L747

Add detail about execution sequence for container kill order during Pod Termination

---

content/en/blog/_posts/2023-07-18-swap-beta1-graduation/index.md
content/en/blog/_posts/2023-08-24-swap-beta1-graduation.md

Add a blog-post about Swap graduating to Beta in Kubernetes 1.28.
For more info, see: https://github.com/kubernetes/enhancements/issues/4128

Swap graduates to Beta1: add a blog-post

---

content/en/blog/_posts/2023-08-15-kubernetes-1.28-blog.md

Update wording and broken release link. Once we get the correct link we will add this back.
Closes https://github.com/kubernetes/website/issues/42563#issuecomment-1679905162
cc @gracenng @divya-mohan0209

update release webinar link and wording

---

content/en/examples/application/deployment-sidecar.yaml
content/en/examples/application/job/job-sidecar.yaml

When I follow the [sidecar containers doc](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#api-for-sidecar-containers) to deploy a sidecar demo, the default example with wrong config(invaild spec and cannot start success).
- fix the startup command
- fix the `spec.volumes` in [deployment-sidecar.yaml]

Fix sidecar example in init-container doc

---

content/zh-cn/blog/_posts/2023-06-29-container-image-signature-verification/index.md

The Chinese version image exists but is not used.
page: https://kubernetes.io/zh-cn/blog/2023/06/29/container-image-signature-verification/
Related: https://github.com/kubernetes/website/pull/42055

[zh-cn] Use Chinese version image in blog container-image-signature-verification

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

This is the latest supported release, which is now also used by the new OBS packages.

Update CRICTL_VERSION to v1.28.0

---

content/en/blog/_posts/2023-08-15-kubernetes-1.28-blog.md

> However, since the tested/supported skew between nodes and control planes is currently limited to 2 versions, a 3-version upgrade would have to update nodes twice to stay within the supported skew.
This is misleading because readers might think “currently” means “on release day, after the release”. I think this was actually referring to the _status quo ante_, which readers might not realize.
/sig release
/sig architecture
/area blog

Fix misleading v1.28 release announcement

---

content/en/blog/_posts/2023-08-15-kubernetes-1.28-blog.md

After reading the release blog, our workgroup spotted 2 misunderstandings regarding the new feature:
1. sidecar container startup completion does not consider postStart handler
2. even in a pod with restartPolicy set to Never, a sidecar container restart when its startup fails
We understand point 2 comes from reading the proposal, but this is not how it is implemented today.
We suggest deleting the whole paragraph and get user feedback to see which is the best behavior before modifying the docs.

correct sidecar section of 1.28 release blog

---

content/zh-cn/blog/_posts/2023-08-16-non-graceful-node-shutdown-to-ga.md

The en filename is changed from `08-15` to `08-16`, so change the zh version accordingly.

[zh] Sync the blog filename of non-graceful-node-shutdown-GA

---

content/en/blog/_posts/2022-12-15-dynamic-resource-allocation-alpha/index.md

Fix some style and indentation issues.
```
content/en/blog/_posts/2022-12-15-dynamic-resource-allocation-alpha/index.md
```
Preview: https://deploy-preview-38882--kubernetes-io-main-staging.netlify.app/blog/2022/12/15/dynamic-resource-allocation/

Fix style and indentations in 12-15 blog

---

content/en/releases/_index.md
data/i18n/en/en.toml
layouts/docs/release-info.html

Resolves https://github.com/kubernetes/website/issues/29428
- Create a Hugo layout `release-info.html`, which will display the page's contents only if the value of `deprecated` in [hugo.toml](https://github.com/kubernetes/website/blob/main/hugo.toml#L149) is set to false.
- The new layout is assigned to a Markdown file by specifying the `layout` parameter in the Markdown front matter.
- Made small adjustment to the warning message text, displayed in yellow, for deprecation warnings, to ensure it is suitable  for documentation and releases.

Add Hugo layout to hide release information on outdated k8s.io versions

---

content/en/docs/setup/production-environment/tools/kops.md

**Fixed incorrect Link**
**Page link** : https://kubernetes.io/docs/setup/production-environment/tools/kops/#what-s-next
Updated incorrect link of Slack with proper Slack channel ID for Kops

Updated incorrect link for slack in kops

---

content/it/docs/concepts/cluster-administration/logging.md
content/it/docs/concepts/cluster-administration/manage-deployment.md

This is a continuation of PR https://github.com/kubernetes/website/pull/42180 (Replace {{< codenew ... >}} with {{% codenew ... %}})
Fixes https://github.com/kubernetes/website/issues/42179 (Copy To Clipboard breaks YAML format)

[it] replaced {{< codenew ... >}} with {{% codenew ... %}}

---

content/en/docs/tasks/administer-cluster/kubelet-config-file.md

Search in `./content/en/docs` and find:
- 1148 kubelet in 176 files
- 157 Kubelet in 56 files
In my opinion, `kubelet` is more commonly used. However, I would appreciate your review and confirmation on this matter. Thank you.

Replace Kubelet with kubelet in kubelet-config-file.md

---

content/en/docs/concepts/storage/persistent-volumes.md

This fixes #42176
**Here is what I did:**
I created two default storage classes. And applied the following manifest file for creating a PVC with no explicit 'storageClassName' attribute.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: pvc
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 3Gi
```
The PVC got bound with the newest storageclass(local-storage).
Here is a reference: kubernetes/kubernetes#110559
>Admission control plugin "DefaultStorageClass": If more than one StorageClass is designated as default (via the "storageclass.kubernetes.io/is-default-class" annotation), choose the newest one instead of throwing an error.

Fix storageclass pvc statement

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

These changes are a follow-up to https://github.com/kubernetes/website/pull/42001. They make minor edits to the documentation of the DevicePlugin API.

Make minor edits to Device Plugin documentation

---

content/zh-cn/docs/concepts/storage/persistent-volumes.md

Sync with recent en history: 1.28 release docs, #42513, #42177, #42514:
```
```
See [preview](https://deploy-preview-42561--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/persistent-volumes/) please.

[zh] sync persistent-volumes.md

---

content/zh-cn/docs/tasks/administer-cluster/kubelet-config-file.md

Sync with en:
```
```
The changes regarding `Kubelet` and `kubelet` mentioned in #42586 have been merged in en upstream.
See preview: https://deploy-preview-42585--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/kubelet-config-file/

[zh] sync kubelet-config-file.md

---

content/en/blog/_posts/2023-08-25-sidecar-kep.md

Add feature blog post for sidecar containers

---

content/en/docs/reference/command-line-tools-reference/kubelet.md

The reference generator wasn't able to generate reference for `kubelet` (for a long time now). This PR updates the reference manually, based on the output from `kubelet --help`.

Manually update kubelet reference

---

content/en/docs/reference/kubectl/cheatsheet.md

Adding  the `go-template` and `go-template-file` output formats to https://kubernetes.io/docs/reference/kubectl/cheatsheet/#formatting-output
Both output formats are supported in kubectl. See https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands.

Add the go-template output format in "kubectl Cheat Sheet" page

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md

Sync with 1.28 en:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md
```
See [preview](https://deploy-preview-42622--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/command-line-tools-reference/feature-gates/) please.

[zh] sync feature-gates.md

---

content/en/blog/_posts/2018-05-29-announcing-kustomize.md

from #42634
Fixed some oudated links in blog post: [Introducing kustomize; Template-free Configuration Customization for Kubernetes](https://kubernetes.io/blog/2018/05/29/introducing-kustomize-template-free-configuration-customization-for-kubernetes/)
Page updated: content/en/blog/_posts/2018-05-29-announcing-kustomize.md
---
The same changes will be applied to the Korean translation of this page, that I am translating right now.

[en] fix links for blog/_posts/2018-05-29-announcing-kustomize

---

content/zh-cn/blog/_posts/2023-08-18-retroactive-default-storage-class-ga.md

Fix #42595 
Add zh text to this new blog.
See preview: https://deploy-preview-42596--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/08/18/retroactive-default-storage-class-ga/

[zh] sync blog: retroactive-default-storage-class-ga.md

---

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md

```
content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
```

[zh] sync device-plugins.md and dynamic-resource-allocation.md

---

content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md

Sync with en:
```
```
See [preview](https://deploy-preview-42597--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers/) please.

[zh] sync extensible-admission-controllers.md

---

content/en/blog/_posts/2023-08-15-kubernetes-1.28-blog.md

The current date and link of the webinar is incorrect. The webinar [event](https://community.cncf.io/events/details/cncf-cncf-online-programs-presents-cncf-live-webinar-kubernetes-128-release/) has been created by the CNCF.

Update 1.28 webinar details

---

content/zh-cn/docs/concepts/architecture/nodes.md

Sync with en #42378, 42568, and 1.28 release doc:
```
```
See [preview](https://deploy-preview-42556--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/nodes/) please.

[zh] sync /concepts/architecture/nodes.md

---

content/zh-cn/docs/concepts/workloads/pods/init-containers.md
content/zh-cn/examples/application/deployment-sidecar.yaml
content/zh-cn/examples/application/job/job-sidecar.yaml

```
```
See [preview](https://deploy-preview-42575--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/init-containers/) please.

[zh] sync init-containers.md

---

content/en/docs/reference/labels-annotations-taints/_index.md

This PR adds the details for annotation apf.kubernetes.io/autoupdate-spec  in the page https://kubernetes.io/docs/reference/labels-annotations-taints/
fixes #42456

Update Well known labels, annotation and taints with annotation apf.kubernetes.io/autoupdate-spec

---

content/en/blog/_posts/2023-09-12-comparing-local-kubernetes-development-tools.md

As suggested by @sftim in another PR, this blog post offers a brief comparison between three prominent tools for local Kubernetes development: Telepresence, Gefyra, and mirrord (of which I am a maintainer). We think the methodology of connecting local apps to the Kubernetes cluster will become more prevalent in the future, and that an overview of some of the current tools could be helpful to readers of the blog.

Add blog article about local Kubernetes development tools

---

content/en/docs/concepts/architecture/nodes.md

Fixes Broken links in 'Node Status' section of 'Nodes' page
Links from https://kubernetes.io/docs/concepts/architecture/nodes/#node-status section are broken.
List of broken links
https://kubernetes.io/docs/concepts/node/node-status/#addresses
https://kubernetes.io/docs/concepts/node/node-status/#condition
https://kubernetes.io/docs/concepts/node/node-status/#capacity
https://kubernetes.io/docs/concepts/node/node-status/#info
https://kubernetes.io/docs/concepts/node/node-status
Issue : #42628

Fixes Broken links in 'Node Status' section of 'Nodes' page

---

content/en/blog/_posts/2023-08-15-kubernetes-1.28-blog.md

This feature has been [removed](https://github.com/kubernetes/enhancements/issues/2371#issuecomment-1641436551) from the release so this one fell through the crack :(

Remove "CRI container and pod statistics without cAdvisor" in release blog

---

content/en/docs/concepts/configuration/secret.md

The documentation should state that the secret type must be used, rather can be used, otherwise pull secrets don't recognize it and kubelet pulls images without credentials.

A secret type must be used for pull secret to work

---

content/en/docs/concepts/workloads/controllers/job.md

- Fix typos like `the the`
- Provide a consistent 2 spaces for unordered bullets

Clean up workload concept: job.md

---

content/en/docs/concepts/configuration/configmap.md

The maximum size limit of a ConfigMap is something that should be emphasized in the document to immediately catch the reader's attention. 
By highlighting this paragraph, users can quickly discern this information and decide whether to proceed with it or explore the other options mentioned in the same paragraph.

Highlighting an important point regarding ConfigMaps

---

content/en/releases/patch-releases.md
data/releases/eol.yaml
data/releases/schedule.yaml

This PR wraps a few updates into one PR:
* Drop 1.24 from the schedule.yaml as it is now EOL
* Update to reflect august patch releases
/assign @saschagrunert @cpanato @puerco @xmudrii 
cc https://github.com/orgs/kubernetes/teams/release-engineering

Remove 1.24 and update august patch releases

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Removed the repetitive word 'to' in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
This will fix https://github.com/kubernetes/website/issues/42708

Fix typo in installing kubeadm

---

content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

This MR changes docs to reflect the current status of gRPC probes.
Related to kubernetes/enhancements#2727

Update gRPC probes status to stable

---

content/zh-cn/docs/concepts/architecture/nodes.md

- **EN upstream**: `content/en/docs/concepts/architecture/nodes.md`
- **Sync to**: `content/zh-cn/docs/concepts/architecture/nodes.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/architecture/nodes.md
diff --git a/content/en/docs/concepts/architecture/nodes.md b/content/en/docs/concepts/architecture/nodes.md
index 512a787919..0a5d098d1e 100644
--- a/content/en/docs/concepts/architecture/nodes.md
+++ b/content/en/docs/concepts/architecture/nodes.md
@@ -164,10 +164,10 @@ that should run on the Node even if it is being drained of workload applications
A Node's status contains the following information:
-* [Addresses](/docs/concepts/node/node-status/#addresses)
-* [Conditions](/docs/concepts/node/node-status/#condition)
-* …
```

[zh] sync concepts/architecture/nodes.md

---

content/zh-cn/docs/concepts/workloads/pods/downward-api.md

- **EN upstream**: `content/en/docs/concepts/workloads/pods/downward-api.md`
- **Sync to**: `content/zh-cn/docs/concepts/workloads/pods/downward-api.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/workloads/pods/downward-api.md
diff --git a/content/en/docs/concepts/workloads/pods/downward-api.md b/content/en/docs/concepts/workloads/pods/downward-api.md
index 971475199c..e084c92abd 100644
--- a/content/en/docs/concepts/workloads/pods/downward-api.md
+++ b/content/en/docs/concepts/workloads/pods/downward-api.md
@@ -44,7 +44,7 @@ You can pass information from available Container-level fields using
-For most Pod-level fields, you can provide them to a container either as
+For some Pod-level fields, you can provide them to a …
```

[zh] sync concepts/workloads/pods/downward-api.md

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_reset-defaults.md

```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_reset-defaults.md
```
See [preview](https://deploy-preview-42742--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_reset-defaults/) please.

[zh] sync kubeadm_config_print_reset-defaults.md

---

content/en/docs/concepts/storage/volumes.md

The description about emptyDir sizeLimit in https://kubernetes.io/docs/concepts/storage/volumes/#emptydir page doesn't match the actual behavior and this PR modified the description in the document to match the actual behavior.
Fixes: https://github.com/kubernetes/website/issues/40723
/language en
/sig storage

Modified the description about emptyDir sizeLimit

---

content/zh-cn/docs/concepts/workloads/controllers/job.md
content/zh-cn/examples/controllers/job-backoff-limit-per-index-example.yaml

Sync with en:
```
```
See [preview](https://deploy-preview-42672--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/job/) please.

[zh] sync concepts: /controllers/job.md

---

content/en/docs/concepts/services-networking/ingress-controllers.md

- [https://docs.fortinet.com/document/fortiadc/7.0.0/fortiadc-ingress-controller-1-0/742835/fortiadc-ingress-controller-overview](https://docs.fortinet.com/document/fortiadc/7.0.0/fortiadc-ingress-controller-1-0/742835/fortiadc-ingress-controller-overview) returns 404 now.
- The new page is allocated in [https://docs.fortinet.com/document/fortiadc/7.0.0/fortiadc-ingress-controller/742835/fortiadc-ingress-controller-overview](https://docs.fortinet.com/document/fortiadc/7.0.0/fortiadc-ingress-controller/742835/fortiadc-ingress-controller-overview)
Thanks so much to @t-inu .
Actually t-inu さん found this bug.
**Related PR: [#42488](https://github.com/kubernetes/website/pull/42488)**
Changed pages list:
- [Ingress Controllers](https://deploy-preview-42749--kubernetes-io-main-staging.netlify.app …

fix: Wrong hyperlink of FortiADC Ingress Controller

---

content/en/blog/_posts/2023-08-29-Gateway-API-v080.md

This is intended to line up with the Gateway v0.8.0 release that's currently scheduled for Tuesday, August 29. I've mostly copied @kflynn's post from https://github.com/kubernetes-sigs/gateway-api/pull/2181, but have rearranged some things and added other non-mesh content, hopefully that makes sense, feedback is very appreciated.
/cc @kflynn @howardjohn @keithmattix @mikemorris @michaelbeaumont @shaneutt @youngnick @sftim 
/hold until release

Adding Gateway API v0.8.0 Blog Post

---

content/en/blog/_posts/2020-08-21-Moving-Forward-From-Beta/index.md

PR addresses the broken link within the "[Moving Forward From Beta](https://kubernetes.io//blog/2020/08/21/moving-forward-from-beta/)" blog post. Since the blog post is more than 1 year old, this PR could serve as companion to PR https://github.com/kubernetes/website/pull/42694, which focuses on eliminating the staleness warning from the same blog. 
The broken URL problem arose due to the relocation of the original content as part of commit https://github.com/kubernetes/enhancements/commit/353137c2716c4d56895974e198139e5e3bd2282d
**[Blog Deploy Preview](https://deploy-preview-42768--kubernetes-io-main-staging.netlify.app/blog/2020/08/21/moving-forward-from-beta/)**

Fix broken link in "Moving Forward From Beta" blog

---

content/en/docs/concepts/workloads/controllers/replicaset.md

This heading doesn't exist: <https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-and-dependents>
This one does: <https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents>

replicaset: fix ownerReferences link

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

Action items
https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/cmd/kubeadm/app/features/features.go#L45-L47
CoreDNS/ DynamicKubeletConfig/Auditing are feature gates before 2020 IIRC. I will not include them here.

kubeadm: update feature gates and add removed FGs

---

content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation.md
content/en/blog/_posts/2023-09-01-legacy-package-repository-deprecation.md

This PR adds a new blog post "Kubernetes Legacy Package Repositories Will Be Frozen On September 13, 2023" to describe the change that we announced today: https://groups.google.com/g/kubernetes-sig-release/c/akDpTHZsv_U/m/X2EPRFuVFQAJ
The blog post release date is set to tomorrow, September 1st, 2023. This is a tentative date, we are pending the confirmation, but given the short notice, it would be preferred to publish this post as soon as possible.
Huge thanks to everyone involved in writing this blog post, especially to @sftim for pushing everything forward on such a short notice.
/assign @sftim @jeremyrickard 

Add Kubernetes Legacy Package Repositories Will Be Frozen On September 13, 2023 blog post

---

content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation.md

Fixups for #42811 / https://blog.k8s.io/2023/08/31/legacy-package-repository-deprecation/
- bring it forward by half an hour
- wrap lines
- mark the blog article as _evergreen_ (it will never get marked as out of date)

Tweak legacy package repository deprecation article

---

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

- **EN upstream**: `content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md`
- **Sync to**: `content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
diff --git a/content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md b/content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
index c86bd3a224..3531587381 100644
--- a/content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
+++ b/content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
@@ -151,7 +151,7 @@ The general workflow of a …
```

[zh] sync compute-storage-net/device-plugins.md

---

static/_redirects

Add k8s.io/linuxrepos short link that redirects to the announcement for freezing legacy package repositories: https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/
We plan on sharing this link a lot, especially on social media, and short link would be much helpful. See the following Slack thread: https://kubernetes.slack.com/archives/C1J0BPD2M/p1693522696343469
Thanks a lot to @sftim for the idea and the `linuxrepos` name!
Note: I'm not sure if that's all or if any other change is required. Please let me know if there's anything else needed.
/assign @sftim @jeremyrickard 

Add k8s.io/linuxrepos short link

---

data/announcements/scheduled.yaml

This is a proposal to add a banner with the message that the legacy Google-hosted package repositories are now deprecated and will be frozen starting from September 13, 2023. The original announcement can be found here: https://k8s.io/linuxrepos
The banner is scheduled to go live from today until KubeCon NA 2023.
This change has **NOT** been discussed at all, so I'm putting this PR on hold until we don't reach consensus.
/hold
/assign @jeremyrickard

Add banner with message that legacy repos are getting frozen

---

content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md

Following up on https://kubernetes.slack.com/archives/CJH2GBF7Y/p1693578289482679?thread_ts=1693246673.041579&cid=CJH2GBF7Y
This PR updates the original pkgs.k8s.io announcement with the information that the legacy repositories are deprecated and that the legacy repositories will be frozen starting with September 13, 2023.

Update pkgs.k8s.io blog post with deprecation information

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md

Sync 4 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md
```

[zh] sync kubeadm_init_phase_control-plane files

---

content/en/releases/_index.md
layouts/docs/release-info.html

Addressing the comment feedback https://github.com/kubernetes/website/pull/41370#issuecomment-1702438756, this pull request updates the layout to improve navigation on outdated k8s.io/releases/ pages by adding links to subsections along with the deprecation notice.
- _Refer screenshot below on how the page will be rendered for deprecated version after these changes:_
/cc @sftim

Refine hugo layout for outdated k8s.io versions with subsection links

---

content/en/docs/concepts/security/pod-security-admission.md
content/en/docs/reference/instrumentation/metrics.md

The term “evaluation“ in the metrics section of the Pod Security Admission page is slightly misleading.
Change the “evaluation“ to “enforcement” in the text
#42853

Change text in Pod Security Admission metrics

---

content/es/blog/_posts/2023-08-29-Gateway-API-v080.md

Versión en español del anuncio de la versión v0.8.0 de Gateway API (https://github.com/kubernetes/website/pull/42727). 
Spanish version of the Gateway API v0.8.0 announcement.
Signed-off-by: Flynn <flynn@buoyant.io>

Gateway API 0.8.0... en español.

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

This change fixes a typo in the feature gate name `KubeletPodResourcesDynamiceResources`. 
Fixes #42842
Deploy Preview: [deploy-preview-42851-feature-gates](https://deploy-preview-42851--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/)

Fix KubeletPodResourcesDynamicResources feature gate name

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

The "KubeletPodResources" feature gate is GAed, but it's still mentioned as a switchable one in the [GetAllocatableResources gRPC endpoint](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-getallocatableresources) section. Perhaps it's time to remove it from the page.
related issue: https://github.com/kubernetes/website/issues/42841

Remove KubeletPodResources switchable feature gatemention

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md

This change fixes a typo in the feature gate name KubeletPodResourcesDynamiceResources.
en PR https://github.com/kubernetes/website/pull/42851/files

[zh] Fix KubeletPodResourcesDynamicResources feature gate name

---

content/en/releases/patch-releases.md

Back when @xmudrii added the [note about skipping November patch releases](https://github.com/kubernetes/website/pull/42108), the Google Build Admin team availability was part of the reason. As a result of the change explained in [Kubernetes Legacy Package Repositories Will Be Frozen On September 13, 2023](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/), I think that the Google Build Admin team availability will not factor into releases after September.
If correct, this clarifying edit removes that no-longer-relevant detail while preserving the main reason (the release team will have KubeCon as their focus at that time).

Rewording message to reflect build process changes

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

I'd like to add a reference to a project I created several years ago called https://github.com/squat/generic-device-plugin, which allows Kubernetes to discover and allocate generic Linux devices such as the FUSE device, serial devices, Linux video devices, sound cards, USB devices, etc. This project provides access to Linux devices that do not require special, vendor-specific setup logic. It is often used in conjunction with Iot deployments, e.g. to expose ZigBee devices to a home assistant Deployment.

device-plugins.md: add generic-device-plugin

---

data/releases/schedule.yaml

Unless a secret flux compensator was discovered in the CNCF basement, I think this was a simple typo :-)

Fix release date for 1.27 in schedule.yaml

---

content/en/docs/concepts/security/pod-security-admission.md
content/en/docs/reference/instrumentation/metrics.md
content/en/examples/validatingadmissionpolicy/basic-example-binding.yaml

The page about ValidatingAdmissionPolicy uses a mixture of API groups: now it will use only admissionregistration.k8s.io/v1beta1 to maintain consistency.
#42876

Fix mismatched API groups in ValidatingAdmissionPolicy page

---

content/en/docs/concepts/architecture/nodes.md

Change the Link under Swap memory management refers to the Blog [Kubernetes 1.28: NodeSwap graduates to Beta1](https://kubernetes.io/blog/2023/07/18/swap-beta1-1.28-2023/) to (https://kubernetes.io//blog/2023/08/24/swap-linux-beta/)
#42890

fix:Reference of Blog in Nodes

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver-etcd-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver-kubelet-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_controller-manager.conf.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-healthcheck-client.md

Provide a consistent style to these pages in the editing view:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver-etcd-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver-kubelet-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_controller-manager.conf.md
```
/kind cleanup

[zh] Clean up kubeadm_certs_renew files

---

content/ja/docs/tutorials/kubernetes-basics/_index.html
content/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
content/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
content/ja/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
content/ja/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/ja/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
content/ja/docs/tutorials/kubernetes-basics/explore/explore-intro.html
content/ja/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
content/ja/docs/tutorials/kubernetes-basics/expose/expose-intro.html
content/ja/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
content/ja/docs/tutorials/kubernetes-basics/scale/scale-intro.html
content/ja/docs/tutorials/kubernetes-basics/update/update-interactive.html
content/ja/docs/tutorials/kubernetes-basics/update/update-intro.html

[Japanese tutorials](https://kubernetes.io/ja/docs/tutorials/kubernetes-basics/) still include old CSS files. However, if you visit these pages, the browser will try to access them and return 404 ([e.g.](https://kubernetes.io/docs/tutorials/kubernetes-basics/public/css/styles.css)). They were removed from the English tutorials in #34188. This PR removes them from the Japanese localisation.
/sig docs
/language ja

[ja] Removing old CSS includes from K8s basics tutorials

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

This change fixes a typo in the feature gate name KubeletPodResourcesDynamicResources.

Fixed typo in feature gate name

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

Update the link to the proposal on the [Device Plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) page. Previously pointed to archived repository, now points to enhancements repo and the specific KEP

Remove link from Device Plugins page to KEP

---

content/en/docs/tasks/configure-pod-container/static-pod.md

In the document, we assume node name is `my-node1`, so the pod name should be `static-web-my-node1`. It would be more clear to readers.

Fix: static pod example pod name

---

content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md

https://k8s.io/blog/2023/08/15/pkgs-k8s-io-introduction/ revisions (fixups for #42830)
- tidying
- reinstate the existing heading fragment identifier
**Not urgent**

Tweak blog article about new Linux repos

---

content/en/docs/tasks/tools/install-kubectl-linux.md

- Changes to fix the current broken page layout at https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
- Possibly, resolves https://github.com/kubernetes/website/issues/42651
- [Original Page](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/) | [Deploy Preview](https://deploy-preview-42655--kubernetes-io-main-staging.netlify.app/docs/tasks/tools/install-kubectl-linux/)

Fix page layout of installing kubectl on linux

---

content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md

/sig node
I saw https://k8s.io/docs/concepts/scheduling-eviction/node-pressure-eviction/ and felt there was room to improve it.
[Preview](https://deploy-preview-42178--kubernetes-io-main-staging.netlify.app/docs/concepts/scheduling-eviction/node-pressure-eviction/) of updated page.

Revise node pressure eviction concept

---

content/en/docs/concepts/cluster-administration/manage-deployment.md
content/en/docs/concepts/configuration/overview.md
content/en/docs/concepts/overview/working-with-objects/labels.md
content/en/docs/tutorials/stateless-application/guestbook.md

The discussion about "managing labels effectively" and "updating labels" are currently difficult to find. They are supposed to be part of the labels concept page. This PR moves this two sections there and adjusts the links where they were pointed at.

Move labels discussion back to its concept page

---

content/en/docs/tasks/configure-pod-container/configure-service-account.md

There is a link has been provided for the word [automatically] and it redirects to the [object-management](https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/) page.
which is an irrelevant link removed it as a URL with a normal word.
#42912

Irrelevant Url link has been removed

---

content/zh-cn/docs/concepts/cluster-administration/manage-deployment.md
content/zh-cn/docs/concepts/overview/working-with-objects/labels.md

Follow en #42818 to relocate label sections:
```
content/zh-cn/docs/concepts/cluster-administration/manage-deployment.md
content/zh-cn/docs/concepts/overview/working-with-objects/labels.md
```

[zh] Sync manage-deployment.md and labels.md

---

content/zh-cn/docs/reference/kubectl/cheatsheet.md

- Remove some `。` to make the comments shorter though this action provides less assistance
- Replace Pods and Services with Pod and Service if it is a description
- 伸缩 -> 扩缩 for consistency with our [localization style guide](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/)

[zh] Clean up /kubectl/cheatsheet.md

---

content/en/docs/concepts/security/overview.md

The link to [OWASP Zed Attack proxy](https://owasp.org/www-project-zap/) in the code security section of https://kubernetes.io/docs/concepts/security/overview/ leads to a 404 error.
fixes #42874

fixes broken link to OWASP Zed Attack proxy

---

content/en/docs/setup/best-practices/certificates.md

`O=system:masters` doesn't required by `kube-apiserver-etcd-client` certificate, because etcd doesn't take it into account.
fixes https://github.com/kubernetes/kubeadm/issues/2926
fixes https://github.com/kubernetes/website/issues/42724

remove "O=system:masters" from "kube-apiserver-etcd-client".md

---

hugo.toml

Coordinated Universal Time feels like the right fit for a project, and website, with global reach. Use that, regardless of the OS settings where the website is built.
I'm going to
/hold
this PR to allow some room to discuss this - and for folks to point out snags I haven't thought of.

Build (and publish) website using UTC timezone

---

content/en/docs/reference/access-authn-authz/validating-admission-policy.md
content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Hi there,
I'm proposing some changes that include adding a link to the [CEL Playground](https://playcel.undistro.io) in the following sections:
- https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
As discussed in [this GitHub issue](https://github.com/kubernetes/website/issues/41788), CEL Playground allows users to easily test expressions from their browsers and also provides some helpful examples.
Additionally, it's worth noting that all [Kubernetes CEL libraries](https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries) are available in the playground.
Feel free to join us in improving the CEL Playground. Your contributions are welcome! …

Add CEL Playground link

---

content/zh-cn/blog/_posts/2023-08-29-Gateway-API-v080.md

The `---` on the top line of [Gateway API v0.8.0](https://kubernetes.io/zh-cn/blog/2023/08/29/gateway-api-v080/) is missing now.
```
content/zh-cn/blog/_posts/2023-08-29-Gateway-API-v080.md
```

[zh] fix blog title of 2023-08-29-Gateway-API-v080

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_ca.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-ca.md

Update 5 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_ca.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-ca.md
```

[zh] Clean up kubeadm_init_phase_certs files

---

content/en/docs/reference/using-api/client-libraries.md

Added [`kr8s`](https://github.com/kr8s-org/kr8s) to the community Python libraries list. The list looked to be alphabetical so I tried to insert it at the right position, but let me know if the order should be different.

Add kr8s to community Python libraries list

---

content/en/docs/reference/config-api/apiserver-audit.v1.md
content/en/docs/reference/config-api/apiserver-encryption.v1.md
content/en/docs/reference/config-api/kubelet-config.v1.md
content/en/docs/reference/config-api/kubelet-config.v1beta1.md
content/en/docs/reference/config-api/kubelet-credentialprovider.v1.md
content/en/docs/reference/config-api/kubelet-credentialprovider.v1alpha1.md
content/en/docs/reference/config-api/kubelet-credentialprovider.v1beta1.md

The upstream source comments are not quite strict at using `*`s, `<`s or `>`s. These characters, when not enclosed in backtiqs, are interpreted as Markdown emphasize markers or HTML tags. Hacking the generator code is not the right solution. We should attempt to fix them in the source code instead.
Before that, let's keep fixing the generated outputs manually.

Fix stars in the generated configuration APIs

---

content/en/docs/tasks/administer-cluster/reserve-compute-resources.md

Fixes #43027.
One of the [KubeletConfiguration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) parameters, `reservedSystemCPUs`, is incorrectly listed as `reservedSystemCpus` in the page below. 
https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#explicitly-reserved-cpu-list
This PR fixes parameter name.

Fix incorrect parameter name

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-peer.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-server.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_front-proxy-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_scheduler.conf.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_completion.md

Update 6 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-peer.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_etcd-server.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_front-proxy-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_scheduler.conf.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_completion.md
```

[zh] Clean up kubeadm_certs files

---

content/en/docs/concepts/storage/volumes.md

Update link in [volumes](https://kubernetes.io/docs/concepts/storage/volumes/) page under **portworx-csi-migration** of Portworx with CSI

Updated link referring to Portworx CSI Drivers

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/tasks/job/job-with-pod-to-pod-communication.md

There was an old mention that the Job API was not suitable for scientific computing.
We have made a lot progress towards that end, starting with Indexed Jobs, so the note was inaccurate.
Also moved the item "Job Template Expansion" last, as it usefulness is limited
/sig apps
/wg batch

Update Job as suitable for scientific computing

---

content/en/docs/concepts/overview/working-with-objects/field-selectors.md

Adding an explicit note for lack of support for set based operators for field selectors 
Article link: https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/
https://github.com/kubernetes/kubernetes/issues/32946

Update field-selectors.md with info about set based requirements

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/using-api/api-concepts.md

Ref https://github.com/kubernetes/enhancements/issues/365
/milestone 1.29

Graduate APIListChunking to GA documentation

---

content/en/docs/concepts/workloads/pods/init-containers.md

Init-containers describes how resource requests and limits for an init container are handled differently, but the section it referenced to did no longer exist.
Looking through the page I edited the link to what I believe is the correct section of the page.

Fix: broken link in init-containers.md

---

content/en/blog/_posts/2023-07-06-confidential-kubernetes.md

Removed Link of [Encrypted State](https://www.amd.com/system/files/TechDocs/Protecting%20VM%20Register%20State%20with%20SEV-ES.pdf) from AMD SEV as the LINK is referring to 404 Page. also, there is an error 404 from the official AMD website for SEV-ES

Remove Link Of AMD for SEV_ES

---

README.md

**Fixes issue -** #42979 
**Made the required changes in README.md file .**
1. Updated `Localization ReadMes` to `Localization READMEs`.

Enhancement By: Renaming 'ReadMes' to 'README' for Improved Clarity.

---

content/en/docs/concepts/storage/ephemeral-volumes.md
content/en/docs/concepts/storage/persistent-volumes.md

This PR fixes the references of [`Types of Persistent Volumes`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes) section in [`Persistent Volumes`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) page. 
Fixes #42868

Remove hyperlinks for obsolete PersistentVolume types

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

xref https://github.com/kubernetes/kubeadm/issues/2563#issuecomment-1696074991

update swap related description before installation

---

content/en/docs/tutorials/hello-minikube.md

One of the objectives stated at the beginning of the tutorial is to "View application logs", added in this pr
https://kubernetes.io/docs/tutorials/hello-minikube/
#42984

fix:"Hello Minikube" tutorial objective discrepancy: 'View Application Logs' mentioned but not covered .

---

content/en/blog/_posts/2023-08-24-swap-beta1-graduation.md

Fix broken doc link in Swap blog

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

There's still a lingering misconception that "beta" implies "enabled", the documentation should better not perpetuate that: the feature gate usually gets changed to "enabled", but there are exceptions. API groups are intentionally left as disabled.
/cc @bart0sh

feature gates: clarify beta enabling state

---

content/en/releases/_index.md
data/i18n/en/en.toml
layouts/docs/release-info.html

Addressing issue #42812
Copied layouts/docs/release-info.html from main branch to update release-1.27 docs
Initial PR to add the layout: #41370
PR to refine the layout: #42835

Backport "layouts/docs/release-info.html" to release-1.27

---

content/en/docs/concepts/services-networking/service.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

This PR promotes [KEP-3668: ServiceNodePortStaticSubrange](https://github.com/kubernetes/enhancements/issues/3668) to stable

KEP-3668: promote ServiceNodePortStaticSubrange to stable

---

content/en/docs/concepts/storage/volumes.md

with the "configmap-pod" yaml,the container "test"fail to run with reason of "CrashLoopBackOff".  
I suggest adding  a command.

fix: configmap-pod CrashLoopBackOff

---

content/en/docs/concepts/cluster-administration/flow-control.md

Fix a broken link that I introduced in https://github.com/kubernetes/website/pull/42075.

Fix broken link in "API Priority and Fairness" page

---

content/en/docs/concepts/workloads/controllers/replicaset.md

The value of `controller.kubernetes.io/pod-deletion-cost` is of type int32 and should be in the range [-2147483648, 2147483647].

update the range of pod-deletion-cost

---

content/en/blog/_posts/2020-08-21-Moving-Forward-From-Beta/index.md

This [article](https://kubernetes.io/blog/2020/08/21/moving-forward-from-beta/) is written to be true even after future releases have happened, and should need minimal maintenance.
Let's suppress the staleness warning.

Mark “Moving Forward From Beta” evergreen

---

static/css/style_apiref.css
static/js/scroll-apiref.js

This is the sister PR to https://github.com/kubernetes-sigs/reference-docs/pull/334 -- the generated API docs will soon use the DOM exclusively for its navigation, making the navData.js redundant. To that end, the `scroll-apiref.js` had to be rewritten entirely.

Improve scrolling in API ref docs

---

content/ja/docs/concepts/architecture/cri.md

- **EN upstream**: `content/en/docs/concepts/architecture/cri.md`
- **Sync to**: `content/ja/docs/concepts/architecture/cri.md`
```diff
$ scripts/lsync.sh content/ja/docs/concepts/architecture/cri.md
diff --git a/content/en/docs/concepts/architecture/cri.md b/content/en/docs/concepts/architecture/cri.md
index 2b8fe79a5b..055df28b4f 100644
--- a/content/en/docs/concepts/architecture/cri.md
+++ b/content/en/docs/concepts/architecture/cri.md
@@ -26,8 +26,7 @@ each Node in your cluster, so that the
The kubelet acts as a client when connecting to the container runtime via gRPC.
The runtime and image service endpoints have to be available in the container
runtime, which can be configured separately within the kubelet by using the …
```

[ja] sync architecture/cri.md

---

content/en/docs/concepts/overview/working-with-objects/annotations.md

Added relevant links in 'What Section' of Annotations page.
Fixes #43086

Add links to What's next section of Annotations page

---

content/en/docs/tasks/administer-cluster/decrypt-data.md
content/en/docs/tasks/administer-cluster/encrypt-data.md

Split out from #33285
Add a new page about decrypting an API once you've already set up Kubernetes to encrypt it.
/sig security
/sig auth

Split at-rest decryption into its own page

---

content/en/docs/concepts/security/hardening-guide/authentication-mechanisms.md

This is the first section for the Kubernetes hardening guide which has been under discussion in SIG-Security-Docs https://github.com/kubernetes/sig-security/issues/30 .

Kubernetes Hardening Guide Section on Authentication Mechanisms

---

content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md

The information provided about Alpine DNS "issue" is not only misleading but completely wrong!
Thanks.

Replace misleading info about Alpine and DNS lookups

---

content/en/docs/reference/_index.md
content/en/docs/reference/external-api/_index.md
content/en/docs/reference/external-api/custom-metrics.v1beta2.md
content/en/docs/reference/external-api/external-metrics.v1beta1.md
content/en/docs/reference/external-api/metrics.v1beta1.md
content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

The 'metrics.k8s.io' APIs are exposed by the 'metrics-server' component to facilitate auto-scaling. The other two APIs are for fetching metrics from custom or external sources respectively.

Add generated references for metric APIs

---

content/en/examples/admin/resource/limit-range-pod-3.yaml
content/en/examples/pods/share-process-namespace.yaml
content/en/examples/pods/storage/projected-secret-downwardapi-configmap.yaml
content/en/examples/pods/storage/projected-secrets-nondefault-permission-mode.yaml
content/en/examples/pods/storage/projected-service-account-token.yaml

Some example scripts have `busybox:1.28` as their image, but no `command` or `arg` values were declared in them that will keep the container alive. Because of which if someone copies the code and try to run it, the pod it will create will complete/crash continuously creating `CrashLoopBackoff` state.

Added 'command' block for some busybox pod's scripts

---

content/en/docs/tasks/tools/install-kubectl-macos.md
content/zh-cn/docs/tasks/tools/install-kubectl-macos.md

This fixes the instructions for finding the location of the `kubectl` binary.

Use correct `which` command instead of non-existent `where`

---

content/zh-cn/docs/reference/external-api/_index.md
content/zh-cn/docs/reference/external-api/external-metrics.v1beta1.md

Add zh text to 2 new pages:
```
content/zh-cn/docs/reference/external-api/_index.md
content/zh-cn/docs/reference/external-api/external-metrics.v1beta1.md
```
See [preview](https://deploy-preview-43107--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/external-api/external-metrics.v1beta1/) please.

[zh] Sync /reference/external-api/

---

content/en/docs/tasks/tools/install-kubectl-linux.md

In the kubectl install documentation, the link to download kubectl is correct but the link to download the checksum (sha256) is missing `/release/` as path prefix.

Fix sha256 url missing '/release/' to download kubectl

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

This PR fixes the typing error in `Extend the Kubernetes API with CustomResourceDefinitions`. 
Fixes #43121  and #43122

Fixed the typo error in Extend the Kubernetes API with CustomResourceDefinitions

---

content/en/docs/tasks/debug/debug-application/get-shell-running-container.md

Updated deprecated command to `kubectl exec [POD] -- [COMMAND]`

fix: update deprecated command in code example

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md

Link from https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/ to the authz page section that first mentions RBAC.

Link from kubeadm mention of RBAC to authz docs

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md

Fix a 404 link to the rbac page.

Fix a link in kubeadm-certs

---

static/css/style_apiref.css
static/js/README.md
static/js/apiref.js

This PR includes the necessary CSS/JS code to make the dark mode for the API docs work. This is the sister PR to https://github.com/kubernetes-sigs/reference-docs/pull/337 and https://github.com/kubernetes-sigs/reference-docs/pull/338
The dark mode would look like this, using default Bootstrap colors:
/hold
This should only be merged if and when the sister PR is merged.
I also adjusted the font and some colors to better match the Kubernetes website (at least in light mode).

Add optional dark mode to API docs

---

content/de/docs/concepts/workloads/pods/_index.md

correted Typo in German Docs about Networking of Pods

[de] Fix typo in "Pods" page

---

content/en/docs/concepts/configuration/secret.md

This PR cleans up the "Types of Secrets" sections in the Secrets concept docs, as follows:
- Clean up Secret and ServiceAccount capitalization and change a URL
- Clean up the big note about TokenRequest to reduce cognitive load of a large callout. Instead:
- Call it a legacy mechanism for long-lived credentials
- Rework note content with a bullet list
- Make the note callout apply to when you should use a SA token Secret
- Improve link accessibility by separating them from inline links where it makes sense
- Clean up the ddocker config Secrets section:
- Move the paragraphs into the bullets and cut down on the content length, no major changes to the actual wording
- Update the step wording to stop it reading like a continuous sentence from step to output
- All authn …

Secret types cleanup

---

content/en/docs/reference/glossary/cloud-controller-manager.md
content/en/docs/reference/glossary/kubelet.md

cloud-controller-manager and kubelet glossary files has been updated with corresponding links
Issue: https://github.com/kubernetes/website/issues/40820

add link for kubelet and cloud-controller-manager

---

content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html

This seems to be a common issue when Docker is the container runtime. A note will be very helpful for beginners.

Update expose-intro.html to add notes for minikube tunnelling with Docker

---

content/en/blog/_posts/2023-09-25-kubeadm-use-etcd-learner-mode.md

@neolit123 @SataQiu 
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/3614-etcd-learner-mode
- xref https://github.com/kubernetes/kubernetes/pull/120228

add a new blog for etcd learner mode usage in kubeadm join

---

content/en/docs/reference/kubectl/cheatsheet.md

Description:
Added kubectl completion for fish shell
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration

Added kubectl completion command for fish shell in kubect cheatsheet docmentation

---

content/zh-cn/blog/_posts/2023-09-25-kubeadm-use-etcd-learner-mode.md

```
content/zh-cn/blog/_posts/2023-09-25-kubeadm-use-etcd-learner-mode.md
```
See [preview](https://deploy-preview-43188--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/09/25/kubeadm-use-etcd-learner-mode/) here.

[zh] Sync 2023-09-25-kubeadm-use-etcd-learner-mode.md

---

content/en/docs/concepts/services-networking/dual-stack.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

KEP-3705 CloudDualStackNodeIPs is beta in 1.29

update CloudDualStackNodeIPs to beta

---

static/docs/reference/generated/kubectl/kubectl-commands.html

`kubectl create clusterip NAME` &
`kubectl create externalname NAME --external-name external.name [--dry-run=server|client|none]`
This command is missing "service". 
Correct command must be:
`kubectl create service externalname NAME --external-name external.name [--dry-run=server|client|none]` &
`kubectl create service clusterip NAME [--tcp=<port>:<targetPort>] [--dry-run=server|client|none]`

fix(docs): missing "service" command name

---

content/en/docs/tasks/administer-cluster/cluster-upgrade.md

The Kubernetes docs [state](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) that minor upgrades of kubelet require draining the node:
> If you are performing a minor version upgrade for any kubelet, you must first drain the node (or nodes) that you are upgrading.
It’s also been [stated](https://github.com/kubernetes/kubernetes/issues/63814#issuecomment-760450426), but not in documentation that patch upgrades don’t require draining the node:
> in place minor version kubelet upgrades are not supported without draining. I think in place patch version upgrades are.
My contention is that currently in-place patch upgrades of kubelet are unsafe and we should clarify the K8s documentation to explicitly state that you must drain the node in all circumstances when …

recommend draining the node before updating kubelet

---

static/docs/reference/generated/kubectl/kubectl-commands.html

- `kubectl create loadbalancer NAME [--tcp=port:targetPort] [--dry-run=server|client|none]`
- `kubectl create nodeport NAME [--tcp=port:targetPort] [--dry-run=server|client|none]`
This command is missing "service". 
Correct command must be:
- `kubectl create service loadbalancer NAME [--tcp=port:targetPort] [--dry-run=server|client|none]`
- `kubectl create service nodeport NAME [--tcp=port:targetPort] [--dry-run=server|client|none]`

fix(doc): add "service" command name for lb and np

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
layouts/partials/head.html
layouts/shortcodes/table.html
static/js/sortable-table.js

Based on the feature request https://github.com/kubernetes/website/pull/41793#issuecomment-1637215677 implemented a shortcode `sortable-table` to sort the table content by a clicking on the column name.
_Addresses #42102_
**[Preview Page](https://deploy-preview-42412--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features)**

Add sortable option to table shortcode

---

content/en/docs/contribute/localization.md

Updated link text terminology to 'Localizing' instead of 'Translating' on docs home page
Fixes https://github.com/kubernetes/website/issues/43148

Update link text to "Localizing" 

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md

Changed the kubelet-config file name from `/var/lib/kubelet/config.conf` to `/var/lib/kubelet/config.yaml`
This will fix https://github.com/kubernetes/website/issues/43213

Fix kubelet-config file name

---

content/en/docs/concepts/workloads/controllers/statefulset.md

Usage of **Gib** (Gibibit) was used where **GiB** (Gibibyte) was intended.

Fix incorrect letter casing for data storage units

---

content/en/docs/tasks/administer-cluster/kubelet-credential-provider.md

This will fix #43237
Problem shown below

Remove redundant text from "Administer a Cluster" page

---

content/en/docs/reference/labels-annotations-taints/_index.md

This PR tries to complete the description of the annotation `alpha.kubernetes.io/provided-node-ip` https://kubernetes.io/docs/reference/labels-annotations-taints/#alpha-kubernetes-io-provided-node-ip
It currently states `IPv4 address`. However, it could also be an IPv6 address. Probably this description was written before dual-stack or IPv6 was supported in Kubernetes and was never updated when those got supported.

Include IPv6 as an option for provided-node-ip annotation

---

layouts/shortcodes/blocks/case-studies.html

In the section featuring quotes from case studies on the home page, remove the "Case-studies" link from the bottom of the section. Instead, hyperlink the headline above the quotes to the case study tab. This change enhances the user experience and eliminates redundancy.
#43065

Remove Case-studies Link and Hyperlink from the bottom of the page

---

OWNERS_ALIASES

(Part of https://github.com/kubernetes/steering/issues/273.)
Add:
Maciej Szulik - @soltysh
Paco Xu 徐俊杰 - @pacoxu
Patrick Ohly - @pohly
Remove:
Carlos Tadeu Panato Jr. - @cpanato
Christoph Blecker - @cblecker
Tim Pepper - @tpepper
/assign @mrbobbytables @BenTheElder @palnabarun
cc: https://github.com/orgs/kubernetes/teams/steering-committee

Update Steering members following 2023 election cycle

---

content/en/docs/reference/using-api/server-side-apply.md

**Description** In the Server-Side Apply docs there is a small spelling error 
```
It is strongly recommended for controllers to always force conflicts on objects that
the own and manage, since they might not be able to resolve or act on these conflicts.
```
Should be `...that they own and manage...`
[Link to error in site - Server Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/#using-server-side-apply-in-a-controller)
[Link to error in code](https://github.com/kubernetes/website/blob/b90ff432446aea88e57de36ca86810755f375f38/content/en/docs/reference/using-api/server-side-apply.md?plain=1#L397)

Address spelling error around own and manage in SSA Docs

---

content/en/docs/concepts/cluster-administration/networking.md

This PR modifies the "what's next" section of the networking concept page. The pointer to the **archived** design proposals is only about the original design and it was archived two years ago. For people interested on "future plans", they should be redirected to the KEPs for SIG-Network.
This PR also fixes the line wrapping problems in two paragraphs (no content changes there).

Cleanup the networking concepts page

---

content/en/docs/concepts/overview/working-with-objects/annotations.md
content/zh-cn/docs/concepts/overview/working-with-objects/annotations.md

This Pull Request resolved the issue mentioned in #42524. I have added explanation and it makes clear that both labels and annotations can be used together.

Improved Explanation of Labels and Annotations

---

content/en/blog/_posts/2023-10-10-cri-o-community-package-infrastructure.md

Adding a blog post about CRI-O's packaging efforts.
PTAL @haircommander @xmudrii 
~The publishing date is just a placeholder for now, means:~
~/hold~
[Deploy preview](https://deploy-preview-43128--kubernetes-io-main-staging.netlify.app/blog/2023/10/10/cri-o-community-package-infrastructure/)

Add blog post about CRI-O's latest packaging efforts

---

content/en/docs/tutorials/_index.md

_issue : unnecessary spaces present between the lines._
**ISSUE DETAILS**
There is unnecessary spaces present between the lines in the section : **Basics, Configuration, Stateless Applications ,Stateful Applications**
_To see the issue go to this link_ "https://kubernetes.io/docs/tutorials/"
**WHY IT NEEDS TO BE CHANGED?**
To maintain uniformity of documentation writing style. So to maintain this uniformity i have removed the extra spaces. You can see these links and screenshots provided below , how the sections are maintained in other pages : 
_Visit this link and go to section **What's next**_ : https://kubernetes.io/docs/setup/
_Visit this link and go to section **Services , Security**_: https://kubernetes.io/docs/tutorials/

Remove some vertical space between lines of text

---

content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md

The etcd operation and maintenance job is not supposed to run on the playground environments.
closes: #4479

Revise etcd task prerequisites to remove playground envs

---

content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md

Fix typo in new package repos introduction blog:
```
content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md
```

Fix typo in new package repos introduction blog

---

OWNERS_ALIASES

Open this PR after kubernetes/org#4465
It is truly an honor for me to be listed in the en-reviews. I greatly appreciate that Kubernetes has provided a fantastic team ladder, enabling my continuous growth. I am committed to doing my best to ensure the healthy growth of our website as a knowledge base of cloud native.
A special thanks to @sftim, @tengqm, @dipesh-rawat, and @mengjiao-liu for your contribution efforts and support.

Add windsonsea to sig-docs-en-reviews

---

content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/en/examples/pods/probe/tcp-liveness-readiness.yaml

Fixes #43259
if `periodSeconds` > `initialDelaySeconds` then the `initialDelaySeconds` would be ignored. Tested on kubernetes 1.27
Deployment preview:
https://deploy-preview-43289--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
https://deploy-preview-43289--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe

Fix initialDelaySeconds docs

---

content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md
content/en/blog/_posts/2023-10-02-steering-committee-results-2023.md

Adding a link to the correct canonical location for the blog post that went out yesterday, per @sftim as explained in https://github.com/kubernetes/website/pull/43294#issuecomment-1744076802.
Also, while I was checking on how the canonical URLs worked, I noticed a typo in the canonical URL for blog post from this summer, which I'm correcting.
Please merge after https://github.com/kubernetes/contributor-site/pull/442 is merged and the updated site is available.

Adding and correcting canonical URLs

---

content/zh-cn/docs/reference/kubernetes-api/common-definitions/_index.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/delete-options.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/label-selector.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/list-meta.md

Updated 4 files:
```
content/zh-cn/docs/reference/kubernetes-api/common-definitions/_index.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/delete-options.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/label-selector.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/list-meta.md
```

[zh] Clean up /kubernetes-api/common-definitions files

---

assets/scss/_custom.scss
layouts/partials/docs/docs-portal-card.html

Closes #23914
This PR is an extension of #43164 to cover the styling changes and make some additional markup changes
Please have a look at the [Deploy Preview](https://deploy-preview-43166--kubernetes-io-main-staging.netlify.app/docs/home/) for a better perspective of the PR

Changes to make the docs homepage cards look consistent

---

content/fr/docs/concepts/workloads/controllers/statefulset.md

**Gib** (Gibibit) was used where **GiB** (Gibibyte) is intended.
- #43238
- #43319
- #43321
- #43322
- #43323
- #43324

content: fr: Fix incorrect letter case for data storage units

---

content/en/docs/tutorials/security/cluster-level-pss.md

I have found the word 'kind' is written like 'KinD'.So i have changed all the letters in 'KinD' to lowercase.
**ISSUE DETAILS**
_To see this issue go to these links:_
https://kubernetes.io/docs/tutorials/security/cluster-level-pss/#before-you-begin
https://kubernetes.io/docs/tutorials/security/cluster-level-pss/#set-modes-versions-and-standards and go to Note section that is under the step number 4
Here in the above issue i have changed the letters into lowercase and converted to italic for easy readability.
**WHY I HAVE CHANGED IT?**
In some other section of documentation i found out that 'kind' is written in lowercase. You can see these screenshots and links below:
https://kubernetes.io/docs/tasks/tools/#kind

Ensure all letters in kind are in lowercase

---

content/en/docs/tasks/configmap-secret/managing-secret-using-kustomize.md

fixes error: file contents should not be base64 encoded
clarifies: full filenames are used for the secret's keys
```bash
❯ cat username.txt
test=abc
❯ cat kustomization.yaml
secretGenerator:
- name: db-user-pass
files:
- username.txt
❯ kustomize build
apiVersion: v1
data:
username.txt: dGVzdD1hYmMK
kind: Secret
metadata:
name: db-user-pass-429b77m65b
type: Opaque
```

Fix & Clarify files secretGenerator

---

content/zh-cn/docs/reference/using-api/deprecation-guide.md

fix bug: in content/zh-cn/docs/reference/using-api/deprecation-guide.md,CustomResourceDefinition version is ```apiextensions.k8s.io/v1```,not ```apiextensions/v1```.

fix CustomResourceDefinition version is 'apiextensions.k8s.io/v1'

---

content/en/docs/reference/config-api/apiserver-admission.v1.md
content/en/docs/reference/config-api/apiserver-audit.v1.md
content/en/docs/reference/config-api/apiserver-config.v1.md
content/en/docs/reference/config-api/apiserver-config.v1alpha1.md
content/en/docs/reference/config-api/apiserver-config.v1beta1.md
content/en/docs/reference/config-api/apiserver-encryption.v1.md
content/en/docs/reference/config-api/apiserver-eventratelimit.v1alpha1.md
content/en/docs/reference/config-api/apiserver-webhookadmission.v1.md
content/en/docs/reference/config-api/client-authentication.v1.md
content/en/docs/reference/config-api/client-authentication.v1beta1.md
content/en/docs/reference/config-api/imagepolicy.v1alpha1.md
content/en/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
content/en/docs/reference/config-api/kube-proxy-config.v1alpha1.md
content/en/docs/reference/config-api/kube-scheduler-config.v1.md
content/en/docs/reference/config-api/kube-scheduler-config.v1beta3.md
content/en/docs/reference/config-api/kubeadm-config.v1beta3.md
content/en/docs/reference/config-api/kubeadm-config.v1beta4.md
content/en/docs/reference/config-api/kubeconfig.v1.md
content/en/docs/reference/config-api/kubelet-config.v1.md
content/en/docs/reference/config-api/kubelet-config.v1alpha1.md
content/en/docs/reference/config-api/kubelet-config.v1beta1.md
content/en/docs/reference/config-api/kubelet-credentialprovider.v1.md
content/en/docs/reference/config-api/kubelet-credentialprovider.v1alpha1.md
content/en/docs/reference/config-api/kubelet-credentialprovider.v1beta1.md

This PR updates the config API reference using updated generator.
The updated generator fixed several things:
- It makes sure there is a deterministic order for packages and types in a API reference page. This has been a problem before, some diffs were caused by non-deterministic order in the types. And that problem has been a pain point for downstream localization teams.
- It allows manually specify the main package name so that the generator won't get confused when multiple API packages are involved in a traveral.
- It fixes the logic for filtering resource types.
closes: #43229

Update config API reference

---

content/en/docs/concepts/services-networking/ingress.md

This PR fixed the hyperlink for `spec`, `flag`, and `recommended` under [The Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource) in the [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)  docs.
Fixes #43105

Fix hyperlinks in Ingress concept

---

assets/scss/_case-studies.scss

Fix the background color of the footer case study page mismatched with the original footer color of the K8 website.
#43020

fix:Mismatch of footer colour at Case-Study pages

---

layouts/case-studies/single.html
layouts/shortcodes/case-studies/quote.html
static/css/new-case-studies.css

**Description:**
In page case study some images were not covering whole section of the body:
**What this PR do ?**
fixes #43019
Fixed the issue

Fix banner image scaling on Case Studies pages

---

hugo.toml

This PR aims to close #36937 and any other related issues which are already closed due to inactivity
I've modified hugo.toml to include a path for the i18n dir. This enables hugo to build the website on windows without explicitly building the symbolic links for it

Local Preview of Website now works normally on windows

---

layouts/shortcodes/blocks/case-studies.html
layouts/shortcodes/blocks/feature.html

Lots of the images on the front page of the Kubernetes website (https://kubernetes.io/) have unhelpful alt attributes, such as the filename. This commit addresses this issue by updating the alt attributes with the empty string.
#42832

improve: Update alt attributes for images on the front page

---

content/en/docs/reference/glossary/container-runtime-interface.md

There is a wrong link text in the glossary for CRI.
Based on the content and link, the word should be `node components` instead of `cluster components`.
Ps. Same issue for other languages, not sure of the right process to solve it.

fix: link text in glossary cri

---

content/en/docs/concepts/workloads/controllers/deployment.md

This PR adds the `strategy` field to the `nginx-deployment.yaml` that is embedded in the [Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) page.
This is a necessary addition to the existing YAML as currently throughout the Docs, we don't have a single YAML snippet where it's mentioned how to add the `strategy` section to a `Deployment` YAML. Mostly in the pages, we have some paragraphs talking about the strategies but miss the exact YAML implementation.
This will help users who want to quickly understand the syntax of adding strategies in Deployment as well as for CKA/CKAD exam takers, who require some boilerplate code for Deployments with Strategy section.

Added Deployment Strategy example in sample deployment

---

content/en/docs/concepts/configuration/secret.md
content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md

> **This is a Feature Request**
> 
> **What would you like to be added**
> 
> * Update the docs for server-side apply to mention that `stringData` for a [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) does not work well with [server-side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/)
> * * Update the docs for Secrets to mention that `stringData` for a [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) does not work well with [server-side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/)
>   * https://kubernetes.io/docs/concepts/configuration/secret/
>   * https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/ 
>   * https://kubernetes.io/docs/tasks/configmap-secret/managing-sec …

Document snag with stringData and server-side apply

---

content/en/docs/reference/labels-annotations-taints/_index.md

Added the Annotation service.kubernetes.io/topology-mode in the  https://kubernetes.io/docs/reference/labels-annotations-taints/ 
#43389

Document annotation service.kubernetes.io/topology-mode

---

content/en/docs/concepts/cluster-administration/system-logs.md

This is not a new policy: there never has been any promise of stability and log output has changed frequently (whenever a log call got modified), including changes that affect all log calls (when changing the underlying output code). We just have not explicit warned about this.

system-logs: warn about log output changes

---

content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
Revamped taint effects to introduce the effects early in the article
- Added three types of taint effects including their implications in the concepts
- Added a brief note about when taint effects are added for NoExecute

Update taint-and-toleration.md  with types of taint effects

---

content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md

Add n ote after `etcdctl restore` command to specify that <data-dir-location> will be (re)created during the restore operation. 
Fixes #36784

Add note after restore cmd to specify that data-dir will be (re)created

---

content/en/docs/tasks/administer-cluster/reserve-compute-resources.md

The note for --kube-reserved-cgroup should match formatting for --system-reserved-cgroup.  This changes helps those match.

Small mistake between sections of the document

---

content/en/docs/concepts/policy/resource-quotas.md

The examples for CrossNamespacePodAffinity were referencing the nonexistent resource quota scope `CrossNamespaceAffinity` in multiple places. Additionally, the example definitions were missing the required operator field.

Fix example errors for CrossNamespacePodAffinity

---

content/en/blog/_posts/2023-10-23-pv-last-phase-transtition-time.md

KEP: https://github.com/kubernetes/enhancements/pull/3796

Add blog for PersistentVolume last phase transition time

---

content/en/blog/_posts/2022-08-31-cgroupv2-ga.md
content/en/docs/concepts/architecture/cgroups.md

This is a follow-on to PR #40189. Since then, we've found an issue in the J9 JVM in the case that a user mixes cgroupsV1 and cgroupsV2. This was fixed in [APAR IJ46681](https://www.ibm.com/support/pages/apar/IJ46681) and this PR updates the versions of IBM Java and IBM Semeru Runtimes to match builds that have this APAR.

Clarify IBM Java and IBM Semeru Runtimes cgroupsV2 support

---

content/en/docs/tasks/access-application-cluster/list-all-running-container-images.md

Hi all,
I found altering this script to include initContainers gave a more thorough picture of what images are actually being used throughout the cluster.
I see there is more doc below around gotemplate etc, I have not included the changes for those.

Include `initContainers` in list-all-running-container-images.md

---

content/en/docs/reference/access-authn-authz/certificate-signing-requests.md

This PR added the `-subj` command option for the `req` command of OpenSSL under the `Create private key` in [Certificates and Certificate Signing Requests](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) docs.
Fixes #39591

Add -subj Command Option.

---

content/en/docs/reference/labels-annotations-taints/_index.md

documented unregistered annotation `"control-plane.alpha.kubernetes.io/leader"`
fixes: #39297

Document deprecated leader annotation

---

static/docs/reference/generated/kubectl/kubectl-commands.html

Added secret keyword to kubectl-command.html file

---

content/en/docs/reference/kubectl/jsonpath.md

The jsonpath implementation of kubernetes differs from some online executors, especially for escaping. Many users don't know how to get value from keys that contains dot(or other char). I think it is necessary to add an example of how to get it.
Related issues:
- https://github.com/kubernetes/kubernetes/issues/117579
- https://github.com/kubernetes/kubernetes/issues/23386
Example ref:
https://github.com/kubernetes/kubernetes/blob/551790729f1d26d75c1d3fa1411e341eb367f9f3/staging/src/k8s.io/client-go/util/jsonpath/jsonpath_test.go#L319-L329
Exec result:

kubectl/jsonpath: add example of escaping termination character

---

content/en/docs/concepts/storage/windows-storage.md

Fixed the reference link for 'secret permissions with default mode'

---

content/en/releases/release-managers.md

Package builds are now integrated into `krel obs`, means we do not have to reference rapture any more. It also got removed in https://github.com/kubernetes/release/pull/3313.
/cc @kubernetes/release-managers

Remove rapture reference for build admins

---

content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md

With [the recent documentation of a Kubernetes CronJob](https://github.com/ahrtr/etcd-defrag/pull/22) for the `etcd-defrag` tool, I think it would be valuable to also reference that possibility in the official documentation.
Indeed, running the tool as a CronJob has several benefits:
- simplicity of use: a typical kubeadm-deployed Cluster can use the referenced manifest as-is.
- period/automatic defragmentation is ensured
/cc @ahrtr

doc(etcd-maintenance): add reference to etcd-defrag CronJob

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md

The legacy package repositories are deprecated and we don't publish packages to the legacy repositories any longer. Because of that, it doesn't make much sense to provide installation instructions based on the legacy repositories.
This PR removes references to the legacy package repositories (`apt.kubernetes.io` and `yum.kubernetes.io`), as well as, updates wording in the relevant documents to highlight that the legacy package repositories have been frozen.
We need to cherry-pick this PR along with #42022 and other relevant PRs to all release branches up to at least v1.25 (ideally v1.24 as well).
/assign @cpanato @saschagrunert @jeremyrickard 

Remove instructions for legacy package repos

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Add a note to install `kubeadm` on Linux distributions that don't include `glibc`. Fixes #39444

Add note for Linux distros that don't include glibc

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

- Remove redundant blank lines and add a blank line after a heading
- Provide a consistent indentations for list in tabs

Clean up /kubeadm/install-kubeadm.md

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md

The `krel` templates are the ones we use right now, while kubepkg got removed in https://github.com/kubernetes/release/pull/3313.
/cc @kubernetes/release-managers

Replace kubepkg reference with krel templates

---

content/es/docs/tasks/tools/included/install-kubectl-linux.md

en PR https://github.com/kubernetes/website/pull/43100/files

[es] Fix sha256 url missing '/release/' to download kubectl

---

content/pt-br/docs/tasks/tools/install-kubectl-linux.md

en PR https://github.com/kubernetes/website/pull/43100/files

[pt] Fix sha256 url missing '/release/' to download kubectl

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

This feature gate is kind of unique one, added as Beta and enabled by default from the first step.
https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L777
/kind documentation
/kind bug

Modify `SchedulerQueueingHints`

---

content/en/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md

Pod Scheduling Readiness graduated to beta in 1.27, this update reflects that feature state.

Update pod-scheduling-readiness.md to beta

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

We received feedback that it's not clear enough that there's a dedicated package repository for each Kubernetes minor version (see #42810). This is a regression from #43407 and this PR is supposed to address this concern.
/assign @sftim @saschagrunert @cpanato @jeremyrickard 

Clarify repositories structure in install kubeadm document

---

content/zh-cn/docs/reference/config-api/kubeconfig.v1.md

This is a follow-up of the PR #43475, which experimented machine translation for reference docs. This PR further fixes some nits in the localized version.

[zh] Tweak localization to kubeconfig v1 reference

---

content/en/docs/tasks/access-application-cluster/ingress-minikube.md

Added the command curl <ip-addr> which is missing between two outputs.
#43473

fix: Missing curl '<ip-addr>' command in ingress-minikube.md document

---

content/en/docs/tasks/administer-cluster/kubelet-config-file.md

This closes #42105
Deploy preview: https://deploy-preview-42702--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/kubelet-config-file/#create-the-config-file

Add eviction thresholds parameters

---

content/en/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md

Stale advice on changing the Container Runtime on a Node from Docker Engine to containerd.
> At least in Kubernetes version 1.22, it is also necessary to add the flag --container-runtime=remote
see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md?plain=1#L1329

Fix stale advice on changing the Container Runtime on a Node

---

content/en/docs/tasks/tools/install-kubectl-linux.md

I experimented with various combinations of indentations in an attempt to resolve the issue, but none of them produced the desired result except for the one I'm proposing here. I copied the spacings from the "Red Hat-based" tab that displays correctly on the website.
This will fix https://github.com/kubernetes/website/issues/43431

Fix broken page layout for "Install and Set Up kubectl on Linux"

---

.editorconfig

I'm not sure why this is defaulted to `false` for all file types, so this just enables it for YAML for now.
(I couldn't figure out why my editor kept stripping this while working on #40780.)

editorconfig: preserve final newline in YAML

---

content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md
content/zh-cn/docs/tasks/administer-cluster/topology-manager.md
content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/zh-cn/docs/tasks/extend-kubernetes/configure-multiple-schedulers.md

[zh-cn]sync kubeadm-reconfigure topology-manager configure-multiple-schedulers onfigure-liveness-readiness

---

content/en/docs/concepts/services-networking/service.md

This PR fixes some nits in the Service concepts page.
- There are long lines that are not manually wrapped properly.
- The `[...]` lines in sample YAML snippets are unnecessary. Their side effects are making the snippets invalid YAMLs. We can safely drop them without causing any confusion.

Fix some nits in the service concept page

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
data/i18n/en/en.toml
layouts/shortcodes/doc-versions-list.html

This is a proposal to add `doc-versions-list` shortcode. This is supposed to be replacement for deprecated `versions-other` shortcode. This shortcode generates links to other versions of the given document, like this:
The new shortcode brings some improvements over the old `versions-other` shortcode:
- Links to the given page instead of the home page
- Brings some improvements from the new `supported-versions` layout
I decided to create a new shortcode because the old shortcode is still being used by some translations.
/assign @sftim

Add doc-versions-list shortcode

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
data/i18n/en/en.toml
layouts/shortcodes/legacy-repos-deprecation.html

This PR updates relevant upgrade guides to clarify that legacy repos are frozen and that you need to switch to the new Kubernetes repositories to installs versions released after September 13, 2023.
/assign @sftim @tengqm @Affan-7 @saschagrunert @cpanato 

Update upgrade guides to clarify that legacy repos are frozen

---

content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
content/en/docs/concepts/storage/volumes.md

Minor amendment to the emptyDir documentation.  I found the existing text a little confusing.

Clearer information about the emptyDir and correction for how topologyKey works

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

The feature gate is added by this change: https://github.com/kubernetes/kubernetes/pull/119946
Also see the link for the comments: https://github.com/kubernetes/kubernetes/pull/119946#discussion_r1360184126

Introduce of the deprecated FG: MergeCLIArgumentsWithConfig

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Move feature gates CronJobTimeZone, JobMutableNodeSchedulingDirectives and LegacyServiceAccountTokenNoAutoGeneration to feature-gates-removed page
Ref: https://github.com/kubernetes/kubernetes/pull/120192

Move feature gates CronJobTimeZone, JobMutableNodeSchedulingDirectives and LegacyServiceAccountTokenNoAutoGeneration to feature-gates-removed page

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

Reverts kubernetes/website#43515
sorry @tengqm , I need to revert this since we found https://github.com/kubernetes/kubernetes/pull/119946 is only partial implemented.
/assign @tengqm 
/cc @pacoxu @neolit123

Revert "Introduce of the deprecated FG: MergeCLIArgumentsWithConfig"

---

content/en/docs/concepts/services-networking/service.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Doc for new feature LoadBalancerIPMode.
PR link: https://github.com/kubernetes/kubernetes/pull/119937
KEP issue: https://github.com/kubernetes/enhancements/issues/1860

add doc for feature LoadBalancerIPMode

---

content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md

Updated 4 files:
```
content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
```
See [preview](https://deploy-preview-43521--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node/) please.

[zh] Sync concepts/scheduling-eviction/ files

---

content/zh-cn/docs/tasks/tools/install-kubectl-linux.md

Subject: New PR (zn-cn) for 'Install and Set Up kubectl on Linux' Documentation Fixes
Solves the issue : https://github.com/kubernetes/website/issues/43366
Dear Reviewers and Maintainers,
I sincerely apologize for the confusion caused by the creation and subsequent closure of multiple Pull Requests (PRs) for the same issue , and I deeply regret any inconvenience this may have caused.
Related PR:#43393 #43481
I have made the relevant changes to the (zh-cn) kubectl installation documentation.
Fix 1:
fixed the typo error in the zn-ch docs for Installation and Setting Up kubectl on Linux
Fix 2:
Translated the new tab about SUSE-based distributions (zn-ch)
image
Fix 3:
Fixed the content merging of two tabs in Install using native package management

Updated (zh-cn) Set up kubectl on Linux docs

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

The `RetroactiveDefaultStorageClass` feature gate was graduated to GA in 1.28 and it has been removed in k8s v1.29 by the following PR: https://github.com/kubernetes/kubernetes/pull/120861, with the reference to it, this PR moves the `RetroactiveDefaultStorageClass` feature gate from **Feature Gates** to **Feature Gates (removed)** docs for the k8s v1.29.

Move Feature Gate RetroactiveDefaultStorageClass to Feature Gates (removed) Page

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Move feature gates TopologyManager to  feature-gates-removed page
Ref: https://github.com/kubernetes/kubernetes/pull/121252

Topology manager remove

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

As discussions in https://github.com/kubernetes/website/pull/43570#discussion_r1364769770, revert v1beta4 to v1beta3 since v1beta4 is still in an early stage of development for v1.29.
cc @pacoxu @chendave

Revert kubeadm-config reference from v1beta4 to v1beta3

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_kubeadm.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_kubelet.md

Update 5 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_kubeadm.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_kubelet.md
```

[zh] Clean up kubeadm_init_phase_upload files

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

This PR adds patch releases that went out in October 2023. I'll create another PR to add release dates for 2024. 1.25 will be marked as EOL after 2023-10-28 (I'll prepare a PR for that too)
/assign @saschagrunert @cpanato @Verolop 

Add October 2023 patch releases

---

content/en/docs/contribute/participate/issue-wrangler.md

created issue-wrangler.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Since https://github.com/kubernetes/kubernetes/pull/120248 was merged for v1.29.
https://github.com/kubernetes/website/blob/63b39839b87d4dea04624d8fbbadd1ac55f28ff2/content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md#L73-L76
- should we remove this part as well?
old blog may not need to be updated.

Remove grpc container probe feature gate

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

Ref https://github.com/kubernetes/kubernetes/pull/121083

update SkipReadOnlyValidationGCE status to Deprecated

---

content/en/docs/reference/issues-security/security.md
content/en/docs/reference/kubectl/_index.md

- Remove redundant blank lines, trailing spaces
- Provide a consistent indentations for bullets
- Add a blank line between code blocks by following [markdownlint suggestions](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md)
No text changes.

Tweak issues-security/security and kubectl index

---

content/en/releases/patch-releases.md

This PR adds patch release dates for January, February, and March 2024. The patch release dates were selected with the following in mind:
- December patch releases being very in December
- KubeCon EU being around mid-March
/assign @saschagrunert @cpanato @Verolop

Add patch release dates for January, February, and March 2024

---

content/ja/docs/setup/best-practices/certificates.md

resolve https://github.com/kubernetes/website/pull/42942/files

[ja] remove "O=system:masters" from "kube-apiserver-etcd-client".md

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/instrumentation/slis.md

Component SLIs is graduating to GA. This updates the documentation accordingly.

update documentation for component-slis

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

PodLifecycleSleepAction updates as part of https://github.com/kubernetes/enhancements/issues/3960

Add information about PodLifecycleSleepAction (KEP3960)

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Corrected information about the removal of the TopologyManager feature gate.
Updated the pages:
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/
The list of removed feature gates incorrectly stated that the last release to include the TopologyManager feature gate was v1.28. However, until the v1.29 release comes out, it is not confirmed. The correction reflects the uncertainty regarding the removal in future releases.
#43613

fix: List of removed feature gates shows feature removed in future release (TopologyManager)

---

content/pt-br/docs/home/_index.md

This PR fixes the footer string that was changed in PR #42962, as explained in issue #43068.

[pt-br] Update linkTitle for docs home page

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Replaces PR https://github.com/kubernetes/website/pull/43554 which targeted the `main` branch and merged but should have targeted the `dev-1.29` branch
Fix for PR https://github.com/kubernetes/website/pull/43554
Followup to PR https://github.com/kubernetes/website/pull/43614 that reverted PR https://github.com/kubernetes/website/pull/43554

Replacement PR for PR 43554 that targets the dev-1.29 branch

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Adjusted the title level of "Validation rules" from h2 to h3 to align with the "Advanced topics" section it belongs to.
---

Adjust the title level of "Validation rules" on custom-resource-definitions.md

---

content/zh-cn/docs/concepts/architecture/cgroups.md

- **EN upstream**: `content/en/docs/concepts/architecture/cgroups.md`
- **Sync to**: `content/zh-cn/docs/concepts/architecture/cgroups.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/architecture/cgroups.md
diff --git a/content/en/docs/concepts/architecture/cgroups.md b/content/en/docs/concepts/architecture/cgroups.md
index b0a98af660..b96d89e0d6 100644
--- a/content/en/docs/concepts/architecture/cgroups.md
+++ b/content/en/docs/concepts/architecture/cgroups.md
@@ -104,8 +104,8 @@ updated to newer versions that support cgroup v2. For example:
DaemonSet for monitoring pods and containers, update it to v0.43.0 or later.
* If you deploy Java applications, prefer to use versions which fully support cgroup v2:
* [OpenJDK / …
```

[zh] sync concepts/architecture/cgroups.md

---

content/id/docs/concepts/workloads/controllers/statefulset.md
content/id/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md

**Gib** (Gibibit) was used where **GiB** (Gibibyte) is intended.
- #43238
- #43319
- #43320
- #43322
- #43323
- #43324

content: id: Fix incorrect letter case for data storage units

---

content/zh-cn/docs/tasks/tools/install-kubectl-linux.md

the checksum file command is to download kubectl checksum file rather than kubectl binary file. 
Related PR: https://github.com/kubernetes/website/pull/43543. This pr contributed to the wrong checksum file command

[zh-cn]fix: download kubectl checksum file command

---

content/pt-br/docs/tutorials/kubernetes-basics/_index.html
content/pt-br/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/pt-br/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Update obsoleted links that were still pointing to `/pt/` instead of `/pt-br/`

[pt-br] Update obsolete links in Portuguese locale

---

content/en/_index.html

Seeing #43565 made me realise that the KubeCon 2023 dates, currently displayed at https://kubernetes.io/, are outdated. This tiny PR puts the upcoming KubeCon 2023 NA first and adds KubeCon 2024 EU.

Update KubeCon dates for NA 2023/EU 2024

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
content/en/docs/tasks/tools/install-kubectl-linux.md
data/i18n/en/en.toml
layouts/shortcodes/doc-versions-list.html
layouts/shortcodes/legacy-repos-deprecation.html

The legacy package repositories (`apt.kubernetes.io` and `yum.kuberentes.io`) are deprecated and frozen. All Kubernetes versions released after September 13, 2023 are published only to the new package repositories hosted at pkgs.k8s.io. Because of that, I think we should update legacy docs to replace legacy repos with the new Kubernetes package repositories.
This is a manual cherry-pick of the followings PRs:
- #42022
- #43407
- #43458
- #43472
- #43478
Note: there might be some other updates included in this PR such as:
- https://github.com/kubernetes/website/pull/43524#discussion_r1362227256
/assign @saschagrunert @cpanato @jeremyrickard 

[release-1.27] Update docs to use pkgs.k8s.io instead of legacy repos

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/en/docs/tasks/tools/install-kubectl-linux.md
data/i18n/en/en.toml
layouts/shortcodes/doc-versions-list.html
layouts/shortcodes/legacy-repos-deprecation.html

The legacy package repositories (`apt.kubernetes.io` and `yum.kuberentes.io`) are deprecated and frozen. All Kubernetes versions released after September 13, 2023 are published only to the new package repositories hosted at pkgs.k8s.io. Because of that, I think we should update legacy docs to replace legacy repos with the new Kubernetes package repositories.
This is a manual cherry-pick of the followings PRs:
- #42022
- #43407
- #43458
- #43472
- #43478
Note: there might be some other updates included in this PR such as:
- https://github.com/kubernetes/website/pull/43524#discussion_r1362227256
/assign @saschagrunert @cpanato @jeremyrickard 

[release-1.25] Update docs to use pkgs.k8s.io instead of legacy repos

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
content/en/docs/tasks/tools/install-kubectl-linux.md
data/i18n/en/en.toml
layouts/shortcodes/doc-versions-list.html
layouts/shortcodes/legacy-repos-deprecation.html

The legacy package repositories (`apt.kubernetes.io` and `yum.kuberentes.io`) are deprecated and frozen. All Kubernetes versions released after September 13, 2023 are published only to the new package repositories hosted at pkgs.k8s.io. Because of that, I think we should update legacy docs to replace legacy repos with the new Kubernetes package repositories.
This is a manual cherry-pick of the followings PRs:
- #42022
- #43407
- #43458
- #43472
- #43478
Note: there might be some other updates included in this PR such as:
- https://github.com/kubernetes/website/pull/43524#discussion_r1362227256
/assign @saschagrunert @cpanato @jeremyrickard 

[release-1.26] Update docs to use pkgs.k8s.io instead of legacy repos

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/en/docs/tasks/tools/install-kubectl-linux.md
data/i18n/en/en.toml
layouts/shortcodes/doc-versions-list.html
layouts/shortcodes/legacy-repos-deprecation.html

The legacy package repositories (`apt.kubernetes.io` and `yum.kuberentes.io`) are deprecated and frozen. All Kubernetes versions released after September 13, 2023 are published only to the new package repositories hosted at pkgs.k8s.io. Because of that, I think we should update legacy docs to replace legacy repos with the new Kubernetes package repositories.
This is a manual cherry-pick of the followings PRs:
- #42022
- #43407
- #43458
- #43472
- #43478
Note: there might be some other updates included in this PR such as:
- https://github.com/kubernetes/website/pull/43524#discussion_r1362227256
/assign @saschagrunert @cpanato @jeremyrickard 

[release-1.24] Update docs to use pkgs.k8s.io instead of legacy repos

---

content/en/docs/tasks/manage-hugepages/scheduling-hugepages.md

This commit add a little more details on pre-allocation and dynamic allocation of huge pages on the node.
It also links to the Linux documentation for further details but gives a quick example on multiple page sizes that is not very obvious from the Linux documentation currently.
/cc. @derekwaynecarr

hugepages: add some details on allocation

---

assets/scss/_base.scss

Fix Issue: #43265
Issue: Code snippet layout at "Kubeadm install" page is causing layout break of page for mobile devices
**Changes made:**
Added some css  for making adjustment in table layout that are under tabs

Fix Kubeadm install layout break for mobile device

---

content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md

This closes #43303
Deploy preview: https://deploy-preview-43336--kubernetes-io-main-staging.netlify.app/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-signals

Remove misleading docs around eviction and image garbage collection

---

content/en/docs/concepts/extend-kubernetes/operator.md

Update the link  to update the paper from "Review Version" to "Final Version".
The old link pointed to "CNCF Operator White Paper - Review Version", see https://github.com/cncf/tag-app-delivery/blob/eece8f7307f2970f46f100f51932db106db46968/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md .
The new link points to "CNCF Operator White Paper - Final Version", see https://github.com/cncf/tag-app-delivery/blob/163962c4b1cd70d085107fc579e3e04c2e14d59c/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md.

Update "Operator White Paper" link on operator.md page

---

content/zh-cn/docs/concepts/cluster-administration/system-logs.md

File content/en/docs/concepts/cluster-administration/system-logs.md not yet localized to zh-cn.

Added translation of system logs

---

content/en/blog/_posts/2023-10-23-pv-last-phase-transtition-time.md

Delete unexpected **``** on 
> phase to another. `` Whether it's transitioning
https://kubernetes.io/blog/2023/10/23/persistent-volume-last-phase-transition-time/#how-to-use-it

Fix a typo on blog 2023-10-23-pv-last-phase-transtition-time.md

---

content/en/docs/reference/access-authn-authz/service-accounts-admin.md
content/en/docs/tasks/configure-pod-container/configure-service-account.md

This PR removed the inaccurate information about SA from the [Managing Service Accounts](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#delete-token) docs and also added the for Manually created Secret API objects under the [Manually create a long-lived API token for a ServiceAccount](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount) in the [Configure Service Accounts for Pods](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) task page.
Fixes #43111

Removed outdated information for SA and Added the Note for Manually created Secret API objects.

---

content/ko/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md

Related Issue: #43700 
fix invalid hyperlink on  `content/ko/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md`, currently "https://docs.cilium.io/en/stable/intro" link is returning an 404 not found response.
as-is
> 실리움의 배경에 대해서는 [실리움 소개](https://docs.cilium.io/en/stable/intro)를 읽어보자.
to-be
> 실리움의 배경에 대해서는 [실리움 소개](https://docs.cilium.io/en/stable/overview/intro)를 읽어보자.

[ko] Fix Outdated Link on cilium-network-policy.md

---

content/en/blog/_posts/2023-11-02-sig-architecture-prod-readiness-spotlight.md

Spotlight on the Production Readiness subproject of SIG Architecture.
The content review is being done at the `contributor-site` repository: https://github.com/kubernetes/contributor-site/pull/440 ; I will update this file with the final version there, minus the small template changes, when it's approved there,

Add SIG Architecture Production Readiness spotlight

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_controller-manager.conf.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig_user.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md

…in docs.
fix: delete deprecated command `kubeadm` in docs.

[zh]: delete removed kubeadm subcommand

---

assets/scss/_custom.scss
layouts/_default/search.html
static/js/search.js

**Reason for this PR:**
- Bing Custom Search has transistioned from Azure Cognitive Services to Microsoft Bing API’s via Azure Marketplace. This happened in 2020, and now support for Cognitive Services will be disabled on 31 October 2023.
- This PR keeps Bing Custom Search working for users who do not use the Google Site Search (predominantly users from China or those behind firewalls where Google is blocked)
**What has been done:**
- Created a serverless function to act as a proxy to run the Bing search. This protects our API key and enables us to restrict access to the API via CORS (Kubernetes.io and localhost are included).
- Updated styling of Bing results
- Improved search page experience if no query has been passed
- Tidied up some CSS
**Notes:** 
- Bing search previously used …

Update Bing Search to use Bing APIs not Cognitive Services

---

content/en/examples/pods/security/seccomp/ga/audit-pod.yaml
content/en/examples/pods/security/seccomp/ga/default-pod.yaml
content/en/examples/pods/security/seccomp/ga/fine-pod.yaml
content/en/examples/pods/security/seccomp/ga/violation-pod.yaml

This PR is part of #42286
* Update the "hashicorp/http-echo" versions to v1.0, which supports ARM64 arhictecture
* [DockerHubReferenceLink](https://hub.docker.com/r/hashicorp/http-echo/tags)
* [HashiCorpHttpEchoPRAdded](https://github.com/hashicorp/http-echo/pull/3) 
* Pre requisites
* ARM64 architecture
* kind
* kubectl
* Follow the steps indicated in the SecComp page for creating a pod
* [RunTime default seccomp profile](https://kubernetes.io/docs/tutorials/security/seccomp/#create-a-pod-that-uses-the-container-runtime-default-seccomp-profile)
* [SecComp profile specified in the audit.json](https://kubernetes.io/docs/tutorials/security/seccomp/#create-a-pod-with-a-seccomp-profile-for-syscall-auditing)  
* Screenshots executed locally in my local setUp (macOs Ventura v.13.1 arm164, kind …

Switch to newer image for hashicorp/http-echo in examples

---

content/zh-cn/examples/pods/probe/tcp-liveness-readiness.yaml

Fix https://github.com/kubernetes/website/issues/43730
Based on the following description and the EN page, the `initialDelaySeconds` of the `readinessProbe` should be 15 instead of 5. 
>  下面这个例子同时使用就绪和存活探针。kubelet 会在容器启动 15 秒后发送第一个就绪探针。 
Related page: https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-TCP-liveness-probe
Refer to the EN page:  https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-TCP-liveness-probe
See **[Preview](https://deploy-preview-43743--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-TCP-liveness-probe)**

[zh] Correct initialDelaySeconds on code snippet of  tcp-liveness-readiness.yaml

---

content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_super-admin.conf.md
content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_super-admin.md
content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
content/en/docs/reference/setup-tools/kubeadm/kubeadm-certs.md
content/en/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
content/en/docs/setup/best-practices/certificates.md
content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md

- Update most pages where the kubeadm generated admin.conf
is discussed. Include information about the new file "super-admin.conf".
tracking issue in k/kubeadm:
https://github.com/kubernetes/kubeadm/issues/2414
(has links to KEP, k/k PR)
- https://github.com/kubernetes/kubernetes/pull/121305 must merge first.

kubeadm: introduce documentation changes for super-admin.conf 

---

content/en/blog/_posts/2023-10-31-Gateway-API-GA/index.md

As requested in issue #43761 udpated the blog article to link to 1.0.0 not 0.1.0
This will fix #43761

Fix broken link in Gateway API v1.0 blog

---

content/en/docs/tutorials/security/seccomp.md

This PR fixes the 👁️  kind cluster added in [Enable the use of RuntimeDefault as the default seccomp profile for all workloads](https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads) 👁️ 
* Impossible to make it run the second kind-worker node
* You can check more detailed logs [here](https://github.com/kubernetes-sigs/kind/issues/3402#issue-1967064032) and also about the issue reported in kind
* Update the "kindest/node" versions to v1.28.0
* [RecommendedInKubernetesSigsKindIssue](https://github.com/kubernetes-sigs/kind/issues/3402#issuecomment-1785532845)
* [kindest/node tags](https://hub.docker.com/r/kindest/node/tags)
* Prerequisiites
* kubernetes v1.28 
* `kind create cluster …

Switch to newer kindest/node version

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

The `PersistentVolumeLastPhaseTransitionTime` feature is moving to beta in 1.29: https://github.com/kubernetes/kubernetes/pull/120627

graduate PersistentVolumeLastPhaseTransitionTime to beta in v1.29

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

Since https://github.com/kubernetes/kubernetes/pull/120228 is merged.
- commit 42e282b442710826a6e5ad5728798883ba17caf2 is from https://github.com/kubernetes/website/pull/42771
- the only change is https://github.com/kubernetes/website/pull/42801/commits/e91265b62e8af79ece52c7d9812dd5c485600d16: update  EtcdLearnerMode  beta in v1.29

kubeadm: EtcdLearnerMode is beta in v1.29

---

content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md

Fix typo in [InitConfiguration](https://kubernetes.io/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-InitConfiguration) 
/language zh
fix: #43796

[zh-cn] Typo fix /config-api/kubeadm-config.v1beta3.md

---

content/zh-cn/docs/reference/config-api/kube-proxy-config.v1alpha1.md

Sync with en upstream. Mainly moved 3 sections from bottom to top.
```
```

[zh] Sync kube-proxy-config.v1alpha1.md

---

content/en/docs/concepts/storage/volumes.md

Updated the "Unclear / misleading information about the emptyDir volume first creation" with a new line. #43805

Clarify information about emptyDir volume first creation

---

content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md

[zh-cn]sync persistent-volume-v1 mutating-webhook-configuration-v1 validating-webhook-configuration-v1

---

content/en/docs/concepts/storage/volumes.md

As it is outdated and also doesn't belong as part of the conceptual explanation of what a volume is. #43809

Remove configuration section from volumes concept

---

content/en/docs/concepts/workloads/controllers/daemonset.md
content/en/examples/controllers/daemonset.yaml

Not using a priority class name can result in DaemonsetPods remaining pending.  This can occur with cluster-autoscaler where the new DS pod is created, but can't evict existing
scheduled pods due to not having a high priority class.  The DS pod then remains pending
indefinitely unless existing pods on the node happen to terminate to make room.

add more clarification regarding priorityClassName use with DaemonSet

---

content/en/blog/_posts/2023-11-06-introducing-sig-etcd.md

Thanks to @logicalhan @serathius for the effort of making etcd a Kubernetes special interest group, @fsmunoz for helping putting together the doc, and @jmhbnz for posting the blog in etcd.
This post is to celebrate introducing etcd as a k8s sig.
cc @ahrtr @jberkus @kaslin @ptabor @mitake

Add mirrored copy of blog article “Introducing sig-etcd”

---

content/zh-cn/docs/concepts/security/service-accounts.md

Fix #43355 
```
content/zh-cn/docs/concepts/security/service-accounts.md
```
See [preview](https://deploy-preview-43764--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/service-accounts/) please.

[zh] Localize service-accounts.md into Chinese

---

content/en/blog/_posts/2020-08-26-kubernetes-release-1.19.md
content/en/docs/tutorials/security/ns-level-pss.md

Fix ```KinD``` typos in en docs.
There are somes show Kind , and somes show KinD.
Review the website of kind [kind quick start](https://kind.sigs.k8s.io/docs/user/quick-start/). 
It is maybe Kind is rightness.

Fix KinD typos in en docs

---

content/en/docs/reference/kubectl/kubectl.md

Since https://github.com/kubernetes/enhancements/issues/3895 has been promoted to beta, environment
variable representing alpha feature enablement has become obsolete. This PR removes this from website.

Remove alpha environment variable because feature is in beta

---

content/en/docs/concepts/services-networking/network-policies.md

1. Add "Pod lifecycle" section to the network policy docs. 
2. Clarify network policy behaviour for hostNetwork pods 
3. Clarify network policy behaviour for L2/L3 protocols 
New sections should clarify some confusing aspect for the users, and become the base to build better-defined API for AdminNetworkPolicy.
The current version is intended for content reviews, and may not completely follow style guidelines, which will be fixed once we agree on the content.

Network policy docs clarifications

---

content/en/docs/concepts/services-networking/gateway.md

The link to custom resources was broken due to a missing / at the beginning.

Fix link to custom resources

---

content/en/docs/setup/best-practices/certificates.md

The kube-apiserver flag --kubelet-client-certificate
accepts a client certificate (kube-apiserver-kubelet-client.crt)
to connect to the kubelet. There is no need for this certificate
to have "system:masters" as "O" in the Subject, instead it
can be a less privileged group like kubeadm's "kubeadm:cluster-admins".
k/k bugfix PR:
https://github.com/kubernetes/kubernetes/pull/121837

certificates.md: add note about system:masters in apiserver cert

---

content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

@sftim left some feedback on backports for docs for new package repositories:
- https://github.com/kubernetes/website/pull/43522
- https://github.com/kubernetes/website/pull/43523
- https://github.com/kubernetes/website/pull/43524
- https://github.com/kubernetes/website/pull/43525
This PR is supposed to address those concerns by:
- Clarifying that changing the package repository is meant to be used only when upgrading to another minor release
- Clarifying that changing the package repository document is only one part of the upgrade process
Fixes #43666

Additional clarifications for changing package repository

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/tasks/debug/debug-application/debug-pods.md

I see this problem more often than not.
Examples:
- https://github.com/kubernetes/kubernetes/issues/121605
- https://github.com/kyverno/kyverno/issues/8815

Troubleshooting for job pod finalizers

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Part of kubernetes/enhancements#3939

Graduate JobPodReplacementPolicy to beta

---

content/en/releases/download.md
data/i18n/en/en.toml
layouts/partials/head.html
layouts/shortcodes/release-binaries.html
static/js/release_binaries.js

This PR incorporates changes that involve to integrate [downloadkubernetes.com ](https://www.downloadkubernetes.com/)into k/website.
Related to feature request: #30579
- **Pre-req:** Will need `release_binaries.json` from `kubernetes-sigs/downloadkubernetes`. The logic to generate the json file is added as part of PR https://github.com/kubernetes-sigs/downloadkubernetes/pull/472
- Added a Hugo shortcode to render the details of release binaries from a JSON file generated by  `kubernetes-sigs/downloadkubernetes` The table structure, CSS, and scripts are mostly reused from 'downloadkubernetes' repository wherever it was appropriate and did not cause any issues.

Integrate downloadkubernetes.com into docs website 

---

content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md

That pods with ResourceClaims get scheduled more slowly, but that this also affects other pods may be surprising and is worth calling out.

Document impact of DRA on scheduling

---

content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

This is a manual backport of #43905 to the `release-1.26` branch in order to add some additional clarifications regarding changing the package repository for users of the new package repositories (`pkgs.k8s.io`).
- Clarify that changing the package repository is meant to be used only when upgrading to another minor release
- Clarify that changing the package repository document is only one part of the upgrade process

[release-1.26] Additional clarifications for changing package repository

---

content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

This is a manual backport of #43905 to the `release-1.25` branch in order to add some additional clarifications regarding changing the package repository for users of the new package repositories (`pkgs.k8s.io`).
- Clarify that changing the package repository is meant to be used only when upgrading to another minor release
- Clarify that changing the package repository document is only one part of the upgrade process

[release-1.25] Additional clarifications for changing package repository

---

content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

This is a manual backport of #43905 to the `release-1.24` branch in order to add some additional clarifications regarding changing the package repository for users of the new package repositories (`pkgs.k8s.io`).
- Clarify that changing the package repository is meant to be used only when upgrading to another minor release
- Clarify that changing the package repository document is only one part of the upgrade process

[release-1.24] Additional clarifications for changing package repository

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

This feature was removed during its alpha state, more information on https://github.com/kubernetes/kubernetes/pull/121229

Remove MultiCIDRRangeAllocator alpha feature

---

content/en/docs/concepts/workloads/pods/_index.md
content/en/docs/concepts/workloads/pods/init-containers.md
content/en/docs/concepts/workloads/pods/pod-lifecycle.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

https://github.com/kubernetes/enhancements/issues/753

Document SidecarContainers graduation to beta

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md

in 1.27, the StatefulsetAutoDeletePVC is default true

in 1.27, the StatefulsetAutoDeletePVC is default true

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Document (GA) CEL validation for custom resources

[KEP-2876] Document (GA) CEL validation for custom resources

---

content/en/docs/concepts/services-networking/service.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

The `ServiceNodePortStaticSubrange` is listed but not documented.
This PR fixes the problem.

Fix feature gate for a gate that is not documented

---

OWNERS_ALIASES

I'd like to apply for sig-docs-ko-reviews role.
I've met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):
This k/website update is based on https://github.com/kubernetes/org/pull/4587
Thanks!
/assign @seokho-son (According to the steps in https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-reviewer)

Add jongwooo to sig-docs-ko-reviews

---

content/zh-cn/docs/tutorials/kubernetes-basics/expose/expose-intro.html

Changes(content/zh-cn/docs/tutorials/kubernetes-basics/expose/expose-intro.html):
1. Sync content with en
2. Fix en source comment to match [localization_zh](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/)

[zh-cn] Sync tutorial expose-intro

---

content/zh-cn/docs/reference/kubernetes-api/authentication-resources/cluster-trust-bundle-v1alpha1.md

Fix #43357 
```
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/cluster-trust-bundle-v1alpha1.md
```
See [preview](https://deploy-preview-43780--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/authentication-resources/cluster-trust-bundle-v1alpha1/) please.

[zh] Localize cluster-trust-bundle-v1alpha1.md into Chinese

---

content/en/blog/_posts/2022-07-13-gateway-api-in-beta.md

Fix GRPC route link in Kubernetes Gateway API blog

---

content/en/docs/contribute/participate/issue-wrangler.md

- Change a link of `Triage and categorize issues` to a relative url
- Adjust heading levels 
- Revise the `prow command` section

Tweak and adjust heading levels in issue-wrangler.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/kubectl/kubectl.md

* Adds documentation for new alpha `TranslateStreamCloseWebsocketRequests` feature flag, allowing the control plane to accept WebSockets/V5 upgrade requests.
* Adds documentation for new alpha kubectl  environment variable `KUBECTL_REMOTE_COMMAND_WEBSOCKETS` feature flag, which attempts to use the WebSockets protocol for `kubectl exec`, `kubectl cp`, and `kubectl attach` when it is set.

Document Kubernetes' use of WebSockets (replacement for SPDY / KEP 4006)

---

layouts/index.html

Closes #43396
Changed the link into a button, Now our asset classes apply on it

Fix visibility of "Learn Kubernetes Basics" button on homepage

---

content/zh-cn/docs/reference/config-api/apiserver-admission.v1.md

Fix #43362 
```
```
See [preview](https://deploy-preview-43974--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/apiserver-admission.v1/) please.

[zh] Localize apiserver-admission.v1.md

---

content/en/docs/reference/using-api/client-libraries.md

Removed third-party lib https://github.com/ericchiang/k8s as requested in issue #43951
This will fix https://github.com/kubernetes/website/issues/43951

Remove archived third-party client library

---

content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html

The indentations in `<pre>` block will rendered on the page, so to match the real output in terminal, I think this block should without indentations unlike previous or next paragraph.
Because of if `</pre>` tag line have indentation, this block will render a new line after contents, so I removed indentations both of the pair of tags.
**Append:**
There are 2 commands example in the tutorial without line break. I add `<p>` tag to fix it.

[en] Fix scale-intro.html outputs indentations of terminal.

---

content/zh-cn/_index.html

The Chinese translations of 'Run Anywhere' and 'Never Outgrow' on homepage are mixed up. Fix it.

[zh-cn] Update KubeCon dates and fix mismatched blocks

---

content/zh-cn/docs/reference/config-api/kubelet-config.v1beta1.md

Only move these sections from bottom to top by following the en upstream:
```
......
......
......
```
See [preview](https://deploy-preview-43922--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/kubelet-config.v1beta1/#TracingConfiguration).

[zh] Sync /config-api/kubelet-config.v1beta1.md

---

content/zh-cn/docs/reference/using-api/api-concepts.md

Fix #43333 
```
```
See [preview](https://deploy-preview-43721--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/using-api/api-concepts/) please.

[zh] Add translations to /using-api/api-concepts.md

---

content/ja/docs/concepts/workloads/controllers/statefulset.md

**Gib** (Gibibit) was used where **GiB** (Gibibyte) is intended.
- #43238
- #43319
- #43320
- #43321
- #43323
- #43324

content: ja: Fix incorrect letter case for data storage units

---

content/ja/docs/concepts/storage/storage-limits.md

Updates broken github link for Japanese doc in content/ja/docs/concepts/storage/storage-limits.md. This is follow up PR from - https://github.com/kubernetes/website/pull/43659

Update broken github link for Japanese Storage-limit doc.

---

content/en/docs/concepts/storage/projected-volumes.md
content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/examples/pods/storage/projected-clustertrustbundle.yaml

ClusterTrustBundle projected volume sources are slated to land in 1.29.  Drop a ~placeholder~ section in the existing ClusterTrustBundle documentation to document it.
Enhancements Issue: https://github.com/kubernetes/enhancements/issues/3257
Implementation PR: https://github.com/kubernetes/kubernetes/pull/113374

ClusterTrustBundles: document projected volumes

---

content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/en/examples/admin/resource/memory-available-cgroupv2.sh

This request adds a script to calculate the memory available in cgroup v2 which is currently missing.  The current [script ](https://kubernetes.io/examples/admin/resource/memory-available.sh) only works for users using cgroup v1. For more details, please check [this](https://github.com/kubernetes/enhancements/issues/2254) issue

Adding script for cgroup v2 memory available.sh

---

content/en/docs/reference/using-api/server-side-apply.md

There is a missing period after the sentence explaining `fieldManager`.

Add missing punctuation in server side apply page

---

content/en/docs/contribute/participate/issue-wrangler.md

The correct link is https://kubernetes.io/docs/contribute/review/for-approvers/#triage-and-categorize-issues

Fix broken link on issue-wrangler.md

---

content/en/docs/concepts/scheduling-eviction/scheduling-framework.md

ref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/4247-queueinghint
It's not a mistake that I try to push this to main branch, not to v1.29 branch.
This KEP is under a unique situation where we assume this feature has been existing as beta since v1.28.

add a doc for QueueingHint

---

content/en/docs/reference/access-authn-authz/service-accounts-admin.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/labels-annotations-taints/_index.md

PR: https://github.com/kubernetes/kubernetes/pull/120682
Issue: https://github.com/kubernetes/enhancements/issues/2799

Add LegacyServiceAccountTokenCleanUp feature in beta

---

content/en/blog/_posts/2023-11-24-sig-testing-spotlight.md

Add SIG Testing spotlight. **This is mirrored from https://github.com/kubernetes/contributor-site/pull/454**, and will be updated with the approved version after discussion ends there - please go to the `contributor-site` repository for the initial review.

Add SIG Testing spotlight

---

content/en/releases/download.md

A follow up to PR #44062 that gets the page to where I think it ought to be.
/sig release
and, in respect of image signatures:
/sig security

Revise detail about container image downloads

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/workloads/controllers/statefulset.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/tasks/administer-cluster/change-pv-access-mode-readwriteoncepod.md
content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md

Update references to ReadWriteOncePod feature gate to indicate it's GA / stable.
Feature: https://github.com/kubernetes/kubernetes/pull/121077
Enhancement: https://github.com/kubernetes/enhancements/issues/2485
/sig storage
/cc @msau42

Graduate ReadWriteOncePod to GA

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

Placeholder docs for [KEP-3902](https://github.com/kubernetes/enhancements/pull/3901)
Implementation on-going in https://github.com/kubernetes/kubernetes/pull/119208

Docs for Decoupled TaintManager from NodeLifeCycleController (KEP-3902)

---

content/en/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md

For the isse which is reported recently: https://github.com/kubernetes/kubeadm/issues/2957 We'd better to provide some tips to workaround this known issue.
related: https://github.com/kubernetes/kubeadm/issues/2957

Update trouble shooting to include the issue of etcd upgrade

---

content/en/docs/concepts/containers/images.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Add docs for KEP 4216: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4216-image-pull-per-runtime-class which has been accepted for k8s 1.29
P.S. : Opened this PR against dev-1.29 branch based on review comment here https://github.com/kubernetes/website/pull/43541#issuecomment-1820057245

[dev-1.29] Add docs for KEP 4216: Image pull per runtime class

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

https://github.com/kubernetes/enhancements/issues/4138

update docs to promote PodReadyToStartContainersCondition into beta

---

content/en/releases/patch-releases.md

This PR updates the patch releases calendar to:
- Remove November patch releases given we had out-of-band releases already
- Delay December patch releases for 2023-12-13 (cherry-pick deadline 2023-12-08) to give more time for PRs to get merged after code freeze
Slack discussion: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1701097256703869
/assign @jeremyrickard @saschagrunert @cpanato @Verolop 

Delay December patch releases for 2023-12-13

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Updates documentation for Alpha 2 of CRD Validation Ratcheting:
- Adds note about DeepEqual comparison working for CEL
- New CRD field `optionalOldSelf` documentation

KEP-4008: CRD Validation Ratcheting - Alpha 2 Docs

---

content/en/blog/_posts/2023-11-24-sig-testing-spotlight.md

Add a correct url prefix in blog post: https://kubernetes.io/blog/2023/11/24/sig-testing-spotlight-2023/.
`/blog/2023/04/12/e2e-testing-best-practices-reloaded/` didn't exist in `https://kubernetes.io/`. Should be `https://www.kubernetes.dev/blog/2023/04/12/e2e-testing-best-practices-reloaded/`

Fix the broken link in blog post

---

content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

What type of PR is this?
/sig node
Which issue(s) this PR fixes:
This PR fixes issue #30849.
The changes are done on this page -> https://deploy-preview-44098--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Document on the probes page that redirects are not followed to 

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

KEP: https://github.com/kubernetes/enhancements/issues/4004
Implementation PR: https://github.com/kubernetes/kubernetes/pull/120954

Document Pod .status.nodeInfo.kubeProxyVersion deprecation

---

content/en/docs/reference/using-api/deprecation-guide.md

Adding the deprecation / removal / replacement details for the last (!) default-on beta API
cc @deads2k @tkashem @MikeSpreitzer 
For [KEP 1040](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness) and [KEP-1635](https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/1635-prevent-permabeta)
/sig api-machinery architecture

Add 1.32 removal info for v1beta3 flowcontrol API

---

content/en/docs/concepts/containers/images.md

Add docs for KEP 4216: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4216-image-pull-per-runtime-class which has been accepted for k8s 1.29
This PR mainly addresses the review comment here https://github.com/kubernetes/website/pull/44028#discussion_r1406194376 from @sftim

[dev-1.29] Address review comment for KEP 4216 doc

---

content/en/docs/concepts/workloads/pods/user-namespaces.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Adding required documentation for [KEP-127](https://github.com/kubernetes/enhancements/issues/127).
Supersedes https://github.com/kubernetes/website/pull/43437
cc @giuseppe @rata @mrunalp 
**Preview: https://deploy-preview-43803--kubernetes-io-vnext-staging.netlify.app/docs/concepts/workloads/pods/user-namespaces**

[KEP-127] Add documentation about user namespaces and PSS

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/storage-classes.md
content/en/docs/concepts/storage/volume-attributes-classes.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

https://github.com/kubernetes/enhancements/issues/3751
https://github.com/kubernetes/kubernetes/pull/121104
Doc draft in [Google doc](https://docs.google.com/document/d/123LvscAa5KBjpycb6ajrxozxriQf8txBlgOSlErpvsk/edit)

Add docs about VolumeAttributesClass API (KEP-3751)

---

content/zh-cn/docs/tasks/configure-pod-container/static-pod.md

[EN]
Configure your kubelet on the node to use this directory by running it with --pod-manifest-path=/etc/kubernetes/manifests/ argument. On Fedora, edit /etc/kubernetes/kubelet to include this line:
[ZH]
配置这个节点上的 kubelet，使用这个参数执行 --pod-manifest-path=/etc/kubelet.d/。 在 Fedora 上编辑 /etc/kubernetes/kubelet 以包含下面这行：

fix: Create a static pod running argument [zh]

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/reference/networking/virtual-ips.md
content/en/docs/tasks/network/extend-service-ip-ranges.md

Demo https://gist.github.com/aojea/c20eb117bf1c1214f8bba26c495be9c7
KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1880-multiple-service-cidrs
Follow up on https://github.com/kubernetes/website/pull/37620

KEP-1880 Multiple ServiceCIDR 

---

content/en/docs/concepts/workloads/controllers/cron-jobs.md

This is a followup from https://github.com/kubernetes/kubernetes/pull/116252
/assign @liggitt @sftim

Update information about CronJob's unsupported time zone field

---

content/en/docs/reference/networking/virtual-ips.md

A tweak to land after https://github.com/kubernetes/website/pull/43469 has merged.
/sig network
/milestone 1.29

Revise docs for API tracking of IP address assignment

---

content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md

Sync with en #43813 
```
content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md
```
See [preview](https://deploy-preview-44042--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework/).

[zh] Sync scheduling-framework.md

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

- In a early note explain that there could be multiple default gateways on a host.
- Do not have 1 note, 1 warning, then other note.
- Leave the warning that the "custom IP" setup is not recommended at the end of the section.
follow up on https://github.com/kubernetes/website/pull/43872#pullrequestreview-1744902982

kubeadm: revisit the "Network setup" section post-feedback

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md

The kubeadm init phase doesn't permit to reconfigure the etcd yaml manifest (when etcd is in local mode)
Adding a little more infos and the right command when etcd needs to be reconfigured

Add details in kubeadm-reconfigure.md for etcd

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

Added details about the newly added Feature Gate `UnauthenticatedHTTP2DOSMitigation`
Helps with https://github.com/kubernetes/website/issues/44122
_Reference in code: [staging/src/k8s.io/apiserver/pkg/features/kube_features.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/features/kube_features.go#L182-L198)_

Add doc for UnauthenticatedHTTP2DOSMitigation feature gate

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

Following up with the docs update after the official announcement: https://groups.google.com/a/kubernetes.io/g/dev/c/OSAd6wvO3EQ/m/W6022Yo0AgAJ
The December patch releases are postponed for 2023-12-19 with the cherry-pick deadline being 2023-12-15.
/assign @saschagrunert @Verolop @cpanato @jeremyrickard 

Postpone December patch releases for 2023-12-19

---

content/en/docs/reference/networking/virtual-ips.md

Noticed while adding the nftables documentation.
filing this against `dev-1.29` because @sftim [said to](https://github.com/kubernetes/website/pull/43588#pullrequestreview-1750988605) but nothing in here is new in 1.29.

clean up iptables/ipvs proxy mode descriptions a bit

---

content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md
data/announcements/scheduled.yaml

Previously we only had a vague warning that users should migrate as soon as possible. We now have a more concrete (though technically approximate) timeline that they _must_ migrate before January 2024 and should re-emphasize this change.
Technically the project could redirect these old apt.kubernetes.io and yum.kubernetes.io endpoints to a static snapshot but that will take time, effort, and resources and it's not clear as a project that we should continue to do this versus moving forward with the new community managed host, so in the meantime we should warn that the endpoints as-is will stop working.

Add new warning for kubernetes deb/RPM packages migration

---

data/i18n/en/en.toml
layouts/partials/deprecation-warning.html

This addresses part of issue https://github.com/kubernetes/website/issues/44196 which deals revert of https://github.com/kubernetes/website/pull/44173/files
The second part of re-opening the issue#29704 can be done once we get this revert in the repo via this PR

Revert misleading link from deprecation notice

---

content/zh-cn/blog/_posts/2019-04-24-Hardware-Accelerated-SSLTLS-Termination-in-Ingress-Controllers-using-Kubernetes-Device-Plugins-and-RuntimeClass.md
content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
content/zh-cn/docs/reference/access-authn-authz/rbac.md
content/zh-cn/docs/reference/glossary/downstream.md
content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md

This PR is for the language zh-cn (Chinese).
Some bold texts marked in markdown are not rendered properly, referring to this blog https://ld246.com/article/1597581380183.
Thus I used the regular expression `[\p{P}]\*\*(?![\p{P}\n\s])` (not precise) to match and find them, and then fixed them.

Add spaces to properly render bold text in Chinese (zh-cn)

---

content/en/docs/contribute/_index.md

**Page Updated:** https://kubernetes.io/docs/contribute/#getting-started
Update broken GitHub Learning link to (https://skills.github.com/)

Fix broken GitHub Learning link in _index.md

---

content/fr/docs/concepts/storage/volumes.md

The link to the page about secrets in the volume is broken in the French documentation.
This commit addresses the broken link on the volume page.

Update fr docs outdated link

---

content/en/examples/validatingadmissionpolicy/replicalimit-param.yaml

Fix wording of `namespace` in validatingadmissionpolicy/replicalimit-param sample

Fix typo in 'replicalimit-param.yaml' example YAML

---

content/en/_index.html

Since KubeCon + CloudNativeCon NA 2024 has passed, it's time to update the dates & links of this event at the https://kubernetes.io/ main page. This PR does it.
Note: [new link](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2024/) to the next (i.e. 2024) NA event went live already but, currently, it features an intro splash only. I guess the full website will follow a bit later. We still

Update KubeCon dates for 2024

---

content/en/examples/application/hpa/php-apache.yaml

Horizontal Pod Autoscaler API version autoscaling/v2 , and it provides more features than autoscaling/v1.
#43685

Change HorizontalPodAutoscaler walkthrough to use autoscaling/v2 API group

---

content/en/docs/concepts/configuration/secret.md

Fix typo in TLS Secrets part.
This seems to be a copy/paste of the same paragraph in the "SSH authentication Secrets" section.

Fix typo in TLS Secrets part

---

content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
content/en/docs/tasks/configmap-secret/managing-secret-using-kustomize.md

supplyment of https://github.com/kubernetes/website/pull/42631
try to fix: https://github.com/kubernetes/website/issues/42603

Document snag with Secrets, stringData, and server-side apply

---

content/en/docs/reference/kubectl/_index.md

When visiting the kubectl docs, the table present at https://kubernetes.io/docs/reference/kubectl/#operations contains a row that describes the "top" command but displays broken or incorrect information.
I found that this problem persisted in other localizations as well.
This PR fixes the broken formatting for the [en] and [zh-cn] docs, and updates the [jp] and [ko] docs.

Fix minor formatting issue in kubectl docs

---

content/en/docs/tutorials/stateful-application/basic-stateful-set.md

`kubectl` can apply manifests direct from the web; let's teach that.
Split out from PR https://github.com/kubernetes/website/pull/42767
[original](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/)
[preview](https://deploy-preview-43984--kubernetes-io-main-staging.netlify.app/docs/tutorials/stateful-application/basic-stateful-set/)

Switch StatefulSet tutorial to HTTP manifest source

---

content/en/docs/reference/using-api/api-concepts.md

- Finalizers are a string array
- Small grammar error

docs: Small fixes to the Resource deletion section of API Concept

---

content/en/docs/concepts/architecture/garbage-collection.md
content/en/docs/concepts/configuration/secret.md
content/en/docs/reference/kubectl/_index.md
content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
content/en/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
content/en/docs/tutorials/stateful-application/basic-stateful-set.md
content/fr/_index.html
content/ru/_index.html
content/uk/_index.html
content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/zh-cn/docs/tasks/debug/debug-cluster/_index.md
content/zh-cn/docs/tasks/tools/included/verify-kubectl.md

Fix a merge conflict provoked by PR #42823

Update dev-1.29 branch to sync with main

---

content/en/docs/concepts/services-networking/service.md

Removed duplicated wording reference to Docker Engine's legacy container links #44272

Remove duplicate references to Docker Engine legacy container feature in "Service" page

---

content/en/docs/concepts/services-networking/ingress-controllers.md

Fixed Broken Voyager link in Ingress controller page
**Page Changed:** https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/#additional-controllers
Changed Link From (https://appscode.com/products/voyager) to (https://voyagermesh.com/)
**[OriginalPage](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/#additional-controllers)  |  [PreviewPage](https://deploy-preview-44276--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/ingress-controllers/#additional-controllers)**

Fix Broken voyager link in ingress-controllers.md

---

hugo.toml

Updates hugo.toml for dev-1.29 ahead of v1.29 release date.

Updates v1.29 hugo.toml to include latest patches ahead of release

---

content/en/docs/concepts/scheduling-eviction/scheduling-framework.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Feature gate SchedulerQueueingHints is disabled by default.
https://github.com/kubernetes/kubernetes/pull/122289
This PR reflects it on the doc.

Feature gate SchedulerQueueingHints is disabled by default

---

config.toml

Updating config.toml for release v1.29.
/hold until v1.29 release day.

Updates v1.25 config.toml for v1.29 release

---

hugo.toml

This PR updates the hugo.toml for v1.28 ahead of the v1.29 release.
Base branch will be updated from main to release-1.28 once that branch exists. 
/hold for v1.29 release day

Update release 1.28 hugo.toml for 1.29 release

---

content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md

[EN]
API object returned in the response, in JSON. The ResponseObject is recorded after conversion to the external type, and serialized as JSON. Omitted for non-resource requests. Only logged at Response Level.
[ZH]
响应中包含的 API 对象，以 JSON 格式呈现。requestObject 是在被转换为外部类型 并序列化为 JSON 格式之后才被记录的。 对于非资源请求，此字段会被忽略。 只有审计级别为 Response 时才会记录。

fix: responseObject error [zh]

---

content/en/blog/_posts/2023-12-13-kubernetes-1.29.md

Go through the [release announcement](https://kubernetes.io/blog/2023/12/13/kubernetes-v1-29-release/) just identified a broken link to the Authors file of the release team members. This PR aims to fix the link.

Fix broken link in v1.29 Release Announcement blog

---

content/en/blog/_posts/2023-12-19-PodReadyToStartContainersCondition-in-beta.md

this PR add blog post to reflect the state of feature: podreadytostartcontainerscondition

Add blog post to reflect state of PodReadyToStartContainersCondition

---

content/en/blog/_posts/2023-12-14-disabling-in-tree-cloud-provider-goes-beta.md

This PR ~is a placeholder for~ _adds_ a blog article on the recent status change for [KEP-2395](https://github.com/kubernetes/enhancements/issues/2395) from alpha to beta.

add blog post for in-tree cloud provider removal going beta

---

content/en/blog/_posts/2023-12-18-kubernetes-1-29-feature-loadbalancer-ip-mode-alpha.md

Blog for new feature LoadBalancerIPMode.
PR link: https://github.com/kubernetes/kubernetes/pull/119937
KEP issue: https://github.com/kubernetes/enhancements/issues/1860

add blog for feature LoadBalancerIPMode

---

content/en/blog/_posts/2023-12-18-read-write-once-pod-access-mode-ga.md

Used the beta graduation blog post as a template: https://github.com/kubernetes/website/pull/39817
Feature: https://github.com/kubernetes/kubernetes/pull/121077
Enhancement: https://github.com/kubernetes/enhancements/issues/2485
/sig storage
CC @msau42

Feature blog for ReadWriteOncePod GA graduation

---

content/en/blog/_posts/2023-12-19-taint-eviction-controller.md

Add a blog for [KEP 3902](https://github.com/kubernetes/enhancements/issues/3902)

Add a blog post about decoupled taint eviction controller

---

content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md

Fixes #44321
Added clear comments to specify that the `kubectl drain` and `kubectl uncordon` commands must be executed on the controlplane node.
Suggestions and feedback are welcome.
Best Regards,
Aditya

Add user guidance comment for executing drain and uncordon on control plane

---

content/en/docs/concepts/architecture/controller.md

The [sample-controller](https://github.com/kubernetes/sample-controller) repository would be helpful if you want to write your own controller.
See [Preview](https://deploy-preview-43774--kubernetes-io-main-staging.netlify.app/docs/concepts/architecture/controller/)

Add a link to sample-controller repository on Controllers page

---

data/releases/schedule.yaml

Resolves https://github.com/kubernetes/website/issues/44330
Despite being reported for a [single page](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/), this is a broader site-wide issue affecting multiple pages using `{{< skew currentPatchVersion >}}`. 
The shortcode "`{{< skew currentPatchVersion >}}`" seems to be struggling to determine the latest patch version with new 1.29 release. The current output from shortcode is `%!f(string=1.).0.` ([see here](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows)). The quick fix involves updating the schedule.yaml to incorporate the latest version, v1.29.0, ensuring the shortcode displays the expected value.
[Fixed Preview …

Add release 1.29 to previousPatches in the schedule.yaml

---

content/en/docs/concepts/overview/working-with-objects/names.md

Add a paragraph explaining what is the difference between RFC 1035
and RFC 1123 labels.
Before this change, the documentation just listed the requirements for
each type of label, which meant the reader had to use their brain to
work out for themselves what the difference actually is. This takes time
and mental load. It is better that the documentation explicitly state
what the actual difference is, so the reader doesn't have to do that.
It will also hopefully reduce the future incidence of people logging
issues due to being confused about the difference between them,
see for example: https://github.com/kubernetes/kubernetes/issues/116964

RFC 1035 vs RFC 1123: clarify the difference

---

content/en/docs/tasks/administer-cluster/kms-provider.md

https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#disabling-encryption-at-rest documents something already covered in https://kubernetes.io/docs/tasks/administer-cluster/decrypt-data/
Link there instead ([preview](https://github.com/kubernetes/website/pull/44086#issuecomment-1831009691)).

Link to existing task about decrypting at rest

---

content/en/docs/reference/networking/virtual-ips.md

The `ServiceIPStaticSubrange` feature gate is GA; you can't disable it. Drop the mention of doing so.
/sig network

Remove stale mention of ServiceIPStaticSubrange

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed/index.md

Document `MultiCIDRRangeAllocator` as a ~deprecated~ removed feature gate.
[[preview](https://deploy-preview-44329--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates-removed/)]
It looks like the v1.29 release removed the docs entirely, which is different from the outcome we want.

Reinstate the MultiCIDRRangeAllocator feature gate

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md

Fix feature gate link to "/docs/reference/command-line-tools-reference/feature-gates/"

Fix broken link in "Container Lifecycle Hooks"

---

content/en/docs/tutorials/hello-minikube.md

It seems a shame to install it and then not show it in use. The first thing I did after installing it and then seeing the next command was to uninstall it was to go and google what it is and how to get data from it.

show the output from metrics server

---

content/en/docs/tutorials/stateful-application/basic-stateful-set.md

Use POSIX-compatible comments to explain the context and expectations to the person following the [tutorial](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) for StatefulSets.
Part of PR #42767

Add comments to shell snippets in StatefulSet tutorial

---

content/en/docs/tasks/administer-cluster/verify-signed-artifacts.md
content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md

While reading the docs about "[Verify Signed Kubernetes Artifacts](https://kubernetes.io/docs/tasks/administer-cluster/verify-signed-artifacts/#verifying-image-signatures-with-admission-controller)" I noticed that the link to the `cosign` (https://docs.sigstore.dev/cosign/keyless) documentation points to a `404 - Not Found` page.
I digged a bit through the cosign documentation and the `/signing/signing_with_containers` seems to the new URL for the same content. It's not a 100% match, but I think provides still the most relevant information for a reader.
- Snapshot of the old `/cosign/keyless`: https://web.archive.org/web/20230301012402/https://docs.sigstore.dev/cosign/keyless/
- The new `/signing/signing_with_containers`: https://docs.sigstore.dev/signing/signing_with_containers/
This PR …

Fix broken hyperlink for 'Cosign Keyless Signatures' in "Verify Signed Kubernetes Artifacts" guide

---

content/zh-cn/docs/reference/using-api/deprecation-guide.md
content/zh-cn/docs/tasks/administer-cluster/kms-provider.md
content/zh-cn/docs/tasks/extend-kubernetes/configure-multiple-schedulers.md

[zh-cn] sync kms-provider configure-multiple-schedulers deprecation-guide

---

content/en/docs/reference/using-api/client-libraries.md

Updated URL of dotnet sample programs to point to the project's sample folder, like in other clients.

Updated dotnet - Sample Programs url to point the example folder of project

---

content/es/docs/tasks/tools/included/optional-kubectl-configs-fish.md

This is a Feature Request closes https://github.com/kubernetes/website/issues/44380
What would you like to be added
Localize content/en/docs/tasks/tools/included/optional-kubectl-configs-fish.md to Spanish
Why is this needed
There is no Spanish localization for this file.

[es] localize content/en/docs/tasks/tools/included/optional-kubectl-configs-fish.md to Spanish

---

content/es/docs/tasks/run-application/delete-stateful-set.md

This is a Feature Request related to #41878 
What would you like to be added
Localize content/en/docs/tasks/run-application/delete-stateful-set.md to Spanish
Why is this needed
There is no Spanish localization for this file.

[es] localize content/en/docs/tasks/run-application/delete-stateful-set.md to Spanish

---

content/en/docs/concepts/windows/intro.md

This updates the Windows nodes in Kubernetes intro paragraph to clarify it from the beginning that Windows Server 2019 is not a required version to run Windows node.
It also aligns the intro with the detailed Windows OS version compatibility section below.

Mention Windows Server 2022 for Windows nodes

---

content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

Was trying new release and looking at the instructions https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository/ there is minor correction needed in the instruction involving yum.
Edit: This will fix https://github.com/kubernetes/website/issues/44437

Fix typo in instruction for Kubernetes repository configuration on CentOS/RHEL/Fedora

---

content/en/docs/tasks/debug/debug-cluster/crictl.md

Using crictl to create a container is useful for debugging container runtimes. On a running Kubernetes cluster, the sandbox will eventually be stopped and deleted by the Kubelet.
the  container not the sandbox.

fix: container not sandbox

---

content/en/docs/concepts/storage/storage-classes.md

The CSI support for `allowVolumeExpansion` went GA in the 1.24 release. This was reflected [in the Persistent Volume documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#csi-volume-expansion) (#36962), but there is also a reference in the Storage Class docs that had not been updated yet to show it was no longer in beta.

Reflect CSI allowVolumeExpansion stable status

---

content/en/blog/_posts/2023-12-20-contextual-logging-in-kubernetes-1-29.md

This is a fixup for https://github.com/kubernetes/website/pull/43579 - I got the URL wrong.

Fix canonical URL

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/accelerators.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/admission-webhook-match-conditions.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/advanced-auditing.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/affinity-in-annotations.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/aggregated-discovery-endpoint.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-ext-traffic-local-endpoints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-insecure-backend-proxy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/any-volume-data-source.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-list-chunking.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-priority-and-fairness.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-response-compression.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-self-subject-review.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-server-identity.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-server-tracing.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/apparmor.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/attach-volume-limit.md

Add zh text to all filename prefixed with "a" in
```
```
1. accelerators.md
2. admission-webhook-match-conditions.md
3. advanced-auditing.md
4. affinity-in-annotations.md
5. aggregated-discovery-endpoint.md
6. allow-ext-traffic-local-endpoints.md
7. allow-insecure-backend-proxy.md
8. any-volume-data-source.md
9. api-list-chunking.md
10. api-priority-and-fairness.md
11. api-response-compression.md
12. api-self-subject-review.md
13. api-server-identity.md
14. api-server-tracing.md
15. apparmor.md
16. attach-volume-limit.md

[zh] Localize /feature-gates/a*.md

---

content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

I made the fix to ENglish page as part of https://github.com/kubernetes/website/pull/44439/files. Submitted same fix for Chinese language.

[zh] Fix typo in instruction for Kubernetes repository configuration on CentOS/RHEL/Fedora 

---

content/en/docs/concepts/storage/storage-classes.md
content/en/examples/storage/storageclass-low-latency.yaml

Update https://kubernetes.io/docs/concepts/storage/storage-classes/ in light of v1.28 changes and for general tidying.
Also, swap an example manifest to use `code` shortcode.

Revise StorageClass docs

---

content/en/docs/reference/kubectl/quick-guide.md
content/en/docs/reference/kubectl/quick-reference.md
static/_redirects

Summary of PR changes as requested in #43433
-   Changed the title and URL for kubectl/cheatsheet/ to kubectl/quick-reference
-   Added redirect from kubectl/cheatsheet/ to the new page
-   Set up a new short URL
I have gone through the previous commits in the website and come up with theses changes. Do review and feedback. Aplogies if changes are not as expected.
This will fix #43433

Change title and add redirects for kubectl cheatsheet

---

content/en/docs/reference/using-api/deprecation-guide.md

This seems to have been erroneously copy-pasted from the v1.29 paragraph. It should be `v1beta2` and that's available since before `1.0.0`. I did not check for the exact version because I think no one cares.

Fix typo in deprecation-guide.md at v1.26

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_super-admin.conf.md

```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_super-admin.conf.md
```
See [preview](https://deploy-preview-44354--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_renew_super-admin.conf/) please.

[zh] Localize kubeadm_certs_renew_super-admin.conf.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed/index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/api-self-subject-review.md
content/en/docs/reference/command-line-tools-reference/feature-gates/index.md

ref https://github.com/kubernetes/kubernetes/issues/120315
feature-gate was removed by https://github.com/kubernetes/kubernetes/pull/122032

remove GA feature-gate APISelfSubjectReview

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/daemon-set-update-surge.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/default-host-network-ports-in-pod-templates.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/default-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/delegate-fs-group-to-csi-driver.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/device-plugin-cdi-devices.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/device-plugins.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-accelerator-usage-metrics.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-cloud-providers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-kubelet-cloud-credential-providers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-node-kube-proxy-version.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/downward-api-huge-pages.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dry-run.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-auditing.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-kubelet-config.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-provisioning-scheduling.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-resource-allocation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-volume-provisioning.md

Localize feature-gates/d*.md
1. daemon-set-update-surge.md
2. default-host-network-ports-in-pod-templates.md
3. default-pod-topology-spread.md
4. delegate-fs-group-to-csi-driver.md
5. device-plugin-cdi-devices.md
6. device-plugins.md
7. disable-accelerator-usage-metrics.md
8. disable-cloud-providers.md
9. disable-kubelet-cloud-credential-providers.md
10. disable-node-kube-proxy-version.md
11. downward-api-huge-pages.md
12. dry-run.md
13. dynamic-auditing.md
14. dynamic-kubelet-config.md
15. dynamic-provisioning-scheduling.md
16. dynamic-resource-allocation.md
17. dynamic-volume-provisioning.md

[zh] Localize feature-gates/d*.md

---

content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
content/en/docs/tasks/job/fine-parallel-processing-work-queue.md
content/en/examples/application/job/rabbitmq/rabbitmq-service.yaml
content/en/examples/application/job/rabbitmq/rabbitmq-statefulset.yaml

I've made some changes to some of the tutorials for Job:
- https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/
- https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/
Now, the tutorials match our style guide a lot better.
There's a lot more to do! Ideally we'd redo them from the ground up.
However, I hope these look like a positive set of changes to make, for now.

Improve tutorials for Job

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_super-admin.md

```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_super-admin.md
```
See [preview](https://deploy-preview-44361--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_super-admin/) please.

[zh] Localize kubeadm_init_phase_kubeconfig_super-admin.md

---

content/en/docs/concepts/configuration/manage-resources-containers.md

Fixes #38472 .
Improve wording on `manage-resource-containers.md` > Note on the CPU resource unit allocation > regarding using milliCPU form. Attempted to make it more clear that using milliCPU for fractional requests makes it easier to avoid the pitfall of using invalid quantities. 
This is my first PR, so open to any feedback or comments.

fix: update note on manage-resources-containers.md on using milliCPU form

---

content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md

Fixed a typo by replacing `_NumNodes` with `NumNodes`

Fixed a typo on page "Create an External Load Balancer"

---

content/en/docs/concepts/workloads/pods/sidecar-containers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/sidecar-containers.md

Revise details for sidecar containers

---

content/en/docs/tutorials/stateful-application/basic-stateful-set.md

Update the [tutorial](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) for StatefulSets to write headings in sentence case, per the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/#headings).
Part of PR #42767
/kind cleanup

Write headings in sentence case for StatefulSet tutorial

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed/index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/index.md

-  Fixed Typo in Feature Name `PersistentVolumeLastPhaseTransitionTime`
- **_Reference_**: [kubernetes/pkg/features/kube_features.go](https://github.com/kubernetes/kubernetes/blob/f68a965e5ae7a954b567c6162de0e2d17606d680/pkg/features/kube_features.go#L590) or [enhancements/KEP-3762](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/3762-persistent-volume-last-phase-transition-time/README.md)
- Correct Minor Typo in version format for `ZeroLimitedNominalConcurrencyShares`
-  All version values in the table follow a consistent format without 'v'.
-  Update Punctuation in Removed Feature Gates table for `SetHostnameAsFQDN`
- ',' _(comma)_ was used instead of '.' _(dot)_ for separation.
[Preview Page  1 ](https://deploy-preview-44469--kubernetes-io-main-staging.netlify.ap …

Fix typos in Feature gates tables

---

content/en/docs/tasks/configure-pod-container/static-pod.md

This PR tries to fix #32835 
This PR contains the following changes:
1. Reflect the "staticPodPath" as the primary option to configure the directory holding the static pod manifests.
2. Specify in a note block that the option to configure this using an argument is now deprecated.
I am personally of the opinion that it is not necessary to mention the deprecated option anymore.
If reviewers agree, I could remove the reference to the deprecated option altogether.
Suggestions and feedback are welcome.
Best Regards,
Aditya

Changes to reflect the deprecation of pod-manifest-path argument

---

content/en/docs/tasks/tools/install-kubectl-macos.md

Sumary of cahnges:
Step 4 of the  https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-kubectl-binary-with-curl-on-macos,  tells users to move kubectl binary to a file location on your system PATH but then Step 6 ask the user to delete kubectl along with kubectl.sha256 file, but kubectl is already moved in Step 4. Also, there is section to remove kubectl below in the same page so I change the Step 6 to remove the sha file only now.
This will fix https://github.com/kubernetes/website/issues/44019

 Fix cleanup instruction in macOS kubectl installation page

---

layouts/index.rss.xml

Improve the formatting of the Kubernetes RSS feed.
**Title**
* _old:_ "Kubernetes - Production Grade Container Orchestration"
* _new:_ "Kubernetes Blog"
This feed is for the Kubernetes blog, and so the title now more accurately reflects that.
**Post titles**
* _old:_ "Blog: Title of post"
* _new:_ "Title of post"
This feed is only used for blog posts, so there's no need to prefix "Blog:" in front of every entry.
**Other minor changes**
* Updated the description (from the blog submission guidelines)
* Changed the <image> tag to correctly act as alt text for the logo
* Correct indentation of one meaningless thing to please my sense of aligment

Modify RSS XML

---

content/en/docs/reference/command-line-tools-reference/feature-gates/index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/stateful-set-auto-delete-pvc.md

This pull request addresses the missing description for the `StatefulSetAutoDeletePVC` feature gate, which despite being listed in the table on the [documentation page](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features), lacks a brief description.
[Preview Page](https://deploy-preview-44465--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/)

Add description for "StatefulSetAutoDeletePVC" feature gate

---

content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

Related to PR #44477
The configure probe doc missing link anchor: https://github.com/kubernetes/website/pull/44477/files#diff-67c0aa7eef1f10a118f3befbb8c8cd13377a94db42466814d582be75f49f68eaR13
---
See the preview of link anchor: https://deploy-preview-44492--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe

[zh] Add missing link anchor of configure probe

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/accelerators.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/admission-webhook-match-conditions.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/advanced-auditing.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/affinity-in-annotations.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/aggregated-discovery-endpoint.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-ext-traffic-local-endpoints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-insecure-backend-proxy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/any-volume-data-source.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-list-chunking.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-priority-and-fairness.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-response-compression.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-self-subject-review.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-server-identity.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-server-tracing.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/apparmor.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/attach-volume-limit.md

Add the new 'stages' metadata to all zh feature gate filename prefixed with "a" in
```
```
1. accelerators.md
2. admission-webhook-match-conditions.md
3. advanced-auditing.md
4. affinity-in-annotations.md
5. aggregated-discovery-endpoint.md
6. allow-ext-traffic-local-endpoints.md
7. allow-insecure-backend-proxy.md
8. any-volume-data-source.md
9. api-list-chunking.md
10. api-priority-and-fairness.md
11. api-response-compression.md
12. api-self-subject-review.md
13. api-server-identity.md
14. api-server-tracing.md
15. apparmor.md
16. attach-volume-limit.md

[zh] Sync /feature-gates/a*.md 

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/balance-attached-node-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/block-volume.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/bound-service-account-token-volume.md

Add the new 'stages' metadata to all zh feature gate filename prefixed with "b" in
```
```
1. balance-attached-node-volumes
2. block-volume
3. bound-service-account-token-volume

[zh] Sync /feature-gates/b*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/gce-regional-persistent-disk.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/generic-ephemeral-volume.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/graceful-node-shutdown-based-on-pod-priority.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/graceful-node-shutdown.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/grpc-container-probe.md

Add the new 'stages' metadata to all zh feature gate filename prefixed with "g" in
```
```
1. gce-regional-persistent-disk.md
2. generic-ephemeral-volume.md
3. graceful-node-shutdown-based-on-pod-priority.md
4. graceful-node-shutdown.md
5. grpc-container-probe.md

[zh] Sync feature-gates/g*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-backoff-limit-per-index.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-mutable-node-scheduling-directives.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-pod-failure-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-pod-replacement-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-ready-pods.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-tracking-with-finalizers.md

Related to issue #44410. Add zh text to these pages:
1. job-backoff-limit-per-index
2. job-mutable-node-scheduling-directives
3. job-pod-failure-policy
4. job-pod-replacement-policy
5. job-ready-pods
6. job-tracking-with-finalizers

[zh] Localize feature-gates/j*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/image-maximum-gc-age.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-aws-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-azure-disk-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-azure-file-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-gce-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-openstack-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-portworx-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-rbd-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-vsphere-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/indexed-job.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ingress-class-namespaced-params.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/initializers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ip-tables-ownership-cleanup.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ipv6-dual-stack.md

Related to issue #44410.  Mostly updated the front matters:
1. in-tree-plugin-aws-unregister.md
2. in-tree-plugin-azure-disk-unregister.md
3. in-tree-plugin-azure-file-unregister.md
4. in-tree-plugin-gce-unregister.md
5. in-tree-plugin-openstack-unregister.md
6. in-tree-plugin-portworx-unregister.md
7. in-tree-plugin-rbd-unregister.md
8. in-tree-plugin-vsphere-unregister.md
9. indexed-job.md
10. ingress-class-namespaced-params.md
11. initializers.md
12. ip-tables-ownership-cleanup.md
13. ipv6-dual-stack.md
14. image-maximum-gc-age.md

[zh] Sync feature-gates/i*.md

---

content/en/docs/tasks/administer-cluster/encrypt-data.md

This PR is heavily inspired by https://github.com/kubernetes/website/pull/33285 but has some custom changes.
- Explain importance of protecting keys and other material that can be
used to decrypt data in etcd
- Revise the explanation for a non-KMS setup example
- Explicitly link to https://k8s.io/docs/tasks/administer-cluster/kms-provider/

Explain more about protection for encryption keys (API data encryption at rest)

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/daemon-set-update-surge.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/default-host-network-ports-in-pod-templates.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/default-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/delegate-fs-group-to-csi-driver.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/device-plugin-cdi-devices.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/device-plugins.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-accelerator-usage-metrics.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-cloud-providers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-kubelet-cloud-credential-providers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-node-kube-proxy-version.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/downward-api-huge-pages.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dry-run.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-auditing.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-kubelet-config.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-provisioning-scheduling.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-resource-allocation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-volume-provisioning.md

Add the new 'stages' metadata in the **_front matter_** of all zh feature gate filename prefixed with "d" in
```
```
1. daemon-set-update-surge.md
2. default-host-network-ports-in-pod-templates.md
3. default-pod-topology-spread.md
4. delegate-fs-group-to-csi-driver.md
5. device-plugin-cdi-devices.md
6. device-plugins.md
7. disable-accelerator-usage-metrics.md
8. disable-cloud-providers.md
9. disable-kubelet-cloud-credential-providers.md
10. disable-node-kube-proxy-version.md
11. downward-api-huge-pages.md
12. dry-run.md
13. dynamic-auditing.md
14. dynamic-kubelet-config.md
15. dynamic-provisioning-scheduling.md
16. dynamic-resource-allocation.md
17. …

[zh] Sync feature-gates/d*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/match-label-keys-in-pod-affinity.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/match-label-keys-in-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/max-unavailable-stateful-set.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/memory-manager.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/memory-qos.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/min-domains-in-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/minimize-ip-tables-restore.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mixed-protocol-lb-service.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mount-containers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mount-propagation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/multi-cidr-range-allocator.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/multi-cidr-service-allocator.md

Add the new 'stages' metadata in the front matter of all zh feature gate filename prefixed with "m" in
```
```
1. match-label-keys-in-pod-affinity
2. match-label-keys-in-pod-topology-spread
3. max-unavailable-stateful-set
4. memory-manager
5. memory-qos
6. min-domains-in-pod-topology-spread
7. minimize-ip-tables-restore
8. mixed-protocol-lb-service
9. mount-containers
10. mount-propagation
11. multi-cidr-range-allocator
12. multi-cidr-service-allocator

[zh] Sync feature-gates/m*.md

---

content/en/docs/concepts/security/pod-security-standards.md
content/en/docs/tasks/administer-cluster/sysctl-cluster.md

https://github.com/kubernetes/kubernetes/blob/v1.29.0/staging/src/k8s.io/pod-security-admission/policy/check_sysctls.go#L80
https://github.com/kubernetes/kubernetes/blob/v1.29.0/pkg/kubelet/sysctl/safe_sysctls.go#L34

update safe sysctls (v1.29)

---

content/en/docs/concepts/storage/volumes.md

Update https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
[[Preview](https://deploy-preview-42510--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/volumes/#hostpath)]
- Combine existing callouts into one warning callout
- Suggest `local` volumes as a more secure alternative
- Add a heading for the section about the `type` field
- Mention OS restrictions for `hostPath` types (you cannot use `CharDevice` or `BlockDevice` in Windows pods)
- Provide examples for Linux and for Windows (showing the different conventions for escaping paths)
- Improve readability
/sig storage

Revise details for hostPath volumes

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/schedule-daemon-set-pods.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/scheduler-queueing-hints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/sctp-support.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/seccomp-default.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/security-context-deny.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/selector-index.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/selinux-mount-read-write-once-pod.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/separate-taint-eviction-controller.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/server-side-apply.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/server-side-field-validation.md

Localize part 1 10 files of feature-gates/s*.md:
1. schedule-daemon-set-pods.md
1. scheduler-queueing-hints.md
1. sctp-support.md
1. seccomp-default.md
1. security-context-deny.md
1. selector-index.md
1. selinux-mount-read-write-once-pod.md
1. separate-taint-eviction-controller.md
1. server-side-apply.md
1. server-side-field-validation.md

[zh] Localize feature-gates/s*.md part 1

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/openapi-enums.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/openapiv3.md

Related to issue #44410 . Add zh text to these pages:
1. openapi-enums.md
2. openapiv3.md

[zh] Localize feature-gates/o*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kube-proxy-draining-terminating-nodes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-plugins-watcher.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-dynamic-resources.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-get-allocatable.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-get.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-separate-disk-gc.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-tracing.md

Related to issue #44410. Localized these files:
1.  kube-proxy-draining-terminating-nodes.md       
2.  kubelet-plugins-watcher.md
3.  kubelet-pod-resources-dynamic-resources.md     
4.  kubelet-pod-resources-get-allocatable.md       
5.  kubelet-pod-resources-get.md
6.  kubelet-pod-resources.md
7.  kubelet-separate-disk-gc.md
8.  kubelet-tracing.md

[zh] Localize part2 of /feature-gates/k*.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md

Update file:
```
content/en/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md
```
Fix missing backtick of field `nominalConcurrencyShares`.
---
See [preview](https://deploy-preview-44563--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/#feature-gates).

Fix feature-gates/z*.md content format

---

content/zh-cn/docs/concepts/workloads/controllers/job.md

* Sync en upstream
* Fix link anchor
* Fix inconsistent translation
Related to PR #44476 
The invalid [link anchor of elastic indexed jobs](https://github.com/kubernetes/website/pull/44476/files#diff-84ae4d9f0b348280f410f896f7b57c265be5a202707185a9d6c51f7f1714c98cR16)
Fix link anchor that mismatched with en version.
---
See preview and link anchor: https://deploy-preview-44491--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/job/#elastic-indexed-jobs

[zh] Sync controllers/job.md and fix link anchor

---

content/zh-cn/blog/_posts/2023-12-19-taint-eviction-controller.md

content/zh-cn/blog/_posts/2023-12-19-taint-eviction-controller.md
[preview](https://deploy-preview-44427--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/12/19/kubernetes-1-29-taint-eviction-controller)

[zh] Localize a blog: taint-eviction-controller.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-issuer-discovery.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-jti.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding-validation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-pod-node-info.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-app-protocol.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-internal-traffic-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-ip-static-subrange.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-lb-node-port-control.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-load-balancer-class.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-load-balancer-finalizer.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-node-exclusion.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-nodeport-static-subrange.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-topology.md

Localize part 2 14 files of feature-gates/s*.md
1. service-account-issuer-discovery.md
1. service-account-token-jti.md
1. service-account-token-node-binding-validation.md
1. service-account-token-node-binding.md
1. service-account-token-pod-node-info.md
1. service-app-protocol.md
1. service-internal-traffic-policy.md
1. service-ip-static-subrange.md
1. service-lb-node-port-control.md
1. service-load-balancer-class.md
1. service-load-balancer-finalizer.md
1. service-node-exclusion.md
1. service-nodeport-static-subrange.md
1. service-topology.md

[zh] Localize feature-gates/s*.md part 2

---

content/zh-cn/docs/concepts/security/pod-security-standards.md
content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
content/zh-cn/docs/tasks/administer-cluster/sysctl-cluster.md

[zh-cn] sync pod-security-standards.md user-namespaces.md sysctl-cluster.md

---

content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md

The feature-gate `ServiceAccountIssuerDiscovery` is referring this link anchor:
```
/zh-cn/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery
```
---
See preview link anchor: https://deploy-preview-44591--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery

[zh] Fix link anchor in configure-service-account.md

---

content/en/docs/concepts/configuration/secret.md

Fix a mistake in Secrets concept

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/set-hostname-as-fqdn.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/sidecar-containers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/size-memory-backed-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/skip-read-only-validation-gce.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stable-load-balancer-node-set.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/startup-probe.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stateful-set-auto-delete-pvc.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stateful-set-min-ready-seconds.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stateful-set-start-ordinal.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/storage-object-in-use-protection.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/storage-version-api.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/storage-version-hash.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/streaming-proxy-redirects.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/structured-authentication-configuration.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/structured-authorization-configuration.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/support-ipvs-proxy-mode.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/support-node-pids-limit.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/support-pod-pids-limit.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/suspend-job.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/sysctls.md

Localize part 3 20 files of feature-gates/s*.md
1. set-hostname-as-fqdn.md
1. sidecar-containers.md
1. size-memory-backed-volumes.md
1. skip-read-only-validation-gce.md
1. stable-load-balancer-node-set.md
1. startup-probe.md
1. stateful-set-auto-delete-pvc.md
1. stateful-set-min-ready-seconds.md
1. stateful-set-start-ordinal.md
1. storage-object-in-use-protection.md
1. storage-version-api.md
1. storage-version-hash.md
1. streaming-proxy-redirects.md
1. structured-authentication-configuration.md
1. structured-authorization-configuration.md
1. support-ipvs-proxy-mode.md
1. support-node-pids-limit.md
1. support-pod-pids-limit.md
1. suspend-job.md
1. sysctls.md

[zh] Localize feature-gates/s*.md part 3

---

netlify.toml

Closes #43671
The change is tested locally, Website container builds on v0.120.3 now

Bump Hugo to v0.120.3

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-ready-to-start-containers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-scheduling-readiness.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-security.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-share-process-namespace.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/prefer-nominated-node.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/probe-termination-grace-period.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/proc-mount-type.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/proxy-terminating-endpoints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pvc-protection.md

Related to issue #44410. Localize these fiels:
1. pod-ready-to-start-containers.md
2. pod-scheduling-readiness.md
3. pod-security.md
4. pod-share-process-namespace.md
5. prefer-nominated-node.md
6. probe-termination-grace-period.md
7. proc-mount-type.md
8. proxy-terminating-endpoints.md
9. pvc-protection.md

[zh] Localize part3 of feature-gates/p*.md

---

content/en/docs/contribute/_index.md
content/en/docs/contribute/docs.md
content/en/docs/home/_index.md

There are lots of ways to get involved. Make it easier to discover what those are.
- [Preview 1](https://deploy-preview-44559--kubernetes-io-main-staging.netlify.app/docs/home/)
- [Preview 2](https://deploy-preview-44559--kubernetes-io-main-staging.netlify.app/docs/contribute/)
I opened this PR to show my alternative take on the change proposed in https://github.com/kubernetes/website/pull/43948.
/label refactor

Emphasize contributions other than docs

---

content/en/docs/reference/config-api/kubelet-config.v1beta1.md

[en] Update go lang link kubelet-config.v1beta1.md

---

assets/scss/_custom.scss
layouts/partials/search-input.html

This PR fixes the `Search-icon` disappearance issue when typing something in the search bar. Earlier the magnifying glass symbol was kept within the placeholder of the input form, so whenever something was typed the `Search-icon` would disappear too along with the placeholder comments `Search this site`. I have fixed that in this PR and now the magnifying glass `Search-icon` stays in place at the left-most side of the search bar. 
This is in the context of the issue #44416.

Fix search-icon when typing

---

OWNERS_ALIASES

Inviting @Gauravpadam to join the blog team as a reviewer.

Add Gaurav Padam to blog team

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/legacy-node-role-behavior.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-clean-up.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-no-auto-generation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-tracking.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/load-balancer-ip-mode.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/local-storage-capacity-isolation-fs-quota-monitoring.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/local-storage-capacity-isolation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/logarithmic-scale-down.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/logging-alpha-options.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/logging-beta-options.md

Related to issue #44410. Localize these files:
1. legacy-node-role-behavior.md
2. legacy-service-account-token-clean-up.md
3. legacy-service-account-token-no-auto-generation.md
4. legacy-service-account-token-tracking.md
5. load-balancer-ip-mode.md
6. local-storage-capacity-isolation-fs-quota-monitoring.md
7. local-storage-capacity-isolation.md
8. logarithmic-scale-down.md
9. logging-alpha-options.md
10. logging-beta-options.md

[zh] Localize feature-gates/l*.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/identify-pod-os.md

Now that the `IdentifyPodOS` feature gate is removed, we can rely on the main Pod documentation to explain what operating systems Kubernetes can support for Pods.
As a result, we can have a simpler description.
[preview](https://deploy-preview-44623--kubernetes-io-main-staging.netlify.app//docs/reference/command-line-tools-reference/feature-gates-removed/)
/sig node
/kind cleanup

Simplify description for IdentifyPodOS

---

README.md

Add link for the video in README.md  for issue https://github.com/kubernetes/website/issues/42927
What would you like to be added
Add a tutorial video [YouTube video link](https://youtu.be/1SDYzXtD5JA?si=-Ap7OcaYRV0vviql) to the contributing section of Readme.md
Why is this needed
It covers almost all the doubts of a beginner starting out in #sig-docs and very helpful for especially for those people who prefers to learn through video tutorials.

Added-link-beginner-starting-out-in-#sig-docs

---

content/en/docs/concepts/services-networking/network-policies.md

This PR aims to clarify two things:
1. Reply traffic is implicitly allowed by NetPol
2. Creating/Editing NetPol in a disruptive manner to existing connections is implementation defined behavior.
Closes #120525 (https://github.com/kubernetes/kubernetes/issues/120525)

Clarify NetPol applies to connections, not pkts

---

content/en/docs/reference/command-line-tools-reference/feature-gates/logging-alpha-options.md
content/en/docs/reference/command-line-tools-reference/feature-gates/logging-beta-options.md

As reported in issue 44625, found the files within content/en/docs/reference/command-line-tools-reference/feature-gates/ that contain the typo and fixed it.
Closes https://github.com/kubernetes/website/issues/44625

Fix typo in feature gates page

---

hugo.toml

This Pr address the issue https://github.com/kubernetes/website/issues/44603 to remove deprecation warnings during build.
I made change to remove following warning as request in https://github.com/kubernetes/website/pull/43672#pullrequestreview-1696117277:
a) Removed "taxonomyterm" to fix the below error:
"2:48:45 PM: WARN DEPRECATED: Kind "taxonomyterm" used in disableKinds is deprecated, use "taxonomy" instead."
b) Shifted "languages.description" and "languagenamelatinscript" feilds to be under language.params
```
2:48:45 PM: WARN config: languages.id.description: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.id.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
2:48:45 PM: …
```

Fixes to address Hugo deprecation warnings during build

---

content/en/docs/concepts/overview/components.md
content/en/docs/reference/glossary/replica.md

This PR updates https://kubernetes.io/docs/concepts/overview/components/
Fixes: #41576
This adds a tooltip for replicas text and includes replicas in the glossary.

Add and use glossary entry for “replica”

---

content/en/docs/tasks/configure-pod-container/configure-service-account.md

Fixes https://github.com/kubernetes/kubernetes/issues/119650
https://github.com/kubernetes/website/blob/c818b277f0001e743f0758a98a7605b8a91fa270/content/en/docs/tasks/configure-pod-container/configure-service-account.md?plain=1#L273-L277

Make image registry hostname more obvious in example

---

static/css/community.css

1. Fixed overflowed line through of headings, use a better solution to achieve the same effect
2. Adjusted the font size of headings when in smaller screens, it was way too big for mobile devices and reduces readability
3. Added paddings for the Recent News section, it used to have no paddings and looks weird
4. Adjusted the navigation anchor links for sections, the button style was way too big and not harmony with the rest of the design pattern
5. Added comments for blocks
6. Make it more consistent for paddings, margins and other styles for each of the sections
7. Fixed the entangled styles with the size of view ports, make it more smoother when resizes
8. Remove hard-coded paddings and margins
9. Fixed incorrect vw unit usages, center navigation items, linted function calls
10. Added …

Fix varies of style issues for community page

---

content/de/docs/concepts/architecture/control-plane-node-communication.md

Modified content/de/docs/concepts/architecture/master-node-communication.md to remove the master/slave terminology

[de] modified master-node-communication.md to remove master/slave terminology

---

content/de/docs/concepts/architecture/cgroups.md
content/de/docs/reference/glossary/cgroup.md

Translate the page content/de/docs/concepts/architecture/cgroups.md and the tooltip content/de/docs/reference/glossary/cgroup.md to German

[de] localize content/de/docs/concepts/architecture/cgroups.md for German

---

content/en/docs/tasks/administer-cluster/encrypt-data.md

Two commits split out from #33285
- When you have set up your cluster for encryption at rest, you can take a defence in depth measure to make sure that anything held without encryption causes a retrieval error (which is then more likely to flag that there is a problem). Document that.
- Revise guidance for rotating a decryption key
/sig security
/sig auth

Improve docs around API data encryption at rest

---

content/en/examples/application/guestbook/frontend-deployment.yaml
content/en/examples/application/guestbook/redis-follower-deployment.yaml

Replaced unavailable image in https://k8s.io/docs/tutorials/stateless-application/guestbook/

---

content/en/docs/reference/using-api/cel.md

We need to be transparent about exactly CEL is configured for each Kubernetes version. This documents the functionality added so far.
Quantity library is being documented in a separate PR so I've excluded that here.

Document CEL option, library and language feature availability by version

---

content/en/docs/concepts/security/security-checklist.md

Fixes #42351 
The enable logs handler flag is removed as per the issue raised in #42351

Remove API server --enable-logs-handler argument from docs

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html
content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
content/en/docs/tutorials/kubernetes-basics/update/update-intro.html

Updated /content/en/docs/tutorials/kubernetes-basics/deploy-intro.html to update-intro.html
- Remove extra </p> tag from the docs
- Updated headings in expose-intro.html and update-intro.html

Fix markup for tutorials

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

The note about the keyring directory not existing applies to a step earlier in the document, I think it'd make more sense for it to be moved closer to the relevant section (underneath where the user would pull down the signing key vs underneath the final step in the workflow)

Move note about keyring directory closer to wher it is used

---

content/en/docs/tutorials/kubernetes-basics/update/update-intro.html

I was tripped up while reading the paragraph that explains what a rolling update is and how it works. This commit makes some small phrasing and grammatical changes to make the explanation easier to read. 
It also replaces the word "updates" with "replaces", since, based on my understanding, rolling updates create *new* pods which replace the old ones, rather than updating the current pods. (If there's more nuance to this or "updates" is a more accurate word, happy to change this.)

Clarify explanation of rolling updates

---

content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md

I have received feedback that it's not clear from the [legacy repositories deprecation announcement](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/) what releases are available in the community-owned package repositories. Instead, the `Timeline of changes` section is giving a feeling that only v1.28.2, v1.27.6, v1.26.9, v1.25.14, and onwards are available.
This PR is supposed to address this feedback by adding a short section explaining that releases starting with v1.24.0 are available in the community-owned package repositories.

Update legacy packages blog post with a note about available releases

---

content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md

This PR updates the original announcement blog post for `pkgs.k8s.io` to highlight that the legacy repositories are going away in January 2024 and to make it explicit that the new package repositories have releases starting with v1.24.0.
Relevant to https://github.com/kubernetes/website/pull/44719

Update pkgs.k8s.io blog post with information about removing legacy repos

---

static/_redirects

As requeested in https://github.com/kubernetes/website/issues/44635 in this PR I have replaced https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands with a redirect to https://kubernetes.io/docs/reference/kubectl
This will fix https://github.com/kubernetes/website/issues/44635

Update redirects for kubectl reference page

---

hugo.toml

This commit will modify `hugo.toml` to have a new configuration block for the Arabic localization. Arabic is an RTL language.
This commit is part of a larger effort to initiate an Arabic localization of the
Kubernetes documentation. It contributes to achieving step 8 of the plan detailed in #44682:
> 8. Open a PR to configure a localization environment
> Note: base and target branches of the PR should be the dev branch of AR.
> [TODO] Add a configuration block for the new language to hugo.toml
> https://kubernetes.io/docs/contribute/localization/#modify-the-site-configuration
Note that this PR introduces the first spelling of "Kubernetes" in Arabic,
and as such, sets the standard for how the word should be spelled throughout
the documentation.

Add configuration block for Arabic to hugo.toml

---

content/en/docs/tasks/administer-cluster/coredns.md

Fixed installation guide in "using CoreDNS for Service Discovery" page which was leading to https://github.com/coredns/deployment/tree/master/kubernetes

fixed installation guide in using CoreDNS for Service Discovery page

---

content/en/docs/concepts/workloads/controllers/cron-jobs.md

The cron scheduling syntax documentation was copied from somewhere else, and included an optional part of the spec (sundays can be referenced as 0 or 7) that is not implemented by kubernetes. This is unnecessarily confusing.

fix: clarify day of the week in cron job documentation

---

content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Fixes #44749
The tutorial for [Running Multiple Instances of Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/) has been improved.
The reader's minikube environment lacks a NodePort service as it is deleted in Step 3 of the [previous section](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/).
This PR mentions the command to create the service again, as it is required in the tutorial.
The PR adds a minor fix in the [Using a Service to Expose Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/) page, as it missed a section labeled as `Step 2`

Add the command exposing the Deployment in the tutorial for scaling an application

---

content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md

Fixes #44728 
The [Configure a Pod to Use a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) page contains a section called [Project keys to specific paths and file permissions](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#project-keys-to-specific-paths-and-file-permissions).
This section contains a link to a corresponding section in the Secrets guide. The link does not take the user to the precise location.
This PR improves the reader's experience while navigating through this section, by redirecting to the exact locations in the Secrets guide.
Regards,
Aditya

Fix links related to projection of keys and file permissions in the ConfigMap documentation

---

content/de/docs/reference/glossary/cloud-controller-manager.md
content/de/docs/reference/glossary/cluster.md
content/de/docs/reference/glossary/container.md
content/de/docs/reference/glossary/control-plane.md
content/de/docs/reference/glossary/deployment.md
content/de/docs/reference/glossary/docker.md

[de] This PR is to add  the German localization of the following files:
/content/de/doc/reference/glossary/cloud-controller-manager.md
/content/de/doc/reference/glossary/cluster.md
/content/de/doc/reference/glossary/container.md
/content/de/doc/reference/glossary/control-plane.md
/content/de/doc/reference/glossary/deployment.md
/content/de/doc/reference/glossary/docker.md

[de] German localization of more glossary entries

---

content/de/docs/reference/glossary/kubeadm.md
content/de/docs/reference/glossary/label.md
content/de/docs/reference/glossary/master.md
content/de/docs/reference/glossary/node.md
content/de/docs/reference/glossary/object.md
content/de/docs/reference/glossary/pod.md
content/de/docs/reference/glossary/selector.md
content/de/docs/reference/glossary/service.md
content/de/docs/reference/glossary/statefulset.md

[de] This PR is to add the German localization for the following glossary files:
/content/de/docs/reference/glossary/kubeadm.md
/content/de/docs/reference/glossary/label.md
/content/de/docs/reference/glossary/master.md
/content/de/docs/reference/glossary/node.md
/content/de/docs/reference/glossary/object.md
/content/de/docs/reference/glossary/pod.md
/content/de/docs/reference/glossary/selector.md
/content/de/docs/reference/glossary/service.md
/content/de/docs/reference/glossary/statefulset.md

[de] German localization of further glossary files

---

content/de/docs/reference/glossary/addons.md
content/de/docs/reference/glossary/admission-controller.md
content/de/docs/reference/glossary/affinity.md
content/de/docs/reference/glossary/aggregation-layer.md
content/de/docs/reference/glossary/annotation.md
content/de/docs/reference/glossary/api-eviction.md
content/de/docs/reference/glossary/api-group.md
content/de/docs/reference/glossary/app-container.md
content/de/docs/reference/glossary/application-architect.md
content/de/docs/reference/glossary/application-developer.md
content/de/docs/reference/glossary/applications.md
content/de/docs/reference/glossary/approver.md

This PR is for the German localization of the following glossary items:
content/de/docs/reference/glossary/addons.md
content/de/docs/reference/glossary/admission-controller.md
content/de/docs/reference/glossary/affinity.md
content/de/docs/reference/glossary/aggregation-layer.md
content/de/docs/reference/glossary/annotation.md
content/de/docs/reference/glossary/api-eviction.md
content/de/docs/reference/glossary/api-group.md
content/de/docs/reference/glossary/app-container.md
content/de/docs/reference/glossary/application-architect.md
content/de/docs/reference/glossary/application-developer.md
content/de/docs/reference/glossary/applications.md
content/de/docs/reference/glossary/approver.md

[de] German localization of further glossary items

---

content/en/docs/tasks/administer-cluster/encrypt-data.md

This is split out from PR https://github.com/kubernetes/website/pull/33285 in order to make a review more likely. See that PR and its previews to show the changes in a wider context.
When using API encryption at rest without KMS, document that the same encryption key must be securely replicated to all the hosts that run a kube-apiserver.
/language en

Recommend replicating encryption key for API data encryption at rest

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/tools/install-kubectl-linux.md

The following command will fail without the folder created manually beforhand.
```
curl -fsSL https://dl.k8s.io/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
```
Hence adding the following command in this PR.
```
mkdir -p /etc/apt/keyrings
```

Add example command to create /etc/apt/keyrings directory

---

content/fr/docs/tasks/administer-cluster/declare-network-policy.md
content/fr/examples/service/networking/nginx-policy.yaml
data/i18n/fr/fr.toml

Hi,
This adds the French translation for the  "Declare Network Policy" task from the "Administer a Cluster" section: https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/.
I also added the supporting file and translated i18n strings regarding third party content that were used in this task.

[fr] translate task "Declare Network Policy"

---

content/en/docs/concepts/storage/volumes.md

This PR added information about how existing in-trees PVs and in-tree format yaml file will be handled after CSI migration is completed to the "Migrating to CSI drivers from in-tree plugin" section at the volume page.
https://kubernetes.io/docs/concepts/storage/volumes/#migrating-to-csi-drivers-from-in-tree-plugins
I think these contents needs to be added for the following reason:
Our users might be confused as to whether their existing in-trees PVs and manifests that use in-tree volume plugins will still work after the CSI Migration is completed, but only the 2022 Blog states that the project will continue to run as usual, the documentation doesn't mention this matter. So I added some introduction about this.
The added content is all from the following blog and Issue:
・Issue [About the …

Add information about how existing in-trees PVs and in-tree format yaml file will be handled after CSI migration is completed

---

content/uk/docs/contribute/localization_uk.md

Translation and adaptation of #20786 for less technical folks.
[Preview link to content](https://deploy-preview-44813--kubernetes-io-main-staging.netlify.app/uk/docs/contribute/localization_uk/#%D0%B7%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81)
As suggested by @seokho-son in the mentioned issue, it's a better place for that kind of stuff, and as long as it easy to find it - there is no reason to maintain issues inside `k/websites`
<details><summary>Page shown on every docs page an easy accesible</summary>
</details> 
/language uk
Close #20786

Add general contibution workflow to language-specific-localization-guide

---

content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md

en PR https://github.com/kubernetes/website/pull/44235/files

[zh] fix typo & link

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

resolve https://github.com/kubernetes/website/issues/44271

Add comments on Tutorial  for not working on ARM architecture cluster

---

layouts/shortcodes/cncf-landscape.html

fixed CNCF Landscape iframe which  uses wrong colors

---

content/en/docs/contribute/generate-ref-docs/metrics-reference.md

closes #42453
This PR adds documentation for generating the metrics reference page from [K/K](https://www,github.com/Kubernetes/Kubernetes) to [K/website](https://www.github.com/Kubernetes/website)

Added documentation for metrics generation

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/zh-cn/docs/tasks/debug/debug-cluster/windows.md

content/zh-cn/docs/tasks/debug/debug-cluster/windows.md

[zh-cn] sync install-kubeadm windows

---

content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md

Add the link of supposed example in topology-spread-constraints.md

---

content/en/examples/service/networking/networkpolicy.yaml

Harmonizing indent of the yaml to be equal in formatting to other code examples in network-policies.md

Update networkpolicy.yaml - match yaml code formatting

---

content/fr/docs/tasks/configmap-secret/_index.md
content/fr/docs/tasks/configmap-secret/managing-secret-using-config-file.md
content/fr/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
content/fr/docs/tasks/configmap-secret/managing-secret-using-kustomize.md

Hi,
This adds the French translation for the 3 tasks from the "Managing Secrets" section: https://kubernetes.io/docs/tasks/configmap-secret/.
There is one thing where I'm not quite sure how to translate properly. A few notes talk about the Server Side Apply concept:
`Note: The stringData field for a Secret does not work well with server-side apply.`
Translating literally  "server-side apply" would be "Application coté serveur", which is not "wrong", but IMO it's confusing, as it could be understood as an actual application hosted on a server. I've used "traitement coté serveur", which I think is closer to the reference term, but there might be a better translation.

[fr] translate tasks from the Managing Secrets section

---

content/zh-cn/docs/concepts/architecture/garbage-collection.md

> I apologize for not contributing over the past three months. I've been preoccupied with a hurried relocation to another country. Hopefully, in 2024, I'll be able to commit more time and effort to our shared goals.
- **EN upstream**: `content/en/docs/concepts/architecture/garbage-collection.md`
- **Sync to**: `content/zh-cn/docs/concepts/architecture/garbage-collection.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/architecture/garbage-collection.md
diff --git a/content/en/docs/concepts/architecture/garbage-collection.md b/content/en/docs/concepts/architecture/garbage-collection.md
index 947ad515fc..4b36d850b5 100644
--- a/content/en/docs/concepts/architecture/garbage-collection.md
+++ …
```

[zh] sync concepts/architecture/garbage-collection.md

---

content/en/docs/tasks/access-application-cluster/access-cluster-services.md

Fix list indent in the section: [Ways to connect](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#ways-to-connect)
The correct list should have 3 method to connect nodes/pods/services:
* Public IP
* `kubectl proxy`
* From a pod/node in the cluster
--- 
See [preview](https://deploy-preview-44831--kubernetes-io-main-staging.netlify.app/docs/tasks/access-application-cluster/access-cluster-services/#ways-to-connect).

Fix access-cluster-services.md list indent

---

content/en/docs/tasks/debug/debug-application/debug-pods.md

The commit https://github.com/kubernetes/website/commit/d536e46dbdb49175da7c711a4b39df56b6a263de#diff-714196198a9cf46c8ef533dd70a18713085f50880821dc829b95e366e186bb7c seems changed the original meaning of the sentence to the wrong one for `content/en/docs/tasks/debug/debug-application/debug-pods.md`.

Correct incorrect expressions for debug-pods

---

content/en/blog/_posts/2024-01-23-image-filesystem.md

Kubernetes has had support for many releases for a separate image filesystem. There are common configuration issues that users can do to get into a separate filesystem case.  This post walks through configurations and the eviction manager.

Add blog post for Separate Image Filesystem for Kubelet

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Fix the page formatting of https://k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm, which is mentioned in #44848 
Links:
- [Current page](https://k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm)
- [Preview](https://deploy-preview-44853--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)

[zh] Fix page formatting at https://k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm

---

content/en/docs/concepts/workloads/controllers/cron-jobs.md

Explain the connection of `.spec.startingDeadlineSeconds` to Forbid concurrencyPolicy. It is a long standing misunderstanding mentioned in https://github.com/kubernetes/kubernetes/issues/57853, https://github.com/kubernetes/kubernetes/issues/63371 and one of our customers ran into this recently.

CronJob: improve documentation for Forbid concurrencyPolicy

---

content/en/docs/contribute/style/style-guide.md

In the section related to [code-style-for-kubernetes-command-tool-and-component-names](https://kubernetes.io/docs/contribute/style/style-guide/#use-code-style-for-kubernetes-command-tool-and-component-names), the first example related to `kubelet` is incorrect. The text in the Do and Don't should be swapped.
This PR fixes it.
The deploy preview is available [here](https://deploy-preview-44875--kubernetes-io-main-staging.netlify.app/docs/contribute/style/style-guide/#use-code-style-for-kubernetes-command-tool-and-component-names).
Regards,
Aditya

Correct the example in the code style for K8S component names

---

content/zh-cn/docs/reference/kubectl/quick-reference.md
content/zh-cn/docs/tasks/access-application-cluster/access-cluster-services.md
content/zh-cn/docs/tasks/access-application-cluster/access-cluster.md

1. Sync `access-application-cluster/*.md`
2. Rename and sync `cheatsheet.md` to `quick-reference.md`
Depends on PR #44669 link anchor fixes of file:
```
content/zh-cn/docs/tasks/administer-cluster/access-cluster-api.md
```

[zh] Sync access-application-cluster/*.md and relative linked files.

---

content/zh-cn/docs/concepts/workloads/controllers/_index.md
content/zh-cn/docs/concepts/workloads/controllers/job.md
content/zh-cn/docs/concepts/workloads/pods/_index.md

content/zh-cn/docs/concepts/workloads/controllers/_index.md

[zh-cn] sync controllers/_index.md job.md pods/_index.md

---

content/en/docs/reference/using-api/deprecation-guide.md

This PR updates the wording in the v1.27 and v1.29 sections of the deprecated API migration guide to reflect the fact that these releases have already been shipped.

Update wording in API deprecation guide for v1.27 and v1.29

---

content/ko/docs/concepts/configuration/configmap.md

'configmap' is an invalid field, correct to 'configMap'
* Fix `configmap` field in example to `configMap`

[kr-ko] Fix `configmap` to `configMap` in configmap.md

---

content/en/docs/tasks/administer-cluster/encrypt-data.md

This is split out from PR https://github.com/kubernetes/website/pull/33285 in order to make a review more likely. See that PR and its previews to show the changes in a wider context.
Help readers check if they need to follow the [task](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/).
/language en

Revise introduction to encryption at rest page

---

content/en/docs/concepts/storage/persistent-volumes.md

just renamed  "claimPolicy" to "persistentVolumeReclaimPolicy"
this will fix this page: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
because PVC's dont have "claimPolicy" field but instead "persistentVolumeReclaimPolicy"

typo fix: "claimPolicy" to "persistentVolumeReclaimPolicy"

---

content/en/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md

Deployment metadata.name in dns-horizontal-autoscaler.yaml is `kube-dns-autoscaler`, so the output of a successful command is `deployment.apps/kube-dns-autoscaler created`. Other out-of-sync areas have also been modified.
ConfigMap same as above.
Fixes:  https://github.com/kubernetes/website/issues/44855
Related to:
- https://github.com/kubernetes/website/pull/29187
- https://github.com/kubernetes/website/issues/15280
See the [preview page](https://deploy-preview-44897--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/dns-horizontal-autoscaling/).

Fix Deployment and ConfigMap name in the dns-horizontal-autoscaling page

---

data/i18n/zh-cn/zh-cn.toml

There are two problems here.
- The first is that the current Chinese translation has a link to the English document address.
- The second is that the module `thridparty-content` is currently different between Chinese and English, should it be synchronized?
https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/operator/#writing-operator
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#writing-operator

[zh] update data/i18n/zh-cn/zh-cn.toml

---

content/zh-cn/docs/concepts/services-networking/network-policies.md
content/zh-cn/examples/service/networking/networkpolicy.yaml

Sync with en upstream
```
```
See [preview](https://deploy-preview-44846--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/network-policies/).

[zh] Sync network-policies.md and its yaml

---

assets/scss/_custom.scss
layouts/blog/baseof.html

Change our customizations to Docsy, so that pages in the [blog](https://blog.k8s.io/) section don't have two `<h1>` elements.
This snag showed up when we were testing PageFind for search.

Avoid two <h1> elements for blog section

---

content/en/docs/reference/command-line-tools-reference/feature-gates/stateful-set-auto-delete-pvc.md

StatefulsetAutoDeletePVC has been on by default since it
graduated to Beta in 1.27
Fixes #43976
Signed-off-by: Naadir Jeewa <naadir.jeewa@broadcom.com>

Fix default status of StatefulsetAutoDeletePVC when beta

---

content/en/docs/tasks/manage-gpus/scheduling-gpus.md

This  patch documents the official k8s-sig NFD project for automated node labeling, and restructures the ` Automatic node labelling` section at `scheduling-gpus` page

Document NFD for GPU Labeling

---

content/en/docs/contribute/new-content/blogs-case-studies.md

This change adds some information about using the `figure` hugo shortcode for adding images to a blog article.
I've added it to the 'Technical Considerations for submitting a blog post' section just after where hugo is mentioned so that it flows logically for anyone reading the guide.
For related discussion, see https://kubernetes.slack.com/archives/CJDHVD54J/p1706544061503169

Add info on using the figure hugo shortcode
