content/zh-cn/docs/setup/best-practices/certificates.md

en PR https://github.com/kubernetes/website/pull/42942/files

[zh] remove "O=system:masters" from "kube-apiserver-etcd-client".md

---

content/zh-cn/docs/reference/_index.md

```
content/zh-cn/docs/reference/_index.md
```

[zh] Sync reference/_index.md

---

content/zh-cn/docs/reference/external-api/metrics.v1beta1.md

```
content/zh-cn/docs/reference/external-api/metrics.v1beta1.md
```
See [preview](https://deploy-preview-43154--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/external-api/metrics.v1beta1/) please.

[zh] Sync metrics.v1beta1.md

---

content/en/docs/tutorials/stateful-application/basic-stateful-set.md

Split out from #42767 to help reviewers. [preview](https://deploy-preview-43132--kubernetes-io-main-staging.netlify.app/docs/tutorials/stateful-application/basic-stateful-set/)

Fix case for headings in StatefulSet tutorial

---

assets/scss/_custom.scss
content/en/docs/home/_index.md

Closes #43147
This PR improves the overall aesthetics of the Kubernetes docs home page
I've made some changes to the Front matter fields for consistency ; The SCSS changes aim to improve the overall aesthetic of the cards.

Docs home page card layout is now consistent

---

content/en/docs/home/_index.md

Reorder docs home page tiles (fix alignment)

---

assets/scss/_custom.scss

Reverting an unintended merge from #43164 which I approved by mistake.

Revert CSS changes for launch cards

---

content/zh-cn/docs/reference/external-api/custom-metrics.v1beta2.md
content/zh-cn/docs/reference/external-api/external-metrics.v1beta1.md

```
content/zh-cn/docs/reference/external-api/custom-metrics.v1beta2.md
```

[zh] Sync custom-metrics.v1beta2.md

---

assets/scss/_base.scss
static/css/community.css
static/css/training.css

Fixes #42893
Adds hover effect on blue buttons on the pages [page1](https://kubernetes.io/docs/home/), [page2](https://kubernetes.io/training/), [page3](https://kubernetes.io/partners/), [page4](https://kubernetes.io/community/)

Added hover effect on blue buttons of all the pages #fixes42893

---

content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md
content/zh-cn/docs/tutorials/stateful-application/cassandra.md
content/zh-cn/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
content/zh-cn/docs/tutorials/stateful-application/zookeeper.md

[zh-cn] sync tutorials/stateful-application/*

---

content/zh-cn/docs/reference/using-api/client-libraries.md

en PR https://github.com/kubernetes/website/pull/42894/files

[zh] Add kr8s to community Python libraries list

---

content/en/docs/concepts/cluster-administration/system-traces.md

Fixes https://github.com/kubernetes/website/issues/42804
@kubernetes/sig-instrumentation-leads

Clarify how trace context works for kubelet tracing

---

content/zh-cn/docs/home/_index.md

content/zh-cn/docs/home/_index.md

[zh-cn] sync docs/home

---

content/zh-cn/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/43049/files

[zh] Updated link referring to Portworx CSI Drivers

---

content/en/docs/concepts/workloads/controllers/job.md

Fix incorrect field path in Job concept

---

assets/scss/_base.scss

Added Hover Effect on buttons to enhance user experience.
Fixes Issue - #43173 
https://github.com/kubernetes/website/assets/90104572/688d4803-3601-4d6b-a26d-8efab65dff65

Added hover effect on buttons

---

README-zh.md

Sync with en version.
/language zh

[zh] Sync README-zh.md

---

content/pt-br/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/43049/files

[pt] Updated link referring to Portworx CSI Drivers

---

content/id/docs/concepts/architecture/cgroups.md

[id] Fix heading for "selanjutnya"

---

content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md

Issue https://github.com/kubernetes/website/issues/42676

Fix - Remove details about SelectorSpread plugin

---

content/en/docs/reference/glossary/workload.md

updated Glossary item workload termid same as filename

---

content/en/docs/tasks/administer-cluster/running-cloud-controller.md

Added a note on Cloud Controller Manager Administration page to clarify --cloud-provider argument usage

---

content/en/blog/_posts/2023-09-25-kubeadm-use-etcd-learner-mode.md

- Use a consistent style in a `1-2-3-4` list
- Fix a code indentation
- Replace a note with short code `{{< note >}}{{< /note >}}`
- Tweak long lines at bottom

Clean up 2023-09-25-kubeadm-use-etcd-learner-mode

---

content/en/blog/_posts/2023-05-05-memory-qos-cgroups-v2/index.md

- Add code symbols
- Replace Note text with short code `{{< note >}}{{< /note >}}`
- **Change formula styles from `$..$` to normal code blocks**
- **Replace 6 SVG images, which looks weird a little, with text**
[Current Page](https://kubernetes.io/blog/2023/05/05/qos-memory-resources/) | [Preview Page](https://deploy-preview-43190--kubernetes-io-main-staging.netlify.app/blog/2023/05/05/qos-memory-resources/)

Try to improve 2023-05-05-memory-qos-cgroups-v2

---

content/en/docs/reference/command-line-tools-reference/kubelet.md

[Page link](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)

Fixed a hyperlink at kubelet page

---

content/zh-cn/blog/_posts/2023-01-12-protect-mission-critical-pods-priorityclass/decision-tree.svg

Localize the decision tree for priorityclass blog:
```
content/zh-cn/blog/_posts/2023-01-12-protect-mission-critical-pods-priorityclass/decision-tree.svg
```

[zh] Localize the decision tree for priorityclass blog

---

content/zh-cn/docs/concepts/workloads/pods/init-containers.md
content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md

[zh-cn] sync concepts/workloads/pods/*

---

content/en/docs/reference/command-line-tools-reference/kubelet.md

Removing stale links, to some that are more relevant.

Update 2 links in command-line-tools-reference/kubelet

---

content/zh-cn/docs/concepts/policy/resource-quotas.md

[zh] sync policy/resource-quotas.md

[zh] sync policy/resource-quotas.md

---

content/zh-cn/docs/concepts/policy/limit-range.md

[zh] sync policy/limit-range.md

[zh] sync policy/limit-range.md

---

content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html

As request in the issue have incorporated the feedback from https://github.com/kubernetes/website/pull/41260#pullrequestreview-1632808581
This will fix https://github.com/kubernetes/website/issues/43179

Fix style guide nits in tutorial

---

content/en/docs/reference/glossary/object.md

Fix grammar in `object`'s short description

---

content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md

[zh-cn] sync scheduling-eviction/topology-spread-constraints.md

---

content/ja/docs/tasks/configure-pod-container/configure-pod-configmap.md

[ja] Update configure-pod-configmap.md

---

content/zh-cn/blog/_posts/2023-07-06-confidential-kubernetes.md

en PR https://github.com/kubernetes/website/pull/42995/files

[zh] Remove Link Of AMD for SEV_ES

---

content/zh-cn/docs/tasks/run-application/configure-pdb.md
content/zh-cn/docs/tasks/run-application/delete-stateful-set.md
content/zh-cn/docs/tasks/run-application/force-delete-stateful-set-pod.md
content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md
content/zh-cn/docs/tasks/run-application/run-replicated-stateful-application.md
content/zh-cn/docs/tasks/run-application/run-single-instance-stateful-application.md
content/zh-cn/docs/tasks/run-application/run-stateless-application-deployment.md
content/zh-cn/docs/tasks/run-application/scale-stateful-set.md

[zh-cn] sync tasks/run-application/*

---

content/zh-cn/docs/tasks/network/customize-hosts-file-for-pods.md
content/zh-cn/docs/tasks/network/validate-dual-stack.md

content/zh-cn/docs/tasks/network/customize-hosts-file-for-pods.md
content/zh-cn/docs/tasks/network/validate-dual-stack.md

[zh-cn] sync tasks/network/*

---

content/zh-cn/docs/reference/kubernetes-api/authentication-resources/service-account-v1.md
content/zh-cn/docs/reference/kubernetes-api/other-resources/_index.md
content/zh-cn/docs/reference/kubernetes-api/other-resources/validating-admission-policy-binding-list-v1alpha1.md

Updated 3 files:
```
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/service-account-v1.md
content/zh-cn/docs/reference/kubernetes-api/other-resources/_index.md
content/zh-cn/docs/reference/kubernetes-api/other-resources/validating-admission-policy-binding-list-v1alpha1.md
```

[zh] Update kubernetes-api/other-resources files

---

content/en/blog/_posts/2023-10-02-steering-committee-results-2023.md

Adding blog post for Steering Committee 2023 election.
/cc @kaslin @dims

Adding SC blog post for 2023 election

---

content/zh-cn/docs/reference/kubectl/cheatsheet.md

content/zh-cn/docs/reference/kubectl/cheatsheet.md

[zh-cn] sync kubectl/cheatsheet.md

---

content/zh-cn/blog/_posts/2023-10-02-steering-committee-results-2023.md

[zh-cn] sync blog: 2023-10-02-steering-committee-results-2023.md

---

content/en/docs/tutorials/kubernetes-basics/_index.html

Fixes #43301
Updated:
docs/tutorials/kubernetes-basics/deploy-app/deploy-intro

Remove mention of Katacoda interactive tutorial

---

content/en/blog/_posts/2023-10-02-steering-committee-results-2023.md

Add the missing parentheses to maintain consistency in the content, as shown in the image below.

Fix typo in 2023 Steering Committee Election Results

---

content/en/blog/_posts/2023-10-10-cri-o-community-package-infrastructure.md

Follow-up on https://github.com/kubernetes/website/pull/43128
cc @kubernetes/release-engineering @haircommander @sftim

Fix links in CRI-O packaging blog

---

content/pt-br/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/42743/files

[pt] fix configmap-pod CrashLoopBackOff

---

content/zh-cn/docs/concepts/cluster-administration/flow-control.md

en PR https://github.com/kubernetes/website/pull/43064/files

[zh] Fix broken link in "API Priority and Fairness" page

---

content/zh-cn/blog/_posts/2023-10-02-steering-committee-results-2023.md

The original text has been updated 
- https://github.com/kubernetes/website/pull/43314
Add the missing parentheses to maintain consistency in the content, as shown in the image below.

[zh]Fix typo in 2023 Steering Committee Election Results

---

content/en/docs/reference/labels-annotations-taints/_index.md

Fix a link in label-annotation-taints page

---

content/en/docs/concepts/cluster-administration/system-metrics.md

Changed from `components that doesn't` to `components that don't` and added comma.

typo: in system-metrics.md

---

content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md

fixes https://github.com/kubernetes/website/issues/42670

Fix stale info about spread minDomains

---

content/en/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md

Spotlight article on SIG Architecture: Conformance, the first of the series.
Contributor-site PR: https://github.com/kubernetes/contributor-site/pull/431 ; content is currently in sync, and I will update this one with the result of the review in the `contributor-site` PR, so for general changes please add to that one (changes specific to the `website`  are welcomed here though).

Add SIG Architecture Conformance spotlight interview

---

content/zh-cn/docs/concepts/cluster-administration/flow-control.md
content/zh-cn/docs/concepts/configuration/configmap.md
content/zh-cn/docs/concepts/containers/images.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/services-networking/service-traffic-policy.md
content/zh-cn/docs/contribute/new-content/blogs-case-studies.md
content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
content/zh-cn/docs/reference/access-authn-authz/rbac.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md
content/zh-cn/docs/reference/labels-annotations-taints/_index.md
content/zh-cn/docs/reference/setup-tools/kubeadm/_index.md
content/zh-cn/docs/tasks/configure-pod-container/assign-memory-resource.md
content/zh-cn/docs/tasks/configure-pod-container/resize-container-resources.md
content/zh-cn/docs/tasks/configure-pod-container/static-pod.md
content/zh-cn/docs/tasks/debug/debug-cluster/audit.md
content/zh-cn/docs/tasks/extend-kubernetes/configure-multiple-schedulers.md
content/zh-cn/docs/tutorials/stateful-application/cassandra.md
content/zh-cn/docs/tutorials/stateful-application/zookeeper.md

[zh] Fix some links in the zh-cn localization site

---

content/en/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md

- Replace `1-2-3` with `1-1-1`  for ordered list
- Use a consistent heading style about capitalization

Clean up kubelet-tls-bootstrapping.md

---

content/en/blog/_posts/2020-09-03-warnings/index.md
content/en/blog/_posts/2021-10-18-kpng-specialized-proxiers.md
content/en/docs/reference/kubectl/cheatsheet.md
content/en/docs/tasks/administer-cluster/verify-signed-artifacts.md
content/en/docs/tasks/tls/managing-tls-in-a-cluster.md

As requested updated outdated links to `jq`
This will fix https://github.com/kubernetes/website/issues/43285

Update outdated jq link

---

content/pt-br/docs/concepts/workloads/controllers/replicaset.md

en PR https://github.com/kubernetes/website/pull/42822/files

[pt] update the range of pod-deletion-cost

---

content/zh-cn/docs/concepts/workloads/_index.md
content/zh-cn/docs/concepts/workloads/controllers/job.md
content/zh-cn/docs/concepts/workloads/controllers/statefulset.md

[zh] Resync workloads concepts page

---

content/zh-cn/docs/reference/access-authn-authz/node.md

Sync with en #43284
```
content/zh-cn/docs/reference/access-authn-authz/node.md
```

[zh] Sync /access-authn-authz/node.md

---

content/zh-cn/docs/concepts/cluster-administration/_index.md
content/zh-cn/docs/concepts/cluster-administration/networking.md
content/zh-cn/docs/concepts/cluster-administration/system-traces.md

[zh] Resync cluster-administration concepts

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md

```
content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md
```
See [preview](https://deploy-preview-43120--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/command-line-tools-reference/kube-proxy/) please.

[zh] Sync /command-line-tools-reference/kube-proxy.md

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_admin.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_controller-manager.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_kubelet.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_scheduler.md

Update 6 files:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_admin.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_controller-manager.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_kubelet.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_scheduler.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig.md
```
/kind cleanup

[zh] Clean up kubeadm_init_phase_kubeconfig files

---

content/zh-cn/docs/concepts/storage/ephemeral-volumes.md
content/zh-cn/docs/concepts/storage/persistent-volumes.md
content/zh-cn/docs/concepts/storage/projected-volumes.md
content/zh-cn/docs/concepts/storage/storage-classes.md
content/zh-cn/docs/concepts/storage/volume-snapshot-classes.md

[zh] Resync storage concepts pages

---

content/pl/docs/setup/_index.md

Refresh Polish localization for main setup index file.

Update pl localization for main setup index

---

content/zh-cn/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md

Sync with en #43345 
```
content/zh-cn/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md
```

[zh] Sync kubelet-tls-bootstrapping.md

---

content/zh-cn/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md

```
content/zh-cn/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md
```
See [preview](https://deploy-preview-43371--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/10/05/sig-architecture-conformance-spotlight-2023/) please.

[zh] Sync 2023-10-05-sig-architecture-conformance-spotlight.md

---

content/pl/_index.html

Update main Polish index page.

Update main Polish index page

---

content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/en/docs/tasks/tools/install-kubectl-linux.md

Added instructions for SUSE-based distributions

Added instructions for SUSE-based distributions

---

data/i18n/en/en.toml
layouts/partials/feedback.html

Added github repository hyperlink to feedback strings

---

content/en/docs/tutorials/stateful-application/basic-stateful-set.md

Split out from https://github.com/kubernetes/website/pull/42767 to help reviewers. [preview](https://deploy-preview-43133--kubernetes-io-main-staging.netlify.app/docs/tutorials/stateful-application/basic-stateful-set/).

Revise introduction to StatefulSet tutorial

---

layouts/index.html

Revise appearance of kubeweekly subscription form

---

content/en/docs/reference/labels-annotations-taints/_index.md

Fix for Label nfd.node.kubernetes.io/node-name

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md

```
content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md
```

[zh] Sync /command-line-tools-reference/kube-scheduler.md

---

content/en/docs/tasks/extend-kubernetes/configure-multiple-schedulers.md

Closes #43156
Deploy preview:
https://deploy-preview-43290--kubernetes-io-main-staging.netlify.app/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#package-the-scheduler

Add statement for explaining the example image

---

content/en/docs/reference/labels-annotations-taints/_index.md

Document annotation container.apparmor.security.beta.kubernetes.io/

---

content/en/docs/concepts/storage/ephemeral-volumes.md

Use glossary tooltip for CSI

---

content/en/docs/reference/kubectl/cheatsheet.md

Added - Check which nodes are ready with custom-columns

Update kubectl cheat sheet with command to identify Nodes in Ready state

---

content/en/docs/reference/labels-annotations-taints/_index.md

Added, registered aws-lb-security-groups annotation

---

content/en/docs/setup/production-environment/tools/kubeadm/high-availability.md

xref https://github.com/kubernetes/kubeadm/issues/2928

updated doc for key type and size

---

README-pt.md

en PR https://github.com/kubernetes/website/pull/43043/files

[pt] Updated resources of README.md

---

content/en/docs/concepts/containers/images.md

As outlined in https://github.com/kubernetes/kubernetes/issues/119941, the implementation is more specific than a regular glob match. Updating the docs to reflect that.
Fixes https://github.com/kubernetes/kubernetes/issues/119941
PTAL @njgibbon

Fix config.json interpretation

---

content/en/releases/_index.md
content/en/releases/download.md
content/en/releases/notes.md
content/en/releases/release-managers.md
content/en/releases/version-skew-policy.md

- Remove redundant blank lines

Clean up pages in /releases

---

content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md

secret is used to have authenticate with the private Container registry
it should be in the same namespace which container the workloads

added Note for secret in same namespace as the Deployment, Pods

---

content/en/docs/concepts/services-networking/service.md

Fix explanation in service concept

---

content/en/docs/reference/glossary/group-version-resource.md

Add an entry in glossary for GVR

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md

Updated what's next section in network plugin page

what's next for network plugin

---

README-pl.md

en PR https://github.com/kubernetes/website/pull/43043/files
/assign @mfilocha

[pl] Updated resources of README.md

---

content/en/docs/reference/using-api/api-concepts.md

Use the correct term given the contextual definitions of a _resource type_ and _resource_.

Correct `collection` definition to a list of instances of a resource _type_

---

content/zh-cn/releases/_index.md
content/zh-cn/releases/download.md
content/zh-cn/releases/notes.md
content/zh-cn/releases/release-managers.md
content/zh-cn/releases/release.md
content/zh-cn/training/_index.html

[zh-cn] sync releases/* and training/*

---

content/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1.md

content/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1.md

[zh-cn] sync apiserver-config.v1alpha1.md

---

content/zh-cn/docs/concepts/workloads/controllers/deployment.md

Fix issues mentioned in https://github.com/kubernetes/website/pull/43420#discussion_r1353830421

[zh] update /controllers/deployment.md

---

content/zh-cn/releases/version-skew-policy.md

content/zh-cn/releases/version-skew-policy.md

[zh-cn] sync releases/version-skew-policy.md

---

content/es/docs/concepts/storage/projected-volumes.md
content/es/examples/pods/storage/projected-secret-downwardapi-configmap.yaml
content/es/examples/pods/storage/projected-secrets-nondefault-permission-mode.yaml
content/es/examples/pods/storage/projected-service-account-token.yaml

Se añadió la documentación en español para las sección:
content/es/docs/concepts/storage/projected-volumes.md
Agradecería puedan revisarlo y darme feedback.
Gracias! :)
closes #41701

[es] Add concepts/storage/projected-volumes.md

---

content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md

content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md

[zh-cn] sync apiserver-config.v1beta1.md

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Sync with en  #42124, #42820,  #43407, #43034, and #43425.
```
```
See [preview](https://deploy-preview-43424--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) please.

[zh] Sync /kubeadm/install-kubeadm.md

---

content/en/blog/_posts/2023-10-12-bootstrap-an-air-gapped-cluster-with-kubeadm/index.md

Fixups for https://github.com/kubernetes/website/pull/42726
@TheFutonEng FYI

Fix nits in air-gapped cluster blog article

---

content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1beta3.md

translate profile to ‘方案’ instead  of  ‘模仿’, be same whit above.

translate profile to ‘方案’ instead  of  ‘模仿’

---

content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md

Sync with one of en #43300.
Only move two sections from bottom, without any text change.

[zh] Sync /config-api/kubeadm-config.v1beta3.md

---

content/zh-cn/docs/tasks/debug/debug-cluster/troubleshoot-kubectl.md

Add zh text to this file:
```
content/zh-cn/docs/tasks/debug/debug-cluster/troubleshoot-kubectl.md
```
See [preview](https://deploy-preview-43466--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-cluster/troubleshoot-kubectl/) please.

[zh] Sync troubleshoot-kubectl.md

---

content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md

add "ServiceAccount控制器 {#ServiceAccount controller}" to https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller

add a 3rd tile,sync form en version

---

content/zh-cn/docs/reference/config-api/kubeconfig.v1.md

added kubeconfig.v1.md in localized language
which 
resolves issue: #43360

Created kubeconfig.v1.md in localized(zn-ch) language.

---

content/zh-cn/docs/tasks/extend-kubernetes/setup-konnectivity.md

content/zh-cn/docs/tasks/extend-kubernetes/setup-konnectivity.md

[zh-cn] sync extend-kubernetes/setup-konnectivity.md

---

content/zh-cn/docs/tasks/debug/debug-application/get-shell-running-container.md

en PR https://github.com/kubernetes/website/pull/43115/files

[zh] fix: update deprecated command in code example

---

content/zh-cn/docs/tutorials/services/connect-applications-service.md

[zh-cn] fix some wording in connect-applications-service.md
thanks

[zh-cn] fix some wording in connect-applications-service.md

---

content/zh-cn/docs/contribute/style/write-new-topic.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md

[zh-cn] sync kubeadm/install-kubeadm.md kubelet-integration.md write-new-topic.md

---

data/i18n/en/en.toml

a feature request to replace "search" with "search this site"
label  #43291

Changed "search" to "search this site" on front page

---

content/zh-cn/docs/tasks/configmap-secret/managing-secret-using-config-file.md
content/zh-cn/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
content/zh-cn/docs/tasks/job/automated-tasks-with-cron-jobs.md
content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md
content/zh-cn/docs/tasks/job/fine-parallel-processing-work-queue.md
content/zh-cn/docs/tasks/job/indexed-parallel-processing-static.md
content/zh-cn/docs/tasks/job/job-with-pod-to-pod-communication.md
content/zh-cn/docs/tasks/job/parallel-processing-expansion.md
content/zh-cn/docs/tasks/job/pod-failure-policy.md

[zh-cn] sync tasks/job/* configmap-secret/*

---

content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md

Same as pr https://github.com/kubernetes/website/pull/43465

translate profile to 方案 instead  of  模仿

---

content/zh-cn/docs/concepts/services-networking/dual-stack.md
content/zh-cn/docs/concepts/services-networking/ingress-controllers.md
content/zh-cn/docs/concepts/services-networking/ingress.md
content/zh-cn/docs/concepts/services-networking/service.md

sync docs/concepts/services-networking/*

[zh] sync dual-stack ingress-controllers ingress service

---

content/zh-cn/docs/tasks/administer-cluster/kubelet-config-file.md
content/zh-cn/docs/tasks/inject-data-application/define-environment-variable-container.md
content/zh-cn/docs/tasks/inject-data-application/define-interdependent-environment-variables.md
content/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure.md
content/zh-cn/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
content/zh-cn/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md
content/zh-cn/docs/tasks/manage-daemon/pods-some-nodes.md
content/zh-cn/docs/tasks/manage-daemon/update-daemon-set.md

[zh-cn]sync kubelet-config-file inject-data-application/* manage-daemon/*

---

content/fr/docs/tasks/debug-application-cluster/get-shell-running-container.md

en PR https://github.com/kubernetes/website/pull/43115/files

[fr] fix: update deprecated command in code example

---

content/en/docs/reference/using-api/api-concepts.md

Updated appearance of examples in k8s API concepts.
Now it comes with user-friendly colors for better comprehension.

updated examples appearance in k8s api concept

---

content/zh-cn/docs/concepts/storage/ephemeral-volumes.md
content/zh-cn/docs/concepts/storage/volumes.md
content/zh-cn/docs/concepts/storage/windows-storage.md

[zh] sync ephemeral-volumes volumes windows-storage

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

ref https://github.com/kubernetes/kubernetes/pull/120249

remove GAed FG DownwardAPIHugePages

---

content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md

content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md

[zh-cn] sync migrate-dockershim-dockerd enforce-standards-admission-controller

---

content/en/docs/concepts/cluster-administration/addons.md

edit addons.md. part of cilium

Update addons.md, Cilium is now a CNCF graduated project

---

content/ja/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/43049/files

[ja] Updated link referring to Portworx CSI Drivers

---

content/ja/docs/reference/glossary/secret.md

This PR update glossary about secret on ja content.
The current content is a bit old, that's why I create this update.

[ja] Update ja glossary about secret

---

content/ja/docs/concepts/workloads/controllers/replicaset.md

en PR https://github.com/kubernetes/website/pull/42822/files
/assign @t-inu 

[ja] update the range of pod-deletion-cost

---

content/ja/docs/concepts/workloads/pods/pod-lifecycle.md

[ja] fix: incorrect translation of 'successfully created'

---

content/id/docs/concepts/workloads/pods/init-containers.md
content/id/examples/application/deployment-sidecar.yaml
content/id/examples/application/job/job-sidecar.yaml

add section for sidecar containers & example

[id] update about sidecar containers

---

content/zh-cn/docs/concepts/cluster-administration/addons.md

- **EN upstream**: `content/en/docs/concepts/cluster-administration/addons.md`
- **Sync to**: `content/zh-cn/docs/concepts/cluster-administration/addons.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/cluster-administration/addons.md
diff --git a/content/en/docs/concepts/cluster-administration/addons.md b/content/en/docs/concepts/cluster-administration/addons.md
index f01736c103..aa36d4c97a 100644
--- a/content/en/docs/concepts/cluster-administration/addons.md
+++ b/content/en/docs/concepts/cluster-administration/addons.md
@@ -37,7 +37,7 @@ installation instructions. The list does not try to be exhaustive.
network policies on L3-L7 using an identity-based security model that is
decoupled from network addressing. Cilium can act …
```

[zh] sync concepts/cluster-administration/addons.md

---

content/zh-cn/docs/concepts/architecture/_index.md

- **EN upstream**: `content/en/docs/concepts/architecture/_index.md`
- **Sync to**: `content/zh-cn/docs/concepts/architecture/_index.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/architecture/_index.md
diff --git a/content/en/docs/concepts/architecture/_index.md b/content/en/docs/concepts/architecture/_index.md
index 61fb48e714..7c9a45c71e 100644
--- a/content/en/docs/concepts/architecture/_index.md
+++ b/content/en/docs/concepts/architecture/_index.md
@@ -5,3 +5,4 @@ description: >
The architectural concepts behind Kubernetes.
---
+{{< figure src="/images/docs/kubernetes-cluster-architecture.svg" alt="Components of Kubernetes" caption="Kubernetes cluster architecture" class="diagram-large" >}}
```
Sync check …

[zh] Sync SVG contents to concepts/architecture/_index.md

---

content/id/docs/tasks/debug-application-cluster/get-shell-running-container.md

en PR https://github.com/kubernetes/website/pull/43115/files
/assign @ariscahyadi

[id] fix: update deprecated command in code example

---

content/en/blog/_posts/2023-10-20-kubernetes-1.28-release-interview.md
content/en/blog/_posts/2023-10-24-kubernetes-1.28-release-interview.md

Publish an abridged transcript of my podcast interview with Grace Nguyen as a kubernetes.io blog post.
See also: #36051, #33280, #30688, #29146, #22882, #22716, #17963 et al.

Add 1.28 release interview blog post

---

content/pl/docs/home/_index.md

Synchronize Polish localization with upstream up to 8e1a175dc5b808344afdc80cf452760760327d04.
Part 1

Synchronize Polish localization for ver 1.28, part 1

---

content/zh-cn/docs/reference/kubectl/_index.md

content/zh-cn/docs/reference/kubectl/_index.md

[zh-cn] sync reference/kubectl/_index.md

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

sync /setup/production-environment/tools/kubeadm/*

[zh] sync high-availability install-kubeadm

---

content/en/docs/concepts/cluster-administration/flow-control.md

This PR updates the documentation on the metrics from API Priority and Fairness.

Add some overlooked APF metrics, note maturity levels

---

content/pl/releases/_index.md

Synchronize Polish localization for ver 1.28, part 2

Synchronize Polish localization for ver 1.28, part 2

---

content/pl/docs/reference/_index.md

Synchronize Polish localization for ver 1.28, part 4

Synchronize Polish localization for ver 1.28, part 4

---

content/uk/_index.html

[uk] add searchbar to index page

---

content/zh-cn/docs/tasks/manage-hugepages/scheduling-hugepages.md
content/zh-cn/docs/tasks/manage-kubernetes-objects/imperative-config.md

Updated 2 files:
```
content/zh-cn/docs/tasks/manage-hugepages/scheduling-hugepages.md
content/zh-cn/docs/tasks/manage-kubernetes-objects/imperative-config.md
```

[zh] Sync scheduling-hugepages.md and imperative-config.md

---

content/id/docs/tasks/configure-pod-container/configure-pod-configmap.md

[id] Update configure-pod-configmap.md

---

content/es/docs/concepts/storage/ephemeral-volumes.md

Hola Rodolfo, añadí la documentacion in Spanish para ephemeral-volumes 
Estoy atenta a cualquier feedback! Gracias!
Closes #43482

[es] Add concepts/storage/ephemeral-volumes.md

---

content/zh-cn/docs/reference/kubernetes-api/common-definitions/status.md

Fix some issues [in this api page](https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-definitions/status/).
```
content/zh-cn/docs/reference/kubernetes-api/common-definitions/status.md
```
See [preview](https://deploy-preview-43691--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/common-definitions/status/) please.

[zh] Clean up /kubernetes-api/common-definitions/status.md

---

content/de/_index.html

[de] add searchbar to index page

---

content/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters.md

Perform changes to keep consistent with our [zh-cn style guide](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#commented-en-text).
```
content/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters.md
```
See [preview](https://deploy-preview-43704--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters/) please.

[zh] Clean up common-parameters.md

---

content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md
content/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry.md

[zh]Sync service-accounts-admin.md,ingress-minikube.md,configure-service-account.md,pull-image-private-registry.md

[zh]Sync service-accounts-admin.md,ingress-minikube.md,configure-service-account.md,pull-image-private-registry.md

---

content/zh-cn/docs/contribute/participate/issue-wrangler.md

```
content/zh-cn/docs/contribute/participate/issue-wrangler.md
```
See [preview](https://deploy-preview-43597--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/participate/issue-wrangler/) please.

[zh] Sync issue-wrangler.md

---

content/zh-cn/docs/concepts/policy/resource-quotas.md
content/zh-cn/docs/tutorials/configuration/configure-redis-using-configmap.md
content/zh-cn/docs/tutorials/hello-minikube.md
content/zh-cn/docs/tutorials/security/apparmor.md
content/zh-cn/docs/tutorials/security/cluster-level-pss.md
content/zh-cn/docs/tutorials/security/seccomp.md

[zh-cn] sync resource-quotas configure-redis-using-configmap tutorials/security/* hello-minikube

---

content/zh-cn/community/_index.html

1. The `/community/_index` page is outdated by comparing to the English version.
2. Not well-formatted and organized, and the style is not consistent with the English version.
3. Tweak some of the translation of `/community/_index` page.
Please note there are inconsistent styles by comparing to the English version:
1. when browsing with mobile devices, the top right corner of the navigation button of the English version of community page is broken because of the overflow of the line through effect of the headings
2. due to the font width of alphabet characters and Chinese characters, some of the sections may look different
The above issues should be fixed by #43740 and will not interfere nor block the current Pull Request.

[zh] Sync outdated style and structure of /community page

---

content/id/_index.html

[id] add searchbar to index page

---

content/en/docs/reference/access-authn-authz/validating-admission-policy.md

The escape is pending due to the cel nature: https://github.com/kubernetes/kubernetes/pull/121299
Remove the inaccurate description before the PR merged.

Remove the inaccurate description 

---

content/zh-cn/docs/contribute/generate-ref-docs/prerequisites-ref-docs.md
content/zh-cn/docs/contribute/localization.md
content/zh-cn/docs/contribute/style/style-guide.md

content/zh-cn/docs/contribute/generate-ref-docs/prerequisites-ref-docs.md

[zh-cn] sync contribute/*

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

Upstream PR # https://github.com/kubernetes/kubernetes/pull/121303
Signed-off-by: Humble Chirammal <humble.devassy@gmail.com>

Promote CSINodeExpandSecret to GA

---

content/zh-cn/docs/concepts/extend-kubernetes/_index.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/security/pod-security-admission.md

```
content/zh-cn/docs/concepts/extend-kubernetes/_index.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/security/pod-security-admission.md
```

[zh-cn] sync extend-kubernetes node-pressure-eviction pod-security-admission

---

content/it/_index.html

[it] add searchbar to index page

---

content/zh-cn/docs/setup/best-practices/node-conformance.md
content/zh-cn/docs/tasks/debug/debug-cluster/_index.md

content/zh-cn/docs/setup/best-practices/node-conformance.md
content/zh-cn/docs/tasks/debug/debug-cluster/_index.md

[zh-cn] sync node-conformance debug-cluster/_index.md

---

content/es/_index.html

[es] add searchbar to index page

---

content/en/docs/concepts/services-networking/gateway.md

Fixes the Typo in #43816 i.e emove -> remove

Fix typo in Gateway API page

---

content/en/docs/concepts/services-networking/gateway.md

Correction: A missing letter added in emove.

Fix typo in Request flow section of Gateway API

---

content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md

[zh-cn] sync stateful-application/basic-stateful-set.md

---

content/pt-br/_index.html

[pt] add searchbar to index page

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

Tracking issue: https://github.com/kubernetes/enhancements/issues/2879

Docs update for JobPodsReady in GA

---

content/en/docs/tasks/access-application-cluster/access-cluster-services.md

- Remove redundant blank lines
- Provide a consistent look for bullets
/kind cleanup

Clean up access-cluster-services.md

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

Tracking issue: https://github.com/kubernetes/enhancements/issues/3850

Docs update for Job Backoff Limit Per Index in Beta

---

content/vi/_index.html

[vi] add searchbar to index page

---

content/zh-cn/docs/concepts/storage/volumes.md

```
```
See [preview](https://deploy-preview-43826--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/volumes/).

[zh] Sync /storage/volumes.md

---

content/zh-cn/docs/reference/kubernetes-api/policy-resources/ip-address-v1alpha1.md

Fix #43359 
```
content/zh-cn/docs/reference/kubernetes-api/policy-resources/ip-address-v1alpha1.md
```
See [preview](https://deploy-preview-43835--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/policy-resources/ip-address-v1alpha1/) please.

[zh] Localize ip-address-v1alpha1.md into Chinese

---

content/de/_index.html

Updated the KubeCon dates on the German homepage

[de] updated kubecon dates on homepage

---

content/zh-cn/docs/tasks/access-application-cluster/access-cluster-services.md

content/zh-cn/docs/tasks/access-application-cluster/access-cluster-services.md

[zh-cn] sync access-cluster-services.md

---

content/zh-cn/blog/_posts/2023-10-23-pv-last-phase-transtition-time.md

[zh-cn] sync blog: 2023-10-23-pv-last-phase-transtition-time.md

---

content/de/docs/tutorials/_index.md

[de] Ensure seccomp starts with small letter

---

content/zh-cn/docs/concepts/services-networking/network-policies.md

Sync with en #39875
```
```
See [preview](https://deploy-preview-43866--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/network-policies/) please.

[zh] Add translations to network-policies.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

Clean up feature-gates.md

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

See https://github.com/kubernetes/kubeadm/pull/2950 and https://github.com/kubernetes/kubeadm/issues/2924

v1.29: kubeadm skew policy for kubelet is n-3

---

content/id/docs/tutorials/_index.md

[id] Ensure seccomp starts with small letter

---

content/fr/docs/home/_index.md

Addresses French l10n strings described in #43068

[fr] Change footer l10n from Home to Documentation

---

content/zh-cn/docs/reference/access-authn-authz/authentication.md
content/zh-cn/docs/reference/kubectl/kubectl.md

[zh-cn] sync kubectl authentication

---

content/vi/docs/home/_index.md

Addresses Vietnamese l10n strings described in #43068

[vi] Change footer l10n from Home to Documentation

---

content/zh-cn/docs/tutorials/security/ns-level-pss.md
content/zh-cn/docs/tutorials/security/seccomp.md

content/zh-cn/docs/tutorials/security/ns-level-pss.md
content/zh-cn/docs/tutorials/security/seccomp.md

[zh-cn] sync ns-level-pss.md seccomp.md

---

content/ru/docs/home/_index.md

Addresses Russian l10n strings described in #43068

[ru] Change footer l10n from Home to Documentation

---

content/zh-cn/blog/_posts/2023-11-07-introducing-sig-etcd.md

page: https://kubernetes.io/zh-cn/blog/2023/11/07/introducing-sig-etcd/

[zh-cn]Fix link in content/zh-cn/blog/_posts/2023-11-07-introducing-sig-etcd.md

---

content/zh-cn/docs/concepts/workloads/controllers/daemonset.md

content/zh-cn/docs/concepts/workloads/controllers/daemonset.md

[zh-cn] sync daemonset.md

---

content/it/docs/home/_index.md

Addresses Italian l10n strings described in #43068

[it](Change footer l10n from Home to Documentation)

---

content/es/docs/tutorials/_index.md

[es] Ensure seccomp starts with small letter

---

content/zh-cn/blog/_posts/2023-10-10-cri-o-community-package-infrastructure.md

Sync 2023-10-10-cri-o-community-package-infrastructure.md blog into Chinese:
```
content/zh-cn/blog/_posts/2023-10-10-cri-o-community-package-infrastructure.md
```

[zh] Sync 2023-10-10-cri-o-community-package-infrastructure.md blog into Chinese

---

content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md

content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md

[zh-cn] sync extend-resources/custom-resource-definition-v1.md

---

content/en/docs/reference/access-authn-authz/validating-admission-policy.md

Summary of changes
- Fixed the broken/invalid link (thanks @dipesh-rawat for pointing in the review)
- Fixed a small typo in the doc i found while going through it.

Fix broken link in "Validating Admission Policy" page

---

content/en/blog/_posts/2018-11-08-kubernetes-docs-update-i18n.md
content/en/docs/contribute/_index.md
content/en/docs/contribute/new-content/open-a-pr.md
content/en/docs/contribute/style/diagram-guide.md
content/en/releases/release.md

Related to https://kubernetes.slack.com/archives/C0191RDKHU1/p1680549820387879

[en] Mention kubernetes/websites everywhere in the same way

---

content/es/docs/home/_index.md

Addresses Spanish l10n strings described in #43068

[es] Change footer l10n from Home to Documentation

---

content/id/docs/home/_index.md

Addresses Indonesian l10n strings described in #43068

[id] Change footer l10n from Home to Documentation

---

content/hi/docs/home/_index.md

Taking hint from https://github.com/kubernetes/website/issues/43900#issuecomment-1810988608  to come up with fix.
This will fix https://github.com/kubernetes/website/issues/43900

[hi] Updated menu option to "Documentation" from "Home"

---

content/en/docs/concepts/workloads/controllers/job.md

Only fixed a link that directs to 404.

Fix a 404 link in job.md

---

content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

Updated the warning in readiness probes as suggested.

Updated warning in readiness probes

---

content/en/blog/_posts/2023-10-02-steering-committee-results-2023.md

Update the broken link for steering committee elections 2023

---

content/zh-cn/docs/tutorials/kubernetes-basics/update/update-intro.html

Sync with:
```
/docs/tutorials/kubernetes-basics/update/update-intro.html
```

[zh] Sync Tutorial update-intro.

---

content/ko/docs/reference/access-authn-authz/authentication.md

[ko] Translate authentication.md into korean

---

assets/scss/_custom.scss
content/de/community/_index.html
content/en/community/_index.html
content/fr/community/_index.html
content/id/community/_index.html
content/it/community/_index.html
content/ja/community/_index.html
content/ko/community/_index.html
content/pt-br/community/_index.html
content/ru/community/_index.html
content/vi/community/_index.html
content/zh-cn/community/_index.html
static/css/community.css
static/css/legacy_community.css

1. Limit embedded X (Twitter) widget `iframe` with
- `600px` of width with `data-width` attribute,
- `800px` of height with `data-height` attribute.
2. Adjusted the styles of the container of X (Twitter) widget for better UI/UX with centered elements.
[Documentations about parameters of X (Twitter) widget](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview)
As suggested changes to a separated Pull Request from #43740 at [comment](https://github.com/kubernetes/website/pull/43740#issuecomment-1787420895):
> > I used the official support of height settings X (Twitter) to limit the height of the widget by setting the [data-height attribute](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview#customization). However, such change requires …

Improve readabilities by restricting X (Twitter) widget width and height in /community page

---

data/releases/eol.yaml
data/releases/schedule.yaml

Add in release dates for November releases

Add November surprise release dates

---

content/ja/docs/tasks/tools/_index.md
content/ja/docs/tutorials/hello-minikube.md

[ja] Fix campitalization of minikube in japanese translation

---

content/ru/docs/tutorials/_index.md

[ru] Ensure seccomp starts with small letter

---

content/zh-cn/docs/reference/issues-security/security.md
content/zh-cn/docs/reference/kubectl/jsonpath.md

content/zh-cn/docs/reference/issues-security/security.md
content/zh-cn/docs/reference/kubectl/jsonpath.md

[zh-cn] sync security.md jsonpath.md

---

content/en/docs/reference/instrumentation/metrics.md

This PR updates documented metrics for v1.29.

update documented metrics for v1.29

---

content/en/docs/concepts/security/service-accounts.md
content/en/docs/reference/access-authn-authz/service-accounts-admin.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/tasks/configure-pod-container/configure-service-account.md

https://github.com/kubernetes/enhancements/issues/4193
https://github.com/kubernetes/enhancements/pull/4141
https://github.com/kubernetes/kubernetes/pull/120780

KEP-4193: bound service account token improvements

---

content/pl/docs/concepts/overview/components.md
content/pl/docs/concepts/overview/kubernetes-api.md

Refresh Polish localization up to 6e6e4ed79a8e219e7db434fb7f6d76433901739b

Refresh Polish localization 23b

---

content/pl/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
content/pl/docs/tutorials/kubernetes-basics/expose/expose-intro.html
content/pl/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
content/pl/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Refresh Polish localization up to 6e6e4ed79a8e219e7db434fb7f6d76433901739b

Refresh Polish localization 23c

---

content/en/docs/contribute/localization.md

Perform actions below:
- Put link text on a single line
- Provide a consistent look for lists
- Provide consistent headings like `v+n`

Clean up localization.md

---

content/en/docs/reference/access-authn-authz/authentication.md

- Provide headings with consistent capitalization
- Provide a consistent look for bullets

Clean up /access-authn-authz/authentication.md

---

content/pt-br/docs/tutorials/_index.md

[pt] Ensure seccomp starts with small letter

---

content/zh-cn/docs/contribute/localization.md

[zh-cn] sync contribute/localization.md

---

content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md

content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md

[zh-cn] sync command-line-tools-reference/kubelet.md

---

content/zh-cn/docs/contribute/new-content/open-a-pr.md
content/zh-cn/docs/contribute/participate/issue-wrangler.md
content/zh-cn/docs/contribute/style/diagram-guide.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md

[zh-cn] sync issue-wrangler open-a-pr feature-gates diagram-guide

---

content/zh-cn/blog/_posts/2023-11-16-mid-cycle-1.29.md

```
content/zh-cn/blog/_posts/2023-11-16-mid-cycle-1.29.md
```
See [preview](https://deploy-preview-43945--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/11/16/kubernetes-1-29-upcoming-changes/).

[zh] Localize blog: 2023-11-16-mid-cycle-1.29.md

---

content/uk/docs/tutorials/_index.md

[uk] Ensure seccomp starts with small letter

---

content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
content/en/docs/reference/command-line-tools-reference/feature-gates.md

add the doc for matchLabelKeys/mismatchLabelKeys in pod (anti)affinity
ref: https://github.com/kubernetes/enhancements/issues/3633

add: the doc for matchLabelKeys/mismatchLabelKeys in pod (anti)affinity

---

content/zh-cn/examples/controllers/daemonset.yaml

content/zh-cn/examples/controllers/daemonset.yaml

[zh-cn] sync daemonset.yaml

---

content/es/docs/concepts/storage/windows-storage.md

Se añadió la documentación en español para las sección: content/es/docs/concepts/storage/windows-storage.md
Agradecería puedan revisarlo y darme feedback. Wohoo!!!! 🕺🏼 
Gracias! :)
Closes #43791

[es] Add concepts/storage/windows-storage.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md
content/en/docs/tasks/administer-cluster/encrypt-data.md
content/en/docs/tasks/administer-cluster/kms-provider.md

ref: https://github.com/kubernetes/enhancements/issues/3299

[KMSv2] add docs for KMSv2 GA

---

content/uk/docs/tutorials/_index.md

en PR https://github.com/kubernetes/website/pull/43234/files

[uk] Remove some vertical space between lines of text

---

content/ja/docs/tasks/debug/debug-application/get-shell-running-container.md

en PR https://github.com/kubernetes/website/pull/43115/files
/assign @t-inu

[ja] fix: update deprecated command in code example

---

content/ja/_index.html

[ja] add searchbar to index page

---

content/ja/docs/tutorials/_index.md

[ja] Ensure seccomp starts with small letter

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability.md

[zh] Update high-availability.md

---

content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

[zh-cn] sync kubeadm/change-package-repository.md

---

content/zh-cn/blog/_posts/2023-08-28-a-new-alpha-mechanism-for-safer-cluster-upgrades.md
static/images/blog/2023-08-28-a-new-alpha-mechanism-for-safer-cluster-upgrades/mvp-flow-diagram_zh.svg

Localized those text in this image into Chinese.
- [Before](https://kubernetes.io/zh-cn/blog/2023/08/28/kubernetes-1-28-feature-mixed-version-proxy-alpha/#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E6%AD%A4%E9%97%AE%E9%A2%98)
- [After](https://deploy-preview-44013--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/08/28/kubernetes-1-28-feature-mixed-version-proxy-alpha/#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E6%AD%A4%E9%97%AE%E9%A2%98)

[zh] Localize a SVG image in safer cluster upgrade blog

---

content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Sync with en: content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
Dependent on #43873 , include format fix ups from en.

[zh] Sync tutorial scale-intro and reformat.

---

content/de/docs/tutorials/_index.md

en PR https://github.com/kubernetes/website/pull/43234/files

[de] Remove some vertical space between lines of text

---

content/en/docs/tasks/access-application-cluster/access-cluster.md

- Remove extra spaces
- Provide consistent headings about capitalization

Clean up access-application-cluster/access-cluster

---

content/de/docs/home/_index.md

Addresses German l10n strings described in #43068

[de] Change footer l10n from Home to Documentation

---

content/en/releases/download.md

Fixing the feature state and adding a warning about the non matching signatures issue.
cc @kubernetes/release-engineering 
Preview: https://deploy-preview-44062--kubernetes-io-main-staging.netlify.app/releases/download/#container-images

Fix container image state and add warning for signatures

---

content/zh-cn/docs/tutorials/_index.md

en PR https://github.com/kubernetes/website/pull/43234/files

[zh] Remove some vertical space between lines of text

---

content/pl/releases/download.md

Proposal for the Polish translation of the 'Download Kubernetes' section.
PL translation of the 'Download Kubernetes' (download.md) section. Pushing to the main branch in the absence of the dev-pl localization branch.

Proposal for the Polish translation of the 'Download Kubernetes' section

---

content/it/docs/tutorials/_index.md

en PR https://github.com/kubernetes/website/pull/43234/files
/assign @fabriziopandini

[it] Remove some vertical space between lines of text

---

content/en/blog/_posts/2023-11-24-sig-testing-spotlight.md
content/en/releases/download.md

This PR syncs the dev-1.29 branch with main to keep the dev-1.29 branch up to date.
cc: @katcosgrove @drewhagen  @harshitasao @Princesso

Merged main into dev 1.29 branch

---

README.md

Fix broken link to Localization READMEs

---

content/zh-cn/docs/concepts/security/service-accounts.md

Sync file:
`content/zh-cn/docs/concepts/security/service-accounts.md`

[zh-cn] sync service-accounts.md

---

content/zh-cn/docs/concepts/services-networking/network-policies.md

Fix:modify an incoherent statement

Fix:modify an incoherent statement.

---

content/uk/_index.html

en PR https://github.com/kubernetes/website/pull/43589/files
/assign @MaxymVlasov

[uk] Update KubeCon dates for 2023-2024

---

content/en/docs/reference/command-line-tools-reference/feature-gates.md

ref: https://github.com/kubernetes/enhancements/issues/2681

[KEP-2681] Docs update for Beta PodHostIPs

---

README.md
content/en/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
content/en/releases/download.md
content/it/docs/tutorials/_index.md
content/pl/releases/download.md
content/zh-cn/docs/concepts/configuration/secret.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/security/secrets-good-practices.md
content/zh-cn/docs/concepts/security/service-accounts.md
content/zh-cn/docs/concepts/services-networking/network-policies.md
content/zh-cn/docs/contribute/participate/issue-wrangler.md
content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
content/zh-cn/docs/reference/config-api/apiserver-encryption.v1.md
content/zh-cn/docs/tutorials/_index.md
content/zh-cn/releases/download.md

Merging main into the dev branch to maintain sync

Merge main into dev-1.29

---

content/en/docs/reference/networking/virtual-ips.md

Enhancement: https://github.com/kubernetes/enhancements/issues/3866
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/3866-nftables-proxy/README.md
Implementation: https://github.com/kubernetes/kubernetes/pull/121046

Document nftables kube-proxy alpha (KEP 3866)

---

content/en/docs/reference/access-authn-authz/authentication.md

ref: https://github.com/kubernetes/enhancements/issues/3331

add docs for StructuredAuthenticationConfig v1alpha1

---

content/en/docs/contribute/localization.md

Corrected link for translating content
Fixes: #44091

corrected link for traslating content

---

content/en/docs/concepts/architecture/garbage-collection.md

garbage collection: add blurb about ImageMaximumGCAge

---

content/en/docs/concepts/cluster-administration/flow-control.md
content/en/examples/priority-and-fairness/health-for-strangers.yaml
content/en/examples/priority-and-fairness/list-events-default-service-account.yaml

- Promote APF flowcontrol API to `v1` - https://github.com/kubernetes/kubernetes/pull/121089 
- set APF featuregate to stable - https://github.com/kubernetes/kubernetes/pull/121638
- KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness
- Enhancement issue: https://github.com/kubernetes/enhancements/issues/1040

Update APF documentation for GA

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/storage-classes.md
content/en/docs/concepts/storage/volumes.md
content/en/docs/concepts/storage/windows-storage.md

Follow up on some comments from  PR #42302 
/sig storage
/cc @xing-yang 
for technical review

Update In-tree storage driver status

---

content/zh-cn/docs/tasks/access-application-cluster/access-cluster.md

Sync with en #43841 
```
content/zh-cn/docs/tasks/access-application-cluster/access-cluster.md
```

[zh] Sync /access-application-cluster/access-cluster.md

---

static/css/community.css

resolve https://github.com/kubernetes/website/issues/42314

fix community page horizontal scrolling

---

content/en/blog/_posts/2023-11-16-the-case-for-kubernetes-limits/index.md

updated image width in blog to user-friendly.

Updated image in blog 2023-11-16

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

Sync with en #43872 
```
```
See [preview](https://deploy-preview-44044--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/) please.

[zh] Add translation to create-cluster-kubeadm.md

---

content/zh-cn/docs/tutorials/security/cluster-level-pss.md

Remove useless step and command.

[zh] Sync cluster-level-pss remove useless step.

---

content/en/docs/reference/access-authn-authz/authentication.md
content/en/docs/tasks/tools/included/verify-kubectl.md

Document setting up cloud provider kubectl auth via plugin (AKS, GKE)

---

content/en/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md

- Add some commas
- Change a code block to improve readability
- Change the style of a note for consistency

Clean up troubleshooting-kubeadm.md

---

content/en/blog/_posts/2023-11-16-the-case-for-kubernetes-limits/index.md
content/en/blog/_posts/2023-11-24-sig-testing-spotlight.md
content/en/blog/_posts/2023-11-28-Gateway-API-Future.md
content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/storage-classes.md
content/en/docs/concepts/storage/volumes.md
content/en/docs/concepts/storage/windows-storage.md
content/en/docs/contribute/localization.md
content/en/docs/reference/access-authn-authz/authentication.md
content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/en/docs/tasks/tools/included/verify-kubectl.md
content/en/releases/patch-releases.md
content/uk/_index.html
content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md
content/zh-cn/docs/reference/using-api/cel.md
content/zh-cn/docs/reference/using-api/deprecation-guide.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/zh-cn/docs/tasks/access-application-cluster/access-cluster.md
content/zh-cn/docs/tasks/configure-pod-container/static-pod.md
content/zh-cn/docs/tutorials/security/cluster-level-pss.md
static/css/community.css

This PR syncs the dev-1.29 branch with main to keep the dev-1.29 branch up to date.
cc: @katcosgrove @taniaduggal @harshitasao @Princesso

Merged main dev 1.29

---

content/en/docs/concepts/windows/intro.md

Fixed the incorrect link for install ContainerD

---

content/zh-cn/docs/contribute/localization.md

[zh-cn] sync localization

---

content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md

1. Sync upstream content and format
2. Add code block with EN comment
3. Fix ZH kustomization.yaml `labels` unknown field.

[zh] Sync config-pod-configmap also fix unknown field

---

content/zh-cn/docs/concepts/windows/intro.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/zh-cn/docs/tasks/tools/included/verify-kubectl.md

[zh-cn] sync create-cluster-kubeadm verify-kubectl intro

---

content/zh-cn/docs/contribute/style/style-guide.md

1. Fix shortcode rendering in list, about #44163
2. Fix list numbers.

[zh] Fix note shortcode rendering in list

---

content/zh-cn/docs/concepts/storage/persistent-volumes.md
content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/zh-cn/releases/patch-releases.md

[zh-cn] sync persistent-volumes configure-liveness-readiness-startup-probes patch-releases

---

content/zh-cn/docs/tasks/configure-pod-container/static-pod.md

page:  https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/static-pod/#configuration-files
preview page: https://deploy-preview-44172--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/static-pod/#configuration-files
Fixes: https://github.com/kubernetes/website/issues/44071

Fix incorrect YAML format in static-web.yaml example

---

content/pl/_index.html

[pl] Update KubeCon dates for 2023-2024

---

data/i18n/en/en.toml
layouts/partials/deprecation-warning.html

Link to same page from old releases' documentation 

---

content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

en PR https://github.com/kubernetes/website/pull/43569/files

[pt] Update install-kubeadm.md

---

content/en/docs/tasks/tools/included/verify-kubectl.md

Optimize document format:
- Wrap lines that are too long
- Remove excess spaces

improve format for included/verify-kubectl.md

---

content/en/docs/tasks/debug/debug-cluster/local-debugging.md

Fix broken Telepresence link in the debugging guide 

---

content/en/docs/tutorials/security/cluster-level-pss.md

Update:
```
content/en/docs/tutorials/security/cluster-level-pss.md
```
Add code sample link to show what user will apply.

[en] Update cluster-level-pss.md show the code sample.

---

content/zh-cn/docs/tutorials/security/cluster-level-pss.md
content/zh-cn/examples/security/example-baseline-pod.yaml

Add code sample that will be applied to the cluster.
Based on #44137

[zh] Sync cluster-level-pss.

---

content/fr/docs/contribute/generate-ref-docs/kubernetes-api.md

[fr] update kubernetes-api.md link

---

content/zh-cn/docs/concepts/storage/windows-storage.md
content/zh-cn/docs/tasks/debug/debug-cluster/local-debugging.md

content/zh-cn/docs/concepts/storage/windows-storage.md
content/zh-cn/docs/tasks/debug/debug-cluster/local-debugging.md

[zh-cn] sync windows-storage local-debugging

---

content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md

content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md

[zh-cn] sync kubeadm/kubeadm-reconfigure.md

---

content/fr/docs/contribute/generate-ref-docs/federation-api.md

[fr] update federation-api.md link

---

content/zh-cn/docs/concepts/configuration/secret.md

There is a typo in `concepts/configuration/secret.md`, This PR aims to fix the typo.
Thanks.

[zh-cn] Fix concepts/configuration/secret.md typo

---

content/zh-cn/docs/concepts/storage/volume-snapshot-classes.md

There is a broken link in **zh-cn** [volume-snapshot-classes.md](https://kubernetes.io/zh-cn/docs/concepts/storage/volume-snapshot-classes/#deletion-policy).
This PR is used to fix the issue mentioned above.
Thanks.

[zh-cn] Fix volume-snapshot-classes broken-links

---

content/ru/docs/contribute/generate-ref-docs/contribute-upstream.md

en PR https://github.com/kubernetes/website/pull/43924/files

[ru] Fix link

---

content/hi/docs/tutorials/_index.md

[hi] Ensure seccomp starts with small letter

---

content/en/docs/concepts/security/pod-security-standards.md
content/en/docs/tasks/administer-cluster/sysctl-cluster.md

https://github.com/kubernetes/kubernetes/blob/v1.27.0/pkg/kubelet/sysctl/safe_sysctls.go#L39
https://github.com/kubernetes/kubernetes/blob/v1.27.0/staging/src/k8s.io/pod-security-admission/policy/check_sysctls.go#L80

update safe sysctls

---

content/en/docs/tasks/debug/debug-cluster/_index.md

Documentation Changes
- fixed some typos in the docs
- makes the sentences in the website grammatically correct

Minor text changes to the index of tasks/debug/debug-cluster

---

content/hi/docs/tasks/tools/install-kubectl-linux.md

en PR https://github.com/kubernetes/website/pull/43100/files
/assing @divya-mohan0209

[hi] Fix sha256 url missing '/release/' to download kubectl

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

Connected "pods" with "Using kubectl to Create a Deployment" tutorial.

---

content/fr/_index.html

update date kubecon doc fr

---

content/ru/_index.html

[ru] Update KubeCon dates for 2023-2024

---

content/uk/_index.html

en PR https://github.com/kubernetes/website/pull/44158
/assign @MaxymVlasov

[uk] Update KubeCon dates for 2024

---

assets/scss/_custom.scss
content/en/docs/reference/instrumentation/metrics.md

Fixes #44008
To fix this issue, this PR revert this PR -> #42823

Metrics reference is for (unreleased) v1.29

---

content/en/docs/tutorials/kubernetes-basics/public/images/module_05_scaling1.svg
content/en/docs/tutorials/kubernetes-basics/public/images/module_05_scaling2.svg
content/en/docs/tutorials/kubernetes-basics/public/images/module_06_rollingupdates1.svg
content/en/docs/tutorials/kubernetes-basics/public/images/module_06_rollingupdates2.svg
content/en/docs/tutorials/kubernetes-basics/public/images/module_06_rollingupdates3.svg
content/en/docs/tutorials/kubernetes-basics/public/images/module_06_rollingupdates4.svg

Solves issue #43711
**SCREENSHOT OF DIAGRAM BEFORE UPDATE**
**SCREENSHOT OF DIAGRAM AFTER UPDATE**

Improve visibility for tutorial diagrams through color change

---

content/zh-cn/docs/concepts/configuration/secret.md
content/zh-cn/docs/reference/kubectl/cheatsheet.md
content/zh-cn/examples/application/hpa/php-apache.yaml

content/zh-cn/examples/application/hpa/php-apache.yaml
content/zh-cn/docs/reference/kubectl/cheatsheet.md

[zh-cn] sync secret cheatsheet php-apache.yaml

---

content/pt-br/docs/concepts/extend-kubernetes/operator.md

en PR https://github.com/kubernetes/website/pull/43642/files

[pt] Update "Operator White Paper" link on operator.md page

---

content/zh-cn/_index.html

[zh-cn] Update KubeCon dates

---

data/releases/schedule.yaml

This PR adds 1.29 to the releases schedule for the 1.29.0 release.
/milestone 1.29
/cc @jimangel @marosset @Priyankasaggu11929

Add 1.29 to release schedule for 1.29 release

---

hugo.toml

Updating hugo.toml for release v1.29.
/hold until v1.29 release day.

Updates v1.26 hugo.toml for v1.29 release

---

hugo.toml

Updating hugo.toml for release v1.29.
/hold until v1.29 release day.

Updates v1.27 hugo.toml for release v1.29

---

content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta4.md

Fix #43363 
```
content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta4.md
```
See [preview](https://deploy-preview-44244--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/kubeadm-config.v1beta4/) please.

[zh] Localize kubeadm-config.v1beta4.md into Chinese

---

content/zh-cn/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md

preview page:  https://deploy-preview-44247--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/08/31/legacy-package-repository-deprecation/

[zh-cn] sync legacy-package-repository-deprecation blog

---

content/zh-cn/docs/concepts/security/pod-security-standards.md
content/zh-cn/docs/tasks/administer-cluster/sysctl-cluster.md

sync https://github.com/kubernetes/website/pull/44170

[zh-cn] sync safe sysctl

---

content/zh-cn/docs/tutorials/hello-minikube.md
content/zh-cn/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/zh-cn/docs/tutorials/kubernetes-basics/expose/expose-intro.html
content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md

[zh-cn] sync tutorials/*

---

content/zh-cn/community/_index.html

Sync X icon. #44287
Sync en comments.
Before:
https://kubernetes.io/zh-cn/community/

[zh] Sync community page.

---

content/de/_index.html

[de] Update KubeCon dates for 2024

---

content/en/blog/_posts/2023-12-15-node-expand-secret-moves-ga.md

KEP#https://github.com/kubernetes/enhancements/issues/3107

CSI NodeExpansion GA promotion blog

---

content/en/docs/reference/access-authn-authz/authentication.md

- update the example tenant value in `userInfo.Extra` to match the value in claims. 
/sig auth
/triage accepted
/assign enj

fix value in structured authn config example

---

content/pl/_index.html

[pl] Update KubeCon dates for 2024

---

content/zh-cn/docs/concepts/services-networking/service.md

Sync with the latest en text:
```
```
See [preview](https://deploy-preview-44341--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/service/) please.

[zh] Add translations to /services-networking/service.md

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Fix a 404 link due to typo of []

Fix a link in custom-resource-definitions task

---

content/es/_index.html

[es] Update KubeCon dates for 2024

---

content/fr/_index.html

[fr] Update KubeCon dates for 2024

---

content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md

[zh] Sync 1.29 docs and polish informational wording

---

content/zh-cn/examples/admin/resource/memory-available-cgroupv2.sh

content/zh-cn/examples/admin/resource/memory-available-cgroupv2.sh

[zh-cn] sync memory-available-cgroupv2.sh

---

content/en/docs/concepts/scheduling-eviction/scheduling-framework.md

- Adjust heading levels and capitalization
See [preview](https://deploy-preview-44045--kubernetes-io-main-staging.netlify.app/docs/concepts/scheduling-eviction/scheduling-framework/) please.

Update scheduling framework concept

---

content/en/docs/reference/glossary/spec.md

Add a term to the glossary: “spec”.

Add "spec" to glossary

---

content/en/docs/reference/command-line-tools-reference/kubelet.md

This PR manually syncs the reference for `kubelet`.

Update reference for kubelet 1.29

---

content/zh-cn/blog/_posts/2023-12-15-volume-attributes-class/index.md

```
content/zh-cn/blog/_posts/2023-12-15-volume-attributes-class/index.md
```
See [preview](https://deploy-preview-44373--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/12/15/kubernetes-1-29-volume-attributes-class/) please.

[zh] Kubernetes 1.29: VolumeAttributesClass for Volume Modification

---

content/pt-br/docs/reference/glossary/shuffle-sharding.md

This commit  adds Portuguese translation to the glossary term shuffle-sharding.

[pt-br] Add docs/reference/glossary/shuffle-sharding.md

---

content/en/docs/reference/labels-annotations-taints/_index.md

This PR adds some descriptions for the annotations added by the kubelet to Pods.

Add few annotations added by the kubelet

---

content/id/_index.html

[id] Update KubeCon dates for 2024

---

content/en/docs/tutorials/services/source-ip.md

 Capitalized the required words

---

content/es/docs/contribute/start.md

Fix small type error in the spanish documentation

[es] update content/es/docs/contribute/start 

---

content/en/docs/concepts/cluster-administration/addons.md

[Spiderpool](https://github.com/spidernet-io/spiderpool) is a CNCF landscape level project that provide Underlay and RDMA network solution of the Kubernetes, for bare metal, VM and any public cloud.
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)

add spiderpool into addons

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed/index.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/index.md

As suggested from:
- https://github.com/kubernetes/website/pull/44413#issuecomment-1860313038
- https://github.com/kubernetes/website/issues/44410#issuecomment-1860005932
Relocate 2 files
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed/index.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/index.md
```

[zh] Relocate feature-gates and feature-gates-removed

---

content/zh-cn/docs/concepts/cluster-administration/flow-control.md
content/zh-cn/docs/concepts/cluster-administration/system-metrics.md

content/zh-cn/docs/concepts/cluster-administration/system-metrics.md

[zh-cn] sync cluster-administration/flow-control.md system-metrics.md

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md

[zh-cn] sync pods/pod-lifecycle.md

---

content/ja/docs/home/_index.md

Addresses Japanese l10n strings described in #43068

[ja] Change footer l10n from Home to Documentation

---

content/zh-cn/docs/concepts/cluster-administration/addons.md

Add spiderpool description in zh-cn/docs/concepts/cluster-administration/addons.md

[zh] Add translations to /cluster-administration/addons.md

---

content/ko/docs/home/_index.md

Addresses Korean l10n strings described in #43068

[ko] Change footer l10n from Home to Documentation

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/immutable-ephemeral-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-place-pod-vertical-scaling.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-aws-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-azure-disk-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-azure-file-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-gce-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-openstack-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-portworx-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-rbd-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-vsphere-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/indexed-job.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ingress-class-namespaced-params.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/initializers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ip-tables-ownership-cleanup.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ipv6-dual-stack.md

Related to issue #44410. Add zh text to these pages:
1. immutable-ephemeral-volumes.md
2. in-place-pod-vertical-scaling.md
3. in-tree-plugin-aws-unregister.md
4. in-tree-plugin-azure-disk-unregister.md
5. in-tree-plugin-azure-file-unregister.md
6. in-tree-plugin-gce-unregister.md
7. in-tree-plugin-openstack-unregister.md
8. in-tree-plugin-portworx-unregister.md
9. in-tree-plugin-rbd-unregister.md
10. in-tree-plugin-vsphere-unregister.md
11. indexed-job.md
12. ingress-class-namespaced-params.md
13. initializers.md
14. ip-tables-ownership-cleanup.md
15. ipv6-dual-stack.md

[zh] Localize feature-gates/i*.md

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

Refers to https://github.com/kubernetes/sig-release/issues/2401, https://github.com/kubernetes/sig-release/issues/2400, https://github.com/kubernetes/sig-release/issues/2399

Update schedule yaml for v1.26.12, v1.27.9 and v1.28.5

---

content/en/blog/_posts/2023-12-20-contextual-logging-in-kubernetes-1-29.md

https://github.com/kubernetes/enhancements/issues/3077
see the [preview page](https://deploy-preview-43579--kubernetes-io-main-staging.netlify.app/blog/2023/12/06/contextual-logging-in-kubernetes-1-29/)

feature blog: contextual logging update for 1.29

---

content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md

```
content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md
```
See [preview](https://deploy-preview-44364--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/configure-service-account/) please.

[zh] Add translations to configure-service-account.md

---

content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md

fix the Chinese single quotes in the code to English single quotes

fix the Chinese single quotes in the code to English single quotes

---

content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
content/zh-cn/docs/reference/using-api/api-concepts.md

[zh-cn]sync kubeadm-init api-concepts

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed/index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/allow-service-lb-status-on-non-lb.md
content/en/docs/reference/command-line-tools-reference/feature-gates/image-maximum-gc-age.md
content/en/docs/reference/command-line-tools-reference/feature-gates/index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/kubelet-separate-disk-gc.md
content/en/docs/reference/command-line-tools-reference/feature-gates/nftables-proxy-mode.md
content/en/docs/reference/command-line-tools-reference/feature-gates/structured-authentication-configuration.md
content/en/docs/reference/command-line-tools-reference/feature-gates/structured-authorization-configuration.md
content/en/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md

Fix feature gates for v1.29

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/honor-pv-reclaim-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hpa-container-metrics.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hpa-scale-to-zero.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/huge-page-storage-medium-size.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/huge-pages.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hyper-v-container.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/identify-pod-os.md

Related to issue #44410. Localize these files:
1. honor-pv-reclaim-policy.md
2. hpa-container-metrics.md
3. hpa-scale-to-zero.md
4. huge-page-storage-medium-size.md
5. huge-pages.md
6. hyper-v-container.md
7. identify-pod-os.md

[zh] Localize /feature-gates/h*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/warning-headers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-bookmark.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-list.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/win-dsr.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/win-overlay.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-endpoint-slice-proxying.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-gmsa.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-host-network.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-host-process-containers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-run-as-user-name.md

Related to issue #44410. Localize w*.md files:
1. warning-headers.md
2. watch-bookmark.md
3. watch-list.md
4. win-dsr.md
5. win-overlay.md
6. windows-endpoint-slice-proxying.md
7. windows-gmsa.md
8. windows-host-network.md
9. windows-host-process-containers.md
10. windows-run-as-user-name.md

[zh] Localize feature-gates/w*.md

---

content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

```
```
See [preview](https://deploy-preview-44365--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) please.

[zh] Add translations to custom-resource-definitions.md

---

content/en/case-studies/vsco/index.html

[en] Update go lang link case index.html

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/balance-attached-node-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/block-volume.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/bound-service-account-token-volume.md

Related to issue #44410 . Localize b*.md files:
1. balance-attached-node-volumes
2. block-volume
3. bound-service-account-token-volume

[zh] Localize /feature-gates/b*.md

---

content/en/docs/tasks/administer-cluster/access-cluster-api.md
content/en/docs/tasks/administer-cluster/change-default-storage-class.md

Performed cleanup actions below:
- Provide consistent indentations for list

Clean up change-default-storage-class and access-cluster-api tasks

---

content/en/docs/tutorials/stateful-application/zookeeper.md

Fix incorrect redirection for "PersistentVolumes" in "Running ZooKeeper"  tutorial

---

content/pt-br/_index.html

[pt] Update KubeCon dates for 2024

---

content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md

```
content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
```
See [preview](https://deploy-preview-44351--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/network/extend-service-ip-ranges/) please.

[zh] Localize extend-service-ip-ranges.md

---

content/en/docs/reference/using-api/deprecation-policy.md

This was discussed at SIG Architecture meeting at 7/13/2023
https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit#bookmark=id.hnmeam992zj4 
/sig architecture
/kind feature

Document that replacement functionality must be the same stability level

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/validate-proxy-redirects.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/validating-admission-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-attributes-class.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-capacity-priority.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-pvc-data-source.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-scheduling.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-snapshot-data-source.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-subpath-env-expansion.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-subpath.md

Related to issue #44410. Localize these v*.md:
1. validate-proxy-redirects.md
2. validating-admission-policy.md
3. volume-attributes-class.md
4. volume-capacity-priority.md
5. volume-pvc-data-source.md
6. volume-scheduling.md
7. volume-snapshot-data-source.md
8. volume-subpath-env-expansion.md
9. volume-subpath.md

[zh] Localize feature-gates/v*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/match-label-keys-in-pod-affinity.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/match-label-keys-in-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/max-unavailable-stateful-set.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/memory-manager.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/memory-qos.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/min-domains-in-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/minimize-ip-tables-restore.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mixed-protocol-lb-service.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mount-containers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mount-propagation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/multi-cidr-range-allocator.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/multi-cidr-service-allocator.md

Related to issue #44410 . Localize these files:
1. match-label-keys-in-pod-affinity
2. match-label-keys-in-pod-topology-spread
3. max-unavailable-stateful-set
4. memory-manager
5. memory-qos
6. min-domains-in-pod-topology-spread
7. minimize-ip-tables-restore
8. mixed-protocol-lb-service
9. mount-containers
10. mount-propagation
11. multi-cidr-range-allocator
12. multi-cidr-service-allocator

[zh] Localize feature-gates/m*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/gce-regional-persistent-disk.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/generic-ephemeral-volume.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/graceful-node-shutdown-based-on-pod-priority.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/graceful-node-shutdown.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/grpc-container-probe.md

Localize 5 feature-gates/g*.md:
* gce-regional-persistent-disk.md
* generic-ephemeral-volume.md
* graceful-node-shutdown-based-on-pod-priority.md
* graceful-node-shutdown.md
* grpc-container-probe.md

[zh] Localize feature-gates/g*.md

---

content/zh-cn/docs/tasks/administer-cluster/access-cluster-api.md
content/zh-cn/docs/tasks/administer-cluster/change-default-storage-class.md

content/zh-cn/docs/tasks/administer-cluster/access-cluster-api.md
content/zh-cn/docs/tasks/administer-cluster/change-default-storage-class.md

[zh-cn] sync access-cluster-api change-default-storage-class

---

content/zh-cn/docs/tasks/debug/debug-application/debug-pods.md

sync debug-pods.md
```
content/en/docs/tasks/debug/debug-application/debug-pods.md
```

[zh-cn] sync debug-pods.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/unauthenticated-http2-dos-mitigation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/unknown-version-interoperability-proxy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/user-namespaces-pod-security-standards.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/user-namespaces-stateless-pods-support.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/user-namespaces-support.md

Related to issue https://github.com/kubernetes/website/issues/44410. Localized these files:
unauthenticated-http2-dos-mitigation.md
unknown-version-interoperability-proxy.md
user-namespaces-pod-security-standards.md
user-namespaces-stateless-pods-support.md
user-namespaces-support.md

[zh] sync feature-gates/u*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pdb-unhealthy-pod-eviction-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/persistent-local-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/persistent-volume-last-phase-transition-time.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-affinity-namespace-selector.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-and-container-stats-from-cri.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-deletion-cost.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-disruption-budget.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-disruption-conditions.md

Related to issue #44410. Localized these files:
1. pdb-unhealthy-pod-eviction-policy.md
2. persistent-local-volumes.md
3. persistent-volume-last-phase-transition-time.md
4. pod-affinity-namespace-selector.md
5. pod-and-container-stats-from-cri.md
6. pod-deletion-cost.md
7. pod-disruption-budget.md
8. pod-disruption-conditions.md

[zh] Localize part1 of /feature-gates/p*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/namespace-default-label-name.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/network-policy-end-port.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/network-policy-status.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/nftables-proxy-mode.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-disruption-exclusion.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-inclusion-policy-in-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-lease.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-log-query.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-out-of-service-volume-detach.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-swap.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/non-preempting-priority.md

Related to issue #44410. Localize these files:
1. namespace-default-label-name.md
2. network-policy-end-port.md
3. network-policy-status.md
4. new-volume-manager-reconstruction.md
5. nftables-proxy-mode.md
6. node-disruption-exclusion.md
7. node-inclusion-policy-in-pod-topology-spread.md
8. node-lease.md
9. node-log-query.md
10. node-out-of-service-volume-detach.md
11. node-swap.md
12. non-preempting-priority.md

[zh] Localize feature-gates/n*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/warning-headers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-bookmark.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-list.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/win-dsr.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/win-overlay.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-endpoint-slice-proxying.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-gmsa.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-host-network.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-host-process-containers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-run-as-user-name.md

Related to issue #44410. Only updated the front matters:
1. warning-headers.md
2. watch-bookmark.md
3. watch-list.md
4. win-dsr.md
5. win-overlay.md
6. windows-endpoint-slice-proxying.md
7. windows-gmsa.md
8. windows-host-network.md
9. windows-host-process-containers.md
10. windows-run-as-user-name.md

[zh] Sync feature-gates/w*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/validate-proxy-redirects.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/validating-admission-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-attributes-class.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-capacity-priority.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-pvc-data-source.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-scheduling.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-snapshot-data-source.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-subpath-env-expansion.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-subpath.md

Related to issue #44410. Only updated the front matters:
1. validate-proxy-redirects.md
2. validating-admission-policy.md
3. volume-attributes-class.md
4. volume-capacity-priority.md
5. volume-pvc-data-source.md
6. volume-scheduling.md
7. volume-snapshot-data-source.md
8. volume-subpath-env-expansion.md
9. volume-subpath.md

[zh] Sync feature-gates/v*.md

---

content/zh-cn/docs/tasks/debug/debug-application/debug-pods.md

Updated some text by following https://github.com/kubernetes/website/pull/44508#discussion_r1436066653
```
content/zh-cn/docs/tasks/debug/debug-application/debug-pods.md
```

[zh] Update debug-pods.md to apply text suggestions

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/efficient-watch-resumption.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/elastic-indexed-job.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/enable-aggregated-discovery-timeout.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/enable-equivalence-class-cache.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/endpoint-slice-node-name.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/endpoint-slice-proxying.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/endpoint-slice-terminating-condition.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/endpoint-slice.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ephemeral-containers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/even-pods-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/evented-pleg.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/exec-probe-timeout.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/expand-csi-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/expand-in-use-persistent-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/expand-persistent-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/expanded-dns-config.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/experimental-critical-pod-annotation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/experimental-host-user-namespace-defaulting.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/external-policy-for-external-ip.md

Localize 19 feature-gates/e*.md:
* efficient-watch-resumption.md
* elastic-indexed-job.md
* enable-aggregated-discovery-timeout.md
* enable-equivalence-class-cache.md
* endpoint-slice-node-name.md
* endpoint-slice-proxying.md
* endpoint-slice-terminating-condition.md
* endpoint-slice.md
* ephemeral-containers.md
* even-pods-spread.md
* evented-pleg.md
* exec-probe-timeout.md
* expand-csi-volumes.md
* expand-in-use-persistent-volumes.md
* expand-persistent-volumes.md
* expanded-dns-config.md
* experimental-critical-pod-annotation.md
* experimental-host-user-namespace-defaulting.md
* external-policy-for-external-ip.md

[zh] Localize feature-gates/e*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/honor-pv-reclaim-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hpa-container-metrics.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hpa-scale-to-zero.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/huge-page-storage-medium-size.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/huge-pages.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hyper-v-container.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/identify-pod-os.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/immutable-ephemeral-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-place-pod-vertical-scaling.md

Related to issue #44410. Only updated the front matters:
1. honor-pv-reclaim-policy.md
2. hpa-container-metrics.md
3. hpa-scale-to-zero.md
4. huge-page-storage-medium-size.md
5. huge-pages.md
6. hyper-v-container.md
7. identify-pod-os.md
8. immutable-ephemeral-volumes.md
9. in-place-pod-vertical-scaling.md

[zh] Sync feature-gates/h*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/qos-reserved.md

Related to issue https://github.com/kubernetes/website/issues/44410. Localized these files:
qos-reserved.md

[zh] sync feature-gates/q*.md

---

content/zh-cn/blog/2023-11-24-sig-testing-spotlight.md

en PR https://github.com/kubernetes/website/pull/44108/files

[zh] Fix the broken link in blog post

---

content/ja/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md

fix #44232 
- fix code block bug in `content/ja/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md`

[ja] fix: code block in `content/ja/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md`

---

content/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

en PR https://github.com/kubernetes/website/pull/43569/files

[ja] Update install-kubeadm.md

---

content/en/blog/_posts/2021-10-05-nsa-cisa-hardening.md

NSA and CISA released the 1.0 version of the Kubernetes hardening guide in August 2021 and updated it based on industry feedback in March 2022 (version 1.1). The most recent version of the Kubernetes hardening guidance was released in August 2022 with corrections and clarifications.

Update hardening Kubernetes clusters URL in website to the latest version 1.2

---

content/zh-cn/blog/_posts/2023-11-24-sig-testing-spotlight.md

To sync with the en upstream, mainly relocate this blog from
```
content/zh-cn/blog/
```
to
```
content/zh-cn/blog/_posts/
```

[zh] Relocate a blog: 2023-11-24-sig-testing-spotlight

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/taint-based-evictions.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/taint-nodes-by-condition.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/token-request-projection.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/token-request.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-aware-hints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-manager-policy-alpha-options.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-manager-policy-beta-options.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-manager-policy-options.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-manager.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/translate-stream-close-websocket-requests.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ttl-after-finished.md

Related to issue #44410. Localized these t*.md:
1. taint-based-evictions.md
2. taint-nodes-by-condition.md
3. token-request-projection.md
4. token-request.md
5. topology-aware-hints.md
6. topology-manager-policy-alpha-options.md
7. topology-manager-policy-beta-options.md
8. topology-manager-policy-options.md
9. topology-manager.md
10. translate-stream-close-websocket-requests.md
11. ttl-after-finished.md

[zh] Localize feature-gates/t*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-has-network-condition.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-host-ips.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-index-label.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-overhead.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-priority.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-readiness-gates.md

Related to issue #44410. Localize these files:
1. pod-has-network-condition.md
2. pod-host-ips.md
3. pod-index-label.md
4. pod-lifecycle-sleep-action.md
5. pod-overhead.md
6. pod-priority.md
7. pod-readiness-gates.md

[zh] Localize part2 of feature-gates/p*.md

---

content/fr/docs/contribute/_index.md

[fr] Fix broken GitHub Learning link

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kmsv1.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kmsv2-kdf.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kmsv2.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-cgroup-driver-from-cri.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-config-file.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-credential-providers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-in-user-namespace.md

Related to issue #44410 . Localized these files:
1. kmsv1.md
2. kmsv2-kdf.md
3. kmsv2.md
4. kubelet-cgroup-driver-from-cri.md
5. kubelet-config-file.md
6. kubelet-credential-providers.md
7. kubelet-in-user-namespace.md

[zh] Localize part1 of /feature-gates/k*.md

---

content/en/docs/tutorials/services/source-ip.md

Add note to specify only AMD64 compatibility for example image

---

content/zh-cn/blog/_posts/2023-12-18-kubernetes-1-29-feature-loadbalancer-ip-mode-alpha.md

[zh] Localize a blog: 2023-12-18-kubernetes-1-29-feature-loadbalancer-ip-mode-alpha.md
[preview](https://deploy-preview-44444--kubernetes-io-main-staging.netlify.app/)

[zh] Localize a blog: 2023-12-18-kubernetes-1-29-feature-loadbalancer-ip-mode-alpha.md

---

content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md

[zh-cn] sync basic-stateful-set.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md

Related to issue #44410
Localize 1 feature-gates/z*.md:
1. zero-limited-nominal-concurrency-shares.md

[zh] Localize feature-gates/z*.md

---

content/en/docs/tasks/configure-pod-container/configure-service-account.md
content/en/docs/tasks/extend-kubernetes/setup-konnectivity.md

fix serviceaccount-token-volume-projection link

---

content/zh-cn/docs/tasks/job/fine-parallel-processing-work-queue.md

content/zh-cn/docs/tasks/job/fine-parallel-processing-work-queue.md

[zh-cn] sync fine-parallel-processing-work-queue.md

---

static/css/style_apiref.css

Fix API reference problem

---

README-pl.md

Update README file for Polish localization.

Update README for Polish localization

---

content/hi/docs/contribute/_index.md

[hi] Fix broken GitHub Learning link

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

Grammar corrections

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/read-write-once-pod.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/recover-volume-expansion-failure.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/remaining-item-count.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/remove-self-link.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/request-management.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/resource-limits-priority-function.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/resource-quota-scope-selectors.md

Related to issue #44410. Localized these files:
1. read-write-once-pod.md
2. recover-volume-expansion-failure.md
3. remaining-item-count.md
4. remove-self-link.md
5. request-management.md
6. resource-limits-priority-function.md
7. resource-quota-scope-selectors.md

[zh] Localize feature-gates/r*.md

---

content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md

Improve an expression from 'value's to 'values' for taint-and-toleration

---

OWNERS
OWNERS_ALIASES

- add kbhawkey to emeritus approvers
- see https://github.com/kubernetes/org/pull/4650

update en admins list

---

content/en/docs/reference/command-line-tools-reference/feature-gates/topology-manager-policy-options.md

For the explanation of `TopologyManagerPolicyOptions`, link to the existing docs about it.
[preview](https://deploy-preview-44624--kubernetes-io-main-staging.netlify.app//docs/reference/command-line-tools-reference/feature-gates/)
/sig node

Link to topology manager fine tuning docs from feature gate

---

content/en/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md

find by using regex `(?<!])\[[^\]]*\]\((?!https?://|mailto:|about:blank)[a-z0-9](?!.*png|.*svg|.*jpg)`

fix links in blog

---

content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md

Fix typos and some minor changes about newline:
```
content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
```

[zh] Update kubeadm-config.v1beta3.md

---

content/zh-cn/blog/_posts/2023-12-19-PodReadyToStartContainersCondition-in-beta.md

```
content/zh-cn/blog/_posts/2023-12-19-PodReadyToStartContainersCondition-in-beta.md
```
See [preview](https://deploy-preview-44348--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/12/19/pod-ready-to-start-containers-condition-now-in-beta/) please.

[zh] Localize a blog: PodReadyToStartContainersCondition-in-beta.md

---

content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md

Added a very small clarification on how to run this guide on `minikube`.

Add a clarification for autoscaling on minikube

---

content/en/docs/reference/command-line-tools-reference/feature-gates-removed/index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/remove-self-link.md

/hold 
util https://github.com/kubernetes/kubernetes/pull/122468 is merged
Fix https://github.com/kubernetes/kubernetes/issues/122466

remove GA featuregate RemoveSelfLink

---

content/en/docs/tutorials/stateful-application/basic-stateful-set.md

Split out from PR #42767
Revise the  “Updating StatefulSets” section of the [StatefulSet tutorial](https://k8s.io/docs/tutorials/stateful-application/basic-stateful-set).

Revise StatefulSet tutorial updates advice

---

content/zh-cn/docs/concepts/configuration/secret.md

en PR https://github.com/kubernetes/website/pull/44251/files

[zh] Fix typo in TLS Secrets part

---

content/zh-cn/docs/contribute/new-content/new-features.md

```
content/zh-cn/docs/contribute/new-content/new-features.md
```

[zh] Sync contribute/new-content/new-features.md

---

content/pt-br/docs/contribute/_index.md

[pt] Fix broken GitHub Learning link

---

content/pt-br/docs/concepts/configuration/secret.md

en PR https://github.com/kubernetes/website/pull/44251/files

[pt] Fix typo in TLS Secrets part

---

content/zh-cn/docs/reference/glossary/cloud-controller-manager.md

[zh-cn] Optimize Linguistic logic

---

content/en/docs/tutorials/hello-minikube.md
content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html

This PR tries to fix https://github.com/kubernetes/website/issues/43256 
Made the following changes:
1. On the page [Using Minikube to Create a Cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/ ) removed the link to [Using kubectl to Create a Deployment](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/).
This is done as the [Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) page already refers to [Using kubectl to Create a Deployment](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/).
2. On the [Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) page, added a note to highlight that only the minikube installation step from [minikube …

Improve user guidance in Kubernetes basics tutorials

---

content/en/docs/concepts/configuration/secret.md
content/en/docs/concepts/extend-kubernetes/_index.md
content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
content/en/docs/concepts/security/hardening-guide/authentication-mechanisms.md
content/en/docs/contribute/new-content/_index.md
content/en/docs/contribute/style/write-new-topic.md
content/en/docs/reference/access-authn-authz/kubelet-authn-authz.md
content/en/docs/reference/command-line-tools-reference/feature-gates/custom-pod-dns.md
content/en/docs/setup/production-environment/container-runtimes.md
content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/en/docs/tasks/access-application-cluster/access-cluster-services.md
content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
content/en/docs/tasks/debug/debug-application/debug-init-containers.md
content/en/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md

fix outdated link/anchor

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/logging-alpha-options.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/logging-beta-options.md

en PR #44638
Correct typo from 'fine-tuing' to 'fine-tuning'.

[zh] Fix typo in feature gates page

---

content/zh-cn/docs/contribute/_index.md

content/zh-cn/docs/contribute/_index.md

[zh-cn] sync contribute/_index.md

---

content/id/docs/tutorials/kubernetes-basics/_index.html

This is actually in Bahasa Indonesia.

[id] Fix language code for tutorial

---

content/en/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md

- fixes broken links to ii.nz site
- use _ii.nz_ instead of _ii-Team_

chore: fix links and names for ii.nz

---

content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

en PR https://github.com/kubernetes/website/pull/44369

[zh] Fix typo & link

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md

```
content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md
```

[zh] Sync kube-proxy.md

---

content/uk/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
content/uk/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
content/uk/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
content/uk/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/uk/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
content/uk/docs/tutorials/kubernetes-basics/explore/explore-intro.html
content/uk/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
content/uk/docs/tutorials/kubernetes-basics/expose/expose-intro.html
content/uk/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
content/uk/docs/tutorials/kubernetes-basics/scale/scale-intro.html
content/uk/docs/tutorials/kubernetes-basics/update/update-interactive.html
content/uk/docs/tutorials/kubernetes-basics/update/update-intro.html

[uk] Fix language code for tutorials

---

content/en/docs/tasks/administer-cluster/encrypt-data.md

This is split out from PR https://github.com/kubernetes/website/pull/33285 in order to make a review more likely. See that PR and its previews to show the changes in a wider context. There is also a [preview](https://deploy-preview-44675--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/encrypt-data/#understanding-the-encryption-at-rest-configuration) for _this_ PR.
Make a comment in some YAML extra obvious to readers.
/language en

Highlight important comment in API encryption at rest task

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

~resolves~ helps with https://github.com/kubernetes/website/issues/44674

Add notes on kubeadm clusters version

---

content/en/docs/contribute/docs.md
content/en/docs/contribute/participate/pr-wranglers.md

Optimize document format:
- Wrap lines that are too long
- Remove excess spaces

improve format for contribute/docs.md pr-wranglers.md

---

content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md

content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md

[zh-cn] sync coarse-parallel-processing-work-queue.md

---

content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md

en PR #44499
Fix number of types of hook handlers available to implement for Containers.

[zh] Fix typo in the number of types of hook handlers for Containers

---

content/zh-cn/docs/concepts/services-networking/ingress-controllers.md

en PR https://github.com/kubernetes/website/pull/44276/files

[zh] Fix voyager link

---

content/pl/docs/contribute/_index.md

[pl] Fix broken GitHub Learning link

---

OWNERS_ALIASES

Hey y'all, I hope this message finds you well!
As the current SIG Release docs lead for the v1.30 release cycle, I would like to request temporary approver privileges.
Thanks!
Drew
/cc @sftim @reylejano @tengqm
/cc @katcosgrove @gracenng

Approval permission for 1.30 Release

---

content/ja/docs/contribute/_index.md

[ja] Fix broken GitHub Learning link

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md

This patch fixes the language of the comment for the webhook conversion strategy.

Fixes comment for webhook conversion strategy

---

content/de/docs/reference/glossary/kube-apiserver.md
content/de/docs/reference/glossary/kube-controller-manager.md
content/de/docs/reference/glossary/kube-scheduler.md
content/de/docs/reference/glossary/kubelet.md

This PR is to remove the master/slave terminology from some files in the glossary of the German localization.

[de] modified files to remove master/slave terminology

---

content/id/docs/concepts/services-networking/ingress-controllers.md

en PR https://github.com/kubernetes/website/pull/44276/files

[id] Fix voyager link

---

README-bn.md

Fix small typing mistake ( bangla)
Tracking issue: #31677

[bn] Fix typo in README-bn.md

---

content/zh-cn/docs/concepts/architecture/nodes.md

en PR https://github.com/kubernetes/website/pull/44296/files

[zh] Update feature state for TopologyManager

---

content/ja/docs/home/_index.md

close #44616 
- Update `content/ja/docs/home/_index.md`
- Updated some links and their descriptions

[ja] Update `content/ja/docs/home/_index.md`

---

content/zh-cn/docs/contribute/docs.md

content/zh-cn/docs/contribute/docs.md

[zh-cn] sync contribute/docs.md

---

data/i18n/pl/pl.toml

Added new strings from data/i118n/en/en.toml that were previously missing in the Polish version of this file, and updated existing translations.

Updated Polish version of the TOML i118n file (data/i118n/pl/pl.toml).

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

- Add January 2024 patch releases to the calendar
- Propose dates for April 2024 patch releases
/assign @puerco @jeremyrickard 

Add January patch releases to the calendar

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Somehow duplicate notes added since the change https://github.com/kubernetes/website/pull/43626 in the first file. 
The second file was fine.
Removing the duplicate note.

Removing the duplicate note

---

content/en/docs/reference/access-authn-authz/authentication.md

Azure Active Directory is now Microsoft Entra ID.
Changing for the sake of correctness.

Update authentication.md - Azure Active Directory is now Microsoft Entra ID

---

hugo.toml

Updating the hugo.toml for v1.30

Updates hugo.toml for 1.30 release

---

content/zh-cn/docs/contribute/participate/pr-wranglers.md

Sync with en #44686 :
```
content/zh-cn/docs/contribute/participate/pr-wranglers.md
```
See [preview](https://deploy-preview-44690--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/participate/pr-wranglers/) please.

[zh] Sync participate/pr-wranglers.md

---

content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
content/zh-cn/docs/tasks/extend-kubernetes/socks5-proxy-access-api.md

content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
content/zh-cn/docs/tasks/extend-kubernetes/socks5-proxy-access-api.md

[zh-cn] sync configure-aggregation-layer socks5-proxy-access-api

---

content/zh-cn/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md

Sync with en #44720 and more wrapping changes:
```
content/zh-cn/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md
```

[zh] Sync a blog: 2023-08-15-pkgs-k8s-io-introduction.md

---

content/zh-cn/docs/home/_index.md

content/zh-cn/docs/home/_index.md

[zh-cn] sync docs/home/_index.md

---

content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md
content/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry.md
content/zh-cn/docs/tasks/tools/install-kubectl-linux.md

content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md
content/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry.md

[zh-cn] sync install-kubectl-linux pull-image-private-registry configure-pod-configmap

---

content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors.md

content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors.md

[zh-cn] sync and improve troubleshooting-cni-plugin-related-errors.md

---

content/zh-cn/docs/tasks/administer-cluster/coredns.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md

content/zh-cn/docs/tasks/administer-cluster/coredns.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md

[zh-cn] sync coredns upgrading-linux-nodes

---

content/it/_index.html

If there are any mistakes let me know, thanks
/assign @Fale

[it] Update KubeCon dates for 2024

---

content/en/docs/contribute/generate-ref-docs/metrics-reference.md

- Provide a consistent look for headings and title
- Fix some grammars and indentations

Clean up metrics-reference.md

---

content/zh-cn/docs/contribute/style/diagram-guide.md
content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
content/zh-cn/docs/contribute/style/write-new-topic.md

```
M       content/zh-cn/docs/contribute/style/diagram-guide.md
M       content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
M       content/zh-cn/docs/contribute/style/write-new-topic.md
```

[zh-cn] sync contribute/style/*

---

content/zh-cn/docs/contribute/generate-ref-docs/kubectl.md

content/zh-cn/docs/contribute/generate-ref-docs/kubectl.md

[zh-cn]sync generate-ref-docs/kubectl.md

---

content/zh-cn/docs/tutorials/configuration/configure-redis-using-configmap.md

en PR https://github.com/kubernetes/website/pull/44396/files

[zh] Update configure-redis-using-configmap.md

---

content/zh-cn/docs/concepts/scheduling-eviction/resource-bin-packing.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md

content/zh-cn/docs/concepts/scheduling-eviction/resource-bin-packing.md

[zh-cn] sync resource-bin-packing create-cluster-kubeadm encrypt-data

---

layouts/case-studies/list.html

Corrected Hindi Sentence Formating 

---

content/zh-cn/blog/_posts/2023-08-24-swap-beta1-graduation.md
content/zh-cn/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md
content/zh-cn/docs/concepts/cluster-administration/flow-control.md
content/zh-cn/docs/concepts/configuration/secret.md
content/zh-cn/docs/concepts/extend-kubernetes/_index.md
content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
content/zh-cn/docs/contribute/new-content/_index.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-pod-dns.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/network-policy-end-port.md
content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
content/zh-cn/docs/reference/using-api/_index.md
content/zh-cn/docs/setup/production-environment/container-runtimes.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
content/zh-cn/docs/tasks/access-application-cluster/access-cluster-services.md
content/zh-cn/docs/tasks/administer-cluster/access-cluster-api.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
content/zh-cn/docs/tasks/configure-pod-container/configure-pod-initialization.md
content/zh-cn/docs/tasks/debug/debug-application/debug-init-containers.md
content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
content/zh-cn/docs/tasks/inject-data-application/distribute-credentials-secure.md
content/zh-cn/docs/tutorials/stateful-application/zookeeper.md

All files involving changes have been checked for anchor availability, and there is no problem.

[zh-cn] fix outdated link/anchor

---

content/zh-cn/docs/contribute/generate-ref-docs/metrics-reference.md

```
content/zh-cn/docs/contribute/generate-ref-docs/metrics-reference.md
```
See [preview](https://deploy-preview-44842--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/generate-ref-docs/metrics-reference/) please.

[zh] Localize metrics-reference.md

---

content/zh-cn/docs/tasks/access-application-cluster/create-external-load-balancer.md

en PR https://github.com/kubernetes/website/pull/43634/files

[zh] Fixed a typo on page "Create an External Load Balancer"

---

content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/zh-cn/docs/concepts/scheduling-eviction/kube-scheduler.md
content/zh-cn/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md

```
M       content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
M       content/zh-cn/docs/concepts/scheduling-eviction/kube-scheduler.md
M       content/zh-cn/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
M       content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
M       content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
```

[zh-cn] sync scheduling-eviction/*

---

content/zh-cn/docs/concepts/security/security-checklist.md

Sync with en #42355 
```
content/zh-cn/docs/concepts/security/security-checklist.md
```

[zh] Sync /security/security-checklist.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md

en PR https://github.com/kubernetes/website/pull/44563/files

[zh] Fix feature-gates/z*.md content format

---

content/zh-cn/docs/concepts/services-networking/dns-pod-service.md

[zh-cn] sync services-networking/dns-pod-service.md

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

Fix typo in deploy-intro.html

---

content/zh-cn/docs/concepts/services-networking/dual-stack.md

content/zh-cn/docs/concepts/services-networking/dual-stack.md

[zh-cn] sync services-networking/dual-stack.md

---

content/zh-cn/docs/reference/using-api/deprecation-policy.md

Sync with en #42031 
```
content/zh-cn/docs/reference/using-api/deprecation-policy.md
```
See [preview](https://deploy-preview-44890--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/using-api/deprecation-policy/)

[zh] Sync /using-api/deprecation-policy.md

---

content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
content/zh-cn/docs/concepts/configuration/secret.md

[zh-cn] sync manage-resources-containers.md secret.md

---

content/zh-cn/docs/concepts/architecture/controller.md

Delete a word to make the sentence smoother

[zh-cn]Update architecture/controller.md

---

OWNERS
OWNERS_ALIASES

This PR reactivates Celeste (Me!) as an approver, because I'm back baybeeee!!!!

Re-activate celestehorgan as approver for SIG Docs

---

content/en/docs/contribute/localization.md
hugo.toml

This PR enhances the arrangement of localized language choices within the navbar dropdown menu. The improvement is achieved through the implementation of alphabetical sorting based on English equivalents, by utilizing the `weight` configuration value in `hugo.toml` for the respective languages. The changes contribute to a more organized and user-friendly navigation experience.
[Preview Page](https://deploy-preview-44869--kubernetes-io-main-staging.netlify.app/)

Enhance language dropdown ordering

---

content/id/docs/tasks/configure-pod-container/configure-service-account.md

en PR https://github.com/kubernetes/website/pull/42446/files
/assign @girikuncoro

[id] Make image registry hostname more obvious in example

---

content/ru/examples/application/guestbook/frontend-deployment.yaml
content/ru/examples/application/guestbook/redis-follower-deployment.yaml

en PR https://github.com/kubernetes/website/pull/44290/files

[ru] Replaced unavailable image

---

content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
content/zh-cn/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md

Sync 2 files:
```
content/zh-cn/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
```

[zh] Sync configure-upgrade-etcd.md and dns-horizontal-autoscaling.md

---

content/zh-cn/docs/concepts/services-networking/gateway.md

fix https://github.com/kubernetes/website/issues/44310

[zh-cn]localize content/zh-cn/docs/concepts/services-networking/gateway.md

---

content/zh-cn/docs/concepts/workloads/pods/sidecar-containers.md

```
```
See [preview](https://deploy-preview-44308--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/sidecar-containers/) please.

[zh] Localize /pods/sidecar-containers.md into Chinese

---

content/zh-cn/docs/concepts/storage/persistent-volumes.md

en PR https://github.com/kubernetes/website/pull/44840/files

[zh] typo fix: "claimPolicy" to "persistentVolumeReclaimPolicy"

---

OWNERS_ALIASES

I am stepping down from my SIG Docs Technical Lead role to make room for new contributors and maintainers. Thank you ALL for a wonderful experience, and I promise not to go TOO far 😄

Move onlydole to emeritus for SIG Docs Tech Lead

---

content/pt-br/docs/concepts/storage/persistent-volumes.md

en PR https://github.com/kubernetes/website/pull/44840/files

[pt] typo fix: "claimPolicy" to "persistentVolumeReclaimPolicy"

---

content/zh-cn/docs/concepts/overview/components.md
content/zh-cn/docs/concepts/overview/working-with-objects/names.md
content/zh-cn/docs/tutorials/hello-minikube.md

content/zh-cn/docs/concepts/overview/components.md
content/zh-cn/docs/concepts/overview/working-with-objects/names.md
content/zh-cn/docs/tutorials/hello-minikube.md

[zh-cn] sync names components hello-minikube

---

content/ja/docs/concepts/services-networking/ingress-controllers.md

en PR https://github.com/kubernetes/website/pull/44276/files
/assign @t-inu 

[ja] Fix voyager link

---

content/zh-cn/docs/reference/scheduling/config.md

content/zh-cn/docs/reference/scheduling/config.md

[zh-cn]sync scheduling/config.md

---

content/en/docs/concepts/services-networking/dns-pod-service.md

updated the link for admission webhook controller in dns for pod and service page

---

content/ja/docs/concepts/architecture/_index.md

close #44916 
- added the figure
- added the description 
in `content/ja/docs/concepts/architecture/_index.md`

[ja] add figure/description in `content/ja/docs/concepts/architecture/_index.md`

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

Using one of the suggested solution in https://github.com/kubernetes/website/issues/45007#issuecomment-1925442177 in this PR to fix issue https://github.com/kubernetes/website/issues/45007
~Closes&nbsp;https://github.com/kubernetes/website/issues/45007~

Add link to supported networking addons in "Creating a cluster with kubeadm" page

---

content/zh-cn/docs/concepts/security/rbac-good-practices.md

en PR https://github.com/kubernetes/website/pull/44957/files

[zh] Resolve typos

---

content/zh-cn/docs/reference/kubectl/quick-reference.md

content/zh-cn/docs/reference/kubectl/quick-reference.md

[zh-cn] sync kubectl/quick-reference.md

---

content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1.md

content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1.md

[zh-cn]sync kubelet-credentialprovider.v1.md

---

content/bn/releases/notes.md

Localize notes.md in bangla 
fixes issue : #44993

[bn] Localize notes.md

---

content/en/docs/concepts/storage/volumes.md

Fixed the link for create a ConfigMap

---

netlify.toml

Signed-off-by: David Tesar <david.tesar@microsoft.com>

Update hugo and node versions

---

content/pt-br/docs/tasks/access-application-cluster/access-cluster.md
content/pt-br/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md

This PR syncs the dev-1.30 branch with the main branch to keep the dev-1.30 branch up to date.
cc: @Vyom-Yadav  @drewhagen @chanieljdan @celestehorgan

Merge main branch into dev-1.30

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

Update the kubeadm page docs

---

content/zh-cn/docs/reference/kubectl/quick-reference.md

en PR https://github.com/kubernetes/website/pull/44914/files

[zh] Update quick-reference.md

---

content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md

en PR https://github.com/kubernetes/website/pull/45022/files

[zh] Fix path for example yaml

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

[zh-cn] sync kubeadm/create-cluster-kubeadm.md

---

content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

Fixes #44812
Deployment preview: https://deploy-preview-44815--kubernetes-io-main-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#kubeadm-s-skew-against-the-kubelet

Fix Kubelet skew version for the Kubeadm

---

content/en/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md

update kubeconfig user --config

---

content/en/docs/reference/command-line-tools-reference/feature-gates/readonly-apidata-volumes.md

Add ReadOnlyAPIDataVolumes in removed feature gates list

---

content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md

content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md

[zh-cn] sync kubeadm-config.v1beta3.md

---

content/zh-cn/docs/tasks/extend-kubernetes/socks5-proxy-access-api.md

en PR https://github.com/kubernetes/website/pull/45120/files

[zh] fix broken mermaid diagram

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/readonly-apidata-volumes.md

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/readonly-apidata-volumes.md

[zh-cn]sync readonly-apidata-volumes.md

---

content/zh-cn/docs/concepts/workloads/pods/init-containers.md

Sync one of en #43346:
```
```
See [preview](https://deploy-preview-44307--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/init-containers/) please.

[zh] Sync /pods/init-containers.md

---

content/zh-cn/docs/reference/kubernetes-api/other-resources/validating-admission-policy-binding-list-v1beta1.md

[zh-cn]sync validating-admission-policy-binding-list-v1beta1.md

---

content/en/docs/reference/labels-annotations-taints/_index.md

…ailure annotation
tried solving according to the issue mentioned in https://github.com/kubernetes/website/issues/45187#issue-2140222281

Register audit annotation for admission policy validation

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md

en PR https://github.com/kubernetes/website/pull/44953/files

[zh] Add missing space

---

content/en/releases/patch-releases.md
data/releases/schedule.yaml

This PR adds the updated patch release info for February patch releases and proposes the dates for May patch releases. 
/sig release
/area release-eng
/assign @saschagrunert @xmudrii

Add feb patch updates and propose May patch release dates

---

content/en/docs/concepts/services-networking/network-policies.md

Provide changes about consistency and grammar,
and remove some redundant spaces.

Minor improvements to network-policies concept

---

content/zh-cn/docs/contribute/localization.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md

[zh-cn] sync encrypt-data create-cluster-kubeadm encrypt-data localization

---

content/en/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy.md

Updated links related to Weave Net documentation to placing onus of upkeep on Weave Net's github repository.
Closes #45257

Fix broken link for "Install the Weave Net addon" documentation in "Weave Net for NetworkPolicy" page

---

content/en/docs/reference/kubectl/kubectl.md

- Update reference links to commands
- Add a few minor changes

Update reference links to commands in /kubectl/kubectl.md

---

content/zh-cn/docs/concepts/architecture/garbage-collection.md
content/zh-cn/docs/concepts/policy/limit-range.md
content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/zh-cn/docs/concepts/security/api-server-bypass-risks.md

[zh] fix typo in `content/zh-cn/docs/concepts`

[zh] fix typo in `content/zh-cn/docs/concepts`

---

content/zh-cn/docs/reference/config-api/apiserver-admission.v1.md
content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md

content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md

[zh-cn] sync apiserver-admission.v1.md imagepolicy.v1alpha1.md

---

content/en/blog/_posts/2024-02-22-k8s-book-club/index.md

[blog] Emphasis on person's name.

---

content/zh-cn/docs/reference/kubectl/kubectl-cmds.md
content/zh-cn/docs/reference/kubectl/kubectl.md

Update two files:
```bash
modified:   content/zh-cn/docs/reference/kubectl/kubectl-cmds.md
modified:   content/zh-cn/docs/reference/kubectl/kubectl.md
```

[zh] Sync kubectl.md and kubectl-cmds.md

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

Performing a `kubeadm upgrade apply` for a version change that includes a new `etcd` image will induce lots of stalled requests on the apiserver, while the `etcd` pod is restarting.
This commit adds a consideration for this fact, and also proposes a workaround to minimize the impact of the upgrade when `etcd` also had to be updated.
This commit is a follow-up to https://github.com/kubernetes/kubeadm/issues/2991#issuecomment-1932337556
/cc @neolit123

docs(kubeadm-upgrade): add consideration on etcd upgrade impact

---

content/zh-cn/docs/concepts/services-networking/network-policies.md
content/zh-cn/releases/patch-releases.md

content/zh-cn/releases/patch-releases.md

[zh-cn]sync patch-releases network-policies

---

content/ko/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy.md

en PR https://github.com/kubernetes/website/pull/45258/files

[ko] Fix broken link

---

content/en/docs/reference/command-line-tools-reference/feature-gates/stable-load-balancer-node-set.md

k/k:  https://github.com/kubernetes/kubernetes/pull/122961 (merged)
kep: https://github.com/kubernetes/enhancements/issues/3458

Promote feature gate StableLoadBalancerNodeSet to GA

---

content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Fixes: https://github.com/kubernetes/website/issues/44975
Synchronization is also performed.
See [the preview page](https://deploy-preview-45013--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro/)

[zh] Fix raw HTML data in the tutorials page

---

content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

[zh-cn] sync kubeadm-upgrade.md

---

content/en/docs/concepts/storage/ephemeral-volumes.md

`s/Some application need/Some applications need`

Fix typo in ephemeral-volumes.md

---

content/de/docs/tutorials/kubernetes-basics/_index.html

Change from English to the German documentations

[de]: fix html reference to the German documentations

---

content/id/docs/concepts/_index.md
content/id/docs/home/_index.md

This PR fix broken link in https://kubernetes.io/id/docs/concepts/

[id] fix link button 

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_annotate/_index.md

```
```
See [preview](https://deploy-preview-45237--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubectl/generated/kubectl_annotate/)

[zh] Localize /kubectl/generated/kubectl_annotate

---

content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md

A few changes throughout the file to improve wording.

Fix wording in configure-upgrade-etcd.md

---

content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md

[zh-cn]fix format issue

---

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

en PR https://github.com/kubernetes/website/pull/45296/files

[zh] Update link

---

content/ja/releases/notes.md

close #44996 
- Translate `content/en/releases/notes.md` into Japanese

[ja] Translate `content/en/releases/notes.md` into Japanese

---

content/zh-cn/docs/setup/best-practices/multiple-zones.md

- Fix minor errors about newline char
- Add anchors
```
content/zh-cn/docs/setup/best-practices/multiple-zones.md
```

[zh] Sync multiple-zones.md

---

content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md

Sync with en #45307 
```
```
See [preview](https://deploy-preview-45376--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd/)

[zh] Sync configure-upgrade-etcd.md

---

content/ru/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Fixed incorrect display of content due to an unclosed tag

update scale-intro.html (close <code> tag)

---

content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md

/kind feature
/language es
/sig docs
/assign @ramrodo @electrocucaracha
solves https://github.com/kubernetes/website/issues/45315

[es] localize content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md to Spanish

---

content/en/docs/tasks/access-application-cluster/service-access-application-cluster.md

Formatted for the documentation standards

Service term is formatted

---

content/en/blog/_posts/2024-03-01-sig-cloud-provider-spotlight.md

SIG Cloud Provider article.
* Original PR in `contributor-site`: https://github.com/kubernetes/contributor-site/pull/477
_Please review the original PR instead of this one_; I will copy the final version of the `contributor-site` here. I will keep this as draft until the original PR is reviewed, and content synced.

Add SIG Cloud Provider spotlight article.

---

content/en/docs/concepts/overview/kubernetes-api.md

Add more documentation around discovery and OpenAPI, updates from aggregated discovery and OpenAPI V3, as well as why the newer versions should be preferred.
/assign @apelisse

Add additional documentation around discovery and OpenAPI

---

content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Fix HTML typo

---

content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md

```
```
See [preview](https://deploy-preview-44340--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node/) please.

[zh] Add translation to assign-pod-node.md

---

content/zh-cn/docs/reference/using-api/cel.md

Sync with en #42695 and #44972
```
content/zh-cn/docs/reference/using-api/cel.md
```
See [preview](https://deploy-preview-44892--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/using-api/cel/)

[zh] Sync using-api/cel.md

---

content/zh-cn/docs/tasks/manage-gpus/scheduling-gpus.md

Sync with en #44915 
```
content/zh-cn/docs/tasks/manage-gpus/scheduling-gpus.md
```

[zh] Add translations to scheduling-gpus.md

---

content/zh-cn/docs/reference/config-api/kubelet-config.v1beta1.md

```
content/zh-cn/docs/reference/config-api/kubelet-config.v1beta1.md
```

[zh] Sync config-api/kubelet-config.v1beta1.md

---

content/zh-cn/docs/concepts/windows/intro.md

Mainly sync with #42518 
```
content/zh-cn/docs/concepts/windows/intro.md
```
See [preview](https://deploy-preview-45149--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/windows/intro/) please.

[zh] Sync /windows/intro.md

---

content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

[zh-cn] sync configure-liveness-readiness-startup-probes.md

---

content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md

content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md

[zh-cn] sync hugo-shortcodes/index.md

---

content/zh-cn/blog/_posts/2023-12-20-contextual-logging-in-kubernetes-1-29.md

en page: https://kubernetes.io/blog/2023/12/20/contextual-logging-in-kubernetes-1-29
See [the preview page](https://deploy-preview-44946--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/12/20/contextual-logging-in-kubernetes-1-29/).

Translate the contextual-logging-in-kubernetes-1-29 blog into Chinese

---

content/zh-cn/docs/concepts/architecture/mixed-version-proxy.md
content/zh-cn/docs/concepts/workloads/pods/pod-qos.md

```
M       content/zh-cn/docs/concepts/architecture/mixed-version-proxy.md
M       content/zh-cn/docs/concepts/workloads/pods/pod-qos.md
```

[zh-cn]sync mixed-version-proxy pod-qos

---

content/pt-br/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/45337/files

[pt] Correcting API field paths

---

content/zh-cn/docs/concepts/workloads/pods/sidecar-containers.md

[zh-cn] sync sidecar-containers

---

content/zh-cn/docs/concepts/workloads/autoscaling.md
content/zh-cn/docs/reference/glossary/replica.md

Localize content/zh-cn/docs/concepts/workloads/autoscaling.md

[zh-cn] Localize autoscaling.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/hpa-container-metrics.md
content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

graduate HPAContainerMetrics to stable.
Part of https://github.com/kubernetes/enhancements/issues/1610

graduate HPAContainerMetrics to stable

---

content/es/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/45337/files

[es] Correcting API field paths

---

content/en/docs/concepts/workloads/autoscaling.md

A few changes about grammar for improvement.

Pick a few grammars in autoscaling.md

---

content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
content/en/docs/reference/command-line-tools-reference/feature-gates/min-domains-in-pod-topology-spread.md

Necessary changes to graduate MinDomain feature to stable.
Part of https://github.com/kubernetes/enhancements/issues/3022.

graduate MinDomain feature to stable

---

content/zh-cn/docs/concepts/workloads/autoscaling.md

content/zh-cn/docs/concepts/workloads/autoscaling.md

[zh-cn]sync workloads/autoscaling.md

---

content/en/docs/concepts/cluster-administration/addons.md

@rajch is the maintainer in charge of Weave Net now, he is doing the work 👏 
Ref: https://github.com/kubernetes/website/pull/45202#issuecomment-1976819974
This PR supersedes and closes #45202 
Supersedes #45258, revisiting #45257 
I am a Kubernetes contributor in other ways for some time but I think this is my first commit in the kubernetes org. 🎉

Update Weave Net link to newly supported fork

---

content/id/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/45337/files

[id] Correcting API field paths

---

content/zh-cn/docs/contribute/style/style-guide.md

Sync with en #44126
```
```
See [preview](https://deploy-preview-45435--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/style/style-guide/)

[zh] Sync style/style-guide.md

---

content/en/docs/reference/kubernetes-api/common-parameters/common-parameters.md

[en] Update go lang link common-parameters.md

---

OWNERS_ALIASES

Add jossemarGT to sig-docs-es-reviews

---

content/fr/docs/concepts/storage/volumes.md

en PR https://github.com/kubernetes/website/pull/45337/files

[fr] Correcting API field paths

---

OWNERS_ALIASES

joining the sig-docs-bn reviewer and approver team.
/cc @a-mccarthy

[bn] Update OWNERS_ALIASES

---

content/bn/releases/_index.md

Localize _index.md in Bengali language.
fixes issue:#44993

[bn] Localize(updated) content/bn/releases/_index.md

---

content/bn/releases/download.md
content/bn/search.md

Localize Releases/download.md 

[bn] Localize Releases/download.md 

---

content/en/blog/_posts/2024-03-12-mid-cycle-1.30.md

Kubernetes 1.30 Mid-cycle blog fixes and minor edits
added after merge of main PR #45411

Add 1.30 mid-cycle blog article fixes

---

content/zh-cn/docs/contribute/participate/pr-wranglers.md

content/zh-cn/docs/contribute/participate/pr-wranglers.md

[zh]sync pr-wranglers.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-clean-up.md
content/en/docs/reference/labels-annotations-taints/_index.md

Issue: https://github.com/kubernetes/enhancements/issues/2799

Revise the feature gate LegacyServiceAccountTokenCleanUp to stable stage

---

content/en/docs/reference/access-authn-authz/validating-admission-policy.md
content/en/docs/reference/command-line-tools-reference/feature-gates/validating-admission-policy.md

Promoting ValidatingAdmissionPolicy to GA.
The code has been merged in 1.30. This is the doc updates.

[KEP-3488]Promoting ValidatingAdmissionPolicy to GA

---

content/ko/docs/concepts/workloads/pods/pod-qos.md

Translate Concepts/Workloads/Pods/Pod Quality of Service Classes(pod-qos) into Korean
from #44052

[ko] Translate Concepts/Workloads/Pods/Pod Quality of Service Classes into Korean

---

OWNERS_ALIASES

based on the discussion here https://github.com/kubernetes/website/pull/44862#issuecomment-1995155214

[ar] Add mboukhalfa as owner for arabic content

---

content/zh-cn/blog/_posts/2024-03-12-mid-cycle-1.30.md

Chinese version for https://kubernetes.io/blog/2024/03/12/kubernetes-1-30-upcoming-changes/

zh-blog: v1.30 mid cycle preview of key enhancements

---

content/zh-cn/docs/reference/using-api/server-side-apply.md

close: https://github.com/kubernetes/website/issues/43332

[zh-cn]resync server-side-apply.md

---

content/zh-cn/docs/concepts/overview/_index.md

Correcting the correct abbreviation `K8s`, and sync with english ver docs

[zh-cn] synchronized with the original english ver post

---

content/en/docs/reference/node/_index.md

Add  missing some items in Index for node reference.
Fixes https://github.com/kubernetes/website/issues/45578

Add missing some items

---

assets/scss/_custom.scss
layouts/partials/navbar.html

fixes #44561
Check this [comment](https://github.com/kubernetes/website/issues/44561#issuecomment-1871322494)

Show a way to search even when page scrolled

---

content/pt-br/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md

Adds docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md

[pt-br] Adds docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md

---

content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md

close: https://github.com/kubernetes/website/issues/43361

[zh-cn]localize content/en/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md

---

content/zh-cn/docs/tutorials/security/apparmor.md

[zh-cn]sync security/apparmor

---

content/zh-cn/docs/tasks/inject-data-application/define-command-argument-container.md

Remove useless tips

---

assets/scss/_custom.scss

Made cahnge to make Search text appear.
Fixes https://github.com/kubernetes/website/issues/45587
Also, this will fix https://github.com/kubernetes/website/issues/45586

Fix navbar Search text visibility and background color on scroll

---

content/en/docs/reference/access-authn-authz/authorization.md
content/en/docs/reference/command-line-tools-reference/feature-gates/structured-authorization-configuration.md

- Add beta feature gate metadata for `StructuredAuthorizationConfiguration`
KEP issue: https://github.com/kubernetes/enhancements/issues/3221

Add feature gate metadata for structured authz config

---

content/zh-cn/docs/tutorials/security/apparmor.md

Update according to style guide.
https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#special-words

[zh] update security\apparmor.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/name-generation-retries.md

Enhancement Issue: https://github.com/kubernetes/enhancements/issues/4420
Enhancement PR: https://github.com/kubernetes/kubernetes/pull/122887

Document NameGenerationRetries feature gate

---

content/ru/docs/tutorials/kubernetes-basics/update/update-intro.html

en PR https://github.com/kubernetes/website/pull/44885/files

[ru] Edit docker-specific image name

---

content/en/docs/concepts/windows/intro.md

Adding  Windows operational Readiness instructions for troubleshooting and Windows cluster validation
refs #45130

Enhancing troubleshoot section with Windows Operational Readiness

---

content/zh-cn/docs/setup/production-environment/container-runtimes.md

at windows tab, it show linux config-path.

[zh-cn]  update containerd tab

---

content/zh-cn/docs/concepts/windows/intro.md

The file `content/en/docs/concepts/windows/intro.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45612) ,so we will synchronize the localization.

[zh] sync concepts\windows\intro.md

---

content/zh-cn/docs/reference/node/_index.md

The file `content/en/docs/reference/node/_index.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45581) ,so we will synchronize the localization.

[zh] sync reference\node\_index.md

---

content/en/docs/reference/access-authn-authz/authentication.md
content/en/docs/reference/command-line-tools-reference/feature-gates/structured-authentication-configuration.md

Doc update for KEP 3331 beta: https://git.k8s.io/enhancements/keps/sig-auth/3331-structured-authentication-configuration

Add docs for Structured Authn beta

---

content/zh-cn/docs/concepts/cluster-administration/addons.md

[zh] Update Weave Net link to newly supported fork

---

content/en/docs/reference/access-authn-authz/authentication.md

Follow-up PR to resolve https://github.com/kubernetes/website/pull/45108#discussion_r1536780866.
/assign @natalisucks

Fix docs for authentication: s/errors/error

---

content/ru/docs/concepts/cluster-administration/addons.md

[ru] Update Weave Net link to newly supported fork

---

content/zh-cn/docs/contribute/analytics.md

The file `content/zh-cn/docs/contribute/analytics.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45247) ,so we will synchronize the localization.

[zh] sync contribute\analytics.md

---

content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md

Added Imagefs inodes default settings in Eviction Hard

---

content/es/docs/concepts/cluster-administration/addons.md

[es] Update Weave Net link to newly supported fork

---

content/en/docs/concepts/configuration/configmap.md
content/en/docs/concepts/configuration/secret.md

[dev-1.30] Remove useless line wrap

---

content/en/docs/concepts/workloads/pods/sidecar-containers.md

Fix a spelling mistake: effecting -> affecting

Fix spelling error in sidecar-containers.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/crd-validation-ratcheting.md
content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

~placeholder for~ https://github.com/kubernetes/enhancements/issues/4008

KEP-4008: CRDValidationRacheting - Beta Docs

---

content/en/docs/reference/access-authn-authz/service-accounts-admin.md
content/en/docs/reference/command-line-tools-reference/feature-gates/service-account-token-jti.md
content/en/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding-validation.md
content/en/docs/reference/command-line-tools-reference/feature-gates/service-account-token-pod-node-info.md

Enhancement: https://github.com/kubernetes/enhancements/issues/4193

Make KEP-4193 documentation updates

---

content/zh-cn/docs/setup/production-environment/_index.md

```
content/zh-cn/docs/setup/production-environment/_index.md
```

[zh] Sync setup/production-environment/_index.md

---

content/en/docs/reference/node/kubelet-config-directory-merging.md
content/en/docs/tasks/administer-cluster/kubelet-config-file.md

taking over https://github.com/kubernetes/website/pull/45479/ as @sohankunkerkar is on vacation

[dev-1.30] docs: Update KubeletConfigDropinDir doc information

---

content/ja/docs/reference/glossary/cluster-architect.md

add: content/ja/docs/reference/glossary/cluster-architect.md
close #45115

[ja] Translate reference/glossary/cluster-architect.md

---

content/en/docs/tasks/configure-pod-container/security-context.md

Fix a hyperlink - see https://github.com/kubernetes/website/pull/45152/files#r1540937594

Fix broken hyperlink

---

content/ja/docs/concepts/cluster-administration/addons.md

[ja] Update Weave Net link to newly supported fork

---

content/ja/docs/reference/glossary/containerd.md

close https://github.com/kubernetes/website/issues/45476 
- add `content/ja/docs/reference/glossary/containerd.md`
/language ja

[ja] Translate content/en/docs/reference/glossary/containerd.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/storage-version-migration.md
content/en/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

Ref: https://github.com/kubernetes/enhancements/issues/4192
PR - https://github.com/kubernetes/kubernetes/pull/123344

docs:add docs for StorageVersionMigration v1alpha1

---

content/ru/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

Applying the tiny fix from #45627 to the Russian localisation.

[ru] Show the correct proxy URL in the deploy-intro

---

content/bn/includes/partner-style.css

Optional document translation
fixes issue : https://github.com/kubernetes/website/issues/44993

[bn] localize content/bn/includes/partner-style.css for Bengali localization

---

content/bn/examples/application/deployment.yaml
content/bn/examples/pods/simple-pod.yaml

Fixing building errors for bangla version

[bn] Fixing building errors

---

content/ja/docs/tasks/debug/debug-cluster/kubectl-node-debug.md

close #44987 
- Translate `content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md` into Japanese

[ja] Translate `content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md` into Japanese

---

content/ja/docs/concepts/workloads/pods/disruptions.md

Fixes #45161
Preview: https://deploy-preview-45162--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/workloads/pods/disruptions/

[ja] Translate content/ja/docs/concepts/workloads/pods/disruptions.md into Japanese

---

content/en/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

Ref: https://github.com/kubernetes/enhancements/issues/4192
PR - https://github.com/kubernetes/kubernetes/pull/123344
Follows up on: https://github.com/kubernetes/website/pull/45714
This accounts for some review suggestions made by @tengqm 
x-post on exception thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1711552644986199
request for new pr: https://kubernetes.slack.com/archives/CA1MMM1HU/p1711594782564529
/cc @nilekhc @deads2k @jpbetz @enj
/milestone 1.30
/sig docs

docs: incorporating more PR feedback on storage version migration

---

content/en/docs/concepts/security/service-accounts.md

Link to API reference for ServiceAccount as requested in #45747
Closes #45747

Signpost to API reference for ServiceAccount

---

content/de/docs/tasks/tools/included/verify-kubectl.md

en PR https://github.com/kubernetes/website/pull/45636/files

[de] Added a link to the minikube installation

---

content/en/docs/concepts/services-networking/service.md
content/en/docs/reference/labels-annotations-taints/_index.md

Explanation about headless service

Explanation about headless service

---

content/zh-cn/docs/concepts/cluster-administration/_index.md

- **EN upstream**: `content/en/docs/concepts/cluster-administration/_index.md`
- **Sync to**: `content/zh-cn/docs/concepts/cluster-administration/_index.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/cluster-administration/_index.md
diff --git a/content/en/docs/concepts/cluster-administration/_index.md b/content/en/docs/concepts/cluster-administration/_index.md
index 2c7baf1d98..456069c980 100644
--- a/content/en/docs/concepts/cluster-administration/_index.md
+++ b/content/en/docs/concepts/cluster-administration/_index.md
@@ -52,6 +52,7 @@ Before choosing a guide, here are some considerations:
* Learn how to [manage nodes](/docs/concepts/architecture/nodes/).
+  * Read about [cluster …
```

[zh] sync content/en/docs/concepts/cluster-administration/_index.md

---

content/zh-cn/docs/tasks/tools/included/verify-kubectl.md

en pr https://github.com/kubernetes/website/pull/45636/files

[zh] Added a link to the minikube installation

---

content/en/blog/_posts/2024-04-03-windows-ops-readiness.md

The PR serves to amend an unintentional oversight in our acknowledgements and adds Marcio Morales (AWS) as he was a notable contributor to the specification.

Update Windows Operational Readiness blog

---

content/pt-br/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

en PR https://github.com/kubernetes/website/pull/45627/files

[pt] Show the correct proxy URL

---

content/es/docs/concepts/services-networking/endpoint-slices.md

/kind feature
/language es
/sig docs
/assign @ramrodo @electrocucaracha
resolves https://github.com/kubernetes/website/issues/45441

[es] Added concepts/services-networking/endpoint-slices.md to Spanish

---

content/zh-cn/docs/concepts/services-networking/network-policies.md

en PR https://github.com/kubernetes/website/pull/45746/files

[zh] Signpost to API reference for NetworkPolicy

---

content/zh-cn/docs/tasks/run-application/configure-pdb.md

Fix feature gate status

---

content/zh-cn/docs/tasks/tools/install-kubectl-linux.md

The file `content/zh-cn/docs/tasks/tools/install-kubectl-linux.md` has been updated in this PR (https://github.com/kubernetes/website/pull/44680) ,so we will synchronize the localization.

[zh]Update kubectl installation instructions for Linux

---

content/zh-cn/docs/reference/glossary/init-container.md

The file `content/zh-cn/docs/reference/glossary/init-container.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45801) ,so we will synchronize the localization.

[zh] Update full_link in init-container.md

---

content/en/docs/concepts/overview/kubernetes-api.md

Pointed at https://github.com/kubernetes/website/pull/45790#discussion_r1555111709
/cc @dipesh-rawat @Jefftree

Correct branch format in Discovery API docs

---

content/zh-cn/docs/concepts/overview/working-with-objects/namespaces.md

en PR https://github.com/kubernetes/website/pull/45763/files

[zh] Fix small typo in Namespaces documentation

---

data/releases/schedule.yaml

This PR adds 1.30 to the releases schedule for the 1.30.0 release.
/milestone 1.30
/cc @jimangel @marosset @katcosgrove

Add 1.30 to release schedule for 1.30 release

---

content/en/docs/tasks/tools/included/verify-kubectl.md

As requested in issue have marked the line as code.
Fixes https://github.com/kubernetes/website/issues/45851

Utilize code style for inline command in "included/verify-kubectl.md"

---

content/en/blog/_posts/2024-04-11-SIG-Architecture-Code-Organization-Spotlight.md

Fix typo in Madhav's name in the code-organization blog post

---

content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md

content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md

[zh-cn] sync migrate-dockershim-dockerd horizontal-pod-autoscale

---

content/zh-cn/docs/concepts/overview/kubernetes-api.md

en PR https://github.com/kubernetes/website/pull/45765/files

[zh] Fix discovery document link

---

content/en/examples/access/deployment-replicas-policy.yaml
content/en/examples/access/image-matches-namespace-environment.policy.yaml
content/en/examples/access/validating-admission-policy-audit-annotation.yaml
content/en/examples/access/validating-admission-policy-match-conditions.yaml
content/en/examples/validatingadmissionpolicy/basic-example-binding.yaml
content/en/examples/validatingadmissionpolicy/basic-example-policy.yaml
content/en/examples/validatingadmissionpolicy/binding-with-param-prod.yaml
content/en/examples/validatingadmissionpolicy/binding-with-param.yaml
content/en/examples/validatingadmissionpolicy/failure-policy-ignore.yaml
content/en/examples/validatingadmissionpolicy/policy-with-param.yaml
content/en/examples/validatingadmissionpolicy/typechecking-multiple-match.yaml
content/en/examples/validatingadmissionpolicy/typechecking.yaml

since v1.30 ValidatingAdmissionPolicy graduate to GA https://github.com/kubernetes/kubernetes/pull/123405

Update ValidatingAdmissionPolicy examples to v1

---

hugo.toml

Updates hugo.toml for dev-1.30 ahead of v1.30 release date.

Updates v1.30 hugo.toml to include latest patches ahead of release

---

content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/zh-cn/examples/pods/probe/http-liveness.yaml

zh-cn equivalent for https://github.com/kubernetes/website/pull/45837

[zh] Switch liveness image to multi-arch agnhost container image

---

content/ru/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/ru/examples/pods/probe/http-liveness.yaml

ru equivalent for https://github.com/kubernetes/website/pull/45837

[ru] Switch liveness image to multi-arch agnhost container image

---

content/fr/docs/concepts/workloads/pods/pod-lifecycle.md
content/fr/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/fr/examples/pods/probe/http-liveness.yaml

fr equivalent for https://github.com/kubernetes/website/pull/45837

[fr] Switch liveness image to multi-arch agnhost container image

---

README-vi.md

This PR contains changes in `README-vi.md`, which includes
- Fix broken links
- Fix translation errors

[vi] Update README-vi.md
