- content/ja/docs/tasks/debug/debug-application/determine-reason-pod-failure.md
Syncs ja docs page with a newer en page.
Links:
- [Japanese docs](https://kubernetes.io/ja/docs/tasks/debug/debug-application/determine-reason-pod-failure/#%E6%AC%A1%E3%81%AE%E9%A0%85%E7%9B%AE)
- [English docs](https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/#what-s-next)
> [ja] sync k8s.io/ja/docs/tasks/debug/debug-application/determine-reason-pod-failure/#次の項目 with en docs

- content/ja/docs/contribute/_index.md
`tag: release-1.26` has [content/ja/docs/contribute/new-content/overview.md](https://github.com/kubernetes/website/blob/release-1.26/content/ja/docs/contribute/new-content/overview.md),
But `tag: main` has no [content/ja/docs/contribute/new-content/overview.md](https://github.com/kubernetes/website/blob/main/content/ja/docs/contribute/new-content/overview.md)
Close:https://github.com/kubernetes/website/issues/44645
> Fix broken link of content/ja/docs/contribute/_index.md

- content/ko/docs/concepts/services-networking/dns-pod-service.md
busy-subdomain -> busybox-subdomain
en-page: https://kubernetes.io/ko/docs/concepts/services-networking/dns-pod-service/#%ED%8C%8C%EB%93%9C%EC%9D%98-hostname-%EB%B0%8F-subdomain-%ED%95%84%EB%93%9C
ko-page: https://kubernetes.io/ko/docs/concepts/services-networking/dns-pod-service/#%ED%8C%8C%EB%93%9C%EC%9D%98-hostname-%EB%B0%8F-subdomain-%ED%95%84%EB%93%9C
en-page: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
```
The dnsConfig field is optional and it can work with any dnsPolicy settings. 
However, when a Pod's dnsPolicy is set to "None", the dnsConfig field has to be specified.
```
ko-page: https://kubernetes.io/ko/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
```dnsConfig``` 필드는 선택적이~~고~~, ```dnsPolicy``` ~~세팅과~~ ~~함께~~ …
> [ko] Fix typo in 'DNS for Services and Pods' page

- content/en/docs/concepts/workloads/pods/init-containers.md
- content/en/docs/concepts/workloads/pods/sidecar-containers.md
- content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Update the documentation around sidecar containers.
This wording fits having at least one minor release after v1.29, so I've targeted the branch _dev-1.30_.
/sig node
> Update docs around sidecar containers

- content/en/docs/tasks/manage-gpus/scheduling-gpus.md
This is a small fixup for https://github.com/kubernetes/website/pull/44915
It helps people correctly see what lines have been added.
[Existing page section](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#node-labeller)
[Preview](https://deploy-preview-44954--kubernetes-io-main-staging.netlify.app/docs/tasks/manage-gpus/scheduling-gpus/#node-labeller)
> Fix highlighting for added lines

- content/en/docs/concepts/security/rbac-good-practices.md
Happy Tuesday, Kubernetes team!
Was reading through the RBAC best practices doc and noticed a small typo. I also went through and cleaned up anything else I could find in the document.
> Resolve typos on page "Role Based Access Control Good Practices"

- content/en/docs/reference/command-line-tools-reference/feature-gates/default-host-network-ports-in-pod-templates.md
Reword the explanation for the `DefaultHostNetworkHostPortsInPodTemplates` feature gate.
[preview](https://deploy-preview-44626--kubernetes-io-main-staging.netlify.app//docs/reference/command-line-tools-reference/feature-gates/)
/sig network
/language en
> Revise explanation for DefaultHostNetworkHostPortsInPodTemplates

- content/en/docs/reference/kubectl/quick-reference.md
Replaces git.io URLs with `example.com` domain, as discussed in issue #33231.
Closes #33231
> Replaces git.io URLs in kubectl cheatsheet

- content/en/docs/reference/command-line-tools-reference/feature-gates/cloud-dual-stack-node-ips.md
per https://github.com/kubernetes/enhancements/pull/4415 and https://github.com/kubernetes/kubernetes/pull/123134
I think this is right? First feature gate change since the new feature gate documentation system...
There were no outstanding references to the feature gate in the rest of the documentation. (They were written out when we went to beta.)
> KEP-3705 CloudDualStackNodeIPs to GA

- content/pt-br/docs/tasks/access-application-cluster/access-cluster.md
This PR is for the Brazilian-Portuguese localization of the file /docs/tasks/access-application-cluster/access-cluster.md
> [pt-br] Add /docs/tasks/access-application-cluster/access-cluster.md

- content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
This PR updates the link to the example yaml in the task page. Currently, the link is incorrect as it has missing 'rabbitmq' dir in the path. 
Fixes https://github.com/kubernetes/website/issues/45020
> Fix path for example yaml in 'Coarse Parallel Processing Using a Work Queue' task page

- content/en/docs/concepts/workloads/pods/_index.md
- content/en/docs/concepts/workloads/pods/disruptions.md
- content/en/docs/concepts/workloads/pods/ephemeral-containers.md
- content/en/docs/reference/glossary/init-container.md
- content/en/docs/reference/glossary/sidecar-container.md
My main motivation for this was to make the init vs. sidecar distinction easier to understand, but also less prominent. People learning about Pods for the first time might want to understand one-container Pods before learning about the more complicated alternative way to do it.
- Add glossary entry for sidecar container
- Revise glossary entry for init container to match
- Revise the Pod concept overview
- Reorder pages in that section
---
_Main [preview](https://deploy-preview-44798--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/pods/)_
> Improve docs for Pods

- content/en/docs/tasks/extend-kubernetes/socks5-proxy-access-api.md
This PR fixes the mermaid syntax to properly render the diagram below:
In [Use a SOCKS5 Proxy to Access the Kubernetes API](https://kubernetes.io/docs/tasks/extend-kubernetes/socks5-proxy-access-api/#task-context) page
- `Figure 1. SOCKS5 tutorial components` diagram is broken due to mermaid syntax error as of version 10.6.1.
```
> cat diagrams/socks5.mm
graph LR;
subgraph local[Local client machine]
client([client])-- local <br> traffic .->  local_ssh[Local SSH <br> SOCKS5 proxy];
end
local_ssh[SSH <br>SOCKS5 <br> proxy]-- SSH Tunnel -->sshd
subgraph remote[Remote server]
sshd[SSH <br> server]-- local traffic -->service1;
end
client([client])-. proxied HTTPs traffic <br> going through the proxy .->service1[Kubernetes API];
classDef plain fill:#ddd,stroke:#fff,stroke-width:4px,color:#000; …
```
> socks5-proxy-access-api.md: fix broken mermaid diagram

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
The `spec.template` of `Deployment` YAML is a `PodTemplateSpec`, so it should be `spec.template.spec.affinity` instead of `spec.template.affinity`.
```
$ k explain deploy.spec.template.affinity
GROUP:      apps
KIND:       Deployment
VERSION:    v1
error: field "affinity" does not exist
```
```
$ explain deploy.spec.template.spec.affinity
GROUP:      apps
KIND:       Deployment
VERSION:    v1
FIELD: affinity <Affinity>
...
```
> Fix `matchLabelKeys` example yaml 

- content/en/docs/concepts/architecture/garbage-collection.md
- content/en/docs/concepts/architecture/leases.md
- content/en/docs/concepts/architecture/mixed-version-proxy.md
- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/concepts/cluster-administration/system-logs.md
- content/en/docs/concepts/cluster-administration/system-traces.md
- content/en/docs/concepts/containers/images.md
- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/en/docs/concepts/services-networking/service.md
- content/en/docs/contribute/style/hugo-shortcodes/index.md
- data/i18n/en/en.toml
- layouts/shortcodes/feature-state.html
This PR builds on top of PR https://github.com/kubernetes/website/pull/44478 to enhance the `feature-state` shortcode functionality to dynamically display the version and state of the documented feature by extracting details from the feature gate description files.
With the introduction of feature gate description files containing metadata (such as stages, default values, versions), leveraging this information to render the feature state becomes feasible. Consequently, as a feature gate progresses through stages, the corresponding changes will automatically reflect on pages utilizing the `feature-state` shortcode.
- Introduced a new parameter `feature_gate_name` in the shortcode to specify the feature gate name.
- Implemented logic to retrieve feature gate state exclusively from …
> Enhance 'feature-state' shortcode to utilize feature gate description files

- content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
follow-up for #44752
A few layout improvements for the page:
- The two-column layout is symmetric now
- The newly added note is on a separate row which adds proper separation
[Original page](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/)
[Deploy Preview](https://deploy-preview-44767--kubernetes-io-main-staging.netlify.app/docs/tutorials/kubernetes-basics/scale/scale-intro/)
> Styling improvements for scale-intro.md

- content/en/docs/concepts/overview/components.md
This Pull Request aims to correct a typo in the documentation by updating instances of "set up scripts" to the correct "setup scripts." According to the Microsoft Style Guide for documentation (https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/s/set-up-setup), "setup" should be one word when it is used as an adjective or noun.
> Fix grammatical error regarding setup scripts in Kubernetes Components documentation

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
No actual content change, just a missing space after a `,`.
No other issues have been found with `git grep -E ',[0-9]+s'`.
> Add missing space in Pod Lifecycle concept page

- content/en/docs/tasks/administer-cluster/encrypt-data.md
This is split out from PR https://github.com/kubernetes/website/pull/33285 in order to make a review more likely. See that PR and its previews to show the changes in a wider context.
/language en
> Reword advice about encryption-at-rest opt outs

- content/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
issue: #44495.
Due to operational errors in the previous PR, it ended up in an awkward state. So I re-created the PR.
The original PR is PR: #44496.
As suggested in the previous PR, I have made updates beyond fixing the problem, specifically revising the entire section related to Debian-based distributions.
> [ja]Update kubeadm installation instructions in Japanese documentation

- content/en/docs/concepts/storage/dynamic-provisioning.md
Issue https://github.com/kubernetes/website/issues/44932
> Information about default StorageClasses

- content/en/docs/concepts/windows/intro.md
What will change
- Added a new section specifying minimum recommended hardware requirements for Windows worker nodes
Why this change is necessary?
- Part of https://github.com/kubernetes/website/issues/31428 issue to add improvements to the windows documentation
- Listing system requirements for Windows will help guide users properly setup their Windows worker nodes, as there are a few caveats and differences compared to Linux.
Documentation
- The relevant page with the new changes is the section `Worker Node Hardware Recommendations`. Navigate using [...staging.netlify.app/docs/concepts/windows/intro/#windows-node-hardware-recommendations](https://deploy-preview-42518--kubernetes-io-main-staging.netlify.app/docs/concepts/windows/intro/#windows-node-hardware-recommendations) to more …
> Specify recommended Windows hardware requirements

- content/en/docs/reference/access-authn-authz/admission-controllers.md
Final step of the SecurityContextDeny admission plugin removal https://github.com/kubernetes/kubernetes/issues/111516.
This removes the admission controller plugin documentation. Other mentions of this are (I guess) generated from the source code. Since the plugin was removed on main k/k, those will disappear once the scripts are run for the 1.30 release.
It seems that you don't need to document the removal apart from removing the documentation linked to a feature. If I need to add some more documentation on the actual removal, and on which version it happened, I can do it if someone points me to the page.
> Remove `SecurityContextDeny` admission documentation

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
The pages for [Upgrading kubeadm clusters](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) and [Upgrading Linux nodes](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes/) have reference to `apt`, `apt-cache`, `apt-mark`, `apt-get`, `yum` and `kubeadm upgrade apply` commands. These commands need elevated permissions through `sudo` (if executed without root).
The PR adds the usage of `sudo` for these commands to ease the experience for the reader.
Regards,
Aditya
> Use sudo for elevated permissions while upgrading clusters using kubeadm

- layouts/docs/glossary.html
This pull request implements miscellaneous changes to the layout of glossary pages by adding missing whitespace after the colon in the list of "also known as" values.
> Update glossary.html by adding missing whitespace after colon for AKA list

- content/en/docs/concepts/workloads/autoscaling.md
This PR introduces a new Concept page Autoscaling, providing an overview of the different options available. It fixes #44084.
I plan to add to the skeleton currently pushed to the PR over the next days.
Some questions for now:
- Is the overall style acceptable? I read the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/), but finding a balance of formatting too much/too little is hard
- Is a single file `concepts/workloads/autoscaling.md` fine or should it rather go into a new directory, e.g. `concepts/workloads/autoscaling/_index.md`?
- How detailed should the overview be? For example, the [Horizontal Pod Autoscaling Task](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) is incredibly detailed - should I link there **OR** copy bits and …
> Adds a new concept page for autoscaling

- content/zh-cn/docs/concepts/containers/images.md
- **EN upstream**: `content/en/docs/concepts/containers/images.md`
- **Sync to**: `content/zh-cn/docs/concepts/containers/images.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/containers/images.md
diff --git a/content/en/docs/concepts/containers/images.md b/content/en/docs/concepts/containers/images.md
index b4b837ae32..9b36a6b728 100644
--- a/content/en/docs/concepts/containers/images.md
+++ b/content/en/docs/concepts/containers/images.md
@@ -159,6 +159,17 @@ that Kubernetes will keep trying to pull the image, with an increasing back-off
Kubernetes raises the delay between each attempt until it reaches a compiled-in limit,
which is 300 seconds (5 minutes).
+### Image pull per runtime class
+
+{{< feature-state …
```
> [zh] sync `concepts/containers/image.md`

- layouts/shortcodes/feature-state.html
This PR addresses the rendering issue encountered when using the `feature-state` shortcode within the `tab` shortcode.
**Problem**:  The `tab` shortcode struggles to render nested `feature-state` shortcode content correctly, resulting in raw HTML output as reported in https://github.com/kubernetes/website/issues/45191#issue-2140757972. This occurs due to spacing and indentation, which disrupt the tab layout _(The behavior is identical when employing the 'note' shortcode with indentation; it disrupts the tab layout)_.
**Changes**: Removal of indentation within the  `feature-state` shortcode output so that `tab` shortcode can function properly.
**Outcome**: The `feature-state` shortcode now renders accurately  within the tab layout and other contexts.
[Fixed Preview Page _(check …
> Fix "feature-state" shortcode rendering within "tab" shortcode

- OWNERS_ALIASES
In conversation with SIG Docs leadership, we've cleaned up some of our membership to the reviewers and approvers group for English docs, and welcome @dipesh-rawat to our approvers group and PR Wrangling schedule
/assign @divya-mohan0209, @reylejano
> Clean up OWNERS_ALIASES English groups

- README.md
No need to build the container image locally; you can pull it instead. Simplify the advice accordingly.
> Revise advice about local API reference preview

- content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md
This is a minor update to the expected end date for the legacy package repos. It was original targeted for January 2024, but current progress looks like it will be any time in the next week, placing it by the end of February. This is a quick update just to make things more accurate for current and historical purposes.
> blog: Update expected end date for legacy package repos

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
Updating an url that is deprecated.
> Update link for "AMD GPU device plugin" in "Devices Plugins" page

- content/zh-cn/docs/reference/kubectl/kubectl.md
Sync with en #45235 
```
content/zh-cn/docs/reference/kubectl/kubectl.md
```
The bottom referenced docs may require additional time to localize due to their size, so only the first one (kubectl_annotate) has been added with the `/zh-cn` prefix.
See [preview](https://deploy-preview-45300--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubectl/kubectl/).
> [zh] Sync /kubectl/kubectl.md

- content/fr/docs/tutorials/kubernetes-basics/_index.html
- content/fr/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
- content/fr/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
- content/fr/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
- content/fr/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
- content/fr/docs/tutorials/kubernetes-basics/explore/explore-intro.html
[French tutorials](https://kubernetes.io/fr/docs/tutorials/kubernetes-basics/) still include old CSS files. However, if you visit these pages, the browser will try to access them and return 404 ([e.g.](https://kubernetes.io/docs/tutorials/kubernetes-basics/public/css/styles.css)). 
They were removed from the English tutorials in https://github.com/kubernetes/website/pull/34188. This PR removes them from the French localisation.
PS: Not directly related to this PR,  even though `https://katacoda.com/embed.js` was included on those pages next to the CSS files I did not remove them.
I also wanted to let you know that all `Katacoda-related` pieces should be removed from the localisation since these interactive tutorials are not supported anymore and need replacing. Here is an umbrella issue …
> [fr]: Removing old CSS includes from tutorials and fix html href

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/concepts/storage/volumes.md
**What this PR does / why we need it:**
Please see https://github.com/kubernetes/kubernetes/pull/122071#discussion_r1442946560
FYI
- [Turn CSIMigrationAWS on by default](https://github.com/kubernetes/kubernetes/pull/106098)
- [turn on CSIMigrationAzureDisk by default on 1.23](https://github.com/kubernetes/kubernetes/pull/104670)
- [feat: turn on CSIMigrationAzureFile by default on 1.24](https://github.com/kubernetes/kubernetes/pull/105070)
- [deprecate CephFS plugin from available in-tree drivers](https://github.com/kubernetes/kubernetes/pull/118143)
- [Mark openstack/cinder csi migrations are on by default](https://github.com/kubernetes/kubernetes/pull/98538)
- [turning on the CSIMigrationGCE feature flag](https://github.com/kubernetes/kubernetes/pull/104722)
- [enabling …
> fix incorrect volume doc

- content/en/docs/setup/best-practices/multiple-zones.md
I just updated the "storage access" section in this page:
https://kubernetes.io/docs/setup/best-practices/multiple-zones/
So that dosen't contain "PersistentVolumeLabel" because its deprecated and added little text explain that zone labels are managed by the cloud provider or storage provisioner now
> Modified storage access for zone and deleted PersistentVolumeLabel since its deprecated

- content/en/docs/concepts/storage/volumes.md
Correcting API field paths in Values doc page for accuracy and consistency with the convention across the entire page.
> Correcting API field paths in Volumes page

- README-vi.md
- data/i18n/vi/vi.toml
Synchronized README-vi.md & vi.toml
> [Synchronized] Update README-vi.md & vi.toml

- content/en/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md
The phrase "allocated to MongoDB on the internet" is confusing. One could read that the MongoDB pod in this example is being exposed to the internet, which is not the case.
I think the original author meant to say that `27017` is the official TCP port assigned to MongoDB by IANA, so I rephrased this sentence.
> Clarify in the documentation what we mean with "allocated to MongoDB on the internet"

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
- content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
- content/en/docs/setup/production-environment/container-runtimes.md
Telling users to set `bridge-nf-call-iptables` themselves was supposed to have been a temporary thing after kube-proxy's behavior changed between kubernetes 1.1 and 1.2. We can stop doing that now.
(kubeadm checks removed in https://github.com/kubernetes/kubernetes/pull/123464)
> Remove references to bridge-nf-call-iptables

- layouts/shortcodes/thirdparty-content.html
This PR fixes an issue with missing `whitespace` char in the Note box.
Before | After
-- | --
> Fix missing whitespace in thirdparty-content.html

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Fixes #44687
The examples documented for the liveness probe contain references to the `hostPort` field. The usage of this field is not recommended as per [Configuration Best Practices](https://kubernetes.io/docs/concepts/configuration/overview/#services).
This PR removes the references to `hostPort` so that readers do not use it unknowingly.
Feedback and suggestions are welcome.
Kind Regards,
Aditya.
> Remove hostPort field from the liveness probe examples to align with Kubernetes best practices.

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/load-balancer-ip-mode.md
- content/en/docs/reference/command-line-tools-reference/kubelet.md
As part of promotion of LoadBalancerIPMode to Beta, this is a placeholder PR to properly update the docs
> Promote LoadBalancerIPMode to Beta

- content/en/docs/reference/using-api/cel.md
The current CEL reference says this is impossible, but it's out of date. I've sent [a PR](https://github.com/google/cel-spec/pull/338) to update that. I don't know what the best way is to document this kind of validation or if we expect this example table to contain quite so many options, but if we think we want to capture this kind of pattern I've added it here.
> cel: provide example map validations

- content/en/docs/concepts/workloads/pods/downward-api.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/pod-host-ips.md
Just updating the text that was added for alpha, #42153. I think this is all that's needed.
/assign @wzshiming
> KEP-2681 PodHostIPs in downward API to stable

- content/zh-cn/docs/concepts/storage/projected-volumes.md
- content/zh-cn/docs/concepts/storage/storage-classes.md
- content/zh-cn/examples/pods/storage/projected-clustertrustbundle.yaml
Updated 2 files:
```
content/zh-cn/docs/concepts/storage/projected-volumes.md
content/zh-cn/docs/concepts/storage/storage-classes.md
```
See [preview](https://deploy-preview-44343--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/projected-volumes/) please.
> [zh] Add translations to projected-volumes.md and storage-classes.md

- content/es/docs/concepts/services-networking/ingress-controllers.md
/kind feature
/language es
/sig docs
/assign @ramrodo @electrocucaracha
resolves https://github.com/kubernetes/website/issues/44744
> [es] Added content/es/docs/concepts/services-networking/ingress-controllers.md

- content/zh-cn/docs/concepts/architecture/nodes.md
- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_reset-defaults.md
- content/zh-cn/docs/tutorials/services/source-ip.md
> [zh-cn]sync nodes assign-pod-node source-ip kubeadm_config_print_reset-defaults

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md
```
M       content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md
M       content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md
```
> [zh-cn]sync kubeadm_config_print_join-defaults kubeadm_init_phase_certs_etcd-healthcheck-client

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-ca.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_sa.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-ca.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_sa.md
> [zh-cn]sync kubeadm_init_phase_certs_etcd-ca kubeadm_init_phase_certs_sa

- content/en/examples/access/validating-admission-policy-audit-annotation.yaml
The "[Audit annotations](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#audit-annotations)" section of the ValidatingAdmissionPolicies docs has an example that doesn't actually show how to use `auditAnnotations`.
This change adds the missing `auditAnnotations` property and removes the invalid `key` property from the `validations`.
> Fix 'auditAnnotations' example

- content/en/docs/contribute/style/style-guide.md
Fix mixed messages in our [style guide](https://kubernetes.io/docs/contribute/style/style-guide/) about whether API kinds should use code style or not.
Parts of the style guide suggested writing with code style; other parts without it. I feel that the convention should be:
- fields always in code style. Eg: `.spec.widgetCount`
- API kinds never in code style (and always in UpperCamelCase). Eg: CustomResourceDefinition
- API paths in URLs, such as `/api/v1/namespaces/{namespace}/resourcequotas`: all lowercase, code style for URI fragments, plain text for whole URIs.
This PR makes the situation clear for API kinds.
It might be nice to have a pop up on every single docs page that you can consult to work out what means what; however, this PR does not add such a thing.
If we really wanted to, …
> Write API kinds without code style

- content/en/docs/tutorials/kubernetes-basics/update/update-intro.html
Hi K8s maintainers!
This documentation failed for me because I was running Minikube on Podman Desktop, and the image name `jocatalin/kubernetes-bootcamp` assumed that the registry was `docker.io`.
I think this slight modification would work for Docker and Podman alike. Let me know if you agree!
> Edit docker-specific image  name

- content/en/docs/concepts/cluster-administration/logging.md
close  https://github.com/kubernetes/website/issues/44550
Since the "Log rotation" feature is stable and [enabled by default from v1.21](https://github.com/kubernetes/kubernetes/blob/1b6b3ba013025c1914f6a992b7223e99c185599c/CHANGELOG/CHANGELOG-1.22.md?plain=1#L2642C1-L2642C281),
we can remove the words "You can configure" and "If you configure rotation".
Also, it would be good to mention defaults for kubelet configuration, refer to https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
> Update logging.md: Log rotation of kubelet

- content/es/docs/concepts/storage/persistent-volumes.md
Hi team!
Sending a new translation page about persistent-volumes
Closes #43792
> [es] Add concepts/storage/persistent-volumes.md

- content/en/blog/_posts/2024-03-07-cri-o-seccomp-oci-artifacts.md
This blog post wraps the efforts around a future CRI-O feature implemented in PR: https://github.com/cri-o/cri-o/pull/7719
cc @haircommander @mrunalp @harche @sairameshv 
Preview link: https://deploy-preview-45121--kubernetes-io-main-staging.netlify.app/blog/2024/02/29/cri-o-seccomp-oci-artifacts
> Add blog post about CRI-O's seccomp OCI artifact feature

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Hello!
I added link to `netcat` official site and a very useful key `-v` at example command.
Why did I add this?
1. My installation did not include netcat out of the box and I had to search for what was meant.
2. When running the example as is (without an additional key) - it is absolutely unclear what is happening.
Example output of the command without a key, if the port is unavailable:
```
$ nc 127.0.0.1 6443
```
Example of command output with key, if port is unavailable:
```
nc 127.0.0.1 6443 -v
nc: connectx to 127.0.0.1 port 6443 (tcp) failed: Connection refused
```
> Added link to netcat official site and '-v' key to netcat command example

- content/en/docs/reference/command-line-tools-reference/feature-gates/runtime-class-in-image-cri-api.md
> Fix link in RuntimeClassInImageCriApi feature gate

- content/en/docs/concepts/workloads/controllers/replicaset.md
- content/en/examples/controllers/frontend.yaml
Updated frontend.yaml in the Controllers File Path
A lot of developers have complained about the image `gcr.io/google_samples/gb-frontend:v3` failing. I was able to trace the image to [here](https://console.cloud.google.com/gcr/images/google-samples/global/gb-frontend).
I noticed that it doesn't work anymore, even when I do a `docker pull` and then a `docker run`
I also tried creating a `php:latest` container alone and it failed.
I initially used `nginx` image, but thanks to @adityasamant25 who pointed me to the latest php-redis image used which was referenced in this PR #44290 `us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5`
The rest of the section had to reflect the new image created.
- A description of the Replicast
- New generated names of the running pods
- New …
> Changing the Image Specified in the ReplicaSet Documentation 

- content/en/docs/concepts/security/multi-tenancy.md
Fixes #40114 
From the Kubernetes documentation standpoint, a minor change in the wording should help clear the ambiguity specified in issue #40114. Instead of stating that Kata Containers is an OCI _"compliant"_ runtime, I'm proposing a change to state that Kata containers _"support"_ the OCI Runtime Specification (from v3.0.2 and above).
> Improve wording around Kata containers and OCI runtime spec

- content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md
This PR updates [the pkgs.k8s.io announcement blog post](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) to include a note about creating `/etc/apt/keyrings` directory on older versions of some distros upon migrating to the new package repositories. This has been an issue for many users, e.g. see https://github.com/kubernetes/release/issues/3491
The note has been copied from Installing Kubeadm page.
> Add a note about /etc/apt/keyrings to pkgs.k8s.io migration guide

- content/en/docs/concepts/scheduling-eviction/api-eviction.md
- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/concepts/scheduling-eviction/kube-scheduler.md
- content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
- content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md
- content/en/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md
- content/en/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
- content/en/docs/concepts/scheduling-eviction/scheduling-framework.md
- content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
This PR aims to fix a spelling mistake in the Kubernetes Scheduler documentation.
An 's' was missing. I checked the rest of the file and did not find any other spelling mistake. No broken link found.
Link to doc: https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/
> Fix spelling mistake in kube scheduler

- layouts/partials/head.html
- layouts/shortcodes/cncf-landscape.html
Add integrity attribute to script used by CNCF Landscape shortcode.
Fixes [#45404](https://github.com/kubernetes/website/issues/45404#issue-2163352174)
> Add integrity attribute to script used by CNCF Landscape shortcode 

- content/en/blog/_posts/2021-11-12-are-you-ready-for-dockershim-removal/index.md
- content/en/blog/_posts/2022-02-17-updated-dockershim-faq.md
- content/en/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md
- content/en/docs/setup/production-environment/container-runtimes.md
- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/en/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
We get a lot of questions around the installation of cri-dockerd in the repo. We've found that many of the questions come from users being linked to the repo from the kubernetes docs and then they try to use the development installation method when they are not developers.
We now have an official documentation page that provides a straightforward installation using the different packages available. This PR is to update the links in the website so users get directed to the official docs rather than the repo.
> Update cri-dockerd links to point to the official docs

- content/en/docs/concepts/architecture/nodes.md
A simple update to the nodes doc, which I thought might clarify that labels are **only** updated upon registration with the API server.
> clarify nodes only update labels upon registration

- content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
Applied fix for Broken tab layout on "Changing The Kubernetes Package Repository" page in 1.27
This will help with https://github.com/kubernetes/website/issues/45048
> Backport fix for tab layout rendering in release-1.27

- content/en/docs/concepts/workloads/management.md
- static/_redirects
Move [Managing Resources](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/) to [Managing Workloads](https://kubernetes.io/docs/concepts/workloads/management/) ([preview](https://deploy-preview-45212--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/management/))
/label refactor
> Move and reword workload management page

- content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
Applied fix for Broken tab layout on "Changing The Kubernetes Package Repository" page in 1.25
This will help with https://github.com/kubernetes/website/issues/45048
> Backport fix for tab layout rendering in release-1.25

- content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
Applied fix for Broken tab layout on "Changing The Kubernetes Package Repository" page in 1.26
This will help with https://github.com/kubernetes/website/issues/45048
> Backport fix for tab layout rendering in release-1.26

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
- Add feature gate WaitForAllControlPlaneComponents
- https://github.com/kubernetes/kubeadm/issues/2907
- https://github.com/kubernetes/kubernetes/pull/123341
- https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-wait-for-all-control-plane-components-latest
> kubeadm: update documentation for 1.30

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
**Whats this PR?**
This PR improves the [Installing kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) document with following improvements:
- When mentioning Kubernetes version, it's consistent to use v1.29 than 1.29.
- In Linux, use of the term "directory" is more preferable than folder.
- Mention it's optional to enable the kubelet service before running kubeadm
> Improvements in "Installing kubeadm" document

- content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/admission-webhook-match-conditions.md
For MatchConditions Beta graduation in v1.30.
https://github.com/kubernetes/enhancements/issues/3716
/milestone v1.30
Opening this PR as a replacement for this other placeholder PR https://github.com/kubernetes/website/pull/45279
> Mark feature AdmissionWebhookMatchConditions to stable in 1.30

- content/en/docs/reference/access-authn-authz/authorization.md
Docs updates for KEP 3221: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3221-structured-authorization-configuration
KEP issue: https://github.com/kubernetes/enhancements/issues/3221
> Add docs for Structured Authz beta

- content/en/docs/concepts/architecture/nodes.md
In our code, we removed `UnlimitedSwap` and added a default setting of `NoSwap`.
Waiting on https://github.com/kubernetes/kubernetes/pull/122745
> [KEP-2400] Update swap with beta2 deprecations

- content/en/docs/tutorials/security/apparmor.md
- content/en/examples/pods/security/hello-apparmor.yaml
The AppArmor documentation has not been updated in a long time, and references a number of details that have since changed or been removed.
This PR updates the docs to be inline with the current implementation, including:
- Removing discussion of the v1.4 version boundary (it's been long enough)
- Removing references to the Kubelets status message (will be removed in v1.30)
- Removing references to Kubelet profile validation ([removed in v1.24](https://github.com/kubernetes/kubernetes/pull/97966))
- Removing references to security configuration in the container created event (was removed with docker-shim)
Note: https://github.com/kubernetes/website/pull/45176 will have the API changes for v1.30. The changes in this PR apply to earlier versions as well.
/sig node
> Refresh AppArmor documentation

- content/en/examples/pods/security/seccomp/profiles/fine-grained.json
If following steps in the *Restrict a Container's Syscalls with seccomp* tutorial, the [`fine-pod`](https://github.com/kubernetes/website/blob/63c3ee3a1e6771b1c4f5c16871dcc2d043e31937/content/en/docs/tutorials/security/seccomp.md#create-a-pod-with-a-seccomp-profile-that-only-allows-necessary-syscalls) will failed to start. The result is not expected as what described in the tutorial.
*   OS: Ubuntu 22.04.2 LTS (in VirtualBox)
*   CPU architecture: x86-64
*   Kind version: 0.22.0
Following steps in the tutorial, I found the `fine-pod` failed to start with status `CrashLoopBackOff`:
```bash
NAME       READY   STATUS             RESTARTS     AGE
fine-pod   0/1     CrashLoopBackOff   1 (2s ago)   10s
```
So I looked into logs of the Pod to try to figure out what happened, and it shows: …
> Add missing syscalls in fine-grained profile of seccomp tutorial

- content/ko/docs/tasks/administer-cluster/quota-api-object.md
- content/ko/examples/admin/resource/quota-objects-pvc-2.yaml
- content/ko/examples/admin/resource/quota-objects-pvc.yaml
- content/ko/examples/admin/resource/quota-objects.yaml
#44507 
위 이슈를 번역하였습니다.
추가적으로 한글화하면서 약간의 질문이 있어서 도움을 받고 싶습니다.
1. 57번째 줄의 각 유형들(PersistentVolumeClaim, LoadBalancer)을 한글로 표기해야하는지, 원문으로 표기해야하는지를 잘 모르겠습니다.
중국버전을 확인해보니  영문 그대로 표현하던데, 그에 대한 근거를 잘 모르겠어서 우선 한글로 표기하였습니다! 
134번째 줄의 LoadBalancer도 같은 상황입니다!
2. 75번째 줄에서 "Here is the configuration file for a PersistentVolumeClaim object:"문장을 "퍼시스턴트볼륨클레임 오브젝트에 대한 설정 파일은 다음과 같다."와 같이 번역하였습니다.
밑에 100번째 줄에서 "Here is the configuration file for a second PersistentVolumeClaim:" 과 같은 문장이 있어서, "두 번째 퍼시스턴트볼륨클레임 오브젝트의 설정 파일은 다음과 같다." 와 같이 번역하였는데, 사실 두 문장의 의미가 거의 동일하다고 봐도 무방하여 통일성을 위해 100번째 줄의 번역에 "오브젝트"라는 단어를 원문과 다르게 추가하였습니다. 이런 식으로 진행해도 괜찮은지, 원문을 따라 "두 번째 퍼시스턴트볼륨클레임의 설정 파일은 다음과 같다." 정도로 번역하면 되는지 궁금합니다.
리뷰어의 의견에 따라 필요시 수정하겠습니다! 항상 감사합니다!
> [ko] Translate /docs/tasks/administer-cluster/quota-api-object into Korean

- assets/scss/_custom.scss
- data/i18n/en/en.toml
- layouts/partials/announcement.html
- layouts/partials/head.html
- static/js/dismiss_banner.js
Closes #39887
This PR adds an option and a script to make the announcement banners dismissable
The script uses cookies which expire over a period of time; Till the next acknowledgement is taken
> The announcement banners can now be made dismissible

- content/en/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
NewVolumeManagerReconstruction is now GA / stable. It should be invisible to users, it only allowed cluster admin to revert back to original behavior if our refactoring was buggy.
~WIP:~
~* [implementation](https://github.com/kubernetes/kubernetes/pull/123442) must be merged first.~
> Mark NewVolumeManagerReconstruction as GA

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- content/en/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md
The changed doc claimed that as part of installing the kubeadm package, the file `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` will be created.
But on Ubuntu 22.04, if I `apt-get install kubeadm=1.28.x-1.1` that file doesn't exist. Instead,  `/lib/systemd/system/kubelet.service.d/10-kubeadm.conf` is created.
Note: I have no quick access to different Ubuntu versions unfortunately. So I don't know if with different versions the file is installed at a different location.
> Fix path of kubelet systemd config file

- content/en/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/pod-scheduling-readiness.md
Ref https://github.com/kubernetes/enhancements/issues/3521.
(A placeholder for now)
> promote feature PodSchedulingReadiness to stable

- content/en/docs/reference/command-line-tools-reference/feature-gates/selinux-mount.md
- content/en/docs/tasks/configure-pod-container/security-context.md
Add documentation for SELinuxMount feature gate.
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling
Issue: https://github.com/kubernetes/enhancements/issues/1710
~WIP:~
~needs the [implementation](https://github.com/kubernetes/kubernetes/pull/123157) merged first~
> Document SELinuxMount feature gate

- content/bn/docs/reference/glossary/container-runtime.md
This is PR is Localize `content/bn/docs/reference/glossary/container-runtime.md` and fixed build error:
```bash
ERROR [bn] "docs/concepts/containers/_index.md": "container-runtime" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
```
Fixes Issue: #44993 
Tracking Issue: #31677
> [bn] Localize glossary entry for container runtime

- content/en/docs/concepts/cluster-administration/system-logs.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/contextual-logging.md
Related-to: https://github.com/kubernetes/enhancements/issues/3077
/hold
https://github.com/kubernetes/kubernetes/pull/122589 needs to be merged first.
> contextual logging: beta in Kubernetes 1.30

- content/en/docs/reference/using-api/deprecation-guide.md
Fix deprecated API migration guidance of HorizontalPodAutoscaler. Because **targetAverageUtilization** is replaced with **target** object in **autoscaling/v2**. Also add example for migration
> Update deprecated API migration guidance of HorizontalPodAutoscaler for v1.25 and v1.26

- content/en/docs/concepts/cluster-administration/logging.md
This PR documents the new configuration parameter for kubelet, that allows changing pod logs directory to a custom path.
ref: https://github.com/kubernetes/kubernetes/pull/112957
> Document changing pod logs directory in kubelet

- content/ko/docs/concepts/workloads/controllers/job.md
- content/ko/docs/tasks/job/pod-failure-policy.md
- content/ko/examples/controllers/job-pod-failure-policy-failjob.yaml
- content/ko/examples/controllers/job-pod-failure-policy-ignore.yaml
from #40973 
Translated [Handling retriable and non-retriable pod failures with Pod failure policy](https://kubernetes.io/docs/tasks/job/pod-failure-policy) into Korean.
> [ko]Translate docs/tasks/job/pod-failure-policy into Korean

- content/en/docs/contribute/new-content/blogs-case-studies.md
Based on comment in https://github.com/kubernetes/website/issues/44123#issuecomment-1831041912 and conversation in slack https://kubernetes.slack.com/archives/CJDHVD54J/p1706577613048429?thread_ts=1706544061.503169&cid=CJDHVD54J and offline conversation with @Gauravpadam , this change adds some guidelines for mirroring a blog post from kubernetes.dev to kubernetes.io
> Add kubernetes.dev mirroring guidelines

- content/en/docs/contribute/participate/pr-wranglers.md
- Mention the [issue wrangler role](https://kubernetes.io/docs/contribute/participate/issue-wrangler/)
- Make it clear that PR wrangling includes the [reference docs generator](https://github.com/kubernetes-sigs/reference-docs/)
> Tweak PR wrangling guide

- content/en/blog/_posts/2024-03-19-go-workspaces.md
A blog post on Go workspaces in k/k
> Go workspaces blog post

- content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md
- content/en/docs/tasks/job/fine-parallel-processing-work-queue.md
Fix documentation for parallel processing work queue tasks.
Changes in details:
- Add instructions to run redis server, since without it the rest of the steps won't work.
- For work-queue jobs, instruct the user to leave the completions number unset (as setting it to 1 won't run more than one job in parallel, and is different when left unset).
- Change the package installation to python3, as python package is no longer available
Documents affected:
- https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/
- https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/
> Fix documentation for parallel processing work queue tasks.

- content/en/docs/reference/command-line-tools-reference/feature-gates/port-forward-websockets.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/translate-stream-close-websocket-requests.md
- content/en/docs/reference/kubectl/kubectl.md
* Updates control plane feature flag: `TranslateStreamCloseWebsocketRequests` to Beta
* Adds new control plane feature flag: `PortForwardWebsockets` as Alpha
* Adds new `kubectl` feature flag: `KUBECTL_PORT_FORWARD_WEBSOCKETS`
https://github.com/kubernetes/enhancements/issues/4006
> [KEP-4006] Docs for Transitioning from SPDY to WebSockets (Beta)

- content/en/docs/concepts/workloads/pods/user-namespaces.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/user-namespaces-support.md
- content/en/docs/tasks/configure-pod-container/user-namespaces.md
This PR updates the documentation for changes coming in 1.30 and some other small fixes that I'll backport once this is merged.
cc @giuseppe
> User namespaces doc changes for 1.30

- content/en/docs/reference/kubectl/quick-reference.md
Added 2 new commands to kubectl quick-reference.md
* kubectl top node                # Show metrics for all nodes
* kubectl top pod                  # Show metrics for all pods in the default namespace
> Add new commands to kubectl quick-reference.md

- content/en/docs/tasks/tools/included/verify-kubectl.md
Hi, I was trying to install Kubernetes on my local machine and I noticed that suggestion to install Minikube did not have a hyperlink to it. So I added a link at the mention of install Minikube so it's convenient for people trying to install it on their local machine.
> Added a link to the minikube installation website

- content/zh-cn/docs/reference/node/node-labels.md
`node-labels.md` refers to a Markdown file containing corrections for the error rendering in Hugo within the browser.
> Update error rendering in node-labels.md

- content/en/docs/concepts/containers/container-lifecycle-hooks.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action.md
This should only involves the stage change of the feature gate.
/hold 
Wait for https://github.com/kubernetes/kubernetes/pull/122456
> graduate PodLifecycleSleepAction to beta (KEP 3960)

- content/en/docs/concepts/security/cloud-native-security.md
- content/en/docs/concepts/security/pod-security-admission.md
- content/en/docs/concepts/security/pod-security-standards.md
- content/en/docs/concepts/security/security-checklist.md
- content/en/docs/reference/labels-annotations-taints/_index.md
- content/en/docs/tasks/debug/debug-cluster/_index.md
- content/en/docs/tutorials/security/apparmor.md
- content/en/examples/pods/security/hello-apparmor.yaml
AppArmor is going to GA in v1.30, including some API changes.
**Note to reviewers:**
This PR is based on https://github.com/kubernetes/website/pull/45471, which should be merged first. Only the second commit should be reviewed in this PR.
https://github.com/kubernetes/enhancements/issues/24
/sig node
/milestone v1.30
> Apparmor 1.30

- content/en/docs/contribute/analytics.md
This PR updates the link to the new analytics dashboard. The dashboard is very similar to the old analytics dashboard.
* page one: User over view page
* page 2: top 50 pages by page views
* page 3: top 50 search terms
* page 4: top blogs
One thing to note is that there are still permission issues which @divya-mohan0209 calls out in https://github.com/kubernetes/website/issues/44292. I'm not sure the best way to make this more sustainable. There can only be one set of credentials to pull the data from GA4 into the dashboard, right now I have it set up to use mine.  @natalisucks @reylejano @divya-mohan0209 if you have any suggestions on who this should be, please let me know and I can update it.  
fixes https://github.com/kubernetes/website/issues/43281
> Update analytics dashboard and change link on site

- content/en/docs/reference/kubectl/introduction.md
> Move the introduction page from SIG CLI guides to the kubectl reference

- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/concepts/cluster-administration/_index.md
- content/en/docs/concepts/cluster-administration/addons.md
- content/en/docs/concepts/cluster-administration/cluster-autoscaling.md
- content/en/docs/concepts/workloads/autoscaling.md
- content/en/docs/setup/best-practices/cluster-large.md
- content/en/docs/setup/production-environment/_index.md
- content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
Add a new page about cluster autoscaling ([preview](https://deploy-preview-45197--kubernetes-io-main-staging.netlify.app/docs/concepts/cluster-administration/cluster-autoscaling/)), and adjust other pages accordingly.
Helps with https://github.com/kubernetes/website/issues/4493
/sig cluster-lifecycle autoscaling
> Add concept page about cluster autoscaling

- content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
It's pretty clear from the context that the goal here is to allow the reader to access the pod through the proxy. The previous URL only pointed towards the API endpoint to get information about the pod, but not the actual proxy endpoint.
> Show the correct proxy URL in the deploy-intro.

- content/en/docs/concepts/storage/volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/recursive-read-only-mounts.md
- content/en/examples/storage/rro.yaml
For:
- https://github.com/kubernetes/enhancements/issues/3857 (alpha in v1.30)
Depends on:
- - -
Preview: https://deploy-preview-45159--kubernetes-io-vnext-staging.netlify.app/docs/concepts/storage/volumes/#recursive-read-only-mounts
> [dev-1.30] KEP-3857: Recursive Read-only (RRO) mounts

- content/en/docs/concepts/configuration/configmap.md
- content/en/docs/concepts/configuration/secret.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/relaxed-environment-variable-validation.md
- content/en/docs/tasks/inject-data-application/define-environment-variable-container.md
> Document option to allow almost all printable ASCII characters in environment variables

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/job-success-policy.md
- content/en/examples/controllers/job-success-policy-example.yaml
- content/en/examples/controllers/job-success-policy.yaml
In this PR, I added documentation for the https://github.com/kubernetes/enhancements/issues/3998.
> Add JobSuccessPolicy Doc

- content/en/docs/concepts/workloads/controllers/job.md
This PR is a follow-up of #45135.
cc: @mimowo @alculquicondor 
/assign @divya-mohan0209
> KEP-3998: Rephrase JobSuccessPolicy documentations

- content/en/docs/concepts/overview/kubernetes-api.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/aggregated-discovery-endpoint.md
https://github.com/kubernetes/enhancements/issues/3352
> [KEP-3352] docs for aggregated discovery

- content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md
This PR updates [the `pkgs.k8s.io` announcement blog post](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) to reflect removal of the legacy package repositories (https://github.com/kubernetes/release/issues/3485).
This PRs follows our usual procedure to cross out parts of the blog post that are not valid any longer instead of removing those parts. As per the feedback on Slack, I left the original announcement that the legacy repos will go away in January 2024.
Ref https://kubernetes.slack.com/archives/CJDHVD54J/p1711456726003369
Another PR will follow up to update https://k8s.io/linuxrepos
> Update pkgs.k8s.io blog to reflect legacy repos removal

- content/en/docs/concepts/architecture/garbage-collection.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/image-maximum-gc-age.md
as well as document accompanying metric
KEP: https://github.com/kubernetes/enhancements/pull/4210
> ImageGCMaxAge beta bump

- content/en/docs/concepts/architecture/nodes.md
- static/_redirects
Adding documentation for the new `disable-force-detach-on-timeout` flag.
The associated k8s PR can be found here: https://github.com/kubernetes/kubernetes/pull/120344
This is a new flag that is being added to disable force detach behavior when the 6 minute node unhealthy timer expires in kube-controller-manager in favor of [non-graceful node-shutdown](https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown).
Note: I am closing https://github.com/kubernetes/website/pull/44931, which was opened against the wrong branch.
@sftim @Shubham82 @bswartz @msau42 @saad-ali @liggitt @jingxu97 @carlory for visibility.
> Add documentation for disable-force-detach-on-timeout

- content/en/docs/tasks/configure-pod-container/security-context.md
KEP: https://github.com/kubernetes/enhancements/pull/4265
> ProcMount 1.30 update

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
In light of this thread: https://github.com/kubernetes/enhancements/issues/3521#issuecomment-2016805887
I suggest we graduate this note to a warning.
Preview: https://deploy-preview-45683--kubernetes-io-main-staging.netlify.app/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
> Upgrade note about nodeName to warning

- README.md
Fixes #45597
The instruction to install a specific Hugo extended version as defined in [netlify.toml](https://github.com/kubernetes/website/blob/main/netlify.toml#L11) is mentioned in the [Running the website locally using Hugo](https://github.com/kubernetes/website?tab=readme-ov-file#running-the-website-locally-using-hugo) section.
However, I believe it would be helpful to move the instruction to the [Prerequisites](https://github.com/kubernetes/website?tab=readme-ov-file#prerequisites) section. This would prevent readers from inadvertently installing the latest Hugo extended version (currently v0.124.1) which is incompatible with k/w.
Suggestions and feedback are welcome!
Kind regards,
Aditya.
> Add a note to specify the required Hugo version in the prerequisites.

- content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md
Follow up on #45682 
Ref https://kubernetes.slack.com/archives/CJDHVD54J/p1711456726003369
This PR updates the [legacy repos deprecation announcement blog post](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/) to reflect that the legacy package repositories are gone.
> Update legacy repos deprecation blog to reflect repos removal

- content/ja/docs/tasks/debug/debug-cluster/windows.md
Fixes #44988 
Preview: https://deploy-preview-45386--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/debug/debug-cluster/windows/
> [ja] Translate content/ja/docs/tasks/debug/debug-cluster/windows.md into Japanese

- content/en/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md
- content/en/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md
@sftim left some nits about our pkgs.k8s.io blog posts here: https://github.com/kubernetes/website/pull/45685#pullrequestreview-1962769549
This PR is supposed to address those nits.
> pkgs.k8s.io: fix nits from previous PRs

- content/en/docs/reference/glossary/immutable-infrastructure.md
Added “Immutable infrastructure” to glossary as part of https://github.com/kubernetes/website/issues/45655 using the content from https://glossary.cncf.io/immutable-infrastructure.
Closes https://github.com/kubernetes/website/issues/45655
> Add “Immutable infrastructure” to glossary

- content/en/docs/reference/config-api/kubeadm-config.v1beta4.md
When adding formatting to the controlPlaneEndpoint config reference for kubeadm-config v1beta4 it appears the first letter of the value was accidentally dropped. This adds it back in the two places where this happened.
My guess is adding the "c" in the `<code>` block in 74516499205c439c913aa8c197eaf9ee0f85763c accidentally picked up the leading "c" from the name.
Closes: #45602
> Fix typo in kubeadm-config v1beta4 config reference

- content/en/docs/concepts/security/rbac-good-practices.md
Updating the RBAC Good Practices guide to include information on Patch operations against Namespaces being a security risk.
> Add Namespace Patching to RBAC good practice

- README-hi.md
Updated the Build link in the README-hi.md file to align with the main [README.md](https://github.com/kubernetes/website/blob/main/README.md) file
Also a ref issue #41241 was opened regarding this
> [hi] Update the Build link in README file

- content/en/blog/_posts/2022-11-04-live-and-let-live-with-kluctl-and-ssa.md
This updates a few dead or outdated links to the kluctl.io docs. It also links to the now merged delivery scenario of podtato-head instead of linking to my fork.
> Update a few dead/outdated links in the "live and let live" blog post

- content/en/docs/reference/command-line-tools-reference/feature-gates/storage-version-migration.md
- content/en/docs/tasks/manage-kubernetes-objects/storage-version-migration.md
Ref: https://github.com/kubernetes/enhancements/issues/4192
PR - https://github.com/kubernetes/kubernetes/pull/123344
Replaces: https://github.com/kubernetes/website/pull/45294
Considering contributor out of office. This also accounts for review suggestions made by @sftim
x-post on exception thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1711552644986199
/cc @nilekhc @deads2k @jpbetz @enj
/milestone 1.30
/sig docs
> docs: adds documentation for Storage Version Migration

- content/en/blog/_posts/2024-04-03-windows-ops-readiness.md
As per recent communication from the Communications Team, this PR adds ~a placeholder for~ an upcoming blog article.
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/2578-windows-conformance
Project: https://github.com/kubernetes-sigs/windows-operational-readiness
/sig windows
cc @knabben @jayunit100
> blog: Windows Operational Readiness

- content/en/docs/reference/labels-annotations-taints/_index.md
Update https://kubernetes.io/docs/reference/labels-annotations-taints/ to revise the entry for `endpointslice.kubernetes.io/managed-by`.
Use the most common value for this label (`endpointslice-controller.k8s.io`) as the example value.
> Improve example for EndpointSlice label

- content/zh-cn/docs/reference/glossary/container.md
The original link "https://kubernetes.io/zh-cn/docs/concepts/overview/what-is-kubernetes/#why-containers" is no longer in use
> [zh-cn] Fix the full_link of glossary in container.md

- content/en/docs/concepts/architecture/leases.md
- content/en/docs/concepts/architecture/nodes.md
- content/en/docs/concepts/configuration/configmap.md
- content/en/docs/concepts/configuration/secret.md
- content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
- content/en/docs/concepts/overview/working-with-objects/namespaces.md
- content/en/docs/concepts/policy/limit-range.md
- content/en/docs/concepts/policy/resource-quotas.md
- content/en/docs/concepts/services-networking/endpoint-slices.md
- content/en/docs/concepts/services-networking/ingress.md
- content/en/docs/concepts/services-networking/service.md
- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/concepts/storage/volumes.md
- content/en/docs/concepts/workloads/controllers/cron-jobs.md
- content/en/docs/concepts/workloads/controllers/daemonset.md
- content/en/docs/concepts/workloads/controllers/deployment.md
- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/concepts/workloads/controllers/replicaset.md
- content/en/docs/concepts/workloads/controllers/replicationcontroller.md
- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/concepts/workloads/pods/_index.md
- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
- data/i18n/en/en.toml
- layouts/docs/list.html
- layouts/docs/single.html
- layouts/partials/docs/api-reference-links.html
- layouts/partials/page-meta-links.html
- layouts/shortcodes/page-api-reference.html
Added new **partial layout** named `api-reference-links.html` to fetch the link of the API reference page based on metadata present in the front matter of the file and add the API reference links to page links section of the page. Also, implemented `page-api-reference` shortcode to display relevant API links in the markdown pages.
Fixes #24441
- The `api-reference-links.html` _partial layout_ functionality relies on the presence of `api_metadata` in the front matter of concept pages. This metadata includes "apiVersion" and "kind" attributes, similar to those found in the auto-generated API reference file, Example structure:
```
- api_metadata:
apiVersion: "v1"
kind: "Node"
```
```
api_metadata:
- apiVersion: "certificates.k8s.io/v1"
kind: "CertificateSigningRequest"
- apiVersion: …
```
> Add mechanism to retrieve API reference page link based on metadata

- content/en/docs/concepts/services-networking/network-policies.md
This builds on the change for https://github.com/kubernetes/website/pull/45496 and adds that mechanism to the NetworkPolicy page (https://k8s.io/docs/concepts/services-networking/network-policies/)
_[Preview](https://deploy-preview-45746--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/network-policies/) of the update page_
> Signpost to API reference for NetworkPolicy

- content/en/docs/reference/glossary/priority-class.md
Hello! This PR address issue #41943. As I see both previous PR is stale and closed. This PR based on #41972 with all comments addressed
> feat: Add PriorityClass in glossary

- content/en/docs/concepts/overview/kubernetes-api.md
Removed an extra "v" in the link to fix the broken link.
> Fix discovery document link in kubernetes-api.md

- content/en/docs/reference/glossary/init-container.md
There are 2 full links in this glossary file so removed one full link and kept the other one to align with other files.
> Remove redundant link from glossary term "Init Container"

- content/en/docs/tasks/tools/install-kubectl-linux.md
The keyring needs to be readable by _apt, otherwise "apt update" prints the following kind of error:
W: GPG error: https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.29/deb  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 234654DA9A296436
E: The repository 'https://pkgs.k8s.io/core:/stable:/v1.29/deb  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
kubernetes.list needs to be world-readable, otherwise command-not-found prints warnings such as:
WARNING:root:could not open file '/etc/apt/sources.list.d/kubernetes.list'
> install-kubectl-linux.md: add chmods

- content/en/docs/reference/access-authn-authz/authentication.md
- Add `certificateAuthority` in structured authn docs
/sig auth
/assign enj
> Add certificateAuthority in structured authn docs

- content/en/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
Wrong scheme link replaced to correct one:
> blog: fix loadbalancer scheme (DIY: Create Your Own Cloud with Kubernetes (Part 2) blog post)

- content/en/blog/_posts/2024-04-04-SIG-Architecture-Code-Organization-Spotlight.md
- content/en/blog/_posts/2024-04-11-SIG-Architecture-Code-Organization-Spotlight.md
SIG Architecture: Code Organization spotlight article.
Initial reviews will be done at the `contributor-site` PR https://github.com/kubernetes/contributor-site/pull/493 ; after they are integrated, I will sync the content of this PR and remove the WIP / unhold.
> Add SIG Architecture Code Organization spotlight article

- OWNERS_ALIASES
- content/ar/OWNERS
Adding OWNERS to fix the issue with approve for arabic team. 
Slack discussion :  https://kubernetes.slack.com/archives/CP9FKRD51/p1710921248918939
> Create OWNERS for ar localization

- OWNERS_ALIASES
Since we have @kirkonru in the organisation, we can add him to the reviewers and owners list for the Russian localisation :tada: 
Related PR: https://github.com/kubernetes/org/pull/4846
> Add kirkonru to sig-docs-ru

- content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md
**This PR:**
- Updates the [Deploying the Dashboard UI](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui) section to use Helm-based installation.
The previous method of deploying the Dashboard is no longer supported, and the Kubernetes Dashboard now only supports Helm-based installation.
> Update Kubernetes Dashboard deployment to Helm-based installation

- content/en/docs/reference/labels-annotations-taints/_index.md
Fixes: https://github.com/kubernetes/website/issues/45369
Added legacy annotation service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset and a note explaining its deprecation.
> Annotation azure-load-balancer-disable-tcp-reset registered & documented

- content/ar/docs/tutorials/kubernetes-basics/_index.html
This PR adds the translation related to the tutorials basics  `/docs/tutorials/kubernetes-basics`.
Part of https://github.com/kubernetes/website/issues/44682
> [ar]: Translate tutorials/kubernetes-basics/_index.html page to arabic

- README-es.md
I was going through the repo README files and found a broken Netlify status badge link in README-es.md. Fixed the badge link by using the value from the english README.md file. The badge now works.
> [es] Fix broken Netlify status badge link in README

- content/en/docs/home/_index.md
- content/en/docs/home/supported-doc-versions.md
Changed link of "About the documentation" to button with text "See available versions" on homepage
This will fix https://github.com/kubernetes/website/issues/43249
> Update button label to 'See available versions' in docs homepage

- layouts/partials/docs/api-reference-links.html
This PR contains changes to resolved an issue where API reference links were not appearing on localized pages. Despite adding `api-metadata` to the front-matter of localized pages.
**Additional Context:**
The root cause of the problem was identified in the `GetPage` function with the particular `site` object, which already possessed knowledge of the language for the current page and thus didn't require a language identifier _(considerable debugging efforts were essential to uncover this)_. Consequently, it failed to detect any localized API reference pages to link. Implemented necessary adjustments to rectify this issue, ensuring that API reference links now display correctly for both English pages and localized pages.
**Useful Preview Links**
[Preview Chinese …
> Refine API reference page link retrieval mechanism to support localized pages

- content/en/docs/concepts/cluster-administration/system-traces.md
This PR is related to K8s trace, and  introduces:
1. How to emit traces to trace backend directly(this is a scenario on public cloud)
2. How to configure OTEL_EXPORTER_OTLP_HEADERS, OTEL_RESOURCE_ATTRIBUTES environment variables to tune OTEL options, including authentication, K8s attributes. 
This PR is based on below discussion.
https://github.com/kubernetes/kubernetes/issues/123531
CC  @dashpole
> Configure Kubernetes components's OTEL traces configuration (emitting traces directly and tuning with environment)

- content/en/docs/concepts/services-networking/ingress.md
This PR fixes the link for `service.NodePort` under the [Ingress docs](https://kubernetes.io/docs/concepts/services-networking/ingress/)
Fixes #45848
> Fix link for service.NodePort

- content/en/blog/_posts/2024-01-15-SIG-Release-Spotlight/index.md
- content/en/blog/_posts/2024-01-23-image-filesystem.md
- content/en/blog/_posts/2024-02-22-k8s-book-club/index.md
- content/en/blog/_posts/2024-03-01-sig-cloud-provider-spotlight.md
- content/en/blog/_posts/2024-03-07-cri-o-seccomp-oci-artifacts.md
- content/en/blog/_posts/2024-03-12-mid-cycle-1.30.md
- content/en/blog/_posts/2024-04-03-windows-ops-readiness.md
- content/en/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-1/index.md
- content/en/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
- content/en/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-3/index.md
- content/en/blog/_posts/2024-04-11-SIG-Architecture-Code-Organization-Spotlight.md
- layouts/blog/list.html
This PR contains changes to incorporate `author` metadata into front matter for improved handling of author details instead of listing authors in the blog content. Utilized Docsy's ([example blog](https://www.docsy.dev/blog/2024/0.9.0/)) native support for `author` metadata to ensure consistency and compatibility.
Fixes https://github.com/kubernetes/website/issues/40175
- Modified the blog content files _(only blogs published in 2024)_ to include the following `author` metadata in front matter.
```yaml
slug: 
title: 
date:
author: >
Author-Name (Affiliation)
```
- Other examples demonstrating inclusion of authors in blog content:
- Multiple authors:
```yaml
slug: 
title: 
date:
author: >
Author-1 (Affiliation),
Author-2 (Affiliation),
Author-3 (Affiliation)
```
- Author with hyperlink …
> Improve blog article summaries presentation with author metadata in front matter

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- content/en/examples/pods/probe/http-liveness.yaml
The current image referenced in the liveness example is amd64 only, switch to the agnhost image and pass the parameter of liveness for equivalent functionality. This image has the benefit of being current, multi-arch and managed from a supply chain viewpoint in the kubernetes code tree.
See also:
https://github.com/kubernetes/website/issues/45809
https://github.com/kubernetes/website/issues/45822
> Switch liveness image to multi-arch agnhost container image

- content/en/training/_index.html
Add a Docsy-style menu entry to the training section.
The way this works is to set `menu` front matter that Docsy would display in a reasonable way. This change does not change the way the current site displays or, at least, that's what I intend.
[Current partner section index](https://k8s.io/training/) | [Preview partner section index](https://deploy-preview-45870--kubernetes-io-main-staging.netlify.app/training/)
> Ready training section for vanilla Docsy

- content/en/blog/_index.md
Align the (currently unused) menu entry for the blog section so it's got the front matter data that plain Docsy would use.
The way this works is to set `menu` front matter that Docsy would display in a reasonable way, and specifically _not_ to include a detailed description (`post`). This change does not change the way the current site displays or, at least, that's what I intend.
[Current blog section index](https://k8s.io/blog) | [Preview blog section index](https://deploy-preview-45868--kubernetes-io-main-staging.netlify.app/blog/)
> Ready blog section for vanilla Docsy

- content/en/case-studies/_index.html
Align how we style the case studies page to work more the way Docsy expects it to.
The way this works is to set `menu` front matter that Docsy would display in a reasonable way. This change does not change the way the current site displays or, at least, that's what I intend.
[Current case studies section index](https://k8s.io/case-studies/) | [Preview case studies section index](https://deploy-preview-45870--kubernetes-io-main-staging.netlify.app/case-studies/)
> Ready case studies page for vanilla Docsy

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
Fixes: https://github.com/kubernetes/website/issues/45033
Compared to the English version, the Chinese version has incorrect indentation：
page: https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
Here is [the preview page](https://deploy-preview-45876--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/).
> Fix the YAML format  in setup-ha-etcd-with-kubeadm

- content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
- content/ja/docs/tasks/tools/included/optional-kubectl-configs-fish.md
- content/ja/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
- content/ja/docs/tasks/tools/included/verify-kubectl.md
- content/ja/docs/tasks/tools/install-kubectl-macos.md
Fixes #45345 
This pull request is for the translation of `content/en/docs/tasks/tools/install-kubectl-macos.md` and its dependencies.
This translation is based on the contents of the [content/ja/docs/tasks/tools/install-kubectl.md](https://github.com/kubernetes/website/blob/de98cc74a50fca202fb6febcf482c99e0ca6efb4/content/ja/docs/tasks/tools/install-kubectl.md) (This file has already been deleted).
> [ja] Translate content/ja/docs/tasks/tools/install-kubectl-macos.md

- content/en/docs/reference/kubectl/quick-reference.md
The jsonpath does not parse properly with nested single quotes, changed single quotes to double quotes.
Nested single quotes gives the following error:
kubectl config view --raw -o jsonpath='{.users[?(.name == 'e2e')].user.client-certificate-data}' | base64 -d
error: error executing jsonpath "{.users[?(.name == e2e)].user.client-certificate-data}": Error executing template: unrecognized identifier e2e. Printing more information for debugging the template: [..]
> Fix nested single quotes in example command

- content/en/docs/concepts/workloads/controllers/cron-jobs.md
Update the `.spec.successfulJobsHistoryLimit` and `.spec.failedJobsHistoryLimit` fields descriptions. Fixes #38771
> Update cronjobs history limits spec description

- content/en/docs/concepts/workloads/controllers/job.md
Removes an incorrectly placed dot in the middle of the sentence which I noticed while reading through the docs.
> [en] Fix typo in job.md

- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
- content/en/docs/tutorials/configuration/configure-redis-using-configmap.md
- content/en/docs/tutorials/configuration/updating-configuration-via-a-configmap.md
- content/en/examples/configmap/immutable-configmap.yaml
- content/en/examples/configmap/new-immutable-configmap.yaml
- content/en/examples/deployments/deployment-with-configmap-and-sidecar-container.yaml
- content/en/examples/deployments/deployment-with-configmap-as-envvar.yaml
- content/en/examples/deployments/deployment-with-configmap-as-volume.yaml
- content/en/examples/deployments/deployment-with-configmap-two-containers.yaml
- content/en/examples/deployments/deployment-with-immutable-configmap-as-volume.yaml
Fixes #23101
Page preview: https://deploy-preview-44540--kubernetes-io-main-staging.netlify.app/docs/tutorials/configuration/updating-configuration-via-a-configmap/ 
I have created an initial draft for "Updating configuration via a ConfigMap".
It is a step-by-step tutorial describing 2 topics:
1. Updating configuration via a ConfigMap mounted as a Volume
2. Updating environment variables of a Pod via a ConfigMap
Following this hands-on tutorial, a reader will be able to understand the difference in the behaviour for the two scenarios.
I have not added a "What's next" section, as I did not find a logical page to follow after this. Suggestions welcome.
I have linked the new page as a "What's next" link from two related pages.
This is my first attempt at documenting an entirely new page in …
> Document updating configuration via a ConfigMap

- content/ar/docs/tutorials/_index.md
- content/ar/docs/tutorials/hello-minikube.md
This PR adds the translation related to the tutorials directory ` /docs/tutorials`.  It is a placeholder for the remaining commits.
Part of #44682
> [ar] Translate tutorials/_index and tutorials/hello-minikube.md pages to arabic

- OWNERS_ALIASES
This commit will add @adowair as an owner (approver) and reviewer for Arabic content on the website. This is based on the discussion here https://github.com/kubernetes/website/pull/44862#issuecomment-1995155214.
> Add adowair as owner, reviewer for Arabic content

- content/en/blog/_posts/2024-04-11-SIG-Architecture-Code-Organization-Spotlight.md
Fix link from relative to absolute: it was kept as-is but since this is not `contributor-site` it obviously fails.
(Thanks to @m1ghtym0 for detecting it)
> Fix link to contributor site article

- hugo.toml
This PR updates the hugo.toml for v1.29 ahead of the v1.30 release.
Base branch will be updated from main to release-1.29 once that branch exists.
/hold for v1.30 release day
> Updates v1.29 hugo.toml for v1.30 release

- content/en/docs/concepts/services-networking/service.md
This pull request revises the examples to include named ports and clarifies that the port names must match to ensure kube-proxy can configure proxy rules correctly for services without selectors.
ref: https://github.com/kubernetes/kubernetes/issues/123954
> recommend usage of named port for services without selectors

- content/en/docs/concepts/workloads/pods/sidecar-containers.md
Hello!
This PR aims to address an issue in the current [documentation](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#differences-from-init-containers) regarding the interaction of containers within a Pod, specifically about the sharing of environment variables.
In the current documentation, there's a statement suggesting that sidecar containers and main application containers within a Pod can share environment variables. This information could potentially lead to confusion, as environment variables are defined per container in Kubernetes and are not shared by default across containers within a Pod.
To clarify this and provide accurate information to users, I have removed the misleading reference to the sharing of environment variables from this statement -
> These …
> Fix misleading advice about sharing of environment variables

- content/en/docs/reference/networking/virtual-ips.md
As of now, we only have feature state information at https://kubernetes.io/docs/concepts/services-networking/service/#trafic-distribution. It would be nice to also have it be available at https://kubernetes.io/docs/reference/networking/virtual-ips/#traffic-distribution
Preview: https://deploy-preview-45907--kubernetes-io-main-staging.netlify.app/docs/reference/networking/virtual-ips/#traffic-distribution
> Add missing information about feature state of ServiceTrafficDistribution

- content/zh-cn/docs/concepts/scheduling-eviction/pod-overhead.md
The file `content/zh-cn/docs/concepts/scheduling-eviction/pod-overhead.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45454) ,so we will synchronize the localization.
> [zh]Update RuntimeClass name in Pod Overhead concept

- content/id/docs/concepts/workloads/pods/pod-lifecycle.md
- content/id/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- content/id/examples/pods/probe/http-liveness.yaml
id equivalent for https://github.com/kubernetes/website/pull/45837
> [id] Switch liveness image to multi-arch agnhost container image

- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_check-expiration.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_validate.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_all.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_coredns.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_wait-control-plane.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
- content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
> Update kubeadm reference for v1.30

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
Request to add Akri to the device plugin example list.
Akri is a Kubernetes Resource Interface that lets you easily expose heterogeneous leaf devices (such as IP cameras and USB devices) as resources in a Kubernetes cluster. The Akri Agent implements Kubernetes Device-Plugins for discovered resources.
> Adding project Akri to the device plugin examples

- .github/OWNERS
- OWNERS
- OWNERS_ALIASES
- assets/OWNERS
- assets/images/OWNERS
- content/OWNERS
- content/de/OWNERS
- content/es/OWNERS
- content/fr/OWNERS
- content/hi/OWNERS
- content/id/OWNERS
- content/it/OWNERS
- content/ja/OWNERS
- content/ko/OWNERS
- content/pl/OWNERS
- content/pt-br/OWNERS
- content/ru/OWNERS
- content/uk/OWNERS
- content/vi/OWNERS
- content/zh-cn/OWNERS
- data/canonical-tags/OWNERS
- data/i18n/OWNERS
- scripts/OWNERS
- scripts/releng/OWNERS
- static/css/OWNERS
- static/js/OWNERS
- Add a new website owners group
- Separate out “I can approve changes to English” from “I can approve changes anywhere on the website”
- Add labels to PRs that make web development changes
- Let the localization team review changes that add new localizations (?)
- Don't allow English reviewers to review changes for other languages (website owners still can)
> Switch to finer controls on approver access

- content/en/blog/_posts/2024-04-23-recursive-read-only-mounts.md
For:
- https://github.com/kubernetes/enhancements/issues/3857
Related:
- https://github.com/kubernetes/website/pull/45159
Preview: https://deploy-preview-45238--kubernetes-io-main-staging.netlify.app/blog/2024/04/23/recursive-read-only-mounts/
> blog post for KEP-3857: Recursive Read-only (RRO) mounts

- hugo.toml
This PR updates the cacheDir setup to utilize `getresource` instead of `getjson`, aligning with recent changes steering us away from 'getJSON' for remote data retrieval. 
Notably, this enhancement now enables correct refreshing of data on the Download Page and CVE feed.
[Preview Refreshed CVE Feed Link ](https://deploy-preview-45922--kubernetes-io-main-staging.netlify.app/docs/reference/issues-security/official-cve-feed/) | [Current Stale CVE Feed](https://kubernetes.io/docs/reference/issues-security/official-cve-feed/)
[Preview Download Page with v1.30](https://deploy-preview-45922--kubernetes-io-main-staging.netlify.app//releases/download/#binaries) | [Current Empty Download Page](https://kubernetes.io/releases/download/#binaries)
>  Update cacheDir configuration with "getresource" usage

- README-it.md
I was going through the repo README files and found a broken Netlify status badge link in README-it.md. Fixed the badge link by using the value from the english README.md file. The badge now works.
> [it] Fix broken Netlify status badge link in README

- content/en/docs/concepts/workloads/pods/pod-qos.md
This PR updates the feature-state shortcode parameter "feature-gate-name" in pod-qos.md to expected value of "feature_gate_name" so that the correct feature state is reflected. 
(Solution was provided by @dipesh-rawat in https://github.com/kubernetes/website/issues/45930#issuecomment-2066996137)
- Current Page with issue: https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#memory-qos-with-cgroup-v2
- Preview Page with updates from PR: https://deploy-preview-45933--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/pods/pod-qos/#memory-qos-with-cgroup-v2
Fixes https://github.com/kubernetes/website/issues/45930
> Fix feature-state for "Memory QoS with cgroup v2"

- content/en/blog/_posts/2024-04-17-kubernetes-1.30.md
Adding a note explaining the 1.30 release blog was updated post publication
Also, found and removed a duplicate paragraph in the CNCF webinar section
> Update release blog-new content note

- content/en/blog/_posts/2024-04-01-validating-admission-policy-ga/index.md
- content/en/blog/_posts/2024-04-24-validating-admission-policy-ga/index.md
- content/en/blog/_posts/2024-04-24-validating-admission-policy-ga/webhook.go
This is a blog post that serves as a walkthrough of converting a validating admission webhook to a validating admission policy. The intention of this post is to encourage the read to try out the newly graduated feature.
> Blog: ValidatingAdmissionPolicy GA

- content/en/docs/tutorials/hello-minikube.md
Delete the `menu` front matter for [Hello, Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/). Docsy would use this menu, but we don't want this page in the top navigation.
This change does not change the way the current site displays or, at least, that's what I intend.
[Current page](https://kubernetes.io/docs/tutorials/hello-minikube/) | [Preview](https://deploy-preview-45938--kubernetes-io-main-staging.netlify.app/docs/tutorials/hello-minikube/)
> Ready Hello, Minikube page for vanilla Docsy

- content/en/docs/reference/glossary/index.md
Set front matter for the glossary page so that we can use Docsy-native custom styling, if we want to.
The way this works is to set `body_class` front matter. This change does not change the way the current site displays.
[Current glossary page](https://k8s.io/docs/reference/glossary/) | [Preview glossary page](https://deploy-preview-45937--kubernetes-io-main-staging.netlify.app/docs/reference/glossary/)
> Ready glossary page for vanilla Docsy

- content/en/docs/home/_index.md
Align the (currently unused) menu entry for the documentation landing page, so it's got the front matter data that plain Docsy would use.
The way this works is to set `menu` front matter that Docsy would display in a reasonable way, and specifically _not_ to include a detailed description (`post`). This change does not change the way the current site displays or, at least, that's what I intend.
[Current documentation landing page](https://k8s.io/docs/home/) | [Preview documentation landing page](https://deploy-preview-45939--kubernetes-io-main-staging.netlify.app/docs/home/)
> Ready docs landing page for vanilla Docsy

- content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
* It didn't let developers know about another feature that can override a taint configuration.
Developers should be mindful that manually scheduling pods with node names in YAML spec files can override standard scheduling mechanisms and bypass taint configurations, impacting deployment behaviour in their Kubernetes cluster.
Thanks to @windsonsea and @tengqm who helped me align my contribution.
> Update Taints and Tolerations Documentation

- data/i18n/en/en.toml
- layouts/partials/footer.html
Don't assume we'll use English text to introduce the ICP license (seen in the footer of every page).
/language en
> Make ICP license leader text localizable

- content/en/docs/contribute/localization.md
Since content/en/docs/tutorials/kubernetes-basics is now a directory of source files and not a single markdown file any longer the instructions should be fixed.
> Fix localization.md since kubernetes-basics is now a directory

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Adding some documentation explaining what a CrashLoopBackOff is, what it implies, and behavioral details per https://github.com/kubernetes/website/issues/18903
> Adding  documentation explaining what is a CrashLoopBackOff

- content/en/docs/tasks/access-application-cluster/ingress-minikube.md
Fixes #44651
Fixes #45027
This PR adds instructions specific to MacOS and Windows to the [ingress-minikube](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) page. These instructions are needed in order to access a Service or an Ingress Resource deployed in minikube via a minikube tunnel.
This change is necessary as several readers have reported that the existing page does not provide this information and users on MacOS or Windows are unable to successfully complete this tutorial due to this gap.
**NOTE:**
I have successfully tested the proposed changes on a MacOS M* series machine. I am unable to test these changes on a Windows machine as I do not have access to one. I would really appreciate if a person having a Windows laptop would help me validate the …
> Instructions to access Service and Ingress Resource through a minikube tunnel

- content/en/docs/reference/using-api/api-concepts.md
- content/en/docs/reference/using-api/server-side-apply.md
- content/en/docs/tasks/administer-cluster/memory-manager.md
- content/en/docs/tasks/administer-cluster/switch-to-evented-pleg.md
- content/en/docs/tasks/configure-pod-container/resize-container-resources.md
- content/en/docs/tasks/configure-pod-container/user-namespaces.md
- content/en/docs/tasks/job/pod-failure-policy.md
- content/en/docs/tasks/network/extend-service-ip-ranges.md
- content/en/docs/tasks/run-application/configure-pdb.md
Switch some feature-state shortcodes to be data driven, using the behavior added in https://github.com/kubernetes/website/pull/45032.
When the relevant feature gates graduate (or get deprecated), the associated shortcode will render the changed data automatically.
Follows #45166
> Switch more feature-state shortcodes to be data driven

- content/en/docs/reference/kubectl/quick-reference.md
put fish completion config in its own conventional place
I almost dumped the completions out directly but then I realized this updates regularly as kubectl updates and adds new functionality.
This is also an improvement over the previous version as it sources the completions immediately.
> Update cheatsheet.md - fish completions

- content/en/docs/concepts/policy/resource-quotas.md
> 1. `count/*` — it's precieved as a wildcard mask as if it contains all the resources such as a pods, services, persistentvolumeclaims. But this doesn’t not work that way. Consider rewording or adding some information about the meaning, maybe as a warning block or as a note block.
> 2\. `quota for the total number of certain resources` and `generic object count quota` means the same, so there could be two syntaxes for the same object, for example `count/pods` and `pods`. I found the only difference — you cannot set any quota in `count/`-less syntax except what mentioned in the table. The problem is the wording — it looks like you can specify something different using different syntaxes, but in fact it's the same things with some limitations for `count/`-less syntax. Consider rewording to …
> clarification for ResourceQuota concept

- content/en/docs/tasks/configure-pod-container/resize-container-resources.md
Mentions the InPlacePodVerticalScaling feature gate in the Pod resource specification example. Fixes #40776, #41365, #45079.
> Add feature gate to pod vertical resource scaling example

- content/en/docs/concepts/workloads/pods/_index.md
Update/clarify the `spec.os.name` description under the Pod OS section in workloads/pods. Fixes #38843
> Update Pod OS description spec.os.name

- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/en/includes/task-tutorial-prereqs-node-upgrade.md
Add need to obtain node shell access before node upgrade cluster task. Fixes #45539
> Add shell access prereq to node upgrade cluster task

- content/en/docs/reference/labels-annotations-taints/_index.md
This PR is a follow-up to https://github.com/kubernetes/website/pull/44898 and updates the  last-change-trigger-time annotation to better adhere to the style guide, improves grammar of a sentence, and updates the example to be more accurate
> Updates details for last-change-trigger-time annotation

- data/releases/eol.yaml
- data/releases/schedule.yaml
The merge of https://github.com/kubernetes/release/pull/3583 introduced a documentation string to both files mentioning how to update them. We now sync the changes to match the output of the latest schedule-builder tool revision.
/cc @kubernetes/release-engineering
> Add doc string on how to update `{eol,schedule}.yaml`

- content/en/blog/_posts/2024-02-21-prevent-unauthorized-volume-mode-conversion-ga.md
- content/en/blog/_posts/2024-04-22-userns-beta/index.md
- content/en/blog/_posts/2024-04-23-recursive-read-only-mounts.md
- content/en/blog/_posts/2024-04-24-validating-admission-policy-ga/index.md
- content/en/blog/_posts/2024-04-25-structured-authentication-configuration-beta.md
- content/en/blog/_posts/2024-04-26-structured-authz-beta.md
Split out from PR https://github.com/kubernetes/website/pull/45957
This PR extends the changes made in PR https://github.com/kubernetes/website/pull/45865 and implements those changes to all the 2024 blog files as per the recommendation in https://github.com/kubernetes/website/pull/45865#issuecomment-2054036103. The primary change involves relocating author details into the metadata within the front matter.
Useful Link
[Preview Blog Summary Page](https://deploy-preview-45983--kubernetes-io-main-staging.netlify.app/blog)
> Update 2024 blog content files to move author details in front-matter 

- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
- content/zh-cn/docs/concepts/scheduling-eviction/pod-priority-preemption.md
- content/zh-cn/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
> [zh-cn] sync assign-pod-node node-pressure-eviction pod-priority-preemption pod-scheduling-readiness

- content/en/blog/_posts/2024-04-17-kubernetes-1.30.md
In this article, two different formats were used to refer to the version. This PR standardizes the version representation to the format "v1.xx."
> standardizes the version representation in blog

- content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
The word '以便' should be '导致' in the context.
> [zh-cn]Fix syntax error in debug-running-pod.md

- content/en/docs/reference/tools/map-crictl-dockercli.md
Fixes: #41385 
Updates pages: https://kubernetes.io/docs/reference/tools/map-crictl-dockercli/
> fixing deprecation note for map-crictl-dockercli deprecation

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Changes in `content/en/docs/concepts/workloads/pods/pod-lifecycle.md` file in [container-restarts][1] section
- remove redundant "the" in line 153 which was `Repeated crashes: After the the initial crash`, become to `Repeated crashes: After the initial crash`
[1]: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-restarts
> Remove Redundant 'the' word in pod-lifecycle.md

- content/en/docs/concepts/security/security-checklist.md
- content/en/docs/reference/access-authn-authz/abac.md
- content/en/docs/reference/access-authn-authz/admission-controllers.md
- content/en/docs/reference/access-authn-authz/authorization.md
- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
- content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md
- content/en/docs/reference/access-authn-authz/node.md
- content/en/docs/reference/access-authn-authz/rbac.md
- content/en/docs/reference/access-authn-authz/webhook.md
Revise https://kubernetes.io/docs/reference/access-authn-authz/authorization/ to explain the topic more clearly ([preview](https://deploy-preview-45195--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/authorization/)):
- merge two duplicate places that listed authorization modes / modules
- write headings appropriate for a guide page (not a task)
- match typical Kubernetes docs style; for example, write our internal API verbs (like **create**) in bold
- revise heading structure
/sig auth security
> Revise authorization topic

- OWNERS_ALIASES
Cleaning up post-1.30 release.
Removes myself and @katcosgrove from sig-docs-website-owners in OWNERS_ALIASES
/cc @kubernetes/sig-docs-leads
> Remove 1.30 leads from sig-docs-website-owners

- content/en/docs/reference/instrumentation/metrics.md
This updates the metrics documentation based on the generated metrics for the v1.30.0 release.
For future reference, the instructions for performing this update can be found here: https://kubernetes.io/docs/contribute/generate-ref-docs/metrics-reference/
Closes: #45998
> Update documented metrics for v1.30

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Small fix for adding a missing check-required-ports anchor to the documentation in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
> Add missing check-required-ports anchor

- content/en/docs/concepts/workloads/controllers/job.md
Seems a typo here, this PR changed `.spec.succeessPolicy.rules` to `.spec.successPolicy.rules`
> Fix typo in 'Jobs' concept page

- content/zh-cn/docs/reference/tools/map-crictl-dockercli.md
The file `content/en/docs/reference/tools/map-crictl-dockercli.md` has been updated in this PR (https://github.com/kubernetes/website/pull/41407) ,so we will synchronize the localization.
> [zh]Update mapping table for crictl and docker CLI commands

- content/hi/training/_index.html
Updated [hi] Invalid Link of Kubernetes Training Partners in training page. #46018
> [hi] Update reference to CNCF landscape (v2) in 'Training' page

- content/zh-cn/docs/tasks/administer-cluster/decrypt-data.md
- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/zh-cn/docs/tasks/administer-cluster/memory-manager.md
- content/zh-cn/docs/tasks/administer-cluster/switch-to-evented-pleg.md
- content/zh-cn/includes/task-tutorial-prereqs-node-upgrade.md
- content/zh-cn/includes/task-tutorial-prereqs.md
- Update `EncryptionConfiguration configuration API (v1)` link
- Add `task-tutorial-prereqs-node-upgrade.md` translate & replace
- `feature-state` replace `feature_gate_name` with `state` & `for_k8s_version`
> [zh-cn] minor update task/administer-cluster

- content/zh-cn/docs/concepts/services-networking/ingress.md
> [zh] Fix link

- content/ar/case-studies/_index.html
This PR adds the minimal translation related to the file case-studies/_index.md and splitting the old https://github.com/kubernetes/website/pull/44902 to smaller PRs
Part of https://github.com/kubernetes/website/issues/37546 and https://github.com/kubernetes/website/issues/44682
> [ar] Translate case-studies index to arabic

- content/zh-cn/community/static/cncf-code-of-conduct.md
Typo fix related to https://github.com/kubernetes/website/pull/46038#issuecomment-2081485114
> [zh] Typo fix: cncf-code-of-conduct.md

- content/zh-cn/docs/reference/tools/map-crictl-dockercli.md
The file `content/en/docs/reference/tools/map-crictl-dockercli.md` has been updated in this PR (https://github.com/kubernetes/website/pull/46068) ,so we will synchronize the localization.
> [zh]Update link to Dockershim-FAQ in map-crictl-dockercli.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-service-lb-status-on-non-lb.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-managed-by.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-success-policy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-dynamice-resources.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/name-generation-retries.md
Add zh text to 5 feature-gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-service-lb-status-on-non-lb.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-managed-by.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-success-policy.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-dynamice-resources.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/name-generation-retries.md
```
> [zh] Add 5 docs in command-line-tools-reference/feature-gates

- content/en/docs/concepts/services-networking/service.md
Fixed typo in Service page from trafic-distribution to not traffic-distribution.
Closes https://github.com/kubernetes/website/issues/46073
> Fix typo in Service page

- content/zh-cn/docs/tasks/administer-cluster/kubelet-config-file.md
Sync with en #46064 
```
```
See [preview](https://deploy-preview-46082--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/kubelet-config-file/#%E6%9F%A5%E7%9C%8B-kubelet-%E9%85%8D%E7%BD%AE) please.
> Wow, our website building speed is amazing! I received a success message in just 2 minutes.
> [zh] Sync administer-cluster/kubelet-config-file.md

- OWNERS_ALIASES
ref. https://github.com/kubernetes/org/pull/4922
- Add @Okabe-Junya to `sig-docs-ja-reviewer`
FYI:
- merged PRs (k/website): https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3AOkabe-Junya+archived%3Afalse+repo%3Akubernetes%2Fwebsite (20+)
- reviewed PRs (k/website): https://github.com/pulls?q=is%3Apr+reviewed-by%3AOkabe-Junya+repo%3Akubernetes%2Fwebsite+ (35+)
This pr is sponsored by @nasa9084 @bells17
> Add Okabe-Junya to `sig-docs-ja-reviewer`

- content/en/community/code-of-conduct.md
- content/en/community/static/cncf-code-of-conduct.md
There seems a typo here, `ocurring` should be `occurring` 🤔
> Sync Community Code of Conduct from CNCF upstream

- content/en/blog/_posts/2024-05-01-cri-streaming-explained.md
A blog post about explaining the Container Runtime Interface streaming server.
/cc @haircommander @mrunalp @kwilczynski @sohankunkerkar @kannon92  
**Preview: https://deploy-preview-45821--kubernetes-io-main-staging.netlify.app/blog/2024/05/01/cri-streaming-explained**
Follow-up: https://github.com/kubernetes/website/pull/45821#discussion_r1562313003
> Add blog post about: CRI streaming explained

- content/en/docs/concepts/security/linux-kernel-security-constraints.md
- content/en/docs/concepts/workloads/pods/_index.md
- content/en/docs/tutorials/security/apparmor.md
Fixes #39601 
Add a new concept page that documents and compares the available kernel-level security constraints for Pods and containers
* Where content was pulled from different pages, I've added comments. That content is verbatim, no grammar or style changes. 
* There are several outstanding TODOs that block merging
* The [Security Checklist page ](https://kubernetes.io/docs/concepts/security/security-checklist/#enabling-seccomp) has smaller conceptual sections about seccomp apparmor and SELinux that we can remove, making the checklist more streamlined. Haven't done that yet
* I used an HTML table because I wanted to wrap the lines
* Review the content for accuracy
* Address outstanding TODOs
* Identify any other pages in the doc set that need to link to this page
/sig docs
/sig …
> Add new page for kernel-level constraints

- content/zh-cn/docs/reference/access-authn-authz/abac.md
- content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
- content/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz.md
- content/zh-cn/docs/reference/access-authn-authz/node.md
- content/zh-cn/docs/reference/access-authn-authz/rbac.md
- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
- content/zh-cn/docs/reference/access-authn-authz/webhook.md
- `docs/reference/access-authn-authz/abac.md`
- `docs/reference/access-authn-authz/certificate-signing-requests.md`
- `docs/reference/access-authn-authz/kubelet-authn-authz.md`
- `docs/reference/access-authn-authz/node.md`
- `docs/reference/access-authn-authz/rbac.md`
- `docs/reference/access-authn-authz/validating-admission-policy.md`
- `docs/reference/access-authn-authz/webhook.md`
> [zh-cn] minor sync docs/reference/access-authn-authz

- content/en/blog/_posts/2024-05-01-cri-streaming-explained.md
Fixing the syntax to let it render again.
Refers to https://github.com/kubernetes/website/pull/45821
Preview: https://deploy-preview-46121--kubernetes-io-main-staging.netlify.app/blog/2024/05/01/cri-streaming-explained/
> Fix mermaid syntax in CRI blog post

- content/en/docs/reference/kubectl/introduction.md
Inspired by https://github.com/kubernetes/website/pull/46056#discussion_r1584032947, it is suggested to make changes to the text by converting the first letter of certain terms from uppercase to lowercase, or to a more natural way.
Thanks @tengqm
> Use lowercases for some terms in kubectl/introduction.md

- content/en/docs/concepts/security/_index.md
Changed "ValidatingAdmisisonPolicy" to "ValidatingAdmissionPolicy"
> Fix typo in security documentation

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_ca.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_ca.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
> [zh-cn] sync kubeadm_init_phase_certs_ca kubeadm_init_phase_control-plane_all

- content/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
- content/zh-cn/examples/customresourcedefinition/shirt-resource-definition.yaml
Sync with new en paras:
```
content/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
```
See [preview](https://deploy-preview-45990--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources/#custom-resource-field-selectors).
> [zh] Add trans to api-extension/custom-resources.md

- content/en/docs/tasks/administer-cluster/encrypt-data.md
This is split out from PR https://github.com/kubernetes/website/pull/33285 in order to make a review more likely. See that PR and its previews to show the changes in a wider context.
/language en
> Revise callouts in encryption-at-rest task page

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/recursive-read-only-mounts.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/relaxed-environment-variable-validation.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/retroactive-default-storage-class.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/root-ca-config-map.md
Add zh text to 4 new feature gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/recursive-read-only-mounts.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/relaxed-environment-variable-validation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/retroactive-default-storage-class.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/root-ca-config-map.md
```
> [zh] Add 4 new feature gates: r*.md

- assets/scss/_custom.scss
Currently, when selecting the search bar, the border size changes, which disrupts the position of other elements in the UI.
I replaced the selected `border` style with an `outline` that will be displayed in addition to the regular border, when selected.
Here's a demonstration, current vs. fixed:
https://github.com/kubernetes/website/assets/32395585/628a293c-c19d-4f8b-a846-7b39ca843d3c
> Fixed selected search bar border styling

- assets/scss/_base.scss
- layouts/partials/feedback.html
Hi!
I noticed that the "Feedback" buttons on documentation pages use the default bootstrap styling. For [example](https://kubernetes.io/docs/concepts/overview/):
This PR swaps the `.btn` class of the buttons with the `.button` class, as used by other buttons on the site. The result is a more coherent UI:
The `::hover` pseudoelement was apparently not copied over from [the `main.button` class](https://github.com/kubernetes/website/blob/3e3764debd156cba421aecf551e239c9d5cfb1a9/assets/scss/_base.scss#L82-L84), which this PR catches up with.
> Fix documentation feedback button style

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/en/examples/examples_test.go
- content/en/examples/pods/pod-with-affinity-preferred-weight.yaml
This [https://github.com/kubernetes/website/blob/main/content/en/examples/pods/pod-with-affinity-anti-affinity.yaml](https://github.com/kubernetes/website/blob/main/content/en/examples/pods/pod-with-affinity-anti-affinity.yaml) example stresses  preferred affinity weights and not the antiAffinity.  The file name and pod name may make some confusing.
> Rename example pod-with-affinity-anti-affinity.yaml

- content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md
This pull request moves explanation of the `suffix` parameter from the end of the list to the second position. This places the `suffix` explanation directly after the definitions of `target` and `patchtype`, which are directly related to using suffixes for ordering patches.
> Customizing with patches - Move suffix parameter to the second position

- content/en/blog/_posts/2021-09-03-api-server-tracing.md
This PR adds some details about working and non working etcd versions to the api-server-tracing blog post.
Even though the post is older, it is still very useful. :smiley: 
cc @dashpole
> Add notes on etcd tracing problems to api-server-tracing blog post

- content/zh-cn/docs/tasks/inject-data-application/define-command-argument-container.md
The file `content/en/docs/tasks/inject-data-application/define-command-argument-container.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45900) ,so we will synchronize the localization.
> [zh] update define-command-argument-container.md

- content/ar/docs/home/_index.md
This PR adds the minimal translation related to the file /home/_index.md and splitting the old [PR](https://github.com/kubernetes/website/pull/44902) to smaller 
Part of https://github.com/kubernetes/website/issues/44682
> [ar] Translate home index to arabic

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-resource-field-selectors.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/runtime-class-in-image-cri-api.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/selinux-mount.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-traffic-distribution.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/storage-version-migrator.md
Add zh text to five new gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-resource-field-selectors.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/runtime-class-in-image-cri-api.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/selinux-mount.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-traffic-distribution.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/storage-version-migrator.md
```
> [zh] Add 5 new feature gates

- content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md
```
content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md
```
See [preview](https://deploy-preview-46211--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler/) please.
> [zh] Sync command-line-tools-reference/kube-scheduler.md

- content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md
```
content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md
```
See [preview](https://deploy-preview-46209--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager/) please.
> [zh] Sync command-line-tools-reference/kube-controller-manager.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/consistent-http-get-handlers.md
This feature is GA and its feature gates will be removed in v1.31:
https://github.com/kubernetes/kubernetes/pull/124463
Following instructions in:
https://kubernetes.io/docs/contribute/new-content/new-features/#ready-for-review-feature-gates
Preview: https://deploy-preview-46214--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates-removed/
> Remove ConsistentHTTPGetHandlers feature-gate

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_wait-control-plane.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
Sync 3 files with en text:
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_show-join-command.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_wait-control-plane.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
```
See [preview](https://deploy-preview-46203--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node/) please.
> [zh] Sync 3 reference files in setup-tools/kubeadm/generated

- content/zh-cn/blog/_posts/2024-04-23-recursive-read-only-mounts.md
fix: https://github.com/kubernetes/website/issues/46220
add `Linux kernel: v5.12 or later` in `Feature availability` section
> [zh] fix miss `Linux kernel: v5.12` in `2024-04-23-recursive-read-only-mounts.md`

- content/en/docs/concepts/workloads/pods/user-namespaces.md
- content/en/docs/tasks/configure-pod-container/user-namespaces.md
Backport of the fixes already merged in main in https://github.com/kubernetes/website/pull/45178.
> [release-1.29]: Fix userns example and add OCI runtime requirements

- content/en/docs/concepts/workloads/pods/user-namespaces.md
- content/en/docs/tasks/configure-pod-container/user-namespaces.md
Backport of the fixes already merged in main in https://github.com/kubernetes/website/pull/45178.
> [release-1.27]: Fix userns example and add OCI runtime requirements

- content/en/docs/tasks/access-application-cluster/ingress-minikube.md
- content/en/examples/service/networking/example-ingress.yaml
Fixes #46118
This PR changes the host used in the Ingress tutorial from `hello-world.info` to `hello-world.example`.
This is needed in order to mitigate a security risk associated with the `hello-world.info` URL which is found to be associated with a suspicious webpage.
> Change the host for the ingress tutorial, to mitigate a security risk.

- content/ja/docs/contribute/localization.md
- revise `content/ja/docs/contribute/localization.md`
- "Node" に関する箇所の微修正
ref. https://github.com/kubernetes/website/pull/46076#discussion_r1591857109
> あと別件かと思うのですが
> 
> > ただし、ノード(Node)に関しては明確にKubernetesとしてのNodeリソース(例: kind: Nodeやkubectl get nodes)を指していないのであれば、「ノード」と表記してください。
> 
> という現在の表現ですが、`kind: Node`　くらいNodeリソース感が無いと"ノード"にすべきなのかな？という印象を受けるので基本下記のようにしてみても良いかもです。 (といっても微修正ですが)
> 
> > ただし、ノード(Node)に関してはKubernetesとしてのNodeリソース(例: kind: Nodeやkubectl get nodes、Nodeコントローラーなど)を指していないのであれば、「ノード」と表記してください。
/cc @bells17 
/assign @nasa9084 
cc @kubernetes/sig-docs-ja-reviews
> [ja] revise `content/ja/docs/contribute/localization.md`

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_check-expiration.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-ca.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_preflight.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_check-expiration.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-ca.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_ph …
```
> [zh] Sync 9 reference files in setup-tools/kubeadm

- README-ja.md
- Sync up README.md (ja) to en
- Update some translations
- Add some notes for Japanese l10n contributor
README preview: https://github.com/kubernetes/website/blob/ff81a892bd70554b63682974511f906340358c4c/README-ja.md
> [ja] Sync up README.md (ja) to en

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/service-nodeport-static-subrange.md
This PR remove GA feature gate ServiceNodePortStaticSubrange
code remove in k/k: https://github.com/kubernetes/kubernetes/pull/124738
KEP: https://github.com/kubernetes/enhancements/issues/3668
> Remove GA ServiceNodePortStaticSubrange feature gate

- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
- Removed `.md` typo formatting  to render the webpage.
- Proposed solution to issue https://github.com/kubernetes/website/issues/46088
> Fix broken link in "Set Kubelet Parameters Via A Configuration File" page

- content/ru/docs/reference/issues-security/issues.md
Similarly to #46281, we need to fix the https://kubernetes.io/cve/ and https://kubernetes.io/cves/ aliases. This issue originates from #43368.
> Fix the incorrect /cve alias

- static/_redirects
1. fixes  https://github.com/kubernetes/website/pull/45009#discussion_r1595758730
2. redirect rule of /bn/docs/setup/learning-environment/
> [bn] Static/ redirects - minor fix

- content/hi/docs/home/_index.md
This PR fixes the issue #45456  where the Hindi localization home page had an incorrect title. 
Changed the title from **कुबेरनेट्स रिलीज नोट्स** to **कुबेरनेट्स डाउनलोड करें** to match the section's content about downloading Kubernetes.
Why This Change:
The old title suggested it was about release notes, which was misleading. The update ensures the title reflects the content accurately, making it easier for users to find the download information.
> [hi] Fix title mismatch in docs home for "Kubernetes Download"

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/concepts/storage/volumes.md
https://github.com/kubernetes/kubernetes/pull/124546 removed CephRBD volume plugin and its csi migration support 
preview: https://deploy-preview-46304--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/volumes/#rbd-removed
> update rbd volume

- content/en/docs/reference/access-authn-authz/admission-controllers.md
https://github.com/kubernetes/kubernetes/pull/124505 removed admission plugin PersistentVolumeLabel.
> remove PersistentVolumeLabel admission plugin

- content/de/docs/reference/glossary/controller.md
This commit updates the definition of controllers in Kubernetes to enhance clarity and conciseness. The changes include:
- Simplified the description by removing redundant phrases and improving the flow.
- Corrected grammatical structure for better readability.
Changes made:
- From: "In Kubernetes sind Controller Kontrollschleifen, die den Zustand des Clusters beobachten, und dann Änderungen ausführen oder anfragen, wenn benötigt."
- To: "In Kubernetes sind Controller Kontrollschleifen, die den Zustand des Clusters überwachen und bei Bedarf Änderungen ausführen oder anfordern."
- From: "Jeder Controller versucht den aktuellen Clusterzustand in Richtung des Wunschzustands zu bewegen."
- To: "Jeder Controller versucht, den aktuellen Clusterzustand in Richtung des Wunschzustands zu bewegen." …
> [de] Update controller definition for clarity and conciseness

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
> [zh-cn]sync kubeadm_config_images_list kubeadm_config_images_pull

- content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Per https://github.com/kubernetes/website/issues/44765 grabbed the https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ and translated that to pt-br taking into account the already existing page.
> [pt-br] Update docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

- content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive-gone.html
- content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive-gone.html
- content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive-gone.html
- content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive-gone.html
- content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive-gone.html
- content/en/docs/tutorials/kubernetes-basics/update/update-interactive-gone.html
- static/_redirects
Katacoda has shut down for good, and we have not added a local / in-project alternative playground in the time since. Serving a 404 helps cement that these pages are no longer part of the site.
[**Current**](https://k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/) vs [**Preview**](https://deploy-preview-46323--kubernetes-io-main-staging.netlify.app/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/)
---
You can see that Netlify now serves a 404 response:
```console
$ curl -I https://deploy-preview-46323--kubernetes-io-main-staging.netlify.app/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
HTTP/2 404
accept-ranges: bytes
age: 5
cache-control: public,max-age=0,must-revalidate
cache-status: "Netlify Edge"; hit
content-type: …
```
> Turn interactive tutorials into custom 404 pages

- content/en/docs/reference/access-authn-authz/authorization.md
Headings weren't rendered as there was no newline between the sentence and the headline
**Before the fix**
**After the fix (Local markdown render)**
> Fixing heading in authorization.md

- content/fr/docs/home/supported-doc-versions.md
- data/i18n/fr/fr.toml
Align https://kubernetes.io/fr/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/
[Preview](https://deploy-preview-46344--kubernetes-io-main-staging.netlify.app/fr/docs/home/supported-doc-versions/) of the updated page
/language fr
> [fr] Update list of versions to match English

- content/bn/docs/tasks/tools/install-kubectl-linux.md
- content/bn/docs/tasks/tools/install-kubectl-macos.md
- content/bn/docs/tasks/tools/install-kubectl-windows.md
Three existing pages are broken as the links don't expand the current patch release correctly.
Fix that (use `skew` shortcode instead of deprecated `param` shortcode).
To see the problem, search in page for `release//bin`; there should be a version number between the two `/` characters.
Current | Preview
------------|------------
[Linux](https://k8s.io/bn/docs/tasks/tools/install-kubectl-linux/) (broken) | [Linux (preview)](https://deploy-preview-46346--kubernetes-io-main-staging.netlify.app/bn/docs/tasks/tools/install-kubectl-linux/)
[macOS](https://k8s.io/bn/docs/tasks/tools/install-kubectl-macos/) (broken) | [macOS (preview)](https://deploy-preview-46346--kubernetes-io-main-staging.netlify.app/bn/docs/tasks/tools/install-kubectl-macos/) …
> [bn] Fix task pages about installing kubectl

- content/en/docs/concepts/workloads/pods/disruptions.md
Just noticed a superfluous white space just before a closing parenthesis:
> fix superfluous white space

- assets/scss/_custom.scss
- content/en/docs/concepts/overview/components.md
- layouts/partials/head.html
- layouts/shortcodes/figure.html
- static/js/zoom.js
Implemented the functionality to enable click-to-zoom for images on the website. This feature enhances user experience by allowing them to view images in a full-screen overlay upon clicking. Core change as part of this pull request introduces a new parameter (`clicktozoom`) in the `figure` shortcode to selectively activate the zoom functionality.
Fixes https://github.com/kubernetes/website/issues/38051
- **custom.scss**: Added CSS rules for full-screen display of `<figure>` elements.
- **js/zoom.js**: Implemented the script to handle image display in an overlay upon click interaction.
- **figure.html**:  The original source code of Docsy's `figure` shortcode is included to create an override with addition of a new parameter called 'clicktozoom', allowing for the selective activation of …
> Implement click-to-zoom option for images

- assets/scss/_custom.scss
- layouts/shortcodes/caution.html
- layouts/shortcodes/note.html
- layouts/shortcodes/warning.html
Adopt callout (notices) that match the Docsy theme we use (see issues https://github.com/kubernetes/website/issues/44564 and https://github.com/kubernetes/website/issues/41171).
Before | After
----------|-------
[Authorization configuration and reloads](http://k8s.io/docs/reference/access-authn-authz/authorization/#authorization-configuration-and-reloads) | [Authorization configuration and reloads](https://deploy-preview-46232--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/authorization/#authorization-configuration-and-reloads)
[Least-privilege access to Secrets](https://k8s.io/docs/concepts/configuration/secret/#configure-least-privilege-access-to-secrets) | [Least-privilege access to …
> Use Docsy-style callouts

- content/en/docs/tasks/configure-pod-container/user-namespaces.md
Backport of the only fix that applies to 1.26, the example typo, already merged in main in https://github.com/kubernetes/website/pull/45178.
Find below the commit msg
---
We were showing 4294967295 for the uid_map file, that is how it looks on the host (not the container). Let's fix that.
While we are there, let's improve the explanation too.
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>
(cherry picked from commit b327397fc61d5c281fdca1733915127057f824c4)
> [release-1.26]: Fix userns example

- content/es/docs/home/supported-doc-versions.md
- data/i18n/es/es.toml
Align https://kubernetes.io/es/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/
[Preview of the updated page.](https://deploy-preview-46348--kubernetes-io-main-staging.netlify.app/es/docs/home/supported-doc-versions/)
/language es
> [es] Update list of versions to match English 

- content/ja/docs/home/supported-doc-versions.md
- data/i18n/ja/ja.toml
Align https://kubernetes.io/ja/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/
[Preview of the updated page.](https://deploy-preview-46352--kubernetes-io-main-staging.netlify.app/ja/docs/home/supported-doc-versions/)
/language ja
> [ja] Update list of versions to match English 

- content/zh-cn/docs/concepts/services-networking/gateway.md
The original ingress migration guide url in zh-CN documentation is incorrect, I've updated it.
> [zh] Fix incorrect ingress migration guide url.

- content/ar/_common-resources/index.md
- content/ar/_index.html
This PR adds the minimal translation related to the file _index.md and splitting the old https://github.com/kubernetes/website/pull/44902 to smaller PRs
Part of https://github.com/kubernetes/website/issues/37546 and https://github.com/kubernetes/website/issues/44682
> [ar] Translate ar index to arabic

- content/en/docs/concepts/extend-kubernetes/operator.md
KUDO was not updated for three years. The docs should not mention it.
> Update operator.md: Removed KUDO

- content/en/blog/_posts/2024-04-28-contribute-as-sig-docs-reviewer.md
This blog post aims to attract open-source contributors with Git/GitHub knowledge to become Kubernetes SIG-Docs reviewers.
cc/ @sftim
> Contribute as sig-docs reviewer blog post

- data/i18n/ru/ru.toml
The `i18n/ru.toml` file lacked many new entries introduced into the original (English) file. Many of them are related to `feature_gate_*`, `layout_docs_glossary_*`, and `release_*`. This PR syncs the translation, making it up-to-date.
> [ru] Sync ru.toml with the actual English file

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/zh-cn/docs/concepts/workloads/pods/disruptions.md
> [zh-cn] sync device-plugins.md disruptions.md

- content/en/docs/concepts/containers/images.md
This PR improves concepts/containers/image page and tries to fix the following issues:
- #40664
- #39870
It related to #4502 (umbrella issue about page improvements)
> feat: Update image name documentation

- layouts/shortcodes/param.html
[AIUI] we prefer not to use the `param` shortcode (we switched to a new approach in PR https://github.com/kubernetes/website/pull/40692)
Change that shortcode to warn if it's used other than for `version` (which we still support, although I recommend using the `skew` shortcode in its place).
~As part of this:~
- ~switch Bengali to the new approach~
- ~fix a broken link in a blog article~
- ~change a couple of pages to use the `skew` shortcode~
> Warn on new use of param shortcode

- content/en/docs/tasks/administer-cluster/kms-provider.md
Updated example configuration to specify separate unix domain socket paths. Two KMS providers will use separate socket files.
cc @enj
> Fix example KMS configuration documentation

- content/en/blog/_posts/2024-05-09-gateway-api-v1.1/index.md
- Add `yaml` to the code snippet, to show colors
- Put link text and its URL on a same line
- Other minor changes about bullets and line wrapping
> Make the gateway-api blog prettier

- OWNERS_ALIASES
I am nominating @sajibAdhi as a reviewer for the Kubernetes Bengali localization. He has been an active contributor from the very beginning and has consistently demonstrated a commitment to maintaining high standards of quality in his contributions, making him well-suited for the role of a reviewer.
As one of the SIG-Docs-BN localization maintainers, I'm looking forward to continuing our collaboration with @sajibAdhi.
Requesting a review from other SIG-Docs-BN localization maintainers
@mitul3737 
@Imtiaz1234 
@rajibmitra 
And SIG-Docs localization subproject leads.
@seokho-son 
@a-mccarthy
> Add sajibAdhi as a reviewer for Bengali localization

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
kubeadm: update docs for removed UpgradeAddonsBeforeControlPlane feature gate
Ref: https://github.com/kubernetes/kubernetes/pull/124715
> kubeadm: update docs for removed UpgradeAddonsBeforeControlPlane feature gate

- content/zh-cn/docs/concepts/extend-kubernetes/api-extension/_index.md
- content/zh-cn/docs/concepts/policy/resource-quotas.md
- Sync docs:
- content/zh-cn/docs/concepts/extend-kubernetes/api-extension/_index.md
- content/zh-cn/docs/concepts/policy/resource-quotas.md
- Regarding the translation of `namespaces` in this article, there are more than 50 translations of "命名空间" and more than 10 translations of "名字空间". To avoid misunderstandings, they have been adjusted to "命名空间".
> [zh-cn]sync api-extension/_index.md resource-quotas.md

- content/en/docs/tutorials/services/connect-applications-service.md
Source: [page](https://kubernetes.io/docs/tutorials/services/connect-applications-service/)
The top one is old, the bottom one is new.
> EndpointSlice that is connected to the Service using **_a labels_**.
> EndpointSlice that is connected to the Service using **_labels_**. 
This pull request removes ' a'. That's all.
> fix minor typo in connect-applications-service.md

- content/bn/OWNERS
- Add `area/localization` label in content/bn/OWNERS
- other languages have `area/localization` label (ref. #42206 )
```console
$ pwd
/path/to/website
$ grep -RIn "area/localization" ./content/**/OWNERS
./content/bn/OWNERS:13:- area/localization
./content/de/OWNERS:14:- area/localization
./content/es/OWNERS:14:- area/localization
./content/fr/OWNERS:14:- area/localization
./content/hi/OWNERS:14:- area/localization
./content/id/OWNERS:14:- area/localization
./content/it/OWNERS:12:- area/localization
./content/ja/OWNERS:14:- area/localization
./content/ko/OWNERS:14:- area/localization
./content/pl/OWNERS:14:- area/localization
./content/pt-br/OWNERS:12:- area/localization
./content/ru/OWNERS:14:- area/localization
./content/uk/OWNERS:14:- area/localization
./content/vi/OWNERS:14:- …
```
> Add area/localization label in content/bn/OWNERS

- content/en/blog/_posts/2024-05-13-cloud-provider-migration.md
Add blog about cloud provider removal effort (KEP-2395).
> add blog about cloud provider migration 

- content/en/docs/tutorials/hello-minikube.md
When I ran `kubectl get deployments`, it showed no available nodes. So I thought I did something wrong. Eventually I ran it again and it matched the expected output. So, I would like to add a helpful hint to the documentation.
> Added small helpful tip to hello-minikube.md

- content/ja/docs/reference/_index.md
- fix "ライブラリー" to "ライブラリ" in `content/ja/docs/reference/_index.md`
ref. https://kubernetes.io/ja/docs/contribute/localization/#long-vowel
> - -ear、-eer、-re、-ty、-dy、-ryで終わる単語は長音を付与しない
>     - 例: 「クリア」「エンジニア」「アーキテクチャ」「セキュリティ」「スタディ」「ディレクトリ」
/assign nasa9084
> [ja] minor fix in content/ja/docs/reference/_index.md

- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
Fixes https://github.com/kubernetes/kubernetes/issues/124796
The current behavior of the drop-in directory merging logic is not properly documented. Ideally, Validation is performed on each drop-in configuration file before merging it into the final configuration structure stored internally by the kubelet.
> [main] Fix drop-in dir logic explaination

- content/en/docs/tasks/tools/install-kubectl-linux.md
On a bare-metal Debian 12 clean install, gnupg is needed to succesfully complete the proposed steps.
Maybe it should be noted with prose rather than simply adding the package to the install list, but I never contributed before and would like to keep minimum noise posible
> kubectl debian install guide does not mention gnupg at all

- content/en/docs/reference/scheduling/config.md
The note that said, "Pod's scheduling events have .spec.schedulerName as the ReportingController", is no longer true. I do not find the `spec.schedulerName` set to `ReportingController`.
```yaml
$ k get pod nginx -o yaml
apiVersion: v1
kind: Pod
metadata:
annotations:
cni.projectcalico.org/containerID: bec575f5e565edc9b9d97deb83cb891036232c559d0acb9759a7092bb2537942
cni.projectcalico.org/podIP: 10.244.49.103/32
cni.projectcalico.org/podIPs: 10.244.49.103/32
creationTimestamp: "2024-05-05T08:13:03Z"
labels:
run: nginx
name: nginx
namespace: default
resourceVersion: "505064"
uid: 1df8c6cc-8aed-4c99-8fe9-7f119d96ab1e
spec:
containers:
- image: nginx
imagePullPolicy: Always
name: nginx
resources: {}
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
volumeMounts:
- …
```
> Update note around spec.schedulerName being ReportingController

- content/pt-br/blog/_index.md
- content/pt-br/case-studies/_index.md
- content/pt-br/community/_index.html
- content/pt-br/docs/home/_index.md
- content/pt-br/docs/tutorials/hello-minikube.md
- content/pt-br/partners/_index.html
Update navbar items in the Brazilian Portuguese localization so layout renders correctly using vanilla Docsy.
Changes in the same vein as #45869 and #46192 in order to allow #46409 to move forward.
/cc @edsoncelio @mboukhalfa @sftim
> [pt-br] Update navbar items for vanilla Docsy

- content/en/docs/reference/command-line-tools-reference/feature-gates/api-self-subject-review.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/csi-migration-azure-file.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/expanded-dns-config.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/experimental-host-user-namespace-defaulting.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/ip-tables-ownership-cleanup.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-get-allocatable.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-tracking.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/minimize-ip-tables-restore.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/proxy-terminating-endpoints.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/security-context-deny.md
The feature gates data are not accurate. This PR fixes those that have been dropped in v1.30.
> Fix feature gates that have been been removed in 1.30

- content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
Under "Scaling an application" [(here)](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/) there is conflicting guidance with rparagraph instructing to delete the "NodePort" service, because this sections expects a "Loadbalancer" service to be active. Adn the immediately the next Note instructs to re-create the "NodePort" service after the "Loadbalancer" service was created.
Resolves https://github.com/kubernetes/website/issues/46429
> Fix guidance regarding Service creation in tutorial

- content/en/docs/concepts/services-networking/service.md
Update known `appProtocols` to match the KEP
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/3726-standard-application-protocols/README.md?plain=1#L179
> Add missing service application protocol definitions

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Update https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
Make [Container restart policy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) fit within the topic of how Pods handle container problems; it belongs there.
> Tweak heading level in Pod lifecycle concept page

- content/ja/docs/concepts/scheduling-eviction/taint-and-toleration.md
- Fix the term "Node/node" to "ノード" in `/docs/concepts/scheduling-eviction/taint-and-toleration.md`
https://kubernetes.io/ja/docs/contribute/localization/#terminology
> ただし、ノード(Node)に関しては明確にKubernetesとしてのNodeリソース(例: kind: Nodeやkubectl get nodes)を指していないのであれば、「ノード」と表記してください。
> [ja] update the term "Node" in `/docs/concepts/scheduling-eviction/taint-and-toleration.md`

- content/ja/docs/concepts/scheduling-eviction/assign-pod-node.md
- Fix the term "Node/node" to "ノード" in `/docs/concepts/scheduling-eviction/assign-pod-node.md`
https://kubernetes.io/ja/docs/contribute/localization/#terminology
> ただし、ノード(Node)に関しては明確にKubernetesとしてのNodeリソース(例: kind: Nodeやkubectl get nodes)を指していないのであれば、「ノード」と表記してください。
> [ja] update the term "Node" in `/docs/concepts/scheduling-eviction/assign-pod-node.md`

- content/ja/docs/concepts/scheduling-eviction/_index.md
- Fix the term "Node/node" to "ノード" in `/docs/concepts/scheduling-eviction/_index.md`
https://kubernetes.io/ja/docs/contribute/localization/#terminology
> ただし、ノード(Node)に関しては明確にKubernetesとしてのNodeリソース(例: kind: Nodeやkubectl get nodes)を指していないのであれば、「ノード」と表記してください。
> [ja] update the term "Node" in /docs/concepts/scheduling-eviction/_index.md

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
This PR refers to the page
Kubernetes Documentation > Tasks > Administer a Cluster > Operating etcd clusters for Kubernetes
In the section titled "Restoring an etcd cluster", the commands use the etcdctl utility to restore from an existing snapshot.
Using etcdctl for restoring snapshots is deprecated since etcd version 3.5.x
Usage of this command displays a deprecation warning and suggests to use etcdutl utility instead
This PR is to depict the use of the etcdutl utility for restoring from an existing snapshot.
Before submitting the PR, I have tested the changes on a local Kubernetes cluster for v1.28.0 and I can confirm everything works as expected.
I have kept a reference to the etcdctl command in the 3rd example and I have added a note highlighting the deprecation.
I feel this change …
> Use etcdutl instead of etcdctl for restoring an etcd cluster

- assets/scss/_custom.scss
> Fix cosmetic bug with note shortcode

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> The feature was left in alpha for a few releases, since k8s started planning on a broader feature UserNamespacesSupport, which is what kubeadm should integrate with.
> UserNamespacesSupport graduated to beta in 1.30.
Once it graduates to GA kubeadm can start using it an remove RootlessControlPlane.
https://github.com/kubernetes/kubeadm/issues/2473#issuecomment-2019804814
https://github.com/kubernetes/kubernetes/pull/124997
> kubeadm: move the RootlessControlPlane FG to deprecated

- content/en/docs/reference/command-line-tools-reference/feature-gates/node-swap.md
- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
the NodeSwap feature gate of the kubelet is beta and enabled by default in 1.30.
/cc @pacoxu @SataQiu @dipesh-rawat
> update kubeadm prerequisites

- content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
- content/en/examples/service/load-balancer-example.yaml
This PR fixes https://github.com/kubernetes/website/issues/45961 by updating the tutorial to use Google's newer image: [hello-app](https://us-docker.pkg.dev/google-samples/containers/gke/hello-app)
This fix closely resembles https://github.com/kubernetes/website/pull/46553
[Original](https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/)
[Fix](https://deploy-preview-46568--kubernetes-io-main-staging.netlify.app/docs/tutorials/stateless-application/expose-external-ip-address/)
> Update node-hello image to Google's newer image

- content/de/docs/concepts/architecture/nodes.md
There is a spelling mistake in the German Kubernetes documentation under:
**Node Condition - Beschreibung**
Incorrect version:
Ready - True wenn der Node in einem guten Zustand und bereit ist Pods aufzunehmen, False wenn der Node nicht in einem guten Zustand ist und nicht bereit ist Pods **aufzunehmeb**
Correct version:
Ready - True wenn der Node in einem guten Zustand und bereit ist Pods aufzunehmen, False wenn der Node nicht in einem guten Zustand ist und nicht bereit ist Pods **aufzunehmen**
> [de] Update nodes.md

- content/en/docs/reference/access-authn-authz/authentication.md
- Put the text with same format into a single line
- Remove redundant spaces and add blank lines
- Change some code symbols after backticks
> Clean up access-authn-authz/authentication.md

- content/en/docs/concepts/architecture/garbage-collection.md
Related k/k issue: https://github.com/kubernetes/kubernetes/issues/125194
> It seems that the first thing we need to do is to update the documentation https://kubernetes.io/docs/concepts/architecture/garbage-collection/ (existed since v1.29) to avoid misleading users.
> Fixed kubelet option ImageMaximumGCAge example for garbage-collection page

- content/en/docs/concepts/services-networking/dual-stack.md
This PR clarifies the behavior of the PreferDualStack and RequireDualStack options for the ipFamilyPolicy field in Service API objects.
Fixes #46562
[Before](https://kubernetes.io/docs/concepts/services-networking/dual-stack/)
[After](https://deploy-preview-46587--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/dual-stack/)
> Clarify PreferDualStack and RequireDualStack in dual-stack documentation

- content/en/docs/tutorials/stateful-application/basic-stateful-set.md
- content/en/examples/application/web/web.yaml
This PR fixes discrepancies between the tutorial documentation and the actual output and changes the manifest to suit original scenario.
1. [The documented output at line 115-116](https://github.com/kubernetes/website/blob/ddec959814fff4d4d32bd401c9567c3b62a4d68f/content/en/docs/tutorials/stateful-application/basic-stateful-set.md?plain=1#L115) of `basic-stateful-set.md` shows DESIRED and CURRENT status columns for `kubectl get statefulset web`.
```
NAME      DESIRED   CURRENT   AGE
web       2         1         20s
```
However, the actual output displays READY status instead. This is updated to match reality.
```
NAME   READY   AGE
web    2/2     37s
```
2. The documented container image names [at line 640-642](https://github.com/kubernetes/website/blob/ddec959814fff4d4d32bd401c9567c3b62a …
> Correcting scenario inconsistencies and output checks

- content/en/docs/tasks/administer-cluster/dns-debugging-resolution.md
This changes corrects an aligment in the output of the command `kubectl get pods dnsutils`, in the **Debugging DNS Resolution** page
> Correct alignment in kubectl get pods dnsutils

- content/en/docs/reference/labels-annotations-taints/_index.md
…ernal-load-balancers
Fixes : #46575
> Fix stale docs about LB annotation

- content/en/blog/_posts/2023-12-14-disabling-in-tree-cloud-provider-goes-beta.md
the AWS and OpenStack removal versions were wrong in one part of the blog.
fixes: #46481
> fix wording on 2023-12-14 blogpost

- content/en/docs/tasks/extend-kubernetes/http-proxy-access-api.md
- content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
- content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
- content/en/examples/pods/inject/envars.yaml
- content/en/examples/pods/security/security-context-2.yaml
- content/en/examples/pods/security/security-context-3.yaml
- content/en/examples/pods/security/security-context-4.yaml
- content/en/examples/service/load-balancer-example.yaml
This pull request aims to fix the error raised by pulling the image `gcr.io/google-samples/node-hello:1.0` that says:
```
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of gcr.io/google-samples/node-hello:1.0 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```
The pull request modifies the image [node-hello](gcr.io/google-samples/node-hello@sha256:d238d0ab54efb76ec0f7b1da666cefa9b40be59ef34346a761b8adc2dd45459b) to [hello-app](gcr.io/google-samples/hello-app@sha256:7104356ed4e3476a96a23b96f8d7c04dfa7a1881aa97d66a76217f6bc8a370d0), so the error will be …
> Modify `node-hello` image to `hello-app`

- content/en/_index.html
Removing the past European event and adding two upcoming KubeCon 2024 events (in Hong Kong and India).
Please, note I'm intentionally removing the 2024 year from all those links' text to fit them for small screens — to prevent the situation pictured here:
For the same reason, I'm using the "KubeCon + CloudNativeCon China" title instead of the full long name ("KubeCon + CloudNativeCon + Open Source Summit + AI_dev China").
Fixes #46386
> Update KubeCon 2024 events

- content/zh-cn/docs/tutorials/stateless-application/expose-external-ip-address.md
- content/zh-cn/examples/service/load-balancer-example.yaml
Sync with en text and provide some minor changes:
```
content/zh-cn/docs/tutorials/stateless-application/expose-external-ip-address.md
```
> [zh] Sync a tutorial: expose-external-ip-address.md

- content/ru/_index.html
Updating upcoming KubeCon events on the main page, like it was just done in English:  #46413
Additionally, I translated another paragraph linking to the download page to keep the localised page fully in sync. (Hopefully, I'll be able to add a Russian translation of this page ASAP, too.)
> [ru] Sync the main page with KubeCon 2024 events

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/device-plugin-cdi-devices.md
This is a documentation update for the [Add CDI devices to device plugin API](https://github.com/kubernetes/enhancements/issues/4009) feature. The feature is planned for GA graduation in 1.31.
The documentation update was explicitly requested in [this comment](https://github.com/kubernetes/enhancements/issues/4009#issuecomment-1943582878)
> Device Plugins: add info about GA graduation

- content/en/docs/reference/command-line-tools-reference/feature-gates/name-generation-retries.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/name-generation-retries.md
Fhix fixes an oversight in feature gate naming. It was noticed here: https://github.com/kubernetes/enhancements/issues/4420#issuecomment-2146317270
> Fix NameGenerationRetries feature gate name in docs to match the RetryGenerateName name in code

- content/en/docs/tasks/manage-hugepages/scheduling-hugepages.md
Removed the always stable state and replaced with picking up from feature state option of feature gate name like some other examples I have seen in doc.
Fixes https://github.com/kubernetes/website/issues/46654
> Fix feature-state for "Manage HugePages"

- content/en/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md
Cleanup duplicates for blog 2024-06-06-10-Years-of-Kubernetes
> Cleanup duplicates for blog 2024-06-06-10-Years-of-Kubernetes

- content/en/blog/_posts/2018-07-24-cpu-manager.md
On blog entry on 2018-07-24: Author's field contains unparsable characters. 
Fails with:
```
error calling Parse: parse "(mailto:<redacted>)": first path segment in URL cannot contain colon
```
> fix(blog-2018-07-24): Authors entry field contains unparsable chars

- content/en/docs/reference/using-api/cel.md
There are mismatched parentheses in the example CEL expressions. This PR tries to fix them.
> Fix mismatched parentheses in cel.md

- content/zh-cn/docs/reference/kubectl/kubectl.md
Fixed the command line tool link in kubectl.md, the correct link should be `/zh-cn/docs/reference/kubectl/`.
> [zh] Fix command line tool link in kubectl.md

- layouts/partials/kubernetes-overview.html
This PR contains a  change in the site front page to link to https://kubernetes.io/blog/2024/06/06/10-years-of-kubernetes/
Changes in detail: Added the link " https://kubernetes.io/blog/2024/06/06/10-years-of-kubernetes/" to the birthday image in the front page
> change in the site front page to link the birthday blog

- content/en/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md
- Fix broken link in content/en/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md
[Deploy preview](https://deploy-preview-46708--kubernetes-io-main-staging.netlify.app/blog/2024/06/06/10-years-of-kubernetes/)
> Fix broken link in content/en/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md

- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/tutorials/stateful-application/basic-stateful-set.md
- content/en/examples/application/web/web-parallel.yaml
- content/en/examples/application/web/web.yaml
This pull request aims to fix the error raised by pulling the image `registry.k8s.io/nginx-slim:0.8` that says:
```
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of registry.k8s.io/nginx-slim:0.8 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```
> Modify registry.k8s.io/nginx-slim version from 0.8 to 0.24

- content/it/docs/reference/glossary/index.md
Glossary's index was missing for localized italian.
Building local hugo fails with
```
ERROR [it] Glossary Bundle not found for language. Create at least an index.md file inside docs/reference/glossary
ERROR [it] No glossary items found
```
> [it] Add missing localized docs/reference/glossary/index.md

- content/en/docs/reference/using-api/cel.md
| CEL Expression | Purpose |
| ------------- | ------------- |
| "abc 123".find('[0-9]*') | Find the first number in a string |
| "1, 2, 3, 4".findAll('[0-9]*').map(x, int(x)).sum() < 100  | Verify that the numbers in a string sum to less than 100  |
The execution environment below is CEL Playground.
```
"abc 123".find('[0-9]*')
""
```
```
"1, 2, 3, 4".findAll('[0-9]*').map(x, int(x)).sum() < 100
failed to evaluate: type conversion error from 'string' to 'int'
"1, 2, 3, 4".findAll('[0-9]*')
["1","","2","","3","","4"]
```
```
"abc 123".find('[0-9]+')
"123"
```
```
"1, 2, 3, 4".findAll('[0-9]+').map(x, int(x)).sum() < 100
true
```
https://www.regular-expressions.info/zerolength.html
- The regular expression `[0-9]*` also matches `""` (empty characters).
- This can be solved by requiring at …
> Correction of CEL sample code.

- content/en/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md
This PR is fixing the following:
1. spaces between links and words
2. link to New Contributor Guide
> Fix formatting and link in 10 Years of Kubernetes blog post

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
Lot of folks are consfused with new etcdutl command and raising PR/Issues reporting as typo.
As part of this PR i want to restructure the section in https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster to highlight the two options of restore in tab layout. This will now have 2 options side by side and the exisitng note content is also used on tab for etcdctl. Hope is this will help.
> Add tab layout for "etcdutl" and "etcdctl" restore options

- content/pt-br/docs/tasks/access-application-cluster/create-external-load-balancer.md
This PR translates the documentation at content/pt-br/docs/tasks/access-application-cluster/create-external-load-balancer/ to Brazilian Portuguese.
The goal is to make the documentation more accessible to Brazilian Kubernetes users.
The translation strives to remain faithful to the original content, with minor adaptations to enhance comprehension for Brazilian DevOps engineers.
@edsoncelio 
@stormqueen1990 
Fixes #46514
> [pt-br] Add tasks/access-application-cluster/create-external-load-balancer.md

- content/es/blog/_index.md
- content/es/case-studies/_index.html
- content/es/community/_index.html
- content/es/docs/home/_index.md
- content/es/partners/_index.html
Align how we style the partners page to work more the way Docsy expects it to.
Update the following pages to align how we style them with Vanilla Docsy:
- Blog
- Case studies
- Community
- Documentation
- Partners
[Current page](https://kubernetes.io/es/) | [Preview](https://deploy-preview-46474--kubernetes-io-main-staging.netlify.app/es/)
> [es] Sync navbar items for vanilla Docsy

- content/en/docs/reference/access-authn-authz/rbac.md
> Reworded 'beyond discovery permissions' wording in "Using RBAC Authorization" page

- content/en/docs/concepts/services-networking/service.md
Service without selectors.
Correct command from proxy to port-forward.
issue #33361
> Service without selectors, command correction issue

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
The PublicKeysECDSA has been poorly tested and supported and apparently it had a bug where keys in kubeconfig files were using RSA even if the FG was true. (even the FG name is misleading...)
Add note about that in the FG section of the kubeadm init doc.
xref https://github.com/kubernetes/kubeadm/issues/3072
> kubeadm: add note about a bug in the PublicKeysECDSA FG

- content/en/examples/service/networking/example-ingress.yaml
fix: https://github.com/kubernetes/website/issues/46546
with new ingress 0.22 + capture groups must be explicit, see https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/rewrite/README.md
Just delete rewrite-target annotation and ingress will work as expect by default.
> Delete rewrite-target annotation in ingress example

- content/en/docs/reference/command-line-tools-reference/feature-gates/read-write-once-pod.md
This feature is GA and its feature gates will be removed in v1.31:
https://github.com/kubernetes/kubernetes/pull/124329
Following instructions in:
https://kubernetes.io/docs/contribute/new-content/new-features/#ready-for-review-feature-gates
/assign sftim
/assign carlory
> Remove ReadWriteOncePod feature gate

- content/en/docs/concepts/scheduling-eviction/pod-overhead.md
In the example section for pod overhead - we need to have requests instead of limits. As sum of requests(not limits) is considered while admitting a pod with pod overhead
> Mention how requests are inferred from limits

- content/en/docs/tutorials/hello-minikube.md
The example command won't work if just copy/pasted, the name in it needs updating to the one in the user's environment.
> tell the user to use their own name, not the example.

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
Tested empirically. Also matches the operator names.
> fix Gt, Lt behaviour documentation

- content/en/docs/reference/glossary/cloud-controller-manager.md
removed self-referencing link per #46613
Tested locally with 
`make container-image`
`make container-serve`
In a web browser, navigate to https://localhost:1313 and view changes
> Remove self referencing link

- content/en/docs/concepts/architecture/garbage-collection.md
The documentation about the feature gate  and option field "ImageMaximumGCAge" is misleading. The option field for the kubelet configuration is camelCase and needs to start with a lowercase "i" instead of an uppercase "I" (like for the feature gate option).
> Update garbage-collection.md for misleading "ImageMaximumGCAge" configuration option

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/honor-pv-reclaim-policy.md
k/k: https://github.com/kubernetes/kubernetes/pull/124842
kep: https://github.com/kubernetes/enhancements/pull/4397
/hold
for k/k merged
preview https://deploy-preview-46794--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/persistent-volumes/#persistentvolume-deletion-protection-finalizer
> promote HonorPVReclaimPolicy to beta

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
- `request.desiredVersion` should be `request.desiredAPIVersion`. Ref - [types.go](https://github.com/kubernetes/kubernetes/blob/a3a49887ee73fa1108adac97a797dec02ccb00d4/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go#L495)
> Fix misnamed field in CRD documentation

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
Add note about that in the PublicKeysECDSA section of the kubeadm init doc.
xref https://github.com/kubernetes/website/issues/46799
> Release 1.29-kubeadm: add note about a bug in the PublicKeysECDSA feature gate

- content/zh-cn/examples/pods/security/hello-apparmor.yaml
Update AppArmor configuration to:
`content/zh-cn/examples/pods/security/hello-apparmor.yaml`
Prior to Kubernetes v1.30, AppArmor was specified through annotations. After Kubernetes v1.30, it needs to be configured in securityContext. The original **hello-apparmor.yaml** file still uses annotations to configure AppArmor, which has been updated to use securityContext configuration.
> [zh] update content/zh-cn/examples/pods/security/hello-apparmor.yaml

- content/ja/docs/contribute/review/reviewing-prs.md
- Update the word "pull request" from Katakana to English
ref. https://kubernetes.io/ja/docs/contribute/localization/#terminology
> Kubernetesのリソース名や技術用語などは、原則としてそのままの表記を使用します。
**Deploy Preview**: [link](https://deploy-preview-46759--kubernetes-io-main-staging.netlify.app/ja/docs/contribute/review/reviewing-prs/)
> [ja] fix: Update the word "pull request" from Katakana to English

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Revise the existing docs about Pod termination.
- Fix a formatting issue
- Overall, have fewer notes
- Make sidecar containers more prominent; they are on by default in Kubernetes v1.30
[Original](https://k8s.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) | [Preview](https://deploy-preview-46525--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)
Fixes #46524
/sig node
> Revise termination section in pod lifecycle concept

- content/en/docs/reference/command-line-tools-reference/feature-gates/name-generation-retries.md
This is not a user visible feature. The change is that name generation is retried automatically by the apiserver if the randomly generated hash collides an existing name.  Name generation failures can still happen, and happen with the same error, but are far more rare.
For this reason, only a feature gate is being added to the documentation.
> KEP-4420: Retry Generate Name: Promote to beta

- assets/scss/_custom.scss
- layouts/shortcodes/cve-feed.html
For the [CVE feed](https://kubernetes.io/docs/reference/issues-security/official-cve-feed/) page, use bold for any vulnerability that hasn't been fixed. [Preview](https://deploy-preview-46996--kubernetes-io-main-staging.netlify.app/docs/reference/issues-security/official-cve-feed/).
Relies on changes from https://github.com/kubernetes/sig-security/pull/115
> Style unfixed vulnerabilities in bold

- content/en/docs/tasks/configure-pod-container/configure-service-account.md
The word `omitted` is likely more appropriate than `elided` here.    `elided` refers more to speech than writing.
> Replaced elided with omitted

- layouts/_default/cve-feed.rss.xml
Includes the new CVE _status_ field for each item in the [RSS feed](https://kubernetes.io/docs/reference/issues-security/official-cve-feed/#cve-feeds-1).
Relies on changes from [kubernetes/sig-security#115](https://github.com/kubernetes/sig-security/pull/115)
> Include CVE status in RSS feed

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
Improve https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/
- Only have **one** prerequisites heading
- Actually list prerequisites
- Don't list a cluster as a prerequisite (they might not have one)
[Preview](https://deploy-preview-46758--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/configure-upgrade-etcd/)
> Improve etcd task introduction

- content/en/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md
We need to update the value in the document to correspond to the source code.
In the source code, the hardcoded minimum number of nodes is 100,
https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/scheduler/schedule_one.go#L54
and scheduler checks all nodes if feasible nodes is less than 100.
https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/scheduler/schedule_one.go#L679-L681
> Fixed minimum feasible nodes value (50->100)

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
This PR addresses the issue of duplicated `feature-state` shortcodes in the [Extend the Kubernetes API with CustomResourceDefinitions page (here)](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#crd-selectable-fields). The manually driven feature-state shortcode has been removed in favor of the dynamically derived one that updates based on feature gate description file changes.
[Fixed Preview Page (here)](https://deploy-preview-47046--kubernetes-io-main-staging.netlify.app/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#crd-selectable-fields) | [Problematic Current Page (here) ](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#crd-selectable-fields)
> Remove duplicate feature-state shortcode in CRD task

- content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
```
content/zh-cn/docs/tasks/debug/debug-application/debug-running-pod.md
```
See [preview](https://deploy-preview-47057--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/debug/debug-application/debug-running-pod/).
> [zh] Sync debug-application/debug-running-pod.md

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md
Fix a typo `extraMounts` should be `extraVolumes`.
> fix typo: extraMounts -> extraVolumes

- assets/js/search.js
- assets/scss/_custom.scss
- layouts/_default/baseof.html
- layouts/_default/search.html
- layouts/blog/baseof.html
- layouts/case-studies/single-baseof.html
- layouts/docs/baseof.html
- layouts/docs/glossary.html
- layouts/partials/docs/content-page.html
- layouts/partials/search-input.html
- netlify.toml
- static/js/search.js
First, this PR has PageFind search available for [all users OUTSIDE of China](https://github.com/cjyabraham/website/commit/3c0442eab47dfa2f91e1c08c102eaff4776e325e). This is just temporary to facilitate testing and we will revert this before merging the PR. The goal is to show PageFind to all users IN China, as a replacement for Bing, which has been [costing CNCF a lot of money recently](https://github.com/kubernetes/website/issues/44475).
Could someone help integrate this into the Makefile properly. I’m not sure where it should be applied and how to integrate it. You can see what I’ve done to get PageFind to run in [the netlify.toml commands](https://github.com/kubernetes/website/pull/46768/files#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489ed) but that may not be …
> PageFind for users in China

- content/de/docs/tasks/tools/install-kubectl-linux.md
The German installation instructions for RedHat were outdated and do not currently work.
This replaced `packages.cloud.google.com` with the current `pkgs.k8s.io` urls. 
Also adds SUSE installation instructions in german language.
I found no active german localization branch so I opened this PR on the main branch. If there is a better branch please let me know.
> Update German install-kubectl-linux.md

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
This PR updates https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/, aiming to explain more about Pod lifecycle. The diagram about associated object lifecycle gets a new more relevant caption.
There are some specific cleanups around Pod scheduling readiness and to emphasize that Pods _can_ (or, at least, sometimes do) restart containers.
[Preview](https://deploy-preview-46529--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/pods/pod-lifecycle/) of the changes
> Improve pod lifecycle concept page

- content/en/docs/reference/labels-annotations-taints/_index.md
Adding & registering the annotation `kubectl.kubernetes.io/restartedAt`
on page https://kubernetes.io/docs/reference/labels-annotations-taints/
Fixes: #40067
> Registering and Documenting restartedAt annotation

- content/ja/docs/tasks/tools/install-kubectl-linux.md
en PR https://github.com/kubernetes/website/pull/45814/files
> [ja] kubectl debian install guide does not mention gnupg at all

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
- content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
- content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md
- content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
- content/en/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md
- content/en/docs/setup/production-environment/tools/kubeadm/high-availability.md
- content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
- content/en/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
- content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- make some updates to --config on upgrade, as now it supports an v1beta4,UpgradeConfiguration and there is no possibility to reconfigure using --config on upgrade anymore.
- start using v1beta4 in all examples, the v1beta4 API page is already generated but needs update for 1.31.
xref https://github.com/kubernetes/kubeadm/issues/2890
> kubeadm: start using v1beta4 in all docs

- content/en/docs/setup/production-environment/container-runtimes.md
We now link to the packaging repository to keep the installation instructions up to date.
@kubernetes/sig-node-cri-o-test-maintainers PTAL
Refers to https://github.com/cri-o/cri-o/issues/8353
> Update CRI-O install link

- content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
en PR https://github.com/kubernetes/website/pull/46577/files
> [pt] Bump cri-tools version to v1.30.0

- static/js/search.js
The only usage of these functions was here, we dropped it when switching to PageFind
https://github.com/kubernetes/website/commit/9d2317aa156e65dcdedd5eb79585d2af5f0d8658#diff-f355db8e18a5352f796b8030582fdf862ec9a7ea193ca4cf71de7df9e7386db1L69-L70
> cleanup(search): drop some bing search leftovers

- content/en/blog/_posts/2015-03-00-Welcome-To-Kubernetes-Blog.md
- content/en/blog/_posts/2015-04-00-Kubernetes-And-Mesosphere-Dcos.md
- content/en/blog/_posts/2015-05-00-Appc-Support-For-Kubernetes-Through-Rkt.md
- content/en/blog/_posts/2015-05-00-Docker-And-Kubernetes-And-Appc.md
- content/en/blog/_posts/2015-05-00-Kubernetes-On-Openstack.md
- content/en/blog/_posts/2015-05-00-Resource-Usage-Monitoring-Kubernetes.md
- content/en/blog/_posts/2015-06-00-The-Distributed-System-Toolkit-Patterns.md
- content/en/blog/_posts/2015-07-00-How-Did-Quake-Demo-From-Dockercon-Work.md
- content/en/blog/_posts/2015-07-00-Strong-Simple-Ssl-For-Kubernetes.md
- content/en/blog/_posts/2015-07-00-The-Growing-Kubernetes-Ecosystem.md
- content/en/blog/_posts/2015-08-00-Using-Kubernetes-Namespaces-To-Manage.md
- content/en/blog/_posts/2015-09-00-Kubernetes-Performance-Measurements-And.md
- content/en/blog/_posts/2015-10-00-Some-Things-You-Didnt-Know-About-Kubectl_28.md
- content/en/blog/_posts/2015-11-00-Creating-A-Raspberry-Pi-Cluster-Running-Kubernetes-The-Shopping-List-Part-1.md
- content/en/blog/_posts/2015-11-00-Kubernetes-1-1-Performance-Upgrades-Improved-Tooling-And-A-Growing-Community.md
- content/en/blog/_posts/2015-11-00-Monitoring-Kubernetes-With-Sysdig.md
- content/en/blog/_posts/2015-11-00-One-Million-Requests-Per-Second-Dependable-And-Dynamic-Distributed-Systems-At-Scale.md
- content/en/blog/_posts/2015-12-00-Creating-Raspberry-Pi-Cluster-Running.md
- content/en/blog/_posts/2015-12-00-How-Weave-Built-A-Multi-Deployment-Solution-For-Scope-Using-Kubernetes.md
- content/en/blog/_posts/2015-12-00-Managing-Kubernetes-Pods-Services-And-Replication-Controllers-With-Puppet.md
This PR extends the changes made in PR https://github.com/kubernetes/website/pull/45865 and implements those changes to all the blog files as per the recommendation in https://github.com/kubernetes/website/pull/45865#issuecomment-2054036103. The primary change involves relocating author details into the metadata within the front matter.
_**Edit**: I'll split this into several PRs each focusing on a single year blog._
[Preview Blog Summary Page](https://deploy-preview-45957--kubernetes-io-main-staging.netlify.app/blog)
> Update blog content files to move author details in front-matter

- content/en/blog/_posts/2023-05-12-in-place-pod-resize/index.md
This PR corrects a minor typo in a blog post by replacing the phrase “do to” with “due to.” The change improves readability and accuracy. Please review and merge as appropriate.
For reference, the affected blog post is titled "Kubernetes 1.27: In-place Resource Resize for Kubernetes Pods (alpha)". You can find it [here](https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/). 😊
> Fix typo in blog post: “do to” -> “due to”

- content/en/docs/concepts/configuration/liveness-readiness-startup-probes.md
- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ is more of a tutorial than a task.
> 
> If someone has the capacity to, we could split it into:
> 
> * a new tutorial page that walks people through learning about container probes
> * a focused guide for people who have already learned, and want to set up one of the four types of probe
>   
>   * with signposting to the tutorial, in case someone wants to learn the background first
> Add Liveness, Readiness, and Startup Probes concept

- content/en/docs/tasks/configure-pod-container/configure-gmsa.md
Fixes ambiguity with `GUID` specified in gMSA credspec's `DomainJoinConfig` section, as well as incorrect description of `SID` - the SID used in `DomainJoinConfig` belongs to the domain and not the gMSA, see the CredSpec module referenced in the [KEP 689](https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/689-windows-gmsa) -- @ https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/windows-server-container-tools/ServiceAccounts/CredentialSpec.psm1#L298-L304
> Fix gMSA credspec definitions

- content/en/docs/concepts/configuration/manage-resources-containers.md
- content/en/docs/concepts/storage/volumes.md
To use default size of memory-backed emptydir, some risks exist. So this adds cautions for the risks.
Ref: https://github.com/kubernetes/kubernetes/issues/119611
> Add caution for using memory-backed emptydir

- content/en/examples/application/cassandra/cassandra-statefulset.yaml
Closes #47039
**Issue**:
The current command waits for the termination grace period of 1800 seconds (30 minutes), causing unnecessary delays for users.
**Solution**:
Reduced the terminationGracePeriodSeconds value to a shorter duration (e.g., 300 or 500 seconds) to avoid prolonged wait times.
**Changes**:
Updated the termination grace period from 1800 seconds to 300 seconds in the relevant command.
Impact:
This change will significantly reduce wait times during the execution of the command, improving user experience.
> Reduce GracePeriod to 300 sec for deploying Cassandra with a StatefulSet

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/elastic-indexed-job.md
Tracking issue: https://github.com/kubernetes/enhancements/issues/3715
> Graduate ElasticIndexedJob to GA

- content/zh-cn/docs/concepts/configuration/_index.md
- content/zh-cn/docs/concepts/configuration/liveness-readiness-startup-probes.md
```
content/zh-cn/docs/concepts/configuration/liveness-readiness-startup-probes.md
```
See [preview](https://deploy-preview-47160--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/configuration/liveness-readiness-startup-probes/).
> [zh] add liveness-readiness-startup-probes.md

- content/en/docs/concepts/extend-kubernetes/operator.md
Update the GitHub repository URL of Java Operator SDK since the repository is migrated to another organization.
> Update the GitHub repo url of Java Operator SDK

- content/zh-cn/docs/tasks/administer-cluster/change-pv-access-mode-readwriteoncepod.md
```
content/zh-cn/docs/tasks/administer-cluster/change-pv-access-mode-readwriteoncepod.md
```
> [zh] Add change-pv-access-mode-readwriteoncepod.md

- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
This change clarifies that kubelet serving and client certificates include the node name in the CN.
cc @enj @liggitt
> Clarify kubelet serving and client cert CN values

- data/releases/eol.yaml
- data/releases/schedule.yaml
I ran `schedule-builder -uc ../website/data/releases/schedule.yaml ../website/data/releases/eol.yaml` as a starting point to update the release schedule.
There might still be some tweaks I need to do.
/hold
> updating release schedules after patch releases

- content/en/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
Example show under [Managing Secrets using Kustomize](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kustomize/) page show setup with password=1f2d1e2e67df. But later in the document, it indicates wrong hash as UyFCXCpkJHpEc2I9 and pointed to a different password value S!B\*d$zDsb=.
This commit aligns the secret and hash value to 1f2d1e2e67df.
> Fix inconsistent example (Kustomize)

- content/en/docs/tasks/configmap-secret/managing-secret-using-kustomize.md
- Use a consistent style for four hits of `kustomization file`
- Remove an extra `}`
> Fix typos in managing-secret-using-kustomize.md

- content/en/docs/tasks/administer-cluster/cpu-management-policies.md
this is a placeholder PR for KEP-4176 https://github.com/kubernetes/enhancements/issues/4176
/cc @Princesso
> Add docs for KEP-4176 new static policy DistributeCPUsAcrossCores

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Modify `validation rules` link in crd docs that was not activated due to typo.
> fix: link typo in crd docs

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Signed-off-by: Stefan Büringer buringerst@vmware.com
Through PR #45155 the additional printer columns & field selector sections got mixed up. This PR fixes that
> Disentangle CRD additional printer columns & field selector sections

- content/en/docs/reference/command-line-tools-reference/feature-gates/kubelet-separate-disk-gc.md
- One-line PR description: Promote [KEP-4191](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4191-split-image-filesystem/README.md?rgh-link-date=2024-06-03T08%3A18%3A51Z) "Split Image Filesystem" to Beta, update references to the `KubeletSeparateDiskGC` feature gate.
- Issue link: https://github.com/kubernetes/enhancements/issues/4191
- Other comments:
Starting from the upcoming Kubernetes release v1.31, the feature will be enabled by default, allowing users to deploy split image and container filesystems without enabling the feature gate to benefit from the new functionality.
Thus, update the documentation that references the `KubeletSeparateDiskGC` feature gate, ensuring that its state post-Beta promotion will be correctly reflected.
Related:
- …
> KEP-4191: Split Image Filesystem promotion to Beta

- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/stateful-set-start-ordinal.md
Remove StatefulSetStartOrdinal feature gate to target stable in 1.31
* KEP-3335 Enhancement: https://github.com/kubernetes/enhancements/pull/3335
> Remove StatefulSetStartOrdinal feature gate to target stable in 1.31

- content/en/docs/reference/access-authn-authz/authentication.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
- content/zh-cn/docs/concepts/services-networking/network-policies.md
Add documentation for Alpha phase of https://github.com/kubernetes/enhancements/issues/4633.
> KEP-4633: Add documentation for Configurable Endpoints for Anonymous Auth.

- data/i18n/zh-cn/zh-cn.toml
When I read page https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
, I find that the note [legacy_repos_message] is not synchronized.
So I resync the file `data/i18n/zh-cn/zh-cn.toml`.
See the [preview page](https://deploy-preview-47244--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl).
> [zh-cn] Resync localization strings

- content/en/docs/reference/command-line-tools-reference/feature-gates/apparmor.md
- content/en/docs/tasks/configure-pod-container/security-context.md
- content/en/docs/tutorials/_index.md
Update the feature gate for AppArmor to Stable stage for 1.31.
With https://github.com/kubernetes/kubernetes/pull/125257 we will be graduating the AppArmor support to GA aka stable. This PR updates the docs to reflect that.
xref https://github.com/kubernetes/enhancements/issues/24
> KEP-24: Graduate Kubernetes' support for AppArmor to GA.

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md
Sync with en text.
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md
```
> [zh] Sync a feature gate: zero-limited-nominal-concurrency-shares.md

- content/en/docs/concepts/storage/volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/image-volume.md
- content/en/docs/tasks/configure-pod-container/image-volumes.md
- content/en/examples/pods/image-volumes.yaml
Adding a simple task to deploy image volumes. I assume most of the details will be generated from the API (https://github.com/kubernetes/kubernetes/pull/125660).
Refers to https://github.com/kubernetes/enhancements/issues/4639
Preview:
- https://deploy-preview-46946--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/image-volumes
- https://deploy-preview-46946--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/volumes/#image
> Document OCI volume sources / KEP-4639

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Signed-off-by: Stefan Büringer buringerst@vmware.com
This PR fixes the example message for CRD CEL transition rules in uncorrelatable paths.
Context: 
* Slack thread: https://kubernetes.slack.com/archives/C0EG7JC6T/p1718987516353139
* Corresponding line that produces the error: https://github.com/kubernetes/kubernetes/blob/d081fd56a2aba4663f11dd5e27dbcf64c0ec6638/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L1261
> Fix CRD CEL transition rule error message example

- content/ja/docs/reference/setup-tools/kubeadm/generated/_index.md
- content/ja/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
- content/ja/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
- content/ja/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_migrate.md
- content/ja/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print.md
- content/ja/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_init-defaults.md
- content/ja/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md
- content/ja/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_validate.md
- content/ja/docs/reference/setup-tools/kubeadm/kubeadm-config.md
Fixes #40420 
Preview: https://deploy-preview-46887--kubernetes-io-main-staging.netlify.app/ja/docs/reference/setup-tools/kubeadm/kubeadm-config/
> [ja] Translate reference/setup-tools/kubeadm/kubeadm-config into Japanese 

- content/en/docs/reference/labels-annotations-taints/audit-annotations.md
Added two audit annotations : k8s.io/deprecated & k8s.io/removed-release
Partially Fixes: #29479
> Registered k8s.io/deprecated & k8s.io/removed-release audit annotation

- content/en/docs/tasks/configure-pod-container/security-context.md
Add `/sys/devices/virtual/powercap` to Masked Paths in security-context.md
The document does not reflect the following:
ref https://github.com/kubernetes/kubernetes/pull/125970
> Add /sys/devices/virtual/powercap to Masked Paths

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
For many, maybe most, installations of etcd, when etcd is restored with etcdctl, when the etcd pod YAML is edited to point at a new restore location, the pod will also need to be restarted and the kubelet restarted in order for etcd to become fully operational again with the new backup. Some basic guidance is provided for use of the (legacy) etcdctl instructions as a reminder.
> Specify likely etcd restart steps for etcdctl-based restore.

- content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/custom-resource-field-selectors.md
- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Update feature gate to reflect that this is in beta starting with 1.31 and is enabled by default.
This feature was accurately documented for alpha in https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/ and https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/, so we don't need to change any other documentation.
> KEP-4358: Custom Resource Field Selectors: Promote to Beta

- content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
- One-line PR description: Add documentation for [KEP-4191](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4191-split-image-filesystem/README.md) "Split Image Filesystem"
- Issue link: https://github.com/kubernetes/enhancements/issues/4191
- Other comments:
The Split Image Filesystem feature introduces changes, such as new eviction signals, resource reclaim conditions, new metrics and a new filesystem type, the `containerfs`. Thus, document newly added changes.
> KEP-4191: Split Image Filesystem add documentation

- .github/PULL_REQUEST_TEMPLATE.md
While reviewing pull requests I noticed there are a lot of PRs that are addressing open issues, but the PRs are not properly linked. This results in a lot of issues being left open, even after the fix has been merged.
This updates the PR template to give a short instruction on adding the expected line in the PR description so that the issue and PR can be linked automatically and closed on merge.
> Add issue link info to PR template

- content/en/docs/reference/command-line-tools-reference/feature-gates/supplemental-groups-policy.md
- content/en/docs/tasks/configure-pod-container/security-context.md
- content/en/examples/pods/security/security-context-5.yaml
- content/en/examples/pods/security/security-context-6.yaml
This PR adds a user-facing document for https://github.com/kubernetes/enhancements/issues/3619 in [Configure a Security Context for a Pod or Container](https://deploy-preview-46920--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/security-context/)
- "Implicit group membership in /etc/group in the container image" section is added to clarify the motivation of this KEP.
- "Configure fine-grained SupplementalGroups control for a Pod" section is introduced to explain feature gates and policies. This section also describes the Node's `.status.containerStatuses[].user.linux` field.
----
For:
- https://github.com/kubernetes/enhancements/issues/3619
Depends on:
- k/k
- contained: 
- CRI-O Update PR(s):
> [dev-1.31] KEP-3619: Fine-grained SupplementalGroups control

- content/en/docs/concepts/storage/persistent-volumes.md
This PR is a doc update explaining the change in behavior described in the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2644-honor-pv-reclaim-policy
cc: @xing-yang @jsafrane @carlory 
KEP: https://github.com/kubernetes/enhancements/issues/2644
> Doc update for Persistent Volumes

- content/en/docs/reference/command-line-tools-reference/feature-gates/port-forward-websockets.md
* Updates control plane feature flag: PortForwardWebsockets to Beta
* Updates `kubectl` feature flag: KUBECTL_PORT_FORWARD_WEBSOCKETS to Beta
https://github.com/kubernetes/enhancements/issues/4006
> [KEP-4006] - Docs for PortForward over WebSockets Feature Gates (Beta)

- content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
This PR clarifies the remark about the restrictions on the name of an object whose kind/resource is defined by a CRD.
Fixes #46262
> Clarify remark about object names wrt CRD

- data/i18n/en/en.toml
- layouts/blog/content.html
close #47223
- Add "translator" metadata to the blog's front matter, just like the [author metadata](https://github.com/kubernetes/website/pull/45865)
- The display remains unchanged for languages that do not require a "translator", like in the English, or where the "translator" metadata is not set
Here is a simple example. This is already working well in Preview - and has already been used by zh-cn - see [`content/zh-cn/blog/_posts
`](https://github.com/kubernetes/website/tree/main/content/zh-cn/blog/_posts)
```yaml
slug: 
title: 
date:
author: >
Author-Name (Affiliation)
translator: >
Translator-Name (Affiliation)
```
- EN: [Preview New Blog Summary Page](https://deploy-preview-47270--kubernetes-io-main-staging.netlify.app/blog/) (not changed)
- EN: [Preview a Blog Article …
> Improve blog article summaries presentation with translator metadata in front matter

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/dra-control-plane-controller.md
This corresponds to https://github.com/kubernetes/enhancements/pull/4709 with API changes from https://github.com/kubernetes/kubernetes/pull/125488.
It covers both DRA KEPs.
> DRA documentation for 1.31

- content/en/docs/concepts/storage/volume-attributes-classes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/volume-attributes-class.md
PR for Alpha -> Beta of [VolumeAttributesClass ModifyVolume · Issue #3751 · kubernetes/enhancements](https://github.com/kubernetes/enhancements/issues/3751)
> KEP-3751 VolumeAttributeClass Beta Promotion

- OWNERS_ALIASES
xref https://github.com/kubernetes/org/pull/5079
- Add @Okabe-Junya (myself) to `sig-docs-ja-owners`
- merged PR (labeled `language/ja`): [35+](https://github.com/pulls?q=is%3Amerged+is%3Apr+author%3AOkabe-Junya+archived%3Afalse+repo%3Akubernetes%2Fwebsite+label%3Alanguage%2Fja+)
- reviewed PR (labeled `language/ja`): [85+](https://github.com/pulls?q=is%3Apr+reviewed-by%3AOkabe-Junya+archived%3Afalse+repo%3Akubernetes%2Fwebsite+label%3A%22language%2Fja%22)
- exactly three months since I became a reviewer: https://github.com/kubernetes/org/pull/4922
cc @kubernetes/sig-docs-ja-owners
> [ja] Add Okabe-Junya to sig-docs-ja-owners

- static/js/search.js
This addresses one of the issues that came from #47108
In deciding what search results to serve, we had previously been checking to see whether a user was in China using the ipinfo.io service. The problem, however, is that many people who are not in China are running privacy software that blocks this service and so they were incorrectly being deemed to be in China. This means that a lot of people would be getting PageFind search results when it would have been fine to serve them the Google search results.
Additionally, there are people in China who are using VPNs so _would_ be able to access Google search results but our system was instead serving them the inferior PageFind results.
This PR moves this test away from a geolocation of whether someone is in China and focuses instead on …
> Improve the test to decide which search results to serve

- content/en/docs/concepts/workloads/pods/_index.md
Fixed a grammar issue dividing one long malformed sentence into two better-formed sentences capturing the intent of the documentation.
Closes: #
> Fix malformed sentence in "Pods" concept page

- content/en/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding.md
- content/en/docs/tasks/configure-pod-container/configure-service-account.md
https://github.com/kubernetes/enhancements/issues/4193
Includes 1.31 updates for the ServiceAccountTokenNodeBinding feature gate portion of KEP-4193 (the only changes made in 1.31)
/sig auth
/cc @munnerz @ritazh
> KEP-4193: beta promotion of ServiceAccountTokenNodeBinding feature gate

- content/en/docs/tasks/configure-pod-container/configure-service-account.md
Follow-up from https://github.com/kubernetes/website/pull/47283#discussion_r1696743150 for https://github.com/kubernetes/enhancements/issues/4193
/assign @sftim
> KEP-4193: clarify required kubectl version

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/evented-pleg.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-dynamic-resources.md
Sync 2 feature gates:
```
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/evented-pleg.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-dynamic-resources.md
```
> [zh] Sync evented-pleg and kubelet-pod-resources-dynamic-resources

- content/en/docs/tasks/administer-cluster/topology-manager.md
Improve the v1.31 version of https://k8s.io/docs/tasks/administer-cluster/topology-manager/
- Write headings in sentence case per [style guide](https://kubernetes.io/docs/contribute/style/style-guide/)
- Revise the guidance about setting topology manager policy options
- Give each item a bookmarkable heading
- Overall rewording
- Recommend configuring kubelet via its configuration file; command line arguments are largely deprecated
- Write the technical text of headings in backticks (eg `pod` scope not pod scope)
This is basically reference content. A future PR may move the page inside https://k8s.io/docs/reference/node/; for now, let's not do that part.
[Before](https://kubernetes-io-vnext-staging.netlify.app/docs/tasks/administer-cluster/topology-manager/) _vs_ …
> Fix up topology manager reference

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/resource-health-status.md
KEP: https://github.com/kubernetes/enhancements/issues/4680
/sig node
> Device plugin failures: KEP docs

- content/en/docs/concepts/security/pod-security-standards.md
- Capitalize (OPA) Gatekeeper and Policy names
- Update `Pods` case in Windows HostProcess for consistency with the Privileged Containers control
- Other minor changes for internal consistency
> consistency updates for pod security standards documentation

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
Add a clarification that CNI has been supported from earliest version, not just the current version.
> Revise advice about network plugin compatibility

- content/ja/blog/_posts/2024-01-23-image-filesystem.md
- content/ja/blog/_posts/2024-02-22-k8s-book-club/index.md
- content/ja/blog/_posts/2024-03-07-cri-o-seccomp-oci-artifacts.md
- content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-1/index.md
- content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
- content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-3/index.md
- content/ja/blog/_posts/2024-05-20-cloud-provider-migration.md
- content/ja/blog/_posts/2024-05-21-sig-node-spotlight/index.md
- content/ja/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md
- In #47270, we're updating the blog to manage "translator(s)" as metadata. Some blogs localized into Japanese already have a "translator" set, so migrate those.
unhold this once #47270 is merged.
- Blog Summary (not changed): [link](https://deploy-preview-47286--kubernetes-io-main-staging.netlify.app/ja/blog/)
- Blog Article page (add "Translate By"): [Before](https://kubernetes.io/ja/blog/2024/06/20/sig-node-spotlight-2024/) | [After](https://deploy-preview-47286--kubernetes-io-main-staging.netlify.app/ja/blog/2024/06/20/sig-node-spotlight-2024/)
/hold
> [ja] Update blog content files to move translator details in front-matter

- content/en/docs/reference/access-authn-authz/bootstrap-tokens.md
- content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
Optimize document format:
- Adjust line breaks appropriately
- Remove excess spaces
> improve format for bootstrap-tokens certificate-signing-requests

- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
With 1.30 stable, the feature does not need to be enabled and the v1beta1 API group is not needed.
Closes: #
> Remove beta pre-requisites from validating admission policies docs

- data/releases/schedule.yaml
Add an entry for v1.31 on the releases schedule, as described [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-releases-page-the-week-before-the-release)
cc: @katcosgrove @saschagrunert @drewhagen @salaxander @sftim
> Update release schedule for v1.31

- content/en/docs/concepts/workloads/pods/disruptions.md
Add "or preemption for system critical pods" to align the docs with the actual implementation. 
This was done in https://github.com/kubernetes/kubernetes/pull/117586
It is also already reflected in the KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures#beta: "Add DisruptionTarget condition for pods which are preempted by Kubelet to make room for critical pods. Also, backport this fix to 1.26 and 1.27 release branches, and update the user-facing documentation to reflect this change."
> Update pod disruption condition to align with the implementation

- hugo.toml
Set the v1.31 release branch to be for Kubernetes v1.31
This change does **not** cover [`/data/releases`](https://github.com/kubernetes/website/tree/main/data/releases), which also needs doing.
/sig release
> Set (partial) release information for v1.31

- content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
- content/en/docs/concepts/windows/intro.md
https://github.com/kubernetes/kubernetes/pull/122922 added support for memory pressure eviction singals on Windows in v1.31 and these are the corresponding doc updates.
/sig windows
/area kubelet
Closes: #
> Updating Windows node eviction signals docs

- content/ja/docs/concepts/workloads/pods/_index.md
fixed typo in /ja/docs/concepts/workloads/pods/_index.md 
Closes: #47341
> [ja] typo: Typo in /ja/docs/concepts/workloads/pods/_index.md 

- assets/scss/_custom.scss
- content/en/docs/test.md
This PR addresses the issue where tables inside alert callouts _(note, caution, warning)_ were not rendering correctly due to missing styles. 
The proposed fix applies the same styling classes used for tables across the site to tables within alert callouts (notes, cautions, warnings), ensuring that they are consistently styled and properly displayed.
Fixes https://github.com/kubernetes/website/issues/37500
[Preview Fixed Table Rendering](https://deploy-preview-47365--kubernetes-io-main-staging.netlify.app/docs/test/#admonitions) | [Current Page with rendering issue](https://kubernetes.io/docs/test/#admonitions)
> Fix table rendering issue inside admonition blocks

- data/releases/schedule.yaml
This PR updates the schedule to delay the August patch releases by one day due to the 1.31 release occurring the same day.
> Delay August patch releases one day

- content/en/docs/reference/using-api/cel.md
One of the CEL examples was missing a closing brace, this PR fixes that.
> Add missing closing brace in CEL example table

- content/fr/docs/tutorials/hello-minikube.md
Getting rid of katacoda mentions in `hello minikube` for French language.
Closes https://github.com/kubernetes/website/issues/47214 and contributes to https://github.com/kubernetes/website/issues/41496
> Hello minikube french

- hugo.toml
This pull request updates the `hugo.toml` configuration file in the **release-1.29** branch by setting the `deprecated` field from 'false' to 'true'. This change will trigger a deprecation banner in the v1.29 documentation, alerting users that docs support for this version has ended.
Please be aware that the current latest release is **v1.30**  _(as of the time this PR was created)_.
[Preview v1.29 Docs](https://deploy-preview-47395--k8s-v1-29.netlify.app/docs/home/) | [Existing v1.29 Docs](https://v1-29.docs.kubernetes.io/docs/home/)
> Fix v1.29 docs incorrectly not marked as stale

- content/es/docs/tasks/tools/included/optional-kubectl-configs-fish.md
- content/es/docs/tasks/tools/install-kubectl-macos.md
This is a Feature Request closes https://github.com/kubernetes/website/issues/41883
What would you like to be added
Localize content/en/docs/tasks/tools/install-kubectl-macos.md to Spanish
Why is this needed
There is no Spanish localization for this file.
> [es] localize content/en/docs/tasks/tools/install-kubectl-macos.md to Spanish

- content/en/docs/concepts/workloads/pods/disruptions.md
Add a note to clarify that the scenarios for the DisruptionTarget condition
need to be retriable.
To improve clarity on the DisruptionTarget semantics.
This was proposed in the thread on the blogpost; https://github.com/kubernetes/website/pull/46896#discussion_r1705973212
Closes: #
> Add note that scenarios for DisruptionTarget must be retriable

- content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
This PR corrects a typo in the link in the Japanese blog post. I came across this error while trying to experiment with [Link render hooks](https://gohugo.io/render-hooks/links/) to improve multilingual support.
> [ja] fix for link formatting in the blog post

- content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
Add the missing newline before `docker`
> Update docker-cli-to-kubectl.md, add the missing newline

- content/zh-cn/docs/concepts/workloads/pods/disruptions.md
> [zh-cn] sync pods/disruptions.md

- content/de/docs/home/supported-doc-versions.md
- data/i18n/de/de.toml
Align https://kubernetes.io/de/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/
[Preview of the updated page.](https://deploy-preview-46350--kubernetes-io-main-staging.netlify.app/de/docs/home/supported-doc-versions/)
/language de
> [de] Update list of versions to match English

- content/en/docs/reference/labels-annotations-taints/_index.md
Documented nginx.ingress.kubernetes.io/configuration-snippet ingress-nginx annotation.
> Document annotation nginx.ingress.kubernetes.io/configuration-snippet

- content/en/docs/tasks/debug/debug-cluster/troubleshoot-kubectl.md
In this section - I found the provided commands didn't generate the desired results.
The proposed commands seem to work for me.
Validated with:
kubectl version
Client Version: v1.28.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.28.6
openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
base64 (GNU coreutils) 8.32
> Fix advice about checking certificate expiry

- hugo.toml
Updates the site configuration (hugo.toml) for dev-1.31 ahead of v1.31 release date.
This PR satisfies the [Update the site configuration files for future release](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-the-site-configuration-files-for-future-release) task in the Release Docs handbook, adding the latest patch versions into the site config so that will get merged into `main` once we release. I will update the handbook with a link to this example to make this clear in later release cycles.
Thanks!
cc: @chanieljdan @salaxander @Princesso @katcosgrove @reylejano
> Updates v1.31 hugo.toml to include latest patches ahead of release

- hugo.toml
Updating site configuration files (hugo.toml) for release v1.31.
/hold until v1.31 release day.
cc: @drewhagen @chanieljdan @salaxander
> Updates v1.27 hugo.toml for 1.31 release

- content/en/blog/_posts/2024-08-16-kubernetes-1.31-image-volume-source.md
Adding a blog post about the new feature.
Preview:
https://deploy-preview-46960--kubernetes-io-main-staging.netlify.app/blog/2024/08/16/kubernetes-1-31-image-volume-source
> Blog post about OCI volume sources / KEP-4639

- content/en/blog/_posts/2024-08-14-moving-cgroup-v1-support-maintenance-mode-kubernetes-1-31.md
Adding a blog post about moving the [cgroup v1 support to maintenance mode](https://github.com/kubernetes/enhancements/blob/382fe4bf47680f12013349c84dc0a4749ba93c71/keps/sig-node/4569-cgroup-v1-maintenance-mode/README.md) in kubernetes.
> Blog post about cgroup v1 support moving to maintenance mode / KEP-4569

- content/pt-br/docs/concepts/extend-kubernetes/operator.md
en PR https://github.com/kubernetes/website/pull/47170/files
> [pt] Update the GitHub repo url of Java Operator SDK

- content/en/blog/_posts/2024-08-14-pv-last-phase-transition-time-ga.md
KEP: https://github.com/kubernetes/enhancements/issues/3762
> Add blog for PersistentVolumeLastPhaseTransitionTime feature GA in v1.31

- content/en/blog/_posts/2024-08-13-Kubernetes-v1-31-Release.md
Update the KubeDay Australia Date: https://events.linuxfoundation.org/kubeday-australia/
> Update KubeDay Australia Dates

- content/en/blog/_posts/2024-08-16-Honor-PV-Reclaim-Policy-Beta.md
This PR is a blog post explaining the change in behavior described in the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2644-honor-pv-reclaim-policy
Most of the content is originally from https://github.com/kubernetes/website/pull/30556, with some additional updates.
cc: @xing-yang @jsafrane @carlory 
KEP: https://github.com/kubernetes/enhancements/issues/2644
> Blogpost for honor PV reclaim policy fix moving to Beta

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
- content/en/docs/tasks/configure-pod-container/configure-service-account.md
The doc about finalizers doesn't give any information about the fact that the API server considers a deleted service account or a deleted pod's token invalid after 1 minute the DeletionTimestamp.
ref: https://github.com/openshift/kubernetes/blob/76463e21d4dec90b4d49975b182a13e1fdb6b20a/pkg/serviceaccount/claims.go#L176-L197 https://github.com/openshift/kubernetes/blob/76463e21d4dec90b4d49975b182a13e1fdb6b20a/pkg/serviceaccount/claims.go#L216-L234
Closes: #47403
> Clarify expiration time for service accounts and tokens of pods pending deletion despite finalizers

- content/en/docs/reference/labels-annotations-taints/_index.md
Fix a 404 link caused by a redundant markdown space.
[Before](https://kubernetes.io/docs/reference/labels-annotations-taints/#nginx-ingress-kubernetes-io-configuration-snippet) | [After](https://deploy-preview-47491--kubernetes-io-main-staging.netlify.app/docs/reference/labels-annotations-taints/#nginx-ingress-kubernetes-io-configuration-snippet)
> Fix a link in labels-annotations-taints/_index.md

- content/en/docs/contribute/participate/_index.md
Resolved Invalid reference  for prow plugins in this page:https://kubernetes.io/docs/contribute/participate/
Fixes: #47494
> Fix broken hyperlink for 'prow plugins'

- content/en/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/index.md
- This PR just fixes a typo in the KEP-3619 feature blog that will be published on 2024-08-22.
- This is a follow up PR for #46921
> KEP-3619: fix typo in the feature blog to be published on 2024-08-22

- content/en/blog/_posts/2024-08-15-volume-attributes-class.md
Blog ~placeholder~ article for [KEP #3571](https://github.com/kubernetes/enhancements/issues/3751).
> Add post-release blog article for VAC beta

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- Put link text and its url into a single line
- Put glossary var into a single line
- Some minor changes about typo and indentations
> Clean up dynamic-resource-allocation.md

- .github/workflows/update-schedule.yml
Fixes https://github.com/kubernetes/release/issues/3179
cc @kubernetes/release-managers 
Preview: https://deploy-preview-45762--kubernetes-io-main-staging.netlify.app/releases
> Add workflow to automatically update schedule.yaml

- hugo.toml
This pull request updates the hugo.toml configuration file in the release-1.30 branch to trigger a deprecation banner in the v1.30 documentation now that v1.31 is latest and main doc version.
Closes https://github.com/kubernetes/website/issues/47514
> Mark v1.30 docs as stale

- content/ja/docs/tasks/configure-pod-container/security-context.md
- content/ja/examples/pods/security/security-context-5.yaml
- content/ja/examples/pods/security/security-context-6.yaml
updated `content/ja/docs/tasks/configure-pod-container/security-context.md` to the latest.
related PRs of `en` contents:
- https://github.com/kubernetes/website/pull/45280
- https://github.com/kubernetes/website/pull/45152
- https://github.com/kubernetes/website/pull/46920
- https://github.com/kubernetes/website/pull/47023
Preview page: https://deploy-preview-47497--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/configure-pod-container/security-context/
> [ja] Update content/ja/docs/tasks/configure-pod-container/security-context.md

- content/zh-cn/docs/tutorials/hello-minikube.md
There is a index error in ```content\zh-cn\docs\tutorials\hello-minikube.md```.
> [zh]: fix index error in content\zh-cn\docs\tutorials\hello-minikube.md

- content/en/docs/tasks/manage-gpus/scheduling-gpus.md
The link to the NVIDIA GPU vendor implementation reference for the scheduling-gpus page was pointing at their gpu-feature-discovery repo. This repo is deprecated and the work has moved to the k8s-device-plugin repo.
Luckily the old repo has a migration notice that leads folks to the new location, so they ultimately are able to get the information they are looking for. This updates the link to take out the extra step of visiting the old repo first.
> Update NVIDIA GPU scheduling link

- .github/workflows/update-schedule.yml
This fixes the incorrect action syntax of the job.
cc @kubernetes/release-engineering 
Follow-up on https://github.com/kubernetes/website/pull/45762
> Fix syntax in update-schedule GitHub action

- content/ja/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/implicit-groups.yaml
- content/ja/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/index.md
- content/ja/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/strict-supplementalgroups-policy.yaml
Depends on:
- https://github.com/kubernetes/website/pull/47497/
-----
- Translated content/en/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control into Japanese
Closes: #47498
Preview Page: https://deploy-preview-47499--kubernetes-io-main-staging.netlify.app/ja/blog/2024/08/22/fine-grained-supplementalgroups-control/
> [ja] Translated content/en/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control into Japanese

- content/en/blog/_posts/2024-08-20-websocket-transition.md
https://github.com/kubernetes/enhancements/issues/4006
> [KEP-4006] Blog Post: Streaming Transition from SPDY to WebSockets is Beta

- content/zh-cn/docs/reference/access-authn-authz/authentication.md
- Use a consistent Authentication 身份认证 on this page
- Add and comment out some missing english text 
- Add zh text added in v1.31
```
```
See [preview](https://deploy-preview-47522--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/authentication/).
> [zh] Sync access-authn-authz/authentication.md

- content/zh-cn/docs/concepts/architecture/leases.md
- content/zh-cn/docs/concepts/cluster-administration/coordinated-leader-election.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/coordinated-leader-election.md
Added new zh text in:
```
content/zh-cn/docs/concepts/architecture/leases.md
content/zh-cn/docs/concepts/cluster-administration/coordinated-leader-election.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/coordinated-leader-election.md
```
See [preview](https://deploy-preview-47486--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/coordinated-leader-election/).
> [zh] Add coordinated-leader-election.md and related 2 pages

- content/zh-cn/docs/tutorials/hello-minikube.md
There is a wrong format in ```zh-cn\docs\tutorials\hello-minikube``` .
> [zh-cn] Fix wrong format in content\zh-cn\docs\tutorials\hello-minikube

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
change for 1.32
xref
- https://github.com/kubernetes/kubeadm/issues/1793
- https://github.com/kubernetes/kubernetes/pull/126374
> kubeadm-init: mark EtcdLearnerMode as GA

- .github/workflows/update-schedule.yml
This fixes the permissions required for the job, which fails like: https://github.com/kubernetes/website/actions/runs/10444771187
> Fix permissions for "Update schedule.yaml" CD job

- content/en/docs/reference/kubectl/quick-reference.md
It fixes a small typo on the Kubectl cheat sheet page.
> fix typo in quick-reference.md

- content/en/docs/concepts/storage/volume-attributes-classes.md
This PR adds `kube-scheduler` as an additional component that requires the `VolumeAttributesClass` feature-gate. This is a change from the alpha -> beta version of this feature due to [kubernetes/kubernetes#121902](https://github.com/kubernetes/kubernetes/pull/121902).
Closes: #
> Fix volume-attributes-classes.md feature gate requirements

- content/en/blog/_posts/2024-08-21-cgroup-driver-from-cri.md
> KEP-4033: cgroup driver from CRI beta blog

- content/ja/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
- content/ja/examples/pods/pod-with-scheduling-gates.yaml
- content/ja/examples/pods/pod-without-scheduling-gates.yaml
Closes: https://github.com/kubernetes/website/issues/44971
> [ja] Translate content/en/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md into Japanese

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
This PR extends https://github.com/kubernetes/website/pull/46299, which disambiguates pod "Phase" from the "Status" field that occurs in certain  kubectl commands.
> Disambiguate Pod Phase from kubectl status

- content/zh-cn/docs/reference/kubectl/generated/kubectl_exec/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_logs/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_exec/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md
> [zh-cn]sync kubectl_logs kubectl_label kubectl_explain kubectl_exec

- content/en/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/index.md
This PR just fixes the typo in KEP-3619 Kubernetes feature blog to be published on 2024-08-22.
follows up #46921
> Fix typo in KEP-3619 blog published on 2024-08-22

- content/ja/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/index.md
This PR just fixes the typo in KEP-3619 Kubernetes feature blog(ja translation).
PR for en: #47603
> [ja] fix typo in content/ja/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/index.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/event-v1.md
There is a typo here, it is "note" instead of "node".
> fix: a typo

- content/en/docs/concepts/configuration/manage-resources-containers.md
- content/en/docs/contribute/new-content/open-a-pr.md
This PR amends the upstream documentation to improve clarity.
This involves fixing a typo in the resource management documentation, and a case of out-of-order words in the contribution docs.
These clarity issues are also present in the `zh-cn` localizations, however, I'll address those separately on approval, as per the [docs](https://kubernetes.io/docs/contribute/localization/#suggest-changes).
Relevant docs:
- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#memory-backed-emptydir
- https://kubernetes.io/docs/contribute/new-content/open-a-pr/#create-a-branch
> Amend English resource management and contribution docs to be clearer

- netlify.toml
Updated netlify.toml, Node 2.11.0 -> Node 2.17.0 - latest as of 21/08/2024.
See the [official Nodejs blog](https://nodejs.org/en/blog/release/v20.17.0) to know more about the new features included in this release.
> Update node version to latest LTS

- content/zh-cn/docs/reference/access-authn-authz/webhook.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/authorize-with-selectors.md
```
content/zh-cn/docs/reference/access-authn-authz/webhook.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/authorize-with-selectors.md
```
See [preview](https://deploy-preview-47610--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/webhook/).
> [zh] Sync access-authn-authz/webhook.md and related feature gate

- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_current-context.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-cluster.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-context.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-user.md
Remove `--cloud-provider-gce` from these files:
```
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_config/_index.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_current-context.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-cluster.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-context.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-user.md
```
> [zh] Sync 5 kubectl files in kubectl_config/

- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_history.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_pause.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_resume.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md
Remove `--cloud-provider-gce` section in these files:
```
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/_index.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_history.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_pause.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_resume.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status.md
modified:   content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md
```
> [zh] Sync kubectl_rollout/* files

- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-clusters.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-contexts.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-users.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_rename-context.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-cluster.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-context.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-credentials.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_unset.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_use-context.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_view.md
Remove `--cloud-provider-gce` sections from these files:
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-clusters.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-contexts.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-users.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_rename-context.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-cluster.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-context.md
ontent/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-credentials.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set.md …
```
> [zh] Remove --cloud-provider-gce sections from kubectl_config/*

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_clusterip.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_externalname.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_loadbalancer.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_nodeport.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_clusterip.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_externalname.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_nodeport.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_loadbalancer.md
> [zh-cn] sync kubectl_create_service_*

- data/releases/schedule.yaml
This PR updates the schedule to reflect the August patch release. 
This was generated with:
```
schedule-builder -uc data/releases/schedule.yaml
```
> Update the release schedule after August patch releases

- content/en/docs/reference/labels-annotations-taints/audit-annotations.md
The audit annotation authorization.k8s.io/decision `authorization.k8s.io/decision` should have valid values listed in description.
Adding the same in the description of the annotation and  as per this [comment](https://github.com/kubernetes/website/pull/47448/commits/efaca25ffb37712fec8fc69a54940c798ac301c7#r1723527238)
Page to be updated: https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/
> improving documented auth annotation decision

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrole.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrolebinding.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_configmap.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_cronjob.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_deployment.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_ingress.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_job.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_namespace.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_poddisruptionbudget.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_priorityclass.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_quota.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_role.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_rolebinding.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_serviceaccount.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_token.md
Mainly remove `--cloud-provider-gce` sections from:
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrole.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrolebinding.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_configmap.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_cronjob.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_deployment.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_ingress.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_job.md …
```
> [zh] Sync kubectl_create/* files to  remove `--cloud-provider-gce` sections

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/image-volume.md
- content/zh-cn/docs/tasks/configure-pod-container/image-volumes.md
- content/zh-cn/examples/pods/image-volumes.yaml
```
content/zh-cn/docs/tasks/configure-pod-container/image-volumes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/image-volume.md
```
See [preview](https://deploy-preview-47636--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/image-volumes/).
> [zh] Add a task: image-volumes.md and its dependent files

- content/zh-cn/docs/reference/kubectl/generated/kubectl_options/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_port-forward/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_proxy/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_scale/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_options/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_port-forward/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_proxy/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_scale/_index.md
> [zh-cn]sync kubectl_options kubectl_port-forward kubectl_proxy kubectl_scale

- content/en/docs/concepts/workloads/controllers/job.md
There is a typo in `job.md` file. A proper name for one of mentioned frameworks is `Horovod`.
> Fix a typo in job.md. Horovord is horovod

- content/en/docs/concepts/architecture/_index.md
- content/en/docs/concepts/overview/components.md
This PR addresses the concerns raised in issue #47111 regarding the potential misunderstanding of component distribution in Kubernetes clusters, particularly the presence of kubelet and kube-proxy on control plane nodes.
[Before](https://kubernetes.io/docs/concepts/architecture/)
[After](https://deploy-preview-47164--kubernetes-io-main-staging.netlify.app/docs/concepts/architecture/)
I'm not entirely sure how much additional detail is appropriate for this introductory page on cluster architecture. I'm open to removing certain details for brevity if needed. Feedback on the level of detail and which points are most crucial to keep would be greatly appreciated. Also if there is anything I have gotten wrong about cluster architecture, please feel free to correct me.
> Clarify cluster diagram as one possible reference architecture

- layouts/_default/_markup/render-link.html
I'm pleased to introduce the Link Decorator feature, which automatically transforms links in localised documents if the referenced documents have been localised. This feature eliminates the need to manually add language codes to links.
This was also inspired by the https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-link.html template, which is already included in Hugo.
```mermaid
graph LR;
src_link("Link in a doc…")
src_link-->none_localized_link("… is not localized\n starts with `/…`")-->
check_for_localization{"if a localized\ndoc exists"}-- "yes, it is" -->add_lng_prefix("Add lang-code\nprefix to the link")
src_link-->indoc_link("… is in the same doc\nstarts with`#` symbol")
src_link-->already_localized_link("… is already localized\n …
```
> Implementation of the Link Decorator function for processing localised links 🈂️

- content/en/docs/concepts/workloads/pods/sidecar-containers.md
- content/en/docs/tutorials/_index.md
- content/en/docs/tutorials/configuration/pod-sidecar-containers.md
/sig node
more questions about sidecars warranted me to write this down. 
It was discussed at Sidecar WG meeting: https://docs.google.com/document/d/1E1guvFJ5KBQIGcjCrQqFywU9_cBQHRtHvjuqcVbCXvU/edit#bookmark=id.u4zmu7j9vn31
This is the first step in this tutorial. It may require more work in the following areas:
1. I am out of my depth on what would be the best practices writing tools and mutating web hooks that will preserve unknown fields: https://github.com/kubernetes/website/pull/46825#discussion_r1710243472 Extended documentation or even a link to other page that may explain this would go a long way. (https://github.com/kubernetes/website/issues/47465)
2. Explain how to implement sidecar containers without the built-in feature. I am not sure how deep we want to go there to cover edge …
> Add tutorial about running Pods with sidecar containers

- README.md
Dear Team,
I've submitted this PR to enhance the readability and cleanliness of our `README.md` document. I noticed some minor formatting issues that could affect the presentation of our documentation, and I have made the following careful adjustments:
- **MD022/blanks-around-headings**: I've added necessary blank lines around all headings to ensure they stand out visually and are more distinct.
- **MD031/blanks-around-fences**: Similarly, I ensured that code blocks are surrounded by blank lines, making the code easier to read while maintaining consistency across our documentation.
We all know that a well-formatted document can greatly enhance the efficiency of information delivery. By following the recommendations of `markdownlint`, we not only enhance the professionalism of our …
> Enhance Readability with Markdown Formatting Improvements To README.md

- content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
The docs have been updated to use `v1beta4` but the structure of `extraArgs` is still `v1beta3`. The produces an error when running, `failed to unmarshal into []Arg`.
This PR updates the docs to use the correct `v1beta4` `extraArgs` structure.
Closes: #47668
> Update High Availability etcd ClusterConfiguration snippet for v1beta4

- content/en/docs/concepts/architecture/_index.md
- content/en/docs/concepts/overview/components.md
Only wrap lone lines in the recently updated two pages:
```
content/en/docs/concepts/architecture/_index.md
content/en/docs/concepts/overview/components.md
```
No any text revised.
> Tweak long lines in cluster architecture and components

- content/zh-cn/docs/concepts/architecture/_index.md
Sync with en #47164 
```
content/zh-cn/docs/concepts/architecture/_index.md
```
See [preview](https://deploy-preview-47676--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/).
> [zh] Sync concepts/architecture/_index.md

- Dockerfile
One of my previous PRs, [this one](https://github.com/kubernetes/website/pull/47612), somehow broke the `make container-image` - the Docker build of the website image.
Seems like a Golang version 1.23.0+ is required for Hugo 0.133.0 to run but interestingly enough the pipeline for that broken PR went fine, including the Netlify build. This might be the occasion for improving the pipeline too (in a separated issue).
I hope this will trigger the pipeline in a way to really validate my fix.
Fixes #47673 
Thanks @sftim for catching this one.
> Fix: updated golang version to avoid breaking the build

- content/en/docs/concepts/overview/_index.md
- content/en/docs/concepts/overview/components.md
- content/en/docs/concepts/overview/working-with-objects/_index.md
- Reorder https://kubernetes.io/docs/concepts/overview/ so that the historical concept comes last
- Make the new cluster overview (_from #47164_) more prominent
See https://deploy-preview-47674--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/ to view the proposed new overview page (and the left sidebar that goes with it).
> Reorder content in Kubernetes overview section

- content/en/docs/reference/node/kernel-version-requirements.md
- content/en/docs/tasks/administer-cluster/sysctl-cluster.md
Starting from https://github.com/kubernetes/kubernetes/issues/116799, I collected a lot of information about kernel.
And the kernel version requirement is one of the top FAQ from users when they want to choose a new OS or kernel.
Besides, some new features like RRO\ User Namespace\ cgroup v2 needs new kernels.
I try to summarize them in a page to make users clear when choosing a kernel version for their clusters.
xref https://github.com/kubernetes/kubernetes/issues/116799
This page did not include those bug-fixes or version compatibility improvement that are related to kernel versions like:
- faster mount detection for linux kernel 5.10+ using openat2 speeding up pod churn rates. On Kernel versions less 5.10, it will fallback to using the original way of detecting mount points i.e by …
> Document kernel version requirements for Linux

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset/_index.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset/kubeadm_reset_phase.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset/kubeadm_reset_phase_cleanup-node.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset/kubeadm_reset_phase_preflight.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset/kubeadm_reset_phase_remove-etcd-member.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset-phase.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
```
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset-phase.md
```
and their dependent files.
See [preview](https://deploy-preview-47707--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset/).
> [zh] Sync kubeadm-reset and kubeadm-reset-phase and its dependencies

- content/en/blog/_posts/2024-08-23-kubeadm-v1beta4.md
Fix doc link typo in blog release in #47248
N/A
> Fix doc link

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token/_index.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token/kubeadm_token_create.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token/kubeadm_token_delete.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token/kubeadm_token_generate.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_token/kubeadm_token_list.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-token.md
```
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-token.md
```
and its dependent files.
See [preview](https://deploy-preview-47717--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-token/).
> [zh] Sync kubeadm-token.md and its dependent files

- content/en/docs/setup/production-environment/container-runtimes.md
This PR corrects the documentation by removing a misleading reference to a closed containerd issue, ensuring the page accurately reflects the current information.
Closes https://github.com/kubernetes/website/issues/47343
> Remove reference to closed containerd issue in "Container Runtimes" page

- content/zh-cn/docs/concepts/containers/images.md
Fix docs/concepts/images.md required-image-pulls typo
https://github.com/kubernetes/website/issues/47736
Closes: #
> Fix required-image-pulls typo

- content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md
Remove `--cloud-provider-gce` from this file.
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md
```
> [zh] Sync kubectl_replace/_index.md

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Addresses https://github.com/kubernetes/kubeadm/issues/2563#issuecomment-2312123413.
Updates the instructions regarding swap configuration:
* Outlines the different options more clearly: either disable swap or tolerate it.
* Improves description of how to tolerate swap.
Closes: https://github.com/kubernetes/kubeadm/issues/2563
Addresses https://github.com/kubernetes/kubeadm/issues/2563#issuecomment-2312123413.
> [install-kubeadm]: Update instructions to disable or tolerate swap

- content/zh-cn/blog/_posts/2024-08-16-matchlabelkeys-podaffinity.md
```
content/zh-cn/blog/_posts/2024-08-16-matchlabelkeys-podaffinity.md
```
See [preview](https://deploy-preview-47751--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/16/matchlabelkeys-podaffinity/)
> [zh] Add a blog: 2024-08-16-matchlabelkeys-podaffinity.md

- content/en/docs/concepts/overview/working-with-objects/namespaces.md
Note block advising against the use of `kube-` prefixes was formatted as a mono space code block which stopped word wrapping.
Closes: #
> Update namespaces.md to remove monospace formatting in Note block

- assets/scss/_base.scss
- layouts/partials/docs/docs-portal-card.html
Drop some vestigial `<br>` elements from the docs portal page, and tweak how we do the styling.
Also avoid a repeated `id` value across different buttons.
Helps get us ready to use vanilla Docsy - see https://github.com/kubernetes/website/issues/41171
/priority backlog
[Before](https://k8s.io/docs) | [After](https://deploy-preview-47785--kubernetes-io-main-staging.netlify.app/docs/)
> Revise docs landing page (Docsy alignment)

- content/en/docs/reference/kubernetes-api/workload-resources/resource-slice-v1alpha3.md
The ListMeta stanza in the ResourceSliceList type was incorrectly customized to be `listMeta` when v1.30 was released. This problem has been fixed in https://github.com/kubernetes/kubernetes/pull/126749.
This PR updates the field name accordingly.
> Fix field name for ListMeta in API reference

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha3.md
Update this api doc from v1alpha2 to v1alpha3:
```
deleted: content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha2.md
added: content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-scheduling-context-v1alpha3.md
```
> [zh] Add pod-scheduling-context-v1alpha3.md

- content/en/docs/reference/kubernetes-api/service-resources/service-v1.md
The `trafficDistribution` field in Service has been graduated to Beta, however the upstream comment wasn't fixed when we generate the API reference for v1.31 (or more precisely, v1.30.0).
This nit has been fixed in https://github.com/kubernetes/kubernetes/pull/127117, and the change is effective in the 1.30 release branch.
This PR fixes the generated contents. 
closes: #47776
> Fix trafficDistribution status in Service v1

- content/zh-cn/docs/concepts/architecture/_index.md
Previously,
After
The after change version matches English version as well, https://kubernetes.io/docs/concepts/architecture/#kubelet
> [zh] Fix rendering error caused by {{< glossary >}} in concepts/architecture/#kubelet

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1alpha3.md
Update this api doc from v1alpha2 to v1alpha3:
```
deleted: content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1alpha2.md
added: content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1alpha3.md
```
See [preview](https://deploy-preview-47779--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1alpha3/).
> [zh] Sync resource-claim-template-v1alpha3.md

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/priority-level-configuration-v1.md
Update this API doc from v1beta3 to v1:
```
deleted: content/zh-cn/docs/reference/kubernetes-api/cluster-resources/priority-level-configuration-v1beta3.md
added: content/zh-cn/docs/reference/kubernetes-api/policy-resources/priority-level-configuration-v1.md
```
See [preview](https://deploy-preview-47813--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/policy-resources/priority-level-configuration-v1/).
> [zh] Add priority-level-configuration-v1.md

- assets/scss/_custom.scss
- content/en/community/code-of-conduct.html
- data/i18n/en/en.toml
- hugo.toml
- layouts/community/list.html
- layouts/partials/community_links.html
Adapt the existing page to work with (near-)vanilla Docsy.
Intended to help with https://github.com/kubernetes/website/issues/41171.
[Preview](https://deploy-preview-47415--kubernetes-io-main-staging.netlify.app/community/) | [existing](https://k8s.io/community)
> Use Docsy-friendly layout for community page

- content/zh-cn/blog/_posts/2024-08-14-moving-cgroup-v1-support-maintenance-mode-kubernetes-1-31.md
```
content/zh-cn/blog/_posts/2024-08-14-moving-cgroup-v1-support-maintenance-mode-kubernetes-1-31.md
```
See [preview](https://deploy-preview-47777--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/14/kubernetes-1-31-moving-cgroup-v1-support-maintenance-mode/)
> [zh] Add 2024-08-14-moving-cgroup-v1-support-maintenance-mode-kubernetes-1-31

- content/en/docs/reference/command-line-tools-reference/feature-gates/RemoveSelfLink.md
Moving 'removed' entry to the end as an implicit convention.
> Update RemoveSelfLink feature gate for readability

- content/en/docs/tutorials/services/source-ip.md
This PR updates the Docker image used in the [Source IP for Services tutorial](https://kubernetes.io/docs/tutorials/services/source-ip/) to `registry.k8s.io/echoserver:1.10`, replacing the deprecated version `1.4`. The existing image (`echoserver:1.4`) is no longer supported due to its use of Docker Image Format v1 and Docker Image manifest version 2, schema 1, which have been deprecated in Kubernetes. 
By updating to `echoserver:1.10`, this PR resolves image pull errors.
```plaintext
Warning  Failed     5m19s (x4 over 6m59s)  kubelet            Failed to pull image "registry.k8s.io/echoserver:1.4": [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release.
```
Updated the image in …
> Update Source IP Tutorial: Replace Deprecated echoserver:1.4 with echoserver:1.10 for Compatibility

- content/en/docs/concepts/extend-kubernetes/compute-storage-net/_index.md
Fixing a grammatical error in the Network plugins
paragraph. I chose to maintain consistency with
the preceding section, Device plugins.
Fixing the following grammatical error:
```
- A network plugin allow Kubernetes to work with different networking topologies and technologies.
+ Network plugins allow Kubernetes to work with different networking topologies and technologies.
```
> Fix grammatical error in Network plugins segment in "Compute, Storage, and Networking Extensions" document

- content/zh-cn/blog/_posts/2024-08-16-matchlabelkeys-podaffinity.md
Sync with en #47753 
```
content/zh-cn/blog/_posts/2024-08-16-matchlabelkeys-podaffinity.md
```
See [preview](https://deploy-preview-47870--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/16/matchlabelkeys-podaffinity/)
> [zh] Sync 2024-08-16-matchlabelkeys-podaffinity.md

- content/bn/examples/admin/dns/dnsutils.yaml
- content/en/examples/admin/dns/dnsutils.yaml
- content/id/examples/admin/dns/dnsutils.yaml
- content/zh-cn/examples/admin/dns/dnsutils.yaml
The jessie-dnsutils image is not maintained, but agnhost is and has all the same tools.
Closes: https://github.com/kubernetes/kubernetes/issues/126936
/cc @BenTheElder
> Change dnsutils from jessie-dnsutils to agnhost

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/min-domains-in-pod-topology-spread.md
k/k: https://github.com/kubernetes/kubernetes/pull/126863
/hold
/cc @sanposhiho 
/cc @sftim
The content of generated references is out of date. The latest commit is last year. 
- website: https://github.com/carlory/website/blob/MinDomainsInPodTopologySpread/content/en/docs/reference/kubernetes-api/workload-resources/pod-v1.md#L241
- api: https://github.com/carlory/kubernetes/blob/MinDomainsInPodTopologySpread/staging/src/k8s.io/api/core/v1/types.go#L4226
> mark feature-gate MinDomainsInPodTopologySpread as removed

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
- content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
Should be _Validation Ratcheting_ instead of _Validation Racheting_.
> Update typo in documentation

- content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
Support for Windows nodes set up with kubeadm is beta; make that clearer.
/sig windows
/language en
Relevant to https://github.com/kubernetes/enhancements/issues/995
> Mark Windows node support as beta

- static/_redirects
We have a page about Windows node setup. If there are legacy links or bookmarks, send people to the new page.
[_example_](https://deploy-preview-47912--kubernetes-io-main-staging.netlify.app/docs/setup/windows/user-guide-windows-nodes/)
Follows #47888
/sig windows
/kind cleanup
Done for English only
> Redirect legacy Windows node setup URLs to new page

- content/en/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
k/k: https://github.com/kubernetes/kubernetes/pull/126775
/hold
> remove feature-gate NewVolumeManagerReconstruction

- content/en/docs/concepts/storage/ephemeral-volumes.md
Image volume type falls under ephemeral volumes.
> added image volume type in ephemeral volumes

- content/ar/docs/setup/_index.md
This commit will fix a build error due to what seems to be a typo, where the term_id and text field for a glossary tooltip were switched.
See [this](https://app.netlify.com/sites/kubernetes-io-ar-staging/deploys/66db07e0492a630008d1f77f) build failure in #47819
> [ar] Fix build error due to bad tooltip label

- content/en/docs/concepts/cluster-administration/addons.md
Weave Scope is not mantained anymore. The link target is a website without valid TLS certificate and a generic hosting landing page (netlify). 
More information:
(https://github.com/weaveworks/scope
Closes: #
> Removed Weave Scope link

- content/en/docs/tasks/administer-cluster/kubeadm/adding-linux-nodes.md
- content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
We have two new pages about node setup. I expect that these will be popular, and also that some people will file issues about their confusion without having read the page properly. For some commands, you run them in a different shell on a different server that is part of the control plane.
Our readers are often smart, but they are also in a hurry.
- Make it extra clear that you need to run some commands in a different shell.
- Also be consistent about expecting use of `sudo`.
/language en
Follows PR #47888
> Emphasize that some kubeadm node setup commands run on control plane

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
While a container is not Ready, the `ReadinessProbe` may be executed at times other than the configured `periodSeconds` interval.
As discussed [here](https://github.com/kubernetes/kubernetes/issues/118815), it is not documented and makes confusion.
https://github.com/kubernetes/kubernetes/issues/118815
https://github.com/kubernetes/kubernetes/pull/119089#issuecomment-2278382891
> Add statement regarding ReadinessProbe manual run

- content/en/docs/tasks/administer-cluster/kubeadm/_index.md
- content/en/docs/tasks/administer-cluster/kubeadm/adding-linux-nodes.md
- content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
- content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
- content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md
- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
- content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- Change the order of pages within https://k8s.io/docs/tasks/administer-cluster/kubeadm/ ([_preview_](https://deploy-preview-47915--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/kubeadm/))
- Installing nodes before upgrading nodes
- Linux before Windows (alphabetical order per CNCF policy)
- overall upgrade advice before OS specific upgrade advice
- other appropriate(?) reordering
- Also, add brief text to that page that signposts readers to https://k8s.io/docs/setup/production-environment/tools/kubeadm/ if they don't have a cluster yet
/kind cleanup
/language en
> Reorganize task pages relevant to nodes and kubeadm

- content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
Updated information about empty toleration key in taint-and-toleration.md to match the API specification.
Closes: #47929
>  Fix wrong info about empty toleration key (#47929)

- content/en/docs/contribute/new-content/blogs-case-studies.md
closes #46821 
Other mentions of author metadata already follow the present norm.
> included author metadata in blog front matter

- content/zh-cn/docs/concepts/overview/components.md
- content/zh-cn/docs/concepts/workloads/pods/disruptions.md
- content/zh-cn/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md
content/zh-cn/docs/concepts/overview/components.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md
> [zh-cn] sync components disruptions validating-webhook-configuration-v1

- content/en/docs/concepts/services-networking/_index.md
Spun off from #41419 which in turn is spun off from #39890. Whee!
This _just_ focuses on improving the existing text, and doesn't (much) add anything to it (leaving that for the two older PRs).
The big problem with this page is that it is very very very old, and that shows in two main ways:
1. It is *super* focused on explaining Kubernetes networking to people who are used to 2015-era single-host docker networking, but it never actually explains that that's what it's contrasting against. I'm sure that when this was first written, it was incredibly helpful, but at this point, it is just confusing to the vast majority of readers.
2. Especially toward the end of the doc, the hyperlinks are very weird. It looks like this is the result of gradual refactoring of the docs; someone linked to …
> Rewrite "The Kubernetes network model"

- layouts/shortcodes/feature-state.html
Fix feature-state shortcode for accurate feature gate rendering within tabs
- Adjusted shortcode logic to correctly render feature gates and their states.
- Ensured compatibility with nested tab structures, resolving issues with displaying feature gates inside tabs.
Closes: #47934
> Fix 'feature-state' shortcode for accurate rendering in tabs

- content/zh-cn/docs/reference/access-authn-authz/bootstrap-tokens.md
- content/zh-cn/docs/reference/glossary/container-runtime-interface.md
- content/zh-cn/docs/reference/glossary/cri.md
content/zh-cn/docs/reference/access-authn-authz/bootstrap-tokens.md
content/zh-cn/docs/reference/glossary/container-runtime-interface.md
content/zh-cn/docs/reference/glossary/cri.md
> [zh-cn] sync bootstrap-tokens container-runtime-interface cri

- content/en/docs/concepts/services-networking/_index.md
- Provide bullets with consistent indentations
- Put url text into a single line
- Minor changes like using "pod" consistently in lowercase in the middle of the sentence
/kind cleanup
See [preview](https://deploy-preview-47982--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/)
> Clean up services-networking/_index.md

- content/zh-cn/docs/tasks/administer-cluster/encrypt-data.md
- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> [zh-cn] sync encrypt-data configure-liveness-readiness-startup-probes

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-rules-review-v1.md
content/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1.md
> [zh-cn] sync self-subject-rules-review-v1.md

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/replication-controller-v1.md
content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1.md
content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/replication-controller-v1.md
> [zh-cn] sync cluster-role-v1 role-v1 replication-controller-v1

- content/en/docs/concepts/architecture/garbage-collection.md
This PR clarifies the use of finalizers during a background cascading deletion. It also clarifies what type of controllers are being referred to.
Closes: #47956
> Clarify Finalizer Usage and Controller Types in Background Cascading Deletion

- content/en/blog/_posts/2024-09-06-sig-scheduling-spotlight.md
- content/en/blog/_posts/2024-09-17-sig-scheduling-spotlight.md
Add SIG Scheduling Spotlight. This mirrors https://github.com/kubernetes/contributor-site/pull/520 , where the initial review is being made. 
Suggestions should be made there first so that they can be synced backed here.
> Add SIG Scheduling spotlight

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1.md
Add some zh text to:
```
content/zh-cn/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1.md
```
See [preview](https://deploy-preview-48013--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1/)
> [zh] Sync an API doc: subject-access-review-v1.md

- content/en/docs/concepts/storage/storage-classes.md
This PR updates the example of StorageClass for the AWS EBS CSI driver by adding the following **previously available but undocumented in k8s** tag specifications:
- `tagSpecification: "key1=value1"`
The tags will be applied to dynamically provisioned EBS volumes for better resource tracking and management.
> Update AWS EBS Storage Class Example

- content/en/docs/concepts/workloads/pods/init-containers.md
I have made the Init container concepts from both Pod and Deployment perspective.
and This is my first contribution and let me know if any changes needs to be done on PR.
Issue
Fixes: https://github.com/kubernetes/website/issues/38271
> Clarify init container concept

- content/pt-br/docs/tasks/tools/install-kubectl-linux.md
This PR solves #47748 , updating the `pt-br` documentation for installing kubectl on Linux.
Updated content/pt-br/docs/tasks/tools/install-kubectl-linux.md to sync it with `en` docs.
Closes: #47748
> [pt-br] Update docs/tasks/tools/install-kubectl-linux.md

- content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
Clarified the ambiguous sentence regarding the conditions when multiple `topologySpreadConstraints` are set.
Fixes: https://github.com/kubernetes/kubernetes/issues/127305
/language en
/sig docs scheduling
> Fix ambiguous sentence about topologySpreadConstraints

- content/ko/docs/tasks/administer-cluster/change-default-storage-class.md
- content/ko/docs/tasks/administer-cluster/change-pv-reclaim-policy.md
- content/ko/docs/tasks/administer-cluster/cluster-upgrade.md
- content/ko/docs/tasks/administer-cluster/coredns.md
- content/ko/docs/tasks/administer-cluster/declare-network-policy.md
- content/ko/docs/tasks/administer-cluster/dns-horizontal-autoscaling.md
- content/ko/docs/tasks/administer-cluster/enable-disable-api.md
- content/ko/docs/tasks/administer-cluster/extended-resource-node.md
Related Issue: #41631
Updated outdated files in `content/en/docs/tasks/administer-cluster/`.
**11 files to be modified**
M127, M128은 이미 변경 사항이 적용되어 있습니다. https://github.com/kubernetes/website/issues/41631#issuecomment-1678902282
그리고 M134는 단순 영문 오탈자 수정입니다.
> [ko] Update outdated files in dev-1.27-ko.1 (M127-M137)

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
While the super-admin.conf change was introduced, looks like we forgot to update this particular section of the kubeadm-certs.md.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#generate-kubeconfig-files-for-control-plane-components
The above section already has the right info.
> kubeadm-certs: fix wrong info about admin.conf

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-binding-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-binding-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
> [zh-cn] sync role-binding-v1 daemon-set-v1

- content/en/docs/concepts/scheduling-eviction/_index.md
The description and its proceeding text on the scheduling index page https://kubernetes.io/docs/concepts/scheduling-eviction/ are almost duplicated. The change in this PR is to remove one of the descrption block.
This will fix #48126 
Links:
- Page having duplicate content: https://kubernetes.io/docs/concepts/scheduling-eviction/
- Fixed Page after PR changes: https://deploy-preview-48132--kubernetes-io-main-staging.netlify.app/docs/concepts/scheduling-eviction
> Remove duplicate description paragraph from scheduling index page

- content/zh-cn/docs/setup/production-environment/_index.md
Removed a leading slash on an absolute URL in the zh docs that is causing Hugo builds to fail for me and a bad link in the doc.
Closes: #48140
> Removes leading slash on absolute link to etcd docs in zh docs

- content/en/docs/concepts/architecture/garbage-collection.md
Clarifies the best-effort nature of the garbage collector controller behavior honoring `blockOwnerDeletion` in sync error and race conditions scenarios.
/assign @deads2k 
https://github.com/kubernetes/kubernetes/pull/125796 makes the best-effort nature even more clear in 1.32, but this was always best-effort and subject to races on creation, so we should document that.
> Clarify foreground deletion behavior of the GC controller in race and sync error conditions

- content/zh-cn/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md
Fixes a zh translated blog post with a repetition of `https://`
Closes: #48144
> [zh] Removed extra https:// prepended to a link in a blog

- content/en/_index.html
This PR makes the "attend KubeCon" links up-to-date on the main page. It removes the past KubeCon China event and adds an upcoming European one in 2025.
> Update KubeCon 2024-2025 events

- content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
Removed the note from the https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ page as given solution in comment https://github.com/kubernetes/website/issues/47818#issuecomment-2334088987
Closes https://github.com/kubernetes/website/issues/47818
> Remove deprecated note on  "Set up a High Availability etcd Cluster with kubeadm" page

- content/en/docs/reference/labels-annotations-taints/_index.md
Closes #47044 
**Problem**: The annotation `resource.kubernetes.io/pod-claim-name` is unregistered, but used in Kubernetes code.
**Changes**:  Registered the annotation, by mentioning it in [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/).
**Additional Information**:
Required for https://github.com/kubernetes/enhancements/issues/3063
> Register Annotation resource.kubernetes.io/pod-claim-name 

- OWNERS_ALIASES
cc: @kubernetes/steering-committee 
ref: https://github.com/kubernetes/steering/issues/286
/assign @natalisucks @saschagrunert @divya-mohan0209
> steering: Onboard/offboard members following 2024 election results

- content/en/docs/reference/access-authn-authz/kubelet-authn-authz.md
This PR adds the `checkpoint` subresource to the kubelet authorization documentation which was introduced with kubernetes 1.25 as alpha, and graduated to beta in 1.30.
Preview: https://deploy-preview-48012--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/kubelet-authn-authz/
> Add checkpoint subresource to Kublet authorization doc

- content/en/blog/_posts/2024-10-02-steering-committee-results-2024.md
Adding mirror of election blog post; merge only after reconciling with any updates that happen before https://github.com/kubernetes/contributor-site/pull/535 is merged.
/hold
> Adding mirror of election blog post

- content/ko/docs/concepts/workloads/controllers/cron-jobs.md
- content/ko/docs/concepts/workloads/controllers/daemonset.md
- content/ko/docs/concepts/workloads/controllers/deployment.md
- content/ko/docs/concepts/workloads/controllers/job.md
- content/ko/docs/concepts/workloads/controllers/replicaset.md
- content/ko/docs/concepts/workloads/controllers/replicationcontroller.md
- content/ko/docs/concepts/workloads/controllers/statefulset.md
- content/ko/docs/concepts/workloads/controllers/ttlafterfinished.md
- Related Issue : https://github.com/kubernetes/website/issues/41631
> M74. `content/en/docs/concepts/workloads/controllers/cron-jobs.md` | 145(+L) 70(-)
M75. `content/en/docs/concepts/workloads/controllers/daemonset.md` | 52(+M) 43(-)
M76. `content/en/docs/concepts/workloads/controllers/deployment.md` | 394(+L) 378(-)
M77. `content/en/docs/concepts/workloads/controllers/job.md` | 162(+L) 121(-)
M78. `content/en/docs/concepts/workloads/controllers/replicaset.md` | 23(+S) 20(-)
M79. `content/en/docs/concepts/workloads/controllers/replicationcontroller.md` | 9(+XS) 3(-)
M80. `content/en/docs/concepts/workloads/controllers/statefulset.md` | 3(+XS) 3(-)
M81. `content/en/docs/concepts/workloads/controllers/ttlafterfinished.md` | 47(+M) 35(-)
> [ko] Update outdated korean contents in dev-1.27-ko.1 (M74-M81)

- content/ko/docs/concepts/cluster-administration/addons.md
- content/ko/docs/concepts/cluster-administration/logging.md
- content/ko/docs/concepts/cluster-administration/manage-deployment.md
- content/ko/docs/concepts/cluster-administration/system-logs.md
- content/ko/docs/concepts/cluster-administration/system-traces.md
- Related Issue : https://github.com/kubernetes/website/issues/41631
M14 : 문서의 변동사항이 없어 수정하지 않았습니다.
이전에 같은 내용으로 PR을 올렸는데, 머지되지 않고 Fork한 Repository를 삭제해버려서
같은 내용으로 다시 생성했습니다.
이전 PR : https://github.com/kubernetes/website/pull/41694
> [ko] Update outdated files in dev-1.27-ko.1 [M10-15]

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
- content/zh-cn/docs/tutorials/security/apparmor.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
> [zh-cn]sync setup-ha-etcd-with-kubeadm apparmor

- content/zh-cn/docs/reference/kubernetes-api/authentication-resources/token-review-v1.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/namespace-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/token-review-v1.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/namespace-v1.md
> [zh-cn] sync token-review-v1 namespace-v1

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
- Keep the style consistent
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
```
See [preview](https://deploy-preview-48046--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1/)
> [zh] Sync an API doc: persistent-volume-v1.md

- content/de/docs/tasks/tools/install-kubectl-linux.md
The kubectl install guide for linux (debian) will contain the correct shell scripts and repository urls in the german documentation.
There is no open german localization branch as far as I can tell.
> fix apt repo urls in german kubectl install guide

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1.md
```
content/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1.md
```
See [preview](https://deploy-preview-48121--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/)
> [zh] Sync self-subject-access-review-v1.md

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attributes-class-v1beta1.md
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attributes-class-v1beta1.md
```
See [preview](https://deploy-preview-48133--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attributes-class-v1beta1/)
> [zh] Add an API doc: volume-attributes-class-v1beta1.md

- content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
This PR adds additional keywords to the *Migrating Deployments and StatefulSets to horizontal autoscaling* section of the Horizontal Pod Autoscaler page to aid users in troubleshooting. This will help users who are not reading the documentation in its entirety but rather skimming it and searching for keywords.
This suggestion stems from an issue I had when troubleshooting a migration to HPA.
N/A
> Update horizontal-pod-autoscale.md with additional keywords

- content/en/docs/reference/glossary/duration.md
* This PR adds a glossary entry for **Duration** to clarify its usage in Kubernetes APIs. 
* The entry defines a duration as a time interval specified in Go's `time.Duration` format, highlights the requirement for non-negativity, and provides examples of valid expressions. 
* This addition aims to enhance user understanding of duration fields within the Kubernetes API.
Closes: #47909
> Add “duration” to glossary

- OWNERS_ALIASES
As the 1.32 Release Docs lead, I would like to add myself to the approver list for the dev-1.32 branch
> Approval permission for 1.32 Release

- content/en/blog/_posts/2024-09-17-sig-scheduling-spotlight.md
Perform changes to:
- Use a consistent expression for `SIG Scheduling`
- Use relative path for URL and put link text on a single line
- Provide indentations for bullets
- Fix some typos and remove redundant spaces
See [preview](https://deploy-preview-48044--kubernetes-io-main-staging.netlify.app/blog/2024/09/24/sig-scheduling-spotlight-2024/)
> Clean up a new blog: 2024-09-17-sig-scheduling-spotlight

- OWNERS_ALIASES
It looks like I'm a website owner from a moment when we thought I'd need to help release 1.31. Removing this now.
I can stay on as an english reviewer and might be able to help out. That depends on the bandwidth of the Release Signal team I'm leading right now though! :)
(cc: @Princesso do you want to stay on as an english reviewer? FYSA you're still on this list)
> fix: Drew should not be a website owner

- content/en/docs/concepts/overview/working-with-objects/names.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/retry-generate-name.md
Promote the RetryGenerateName feature to GA
/hold
until https://github.com/kubernetes/kubernetes/pull/127093 merges
> Promote RetryGenerateName to GA in 1.32

- content/zh-cn/docs/reference/kubernetes-api/common-definitions/delete-options.md
- content/zh-cn/docs/reference/kubernetes-api/common-definitions/label-selector.md
- content/zh-cn/docs/reference/kubernetes-api/common-definitions/object-meta.md
Update 3 zh files:
```
content/zh-cn/docs/reference/kubernetes-api/common-definitions/delete-options.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/label-selector.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/object-meta.md
```
> [zh] Sync common-definitions/object-meta, delete-options, and label-selector

- content/en/docs/concepts/security/linux-kernel-security-constraints.md
- content/en/docs/reference/node/_index.md
- content/en/docs/reference/node/seccomp.md
- content/en/docs/tasks/administer-cluster/securing-a-cluster.md
- content/en/examples/pods/security/seccomp/fields.yaml
Adding a node reference page about seccomp.
Fixes #47687
Preview: https://deploy-preview-47967--kubernetes-io-main-staging.netlify.app/docs/reference/node/seccomp/
> Add dedicated seccomp node reference

- content/en/docs/reference/node/_index.md
- content/en/docs/reference/node/kubelet-files.md
Refrence page on files being used and written by the kubelet.
/sig node
> outline files kubelet uses

- content/en/docs/tasks/configure-pod-container/share-process-namespace.md
attaching doesn't work -
when i run kubectl attach -it nginx -c shell
I get
If you don't see a command prompt, try pressing enter.
and pressing enter doens't help
Proposed Solution : -
kubectl exec -it nginx -c shell -- /bin/sh
this command is working fine
#46478
> Changed the command for Attaching to the shell container

- content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
With https://github.com/kubernetes/kubernetes/pull/124123 in 1.31, it is possible to write `kubectl create something` plugins by providing a `kubectl-create-something` binary. This PR adds the documentation.
xref https://kubernetes.slack.com/archives/CTJNMDM24/p1728488438493869
> kubectl: document create plugins

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/load-balancer-ip-mode.md
Update the docs about promoting LoadBalancerIPMode to GA.
xref:
[KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1860-kube-proxy-IP-node-binding)
kubernetes/kubernetes#127348
> Promote LoadBalancerIPMode to GA

- content/en/docs/concepts/security/multi-tenancy.md
This change removes a reference to the kiosk project from the multi tenancy page as this project appears to have been archived by its owners.
> Update the multi tenancy docs to remove reference to archived project

- content/en/docs/reference/using-api/cel.md
- Remove redundant spaces from those relatively big markdown tables
- Put the link text and its url on a single line
- Changes about bullets, consistency, and typo
See [preview](https://deploy-preview-48296--kubernetes-io-main-staging.netlify.app/docs/reference/using-api/cel/)
> Clean up using-api/cel.md

- content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
- Replace url with zh-cn version if available
- Fix rendering issues by adding blank lines
- Some minor changes about translation
in
```
content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
```
> [zh] update service-resources/service-v1.md

- content/en/docs/concepts/containers/_index.md
Marc Brooker has written [a blog post](https://brooker.co.za/blog/2023/06/19/container.html) explaining that "container" means different thing to different people, and that it should be checked whether audience and narrator use the same definition. Below are his four suggested definition. Given the authority of Kubernetes, I suggest this nuance to be mentioned. So readers are more informed and take cautionary acts to ensure they are synced with their audience. I've added it. 
> - An approach to packaging an application along with its dependencies (sometimes a whole operating system user space), that can then run on a minimal runtime environment with a clear contract.
> - A set of development, deployment, architectural, and operational approaches built around applications packaged this …
> Explain nuances of the term "container"

- content/en/docs/reference/glossary/manifest.md
- content/en/docs/reference/using-api/api-concepts.md
Revise https://k8s.io/docs/reference/using-api/api-concepts/
[_Preview_](https://deploy-preview-46230--kubernetes-io-main-staging.netlify.app/docs/reference/using-api/api-concepts/#alternate-representations-of-resources)
- Add section about JSON encoding for API
- Mention that the HTTP API doesn't use YAML
- Add links to JSON, YAML and Protobuf
/wg api-expression
/language en
> Add more detail about media types

- content/en/docs/reference/using-api/api-concepts.md
This is the changes made to the wrong content detail at https://kubernetes.io/docs/reference/using-api/api-concepts/#json-encoding
which was first incorrectly written as `Content-Type: json` and is now changed to `Content-Type: application/json`
Closes: #48303
> Fix incorrect content type in API reference page

- content/en/docs/concepts/workloads/pods/sidecar-containers.md
Adding information about sidecar termination behavior and linking existing documentation to https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-containers-and-pod-lifecycle 
Closes: #48290
> adding docs and link for sidecar termination behaviour

- content/zh-cn/blog/_posts/2024-08-21-cgroup-driver-from-cri.md
fixed: #48297
Translate Chinese version for blog：2024-08-21-cgroup-driver-from-cri.md
Preview：https://deploy-preview-48300--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/21/cri-cgroup-driver-lookup-now-beta/
> [zh-cn] add 2024-08-21-cgroup-driver-from-cri.md chinese version

- content/en/docs/reference/node/kernel-version-requirements.md
- content/en/docs/tasks/administer-cluster/sysctl-cluster.md
This should be merged after https://github.com/kubernetes/kubernetes/pull/127489 was merged.
xref https://github.com/kubernetes/kubernetes/issues/125234
> Safe Sysctl 1.32 sync: net.ipv4.rmem and net.ipv4.wmem

- content/en/docs/concepts/workloads/controllers/ttlafterfinished.md
I don't believe that `selector-selector` is an actual k8s term. This appears to be the only usage of the term throughout the English localization of the docs, so I imagine it was just a typo introduced in https://github.com/kubernetes/website/pull/37595.
No corresponding issue created
> Fix typo of selector-selector

- content/en/docs/reference/glossary/network-policy.md
- content/en/docs/reference/glossary/node.md
- content/en/docs/reference/glossary/pod-template.md
* This is the first part of resolving the issue regarding core objects in the Kubernetes glossary.
*  In this PR, I have included necessary API kinds that are built into Kubernetes as core objects, such as Node, PodTemplate, and NetworkPolicy.
#45972
> Include missing core object in glossary

- content/en/docs/concepts/cluster-administration/system-metrics.md
This PR correct the doc for metrics cardinality enforcement
1. Use correct flag name as `allow-metric-labels` following the [flag definition](https://github.com/kubernetes/kubernetes/blob/c15581b277e9e42d830898357fdbd92dcf7981c6/staging/src/k8s.io/component-base/metrics/options.go#L81)
2. Use correct manifest pattern following the [flag process function](https://github.com/kubernetes/kubernetes/blob/c15581b277e9e42d830898357fdbd92dcf7981c6/staging/src/k8s.io/component-base/metrics/opts.go#L365 )
Closes: #
> fix: update the doc for metrics cardinality enforcement

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
This PR fixes the fragment in the URL for OpenAPI v3 schemas.
This is needed because GitHub changed the way it renders markdown into HTML, in particular how it renders multi-word anchors. This change was made over a year ago. The spec repo itself merged a PR that fixes the cross-references, https://github.com/OAI/OpenAPI-Specification/pull/3548, 8 months ago.
Closes: #
> Fix schema URL fragment in custom-resource-definitions.md

- data/releases/schedule.yaml
The October patch releases have been delayed for October 22, 2024, as stated in https://groups.google.com/a/kubernetes.io/g/dev/c/ycnFVQwOlz8/m/o_ML2JsNAAAJ
This PR updates the schedule file to reflect that.
/assign @jeremyrickard @puerco 
> Change date for October 2024 releases

- content/en/docs/reference/glossary/cloud-controller-manager.md
- content/en/docs/reference/glossary/dynamic-volume-provisioning.md
- content/en/docs/reference/glossary/qos-class.md
- content/en/docs/reference/glossary/quantity.md
- content/en/docs/reference/glossary/taint.md
- content/en/docs/reference/glossary/volume-plugin.md
- content/en/docs/reference/glossary/volume.md
* This is the second part of resolving the issue regarding core objects in the Kubernetes glossary.
* First part of issue is PR #48318 for adding core objects in glossary.
* In this PR, I have removed objects that aren't core object kinds: 
Quantity (not an API kind that you can create using kubectl etc)
Dynamic Volume Provisioning (not an API kind at all)
Cloud Controller Manager (a binary, not an API kind)
Taint (a fundamental concept, but not an API kind)
Volume (not an API kind that you can create using kubectl etc)
Volume Plugin (not an API kind at all)
QoS Class (not an API kind) 
* Issue - https://github.com/kubernetes/website/issues/45972
#45972
> Remove the object from glossary which are not part of core objects

- content/ru/README.md
> [ru] Delete Localization READMEs section in localized README

- content/en/docs/tutorials/_index.md
- content/en/docs/tutorials/cluster-management/_index.md
- content/en/docs/tutorials/cluster-management/kubelet-standalone.md
Wrote a Tutorial [[preview](https://deploy-preview-48094--kubernetes-io-main-staging.netlify.app/docs/tutorials/cluster-management/kubelet-standalone/)] with step-by-step instructions on how to install and configure the Kubelet to run in standalone mode.
Fixes #47402
> Add Tutorial Running Kubelet in Standalone Mode

- content/en/docs/contribute/new-content/open-a-pr.md
Fix an issue with https://kubernetes.io/docs/contribute/new-content/open-a-pr/ where the local preview showed up with HTTPS.
It's actually plain HTTP, eg http://localhost:1313 - so fix that difference.
> Fix wrong URL scheme for local preview

- content/uk/README.md
> [uk] Delete Localization READMEs section in localized README

- content/ja/README.md
/kind cleanup
/approve
Closes: #
> [ja] Delete Localization READMEs section in localized README

- content/bn/README.md
> [bn] Delete Localization READMEs section in localized README

- content/en/docs/reference/glossary/cluster-operator.md
If you expand https://kubernetes.io/docs/reference/glossary/?user-type=true#term-cluster-operator you see a link to the operator pattern, but it's an off site link back from before I wrote https://kubernetes.io/docs/concepts/extend-kubernetes/operator/
We should change that glossary entry so that it links to https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ instead. 
Closes: #48404
> Link from cluster operator glossary entry to operator pattern page

- content/en/docs/concepts/storage/persistent-volumes.md
Contains update to add a link to the right hand navigation of
https://kubernetes.io/docs/concepts/storage/persistent-volumes/ that links to the API reference for PersistentVolumeClaim.
Verification link https://deploy-preview-48391--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/persistent-volumes/
Closes #48334
> Link to PVC API reference from "Persistent Volumes" concept page

- content/en/docs/contribute/new-content/new-features.md
- provide bullets with a consistent look
- fix a typo: `Feature gates for Alpha/Feature` to `Feature gates for Alpha/Beta`
See [preview](https://deploy-preview-48414--kubernetes-io-main-staging.netlify.app/docs/contribute/new-content/new-features/)
> Clean up new-content/new-features.md

- content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html
The text states:
"We hit a different Pod with every request. This demonstrates that the load-balancing is working."
Everything worked fine as followed by the tutorial but how do we know or actually see that a different Pod was invoked for the multiple curl requests?
Nothing is demonstrated or confirms that multiple Pods were involved. Is there a log trace somewhere or a command execution history logged where we can actually see the "demonstration" that multiple Pods were involved in the scaling or is it just blind trust?
output added : -
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-wp67j | v=1
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-hs9dj | v=1
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-4hjvf | v=1 …
> Add sample output to Kubernetes introductory tutorial (scaling)

- content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
Sync with en #48003 
```
content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
```
See [preview](https://deploy-preview-48455--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro/)
> [zh] Sync scale/scale-intro.html

- assets/scss/_custom.scss
- content/en/releases/patch-releases.md
- data/i18n/en/en.toml
- data/releases/eol.yaml
- data/releases/schedule.yaml
- layouts/shortcodes/eol-releases.html
- layouts/shortcodes/release-branches.html
- layouts/shortcodes/upcoming-releases.html
Improve https://kubernetes.io/releases/patch-releases/ especially around date rendering.
- Here's a [preview](https://deploy-preview-46368--kubernetes-io-main-staging.netlify.app/releases/patch-releases/) link for English.
- Here's a [preview](https://deploy-preview-46368--kubernetes-io-main-staging.netlify.app/bn/releases/patch-releases/) link for Bangla / Bengali.
> Improve patch releases page

- content/en/docs/tasks/administer-cluster/topology-manager.md
- fix typos
- keep terms consistent like `kubelet` and `Topology Manager`
- remove redundant spaces
- fix a link anchor
See [preview](https://deploy-preview-48458--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/topology-manager/)
/kind cleanup
> Clean up topology-manager.md

- content/en/docs/reference/using-api/api-concepts.md
* Kubernetes API server supports [YAML](https://yaml.org/) (for encoding request bodies, or for a negotiated response format), but the documentation says it does not.
* In this PR new section for `application/yaml` is added and removed the note saying YAML for encoding request bodies is not supported.
Closes: #48317
> Add application/yaml section in api-concepts

- content/zh-cn/docs/concepts/workloads/controllers/cron-jobs.md
Fix incorrect crontab expression in Chinese translation of cron-jobs docs.
```
```
> [zh-cn] Fix crontab expression in /controllers/cron-jobs.md translation
