hugo.toml

Updating hugo.toml for release v1.30.
/hold until v1.30 release day.

Updates v1.28 hugo.toml for v1.30 release

---

hugo.toml

Updating hugo.toml for release v1.30.
/hold until v1.30 release day.

Updates v1.27 hugo.toml for v1.30 release 

---

hugo.toml

Updating hugo.toml for release v1.30.
/hold until v1.30 release day.

Updates v1.26 hugo.toml for v1.30 release

---

content/zh-cn/docs/tasks/tools/included/verify-kubectl.md

The file `content/en/docs/tasks/tools/included/verify-kubectl.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45852) ,so we will synchronize the localization.

 [zh] sysc verify-kubectl.md

---

content/de/docs/tasks/tools/included/verify-kubectl.md

en PR https://github.com/kubernetes/website/pull/45852/files

[de] Utilize code style for inline command

---

content/en/blog/_posts/2024-04-17-kubernetes-1.30.md

Fix broken link in K8s 1.30 Release blog post

fix release team link in 1.30 release blog post

---

content/es/docs/tasks/tools/included/verify-kubectl.md

en PR https://github.com/kubernetes/website/pull/45852/files

[es] Utilize code style for inline command

---

content/en/blog/_posts/2024-04-25-structured-authentication-configuration-beta.md
content/en/blog/_posts/2024-04-29-structured-authentication-configuration-beta.md

Feature blog post for KEP 3331: https://git.k8s.io/enhancements/keps/sig-auth/3331-structured-authentication-configuration

Add blog post for Structured Authn beta

---

content/en/blog/_posts/2024-02-21-prevent-unauthorized-volume-mode-conversion-ga.md

~Placeholder~ PR for volume mode conversion stable blog post
KEP - https://github.com/kubernetes/enhancements/issues/3141

Add blog article about volume mode conversion going GA

---

content/bn/includes/federation-deprecation-warning-note.md

Optional document translation
fixes issue : https://github.com/kubernetes/website/issues/44993

[bn] localize content/bn/includes/federation-deprecation-warning-note.md

---

content/en/blog/_posts/2024-04-17-kubernetes-1.30.md

Add SIG Auth enhancements - Structured Authn/z in v1.30 release blog

Add SIG Auth enhancements in v1.30 release blog

---

content/en/blog/_posts/2024-04-17-kubernetes-1.30.md

Add SIG API Machinery enhancements - Storage Version Migration in v1.30 release blog
/assign @enj @deads2k @jpbetz

docs: adds SVM details to enhancement blog post

---

content/fr/docs/tasks/tools/install-kubectl.md

 fr: fix broken link to kubectl

---

content/zh-cn/docs/concepts/architecture/garbage-collection.md
content/zh-cn/docs/concepts/architecture/nodes.md

[zh-cn] sync nodes garbage-collection

---

content/zh-cn/docs/concepts/configuration/configmap.md
content/zh-cn/docs/setup/production-environment/container-runtimes.md

content/zh-cn/docs/concepts/configuration/configmap.md
content/zh-cn/docs/setup/production-environment/container-runtimes.md

[zh-cn] sync container-runtimes configmap

---

content/zh-cn/docs/tasks/configure-pod-container/security-context.md

content/zh-cn/docs/tasks/configure-pod-container/security-context.md

[zh-cn] sync security-context

---

content/en/docs/tutorials/stateful-application/basic-stateful-set.md

Improvements to https://k8s.io/docs/tutorials/stateful-application/basic-stateful-set
~I'll split this into several commits. Feel free to provide feedback before that happens~. This is what's left after I split out some PRs.

Revise StatefulSet tutorial

---

content/en/docs/reference/labels-annotations-taints/_index.md

documented last-change-trigger-time

---

data/i18n/en/en.toml
layouts/case-studies/single.html

Make case study title prefix localizable (also, switch to title case).

Make case study title prefix localizable

---

content/en/docs/reference/kubectl/quick-reference.md

Adding a few helpful commands for <https://kubernetes.io/docs/reference/kubectl/generated/kubectl_debug/>

Add debug references

---

content/en/docs/reference/using-api/server-side-apply.md

resolve: https://github.com/kubernetes/website/issues/45751

Explain SSA JSON/YAML compatibility bug

---

content/en/docs/concepts/architecture/cgroups.md

Update the stale link for memory Qos

---

content/zh-cn/docs/home/_index.md
content/zh-cn/docs/home/supported-doc-versions.md
content/zh-cn/docs/tasks/configure-pod-container/user-namespaces.md

content/zh-cn/docs/home/_index.md
content/zh-cn/docs/home/supported-doc-versions.md
content/zh-cn/docs/tasks/configure-pod-container/user-namespaces.md

[zh-cn] sync home/* user-namespaces

---

content/id/docs/concepts/services-networking/ingress.md

[id] Fix link

---

content/zh-cn/docs/concepts/architecture/cgroups.md

The file `content/en/docs/concepts/architecture/cgroups.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45935) ,so we will synchronize the localization.

[zh]Update cgroups.md with correct link to MemoryQoS feature

---

content/zh-cn/docs/concepts/workloads/controllers/deployment.md

[zh-cn] sync Deployment with en

---

content/zh-cn/docs/concepts/workloads/controllers/statefulset.md

[zh-cn] sync StatefulSet with en

---

content/en/docs/reference/using-api/api-concepts.md

Fixed the typo in Kubernetes API concepts

---

content/en/docs/concepts/services-networking/ingress-controllers.md

Update Hyperlink of `Easegress IngressController` in [Ingress Controllers](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) documentation. 
Fixes #45962

Updated Hyperlink of Easegress IngressController

---

content/ja/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/ja/examples/pods/probe/http-liveness.yaml

ja equivalent for https://github.com/kubernetes/website/pull/45837

[ja] Switch liveness image to multi-arch agnhost container image

---

content/zh-cn/docs/concepts/workloads/controllers/daemonset.md

[zh-cn] sync DaemonSet with en

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

Some minor wording changes to address [comment in the previous PR](https://github.com/kubernetes/website/pull/45833/files#r1570805824) from @sftim.

Minor update to Akri description

---

content/zh-cn/docs/concepts/services-networking/ingress-controllers.md

The file `content/en/docs/concepts/services-networking/ingress-controllers.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45976) ,so we will synchronize the localization.

[zh]Update Easegress IngressController hyperlink

---

content/en/docs/reference/command-line-tools-reference/kubelet.md

Resync kubelet reference for 1.30

---

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
content/zh-cn/docs/concepts/overview/working-with-objects/field-selectors.md
content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
content/zh-cn/docs/concepts/workloads/controllers/statefulset.md

[zh-cn]sync network-plugins field-selectors replicaset statefulset

---

content/zh-cn/docs/concepts/architecture/leases.md
content/zh-cn/docs/concepts/policy/limit-range.md
content/zh-cn/docs/concepts/services-networking/endpoint-slices.md
content/zh-cn/docs/concepts/workloads/controllers/replicationcontroller.md
data/i18n/zh-cn/zh-cn.toml

Update docs:
- Lease
- LimitRange
- EndpointSlice
- ReplicationController

[zh-cn] sync only update `api_metadata` docs

---

content/zh-cn/docs/concepts/overview/kubernetes-api.md
content/zh-cn/docs/concepts/policy/_index.md
content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
content/zh-cn/docs/tutorials/hello-minikube.md

[zh-cn]sync policy kubernetes-api kubeadm-config.v1beta3 hello-minikube apiserver-audit.v1

---

content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md

Update `minDomains` note description.

[zh-cn] sync `Pod Topology Spread Constraints`

---

content/pt-br/docs/concepts/services-networking/ingress.md

[pt] Fix link

---

content/bn/examples/application/deployment-sidecar.yaml

Adding  deployment-sidecar.yaml in bangla version

[bn] Adding  deployment-sidecar.yaml in bn version

---

content/bn/docs/reference/_index.md

update Content/bn/docs/reference/ index.md for bangla 

[bn] update Content/bn/docs/reference/ index.md

---

content/zh-cn/docs/reference/node/kubelet-config-directory-merging.md

```
content/zh-cn/docs/reference/node/kubelet-config-directory-merging.md
```
See [preview](https://deploy-preview-46058--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/node/kubelet-config-directory-merging/) please.

[zh] Add kubelet-config-directory-merging.md

---

content/zh-cn/docs/concepts/workloads/controllers/cron-jobs.md

There seems a typo here, It should be `cron-job-limitations`.

[zh] Sync controllers/cron-jobs.md

---

content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md

[zh] Sync admission-controllers.md and extensible-admission-controllers.md

---

content/en/docs/tasks/administer-cluster/kubelet-config-file.md

- Provide a consistent appearance for ordered list 
- Change some wrapping style
- No any text changed
[Current Online Page](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#viewing-the-kubelet-configuration) | [Changes Preview](https://deploy-preview-46064--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/kubelet-config-file/#viewing-the-kubelet-configuration)
/kind cleanup

Make a task prettier: kubelet-config-file

---

content/zh-cn/docs/tasks/administer-cluster/kubelet-config-file.md

[zh-cn] sync kubelet-config-file.md

---

content/zh-cn/docs/concepts/storage/persistent-volumes.md

[zh-cn] sync persistent-volumes

---

content/zh-cn/docs/reference/using-api/api-concepts.md
content/zh-cn/docs/reference/using-api/cel.md
content/zh-cn/docs/reference/using-api/deprecation-guide.md
content/zh-cn/docs/reference/using-api/health-checks.md
content/zh-cn/docs/reference/using-api/server-side-apply.md

- `content/en/docs/reference/using-api/api-concepts.md`
- `content/en/docs/reference/using-api/cel.md`
- `content/en/docs/reference/using-api/deprecation-guide.md`
- `content/en/docs/reference/using-api/health-checks.md`
- `content/en/docs/reference/using-api/server-side-apply.md`

[zh-cn] Sync docs/reference/using-api

---

content/ja/docs/concepts/services-networking/ingress.md

[ja] Fix link

---

OWNERS_ALIASES

This commit will add seifrajhi  as an owner (approver) and reviewer for Arabic content on the website.

Add seifrajhi as approver and reviewer for Arabic localisations docs

---

content/de/training/_index.html

[de] Ready training section for vanilla Docsy

---

content/en/_index.html
content/en/docs/contribute/style/style-guide.md

This PR adds "cloud native" and "open source" to the style guide to establish a standard within the project. Current usage across the site is inconsistent.
Also addresses a singular usage of "open-source" on the homepage.
/assign @natalisucks

Update style guide

---

content/zh-cn/docs/concepts/overview/working-with-objects/common-labels.md

The file `content/en/docs/concepts/overview/working-with-objects/common-labels.md` has been updated in this PR (https://github.com/kubernetes/website/pull/45585) ,so we will synchronize the localization.

[zh]Update common-labels.md with corrected instance names

---

content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md

The list has grown beyond four, and may keep growing in the future

Correction: More than four types are available

---

content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
content/zh-cn/docs/tasks/run-application/configure-pdb.md

content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
content/zh-cn/docs/tasks/run-application/configure-pdb.md

[zh-cn]sync extend-service-ip-ranges configure-pdb

---

content/zh-cn/docs/concepts/workloads/pods/_index.md

[zh-cn] sync pods/_index.md

---

content/ar/docs/_index.md

This PR adds the minimal translation related to the file _index.md and splitting the old https://github.com/kubernetes/website/pull/44902 to smaller
Part of https://github.com/kubernetes/website/issues/37546 and https://github.com/kubernetes/website/issues/44682

[ar] Translate index to arabic

---

content/ar/docs/setup/production-environment/tools/_index.md

Added translation for `setup/production-environment/tools/_index.md`

[ar] Localize setup/production-environment/tools/_index.md

---

content/zh-cn/docs/contribute/style/style-guide.md
content/zh-cn/docs/tasks/debug/debug-cluster/_index.md

content/zh-cn/docs/tasks/debug/debug-cluster/_index.md

[zh-cn] sync style-guide debug-cluster/_index

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/rotate-kubelet-client-certificate.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/rotate-kubelet-server-certificate.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/run-as-group.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/runtime-class.md

Add zh text to 4 new feature gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/rotate-kubelet-client-certificate.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/rotate-kubelet-server-certificate.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/run-as-group.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/runtime-class.md
```

[zh] Add 4 feature-gates: r*.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/admission-webhook-match-conditions.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-self-subject-review.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/crd-validation-ratcheting.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/hpa-container-metrics.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/identify-pod-os.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/image-maximum-gc-age.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-clean-up.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-log-query.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-host-ips.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-jti.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stable-load-balancer-node-set.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/structured-authentication-configuration.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/structured-authorization-configuration.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/translate-stream-close-websocket-requests.md

Sync with en text in 15 feature gates, mainly about front matters

[zh] Sync 15 feature gates for reference

---

content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md

content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md

[zh-cn] sync kube-controller-manager-config.v1alpha1 kube-scheduler-config.v1

---

content/zh-cn/docs/concepts/cluster-administration/system-traces.md
content/zh-cn/docs/concepts/security/pod-security-standards.md
content/zh-cn/docs/concepts/security/security-checklist.md
content/zh-cn/docs/concepts/security/service-accounts.md

[zh-cn] sync pod-security-standards security-checklist service-accounts system-traces

---

content/zh-cn/docs/tutorials/security/apparmor.md

[zh-cn] sync security/apparmor.md

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md

content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md

[zh-cn]sync kube-apiserver.md

---

content/zh-cn/releases/_index.md

- `content/en/releases/_index.md`

[zh-cn] sync releases/_index.md

---

content/zh-cn/docs/concepts/services-networking/dual-stack.md

[zh] sync services-networking/dual-stack.md

[zh] sync services-networking/dual-stack.md

---

content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
content/zh-cn/examples/customresourcedefinition/shirt-resource-definition.yaml
content/zh-cn/examples/customresourcedefinition/shirt-resources.yaml

[zh-cn]sync custom-resource-definitions.md

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md

content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md

[zh-cn] sync kube-proxy.md

---

content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md

content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md

[zh-cn]sync kubelet.md

---

content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md

The file `content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md` has been updated in this PR (https://github.com/kubernetes/website/pull/46115) ,so we will synchronize the localization.

[zh] Sync dynamic-resource-allocation.md

---

content/zh-cn/blog/_posts/2024-04-23-recursive-read-only-mounts.md

content/zh-cn/blog/_posts/2024-04-23-recursive-read-only-mounts.md

[zh-cn] Localization blog: 2024-04-23-recursive-read-only-mounts.md

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-join.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-join.md

[zh-cn]sync kubeadm_upgrade_plan kubeadm-init kubeadm-join

---

content/zh-cn/docs/reference/kubectl/introduction.md

```
content/zh-cn/docs/reference/kubectl/introduction.md
```
See [preview](https://deploy-preview-46056--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubectl/introduction/) please.

[zh] Add kubectl/introduction.md

---

content/en/docs/concepts/services-networking/ingress.md
content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/volumes.md

- `ingress.md` remove redundant closing spaces

Remove redundant closing spaces

---

content/zh-cn/docs/concepts/cluster-administration/node-shutdown.md

```
content/zh-cn/docs/concepts/cluster-administration/node-shutdown.md
```
See [preview](https://deploy-preview-46080--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/node-shutdown/) please.

[zh] Add cluster-administration/node-shutdown.md

---

content/en/docs/tutorials/kubernetes-basics/update/update-intro.html

Following tutorial step by step at this point service is not defined.

check-service-exists

---

content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
content/zh-cn/docs/concepts/storage/persistent-volumes.md
content/zh-cn/examples/pods/pod-with-affinity-preferred-weight.yaml

[zh-cn]sync assign-pod-node persistent-volumes

---

content/zh-cn/docs/concepts/services-networking/ingress.md
content/zh-cn/docs/concepts/storage/dynamic-provisioning.md

content/zh-cn/docs/concepts/services-networking/ingress.md
content/zh-cn/docs/concepts/storage/dynamic-provisioning.md

[zh-cn]sync ingress dynamic-provisioning

---

content/zh-cn/blog/_posts/2024-02-21-prevent-unauthorized-volume-mode-conversion-ga.md

content/zh-cn/blog/_posts/2024-02-21-prevent-unauthorized-volume-mode-conversion-ga.md

[zh-cn]Locatlization blog:2024-02-21-prevent-unauthorized-volume-mode-conversion-ga.md

---

content/ja/docs/tasks/tools/_index.md

Fixes #45855 
This pull request is for the translation of the latest `content/en/docs/tasks/tools/_index.md`.
Preview: https://deploy-preview-46030--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/tools/

[ja] Translate content/ja/docs/tasks/tools/_index.md

---

content/ja/docs/reference/glossary/statefulset.md

close https://github.com/kubernetes/website/issues/42310
- Corrected the Japanese translation to match the original "deployment" content\ja\docs\reference\glossary\statefulset.md

[ja] Localization of StatefulSet concept uses wrong term

---

content/zh-cn/docs/concepts/workloads/pods/_index.md
content/zh-cn/docs/concepts/workloads/pods/ephemeral-containers.md

content/zh-cn/docs/concepts/workloads/pods/ephemeral-containers.md

[zh-cn] sync pods/_index.md ephemeral-containers.md

---

content/ja/docs/home/_index.md

Closes: https://github.com/kubernetes/website/issues/46096

[ja] Add button for About the documentation in `content/ja/docs/home/_index.md`

---

content/bn/community/code-of-conduct.md

Fixes : https://github.com/kubernetes/website/pull/46048#discussion_r1586552479
Related Issue : https://github.com/kubernetes/website/issues/44993

[bn] update commit hash no in /bn/community/code-of-conduct.md

---

content/bn/case-studies/_index.html

[bn] update case-studies /_index.html

---

content/bn/docs/contribute/_index.md

[bn] Update  bn/docs/contribute _index.md

---

content/bn/training/_index.html

[bn] Localize training / index.html

---

content/it/training/_index.html

[it] Ready training section for vanilla Docsy

---

content/en/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

- Use a consistent format in the front matter
- Fix those text with wave error prompts in the markdown editing mode, by adding blank lines or punctuations
- Use `" "` instead of `' '` for field values in YAML
/kind cleanup
See [preview](https://deploy-preview-46201--kubernetes-io-main-staging.netlify.app/docs/tasks/manage-kubernetes-objects/storage-version-migration/) please.

Make the markdown prettier: storage-version-migration.md

---

content/zh-cn/docs/concepts/cluster-administration/networking.md

The file `content/en/docs/concepts/cluster-administration/networking.md`has been updated in this PR (https://github.com/kubernetes/website/pull/45464) ,so we will synchronize the localization.

[zh] Update networking.md

---

content/zh-cn/docs/concepts/workloads/pods/disruptions.md
content/zh-cn/docs/concepts/workloads/pods/init-containers.md
content/zh-cn/docs/concepts/workloads/pods/pod-qos.md

content/zh-cn/docs/concepts/workloads/pods/pod-qos.md

[zh-cn] sync disruptions init-containers pod-qos

---

content/zh-cn/docs/concepts/services-networking/service.md

[zh-cn]sync services-networking/service

---

content/pl/training/_index.html

[pl] Ready training section for vanilla Docsy

---

content/zh-cn/docs/concepts/workloads/management.md

Localize docs/concepts/workloads/management.md
Preview: https://deploy-preview-46028--kubernetes-io-main-staging.netlify.app/

[zh-cn] Localize docs/concepts/workloads/management.md

---

content/zh-cn/training/_index.html

[zh] Ready training section for vanilla Docsy

---

content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

Added zh text to this new page and applied changes in #46201 :
```
content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md
```
See [preview](https://deploy-preview-46200--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration/) please.

[zh] Add storage-version-migration.md

---

assets/scss/_base.scss
assets/scss/_custom.scss
assets/scss/_skin.scss
assets/scss/_variables_project.scss
static/css/glossary.css
static/css/style_apiref.css
static/css/training.css

Per https://github.com/kubernetes/kubernetes/blob/1dc30bf/logo/colors.md, our RGB blue color is #326CE5. Use that.

Use correct shade of Kubernetes blue

---

content/en/docs/reference/setup-tools/kubeadm/implementation-details.md

- Replace short notes with `{{< note >}} Hugo style {{< /note >}}`
- Improve the grammar and wording for the entire page
See [preview](https://deploy-preview-46235--kubernetes-io-main-staging.netlify.app/docs/reference/setup-tools/kubeadm/implementation-details/) please.

Clean up kubeadm/implementation-details.md

---

content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md
content/zh-cn/docs/tutorials/configuration/configure-redis-using-configmap.md

content/zh-cn/docs/tutorials/configuration/configure-redis-using-configmap.md

[zh-cn]sync container-lifecycle-hooks configure-redis-using-configmap

---

OWNERS_ALIASES

Please note that this PR is **not open for comments from the deleted ALIASES** and is a follow-up PR to #44217 since I messed up the commit history.
The changes suggested by the PR are long overdue & will be revisited at the end of this year during the annual cleanup activity.
cc: @seokho-son @a-mccarthy @reylejano @natalisucks @tengqm

Updating OWNERS_ALIASES with final changes

---

content/ja/training/_index.html

[ja] Ready training section for vanilla Docsy

---

content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md

Fixes #46188 
Preview: https://deploy-preview-46207--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/tools/install-kubectl-macos/

[ja] Update content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md

---

content/zh-cn/docs/reference/config-api/apiserver-admission.v1.md
content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md

content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md

[zh-cn] sync apiserver-admission.v1 imagepolicy.v1alpha1

---

content/bn/docs/reference/glossary/node.md

[bn] Localize glossary entry for "Node"

---

content/bn/docs/reference/glossary/control-plane.md

Localized control-plane.md in Bengali Language.
Fixes issue:#45729

[bn] Localize control-plane.md

---

content/bn/docs/reference/glossary/daemonset.md

Localized daemonset.md in Bengali.
Fixes issue: #45729

[bn] Localize daemonset.md

---

content/en/docs/concepts/architecture/leases.md

Fix link to 'Node heartbeats' section

---

content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md

content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md

[zh-cn] sync ingress-minikube.md

---

content/zh-cn/examples/service/networking/example-ingress.yaml

The file `content/en/docs/tasks/access-application-cluster/ingress-minikube.md` has been updated in this PR (https://github.com/kubernetes/website/pull/46239) ,so we will synchronize the localization.

[zh]Update host in example-ingress.yaml to hello-world.example

---

README-bn.md
README.md

Updating README-bn.md and adding 'Bengali' option in README.md

[bn] Updating README-bn.md and  README.md

---

content/en/docs/tutorials/security/apparmor.md

Mainly fix the rendering issue of an unordered list:
[Current Online Page](https://kubernetes.io/docs/tutorials/security/apparmor/#appArmorProfile)｜ [Preview Changes](https://deploy-preview-46301--kubernetes-io-main-staging.netlify.app/docs/tutorials/security/apparmor/#appArmorProfile)

Fix lists in apparmor.md

---

OWNERS_ALIASES
SECURITY_CONTACTS

Adding salaxander as a SIG docs tech lead 
CC @natalisucks @divya-mohan0209 @reylejano

docs: add salaxander as SIG docs tech lead

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md

[zh-cn]sync kubeadm_init_phase_upload-certs kubeadm_join_phase_control-plane-prepare_all

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md

[zh] sync/pods/pod-lifecycle.md

[zh] sync/pods/pod-lifecycle.md

---

content/zh-cn/docs/reference/glossary/immutable-infrastructure.md
content/zh-cn/docs/reference/glossary/sidecar-container.md

Add zh text to 2 new glossary:
```
content/zh-cn/docs/reference/glossary/immutable-infrastructure.md
content/zh-cn/docs/reference/glossary/sidecar-container.md
```

[zh] Add two glossary: immutable-infrastructure and sidecar-container

---

content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md

[zh] Sync kubeadm/implementation-details.md

---

content/ar/docs/contribute/localization.md

Add existing terminology from : 
- CNCF https://github.com/cncf/glossary/blob/dev-ar/content/ar
- Spreadsheets https://docs.google.com/spreadsheets/d/1Biw8HzSvPSp02lTDDv2JwJQzGFanFcATh_YCgyS61c8

[ar] Add Arabic terms into localization glossary

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md

[zh-cn]sync kubeadm_init kubeadm_init_phase_control-plane_apiserver

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-scheduling-readiness.md

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-scheduling-readiness.md

[zh-cn]sync feature-gates/p*

---

content/ru/docs/tutorials/kubernetes-basics/explore/explore-intro.html

Fixed: proxy port for the pod in the example
en version:
https://github.com/kubernetes/website/blob/be4f4b9e334d6b151715e5ff951d65dfa5169bc8/content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html#L157

[ru] fixed example port: *8080

---

content/zh-cn/docs/reference/_index.md
content/zh-cn/docs/reference/kubectl/_index.md
content/zh-cn/docs/reference/kubectl/kubectl.md
content/zh-cn/docs/reference/kubectl/quick-reference.md

content/zh-cn/docs/reference/_index.md
content/zh-cn/docs/reference/kubectl/quick-reference.md
content/zh-cn/docs/reference/kubectl/_index.md
content/zh-cn/docs/reference/kubectl/quick-reference.md

[zh-cn] sync kubectl/_index kubectl quick-reference reference/_index

---

content/zh-cn/docs/reference/glossary/cri-o.md
content/zh-cn/docs/reference/glossary/index.md
content/zh-cn/docs/reference/glossary/priority-class.md
content/zh-cn/docs/reference/glossary/spec.md

Sync 4 glossary files:
```
content/zh-cn/docs/reference/glossary/cri-o.md
content/zh-cn/docs/reference/glossary/index.md
content/zh-cn/docs/reference/glossary/priority-class.md
content/zh-cn/docs/reference/glossary/spec.md
```

[zh] Sync 4 files in reference/glossary

---

content/de/docs/tutorials/hello-minikube.md

[de] Ready Hello, Minikube page for vanilla Docsy

---

OWNERS_ALIASES
SECURITY_CONTACTS

Adding myself as SIG Docs tech lead!

Add Kat Cosgrove as SIG Docs tech lead

---

content/zh-cn/blog/_posts/2024-04-11-SIG-Architecture-Code-Organization-Spotlight.md

content/zh-cn/blog/_posts/2024-04-11-SIG-Architecture-Code-Organization-Spotlight.md

[zh-cn] Locaization blog: 2024-04-11-SIG-Architecture-Code-Organization-Spotlight.md

---

content/ko/docs/tasks/tools/included/verify-kubectl.md

en PR https://github.com/kubernetes/website/pull/45852/files

[ko] Utilize code style for inline command

---

content/ko/training/_index.html

[ko] Ready training section for vanilla Docsy

---

content/ko/docs/tutorials/configuration/configure-redis-using-configmap.md

en PR https://github.com/kubernetes/website/pull/44396/files

[ko] Update configure-redis-using-configmap.md

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-start.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-start.md

[zh-cn] sync kubeadm_init_phase_kubelet-start

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/daemon-set-update-surge.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/default-host-network-ports-in-pod-templates.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/default-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/delegate-fs-group-to-csi-driver.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/device-plugins.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-accelerator-usage-metrics.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/downward-api-huge-pages.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dry-run.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-auditing.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-kubelet-config.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-provisioning-scheduling.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-volume-provisioning.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kube-proxy-draining-terminating-nodes.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/load-balancer-ip-mode.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/min-domains-in-pod-topology-spread.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/remove-self-link.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding-validation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-pod-node-info.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-aware-hints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-manager-policy-alpha-options.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/user-namespaces-support.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/validating-admission-policy.md

[zh-cn] sync feature-gates/d* m* v* l* s* t* r* u* k*

---

content/it/docs/home/supported-doc-versions.md
data/i18n/it/it.toml

Align https://kubernetes.io/es/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/
/language it

[it] Update list of versions to match English

---

content/zh-cn/blog/_posts/2024-04-24-validating-admission-policy-ga/index.md
content/zh-cn/blog/_posts/2024-04-24-validating-admission-policy-ga/webhook.go

```
content/zh-cn/blog/_posts/2024-04-24-validating-admission-policy-ga/
```
See [preview](https://deploy-preview-46187--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/04/24/validating-admission-policy-ga/) please.

[zh] Add a blog: 2024-04-24-validating-admission-policy-ga/

---

content/en/docs/tasks/administer-cluster/encrypt-data.md
content/en/docs/tasks/administer-cluster/kms-provider.md

Fixes https://github.com/kubernetes/kubernetes/issues/122563
/cc @enj @aramase

docs: updates automatics reloading behaviour.

---

content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
content/zh-cn/docs/reference/networking/ports-and-protocols.md

content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
content/zh-cn/docs/reference/networking/ports-and-protocols.md

[zh-cn] sync client-authentication.v1beta1 ports-and-protocols

---

content/zh-cn/docs/tasks/administer-cluster/kms-provider.md
content/zh-cn/docs/tasks/administer-cluster/kubelet-config-file.md

content/zh-cn/docs/tasks/administer-cluster/kms-provider.md

[zh-cn] sync kms-provider kubelet-config-file

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_preflight.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_preflight.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md

[zh-cn]sync kubeadm_join_phase_preflight kubeadm_upgrade_apply

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/aggregated-discovery-endpoint.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/cloud-dual-stack-node-ips.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/contextual-logging.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/topology-manager-policy-options.md

[zh-cn] sync feature-gates/*

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/volumes.md

k/k: https://github.com/kubernetes/kubernetes/pull/124544 (merged)
preview: https://deploy-preview-46363--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/volumes/#cephfs

update cephfs volume

---

content/ja/docs/reference/glossary/cidr.md

close https://github.com/kubernetes/website/issues/45112
- Translate [content/en/docs/reference/glossary/cidr.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/cidr.md) into Japanese

[ja] Localization of content/ja/docs/reference/glossary/cidr.md

---

content/en/docs/concepts/scheduling-eviction/assign-pod-node.md

Definitions of Gt and Lt mixed up but now amended

Update assign-pod-node.md - Gt and Lt definition amendment for nodeAffinity

---

content/vi/docs/home/supported-doc-versions.md

Align https://kubernetes.io/vi/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/
[Preview](https://deploy-preview-46381--kubernetes-io-main-staging.netlify.app/vi/docs/home/supported-doc-versions/) of the updated page.
/language vi

[vi] Update list of versions to match English

---

content/zh-cn/blog/_posts/2024-04-28-contribute-as-sig-docs-reviewer.md

```
content/zh-cn/blog/_posts/2024-04-28-contribute-as-sig-docs-reviewer.md
```
See [preview](https://deploy-preview-46396--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/05/16/contribute-as-sig-docs-reviewer/) here.

[zh] Localize 2024-04-28-contribute-as-sig-docs-reviewer.md

---

content/en/docs/reference/instrumentation/cri-pod-container-metrics.md

Changed term-id from cri to container-runtime-interface

---

content/en/blog/_posts/2024-04-25-structured-authentication-configuration-beta.md

Fix CA in authentication example

---

content/ko/docs/home/supported-doc-versions.md

Align https://kubernetes.io/ko/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/
[Preview ](https://deploy-preview-46353--kubernetes-io-main-staging.netlify.app/ko/docs/home/supported-doc-versions/)of the updated page.
/language ko

[ko] Update list of versions to match English

---

content/en/docs/concepts/cluster-administration/flow-control.md

content/en/docs/concepts/cluster-administration/flow-control.md

improve cluster-administration/flow-control format

---

content/zh-cn/docs/tutorials/security/apparmor.md

[zh-cn] sync apparmor.md

---

content/zh-cn/docs/concepts/cluster-administration/flow-control.md

[zh] Sync cluster-administration/flow-control.md

---

content/zh-cn/blog/_posts/2024-04-25-structured-authentication-configuration-beta.md

```
content/zh-cn/blog/_posts/2024-04-25-structured-authentication-configuration-beta.md
```
See [preview](https://deploy-preview-46369--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/04/25/structured-authentication-moves-to-beta/)

[zh] Localize 2024-04-25-structured-authentication-configuration-beta.md

---

content/pt-br/docs/contribute/localization_pt-br.md

WIP: Add pt-BR localization glossary (and other instructions)

[pt-br] Add pt-BR localization contributor guide

---

content/es/docs/tutorials/hello-minikube.md

[es] Ready Hello, Minikube page for vanilla Docsy

---

content/bn/docs/tutorials/hello-minikube.md

Sync with en #45938
[Current glossary page](https://k8s.io/bn/docs/tutorials/hello-minikube/) | [Preview glossary page](https://deploy-preview-46436--kubernetes-io-main-staging.netlify.app/bn/docs/tutorials/hello-minikube/)

[bn] Ready Hello, Minikube page for vanilla Docsy

---

content/zh-cn/docs/reference/instrumentation/cri-pod-container-metrics.md

content/zh-cn/docs/reference/instrumentation/cri-pod-container-metrics.md

[zh-cn] sync cri-pod-container-metrics

---

content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md

kubeadm: add corednsdeployment as a patch target
Ref: https://github.com/kubernetes/kubernetes/pull/124820

kubeadm: add corednsdeployment as a patch target

---

content/bn/docs/reference/glossary/index.md

Sync with en #45937 
[Current glossary page](https://k8s.io/bn/docs/reference/glossary/) | [Preview glossary page](https://deploy-preview-46435--kubernetes-io-main-staging.netlify.app/bn/docs/reference/glossary/)

[bn] Ready glossary page for vanilla Docsy

---

content/ja/docs/tutorials/hello-minikube.md

[ja] Ready Hello, Minikube page for vanilla Docsy

---

content/zh-cn/docs/tutorials/hello-minikube.md

en PR: https://github.com/kubernetes/website/pull/46443/

[zh-cn] Sync hello-minikube.md

---

content/zh-cn/docs/reference/config-api/kubelet-config.v1beta1.md

content/zh-cn/docs/reference/config-api/kubelet-config.v1beta1.md

[zh-cn] sync kubelet-config.v1beta1.md

---

content/zh-cn/docs/reference/node/kubelet-checkpoint-api.md
content/zh-cn/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md

- `content/en/docs/reference/node/kubelet-checkpoint-api.md`
- `content/en/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md`

[zh-cn] sync reference/node content

---

content/zh-cn/blog/_posts/2024-04-22-userns-beta/index.md

```
content/zh-cn/blog/_posts/2024-04-22-userns-beta/index.md
```
See [preview](https://deploy-preview-46457--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/04/22/userns-beta/)

[zh] Localize a blog: 2024-04-22-userns-beta/

---

content/en/blog/_posts/2024-02-22-k8s-book-club/index.md

- Remove redundant `-` from front matter
- Put link text and its url on a single line in an editing mode

Fix dashes in front matter to 2024-02-22-k8s-book-club

---

content/uk/docs/tutorials/hello-minikube.md

[uk] Ready Hello, Minikube page for vanilla Docsy

---

content/zh-cn/docs/tasks/tools/install-kubectl-linux.md

[zh] Sync tasks/tools/install-kubectl-linux.md

---

content/zh-cn/docs/reference/scheduling/config.md

Sync with en text.
```
content/zh-cn/docs/reference/scheduling/config.md
```

[zh] Sync reference/scheduling/config.md

---

content/pl/docs/reference/glossary/index.md

[pl] Ready glossary page for vanilla Docsy

---

content/zh-cn/blog/_posts/2024-05-20-cloud-provider-migration.md

content/zh-cn/blog/_posts/2024-05-20-cloud-provider-migration.md

[zh-cn] Localize blog: 2024-05-20-cloud-provider-migration.md

---

content/ko/docs/concepts/cluster-administration/addons.md

[ko] Update Weave Net link to newly supported fork

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-self-subject-review.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/csi-migration-azure-file.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/expanded-dns-config.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/experimental-host-user-namespace-defaulting.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ip-tables-ownership-cleanup.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources-get-allocatable.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-pod-resources.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-tracking.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/minimize-ip-tables-restore.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/proxy-terminating-endpoints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/security-context-deny.md

[zh] Sync feature gates removed in 1.30

---

content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md

[zh] polish etcd backup doc

---

content/zh-cn/docs/concepts/containers/images.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_coredns.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_coredns.md

[zh-cn] sync images kubeadm_init_phase_addon_coredns

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_download-certs.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_download-certs.md

[zh-cn]sync kubeadm_join_phase_control-plane-prepare_download-certs

---

content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Sync with en version and update some text:
```
content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
```
See [preview](https://deploy-preview-46516--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro/)

[zh] Sync kubernetes-basics/scale/scale-intro.html

---

content/ru/docs/reference/glossary/index.md

[ru] Ready glossary page for vanilla Docsy

---

content/zh-cn/docs/reference/config-api/client-authentication.v1.md

[zh-cn] sync client-authentication.v1.md

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md

[zh-cn] sync pod-lifecycle

---

content/zh-cn/docs/concepts/services-networking/service.md

[zh] Sync services-networking/service.md

---

content/zh-cn/docs/reference/access-authn-authz/authentication.md

[zh-cn] sync authentication.md

---

content/de/docs/reference/glossary/index.md

[de] Ready glossary page for vanilla Docsy

---

content/zh-cn/docs/reference/access-authn-authz/authorization.md

content/zh-cn/docs/reference/access-authn-authz/authorization.md

[zh-cn] sync authorization.md

---

content/ja/docs/tasks/configure-pod-container/configure-gmsa.md

Fixes #45342 
Preview: https://deploy-preview-46535--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/configure-pod-container/configure-gmsa/

[ja] Translate content/ja/docs/tasks/configure-pod-container/configure-gmsa.md

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_kubeconfig.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_kubeconfig.md

[zh-cn] sync kubeadm_join kubeadm_join_phase_control-plane-prepare_kubeconfig

---

content/en/docs/concepts/overview/working-with-objects/_index.md

Fix grammar in "Objects In Kubernetes" page

---

content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md

/kind feature
/language es
/sig docs
/assign 
@ramrodo
@electrocucaracha
resolves #44739

[es] Added content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md

---

content/es/docs/reference/glossary/index.md

[es] Ready glossary page for vanilla Docsy

---

data/i18n/es/es.toml

Add new translations and fix spelling/grammer errors.

[es] Update es.toml 

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Use the latest version instead of v1.28.

Bump cri-tools version to v1.30.0

---

content/zh-cn/docs/concepts/overview/working-with-objects/_index.md

Sync with en #46565 
```
content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
```

[zh] Sync overview/working-with-objects/_index.md

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

[zh] Sync kubeadm/install-kubeadm.md

---

content/en/docs/reference/instrumentation/node-metrics.md

Fix glossary tooltip link for 'Container Runtime Interface' text

---

content/en/docs/concepts/policy/resource-quotas.md

Fixes : https://github.com/kubernetes/kubernetes/issues/125188

Updated the ResourceQuota doc for NodePort and LoadBalancer

---

content/id/docs/reference/glossary/index.md

[id] Ready glossary page for vanilla Docsy

---

content/en/docs/concepts/architecture/garbage-collection.md

Backport of the fixes already merged in the main branch in #46588.

[release-1.29]: Fixed kubelet option ImageMaximumGCAge example for garbage-collection page

---

content/zh-cn/docs/concepts/architecture/garbage-collection.md

[zh] Sync architecture/garbage-collection.md

---

content/zh-cn/docs/reference/instrumentation/node-metrics.md

content/zh-cn/docs/reference/instrumentation/node-metrics.md

[zh-cn] sync node-metrics.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-swap.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_annotate/_index.md

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/node-swap.md

[zh-cn] sync node-swap kubectl_annotate/_index

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability.md

[zh] Modify ambiguous sentences in high-availability.md

---

content/hi/docs/reference/glossary/index.md

[hi] Ready glossary page for vanilla Docsy

---

content/zh-cn/docs/tasks/administer-cluster/kubelet-config-file.md

[zh] Sync administer-cluster/kubelet-config-file.md

---

content/ja/docs/reference/glossary/code-contributor.md

[ja] Translate code contributor definition

---

content/ja/docs/reference/glossary/index.md

[ja] Ready glossary page for vanilla Docsy

---

content/zh-cn/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md

content/zh-cn/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md

[zh-cn]sync update-api-object-kubectl-patch.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_version/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_version/_index.md

[zh-cn] Localize generated/kubectl_version

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_uncordon/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_uncordon/_index.md

[zh-cn] Localize generated/kubectl_uncordon

---

content/zh-cn/docs/concepts/policy/resource-quotas.md

content/zh-cn/docs/concepts/policy/resource-quotas.md

[zh-cn] sync resource-quotas.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_api-resources/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_api-resources/_index.md

[zh-cn] Localize generated/kubectl_api-resources

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_attach/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_attach/_index.md

[zh-cn] Localize generated/kubectl_attach

---

content/ko/docs/reference/glossary/index.md

[ko] Ready glossary page for vanilla Docsy

---

content/ko/_index.html

[ko] add searchbar to index page

---

content/ko/docs/concepts/architecture/mixed-version-proxy.md

Translate Concepts/Architecture/Mixed Version Proxy into Korean
from #45395

[ko] Translate Concepts/Architecture/Mixed Version Proxy into Korean

---

content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

resolve https://github.com/kubernetes/website/pull/45296/files

[ko] Update link

---

content/ko/docs/tutorials/hello-minikube.md

[ko] Ready Hello, Minikube page for vanilla Docsy

---

OWNERS_ALIASES

As a follow-up to issue #46434 and per our conversation with @celestehorgan, this PR introduces the following changes:
- @anubha-v-ardhan is offboarded as an approver and reviewer of the Hindi localisation
- @dipesh-rawat is added as an approver and reviewer of the Hindi localisation
- @celestehorgan is offboarded as an approver and reviewer of the English website.
cc: @seokho-son @a-mccarthy @reylejano @natalisucks 
/sig docs

Updating Hindi localisation maintainers and PR wrangler for English

---

content/ja/docs/concepts/workloads/controllers/statefulset.md

Fixes https://github.com/kubernetes/website/issues/46572

[ja] fix Stable Storage section in Japanese

---

content/en/docs/tasks/administer-cluster/reserve-compute-resources.md

- 📖 Add a link to how to change kubelet settings
- 🗑️ Remove mention of k8s 1.17
- 🧹  Remove deprecated CLI flags and replace by KubeletConfiguration settings ; and properly document defaults
- 👍 properly document enforcement (`enforceNodeAllocatable` should be set)

Improve "Reserve Compute Resources for System Daemons" doc

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_cp/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_cp/_index.md
```

[zh] Localize kubectl/generated/kubectl_cp/

---

content/zh-cn/docs/reference/kubectl/generated/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl.md

Add zh text to 2 files:
```
content/zh-cn/docs/reference/kubectl/generated/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl.md
```

[zh] Add index.md and kubectl.md to kubectl/generated

---

content/fr/docs/tasks/access-application-cluster/service-access-application-cluster.md
content/fr/examples/service/access/hello-application.yaml

This PR updates the docker image used in the page "Utiliser un Service pour accéder à une application dans un cluster". It is similar to https://github.com/kubernetes/website/pull/46553
[Before](https://kubernetes.io/fr/docs/tasks/access-application-cluster/service-access-application-cluster/)
[After](https://deploy-preview-46645--kubernetes-io-main-staging.netlify.app/fr/docs/tasks/access-application-cluster/service-access-application-cluster/)

Update node-hello image to Google's newer image

---

content/uk/docs/reference/glossary/index.md

[uk] Ready glossary page for vanilla Docsy

---

content/es/docs/concepts/architecture/leases.md

/kind feature
/language es
/sig docs
resolves #45698

[es] Added docs/concepts/architecture/leases to Spanish

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_api-versions/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_api-versions/_index.md

[zh-cn] Localize generated/kubectl_api-versions

---

content/pt-br/docs/reference/glossary/index.md

[pt] Ready glossary page for vanilla Docsy

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md
```

[zh] Add kubectl/generated/kubectl_cordon/

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md
```

[zh] Add kubectl/generated/kubectl_label/

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_logs/_index.md

[zh] Add kubectl/generated/kubectl_logs/

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_completion/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_completion/_index.md

[zh-cn] Localize generated/kubectl_completion

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_exec/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_exec/_index.md

[zh-cn] Localize generated/kubectl_exec

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_options/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_options/_index.md

[zh-cn] Localize generated/kubectl_options

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_plugin/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_plugin/_index.md

[zh-cn] Localize kubectl_plugin/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/_index.md

[zh-cn] Localize kubectl_set/_index.md

---

content/zh-cn/docs/tasks/administer-cluster/reserve-compute-resources.md

Sync with en #45771 
```
content/zh-cn/docs/tasks/administer-cluster/reserve-compute-resources.md
```

[zh] Sync a task: reserve-compute-resources.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrolebinding.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrolebinding.md
```

[zh] Add kubectl_create_clusterrolebinding.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_configmap.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_configmap.md
```

[zh] Add kubectl_create_configmap.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_top/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_top/_index.md

[zh-cn] Localize kubectl_top/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrole.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrole.md
```

[zh] Add kubectl_create/kubectl_create_clusterrole.md

---

content/fr/docs/reference/glossary/index.md

Glossary's index was missing for localized french.
Building local hugo would then fail.

[fr] Localized docs/reference/glossary/index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_namespace.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_namespace.md
```

[zh] Add kubectl_create_namespace.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_serviceaccount.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_serviceaccount.md

[zh-cn] Add kubectl_create_serviceaccount.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/_index.md

[zh-cn] Localize kubectl_cluster-info/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_role.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_role.md
```

[zh] Add kubectl_create_role.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/_index.md

[zh-cn] Localize kubectl_certificate/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/_index.md

[zh-cn] Localize kubectl_config/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service.md

[zh-cn] Add kubectl_create_service.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret.md

[zh-cn] Add kubectl_create_secret.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_job.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_job.md
```

[zh] Add kubectl_create_job.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_priorityclass.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_priorityclass.md
```

[zh] Add kubectl_create_priorityclass.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_rolebinding.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_rolebinding.md
```

[zh] Add kubectl_create_rolebinding.md

---

content/de/docs/concepts/architecture/cgroups.md

en PR https://github.com/kubernetes/website/pull/45935/files

[de] Update the stale link for memory Qos

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_cronjob.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_cronjob.md
```

[zh] Add kubectl_create_cronjob.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_poddisruptionbudget.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_poddisruptionbudget.md
```

[zh] Add kubectl_create_poddisruptionbudget.md

---

content/fr/docs/concepts/services-networking/ingress.md

[fr] Fix link

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_nodeport.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_nodeport.md

[zh-cn] Add kubectl_create_service_nodeport.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_loadbalancer.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_loadbalancer.md

[zh-cn] Add kubectl_create_service_loadbalancer.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_current-context.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_current-context.md

[zh-cn] Add kubectl_config_current-context.md

---

content/en/docs/contribute/style/style-guide.md

Fix Style Guide Violation

---

OWNERS_ALIASES

I've created this pull request as I would like to become an approver for the Kubernetes documentation translation project. I am eager to utilize my experience and knowledge to further contribute to this project.

assign bells17 as sig-docs-ja approver

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_externalname.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_externalname.md
```

[zh] Add kubectl_create_service_externalname.md

---

static/_redirects

Signed-off-by: babugeet <abhinandhbg@gmail.com>
Adding  a short link https://kubernetes.io/blog/2024/06/06/10-years-of-kubernetes/ as https://k8s.io/kubertenes
Requirement ref: https://kubernetes.slack.com/archives/C1J0BPD2M/p1717690148648729

Added short link for birthday blog

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_clusterip.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_clusterip.md
```

[zh] Add kubectl_create_service_clusterip.md

---

content/ja/docs/concepts/architecture/cgroups.md

en PR https://github.com/kubernetes/website/pull/45935/files

[ja] Update the stale link for memory Qos

---

content/ja/docs/reference/glossary/cri-o.md

Fixes https://github.com/kubernetes/website/issues/46656.
This pull request is for the translation of [content/en/docs/reference/glossary/cri-o.md](https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-cri-o) .

[ja] Translate content/en/docs/reference/glossary/cri-o.md into Japanese

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md

Clarify the Pod Phase "Failed" Explanation

---

content/ja/docs/reference/glossary/customresourcedefinition.md

[ja] Translate CustomResourceDefinition

---

content/ja/blog/_posts/2024-03-07-cri-o-seccomp-oci-artifacts.md

Corrected an error in the author's name. (`Kevin Hannon (Red Hat)` → `Sascha Grunert`)
Right: https://kubernetes.io/blog/2024/03/07/cri-o-seccomp-oci-artifacts/
Wrong: https://kubernetes.io/ja/blog/2024/03/07/cri-o-seccomp-oci-artifacts/

[ja] Fix: content/ja/blog/_posts/2024-03-07-cri-o-seccomp-oci-artifacts.md

---

content/id/docs/concepts/architecture/cgroups.md

resolve https://github.com/kubernetes/website/pull/45935/files

[id] Update the stale link for memory Qos

---

content/zh-cn/docs/reference/using-api/server-side-apply.md

fixed:Update server-side-apply.md,there's an extra period.

---

content/en/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md

The link points to a blog that does not match the content.

Fixed incorrect link in the blog of 10 Years of Kubernetes

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md
```

[zh] Localize kubectl_create/_index.md

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

Note for to clear backup files

---

content/en/docs/concepts/cluster-administration/flow-control.md

This PR updates the website page about API Priority and Fairness to add a section discussing recursive server scenarios: explaining the problems that can arise and how to cope.

Add section to APF page about recursive scenarios

---

README.md

This PR is to update the New Contributor Ambassador for SIG Docs with my information. I had discussed with @divya-mohan0209 and confirmed this change. [Reference](https://groups.google.com/a/kubernetes.io/g/dev/c/aFyRtLOhIJE/m/BXCegyBoAAAJ).

Updated new contributor ambassador

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_docker-registry.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_docker-registry.md
```

[zh] Add /kubectl_create_secret_docker-registry.md

---

content/en/docs/concepts/services-networking/dual-stack.md

Fix references in IPv4/IPv6 dual-stack

---

content/ja/docs/concepts/services-networking/ingress-controllers.md

en PR https://github.com/kubernetes/website/pull/45976/files

[ja] Updated Hyperlink of Easegress IngressController

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic.md
```

[zh] Add kubectl_create_secret_generic.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_token.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_token.md
```

[zh] Add kubectl_create_token.md

---

content/es/docs/concepts/services-networking/ingress-controllers.md

en PR https://github.com/kubernetes/website/pull/45976/files

[es] Updated Hyperlink of Easegress IngressController

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_debug/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_debug/_index.md
```

[zh] Add kubectl_debug/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_ingress.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_ingress.md
```

[zh] Add kubectl_create_ingress.md

---

content/ja/docs/reference/glossary/cri.md

Closes: #45475
This pull request is for the translation of [content/en/docs/reference/glossary/cri.md](https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-cri) .

[ja] Translate content/en/docs/reference/glossary/cri.md into Japanese

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-context.md

Add content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-context.md

[zh-cn] Add kubectl_config_delete-context.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-user.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-user.md

[zh-cn] Add kubectl_config_delete-user.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_deny.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_deny.md
```

[zh] Add kubectl_certificate_deny.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_rename-context.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_rename-context.md

[zh-cn] Add kubectl_config_rename-context.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_use-context.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_use-context.md

[zh-cn] Add kubectl_config_use-context.md

---

content/en/blog/_posts/2024-04-17-kubernetes-1.30.md

[en] fix typo blog post

---

content/zh-cn/docs/concepts/architecture/garbage-collection.md

[zh] Sync garbage-collection.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-clusters.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-clusters.md

[zh-cn] Add kubectl_config_get-clusters.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-contexts.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-contexts.md

[zh-cn] Add kubectl_config_get-contexts.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-users.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-users.md

[zh-cn] Add kubectl_config_get-users.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-cluster.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-cluster.md

[zh-cn] Add kubectl_config_delete-cluster.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_approve.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_approve.md
```

[zh] Add kubectl_certificate_approve.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_events/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_events/_index.md
```

[zh] Add kubectl_events/_index.md

---

content/en/blog/_posts/2024-04-17-kubernetes-1.30.md
content/en/docs/concepts/architecture/garbage-collection.md
content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
content/en/docs/reference/glossary/cloud-controller-manager.md
content/en/docs/tutorials/hello-minikube.md
content/es/docs/concepts/services-networking/ingress-controllers.md
content/ja/docs/reference/glossary/cri.md
content/zh-cn/docs/concepts/architecture/garbage-collection.md
content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
content/zh-cn/docs/concepts/scheduling-eviction/pod-overhead.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_approve.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_deny.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-cluster.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-context.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_delete-user.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-clusters.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-contexts.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-users.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_rename-context.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_use-context.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_ingress.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_debug/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_events/_index.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

This PR syncs the dev-1.31 branch with the main branch to keep the dev-1.31 branch up to date.
cc: @Princesso @chanieljdan @salaxander @hacktivist123 @LaurentGoderre

Merged main dev 1.31

---

OWNERS_ALIASES

Add release Docs lead K8s v1.31 , @Princesso as an approver and reviewer.
I want to add myself to the approver list.
cc: @salaxander @divya-mohan0209

Add release Docs lead K8s v1.31 as approver

---

content/ja/docs/reference/glossary/dockershim.md

Closes: #46659 
I translated content/ja/docs/reference/glossary/dockershim.md

[ja] Translate content/ja/docs/reference/glossary/dockershim.md into Japanese

---

content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md

Improve https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/
- Aim to reduce the large number of note callouts
- promote one to a caution.
[Preview](https://deploy-preview-46777--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/configure-upgrade-etcd/)

Reorganize some callouts in etcd admin task

---

content/en/blog/_posts/2023-10-12-bootstrap-an-air-gapped-cluster-with-kubeadm/index.md

[en] fix typo

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set.md

Add content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set.md

[zh-cn] Add kubectl_config_set.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-cluster.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-cluster.md

[zh-cn] Add kubectl_config_set-cluster.md

---

content/en/docs/concepts/workloads/controllers/replicaset.md
content/en/docs/reference/command-line-tools-reference/feature-gates/logarithmic-scale-down.md

ref: https://github.com/kubernetes/enhancements/issues/2185

Add documentation for LogarithmicScaleDown featuregate

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-context.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-context.md

[zh-cn] Add kubectl_config_set-context.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_unset.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_unset.md

[zh-cn] Add kubectl_config_unset.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_view.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_view.md

[zh-cn] Add kubectl_config_view.md

---

content/zh-cn/docs/concepts/workloads/controllers/job.md
content/zh-cn/examples/controllers/job-success-policy.yaml

```
```
See [preview](https://deploy-preview-46503--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/job/)

[zh] Sync workloads/controllers/job.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md

add zh text to:
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md
```

[zh] Add kubectl_top_node.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_pod.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_pod.md
```

[zh] Add kubectl_top_pod.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image.md
```

[zh] Add kubectl_set_image.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_env.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_env.md
```

[zh] Add kubectl_set_env.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-credentials.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set-credentials.md

[zh-cn] Add kubectl_config_set-credentials.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/_index.md

[zh-cn] Add kubectl_rollout/_index.md

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/volumes.md

k/k: https://github.com/kubernetes/kubernetes/pull/125016

update portworxVolume doc

---

content/en/docs/concepts/services-networking/topology-aware-routing.md

Fix broken link in topology-aware-routing.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_plugin/kubectl_plugin_list.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_plugin/kubectl_plugin_list.md

[zh-cn] Add kubectl_plugin_list.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/kubectl_cluster-info_dump.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/kubectl_cluster-info_dump.md

[zh-cn] Add kubectl_cluster-info_dump.md

---

content/zh-cn/docs/concepts/security/_index.md

en PR https://github.com/kubernetes/website/pull/46134/files

[zh] Fix typo in security documentation

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_subject.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_subject.md
```

[zh] Add kubectl_set_subject.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_resources.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_resources.md
```

[zh] Add kubectl_set_resources.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status.md

[zh-cn] Add kubectl_rollout_status.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md

[zh-cn] Add kubectl_rollout_undo.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_serviceaccount.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_serviceaccount.md
```

[zh] Add kubectl_set_serviceaccount.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_history.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_history.md

[zh-cn] Add kubectl_rollout_history.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_pause.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_pause.md

[zh-cn] Add kubectl_rollout_pause.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_restart.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_restart.md

[zh-cn] Add kubectl_rollout_restart.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_resume.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_resume.md

[zh-cn] Add kubectl_rollout_resume.md

---

content/es/docs/concepts/architecture/leases.md

en PR https://github.com/kubernetes/website/pull/46276/files

[es] Fix link to 'Node heartbeats' section

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_can-i.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_can-i.md

[zh-cn] Add kubectl_auth_can-i.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_selector.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_selector.md
```

[zh] Add kubectl_set_selector.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_whoami.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_whoami.md

[zh-cn] Add kubectl_auth_whoami.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_reconcile.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_reconcile.md

[zh-cn] Add kubectl_auth_reconcile.md

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

Add note about that in the FG section of the kubeadm init doc.
xref https://github.com/kubernetes/website/issues/46799

kubeadm: add note about a bug in the PublicKeysECDSA feature gate

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

Add note about that in the FG section of the kubeadm init doc.
xref https://github.com/kubernetes/website/issues/46799

kubeadm: add note about a bug in the PublicKeysECDSA feature gate 

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/_index.md

[zh-cn] Add kubectl_apply/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_autoscale/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_autoscale/_index.md

[zh-cn] Add kubectl_autoscale/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_describe/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_describe/_index.md
```

[zh] Add kubectl_describe/_index.md

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

Action items
- k/k PR: https://github.com/kubernetes/kubernetes/pull/125582
Part of:
- https://github.com/kubernetes/enhancements/issues/4471
cc @neolit123 @pacoxu

kubeadm: add ControlPlaneKubeletLocalMode FG descriptions

---

content/en/docs/concepts/storage/storage-classes.md

Resolved Invalid reference of the link in Default StorageClass.
Fixes #46942

updated the wrong link in default storage classes

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_quota.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_quota.md
```

[zh] Add kubectl_create_quota.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_set-last-applied.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_set-last-applied.md

[zh-cn] Add kubectl_apply_set-last-applied.md

---

content/ja/docs/concepts/architecture/nodes.md

following up to #46939 (https://github.com/kubernetes/website/pull/46939#pullrequestreview-2134666849)
- Update anchor link in node.md
friendly cc @Arhell

[ja] Update nodes.md

---

content/zh-cn/docs/concepts/storage/storage-classes.md
content/zh-cn/examples/storage/storageclass-low-latency.yaml

```
content/zh-cn/docs/concepts/storage/storage-classes.md
```
See [preview](https://deploy-preview-46561--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/storage-classes/)

[zh] Sync storage/storage-classes.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md
```

[zh] Add kubectl_explain/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_port-forward/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_port-forward/_index.md
```

[zh] Add kubectl_port-forward/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_patch/_index.md

[zh] Add kubectl_patch/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_edit-last-applied.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_edit-last-applied.md

[zh-cn] Add kubectl_apply_edit-last-applied.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_proxy/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_proxy/_index.md
```

[zh] Add kubectl_proxy/_index.md

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md

Sync with  en #46525 
```
```
Ready for review. cc @tengqm

[zh] Sync pod-lifecycle.md and fix notes style

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls.md
```

[zh] Add kubectl_create_secret_tls.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md
```

[zh] Add kubectl_diff/_index.md

---

content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md

Fix wrong describe about `align-by-socket`

[zh] update cpu-management-policies

---

content/en/docs/concepts/configuration/secret.md

fix: https://github.com/kubernetes/website/issues/46622

Fix incorrect statement about Basic auth Secrets

---

content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md

Fixes #46595 
some images were failing to pull.  updated kompose version and compose example file, along with sample output.

Revise stale "Translate a Docker Compose File to Kubernetes Resources" page

---

content/ja/docs/concepts/extend-kubernetes/operator.md

en PR https://github.com/kubernetes/website/pull/46390/files

[ja] Update operator.md: Removed KUDO

---

content/ja/docs/reference/glossary/dynamic-volume-provisioning.md

Closes: #46660
I translated content/ja/docs/reference/glossary/dynamic-volume-provisioning.md into Japanese

[ja] Translate content/ja/docs/reference/glossary/dynamic-volume-provisioning.md into Japanese

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_scale/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_scale/_index.md
```

[zh] Add kubectl_scale/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md
```

[zh] Add kubectl_replace/_index.md

---

content/en/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

Adds feature gates and runtime config information required to use storage version migration feature.
Fixes https://github.com/kubernetes/website/issues/46862
/cc @enj @jpbetz @deads2k

[Storage Version Migrator] docs: adds feature gates and runtime config information

---

content/en/docs/reference/command-line-tools-reference/feature-gates/disable-node-kube-proxy-version.md

Document promote DisableNodeKubeProxyVersion feature gate to beta

---

content/en/docs/concepts/services-networking/service.md

internal-load-balancer section indentation alignment fix

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_view-last-applied.md

add zh text to:
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_view-last-applied.md
```

[zh] Add kubectl_apply_view-last-applied.md

---

content/zh-cn/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md

[zh] Fixed minimum feasible nodes value 50->100

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md

Add content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md

[zh-cn] Add kubectl_edit/_index.md

---

content/ja/docs/reference/command-line-tools-reference/feature-gates/in-place-pod-vertical-scaling.md

…feature-gates/in-place-pod-vertical-scaling.md
- add `content/ja/docs/reference/command-line-tools-reference/feature-gates/in-place-pod-vertical-scaling.md`
This PR is necessary to resolve [#46749 (comment)](https://github.com/kubernetes/website/pull/46749#discussion_r1632428806).
/language ja

[ja]Translate content/ja/docs/reference/command-line-tools-reference/feature-gates/in-place-pod-vertical-scaling.md

---

content/ja/docs/concepts/architecture/leases.md

en PR https://github.com/kubernetes/website/pull/46276/files

[ja] Fix link to 'Node heartbeats' section

---

content/en/docs/tasks/debug/debug-application/debug-running-pod.md
content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md

This PR add description about debugging profile.
ref: 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1441-kubectl-debug/README.md#debugging-profiles
https://github.com/kubernetes/kubernetes/pull/123149#discussion_r1598690150

Add description about debugging profile

---

content/zh-cn/blog/_posts/2024-04-25-structured-authentication-configuration-beta.md

en PR https://github.com/kubernetes/website/pull/46402/files

[zh] Fix CA in authentication example

---

content/id/docs/concepts/extend-kubernetes/operator.md

resolve https://github.com/kubernetes/website/pull/46390/files

[id] Update operator.md: Removed KUDO

---

content/zh-cn/docs/tasks/configure-pod-container/translate-compose-kubernetes.md

content/zh-cn/docs/tasks/configure-pod-container/translate-compose-kubernetes.md

[zh-cn] Sync translate-compose-kubernetes

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_drain/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_drain/_index.md

[zh-cn] Add kubectl_drain

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md
```

[zh] Add kubectl_get/_index.md

---

content/hi/docs/tasks/tools/install-kubectl-linux.md

en PR https://github.com/kubernetes/website/pull/45814/files

[hi] kubectl debian install guide does not mention gnupg at all

---

content/es/docs/tasks/tools/install-kubectl-linux.md

en PR https://github.com/kubernetes/website/pull/45814/files

[es] kubectl debian install guide does not mention gnupg at all

---

content/zh-cn/docs/concepts/cluster-administration/flow-control.md

English documentation PR - https://github.com/kubernetes/website/pull/47060

[zh-cn] fixes typo in documentation

---

content/ja/docs/reference/glossary/device-plugin.md

Closes #46658 
I translated content/en/docs/reference/glossary/device-plugin.md into Japanese

[ja] Translate content/en/docs/reference/glossary/device-plugin.md into Japanese

---

content/ja/docs/reference/glossary/kubeadm.md

Worker node Typo fix

---

content/en/docs/concepts/services-networking/_index.md

Closes #44246 
- **Page to be updated**: https://kubernetes.io/docs/concepts/services-networking/
- **changes** : [The Kubernetes network model](https://kubernetes.io/docs/concepts/services-networking/#the-kubernetes-network-model) section updated per https://github.com/kubernetes/website/pull/32363#discussion_r1413838618 and https://github.com/kubernetes/website/pull/32363#discussion_r1413840655

Update k8s network model section

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md

[zh] Sync pods/pod-lifecycle.md

---

content/en/docs/concepts/overview/kubernetes-api.md

fix the broken link for discovery document.
Fixes #47068

fix the broken link for discovery document

---

content/en/docs/reference/command-line-tools-reference/feature-gates/kube-proxy-draining-terminating-nodes.md

Enhancement: https://github.com/kubernetes/enhancements/issues/3836
Original implementation PR: https://github.com/kubernetes/kubernetes/pull/116470
Original doc PR: https://github.com/kubernetes/website/pull/45678
Superseedes: https://github.com/kubernetes/website/pull/47030
/sig network
/cc @aojea

Graduate KubeProxyDrainingTerminatingNodes to GA

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_run/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_run/_index.md
```

[zh] Add kubectl_run/_index.md

---

content/pt-br/docs/concepts/extend-kubernetes/operator.md

en PR https://github.com/kubernetes/website/pull/46390/files

[pt] Update operator.md: Removed KUDO

---

content/zh-cn/docs/concepts/security/cloud-native-security.md

[zh-cn] Localize cloud-native-security.md
https://deploy-preview-47112--kubernetes-io-main-staging.netlify.app/

[zh-cn] Localize cloud-native-security.md

---

content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md

Sync with en #46758 and #46777 
```
```

[zh] Sync administer-cluster/configure-upgrade-etcd.md

---

content/en/docs/concepts/scheduling-eviction/assign-pod-node.md

This PR fixes small typos in the text for consistency.

Fix typos in assign-pod-node.md

---

content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md

This PR improves the existing sentence for clarity.

Clarify sentence

---

content/zh-cn/examples/service/networking/example-ingress.yaml

[zh] Add ingress class name to example-ingress.yaml

---

content/zh-cn/docs/concepts/storage/volume-attributes-classes.md

```
content/zh-cn/docs/concepts/storage/volume-attributes-classes.md
```
See [preview](https://deploy-preview-47082--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/volume-attributes-classes/).

[zh] Add volume-attributes-classes.md

---

content/en/docs/concepts/storage/volumes.md

try to resolve: https://github.com/kubernetes/website/issues/47122

add warning about hostPath volumes

---

content/es/examples/service/networking/example-ingress.yaml

[es] Add ingress class name to example-ingress.yaml

---

content/en/docs/reference/labels-annotations-taints/_index.md

Resolves #47092.
Code change done in https://github.com/kubernetes/kubernetes/pull/118942.

Entry for contains-group-kinds annotation and updated contains-group-resources annotation

---

content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-1/index.md

- Fix https://github.com/kubernetes/website/pull/46686
- Fixed invalid links in the documentation.

[ja] Fix "DIY: Create Your Own Cloud with Kubernetes (Part 1)"

---

content/zh-cn/docs/reference/labels-annotations-taints/_index.md

Also add those zh text from en #47120 
```
```
See [preview](https://deploy-preview-47127--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/labels-annotations-taints/).

[zh] Add translations to labels-annotations-taints/_index.md

---

content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

Sync with en content.
```
content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md
```

[zh] Sync storage-version-migration.md

---

content/zh-cn/docs/concepts/storage/volumes.md
content/zh-cn/examples/storage/rro.yaml

```
```
See [preview](https://deploy-preview-47135--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/volumes/).

[zh] Sync concepts/storage/volumes.md

---

content/bn/examples/service/networking/example-ingress.yaml

[bn] Add ingress class name to example-ingress.yaml

---

content/zh-cn/docs/concepts/services-networking/_index.md
content/zh-cn/docs/concepts/services-networking/dual-stack.md
content/zh-cn/docs/concepts/services-networking/service.md

content/zh-cn/docs/concepts/services-networking/_index.md
content/zh-cn/docs/concepts/services-networking/dual-stack.md

[zh-cn] Sync services-networking/*

---

content/zh-cn/docs/tasks/configure-pod-container/configure-gmsa.md

content/zh-cn/docs/tasks/configure-pod-container/configure-gmsa.md

[zh-cn] sync configure-gmsa

---

content/en/docs/reference/command-line-tools-reference/feature-gates/service-traffic-distribution.md

Previews:
- https://deploy-preview-46973--kubernetes-io-main-staging.netlify.app//docs/concepts/services-networking/service/#trafic-distribution
- https://deploy-preview-46973--kubernetes-io-main-staging.netlify.app//docs/reference/networking/virtual-ips/#traffic-distribution
- https://deploy-preview-46973--kubernetes-io-main-staging.netlify.app//docs/reference/command-line-tools-reference/feature-gates/
Code changes for promotion to beta: https://github.com/kubernetes/kubernetes/pull/125838
KEP: https://github.com/kubernetes/enhancements/issues/4444
/sig network

Docs update for k8s 1.31 regarding Service trafficDistribution

---

content/zh-cn/docs/concepts/storage/volume-health-monitoring.md

“如果 CSI 驱动程序支持节点**测**的卷健康检测” chagne to "如果 CSI 驱动程序支持节点**侧**的卷健康检测"

Update volume-health-monitoring.md, “测” chagne to  "侧"

---

content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md

```
content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md
```
See [preview](https://deploy-preview-47169--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling/)

[zh] Add cluster-autoscaling.md

---

content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

updated default and min value

---

content/ja/examples/service/networking/example-ingress.yaml

[ja] Add ingress class name to example-ingress.yaml

---

content/ja/docs/concepts/policy/node-resource-managers.md

Closes #47140 
I translated content/ja/docs/concepts/policy/node-resource-managers.md into Japanese.

[ja] Translate node-resource-managers.md into Japanese

---

content/en/docs/tutorials/configuration/updating-configuration-via-a-configmap.md

Try to make it prettier in the editing mode:
- Add a blank line between paras
- Replace four \` with three \` for a few code snippets

Clean up updating-configuration-via-a-configmap.md

---

content/zh-cn/docs/concepts/extend-kubernetes/operator.md

content/zh-cn/docs/concepts/extend-kubernetes/operator.md

[zh-cn] sync extend-kubernetes/operator.md

---

content/en/docs/tutorials/security/apparmor.md

Fixed a dead link in AppArmor doc

---

content/en/docs/reference/access-authn-authz/certificate-signing-requests.md

Fixes: #47192
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>

Add links to CertificateSigningRequest API

---

content/es/docs/concepts/services-networking/service.md

en PR https://github.com/kubernetes/website/pull/44099/files

[es] Service without selectors, command correction issue

---

content/zh-cn/docs/tutorials/hello-minikube.md

content/zh-cn/docs/tutorials/hello-minikube.md

[zh-cn] sync tutorials/hello-minikube.md

---

content/zh-cn/examples/service/networking/example-ingress.yaml

[zh] Delete rewrite-target annotation in ingress example

---

content/en/docs/reference/labels-annotations-taints/_index.md

Adding annotationstorage.alpha.kubernetes.io/migrated-plugins
Relates to: #36194

Added Annotation storage.alpha.kubernetes.io/migrated-plugins

---

content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

[zh] Sync a task: custom-resource-definitions.md

---

content/ja/docs/reference/kubectl/_index.md

Fixes broken link to kubectl installation page

[ja] Fix link error

---

content/ja/examples/service/networking/example-ingress.yaml

[ja] Delete rewrite-target annotation in ingress example

---

content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md

Sync with en #46694 
```
content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
```

[zh] Sync a task: cpu-management-policies.md

---

content/zh-cn/docs/tasks/configmap-secret/managing-secret-using-kustomize.md

content/zh-cn/docs/tasks/configmap-secret/managing-secret-using-kustomize.md

[zh-cn] sync configmap-secret/managing-secret-using-kustomize

---

content/zh-cn/blog/_posts/2024-07-19-kubernetes-1.31-deprecations-and-removals.md

Localize blog: 2024-07-19-kubernetes-1.31-deprecations-and-removals.md

[zh-cn] Localize blog: 2024-07-19-kubernetes-1.31-deprecations-and-removals.md

---

content/es/examples/service/networking/example-ingress.yaml

[es] Delete rewrite-target annotation in ingress example

---

content/ja/blog/_posts/2020-12-02-dont-panic-kubernetes-and-docker.md
content/ja/blog/_posts/2022-12-05-forensic-container-checkpointing/index.md
content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
content/ja/blog/_posts/2023-03-10-forensic-container-analysis/index.md
content/ja/blog/_posts/2024-01-15-SIG-Release-Spotlight/index.md
content/ja/blog/_posts/2024-01-23-image-filesystem.md
content/ja/blog/_posts/2024-02-22-k8s-book-club/index.md
content/ja/blog/_posts/2024-03-07-cri-o-seccomp-oci-artifacts.md
content/ja/blog/_posts/2024-03-12-mid-cycle-1.30.md
content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-1/index.md
content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-3/index.md
content/ja/blog/_posts/2024-05-20-cloud-provider-migration.md

this pr is following up to #45957
- move author details in front-matter (ja)
Deploy preview (summary): [link](https://deploy-preview-47152--kubernetes-io-main-staging.netlify.app/ja/blog/)

[ja] Update blog content files to move author details in front-matter

---

content/ja/docs/contribute/participate/roles-and-responsibilities.md

close #47150 
- Translate docs/contribute/participate/roles-and-responsibilities.md into Japanese
Deploy preview: [link](https://deploy-preview-47151--kubernetes-io-main-staging.netlify.app/ja/docs/contribute/participate/roles-and-responsibilities/)

[ja] Translate docs/contribute/participate/roles-and-responsibilities.md into Japanese

---

content/en/docs/reference/command-line-tools-reference/feature-gates/custom-resource-validation-expressions.md

Doc for merged change:  https://github.com/kubernetes/kubernetes/pull/126136

Remove the fg CustomResourceValidationExpressions

---

content/en/docs/concepts/workloads/pods/_index.md

Made correction to the explanation in the text under Pod OS to reflect the acutal correct behvior.
Fixes https://github.com/kubernetes/website/issues/47238

Fix text in "Pods" concept page

---

content/en/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-aws-unregister.md
content/en/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-azure-disk-unregister.md
content/en/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-azure-file-unregister.md
content/en/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-gce-unregister.md
content/en/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-openstack-unregister.md
content/en/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-vsphere-unregister.md

/hold
util https://github.com/kubernetes/kubernetes/pull/124815 is merged.

remove some unneeded feature-gates

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md

Clarify What a PostStart Hook Does

---

content/en/docs/concepts/security/pod-security-standards.md
content/en/docs/reference/access-authn-authz/psp-to-pod-security-standards.md

follow up of https://github.com/kubernetes/kubernetes/pull/126165#issuecomment-2245401925

PSS: add container_engine_t to allowed list of selinux types

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_delete/_index.md

[zh] Add kubectl_delete/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_expose/_index.md

```
content/zh-cn/docs/reference/kubectl/generated/kubectl_expose/_index.md
```

[zh] Add kubectl_expose/_index.md

---

content/zh-cn/docs/tutorials/configuration/updating-configuration-via-a-configmap.md
content/zh-cn/examples/configmap/immutable-configmap.yaml
content/zh-cn/examples/configmap/new-immutable-configmap.yaml
content/zh-cn/examples/deployments/deployment-with-configmap-and-sidecar-container.yaml
content/zh-cn/examples/deployments/deployment-with-configmap-as-envvar.yaml
content/zh-cn/examples/deployments/deployment-with-configmap-as-volume.yaml
content/zh-cn/examples/deployments/deployment-with-configmap-two-containers.yaml
content/zh-cn/examples/deployments/deployment-with-immutable-configmap-as-volume.yaml

```
content/zh-cn/docs/tutorials/configuration/updating-configuration-via-a-configmap.md
```
See [preview](https://deploy-preview-47226--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/configuration/updating-configuration-via-a-configmap/)

[zh] Add updating-configuration-via-a-configmap.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md

Fix feature gate ZeroLimitedNominalConcurrencyShares in v1.30

---

content/bn/examples/service/networking/example-ingress.yaml

[bn] Delete rewrite-target annotation in ingress example

---

content/en/docs/reference/command-line-tools-reference/feature-gates/pdb-unhealthy-pod-eviction-policy.md
content/en/docs/tasks/run-application/configure-pdb.md

add docs for PDBUnhealthyPodEvictionPolicy GA promotion
- https://github.com/kubernetes/kubernetes/pull/123428
- https://github.com/kubernetes/enhancements/issues/3017

[KEP-3017]: promote PDBUnhealthyPodEvictionPolicy to GA

---

content/en/docs/reference/command-line-tools-reference/feature-gates/watch-from-storage-without-resource-version.md

Add feature gate WatchFromStorageWithoutResourceVersion for v1.30

---

content/en/docs/reference/command-line-tools-reference/feature-gates/container-checkpoint.md
content/en/docs/reference/node/kubelet-checkpoint-api.md

Fix feature gate status for ContainerCheckpoint in v1.30

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/reference/command-line-tools-reference/feature-gates/job-success-policy.md

This PR update is just the feature gate stage since there are no user-facing changes in the beta stage.
Part of: https://github.com/kubernetes/enhancements/issues/3998

Update JobSuccessPolicy documentations for the beta graduation

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/container-checkpoint.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-from-storage-without-resource-version.md

Sync 2 feature gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/container-checkpoint.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-from-storage-without-resource-version.md
```

[zh] Sync container-checkpoint and watch-from-storage

---

content/zh-cn/docs/reference/node/kubelet-checkpoint-api.md
content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

content/zh-cn/docs/reference/node/kubelet-checkpoint-api.md

[zh-cn] sync kubelet-checkpoint-api custom-resource-definitions

---

content/en/docs/reference/command-line-tools-reference/feature-gates/resilient-watch-cache-initialization.md
content/en/docs/reference/command-line-tools-reference/feature-gates/watch-cache-initialization-post-start-hook.md

ResilientWatchCacheInitialization documentation

---

content/en/docs/reference/command-line-tools-reference/feature-gates/mutating-admission-policy.md

Add feature gate for MutatingAdmissionPolicy in v1.30

---

content/de/docs/reference/glossary/cloud-controller-manager.md

en PR https://github.com/kubernetes/website/pull/46823/files

[de] Remove self referencing link

---

content/zh-cn/docs/concepts/configuration/secret.md

[zh-cn] sync configuration/secret

---

content/en/docs/reference/access-authn-authz/node.md
content/en/docs/reference/access-authn-authz/validating-admission-policy.md
content/en/docs/reference/access-authn-authz/webhook.md
content/en/docs/reference/command-line-tools-reference/feature-gates/authorize-node-with-selectors.md
content/en/docs/reference/command-line-tools-reference/feature-gates/authorize-with-selectors.md
content/en/docs/reference/using-api/cel.md

Alpha docs for https://github.com/kubernetes/enhancements/issues/4601

KEP-4601: alpha docs

---

content/en/docs/reference/command-line-tools-reference/feature-gates/retry-generate-name.md

Fix feature gate RetryGenerateName for v1.30

---

content/pl/docs/reference/glossary/cloud-controller-manager.md

en PR https://github.com/kubernetes/website/pull/46823/files

[pl] Remove self referencing link

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/retry-generate-name.md

Sync with #47257 
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/retry-generate-name.md
```

[zh] Sync a feature gate: retry-generate-name.md

---

content/pt-br/examples/service/networking/example-ingress.yaml

[pt] Add ingress class name to example-ingress.yaml

---

content/zh-cn/docs/concepts/storage/storage-classes.md

en PR https://github.com/kubernetes/website/pull/46943/files

[zh] Fix the wrong link in default storage classes

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mutating-admission-policy.md

Add zh text to this feature gate:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/mutating-admission-policy.md
```

[zh] Add a feature gate: mutating-admission-policy

---

content/en/docs/reference/command-line-tools-reference/feature-gates/evented-pleg.md

Fix feature gate for EventedPLEG in v1.30

---

content/en/docs/reference/command-line-tools-reference/feature-gates/kubelet-cgroup-driver-from-cri.md
content/en/docs/setup/production-environment/container-runtimes.md

xref: https://github.com/kubernetes/website/pull/46965

Update docs for beta promotion of cgroup driver detection from CRI

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/concepts/workloads/pods/disruptions.md
content/en/docs/concepts/workloads/pods/pod-lifecycle.md
content/en/docs/reference/command-line-tools-reference/feature-gates/job-pod-failure-policy.md
content/en/docs/reference/command-line-tools-reference/feature-gates/pod-disruption-conditions.md
content/en/docs/tasks/job/pod-failure-policy.md

Tracking issue: https://github.com/kubernetes/enhancements/issues/3329

Graduate Job Pod Failure Policy to stable

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/tasks/job/pod-failure-policy.md

Tracking issue: https://github.com/kubernetes/enhancements/issues/4368.
The change of the logic reflected in the notes describes the fix for the issue: 
https://github.com/kubernetes/kubernetes/issues/123775

Update the docs for JobManagedBy and JobPodReplacementPolicy related to pod termination

---

content/ja/docs/reference/glossary/endpoint.md

[ja] Endpoints translation

---

content/ja/docs/setup/production-environment/container-runtimes.md

en PR https://github.com/kubernetes/website/pull/47110/files

[ja] Update CRI-O install link

---

static/js/search.js

These logs were leftover from the work on [this PR](https://github.com/kubernetes/website/pull/47128)

Remove console logging about search engine choice

---

data/i18n/zh-cn/zh-cn.toml

Sync translator metadata in zh-cn.toml
- en PR: https://github.com/kubernetes/website/pull/47270

[zh-cn] Sync translator metadata in zh-cn.toml

---

content/en/docs/concepts/configuration/manage-resources-containers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/local-storage-capacity-isolation-fs-quota-monitoring.md

Promote LocalStorageCapacityIsolationFSQuotaMonitoring to beta
KEP reference: https://github.com/kubernetes/enhancements/pull/4679

Promote ephemeral storage quota to beta(1.31)

---

content/en/docs/tasks/administer-cluster/topology-manager.md

Add documentation for KEP-4622

KEP-4622: Add docs for TopologyManager policy option for MaxAllowableNUMANodes

---

content/en/docs/concepts/overview/working-with-objects/labels.md

corrected label for accelerator

---

content/en/docs/concepts/architecture/coordinated-leader-election.md
content/en/docs/concepts/cluster-administration/coordinated-leader-election.md
content/en/docs/reference/command-line-tools-reference/feature-gates/coordinated-leader-election.md
content/en/docs/reference/kubernetes-api/cluster-resources/lease-candidate-v1alpha1.md

https://github.com/kubernetes/enhancements/issues/4355#issuecomment-2181407075

[KEP-4355] Coordinated Leader Election alpha documentation

---

content/en/docs/concepts/architecture/leases.md

Add a missing link
@Jefftree FYI

Link from Lease concept to LeaseCandidate docs

---

content/zh-cn/docs/concepts/workloads/pods/_index.md

[zh] Sync workloads/pods/_index.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/consistent-list-from-cache.md
content/en/docs/reference/using-api/api-concepts.md

Document https://github.com/kubernetes/enhancements/issues/2340

Beta documentation for Consistent Reads from Cache

---

content/uk/_index.html

[uk] Update banner

---

content/zh-cn/docs/reference/access-authn-authz/rbac.md

[zh-cn] sync access-authn-authz/rbac.md

---

content/pt-br/examples/service/networking/example-ingress.yaml

[pt] Delete rewrite-target annotation in ingress example

---

content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md

Sync with en #46731 
```
```
See [preview](https://deploy-preview-47247--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/containers/container-lifecycle-hooks/)

[zh] Sync container-lifecycle-hooks.md

---

content/zh-cn/docs/reference/access-authn-authz/bootstrap-tokens.md
content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md

content/zh-cn/docs/reference/access-authn-authz/bootstrap-tokens.md
content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md

[zh-cn] sync bootstrap-tokens certificate-signing-requests

---

content/zh-cn/docs/concepts/security/pod-security-standards.md

```
content/zh-cn/docs/concepts/security/pod-security-standards.md
```
See [preview](https://deploy-preview-47327--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/pod-security-standards/).

[zh] Sync security/pod-security-standards.md

---

content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
content/zh-cn/examples/validatingadmissionpolicy/basic-example-binding.yaml
content/zh-cn/examples/validatingadmissionpolicy/basic-example-policy.yaml
content/zh-cn/examples/validatingadmissionpolicy/binding-with-param-prod.yaml
content/zh-cn/examples/validatingadmissionpolicy/binding-with-param.yaml
content/zh-cn/examples/validatingadmissionpolicy/failure-policy-ignore.yaml
content/zh-cn/examples/validatingadmissionpolicy/policy-with-param.yaml
content/zh-cn/examples/validatingadmissionpolicy/typechecking-multiple-match.yaml
content/zh-cn/examples/validatingadmissionpolicy/typechecking.yaml

Sync 2 files:
```
```
See [preview](https://deploy-preview-47340--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/validating-admission-policy/).

[zh] Sync reference: validating-admission-policy.md and service-accounts-admin.md

---

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
content/zh-cn/docs/concepts/overview/working-with-objects/labels.md

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md
content/zh-cn/docs/concepts/overview/working-with-objects/labels.md

[zh-cn] sync network-plugins labels

---

content/ru/examples/application/cassandra/cassandra-statefulset.yaml

resolve https://github.com/kubernetes/website/pull/47087/files

[ru] Update stale StatefulSet with Cassandra example

---

content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md

content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md

[zh-cn] sync configure-upgrade-etcd dns-debugging-resolution

---

content/ko/docs/concepts/extend-kubernetes/operator.md

en PR https://github.com/kubernetes/website/pull/46390/files

[ko] Update operator.md: Removed KUDO

---

content/ko/docs/setup/production-environment/container-runtimes.md

en PR https://github.com/kubernetes/website/pull/47110/files

[ko] Update CRI-O install link

---

content/zh-cn/examples/application/cassandra/cassandra-statefulset.yaml

en PR https://github.com/kubernetes/website/pull/47087/files

[zh] Update stale StatefulSet with Cassandra example

---

content/ja/examples/application/cassandra/cassandra-statefulset.yaml

en PR https://github.com/kubernetes/website/pull/47087/files

[ja] Update stale StatefulSet with Cassandra example

---

OWNERS_ALIASES

Adding myself temporarily to same access as the K8s v1.31 lead, to help out with the lead responsibilities asynchronously while @Princesso is out sick.
Feel better soon Princess!
I will remove myself in cleanup post the 1.31 release.
cc: @salaxander @divya-mohan0209 @katcosgrove @reylejano

Add Drew temporarily as acting release Docs lead K8s v1.31

---

content/en/blog/_posts/2024-08-12-feature-gates_client-go.md

Blog Post: Introducing Feature Gates to Client-Go: Enhancing Flexibility and Control

---

content/ja/docs/concepts/extend-kubernetes/operator.md

en PR https://github.com/kubernetes/website/pull/47170/files

[ja] Update the GitHub repo url of Java Operator SDK

---

README-zh.md

[fix]: fix translation error in README-zh.md

---

content/zh-cn/docs/concepts/services-networking/ingress.md

There is a typo, it should be "以下" instead of "一下".

Fix a typo.

---

content/bn/docs/concepts/security/_index.md

en PR https://github.com/kubernetes/website/pull/46134/files

[bn] Fix typo in security documentation

---

content/bn/docs/concepts/security/_index.md

Merged main branch into dev 1.31nto keep it in sync.
I noticed that main is ahead of dev-1.31, hence a final sync.
cc: @drewhagen @salaxander @reylejano

Merged main branch into dev 1.31nto keep it in sync

---

content/bn/docs/concepts/security/_index.md

PR to merge main into release-1.30 to keep in sync.
cc: @reylejano @salaxander @katcosgrove @drewhagen

Merge main into release-1.30 to keep in sync

---

hugo.toml

Updating configuration files for release 1.31
/hold for v1.31 release day
cc: @drewhagen @chanieljdan @salaxander

Updates v1.29 hugo.toml for 1.31 release

---

content/bn/examples/application/cassandra/cassandra-statefulset.yaml

en PR https://github.com/kubernetes/website/pull/47087/files

[bn] Update stale StatefulSet with Cassandra example

---

data/i18n/bn/OWNERS
data/i18n/de/OWNERS
data/i18n/es/OWNERS
data/i18n/fr/OWNERS
data/i18n/hi/OWNERS
data/i18n/id/OWNERS
data/i18n/it/OWNERS
data/i18n/ja/OWNERS
data/i18n/ko/OWNERS
data/i18n/pt-br/OWNERS
data/i18n/ru/OWNERS
data/i18n/uk/OWNERS
data/i18n/vi/OWNERS
data/i18n/zh-cn/OWNERS

following up to #42206
- `area/localization` label is added when `data/i18n/**/*.toml` is fixed
Closes: #

Add label when data/i18n/**/*.toml is updated

---

content/en/blog/_posts/2024-08-19-pod-failure-policy-for-jobs-goes-ga.md

It's a blog post for https://github.com/kubernetes/enhancements/issues/3329

blogpost: Pod Failure Policy for Jobs Goes GA

---

content/en/blog/_posts/2024-08-15-consistent-read-from-cache.md

Blogpost for https://github.com/kubernetes/enhancements/issues/2340

Consistent read from cache blogpost

---

content/en/docs/tasks/tools/install-kubectl-linux.md

Added one more step to SUSE kubectl installation process

Update SUSE install-kubectl-linux.md

---

content/en/docs/setup/best-practices/cluster-large.md

Added link to first mention of VerticalPodAutoscaler for reader's convenience based on standard wiki/knowledgebase convention

Added link to first mention of VerticalPodAutoscaler for reader's convenience

---

content/zh-cn/blog/_posts/2024-08-07-sig-api-machinery-spotlight.md

```
content/zh-cn/blog/_posts/2024-08-07-sig-api-machinery-spotlight.md
```
See [preview](https://deploy-preview-47357--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/07/sig-api-machinery-spotlight-2024/).

[zh] Add blog: 2024-08-07-sig-api-machinery-spotlight.md

---

content/en/blog/_posts/2024-06-21-custom-profiling-kubectl-debug.md

Feature blog ~place holder~ article for https://github.com/kubernetes/enhancements/issues/4292

Custom profiling in kubectl debug feature blog

---

content/en/blog/_posts/2024-08-16-matchlabelkeys-podaffinity.md
content/en/blog/_posts/2024-xx-xx-matchlabelkeys-podaffinity.md

~This is just a place holder PR for now.~
It's a blog post for https://github.com/kubernetes/enhancements/issues/3633

blog post for MatchLabelKeys in PodAffinity

---

content/en/docs/setup/production-environment/tools/_index.md

If you manage several clusters on your own, then Cluster API is one of the most common
ways to do that. Up to now it was not on the [corresponding page](https://kubernetes.io/docs/setup/production-environment/tools/).

Added Cluster API to "Installing Kubernetes"

---

content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md

```
```
See [preview](https://deploy-preview-47495--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init/).

[zh] Sync kubeadm/kubeadm-init.md

---

content/zh-cn/docs/concepts/storage/persistent-volumes.md

```
```
See [preview](https://deploy-preview-47493--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/persistent-volumes/).

[zh] Sync storage/persistent-volumes.md

---

content/en/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control/index.md

It adds a its KEP link to the KEP-3619 feature blog to be published on 2024-08-22
This is a follow up PR for #46921

KEP-3619: add its KEP link to the blog

---

data/i18n/bn/bn.toml
hugo.toml

Update date format for bengali .
MM-DD-YYYY  to DD-MM-YYYY

Update date format for bengali

---

content/zh-cn/docs/concepts/workloads/controllers/replicaset.md

content/zh-cn/docs/concepts/workloads/controllers/replicaset.md

[zh-cn] sync controllers/replicaset.md

---

content/zh-cn/docs/concepts/workloads/controllers/statefulset.md

content/zh-cn/docs/concepts/workloads/controllers/statefulset.md

[zh-cn] sync controllers/statefulset.md

---

content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md

update zh text in:
```
content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
```

[zh] Sync scheduling-eviction/dynamic-resource-allocation.md

---

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
content/zh-cn/docs/concepts/windows/intro.md

content/zh-cn/docs/concepts/architecture/leases.md

[zh-cn] sync device-plugins.md and intro.md

---

content/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources.md

content/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources.md

[zh-cn] sync custom-resources.md

---

content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
content/zh-cn/docs/tutorials/_index.md

content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
content/zh-cn/docs/tutorials/_index.md

[zh-cn] sync kubeadm-init-phase tutorials/_index.md

---

content/zh-cn/blog/_posts/2024-08-12-feature-gates_client-go.md

[zh-cn] Add blog 2024-08-12-feature-gates_client-go.md
Closes: #

[zh-cn] Add blog 2024-08-12-feature-gates_client-go.md

---

content/zh-cn/docs/concepts/workloads/controllers/job.md

[zh-cn] sync controllers/job.md

---

content/zh-cn/docs/contribute/participate/pr-wranglers.md

Sync with en #47533 
```
content/zh-cn/docs/contribute/participate/pr-wranglers.md
```

[zh] sync pr-wranglers.md

---

content/bn/docs/reference/glossary/container-runtime-interface.md

Bengali localization of content/en/docs/reference/glossary/container-runtime-interface.md

[bn] Localize reference glossary container-runtime-interface.md

---

content/zh-cn/blog/_posts/2024-08-15-volume-attributes-class.md

```
content/zh-cn/blog/_posts/2024-08-15-volume-attributes-class.md
```
See [preview](https://deploy-preview-47516--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/15/kubernetes-1-31-volume-attributes-class/).

[zh] Add a blog: 2024-08-15-volume-attributes-class.md

---

content/en/docs/concepts/storage/volume-attributes-classes.md

Clean up storage/volume-attributes-classes.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-separate-disk-gc.md

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-separate-disk-gc.md

[zh-cn] sync kubelet-separate-disk-gc.md

---

content/zh-cn/docs/concepts/storage/volume-attributes-classes.md
content/zh-cn/docs/tasks/tools/install-kubectl-linux.md

content/zh-cn/docs/concepts/storage/volume-attributes-classes.md

[zh-cn] sync volume-attributes-classes.md install-kubectl-linux.md

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md

```
content/zh-cn/docs/reference/command-line-tools-reference/kube-proxy.md
```

[zh] Sync command-line-tools-reference/kube-proxy.md

---

content/id/docs/contribute/participate/_index.md

en PR https://github.com/kubernetes/website/pull/47496/files

[id] Fix broken hyperlink

---

content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/zh-cn/docs/tasks/job/pod-failure-policy.md

[zh-cn] sync kubeadm/* pod-failure-policy.md

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md

```
content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md
```

[zh] Sync command-line-tools-reference/kube-controller-manager.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_expose/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_kustomize/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_expose/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_kustomize/_index.md

[zh-cn] sync kubectl_kustomize kubectl_get kubectl_expose

---

content/de/docs/contribute/participate/_index.md

en PR https://github.com/kubernetes/website/pull/47496/files

[de] Fix broken hyperlink

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_docker-registry.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_docker-registry.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls.md

[zh-cn] sync kubectl_create_secret_*

---

content/zh-cn/blog/_posts/2024-08-23-kubeadm-v1beta4.md

```
content/zh-cn/blog/_posts/2024-08-23-kubeadm-v1beta4.md
```
See [preview](https://deploy-preview-47598--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/23/kubernetes-1-31-kubeadm-v1beta4/).

[zh] Add a blog: 2024-08-23-kubeadm-v1beta4.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_debug/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_debug/_index.md

[zh-cn] sync kubectl_debug/_index.md

---

content/en/docs/reference/using-api/deprecation-policy.md

Fix tiny typo on deprecation-policy.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_restart.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_pod.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_restart.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_pod.md

[zh-cn] sync kubectl_top/* kubectl_rollout_restart

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_patch/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_plugin/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_plugin/kubectl_plugin_list.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_plugin/_index.md

[zh-cn] sync kubectl_plugin/* kubectl_patch

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_run/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_run/_index.md

[zh-cn] sync kubectl_run/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_taint/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_uncordon/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_version/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_wait/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_taint/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_uncordon/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_version/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_wait/_index.md

[zh-cn] sync kubectl_wait kubectl_version kubectl_uncordon kubectl_taint

---

content/ru/docs/concepts/overview/what-is-kubernetes.md

Added the initial of the language ("ru") for the page link in the documentation

Added the initial of the Russian language for the link

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_edit-last-applied.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_set-last-applied.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_view-last-applied.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_edit-last-applied.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_set-last-applied.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_view-last-applied.md

[zh-cn] sync generated/kubectl_apply/*

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_can-i.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_reconcile.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_whoami.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_can-i.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_reconcile.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_whoami.md

[zh-cn] sync generated/kubectl_auth/*

---

content/ja/docs/contribute/participate/_index.md

en PR https://github.com/kubernetes/website/pull/47496/files

[ja] Fix broken hyperlink

---

content/zh-cn/docs/reference/kubectl/generated/kubectl.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_annotate/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_api-resources/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_api-versions/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_api-resources/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_api-versions/_index.md

[zh-cn] sync kubectl kubectl_annotate kubectl_api-resources kubectl_api-versions

---

content/ja/_index.html

Update Japanese index.html
N/A

[ja] update Japanese index.html

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_set/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_env.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_resources.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_selector.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_serviceaccount.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_subject.md

[zh-cn] sync kubectl_set/*

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_delete/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_describe/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_drain/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_describe/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_drain/_index.md

[zh-cn] sync kubectl_delete kubectl_describe kubectl_diff kubectl_drain

---

content/ko/docs/contribute/participate/_index.md

en PR https://github.com/kubernetes/website/pull/47496/files

[ko] Fix broken hyperlink

---

README-bn.md
README-ja.md
README-ko.md
README-pt.md
README-uk.md
README-vi.md
README-zh.md

sync new contributor ambassador from README.md
the new contributor ambassador  in some of the translation is out of date , so update it .
Closes: #

sync new contributor ambassador from README.md

---

content/ko/docs/reference/kubectl/docker-cli-to-kubectl.md

en PR https://github.com/kubernetes/website/pull/47399/files

[ko] add the missing newline

---

content/en/docs/reference/command-line-tools-reference/feature-gates/kmsv2-kdf.md
content/en/docs/reference/command-line-tools-reference/feature-gates/kmsv2.md

Mark KMSv2 and KMSv2KDF feature gates as removed
fixes https://github.com/kubernetes/kubernetes/issues/126859

Mark KMSv2 and KMSv2KDF feature gates as removed

---

content/en/docs/tasks/configure-pod-container/image-volumes.md

Have a try to revise the step text, to tell why it is required to run those commands.

Revise step desc in image-volumes

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_autoscale/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_approve.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_deny.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_autoscale/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_approve.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_deny.md

[zh-cn] sync kubectl_autoscale kubectl_certificate/*

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_attach/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/kubectl_cluster-info_dump.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_completion/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_attach/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/kubectl_cluster-info_dump.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_completion/_index.md

[zh-cn] sync kubectl_attach kubectl_completion kubectl_cluster-info/*

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cp/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_events/_index.md

```
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_cp/_index.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_events/_index.md
```

[zh-cn] sync kubectl_cordon kubectl_cp kubectl_edit kubectl_events

---

content/en/docs/reference/command-line-tools-reference/feature-gates/legacy-service-account-token-clean-up.md

k/k: https://github.com/kubernetes/kubernetes/pull/126839
/hold

mark LegacyServiceAccountTokenCleanUp as removed

---

content/en/docs/reference/command-line-tools-reference/feature-gates/cloud-dual-stack-node-ips.md

k/k: https://github.com/kubernetes/kubernetes/pull/126840
/hold

mark CloudDualStackNodeIPs as removed

---

content/en/docs/reference/command-line-tools-reference/feature-gates/stable-load-balancer-node-set.md

k/k: https://github.com/kubernetes/kubernetes/pull/126841
/hold

mark StableLoadBalancerNodeSet as removed

---

content/zh-cn/blog/_posts/2024-06-21-custom-profiling-kubectl-debug.md

content/zh-cn/blog/_posts/2024-06-21-custom-profiling-kubectl-debug.md

[zh-cn] Add blog: 2024-06-21-custom-profiling-kubectl-debug.md

---

content/en/docs/concepts/services-networking/dns-pod-service.md

Signed-off-by: babugeet abhinandhbg@gmail.com
Better wording on A/AAAA records 
https://github.com/kubernetes/website/issues/47097

Updated Notes for DNS for Services and Pods

---

content/en/docs/tasks/tools/install-kubectl-windows.md

This PR clearly describes the two options for installing kubectl on Windows.
Closes: #47614

Update kubectl Download Options

---

content/zh-cn/docs/contribute/generate-ref-docs/kubernetes-components.md

[zh] Fix a typo

---

content/zh-cn/docs/tasks/administer-cluster/topology-manager.md

```
content/zh-cn/docs/tasks/administer-cluster/topology-manager.md
```
See [preview](https://deploy-preview-47649--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/topology-manager/).

[zh] Sync administer-cluster/topology-manager.md

---

content/zh-cn/docs/concepts/overview/components.md

content/zh-cn/docs/concepts/overview/components.md

[zh-cn] sync working-with-objects/components.md

---

content/zh-cn/blog/_posts/2024-08-20-websocket-transition.md

content/zh-cn/blog/_posts/2024-08-20-websocket-transition.md

[zh-cn] Add blog: 2024-08-20-websocket-transition.md

---

content/en/docs/tasks/administer-cluster/kms-provider.md

resolve: https://github.com/kubernetes/website/issues/47639

Remove stale advice about Kubernetes versions and KMS

---

content/zh-cn/docs/reference/kubectl/quick-reference.md

en PR https://github.com/kubernetes/website/pull/47570/files

[zh] fix typo in quick-reference.md

---

content/zh-cn/docs/reference/kubernetes-api/cluster-resources/component-status-v1.md

Update some text in :
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/component-status-v1.md
```
Find an issue like #47694.

[zh] Sync an api doc: component-status-v1.md

---

content/zh-cn/docs/concepts/overview/_index.md

Sync part of #47674 
```
content/zh-cn/docs/concepts/overview/_index.md
```
See [preview](https://deploy-preview-47693--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/overview/)

[zh] Sync concepts/overview/_index.md

---

content/en/docs/concepts/workloads/controllers/cron-jobs.md

the cron job in this example runs on the intersection of 13th of every month and Friday, not the union of these conditions. If the 13th falls on any other day of the week, the job will not run.
Closes: #

fixed cron job interpretation in the example

---

content/zh-cn/docs/reference/using-api/deprecation-policy.md

en PR https://github.com/kubernetes/website/pull/47479/files

[zh] fix typo in deprecation-policy.md

---

content/zh-cn/docs/reference/node/kernel-version-requirements.md

```
content/zh-cn/docs/reference/node/kernel-version-requirements.md
```

[zh] add kernel-version-requirements.md

---

content/en/docs/concepts/security/cloud-native-security.md

Fixed the security white-paper link in cloud-native-security.md

---

content/en/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md

Ref: #45409 
Updated the referenced doc as per the issue and the proposed solution

Update the apiserver-aggregation.md

---

layouts/blog/baseof.html
layouts/blog/list.html
layouts/blog/single.html
layouts/docs/baseof.html
layouts/docs/glossary.html
layouts/docs/list.html
layouts/docs/release-info.html
layouts/docs/single.html
layouts/partials/deprecation-warning.html

- Ready the deprecation warning mechanism for when we want to align with upstream Docsy
Intended to help with #41171.

Revise deprecation warnings to be more Docsy friendly

---

content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md

[zh] sync scheduling-eviction/node-pressure-eviction.md

[zh] sync scheduling-eviction/node-pressure-eviction.md

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/supplemental-groups-policy.md
content/zh-cn/docs/tasks/configure-pod-container/security-context.md
content/zh-cn/examples/pods/security/security-context-5.yaml
content/zh-cn/examples/pods/security/security-context-6.yaml

```
content/zh-cn/docs/tasks/configure-pod-container/security-context.md
```
See [preview](https://deploy-preview-47752--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/security-context/)

[zh] Sync a task: security-context.md

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_completion/_index.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig/_index.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_kubeconfig/kubeadm_kubeconfig_user.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_version/_index.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-version.md

```
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig.md
modified:   content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-version.md
```
and its dependent files
See [preview](https://deploy-preview-47726--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig/).

[zh] Sync kubeadm_completion, _kubeconfig, and _version

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/authorize-node-with-selectors.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dra-control-plane-controller.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/resilient-watch-cache-initialization.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/resource-health-status.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-cache-initialization-post-start-hook.md

```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/authorize-node-with-selectors.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dra-control-plane-controller.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/resilient-watch-cache-initialization.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/resource-health-status.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-cache-initialization-post-start-hook.md
```

[zh] Add 6 feature gates

---

content/ja/docs/concepts/security/_index.md

I translated docs/concepts/security/_index.md into Japanese.
Closes: #47434

[ja] Translate docs/concepts/security/_index.md into Japanese

---

content/ja/docs/reference/glossary/horizontal-pod-autoscaler.md

[ja] Translate Horizontal Pod Autoscaler into Japanese

---

api-ref-assets/config/fields.yaml

This PR updates the assets for API reference generation, again.
depends-on: #47711

Update assets for API reference generation

---

content/ja/docs/concepts/workloads/controllers/job.md

- Update Job title
FYI: https://kubernetes.io/ja/docs/contribute/localization/#terminology
> またこれらの単語は、複数形ではなく単数形を用います。 例えば、原文に"pods"と表記されている場合でも、日本語訳では"Pod"と表記してください。
Closes: #

[ja] Update title in job.md

---

content/ja/docs/reference/glossary/flexvolume.md

/language ja
- Translate `content/en/docs/reference/glossary/flexvolume.md` into Japanese
Closes: #47679

[ja]Translate content/en/docs/reference/glossary/flexvolume.md into Japanese

---

content/en/docs/reference/command-line-tools-reference/feature-gates/server-side-apply.md
content/en/docs/reference/command-line-tools-reference/feature-gates/server-side-field-validation.md

k/k: https://github.com/kubernetes/kubernetes/pull/127058
/hold

mark feature-gate ServerSideApply/ServerSideFieldValidation as removed

---

content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md

[zh] Update kubelet.md to fix several links

---

content/zh-cn/docs/reference/kubernetes-api/policy-resources/flow-schema-v1.md

Update this API doc from v1beta3 to v1:
```
deleted: content/zh-cn/docs/reference/kubernetes-api/cluster-resources/flow-schema-v1beta3.md
added: content/zh-cn/docs/reference/kubernetes-api/policy-resources/flow-schema-v1.md
```
See [preview](https://deploy-preview-47802--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/policy-resources/flow-schema-v1/)

[zh] Add an api doc: flow-schema-v1.md

---

OWNERS_ALIASES

Adding @niranjandarshann to Hindi reviewers
cc: @dipesh-rawat for approval.
@niranjandarshann : Once this PR is merged, you'll need to add yourself to [this file](https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml) and seek approval from Dipesh and me.

Adding Niranjan Darshan to Hindi reviewers

---

content/zh-cn/docs/reference/kubernetes-api/workload-resources/binding-v1.md

content/zh-cn/docs/reference/kubernetes-api/workload-resources/binding-v1.md

[zh-cn] Add binding-v1.md

---

content/vi/docs/reference/glossary/index.md

[vi] Ready glossary page for vanilla Docsy

---

README-es.md

[es] Enhance Readability with Markdown Formatting Improvements

---

content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1alpha3.md

```
content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1alpha3.md
```
See [preview](https://deploy-preview-47849--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1alpha3/)

[zh] Add device-class-v1alpha3.md

---

content/zh-cn/docs/reference/kubernetes-api/cluster-resources/service-cidr-v1beta1.md

```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/service-cidr-v1beta1.md
```
See [preview](https://deploy-preview-47866--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/service-cidr-v1beta1/).

[zh] Add cluster-resources/service-cidr-v1beta1.md

---

content/en/docs/concepts/overview/kubernetes-api.md

-  Add a **comma** before `while`.
To improve readability.

Update kubernetes-api.md: correct tenses and add punctuation

---

content/en/docs/reference/access-authn-authz/authentication.md

doc update for https://github.com/kubernetes/kubernetes/pull/126553
/sig auth
/assign enj

Add note about k8s.io, kubernetes disallowed prefix for structured authn

---

content/zh-cn/docs/concepts/security/cloud-native-security.md

en PR https://github.com/kubernetes/website/pull/47651/files

[zh] Fixed the security white-paper link

---

content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md

Revise some style issues in:
```
content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
```

[zh] update dns-debugging-resolution.md

---

content/en/docs/reference/access-authn-authz/bootstrap-tokens.md

Adds hyperlink for RFC3339
Closes: #47876

docs: add hyperlink for RFC3339 in bootstrap-tokens.md

---

content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md

Add some zh text in:
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md
```
See [preview](https://deploy-preview-47880--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1/)

[zh] Sync an api doc: cluster-resources/node-v1.md

---

content/en/docs/concepts/configuration/configmap.md
content/en/examples/configmap/env-configmap.yaml

Add envFrom details in docs

---

content/en/docs/concepts/overview/_index.md

Removed duplicated paragraph

---

content/ko/docs/concepts/overview/working-with-objects/owners-dependents.md

[ko] Translate /docs/concepts/overview/working-with-objects/owners-dependents into korean

---

content/en/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

Fix typo in storage-version-migration.md

---

content/zh-cn/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md

en PR https://github.com/kubernetes/website/pull/47165/files

[zh] Update the apiserver-aggregation.md

---

README-ja.md

en PR https://github.com/kubernetes/website/pull/47430/files

[ja] Enhance Readability with Markdown Formatting Improvements

---

data/releases/schedule.yaml

Update the release schedule to reflect the latest patches.
Updated using schedule-builder v0.17.7:
```
> schedule-builder -uc data/releases/schedule.yaml -e data/releases/eol.yaml
INFO Validating options
INFO Reading schedule file: data/releases/schedule.yaml
INFO Parsing schedule
INFO Updating schedule
INFO Adding release schedule: &{Release:1.31.2 CherryPickDeadline:2024-10-11 TargetDate:2024-10-15 Note:}
INFO Adding release schedule: &{Release:1.30.6 CherryPickDeadline:2024-10-11 TargetDate:2024-10-15 Note:}
INFO Adding release schedule: &{Release:1.29.10 CherryPickDeadline:2024-10-11 TargetDate:2024-10-15 Note:}
INFO Adding release schedule: &{Release:1.28.15 CherryPickDeadline:2024-10-11 TargetDate:2024-10-15 Note:}
INFO Skipping outdated upcoming release for  (2024-09-10)
INFO Using …
```

Update release schedule

---

content/zh-cn/docs/concepts/configuration/configmap.md
content/zh-cn/examples/configmap/env-configmap.yaml

Add som zh text to:
```
content/zh-cn/docs/concepts/configuration/configmap.md
```
See [preview](https://deploy-preview-47905--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/configuration/configmap/)

[zh] Sync a concept: configuation/configmap.md

---

content/zh-cn/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md

content/zh-cn/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/cluster-cidr-v1alpha1.md

[zh-cn] sync apiserver-aggregation

---

content/zh-cn/blog/_posts/2024-08-23-kubeadm-v1beta4.md

en PR https://github.com/kubernetes/website/pull/47714/files

[zh] Fix doc link

---

content/en/docs/tasks/administer-cluster/verify-signed-artifacts.md

Changes outdated Cosign link with new one
Closes: #47940

Changes outdated cosign link

---

content/zh-cn/docs/concepts/services-networking/ingress.md
content/zh-cn/docs/concepts/services-networking/service.md

content/zh-cn/docs/concepts/services-networking/ingress.md

[zh-cn] sync service ingress

---

content/zh-cn/docs/tasks/administer-cluster/kms-provider.md
content/zh-cn/docs/tasks/administer-cluster/kubelet-config-file.md
content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

content/zh-cn/docs/tasks/administer-cluster/kms-provider.md
content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md

[zh-cn]sync kms-provider kubelet-config-file storage-version-migration
