- content/zh-cn/docs/concepts/cluster-administration/addons.md
- content/zh-cn/docs/concepts/overview/_index.md
content/zh-cn/docs/concepts/cluster-administration/addons.md
content/zh-cn/docs/concepts/overview/_index.md
> [zh-cn] sync addons.md overview/_index.md

- content/zh-cn/docs/tasks/administer-cluster/decrypt-data.md
content/zh-cn/docs/tasks/administer-cluster/decrypt-data.md
> [zh-cn] sync decrypt-data

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/stateful-set-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/stateful-set-v1.md
> [zh-cn] sync stateful-set-v1.md

- content/en/docs/concepts/storage/storage-classes.md
> Add AWS EFS To storage-classes.md

- content/zh-cn/docs/reference/glossary/kube-apiserver.md
en PR https://github.com/kubernetes/website/pull/47743/files
> [zh] Update kube-apiserver.md

- content/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters.md
content/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters.md
> [zh-cn] sync common-parameters.md

- content/zh-cn/docs/reference/kubernetes-api/authentication-resources/service-account-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authentication-resources/token-request-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/service-account-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/token-request-v1.md
> [zh-cn] sync service-account-v1 token-request-v1

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md
> [zh-cn] sync persistent-volume-claim-v1.md

- content/zh-cn/docs/concepts/services-networking/dns-pod-service.md
> [zh] Update concepts/service-networking/dns-pod-service.md

- content/zh-cn/docs/setup/best-practices/certificates.md
content/zh-cn/docs/setup/best-practices/certificates.md
> [zh-cn] sync best-practices/certificates.md

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
> [zh-cn] sync manage-resources-containers assign-pod-node pod-lifecycle

- content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
- content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> [zh-cn]sync network-policy-v1 resource-quota-v1 endpoints-v1 kubeadm-config.v1beta3

- content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
- content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
- content/zh-cn/docs/reference/config-api/kube-proxy-config.v1alpha1.md
content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
> [zh-cn]sync apiserver-audit.v1 kube-controller-manager-config.v1alpha1 kube-proxy-config.v1alpha1

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md
> [zh-cn] sync job-v1.md

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
> [zh-cn] sync custom-resource-definition-v1.md

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/_index.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/limit-range-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
Sync 3 files and add some minor changes:
```
content/zh-cn/docs/reference/kubernetes-api/policy-resources/_index.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/limit-range-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
```
> [zh] Sync api docs in policy-resources/

- content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1.md
content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1.md
> [zh-cn] sync endpoint-slice-v1.md

- content/en/docs/concepts/cluster-administration/node-shutdown.md
- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/node-out-of-service-volume-detach.md
- content/en/docs/reference/labels-annotations-taints/_index.md
k/k: https://github.com/kubernetes/kubernetes/pull/127019
/hold
/sig storage
/cc @xing-yang
> mark feature-gate NodeOutOfServiceVolumeDetach as removed

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/csi-node-expand-secret.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-resource-field-selectors.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-resource-validation-expressions.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/csi-node-expand-secret.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-resource-field-selectors.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/custom-resource-validation-expressions.md
> [zh-cn] sync feature-gates/c*

- data/releases/schedule.yaml
Manually adding the release.
cc @kubernetes/release-managers 
Refers to https://github.com/kubernetes/website/issues/47990
> Add v1.31.0 to the release schedule

- content/ja/docs/tutorials/hello-minikube.md
Can not pull echo-server image 1.4 and different from english page.
> [ja] Change an container image which hello-node to e2e-test-images

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/local-storage-capacity-isolation-fs-quota-monitoring.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/logarithmic-scale-down.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/local-storage-capacity-isolation-fs-quota-monitoring.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/logarithmic-scale-down.md
> [zh-cn] sync feature-gates/l*

- content/zh-cn/examples/pods/inject/envars.yaml
- content/zh-cn/examples/pods/pod-with-scheduling-gates.yaml
- content/zh-cn/examples/pods/security/seccomp/ga/audit-pod.yaml
- content/zh-cn/examples/pods/security/seccomp/ga/default-pod.yaml
- content/zh-cn/examples/pods/security/seccomp/ga/fine-pod.yaml
- content/zh-cn/examples/pods/security/seccomp/ga/violation-pod.yaml
- content/zh-cn/examples/pods/security/security-context-2.yaml
- content/zh-cn/examples/pods/security/security-context-3.yaml
- content/zh-cn/examples/pods/security/security-context-4.yaml
- content/zh-cn/examples/pods/security/security-context.yaml
- content/zh-cn/examples/pods/share-process-namespace.yaml
- content/zh-cn/examples/pods/storage/projected-clustertrustbundle.yaml
- content/zh-cn/examples/pods/storage/projected-secret-downwardapi-configmap.yaml
- content/zh-cn/examples/pods/storage/projected-secrets-nondefault-permission-mode.yaml
- content/zh-cn/examples/pods/storage/projected-service-account-token.yaml
[zh-cn] Resync pod example YAMLs
Closes: #
> [zh-cn] Resync pod example YAMLs

- content/zh-cn/docs/concepts/services-networking/_index.md
```
content/zh-cn/docs/concepts/services-networking/_index.md
```
See [preview](https://deploy-preview-48007--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/services-networking/)
> [zh] Sync services-networking/_index.md

- content/zh-cn/examples/application/deployment-sidecar.yaml
- content/zh-cn/examples/application/job/job-sidecar.yaml
- content/zh-cn/examples/application/web/web-parallel.yaml
- content/zh-cn/examples/application/web/web.yaml
- content/zh-cn/examples/priority-and-fairness/health-for-strangers.yaml
- content/zh-cn/examples/priority-and-fairness/list-events-default-service-account.yaml
- content/zh-cn/examples/service/access/hello-application.yaml
[zh-cn] Resync the remaining examples YAMLs
Closes: #
> [zh-cn] Resync the remaining examples YAMLs

- content/zh-cn/docs/concepts/architecture/controller.md
- content/zh-cn/docs/concepts/architecture/garbage-collection.md
- content/zh-cn/docs/concepts/architecture/nodes.md
content/zh-cn/docs/concepts/architecture/controller.md
> [zh-cn]sync controller garbage-collection nodes

- content/zh-cn/docs/reference/kubernetes-api/common-definitions/status.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/status.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1.md
> [zh-cn] sync status csi-storage-capacity-v1

- content/ja/docs/tutorials/services/source-ip.md
https://github.com/kubernetes/website/pull/47832/files
> [ja] Replace Deprecated echoserver

- content/zh-cn/docs/tutorials/services/source-ip.md
https://github.com/kubernetes/website/pull/47832/files
> [zh] Replace Deprecated echoserver

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/nftables-proxy-mode.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-attributes-class.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/nftables-proxy-mode.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/volume-attributes-class.md
> [zh-cn]sync nftables-proxy-mode volume-attributes-class

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/apparmor.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-node-kube-proxy-version.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/apparmor.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-node-kube-proxy-version.md
> [zh-cn] sync apparmor disable-node-kube-proxy-version

- content/zh-cn/docs/contribute/new-content/blogs-case-studies.md
content/zh-cn/docs/contribute/new-content/blogs-case-studies.md
> [zh-cn] sync blogs-case-studies

- content/zh-cn/docs/concepts/architecture/control-plane-node-communication.md
- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
content/zh-cn/docs/concepts/architecture/control-plane-node-communication.md
content/zh-cn/docs/concepts/workloads/controllers/deployment.md
> [zh-cn] sync control-plane-node-communication deployment

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-vsphere-unregister.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-vsphere-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding.md
> [zh-cn]sync in-tree-plugin-vsphere-unregister service-account-token-node-binding

- content/ko/docs/tutorials/services/source-ip.md
https://github.com/kubernetes/website/pull/47832/files
> [ko] Replace Deprecated echoserver

- content/en/docs/concepts/storage/storage-classes.md
Contente was mixed btw ebs and efs
https://github.com/kubernetes/website/issues/48049
Closes: #
> Fix Content Got Mixed btw EBS & EFS

- data/i18n/bn/bn.toml
/language bn
Fix a bug where the month name was hard coded.
> bn: Fix bad localization for a date string

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/_index.md
https://github.com/kubernetes/website/pull/47861/files
> [zh] Fix grammatical error

- content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
- content/zh-cn/docs/concepts/storage/ephemeral-volumes.md
content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
content/zh-cn/docs/concepts/storage/ephemeral-volumes.md
> [zh-cn] sync taint-and-toleration ephemeral-volumes

- content/zh-cn/docs/concepts/storage/volumes.md
Sync file:
```
/docs/concepts/storage/volumes.md
```
Find a missing sentence in this file and translate it.
> [zh-cn] sync /docs/concepts/storage/volumes.md

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
```
See [preview](https://deploy-preview-47997--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume/)
> [zh] Sync config-and-storage-resources/volume.md

- content/en/docs/tasks/administer-cluster/coredns.md
- content/pt-br/docs/tasks/administer-cluster/coredns.md
This PR adds the brazilian portuguese version of docs/tasks/administer-cluster/coredns.md
PR for https://github.com/kubernetes/website/issues/47400
> [pt-br] Add /docs/tasks/administer-cluster/coredns.md

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/_index.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/_index.md
> [zh-cn]sync kubeadm/_index.md

- content/en/blog/_posts/2022-12-19-devicemanager-ga.md/index.md
- content/en/docs/tasks/manage-gpus/scheduling-gpus.md
Similar to https://github.com/kubernetes/website/pull/45296, updating urls to avoid redirects due to repo move.
> Update links for AMD GPU device plugin

- content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
Remove PersistentVolumeLabel section from zh page:
```
```
> [zh] Sync admission-controllers.md

- content/pt-br/docs/reference/access-authn-authz/bootstrap-tokens.md
https://github.com/kubernetes/website/pull/47882/files
> [pt] Add hyperlink for RFC3339

- content/zh-cn/blog/_posts/2024-08-13-Kubernetes-v1-31-Release.md
> [zh] add blog 2024-08-13-Kubernetes-v1-31-Release.md

- content/es/docs/tasks/network/_index.md
- Create content spanish translation : docs/tasks/network/_index.md
Related to https://github.com/kubernetes/website/issues/48073
> feat: [es] Create docs/tasks/network/_index.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1.md
Update this zh page:
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1.md
```
See [preview](https://deploy-preview-48075--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1/)
> [zh] Sync cluster-resources/lease-v1.md

- content/zh-cn/docs/concepts/workloads/controllers/cron-jobs.md
- content/zh-cn/docs/concepts/workloads/pods/_index.md
> [zh-cn] sync cron-jobs pods/_index

- content/en/docs/concepts/storage/storage-classes.md
- content/en/examples/storage/storageclass/pod-volume-binding.yaml
- content/en/examples/storage/storageclass/storageclass-aws-ebs.yaml
- content/en/examples/storage/storageclass/storageclass-aws-efs.yaml
- content/en/examples/storage/storageclass/storageclass-azure-file.yaml
- content/en/examples/storage/storageclass/storageclass-ceph-rbd.yaml
- content/en/examples/storage/storageclass/storageclass-local.yaml
- content/en/examples/storage/storageclass/storageclass-nfs.yaml
- content/en/examples/storage/storageclass/storageclass-portworx-volume.yaml
- content/en/examples/storage/storageclass/storageclass-topology.yaml
content/en/docs/concepts/storage/storage-classes.md
> improve yaml context for storage/storage-classes.md

- content/zh-cn/blog/_posts/2024-09-17-sig-scheduling-spotlight.md
```
content/zh-cn/blog/_posts/2024-09-17-sig-scheduling-spotlight.md
```
See [preview](https://deploy-preview-48043--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/09/24/sig-scheduling-spotlight-2024/)
> [zh] Add a blog: 2024-09-17-sig-scheduling-spotlight

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
Sync file:
```
content/zh-cn/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
```
> [zh-cn] sync adding-windows-nodes.md

- content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
- content/zh-cn/docs/reference/access-authn-authz/node.md
- content/zh-cn/docs/reference/glossary/watch.md
- content/zh-cn/docs/reference/using-api/api-concepts.md
content/zh-cn/docs/reference/access-authn-authz/node.md
> [zh-cn] sync api-concepts admission-controllers node

- content/zh-cn/docs/concepts/overview/kubernetes-api.md
- content/zh-cn/docs/concepts/windows/intro.md
content/zh-cn/docs/concepts/overview/kubernetes-api.md
content/zh-cn/docs/concepts/windows/intro.md
> [zh-cn]sync kubernetes-api intro

- content/zh-cn/docs/tutorials/_index.md
- content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md
content/zh-cn/docs/tutorials/_index.md
> [zh-cn]sync basic-stateful-set tutorials/_index

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
> [zh-cn] sync docs/reference/kubernetes-api/csi-driver-v1.md

- content/en/docs/tutorials/security/apparmor.md
Just fixing a super small grammar issue.
Closes: #
> Fix typo in apparmor.md

- content/de/docs/concepts/cluster-administration/addons.md
> [de] Removed Weave Scope link

- content/zh-cn/docs/contribute/docs.md
使用 `./scripts/lsync.sh content/zh-cn/docs/contribute/docs.md` 发现变更的地方挺多，但是逐一检查后只有两处尾部空格多余。
Closes: #
> [zh-cn] sync docs/contribute/docs.md

- content/zh-cn/docs/concepts/overview/working-with-objects/labels.md
> [zh-cn] sync docs/concepts/overview/working-with-objects/labels.md

- content/ko/docs/concepts/cluster-administration/addons.md
> [ko] Removed Weave Scope link

- content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> [zh-cn] sync docs/concepts/overview/working-with-objects/_index.md

- content/en/docs/reference/config-api/kubeadm-config.v1beta4.md
> Update config API for kubeadm v1beta4

- content/ru/docs/concepts/cluster-administration/addons.md
> [ru] Removed Weave Scope link

- content/zh-cn/docs/concepts/workloads/pods/init-containers.md
> [zh-cn] sync docs/concepts/workloads/pods/init-containers.md

- content/en/docs/contribute/participate/pr-wranglers.md
- content/en/docs/doc-contributor-tools/linkchecker/README.md
Perform the following changes:
- provide consistent indentations for bullets
/kind cleanup
> Tweak and clean up pr-wranglers and linkchecke readme

- content/zh-cn/docs/concepts/scheduling-eviction/_index.md
> [zh-cn] sync docs/concepts/scheduling-eviction/_index.md

- content/es/docs/tutorials/_index.md
- Update content spanish translation : docs/tutorials/_index.md
Related to https://github.com/kubernetes/website/issues/48066
> feat: [es] Update docs/tutorials/_index.md

- content/zh-cn/docs/concepts/architecture/garbage-collection.md
> [zh-cn] sync docs/concepts/architecture/garbage-collection.md

- content/zh-cn/docs/concepts/security/cloud-native-security.md
> [zh-cn] sync /docs/concepts/security/cloud-native-security.md

- hugo.toml
Updating hugo.toml for the 1.32 release.
> Updated config.toml for 1.32 release

- content/zh-cn/docs/concepts/storage/storage-classes.md
> [zh-cn] sync docs/concepts/storage/storage-classes.md

- assets/scss/_base.scss
- assets/scss/_custom.scss
- layouts/partials/footer.html
This helps with https://github.com/kubernetes/website/issues/41171
Make the site footer look more like the footer from Docsy.
[Before](https://k8s.io/docs/) | [After](https://deploy-preview-47789--kubernetes-io-main-staging.netlify.app/docs/)
> Use Docsy friendly footer

- content/zh-cn/docs/concepts/scheduling-eviction/_index.md
- content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
Update 3 files:
```
content/zh-cn/docs/concepts/scheduling-eviction/_index.md
content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
```
> [zh] Sync scheduling-eviction/*.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/controller-revision-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/deployment-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/controller-revision-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/deployment-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> [zh-cn]sync controller-revision-v1 deployment-v1 priority-class-v1

- content/zh-cn/docs/contribute/participate/pr-wranglers.md
- content/zh-cn/docs/doc-contributor-tools/linkchecker/README.md
content/zh-cn/docs/contribute/participate/pr-wranglers.md
content/zh-cn/docs/doc-contributor-tools/linkchecker/README.md
> [zh-cn]sync pr-wranglers linkchecker/README

- content/zh-cn/docs/tasks/network/customize-hosts-file-for-pods.md
```
content/zh-cn/docs/tasks/network/customize-hosts-file-for-pods.md
```
> [zh] Sync customize-hosts-file-for-pods.md

- content/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz.md
Sync with en PR #48012 
```
content/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz.md
```
> [zh] Sync kubelet-authn-authz.md

- content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
> [zh-cn] sync docs/reference/access-authn-authz/service-accounts-admin.md

- content/ja/docs/concepts/cluster-administration/addons.md
> [ja] Removed Weave Scope link

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/zh-cn/docs/tasks/manage-gpus/scheduling-gpus.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
content/zh-cn/docs/tasks/manage-gpus/scheduling-gpus.md
> [zh-cn]sync kubeadm-upgrade scheduling-gpus

- content/zh-cn/docs/reference/labels-annotations-taints/audit-annotations.md
> [zh-cn] sync reference/audit-annotations.md

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-node-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-node-v1.md
> [zh-cn]sync csi-node-v1.md

- content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> [zh-cn] sync docs/reference/labels-annotations-taints

- content/zh-cn/docs/reference/kubernetes-api/common-definitions/local-object-reference.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/local-object-reference.md
> [zh-cn]sync local-object-reference.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/consistent-list-from-cache.md
sync file:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/consistent-list-from-cache.md
```
> [zh-cn] sync consistent-list-from-cache.md

- content/zh-cn/docs/reference/config-api/apiserver-config.v1.md
```
content/zh-cn/docs/reference/config-api/apiserver-config.v1.md
```
See [preview](https://deploy-preview-48091--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/apiserver-config.v1/)
> [zh] Add zh text to: config-api/apiserver-config.v1.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-candidate-v1alpha1.md
Add zh text to this API doc:
```
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-candidate-v1alpha1.md
```
See [preview](https://deploy-preview-48123--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-candidate-v1alpha1/)
> [zh] Add an API doc: lease-candidate-v1alpha1.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-resource-allocation.md
> [zh-cn] sync reference/dynamic-resource-allocation.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/device-plugin-cdi-devices.md
> [zh-cn] sync reference/device-plugin-cdi-devices.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/consistent-http-get-handlers.md
> [zh-cn] sync reference/consistent-http-get-handlers.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/honor-pv-reclaim-policy.md
> [zh-cn] sync reference/honor-pv-reclaim-policy.md

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1.md
update this zh file:
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1.md
```
See [preview](https://deploy-preview-48227--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/)
> [zh] Sync config-and-storage-resources/storage-class-v1.md

- content/es/docs/concepts/cluster-administration/addons.md
> [es] Removed Weave Scope link

- content/zh-cn/blog/_posts/2024-09-17-sig-scheduling-spotlight.md
content/zh-cn/blog/_posts/2024-09-17-sig-scheduling-spotlight.md
> [zh-cn]sync 2024-09-17-sig-scheduling-spotlight.md

- content/zh-cn/blog/_posts/2024-10-02-steering-committee-results-2024.md
content/zh-cn/blog/_posts/2024-10-02-steering-committee-results-2024.md
> [zh-cn] Add blog: 2024-10-02-steering-committee-results-2024.md

- content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
Change:
```
content/en/docs/tasks/configure-pod-container/configure-pod-configmap.md
```
* Remove special-config before next step will create newer with different data.
* Fix quotation mark of cleanup command.
* Add cleanup command of created files and directories.
> [en] config-pod-configmap add cleanup step and fix commands.

- content/ru/_index.html
Bringing the events update (from #48152) to the Russian localisation.
> [ru] Update KubeCon 2024-2025 events

- content/ja/docs/tasks/manage-gpus/scheduling-gpus.md
https://github.com/kubernetes/website/pull/48022/files
> [ja] Update links for AMD GPU device plugin

- content/en/docs/tasks/run-application/run-replicated-stateful-application.md
[kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#statefulset
](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#statefulset)this page does not specify AMD64 CPU as a requirement
> added AMD64 CPU as a requirement

- content/en/docs/reference/networking/virtual-ips.md
Supplement IPVS scheduling algorithms that added in https://github.com/kubernetes/kubernetes/issues/114619
Closes: #
> Supplement the description of IPVS

- content/zh-cn/docs/concepts/security/linux-kernel-security-constraints.md
content/zh-cn/docs/concepts/security/linux-kernel-security-constraints.md
> [zh-cn]sync linux-kernel-security-constraints

- content/uk/_index.html
https://github.com/kubernetes/website/pull/48152/files
> [uk] Update KubeCon 2024-2025 events

- content/pt-br/docs/concepts/cluster-administration/addons.md
> [pt] Removed Weave Scope link

- content/ja/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
https://github.com/kubernetes/website/pull/48120/files
> [ja] Remove deprecated note

- content/zh-cn/docs/reference/networking/virtual-ips.md
Closes: #48245
See [the preview page](https://deploy-preview-48249--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/networking/virtual-ips/).
> [zh-cn] Resync content/zh-cn/docs/reference/networking/virtual-ips.md

- content/zh-cn/docs/concepts/security/cloud-native-security.md
> [zh-cn] sync cloud-native-security.md

- content/zh-cn/docs/concepts/security/multi-tenancy.md
> [zh-cn] sync concepts/multi-tenancy.md

- content/zh-cn/docs/reference/node/seccomp.md
- content/zh-cn/examples/pods/security/seccomp/fields.yaml
Sync one file after en PR #47967
```
content/zh-cn/docs/reference/node/seccomp.md
```
See [preview](https://deploy-preview-48269--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/node/seccomp/)
> [zh] Add node/seccomp.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/RemoveSelfLink.md
Add zh text to this feature gate:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/RemoveSelfLink.md
```
> [zh] Add feature-gates/RemoveSelfLink.md

- assets/scss/_custom.scss
- static/css/gridpage.css
> Fix poor web style in some page footers

- content/zh-cn/docs/reference/labels-annotations-taints/_index.md
Update some zh text in:
```
```
> [zh] Resync labels-annotations-taints/_index.md

- content/zh-cn/blog/_posts/2024-08-19-pod-failure-policy-for-jobs-goes-ga.md
```
content/zh-cn/blog/_posts/2024-08-19-pod-failure-policy-for-jobs-goes-ga.md
```
See [preview](https://deploy-preview-48285--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/19/kubernetes-1-31-pod-failure-policy-for-jobs-goes-ga/)
> [zh] Add 2024-08-19-pod-failure-policy-for-jobs-goes-ga.md

- content/zh-cn/docs/reference/glossary/duration.md
Add zh text to this glossary:
```
content/zh-cn/docs/reference/glossary/duration.md
```
> [zh] Add glossary/duration.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
> [zh-cn] sync reference/cron-job-v1.md

- content/zh-cn/docs/reference/node/_index.md
> [zh-cn] sync reference/node/_index.md

- content/zh-cn/docs/reference/access-authn-authz/psp-to-pod-security-standards.md
> [zh-cn] sync reference/psp-to-pod-security-standards.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v1.md
> [zh-cn] sync reference/horizontal-pod-autoscaler-v1.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/runtime-class-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attachment-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-template-v1.md
> [zh-cn] sync weight in multi reference files

- content/fr/docs/tasks/configure-pod-container/share-process-namespace.md
https://github.com/kubernetes/website/pull/48267/files
> [fr] Changed the command for Attaching to the shell container

- content/zh-cn/docs/reference/glossary/manifest.md
> [zh-cn] sync reference/manifest.md

- content/ko/examples/service/networking/example-ingress.yaml
> [ko] Add ingress class name to example-ingress.yaml

- content/ko/docs/tasks/configure-pod-container/_index.md
- content/ko/docs/tasks/configure-pod-container/assign-cpu-resource.md
- content/ko/docs/tasks/configure-pod-container/assign-memory-resource.md
- content/ko/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md
- content/ko/docs/tasks/configure-pod-container/assign-pods-nodes.md
- content/ko/docs/tasks/configure-pod-container/configure-gmsa.md
- content/ko/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
- content/ko/docs/tasks/configure-pod-container/configure-pod-initialization.md
- content/ko/docs/tasks/configure-pod-container/configure-projected-volume-storage.md
- content/ko/docs/tasks/configure-pod-container/configure-runasusername.md
- content/ko/docs/tasks/configure-pod-container/configure-volume-storage.md
- content/ko/docs/tasks/configure-pod-container/extended-resource.md
- content/ko/docs/tasks/configure-pod-container/pull-image-private-registry.md
- content/ko/docs/tasks/configure-pod-container/quality-service-pod.md
- content/ko/docs/tasks/configure-pod-container/static-pod.md
- content/ko/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
- content/ko/docs/tasks/configure-pod-container/user-namespaces.md
Related Issue: #41631
Updated outdated files in `content/en/docs/tasks/configure-pod-container/`.
**17 files to be modified**
> [ko] Update outdated files in dev-1.27-ko.1 (M160-M176)

- content/zh-cn/docs/reference/using-api/api-concepts.md
Sync with en PR #46230 
```
```
> [zh] Sync using-api/api-concepts.md

- content/ja/docs/tasks/configure-pod-container/share-process-namespace.md
https://github.com/kubernetes/website/pull/48267/files
> [ja] Changed the command for Attaching to the shell container

- content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md
content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md
> [zh-cn] sync configure-pod-configmap.md

- content/zh-cn/docs/concepts/containers/_index.md
> [zh-cn] sync concepts/containers/_index.md

- content/zh-cn/docs/concepts/workloads/pods/sidecar-containers.md
> [zh] Sync pods/sidecar-containers.md

- content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
Update zh text:
```
content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
```
> [zh] Sync cluster-administration/system-metrics.md

- content/zh-cn/README.md
> [zh] Delete Localization READMEs section in localized README

- content/vi/README.md
> [vi] Delete Localization READMEs section in localized README

- content/zh-cn/docs/reference/using-api/cel.md
```
content/zh-cn/docs/reference/using-api/cel.md
```
> [zh] Resync reference/using-api/cel.md

- content/id/docs/tasks/configure-pod-container/share-process-namespace.md
https://github.com/kubernetes/website/pull/48267/files
> [id] Changed the command for Attaching to the shell container

- content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
- content/en/docs/setup/production-environment/tools/kubeadm/ha-topology.md
- content/en/docs/setup/production-environment/tools/kubeadm/high-availability.md
- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
- remove redundant blank lines
- make bullet indentations consistent
- fix a few typos and add backtick symbols
> Tweak and clean up four kubeadm files

- content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
Correct statement about Pod Ready condition in probe config section
Closes: #47503
> Correct statement about Pod Ready condition in probe config section

- content/zh-cn/docs/setup/best-practices/cluster-large.md
> [zh] Update best-practices/cluster-large.md

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
- content/zh-cn/docs/setup/production-environment/tools/kubeadm/ha-topology.md
- content/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability.md
- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Sync with en #48375 
```
content/zh-cn/docs/setup/production-environment/tools/kubeadm/ha-topology.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/high-availability.md
```
> [zh] Sync four files in tools/kubeadm/

- content/pt-br/docs/tasks/configure-pod-container/share-process-namespace.md
https://github.com/kubernetes/website/pull/48267/files
> [pt] Changed the command for Attaching to the shell container

- content/en/docs/contribute/new-content/new-features.md
- Clarify a few details about feature gate metadata
- Clean up some whitespace
> Tweak docs about docs for features

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
- content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- content/zh-cn/docs/tasks/extend-kubectl/kubectl-plugins.md
Synchronize the following files:
```
content/zh-cn/docs/tasks/configure-pod-container/ss-readiness-startup-probes.md
content/zh-cn/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md
content/zh-cn/docs/tasks/extend-kubectl/kubectl-plugins.md
```
> [zh-cn] Resync tasks/

- content/zh-cn/docs/contribute/new-content/new-features.md
Sync with en #48386 and #48414
```
content/zh-cn/docs/contribute/new-content/new-features.md
```
> [zh] Sync new-content/new-features.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/api-service-v1.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/api-service-v1.md
> [zh-cn]sync api-service-v1.md

- content/zh-cn/docs/contribute/new-content/open-a-pr.md
content/zh-cn/docs/contribute/new-content/open-a-pr.md
> [zh-cn] sync open-a-pr.md

- content/zh-cn/docs/concepts/storage/persistent-volumes.md
- content/zh-cn/docs/concepts/workloads/controllers/ttlafterfinished.md
- content/zh-cn/docs/tutorials/_index.md
content/zh-cn/docs/concepts/workloads/controllers/ttlafterfinished.md
content/zh-cn/docs/tutorials/_index.md
> [zh-cn]sync persistent-volumes ttlafterfinished tutorials/_index

- assets/scss/_base.scss
- assets/scss/_custom.scss
- assets/scss/_documentation.scss
- assets/scss/_tablet.scss
- assets/scss/_variables_project.scss
As blue is our site's primary color, use the Docsy variable for that: `$primary`.
Here's a [preview](https://deploy-preview-48229--kubernetes-io-main-staging.netlify.app/)
> Use Docsy variable name for blue

- content/zh-cn/docs/reference/config-api/apiserver-admission.v1.md
- content/zh-cn/docs/reference/config-api/client-authentication.v1.md
> [zh-cn]sync apiserver-admission.v1 client-authentication.v1

- content/zh-cn/docs/reference/glossary/network-policy.md
- content/zh-cn/docs/reference/glossary/volume.md
content/zh-cn/docs/reference/glossary/network-policy.md
content/zh-cn/docs/reference/glossary/volume.md
> [zh-cn]sync network-policy volume

- content/zh-cn/docs/reference/glossary/cluster-operator.md
- content/zh-cn/docs/reference/glossary/node.md
- content/zh-cn/docs/reference/glossary/quantity.md
content/zh-cn/docs/reference/glossary/cluster-operator.md
content/zh-cn/docs/reference/glossary/node.md
content/zh-cn/docs/reference/glossary/quantity.md
> [zh-cn]sync cluster-operator node quantity

- content/zh-cn/docs/reference/glossary/cloud-controller-manager.md
- content/zh-cn/docs/reference/glossary/cluster-operator.md
- content/zh-cn/docs/reference/glossary/dynamic-volume-provisioning.md
- content/zh-cn/docs/reference/glossary/network-policy.md
- content/zh-cn/docs/reference/glossary/node.md
- content/zh-cn/docs/reference/glossary/qos-class.md
- content/zh-cn/docs/reference/glossary/quantity.md
- content/zh-cn/docs/reference/glossary/taint.md
- content/zh-cn/docs/reference/glossary/volume-plugin.md
- content/zh-cn/docs/reference/glossary/volume.md
> [zh-cn] sync tags in reference/glossary

- content/id/docs/tasks/configure-pod-container/static-pod.md
https://github.com/kubernetes/website/pull/48345/files
> [id] Fix typo

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
Update the overview to make it clear that `kubeadm join` can be run to create a worker node as well as a new control plane.
Closes:  #48399
> update kubeadm doc

- content/bn/docs/reference/glossary/developer.md
localized developer.md
fixes issue: #45729
> [bn] localized developer.md

- content/bn/docs/concepts/containers/_index.md
update containers/_index.md in bangla
Tracking Issue:  #31677
> [bn] update containers/_index.md

- content/bn/_index.html
update bn _index.html
tracking issue : https://github.com/kubernetes/website/issues/31677
> [bn] update bn _index.html

- content/bn/docs/reference/glossary/volume.md
delete core-object tag in  bn/docs/reference/glossary/volume.md
> [bn] delete  core-object tag

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/job-managed-by.md
This is a placeholder PR to update docs as JobManagedBy graduates to Beta. The code PR is already merged https://github.com/kubernetes/kubernetes/pull/127402.
Part of https://github.com/kubernetes/enhancements/issues/4368
> Update docs as JobManagedBy graduates to Beta

- content/en/docs/reference/access-authn-authz/kubelet-authn-authz.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/kubelet-finegrained-authz.md
Add documentation for [KEP-2862](https://github.com/kubernetes/enhancements/issues/2862): Fine-grained Authz for Kubelet API.
https://github.com/kubernetes/enhancements/issues/2862
> KEP-2862: Fine-grained Authz for Kubelet API.

- data/i18n/en/en.toml
- layouts/shortcodes/feature-state.html
Update the feature-state shortcode to display the default value. This makes it clear what the feature-gate default value is and we don't need to update the docs content if we are only updating the feature-gate launch stage.
Closes: #
Before change:
After change:
> Update the feature-state shortcode to display the default value.

- content/en/docs/reference/command-line-tools-reference/feature-gates/authorize-node-with-selectors.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/authorize-with-selectors.md
Promotes https://github.com/kubernetes/enhancements/issues/4601 to beta
/hold for https://github.com/kubernetes/kubernetes/pull/128168
/sig auth
/cc @deads2k
> KEP-4601: Promote AuthorizeWithSelectors / AuthorizeNodeWithSelectors to beta

- content/en/docs/reference/command-line-tools-reference/feature-gates/api-priority-and-fairness.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/csi-migration-rbd.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-rbd-unregister.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/job-ready-pods.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/skip-read-only-validation-gce.md
Mark some already-removed feature gates as removed. Also, tweak descriptions.
---
Inspired by existing PRs:
- #47837
- #47842
- #47848
- #47850
- #47856
> Mark some already-removed feature gates as removed

- content/pt-br/docs/concepts/windows/_index.md
Closes: https://github.com/kubernetes/website/issues/48421
> [pt-br] Create docs/concepts/windows

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-join.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-join.md
> [zh-cn]sync kubeadm-join.md

- content/zh-cn/docs/reference/using-api/api-concepts.md
> [zh] Resync using-api/api-concepts.md

- content/en/docs/concepts/services-networking/cluster-ip-allocation.md
> Fix Typo in Cluster IP Allocation Page

- content/zh-cn/docs/concepts/architecture/_index.md
- content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md
- content/zh-cn/docs/reference/glossary/duration.md
content/zh-cn/docs/concepts/architecture/_index.md
content/zh-cn/docs/reference/glossary/duration.md
content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md
> [zh-cn]sync architecture/_index duration cluster-autoscaling

- content/zh-cn/docs/concepts/architecture/garbage-collection.md
- content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
content/zh-cn/docs/contribute/style/hugo-shortcodes/index.md
> [zh-cn]sync hugo-shortcodes/index garbage-collection

- content/zh-cn/docs/reference/using-api/deprecation-policy.md
Sync with en #48542 
```
content/zh-cn/docs/reference/using-api/deprecation-policy.md
```
> [zh] Sync using-api/deprecation-policy.md

- content/en/community/static/cncf-code-of-conduct.md
> [en] update contributor covenant links

- content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md
content/zh-cn/docs/reference/config-api/imagepolicy.v1alpha1.md
> [zh-cn]sync imagepolicy.v1alpha1.md

- content/en/docs/reference/access-authn-authz/authentication.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
Update the stage from Alpha to Beta for featuregate AnonymousAuthConfigurableEndpoints in kubernetes documentation.
KEP: https://github.com/kubernetes/enhancements/issues/4633
PR(s): https://github.com/kubernetes/kubernetes/pull/127009
> KEP-4633: Graduate to BETA.

- content/en/docs/concepts/cluster-administration/cluster-autoscaling.md
Fix typo in cluster-autoscaling.md
Closes: #
> Fix typo in cluster-autoscaling.md

- content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md
content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md
> [zh-cn]sync cluster-autoscaling

- content/ja/community/static/cncf-code-of-conduct.md
https://github.com/kubernetes/website/pull/48580/files
> [ja] update contributor covenant links

- content/en/docs/reference/command-line-tools-reference/feature-gates/cron-jobs-scheduled-annotation.md
Upstream PR: https://github.com/kubernetes/kubernetes/pull/128336
Status: merged
Closes: #
> Mark CronJobsScheduledAnnotation as GA

- content/zh-cn/blog/_posts/2024-08-16-Honor-PV-Reclaim-Policy-Beta.md
```
content/zh-cn/blog/_posts/2024-08-16-Honor-PV-Reclaim-Policy-Beta.md
```
See [preview](https://deploy-preview-48379--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/16/kubernetes-1-31-prevent-persistentvolume-leaks-when-deleting-out-of-order/)
> [zh] Add 2024-08-16-Honor-PV-Reclaim-Policy-Beta.md

- content/zh-cn/blog/_posts/2024-08-16-kubernetes-1.31-image-volume-source.md
```
content/zh-cn/blog/_posts/2024-08-16-kubernetes-1.31-image-volume-source.md
```
See [preview](https://deploy-preview-48446--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/08/16/kubernetes-1-31-image-volume-source/)
> [zh] Add 2024-08-16-kubernetes-1.31-image-volume-source.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/topology-manager-policy-options.md
- content/en/docs/tasks/administer-cluster/topology-manager.md
Promote TopologyManagerPolicyOptions to stable.
Related-to: https://github.com/kubernetes/enhancements/issues/3545
> topology-manager: promoto TopologyManagerPolicyOptions to stable

- content/en/docs/contribute/participate/_index.md
> [en] update kubernetes link

- content/zh-cn/docs/reference/kubectl/docker-cli-to-kubectl.md
- content/zh-cn/docs/setup/best-practices/node-conformance.md
content/zh-cn/docs/reference/kubectl/docker-cli-to-kubectl.md
content/zh-cn/docs/setup/best-practices/node-conformance.md
> [zh-cn]sync and improve docker-cli-to-kubectl node-conformance

- content/zh-cn/docs/contribute/review/reviewing-prs.md
content/zh-cn/docs/contribute/review/reviewing-prs.md
> [zh-cn]sync reviewing-prs.md

- content/zh-cn/docs/reference/glossary/pod-disruption-budget.md
content/zh-cn/docs/reference/glossary/pod-disruption-budget.md
> [zh-cn]sync pod-disruption-budget

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
> Fix typo in "Pod Lifecycle" page

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/recursive-read-only-mounts.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/recursive-read-only-mounts.md
> [zh-cn]sync recursive-read-only-mounts.md

- content/zh-cn/docs/contribute/participate/_index.md
content/zh-cn/docs/contribute/participate/_index.md
> [zh-cn]sync participate/_index.md

- content/zh-cn/docs/concepts/workloads/pods/sidecar-containers.md
> [zh-cn] sync sidecar-containers.md

- content/en/docs/concepts/security/application-security-checklist.md
- fix some typos
- fix consistency issues:
- provide consistent headings with capitalization
- provide consistent link text before and after clicking
/kind cleanup
> Tweak application-security-checklist.md for cleanup

- content/de/docs/contribute/participate/_index.md
https://github.com/kubernetes/website/pull/48625/files
> [de] update kubernetes link

- content/pt-br/community/static/cncf-code-of-conduct.md
https://github.com/kubernetes/website/pull/48580/files
> [pt] update contributor covenant links

- content/en/docs/concepts/containers/container-lifecycle-hooks.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action.md
Document `PodLifecycleSleepAction` for GA
GA doc requirement for KEP-3960
Closes: #
> [KEP-3960] - update docs for GA

- content/en/docs/reference/command-line-tools-reference/feature-gates/hpa-container-metrics.md
k/k: https://github.com/kubernetes/kubernetes/pull/126862
/hold
/cc @sanposhiho
> mark feature-gate HPAContainerMetrics as removed

- content/ja/docs/contribute/participate/_index.md
https://github.com/kubernetes/website/pull/48649/files
> [ja] update kubernetes link

- content/id/docs/contribute/participate/_index.md
https://github.com/kubernetes/website/pull/48641/files
> [id] update kubernetes link

- data/releases/schedule.yaml
Due to KubeCon. PTAL @kubernetes/release-engineering 
Will drop a note to k-dev once this merges.
> Move November patch releases +1 week

- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/stateful-set-auto-delete-pvc.md
Docs changes for [KEP-1847](https://github.com/kubernetes/enhancements/issues/1847) going stable.
> KEP-1847 v1.32 stable docs changesAutodelete 132

- content/en/docs/reference/command-line-tools-reference/feature-gates/pod-host-ips.md
The upstream change is https://github.com/kubernetes/kubernetes/pull/128634.
Closes: #
> Drop PodHostIPs feature gate in v1.32

- content/en/docs/reference/command-line-tools-reference/feature-gates/service-account-token-jti.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/service-account-token-node-binding-validation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/service-account-token-pod-node-info.md
- content/en/docs/tasks/configure-pod-container/configure-service-account.md
The upstream K8s PR:
- https://github.com/kubernetes/kubernetes/pull/128169
> Update ServiceAccountTokenJTI, ServiceAccountTokenPodNodeInfo, ServiceAccountTokenNodeBindingValidation to stable

- content/en/docs/concepts/configuration/manage-resources-containers.md
Fix typos and text in manage-resources-containers.md
Closes: #
> Fix typos and text in manage-resources-containers.md

- content/ja/docs/reference/glossary/limitrange.md
- I find this issue by `good first issue` label know this issue and want to contribute to this repo.
- I know this issue already have a assignee and a PR, since old PR didn't update to follow the guide in two weeks, so I think I can take this issue to make a new PR. Sorry I'm new in Github and this repo, I don't know this behavior is polite or not, if I have done something wrong please tell me I'll fix it.
Closes: #47684
> [ja] Localize glossary entry for "LimitRange"

- data/i18n/ja/ja.toml
- Update `ja.toml` to follow up with `en.toml`
Closes: #
> [ja] Update ja.toml

- content/pt-br/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md
- content/pt-br/examples/pods/pod-nginx-preferred-affinity.yaml
- content/pt-br/examples/pods/pod-nginx-required-affinity.yaml
added page in pt-br
tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md
issue #48280
> [pt-br] Add tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
> [zh-cn]sync manage-resources-containers.md

- content/zh-cn/docs/tutorials/configuration/pod-sidecar-containers.md
content/zh-cn/docs/tutorials/configuration/pod-sidecar-containers.md
> [zh-cn]sync pod-sidecar-containers.md

- content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> [zh-cn]sync labels-annotations-taints/_index.md

- content/en/docs/reference/labels-annotations-taints/_index.md
https://github.com/kubernetes-sigs/kube-scheduler-simulator/ has some internal annotations. 
This PR adds them in the page.
/cc @sftim 
Ref: https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/386
Ref: https://github.com/kubernetes/website/pull/47104#discussion_r1833180455
Closes: #
> feat: add the simulator annotations

- content/en/docs/concepts/cluster-administration/compatibility-version.md
Add docs for compatibility version.
> [KEP-4330] Add doc for CompatibilityVersion

- content/en/docs/reference/command-line-tools-reference/feature-gates/allow-dns-only-node-csr.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/allow-insecure-kubelet-certificate-signing-requests.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/app-armor-fields.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/concurrent-watch-object-decode.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/csi-migration-portworx.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/disable-allocator-dual-write.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/disable-cloud-providers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/disable-kubelet-cloud-credential-providers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/proc-mount-type.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/reload-kubelet-server-certificate-file.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/retry-generate-name.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/strict-cost-enforcement-for-vap.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/strict-cost-enforcement-for-webhooks.md
Based on many PRs:
#47836 #47838 #47839 #47840 #47843 #47844 #47845 #47846 #47847 #47851 #47852 #47853 #47855  #47857 #47858
but with my own tweaks.
> Update feature gate information for v1.31

- content/en/docs/reference/instrumentation/metrics.md
Closes: #48538
Wait for the upstream PR https://github.com/kubernetes/kubernetes/pull/128376 to merge first.
/hold
> Update metrics documentation for v1.31

- content/en/docs/reference/command-line-tools-reference/feature-gates/relaxed-environment-variable-validation.md
Promoted the RelaxedEnvironmentVariableValidation feature gate to beta and is enabled by default.
Closes: #
> Promote RelaxedEnvironmentVariableValidation to beta

- content/en/docs/concepts/security/multi-tenancy.md
Add link to Multi Tenant Operator in Multi-Tenancy chapter
> Add link to Multi Tenant Operator in Multi-Tenancy chapter

- content/en/_index.html
> [en] update queue link

- content/zh-cn/docs/reference/access-authn-authz/authorization.md
content/zh-cn/docs/reference/access-authn-authz/authorization.md
> [zh-cn] Resync access-authn-authz/authorization.md

- content/zh-cn/docs/concepts/security/application-security-checklist.md
Add zh text to this concept page:
```
content/zh-cn/docs/concepts/security/application-security-checklist.md
```
See [preview](https://deploy-preview-48564--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/security/application-security-checklist/)
> [zh] Add application-security-checklist.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/reload-kubelet-server-certificate-file.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/reload-kubelet-server-certificate-file.md
> [zh-cn]sync reload-kubelet-server-certificate-file

- content/zh-cn/docs/concepts/security/multi-tenancy.md
content/zh-cn/docs/concepts/security/multi-tenancy.md
> [zh-cn]sync multi-tenancy.md

- content/pt-br/docs/concepts/scheduling-eviction/kube-scheduler.md
Description:
This PR updates the kube-scheduler concepts page in the Portuguese documentation (pt-br) to reflect the latest version of the page in English.
Changes:
- Update of the page content/pt-br/docs/concepts/scheduling-eviction/kube-scheduler.md
- Synchronization with the latest version of the English documentation
Related issue: #48441
--- 
Descrição:
Este PR atualiza a página de conceit do kube-scheduler na documentação em português (pt-br) para refletir a versão mais recente da página em inglês. 
Mudanças:
•	Atualização da página content/pt-br/docs/concepts/scheduling-eviction/kube-scheduler.md
•	Sincronização com a versão mais recente da documentação em inglês
Issue relacionada:
•	Issue: #48441
> [pt-br] Update docs/concepts/scheduling-eviction/kube-scheduler

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-dns-only-node-csr.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-insecure-kubelet-certificate-signing-requests.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/app-armor-fields.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/concurrent-watch-object-decode.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-allocator-dual-write.md
allow-dns-only-node-csr
allow-insecure-kubelet-certificate-signing-requests
app-armor-fields
concurrent-watch-object-decode
disable-allocator-dual-write
> [zh-cn]add 6 feature-gates

- content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
> [zh-cn]sync user-namespaces.md

- content/ko/docs/concepts/services-networking/ingress-controllers.md
en PR https://github.com/kubernetes/website/pull/45976/files
> [ko] Updated Hyperlink of Easegress IngressController (fix)

- content/ko/examples/service/networking/example-ingress.yaml
> [ko] Delete rewrite-target annotation in ingress example

- content/zh-cn/docs/reference/node/kubelet-files.md
```
content/zh-cn/docs/reference/node/kubelet-files.md
```
See [preview](https://deploy-preview-48707--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/node/kubelet-files/)
> [zh] Add reference/node/kubelet-files.md

- content/ko/examples/application/cassandra/cassandra-statefulset.yaml
en PR https://github.com/kubernetes/website/pull/47087/files
> [ko] Update stale StatefulSet with Cassandra example

- content/ko/docs/concepts/extend-kubernetes/operator.md
en PR https://github.com/kubernetes/website/pull/47170/files
> [ko] Update the GitHub repo url of Java Operator SDK

- content/ko/docs/tasks/manage-gpus/scheduling-gpus.md
https://github.com/kubernetes/website/pull/48022/files
> [ko] Update links for AMD GPU device plugin

- content/ko/docs/contribute/new-content/open-a-pr.md
https://github.com/kubernetes/website/pull/48387/files
> [ko] Fix wrong URL scheme

- content/ko/community/static/cncf-code-of-conduct.md
https://github.com/kubernetes/website/pull/48580/files
> [ko] update contributor covenant links

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/strict-cost-enforcement-for-vap.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/strict-cost-enforcement-for-webhooks.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/strict-cost-enforcement-for-vap.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/strict-cost-enforcement-for-webhooks.md
> [zh-cn]sync strict-cost-enforcement-*

- content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
> [zh] update extensible-admission-controllers.md

- content/en/docs/concepts/architecture/garbage-collection.md
Check source code: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L200
Closes: #
> fix wrong image-gc-period in doc

- content/en/docs/reference/instrumentation/metrics.md
Update metrics reference for v1.32 release
The upstream Kubernetes PR: 
- https://github.com/kubernetes/kubernetes/pull/128720
/hold 
Wait for the upstream Kubernetes PR to merge first.
> Update metrics reference for v1.32 release

- content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md
Applied [some recent comments from reviewer](https://github.com/kubernetes/website/pull/48727#discussion_r1843563366) to keep consistency.
```
content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md
```
> [zh] Update config-api/apiserver-config.v1beta1.md

- content/en/docs/contribute/style/style-guide.md
Updates the style guide "Headings and titles" section with guidance on:
1. links in headers
2. using properly formatted headers
[Deploy preview](https://deploy-preview-48667--kubernetes-io-main-staging.netlify.app/docs/contribute/style/style-guide/#headings)
Closes: #48662
> Updating Style Guide Headings and Titles section

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-version-migration-v1alpha1.md
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-version-migration-v1alpha1.md
```
See [preview](https://deploy-preview-48697--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-version-migration-v1alpha1/)
> [zh] Add storage-version-migration-v1alpha1.md

- content/zh-cn/docs/contribute/style/style-guide.md
> [zh-cn]sync style-guide.md

- content/uk/_index.html
> [uk] update queue link

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/external-service-account-token-signer.md
This is a placeholder PR
- PR on `kubernetes/kubernetes`: https://github.com/kubernetes/kubernetes/pull/128190
- `kubernetes/enhancement` issue: https://github.com/kubernetes/enhancements/issues/740
> Docs for ExternalJWTSigner

- content/ja/docs/tasks/debug/debug-application/debug-running-pod.md
kubectl debugのカスタムプロファイルについて追記しました。
related: #48154
> [ja] Add description about custom profile

- content/en/blog/_posts/2024-11-08-kubernetes-1.32-sneak-peek.md
> improve 2024-11-08-kubernetes-1.32-sneak-peek.md

- go.mod
> Fix Go version in go.mod by dropping patch number

- content/de/_index.html
> [de] update queue link

- content/zh-cn/docs/tasks/administer-cluster/node-overprovisioning.md
- content/zh-cn/examples/deployments/deployment-with-capacity-reservation.yaml
- content/zh-cn/examples/priorityclass/low-priority-class.yaml
Add zh text to this new page, to sync with en #46635
```
content/zh-cn/docs/tasks/administer-cluster/node-overprovisioning.md
```
> [zh] Add node-overprovisioning.md

- content/en/docs/tutorials/services/connect-applications-service.md
- content/en/docs/tutorials/services/pods-and-endpoint-termination-flow.md
Some small changes to documentation to get familiar with CI/CD, tooling, etc. 
Thanks!
1. Some nitpicks/fairly trivial typos fixed.
2. Was asked to separate these changes from another PR: https://github.com/kubernetes/website/pull/48622#pullrequestreview-2421767186 with suggestion from: @ArvindParekh https://github.com/kubernetes/website/pull/48622#discussion_r1826954596
@sftim - Here are the English content changes per your request! Thanks!
> docs: typos

- content/en/docs/concepts/storage/volume-snapshots.md
This PR adds a doc link for the Volume Group Snapshot feature.
Closes: #
> Add document link for volume group snapshots

- content/pt-br/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
- content/pt-br/docs/tasks/tools/install-kubectl-macos.md
Small adjustments for consistency and anchor fixes.
/cc @edsoncelio
> [pt-br] Update docs/tasks/tools/install-kubectl-macos

- content/en/docs/tasks/administer-cluster/node-overprovisioning.md
- content/en/examples/deployments/deployment-with-capacity-reservation.yaml
- content/en/examples/priorityclass/low-priority-class.yaml
Tweaks to recently-merged task page https://kubernetes.io/docs/tasks/administer-cluster/node-overprovisioning/
[preview](https://deploy-preview-48753--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/node-overprovisioning/)
> Tweak node capacity overprovisioning task

- content/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry.md
content/zh-cn/docs/tasks/configure-pod-container/pull-image-private-registry.md
> [zh-cn]sync pull-image-private-registry

- content/zh-cn/docs/tasks/administer-cluster/node-overprovisioning.md
- content/zh-cn/examples/deployments/deployment-with-capacity-reservation.yaml
- content/zh-cn/examples/priorityclass/low-priority-class.yaml
Sync with en pr #48753 
```
content/zh-cn/docs/tasks/administer-cluster/node-overprovisioning.md
```
> [zh] Resync node-overprovisioning.md

- content/zh-cn/docs/tutorials/services/connect-applications-service.md
content/zh-cn/docs/tutorials/services/connect-applications-service.md
> [zh-cn]sync connect-applications-service.md

- content/en/docs/concepts/security/hardening-guide/authentication-mechanisms.md
Performed actons below:
- remove redundant spaces
- provide a consistent look for bullets
- add some reference links to the bottom
- minor changes about typo and grammar
/kind cleanup
> Add reference to and clean up authentication-mechanisms.md

- assets/scss/_base.scss
- assets/scss/_custom.scss
- assets/scss/_tablet.scss
- layouts/shortcodes/blocks/kubernetes-features.html
Change how we put the feature boxes on the main page.
- use CSS for layout
Here's a [preview](https://deploy-preview-48308--kubernetes-io-main-staging.netlify.app/)
> Restyle feature boxes on main page and ready for vanilla Docsy

- content/zh-cn/docs/concepts/security/hardening-guide/authentication-mechanisms.md
content/zh-cn/docs/concepts/security/hardening-guide/authentication-mechanisms.md
> [zh-cn]sync authentication-mechanisms.md

- content/zh-cn/blog/_posts/2024-11-08-kubernetes-1.32-sneak-peek.md
content/zh-cn/blog/_posts/2024-11-08-kubernetes-1.32-sneak-peek.md
> [zh-cn]Add blog: 2024-11-08-kubernetes-1.32-sneak-peek.md

- content/zh-cn/docs/reference/using-api/server-side-apply.md
Mainly sync with en pr #48695 
```
content/zh-cn/docs/reference/using-api/server-side-apply.md
```
See [preview](https://deploy-preview-48801--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/using-api/server-side-apply/)
> [zh] Resync using-api/server-side-apply.md

- content/pt-br/_index.html
> [pt] update queue link

- content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md
content/zh-cn/docs/concepts/cluster-administration/cluster-autoscaling.md
> [zh-cn]sync cluster-autoscaling.md

- content/es/_index.html
> [es] update queue link

- content/en/docs/concepts/workloads/controllers/statefulset.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/pod-index-label.md
Docs changes for https://github.com/kubernetes/enhancements/issues/4017 going stable.
> [KEP 4017]: add documentation for PodIndexLabel going GA

- content/en/docs/reference/command-line-tools-reference/feature-gates/cbor-serving-and-storage.md
- content/en/docs/reference/using-api/api-concepts.md
Alpha documentation additions for https://kep.k8s.io/4222
Closes: #
> Document API support for CBOR encoding

- OWNERS_ALIASES
After a local meetup discussion, some of Japanese localization owners are joining reviewing duty 
N/A
> [ja] Add nasa and inductor (current owners) to reviewer too

- content/zh-cn/docs/concepts/storage/storage-classes.md
content/zh-cn/docs/concepts/storage/storage-classes.md
> [zh-cn]sync storage-classes.md

- content/pl/_index.html
> [pl] Update KubeCon 2024-2025 events

- content/en/docs/reference/command-line-tools-reference/feature-gates/systemd-watchdog.md
- content/en/docs/reference/node/systemd-watchdog.md
Add a `systemd watchdog` user manual for the kubelet, which introduces why to use the `watchdog` and how to use it.
Related issue https://github.com/kubernetes/kubernetes/issues/127460
Closes: #
> feat:  Add system watchdog configuration doc

- content/zh-cn/docs/reference/kubernetes-api/common-definitions/quantity.md
Sync with the english text:
```
content/zh-cn/docs/reference/kubernetes-api/common-definitions/quantity.md
```
> [zh] Sync common-definitions/quantity.md

- OWNERS_ALIASES
Add myself as a SIG Docs reviewer
I would like to apply for becoming a SIG Docs reviewer by adding my GitHub username to the OWNERS_ALIASES file. 
Closes: #
> [ja] Add b1gb4by to sig-docs-ja reviewer

- content/fr/_index.html
> [fr] update queue link

- content/ja/docs/reference/glossary/probe.md
Translate `docs/reference/glossary/probe.md` into Japanese
https://github.com/kubernetes/website/issues/48853
Closes: #
---
/language ja
> [ja] Translate docs/reference/glossary/probe.md into Japanese

- content/en/docs/concepts/cluster-administration/logging.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/pod-logs-query-split-streams.md
- content/en/examples/debug/counter-pod-err.yaml
This is a ~placeholder~ PR for the new feature https://github.com/kubernetes/enhancements/issues/3288. I will update the document after the implemention PR get merged.
KEP issue: https://github.com/kubernetes/enhancements/issues/3288
Code (k/k) update PR(s):
* https://github.com/kubernetes/kubernetes/pull/127360
* https://github.com/kubernetes/kubernetes/pull/128159
> Update docs for split stdout / stderr Pod logging

- content/it/_index.html
> [it] update queue link

- content/ja/docs/reference/glossary/rbac.md
Translate `content/en/docs/reference/glossary/rbac.md` into Japanese.
Closes: #48880
> [ja] Translate docs/reference/glossary/rbac.md

- content/zh-cn/docs/contribute/participate/issue-wrangler.md
Page: https://kubernetes.io/zh-cn/docs/contribute/participate/issue-wrangler/
> [zh-cn] Update the translation of the Issue Wranglers page

- content/en/docs/reference/config-api/kubeadm-config.v1beta4.md
> Fix descrption for encryptionAlgorithm field

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-cloud-providers.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-resource-allocation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/disable-cloud-providers.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dynamic-resource-allocation.md
> [zh-cn]sync disable-cloud-providers dynamic-resource-allocation

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
> [zh-cn]sync new-volume-manager-reconstruction

- content/id/docs/concepts/cluster-administration/addons.md
> [id] Removed Weave Scope link

- content/id/community/static/cncf-code-of-conduct.md
https://github.com/kubernetes/website/pull/48580/files
> [id] update contributor covenant links

- content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
Sync with en #48895 
```
content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
```
> [zh] Sync network/extend-service-ip-ranges.md

- content/ja/docs/reference/glossary/replica.md
Translate `content/en/docs/reference/glossary/replica.md` into Japanese.
Closes: #48845
> [ja] Translate docs/reference/glossary/replica.md

- content/it/docs/concepts/cluster-administration/addons.md
> [it] Removed Weave Scope link

- content/en/blog/_posts/2024-11-11-memory-manager-moves-to-ga/index.md
List and describe the changes done
for Memory manager since beta and made it GA ready.
https://github.com/kubernetes/enhancements/issues/1769
Closes: #
> blog: Memory Manager goes GA

- content/en/docs/reference/config-api/kubeadm-config.v1beta4.md
> Fix typo in kubeadm config v1beta4

- content/vi/_index.html
> [vi] update queue link

- content/ja/docs/reference/glossary/userns.md
Translate `content/en/docs/reference/glossary/userns.md` into Japanese.
Closes: #48881
> [ja] Translate docs/reference/glossary/userns.md

- content/ja/docs/reference/glossary/sidecar-container.md
Translate 
`content/en/docs/reference/glossary/sidecar-container.md` 
into Japanese
`content/ja/docs/reference/glossary/sidecar-container.md`
Closes: #48851 
/language ja
> [ja] Translate sidecar-container.md into Japanese

- content/id/_index.html
> [id] update queue link

- content/ja/docs/reference/glossary/jwt.md
Translate `content/en/docs/reference/glossary/jwt.md` into Japanese.
Closes: #48879
> [ja] Translate docs/reference/glossary/jwt.md

- content/en/blog/_posts/2024-12-11-Kubernetes-v1-32-Release/index.md
- Udating with SIG feedback
- Fixing last nits before the release day
> Update release announcement for v1.32

- content/zh-cn/docs/tutorials/security/apparmor.md
> [zh-cn]sync apparmor.md

- content/zh-cn/docs/reference/glossary/pod-template.md
Add zh text to this glossary:
```
content/zh-cn/docs/reference/glossary/pod-template.md
```
> [zh] Add a glossary: pod-template.md

- content/zh-cn/docs/tasks/administer-cluster/controller-manager-leader-migration.md
content/zh-cn/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> [zh-cn]sync controller-manager-leader-migration

- content/zh-cn/docs/concepts/policy/resource-quotas.md
content/zh-cn/docs/concepts/policy/resource-quotas.md
> [zh-cn]sync resource-quotas.md

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
> [zh-cn] sync device-plugin.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/translate-stream-close-websocket-requests.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/translate-stream-close-websocket-requests.md
> [zh-cn]sync translate-stream-close-websocket-requests

- content/ru/docs/concepts/workloads/pods/_index.md
> [ru] Update an outdated link in _index.md

- content/ja/docs/concepts/workloads/pods/_index.md
> [ja] Update _index.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-slice-v1alpha3.md
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-slice-v1alpha3.md
```
See [preview](https://deploy-preview-48683--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-slice-v1alpha3/)
> [zh] Add an API doc: resource-slice-v1alpha3.md

- data/releases/schedule.yaml
Adding the patch releases for January.
> Update schedule for patches in January

- data/releases/schedule.yaml
Followup-on https://github.com/kubernetes/website/pull/49007
cc @kubernetes/release-managers
> Add v1.32.0 to schedule

- hugo.toml
Updating hugo.toml for release v1.32.
/hold until v1.32 release day.
> Updates v1.30 hugo.toml for release v1.32

- hugo.toml
Updating hugo.toml for release v1.32.
/hold until v1.32 release day.
> Updates v1.29 hugo.toml for release v1.32

- hugo.toml
Updating hugo.toml for release v1.32.
/hold until v1.32 release day.
> Update dev 1.32 hugo.toml for release v1.32

- content/en/docs/reference/labels-annotations-taints/_index.md
Documented label cluster-service
#48609 
Closes: #
> documented label cluster-service

- hugo.toml
Updating hugo.toml for release v1.32.
/hold until v1.32 release day.
> Updates v1.28 hugo.toml for release v1.32

- content/en/blog/_posts/2024-12-12-scheduler-queueinghint/index.md
follow up: https://github.com/kubernetes/website/pull/48541#discussion_r1871744547
Closes: #
> chore: fix wording on QHint blog

- content/zh-cn/blog/_posts/2023-12-15-volume-attributes-class/index.md
> [zh] Fix type parameter in example

- content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
> [zh-cn]sync topology-spread-constraints.md

- content/zh-cn/docs/concepts/security/secrets-good-practices.md
content/zh-cn/docs/concepts/security/secrets-good-practices.md
> [zh-cn]sync secrets-good-practices.md

- content/zh-cn/docs/tasks/administer-cluster/sysctl-cluster.md
content/zh-cn/docs/tasks/administer-cluster/sysctl-cluster.md
> [zh-cn]sync sysctl-cluster.md

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
> [zh-cn]sync kubeadm-certs.md

- content/zh-cn/docs/setup/production-environment/tools/_index.md
Fix a link and update several zh text:
```
content/zh-cn/docs/setup/production-environment/tools/_index.md
```
> [zh] Sync production-environment/tools/_index.md

- content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
> [zh-cn]sync cpu-management-policies.md

- content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md
content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md
> [zh-cn]sync configure-service-account.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-cpu-and-memory-affinity.md
- content/zh-cn/docs/tasks/administer-cluster/memory-manager.md
```
content/zh-cn/docs/tasks/administer-cluster/memory-manager.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-cpu-and-memory-affinity.md
```
See [preview](https://deploy-preview-49033--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/administer-cluster/memory-manager/)
> [zh] Sync administer-cluster/memory-manager.md

- content/zh-cn/docs/tasks/configure-pod-container/security-context.md
```
content/zh-cn/docs/tasks/configure-pod-container/security-context.md
```
> [zh] Sync configure-pod-container/security-context.md

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/concepts/configuration/secret.md
- content/zh-cn/examples/pods/resource/pod-level-resources.yaml
> [zh-cn]sync manage-resources-containers secret

- content/zh-cn/docs/concepts/containers/images.md
Optimize the description of the mirror concept in the Chinese document content
`/zh-cn/docs/concepts/containers/images.md
`
> [zh-cn] Update images.md 

- OWNERS_ALIASES
adding Natali as part of the blog-alias for owners and reviewers in preparation for the 1.33 release and onwards
/assign @divya-mohan0209 @reylejano @sftim
> add natalisucks to blog-owners and reviewers

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join/kubeadm_join_phase.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join/kubeadm_join_phase.md
> [zh-cn]sync kubeadm_join_phase

- content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md
> [zh-cn]sync kube-scheduler-config.v1.md

- content/vi/docs/setup/_index.md
- content/vi/docs/setup/best-practices/_index.md
I translated docs/setup/_index.md into Vietnamese. I'm going to translate another files later.
Closes: #
> [vi] Translate setup/_index.md into Vietnamese

- content/fr/docs/concepts/workloads/pods/pod.md
> [fr] Update _pod.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset/kubeadm_reset_phase.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset/kubeadm_reset_phase.md
> [zh-cn]sync kubeadm_reset_phase.md

- content/en/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
There were some external packages not included in the current reference due to defects found in the generator. This PR fixes the generated reference.
Closes: #
> Fix config API for kcm config v1alpha1

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
```
```
See [preview](https://deploy-preview-49067--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init/)
> [zh] Sync setup-tools/kubeadm/kubeadm-init.md

- content/es/docs/concepts/workloads/pods/pod.md
> [es] Update _pod.md

- content/zh-cn/docs/reference/node/node-status.md
https://github.com/kubernetes/website/pull/48915/files
> [zh] fix node-monitor-grace-period

- content/zh-cn/docs/concepts/policy/limit-range.md
content/zh-cn/docs/concepts/policy/limit-range.md
> [zh-cn]sync limit-range.md

- content/zh-cn/docs/concepts/cluster-administration/logging.md
- content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
- content/zh-cn/examples/debug/counter-pod-err.yaml
content/zh-cn/docs/concepts/cluster-administration/logging.md
content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
content/zh-cn/examples/debug/counter-pod-err.yaml
> [zh-cn]sync logging counter-pod-err.yaml apiserver-audit.v1

- content/zh-cn/docs/concepts/storage/volumes.md
- content/zh-cn/docs/concepts/workloads/controllers/statefulset.md
content/zh-cn/docs/concepts/workloads/controllers/statefulset.md
> [zh-cn]sync volumes statefulset

- content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md
> [zh-cn] sync container-lifecycle-hooks.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply.md
> [zh-cn]sync kubeadm_upgrade_apply

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_post-upgrade.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_post-upgrade.md
> [zh-cn]sycn kubeadm_upgrade_node_phase_post-upgrade.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_bootstrap-token.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_bootstrap-token.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_bootstrap-token

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon_kube-proxy.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon_kube-proxy.md
> [zh-cn]sync kubeadm_upgrade_node_phase_addon_kube-proxy

- content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
> [zh-cn]sync kubeadm-config.v1beta3.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_addon_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_addon_all.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_addon_all.md

- content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
> [zh-cn]sync dynamic-resource-allocation.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon_coredns.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon_coredns.md
> [zh-cn]sync kubeadm_upgrade_node_phase_addon_coredns

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_control-plane.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_control-plane.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_control-plane

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon_all.md
> [zh-cn]sync kubeadm_upgrade_node_phase_addon_all

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_upload-config_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_upload-config_all.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_upload-config_all

- content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
content/zh-cn/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
> [zh-cn] sync cpu-default-namespace.md

- content/zh-cn/docs/reference/kubectl/kubectl.md
content/zh-cn/docs/reference/kubectl/kubectl.md
> [zh-cn]sync kubectl/kubectl.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase.md
> [zh-cn]sync kubeadm_upgrade_node_phase.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_kubelet-config.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_kubelet-config.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_kubelet-config

- content/zh-cn/blog/_posts/2022-09-14-pod-has-network-condition.md
sync file:
```
content/zh-cn/blog/_posts/2022-09-14-pod-has-network-condition.md
```
> [zh-cn] sync 2022-09-14-pod-has-network-condition.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_addon_kube-proxy.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_addon_kube-proxy.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_addon_kube-proxy.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_upload-config_kubelet.md
content/zh-cn/docs/reference/config-api/kubeadm_upgrade_apply_phase_upload-config_kubelet.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_upload-config_kubelet

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_post-upgrade.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_post-upgrade.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_post-upgrade.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-unsafe-malformed-object-deletion.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/cbor-serving-and-storage.md
- content/zh-cn/docs/reference/using-api/api-concepts.md
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/allow-unsafe-malformed-object-deletion.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/cbor-serving-and-storage.md
```
> [zh] Sync using-api/api-concepts.md and its feature gates

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_upload-config_kubeadm.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_upload-config_kubeadm.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_upload-config_kubeadm

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_preflight.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_preflight.md
> [zh-cn]sync kubeadm_upgrade_apply_phase_preflight

- content/zh-cn/docs/reference/access-authn-authz/authorization.md
content/zh-cn/docs/reference/access-authn-authz/authorization.md
> [zh-cn]sync authorization.md

- content/ja/docs/setup/production-environment/tools/kubespray.md
https://github.com/kubernetes/website/pull/48994/files
> [ja] Update Link of Inventory in Install k8s doc

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_addon_coredns.md
```
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_addon_coredns.md
```
> [zh] Add kubeadm_upgrade_apply_phase_addon_coredns.md

- content/zh-cn/blog/_posts/2024-08-15-consistent-read-from-cache.md
translate file
```
content/zh-cn/blog/_posts/2024-08-15-consistent-read-from-cache.md
```
> [zh-cn] translate 2024-08-15-consistent-read-from-cache.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_apply_phase_upload-config.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_control-plane.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_preflight.md
Added zh text to:
```
Added      kubeadm_upgrade_apply_phase_upload-config.md
Modified   kubeadm_upgrade_node_phase_control-plane.md
Modified   kubeadm_upgrade_node_phase_preflight.md
```
> [zh] Sync kubeadm_upgrade_apply_phase_upload-config.md

- content/zh-cn/docs/concepts/cluster-administration/flow-control.md
Wrong bookmark format causes the bookmark text to be displayed incorrectly on the front-end page.
[递归服务器场景-recursive-server-scenarios](https://kubernetes.io/zh-cn/docs/concepts/cluster-administration/flow-control/#%E9%80%92%E5%BD%92%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%BA%E6%99%AF-recursive-server-scenarios)
> Fix incorrect fragment identifier

- content/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-finegrained-authz.md
```
content/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-finegrained-authz.md
```
> [zh] Sync kubelet-authn-authz.md and its feature gate

- content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/external-service-account-token-signer.md
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/external-service-account-token-signer.md
```
> [zh] Add text to: service-accounts-admin.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/systemd-watchdog.md
- content/zh-cn/docs/reference/node/systemd-watchdog.md
```
content/zh-cn/docs/reference/node/systemd-watchdog.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/systemd-watchdog.md
```
> [zh] Add systemd-watchdog.md and its feature gate

- content/zh-cn/docs/reference/config-api/apiserver-admission.v1.md
> [zh-cn]sync apiserver-admission.v1.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase.md
> [zh-cn]sync kubeadm_init_phase.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stateful-set-auto-delete-pvc.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-list.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/stateful-set-auto-delete-pvc.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-list.md
> [zh-cn]sync stateful-set-auto-delete-pvc watch-list

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs/_index.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs/kubeadm_certs_renew.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs/_index.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs/kubeadm_certs_renew.md
> [zh-cn]sync kubeadm_certs_renew kubeadm_certs/_index

- content/en/docs/concepts/configuration/manage-resources-containers.md
> fix: typo in manage-resources-containers.md

- content/zh-cn/docs/reference/config-api/client-authentication.v1.md
- content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
content/zh-cn/docs/reference/config-api/client-authentication.v1beta1.md
> [zh-cn]sync client-authentication.v1 client-authentication.v1beta1

- content/zh-cn/docs/reference/config-api/kube-proxy-config.v1alpha1.md
> [zh-cn]sync kube-proxy-config.v1alpha1.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node.md
> [zh-cn]sync kubeadm_upgrade_node.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_delete/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_wait/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_wait/_index.md
> [zh-cn]sync kubectl_delete kubectl_wait kubectl_create

- content/zh-cn/docs/tasks/manage-kubernetes-objects/kustomization.md
content/zh-cn/docs/tasks/manage-kubernetes-objects/kustomization.md
> [zh-cn]sync kustomization.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_logs/_index.md
> [zh-cn]sync kubectl_logs/_index

- content/zh-cn/docs/setup/production-environment/_index.md
content/zh-cn/docs/setup/production-environment/_index.md
> [zh-cn]sync production-environment/_index.md

- content/zh-cn/docs/concepts/storage/volumes.md
- content/zh-cn/docs/concepts/workloads/autoscaling.md
content/zh-cn/docs/concepts/workloads/autoscaling.md
> [zh-cn]sync volumes autoscaling

- content/zh-cn/examples/examples_test.go
Sync with en #49201 and more
```
content/zh-cn/examples/examples_test.go
```
> [zh] Sync examples/examples_test.go

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dra-admin-access.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dra-resource-claim-device-status.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action-allow-zero.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-logs-query-split-streams.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/prefer-align-cpus-by-uncorecache.md
Add 5 new feature gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dra-admin-access.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/dra-resource-claim-device-status.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action-allow-zero.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-logs-query-split-streams.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/prefer-align-cpus-by-uncorecache.md
```
> [zh] Add 5 feature gates

- content/zh-cn/docs/reference/access-authn-authz/node.md
```
content/zh-cn/docs/reference/access-authn-authz/node.md
```
> [zh] Add text to: access-authn-authz/node.md

- content/zh-cn/examples/application/job/rabbitmq/rabbitmq-service.yaml
- content/zh-cn/examples/application/job/rabbitmq/rabbitmq-statefulset.yaml
- content/zh-cn/examples/pods/resource/pod-level-cpu-request-limit.yaml
- content/zh-cn/examples/pods/resource/pod-level-memory-request-limit.yaml
This PR synchronizes the example manifests from the English upstream so that the test case can succeed. To test it, run `go test k8s.io/website/content/zh-cn/examples`.
> [zh] Sync example manifests

- content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
> [zh-cn]sync kube-controller-manager-config.v1alpha1.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_kustomize/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_kustomize/_index.md
> [zh-cn]sync kubectl_kustomize/_index.md

- content/zh-cn/docs/concepts/security/service-accounts.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
- content/zh-cn/docs/tasks/administer-cluster/topology-manager.md
content/zh-cn/docs/concepts/security/service-accounts.md
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
content/zh-cn/docs/tasks/administer-cluster/topology-manager.md
> [zh-cn]sync kubeadm-upgrade-phase topology-manager service-accounts

- content/zh-cn/docs/reference/access-authn-authz/authentication.md
- content/zh-cn/docs/reference/access-authn-authz/rbac.md
> [zh-cn]sync authentication rbac

- content/es/docs/concepts/storage/volumes.md
> [es] Use a path different from the key in the ConfigMap

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
- content/zh-cn/docs/tasks/administer-cluster/quota-api-object.md
content/zh-cn/docs/tasks/administer-cluster/quota-api-object.md
> [zh-cn]sync manage-resources-containers quota-api-object

- content/zh-cn/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md
```
content/zh-cn/blog/_posts/2023-08-15-pkgs-k8s-io-introduction.md
```
See [preview](https://deploy-preview-49235--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/08/15/pkgs-k8s-io-introduction/)
> [zh] Update 2023-08-15-pkgs-k8s-io-introduction.md

- content/fr/docs/concepts/storage/volumes.md
> [fr] Use a path different from the key in the ConfigMap

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-slice-v1beta1.md
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-slice-v1beta1.md
```
> [zh] Add resource-slice-v1beta1.md

- content/ja/docs/tasks/debug/debug-application/debug-running-pod.md
v1.32のリリースに伴いCustom Profileをstableに変更しました。
related: #49245
※英語版の方がMergeされ次第、こちらのPRについてもご対応を頂ければと思います。
> [ja] Custom Profile has graduated to stable

- content/zh-cn/docs/tasks/configure-pod-container/assign-pod-level-resources.md
```
content/zh-cn/docs/tasks/configure-pod-container/assign-pod-level-resources.md
```
See [preview](https://deploy-preview-49222--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/configure-pod-container/assign-pod-level-resources/)
> [zh] Add assign-pod-level-resources.md

- content/zh-cn/docs/concepts/cluster-administration/compatibility-version.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/selinux-change-policy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/server-side-field-validation.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/size-memory-backed-volumes.md
```
added      content/zh-cn/docs/concepts/cluster-administration/compatibility-version.md
added      ../feature-gates/selinux-change-policy.md
modified   ../feature-gates/server-side-field-validation.md
modified   ../feature-gates/size-memory-backed-volumes.md
```
> [zh] Add compatibility-version and update 3 feature gates

- content/zh-cn/docs/reference/glossary/addons.md
- content/zh-cn/docs/reference/glossary/admission-controller.md
- content/zh-cn/docs/reference/glossary/drain.md
- content/zh-cn/docs/reference/glossary/rbac.md
- content/zh-cn/docs/reference/glossary/replica-set.md
Update zh text in these glossary:
```
content/zh-cn/docs/reference/glossary/addons.md
content/zh-cn/docs/reference/glossary/admission-controller.md
content/zh-cn/docs/reference/glossary/drain.md
content/zh-cn/docs/reference/glossary/rbac.md
content/zh-cn/docs/reference/glossary/replica-set.md
```
> [zh] Update glossary: drain, rbac, addons, replicaset

- content/bn/docs/setup/production-environment/tools/_index.md
https://github.com/kubernetes/website/pull/48994/files
> [bn] Update Link of Inventory in Install k8s doc

- content/en/blog/_posts/2024-12-17-api-streaming/index.md
> Enable click-to-zoom on blog post kube-apiserver-api-streaming

- content/hi/docs/setup/production-environment/tools/_index.md
https://github.com/kubernetes/website/pull/48994/files
> [hi] Update Link of Inventory in Install k8s doc

- content/pt-br/docs/concepts/storage/volumes.md
> [pt] Use a path different from the key in the ConfigMap

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_kubelet-config.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_kubelet-config.md
> [zh-cn]sync kubeadm_upgrade_node_phase_kubelet-config

- content/zh-cn/docs/concepts/configuration/configmap.md
> [zh-cn] Update configmap.md

- content/en/docs/concepts/storage/persistent-volumes.md
This PR adds volumeName, a persistent volume claim spec, to the persistent volume page.
Relevant to #45873
> Add VolumeName to the PV Page

- content/zh-cn/docs/concepts/workloads/pods/_index.md
> [zh] Fix Borg research publication link

- content/en/docs/concepts/workloads/pods/user-namespaces.md
Fixed an incomplete explanation about the subuid numbers, and moved the sentence for ease of reading
NONE
> Update user-namespaces.md (improve readability of `/etc/subuid`)

- content/de/docs/concepts/workloads/pods/_index.md
> [de] Fix Borg research publication link

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
> [en] update semver link

- content/ru/docs/concepts/workloads/pods/_index.md
> [ru] Fix Borg research publication link

- content/zh-cn/docs/tasks/manage-daemon/create-daemon-set.md
- content/zh-cn/examples/application/basic-daemonset.yaml
```
content/zh-cn/docs/tasks/manage-daemon/create-daemon-set.md
```
> [zh] Add create-daemon-set.md

- content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
remove duplicate descriptions in pod-termination
Closes: #49293
> [zh] remove duplicate descriptions in pod-termination

- content/en/docs/tasks/manage-daemon/create-daemon-set.md
- fix the indentations for 1-2-3 lists 
- add a ‘What’s Next’ section by following  [comments below](https://github.com/kubernetes/website/pull/49307#discussion_r1904863095)
[Current Online Page](https://kubernetes.io/docs/tasks/manage-daemon/create-daemon-set/#define-the-daemonset) |  [Preview](https://deploy-preview-49307--kubernetes-io-main-staging.netlify.app/docs/tasks/manage-daemon/create-daemon-set/#define-the-daemonset)
> Clean up create-daemon-set.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/pdb-unhealthy-pod-eviction-policy.md
k/k: https://github.com/kubernetes/kubernetes/pull/129500
/hold
> mark PDBUnhealthyPodEvictionPolicy as removed

- content/en/docs/concepts/overview/kubernetes-api.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/Accelerators.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/AppArmor.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/Initializers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/KMSv1.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/KMSv2.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/OpenAPIV3.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/Sysctls.md
- content/en/docs/tutorials/security/apparmor.md
- layouts/shortcodes/feature-state.html
> Fix feature gate name conflicts (2/2)

- content/en/docs/reference/command-line-tools-reference/feature-gates/SeparateCacheWatchRPC.md
> Add feature gate SeparateCacheWatchRPC v1.32

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_upload-config.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_upload-config.md
> [zh-cn]sync kubeadm_init_phase_addon kubeadm_init_phase_upload-config

- content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md
https://github.com/kubernetes/website/pull/49276
> [en] update cluster add-on link

- content/bn/docs/concepts/workloads/pods/_index.md
> [bn] Fix Borg research publication link

- content/en/docs/reference/instrumentation/slis.md
> Corrected featute state for ComponentSLIs

- content/en/docs/reference/glossary/minikube.md
Changes:
- Specify that minikube supports multi-node
- Why: To avoid misunderstanding that only single-node is supported.
- Update internal links 
- Why: The linked page was redirected, and the minikube part was not displayed on the first screen (the area visible without scrolling).
Closes: #49116
> Update stale glossary entry for "minikube"

- hugo.toml
Removed pygments from hugo config file as they are no longer needed for Docsy.
Closes: #49371
> fix: removed pygments from hugo config file

- content/id/docs/concepts/workloads/pods/pod.md
> [id] Update _pod.md

- content/id/docs/concepts/storage/volumes.md
> [id] Use a path different from the key in the ConfigMap

- content/id/docs/reference/glossary/name.md
- content/id/docs/reference/glossary/uid.md
- content/ko/docs/reference/glossary/object.md
- content/vi/docs/reference/glossary/container.md
- content/vi/docs/reference/glossary/cri.md
- content/vi/docs/reference/glossary/deployment.md
- content/vi/docs/reference/glossary/docker.md
- content/vi/docs/reference/glossary/etcd.md
- content/vi/docs/reference/glossary/kube-proxy.md
- content/vi/docs/reference/glossary/kubelet.md
- content/vi/docs/reference/glossary/label.md
- content/vi/docs/reference/glossary/node.md
- content/vi/docs/reference/glossary/pod.md
- content/vi/docs/reference/glossary/selector.md
- content/vi/docs/reference/glossary/service.md
- content/vi/docs/reference/glossary/taint.md
I found invalid dates when running `make serve`, so I fixed it.
Closes: #
> Fix invalid dates

- content/en/docs/reference/access-authn-authz/validating-admission-policy.md
Change `ValidatingAdmissionWebhook`  to `ValidatingAdmissionPolicy`
> Fix incorrect statement in ValidatingAdmissionPolicy reference

- content/en/docs/tasks/configure-pod-container/user-namespaces.md
Fixes error reported in #48675 
Closes: #48675
> Change attach by debug CLI command in user namespace  example

- content/es/docs/concepts/workloads/pods/pod.md
> [es] Fix Borg research publication link

- content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
Adicionado a seguinte pagina em pt-br
tasks/access-application-cluster/list-all-running-container-images.md
issue #48282
> [pt-br] Add tasks/access-application-cluster/list-all-running-container-images.md

- content/zh-cn/docs/concepts/scheduling-eviction/kube-scheduler.md
> [zh] fix scheduling-eviction/kube-scheduler.md translation issues

- content/zh-cn/docs/concepts/storage/volumes.md
Sync with en #49154 
```
```
See [preview](https://deploy-preview-49458--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/storage/volumes/)
> [zh] Sync storage/volumes.md

- content/en/docs/tasks/administer-cluster/nodelocaldns.md
> fix md formatting in nodelocaldns.md

- content/zh-cn/case-studies/chinaunicom/index.html
Add zh text to this case study:
```
content/zh-cn/case-studies/chinaunicom/index.html
```
See [preview](https://deploy-preview-49470--kubernetes-io-main-staging.netlify.app/zh-cn/case-studies/chinaunicom/)
> [zh] Add case-studies/chinaunicom/

- content/zh-cn/docs/reference/glossary/minikube.md
content/zh-cn/docs/reference/glossary/minikube.md
> [zh-cn]sync minikube.md

- content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md
content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md
> [zh-cn]sync kube-scheduler.md

- content/fr/docs/concepts/workloads/pods/pod.md
> [fr] Fix Borg research publication link

- content/id/docs/concepts/workloads/pods/pod.md
> [id] Fix Borg research publication link

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
```
content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
```
> [zh] Sync kubeadm/kubeadm-reset.md

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1beta1.md
```
content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1beta1.md
```
See [preview](https://deploy-preview-49226--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1beta1/)
> [zh] Add device-class-v1beta1.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DisableNodeKubeProxyVersion.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DisableNodeKubeProxyVersion.md
> [zh-cn]sync DisableNodeKubeProxyVersion

- content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md
> [zh-cn]sync kubectl_edit/_index kubectl_explain/_index

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrolebinding.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_configmap.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_cronjob.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_deployment.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_ingress.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_job.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_namespace.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_poddisruptionbudget.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_priorityclass.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_quota.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_externalname.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service_loadbalancer.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/*
> [zh-cn]sync kubectl_create/*

- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
> [zh-cn]sync validating-admission-policy.md

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
- provide a 1-2-3 list with same indentations of 3 spaces
/kind cleanup
See [preview](https://deploy-preview-49507--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/service-accounts-admin/#verifying-and-inspecting-private-claims)
> Clean up service-accounts-admin.md

- content/zh-cn/docs/reference/node/kernel-version-requirements.md
content/zh-cn/docs/reference/node/kernel-version-requirements.md
> [zh-cn]sync kernel-version-requirements.md

- content/zh-cn/docs/concepts/policy/node-resource-managers.md
Sync with en #49108 
```
content/zh-cn/docs/concepts/policy/node-resource-managers.md
```
> [zh] Sync policy/node-resource-managers.md

- content/zh-cn/docs/concepts/cluster-administration/system-traces.md
content/zh-cn/docs/concepts/cluster-administration/system-traces.md
> [zh-cn]sync system-traces

- content/en/docs/tasks/network/extend-service-ip-ranges.md
- content/en/docs/tasks/network/validate-dual-stack.md
- minor changes about blank lines and backtick symbols
/kind cleanup
See [preview](https://deploy-preview-49537--kubernetes-io-main-staging.netlify.app/docs/tasks/network/extend-service-ip-ranges/)
> Tweak two network tasks: validate-dual-stack and extend-service-ip-ranges

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_list.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_pull.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_kubeconfig.md
```
M       content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_list.md
M       content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_pull.md
M       content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane.md
M       content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_kubeconfig.md
```
> [zh-cn]sync kubeadm_config/* kubeadm_init/*

- content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md
content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md
> [zh-cn]sync implementation-details.md

- content/en/docs/tasks/administer-cluster/configure-upgrade-etcd.md
While checking etcdctl --help output, i noticed --key-file and --cert-file are not present. Maybe it was in the past, not sure. Submitting to normalize text with provided example. 
Closes: #
> docs: adjust mentioned flags for etc client

- content/en/blog/_posts/2016-10-00-Production-Kubernetes-Dashboard-UI-1-4-improvements_3.md
https://github.com/kubernetes/website/pull/49521/files
> [en] Fix Borg research publication link

- content/ja/docs/concepts/workloads/controllers/deployment.md
fix a small inconsistency .
the same as in english documentation #49527 .
> [ja] fix: typo in deployment.md

- content/en/docs/tutorials/stateful-application/basic-stateful-set.md
Signed-off-by: babugeet <abhinandhbg@gmail.com>
Fixed command for kubectl patch statefulset
https://github.com/kubernetes/website/issues/47038
Closes: #
https://github.com/kubernetes/website/issues/47038
> Fixed command for kubectl patch statefulset

- data/i18n/en/en.toml
Fixed order of translation IDs in en.toml to align with the rest of the entries.
Closes: #49409
> Fixed order of translation IDs in en.toml

- content/en/docs/concepts/security/_index.md
Add IaaS Provider `Tencent Cloud`  in cloud provider security, ordered by the alphabetical order.
Closes: #
> Add Tencent Cloud in cloud provider security

- content/en/docs/tasks/administer-cluster/encrypt-data.md
See more details in https://github.com/kubernetes/kubernetes/issues/129610
Closes: https://github.com/kubernetes/kubernetes/issues/129610
> Fix the supported key length for AES-CBC

- content/en/docs/concepts/services-networking/service.md
- content/en/examples/service/simple-service.yaml
This PR is intended to add functionality to copy the service content directly by clicking a copy button.
I am preparing for CKAD and having a button helps.
> Enable copying service content

- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
fix a small inconsistency .
the same as in english documentation #49527 .
> [zh-cn] fix: typo in deployment.md

- hugo.toml
Closes: #
1. Commented out X/Twitter from hugo.yaml
2. Added LinkedIn
3. I don't understand FontAwesome release artifacts well enough to update for Bluesky yet
Signed-off-by: Chris "Not So" Short <chrisshort@duck.com>
> Footer Social Icons

- content/en/blog/_posts/2025-01-15-swap-fresh-improvements.md
Swap GA graduation: blog-post.
For more info, see: https://github.com/kubernetes/enhancements/issues/4128
> Swap GA graduation: blog-post

- content/pt-br/docs/tasks/administer-cluster/dns-custom-nameservers.md
https://github.com/kubernetes/website/pull/49281/files
> [pt] update cluster add-on link

- content/pt-br/docs/contribute/localization_pt-br.md
Update the Brazilian Portuguese contributor guide:
* Add new getting started section.
* Add a note explaining that pull requests that are not passing the preview step cannot be merged.
* Include more term translations and more terms that should not be translated.
/cc @edsoncelio @MrErlison
> [pt-br] Update Brazilian Portuguese contributor guide

- layouts/partials/scripts.html
This PR fixes typo, updates attribute to integrity
https://github.com/kubernetes/website/issues/49629
> updates attribute to integrity

- content/ja/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md
https://github.com/kubernetes/website/pull/49479/files
> [ja] Remove monitoring link

- content/zh-cn/docs/tasks/administer-cluster/nodelocaldns.md
https://github.com/kubernetes/website/pull/49463/files
> [zh] fix md formatting in nodelocaldns.md

- content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
- content/zh-cn/docs/tasks/network/validate-dual-stack.md
Sync with en #49537 
```
content/zh-cn/docs/tasks/network/extend-service-ip-ranges.md
content/zh-cn/docs/tasks/network/validate-dual-stack.md
```
> [zh] Sync validate-dual-stack and extend-service-ip-ranges

- content/zh-cn/docs/reference/access-authn-authz/mutating-admission-policy.md
- content/zh-cn/examples/mutatingadmissionpolicy/applyconfiguration-example.yaml
- content/zh-cn/examples/mutatingadmissionpolicy/json-patch-example.yaml
```
content/zh-cn/docs/reference/access-authn-authz/mutating-admission-policy.md
```
> [zh] Add mutating-admission-policy.md

- content/zh-cn/docs/concepts/configuration/manage-resources-containers.md
please review
src:  ([#49583](https://github.com/kubernetes/website/pull/49583))
> [zh-cn] sync manage-resources-containers.md

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
xref:
- https://github.com/kubernetes/kubeadm/issues/2907
- https://github.com/kubernetes/kubernetes/pull/129620
> kubeadm: graduate WaitForAllControlPlaneComponents to Beta

- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
Updated the example as eviction hard now has five paramters. This PR can be referred :https://github.com/kubernetes/kubernetes/pull/121834
> Updated the threshold parameter in example

- content/en/docs/concepts/services-networking/dns-pod-service.md
- remove redundant spaces
- add bullets and a note
/kind cleanup
See [preview](https://deploy-preview-49664--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/dns-pod-service/#srv-records)
> Clean up dns-pod-service.md

- content/pl/docs/contribute/style/_index.md
> [pl] docs/contribute/style/_index.md

- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
https://github.com/kubernetes/website/pull/49478/files
> [zh] Fix typo in mismatchLabelKeys example

- content/zh-cn/docs/test.md
Sync with en #49663 
See [preview](https://deploy-preview-49679--kubernetes-io-main-staging.netlify.app/zh-cn/docs/test/)
> [zh] Sync docs/test.md

- content/zh-cn/docs/contribute/new-content/open-a-pr.md
content/zh-cn/docs/contribute/new-content/open-a-pr.md
> [zh-cn]sync open-a-pr.md

- content/en/docs/test.md
Fix a rendering issue caused by a code block.
[current website](https://kubernetes.io/docs/test/#images) | [preview](https://deploy-preview-49680--kubernetes-io-main-staging.netlify.app/docs/test/#images)
> Fix a figure rendering issue in docs/test.md

- content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
> [zh-cn] sync cpu-management-policies.md

- content/zh-cn/docs/concepts/cluster-administration/addons.md
- content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md
content/zh-cn/docs/concepts/cluster-administration/addons.md
> [zh-cn]sync addons basic-stateful-set

- content/en/docs/tasks/job/job-with-pod-to-pod-communication.md
- fix style and typo issues
/kind cleanup
See [preview](https://deploy-preview-49687--kubernetes-io-main-staging.netlify.app/docs/tasks/job/job-with-pod-to-pod-communication/)
> Tweak job-with-pod-to-pod-communication.md

- content/zh-cn/docs/concepts/services-networking/dns-pod-service.md
src: ([#49532](https://github.com/kubernetes/website/pull/49532))
> [zh-cn] sync dns-pod-service.md

- content/zh-cn/docs/reference/config-api/apiserver-config.v1.md
content/zh-cn/docs/reference/config-api/apiserver-config.v1.md
> [zh-cn]sync apiserver-config.v1.md

- content/zh-cn/docs/tasks/job/job-with-pod-to-pod-communication.md
content/zh-cn/docs/tasks/job/job-with-pod-to-pod-communication.md
> [zh-cn]sync job-with-pod-to-pod-communication

- content/ru/docs/concepts/cluster-administration/addons.md
> [ru] Fixed link for core dns helm charts

- content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
- content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md
- content/zh-cn/docs/concepts/security/_index.md
please review
```
content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
content/zh-cn/docs/concepts/security/_index.md
```
> [zh] Sync system-metric, container-lifecycle-hooks, and security index

- content/pl/docs/home/_index.md
- update the `menu` section
- add a missing button "See available versions"
https://kubernetes.slack.com/archives/C0191RDKHU1/p1738917120280889
> [pl] update: docs/home/_index.md

- content/zh-cn/blog/_posts/2025-01-21-sig-arch-enhancements-spotlight.md
```
content/zh-cn/blog/_posts/2025-01-21-sig-arch-enhancements-spotlight.md
```
See [preview](https://deploy-preview-49648--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2025/01/21/sig-architecture-enhancements/)
> [zh] Add 2025-01-21-sig-arch-enhancements-spotlight

- content/zh-cn/README.md
As suggested by @pacoxu , update the zh-cn readme.md with active maintainers:
```
content/zh-cn/README.md
```
> update text and maintainers to zh-cn/README.md

- content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
> [zh-cn]sync configure-upgrade-etcd.md

- content/pt-br/docs/concepts/cluster-administration/addons.md
> [pt] Fixed link for core dns helm charts

- content/en/docs/reference/node/systemd-watchdog.md
Update the concept page at https://kubernetes.io/docs/reference/node/systemd-watchdog/ to use math style division, per https://kubernetes.io/docs/contribute/style/style-guide/#formulae-and-equations
[Preview](https://deploy-preview-49726--kubernetes-io-main-staging.netlify.app/docs/reference/node/systemd-watchdog/)
> Use math formula to show division

- content/it/docs/concepts/cluster-administration/addons.md
> [it] Fixed link for core dns helm charts

- content/en/blog/_posts/2025-02-14-cloud-controller-manager-chicken-egg-problem.md
This PR proposes a new blog post (i added the date 2025-02-14 as a placeholder) about problems that can occur when deploying incorrectly configured cloud controller manager. This post is to help users triage and fix errors that they might be seeing after migrating to use external cloud controllers.
Closes: # n/a
> add blog post 2025-02-14 on cloud controller managers and the chicken and egg problem

- content/en/blog/_posts/2025-02-14-cloud-controller-manager-chicken-egg-problem.md
/area blog
Small fixup for PR #49612
/approve
> Fix annotation incorrectly used as label

- content/pl/docs/concepts/overview/_index.md
I added the missing title to the front-matter
> fix: add missing title to front-matter

- content/pl/docs/contribute/review/_index.md
> [pl] docs/contribute/review/_index.md

- content/pl/docs/contribute/_index.md
> [pl] docs/contribute/_index.md

- content/pl/includes/index.md
hugo maintenance : I added one metadata file that is needed by a few of my PRs.
I know that I can add it to the PR, but there will be more than one PR that needs it to work, and I think it's better to add it beforehand for all of them.
> [pl] maintenance: content/pl/includes/index.md

- content/zh-cn/docs/reference/using-api/client-libraries.md
content/zh-cn/docs/reference/using-api/client-libraries.md
> [zh-cn] client-libraries.md

- content/zh-cn/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
content/zh-cn/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
> [zh-cn]sync guaranteed-scheduling-critical-addon-pods

- content/id/docs/concepts/cluster-administration/addons.md
> [id] Fixed link for core dns helm charts

- content/zh-cn/docs/tasks/administer-cluster/change-default-storage-class.md
content/zh-cn/docs/tasks/administer-cluster/change-default-storage-class.md
Closes: #
> [zh-cn]sync change-default-storage-class

- content/zh-cn/docs/reference/glossary/kubectl.md
content/zh-cn/docs/reference/glossary/kubectl.md
> [zh-cn]sync kubectl.md

- content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md
content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md
> [zh-cn]sync apiserver-config.v1beta1.md

- content/zh-cn/docs/tutorials/stateful-application/basic-stateful-set.md
https://github.com/kubernetes/website/pull/49568/files
> [zh] Fixed command for kubectl patch statefulset

- content/en/docs/concepts/workloads/pods/sidecar-containers.md
Fix common grammar error "effecting" -> "affecting"
See e.g. https://www.merriam-webster.com/grammar/affect-vs-effect-usage-difference
> fix(typo): Update sidecar-containers.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/DisableCloudProviders.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/DisableKubeletCloudCredentialProviders.md
k/k: https://github.com/kubernetes/kubernetes/pull/130162
/hold
> Mark DisableCloudProviders and DisableKubeletCloudCredentialProviders as removed

- content/en/docs/reference/command-line-tools-reference/feature-gates/AppArmorFields.md
k/k: https://github.com/kubernetes/kubernetes/pull/129497
/hold
> mark AppArmorFields as removed

- content/ja/releases/version-skew-policy.md
This PR:
* Fixes two broken links to appropreate them.
* Adds description according to latest English ver.
This PR fixes bellow web page:
https://kubernetes.io/ja/releases/version-skew-policy/
You can see fixed page:
https://deploy-preview-49673--kubernetes-io-main-staging.netlify.app/ja/releases/version-skew-policy/
> [ja] Update version-skew-policy.md

- content/de/docs/contribute/_index.md
Fixed small typos in DE contribution guide
> fix(de): fixed small typos

- content/zh-cn/docs/concepts/architecture/cloud-controller.md
```
content/zh-cn/docs/concepts/architecture/cloud-controller.md
```
> [zh] Sync architecture/cloud-controller.md

- content/zh-cn/docs/reference/glossary/api-resource.md
- content/zh-cn/docs/reference/glossary/infrastructure-resource.md
- content/zh-cn/docs/reference/glossary/object.md
```
Added   content/zh-cn/docs/reference/glossary/api-resource.md
Added   content/zh-cn/docs/reference/glossary/infrastructure-resource.md
Modified   content/zh-cn/docs/reference/glossary/object.md
```
> [zh] Add glossary: api-resource and infrastructure-resource

- content/zh-cn/releases/release.md
Update some zh text 
```
content/zh-cn/releases/release.md
```
> [zh] Sync releases/release.md

- data/i18n/zh-cn/zh-cn.toml
https://github.com/kubernetes/website/pull/49412/files
> [zh] Fixed order of translation IDs

- content/zh-cn/case-studies/adidas/index.html
```
content/zh-cn/case-studies/adidas/index.html
```
See [preview](https://deploy-preview-49424--kubernetes-io-main-staging.netlify.app/zh-cn/case-studies/adidas/)
> [zh] Add case-studies/adidas/

- data/i18n/pt-br/pt-br.toml
https://github.com/kubernetes/website/pull/49412/files
> [pt] Fixed order of translation IDs

- content/zh-cn/docs/concepts/security/cloud-native-security.md
> correct one chinese word

- content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_edit-last-applied.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_taint/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_edit-last-applied.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_taint/_index.md
> [zh-cn]sync kubectl_apply/* kubectl_taint

- content/zh-cn/docs/concepts/scheduling-eviction/pod-priority-preemption.md
content/zh-cn/docs/concepts/scheduling-eviction/pod-priority-preemption.md
> [zh-cn]sync pod-priority-preemption

- content/zh-cn/docs/contribute/localization.md
> [zh-cn]sync localization.md

- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
Mainly sync with en #49854 
```
content/zh-cn/docs/concepts/workloads/controllers/deployment.md
```
> [zh] Sync controllers/deployment.md

- content/zh-cn/docs/reference/kubectl/jsonpath.md
Mainly sync with en #49874 
```
content/zh-cn/docs/reference/kubectl/jsonpath.md
```
See [preview](https://deploy-preview-49888--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubectl/jsonpath/)
> [zh] Sync kubectl/jsonpath.md

- content/pl/docs/concepts/windows/_index.md
> [pl] docs/concepts/windows/_index.md

- content/bn/docs/concepts/security/_index.md
https://github.com/kubernetes/website/pull/49411/files
> [bn] Add Tencent Cloud in cloud provider security

- content/ja/docs/concepts/security/_index.md
https://github.com/kubernetes/website/pull/49411/files
> [ja] Add Tencent Cloud in cloud provider security

- content/ru/docs/reference/glossary/kube-apiserver.md
Fixed typo in the `content/ru/docs/reference/glossary/kube-apiserver.md` file.
Closes: #
> Fix typo on the Russian kube-apiserver.md page

- content/en/docs/reference/node/kubelet-files.md
Add a mention of the file graceful_node_shutdown_state on the page https://kubernetes.io/docs/reference/node/kubelet-files/
Closes: https://github.com/kubernetes/website/issues/48610
> Mention graceful_node_shutdown_state in kubelet local files page

- content/en/docs/concepts/security/_index.md
last comment https://github.com/kubernetes/website/pull/49892
> [en] Fix VMware link

- content/en/docs/reference/command-line-tools-reference/feature-gates/HonorPVReclaimPolicy.md
k/k: https://github.com/kubernetes/kubernetes/pull/129583
/hold
> mark HonorPVReclaimPolicy as stable

- content/pl/releases/download.md
update the polish documentation according to the EN.
> [pl] update: releases/download.md

- layouts/blog/content.html
Use the correct lookup for Disqus configuration.
> Fix Disqus config lookup

- content/zh-cn/docs/contribute/style/diagram-guide.md
- content/zh-cn/docs/contribute/style/page-content-types.md
content/zh-cn/docs/contribute/style/diagram-guide.md
content/zh-cn/docs/contribute/style/page-content-types.md
> [zh-cn]sync diagram-guide page-content-types

- content/zh-cn/docs/concepts/security/_index.md
- content/zh-cn/docs/concepts/security/pod-security-standards.md
content/zh-cn/docs/concepts/security/_index.md
content/zh-cn/docs/concepts/security/pod-security-standards.md
> [zh-cn]sync security/_index pod-security-standards

- content/zh-cn/docs/concepts/workloads/autoscaling.md
- content/zh-cn/docs/concepts/workloads/pods/sidecar-containers.md
content/zh-cn/docs/concepts/workloads/autoscaling.md
> [zh-cn]sync sidecar-containers autoscaling

- content/zh-cn/docs/contribute/review/reviewing-prs.md
content/zh-cn/docs/contribute/review/reviewing-prs.md
> [zh-cn]sync reviewing-prs

- content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
> [zh-cn]sync extensible-admission-controllers.md

- content/zh-cn/docs/reference/instrumentation/zpages.md
content/zh-cn/docs/reference/instrumentation/zpages.md
> [zh-cn]sync zpages

- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
- content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors.md
Sync with en text
```
content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors.md
content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
```
> [zh] Sync troubleshooting-cni-plugin-related-errors and security-agent

- content/ja/docs/tasks/run-application/access-api-from-pod.md
Translate content/en/docs/tasks/run-application/access-api-from-pod.md into Japanese.
Preview: https://deploy-preview-49751--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/run-application/access-api-from-pod/
Closes: #49729
> [ja] Translate content/en/docs/tasks/run-application/access-api-from-pod.md

- content/ja/docs/concepts/security/_index.md
> [ja] Fix VMware link

- content/pt-br/docs/concepts/windows/user-guide.md
Localize docs/concepts/windows/user-guide
Closes: # [49553](https://github.com/kubernetes/website/issues/49553#event-16070401820)
> [pt-br] Localize docs/concepts/windows/user-guide

- content/zh-cn/docs/reference/node/kubelet-files.md
```
content/zh-cn/docs/reference/node/kubelet-files.md
```
> [zh] Sync node/kubelet-files.md

- content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md
Ref: https://github.com/kubernetes/website/commit/9a0a7a5f39f1c4255a9813ac87c1c3b1c4fc1a5d#r153205579
> [zh-cn]remove unnecessary lines in taint-and-toleration.md

- content/vi/_index.html
This PR provides below update on landing page (vi language)
- Update link to KubeCon events
- Remove block case-studies, we don't maintain or have plan to add those case-studies in vietnamese anyway, so better to remove the session
- Add missing session: Sign up for KubeWeekly
NONE
> Update landing page vi

- content/zh-cn/docs/reference/node/systemd-watchdog.md
content/zh-cn/docs/reference/node/systemd-watchdog.md
> [zh-cn]sync systemd-watchdog.md

- content/pl/docs/contribute/suggesting-improvements.md
> [pl] docs/contribute/suggesting-improvements.md

- content/id/docs/concepts/security/overview.md
> [id] Fix VMware link

- OWNERS_ALIASES
Added myself to sig-docs-ko-owners.
[[Requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-2)]
Reviewer of the codebase for at least 3 months - I have been a ko-reviewer since [Nov 17, 2023](https://github.com/kubernetes/website/pull/43965).
- Primary reviewer for at least 10 substantial PRs to the codebase - [is:pr assignee:jongwooo](https://github.com/kubernetes/website/pulls?q=is%3Apr+assignee%3Ajongwooo)
- Reviewed or merged at least 30 PRs to the codebase
- Reviewed: [is:pr reviewed-by: jongwooo](https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Ajongwooo)
- Merged: [is:pr is:merged author: jongwooo](https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Ajongwooo)
/cc @kubernetes/sig-docs-ko-owners …
> Add jongwooo to sig-docs-ko-owners

- content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md
> [zh-cn]sync kubectl_replace/_index.md

- content/en/training/_index.html
Remove duplicate element IDs in training page
Closes: #50010
> Update duplicate element ID in training page

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/BtreeWatchCache.md
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/BtreeWatchCache.md
```
> [zh] Add feature-gates/BtreeWatchCache.md

- content/pt-br/docs/concepts/security/overview.md
> [pt] Fix VMware link

- content/zh-cn/docs/reference/glossary/device-plugin.md
https://github.com/kubernetes/website/pull/49834/files
> [zh] remove extra space in pod tag

- content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Tell `nc` to report open ports instead of initiating a connection by using the `-z` flag, and report connection failure after a timeout of 2 seconds.
Closes: #
> Update the check for open port in install-kubeadm.md

- content/en/blog/_posts/2025-03-05-sig-apps-spotlight.md
- content/en/blog/_posts/2025-03-12-sig-apps-spotlight.md
Add SIG Apps Spotlight.
`contributor-site` PR: https://github.com/kubernetes/contributor-site/pull/573 ; reviews to be done there, final approved version will be synced here.
/cc @sandipanpanda
> Add SIG Apps spotlight

- content/ko/docs/setup/production-environment/tools/kubespray.md
resolve https://github.com/kubernetes/website/pull/48994/files
> [ko] Update Link of Inventory in Install k8s doc

- content/ko/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md
https://github.com/kubernetes/website/pull/49479/files
> [ko] Remove monitoring link

- content/ko/docs/concepts/workloads/pods/_index.md
> [ko] Fix Borg research publication link

- content/vi/releases/_index.md
Add release page in vietnamese. We should have this information clear in all language.
NONE
> [vi] Add release page

- i18n/zh-cn/zh-cn.toml
> [zh] Added "LinkedIn" to toml

- content/vi/releases/notes.md
Add page to explain about Kubernetes release note for Vietnamese docs
NONE
> Add release note page for vi docs

- i18n/ru/ru.toml
> [ru] Added "LinkedIn" to toml

- i18n/pt-br/pt-br.toml
> [pt] Added "LinkedIn" to toml

- content/vi/releases/_index.md
- content/vi/releases/version-skew-policy.md
This page contains version skew policy and guideline to upgrade cluster best practice that follow version policy. It should available in Vietnamese too.
NONE
> Add Version Skew Policy page in Vietnamese

- content/en/docs/reference/command-line-tools-reference/feature-gates/PersistentVolumeLastPhaseTransitionTime.md
k/k: https://github.com/kubernetes/kubernetes/pull/129295
/hold
> mark PersistentVolumeLastPhaseTransitionTime as removed

- content/zh-cn/includes/task-tutorial-prereqs.md
Add a reference link:
```
content/zh-cn/includes/task-tutorial-prereqs.md
```
> [zh] Sync includes/task-tutorial-prereqs.md

- content/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers.md
```
```
See [preview](https://deploy-preview-50036--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-deadlocks-in-self-hosted-webhooks)
> [zh] Add text to: extensible-admission-controllers.md

- content/vi/releases/download.md
Part of Release Version group page in Vietnamese
NONE
> Add download Kubernetes page in Vietnamese

- content/id/docs/concepts/workloads/pods/pod-qos.md
- content/id/docs/reference/glossary/qos-class.md
- Localize pod-qos class documentation page.
- Localize pod-qos class glossary.
Closes: #
> [id] Localize pod-qos class documentation

- content/id/docs/concepts/security/_index.md
Translate https://kubernetes.io/docs/concepts/security/ to ID
> ID: Initial commit on translating to ID on concepts/security index page

- i18n/bn/bn.toml
I used a translator, if anything please correct me
> [bn] Added "LinkedIn" to toml

- content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
- content/en/docs/tasks/administer-cluster/kubelet-config-file.md
> Document MergeDefaultEvictionSettings Kubelet Config

- i18n/uk/uk.toml
> [uk] Added "LinkedIn" to toml

- content/vi/releases/release-managers.md
Add release managers page in Vietnamese.
NONE
> Add release managers page in Vietnamese

- content/en/docs/reference/command-line-tools-reference/feature-gates/CRDValidationRatcheting.md
- https://github.com/kubernetes/kubernetes/pull/130013
- https://github.com/kubernetes/enhancements/pull/5082
- https://github.com/kubernetes/enhancements/issues/4008
> KEP-4008: promote CRDValidationRatcheting to GA for 1.33

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletCrashLoopBackOffMax.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletCrashLoopBackOffMax.md
> [zh-cn]sync KubeletCrashLoopBackOffMax.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DaemonSetUpdateSurge.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DaemonSetUpdateSurge.md
> [zh-cn]sync DaemonSetUpdateSurge

- content/en/docs/concepts/policy/node-resource-managers.md
- content/en/docs/tasks/administer-cluster/cpu-management-policies.md
- content/zh-cn/docs/concepts/policy/node-resource-managers.md
- content/zh-cn/docs/tasks/administer-cluster/cpu-management-policies.md
KEP-4540: Move to beta
https://github.com/kubernetes/enhancements/issues/4540
Closes: https://github.com/kubernetes/enhancements/issues/4540
> Mark strict-cpu-reservation as beta

- content/en/docs/reference/command-line-tools-reference/feature-gates/MatchLabelKeysInPodAffinity.md
doc update to graduate MatchLabelKeys (PodAffinity) to GA
https://github.com/kubernetes/enhancements/issues/3633
> KEP-3633: graduate MatchLabelKeys (PodAffinity) to GA

- content/id/docs/concepts/security/hardening-guide/authentication-mechanisms.md
Translate https://kubernetes.io/docs/concepts/security/hardening-guide/authentication-mechanisms/ to ID.
> [id] Initial commit on translate hardening-guide to ID

- content/id/docs/concepts/security/hardening-guide/authentication-mechanisms.md
Fix typo on previous PR which already merged
https://github.com/kubernetes/website/pull/50144
> [id] Translate hardening guide: fix typo and replace to autentikasi

- content/en/docs/reference/command-line-tools-reference/feature-gates/CPUManager.md
k/k: https://github.com/kubernetes/kubernetes/pull/129296
/hold
> mark CPUManager as removed

- content/zh-cn/docs/concepts/storage/persistent-volumes.md
- content/zh-cn/docs/concepts/storage/storage-limits.md
```
content/zh-cn/docs/concepts/storage/storage-limits.md
```
> [zh] Sync persistent-volumes.md and storage-limits.md

- content/en/blog/_posts/2025-12-31-kube-scheduler-simulator/index.md
/sig scheduling 
address the last suggestions, https://github.com/kubernetes/website/pull/47104.
Closes: #
> fix: wording correction on the simulator blog

- content/it/_index.html
> [it] Removed site-searchbar

- i18n/vi/vi.toml
> [vi] Added "LinkedIn" to toml

- content/id/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
- content/id/examples/application/wordpress/mysql-deployment.yaml
- content/id/examples/application/wordpress/wordpress-deployment.yaml
EN page:
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/
> Initial commit on translating wordpress tutorial persistent volume

- content/zh-cn/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md
sync file:
```
content/zh-cn/blog/_posts/2023-08-31-legacy-package-repository-deprecation/index.md
```
> [zh-cn] sync 2023-08-31-legacy-package-repository-deprecation blog

- content/zh-cn/blog/_posts/2025-03-12-sig-apps-spotlight.md
content/zh-cn/blog/_posts/2025-03-12-sig-apps-spotlight.md
> [zh-cn] Add blog: 2025-03-12-sig-apps-spotlight.md

- content/zh-cn/_index.html
```
content/zh-cn/_index.html
```
See [preview](https://deploy-preview-50207--kubernetes-io-main-staging.netlify.app/zh-cn/)
> [zh] Sync zh-cn/_index.html

- i18n/fr/fr.toml
> [fr] Added "LinkedIn" to toml

- content/zh-cn/blog/_posts/2025-03-24-ingress-nginx-CVE-2025-1974.md
```
content/zh-cn/blog/_posts/2025-03-24-ingress-nginx-CVE-2025-1974.md
```
See [preview](https://deploy-preview-50224--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2025/03/24/ingress-nginx-cve-2025-1974/)
> [zh] Add 2025-03-24-ingress-nginx-CVE-2025-1974.md

- content/id/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
Update previous PR
https://github.com/kubernetes/website/pull/50225
> Replace Anda with kamu for a friendlier tone

- content/vi/docs/concepts/_index.md
- content/vi/docs/reference/_index.md
- content/vi/docs/tasks/_index.md
- content/vi/docs/tutorials/_index.md
This change reconstruct the Vietnamese docs to be the same as latest English version
Closes: #
> Reconstruct Vietnamese docs

- content/zh-cn/docs/concepts/security/_index.md
content/zh-cn/docs/concepts/security/_index.md
> [zh-cn]sync security/_index.md

- content/ja/docs/reference/glossary/minikube.md
Translate [`content/en/docs/reference/glossary/minikube.md`](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/minikube.md) into Japanese
Closes: #48904
> [ja] Translate docs/reference/glossary/minikube.md into Japanese

- content/vi/docs/tasks/tools/included/_index.md
- content/vi/docs/tasks/tools/included/verify-kubectl.md
Translate content/vi/docs/tasks/tools/included/verify-kubectl.md
This PR is a prerequisite for PR [50284](https://github.com/kubernetes/website/pull/50284)
> Translate verify-kubectl.md

- content/zh-cn/docs/concepts/architecture/self-healing.md
content/zh-cn/docs/concepts/architecture/self-healing.md
> [zh-cn]sync self-healing.md

- content/zh-cn/docs/tasks/tls/certificate-issue-client-csr.md
Sync with part of en #50002, add a zh file:
```
content/zh-cn/docs/tasks/tls/certificate-issue-client-csr.md
```
See [preview](https://deploy-preview-50083--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/tls/certificate-issue-client-csr/)
> [zh] Add tls/certificate-issue-client-csr.md

- content/zh-cn/docs/concepts/cluster-administration/node-autoscaling.md
Add a zh page:
```
content/zh-cn/docs/concepts/cluster-administration/node-autoscaling.md
```
See [preview](https://deploy-preview-50166--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/node-autoscaling/)
> [zh] Add node-autoscaling.md

- content/zh-cn/case-studies/huawei/index.html
Sync the zh text and layout with the en upstream:
```
content/zh-cn/case-studies/huawei/index.html
```
> [zh] Sync case-studies/huawei/

- content/ja/docs/tasks/manage-daemon/update-daemon-set.md
- content/ja/examples/controllers/fluentd-daemonset-update.yaml
- content/ja/examples/controllers/fluentd-daemonset.yaml
Translate content/en/docs/tasks/manage-daemon/update-daemon-set.md into Japanese
Closes: #50156
> [ja] Translate content/en/docs/tasks/manage-daemon/update-daemon-set.md

- i18n/hi/hi.toml
> [hi] Added "LinkedIn" to toml

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/Accelerators.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_patch/_index.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/Accelerators.md
> [zh-cn]sync Accelerators kubectl_patch/_index

- content/zh-cn/blog/_posts/2024-12-16-cpumanager-strict-cpu-reservation.md
content/zh-cn/blog/_posts/2024-12-16-cpumanager-strict-cpu-reservation.md
> [zh-cn]Add blog: 2024-12-16-cpumanager-strict-cpu-reservation.md

- content/pl/docs/reference/glossary/kubelet.md
[pl] sync with PR #40931
the corresponding commit for EN:
https://github.com/kubernetes/website/commit/2a4a506919b01acaffbd33fc09928ae217454b97
> [pl] sync with PR #40931

- content/pl/releases/_index.md
[pl] sync with PR #45030
additionally:
- add a blank line to synchronize the lines with the EN version
- add an explicit header ID
> [pl] sync with PR #45030

- content/pl/docs/reference/glossary/container-runtime.md
the polish synchronization with PR #42502
> [pl] sync with PR #42502
