kubernetes/website

content/en/docs/reference/access-authn-authz/authorization.md
content/en/docs/reference/access-authn-authz/node.md
content/en/docs/reference/access-authn-authz/rbac.md
content/en/docs/reference/command-line-tools-reference/feature-gates/structured-authorization-configuration.md
content/en/docs/setup/production-environment/_index.md

Adds docs for GA of https://github.com/kubernetes/enhancements/issues/3221
/sig auth
/cc @ritazh @palnabarun

KEP-3221: Promote StructuredAuthorizationConfiguration to GA

---

content/en/docs/concepts/cluster-administration/cluster-autoscaling.md

This PR fixed the hyperlink for `cluster API` and `README` under the [Cluster Autoscaling](https://kubernetes.io/docs/concepts/cluster-administration/cluster-autoscaling/) docs.
Closes: #48461

Fix hyperlinks in Cluster Autoscaling docs.

---

assets/scss/_documentation.scss
content/en/docs/concepts/architecture/_index.md
content/en/docs/contribute/style/hugo-shortcodes/index.md
layouts/shortcodes/details.html

This is about the diagram in https://k8s.io/docs/concepts/architecture/ and how we explain it.
- add a whole new shortcode for creating a `<details>` element
- use that to simplify the explanation about the cluster diagram, whilst still leaving the details there to read in case readers are wondering
- align with our [diagram guide](https://kubernetes.io/docs/contribute/style/diagram-guide/)
[Preview](https://deploy-preview-48447--kubernetes-io-main-staging.netlify.app/docs/concepts/architecture/)

Redo cluster diagram details on architecture page

---

content/en/docs/reference/using-api/api-concepts.md

- remove redundant spaces from a big table
- provide bullets with a consistent look
- fix a link to an anchor `##protobuf-encoding-idl`
/kind cleanup

Clean up using-api/api-concepts.md

---

content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
content/en/docs/tasks/debug/debug-application/debug-service.md

With https://github.com/kubernetes/kubernetes/pull/126847 kube-proxy will no longer depend on conntrack binary, this PR updates the doc with the required changes.
Closes: #

Remove conntrack references

---

content/pt-br/docs/concepts/scheduling-eviction/_index.md

Description:
This PR updates the scheduling-eviction page in the Portuguese documentation (pt-br) to reflect the latest version of the page in English.
Note on Descheduler:
In addition to the main update, we chose to keep the term “Descheduler” instead of translating it to “desagendamento,” to preserve the reference to the official Kubernetes tool and avoid confusion that could arise from the translation.
Changes:
- Update of the page content/pt-br/docs/concepts/scheduling-eviction/_index.md
- Synchronization with the latest version of the English documentation
Related issue: #48426
--- 
Descrição:
Este PR atualiza a página scheduling-eviction na documentação em português (pt-br) para refletir a versão mais recente da página em inglês. 
**Nota sobre Descheduler:**
Além da atualização …

[pt-br] Update scheduling-eviction page based on the English version

---

content/en/docs/reference/using-api/deprecation-policy.md

- remove redundant spaces and wrap lines
- provide bullets with a consistent look
- change a table note text from
`v1alpha2 is removed, "action required" relnote`
to
`v1alpha2 is removed. See release notes for required actions.`

Clean up using-api/deprecation-policy.md

---

layouts/shortcodes/glossary_tooltip.html

This fine-tuning will help to avoid explicit manual language prefixing for the `full_link`. This change does not affect already language prefixed `full_link` (e.g. zh-cn)

Update glossary_tooltip.html to include relLangURL for $external_link

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-priority-and-fairness.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/csi-migration-rbd.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-rbd-unregister.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-ready-pods.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/skip-read-only-validation-gce.md

Sync with en #48436 
```
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/api-priority-and-fairness.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/csi-migration-rbd.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/in-tree-plugin-rbd-unregister.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/job-ready-pods.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/skip-read-only-validation-gce.md
```

[zh] Sync feature-gates/*.md

---

content/en/docs/concepts/security/application-security-checklist.md

Creating an application security checklist.
https://github.com/kubernetes/sig-security/issues/111
https://deploy-preview-46326--kubernetes-io-main-staging.netlify.app/docs/concepts/security/application-security-checklist/

Creating application security checklist

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

NVIDIA's GPU Device Plugin is the most widely used device plugin when it comes to exposing and scheduling NVIDIA GPUs on k8s clusters.

add NVIDIA's k8s-device-plugin to the list of device plugin examples

---

content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md

Fixes the broken link to https://kubernetes.io//docs/reference/access-authn-authz/authentication/#anonymous-authenticator-configuration in `AnonymousAuthConfigurableEndpoints` feature gate description [file](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md).
```diff
- https://kubernetes.io//docs/reference/access-authn-authz/authentication/#anonymous-authenticator-onfiguration
+ https://kubernetes.io//docs/reference/access-authn-authz/authentication/#anonymous-authenticator-configuration
```

Fix broken link in 'AnonymousAuthConfigurableEndpoints' feature gate file

---

content/en/docs/reference/glossary/pod-disruption-budget.md

The tooltip text for the Pod Disruption Budget term renders incorrectly due to the templating of the "Pod" term within the `short_description`. This can be observed by hovering the cursor over the "PodDisruptionBudget" term on the following page: https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/
Fix the issue by replacing the templated text with the literal word "Pod" for the English and Chinese versions of the documentation. Also slightly modify the wording to align with the full description on the following page: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets
Closes: #

glossary: Fix PDB tooltip text

---

content/en/docs/concepts/storage/volumes.md
content/en/docs/reference/command-line-tools-reference/feature-gates/size-memory-backed-volumes.md

Document SizeMemoryBackedVolumes for GA
GA doc requirement for KEP-1967
Closes: #

[KEP-1967] - update docs for GA

---

content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
content/en/docs/concepts/overview/working-with-objects/field-selectors.md
content/en/docs/reference/command-line-tools-reference/feature-gates/custom-resource-field-selectors.md
content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

KEP: ~https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/95-custom-resource-definitions/README.md~
https://github.com/kubernetes/enhancements/issues/4358

KEP-4358: Custom resource field selectors GA

---

content/pt-br/README.md

[pt-br] Delete Localization READMEs section in localized README

---

data/releases/eol.yaml
data/releases/schedule.yaml

I ran `schedule-builder -uc ./data/releases/schedule.yaml -e ./data/releases/eol.yaml` as a starting point to update the release schedule.
/cc @kubernetes/release-managers 
/hold

updating release schedule after alpha cuts

---

content/en/docs/contribute/review/reviewing-prs.md

This PR amends the [Reviewing PRs](https://kubernetes.io/docs/contribute/review/reviewing-prs/) page with a blog section under the Reviewing checklist header
This PR replaces PR  [48180](https://github.com/kubernetes/website/pull/48180)
Credit to @chris-short for commits in the original PR [48180](https://github.com/kubernetes/website/pull/48180) that are not reflected in this PR

Add blog review guideline to Reviewing PRs page

---

content/en/docs/setup/best-practices/certificates.md
content/en/docs/setup/best-practices/node-conformance.md

- try a footnote syntax like [^1]
- remove spaces from a big markdown table
- fix some typos, indentations
See [preview](https://deploy-preview-48401--kubernetes-io-main-staging.netlify.app/docs/setup/best-practices/certificates/)

Clean up best-practices: certificates and node-conformance

---

content/en/docs/concepts/workloads/pods/sidecar-containers.md
content/en/docs/tutorials/configuration/pod-sidecar-containers.md

This is a follow up from https://github.com/kubernetes/enhancements/issues/753#issuecomment-2332796992
We need to improve the page https://kubernetes.io/docs/tutorials/configuration/pod-sidecar-containers/ with the best practices on how to implement sidecar containers. Things like exiting with 0 on SIGTERM
Closes: https://github.com/kubernetes/website/issues/47823

[SidecarContainer] provide sidecar best practices hints about exit code

---

content/en/docs/reference/kubectl/kubectl.md

This PR remove environment variable `KUBECTL_DEBUG_CUSTOM_PROFILE` from the docs for https://github.com/kubernetes/enhancements/issues/4292 as it is promoted to stable now.

KEP-4292: Remove custom profiling env var as it is GA now

---

content/en/docs/reference/command-line-tools-reference/feature-gates/recursive-read-only-mounts.md

The gate has reached beta in v1.31.
refs:
- kubernetes/enhancements#3857
- kubernetes/kubernetes#125475
Closes: #48614

KEP-3857: promote RecursiveReadOnlyMounts feature to beta

---

content/zh-cn/docs/setup/best-practices/certificates.md

Sync with part of en #48401 
```
content/zh-cn/docs/setup/best-practices/certificates.md
```
See [preview](https://deploy-preview-48612--kubernetes-io-main-staging.netlify.app/zh-cn/docs/setup/best-practices/certificates/)

[zh] Sync best-practices/certificates.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/zero-limited-nominal-concurrency-shares.md

k/k: https://github.com/kubernetes/kubernetes/pull/126894
/hold

mark ZeroLimitedNominalConcurrencyShares as removed

---

content/en/docs/concepts/storage/volumes.md

CRI-O v1.30 added the support for this feature.
- cri-o/cri-o#7962
NONE

RecursiveReadOnlyMounts: update the status about CRI-O

---

content/en/docs/tutorials/cluster-management/kubelet-standalone.md

- change `Kubelet` to `kubelet`
- fix indentations of a bullet
- other minor changes about grammar
/kind cleanup

Fix bullet indentations and typos in kubelet-standalone.md

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md
content/en/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action.md

This reverts commit 563032ef023a9b4f1ada8dd405f348505dac0662.
KEP-3960 will not be able to graduated to GA since lack of Periodic testing, and current tests show bad flaking.
Closes: #

Revert #48295 Update KEP-3960 to GA

---

content/en/docs/concepts/configuration/liveness-readiness-startup-probes.md
content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

This pull request includes several minor changes to the documentation in the Kubernetes project, specifically focusing on improving the clarity and correctness of the text.
Documentation improvements:
* Corrected the phrasing in the description of liveness probes to improve readability (`content/en/docs/concepts/configuration/liveness-readiness-startup-probes.md`).
* Fixed the grammar in the explanation of readiness probes to ensure proper verb agreement (`content/en/docs/concepts/configuration/liveness-readiness-startup-probes.md`).
* Adjusted the formatting of a mathematical expression in the startup probe documentation to enhance clarity (`content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md`).
Closes: N/A

Fix: improve clarity and formatting in liveness, readiness, and startup probes documentation

---

content/zh-cn/docs/concepts/configuration/liveness-readiness-startup-probes.md
content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

content/zh-cn/docs/concepts/configuration/liveness-readiness-startup-probes.md

[zh-cn]sync liveness-readiness-startup-probes configure-liveness-readiness-startup-probes

---

content/zh-cn/docs/tutorials/cluster-management/_index.md
content/zh-cn/docs/tutorials/cluster-management/kubelet-standalone.md

Add zh text to the tutorial:
```
content/zh-cn/docs/tutorials/cluster-management/_index.md
content/zh-cn/docs/tutorials/cluster-management/kubelet-standalone.md
```
See [preview](https://deploy-preview-48652--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/cluster-management/kubelet-standalone/)

[zh] Add a tutorial: kubelet-standalone

---

content/en/docs/reference/labels-annotations-taints/_index.md

I assume this is an oversight in the phrasing. If taints are in fact **not** reserved, this still should change, but then I suppose it would not be a documentation issue only.

Taints in kubernetes.io and k8s.io namespace are also reserved

---

content/en/docs/tutorials/configuration/pod-sidecar-containers.md

- fix typos, grammar and consistency issues
- remove `https://kubernetes.io` to use a relative path
See [preview](https://deploy-preview-48651--kubernetes-io-main-staging.netlify.app/docs/tutorials/configuration/pod-sidecar-containers/)

Clean up a tutorial: pod-sidecar-containers.md

---

content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/en/docs/reference/command-line-tools-reference/feature-gates/dra-control-plane-controller.md

This matches https://github.com/kubernetes/kubernetes/pull/128003.
Related-to: https://github.com/kubernetes/enhancements/issues/3063

DRA:  remove "classic DRA"

---

content/en/docs/concepts/containers/images.md

- since the e2e test was added in https://github.com/kubernetes/kubernetes/pull/121604
See https://github.com/kubernetes/enhancements/issues/3673 for more details.

update maxParallelImagePulls to beta

---

content/en/docs/reference/access-authn-authz/authorization.md

Adds a paragraph describing the `systems:master` group to the Authorization reference page
Fixes #48546

Add systems:master mention to the Authz reference page

---

content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md

The file `content/zh-cn/docs/reference/config-api/apiserver-config.v1beta1.md` is outdated and needs to resync.
See [the preview page](https://deploy-preview-48700--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/apiserver-config.v1beta1/).

[zh-cn] resync apiserver-config.v1beta1 reference

---

content/en/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md

Description
fixes this https://github.com/kubernetes/website/issues/48403
Issue
Closes: https://github.com/kubernetes/website/issues/48403
Current 
Proposed

update how to persist enabling ipv6 forwarding across reboot 

---

package-lock.json
package.json

- Fixes #48737
- Now when we run `npm install` or `npm ci` there are no more vulnerabilities:
```console
$ rm -Rf node_modules
$ npm install
added 75 packages, and audited 76 packages in 776ms
21 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
---
In terms of the generated site files:
- There are no changes to the English language pages (i.e., the default locale). That is, `cd public && git diff | grep ^diff | grep -Ev 'diff --git a/..(-..)?/' | wc -l` returns 0
- The only changes that appear to be there for the non-English languages are in the sidenav entries for section entries not of the current page.
```console
$ cd public
$ git diff | grep ^diff | wc -l                                
1356
$ git diff | grep ^diff | head -3
diff --git …
```

Update NPM packages and lock file to eliminate vulnerabilities and warnings

---

content/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1.md

Copy the majority of the new zh text from #48700,
only replacing `v1beta1` with `v1alpha1` more than 50 times.
```
content/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1.md
```
See [preview](https://deploy-preview-48727--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/config-api/apiserver-config.v1alpha1/)

[zh] Sync config-api/apiserver-config.v1alpha1.md

---

content/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md

Add some zh text to sync with en pr #48572 
```
content/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md
```

[zh] Sync kubeadm/dual-stack-support.md

---

Dockerfile

Luc no longer works for the CNCF. Drop the `maintainer` label on our container images.

Drop Luc Perkins as Dockerfile maintainer

---

content/en/docs/contribute/style/style-guide.md

Correcting headings style guide recommendation in Headings & Titles section (use `#` not `---` or `===`) to be consistent with earlier guidance.
Follow up to: https://github.com/kubernetes/website/pull/48667

Correcting Style Guide Headings and Titles section

---

content/ko/docs/tasks/configure-pod-container/quality-service-pod.md

fix ambiguous translations.
This translation can be understood as 'Pod is given a BestEffort even if it doesn't have either requests or limits of Memory or CPU'.
모호한 번역 수정.
이 번역은 메모리 또는 CPU에 요청이나 제한 중 하나만 없어도 pod에 BestEffort가 부여된다 라고 이해될 수 있습니다.

[ko] Fix ambiguous translations

---

content/en/blog/_posts/2018-01-00-Reporting-Errors-Using-Kubernetes-Events.md

As requested in issue https://github.com/kubernetes/website/issues/48754 removed an invalid published date in front matter of `content/en/blog/_posts/2018-01-00-Reporting-Errors-Using-Kubernetes-Events.md`.
Sovles part 1 of https://github.com/kubernetes/website/issues/48754

Remove an invalid published date in front matter of blog

---

content/en/docs/reference/command-line-tools-reference/feature-gates/scheduler-async-preemption.md

Add KEP-4832 feature gate to the doc.
KEP: https://github.com/kubernetes/enhancements/issues/4832

KEP-4832: add SchedulerAsyncPreemption to the doc

---

content/en/docs/reference/access-authn-authz/authorization.md

…f cmd line
remove mentions of beta and featuregate, and change order of cmd line https://github.com/kubernetes/enhancements/issues/3221
Closes: #
/sig auth
/cc @liggitt @palnabarun

KEP-3221: remove mentions of beta and featuregate, and change order of cmd line

---

content/zh-cn/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md

As requested in issue https://github.com/kubernetes/website/issues/48754 updated `content/zh-cn/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md` has an invalid date in its front matter.
Error to solve  when full error message I got when trying to run make serve with Hugo 
`ERROR the "date" front matter field is not a parsable date: see /Users/sreeram/OSS/kube/kubernetes-website/content/zh-cn/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md`
I have put the same value of date as in English version of same files I found https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md?plain=1
Sovles part 2 of https://github.com/kubernetes/website/issues/48754

(zh-cn) Update an invalid date in its front matter in blog

---

content/en/docs/concepts/containers/images.md
content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md

The statement about missing pull secrets is incorrect, the kubelet will still attempt to pull the image if a pull secret is missing.
Added some information about how multiple pull secrets are handled.
Closes: n/a

Clarify image pull secret documentation

---

OWNERS_ALIASES

This PR adds @nate-double-u to the sig-docs-website-owners group so they can approve website code updates.
/cc @natalisucks @reylejano @divya-mohan0209

adding nate-double-u to sig-docs-website-owners

---

assets/scss/_custom.scss

Fix project logo overlapping with other parts of nav bar

---

.dockerignore
Dockerfile
Makefile

In addition to fixing the issue named below, this PR has the **container use the project's specified NPM dependencies**, rather than using a separate list, keeping things DRY.
- Fixes #48739
- Updates Dockerfile to:
- Copy the project's `package.json package-lock.json` files
- Run `npm ci` ... so that Hugo commands from the container use the same NPM packages we do in local development.
- Fixes `container-build`, and changes the command so that it **writes to the local `public` folder**, making it **easier to debug** generated files (without this change, the container build command fails because it can't write to `./public` -- which means the only other alternative would be to write to another container-only folder such as `/tmp/public`, but I think that the solution proposed here is …

Container build: use npm ci over packages files and fix build cmd

---

.gitmodules
hugo.toml
layouts/partials/sidebar-tree.html

This PR upgrades to a newer version of Docsy: 0.3.0 ([preview](https://deploy-preview-48721--kubernetes-io-main-staging.netlify.app/docs/))
Helps with https://github.com/kubernetes/website/issues/32905; also relevant to issue https://github.com/kubernetes/website/issues/44002
In the testing I've done, I haven't found any different look or behavior that still needs fixing.

Bump Docsy to 0.3.x

---

data/releases/schedule.yaml

Update the release schedule to reflect the latest patches.
Generated using schedule builder:
```
[puerco@babieco website] on  main 🦆❯ schedule-builder -uc data/releases/schedule.yaml -e data/releases/eol.yaml 
INFO Validating options                           
INFO Reading schedule file: data/releases/schedule.yaml 
INFO Parsing schedule                             
INFO Updating schedule                            
INFO Adding release schedule: &{Release:1.31.4 CherryPickDeadline:2024-12-06 TargetDate:2024-12-10 Note:} 
INFO Adding release schedule: &{Release:1.30.8 CherryPickDeadline:2024-12-06 TargetDate:2024-12-10 Note:} 
INFO Adding release schedule: &{Release:1.29.12 CherryPickDeadline:2024-12-06 TargetDate:2024-12-10 Note:} 
INFO Skipping outdated upcoming release for 2024-11-19 …
```

Update release schedule with dec '04 patches

---

content/en/docs/reference/using-api/server-side-apply.md

Update the Server-Side Apply doc.
Closes: #

Clarify Server-Side Apply docs and example

---

layouts/shortcodes/reference_docs.html

None of our content uses the `reference_docs` shortcode any more. Drop it.
/kind cleanup

Drop unused Hugo shortcode

---

content/en/docs/concepts/cluster-administration/node-shutdown.md
content/en/docs/reference/command-line-tools-reference/feature-gates/windows-graceful-node-shutdown.md

https://github.com/kubernetes/enhancements/issues/4802
code PR:
https://github.com/kubernetes/kubernetes/pull/127404
Closes: #

Add windows node graceful shutdown doc

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md
content/en/docs/reference/command-line-tools-reference/feature-gates/pod-lifecycle-sleep-action-allow-zero.md

Docs for [KEP 4818: Allow zero value for Sleep Action of PreStop Hook](https://github.com/kubernetes/enhancements/issues/4818). 
Related PRs
- Enhancements PR: https://github.com/kubernetes/enhancements/pull/4855
- Code PR: https://github.com/kubernetes/kubernetes/pull/127094
Closes: nil, part of https://github.com/kubernetes/enhancements/issues/4818

KEP 4818: PodLifecycleSleepActionAllowZero

---

content/en/docs/concepts/storage/volumes.md

Fix sample CEL expression for rejecting gitRepo volumes in volumes.md
Update the sample CEL expression for rejecting gitRepo volumes under `docs/concepts/storage/volumes.md` from \(incorrect\):
```cel
has(object.spec.volumes) || !object.spec.volumes.exists(v, has(v.gitRepo))
```
To \(correct\):
```cel
!has(object.spec.volumes) || !object.spec.volumes.exists(v, has(v.gitRepo))
```
Fix #48816

Fix sample CEL expression in volumes.md

---

content/en/docs/concepts/configuration/manage-resources-containers.md

Clairify the container runtime and kubelet do not enforece memory limits, the kernel does. Also clarify that workloads won't always be OOM killed, and more clearly spell out the differences between memory and CPU limits

clarify CPU and memory limit enforcement differences

---

content/en/blog/_posts/2023-12-15-volume-attributes-class/index.md

The blog post doesn't match how the field actually works and trying to use the blog post content as-is results in a failure.

Fix type parameter in example

---

content/en/docs/tasks/administer-cluster/cpu-management-policies.md

KEP-4540: CPUManager strict-cpu-reservation policy option documentation
https://github.com/kubernetes/enhancements/issues/4540
Kubelet PR:
https://github.com/kubernetes/kubernetes/pull/127483
Closes: https://github.com/kubernetes/enhancements/issues/4540

KEP-4540: CPUManager strict-cpu-reservation policy option documentation

---

content/en/docs/reference/command-line-tools-reference/feature-gates/watch-list-client.md
content/en/docs/reference/command-line-tools-reference/feature-gates/watch-list.md
content/en/docs/reference/using-api/api-concepts.md

Document https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3157-watch-list
xref: https://github.com/kubernetes/enhancements/issues/3157

Document KEP 3157 (watch-list) for milestone 1.32

---

content/en/docs/concepts/storage/storage-classes.md
content/en/examples/storage/storageclass/storageclass-aws-ebs.yaml

This PR corrects a formatting issue in the `StorageClass` YAML configuration where a comment about `tagSpecification` was mistakenly included inside the YAML block. The comment is now moved outside the YAML block for better clarity.
- Moved the comment about `tagSpecification` outside the YAML block.
Closes: #

Move misplaced comment outside YAML block in storageclass-aws-ebs.yaml

---

content/zh-cn/docs/reference/config-api/kubelet-config.v1beta1.md

fixed: update the default value of parameter maxParallelImagePulls
the original description:
MaxParallelImagePulls sets the maximum number of image pulls in parallel. This field cannot be set if SerializeImagePulls is true. Setting it to nil means no limit. Default: nil
Translation error in Chinese version

fixed: update the default value of parameter maxParallelImagePulls

---

content/en/docs/reference/command-line-tools-reference/feature-gates/component-flagz.md
content/en/docs/reference/command-line-tools-reference/feature-gates/component-statusz.md
content/en/docs/reference/instrumentation/zpages.md

Docs for Kubernetes z-pages 
https://github.com/kubernetes/enhancements/issues/4827
https://github.com/kubernetes/enhancements/issues/4828

Add docs for zpages

---

content/en/docs/reference/command-line-tools-reference/feature-gates/allow-unsafe-malformed-object-deletion.md
content/en/docs/reference/using-api/api-concepts.md

KEP: https://kep.k8s.io/3926
PR: https://github.com/kubernetes/kubernetes/pull/127513
/sig auth

add doc for new delete option ignoreStoreReadErrorWithClusterBreakingPotential

---

content/en/docs/reference/command-line-tools-reference/feature-gates/selinux-change-policy.md
content/en/docs/reference/command-line-tools-reference/feature-gates/selinux-mount.md
content/en/docs/tasks/configure-pod-container/security-context.md

This is documentation of SELinuxMount and SELinuxChangePolicy features for 1.32.
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling
It is a complex feature. There are three feature gates + a new controller that affect SELinux + possible breaking change. I tried to put everything into "Assign SELinux labels to a Container" chapter. 
It will get much simpler when all feature gates graduate to GA.
In the future Kubernetes releases, the feature gates will be get enabled in the sequence describe in the [kep](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1710-selinux-relabeling/README.md#story-3-cluster-upgrade), requiring cluster admins to check their cluster before upgrades and opt-out when necessary. I think that …

Document SELinuxChangePolicy and SELinuxMount

---

content/en/docs/concepts/configuration/secret.md
content/en/docs/concepts/security/secrets-good-practices.md
content/en/docs/concepts/security/service-accounts.md
content/en/docs/reference/access-authn-authz/admission-controllers.md
content/en/docs/reference/labels-annotations-taints/_index.md

Add warnings for deprecated `kubernetes.io/enforce-mountable-secrets `annotation. Encourage the use of separate namespaces when isolation is desired.
Closes: #
/sig auth
/cc @liggitt

Add deprecation warnings for enforce-mountable-secrets annotation

---

content/en/docs/concepts/policy/node-resource-managers.md
content/en/docs/tasks/administer-cluster/cpu-management-policies.md

Move the cpu management policies and options docs from tasks to concepts
xref: https://github.com/kubernetes/website/pull/48340#pullrequestreview-2443697490
In the 1.32 cycle I don't have capacity to move except for CPU manager, which is the worst offender anyway. Other managers should follow suite, hopefully in the 1.33 cycle already.
Closes: https://github.com/kubernetes/website/issues/38121 (albeit in a different and IMO better way)

node: start moving the resource management docs to concepts

---

content/en/docs/reference/access-authn-authz/mutating-admission-policy.md
content/en/docs/reference/command-line-tools-reference/feature-gates/mutating-admission-policy.md
content/en/examples/mutatingadmissionpolicy/applyconfiguration-example.yaml
content/en/examples/mutatingadmissionpolicy/json-patch-example.yaml

This documents KEP-3962 for the alpha release of the enhancement in 1.32
Supersedes https://github.com/kubernetes/website/pull/48467
Comments still outstanding from that PR are addressed.

KEP-3962: Mutating admission policy documentation

---

content/en/docs/concepts/policy/node-resource-managers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/prefer-align-cpus-by-uncorecache.md
content/en/docs/tasks/administer-cluster/cpu-management-policies.md

Add documentation for new alpha feature gate: prefer-align-cpus-by-uncorecache
https://github.com/kubernetes/enhancements/issues/4800
https://github.com/kubernetes/kubernetes/pull/126750

Add prefer-align-cpus-by-uncorecache feature gate

---

content/en/docs/concepts/policy/node-resource-managers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/prefer-align-cpus-by-uncorecache.md
content/en/docs/tasks/administer-cluster/cpu-management-policies.md

Add documentation for new alpha feature gate: prefer-align-cpus-by-uncorecache
Closes: #
https://github.com/kubernetes/enhancements/issues/4800
https://github.com/kubernetes/kubernetes/pull/126750

Docs for prefer-align-cpus-by-uncorecache feature

---

content/en/docs/reference/access-authn-authz/service-accounts-admin.md

Adds additional information on handling bound service account tokens, including details on external validation, as per KEP 4193.
https://github.com/kubernetes/enhancements/issues/4193
/cc @liggitt

KEP-4193: Update ServiceAccount admin docs with additional info on bound tokens

---

content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/en/docs/reference/command-line-tools-reference/feature-gates/dra-admin-access.md
content/en/docs/reference/command-line-tools-reference/feature-gates/dynamic-resource-allocation.md
content/en/docs/reference/kubernetes-api/extend-resources/device-class-v1beta1.md
content/en/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1beta1.md
content/en/docs/reference/kubernetes-api/workload-resources/resource-claim-v1beta1.md
content/en/docs/reference/kubernetes-api/workload-resources/resource-slice-v1beta1.md

DRA structured parameters are going to be beta in 1.32.
Related-to: https://github.com/kubernetes/enhancements/issues/4381

DRA 1.32: beta

---

content/en/docs/concepts/workloads/controllers/cron-jobs.md

Add `batch.kubernetes.io/cronjob-scheduled-timestamp` annotation information to CronJob page
[kubernetes/enhancements#4026](https://github.com/kubernetes/enhancements/issues/4026)

Add `batch.kubernetes.io/cronjob-scheduled-timestamp` annotation information to CronJob page

---

content/ja/docs/reference/glossary/security-context.md

Translate `content/en/docs/reference/glossary/security-context.md` into Japanese.
Closes: #48872

[ja] Translate docs/reference/glossary/security-context.md

---

content/en/docs/concepts/configuration/manage-resources-containers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/pod-level-resources.md
content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
content/en/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
content/en/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
content/en/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md
content/en/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
content/en/docs/tasks/administer-cluster/quota-api-object.md
content/en/docs/tasks/configure-pod-container/assign-cpu-resource.md
content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
content/en/docs/tasks/configure-pod-container/assign-pod-level-resources.md
content/en/docs/tasks/configure-pod-container/resize-container-resources.md
content/en/examples/pods/resource/pod-level-cpu-request-limit.yaml
content/en/examples/pods/resource/pod-level-memory-request-limit.yaml
content/en/examples/pods/resource/pod-level-resources.yaml

~Placeholder~ PR for documentation changes for Pod Level Resources Alpha
https://github.com/kubernetes/enhancements/issues/2837

Document pod level resources

---

content/en/docs/reference/command-line-tools-reference/feature-gates/disable-cloud-providers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/dynamic-resource-allocation.md
content/en/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md
content/en/docs/reference/command-line-tools-reference/feature-gates/translate-stream-close-websocket-requests.md

Description
fixes this #47996 
Issues
Closes: #47996

update feature gate information

---

Makefile

Fix an issue where local previewing in a container didn't include draft content.

Build draft content for local preview

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/_index.md

Add Alpha Disclaimer text to:
```
```

[zh] Add alpha disclaimer to kubectl_apply

---

static/css/gridpage.css

Texts are not visible in case-studies page .
Closes: #48770

Fix text not visible in case studies page

---

content/en/blog/_posts/2024-12-11-volume-group-snapshot-beta.md

This is a blog PR for moving volume group snapshots to beta.
Closes: #

Add a blog for volume group snapshots beta

---

content/en/docs/concepts/policy/limit-range.md

1. Improved overall LimitRange Documentation by fixing format and indentation. 
2. Closes: #46899

Improve LimitRange Documentation.

---

content/en/docs/reference/node/node-status.md

https://github.com/kubernetes/website/pull/48848
Closes: #

fix node-monitor-grace-period

---

content/en/blog/_posts/2024-12-11-cpumanager-strict-cpu-reservation.md

KEP-4540: CPUManager strict-cpu-reservation policy option blog
https://github.com/kubernetes/enhancements/issues/4540
Closes: #

KEP-4540: CPUManager strict-cpu-reservation policy option blog

---

content/en/docs/tutorials/security/apparmor.md

Fix collection of node host names for AppArmor profile distribution.
An example in [Setting up nodes with profiles](https://kubernetes.io/docs/tutorials/security/apparmor/#setting-up-nodes-with-profiles) assumes that cluster node names match host names. However, when cluster nodes are listed using the name output format, each node is prefixed with the resource type prefix `node/`, which may not match the node hostname.

Fix collection of node host names for AppArmor profile distribution

---

content/en/blog/_posts/2024-12-11-Kubernetes-v1-32-Release/index.md

PR for adding the Kubernetes 1.32 release blog.
Mergeable before Kubernetes v1.32 is released since this PR contains a `draft: true` attribute in the file metadata.
This blog includes the majority of the identified Major themes from this discussion: https://github.com/kubernetes/sig-release/discussions/2639
In subsitution to the usual blog merge process it will be necessary to open a second PR to remove the `draft: true` attribute on the day of the release, this PR will also include the release name, the logo, the story behind the logo and the definitive date for the release webinar (chapters containing this info are marked in the title as WIP) - see [this discussion](https://kubernetes.slack.com/archives/CNT9Y603D/p1729676191066199).

Add release announcement for v1.32

---

content/en/docs/concepts/policy/resource-quotas.md

Performed actons below:
- remove trailing spaces
- remove redundant spaces from a markdown table with long sentences
- fix some typos and grammar issues
/kind cleanup
See [preview](https://deploy-preview-48944--kubernetes-io-main-staging.netlify.app/docs/concepts/policy/resource-quotas/)

Clean up a policy concept page: resource-quotas

---

content/pt-br/docs/tasks/tools/included/optional-kubectl-configs-pwsh.md
content/pt-br/docs/tasks/tools/install-kubectl-windows.md

added page in pt-br
tasks/tools/install-kubectl-windows.md
issue #48279

[pt-br] Add tasks/tools/install-kubectl-windows.md

---

content/pt-br/case-studies/_index.md
content/pt-br/community/_index.html
content/pt-br/docs/_index.md
data/i18n/pt-br/pt-br.toml

* Sync the l18n strings in the Brazilian Portuguese localization with the current English version.
* Add small updates to `content/pt-br/community/_index.html` and `content/pt-br/docs/_index.md`.
* Fix case studies title (was "Casos de Estudo", but correct translation in Portuguese is "Estudos de Caso").
/cc @edsoncelio @MrErlison

[pt-br] Sync pt-br l18n strings with the English version.

---

content/en/docs/reference/access-authn-authz/admission-controllers.md

Improve (I hope) https://k8s.io/docs/reference/access-authn-authz/admission-controllers/ [[preview](https://deploy-preview-48130--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/admission-controllers/)]
- Change page title. The reference is about admission control (as a concept) as well as providing a list of all admission controllers.
- Expand the intro section to provide more of an explanation of admission control.
- Emphasize that ValidatingAdmissionPolicy, along with mutating and validating webhooks, are extension points.
- Drop stale mention that ValidatingAdmissionPolicy is alpha
I designed these changes so that they won't conflict with #48131. The best way to understand these changes is to merge them both locally and then preview the result.

Improve admission control reference

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

add hami to Kubernetes device plugin examples
Closes: #

add hami to Kubernetes device plugin examples

---

data/releases/schedule.yaml

This PR adds 1.32 to the releases schedule for the 1.32.0 release.
/milestone 1.32
@fsmunoz @sreeram-venkitesh @katcosgrove @kubernetes/release-managers

Add 1.32 to release schedule for 1.32 release

---

content/en/docs/setup/production-environment/tools/_index.md

In [Installing Kubernetes with deployment tools](https://kubernetes.io/docs/setup/production-environment/tools/) the link for `inventory` was updated from: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md#inventory to: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible/inventory.md
It was necessary as it shows "404-Page not found".

Update Link of Inventory in Install k8s doc

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure.md

Once the `kube-proxy` ConfigMap has been updated, we need to restart the `kube-proxy` pods. 
Instead of using two `kubectl` commands, we can do this in one go. 
Closes: #

Simplify kube-proxy refresh once the kube-proxy ConfigMap is updated

---

data/releases/schedule.yaml

This PR updates the patches if we merge https://github.com/kubernetes/website/pull/49006 into `main`. 
It also fixes the target date of v1.32.1 to become Jan 14. 
Follow-up on https://github.com/kubernetes/website/pull/48933

Update release schedule based on main

---

hugo.toml

This PR updates the hugo.toml for v1.31 ahead of the v1.32 release.
Base branch will be updated from main to release-1.31 once that branch exists.
/hold for v1.32 release day

Updates v1.31 hugo.toml for release v1.32

---

content/en/releases/release.md
scripts/releng/update-release-info.sh

Update the script for fetching [Kubernetes Release Cycle](https://kubernetes.io/releases/release/) and updating it.
- Change the warning to a `pageinfo` shortcode
- We reserve warning shortcodes for dangerous, never-do-this kind of advice
- Update the fetched page to match
- Change the first heading to a level 2 (the page title becomes a level 1 heading)
/sig release

Tweak script to update release info page

---

content/zh-cn/docs/tasks/administer-cluster/nodelocaldns.md

Modify an incoherent statement
The "为" is missing from the statement, making the context unintelligible.
语句中缺少了“为”，使上下文无法理解。

fixed:modify an incoherent statement

---

content/en/docs/reference/command-line-tools-reference/kubelet.md

We cannot generate reference for kubelet due to implementation constraints. This PR updates the reference based on a manual comparison between the reference and the kubelet help message.

Update kubelet reference for v1.32

---

content/zh-cn/blog/_posts/2024-12-13-memory-manager-moves-to-ga/index.md

```
content/zh-cn/blog/_posts/2024-12-13-memory-manager-moves-to-ga/index.md
```
See [preview](https://deploy-preview-48935--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2024/11/11/memory-manager-goes-ga/)

[zh] sync 2024-12-13-memory-manager-moves-to-ga/

---

content/en/blog/_posts/2018-05-04-Announcing-Kubeflow-0-1.md
content/en/blog/_posts/2021-10-18-kpng-specialized-proxiers.md
content/en/blog/_posts/2024-12-11-Kubernetes-v1-32-Release/index.md

I just noticed the Kubernetes Penelope blog post typo but while
fixing it I looked around to see if it was anywhere else and found
a couple.

Fix some blog post typos

---

content/ja/docs/tasks/configure-pod-container/pull-image-private-registry.md

Translate `content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md` into Japanese.
Closes: #48888

[ja] Translate docs/tasks/configure-pod-container/pull-image-private-registry.md

---

content/en/docs/reference/glossary/rbac.md

The RBAC section of the glossary page explains only two types of Kubernetes objects: `Role` and `RoleBinding`.
However, RBAC utilizes four types of Kubernetes objects: `Role`, `RoleBinding`, `ClusterRole`, and `ClusterRoleBinding`.
This PR adds descriptions of `ClusterRole` and `ClusterRoleBinding` along with a link to the RBAC documentation to help readers better understand RBAC.
Closes: #48967

Add descriptions of ClusterRole and ClusterRoleBinding to docs/reference/glossary/rbac.md

---

content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md

```
content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md
```
See [preview](https://deploy-preview-49060--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver/)

[zh] Sync command-line-tools-reference/kube-apiserver.md

---

content/en/docs/reference/glossary/kubectl.md

In the glossary entry for [kubectl](https://kubernetes.io/docs/reference/glossary/?all=true#term-kubectl), mention how to pronounce it ([preview](https://deploy-preview-49089--kubernetes-io-main-staging.netlify.app/docs/reference/glossary/?all=true#term-kubectl)).
/language en
/priority backlog

Mention official kubectl pronunciation

---

content/en/docs/reference/command-line-tools-reference/feature-gates/recover-volume-expansion-failure.md

Since Kubernetes 1.32 release, the RecoverVolumeExpansionFailure feature flag is in Beta stage.
C.f: https://kubernetes.io/blog/2024/12/11/kubernetes-v1-32-release/

feat: the RecoverVolumeExpansionFailure feature flag is in Beta stage since 1.32

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-crash-loop-back-off-max.md

```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/kubelet-crash-loop-back-off-max.md
```

[zh] Add zh text to pods/pod-lifecycle.md and related feature gate

---

content/en/docs/concepts/storage/volumes.md

Currently, the name of the `key` in the `ConfigMap` coincides with the name of the `path` inside the `volumes` declaration. This may confuse people since it is not clear which of the values will be used later on when constructing the path to the file in the `volumeMounts` specification of the Container. To make the example more clear I renamed the filename so that it is different from the `key` and therefore it is more clear what object is used.
Currently, the value of the `ConfigMap.items[].key` field is the same as the `ConfigMap.items[].path` name in the declaration of `volumes`:
```yaml
volumes:
- name: config-vol
configMap:
name: log-config
items:
- key: log_level
path: log_level
```
This can confuse people, as it is not clear which of these values will be used when constructing the …

Use a path different from the key in the ConfigMap

---

content/zh-cn/docs/reference/instrumentation/zpages.md

```
content/zh-cn/docs/reference/instrumentation/zpages.md
```
See [preview](https://deploy-preview-49148--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/instrumentation/zpages/).

[zh] Add instrumentation/zpages.md

---

content/zh-cn/docs/concepts/cluster-administration/node-shutdown.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-graceful-node-shutdown.md

```
content/zh-cn/docs/concepts/cluster-administration/node-shutdown.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/windows-graceful-node-shutdown.md
```

[zh] Sync cluster-administration/node-shutdown.md and its feature gate

---

content/en/docs/tasks/manage-kubernetes-objects/kustomization.md

Description
fixes this #48782 
Issues
Closes: #48782

update deprecated fields in kustomization documentation

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon_coredns.md

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon_coredns.md

[zh-cn]sync kubeadm_init_phase_addon_coredns.md

---

content/en/docs/concepts/overview/working-with-objects/names.md

Hello ,
This PR resolve the issue bellow related to a typographical error in "Object Names and IDs" page #49199 
Current Text:
resulting in a HTTP 409 resopnse.
Change made:
resulting in a HTTP 409 response.
The related Page :
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
https://github.com/kubernetes/website/issues/49199

fixing the typo the Object Names and IDs page

---

content/ja/docs/tasks/configure-pod-container/resize-container-resources.md
content/ja/examples/pods/qos/qos-pod-5.yaml

Translate
`content/en/docs/tasks/configure-pod-container/resize-container-resources.md`
into Japanese
`content/ja/docs/tasks/configure-pod-container/resize-container-resources.md`
Closes: https://github.com/kubernetes/website/issues/48884
/language ja

[ja] Translate resize-container-resources.md into Japanese

---

content/zh-cn/docs/concepts/storage/volumes.md

[zh] Use a path different from the key in the ConfigMap

---

content/zh-cn/docs/concepts/overview/working-with-objects/field-selectors.md

content/zh-cn/docs/concepts/overview/working-with-objects/field-selectors.md

[zh-cn]sync field-selectors.md

---

content/zh-cn/docs/concepts/overview/working-with-objects/names.md
content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon.md

content/zh-cn/docs/concepts/overview/working-with-objects/names.md
content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_node_phase_addon.md

[zh-cn]sync scheduling-framework kubeadm_upgrade_node_phase_addon names

---

content/zh-cn/docs/tasks/configure-pod-container/resize-container-resources.md

Fix some issues mentioned in https://github.com/kubernetes/website/pull/49035#discussion_r1893556426

[zh] Update resize-container-resources.md

---

content/ja/docs/concepts/storage/volumes.md

[ja] Use a path different from the key in the ConfigMap

---

content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
content/zh-cn/docs/concepts/policy/pid-limiting.md

content/zh-cn/docs/concepts/policy/pid-limiting.md

[zh-cn]sync device-plugins pid-limiting

---

content/zh-cn/docs/concepts/policy/node-resource-managers.md

[zh] sync concepts/policy/node-resource-managers.md
Closes: #

[zh] sync concepts/policy/node-resource-managers.md

---

content/fr/docs/reference/kubectl/quick-reference.md

This PR main purpose is to add a new file of the french version of the documentation page https://kubernetes.io/docs/reference/kubectl/quick-reference/ , that's the equivalent of/ redirecting to [cheatsheet/](https://kubernetes.io/docs/reference/kubectl/cheatsheet/).
This pull request resolves partially the open issue : 
[ Most wanted page - French #17598 ](https://github.com/kubernetes/website/issues/17598)

Create quick reference new french page

---

content/en/docs/reference/glossary/drain.md

This PR adds a new glossary entry for the term "drain" to explain its meaning in Kubernetes. 
The entry includes a brief explanation of the concept, along with a reference to the kubectl drain command. 
Closes: #49185

Add drain to glossary

---

content/fr/docs/concepts/overview/kubernetes-api.md

Update the discovery document link in the [Kubernetes APIs documentation](https://kubernetes.io/fr/docs/concepts/overview/kubernetes-api/#d%C3%A9couverte-agr%C3%A9g%C3%A9e). The current link is returning a 404 error on GitHub.

[fr] update discovery document link

---

content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/component-flagz.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/component-statusz.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-level-resources.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/scheduler-async-preemption.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-list-client.md

Add 5 new more feature gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/component-flagz.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/component-statusz.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/pod-level-resources.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/scheduler-async-preemption.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/watch-list-client.md
```

[zh] Add 5 more feature gates

---

layouts/partials/css.html

> Start building sites … 
hugo v0.134.2+extended darwin/arm64 BuildDate=2024-09-10T10:46:33Z VendorInfo=brew
> 
>WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
Closes: #

Replace resources.ToCSS with css.Sass due to deprecation of the former

---

content/en/docs/contribute/new-content/new-features.md

The current naming style creates some problems for tracking/maintaining the list of feature gates. People gets confused about how to convert the feature name to the kebal-case. The sorted list of the converted names are different from the output of the help of command line tools. This further complicates the cross-checking of missing/removed features.
This PR changes the style to be a more straigth-forward way, i.e. use the feature name as the file name. No extra conversion should be included. This makes the lives of everyone a lot easier.
Closes: #

Revise naming style for feature state files

---

content/en/docs/concepts/workloads/pods/_index.md

Current link to Borg research paper (`https://research.google.com/pubs/pub43438.html`) is being redirected to `https://ai.google/research/pubs/pub43438/`, which in turn displays "Page not found" error.
Use a direct link to PDF.

Fix Borg research publication link

---

content/en/docs/reference/labels-annotations-taints/_index.md

This is a followup to https://github.com/kubernetes/website/pull/47383

Document labels, annotations and taints for JobSet

---

content/ja/docs/reference/glossary/pod-lifecycle.md

/language ja
Translate content/en/docs/reference/glossary/pod-lifecycle.md into Japanese.
Closes: #48855

[ja] Translate content/en/docs/reference/glossary/pod-lifecycle.md into Japanese

---

content/zh-cn/docs/reference/labels-annotations-taints/_index.md

[zh] Add text to: labels-annotations-taints/_index.md

---

content/en/docs/concepts/cluster-administration/node-shutdown.md

Fix some typos and consistency issues after running `npx prettier --w`
/kind cleanup
See [preview](https://deploy-preview-49146--kubernetes-io-main-staging.netlify.app/docs/concepts/cluster-administration/node-shutdown/)

Clean up cluster-administration/node-shutdown.md

---

content/en/docs/concepts/workloads/pods/user-namespaces.md

The number of subuids and subgids for each of pods is hard-coded to 65536, regardless to the total ID count specified in `/etc/subuid` and `/etc/subgid`: https://github.com/kubernetes/kubernetes/blob/v1.32.0/pkg/kubelet/userns/userns_manager.go#L211-L228
This fact was not clarified in the documentation.
NONE

user-namespaces.md: subid count per pod is hard-coded to 65536

---

content/en/docs/setup/production-environment/container-runtimes.md

Upgrade the version of the sandbox image, to the one used in Kubernetes 1.32
Closes: #49296

Upgrade the version of the sandbox image

---

content/en/docs/concepts/overview/kubernetes-api.md

Updated kubernetes-api.md - Added short warning about possible incompleteness of OpenAPI schemas

Add warning about incompleteness of OpenAPI schemas to kubernetes-api.md

---

content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md

The suggested link `kubectl proxy` does not work anymore. Also the new helm chart's output of `helm upgrade ...` suggests the usage to `kubectl port-forward`. This commit adepts the way ass suggested by the helm chart.
Closes: #46475

Update web-ui-dashboard.md: Adopted port-forward from official helm chart

---

content/en/docs/tasks/manage-daemon/create-daemon-set.md
content/en/examples/application/basic-daemonset.yaml

* This PR adds a new page to the Kubernetes documentation under the "Manage Daemon" tasks section. The new guide provides a step-by-step process for creating a basic DaemonSet that:
* Mounts `/etc/machine-id` from the host as a read-only volume. 
* Logs the machine ID using an init container.
* Uses a pause container as the main container.
* This guide helps users understand how to get started with DaemonSets, focusing on key features like init containers and host path volumes. The task is designed to demonstrate a simple, functional DaemonSet running on all nodes in a cluster, providing an easy-to-follow introduction to DaemonSets.
Closes: #48438

Create new task for building basic daemon set

---

OWNERS_ALIASES

Removes sftim from leads, as he is now emeritus. Adds katcosgrove, as I am a tech lead.
cc: @divya-mohan0209 @natalisucks @reylejano @salaxander

Removes sftim from leads; adds katcosgrove

---

netlify.toml

This removes the branch based context of "context.main" which would be triggered and override any other contexts even during the PR cycle. The assumption here is that "production" context is marked appropriately on Netlify admin UI, and once it's in place, this should have the same effect to ensure we do not publish any draft or future date posts.
I'm not fully familiar with Netlify, and this is an attempt to solve the draft blog posts to be reviewed in the future (this was originally highlighted in #48962 and tested with #48998). While I believe we need Netlify build to handle PRs better, this would need to be checked carefully as it could impact the website as a whole.

Update branch based context to production for Netlify

---

OWNERS_ALIASES

This is a cleanup PR after the 1.32 release
See https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#clean-up-access for cleanup tasks
- removed 1.32 release team docs lead from sig-docs-en-owners
- add 1.33 release team docs lead to sig-docs-en-owners
cc @chendave @rayandas

Remove 1.32 docs lead from en owners after 1.32 release and add 1.33 docs lead

---

content/en/docs/reference/command-line-tools-reference/feature-gates/JobManagedBy.md

The default value for `JobManagedBy` is `true`, not `false`.

Fix gate status for JobManagedBy in v1.32

---

content/en/docs/reference/command-line-tools-reference/feature-gates/DefaultHostNetworkHostPortsInPodTemplates.md

The gate was removed in v1.31.

Fix gate status for DefaultHostNetworkHostPortsInPodTemplates

---

content/en/docs/reference/command-line-tools-reference/feature-gates/APIServingWithRoute.md

Docs for this gate has been missing since v1.30.

Add feature gate for APIServingWithRoute

---

content/en/docs/concepts/overview/kubernetes-api.md

Fixed broken link for  discovery document in https://kubernetes.io/docs/concepts/overview/kubernetes-api/
Closes: #49286

Fix broken link for discovery document

---

content/en/docs/reference/command-line-tools-reference/feature-gates/EventedPLEG.md

This gate was introduced in v1.26 rather than v1.25.

Fix status for EventedPLEG

---

content/en/docs/reference/command-line-tools-reference/feature-gates/StorageVersionMigrator.md

The alpha stage for `StorageVersionMigrator` has not ended yet.

Fix gate status for StorageVersionMigrator in v1.32

---

static/_redirects

As per [comments](https://github.com/kubernetes/website/pull/49304#discussion_r1905522620) in #49304, add a redirect link from the legacy AppArmor tutorial to the new page.
If there are legacy links, send people to the new page.
Done for Japanese only.
/cc @Okabe-Junya

[ja] Redirect legacy AppArmor tutorial to new page

---

content/en/releases/release.md

Folks have been adding milestone to their PRs post Code-Freeze, which they shouldn't do.
We're adding documentation to discourage that behaviour.
Also updated here: https://github.com/kubernetes/sig-release/pull/2668
cc @katcosgrove @fsmunoz

Clarification for milestone-maintainer post Code-Freeze (2/2)

---

content/en/docs/reference/command-line-tools-reference/feature-gates/StrictCostEnforcementForWebhooks.md

The feature gate `StrictCostEnforcementForWebhooks` is now stable in v1.32.

Fix gate status for StrictCostEnforcementForWebhooks in v1.32

---

content/en/docs/reference/command-line-tools-reference/feature-gates/StrictCostEnforcementForVAP.md

The gate `StrictCostEnforcementForVAP` has been GA'ed and locked to default in v1.32.

Fix gate status for StrictCostEnforcementForVAP in v1.32

---

assets/scss/_custom.scss

Currently, if the deprecation warning is displayed, it brings unnecessary horizontal scrolling when old versions of some pages (e.g. [/community in v1.31](https://v1-31.docs.kubernetes.io/community/)) rendered in Google Chrome. It happens due to this block's width being a bit larger than the actual screen width:
This PR fixes that by changing the width value from `100vw` to `100%`. I tested this change in Google Chrome 131.0.6778.139 (Official Build) (64-bit) under Linux + reassured it didn't affect the page rendering in Firefox/Linux.

Fix horizontal scrolling for the deprecation warning

---

content/pl/docs/tutorials/_index.md

[pl] Remove tutorials link to java microservice example

---

content/uk/docs/tutorials/_index.md

[uk] Remove tutorials link to java microservice example

---

content/en/docs/concepts/storage/volume-snapshot-classes.md

This improves the understanding of what happens when you run multiple CSI drivers and create a default VolumeSnapshotClass. For example:
- The effect of creating a volume snapshot for multiple CSI drivers without specifying a VolumeSnapshotClass.
- The effect of creating multiple default VolumeSnapshotClass for the same CSI driver.
Closes: #49069

Update the Volume Snapshot Classes Page

---

content/zh-cn/docs/tutorials/_index.md

[zh-cn] Remove tutorial link to java microservice example

---

content/zh-cn/docs/concepts/overview/kubernetes-api.md

please review
Original link：(https://github.com/kubernetes/website/pull/49025)

[zh-cn] Sync kubernetes-api.md

---

content/ja/docs/concepts/workloads/pods/_index.md

[ja] Fix Borg research publication link

---

content/ja/docs/tutorials/_index.md

[ja] Remove tutorials link to java microservice example

---

content/en/docs/reference/access-authn-authz/validating-admission-policy.md

Reorder the bullet points in the "What Resources Make a Policy" section of the Validating Admission Policy documentation to improve logical flow. Previously, the `ValidatingAdmissionPolicyBinding` was described as linking "the above resources" when only one resource had been mentioned. This change puts the parameter resource description before the binding, making the documentation more accurate and easier to understand.
The change reorders the components as follows:
1. ValidatingAdmissionPolicy (abstract logic)
2. Parameter resource (concrete configuration)
3. ValidatingAdmissionPolicyBinding (links the above two resources)
Closes: #49136

Reorder ValidatingAdmissionPolicy components for logical flow

---

content/bn/docs/tutorials/_index.md

[bn] Remove tutorials link to java microservice example

---

content/en/docs/reference/command-line-tools-reference/feature-gates/DisableNodeKubeProxyVersion.md

The gate was "deprecated" in v1.31 after several rounds of battles.

Fix gate status for DisableNodeKubeProxyVersion

---

content/es/docs/tutorials/_index.md

[es] Remove tutorials link to java microservice example

---

content/en/docs/tasks/manage-kubernetes-objects/kustomization.md

- Fix some typos.
- Wrap long lines
- Remove extra spaces and `|` from a markdown table with long sentences

Tweak manage-kubernetes-objects/kustomization.md

---

content/pt-br/docs/tutorials/_index.md

[pt-br] Remove tutorial link to java microservice example

---

assets/scss/_base.scss
assets/scss/_desktop.scss
assets/scss/_tablet.scss
content/en/_index.html

I'm suggesting this redesign of the "Attend KubeCon…" block on the main page (see _After_):
In my understanding, it's needed since we have five KubeCons now, and adding more huge buttons (as we did before — see _Before_) won't really work anymore.
While working on this design improvement, I've also noticed a long-standing HTML bug since we had such entities for the KubeCon links for many years: `<a href="..." button id="desktopKCButton">`. They are not valid for two reasons: a) the `<a>`  tag does not have the `button` attribute, and b) we can't use the same `id` for numerous HTML objects on the same page. Thus, I removed the `button` attribute and converted `desktopKCButton` from `id` to `class`.
UPDATE: To maintain back compatibility with the localised pages having old content at the …

Redesign KubeCon links on the main page

---

data/i18n/en/en.toml
layouts/partials/sidebar-tree.html

Allow localizing labels that are used in the sidebar navigation to help accessibility.
Helps with https://github.com/kubernetes/website/issues/49298
Split out from https://github.com/kubernetes/website/pull/48721
We could also contribute this to Docsy

Localize accessibility text in sidebar nav

---

content/en/docs/concepts/overview/kubernetes-api.md

Update the discovery document link in the [Kubernetes APIs documentation](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#aggregated-discovery). The current link is returning a 404 error on GitHub.

[en] update discovery document link

---

.gitignore
Dockerfile
Makefile
content/en/docs/contribute/style/diagram-guide.md
layouts/partials/hooks/head-end.html
layouts/partials/scripts.html
package-lock.json
package.json

This PR upgrades to a newer version of Docsy: 0.6.0
Relevant to issue #44002
Local and container testing looks good, including mermaid graphs
Related PR #48724

Upgrade Docsy to 0.6

---

content/en/docs/concepts/workloads/pods/sidecar-containers.md

Clarify that only chaging the image of a sidecar container will not restart the pod.
Previously had contradicting information:
`Altering an init container image field is equivalent to restarting the Pod.`
and
`The Pod will not be restarted when the init container image is changed,`
xref: https://github.com/kubernetes/kubernetes/issues/121333

Clarify image change restart behavior for sidecar containers

---

content/de/_index.html

Following the recent KubeCon links section UI update & content actualisation for 2025 (#49167), I'm applying the same changes to the German localisation.

[de] Sync KubeCon section UI & 2025 links to German

---

content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md

[zh-cn] sync user-namespaces.md

---

content/ru/_index.html

Following the recent KubeCon links section UI update & content actualisation for 2025 (#49167), I'm applying the same changes to the Russian localisation.

[ru] Sync KubeCon section UI & 2025 links to Russian

---

content/fr/_index.html

Following the recent KubeCon links section UI update & content actualisation for 2025 (https://github.com/kubernetes/website/pull/49167), I'm applying the same changes to the French localisation.

[fr] Sync KubeCon section UI & 2025 links to French

---

content/uk/_index.html

Following the recent KubeCon links section UI update & content actualisation for 2025 (#49167), I'm applying the same changes to the Ukrainian localisation.

[uk] Sync KubeCon section UI & 2025 links to Ukrainian

---

content/en/docs/contribute/style/diagram-guide.md

The `{{</* figure */>}}` is failed to render in the notes of [diagram-guide page](https://kubernetes.io/docs/contribute/style/diagram-guide/), like:

Fix figure shortcode rendering failed in the notes of diagram-guide

---

content/pt-br/docs/concepts/windows/intro.md

ContainerD is a product name and should not be localized.
/cc @edsoncelio

[pt-br] Fix small typo in containerd product name

---

content/en/docs/concepts/storage/persistent-volumes.md

Courrently, description of `ReadWriteOnce` leaves room for misinterpretation
of the `access` in "multiple pods to access the volume" bit. This leads
to spread of confusing information like multiple pods can access but only
one pod can write at a time.
See also  https://github.com/kubernetes/kubernetes/issues/60903#issuecomment-2592863002

Clarify ReadWriteOnce allows multiple pods to read and write

---

content/zh-cn/docs/contribute/style/diagram-guide.md

Update zh content in:
```
content/zh-cn/docs/contribute/style/diagram-guide.md
```
See [preview](https://deploy-preview-49434--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/style/diagram-guide/)

[zh] sync style/diagram-guide.md

---

assets/js/banner-dismiss.js

At the moment, opening any documentation page results in a JavaScript error caused by referring to a null object. Here's how Firefox displays it in the Console:
```
Uncaught TypeError: e is null
<anonymous> https://kubernetes.io/js/banner-dismiss.min.095ea25f4d8d1299fa348e27bfc7822ce87d0fba4f01d3660670afc7b3184df0.js:1
jQuery 2
e
t
banner-dismiss.min.095ea25f4d8d1299fa348e27bfc7822ce87d0fba4f01d3660670afc7b3184df0.js:1:394
<anonymous> https://kubernetes.io/js/banner-dismiss.min.095ea25f4d8d1299fa348e27bfc7822ce87d0fba4f01d3660670afc7b3184df0.js:1
jQuery 2
```
This PR fixes the error by adding extra `if`'s to check whether the desired HTML objects (`#announcement` and `#banner-dismiss`) exist before using them. It's very similar to what was offered in #45991, but I'm not sure why that PR …

Fix JavaScript null object error in banner-dismiss.js

---

content/en/blog/_posts/2024-09-18-sig-arch-enhancements-spotlight.md
content/en/blog/_posts/2025-01-21-sig-arch-enhancements-spotlight.md

Add SIG Architecture: Enhancements spotlight article.
contrib-site PR: https://github.com/kubernetes/contributor-site/pull/526

Add SIG Architecture Enhancements spotlight

---

content/en/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md

Removing the monitoring link from the What's Next section from the monitoring page as it is redirecting to the same page itself. I think the reader has read that page and would want to read some other page in the what's next section.

Remove monitoring link

---

content/en/docs/concepts/architecture/leases.md

fix typo in leases.md
when i execute the following command, there is no "kube-" in "kube-apiserver-sha256-hash"
```
myuser@workstation0:~$ kubectl -n kube-system get lease -l apiserver.kubernetes.io/identity=kube-apiserver
NAME                                   HOLDER                                                                      AGE
apiserver-c7uylvfxlbqccnk6myfkwetzze   apiserver-c7uylvfxlbqccnk6myfkwetzze_1c2230d2-4137-4a1c-88ee-1a23655c0fb7   8h
```

fix: typo in leases.md

---

content/zh-cn/docs/concepts/storage/persistent-volumes.md

Sorry, I don't know why there are more and more conflicts to resolve. Finally, I wanted to roll back but was forced to terminate the last PR. ([49469](https://github.com/kubernetes/website/pull/49469))
`content/zh-cn/docs/concepts/storage/persistent-volumes.md`
src: 
- ([#49447](https://github.com/kubernetes/website/pull/49447))
- ([#49279](https://github.com/kubernetes/website/pull/49279))

[zh-cn] sync persistent-volumes.md

---

content/zh-cn/docs/concepts/workloads/controllers/daemonset.md
content/zh-cn/docs/concepts/workloads/controllers/job.md
content/zh-cn/docs/concepts/workloads/controllers/replicaset.md

[zh] unify spec section translation for all workloads
Closes: #

[zh] unify spec section translation for all workloads

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md

currently the `kubeadm reset` command when finished prints the following:
```
The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d
The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually by using the "iptables" command.
If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.
The reset process does not clean your kubeconfig files and you must remove them manually.
Please, check the contents of the $HOME/.kube/config file.
```
instead of printing that information from the CLI we should keep it document at the website and link to the reset page from the output of the command.
xref
- …

kubeadm-reset: add notes about more manual cleanup steps

---

content/es/docs/concepts/architecture/leases.md

there is no 'kube-' in 'kube-apiserver-sha256-hash' .
i reported this typo in pull request #49475 for english language 
and it was accepted .
however, the next day, i realized that this it is a technical typo so 
it should be corrected in all other translations .
today, I corrected that typo in the translations: es, fr, ja, ko, zh-cn .
but interestingly, in the 'JA' translation (at lines 39-44) and
the 'KO' translation (at lines 46-50), there is a result with 'kube-apiserver-' .
maybe someone who translated it into JA/KO languages noticed this typo, but
it was corrected in the wrong place, or perhaps it worked differently 
in an older version.
i double-checked on my computer, and I have 'apiserver-sha256-hash' with no 'kube-'.
```
myuser@workstation0:~$ kind --version
kind version 0.26.0 …
```

[es] fix: typo in leases.md

---

content/zh-cn/docs/contribute/new-content/new-features.md

content/zh-cn/docs/contribute/new-content/new-features.md

[zh-cn]sync new-features.md

---

content/zh-cn/docs/concepts/architecture/leases.md

there is no 'kube-' in 'kube-apiserver-sha256-hash' .
i reported this typo in pull request #49475 for english language 
and it was accepted .
however, the next day, i realized that this it is a technical typo so 
it should be corrected in all other translations .
today, I corrected that typo in the translations: es, fr, ja, ko, zh-cn .
but interestingly, in the 'JA' translation (at lines 39-44) and
the 'KO' translation (at lines 46-50), there is a result with 'kube-apiserver-' .
maybe someone who translated it into JA/KO languages noticed this typo, but
it was corrected in the wrong place, or perhaps it worked differently 
in an older version.
i double-checked on my computer, and I have 'apiserver-sha256-hash' with no 'kube-'.
```
myuser@workstation0:~$ kind --version
kind version 0.26.0 …
```

[zh-cn] fix: typo in leases.md

---

content/zh-cn/docs/concepts/storage/volume-snapshot-classes.md

please review
`content/zh-cn/docs/concepts/storage/volume-snapshot-classes.md`
src: ([#49381](https://github.com/kubernetes/website/pull/49381))

[zh-cn] sync volume-snapshot-classes.md

---

content/fr/docs/concepts/architecture/leases.md

there is no 'kube-' in 'kube-apiserver-sha256-hash' .
i reported this typo in pull request #49475 for english language 
and it was accepted .
however, the next day, i realized that this it is a technical typo so 
it should be corrected in all other translations .
today, I corrected that typo in the translations: es, fr, ja, ko, zh-cn .
but interestingly, in the 'JA' translation (at lines 39-44) and
the 'KO' translation (at lines 46-50), there is a result with 'kube-apiserver-' .
maybe someone who translated it into JA/KO languages noticed this typo, but
it was corrected in the wrong place, or perhaps it worked differently 
in an older version.
i double-checked on my computer, and I have 'apiserver-sha256-hash' with no 'kube-'.
```
myuser@workstation0:~$ kind --version
kind version 0.26.0 …
```

[fr] fix: typo in leases.md

---

content/ja/docs/concepts/architecture/leases.md

there is no 'kube-' in 'kube-apiserver-sha256-hash' .
i reported this typo in pull request #49475 for english language 
and it was accepted .
however, the next day, i realized that this it is a technical typo so 
it should be corrected in all other translations .
today, I corrected that typo in the translations: es, fr, ja, ko, zh-cn .
but interestingly, in the 'JA' translation (at lines 39-44) and
the 'KO' translation (at lines 46-50), there is a result with 'kube-apiserver-' .
maybe someone who translated it into JA/KO languages noticed this typo, but
it was corrected in the wrong place, or perhaps it worked differently 
in an older version.
i double-checked on my computer, and I have 'apiserver-sha256-hash' with no 'kube-'.
```
myuser@workstation0:~$ kind --version
kind version 0.26.0 …
```

[ja] fix: typo in leases.md

---

content/zh-cn/docs/concepts/overview/kubernetes-api.md

Update the discovery document link in the [Kubernetes APIs documentation](https://kubernetes.io/zh-cn/docs/concepts/overview/kubernetes-api/#aggregated-discovery). The current link is returning a 404 error on GitHub.

[zh] update discovery document link

---

data/releases/schedule.yaml

This PR adds January 2025 releases to the schedule and adds a release date for April 2025 releases.
/assign @saschagrunert @Verolop @jeremyrickard 

Add January 2025 releases to the schedule

---

content/zh-cn/docs/tasks/manage-daemon/create-daemon-set.md

content/zh-cn/docs/tasks/manage-daemon/create-daemon-set.md

[zh-cn]sync create-daemon-set.md

---

content/zh-cn/docs/reference/instrumentation/slis.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_etcd.md

content/zh-cn/docs/reference/instrumentation/slis.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_etcd.md

[zh-cn]sync slis kubeadm_init_phase_etcd

---

content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/_index.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_upload-config_kubeadm.md

[zh-cn]sync kubeadm_init/*

---

content/en/docs/concepts/scheduling-eviction/assign-pod-node.md

There is a typo in the example for `mismatchLabelKeys` where the word `have` was accidentally written as `hate`.
Furthermore, the part `otherwise this Pod would have Pods from daemonsets as well` does not seem clear enough to me. I guess we could replace `have` with something more descriptive?

Fix typo in mismatchLabelKeys example

---

content/en/docs/concepts/cluster-administration/system-traces.md

Fix OpenTelemetry Protocol hyperlink to point directly to OTLP specification

---

Dockerfile

Creating this draft PR to check if the issue #49460 is due to flakiness. This PR updates the Dockerfile by changing the version of the base image from `golang:1.23.0-alpine3.20` to `golang:1.23.1-alpine3.20` which is a trigger condition for the prow job to run.
Re: #49460 
/cc @ameukam

Bump Golang version for local preview container image

---

content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

I spent lots of time trying to upgrade my Kubernetes cluster and re-reading the official doc only to realise the information I was missing wasn't referenced in the main kubeadm upgrade document, but one of the subsequent pages. I believe simple reference in correct place will facilitate upgrade process for many people doing this from now on
N/A

Add advice about checking package repository source (RPM)

---

content/pt-br/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md

Translate the card front-matter in the
`tasks/access-application-cluster/configure-access-multiple-clusters` page so the correct version shows up in the documentation initial page.
/cc @edsoncelio @MrErlison

[pt-br] Translate card front-matter for configuring clusters

---

content/ja/docs/tasks/configure-pod-container/migrate-from-psp.md

[ja] Translated content/ja/docs/tasks/configure-pod-container/migrate-from-psp.md
recreated from #48952
Translate
content/en/docs/tasks/configure-pod-container/migrate-from-psp.md
into Japanese
content/ja/docs/tasks/configure-pod-container/migrate-from-psp.md
This PR contains several translation proposal for following terms:
| original | first experimental translation  | current proposal |
| --- | --- |--- |
| Validating Admission Controller | 検証型のアドミッションコントローラー | Validating Admission Controller |
| Mutating Admission Controller |  改変型のアドミッションコントローラー | Mutating Admission Controller |
| mutating field | Podを改変する設定 | Podを変更する設定 | 
| Pod Security Standard |Podセキュリティ基準  | Podセキュリティ基準 | 
Also the format fixation is contained to suite the translation style guide. 
* (Validation|Mutating) …

[ja] Translated content/ja/docs/tasks/configure-pod-container/migrate-from-psp.md

---

content/en/docs/concepts/cluster-administration/addons.md

Fixed hyperlink for core dns helm charts on the page https://kubernetes.io/docs/concepts/cluster-administration/addons/
https://github.com/kubernetes/website/issues/49208
Closes: #
https://github.com/kubernetes/website/issues/49208

Fixed link for core dns helm charts

---

content/en/docs/concepts/cluster-administration/addons.md

Since Weavework has been closed (#45482) its URL mentioned  has been removed from docs.
Issue: #47421

Removed weavework-scope url from the doc

---

content/en/docs/concepts/storage/volumes.md
content/en/docs/reference/command-line-tools-reference/feature-gates/CSIMigrationPortworx.md

This PR updates the doc for Portworx CSI migration feature moving to stable in 1.33 release.
https://github.com/kubernetes/enhancements/issues/2589
k/k - https://github.com/kubernetes/kubernetes/pull/129297
KEP Update - https://github.com/kubernetes/enhancements/pull/5011

Update doc for Portworx CSI migration moving to stable

---

layouts/partials/scripts.html

Add the missing code to load the splitter library.
Fixup for PR #48350
/priority critical-urgent

fix: reinstate splitter

---

content/en/docs/reference/using-api/client-libraries.md

Adds [CloudCoil](https://github.com/cloudcoil/cloudcoil) - Production-ready Python client for Kubernetes with async support

Add cloudcoil to client libraries

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md

Removes `tcpSocket` from the container lifecycle hooks page because "TCPSocket is NOT supported as a LifecycleHandler" as [mentioned in api reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#lifecyclehandler-v1-core). Also the `tcpSocket` is not mentioned on this documentation page except for this case.

Mark tcpSocket Pod lifecycle handler as deprecated

---

content/ja/docs/reference/glossary/rbac.md

Sync `content/ja/docs/reference/glossary/rbac.md` with the English upstream.
- English upstream:
- URL: https://kubernetes.io/docs/reference/glossary/?all=true#term-rbac
- File: https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/rbac.md

[ja] Sync reference/glossary/rbac.md

---

content/en/docs/concepts/workloads/autoscaling.md

Replace the '2.13' version on the keda.sh docs with the 'latest' alias.

Update keda/scalers/cron URL to 'latest' to prevent outdated references 

---

content/en/docs/contribute/new-content/open-a-pr.md

Section "Preview your changes locally" at https://kubernetes.io/docs/contribute/new-content/open-a-pr/#preview-locally .
There is a lack of a step about the required initiation before `make container-serve` . 
When you perform the steps according to the document:
https://kubernetes.io/docs/contribute/new-content/open-a-pr/#preview-locally ,
you get the following error:
```
~/w/tool/kdoc-ws$ git clone https://github.com/kubernetes/website website-tmp
~/w/tool/kdoc-ws$ cd website-tmp
~/w/tool/kdoc-ws/website-tmp$ make container-image
~/w/tool/kdoc-ws/website-tmp$ make container-serve
WARNING Submodule not initialized: api-ref-generator
You need to run make module-init to initialize missing modules first
make: *** [Makefile:41: module-check] Error 1
```
This step is required:
``` …
```

Fix missing command for local container preview

---

content/en/docs/concepts/services-networking/dns-pod-service.md

related to https://github.com/kubernetes/dns/issues/633

fix: clarify that certain Pod A records are only available with CoreDNS

---

content/en/docs/reference/access-authn-authz/mutating-admission-policy.md
content/en/docs/reference/access-authn-authz/validating-admission-policy.md

Certain resources are (by design) exempt from being targeted by `ValidatingAdmissionPolicy` and `MutatingAdmissionPolicy`. Unfortunately there is no clear documentation in the [KEP-3488](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3488-cel-admission-control) nor in the official Kubernetes docs which resources are affected by this exemption.
This MR extends the documentation to mention these resources in the official docs. I think this helps other users in the future to not waste a lot of time (like I did) to figure out which resources are exempt.
Im not sure if this is the right approach but I think it is better than no documentation at all. See also these issues/PRs for reference:
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machi …

docs: extend VAP docs with exempt resources

---

content/en/docs/reference/access-authn-authz/rbac.md
content/en/examples/access/simple-clusterrole.yaml
content/en/examples/access/simple-role.yaml

Enable copying Role and ClusterRole snippets.  
This feature allows users to easily copy content, which is especially helpful during certification exams. (I found this beneficial while taking mock exams.)

Enable copying role and clusterRole snippets

---

content/en/docs/concepts/workloads/controllers/deployment.md

fix a small inconsistency.
one of the code blocks for a command output has a different color (red).
this is because it is a code block of type 'ini', 
but it should not be.

fix: code block typo in deployment.md

---

content/ja/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md

Both `ja` and `zh-cn` have the wrong link for Bob Killen on the 2024-06-06 blog post "10 Years of Kubernetes". This PR fixes `ja`.
See also #49611

[ja] Fix link typo for mrbobbytables

---

package-lock.json
package.json

This PR changes the docsy dependency to the 0.6.x branch of Docsy which removed `hugo-extended` from its dependencies. This ensures that `hugo-extended` is not installed.
Closes: #49460

fix: use docsy dependency without hugo-extended

---

content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md

This PR updates the description of TopologySpreadConstraints's `matchLabelKeys` to align with the design change by https://github.com/kubernetes/kubernetes/pull/129874.
This also includes the [deprecation notice](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades#the-update-to-labels-specified-at-matchlabelkeys-isnt-supported) related to `matchLabelKeys`.
related: 
- [KEP-3243 he update to labels specified at matchLabelKeys isn't supported](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades#the-update-to-labels-specified-at-matchlabelkeys-isnt-supported)
- https://github.com/kubernetes/kubernetes/pull/129874
- …

Update the description of TopologySpreadConstraints's matchLabelKeys to align with the design change

---

content/pt-br/docs/tasks/debug/_index.md

Esse PR traz a localização da página https://kubernetes.io/docs/tasks/debug/ para PT-BR. Adicionado a raiz de `/content/pt-br/docs/tasks/debug` o arquivo `_index.md`, ficando localizado como `/content/pt-br/docs/tasks/debug/_index.md` no repositório.
---
This PR introduces the localization of the page https://kubernetes.io/docs/tasks/debug/ to PT-BR. The file `_index.md` has been added to the root of `/content/pt-br/docs/tasks/debug`, and it will be located as `/content/pt-br/docs/tasks/debug/_index.md` in the repository.
Closes: #49466

[pt-br] Localize tasks/debug/_index.md

---

content/pt-br/docs/tasks/debug/debug-application/_index.md

Esse PR traz a localização da página https://kubernetes.io/docs/tasks/debug/debug-application/ para **PT-BR**. 
Adicionado a raiz de `content/en/docs/tasks/debug/debug-application/` o arquivo `_index.md`, ficando localizado como `content/en/docs/tasks/debug/debug-application/_index.md` no repositório.
---
This PR brings the localization of the page https://kubernetes.io/docs/tasks/debug/debug-application/ to **PT-BR**.  
The `_index.md` file was added to the root of `content/en/docs/tasks/debug/debug-application/`, making it located as `content/pt-br/docs/tasks/debug/debug-application/_index.md` in the repository. 
Closes: #49557

Localize content/pt-br/docs/tasks/debug/debug-application/_index.md

---

content/en/docs/tasks/administer-cluster/cpu-management-policies.md

Fix header levels in CPU Management article: https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/
After the brief intro, pretty much the whole article appears to be about Windows Support. There is nothing in it about CPU management policies on Linux. Presumably it is just an error with the headers.

Fix header nesting in cpu-management-policies.md

---

assets/scss/_custom.scss
content/en/_index.html
layouts/index.html
layouts/partials/hooks/head-end.html
layouts/shortcodes/kubeweekly.html

Turn it into a shortcode [[preview](https://deploy-preview-48258--kubernetes-io-main-staging.netlify.app/#kubeweekly)]
~I have done limited testing. If you want to approve this but are concerned about testing it, hold the PR before you approve. I will then unhold when I have time to test the live site post-merge.~
---
Intended to help with issue https://github.com/kubernetes/website/issues/41171

Refactor KubeWeekly signup form

---

content/zh-cn/docs/concepts/workloads/controllers/deployment.md

the same as in english documentation #49600 .
fix a small inconsistency.
one of the code blocks for a command output has a different color (red).
this is because it is a code block of type 'ini',
but it should not be.

[zh-cn] fix: code block typo in deployment.md

---

content/zh-cn/blog/_posts/2024-06-06-10-Years-of-Kubernetes/index.md

Both `ja` and `zh-cn` have the wrong link for Bob Killen on the 2024-06-06 blog post "10 Years of Kubernetes". This PR fixes `zh-cn`.
See also #49603

[zh-cn] Fix link typo for mrbobbytables

---

content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md

Sync with en #49507 
```
```
See [preview](https://deploy-preview-49516--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/service-accounts-admin/#verifying-and-inspecting-private-claims)

[zh] Sync service-accounts-admin.md

---

README.md
content/en/docs/contribute/new-content/open-a-pr.md

This PR updates the Kubernetes contributor documentation regarding the local setup for building and previewing the website. The current instructions are outdated due to recent changes in the Docsy theme and the build process. The steps for installing dependencies and building the site locally have been updated to reflect the new, correct process.
Changes:
Revise instructions for installing the Docsy theme.
Update the README to include the correct steps for setting up the project.
Clarify the build process using npm ci and make serve to preview changes locally.
This update ensures that contributors can successfully follow the steps for local development and avoid issues caused by the previous setup instructions.
Closes: #49627

Update the Website Setup Instructions in Contributor Docs and README

---

content/en/docs/contribute/style/diagram-guide.md

there was no closing quotation mark in the caption attribute :
```
caption="Figure 4. Kubernetes Architecture Components >}}
```

fix: typo in diagram-guide.md

---

assets/scss/_custom.scss

I think this may have been a recent regression.
It makes https://k8s.io/search/?q=Kubernetes look right. [[Preview](https://deploy-preview-49630--kubernetes-io-main-staging.netlify.app/search/?q=Kubernetes)]

Fix incorrect width for search page

---

assets/scss/case_studies.scss
layouts/case-studies/single.html
static/css/gridpage.css

This PR iterates on yesterday's #49587 to improve CSS styles for case studies. Mainly, it fixes two issues:
1. Makes the featured case study (with video) two-columned: a quote on the left and a video on the right (the size of the YouTube embed now allows us to watch it). That's what we will see:
2. Helps to avoid this situation with two narrow text descriptions on smaller screens like it's shown below:
It also includes a tiny fix for a single case study page (font colour and extra space for the title).
P.S. It still leaves room for improvement for the mobile view since @Arhell wanted to handle that.

Improve the  styles for case studies' pages

---

content/en/docs/contribute/style/style-guide.md
layouts/partials/scripts.html

Per https://www.docsy.dev/docs/adding-content/diagrams-and-formulae/#latex-support-with-katex we can have formulae using $`\text{K\kern-.23em{\small a}TeX}`$. Make it so, and document this in the style guide.
[Preview](https://deploy-preview-49592--kubernetes-io-main-staging.netlify.app/docs/contribute/style/style-guide/#formulae-and-equations)

Add support for KaTeX formulas

---

assets/js/detect-js.js
layouts/partials/hooks/body-end.html
static/js/script.js

Moves the script which detects if js is enabled in the browser to its own module. Its also imported separately into the `body-end` hook.
Intended to help with #41171 

feat: move js detection script to its own module and import into body-end

---

content/en/docs/reference/access-authn-authz/admission-controllers.md
content/en/docs/tasks/administer-cluster/change-default-storage-class.md

fixes this [issue](https://github.com/kubernetes/website/issues/42288)
Closes: #42288

fix inconsistency in documentation of default storageclass

---

content/en/blog/_posts/2025-02-28-nftables-kube-proxy/index.md

Updates the nftables GA blog post (#49393) to remove `draft: true`.
/hold
1. I picked the current date at random. Needs a real date.
2. I need to make sure everything actually renders correctly... it didn't show up in the netlify preview before, I guess because it was still draft?

Publish nftables GA blog post

---

content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

Update the concept page at https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ (yes, it's in the Tasks section - see https://github.com/kubernetes/website/issues/4493) to use math style formulae, per https://kubernetes.io/docs/contribute/style/style-guide/#formulae-and-equations
[Preview](https://deploy-preview-49718--kubernetes-io-main-staging.netlify.app/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details)

Use math formulae in HPA task page

---

content/en/docs/reference/access-authn-authz/rbac.md
content/en/examples/access/simple-clusterrolebinding.yaml
content/en/examples/access/simple-rolebinding-with-clusterrole.yaml
content/en/examples/access/simple-rolebinding-with-role.yaml
content/en/examples/controllers/job.yaml

Make RoleBinding examples easily copyable to help during certificate examinations and
an additional white line removal at the end of the file.

docs(style): embed rolebinding code samples

---

content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md
content/en/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md

AIUI, this list of per-item reviewers is stale; drop it and let SIG Docs handle reviews here.
/kind cleanup
@davidopp, @wojtek-t, @piosz, @filipg FYI

Drop stale reviewers for Pod priority pages

---

content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/en/examples/pods/inject/dapi-envars-container.yaml
content/en/examples/pods/inject/dapi-envars-pod.yaml
content/en/examples/pods/inject/dapi-volume-resources.yaml
content/en/examples/pods/inject/dapi-volume.yaml
content/en/examples/pods/pod-configmap-env-var-valueFrom.yaml
content/en/examples/pods/pod-configmap-envFrom.yaml
content/en/examples/pods/pod-configmap-volume-specific-key.yaml
content/en/examples/pods/pod-configmap-volume.yaml
content/en/examples/pods/pod-multiple-configmap-env-variable.yaml
content/en/examples/pods/pod-single-configmap-env-variable.yaml
content/en/examples/pods/probe/exec-liveness.yaml

fixes this https://github.com/kubernetes/website/issues/49406
Updating the tag for `registry.k8s.io/busybox` from `latest` to `1.27.2`.
When using the `registry.k8s.io/busybox` image with the `latest` tag to create a workload, the workload is stuck in `ImagePullBackOff` with the error.
```
Failed to pull image "registry.k8s.io/busybox": Error response from daemon: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of registry.k8s.io/busybox:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2.
```
Issue
Closes: https://github.com/kubernetes/website/issues/49406

update image tag in manifest

---

OWNERS_ALIASES

We've been using the [maintainer's tool](https://github.com/kubernetes-sigs/maintainers) to clean up the OWNERS_ALIASES file for k/website annually. With this exercise, we aim to keep the file updated and hope to foster healthy community leadership within SIG Docs. The results of running the tool this year have been provided below.
If you wish to continue as an approver, reviewer, or localization owner, please confirm your intent on this PR by **2nd February 2025**
- We recognize that GitHub isn't the only way to contribute and are seeking confirmation of your intent to continue as an approver/reviewer for the next year based on your bandwidth. 
- While we understand that localisations have a different volume of contributors and contributions, the respective approvers & reviewers are …

Annual updation of OWNERS_ALIASES

---

content/ja/docs/concepts/cluster-administration/addons.md

[ja] Fixed link for core dns helm charts

---

content/ja/docs/tasks/extend-kubernetes/_index.md
content/ja/docs/tasks/extend-kubernetes/configure-multiple-schedulers.md
content/ja/examples/admin/sched/clusterrole.yaml
content/ja/examples/admin/sched/my-scheduler.yaml
content/ja/examples/admin/sched/pod1.yaml
content/ja/examples/admin/sched/pod2.yaml
content/ja/examples/admin/sched/pod3.yaml

**Description**
- Translate [Configure Multiple Schedulers](https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/) into Japanese.
- Copied the latest version of example codes from [en].
- Also translate [Extend Kubernetes](https://kubernetes.io/docs/tasks/extend-kubernetes/) into Japanese.
**Issue**
- Closes: #49579

[ja] Translate content/en/docs/tasks/extend-kubernetes/configure-multiple-schedulers.md into Japanese

---

content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md

Updated extensible admission controller page **Request* example to `Json` from `yaml`

Switch extensible admission payload example from YAML to JSON

---

data/releases/eol.yaml
data/releases/schedule.yaml

Update the schedule for the february releases and mark 1.29 EOL.
Refers to https://github.com/kubernetes/sig-release/issues/2724, https://github.com/kubernetes/sig-release/issues/2725, https://github.com/kubernetes/sig-release/issues/2726, https://github.com/kubernetes/sig-release/issues/2727
cc @kubernetes/release-managers

Update release schedule

---

content/en/docs/reference/kubectl/kubectl.md

This PR adds new environment variable into the docs for https://github.com/kubernetes/enhancements/issues/3104 which is revival of https://github.com/kubernetes/website/pull/48402 in 1.33.

Add KUBECTL_KUBERC environment variable description

---

content/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md

[zh-cn]sync configure-liveness-readiness-startup-probes.md

---

content/en/docs/concepts/architecture/nodes.md
content/en/docs/reference/labels-annotations-taints/_index.md

Updated node roles in docs

---

content/en/docs/tutorials/configuration/updating-configuration-via-a-configmap.md

The subsection "Update configuration via a ConfigMap in a Pod possessing a sidecar container" contains the sentence:
> Please see [Enabling sidecar containers](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#enabling-sidecar-containers) to utilize this feature.
The sidecar-containers page doesn't have a subsection on enabling sidecar containers, so I navigated the link to example showing deployment having sidecar config.
Closes: #49326

Fixed link navigation bug

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

This change documents the promotion of kubeadm's ControlPlaneKubeletLocalMode feature gate to beta. 
/hold not sure if I should change the chinese version or if it is generated in some way or needs a separate PR to separate branch.
Part of:
- https://github.com/kubernetes/enhancements/issues/4471
Note: the following PR should merge first:
- https://github.com/kubernetes/kubernetes/pull/129716

kubeadm: Document ControlPlaneKubeletLocalMode promotion to beta

---

content/en/docs/concepts/scheduling-eviction/assign-pod-node.md

Add deprecation notices related to PodAffinity's `matchLabelKeys`/`mismatchLabelKeys`.
related:
- [KEP-3633 Introduce MatchLabelKeys and MismatchLabelKeys to PodAffinity and PodAntiAffinity](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3633-matchlabelkeys-to-podaffinity) 
- [KEP-3243 he update to labels specified at matchLabelKeys isn't supported](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3243-respect-pod-topology-spread-after-rolling-upgrades#the-update-to-labels-specified-at-matchlabelkeys-isnt-supported)
- https://github.com/kubernetes/kubernetes/issues/129480#issuecomment-2599513823
This notification was found when we discussed about PodTopologySpread's `matchLabelKeys`.([#129480](https://github.com/kubernetes/kubernetes/is …

Add deprecation notices related to PodAffinity's matchLabelKeys/mismatchLabelKeys

---

content/en/docs/concepts/architecture/cloud-controller.md

While trying to clean up stray references to Endpoints in the docs, I found this seemingly very confusing cloud-controller documentation that claims that the cloud controller updates Endpoints objects. I don't think this has ever been true?

Fix some confused cloud-controller documentation

---

content/es/docs/concepts/cluster-administration/addons.md

[es] Fixed link for core dns helm charts

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md

Use a formula (per [style guide](https://kubernetes.io/docs/contribute/style/style-guide/#formulae-and-equations)) in the Pod lifecycle concept page
[Original](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-startup-probe) vs [preview](https://deploy-preview-49796--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-startup-probe)

Pod lifecycle concept: use formula for clearer math

---

content/en/docs/concepts/workloads/autoscaling.md

Fix a typo in the autoscaling docs: this part is about VPA, the Vertical Pod Autoscaler, not HPA, like in the previous section.

Fix typo in autoscaling docs

---

content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

Added ceil function in the desired replicas Algorithm
The kubernetes documentation had a ceil function added in the desired replicas Algorithm and recently a PR "https://github.com/kubernetes/website/pull/49719" was created to update the math style formulae. In doing so, the ceil function was also removed. Hence, I have created this PR to update the same.
Closes: #

Fix formula in HPA page

---

content/en/docs/reference/glossary/device-plugin.md

There was an extra space within the Pod tag of `content/en/docs/reference/glossary/device-plugin.md`
On the website it seems to be missing an extra space in the device-plugin.md
Looking at the file, I'm assuming this is due to the extra space in the pod tag. Please correct me if I'm wrong
Link: https://kubernetes.io/docs/reference/glossary/?fundamental=true
go to device plugin
Closes: #

extra space in pod tag

---

content/en/docs/concepts/storage/volumes.md

- fix some grammar issues
- indent consistenly in bullets
/kind cleanup
See [preview](https://deploy-preview-49833--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/volumes/)

Clean up storage/volumes.md

---

content/en/docs/reference/kubectl/conventions.md
content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning.md
content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md

Updates kubectl subresource documentation
Ref: https://github.com/kubernetes/enhancements/issues/2590
/assign @ardaguclu

Update kubectl subresource documentation

---

content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md

Webhooks can cause deadlocks in several ways, expand the list to cover more subtle cases.
Was recently debugging an issue where this came up and I thought, perhaps I can improve the docs to call out more cases.  Not sure we've got the root cause of the issue correct yet but I can't see why it wouldn't be possible to cause deadlocks in these ways (and I think I was seeing these problems in a customer cluster).

Add more suggestions for avoiding deadlocks to webhook docs

---

content/en/docs/reference/glossary/api-resource.md
content/en/docs/reference/glossary/infrastructure-resource.md
content/en/docs/reference/glossary/object.md

Add a definitions of 'API resource' and 'resource (infrastructure)' to the glossary. As the term "resource" is frequently used in the docs, the Kubernetes API itself, and in the community (but not actually defined).
Inspiration / definitions taken from:
https://kubernetes.io/docs/reference/using-api/api-concepts/#standard-api-terminology
https://stackoverflow.com/questions/52309496/difference-between-kubernetes-objects-and-resources
https://datatracker.ietf.org/doc/html/rfc7231#section-2
https://en.wikipedia.org/wiki/System_resource
Closes: https://github.com/kubernetes/website/issues/25903

Define 'resource' in glossary

---

content/en/docs/concepts/workloads/controllers/deployment.md

This PR adds a new note about deployment cleanup policy.
See https://kubernetes.slack.com/archives/C18NZM5K9/p1740135413167499 for more context.
There are some cases when number of ReplicaSets associated with a deployment might get higher than `.spec.revisionHistoryLimit`. These cases are not documented very well.

Add note about deployment cleanup policy

---

content/ja/docs/concepts/containers/container-lifecycle-hooks.md

Description
Sync [content/ja/docs/concepts/containers/container-lifecycle-hooks.md](https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/containers/container-lifecycle-hooks.md) with the content in [en](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/containers/container-lifecycle-hooks.md).
Issue
Closes: #49850 
---
/language ja
/assign

[ja] content/ja/docs/concepts/containers/container-lifecycle-hooks.md follow of the en text

---

content/zh-cn/docs/tutorials/configuration/updating-configuration-via-a-configmap.md

content/zh-cn/docs/tutorials/configuration/updating-configuration-via-a-configmap.md

[zh-cn]sync updating-configuration-via-a-configmap

---

content/en/docs/reference/kubectl/jsonpath.md

* Add headings
* Avoid consecutive callouts (note directly after a note)
* Add a caption to the table
* Misc. small alignments to docs style guide
[preview](https://deploy-preview-49874--kubernetes-io-main-staging.netlify.app//docs/reference/kubectl/jsonpath/)
/language en

Improve JSONPath reference

---

data/i18n/en/en.toml

This PR adds "LinkedIn" to the Community page that is currently missing.
Before | After
--- | --
Closes: #

Added "LinkedIn" to en.toml

---

assets/scss/_documentation.scss
assets/scss/_variables_project.scss

Adapt the existing styles for the docs section, to align more closely with how Docsy does it.
Helps with #41171
[Preview](https://deploy-preview-49825--kubernetes-io-main-staging.netlify.app/docs/home)

Use Docsy-like styling for documentation

---

content/en/docs/contribute/review/reviewing-prs.md

it seems that there is an error with the indentation of two list items.
after the sentence :
```
- We are willing to mirror any blog article that was published to https://kubernetes.dev/blog/ (the contributor blog) provided that:
```
the three next points refer to that sentence,
so they should have the same indentation,
but the first one is not indented and it is the same level as the main sentence.
the second error is about the sentence starting with :
```
- You should set the canonical URL for the mirrored article, to the URL of the original article
```
it looks like it refers to the main sentence, but it seems it should not.
---
EDIT: 2025-02-14
it seems that it is:
```
- AAA
- BBB
- CCC
- DDD1
- DDD2
- DDD3
- EEE
- FFF
```
but should be:
```
- AAA
- BBB
- CCC
- DDD1
- DDD2
- DDD3
- …
```

fix: indentation for list items in reviewing-prs.md

---

content/zh-cn/docs/reference/access-authn-authz/admission-control-phases.svg
content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md

Sync with en #43836 
```
```
See [preview](https://deploy-preview-49876--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/admission-controllers/#admission-control-phases)

[zh] Add a diagram to admission-controllers.md

---

content/zh-cn/README.md

This is a revert action. Apologies for my mistake in removing a zh-maintainer, @chenrui333, in #49712.
He has been actively reviewing PRs and making significant contributions to k/website in recent years:
https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Achenrui333

[zh] Update on-duty maintainers list in readme

---

content/bn/docs/concepts/security/_index.md

According to the issue #49916 I have updated the old link with the new link.

Update VMware security link

---

content/en/docs/concepts/workloads/autoscaling.md

I was going through the docs, and found this mistake here:
This PR changes it to "KEDA is a CNCF-graduated project enabling..."
Closes #49934

Fix grammar in "Autoscaling Workloads" page

---

content/en/docs/reference/instrumentation/slis.md
content/en/docs/reference/instrumentation/zpages.md

**Description**
Add descriptions for Kubernetes Component SLI Metrics and z-pages as they are only missing ones.
**Issue**
Closes: [#48959](https://github.com/kubernetes/website/issues/48959)
**Additional**
This PR is addition to [#49295](https://github.com/kubernetes/website/pull/49295). Because, this one also includes description for z-pages.

Add description for Kubernetes Component SLI Metrics and z-pages

---

content/en/docs/concepts/cluster-administration/node-shutdown.md

Hello!
I was just reading the documentation and noticed that there's probably a misuse of the word 'administers', where we should be using the word 'administrators' instead, to be more coherent with the rest of the documentation.

Update node-shutdown docs: typo in word 'administrators'

---

content/zh-cn/docs/reference/labels-annotations-taints/_index.md

[zh-cn]sync labels-annotations-taints/_index.md

---

content/en/docs/tasks/debug/debug-cluster/crictl.md

This PR removed `Map docker CLI commands to crictl` hyperlink from the [What's next](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#what-s-next) section of [Debugging Kubernetes nodes with crictl](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/) task.
Closes: #49979

Remove broken hyperlink

---

content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
content/zh-cn/docs/reference/instrumentation/slis.md

content/zh-cn/docs/reference/instrumentation/slis.md

[zh-cn]sync pod-lifecycle slis

---

content/en/docs/concepts/storage/volumes.md
content/en/docs/reference/command-line-tools-reference/feature-gates/KubeletFineGrainedAuthz.md

Update the documentation for gitRepo volumes to highlight that the gitRepo volume plugin has been disabled by default.
xref: https://github.com/kubernetes/enhancements/issues/5040

KEP-5040: Disable git_repo volume driver.

---

content/pt-br/docs/tasks/access-application-cluster/web-ui-dashboard.md

This pull request includes the complete translation of the "web-ui-dashboard.md" document from English to Portuguese. 
The translation covers all sections of the document, including the introduction, implementation instructions, dashboard access, and details on using the Kubernetes Dashboard. 
The translation aims to facilitate access and understanding of the and is linked to the issue **[pt-br] Localize docs/tasks/access-application-cluster/web-ui-dashboard/ (https://github.com/kubernetes/website/issues/46782).**
cc  @edsoncelio, @stormqueen1990

[pt-br] Add docs/tasks/access-application-cluster/web-ui-dashboard

---

content/pt-br/docs/tasks/debug/debug-application/debug-service.md

Esse PR traz a localização da página https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/ para **PT-BR**.
Adicionado a raiz de `content/pt-br/docs/tasks/debug/debug-application/` o arquivo `debug-service.md`, ficando localizado como `content/pt-br/docs/tasks/debug/debug-application/debug-service.md` no repositório.
---
This PR brings the localization of the page https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/ to **PT-BR**.  
Added to the root of `content/pt-br/docs/tasks/debug/debug-application/` the file `debug-service.md`, which is now located at `content/pt-br/docs/tasks/debug/debug-application/debug-service.md` in the repository.
Closes: #49559

[pt-br] Add tasks/debug/debug-application/debug-service

---

content/pl/docs/reference/glossary/cloud-controller-manager.md
content/pl/docs/reference/glossary/etcd.md
content/pl/docs/reference/glossary/kube-apiserver.md

fix a minor typo in the directory: docs/reference/glossary

[pl] fix: typo in docs/reference/glossary

---

i18n/en/en.toml

The `parentoptions` heading is missing from the locale string file. The result is that in the command reference pages, the second table has no heading. It is weird to see two tables on the same page without this heading text.

Fix locale string configuration for parentoptions

---

content/en/training/_index.html

Removes duplicate element IDs in the training page.
Closes: #50010

fix: duplicate element ID in training page

---

content/ja/docs/tasks/access-application-cluster/ingress-minikube.md

This pull request is to remove the remaining part of Katacoda from [content/ja/docs/tasks/access-application-cluster/ingress-minikube.md](https://github.com/kubernetes/website/blob/main/content/ja/docs/tasks/access-application-cluster/ingress-minikube.md).

[ja] Remove the remaining part of Katacoda from content/ja/docs/tasks/access-application-cluster/ingress-minikube.md

---

content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

Description
This pull request fixes a typo in the Kubernetes Japanese documentation on creating a cluster with Kubeadm. The command kubectl init was incorrectly referenced and has been corrected to kubeadm init in the section on allowing non-root users to run kubectl.
```
$ kubectl init
error: unknown command "init" for "kubectl"
Did you mean this?
edit
wait
```
You can view the relevant page here: [kubeadmを使用したクラスターの作成 | Kubernetes](https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#%E8%A9%B3%E7%B4%B0%E3%81%AA%E6%83%85%E5%A0%B1)
Issue
This PR addresses a minor typo in the documentation that could lead to confusion for users following the setup instructions.
Closes: #

Fix typo in kubeadm documentation: Corrected `kubectl init` to `kubeadm init`

---

content/pl/docs/contribute/style/page-content-types.md

[pl] docs/contribute/style/page-content-types.md

---

content/en/includes/task-tutorial-prereqs.md

I would like to propose a new playground to be added: KodeKloud Kubernetes Playgrounds. It's an open playground, supporting multiple versions of kubernetes to try out, and no Sign Ups needed too. Making learning quick.
Closes: #49978

add new playground to kubernetes documentation

---

content/ko/docs/concepts/workloads/pods/_index.md

[ko] Update _index.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/RecursiveReadOnlyMounts.md

Promote the `RecursiveReadOnlyMounts` feature gate to GA
Depends on:
- kubernetes/kubernetes#130116
NONE

KEP-3857: Recursive Read-only (RRO) mounts: promote to GA

---

content/en/blog/_posts/2025-03-24-swap-fresh-improvements.md

Releases the blog post "Kubernetes 1.32: Fresh Swap Features for Linux Users" that was introduced here https://github.com/kubernetes/website/pull/48099
cc @sftim @iholder101

Release blog post: Swap fresh improvements

---

content/pt-br/docs/tasks/debug/debug-application/debug-statefulset.md

Esse PR traz a localização da página  https://kubernetes.io/docs/tasks/debug/debug-application/debug-statefulset/ para **PT-BR**.
Adicionado a raiz de `content/pt-br/docs/tasks/debug/debug-application/` o arquivo `debug-statefulset.md`, ficando localizado como `content/pt-br/docs/tasks/debug/debug-application/debug-statefulset.md` no repositório.
---
This PR brings the localization of the page https://kubernetes.io/docs/tasks/debug/debug-application/debug-statefulset/ to **PT-BR**.  
The file `debug-statefulset.md` was added to the root of `content/pt-br/docs/tasks/debug/debug-application/`, making it located as `content/pt-br/docs/tasks/debug/debug-application/debug-statefulset.md` in the repository.
Closes: #49699

[pt-br] Add /tasks/debug/debug-application/debug-statefulset.md

---

content/en/docs/concepts/storage/volumes.md

Simple fix to small typo in first sentence of the page.
Before: 
"Kubernetes volumes provide a way for containers in a `pods` to access[...]"
After: 
"Kubernetes volumes provide a way for containers in a `pod` to access[...]"

Fix typo in volumes.md

---

content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md

Remove the Fedora and CentOS (i.e. epel) install section from kompose as the package have been orphaned for over 2 years.
See [this commit](https://src.fedoraproject.org/rpms/kompose/c/8afab6b0014862b81ffa30f9ee87d4b8192fdf3f?branch=rawhide) for more details.
The docs pointed users to install non-existing packages.

Remove Fedora and CentOS packages for kompose

---

content/en/_index.html
layouts/index.html

This PR creates a way to move the search bar in the homepage from the content html file to the layout. This reduces code duplication as a shortcode is used in the homepage file for every language.
It checks if a page calls the search bar shortcode and if it does, it emits a warning during build time. This gives localisation teams enough information and the resolution to convert all homepages to remove the shortcode. Once the shortcode is removed, the search bar in the layout is automatically removed.
This check must be removed once all localized home pages have removed the shortcode.
Closes: #50031

Move the search bar in the homepage from the content to the layout

---

content/en/docs/reference/access-authn-authz/authentication.md

follow-up to https://github.com/kubernetes/kubernetes/pull/130875
/sig auth
/assign enj liggitt
/cc @benjaminapetersen

fix doc for email_verified requirement when username contains `claims.email`

---

content/en/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/storage/volumes.md

Delete removed volume types from feature support lists. Also align documentation for azurefile and vsphere with the other csi migrated types.
Closes: #

Delete removed volume types from feature support list

---

content/en/docs/reference/command-line-tools-reference/feature-gates/KubeletCrashLoopBackOffMax.md

This PR amends the feature gate description for configuring the maximum loop backoff delay in kubelet.

Clarify how to config maximum loopback off delay

---

content/zh-cn/docs/contribute/_index.md

- Add one missing paragraph
- Fix the link syntax (was invalid due to full-width period `。`)
- Improve some wording
(The file is already synced as `lsync.sh` said)
Current Page: https://kubernetes.io/zh-cn/docs/contribute/
Netlify Preview: https://deploy-preview-50152--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/

[zh] fix contribute/_index.md

---

content/pl/docs/contribute/style/page-content-types.md

the polish synchronization with PR #49643

[pl] sync with PR #49643

---

layouts/index.html
layouts/shortcodes/kubeweekly.html

Currently, the "[View past newsletters](https://us10.campaign-archive.com/home/?u=3885586f8f1175194017967d6&id=11c1b8bcb2)" link on the main page leads to an old Mailchimp page listing really outdated KubeWeekly issues. The latest issue available there is KubeWeekly 257 (dated 04/02/2021).
I found the full and up-to-date KubeWeekly archive on the [CNCF website](https://www.cncf.io/kubeweekly/) and suggest using this link instead.

Fix KubeWeekly archive link

---

content/en/blog/_posts/2025-03-24-kubernetes-1.33-sneak-peek.md

Add `2025-03-24-kubernetes-1.33-sneak-peek.md`
Preview link: https://deploy-preview-50111--kubernetes-io-main-staging.netlify.app/blog/2025/03/24/kubernetes-v1-33-upcoming-changes/

Kubernetes v1.33 Mid Cycle Sneak Peek Blog

---

content/pl/docs/contribute/new-content/new-features.md

[pl] docs/contribute/new-content/new-features.md

---

content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md

Reverts kubernetes/website#49607
Since [this feature](https://github.com/kubernetes/kubernetes/pull/129874) have not meet the v1.33 code freeze, I've reverted this PR.
I'll submit new PR for next release cycle.

Revert "Update the description of TopologySpreadConstraints's matchLabelKeys to align with the design change"

---

content/en/blog/_posts/2025-03-24-kubernetes-1.33-sneak-peek.md
content/en/blog/_posts/2025-03-25-swap-fresh-improvements.md

/area blog
Release Comms had hoped to publish a mid-cycle blog article on the 24th of March 2025, so defer the other article already scheduled for that day.
Relevant to
- PR https://github.com/kubernetes/website/pull/50111 and PR https://github.com/kubernetes/website/pull/50163 
- PR https://github.com/kubernetes/website/pull/48099 and PR https://github.com/kubernetes/website/pull/50071

Defer clashing blog article about swap

---

assets/scss/_documentation.scss

The fix involves removing the SCSS which "hid" the element. Moreover, the sidebars no longer have the `#m-docs` HTML ID anywhere as the HTML element bearing that ID in Docsy is removed from the overriden `sidebar-tree.html` template.
Closes: #50132 
Before -> After

Fix for `(EN)` not appearing in docs sidebar for i18nised site

---

content/en/docs/reference/using-api/server-side-apply.md

Since JSON messages are valid YAML, the request body for a server-side apply request (`application/apply-patch+yaml` content type) can be in either JSON or YAML.
Example:
```
kubectl create deploy nginx --image nginx --replicas 1
cat <<EOF | curl  -XPATCH -H 'content-type: application/apply-patch+yaml' \
'http://localhost:8001/apis/apps/v1/namespaces/default/deployments/nginx?fieldManager=test&force=true' \
--data-binary @-
{
"apiVersion": "apps/v1",
"kind": "Deployment",
"spec": {
"replicas": 2
}
}
EOF
cat <<EOF | curl  -XPATCH -H 'content-type: application/apply-patch+yaml' \
'http://localhost:8001/apis/apps/v1/namespaces/default/deployments/nginx?fieldManager=test&force=true' \
--data-binary @-
apiVersion: apps/v1
kind: Deployment
spec:
replicas: 1
EOF
```

SSA request bodies can include either JSON or YAML

---

content/en/docs/reference/command-line-tools-reference/feature-gates/SupplementalGroupsPolicy.md
content/en/docs/tasks/configure-pod-container/security-context.md

This PR updates a user-facing document for https://github.com/kubernetes/enhancements/issues/3619 in [Configure a Security Context for a Pod or Container](https://deploy-preview-46920--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/security-context/)
- bump the feature gate information to beta
- adds the behavioral change(pod rejection when the pod uses `Strict` policy and get scheduled to a node that does NOT support this feature) introduced in beta release in notes. 
https://deploy-preview-49880--kubernetes-io-main-staging.netlify.app/docs/tasks/configure-pod-container/security-context/
For
- https://github.com/kubernetes/enhancements/issues/3619
Depends on:
- k/k
- https://github.com/kubernetes/kubernetes/pull/130210

[dev-1.33] KEP-3619: Promote Fine-grained SupplementalGroups control to Beta

---

content/fr/_index.html

[fr] Removed site-searchbar

---

content/vi/_index.html

[vi] Removed site-searchbar 

---

content/ja/_index.html

[ja] Removed site-searchbar

---

content/ja/docs/concepts/workloads/pods/ephemeral-containers.md

Updated https://kubernetes.io/ja/docs/concepts/workloads/pods/ephemeral-containers/ to the latest version.
Closes: #50106

[ja] Update concepts/workloads/pods/ephemeral-containers to follow the upstream

---

content/uk/_index.html

[uk] Removed site-searchbar 

---

content/es/_index.html

[es] Removed site-searchbar

---

content/en/blog/_posts/2025-03-24-kubernetes-1.33-sneak-peek.md

The new schedule is 26th March rather than 24th March.

Delay Kubernetes v1.33 mid cycle blog release

---

content/pt-br/_index.html

[pt-br] Removed site-searchbar 

---

content/en/docs/concepts/policy/node-resource-managers.md
content/en/docs/tasks/administer-cluster/cpu-management-policies.md

Documentation update for Beta graduation of KEP-2902
https://github.com/kubernetes/enhancements/issues/2902
Closes: #

node: KEP- 2902: Docs update for Beta graduation

---

content/id/_index.html

[id] Removed site-searchbar

---

content/en/docs/reference/command-line-tools-reference/feature-gates/NFTablesProxyMode.md

update `NFTablesProxyMode` feature gate info for 1.33
I wasn't sure if I was supposed to remove the line:
```
{{< feature-state feature_gate_name="NFTablesProxyMode" >}}
```
from `content/en/docs/reference/networking/virtual-ips.md` or not?
Also, the existing note
```
As of Kubernetes {{< skew currentVersion >}}, the `nftables` mode is
still relatively new, and may not be compatible with all network
plugins; consult the documentation for your network plugin.
```
still seems true for now, so I didn't remove it.
https://github.com/kubernetes/enhancements/issues/3866

KEP-3866 nftables kube-proxy to GA

---

content/bn/_index.html

[bn] Removed site-searchbar

---

content/en/docs/concepts/storage/persistent-volumes.md

Though this is not explicitly stated, it seems acceptable that
once a provider builds a filesystem on top of a block device,
some writeable capacity is lost:
https://github.com/container-storage-interface/spec/issues/338
Closes: #

Add a note about filesystem overhead for PVC size request

---

content/en/docs/contribute/localization.md
i18n/en/en.toml
layouts/partials/search-input-custom.html

This PR replaces the old translation placeholder key `ui_search_placeholder` with the newer placeholder [`ui_search`](https://github.com/google/docsy/blob/de445c7305ec72c29c262f5d032864b5cba34af5/i18n/en.toml#L12). This was only possible after #49643 was closed as without the changes in that PR, using the same placeholder key as Docsy would not override Docsy's value.
But now, this change works.
This is a technical change and *should* not impact localisation but if needed, I can update this PR only for english and let other languages do their own updates.

Replace `ui_search_placeholder` with docsy provided `ui_search`

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

@sttts helpfully [explained what this means a few years ago](https://kubernetes.slack.com/archives/C0EG7JC6T/p1618822249257400). But re-reading this today after 4 years I was just as clueless about what this means as I was the first time. This is a good sign that this paragraph should be expanded.

Clarify pruning of defaults

---

i18n/pt-br/pt-br.toml

[pt-br] Renamed search placeholder

---

i18n/hi/hi.toml

[hi] Renamed search placeholder

---

i18n/ja/ja.toml

[ja] Renamed search placeholder

---

content/en/docs/concepts/architecture/self-healing.md

This PR introduces a new page under [Kubernetes Architecture](https://kubernetes.io/docs/concepts/architecture/) to explain Kubernetes' self-healing capabilities. 
The page provides an overview of how Kubernetes automatically recovers from failures.
- Explains key self-healing mechanisms, including Pod restarts, replica replacement, node failover, and storage recovery 
- Lists Kubernetes components involved in self-healing 
Closes: https://github.com/kubernetes/website/issues/48963

Add new page for self-healing

---

i18n/uk/uk.toml

[uk] Renamed search placeholder

---

content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md

Using stable API `kubescheduler.config.k8s.io/v1` instead of beta API  `kubescheduler.config.k8s.io/v1beta3`.
We should not use beta API when it is graduated to stable.
For your convenience: https://github.com/search?q=repo%3Akubernetes%2Fwebsite+path%3Acontent%2Fen%2Fdocs%2F+kubescheduler.config.k8s.io%2Fv1beta3&type=code
The following page is not included:
https://kubernetes.io/docs/concepts/scheduling-eviction/scheduler-perf-tuning/
(Reason: this page is outdated and should be edited via another PR, while this PR only includes some small changes.)
Closes: #50240

Update API version from `kubescheduler.config.k8s.io/v1beta3` to `kubescheduler.config.k8s.io/v1`

---

content/zh-cn/docs/contribute/localization.md
i18n/zh-cn/zh-cn.toml

This is a housekeeping PR following the merge of #50049 which renames `ui_search_placeholder` localisation key by the Docsy provided `ui_search`. It also updates the documentation to reflect this change.

[zh-cn] Renamed search placeholder

---

i18n/id/id.toml

[id] Renamed search placeholder

---

content/en/docs/concepts/workloads/controllers/deployment.md
content/en/docs/concepts/workloads/controllers/replicaset.md
content/en/docs/reference/command-line-tools-reference/feature-gates/deployment-pod-replacement-policy.md

Document .status.terminatingReplicas enabled by DeploymentPodReplacementPolicy feature (replaces https://github.com/kubernetes/website/pull/48370)
- https://github.com/kubernetes/kubernetes/pull/128546
- https://github.com/kubernetes/enhancements/issues/3973

[KEP-3973]: document .status.terminatingReplicas enabled by DeploymentPodReplacementPolicy feature

---

content/id/docs/concepts/services-networking/gateway.md

Localize gateway page to Bahasa Indonesia. English reference: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/services-networking/gateway.md

[id] Localize gateway page to Bahasa Indonesia

---

content/en/docs/concepts/workloads/pods/user-namespaces.md

@vinayakankugoyal raised some questions about volumes usage and this PR aims to clarify that
cc @giuseppe 
Closes: #

userns: Clarify volume usage

---

content/en/docs/concepts/workloads/controllers/job.md
content/en/docs/reference/command-line-tools-reference/feature-gates/JobBackoffLimitPerIndex.md
content/en/docs/tasks/job/pod-failure-policy.md
content/en/examples/controllers/job-backoff-limit-per-index-failindex.yaml

Update the documentation as we are promoting JobBackoffLimitPerIndex to stable in 1.33.
The code changes are already merged in PR: https://github.com/kubernetes/kubernetes/pull/130061
Also proposing to extend the documentation of the tasks page for handling BackoffLimitPerIndex, as proposed in the KEP's [graduation criteria](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3850-backoff-limits-per-index-for-indexed-jobs#ga): "Revisit extending the hands-on guide for Pod failure policy to use FailIndex".
Enhancement-tracking issue: https://github.com/kubernetes/enhancements/issues/3850

Docs update as we promote JobBackoffLimitPerIndex to stable

---

i18n/de/de.toml

[de] Renamed search placeholder

---

content/en/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
content/en/docs/concepts/extend-kubernetes/api-extension/declarative-validation.md
content/en/docs/reference/using-api/declarative-validation.md

PR related to docs changes necessary for KEP 5073.  This PR adds documentation to address comments here:
https://github.com/kubernetes/website/pull/49732#issuecomment-2754125146
related to PR: https://github.com/kubernetes/website/pull/49732
KEP Issue: https://github.com/kubernetes/enhancements/issues/5073
KEP PR: https://github.com/kubernetes/enhancements/pull/5074
KEP Implementation PRs:
- Migrate to declarative validation - ReplicationController spec.replicas and spec.minReadySeconds fields: https://github.com/kubernetes/kubernetes/pull/130725
- Enable Declarative Validation for ReplicationController: https://github.com/kubernetes/kubernetes/pull/130724
- add declarative validation metrics and associated runtime verification tests: https://github.com/kubernetes/kubernetes/pull/130705
- …

docs: add new declarative validation doc page and link to it

---

i18n/bn/bn.toml

[bn] Renamed search placeholder

---

content/en/docs/reference/command-line-tools-reference/feature-gates/SELinuxChangePolicy.md
content/en/docs/reference/command-line-tools-reference/feature-gates/SELinuxMount.md
content/en/docs/tasks/configure-pod-container/security-context.md

Document how SELinux feature gates (now beta) work together and potential actions needed before they graduate to GA.
Goals:
* Ensure non-SELinux users that nothing changes for them (= vast majority of users / cluster admins can just ignore all SELinux feature gates).
* Warn users / cluster admins / Kubernetes vendors that use SELinux about potentially breaking changes in a future release. Provide a clear way how to check if they're safe or they need to change anything. This is important to ensure smooth update.
* OpenShift stats show that ~ 1.3% of all clusters would have at least one affected Pod, most of them with just handful of them. Some clusters (~0.3%) have more than 100 affected Pods and may need some work before the breaking upgrade when `SELinuxMount` goes GA + locked. Data …

Announce improved SELinux volume relabelling beta

---

content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

- removed redundant spaces from two markdown tables
- sync with en text
- add minor changes about newline char and bullets indentation
```
```

[zh] sync custom-resource-definitions.md

---

content/en/docs/reference/access-authn-authz/kubelet-authn-authz.md

This PR updates the description about the kubelet fine-grained API authorization.
According to the upstream implementation (https://github.com/kubernetes/kubernetes/pull/126347), the fine-grained authorization doesn't include `nodes/spec`.
The previous docs didn't mention that the builtin clusterrole exists and will get updated.

Mention the builtin clusterrole in kubelet authorization

---

i18n/vi/vi.toml

[vi] Renamed search placeholder

---

content/en/docs/concepts/storage/volumes.md
content/en/docs/reference/command-line-tools-reference/feature-gates/ImageVolume.md
content/en/docs/tasks/configure-pod-container/image-volumes.md
content/en/examples/pods/image-volumes-subpath.yaml

Update the documentation to reflect the graduated feature.
Refers to https://github.com/kubernetes/enhancements/issues/4639
https://deploy-preview-49936--kubernetes-io-main-staging.netlify.app/docs/concepts/storage/volumes/#image
https://deploy-preview-49936--kubernetes-io-main-staging.netlify.app//docs/tasks/configure-pod-container/image-volumes

[KEP-4639] Graduate image volume source to beta

---

content/ja/blog/_posts/2024-05-21-sig-node-spotlight/index.md

Fixes the image rendering issue in the Japanese version of the blog post
[`SIG Node Spotlight 2024`](https://kubernetes.io/ja/blog/2024/06/20/sig-node-spotlight-2024/).
The current image path is:
```markdown
```
However, the image file is located in the same directory as index.md, so the correct relative path should be:
```
```
This PR updates the Markdown file to use the correct relative path so that the image renders properly. The English version already uses the correct format and displays correctly.
Closes: #50326

[ja] Fix broken image in SIG Node Spotlight 2024 blog post due to incorrect path

---

i18n/pl/pl.toml

[pl] Renamed search placeholder

---

content/en/docs/concepts/workloads/pods/user-namespaces.md

Kubernetes v1.33 will support setting `userNamespaces.idsPerPod` in `KubeletConfiguration`.
Depends on:
- kubernetes/kubernetes#130028
Closes: NONE

user-namespaces: add idsPerPod configuration

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md
content/en/docs/reference/command-line-tools-reference/feature-gates/PodLifecycleSleepActionAllowZero.md

Docs changes for [KEP 4818: Allow zero value for Sleep Action of PreStop Hook](https://github.com/kubernetes/enhancements/issues/4818) beta graduation. 
Related PRs
- Enhancements PR for beta graduation: https://github.com/kubernetes/enhancements/pull/5139
Closes: nil, part of https://github.com/kubernetes/enhancements/issues/4818

KEP 4818: PodLifecycleSleepActionAllowZero beta graduation

---

content/en/docs/concepts/workloads/pods/_index.md
content/en/docs/reference/command-line-tools-reference/feature-gates/SidecarContainers.md

ref to https://github.com/kubernetes/enhancements/issues/753
- https://github.com/kubernetes/kubernetes/pull/129731 was merged to promote the feature gate.

update SidecarContainers to stable in v1.33

---

content/en/docs/reference/command-line-tools-reference/feature-gates/DeclarativeValidation.md
content/en/docs/reference/command-line-tools-reference/feature-gates/DeclarativeValidationTakeover.md

PR related to docs changes necessary for KEP 5073
KEP Issue: https://github.com/kubernetes/enhancements/issues/5073
KEP PR: https://github.com/kubernetes/enhancements/pull/5074
KEP Implementation PRs:
- Migrate to declarative validation - ReplicationController spec.replicas and spec.minReadySeconds fields: https://github.com/kubernetes/kubernetes/pull/130725
- Enable Declarative Validation for ReplicationController: https://github.com/kubernetes/kubernetes/pull/130724
- add declarative validation metrics and associated runtime verification tests: https://github.com/kubernetes/kubernetes/pull/130705
- Add default + optional handling: https://github.com/kubernetes/kubernetes/pull/130706
- add Add CoveredByDeclarative to field error struct: …

docs: add necessary feature gate information for KEP-5073 - Declarative Validation of K8s Native Types With validation-gen

---

content/en/docs/reference/command-line-tools-reference/feature-gates/KubeletServiceAccountTokenForCredentialProviders.md
content/en/docs/tasks/administer-cluster/kubelet-credential-provider.md

Doc update for KEP 4412: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
KEP issue: https://github.com/kubernetes/enhancements/issues/4412

Add docs for PSAT for Kubelet Image Credential Providers alpha

---

content/en/docs/reference/node/node-labels.md

Fixed broken link for kubernetes.io/hostname label in "Node Labels Populated By The Kubelet" page
Closes: #50385

Fix broken link in "Node Labels Populated By The Kubelet" page

---

content/en/docs/concepts/policy/node-resource-managers.md
content/en/docs/tasks/administer-cluster/cpu-management-policies.md

Documentation update for the KEP-2625 GA graduation
Closes: https://github.com/kubernetes/enhancements/issues/2625
k/k code changes:
- https://github.com/kubernetes/kubernetes/pull/129950
- https://github.com/kubernetes/kubernetes/pull/130535
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2625-cpumanager-policies-thread-placement/README.md

KEP-2625: cpumanager full-pcpus-only becomes GA

---

content/en/docs/reference/kubectl/jsonpath.md

When using JSONPath, it's more likely to apply the feature to a specific pod (or deployment, or ingress) than generically with `get pods`. Yet, when switching from `get pods` to `get pod/pod1` the JSONPath examples break. Therefore it seems worthwhile to show a couple examples with `get pod/pod1` also.

JSONPath example

---

content/en/docs/reference/command-line-tools-reference/feature-gates/HPAConfigurableTolerance.md
content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

This PR updates the documentation to describe the Workload Autoscaling _configurable tolerance_ feature.
* KEP-4951 PR: https://github.com/kubernetes/enhancements/issues/4951
* k/k PR: https://github.com/kubernetes/kubernetes/pull/130797
* Blog post: https://github.com/kubernetes/website/pull/50000
* Issue: https://github.com/kubernetes/enhancements/issues/4951

Add documentation for configurable autoscaling tolerance.

---

content/en/docs/concepts/workloads/controllers/deployment.md
content/en/docs/concepts/workloads/controllers/replicaset.md
content/en/docs/reference/command-line-tools-reference/feature-gates/deployment-pod-replacement-policy.md

React to last minute changes in the feature gate name once https://github.com/kubernetes/kubernetes/pull/131088 merges.
- https://github.com/kubernetes/kubernetes/pull/128546
- https://github.com/kubernetes/enhancements/issues/3973
- https://github.com/kubernetes/kubernetes/pull/131088

[KEP-3973]: update the DeploymentPodReplacementPolicy FG references to DeploymentReplicaSetTerminatingReplicas

---

OWNERS_ALIASES

Description
Adds @raelga to to sig-docs-es reviewer and owner aliases as discussed in the weekly meeting.
/cc @electrocucaracha
/cc @krol3

cfg: update sig docs es owners aliases

---

content/ko/_index.html

[ko] Removed site-searchbar 

---

content/pl/docs/contribute/generate-ref-docs/prerequisites-ref-docs.md

[pl] docs/contribute/generate-ref-docs/prerequisites-ref-docs.md

---

content/en/docs/concepts/storage/storage-limits.md
content/en/docs/reference/command-line-tools-reference/feature-gates/MutableCSINodeAllocatableCount.md

Add docs for KEP-4876: Mutable CSINode Allocatable Property.
https://github.com/kubernetes/enhancements/issues/4876

Add docs for KEP-4876: Mutable CSINode Allocatable Property

---

content/en/docs/concepts/scheduling-eviction/scheduling-framework.md
content/en/docs/reference/command-line-tools-reference/feature-gates/StorageCapacityScoring.md
content/en/docs/reference/command-line-tools-reference/feature-gates/VolumeCapacityPriority.md
content/en/docs/reference/scheduling/config.md

This PR updates existing documentation to include the addition of the StorageCapacityScoring feature gate of KEP-4049  as an alpha version.
- https://github.com/kubernetes/enhancements/issues/4049

KEP-4049: Add StorageCapacityScoring feature gate documents

---

content/pl/docs/contribute/generate-ref-docs/kubectl.md
content/pl/docs/contribute/generate-ref-docs/prerequisites-ref-docs.md
content/pl/includes/index.md

[pl] docs/contribute/generate-ref-docs/kubectl.md

---

content/en/docs/reference/command-line-tools-reference/feature-gates/StrictIPCIDRValidation.md

I don't think we need any further documentation for 1.33, beyond the release note which will be added by https://github.com/kubernetes/kubernetes/pull/128786.

KEP-4858: Add StrictIPCIDRValidation feature gate file

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md
content/en/docs/concepts/workloads/pods/pod-lifecycle.md
content/en/docs/reference/command-line-tools-reference/feature-gates/ContainerStopSignals.md

Docs for [KEP 4960: Container Stop Signals](https://github.com/kubernetes/enhancements/issues/4960). 
Related PRs
- Enhancements PR: https://github.com/kubernetes/enhancements/pull/5122
Closes: nil, part of https://github.com/kubernetes/enhancements/issues/4960

KEP 4960: Container Stop Signals

---

content/en/docs/reference/command-line-tools-reference/feature-gates/SchedulerPopFromBackoffQ.md

Add SchedulerPopFromBackoffQ feature gate to docs.
kubernetes/enhancements/issues/5142

KEP-5142: Add SchedulerPopFromBackoffQ feature gate docs

---

content/en/docs/concepts/cluster-administration/system-metrics.md
content/en/docs/reference/command-line-tools-reference/feature-gates/KubeletPSI.md
content/en/docs/reference/instrumentation/node-metrics.md
content/en/docs/reference/node/kernel-version-requirements.md

KEP-4205: update for alpha release in 1.33

---

content/en/docs/concepts/services-networking/windows-networking.md

Add documentation for WinDSR / WinOverlay kube-proxy functionality.
https://github.com/kubernetes/enhancements/issues/5100
Closes: #
/sig windows network
/milestone v1.33

Website updates for WinDSR / WinOverlay v1.33 beta

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md
content/en/docs/reference/command-line-tools-reference/feature-gates/ReduceDefaultCrashLoopBackOffDecay.md

Docs changes for alpha feature ReduceDefaultCrashLoopBackOffDecay to CrashLoopBackoff behavior per [KEP-4603](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4603-tune-crashloopbackoff)
kubernetes/enhancements: https://github.com/kubernetes/enhancements/issues/4603
kubernetes/kubernetes PRs:
- https://github.com/kubernetes/kubernetes/pull/130711

KEP-4603: Docs for feature behind ReduceDefaultCrashLoopBackoffDecay feature gate

---

content/en/docs/concepts/cluster-administration/system-metrics.md
content/en/docs/reference/instrumentation/node-metrics.md

A followup of https://github.com/kubernetes/website/pull/49895. PSI requires cgroup v2. 
Ref: 
- https://github.com/kubernetes/enhancements/issues/4205
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4205-psi-metric/README.md
/assign @tengqm @kannon92 @haircommander

Add cgroup v2 to PSI requirements

---

content/en/docs/concepts/windows/intro.md

Windows hostNetwork support is being withdrawn from alpha in v.133 release and this PR updates k/website acordingly
https://github.com/kubernetes/enhancements/issues/3503
Closes: #
/sig windows network

Removing docs for Windows hostNetwork support for v1.33

---

content/zh-cn/docs/tutorials/cluster-management/namespaces-walkthrough.md

Follow en #49125 
```
content/zh-cn/docs/tutorials/cluster-management/namespaces-walkthrough.md
```

[zh] Move 'Namespaces Walkthrough' to tutorials section

---

content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
content/en/docs/reference/command-line-tools-reference/feature-gates/DRADeviceTaints.md

Related-to: https://github.com/kubernetes/enhancements/issues/5055

DRA: device taints and tolerations

---

content/en/docs/reference/command-line-tools-reference/feature-gates/AppArmor.md

k/k: https://github.com/kubernetes/kubernetes/pull/129375
/hold

mark AppArmor as removed

---

i18n/es/es.toml

[es] Renamed search placeholder

---

i18n/ko/ko.toml

[ko] Renamed search placeholder

---

content/zh-cn/docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/cluster-trust-bundle-v1alpha1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/service-account-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/token-request-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/token-review-v1.md

[zh-cn] sync kubernetes-api/authentication-resources/*

---

data/releases/schedule.yaml

This PR adds 1.33 to the releases schedule for the 1.33.0 release.
/milestone 1.33
cc: @npolshakova @dipesh-rawat @chanieljdan @katcosgrove @kubernetes/release-managers

Add 1.33 to the release schedule for 1.33 release

---

content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/replica-set-v1.md

Added 
```
- **ignoreStoreReadErrorWithClusterBreakingPotential** (*in query*): boolean
<a href="{{< ref "../common-parameters/common-parameters#ignoreStoreReadErrorWithClusterBreakingPotential" >}}">ignoreStoreReadErrorWithClusterBreakingPotential</a>
```
to:
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/replica-set-v1.md
```
and removed some blank lines.

[zh] Sync workload-resources/cron-job-v1, daemon-set-v1, replica-set-v1

---

content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md

Sync with en text and fix some format issues like:
in 
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md
```

[zh] Sync config-and-storage-resources/persistent-volume-claim-v1.md

---

content/en/docs/concepts/workloads/controllers/job.md

Clarify the defaulting of the backoffLimit field, as the current description is not accurate. 
This was discussed in https://github.com/kubernetes/website/pull/49982#discussion_r2036953030

Improve Job docs by clarifying defaulting of backoffLimit field

---

Makefile

The flag now mirrors the build-preview setup. This would allow having the preview for draft blogs.
Ref: https://gohugo.io/methods/page/draft/

Include drafts in preview deploy

---

layouts/partials/blog-sidebar-tree.html
layouts/partials/blog-sidebar.html

This PR reworks how the sidebar for the blogs is laid out. The main goal is to bring the layout as close as possible to the `sidebar-tree.html` provided by Docsy. To do that, the first important thing was to change the existing `blog-sidebar.html` to be the same as `sidebar.html` from Docsy, apart from calling the newly created `blog-sidebar-tree.html`. Since the layout itself calls the partials `blog-sidebar`, no changes to the layout are necessary.
The newly created `blog-sidebar-tree.html` is a reworked version of what was present in `blog-sidebar.html`. The rework targets to achieve a UX similar to the sidebar present in the docs pages, which includes collapsible menu items and proper caching. The changes include the following:
- The `$sidebarCacheLimit` and `$shouldDelayActive` now …

Rework blog sidebar to align to how Docsy sidebars are implemented

---

layouts/_default/search.html
layouts/index.html
layouts/shortcodes/site-searchbar.html

This PR removes the `site-searchbar` shortcode following the merge of #50040.
But this PR can't be merged unless the following are merged.
- #50185
- #50186
- #50187
- #50188
- #50189
- #50190
- #50191
- #50192
- #50193
- #50194
- #50195
- #50196
- ~~#50197~~#50207
Closes #50147

Remove the site-searchbar shortcode

---

layouts/partials/search-input-custom.html

This PR removes the workaround created to handle some localisations not handling the Docsy i18n key for search following the merge of #50049.
But this PR can't be merged unless he following are merged.
- #50247
- #50248
- #50249
- #50250
- #50251
- #50252
- #50253
- #50254
- #50255
- #50256
- #50257
- #50258
- #50259
- #50260
- #50261

Remove the search placeholder workaround

---

content/en/docs/tasks/configure-pod-container/configure-persistent-volume-storage.md
content/en/examples/pods/storage/nginx.conf
content/en/examples/pods/storage/pv-duplicate.yaml

This PR improves the explanation of this section titled "Mounting the same persistentVolume in two places" in the [Configure a Pod to Use a PersistentVolume for Storage](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#mounting-the-same-persistentvolume-in-two-places) page.
1. I used the existing PV and PVC in this example.
2. I created a new `nginx.conf` file to show the file referenced in the pods manifest.
3. I explained why a `subPath` is used.
Closes: #43293 and #49119

Improve PV Storage Task

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Document kubeadm OS version requirement.
https://github.com/kubernetes/kubeadm/issues/3177
Closes: https://github.com/kubernetes/kubeadm/issues/3177

Document kubeadm OS version requirement

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

The `||` was misinterpreted as table cell boundary and ruined the markup.
According to [this SO answer](https://stackoverflow.com/a/17320389/1407369) this can be worked around with an entity, but then need to use `<code>` for formatting.
Before:
After:

fix: escape pipe symbol in a table

---

OWNERS_ALIASES

I'd like to re-apply for sig-docs-ko-owners & sig-docs-ko-reviews role.
I had sig-docs-ko-owners & sig-docs-ko-reviews roles by 2023 (I was removed through https://github.com/kubernetes/website/pull/43975 ).
After stabilizing some personal status through 2024 (moving job position), I would like to re-apply for the roles to facilitate Korean L10n progress.
Thank you for the discussion @seokho-son , and appreciate so much in advance if you are supportive on this PR.
It aligns with https://github.com/kubernetes/org/pull/5374 PR on kubernetes/org repo.
Note that I've met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):

Add ianychoi to sig-docs-ko-owners & sig-docs-ko-reviews 

---

content/en/blog/_posts/XXXX-XX-XX-in-place-pod-resize-beta.md

In-place pod resize (`InPlacePodVerticalScaling`) is planning to graduate to beta in v1.33 (still at risk to get all the changes merged). If it makes it, it's a big feature that deserves a dedicated blogpost.
For https://github.com/kubernetes/enhancements/issues/1287

Add in-Place pod resize beta blog post

---

content/en/docs/reference/labels-annotations-taints/_index.md

@adrianmoisey suggested in https://github.com/kubernetes/kubernetes/pull/130564#issuecomment-2701315382 that I should document the new label, even though it's really only intended for internal use, because people might see it and want to know more.
The label is new in 1.33 so this PR is against `dev-1.33` but if it's too late to make it into the 1.33 docs, it can just wait until post-release and I'll rebase to `main`. (I didn't add anything about "since 1.33" because none of the other entries do that...)

Document endpoints.kubernetes.io/managed-by

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md

Simple fix to small typo -  "CRS" to "CSR" in kubeadm-join.md
Before: 
"This would change the **CRS** resource to Active state."
After: 
"This would change the **CSR** resource to Active state."

Fix typo in kubeadm-join.md

---

content/en/docs/contribute/blog/submission.md

Made small change to fix the link in https://kubernetes.io/docs/contribute/blog/article-submission

Fix broken link in "Submitting Articles to Kubernetes Blogs" page

---

content/en/releases/release-managers.md

Remove the link to GitHub @kubernetes/release-engineering page in Release Managers docs. This means to team mention (as text), should not provide link to prevent misleading.
NONE

Remove link to Release Engineering teams page on GitHub in Release Managers docs

---

content/en/examples/policy/service-cluster-cidr-address-range.yaml

This PR adds an example manifest named `service-cluster-cidr-address-range.yaml` in `content/en/examples/policy/` so that it can be referred in the 1.33 Release Note that was added as part of this PR: https://github.com/kubernetes/kubernetes/pull/128971. Which will be getting added via the Final Release Notes PR: https://github.com/kubernetes/sig-release/pull/2762
/milestone 1.33
@LMKTFY @npolshakova

Add service-cluster-cidr-address-range.yaml as an example to simplify 1.33 release note

---

content/en/docs/reference/command-line-tools-reference/feature-gates/WatchList.md

Since https://github.com/kubernetes/kubernetes/pull/131359 disabled the WatchList feature in 1.33, this updates the docs to match.
Closes: #

update WatchList feature default to false for 1.33

---

content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md

Fix an api extension typo to x-kubernetes-list-map-keys

---

content/pl/docs/contribute/generate-ref-docs/kubernetes-components.md

[pl] docs/contribute/generate-ref-docs/kubernetes-components.md

---

OWNERS_ALIASES

Remove archived account of sftim from Docs owners, as this account should no longer be used
cc. sig docs leads: @divya-mohan0209 @reylejano @salaxander @tengqm @katcosgrove 
FYI: @lmktfy

remove archived account of sftim from docs owners

---

content/en/blog/_posts/2025-XX-XX-endpoints-deprecation.md

Blog post about the deprecation of the Endpoints API in 1.33 (https://github.com/kubernetes/enhancements/issues/4974)
Kind of trails off at the end. I think it still needs some sort of conclusion.
Feel free to steal wording for the mid cycle deprecation blog post.

KEP-4974 endpoints deprecation blog post for 1.33

---

content/en/examples/pods/image-volumes-subpath.yaml
content/en/examples/pods/image-volumes.yaml

Use the `v2` version of the artifact to allow compatibility with containerd.
/cc @kubernetes/sig-node-pr-reviews @mikebrow

[dev-1.33] Update image volume example to use `v2`

---

content/en/docs/concepts/policy/resource-quotas.md
content/en/examples/policy/gold-vac-pvc.yaml
content/en/examples/policy/quota-vac.yaml

k/k: https://github.com/kubernetes/kubernetes/pull/124360
/hold

Resource Quota Per VolumeAttributesClass

---

hugo.toml

This PR updates the hugo.toml for v1.32 ahead of the v1.33 release.
Base branch will be updated from main to release-1.32 once that branch exists.
/hold for v1.33 release day

Updates v1.32 hugo.toml for release v1.33

---

content/en/docs/reference/using-api/cel.md

The markdown tables have too many constraints for no good reason.
Using HTML tables directly would be more appropriate.

Rework CEL page to use HTML table rather than Markdown table

---

content/id/docs/reference/issues-security/security.md

https://kubernetes.io/security must route to the EN docs.
fixes https://github.com/kubernetes/website/issues/50656

Fix incorrect /security alias

---

content/en/blog/_posts/2025-03-01-Container-Stop-Signals.md

This PR is a placeholder for the blog post announcing https://github.com/kubernetes/enhancements/issues/4960, container stop signals.
Blog post for https://github.com/kubernetes/enhancements/issues/4960

v1.33 release blog post for KEP 4960 (Container Stop Signals) and KEP 4818 (Allow zero for pod lifecycle sleep action)

---

layouts/partials/hooks/body-end.html

It no longer works, so drop it. Only stale localized pages still use this shortcode.
See https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/ and discussion https://github.com/kubernetes/website/discussions/38878
Replacement for PR https://github.com/kubernetes/website/pull/50283
/kind cleanup

Drop div used for Katacoda button

---

content/en/docs/concepts/architecture/self-healing.md
content/en/docs/concepts/workloads/controllers/replicaset.md

- Move where landing page self-healing refers to [[preview](https://deploy-preview-50263--kubernetes-io-main-staging.netlify.app/)]
- Add a note for localizers
Replaces PR https://github.com/kubernetes/website/pull/50263
/kind cleanup

Switch target of landing page "self-healing" feature

---

content/en/blog/_posts/2025-05-02-dra-133-updates.md
content/en/blog/_posts/2025-05-02-kubernetes-v1-33-dra-updates.md

This schedules [DRA Updates in v1.33 blog](https://github.com/kubernetes/website/pull/49993 ) for publication on Friday, 2nd May, 2025.

Revise DRA Updates blog and schedule for publication

---

content/en/blog/_posts/2024-12-17-api-streaming/index.md

The streaming collection encoders appear more efficient, don't require client changes, and avoid much complexity. The more technical reasons are listed in the disablement PR: https://github.com/kubernetes/kubernetes/pull/131359
Closes: #

Update the streaming list blog to reflect disablement in 1.33

---

content/en/blog/_posts/2025-05-01-storage-capacity-scoring.md

This schedules https://github.com/kubernetes/website/pull/49992 for publication on Thursday, 1st May, 2025.

KEP-4049: Updated slug, removed draft status and updated publish date

---

content/en/_index.html

Since KubeCon Europe 2025 has passed, it's time to update the events list on the main page. I think we can not only remove the old event but also feature the next KubeCon Europe (2026 in Amsterdam) already? If others think it's too early, please let me know.

Update KubeCon 2025 events after KubeCon EU

---

content/zh-cn/blog/_posts/2025-04-23-storage-capacity-scoring.md

content/zh-cn/blog/_posts/2025-04-23-storage-capacity-scoring.md

[zh-cn]Add blog 2025-04-23-storage-capacity-scoring

---

content/en/blog/_posts/2025-04-30-mutable-csi-node-allocatable.md

Blog for KEP 4876 Mutable CSI CSINode Allocatable
Closes: # https://github.com/kubernetes/enhancements/issues/4876

sig-storage: Blog for KEP 4876 Mutable CSI CSINode Allocatable

---

content/en/blog/_posts/2025-04-24-endpoints-deprecation.md

This seems to be the convention we used to use for the previous cycles. I will document in the handbook about how the future Feature Blogs should be created with correct front matter to begin with (including `draft: true`)

Ensure to add v1.33 prefix for title

---

content/en/blog/_posts/2025-05-08-volume-populators-ga/index.md

Blog post for volume populator GA, waiting for https://github.com/kubernetes/kubernetes/pull/129770
https://github.com/kubernetes/website/issues/49541 
Closes: #
/hold

Add Blog Post for Volume Populator GA

---

content/en/blog/_posts/2025-05-02-mutable-csi-node-allocatable.md
content/en/blog/_posts/2025-05-08-volume-populators-ga/index.md
content/en/blog/_posts/2025-05-15-Container-Stop-Signals.md

This includes the following KEPs:
- KEP-4876: For Friday, 2nd May ([original blog PR](https://github.com/kubernetes/website/pull/50016))
- KEP-1495: For Thursday, 8th May ([original blog PR](https://github.com/kubernetes/website/pull/49542))
- KEP-4960: For Thursday, 15th May ([original blog PR](https://github.com/kubernetes/website/pull/49967))

Schedule Feature Blogs for publication

---

content/en/blog/_posts/2025-05-05-Honor-Persistent-Volume-Reclaim-Policy-Graduate-to-GA.md

This schedules https://github.com/kubernetes/website/pull/49948 for publication on Monday, 5th May, 2025.

Schedule KEP-2644 blog for publication

---

content/en/docs/reference/access-authn-authz/validating-admission-policy.md
content/en/examples/validatingadmissionpolicy/binding-with-param-prod.yaml
content/en/examples/validatingadmissionpolicy/binding-with-param.yaml

This pull request updates the Kubernetes documentation for Validating Admission Policies to include details about the `parameterNotFoundAction` field in `ValidatingAdmissionPolicyBinding`. 
- Added a detailed explanation of the `parameterNotFoundAction` field to the `paramRef` section in `validating-admission-policy.md`, describing its purpose, allowed values (`Allow` and `Deny`), and behavior.
- Updated YAML examples (`binding-with-param.yaml` and `binding-with-param-prod.yaml`) to include the `parameterNotFoundAction` field, ensuring consistency with the API requirements.
- Clarified the importance of setting `parameterNotFoundAction` for policy bindings that use parameter resources.
- Highlighted how the field interacts with scenarios where parameters are missing.
This change addresses …

Include parameterNotFoundAction in Validating Admission Policy documentation

---

content/en/blog/_posts/2025-05-07-kubernetes-1-33-wi-for-image-pulls.md

Following the same convention as other to have `Kubernetes v1.33:` in the title. Also changed the publication date based on [this project view](https://github.com/orgs/kubernetes/projects/200/views/5). The PR is still marked as `draft: true`.
follow-up PR based on https://github.com/kubernetes/website/pull/49924#issuecomment-2844360182

KEP-4412: update blog to add v1.33 prefix for title

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md

This PR updates documentation about readiness probes to explicitly state that pods that are being terminating (i.e. `.metadata.deletionTimestamp` is set) still have `Ready` condition `"True"` and `.status.Phase == "Running"`. I kept the exiting text, but looking at
1.  https://github.com/kubernetes/kubernetes/blob/f64b651ebae643d422f4625161dc415970e2c166/pkg/kubelet/prober/prober_manager.go#L298 and https://github.com/kubernetes/kubernetes/blob/f64b651ebae643d422f4625161dc415970e2c166/pkg/kubelet/prober/prober_manager.go#L339 
2. https://github.com/kubernetes/kubernetes/blob/f64b651ebae643d422f4625161dc415970e2c166/pkg/kubelet/prober/worker.go#L259
I'd say that ~~liveness~~ READINESS probes are processed the same way no matter is the pod is terminating or not. Please advice if we should …

Update readiness probe docs to match observed behaviour

---

content/pl/docs/contribute/analytics.md

[pl] docs/contribute/analytics.md

---

content/en/docs/contribute/participate/pr-wranglers.md

Since Brad is no longer the point of contact for coming up with the PR Wrangling schedule, I am removing his name from the official website to avoid confusion for newer contributors.
cc: @natalisucks @reylejano

Removing Brad Topol's name from the PR Wrangler contact

---

content/zh-cn/docs/concepts/architecture/self-healing.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md

sync
`
content/zh-cn/docs/concepts/architecture/self-healing.md
`
`content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
`
`content/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration.md`

[zh-cn] Sync self-healing node-pressure-eviction taint-and-toleration

---

content/en/blog/_posts/XXXX-XX-XX-fine-grained-supplementalgroups-control-beta/index.md

Schedule KEP-3619 blog for publication on May 6th. Removing the `draft` flag and adding publication date.

Schedule KEP-3619 blog for publication

---

content/en/blog/_posts/2025-04-23-jobs-backofflimitperindex-goes-ga.md

Blog Post for graduating Job's Backoff Limit Per Index to GA.
Tracking enhancement issue: https://github.com/kubernetes/enhancements/issues/3850

BlogPost: Job's Backoff Limit Per Index Goes GA

---

content/en/docs/reference/command-line-tools-reference/feature-gates/BtreeWatchCache.md
content/en/docs/reference/command-line-tools-reference/feature-gates/CPUManagerPolicyOptions.md
content/en/docs/reference/command-line-tools-reference/feature-gates/DisableNodeKubeProxyVersion.md
content/en/docs/reference/command-line-tools-reference/feature-gates/HonorPVReclaimPolicy.md
content/en/docs/reference/command-line-tools-reference/feature-gates/InPlacePodVerticalScalingAllocatedStatus.md
content/en/docs/reference/command-line-tools-reference/feature-gates/JobBackoffLimitPerIndex.md
content/en/docs/reference/command-line-tools-reference/feature-gates/JobSuccessPolicy.md
content/en/docs/reference/command-line-tools-reference/feature-gates/MatchLabelKeysInPodAffinity.md
content/en/docs/reference/command-line-tools-reference/feature-gates/MultiCIDRServiceAllocator.md
content/en/docs/reference/command-line-tools-reference/feature-gates/NFTablesProxyMode.md
content/en/docs/reference/command-line-tools-reference/feature-gates/NodeInclusionPolicyInPodTopologySpread.md
content/en/docs/reference/command-line-tools-reference/feature-gates/RecursiveReadOnlyMounts.md
content/en/docs/reference/command-line-tools-reference/feature-gates/SeparateCacheWatchRPC.md
content/en/docs/reference/command-line-tools-reference/feature-gates/ServiceAccountTokenNodeBinding.md
content/en/docs/reference/command-line-tools-reference/feature-gates/ServiceTrafficDistribution.md
content/en/docs/reference/command-line-tools-reference/feature-gates/SidecarContainers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/StorageNamespaceIndex.md
content/en/docs/reference/command-line-tools-reference/feature-gates/TopologyAwareHints.md
content/en/docs/reference/command-line-tools-reference/feature-gates/WatchFromStorageWithoutResourceVersion.md
content/en/docs/reference/command-line-tools-reference/feature-gates/WindowsHostNetwork.md

We have some features GA'ed or deprecated but failed to document them correctly.
This PR fixes this issue.

Update graduated/deprecated features in v1.33

---

content/en/docs/reference/access-authn-authz/certificate-signing-requests.md

The ClusterTrustBundles were being documented as alpha in some parts of the documentation.
Related-to: https://github.com/kubernetes/enhancements/issues/3257#issuecomment-2856617519

cluster trust bundles: use correct version/feature maturity stage

---

content/fr/docs/reference/kubectl/kubectl.md
layouts/docs/docsportal_home.html
layouts/partials/docs/content-page.html

This PR removes a front matter parameter called `notitle` from the `fr` language [kubectl](https://kubernetes.io/fr/docs/reference/kubectl/kubectl/) page. It also removes guards for the parameter.
This parameter has become obsolete and is not used anywhere else including the `en` version of the same page.
Helps with #41171
Closes #50447

[fr] Remove the `notitle` param that is not used anywhere else

---

content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.md

Expose intro tutorial missing expose command #50418
This is a Bug Report
Problem: On the Expose Intro Page the command to expose the pod created in the deploy tutorial is missing.
Proposed Solution: Add the kubectl expose command that previously existed in the [html documentation](https://github.com/kubernetes/website/blob/6ad170bf1720c77c7119e8174054c1791cd01e3c/content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html#L106).
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/
https://github.com/kubernetes/website/issues/50418
Closes: # https://github.com/kubernetes/website/issues/50418

Update expose command in expose-intro.md

---

content/vi/community/_index.html

This PR updates the Code of Conduct link in the Vietnamese community page to point to the localized Vietnamese version of the Code of Conduct document.
Link: https://kubernetes.io/community/
NONE

[vi] update Code of Conduct link to use localized Vietnamese path

---

content/en/docs/tasks/administer-cluster/encrypt-data.md
content/en/docs/tasks/administer-cluster/kms-provider.md

xref: https://github.com/kubernetes/kubernetes/blob/7017be7b0823ce56de2d4c78e402931ec817d3be/OWNERS_ALIASES#L57C2-L59
/sig auth
/assign enj

Sync encryption docs reviewers with kubernetes sig-auth-encryption-at-rest-reviewers

---

content/en/blog/_posts/2025-05-12-ensure-secret-pulled-images/index.md

Update publish time for KEP-2535 blog post and fix a few nits.
Orig PR: #49999
@stlaz @aramase

KEP-2535: add publish time, minor nits

---

content/en/examples/mutatingadmissionpolicy/applyconfiguration-example.yaml

The MutatingAdmissionPolicy example indicates that "pods" are in the "apps" ApiGroup, but they're in the "" ApiGroup.

Fix incorrect apiGroup for pods in MutatingAdmissionPolicy example

---

content/en/blog/_posts/2025-04-28-hpa-configurable-tolerance.md

**Description**
This pull request updates the term "Horizontal Pod Autoscaler" to "HorizontalPodAutoscaler" in the 2024-05-07 blog post to use the correct Kubernetes API object name when referring to the resource.
The update ensures consistency with how other Kubernetes resource kinds are written (e.g., Deployment, StatefulSet) and avoids ambiguity between the general concept and the actual object.
**Issue**
/close #50835

Use HorizontalPodAutoscaler when referring to the API object in 2024-04-28 HPA blog post

---

content/ja/blog/_posts/2025-04-28-hpa-configurable-tolerance.md

Translated [/content/en/blog/_posts/2025-04-28-hpa-configurable-tolerance.md](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2025-04-28-hpa-configurable-tolerance.md) into Japanese.
Closes: #50771 
/language ja
I translated "HorizontalPodAutoscaler Configurable Tolerance" as "HorizontalPodAutoscalerの設定可能な許容値", following the "Kubernetes v1.33: Octarine"'s translated blog.
While reading the translated blog post, I noticed a minor wording issue in the Japanese text:
The phrase "HorizontalPodAutoscaler設定可能な許容値" seems to be missing "の" ?
[Blog link](https://kubernetes.io/ja/blog/2025/04/23/kubernetes-v1-33-release/#horizontalpodautoscaler%E3%81%AE%E8%A8%AD%E5%AE%9A%E5%8F%AF%E8%83%BD%E3%81%AA%E8%A8%B1%E5%AE%B9%E5%80%A4)
> …

[ja] Translate HorizontalPodAutoscaler Configurable Tolerance into Japanese

---

content/en/blog/_posts/2025-05-13-jobs-backofflimitperindex-goes-ga.md
content/en/blog/_posts/2025-05-14-Container-Stop-Signals.md
content/en/blog/_posts/2025-05-15-jobs-successpolicy-goes-ga.md
content/en/blog/_posts/2025-05-16-in-place-pod-resize-beta.md

This updates the following blogs
- KEP-3850: to be published on Tuesday, 13th May ([original PR](https://github.com/kubernetes/website/pull/49982))
- KEP-4960: to be published on Wednesday, 14th May ([original PR](https://github.com/kubernetes/website/pull/49967))
- KEP-3998: to be published on Thursday, 15th May ([original PR](https://github.com/kubernetes/website/pull/49998))
- KEP-1287: to be published on Friday, 16th May ([original PR](https://github.com/kubernetes/website/pull/50024))
For KEP-3850, there are also a few wording updates that were mentioned in the original PR.

Bump up schedule of blogs ready to publish

---

content/ja/docs/tasks/configure-pod-container/security-context.md

Added a note about pod rejection released on KEP-3619(Beta) in content/ja/docs/tasks/configure-pod-container/security-context.md
related PRs of `en` contents: 
- https://github.com/kubernetes/website/pull/49880
Preview: https://deploy-preview-50877--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/configure-pod-container/security-context/#implementations-supplementalgroupspolicy

[ja] added a note about pod rejection released on KEP-3619(Beta) in content/ja/docs/tasks/configure-pod-container/security-context.md

---

content/en/blog/_posts/2025-05-16-in-place-pod-resize-beta.md

The wording sounded as if the change is still pending, but as we have v1.33 already released, changed the tenses to better align with other announcements.

Correct "graduating" to "graduated" for in-place pod update

---

content/en/docs/reference/using-api/cel.md

CEL options, features, and libraries table contains a row in the table body that is a duplicate of the table header:

remove duplicate table row in cel.md

---

content/en/docs/concepts/containers/images.md

While reviewing #50183, I noticed some missing punctuation in https://k8s.io/docs/concepts/containers/images, as well as some parts that were not following the recommendations described in the [Kubernetes Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/). This PR aims to address these points.
The following changes were made to this page:
* Updated punctuation to make it consistent across list items.
* Updated wording of API types to use upper camel case.
* Removed unnecessary phrases.
* Included links to content within the same page.
* Fixed grammar and typos in some sentences, including missing periods.
* Updated placeholders to use angle brackets, as described in the style guide.
* Updated the words Windows and Hyper-V to use the exact same spelling …

[en] Update images.md to follow style guide recommendations

---

content/en/blog/_posts/2025-05-14-Container-Stop-Signals.md

Fixes the title for the release blog post for container lifecycle. Specifically this PR removes a repeating `Kubernetes v1.33` in the title.
Closes: N/A

Fixed the title for the v1.33 container lifecycle blog post

---

content/en/examples/admin/sched/my-scheduler.yaml

When the example file [examples/admin/sched/my-scheduler.yaml](https://github.com/kubernetes/website/blob/main/content/en/examples/admin/sched/my-scheduler.yaml) is used as is, I see the following error which indicates that the deprecated API version is not recognized:
```
"command failed" err="no kind \"KubeSchedulerConfiguration\" is registered for version \"kubescheduler.config.k8s.io/v1beta2\" in scheme \"pkg/runtime/scheme.go:110\""
```
Replace deprecated API version `kubescheduler.config.k8s.io/v1beta2` with `kubescheduler.config.k8s.io/v1` so the example can be directly run without modifications.

Replace deprecated API version of `kubescheduler.config.k8s.io` in `my-scheduler.yaml`.

---

content/en/docs/concepts/workloads/pods/disruptions.md

[Link to Node Autoscaling docs](https://kubernetes.io//docs/concepts/cluster-administration/node-autoscaling/) in the [Pod Disruption docs](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#voluntary-and-involuntary-disruptions) is [incorrect](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/(/docs/concepts/cluster-administration/node-autoscaling/)).
I fixed it.
Closes: #

Fix wrong link to Node Autoscaling docs

---

content/en/blog/_posts/2025-03-24-ingress-nginx-CVE-2025-1974.md

This PR updates the release note links in the 2024/03/24 ingress-nginx security blog post to point to specific release tags instead of the generic releases page.
This improves user experience by allowing readers to navigate directly to the relevant release information without manual searching.
Closes: #50834 
I apologize for submitting this PR before the issue was formally triaged.
Please let me know if you'd like any changes to the approach or if you'd prefer to wait for the issue triage before proceeding with the review.

Update ingress-nginx release links in 2024/03/24 security blog post for clarity

---

content/en/docs/reference/_index.md
content/en/docs/reference/config-api/kuberc.v1alpha1.md

The upstream generator is updated for supporting kuberc v1alpha1 (https://github.com/kubernetes-sigs/reference-docs/pull/395).

Add config API for kuberc v1alpha1

---

content/pl/docs/contribute/generate-ref-docs/contribute-upstream.md

[pl] docs/contribute/generate-ref-docs/contribute-upstream.md

---

content/pl/docs/tutorials/kubernetes-basics/explore/explore-intro.html

sync explore-intro.html with the latest EN version
preview:
https://deploy-preview-50532--kubernetes-io-main-staging.netlify.app/pl/docs/tutorials/kubernetes-basics/explore/explore-intro/

[pl] sync explore-intro.html with the latest EN version

---

content/pl/docs/contribute/localization.md

[pl] docs/contribute/localization.md

---

content/pl/docs/contribute/new-content/_index.md

[pl] docs/contribute/new-content/_index.md

---

content/ja/docs/reference/glossary/job.md

Translate `content/en/docs/reference/glossary/job.md` into Japanese
Closes: #50888
- https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/job.md

[ja] Translate content /en/docs/reference/glossary/job.md into Japanese

---

content/pl/docs/concepts/workloads/controllers/_index.md

EDIT:
the parent _index.md : #49797

[pl] docs/concepts/workloads/controllers/_index.md

---

content/pl/docs/concepts/workloads/_index.md
content/pl/docs/reference/glossary/workload.md

[pl] docs/concepts/workloads/_index.md

---

content/zh-cn/blog/_posts/2025-05-15-jobs-successpolicy-goes-ga.md

```
content/zh-cn/blog/_posts/2025-05-15-jobs-successpolicy-goes-ga.md
```
See [preview](https://deploy-preview-50964--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2025/05/15/kubernetes-1-33-jobs-success-policy-goes-ga/)

[zh] Add 2025-05-15-jobs-successpolicy-goes-ga.md

---

content/en/docs/concepts/containers/images.md

This is controlled by the`imagePullCredentialsVerificationPolicy` field in the
[Kubelet configuration](/docs/reference/config-api/kubelet-config.v1beta1#ImagePullCredentialsVerificationPolicy).
to 
[Kubelet configuration]https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#imagepullcredentialsverificationpolicy
#correction - 
[Kubelet configuration](/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-ImagePullCredentialsVerificationPolicy).
imagePullCredentialsVerificationPolicy field is missing in the /docs/reference/config-api/kubelet-config.v1beta1
Closes: #50681

Fix broken link in container images concept

---

content/en/docs/concepts/security/multi-tenancy.md

Drops third-party links and warnings from https://kubernetes.io/docs/concepts/security/multi-tenancy/ to match guidance at https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content
Also drops link to archived kubernetes-sigs project.

Drop links to third-party projects from multi-tenancy page

---

content/en/docs/concepts/workloads/pods/sidecar-containers.md

According to [documentation](https://kubernetes.io/blog/2025/04/23/kubernetes-v1-33-release/#stable-sidecar-containers), sidecar containers is now stable

fixes - sidecar containers graduated to stable  in 1.33

---

content/en/docs/reference/command-line-tools-reference/feature-gates/StreamingCollectionEncodingToJSON.md
content/en/docs/reference/command-line-tools-reference/feature-gates/StreamingCollectionEncodingToProtobuf.md

Add feature gates related to streaming collections

---

content/en/docs/tasks/run-application/run-single-instance-stateful-application.md
content/en/examples/application/mysql/mysql-deployment.yaml

**This pull request includes changes only for the EN version of the website, while MR  #50822  contains changes for all languages**
--- 
I've upgraded the version of the image used as this is as simple as that to make it work on newest macbook pro. 
This is an effort of #45822 
Without this : 
```bash
➜ kubectl describe pods -l app=mysql | grep image
Normal   Pulling    3s    kubelet            Pulling image "mysql:5.6"
Warning  Failed     1s    kubelet            Failed to pull image "mysql:5.6": no matching manifest for linux/arm64/v8 in the manifest list entries
```
With this : 
```bash
➜ kubectl describe pods -l app=mysql | grep image
Normal …
```

Upgrade mysql image version to allow multi-arch env

---

content/zh-cn/docs/tasks/run-application/run-single-instance-stateful-application.md
content/zh-cn/examples/application/mysql/mysql-deployment.yaml

**This pull request includes changes only for the ZH-CH version of the website, now MR #50991 (EN version change)  has been accepted**

[zh-cn] Sync run-single-instance-stateful-application.md Upgrade mysql image

---

content/hi/examples/application/mysql/mysql-deployment.yaml

**This pull request includes changes only for the HI version of the website, now MR #50991 (EN version change)  has been accepted**

[hi] Sync run-single-instance-stateful-application.md Upgrade mysql image

---

content/fr/docs/tasks/run-application/run-single-instance-stateful-application.md
content/fr/examples/application/mysql/mysql-deployment.yaml

**This pull request includes changes only for the FR version of the website, now MR #50991 (EN version change)  has been accepted**

[FR] Sync run-single-instance-stateful-application.md Upgrade mysql image

---

content/ja/docs/tasks/run-application/run-single-instance-stateful-application.md
content/ja/examples/application/mysql/mysql-deployment.yaml
content/ja/examples/application/wordpress/mysql-deployment.yaml

**This pull request includes changes only for the JA version of the website, now MR #50991 (EN version change)  has been accepted**
Note:
I've also sync the content of mysql-deployment.yaml to version 8 (and not 9 !!) like the EN version

[JA] Sync run-single-instance-stateful-application.md Upgrade mysql image

---

OWNERS_ALIASES

Removing the following folks since they've been inactive and/or have stepped away from contributing to the kubernetes/website repo in the past year
- @Princesso 
- @drewhagen 
- @kbhawkey 
Please note: 
- If you wish to restart your contribution journey, we're happy for you to pick up from where you left off. If you'd like to discuss this privately before publicly commenting here, please start a group DM with all the chairs included. 
- Since these are named roles, the PR will be open for comment until **13th May 2025** EOD. Kindly comment on the PR, failing which we will merge as-is. 
cc: @reylejano @natalisucks

OWNERS_ALIASES cleanup activity from previous cycles

---

content/zh-cn/docs/concepts/containers/images.md
content/zh-cn/docs/concepts/workloads/pods/sidecar-containers.md

[zh-cn]sync images sidecar-containers

---

content/en/docs/concepts/overview/working-with-objects/finalizers.md

This PR updates the Finalizers concept documentation to clearly state that custom finalizer names must be fully qualified names. 
While the Kubernetes API server enforces this validation at runtime, the current documentation does not explicitly mention the requirement, which can lead to confusion for users manually adding finalizers to objects.
This clarification helps users avoid validation errors when creating or updating resources with custom finalizers.

Clarify that custom finalizer names must be publicly qualified finalizer names

---

content/ko/docs/tasks/administer-cluster/declare-network-policy.md

https://github.com/kubernetes/website/pull/49937/files

[ko] Update busybox image

---

content/en/docs/reference/using-api/server-side-apply.md

"can accepts" doesn't make sense, it should be "can accept".
Closes: #

fix grammar error in server-side-apply

---

content/en/training/_index.html

add the missing </div> closing tag to fix the html syntax error

Fix missing closing tag at the Training page

---

assets/scss/_custom.scss
layouts/shortcodes/blocks/case-studies.html

Revise a shortcode that renders a selection of case studies. Also update the SCSS to make it look about right.
This changes the HTML on the site landing page(s), not the rendering within the Case Studies section.
Here's a [preview](https://deploy-preview-50983--kubernetes-io-main-staging.netlify.app/)
Helps with issue #41171
Supersedes PR #48560

Ready case studies shortcode for Docsy

---

content/ko/docs/concepts/workloads/controllers/deployment.md

the same as in english documentation #49600 .
fix a small inconsistency.
one of the code blocks for a command output has a different color (red).
this is because it is a code block of type 'ini',
but it should not be.

[ko] fix: code block typo in deployment.md

---

content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md

[zh-cn]sync assign-pod-node.md

---

content/es/docs/tasks/tools/included/optional-kubectl-configs-pwsh.md
content/es/docs/tasks/tools/install-kubectl-windows.md

Se traduce y revisa completamente al español la página “Install and configure kubectl on Windows”:
- Todos los bloques de notas y ejemplos de comandos
- Enlaces internos y referencias

docs(i18n): traducir guía de instalación y configuración de kubectl en Windows al español

---

content/id/docs/contribute/localization_id.md
content/id/docs/setup/best-practices/enforcing-pod-security-standards.md

- Add Pod Security Admission to the Bahasa Indonesia Glossarium
- Translate [Enforcing Pod Security Standards](https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/) page to Bahasa Indonesia
None

[id] Translate Enforcing Pod Security Standards page to Bahasa Indonesia

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.md

The current text on the website is:
> You will need to have installed kubectl as well. If you need to install it, visit [install tools](https://kubernetes.io/docs/tasks/tools/#kubectl) install tools.
This removes the duplicate "install tools" text.

Remove duplicate words with anchor text

---

content/en/docs/concepts/security/hardening-guide/scheduler.md

Creating a scheduler hardening guide as a part of https://github.com/kubernetes/sig-security/issues/30.
Page preview  - https://deploy-preview-45080--kubernetes-io-main-staging.netlify.app/docs/concepts/security/hardening-guide/scheduler/

Security hardening guide for scheduler configuration

---

content/id/docs/concepts/services-networking/cluster-ip-allocation.md

This PR translates [cluster-ip-allocation](https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/) Page into Bahasa Indonesia
/cc @kubernetes/sig-docs-id-reviews

[id] Translate cluster-ip-allocation page to Bahasa Indonesia

---

content/en/docs/reference/config-api/kubeadm-config.v1beta4.md

Correct a typo in the documentation where the `advertiseAddress` field was missing the initial 'a':
```diff
-   <p><code>dvertiseAddress</code> sets the IP address for the API server to advertise.</p>
+   <p><code>advertiseAddress</code> sets the IP address for the API server to advertise.</p>
```

correct advertiseAddress typo

---

content/en/docs/reference/kubectl/kuberc.md
content/en/docs/reference/kubectl/quick-reference.md
content/en/docs/tasks/tools/install-kubectl-linux.md
content/en/docs/tasks/tools/install-kubectl-macos.md
content/en/docs/tasks/tools/install-kubectl-windows.md

This PR adds documentations for the kuberc (KEP issue: https://github.com/kubernetes/enhancements/issues/3104). 
This PR is complementary of this https://github.com/kubernetes/website/pull/50961.

Add documents for kuberc

---

content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md

This PR replaces a paywalled Medium article link with a publicly accessible Stack Exchange post in the macOS shell autocompletion section of the "Install and Set Up kubectl" guide.
The original external link for upgrading Bash on macOS pointed to a Medium article that is behind a paywall, which impacts the user experience.
Updated the link to a Stack Exchange post:
https://apple.stackexchange.com/a/292760
The new link is publicly accessible, still relevant, and recently verified.
Closes: #51107
/sig docs

Fix: Replace external paywall link in macOS kubectl autocompletion instructions

---

content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md

Moving the feature-state notice to where it belongs.
Currently the feature-state block appears to be for the entire "Node-pressure eviction" page, however, it's just for the note block listed on top of the page. So moving this notice inside the node block.
Closes: N/A (no bug open).

fix: move KubeletSeparateDiskGC feature notice inside note

---

content/pt-br/_index.html

Following the recent KubeCon links section UI update & content actualisation for 2025 (#49167), I'm applying the same changes to the Portuguese localisation.

[pt-br] Sync KubeCon section UI & 2025 links to Portuguese

---

content/ja/docs/tutorials/hello-minikube.md

In the markdown file, hugo automatically insert /ja prefix if the localized page already exists.
Fix hello-minikube.md file.
https://github.com/kubernetes/website/issues/51260
Closes: #

[ja] Remove /ja prefix from hello-minikube.md links

---

content/ja/docs/concepts/_index.md

Remove the /ja prefix from text links on concepts _index.md.
https://github.com/kubernetes/website/issues/51260
Closes: #

[jp] Remove the /ja prefix from japanese docs

---

content/en/docs/reference/access-authn-authz/admission-controllers.md

The additional whitespace caused the site to not render the note, displaying[ the literal "{{ }}" instead](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podtopologylabels).
Before:
After:

Fix PodTopologyLabels note not rendering

---

content/en/docs/concepts/windows/intro.md
content/en/docs/setup/production-environment/container-runtimes.md

Currently, in:
- https://kubernetes.io/docs/setup/production-environment/container-runtimes/#mcr
- https://kubernetes.io/docs/concepts/windows/intro/#mcr
when clicking on [Mirantis Container Runtime](https://docs.mirantis.com/mcr/20.10/overview.html) and "visit [MCR Deployment Guide](https://docs.mirantis.com/mcr/20.10/install.html)" the links are for Mirantis Container Runtime (MCR) 20.10 which is EOL.
The most recent one and supported by Mirantis is MCR 25.0.
This PR updates all of the `https://docs.mirantis.com/mcr/20.10` URLs with `https://docs.mirantis.com/mcr/25.0` in pages (English-only)
https://github.com/kubernetes/website/issues/51216

Fix EOL MCR links in CRI and Windows Installation Pages

---

data/releases/schedule.yaml

This PR adds the June 2025 patch releases (with the updated release date) to the patch releases schedule/page.
/assign @jeremyrickard 

Add June 2025 patch releases to the schedule

---

content/en/docs/reference/access-authn-authz/authentication.md
content/en/docs/reference/command-line-tools-reference/feature-gates/StructuredAuthenticationConfiguration.md

Doc update for KEP 3331 GA: https://git.k8s.io/enhancements/keps/sig-auth/3331-structured-authentication-configuration
/triage accepted
/sig auth
/assign enj liggitt

Add docs for Structured Authn GA

---

content/ja/docs/concepts/configuration/windows-resource-management.md

Description
Translated content/en/docs/concepts/configuration/windows-resource-management.md  into Japanese.
Issue
Closes: https://github.com/kubernetes/website/issues/51278
/language ja

[ja] Translate content/en/docs/concepts/configuration/windows-resource-management.md into Japanese

---

content/en/docs/reference/labels-annotations-taints/_index.md

The non-graceful shutdown documentation has been moved, this link now pointed to a non-existing paragraph.
The node shutdown documentation is part of the cluster-administration guide, so point readers there.

Correct out-of-service taint link to non-graceful node shutdown

---

content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
static/css/training.css

The "kubeadm upgrade node phase" section tabs were not updating content when clicked due to a name collision with the "kubeadm upgrade apply phase" section. Both tab groups were using the same name attribute, causing unexpected behavior.
Changes:
Changed the tab name for the "kubeadm upgrade node phase" section from name="tab-upgrade-phase" to name="tab-node-phase" to ensure unique tab group identifiers
This ensures each tab group has a unique name and prevents state sharing between different tab sections
Closes: #51358

Kubeadm upgrade phase navigation

---

content/en/docs/concepts/policy/resource-quotas.md

The link in the introduction to ResourceQuotas to Object count ResourceQuotas is not working. This PR fixes the link.

Fix broken link to Object count quota

---

content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.md

add missing closing round bracket in deploy-intro.md .
the original sentence in the HTML version was :
"
For your first Deployment, you'll use a hello-node application packaged in a Docker container that uses NGINX to echo back all the requests. (If you didn't already try creating a hello-node application and deploying it using a container, you can do that first by following the instructions from the <a href="/docs/tutorials/hello-minikube/">Hello Minikube tutorial</a>).
"
the clossing braket was probably missed when the `<a>` was replaced with a MD-style link `[]()`.

Add missing closing round bracket in deploy-intro.md

---

content/en/docs/concepts/storage/volumes.md

Grammar fix of "media" to "medium": "The storage media (such as Disk or SSD) of an `emptyDir` volume is determined" -> "The storage medium (such as Disk or SSD) of an `emptyDir` volume is determined"

Grammar fix in volumes.md: media -> medium

---

content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

Small focused update to https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
- Don't assume that solution developers can reconfigure the cluster (recommend changing controller manager configuration, but treat this as secondary)
- Consider a startup probe
/language en
/sig autoscaling

Revise best practice for autoscaling

---

content/pt-br/docs/tasks/run-application/run-single-instance-stateful-application.md
content/pt-br/examples/application/mysql/mysql-deployment.yaml
content/pt-br/examples/application/mysql/mysql-pv.yaml
content/pt-br/includes/default-storage-class-prereqs.md

Esse PR traz a localização da página https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/ para PT-BR.
Adicionado a raiz de /content/pt-br/docs/tasks/run-application o arquivo run-single-instance-stateful-application.md, ficando localizado como /content/pt-br/docs/tasks/run-application/run-single-instance-stateful-application.md no repositório.
Foi feita uma cópia dos arquivos mysql-deployment.yaml e mysql-pv.yaml de /content/en/examples/application/mysql para /content/pt-br/examples/application/mysql. Também foi adicionado ao diretório /content/pt-br/includes o arquivo default-storage-class-prereqs.md e feita sua localização.
---
This PR brings the localization of the page https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-ap …

[pt-br] Add /tasks/run-application/run-single-instance-stateful-application.md

---

scripts/lsync.sh

At this PR, I refactor `scripts/lsync.sh` to make more robust and align shell scripting best practices.
- **Handles special filenames:** The script now correctly processes filenames containing spaces or other special characters by using a `find ... -print0` | `while read` loop.
- **Modernized syntax:** Replaced legacy backticks (`` `...` ``) with `$(...)`
- **Simplified conditionals:** Use `if` were simplified to check command exit codes, cleaner and more readable.
**Special**: Improvements the script without changing its core functionality.
> use https://www.shellcheck.net for find this issues.

refactor(scripts): improve robustness and readability of lsync.sh

---

layouts/_default/baseof.html
layouts/blog/baseof.html
layouts/docs/baseof.html
layouts/docs/single.html

This PR removes some template blocks that are not required anymore.
- `post-hero` block is removed from `_default/baseof.html` as its an empty `block` and is not defined anywhere else.
- `hero-more` is removed from `blog/baseof.html` and `docs/baseof.html` as they are empty blocks and not defined anywhere else.
- `hero-more` definition is removed from `docs/single.html` as that block is only applicable when `.IsHome` is true but it's never true for any content applicable for the docs/single layout.
Helps with #41171 and #50317

Cleanup some hero elements

---

content/zh-cn/docs/concepts/policy/resource-quotas.md

content/zh-cn/docs/concepts/policy/resource-quotas.md

[zh] sync concepts/policy/resource-quotas.md

---

content/zh-cn/docs/concepts/storage/volumes.md

```bash
```
- Fix syntax errors in English comments: 'storage media' -> 'storage medium'
- Synchronize with English version.

[zh-cn] sync content/en/docs/concepts/storage/volumes.md

---

content/en/docs/reference/kubectl/_index.md
content/en/docs/reference/kubectl/quick-reference.md

xref https://github.com/kubernetes/enhancements/issues/5295
/cc @lmktfy

Document KYAML feature 

---

content/en/docs/reference/command-line-tools-reference/feature-gates/PodDisruptionConditions.md

k/k: https://github.com/kubernetes/kubernetes/pull/129501
/hold

mark PodDisruptionConditions as removed

---

content/en/examples/pods/config/redis-pod.yaml

Description
Updated the Redis image version in the redis-pod.yaml example from 5.0.4 to the latest stable version 8.0.2.
This ensures that the example uses a supported and up-to-date Redis image available on Docker Hub.
The example was tested on a Kubernetes v1.32.0 cluster and the Pod successfully started with the new version, reading the configuration from the ConfigMap as expected.
Issue
No related issue.

Update Redis version in redis-pod.yaml to 8.0.2

---

content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

sync
```
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
```
术语一致性: 统一使用 "控制平面" 替代 "控制面"

[zh-cn] sync kubeadm-upgrade.md

---

content/en/docs/tasks/network/reconfigure-default-service-ip-ranges.md

Description
This is a simple fix on the markdown that had a broken link. I've followed the other links on the same page that use the full url reference to the section
Issue
There is no open issue created (afaik) but the markdown is incorrect or incomplete in the section:
https://kubernetes.io/docs/tasks/network/reconfigure-default-service-ip-ranges/#kubernetes-service-cidr-reconfiguration-categories ----> Anything that results in changing the primary service CIDR

fixing broken markdown for hyperlink on network configuration page

---

content/en/docs/contribute/generate-ref-docs/kubectl.md

This PR fix the link functionality. Now this is working as expected. 
Closes: #51417

Fix non-functional link for Generating Reference Documentation for kubectl Commands page

---

assets/js/sidebar-tree.js
assets/scss/_custom.scss
assets/scss/_k8s_sidebar-tree.scss
assets/scss/_styles_project.scss
layouts/partials/blog-sidebar-tree.html
layouts/partials/hooks/head-end.html
layouts/partials/scripts.html
layouts/partials/sidebar-tree.html

This PR reworks the styling of the sidebar components
- Moves all sidebar related styles out of `_custom.scss` into a new `_k8s_sidebar-tree.scss`.
- `_k8s_sidebar-tree.scss` is imported as a partial into `_styles_project.scss`.
- The sidebar heading and the language dropdowns are disabled via CSS instead of removing the block in the layout.
- Instead of using a media query, `media-breakpoint-*` bootstrap functions are used wherever possible.
- The 1 rem margin from the search within the sidebar is removed.
- The CSS associated with `#m-docs-search` is removed as that element id no longer exists
- The script for using split.js for the sidebar is moved away from `scripts.html` to its own `assets/js/sidebar-tree.js` and then imported back in `scripts.html`.
- Proper cache handling using the …

Rework the stylesheet of sidebar

---

content/bn/examples/application/mysql/mysql-deployment.yaml

**This pull request includes changes only for the BN version of the website, now MR #50991 (EN version change)  has been accepted**

[BN] Sync run-single-instance-stateful-application.md Upgrade mysql image

---

content/en/docs/reference/labels-annotations-taints/_index.md

Clarifying what [service.kubernetes.io/service-proxy-name](https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioservice-proxy-name) does. See [this reference to lack of clarity](https://github.com/kubernetes/kubernetes/issues/132710#issuecomment-3052535236). And see the implementation [here](https://github.com/kubernetes/kubernetes/blob/93bb3858f381bed5c18f3ad53688f01d0013a42b/cmd/kube-proxy/app/server.go#L550).

Update service-proxy-name comment to be more descriptive

---

content/en/docs/reference/access-authn-authz/authentication.md
content/en/docs/reference/command-line-tools-reference/feature-gates/AnonymousAuthConfigurableEndpoints.md

Update the feature-gate in the docs to stable. I took a look at the docs and AFAICT they don't need an update.
xref: #https://github.com/kubernetes/enhancements/issues/4633

KEP-4633: Graduate to Stable.

---

content/en/docs/reference/access-authn-authz/authentication.md

Drops third-party links and warnings from https://kubernetes.io/docs/reference/access-authn-authz/authentication/ to match guidance at https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content (similar to https://github.com/kubernetes/website/pull/51014)

Drop links to third-party projects from authentication page

---

content/en/docs/tasks/configure-pod-container/security-context.md

Description
This pull request fixes a minor typo in the Kubernetes documentation.
The word “identitiy” was corrected to “identity” in the section describing the process identity exposed in status.containerStatuses[].user.linux.
This improves the clarity and professionalism of the documentation.
Issue
No related issue. This is a minor typo fix noticed during reading.

Fix typo: identitiy ➔ identity in security context docs

---

content/en/docs/reference/access-authn-authz/authorization.md

This PR documents the newly introduced features `cacheAuthorizedRequests`  and `cacheUnauthorizedRequests` in the `apiserver.config.k8s.io/v1{alpha1,beta1}. AuthorizationConfiguration` API.
Part of https://github.com/kubernetes/kubernetes/issues/129233
Follow-up of https://github.com/kubernetes/kubernetes/pull/129237

Document new `cache{A,Una}uthorizedRequests` field in `AuthorizationConfiguration`

---

content/ru/_index.html

Based on #51406 for the English version, I removed two KubeCon events that had already passed from the Russian localisation.

[ru] Sync KubeCon 2025 events

---

content/en/docs/concepts/extend-kubernetes/operator.md

The repository (KubeOps) has been approved and
adopted by the .NET Foundation. As such, the repository was moved and we need to update the URI.
Wrong URI pointing currently to a 404 site.

docs(operators): update URI to KubeOps

---

content/en/docs/reference/labels-annotations-taints/_index.md
content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
content/en/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md
content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md
content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
content/en/docs/tasks/debug/debug-cluster/_index.md

This document includes the docs changes to upgrade the kubeadm NodeLocalCRISocket Feature Gate to the beta stage and removes references to `kubeadm.alpha.kubernetes.io/cri-socket`.
relate: https://github.com/kubernetes/kubeadm/issues/3042
Closes: #

Add documentation for promoting the NodeLocalCRISocket to Beta

---

content/en/docs/reference/access-authn-authz/node.md
content/en/docs/reference/access-authn-authz/webhook.md
content/en/docs/reference/command-line-tools-reference/feature-gates/AuthorizeNodeWithSelectors.md
content/en/docs/reference/command-line-tools-reference/feature-gates/AuthorizeWithSelectors.md
content/en/docs/reference/using-api/cel.md

Promote KEP-4601 to stable
https://github.com/kubernetes/enhancements/issues/4601
/sig auth
/cc @deads2k

KEP-4601: promote AuthorizeWithSelectors / AuthorizeNodeWithSelectors to stable

---

content/en/docs/reference/command-line-tools-reference/feature-gates/APIServingWithRoutine.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/APIServingWithRoutine.md

There's no feature flag in code called `APIServingWithRoute`, but there is `APIServingWithRoutine`. I believe this was a typo, correcting
Closes: #51639

rename APIServingWithRoute typo to APIServingWithRoutine

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md

According to [this](https://github.com/kubernetes/community/commit/76c29a326d74a60bb219c4c323993ace49bf9816) commit, file name was changed.
Closes: #51650

fix: instrumentation guidelines link in device plugin page

---

content/en/docs/concepts/services-networking/dns-pod-service.md

This example will help the reader understand. It's also more consistent to provide an example like the preceding Pod-scoped DNS record paragraphs.
follow up to https://github.com/kubernetes/website/pull/49532

docs: add an example of a Service-scoped Pod DNS record

---

content/zh-cn/docs/concepts/services-networking/dns-pod-service.md

[zh-cn]sync dns-pod-service.md

---

content/zh-cn/docs/tutorials/kubernetes-basics/_index.md

Fixed incorrect double language prefix in Chinese Kubernetes tutorial navigation links. The tutorial module paths were manually including `/zh-cn/` prefix, but Hugo was automatically adding the language prefix again based on the current page context, resulting in invalid URLs with `/zh-cn/zh-cn/` double prefix.
**Changes made:**
- Removed manual `/zh-cn/` prefix from all tutorial module paths in the Chinese localization
- Links now follow the same pattern as the English version, allowing Hugo to handle language prefixing automatically
- All 6 tutorial modules updated: create cluster, deploy app, explore app, expose app, scale app, and update app
Closes #51643
**Root cause:** Hugo automatically prepends language-specific URL prefixes (`/zh-cn/`) when serving localized content. The manual …

Updated image links at Kubernetes basic tutorial

---

content/pt-br/docs/tasks/run-application/scale-stateful-set.md

Esse PR traz a localização da página https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/ para PT-BR.
Adicionado a raiz de /content/pt-br/docs/tasks/run-application o arquivo scale-stateful-set.md, ficando localizado como `/content/pt-br/docs/tasks/run-application/scale-stateful-set.md` no repositório.
---
This PR brings the localization of the page https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/ to PT-BR.
The file scale-stateful-set.md was added to the root of /content/pt-br/docs/tasks/run-application, resulting in the path `/content/pt-br/docs/tasks/run-application/scale-stateful-set.md` in the repository.
Closes: #50951

[pt-br] Add tasks/run-application/scale-stateful-set.md

---

content/en/docs/reference/kubectl/kuberc.md

Promote kuberc to beta
KEP: https://github.com/kubernetes/enhancements/issues/3104
/assign @ardaguclu 
for sig-cli review 
The generated changes are coming from https://github.com/kubernetes-sigs/reference-docs/pull/396

[KEP-3104] Kuberc beta

---

content/en/docs/tutorials/services/connect-applications-service.md

This PR fixes broken links to the `https-nginx` example in the following document:
`content/en/docs/tutorials/services/connect-applications-service.md`.
The original links were pointing to the staging/ directory, which has now been moved to _archived/
- https://github.com/kubernetes/examples/tree/master/staging/https-nginx/
- https://github.com/kubernetes/examples/tree/master/staging/https-nginx/default.conf
These have been updated to point to the correct archived paths:
- https://github.com/kubernetes/examples/tree/master/_archived/https-nginx/
- https://github.com/kubernetes/examples/blob/master/_archived/https-nginx/default.conf
Closes: #51682

Fix broken links to https-nginx example

---

assets/scss/_desktop.scss
assets/scss/_documentation.scss
assets/scss/_tablet.scss
layouts/_default/baseof.html
layouts/blog/baseof.html
layouts/docs/baseof.html

Add RTL support to the Kubernetes website.

Add RTL support

---

content/en/docs/concepts/configuration/manage-resources-containers.md
content/en/docs/reference/command-line-tools-reference/feature-gates/PodLevelResources.md
content/en/docs/tasks/configure-pod-container/assign-pod-level-resources.md

PR for documentation changes for Pod Level Resources
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2837-pod-level-resource-spec

 Documentation updates for KEP 2837 beta phase

---

content/hi/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md

English translation to Hindi: 
https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy.md?plain=1
Closes: #

[hi] Translate to Hindi calico-network-policy.md

---

content/zh-cn/docs/concepts/configuration/liveness-readiness-startup-probes.md

content/zh-cn/docs/concepts/configuration/liveness-readiness-startup-probes.md

[zh-cn]sync liveness-readiness-startup-probes.md

---

content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md
content/en/docs/reference/command-line-tools-reference/feature-gates/SeparateTaintEvictionController.md

/hold
until https://github.com/kubernetes/kubernetes/pull/122634 is merged.

Mark SeparateTaintEvictionController feature gate as stable

---

content/en/docs/concepts/configuration/manage-resources-containers.md
content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/en/docs/reference/command-line-tools-reference/feature-gates/DRAExtendedResource.md
content/en/docs/tasks/administer-cluster/extended-resource-node.md

Documentation for the DRA Extended resource feature
https://github.com/kubernetes/enhancements/issues/5004
Closes: #

[KEP-5004] DRA Extended resource documentation

---

content/en/docs/concepts/workloads/pods/_index.md

Add pod ObservedGeneration info to pod docs as part of beta promotion.
Observed Pod Generation KEP: [kubernetes/enhancements#2377](https://github.com/kubernetes/enhancements/pull/5377)
Closes: #51195

Document pod `status.observedGeneration`

---

content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
content/en/docs/reference/command-line-tools-reference/feature-gates/KubeletPodResourcesDynamicResources.md
content/en/docs/reference/command-line-tools-reference/feature-gates/KubeletPodResourcesGet.md

Document feature gate updates for beta graduation in 1.34
https://github.com/kubernetes/enhancements/issues/3695
Closes: #N/A

KEP-3695: node: dra: podresources: Beta in 1.34

---

content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
content/en/docs/reference/command-line-tools-reference/feature-gates/DRAConsumableCapacity.md

Docs change for KEP-5075.
kubernetes/enhancements: https://github.com/kubernetes/enhancements/issues/5075
kubernetes/kubernetes: https://github.com/kubernetes/kubernetes/pull/132522

[KEP-5075] DRAConsumableCapacity documentation

---

content/en/docs/concepts/services-networking/service.md
content/en/docs/reference/command-line-tools-reference/feature-gates/PreferSameTrafficDistribution.md
content/en/docs/reference/networking/virtual-ips.md

Update feature gate data for PreferSameTrafficDistribution for 1.34
Not doing any ~code/~ docs changes at this point; when we go to GA I'll update the docs to more clearly deprecate `PreferClose` in favor of `PreferSameZone`.
https://github.com/kubernetes/enhancements/issues/3015
/hold
until KEP update merges (https://github.com/kubernetes/enhancements/pull/5376)

KEP-3015: PreferSameTrafficDistribution to Beta

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Resolving wrong redirect to /docs/concepts/architecture/nodes/#swap-memory instead of /docs/concepts/cluster-administration/swap-memory-management/
Closes: #51810

fixed swap link in install-kubeadm.md

---

content/en/docs/concepts/policy/node-resource-managers.md
content/en/docs/tasks/administer-cluster/cpu-management-policies.md

Trivial graduation to beta. We expect no user-visible changes.
https://github.com/kubernetes/enhancements/issues/5109
Closes: #N/A (issue 5109 will close once the feature is GA)

KEP-4800: move to beta

---

content/en/docs/concepts/security/pod-security-standards.md

Notify users that `.host` field in probes and lifecycle handlers can be blocked using PSA
Closes: https://github.com/kubernetes/kubernetes/issues/99425
Enhancement Issue: https://github.com/kubernetes/enhancements/issues/4940
Implementation PR: https://github.com/kubernetes/kubernetes/pull/125271

PSA host field docs

---

content/en/docs/concepts/storage/storage-limits.md
content/en/docs/reference/command-line-tools-reference/feature-gates/MutableCSINodeAllocatableCount.md

Update docs for KEP-4876: Mutable CSINode Allocatable Property.
https://github.com/kubernetes/enhancements/issues/4876

Update docs for MutableCSINodeAllocatableCount

---

content/en/docs/reference/using-api/api-concepts.md

Documenting https://github.com/kubernetes/enhancements/issues/5116

Document KEP-5116

---

content/en/docs/tasks/configure-pod-container/resize-container-resources.md

In-place pod resize docs for 1.34: 
- Relaxing the memory limit decrease limitation
- How to use observedGeneration to track resize requests
- Resize prioritization logic
https://github.com/kubernetes/enhancements/issues/1287
can either replace or be cherry-picked into https://github.com/kubernetes/website/pull/51533

In-place pod resize docs for 1.34

---

content/en/docs/concepts/security/pod-security-standards.md

Fixes https://github.com/kubernetes/website/pull/51498#discussion_r2257241323
We do allow for the host field to be empty - forgot to update this part of docs.
/cc @liggitt

nit-fix: Add empty value for host field in probes PSA

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md
content/en/docs/reference/command-line-tools-reference/feature-gates/ContainerRestartRules.md

Add documentation for container restart policy and container restart rules for 1.34.
https://github.com/kubernetes/enhancements/issues/5307
Closes: #

Documentation change for container restart rules

---

content/en/docs/reference/command-line-tools-reference/feature-gates/RelaxedEnvironmentVariableValidation.md
content/en/docs/tasks/inject-data-application/define-environment-variable-container.md

This PR adds documentation for graduating the feature gate RelaxedEnvironmentVariableValidation to GA.
KEP link: https://github.com/kubernetes/enhancements/issues/4369
Associated k/k repo PR:  https://github.com/kubernetes/kubernetes/pull/132054 (merged)
Closes: #

Add documentation for graduating the RelaxedEnvironmentVariableValidation to GA.

---

content/en/docs/concepts/containers/container-lifecycle-hooks.md
content/en/docs/reference/command-line-tools-reference/feature-gates/PodLifecycleSleepAction.md

Document PodLifecycleSleepAction for GA
GA doc requirement for KEP-3960
Closes: #

[KEP-3960] - update docs for GA

---

content/en/docs/concepts/storage/projected-volumes.md
content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
content/en/docs/reference/command-line-tools-reference/feature-gates/PodCertificateRequests.md
content/en/examples/pods/storage/projected-podcertificate.yaml

This is a narrow change that just adds documentation for the new PodCertificate type and podCertificate projected volumes.
The "Certificates" page is now very unwieldy, and needs to be split up.  This is being pursued in a separate PR (https://github.com/kubernetes/website/pull/51487)

Pod Certificate: Document PodCertificate and podCertificate projected volumes

---

content/en/docs/reference/using-api/api-concepts.md

This PR fixes a typo in the API concepts reference docs that says a `JSON` encoded response is returned when using `Accept: application/vnd.kubernetes.protobuf`, while it is a `binary` encoded response.

fix(api-concepts): Typo - Change JSON to binary

---

content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md

Relocates the containerfs/split image filesystem FEATURE STATE note from the top of the Node-pressure Eviction documentation page into the Filesystem signals section where containerfs is explained. This change clarifies that the note applies only to split image filesystem support, not to node-pressure eviction as a whole.
Closes: #51837

Move split image filesystem FEATURE STATE note to Filesystem signals section for clarity

---

assets/js/banner-dismiss.js

You can now click the button on a dismissible site-wide banner, and it actually dismisses.

Fix bug where dismissible banners didn't

---

content/ko/docs/concepts/security/pod-security-admission.md

- Translate the Metrics section into Korean.
- The `container.apparmor.security.beta.kubernetes.io/*` annotation is deprecated, so we need to translate it into Korean.
- In the "What's Next" section, "migrate from PodSecurityPolicy to the Built-In PodSecurity Admission Controller" is no longer listed as a bullet point but instead has expanded detailed instructions.
#51803 
Closes: #51803

[ko] Translate the Metrics section of Concepts/Security/Pod Security Admission into Korean

---

content/en/blog/_posts/2025-0X-XX-Per-Container-Restart-Policy.md

Add a blog post about the new alpha feature ContainerRestartRules in 1.34. The blog post explains how it works and provides some useful examples and set up.
Related KEP: https://github.com/kubernetes/enhancements/issues/5307

Blog for container restart policy

---

content/ja/blog/_index.md
content/ja/community/_index.html
content/ja/docs/home/_index.md
content/ja/partners/_index.html

Update the front matter for Japanese pages so that if we align more with Docsy, the top nav still works how we want. Currently, the top nav sections are hard coded:
- https://github.com/kubernetes/website/blob/c07ffdf392aa3448d343a46d5ff744e482c5c52d/layouts/partials/navbar.html#L28
- https://github.com/kubernetes/website/blob/c07ffdf392aa3448d343a46d5ff744e482c5c52d/layouts/404.html#L9 
[Original](https://k8s.io/ja/) vs [preview](https://deploy-preview-51875--kubernetes-io-main-staging.netlify.app/ja/) (no visible difference; this is an enabling change)

Update Japanese to support Docsy-style menus

---

content/en/blog/_posts/2023-08-15-kubernetes-1.28-blog.md

Fix the Non-graceful node shutdown link in the 1.28 release

Fix the broken link in the 1.28 release

---

content/en/blog/_posts/2025-0x-xx-jobs-podreplacementpolicy-goes-ga.md

This PR will include a blog post on the latest state of Job Pod Replacement Policy feature gate (GA) as of k8s v1.34.
KEP: https://github.com/kubernetes/enhancements/issues/3939

JobPodReplacementPolicy Promoted To GA Blog Post

---

content/uk/docs/home/_index.md

Update the front matter for Ukrainian pages so that if we align more with Docsy, the top nav still works how we want. Currently, the top nav sections are hard coded:
- https://github.com/kubernetes/website/blob/c07ffdf392aa3448d343a46d5ff744e482c5c52d/layouts/partials/navbar.html#L28
- https://github.com/kubernetes/website/blob/c07ffdf392aa3448d343a46d5ff744e482c5c52d/layouts/404.html#L9 
[Original](https://k8s.io/uk/) vs [preview](https://deploy-preview-51945--kubernetes-io-main-staging.netlify.app/uk/) (no visible difference; this is an enabling change)
Helps with issues https://github.com/kubernetes/website/issues/41171 and https://github.com/kubernetes/website/issues/50228

Update Ukrainian to support Docsy-style menus

---

content/en/blog/_posts/2025-08-27-Kubernetes-v1-34-Release/index.md

The following sections are pending:

Kubernetes v1.34 Release Announcement Blog

---

layouts/blog/baseof.html
layouts/docs/baseof.html

Avoid having a `<title>` element twice in the `<head>` of some pages (documentation and blog sections).
Also helps with issue https://github.com/kubernetes/website/issues/41171

Fix bug where some pages had two title elements

---

content/ko/docs/contribute/localization.md

Add Korean localization for `content/ko/docs/contribute/localization.md`.
This commit adds the Korean translation of the localization contribution guide.
It provides instructions for starting a localization project, managing branches,
and contributing translations, ensuring consistency with the upstream English
documentation.
Closes: #38443

[ko] Translate content/ko/docs/contribute/localization.md into Korean

---

content/en/releases/_index.md

The "schedule" link for upcoming Kubernetes releases occasionally breaks during the early stages of release preparation on [releases page.](https://kubernetes.io/releases/) See discussion [here](https://github.com/kubernetes/website/issues/50883)
Added a note that explains when the link might be temporarily unavailable and provides alternative resources for users to track release progress.
**Screenshot**
Close #50883

Add note about temporarily broken upcoming release schedule link

---

content/en/blog/_posts/2025-08-27-Kubernetes-v1-34-Release/index.md

The following sections are pending:

Publish Kubernetes v1.34 Release Announcement Blog

---

content/en/blog/_posts/2025-08-29-Per-Container-Restart-Policy.md

Schedules https://github.com/kubernetes/website/pull/51745 for publication on Friday, 29th August, 2025.

Schedule KEP-5307 blog for publication

---

hugo.toml

This PR updates the hugo.toml for v1.33 ahead of the v1.34 release.
Base branch will be updated from main to release-1.33 once that branch exists.
/hold for v1.34 release

Update release v1.33 hugo.toml for v1.34 release

---

hugo.toml

Updating hugo.toml for release v1.34.
/hold until v1.34 release.

Updates hugo.toml for v1.32 ahead of v1.34 release

---

content/en/docs/reference/kubectl/kuberc.md

Adds missing information about the `KUBERC` environment variable to set a custom path to the kuberc file.  
Inspired by https://github.com/kubernetes/kubectl/issues/1776#issuecomment-3233727343

Doc for setting custom path to kuberc using KUBERC environment variable

---

content/en/blog/_posts/2025-09-01-dra-134-update.md

Schedules https://github.com/kubernetes/website/pull/51488 for publication on Monday, 1st September, 2025.

Schedule v1.34 DRA updates blog for publication

---

content/en/docs/concepts/workloads/controllers/deployment.md

This PR clarifies the Deployment rollout documentation.
The docs describes Deployments as "moving Pods from the old ReplicaSet to the new one." This is misleading because Pods follow a defined lifecycle and are never "moved". 
This change updates the relevant sentence to more accurately reflect the actual behavior of Deployments during a rolling update.

Improve Deployment rollout wording

---

content/en/docs/tutorials/cluster-management/install-use-dra.md
content/en/examples/dra/driver-install/daemonset.yaml
content/en/examples/dra/driver-install/deviceclass.yaml
content/en/examples/dra/driver-install/example/resourceclaim.yaml

DRA driver tutorial in 1.34 version. Cherry-picks the individual commits that are already in main [1] from [published 1.33 tutorial ](https://kubernetes.io/docs/tutorials/cluster-management/install-use-dra/) against 1.34 dev branch, and then adds commits on top to update the tutorial for 1.34. This is happening this way so we have the 1.33 version snapshotted today, and then this version will be snapshotted for 1.34+. cc @lmktfy 
* Updates prereqs/DRA enable directions to targets resource.k8s.io/v1
* Updates manifests to ResourceClaim and DeviceClass v1
* Uses a new example driver that is set to v1 (⚠️ THIS IS BLOCKED BY MERGE AND RELEASE OF https://github.com/kubernetes-sigs/dra-example-driver/pull/116 ⚠️ )
Quick link to preview page: …

Update DRA tutorial for K8s 1.34

---

content/en/blog/_posts/2025-08-29-Per-Container-Restart-Policy.md

Fixes broken documentation link reported [here](https://kubernetes.slack.com/archives/C0BP8PW9G/p1756524297925099)

Fix doc link in kubernetes-v1-34-per-container-restart-policy

---

content/ko/docs/concepts/configuration/configmap.md

`configmap` -> `configMap`
Sync configMap yaml example in Korean doc `content/ko/docs/concepts/configuration/configmap.md` with [English version](https://kubernetes.io/docs/concepts/configuration/configmap/#using-configmaps-as-files-from-a-pod) 
Closes: #

[ko] Fix typo in configmap yaml example to sync with English version

---

content/en/blog/_posts/2025-09-03-kubernetes-1-34-sa-tokens-image-pulls-beta.md

Schedules https://github.com/kubernetes/website/pull/51305 for publication on Wednesday, 3rd September, 2025.

Schedule KEP-4412 blog for publication

---

content/fa/docs/tutorials/cluster-management/_index.md
content/fa/docs/tutorials/cluster-management/kubelet-standalone.md
content/fa/docs/tutorials/cluster-management/namespaces-walkthrough.md

Add Persian Translation For content/fa/docs/tutorials/cluster-management

[fa] Add Persian translation for content/fa/docs/tutorials/cluster-management/

---

content/id/docs/concepts/cluster-administration/system-metrics.md

Update the "What's next" section in the Indonesian system-metrics page to correct the Prometheus text format link.
Fixes #52091

[id] Correct Prometheus text format link in system-metrics page

---

content/en/docs/concepts/storage/volumes.md

Fixes #51495 
This PR updates broken volume example links for:
- Fibre Channel
- ISCSI
- NFS
- Portworx
These folders were removed from the upstream kubernetes/examples repo. I’ve updated the links accordingly.

Fix broken example volume links

---

content/en/docs/reference/instrumentation/understand-psi-metrics.md

Followup of https://github.com/kubernetes/website/pull/51541
Some enhancement and fix to the "understanding PSI" doc:
1. Add CPU resource requests and limits to the example CPU stress pod to produce more reliable CPU stress. This is a best practice that we're also [adding to the k/k E2E test](https://github.com/kubernetes/kubernetes/pull/133473). Also see evidence of PSI results for pods [without the limit](https://gist.github.com/roycaihw/2f9e256cede94be24fffa9c0a74d94ec) v.s. [with the limit](https://gist.github.com/roycaihw/a600c9a5e9d461a53b6b0257ed31a8b1). Users will observe more visible PSI data for the latter. 
1. Fix PSI Prometheus metrics grep regex so that users can correctly query the metrics for the target containers. This was an oversight in the doc. See …

Enhance PSI example CPU stress pod; fix PSI Prometheus metrics grep regex

---

content/en/docs/reference/node/seccomp.md

There was a small typo in the documentation, it says 'ephermal' instead of 'ephemeral'
Closes: #52149

Fix typo on seccomp documentation

---

content/pl/docs/contribute/generate-ref-docs/metrics-reference.md

[pl] docs/contribute/generate-ref-docs/metrics-reference.md

---

content/en/docs/reference/node/seccomp.md

Fixed the typo in seccomp documentation page.
Changed the word "ephermal" to "ephemeral"
https://github.com/kubernetes/website/issues/52149
Closes: #

Fixing typo in seccomp.md

---

content/uk/includes/task-tutorial-prereqs.md

Sync content/uk/includes/task-tutorial-prereqs.md with upstream
https://github.com/kubernetes/website/blob/5622fb7bedbd3253d643f96f00b3fe2a80bd85c3/content/en/includes/task-tutorial-prereqs.md?plain=1#L7

[uk] sync task-tutorial-prereqs.md

---

assets/scss/_base.scss

Due to `width: 100vw;` in `#video`, this block doesn't fit a normal screen width in Chrome/Linux, and an unnecessary horizontal scroll appears:
Removing this style leaves the video at 100% width, with no scrolling involved. I checked it in Firefox and Chrome in Linux (including small screens), but validating this change in other browsers/platforms will be much appreciated.

Fix video width/horizontal scroll on the main page

---

content/en/docs/setup/production-environment/tools/kubeadm/high-availability.md

Adds a note to the kubeadm high-availability setup guide advising users to restart the CoreDNS Deployment to redistribute Pods after additional control plane nodes join.
Inserted the same coredns rebalance note from https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-linux-nodes/ after additional control plane add instructions
Removes parallel join note 
Closes: #52089

Add CoreDNS rebalance note to kubeadm HA guide + remove parallel join note

---

content/zh-cn/blog/_posts/2025-09-16-volume-group-snapshot-beta-2.md

content/zh-cn/blog/_posts/2025-08-27-volume-group-snapshot-beta-2.md

[zh] Add a blog: 2025-09-16-volume-group-snapshot-beta-2.md

---

content/pt-br/docs/tutorials/hello-minikube.md

Este PR traz a atualização da página  https://kubernetes.io/pt-br/docs/tutorials/hello-minikube/ para sync com a versão EN.
Caminho da página PT-BR no repositório: `content/pt-br/docs/tutorials/hello-minikube.md`
Caminho da página EN no repositório: `content/en/docs/tutorials/hello-minikube.md`
---
This PR brings the update to the page https://kubernetes.io/pt-br/docs/tutorials/hello-minikube/ to sync with the EN version.
PT-BR page path in the repository: `content/pt-br/docs/tutorials/hello-minikube.md`
EN page path in the repository: `content/en/docs/tutorials/hello-minikube.md`
Closes: #52304

[pt-br] Update /tutorials/hello-minikube.md

---

content/en/docs/reference/networking/virtual-ips.md

OK, so the status of the kube-proxy ipvs backend is:
- It's faster than iptables in large clusters.
- It works on older Linux distros, unlike nftables
- It doesn't implement some corner cases of Service functionality correctly, and this is not likely to ever be fixed, because most remaining fixes would require heavy rearchitecting of the code, and all of the people in SIG Network who used to care about fixing ipvs bugs have drifted away, and the SIG leads would rather push people toward nftables than try to figure out how to fix ipvs.
So this tries to explain that some. I'm not particularly attached to any of the specific text here; consider this a starting point.
Fixes #51917
/assign @lmktfy @aojea 
/sig network

Try to clarify the status of ipvs kube-proxy

---

content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

#52027 introduced new examples for systems using DNF5. One of the areas introduced incorrect indentation for the commands on this page: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
This PR fixes that:

Fix indentation of kubelet, kubeadm, kubectl install commands

---

content/en/docs/reference/instrumentation/metrics.md

Small follow up to https://github.com/kubernetes/website/pull/52334 to reflect the Deprecated Version of the `apiserver_storage_objects` metric. Corresponding change was already merged in k/k via https://github.com/kubernetes/kubernetes/pull/134030

Update deprecation version(1.34) for apiserver_storage_objects metric

---

content/en/docs/reference/access-authn-authz/authentication.md

Make https://kubernetes.io/docs/reference/access-authn-authz/authentication/ better:
align more to Kubernetes [style guide](https://kubernetes.io/docs/contribute/style/style-guide/) for documentation [[preview](https://deploy-preview-52412--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/authentication/)].
/kind cleanup
Split out from PR https://github.com/kubernetes/website/pull/50364

Clean up authn reference

---

content/ko/docs/concepts/overview/components.md

Sync Korean doc [/ko/docs/concepts/overview/components.md](https://kubernetes.io/ko/docs/concepts/overview/components) with the latest [English version](https://kubernetes.io/docs/concepts/overview/components).
Updated the contents to reflect recent changes in the upstream English document, ensuring consistency between the two versions.
Closes: #51935

[ko] Sync /ko/docs/concepts/overview/components.md to match latest en contents

---

content/zh-cn/docs/concepts/architecture/cri.md
content/zh-cn/docs/reference/glossary/cri.md

[https://kubernetes.io/zh-cn/docs/concepts/architecture/cri/](https://kubernetes.io/zh-cn/docs/concepts/architecture/cri/) Delete redundant comments and fixed the rendering issues.
Closes: #

[zh-cn] Delete redundant comments to fix rendering issues.

---

content/zh-cn/examples/dra/resourceclaimtemplate.yaml

fix cel expression in content/zh-cn/examples/dra/resourceclaimtemplate.yaml
sync with #52338

[zn-ch] fix cel expression in resourceclaimtemplate.yaml

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_create/_index.md

[zh-cn]sync kubectl_create/_index.md

---

content/zh-cn/docs/reference/kubectl/generated/kubectl_exec/_index.md

content/zh-cn/docs/reference/kubectl/generated/kubectl_exec/_index.md

[zh-cn]sync kubectl_exec/_index.md

---

content/pt-br/docs/reference/glossary/duration.md

/kind documentation
Tradução do documento "Duration" para português (pt-BR) no Kubernetes Docs.
Este PR adiciona a versão em português do conteúdo, mantendo a estrutura e links originais.
Closes: #52499
Primeiro PR de tradução para PT-BR.
```release-note
NONE

[pt-br] Add docs/reference/glossary/duration.md

---

content/en/docs/concepts/workloads/pods/pod-lifecycle.md

Edit:
Corrected some spelling mistakes in the Pod lifecycle documentation.
Changes:
EndppointSlice -> EndpointSlice
initialiaztion -> initialization
built in PodCondition -> built-in PodCondition

Fix typo: EndppointSlice -> EndpointSlice

---

content/ja/docs/reference/glossary/taint.md

Translate `content/en/docs/reference/glossary/taint.md` into Japanese
Closes: #50369
- https://github.com/kubernetes/website/issues/45972
- https://github.com/kubernetes/website/commits/main/content/en/docs/reference/glossary/taint.md

[ja] Translate content/en/docs/reference/glossary/taint.md into Japanese

---

content/en/docs/concepts/overview/working-with-objects/labels.md

This PR fixes broken link to the guestbook example in the following document:
content/en/docs/concepts/overview/working-with-objects/labels.md
The original link was pointing to the /guestbook directory, which has now been moved to /web/guestbook
[https://github.com/kubernetes/examples/tree/master/guestbook/](https://github.com/kubernetes/examples/tree/master/guestbook/)
These have been updated to point to the correct path:
[https://github.com/kubernetes/examples/tree/master/guestbook/](https://github.com/kubernetes/examples/tree/master/web/guestbook/)
no issue found
Closes: #

Fix broken link to guestbook example

---

content/ja/docs/concepts/cluster-administration/kube-state-metrics.md

Translated [/docs/concepts/cluster-administration/kube-state-metrics.md](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/kube-state-metrics.md) into Japanese.
Closes: #52541 
/language ja

[ja] Translated /docs/concepts/cluster-administration/kube-state-metrics.md into Japanese

---

content/en/blog/_posts/2025-09-18-dra-consumable-capacity.md
content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md

https://github.com/kubernetes/kubernetes/blob/2fc2c0a38df83f892d6c1010646ab1c4d2c7d95f/staging/src/k8s.io/api/resource/v1/types.go#L581-L586
```
// BoolValue is a true/false value.
//
// +optional
// +oneOf=ValueType
BoolValue *bool `json:"bool,omitempty" protobuf:"varint,3,opt,name=bool"`
```
https://github.com/kubernetes/kubernetes/blob/2fc2c0a38df83f892d6c1010646ab1c4d2c7d95f/staging/src/k8s.io/api/resource/v1/types.go#L783-L791
```
type DeviceRequest struct {
...
// Exactly specifies the details for a single request that must
// be met exactly for the request to be satisfied.
//
// One of Exactly or FirstAvailable must be set.
//
// +optional
// +oneOf=deviceRequestType
Exactly *ExactDeviceRequest `json:"exactly,omitempty" protobuf:"bytes,2,name=exactly"`
...
}
// ExactDeviceRequest …
```

fix dra resource slice example: boolean to bool

---

content/ko/docs/concepts/overview/components.md

Fixes a mistranslation in the Korean documentation for the kubelet component.
In the Korean documentation for the Node Components section, the kubelet description incorrectly says:
“파드와 그 안의 컨트롤러가 실행 중임을 보장한다.”
The word 컨트롤러 (“controller”) is a mistranslation.
The English source says “Ensures that Pods are running, including their containers.”
so it should say 컨테이너 (“container”) instead of 컨트롤러.
Closes: #52515

[ko] fix mistranslation in kubelet description

---

content/vi/blog/_index.md
content/vi/case-studies/_index.html
content/vi/community/_index.html
content/vi/docs/home/_index.md
content/vi/partners/_index.html

Update the front matter for Vietnamese pages so that if we align more with Docsy, the top nav still works how we want. Currently, the top nav sections are hard coded:
- https://github.com/kubernetes/website/blob/7fe1afd6140c97a2c6c5c30d5a0124f551a92e89/layouts/partials/navbar.html#L28
- https://github.com/kubernetes/website/blob/7fe1afd6140c97a2c6c5c30d5a0124f551a92e89/layouts/404.html#L9 
[Original](https://k8s.io/vi/) vs [preview](https://deploy-preview-52595--kubernetes-io-main-staging.netlify.app/vi/) (no visible difference; this is an enabling change)
Helps with issues https://github.com/kubernetes/website/issues/41171 and https://github.com/kubernetes/website/issues/50228

Update Vietnamese to support Docsy-style menus

---

content/en/docs/concepts/overview/working-with-objects/names.md

Correct RFC 1123 label names to require starting with alphabetic character to match the actual Kubernetes implementation regex [a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?.
Add note about RelaxedServiceNameValidation feature gate exception for Services.
Update explanation of RFC differences to reflect actual implementation where both RFC 1035 and RFC 1123 require starting with alphabetic characters, with the exception being the RelaxedServiceNameValidation feature gate for Service objects.
This addresses issue 52578.
Closes: #

docs: Fix RFC 1123 label names documentation

---

content/zh-cn/docs/concepts/workloads/controllers/statefulset.md

```
content/zh-cn/docs/concepts/workloads/controllers/statefulset.md
```
See [preview](https://deploy-preview-52363--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/controllers/statefulset/#revision-history)

[zh] Add text to controllers/statefulset.md

---

content/en/blog/_posts/2024-12-27-seven-kubernetes-pitfalls-and-how-to-avoid.md

This is a request to create a blog post that walks readers through seven common Kubernetes pitfalls, which can trip up both beginners and experienced practitioners.
Thanks in advance for your consideration.

Add blog article on 7 Common Kubernetes Pitfalls

---

content/de/docs/setup/best-practices/cluster-large.md

- Fix URL for [Überlegungen für große Cluster](https://kubernetes.io/de/docs/setup/best-practices/grosser-cluster/)
- Drop @lavalamp as reviewer
/language de
Fixup for PR https://github.com/kubernetes/website/pull/51995

[de] Fix large cluster guidelines page

---

content/de/docs/tasks/tools/install-kubectl.md

The German kubectl installation page still references the deprecated Google Cloud package repositories (packages.cloud.google.com), which were officially deprecated and frozen as of September 13, 2023. Users following these instructions may encounter issues or receive outdated packages.
Affected page- https://kubernetes.io/de/docs/tasks/tools/install-kubectl/
Replace deprecated packages.cloud.google.com URLs with official pkgs.k8s.io
repositories in German kubectl installation documentation.
- Update Ubuntu/Debian installation commands  
- Update CentOS/RHEL/Fedora installation comman
Closes: #51911

[de] Update kubectl installation to use new pkgs.k8s.io repositories

---

content/en/docs/tasks/run-application/horizontal-pod-autoscale.md

Change "behaviour" to "behavior" to match U.S English
https://kubernetes.io/docs/contribute/style/style-guide/#language

Fix typo in horizontal pod autoscale documentation
