- content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
> [zh-cn] sync pods/user-namespaces.md

- content/id/docs/tutorials/security/ns-level-pss.md
https://kubernetes.io/docs/tutorials/security/ns-level-pss/
> id: translate security tutorial pod security standards

- content/zh-cn/docs/reference/access-authn-authz/rbac.md
- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
- content/zh-cn/examples/access/simple-clusterrole.yaml
- content/zh-cn/examples/access/simple-role.yaml
content/zh-cn/examples/access/simple-clusterrole.yaml
content/zh-cn/examples/access/simple-role.yaml
> [zh-cn]sync rbac validating-admission-policy

- i18n/id/id.toml
> [id] Added "LinkedIn" to toml

- content/ja/blog/_posts/2024-03-01-sig-cloud-provider-spotlight.md
Sync [content/ja/blog/_posts/2024-03-01-sig-cloud-provider-spotlight.md](https://github.com/kubernetes/website/blob/main/content/ja/blog/_posts/2024-03-01-sig-cloud-provider-spotlight.md) with the content in [en](https://github.com/kubernetes/website/blob/main/content/ja/blog/_posts/2024-03-01-sig-cloud-provider-spotlight.md).
Closes: #45598
/language ja
> [ja] Translate blog: Spotlight on SIG Cloud Provider into Japanese

- i18n/ja/ja.toml
> [ja] Added "LinkedIn" to toml

- content/pl/docs/reference/_index.md
[pl] sync with PR #45916,#44349
additionally:
- add slight changes to synchronize the lines with the EN version
- add an explicit header ID
> [pl] sync with PR #45916,#44349

- i18n/pl/pl.toml
> [pl] Added "LinkedIn" to toml

- content/pl/docs/concepts/configuration/_index.md
> [pl] docs/concepts/configuration/_index.md

- content/pl/docs/reference/glossary/pod-disruption.md
> [pl] docs/reference/glossary/pod-disruption.md

- content/pl/docs/concepts/storage/_index.md
> [pl] docs/concepts/storage/_index.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/DisableAllocatorDualWrite.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/MultiCIDRServiceAllocator.md
- content/en/docs/reference/networking/virtual-ips.md
Multiple Service CIDRs #1880 - GA
https://github.com/kubernetes/enhancements/issues/1880
Closes: #
> Multiple Service CIDRs - KEP 1880

- content/en/docs/reference/command-line-tools-reference/feature-gates/DRAResourceClaimDeviceStatus.md
[KEP-4817] DRAResourceClaimDeviceStatus to Beta
> [KEP-4817] DRAResourceClaimDeviceStatus to Beta

- content/en/docs/reference/access-authn-authz/service-accounts-admin.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/ServiceAccountTokenNodeBinding.md
Doc updates for KEP-4193 GA
xref https://github.com/kubernetes/enhancements/issues/4193
/sig auth
/assign @munnerz
> KEP-4193: 1.33 updates for ServiceAccountTokenNodeBinding GA

- content/en/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundle.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundleProjection.md
Moves the CTBs to beta.
Related to https://github.com/kubernetes/enhancements/issues/3257
> bump ClusterTrustBundle FGs to beta

- content/ja/docs/concepts/workloads/management.md
Sync [content/ja/docs/concepts/workloads/management.md](https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/workloads/management.md) with the content in [en](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/management.md).
Closes: #47544
/language ja
> [ja] Translate content/en/docs/concepts/workloads/management.md into Japanese

- content/zh-cn/docs/reference/node/node-labels.md
content/zh-cn/docs/reference/node/node-labels.md
> [zh-cn]sync node-labels.md

- content/ja/docs/tasks/manage-daemon/rollback-daemon-set.md
Translate content/en/docs/tasks/manage-daemon/rollback-daemon-set.md
Closes: #50299
> [ja] Translate content/en/docs/tasks/manage-daemon/rollback-daemon-set.md

- content/en/docs/concepts/containers/images.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/kubelet-ensure-secret-pulled-images.md
- content/en/docs/reference/node/kubelet-files.md
Update documentation for `KubeletEnsureSecretPulledImages` alpha
KEP: https://github.com/kubernetes/enhancements/issues/2535
Related k/k PRs: https://github.com/kubernetes/kubernetes/pull/128152
> KEP 2535: Ensure Secret Pulled Images

- content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
- content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
> [zh-cn]sync assign-pod-node topology-spread-constraints user-namespaces

- content/en/docs/concepts/storage/projected-volumes.md
CTBs are beta in 1.33
Raised in https://github.com/kubernetes/website/pull/49955#pullrequestreview-2732055946
/assign dipesh-rawat
> fix: projected volumes: clustertrustbundle API is beta in 1.33+

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/DRAAdminAccess.md
- content/en/docs/reference/labels-annotations-taints/_index.md
- https://github.com/kubernetes/enhancements/issues/5018
- https://github.com/kubernetes/kubernetes/pull/130225
> 5018 dra admin access

- content/en/docs/concepts/services-networking/service.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/PreferSameTrafficDistribution.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/ServiceTrafficDistribution.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/TopologyAwareHints.md
- content/en/docs/reference/networking/virtual-ips.md
Update for PreferSameTrafficDistribution, and also update for ServiceTrafficDistribution and TopologyAwareHints becoming GA.
TopologyAwareHints still needs more updates, #50229
> KEP-3015 PreferSameNode TrafficDistribution 1.33

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/DRAPrioritizedList.md
k/k development PR: https://github.com/kubernetes/kubernetes/pull/128586
k/enhancement issue: https://github.com/kubernetes/enhancements/issues/4816
> Document DRA prioritized list(s)

- content/en/docs/reference/using-api/api-concepts.md
Placeholder PR for KEP-4988 documentation changes
https://github.com/kubernetes/enhancements/issues/4988
> KEP-4988 documentation changes

- content/en/docs/reference/command-line-tools-reference/feature-gates/OrderedNamespaceDeletion.md
Doc update PR for KEP 5080
Closes: #
> KEP-5080: OrderedNamespaceDeletion

- content/zh-cn/blog/_posts/2024-05-09-gateway-api-v1.1/index.md
Update a YAML by following english upstream:
```
content/zh-cn/blog/_posts/2024-05-09-gateway-api-v1.1/index.md
```
> [zh] Update 2024-05-09-gateway-api-v1.1/index.md

- content/zh-cn/docs/contribute/new-content/_index.md
- content/zh-cn/docs/contribute/new-content/case-studies.md
```
modified:   content/zh-cn/docs/contribute/new-content/_index.md
added:  content/zh-cn/docs/contribute/new-content/case-studies.md
```
> [zh] Add new-content/case-studies.md and update _index.md

- content/zh-cn/blog/_posts/2024-08-14-pv-last-phase-transition-time-ga.md
- content/zh-cn/docs/concepts/storage/persistent-volumes.md
sync file:
```
content/zh-cn/blog/_posts/2024-08-14-pv-last-phase-transition-time-ga.md
```
> [zh-cn] sync blog file 2024-08-14-pv-last-phase-transition-time-ga.md

- content/zh-cn/docs/contribute/review/for-approvers.md
`
content/zh-cn/docs/contribute/review/for-approvers.md
`
> [zh-cn] sync review/for-approvers.md

- content/en/docs/reference/access-authn-authz/admission-controllers.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/PodTopologyLabelsAdmission.md
Add documentation for KEP 4742
KEP: https://github.com/kubernetes/enhancements/issues/4742
K/K: https://github.com/kubernetes/kubernetes/pull/127092
> 4742 Expose Node Labels in Downward API Docs

- content/id/docs/tutorials/security/cluster-level-pss.md
- content/id/examples/security/example-baseline-pod.yaml
- content/id/examples/security/kind-with-cluster-level-baseline-pod-security.sh
translate https://kubernetes.io/docs/tutorials/security/cluster-level-pss/ to ID
> id: translate tutorial pod security

- content/id/docs/tutorials/security/_index.md
https://kubernetes.io/docs/tutorials/security/
> id: translate index page on security tutorial

- content/en/docs/reference/command-line-tools-reference/feature-gates/SchedulerAsyncPreemption.md
doc update to graduate the async preemption feature to beta
https://github.com/kubernetes/enhancements/issues/4832
> KEP-4832: graduate the async preemption feature to beta

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/DRAPartitionableDevices.md
k/k development PR: https://github.com/kubernetes/kubernetes/pull/129140
k/enhancement issue: https://github.com/kubernetes/enhancements/issues/4815
> Document DRA partitionable devices

- content/zh-cn/docs/contribute/review/reviewing-prs.md
```
content/zh-cn/docs/contribute/review/reviewing-prs.md
```
> [zh] Sync review/reviewing-prs.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/JobPodFailurePolicy.md
k/k: https://github.com/kubernetes/kubernetes/pull/129498
/hold
> mark JobPodFailurePolicy as removed

- content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md
- content/zh-cn/docs/reference/kubectl/jsonpath.md
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md
content/zh-cn/docs/reference/kubectl/jsonpath.md
```
> [zh] Sync kubectl/jsonpath.md and kubectl_get/

- content/zh-cn/docs/tasks/administer-cluster/declare-network-policy.md
src: ([#49937](https://github.com/kubernetes/website/pull/49937))
`
content/zh-cn/docs/tasks/administer-cluster/declare-network-policy.md
`
> [zh-cn] Sync declare-network-policy.md

- content/ko/docs/concepts/architecture/leases.md
https://github.com/kubernetes/website/pull/49475/files
> [ko] fix: typo in leases.md

- content/en/docs/reference/config-api/kubeadm-config.v1beta4.md
This PR updates the code snippet to be YAML, using updated config file source code and generator.
Supersedes: #50448
> Update the kubeadm config v1beta4 for readability

- content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
https://github.com/kubernetes/website/pull/50043/files
> [pt] Update the check for open port in install-kubeadm.md

- content/pt-br/docs/concepts/containers/images.md
Esse PR traz a atualização da localização da página https://kubernetes.io/pt-br/docs/concepts/containers/images/ para **PT-BR**.
Caminho no projeto: content/pt-br/docs/concepts/containers/images.md
---
This PR updates the localization of the page https://kubernetes.io/pt-br/docs/concepts/containers/images/ to **PT-BR**.
Path in project: content/pt-br/docs/concepts/containers/images.md
Closes: #50120
> [pt-br] Update concepts/containers/images

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1.md
> [zh-cn]sync config-map-v1

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
- content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
- content/zh-cn/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md
> [zh-cn]sync extend-resources/*

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md
```
M       content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v1.md
M       content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md
M       content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md
```
> [zh-cn]sync horizontal-pod-autoscaler-* job-v1

- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-binding-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-binding-v1.md
- content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-v1.md
```
M       content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-binding-v1.md
M       content/zh-cn/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1.md
M       content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-binding-v1.md
M       content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-v1.md
```
> [zh-cn]sync authorization-resources/*

- content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1.md
- content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
- content/zh-cn/docs/reference/kubernetes-api/service-resources/ingress-class-v1.md
- content/zh-cn/docs/reference/kubernetes-api/service-resources/ingress-v1.md
- content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> [zh-cn]sync service-resources/*

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/namespace-v1.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/lease-v1.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/namespace-v1.md
> [zh-cn]sync lease-v1 namespace-v1 node-v1

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
> [zh-cn]sync config-and-storage-resources/volume.md

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1beta1.md
content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1beta1.md
> [zh-cn] sync device-class-v1beta1.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-slice-v1beta1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-slice-v1beta1.md
> [zh-cn]sync resource-slice-v1beta1.md

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> [zh-cn] sync persistent-volume-v1.md

- content/zh-cn/docs/concepts/cluster-administration/admission-webhooks-good-practices.md
content/zh-cn/docs/concepts/cluster-administration/admission-webhooks-good-practices.md
> [zh-cn]sync admission-webhooks-good-practices

- content/id/docs/reference/issues-security/OWNERS
- content/id/docs/reference/issues-security/_index.md
- content/id/docs/reference/issues-security/issues.md
- content/id/docs/reference/issues-security/official-cve-feed.md
- content/id/docs/reference/issues-security/security.md
Translate https://kubernetes.io/docs/reference/issues-security/security/ into ID.
> id: translate issues-security into ID

- content/de/docs/concepts/cluster-administration/addons.md
> [de] Fixed link for core dns helm charts

- content/id/docs/concepts/security/application-security-checklist.md
initial commit
translate: https://kubernetes.io/docs/concepts/security/application-security-checklist/ into Indonesian language.
> id: translate application security checklist

- content/zh-cn/docs/contribute/blog/_index.md
```
content/zh-cn/docs/contribute/blog/_index.md
```
> [zh] Add contribute/blog/_index.md

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/flow-schema-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/limit-range-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/priority-level-configuration-v1.md
- content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
```
content/zh-cn/docs/reference/kubernetes-api/policy-resources/flow-schema-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/limit-range-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/priority-level-configuration-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
```
> [zh] Sync kubernetes-api/policy-resources/*

- layouts/shortcodes/blocks/case-studies.html
Updates the case studies link to use the `RelPermalink`
NONE
> Updates case studies link

- content/en/blog/_posts/2025-04-11-multicontainer-patterns/index.md
Add blog post about Kubernetes sidecar patterns
> blog: add Kubernetes sidecar patterns

- data/releases/schedule.yaml
Add March 2025 and delay April 2025 releases
/assign @saschagrunert 
> Add March 2025 and delay April 2025 releases

- content/ko/includes/task-tutorial-prereqs.md
> [ko] add new playground to kubernetes documentation

- content/ko/docs/tasks/debug/debug-cluster/crictl.md
https://github.com/kubernetes/website/pull/49981/files
> [ko] Remove broken hyperlink

- content/ko/docs/reference/using-api/client-libraries.md
https://github.com/kubernetes/website/pull/49528/files
> [ko] Add cloudcoil to client libraries

- content/ko/docs/concepts/workloads/controllers/deployment.md
https://github.com/kubernetes/website/pull/49600/files
> [ko] fix: code block typo in deployment.md

- content/ko/docs/concepts/security/overview.md
> [ko] Fix VMware link

- content/ko/docs/concepts/cluster-administration/system-traces.md
https://github.com/kubernetes/website/pull/49526/files
> [ko] Fix OpenTelemetry Protocol hyperlink

- i18n/ko/ko.toml
> [ko] Added "LinkedIn" to toml

- content/ja/includes/task-tutorial-prereqs.md
> [ja] add new playground to kubernetes documentation

- content/zh-cn/docs/contribute/blog/buddying.md
content/zh-cn/docs/contribute/blog/buddying.md
> [zh-cn] add contribute/blog/buddying.md

- content/zh-cn/docs/contribute/blog/mirroring.md
content/zh-cn/docs/contribute/blog/mirroring.md
> [zh-cn]Add contribute/blog/mirroring.md

- content/zh-cn/docs/contribute/blog/release-comms.md
content/zh-cn/docs/contribute/blog/release-comms.md
> [zh-cn]Add contribute/blog/release-comms.md

- content/vi/docs/reference/glossary/device-plugin.md
Add Vietnamese translation for Device Plugin glossary
NONE
> [vi] add Vietnamese translation for Device Plugin glossary

- content/vi/includes/task-tutorial-prereqs.md
Update Vietnamese translation to match current English content
NONE
> [vi] update translation for task-tutorial-prereqs

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/controller-revision-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-template-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/replication-controller-v1.md
Update 3 files:
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/controller-revision-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-template-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/replication-controller-v1.md
```
> [zh] controller-revision-v1, pod-template-v1, replication-controller-v1

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/deployment-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
Update 2 files:
```
content/zh-cn/docs/reference/kubernetes-api/workload-resources/deployment-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
```
> [zh] Sync workload-resources/deployment-v1, priority-class-v1

- content/vi/docs/setup/_index.md
- content/vi/docs/setup/production-environment/_index.md
- content/vi/docs/setup/production-environment/tools/_index.md
- content/vi/docs/setup/production-environment/tools/kubeadm/_index.md
- content/vi/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
- i18n/vi/vi.toml
Hi anh @khanhtc1202 ,
Em có bổ sung thêm 2 page `Production environment` và `Setup HA etcd with kubeadm`.
Nhờ anh hỗ trợ em review và approve ạ.
Em xin cảm ơn!
> [vi] add Production environment + Setup HA etcd with kubeadm

- content/vi/releases/release-managers.md
> Remove GitHub team mention from Release Managers docs in Vietnamese

- content/en/docs/concepts/security/multi-tenancy.md
- content/en/docs/setup/production-environment/_index.md
xref https://github.com/kubernetes/website/pull/50519 https://github.com/kubernetes/org/issues/5484#issuecomment-2809749464
/assign @enj
> Remove references to archived HNC project

- content/ru/includes/task-tutorial-prereqs.md
> [ru] add new playground to kubernetes documentation

- content/zh-cn/docs/tutorials/_index.md
> [zh-cn] fix url

- content/zh-cn/docs/concepts/security/multi-tenancy.md
Sync with en #50544 
```
content/zh-cn/docs/concepts/security/multi-tenancy.md
```
> [zh] Sync security/multi-tenancy.md

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-node-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1.md
Update 4 files:
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-node-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-storage-capacity-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1.md
```
> [zh] Sync csi-driver-v1, csi-node-v1, csi-storage-capacity-v1, secret-v1

- content/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
Sync with en #50375. Add zh text to:
```
```
> [zh] Update kubeadm/install-kubeadm.md

- OWNERS_ALIASES
This PR adds @dipesh-rawat to the sig-docs-website-owners group so they can approve website code updates.
/cc @natalisucks @reylejano @divya-mohan0209
> Add dipesh-rawat to sig-docs-website-owners

- content/bn/includes/task-tutorial-prereqs.md
> [bn] add new playground to kubernetes documentation

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-version-migration-v1alpha1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attachment-v1.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attributes-class-v1beta1.md
Update 4 files:
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attachment-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attributes-class-v1beta1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/storage-version-migration-v1alpha1.md
```
> [zh] storage-class-v1, volume-attachment-v1, volume-attributes-class-v1beta1

- content/pt-br/docs/tasks/debug/debug-application/debug-running-pod.md
- content/pt-br/examples/application/nginx-with-request.yaml
Esse PR traz a localização da página https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/ para **PT-BR**.
Adicionado a raiz de `content/pt-br/docs/tasks/debug/debug-application/` o arquivo `debug-running-pod.md`, ficando localizado como `content/pt-br/docs/tasks/debug/debug-application/debug-running-pod.md` no repositório.
Também foi adicionado o arquivo de exemplo `nginx-with-request.yaml` em `content/pt-br/examples/application/` sendo uma cópia de `content/en/examples/application/nginx-with-request.yaml`.
---
This PR brings the localization of the page https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/ to **PT-BR**.  
The file `debug-running-pod.md` was added to the root of `content/pt-br/docs/tasks/debug/debug-application/`, making it …
> [pt-br] Add /tasks/debug/debug-application/debug-running-pod.md

- content/fr/includes/task-tutorial-prereqs.md
> [fr] add new playground to kubernetes documentation

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WatchList.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WatchList.md
> [zh-cn]sync feature-gates/WatchList

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/binding-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/binding-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
> [zh-cn]sync binding-v1.md cron-job-v1.md

- content/en/blog/_posts/2025-04-22-multicontainer-patterns/index.md
> Publish "blog: add Kubernetes sidecar patterns" post

- content/id/docs/concepts/security/security-checklist.md
Translate https://kubernetes.io/docs/concepts/security/security-checklist/ into Indonesian language.
> id: initiate translation for security-checklist into Indonesian language

- content/hi/application/cassandra/cassandra-service.yaml
- content/hi/application/cassandra/cassandra-statefulset.yaml
Cassandra Example sample app code for hindi 
Origin Content : https://github.com/kubernetes/website/tree/main/content/en/examples/application/cassandra
Closes: #https://github.com/kubernetes/website/issues/50524
> Example Cassandra app for Hindi content

- content/pl/docs/concepts/extend-kubernetes/api-extension/_index.md
EDIT:
the parent _index.md : #49784
> [pl] docs/concepts/extend-kubernetes/api-extension/_index.md

- hugo.toml
Updating hugo.toml for dev-1.33.
/hold until v1.33 release day.
> Updates v1.33 hugo.toml for dev-1.33

- content/ja/docs/concepts/security/service-accounts.md
fix typo 
service-accounts.md has typo
> [ja] fix typo in service-accounts

- hugo.toml
Updating hugo.toml for release v1.33.
/hold until v1.33 release day.
> Updates v1.30 hugo.toml for release v1.33

- content/en/blog/_posts/2025-04-24-endpoints-deprecation.md
This schedules #49976 for publication on Thursday, 24th April, 2025.
> Schedule KEP-4974 blog for publication

- content/hi/examples/application/job/cronjob.yaml
- content/hi/examples/application/job/indexed-job-vol.yaml
- content/hi/examples/application/job/indexed-job.yaml
- content/hi/examples/application/job/job-sidecar.yaml
- content/hi/examples/application/job/job-tmpl.yaml
- content/hi/examples/application/job/rabbitmq/Dockerfile
- content/hi/examples/application/job/rabbitmq/job.yaml
- content/hi/examples/application/job/rabbitmq/rabbitmq-service.yaml
- content/hi/examples/application/job/rabbitmq/rabbitmq-statefulset.yaml
- content/hi/examples/application/job/rabbitmq/worker.py
- content/hi/examples/application/job/redis/Dockerfile
- content/hi/examples/application/job/redis/job.yaml
- content/hi/examples/application/job/redis/redis-pod.yaml
- content/hi/examples/application/job/redis/redis-service.yaml
- content/hi/examples/application/job/redis/rediswq.py
- content/hi/examples/application/job/redis/worker.py
Adding Hindi content for example application job
Origin Content of Hpa : https://github.com/kubernetes/website/tree/main/content/en/examples/application/job
Closes: #
> [hi] job app

- content/hi/examples/application/guestbook/frontend-deployment.yaml
- content/hi/examples/application/guestbook/frontend-service.yaml
- content/hi/examples/application/guestbook/redis-follower-deployment.yaml
- content/hi/examples/application/guestbook/redis-follower-service.yaml
- content/hi/examples/application/guestbook/redis-leader-deployment.yaml
- content/hi/examples/application/guestbook/redis-leader-service.yaml
Adding Hindi content for example application guestbook
Origin Content of Hpa : https://github.com/kubernetes/website/tree/main/content/en/examples/application/guestbook
Closes: #
> [hi] guestbook app

- content/zh-cn/docs/reference/access-authn-authz/service-accounts-admin.md
> [zh-cn]sync service-accounts-admin.md

- content/zh-cn/docs/concepts/workloads/controllers/cron-jobs.md
- content/zh-cn/docs/concepts/workloads/pods/_index.md
> [zh-cn]sync workloads/pods/_index cron-jobs

- content/zh-cn/docs/tasks/configure-pod-container/security-context.md
content/zh-cn/docs/tasks/configure-pod-container/security-context.md
> [zh-cn]sync security-context.md

- content/zh-cn/docs/concepts/services-networking/service.md
- content/zh-cn/docs/concepts/services-networking/windows-networking.md
update text in:
```
content/zh-cn/docs/concepts/services-networking/windows-networking.md
```
> [zh] Sync services-networking/service.md and windows-networking.md

- content/zh-cn/docs/tasks/configure-pod-container/image-volumes.md
- content/zh-cn/docs/tasks/debug/debug-application/debug-service.md
- content/zh-cn/examples/pods/image-volumes-subpath.yaml
content/zh-cn/docs/tasks/configure-pod-container/image-volumes.md
content/zh-cn/docs/tasks/debug/debug-application/debug-service.md
content/zh-cn/examples/pods/image-volumes.yaml
content/zh-cn/examples/pods/image-volumes-subpath.yaml
> [zh-cn]sync image-volumes debug-service

- content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/_index.md
> [zh-cn]sync kubectl_apply/_index

- content/ja/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/ja/docs/concepts/scheduling-eviction/topology-spread-constraints.md
https://github.com/kubernetes/website/pull/50241/files
> [ja] Update API version

- content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md
- content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
> [zh-cn]sync user-namespaces admission-controllers

- content/zh-cn/docs/concepts/storage/storage-limits.md
- content/zh-cn/docs/concepts/storage/volumes.md
content/zh-cn/docs/concepts/storage/storage-limits.md
> [zh-cn]sync storage-limits volumes

- content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
> [zh-cn]sync kubelet-credential-provide

- content/zh-cn/docs/reference/using-api/declarative-validation.md
content/zh-cn/docs/reference/using-api/declarative-validation.md
> [zh-cn]sync declarative-validation.md

- content/zh-cn/docs/reference/kubernetes-api/authentication-resources/cluster-trust-bundle-v1beta1.md
- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/ip-address-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/cluster-trust-bundle-v1beta1.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/ip-address-v1.md
> [zh-cn]sync cluster-trust-bundle-v1beta1 ip-address-v1

- content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_get/_index.md
> [zh-cn]sync kubectl_get/_index

- content/zh-cn/blog/_posts/2025-04-07-kube-scheduler-simulator/index.md
content/zh-cn/blog/_posts/2025-04-07-kube-scheduler-simulator/index.md
> [zh-cn] Add blog: 2025-04-07-kube-scheduler-simulator

- content/en/blog/_posts/2025-04-29-hpa-configurable-tolerance.md
This schedules #50000 for publication on Tuesday, 29th April, 2025.
> Schedule KEP-4951 blog for publication

- content/hi/examples/application/mysql/mysql-configmap.yaml
- content/hi/examples/application/mysql/mysql-deployment.yaml
- content/hi/examples/application/mysql/mysql-pv.yaml
- content/hi/examples/application/mysql/mysql-services.yaml
- content/hi/examples/application/mysql/mysql-statefulset.yaml
Adding Hindi content for example application mysql
Origin Content of Hpa : https://github.com/kubernetes/website/tree/main/content/en/examples/application/mysql
Closes: #
> [hi] Mysql app

- content/hi/examples/application/mongodb/mongo-deployment.yaml
- content/hi/examples/application/mongodb/mongo-service.yaml
Adding Hindi content for example application mongodb
Origin Content of Hpa : https://github.com/kubernetes/website/tree/main/content/en/examples/application/mongodb
Closes: #
> [hi] Include MongoDB Application YAML files in Hindi localisation folder structure

- content/pl/docs/contribute/_index.md
- content/pl/docs/contribute/new-content/new-features.md
- content/pl/docs/contribute/suggesting-improvements.md
[pl] sync contribute/_index.md with PR #50092
> [pl] sync with PR #50092

- OWNERS_ALIASES
Follow up to https://github.com/kubernetes/website/pull/50580
I was using @sftim; now I'm @lmktfy.
> Add Tim Bannister access (new identity)

- content/en/blog/_posts/2025-05-19-in-place-pod-resize-beta.md
This schedules #50024 for publication on Monday, 19th May, 2025.
> Schedule KEP-1287 blog for publication

- content/zh-cn/docs/reference/node/kernel-version-requirements.md
- content/zh-cn/docs/reference/node/kubelet-files.md
```
content/zh-cn/docs/reference/node/kubelet-files.md
content/zh-cn/docs/reference/node/kernel-version-requirements.md
```
> [zh] Sync node/kubelet-files.md and kernel-version-requirements.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AnyVolumeDataSource.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AppArmor.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AppArmorFields.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/CPUManager.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/CRDValidationRatcheting.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/CSIMigrationPortworx.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundle.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundleProjection.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ContainerStopSignals.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/CoordinatedLeaderElection.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAAdminAccess.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAControlPlaneController.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRADeviceTaints.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAPartitionableDevices.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAPrioritizedList.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAResourceClaimDeviceStatus.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DisableAllocatorDualWrite.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DisableCloudProviders.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DisableKubeletCloudCredentialProviders.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DynamicProvisioningScheduling.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DynamicResourceAllocation.md
Update text in feature gates in A-D
> [zh] Update feature-gates/A*.md to D*.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/HPAConfigurableTolerance.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/HonorPVReclaimPolicy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ImageVolume.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/InPlacePodVerticalScaling.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/JobBackoffLimitPerIndex.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/JobPodFailurePolicy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/JobSuccessPolicy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletFineGrainedAuthz.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletPSI.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletServiceAccountTokenForCredentialProviders.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/MatchLabelKeysInPodAffinity.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/MultiCIDRServiceAllocator.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/MutableCSINodeAllocatableCount.md
Update text for feature gates H-M
> [zh] Sync feature-gates/H*.md to M*.md

- content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1beta2.md
```
content/zh-cn/docs/reference/kubernetes-api/extend-resources/device-class-v1beta2.md
```
> [zh] Sync device-class-v1beta2.md

- content/zh-cn/docs/reference/networking/virtual-ips.md
```
content/zh-cn/docs/reference/networking/virtual-ips.md
```
> [zh] Sync virtual-ips.md

- content/id/docs/contribute/localization_id.md
Update to https://github.com/kubernetes/website/pull/50550.
- Remove unnecessary fields in glossary tables.
- Provide updated examples in the "feature gate" translation guide.
- Use rendered emoji.
Closes: #
> [id] New localization proposal (Update 1)

- content/en/blog/_posts/XXXX-XX-XX-dra-133-update.md
Blog that provides updates on the changes in DRA for 1.33. This includes information about new features promoted to Beta, new Alpha features, and a short outline of the plans for DRA for 1.34.
Closes: #
> Blog with DRA updates in 1.33

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/NFTablesProxyMode.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/NodeInclusionPolicyInPodTopologySpread.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/OrderedNamespaceDeletion.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/PDBUnhealthyPodEvictionPolicy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/PersistentVolumeLastPhaseTransitionTime.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/PodLifecycleSleepActionAllowZero.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/PodObservedGenerationTracking.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/PodTopologyLabelsAdmission.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/PreferSameTrafficDistribution.md
Update text for feature gates N-P
> [zh] Sync feature-gates/N*.md to P*.md

- content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
https://github.com/kubernetes/website/pull/50241/files
> [ru] Update API version

- content/hi/examples/application/web/web-parallel.yaml
- content/hi/examples/application/web/web.yaml
Adding Hindi content for example application web
Origin Content of Hpa : https://github.com/kubernetes/website/tree/main/content/en/examples/application/web
Closes: #
> [hi] Add web app YAML samples for Hindi localization

- content/hi/examples/application/ssa/nginx-deployment-no-replicas.yaml
- content/hi/examples/application/ssa/nginx-deployment.yaml
Adding Hindi content for example application ssa
Origin Content of Hpa : https://github.com/kubernetes/website/tree/main/content/en/examples/application/ssa
Closes: #
> [hi] Add Server-Side Apply YAML samples for Hindi localization

- content/hi/examples/application/nginx/nginx-deployment.yaml
- content/hi/examples/application/nginx/nginx-svc.yaml
Adding Hindi content for example application nginx
Origin Content of Hpa : https://github.com/kubernetes/website/tree/main/content/en/examples/application/nginx
Closes: #
> [hi] Add nginx YAML samples for Hindi localization

- content/zh-cn/docs/contribute/blog/guidelines.md
content/zh-cn/docs/contribute/blog/guidelines.md
> [zh-cn]sync contribute/blog/guidelines.md

- content/ru/docs/concepts/workloads/pods/_index.md
https://github.com/kubernetes/website/pull/49685/files
> [ru] update SidecarContainers

- content/zh-cn/docs/tasks/configure-pod-container/assign-memory-resource.md
content/zh-cn/docs/tasks/configure-pod-container/assign-memory-resource.md
> [zh-cn]sync assign-memory-resource.md

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_plan.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade/kubeadm_upgrade_plan.md
> [zh-cn] sync kubeadm_upgrade_plan.md

- content/zh-cn/docs/concepts/cluster-administration/coordinated-leader-election.md
- **EN upstream**: `content/en/docs/concepts/cluster-administration/coordinated-leader-election.md`
- **Sync to**: `content/zh-cn/docs/concepts/cluster-administration/coordinated-leader-election.md`
```diff
$ scripts/lsync.sh content/zh-cn/docs/concepts/cluster-administration/coordinated-leader-election.md
diff --git a/content/en/docs/concepts/cluster-administration/coordinated-leader-election.md b/content/en/docs/concepts/cluster-administration/coordinated-leader-election.md
index 2bd831324a..1758bd7f5e 100644
--- a/content/en/docs/concepts/cluster-administration/coordinated-leader-election.md
+++ b/content/en/docs/concepts/cluster-administration/coordinated-leader-election.md
@@ -10,7 +10,7 @@ weight: 200
{{< feature-state …
```
> [zh] sync concepts/cluster-administration/coordinated-leader-election.md

- content/hi/examples/application/nginx-app.yaml
- content/hi/examples/application/nginx-with-request.yaml
Adding Hindi content for example application nginx
Origin Content of nginx : https://github.com/kubernetes/website/tree/main/content/en/examples/application/nginx
Closes: #
>   [hi] Add nginx app YAML samples for Hindi localization

- content/hi/examples/application/wordpress/mysql-deployment.yaml
- content/hi/examples/application/wordpress/wordpress-deployment.yaml
Adding Hindi content for example application wordpress
Origin Content of wordpress : https://github.com/kubernetes/website/tree/main/content/en/examples/application/wordpress
Closes: #
> [hi] Add wordpress app YAML samples for Hindi localization

- content/hi/examples/application/zookeeper/zookeeper.yaml
Adding Hindi content for example application zookeeper
Origin Content of zookeeper : https://github.com/kubernetes/website/tree/main/content/en/examples/application/zookeeper
Closes: #
>  [hi] Add zookeeper app YAML samples for Hindi localization

- content/hi/examples/application/php-apache.yaml
- content/hi/examples/application/shell-demo.yaml
- content/hi/examples/application/simple_deployment.yaml
Adding Hindi content for example application other
Origin Content of other : https://github.com/kubernetes/website/tree/main/content/en/examples/application/
Closes: #
>  [hi] Add other app YAML samples for Hindi localization

- content/en/docs/reference/networking/virtual-ips.md
- put glossary shortcode on a single line
- fix grammar issues
- provide bullets with consistent indentations
/kind cleanup
> Clean up networking/virtual-ips.md

- content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
content/zh-cn/docs/concepts/scheduling-eviction/api-eviction.md
> [zh-cn]sync api-eviction.md

- content/zh-cn/docs/concepts/workloads/controllers/deployment.md
- content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
sync
`content/zh-cn/docs/concepts/workloads/controllers/deployment.md`
`content/zh-cn/docs/concepts/workloads/controllers/replicaset.md`
> [zh-cn] sync replicaset.md and deployment.md

- content/zh-cn/docs/reference/networking/virtual-ips.md
> [zh] Sync networking/virtual-ips.md

- content/en/blog/_posts/2025-04-30-image-volume-beta/index.md
- content/en/blog/_posts/2025-05-09-streaming-list-responses/2025-05-09-streaming-list-responses.md
This schedules 
1. https://github.com/kubernetes/website/pull/49984 for publication on Wednesday, 30th April, 2025.
2. https://github.com/kubernetes/website/pull/49985 for publication on Friday, 9th May, 2025.
Closes: #
> Mark & reschedule blog articles for KEP-4639

- content/zh-cn/docs/concepts/storage/projected-volumes.md
https://github.com/kubernetes/website/pull/50420/files
> [zh] fix: projected volumes: clustertrustbundle API

- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1.md
> [zh-cn]sync csi-driver-v1

- content/zh-cn/docs/tasks/debug/debug-application/debug-pods.md
content/zh-cn/docs/tasks/debug/debug-application/debug-pods.md
> [zh-cn]sync debug-pods.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2.md
> [zh-cn]sync horizontal-pod-autoscaler-v2.md

- content/zh-cn/blog/_posts/2025-04-29-hpa-configurable-tolerance.md
content/zh-cn/blog/_posts/2025-04-29-hpa-configurable-tolerance.md
> [zh-cn]Add blog: 2025-04-29-hpa-configurable-tolerance.md

- content/zh-cn/blog/_posts/2025-05-19-in-place-pod-resize-beta.md
content/zh-cn/blog/_posts/2025-05-19-in-place-pod-resize-beta.md
> [zh-cn] Add blog: 2025-05-19-in-place-pod-resize-beta.md

- content/zh-cn/docs/concepts/services-networking/gateway.md
content/zh-cn/docs/concepts/services-networking/gateway.md
> [zh-cn]sync gateway.md

- content/en/blog/_posts/2025-04-29-image-volume-beta/index.md
- content/en/blog/_posts/2025-05-01-storage-capacity-scoring.md
- Bump up the one scheduled for 30th April to 29th, given the delay in review in other blogs
- Ensure the schedule is set with 10.30 am PST
> Update Feature Blog publication schedule

- content/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
[pl] sync with the latest EN version : content/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> [pl] sync cluster-intro.html with the latest EN version

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
> [zh-cn]sync pod-disruption-budget-v1.md

- content/zh-cn/docs/concepts/policy/node-resource-managers.md
content/zh-cn/docs/concepts/policy/node-resource-managers.md
> [zh-cn]sync node-resource-managers.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/job-v1.md
> [zh-cn]sync job-v1.md

- content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md
content/zh-cn/docs/reference/kubernetes-api/cluster-resources/node-v1.md
> [zh-cn]sync node-v1.md

- content/hi/examples/access/certificate-signing-request/clusterrole-approve.yaml
- content/hi/examples/access/certificate-signing-request/clusterrole-create.yaml
- content/hi/examples/access/certificate-signing-request/clusterrole-sign.yaml
- content/hi/examples/access/deployment-replicas-policy.yaml
- content/hi/examples/access/endpoints-aggregated.yaml
- content/hi/examples/access/image-matches-namespace-environment.policy.yaml
- content/hi/examples/access/simple-clusterrole.yaml
- content/hi/examples/access/simple-clusterrolebinding.yaml
- content/hi/examples/access/simple-role.yaml
- content/hi/examples/access/simple-rolebinding-with-clusterrole.yaml
- content/hi/examples/access/simple-rolebinding-with-role.yaml
- content/hi/examples/access/validating-admission-policy-audit-annotation.yaml
- content/hi/examples/access/validating-admission-policy-match-conditions.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples needs to be added here
Closes: #
> [hi] add example access

- content/id/docs/concepts/security/cloud-native-security.md
translate this page: https://kubernetes.io/docs/concepts/security/cloud-native-security/ into Indonesian language.
> id: initial commit on translate cloud-native-security into Bahasa Indonesia

- content/en/blog/_posts/2025-04-30-storage-capacity-scoring.md
- content/en/blog/_posts/2025-05-01-kubernetes-v1-33-dra-updates.md
- 2 blogs will be published a bit earlier than originally scheduled
- other blog schedule will need to be updated accordingly, but they will be handled separately
> Update publication schedule for Feature Blogs that are fully ready

- content/zh-cn/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
- content/zh-cn/docs/concepts/workloads/autoscaling.md
sync
`content/zh-cn/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md`
`content/zh-cn/docs/concepts/workloads/autoscaling.md`
> [zh-cn] sync apiserver-aggregation.md and autoscaling.md

- content/hi/examples/concepts/policy/limit-range/example-conflict-with-limitrange-cpu.yaml
- content/hi/examples/concepts/policy/limit-range/example-no-conflict-with-limitrange-cpu.yaml
- content/hi/examples/concepts/policy/limit-range/problematic-limit-range.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/concepts are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/concepts need to be added here
Closes: #50716
> [hi] add example concepts

- content/hi/examples/audit/audit-policy.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/audit are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/audit need to be added here
Closes: #50716
> [hi] add example audit

- content/hi/examples/application/deployment-patch.yaml
- content/hi/examples/application/deployment-retainkeys.yaml
- content/hi/examples/application/deployment-scale.yaml
- content/hi/examples/application/deployment-sidecar.yaml
- content/hi/examples/application/deployment-update.yaml
- content/hi/examples/application/deployment.yaml
Description
Adding Hindi content for example application deployment
Origin Content of deployment : https://github.com/kubernetes/website/tree/main/content/en/examples/application/deployment
Closes: #
>  [hi] Add deployment app YAML samples for Hindi localization

- content/en/docs/reference/instrumentation/metrics.md
Follow up to closure of https://github.com/kubernetes/kubernetes/issues/129761, where we marked the stability of prober_probe_total as BETA
https://github.com/kubernetes/website/issues/50751
Closes: #
> Update metrics docs after the bump for prober_probe_total to BETA

- content/zh-cn/blog/_posts/2025-04-23-jobs-successpolicy-goes-ga.md
```
content/zh-cn/blog/_posts/2025-04-23-jobs-successpolicy-goes-ga.md
```
See [preview](https://deploy-preview-50722--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2025/04/23/kubernetes-1-33-jobs-success-policy-goes-ga/)
> [zh] Add 2025-04-23-jobs-successpolicy-goes-ga.md

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/en/docs/concepts/workloads/controllers/job.md
I'm no longer involved in the project.
Part of https://github.com/kubernetes/community/issues/8428
> Update reviewers for scheduling and job controller

- content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> [zh-cn]sync service-v1.md

- content/zh-cn/docs/concepts/workloads/controllers/job.md
- content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
- content/zh-cn/docs/concepts/workloads/pods/downward-api.md
content/zh-cn/docs/concepts/workloads/controllers/replicaset.md
content/zh-cn/docs/concepts/workloads/pods/downward-api.md
> [zh-cn] sync job replicaset downward-api

- content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
- content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
content/zh-cn/docs/reference/kubernetes-api/workload-resources/daemon-set-v1.md
> [zh-cn]sync endpoints-v1 daemon-set-v1

- content/hi/examples/configmap/configmap-multikeys.yaml
- content/hi/examples/configmap/configmaps.yaml
- content/hi/examples/configmap/configure-pod.yaml
- content/hi/examples/configmap/env-configmap.yaml
- content/hi/examples/configmap/game-env-file.properties
- content/hi/examples/configmap/game.properties
- content/hi/examples/configmap/immutable-configmap.yaml
- content/hi/examples/configmap/new-immutable-configmap.yaml
- content/hi/examples/configmap/ui-env-file.properties
- content/hi/examples/configmap/ui.properties
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/configmap are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/configmap need to be added here
Closes:
> [hi] add example configmap

- content/fr/docs/tasks/administer-cluster/declare-network-policy.md
https://github.com/kubernetes/website/pull/49937/files
> [fr] Update busybox image

- content/es/docs/concepts/security/overview.md
https://github.com/kubernetes/website/pull/49920/files
> [es] Update VMware security link

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-join.md
https://github.com/kubernetes/website/pull/50533/files
> [zh] Fix typo in kubeadm-join.md

- content/pt-br/includes/task-tutorial-prereqs.md
> [pt] add new playground to kubernetes documentation

- OWNERS_ALIASES
so za can start reviewing and merging PR for sig-docs-id PRs.
Related PR on org:
https://github.com/kubernetes/org/pull/5489
> id: Add za in as owners and reviewers in sig-docs-id

- content/ru/_index.html
Bringing the recent changes from #50486 to the Russian localisation.
> [ru] Update KubeCon 2025 events after KubeCon EU

- content/hi/examples/deployments/deployment-with-capacity-reservation.yaml
- content/hi/examples/deployments/deployment-with-configmap-and-sidecar-container.yaml
- content/hi/examples/deployments/deployment-with-configmap-as-envvar.yaml
- content/hi/examples/deployments/deployment-with-configmap-as-volume.yaml
- content/hi/examples/deployments/deployment-with-configmap-two-containers.yaml
- content/hi/examples/deployments/deployment-with-immutable-configmap-as-volume.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/deployments are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/deployments need to be added here
Closes:
> [hi] add example deployments

- content/hi/examples/customresourcedefinition/shirt-resource-definition.yaml
- content/hi/examples/customresourcedefinition/shirt-resources.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/customresourcedefinition are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/customresourcedefinition need to be added here
Closes:
> [hi] add example customresourcedefinition

- content/zh-cn/docs/reference/access-authn-authz/validating-admission-policy.md
- content/zh-cn/examples/validatingadmissionpolicy/binding-with-param-prod.yaml
- content/zh-cn/examples/validatingadmissionpolicy/binding-with-param.yaml
> [zh] Sync validating-admission-policy.md

- content/fr/_index.html
Bringing the recent changes from #50486 to the French localisation.
> [fr] Update KubeCon 2025 events after KubeCon EU

- content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md
- content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
sync
`
content/zh-cn/docs/concepts/scheduling-eviction/scheduling-framework.md
`
`
`
> [zh-cn] Sync scheduling-framework.md and topology-spread-constraints.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/APIListChunking.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/AdmissionWebhookMatchConditions.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/AggregatedDiscoveryEndpoint.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/EfficientWatchResumption.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/KubeProxyDrainingTerminatingNodes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/RemainingItemCount.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/ValidatingAdmissionPolicy.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/VolumeCapacityPriority.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/WatchBookmark.md
We missed some updates to the feature gates in v1.33/v1.32.
> Update removed feature gates in v1.33/1.32

- content/zh-cn/blog/_posts/2025-04-11-multicontainer-patterns/index.md
content/zh-cn/blog/_posts/2025-04-11-multicontainer-patterns/index.md
> [zh-cn]Add blog: 2025-04-11-multicontainer-patterns

- content/zh-cn/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> [zh-cn]sync kubeadm-init.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/ListFromCacheSnapshot.md
> Add feature gate ListFromCacheSnapshot

- content/zh-cn/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
https://github.com/kubernetes/website/pull/50812/files
> [zh] update kompose link

- content/en/docs/reference/command-line-tools-reference/feature-gates/WinDSR.md
> Fix feature gate WinDSR

- content/en/docs/reference/command-line-tools-reference/feature-gates/ServiceAccountNodeAudienceRestriction.md
> Add missing feature gate ServiceAccountNodeAudienceRestriction

- content/zh-cn/docs/tutorials/kubernetes-basics/expose/expose-intro.md
```
content/zh-cn/docs/tutorials/kubernetes-basics/expose/expose-intro.md
```
> [zh] Sync expose/expose-intro.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/UserNamespacesSupport.md
> Fix feature gate UserNamespacesSupport

- content/hi/examples/mutatingadmissionpolicy/applyconfiguration-example.yaml
- content/hi/examples/mutatingadmissionpolicy/json-patch-example.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/mutatingadmissionpolicy are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/mutatingadmissionpolicy need to be added here
Closes:
> [hi] add example mutatingadmissionpolicy

- content/hi/examples/pods/commands.yaml
- content/hi/examples/pods/image-volumes-subpath.yaml
- content/hi/examples/pods/image-volumes.yaml
- content/hi/examples/pods/lifecycle-events.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods need to be added here
Closes:
> [hi] add example pod - Part 1

- content/vi/docs/concepts/containers/container-lifecycle-hooks.md
Update Vietnamese translation for Container Lifecycle Hooks page that was already outdated
Refs: 
- https://kubernetes.io/vi/docs/concepts/containers/container-lifecycle-hooks
- https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks
> [vi] Update Vietnamese translation for Container Lifecycle Hooks

- content/vi/docs/reference/glossary/app-container.md
- content/vi/docs/reference/glossary/init-container.md
- content/vi/docs/reference/glossary/sidecar-container.md
- content/vi/docs/reference/glossary/statefulset.md
- content/vi/docs/reference/glossary/workload.md
Add Vietnamese translation for glossary Statefulset, Workload, Init/Sidecar container, App container
Link: https://kubernetes.io/docs/reference/glossary/?fundamental=true
NONE
> [vi] Add Vietnamese translation for glossary Statefulset, Workload, Init/Sidecar container, App container

- content/vi/docs/reference/glossary/api-resource.md
- content/vi/docs/reference/glossary/kubernetes-api.md
- content/vi/docs/reference/glossary/object.md
Add Vietnamese translation for glossary API-resource, Kubernetes API & Object
Link: https://kubernetes.io/docs/reference/glossary/?fundamental=true
> [vi] Add Vietnamese translation for glossary API-resource, Kubernetes API & Object

- content/vi/docs/reference/glossary/contributor.md
- content/vi/docs/reference/glossary/member.md
- content/vi/docs/reference/glossary/sig.md
Add translation for glossary member, contributor, sig
NONE
> [vi] add translation for glossary member, contributor, sig

- content/vi/_index.html
Add case studies block to the homepage of Vi
Link: https://kubernetes.io/
NONE
> [vi] add case studies block to the homepage

- content/ko/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
https://github.com/kubernetes/website/pull/50812/files
> [ko] update kompose link

- content/ko/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/ko/docs/concepts/scheduling-eviction/topology-spread-constraints.md
https://github.com/kubernetes/website/pull/50241/files
> [ko] Update API version

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/APIListChunking.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AdmissionWebhookMatchConditions.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AggregatedDiscoveryEndpoint.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AllowParsingUserUIDFromCertAuth.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/EfficientWatchResumption.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeProxyDrainingTerminatingNodes.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ListFromCacheSnapshot.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/RemainingItemCount.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/StrictIPCIDRValidation.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/TopologyAwareHints.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ValidatingAdmissionPolicy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/VolumeCapacityPriority.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WatchBookmark.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WinDSR.md
```
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/APIListChunking.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AdmissionWebhookMatchConditions.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AggregatedDiscoveryEndpoint.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/EfficientWatchResumption.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeProxyDrainingTerminatingNodes.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/RemainingItemCount.md
modified:   content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/TopologyAwareHints.md
modified: …
```
> [zh] Sync several more feature gates

- content/zh-cn/docs/reference/config-api/kube-scheduler-config.v1.md
- content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
content/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3.md
> [zh-cn]sync kubeadm-config.v1beta3 kube-scheduler-config.v1

- content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
https://github.com/kubernetes/website/pull/50824/files
> [zh] cluster trust bundles: use correct version/feature maturity stage

- content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
- content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1.md
content/zh-cn/docs/reference/config-api/apiserver-audit.v1.md
content/zh-cn/docs/reference/config-api/kubelet-credentialprovider.v1.md
> [zh-cn]sync kubelet-credentialprovider.v1 apiserver-audit.v1

- content/hi/examples/mutatingadmissionpolicy/applyconfiguration-example.yaml
https://github.com/kubernetes/website/pull/50695/files
> [hi] Fix incorrect apiGroup for pods in MutatingAdmissionPolicy example

- content/hi/examples/pods/config/example-redis-config.yaml
- content/hi/examples/pods/config/redis-config
- content/hi/examples/pods/config/redis-pod.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/config are not similar to
https://github.com/kubernetes/website/tree/main/content/hi/examples/pods
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/config need to be added here
https://github.com/kubernetes/website/tree/main/content/hi/examples/pods
Closes:
> [hi] add example pod - config

- content/hi/examples/pods/qos/qos-pod-2.yaml
- content/hi/examples/pods/qos/qos-pod-3.yaml
- content/hi/examples/pods/qos/qos-pod-4.yaml
- content/hi/examples/pods/qos/qos-pod-5.yaml
- content/hi/examples/pods/qos/qos-pod.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/qos/  are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/qos/ need to be added here
Closes:
> [hi] add example pod - qos files

- content/hi/examples/pods/inject/dapi-envars-container.yaml
- content/hi/examples/pods/inject/dapi-envars-pod.yaml
- content/hi/examples/pods/inject/dapi-volume-resources.yaml
- content/hi/examples/pods/inject/dapi-volume.yaml
- content/hi/examples/pods/inject/dependent-envars.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/inject/  are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/inject/ need to be added here
https://github.com/kubernetes/website/tree/main/content/hi/examples/pods/inject/
Closes:
> [hi] add example pod - inject files starting with d*

- content/hi/examples/pods/inject/envars.yaml
- content/hi/examples/pods/inject/pod-multiple-secret-env-variable.yaml
- content/hi/examples/pods/inject/pod-secret-envFrom.yaml
- content/hi/examples/pods/inject/pod-single-secret-env-variable.yaml
- content/hi/examples/pods/inject/secret-envars-pod.yaml
- content/hi/examples/pods/inject/secret-pod.yaml
- content/hi/examples/pods/inject/secret.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/inject/  are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/inject/ need to be added here
https://github.com/kubernetes/website/tree/main/content/hi/examples/pods/inject/
Closes:
> [hi] add example pod - inject files

- content/hi/examples/pods/probe/exec-liveness.yaml
- content/hi/examples/pods/probe/grpc-liveness.yaml
- content/hi/examples/pods/probe/http-liveness.yaml
- content/hi/examples/pods/probe/pod-with-http-healthcheck.yaml
- content/hi/examples/pods/probe/pod-with-tcp-socket-healthcheck.yaml
- content/hi/examples/pods/probe/tcp-liveness-readiness.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/probe/  are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/probe/ need to be added here
Closes:
> [hi] add example pod - probe files

- content/hi/examples/pods/resource/cpu-request-limit-2.yaml
- content/hi/examples/pods/resource/cpu-request-limit.yaml
- content/hi/examples/pods/resource/extended-resource-pod-2.yaml
- content/hi/examples/pods/resource/extended-resource-pod.yaml
- content/hi/examples/pods/resource/pod-resize.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/resource/  are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/resource/ need to be added here
Closes:
> [hi] add example pod - resources files 1

- content/zh-cn/docs/tasks/network/reconfigure-default-service-ip-ranges.md
```
content/zh-cn/docs/tasks/network/reconfigure-default-service-ip-ranges.md
```
> [zh] Add reconfigure-default-service-ip-ranges.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DeclarativeValidation.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DeclarativeValidationTakeover.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DeploymentReplicaSetTerminatingReplicas.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletEnsureSecretPulledImages.md
Add 4 feature gates:
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DeclarativeValidation.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DeclarativeValidationTakeover.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DeploymentReplicaSetTerminatingReplicas.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletEnsureSecretPulledImages.md
```
> [zh] Add four feature gates

- content/en/docs/concepts/workloads/pods/pod-lifecycle.md
Add the following pod conditions to the list of conditions managed by the Kubelet:
- `DisruptionTarget`
- `PodResizePending`
- `PodResizeInProgress`
/sig node
/assign @natasha41575 @lmktfy
> Document additional pod condition types

- content/zh-cn/examples/mutatingadmissionpolicy/applyconfiguration-example.yaml
https://github.com/kubernetes/website/pull/50695/files
> [zh] Fix incorrect apiGroup for pods in MutatingAdmissionPolicy example

- content/hi/examples/pods/security/seccomp/ga/audit-pod.yaml
- content/hi/examples/pods/security/seccomp/ga/default-pod.yaml
- content/hi/examples/pods/security/seccomp/ga/fine-pod.yaml
- content/hi/examples/pods/security/seccomp/ga/violation-pod.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/security/seccomp/ga are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/security/seccomp/ga need to be added here
Closes:
> [hi] Add example files from the ga subfolder under pods/security/seccomp

- content/hi/examples/pods/security/seccomp/alpha/audit-pod.yaml
- content/hi/examples/pods/security/seccomp/alpha/default-pod.yaml
- content/hi/examples/pods/security/seccomp/alpha/fine-pod.yaml
- content/hi/examples/pods/security/seccomp/alpha/violation-pod.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/security/seccomp/alpha are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/security/seccomp/alpha need to be added here
Closes:
> [hi] Add example files from the alpha subfolder under pods/security/seccomp

- content/zh-cn/docs/reference/networking/ports-and-protocols.md
https://github.com/kubernetes/website/pull/47991/files
> [zh] Update ports-and-protocols.md

- content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> mark yaml examples as such to get syntax highlighting

- content/zh-cn/docs/concepts/containers/images.md
> [zh] Sync containers/images.md

- content/zh-cn/docs/concepts/workloads/pods/pod-lifecycle.md
- content/zh-cn/docs/tasks/configure-pod-container/resize-container-resources.md
- content/zh-cn/examples/pods/resource/pod-resize.yaml
sync
```
content/zh-cn/docs/tasks/configure-pod-container/resize-container-resources.md
```
> [zh-cn] sync pod-lifecycle.md and resize-container-resources.md

- content/hi/examples/pods/pod-with-affinity-preferred-weight.yaml
- content/hi/examples/pods/pod-with-node-affinity.yaml
- content/hi/examples/pods/pod-with-pod-affinity.yaml
- content/hi/examples/pods/pod-with-scheduling-gates.yaml
- content/hi/examples/pods/pod-with-toleration.yaml
- content/hi/examples/pods/pod-without-scheduling-gates.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/  are not similar to
Closes:
> [hi] add example Pods-with*

- content/hi/examples/pods/pod-configmap-env-var-valueFrom.yaml
- content/hi/examples/pods/pod-configmap-envFrom.yaml
- content/hi/examples/pods/pod-configmap-volume-specific-key.yaml
- content/hi/examples/pods/pod-configmap-volume.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/  are not similar to
Closes:
> [hi] add example Pods configmap

- content/hi/examples/pods/init-containers.yaml
- content/hi/examples/pods/share-process-namespace.yaml
- content/hi/examples/pods/simple-pod.yaml
- content/hi/examples/pods/two-container-pod.yaml
- content/hi/examples/pods/user-namespaces-stateless.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/  are not similar to
Closes:
> [hi] add example Pods part 1

- content/hi/examples/pods/topology-spread-constraints/one-constraint-with-nodeaffinity.yaml
- content/hi/examples/pods/topology-spread-constraints/one-constraint.yaml
- content/hi/examples/pods/topology-spread-constraints/two-constraints.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/topology-spread-constraints not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/topology-spread-constraints need to be added here
Closes:
> [hi] Add example files from examples/pods/topology-spread-constraints

- content/en/docs/reference/command-line-tools-reference/feature-gates/InformerResourceVersion.md
This gate is funny, and ridiculous.
It was introduced in v1.30 and not yet documented.
> Add feature gate InformerResourceVersion v1.32

- content/es/docs/concepts/security/overview.md
> [es] Fix VMware link

- i18n/es/es.toml
https://github.com/kubernetes/website/pull/50176/files
> [es] Added "LinkedIn" to toml

- content/zh-cn/docs/reference/labels-annotations-taints/_index.md
- content/zh-cn/docs/reference/labels-annotations-taints/audit-annotations.md
update text in:
```
content/zh-cn/docs/reference/labels-annotations-taints/audit-annotations.md
```
> [zh] Sync labels-annotations-taints/audit-annotations.md and _index.md

- content/zh-cn/docs/reference/access-authn-authz/rbac.md
> [zh-cn]sync rbac

- content/hi/examples/pods/pod-nginx-preferred-affinity.yaml
- content/hi/examples/pods/pod-nginx-required-affinity.yaml
- content/hi/examples/pods/pod-nginx-specific-node.yaml
- content/hi/examples/pods/pod-projected-svc-token.yaml
- content/hi/examples/pods/pod-rs.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/  are not similar to
Closes:
> [hi] add example Pods nginx

- content/hi/examples/pods/storage/nginx.conf
- content/hi/examples/pods/storage/projected-clustertrustbundle.yaml
- content/hi/examples/pods/storage/projected-secret-downwardapi-configmap.yaml
- content/hi/examples/pods/storage/projected-secrets-nondefault-permission-mode.yaml
- content/hi/examples/pods/storage/projected-service-account-token.yaml
- content/hi/examples/pods/storage/projected.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods/storage are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/pods/storage need to be added here
Closes:
> [hi] Add example files subfolder under pods/storage part 2

- data/releases/schedule.yaml
Update the Kubernetes Release Schedule
Closes: None
/assign @saschagrunert @cpanato @xmudrii 
cc: @kubernetes/release-engineering
> 2025 May: Update Release Schedule for further months

- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_env.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_env.md
> [zh-cn]sync kubectl_set_env.md

- content/zh-cn/docs/tasks/administer-cluster/access-cluster-api.md
content/zh-cn/docs/tasks/administer-cluster/access-cluster-api.md
> [zh-cn]sync access-cluster-api.md

- content/zh-cn/docs/tasks/debug/debug-cluster/audit.md
Sync with en #49809 
```
content/zh-cn/docs/tasks/debug/debug-cluster/audit.md
```
> [zh] Sync debug-cluster/audit.md

- content/ja/docs/concepts/workloads/autoscaling.md
Update content/ja/docs/concepts/workloads/autoscaling.md
en: https://kubernetes.io/docs/concepts/workloads/autoscaling/
ja: https://kubernetes.io/ja/docs/concepts/workloads/autoscaling/
以下のPRの取り込み
- https://github.com/kubernetes/website/pull/45802/files
- https://github.com/kubernetes/website/pull/48503/files
- https://github.com/kubernetes/website/pull/50290/files
その他
- `tille:`を`title:`に修正
- 日本語ページが存在するリンクを更新
- 不要な空白や長音記号の削除、括弧を半角に修正、長い文に読点を挿入など
Closes: #50895
> [ja] Update content/ja/docs/concepts/workloads/autoscaling.md

- content/hi/examples/priorityclass/low-priority-class.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/priorityclass are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/priorityclass need to be added here
Closes:
> [hi] add example priorityclass

- content/hi/examples/pods/pod-multiple-configmap-env-variable.yaml
- content/hi/examples/pods/pod-nginx.yaml
- content/hi/examples/pods/pod-single-configmap-env-variable.yaml
- content/hi/examples/pods/private-reg-pod.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/pods not similar to
Closes:
> [hi] add example Pods remaining yamls

- content/hi/examples/priority-and-fairness/health-for-strangers.yaml
- content/hi/examples/priority-and-fairness/list-events-default-service-account.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/priority-and-fairness are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/priority-and-fairness need to be added here
Closes:
> [hi] add example priority-and-fairness

- content/hi/examples/secret/basicauth-secret.yaml
- content/hi/examples/secret/bootstrap-token-secret-base64.yaml
- content/hi/examples/secret/bootstrap-token-secret-literal.yaml
- content/hi/examples/secret/dockercfg-secret.yaml
- content/hi/examples/secret/serviceaccount/mysecretname.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/secret are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/secret need to be added here
Closes:
> [hi] Add example files under Secret subfolder

- content/hi/examples/policy/priority-class-resourcequota.yaml
- content/hi/examples/policy/privileged-psp.yaml
- content/hi/examples/policy/quota-vac.yaml
- content/hi/examples/policy/quota.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/policy not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/policy/ need to be added here
Closes:
> [hi] add example policy Part 2

- content/hi/examples/policy/baseline-psp.yaml
- content/hi/examples/policy/example-psp.yaml
- content/hi/examples/policy/gold-vac-pvc.yaml
- content/hi/examples/policy/high-priority-pod.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/policy not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/policy/ need to be added here
Closes:
> [hi] add example policy part 1

- content/en/docs/reference/using-api/deprecation-guide.md
Updated deprecation guide for v1.32 
Closes: #50937
> Updated deprecation guide for v1.32

- content/zh-cn/docs/reference/using-api/api-concepts.md
> [zh-cn]sync api-concepts

- content/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters.md
- content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attachment-v1.md
content/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume-attachment-v1.md
> [zh-cn]sync common-parameters volume-attachment-v1

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ServiceTrafficDistribution.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ServiceTrafficDistribution.md
> [zh-cn]sync ServiceTrafficDistribution

- content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_resources.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_subject.md
```
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_explain/_index.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_resources.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_subject.md
```
> [zh-cn]sync kubectl_set/* kubectl_explain

- content/zh-cn/docs/reference/kubectl/generated/kubectl_describe/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_describe/_index.md
> [zh-cn]sync kubectl_describe kubectl_edit

- content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_view-last-applied.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_pause.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_restart.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_resume.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status.md
```
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_apply/kubectl_apply_view-last-applied.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_pause.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_restart.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_resume.md
M       content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_status.md
```
> [zh-cn]sync kubectl_rollout/* kubectl_apply

- content/zh-cn/docs/reference/config-api/kubelet-config.v1alpha1.md
content/zh-cn/docs/reference/config-api/kubelet-config.v1alpha1.md
> [zh-cn]sync kubelet-config.v1alpha1.md

- content/zh-cn/docs/reference/kubernetes-api/common-definitions/delete-options.md
content/zh-cn/docs/reference/kubernetes-api/common-definitions/delete-options.md
> [zh-cn]sync delete-options.md

- content/zh-cn/examples/admin/sched/my-scheduler.yaml
https://github.com/kubernetes/website/pull/50908/files
> [zh] Replace deprecated API version

- content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
content/zh-cn/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md
> [zh-cn]sync kube-controller-manager-config.v1alpha1

- content/pl/_index.html
- content/pl/case-studies/_index.html
[pl] sync content/pl/_index.html with PR #50486
> [pl] sync with PR #50486

- content/pt-br/docs/tasks/run-application/access-api-from-pod.md
Esse PR traz a localização da página https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/ para **PT-BR**.
Adicionado a raiz de `/content/pt-br/docs/tasks/run-application` o arquivo `access-api-from-pod.md`, ficando localizado como `/content/pt-br/docs/tasks/run-application/access-api-from-pod.md` no repositório.
---
This PR adds the localization of the page https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/ to **PT-BR**.
The file `access-api-from-pod.md` was added to the root of `/content/pt-br/docs/tasks/run-application`, resulting in the path `/content/pt-br/docs/tasks/run-application/access-api-from-pod.md` in the repository.
Closes: #50137
> [pt-br] Add /tasks/run-application/access-api-from-pod.md

- content/zh-cn/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
sync
`content/zh-cn/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md`
> [zh-cn] Sync update-api-object-kubectl-patch.md

- content/hi/examples/security/example-baseline-pod.yaml
- content/hi/examples/security/kind-with-cluster-level-baseline-pod-security.sh
- content/hi/examples/security/kind-with-namespace-level-baseline-pod-security.sh
- content/hi/examples/security/podsecurity-baseline.yaml
- content/hi/examples/security/podsecurity-privileged.yaml
- content/hi/examples/security/podsecurity-restricted.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/security are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/security need to be added here
Closes:
> [hi] add example security

- content/hi/examples/service/access/Dockerfile
- content/hi/examples/service/access/backend-deployment.yaml
- content/hi/examples/service/access/backend-service.yaml
- content/hi/examples/service/access/frontend-deployment.yaml
- content/hi/examples/service/access/frontend-nginx.conf
- content/hi/examples/service/access/frontend-service.yaml
- content/hi/examples/service/access/hello-application.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/service/access are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/service/access need to be added here
Closes:
> [hi] add example service/access

- content/hi/examples/service/networking/default-ingressclass.yaml
- content/hi/examples/service/networking/dual-stack-default-svc.yaml
- content/hi/examples/service/networking/dual-stack-ipfamilies-ipv6.yaml
- content/hi/examples/service/networking/dual-stack-ipv6-svc.yaml
- content/hi/examples/service/networking/dual-stack-prefer-ipv6-lb-svc.yaml
- content/hi/examples/service/networking/dual-stack-preferred-ipfamilies-svc.yaml
- content/hi/examples/service/networking/dual-stack-preferred-svc.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/networking are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/networking need to be added here
Closes:
> [hi] add example service/networking part 2

- content/hi/examples/service/networking/ingress-resource-backend.yaml
- content/hi/examples/service/networking/ingress-wildcard-host.yaml
- content/hi/examples/service/networking/minimal-ingress.yaml
- content/hi/examples/service/networking/name-virtual-host-ingress-no-third-host.yaml
- content/hi/examples/service/networking/name-virtual-host-ingress.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/networking are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/networking need to be added here
Closes:
> [hi] add example service/networking part 3

- content/hi/examples/service/networking/nginx-policy.yaml
- content/hi/examples/service/networking/nginx-secure-app.yaml
- content/hi/examples/service/networking/nginx-svc.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/networking are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/networking need to be added here
Closes:
> [hi] add example service/networking part 5

- content/hi/examples/service/networking/run-my-nginx.yaml
- content/hi/examples/service/networking/simple-fanout-example.yaml
- content/hi/examples/service/networking/test-ingress.yaml
- content/hi/examples/service/networking/tls-example-ingress.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/networking are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/networking need to be added here
Closes:
> [hi] add example service/networking part 6

- content/hi/examples/service/explore-graceful-termination-nginx.yaml
- content/hi/examples/service/load-balancer-example.yaml
- content/hi/examples/service/nginx-service.yaml
- content/hi/examples/service/pod-with-graceful-termination.yaml
- content/hi/examples/service/simple-service.yaml
e.g. https://github.com/kubernetes/website/tree/main/content/en/examples/service are not similar to
All examples from https://github.com/kubernetes/website/tree/main/content/en/examples/service need to be added here
Closes:
> [hi] add example service

- content/pl/docs/concepts/containers/_index.md
> [pl] docs/concepts/containers/_index.md

- content/pl/docs/home/supported-doc-versions.md
[pl] sync content/pl/docs/home/supported-doc-versions.md with PR #45571
https://github.com/kubernetes/website/pull/45571/files
> [pl] sync with PR #45571

- content/pl/training/_index.html
[pl] sync content/pl/training/_index.html with PR #49959 , #50056 , and one missing section .
> [pl] sync with PR #49959 , #50056

- content/pl/docs/tutorials/kubernetes-basics/expose/expose-intro.html
[pl] sync expose-intro.html with the latest EN version
preview:
https://deploy-preview-50549--kubernetes-io-main-staging.netlify.app/pl/docs/tutorials/kubernetes-basics/expose/expose-intro/
> [pl] sync expose-intro.html with the latest EN version

- content/pl/docs/tutorials/kubernetes-basics/scale/scale-intro.html
sync scale-intro.html with the latest EN version
> [pl] sync scale-intro.html with the latest EN version

- content/de/_index.html
Bringing the recent changes from #50486 to the German localisation.
> [de] Update KubeCon 2025 events after KubeCon EU

- content/ja/blog/_posts/2025-03-24-ingress-nginx-CVE-2025-1974.md
Translated [/content/en/blog/_posts/2025-03-24-ingress-nginx-CVE-2025-1974.md](https://github.com/kfess/website/blob/main/content/en/blog/_posts/2025-03-24-ingress-nginx-CVE-2025-1974.md) into Japanese.
Closes: #50362 
/language ja
> [ja] Translate blog: Ingress-nginx CVE-2025-1974: What You Need to Know

- content/zh-cn/blog/_posts/2025-05-13-jobs-backofflimitperindex-goes-ga.md
```
content/zh-cn/blog/_posts/2025-05-13-jobs-backofflimitperindex-goes-ga.md
```
> [zh] Add 2025-05-13-jobs-backofflimitperindex-goes-ga.md

- content/ja/_index.html
Update content/ja/_index.html
- KubeCon情報の更新
- その他の最新化
ファイルの場所
en: https://github.com/kubernetes/website/blob/main/content/en/_index.html
ja: https://github.com/kubernetes/website/blob/main/content/ja/_index.html
Webページ
en: https://kubernetes.io
ja: https://kubernetes.io/ja/
Closes: #50979
> [ja] Update content/ja/_index.html

- content/pl/docs/concepts/architecture/_index.md
> [pl] docs/concepts/architecture/_index.md

- content/pl/docs/concepts/security/_index.md
> [pl] docs/concepts/security/_index.md

- content/pl/docs/contribute/participate/_index.md
> [pl] docs/contribute/participate/_index.md

- content/pl/docs/contribute/advanced.md
> [pl] docs/contribute/advanced.md

- content/pl/docs/concepts/extend-kubernetes/_index.md
> [pl] docs/concepts/extend-kubernetes/_index.md

- content/pl/docs/contribute/docs.md
> [pl] docs/contribute/docs.md

- content/ja/blog/_posts/2025-03-12-sig-apps-spotlight.md
Sync [/content/en/blog/_posts/2025-03-12-sig-apps-spotlight.md](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2025-03-12-sig-apps-spotlight.md) with the content in [en](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2025-03-12-sig-apps-spotlight.md).
Closes: #50397  
/language ja
> [ja] Translate /content/en/blog/_posts/2025-03-12-sig-apps-spotlight into Japanese

- content/pl/docs/reference/glossary/workload.md
> [pl] docs/reference/glossary/workload.md

- content/pl/docs/concepts/workloads/pods/_index.md
- content/pl/examples/pods/simple-pod.yaml
> [pl] docs/concepts/workloads/pods/_index.md

- content/pl/docs/concepts/scheduling-eviction/_index.md
- content/pl/docs/reference/glossary/pod-disruption.md
> [pl] docs/concepts/scheduling-eviction/_index.md

- content/pl/docs/concepts/policy/_index.md
> [pl] docs/concepts/policy/_index.md

- content/pl/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
[pl] sync with the latest EN version:
content/pl/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
the preview link:
https://deploy-preview-50396--kubernetes-io-main-staging.netlify.app/pl/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
> [pl] sync deploy-intro.html with the latest EN version

- content/pl/docs/tutorials/kubernetes-basics/update/update-intro.html
[pl] sync with the latest EN version : content/pl/docs/tutorials/kubernetes-basics/update/update-intro.html
> [pl] sync update-intro.html with the latest EN version

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon_coredns.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon_coredns.md
> [zh-cn]sync kubeadm_init_phase_addon_coredns

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/APIListChunking.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/APISelfSubjectReview.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AdvancedAuditing.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/AllowServiceLBStatusOnNonLB.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/BtreeWatchCache.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/CPUManagerPolicyOptions.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DisableNodeKubeProxyVersion.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/HonorPVReclaimPolicy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/InPlacePodVerticalScalingAllocatedStatus.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/InformerResourceVersion.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/JobBackoffLimitPerIndex.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/JobSuccessPolicy.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/MatchLabelKeysInPodAffinity.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/MultiCIDRServiceAllocator.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/NFTablesProxyMode.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/NodeInclusionPolicyInPodTopologySpread.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/RecursiveReadOnlyMounts.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/SeparateCacheWatchRPC.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ServiceAccountNodeAudienceRestriction.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ServiceAccountTokenNodeBinding.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/SidecarContainers.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/StorageNamespaceIndex.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/UserNamespacesSupport.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WatchFromStorageWithoutResourceVersion.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WindowsHostNetwork.md
Update all feature gates by checking with `./scripts/lsync.sh`
> [zh] Sync feature-gates/*.md

- content/zh-cn/blog/_posts/2025-05-05-Honor-Persistent-Volume-Reclaim-Policy-Graduate-to-GA.md
content/zh-cn/blog/_posts/2025-05-05-Honor-Persistent-Volume-Reclaim-Policy-Graduate-to-GA.md
> [zh-cn] Add blog: 2025-05-05-Honor-Persistent-Volume-Reclaim-Policy-Graduate-to-GA.md

- content/bn/examples/admin/sched/my-scheduler.yaml
https://github.com/kubernetes/website/pull/50908/files
> [bn] Replace deprecated API version

- content/ja/examples/admin/sched/my-scheduler.yaml
https://github.com/kubernetes/website/pull/50908/files
> [ja] Replace deprecated API version

- content/ko/examples/admin/sched/my-scheduler.yaml
https://github.com/kubernetes/website/pull/50908/files
> [ko] Replace deprecated API version

- content/en/docs/reference/command-line-tools-reference/feature-gates/ProcMountType.md
> Fix feature gate ProcMountType

- content/zh-cn/docs/reference/kubectl/generated/kubectl_annotate/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_logs/_index.md
> [zh-cn]sync kubectl_annotate kubectl_logs

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_list.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_list.md
> [zh-cn]sync kubeadm_config_images_list.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_patch/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_replace/_index.md
> [zh-cn]sync kubectl_patch kubectl_replace

- content/zh-cn/docs/contribute/blog/submission.md
```
content/zh-cn/docs/contribute/blog/submission.md
```
See [preview](https://deploy-preview-51019--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/blog/article-submission/)
> [zh] Add blog/submission.md

- content/zh-cn/blog/_posts/2025-05-14-Container-Stop-Signals.md
content/zh-cn/blog/_posts/2025-05-14-Container-Stop-Signals.md
> [zh-cn] Add blog: 2025-05-14-Container-Stop-Signals.md

- content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1beta2.md
```
deleted: content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1alpha3.md
added: content/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1beta2.md
```
See [preview](https://deploy-preview-50996--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/workload-resources/resource-claim-template-v1beta2/)
> [zh] Sync resource-claim-template-v1beta2.md

- content/fr/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
This update follows current best practices for GPG key handling and apt repository signing, which are now mandatory on systems like Ubuntu 24.
It replaces deprecated apt-key usage with the recommended signed-by approach using /etc/apt/keyrings.
> [fr] Update installation kubeadm, kubelet & kubectl

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/validating-admission-policy-v1.md
content/zh-cn/docs/reference/kubernetes-api/policy-resources/validating-admission-policy-v1.md
> [zh-cn]sync validating-admission-policy-v1.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon_all.md
sync
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_addon_all.md
```
> [zh-cn] sync _index kubectl_rollout_undo kubeadm_init_phase_addon_all

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/ProcMountType.md
https://github.com/kubernetes/website/pull/50825/files
> [zh] Fix feature gate ProcMountType

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/_index.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/_index.md
> [zh-cn]sync kubeadm_init/_index.md

- content/zh-cn/docs/reference/config-api/kuberc.v1alpha1.md
content/zh-cn/docs/reference/config-api/kuberc.v1alpha1.md
> [zh-cn] Add config-api/kuberc.v1alpha1

- content/id/docs/reference/networking/ports-and-protocols.md
https://github.com/kubernetes/website/pull/47991/files
> [id] Update ports-and-protocols.md

- content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md
content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale.md
> [zh-cn]sync horizontal-pod-autoscale.md

- content/pl/docs/contribute/docs.md
[pl] sync content/pl/docs/contribute/docs.md with PR 50092
https://github.com/kubernetes/website/pull/50092/files#diff-dddcbe09300e7172a21010f29951cbe1e206faa3bc8569ba1c2698f83e6306b0
> [pl] sync with PR 50092

- content/pl/docs/concepts/security/_index.md
[pl] sync content/pl/docs/concepts/security/_index.md with PRs 49626 and 49923 .
PRs:
#49923
#49626
commits:
https://github.com/kubernetes/website/commit/8558bc356159da25cf4a79e4dda338ec4f973800
https://github.com/kubernetes/website/commit/bf971d28d3b485726e8e6b3a502626de5852256f
> [pl] sync with PRs 49626 and 49923

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/RelaxedDNSSearchValidation.md
https://github.com/kubernetes/website/pull/50828/files
> [zh] Fix feature gate RelaxedDNSSearchValidation

- content/zh-cn/docs/reference/config-api/client-authentication.v1.md
> [zh-cn]sync client-authentication.v1

- content/pl/training/_index.html
[pl] sync content/pl/training/_index.html with PR 51035
https://github.com/kubernetes/website/commit/34741008bed9f701241242ca695062ca59deb541
---
PL
dodanie brakujacego </div> + dodanie wciec
> [pl] sync with PR 51035

- content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
sync
`content/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md`
please review: [dynamic-resource-allocation](https://deploy-preview-50976--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation/)
> [zh-cn] Sync dynamic-resource-allocation.md

- content/zh-cn/docs/home/_index.md
Update some text in:
```
content/zh-cn/docs/home/_index.md
```
> [zh] Update docs/home/_index.md

- content/pl/docs/reference/_index.md
[pl] sync ( content/pl/docs/reference/_index.md ) with PR 50961
- PR: https://github.com/kubernetes/website/pull/50961
- original commit:
https://github.com/kubernetes/website/commit/1bba58be29c77b5e09e7b634300cfd3767ab9904#diff-26605086bdd7763aa1897e5d7fb32ec6a79797bf2225dc7d499b4c965cf9f60f
> [pl] sync with PR 50961

- content/zh-cn/docs/reference/kubectl/generated/kubectl_autoscale/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_autoscale/_index.md
> [zh-cn]sync kubectl_autoscale/_index.md

- content/hi/docs/tasks/administer-cluster/network-policy-provider/antrea-network-policy.md
[hi] Translate Hindi [network-policy-provider/antrea-network-policy](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/network-policy-provider/antrea-network-policy.md?plain=1)
Closes: #
> [hi] Translate Hindi network-policy-provider/antrea-network-policy

- content/en/case-studies/appdirect/index.html
> [en] update spring.io link

- content/zh-cn/docs/concepts/overview/components.md
Sync with en #51125 
```
content/zh-cn/docs/concepts/overview/components.md
```
See [preview](https://deploy-preview-51154--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/overview/components/)
> [zh] overview/components.md

- content/id/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
This translate https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/ page into Bahasa Indonesia
> [id] Localize dynamic-resource-allocation page into Bahasa Indonesia

- content/en/careers/_index.html
- content/en/community/_index.html
- layouts/partials/navbar.html
Add an embedded careers page powered by CNCF's [GitJobs](https://gitjobs.dev) job board (Pre-filtering on the keyword "Kubernetes")
cc @caniszczyk @tegioz @cynthia-sg
> Add gitjobs embed to create a Kubernetes Careers page

- content/id/docs/tasks/administer-cluster/configure-upgrade-etcd.md
https://github.com/kubernetes/website/pull/49266/files
> [id] update semver link

- content/pt-br/docs/contribute/analytics.md
Update text for better translation.
Update URL for the correct analytics dashboard.
Closes: #
> [pt-br] Update docs/contribute/analytics.md

- content/zh-cn/docs/concepts/overview/working-with-objects/finalizers.md
```
content/zh-cn/docs/concepts/overview/working-with-objects/finalizers.md
```
> [zh] Sync working-with-objects/finalizers.md

- content/zh-cn/careers/_index.html
- content/zh-cn/case-studies/_index.html
- content/zh-cn/community/_index.html
Sync with en #50925 
```
added:       content/zh-cn/careers/_index.html
modified:   content/zh-cn/case-studies/_index.html
modified:   content/zh-cn/community/_index.html
```
> [zh] Update index file for careers, community, and case-studies

- content/en/case-studies/golfnow/index.html
> [en] update kubernetes links golfnow index

- content/ja/docs/tasks/inject-data-application/define-interdependent-environment-variables.md
- content/ja/examples/pods/inject/dependent-envars.yaml
Translated [/content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md) into Japanese.
Closes: #51121 
/language ja
> [ja] Translated /content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md into Japanese

- assets/scss/_custom.scss
- content/en/careers/_index.html
- Margin adjustments for desktop/mobile devices
- Reduce font size for `Powered by` text
Related to #50925
@jeefy @nate-double-u @tegioz
> Some minor styling changes to careers page

- content/ja/docs/concepts/architecture/cgroups.md
remove  /ja prefixes from link of this page.
#51260
> [ja] Update cgroups.md by removing /ja prefixes

- hugo.toml
Enable untranslated content to visible as link on left side bar
Closes: #
> Enable config to add untranslated content to the left side bar

- content/ja/docs/concepts/architecture/self-healing.md
Translated [/content/en/docs/concepts/architecture/self-healing.md](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/architecture/self-healing.md) into Japanese.
Closes: #51139 
/language ja
> [ja] Translated /content/en/docs/concepts/architecture/self-healing.md into Japanese

- content/ja/docs/tasks/access-application-cluster/configure-dns-cluster.md
Translated [/content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md) into Japanese.
Closes: #51127  
/language ja
> [ja] Translated /content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md into Japanese

- content/zh-cn/case-studies/golfnow/index.html
https://github.com/kubernetes/website/pull/51239/files
> [zh] update kubernetes links golfnow index

- content/en/blog/_posts/2025-06-16-Change-To-Kubernetes-Slack.md
This is a now completed blog post to mirror the one on Contributor Site: https://github.com/kubernetes/contributor-site/pull/583
attn: @lmktfy @natalisucks
> Slack Changes Blog post Mirror

- content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md
> [zh-cn]sync kubectl_diff

- content/ko/docs/concepts/cluster-administration/system-traces.md
https://github.com/kubernetes/website/pull/50718/files
> [ko] Update system-traces.md to use the Otel debug exporter

- content/zh-cn/docs/reference/kubectl/kuberc.md
content/zh-cn/docs/reference/kubectl/kuberc.md
> [zh-cn]sync kuberc.md

- content/zh-cn/docs/reference/using-api/deprecation-guide.md
content/zh-cn/docs/reference/using-api/deprecation-guide.md
> [zh-cn]sync deprecation-guide.md

- content/zh-cn/docs/reference/kubernetes-api/policy-resources/validating-admission-policy-v1.md
```
content/zh-cn/docs/reference/kubernetes-api/policy-resources/validating-admission-policy-v1.md
```
> [zh] Update validating-admission-policy-v1.md

- content/zh-cn/blog/_posts/2025-06-16-Change-To-Kubernetes-Slack.md
sync
```
content/zh-cn/blog/_posts/2025-06-16-Change-To-Kubernetes-Slack.md
```
please [review](https://deploy-preview-51285--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2025/06/16/changes-to-kubernetes-slack/)
> [zh-cn] sync blog 2025-06-16-Change-To-Kubernetes-Slack

- content/zh-cn/docs/concepts/windows/user-guide.md
Update zh text to sync with en upstream.
```
content/zh-cn/docs/concepts/windows/user-guide.md
```
> [zh] Sync windows/user-guide.md

- content/zh-cn/docs/setup/production-environment/container-runtimes.md
content/zh-cn/docs/setup/production-environment/container-runtimes.md
> [zh-cn]sync container-runtimes

- content/en/docs/reference/access-authn-authz/authentication.md
/triage accepted
/sig auth
/assign enj
> fix example userinfo object in authn docs

- content/de/docs/tasks/tools/install-kubectl.md
https://github.com/kubernetes/website/pull/51152/files
> [de] Replace external paywall link

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_all.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_apiserver.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_controller-manager.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_all.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/kubeadm_init_phase_control-plane_controller-manager.md
> [zh-cn]sync/improve kubeadm_init_phase_control-plane* kubeadm_init_phase_control-plane_controller-manager

- content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
resolve https://github.com/kubernetes/website/pull/51152/files
> [ja] Replace external paywall link

- content/zh-cn/docs/reference/kubectl/quick-reference.md
content/zh-cn/docs/reference/kubectl/quick-reference.md
> [zh-cn]sync quick-reference.md

- content/en/docs/concepts/workloads/controllers/deployment.md
feat: make rollingUpdate description clearer in deployment.md
make `rollingUpdate` description clearer in deployment.md 
Like described in kubectl explain output
```
% k explain deployment.spec.strategy
GROUP:      apps
KIND:       Deployment
VERSION:    v1
FIELD: strategy <DeploymentStrategy>
DESCRIPTION:
The deployment strategy to use to replace existing pods with new ones.
DeploymentStrategy describes how to replace existing pods with new ones.
FIELDS:
rollingUpdate	<RollingUpdateDeployment>
Rolling update config params. Present only if DeploymentStrategyType =
RollingUpdate.
type	<string>
enum: Recreate, RollingUpdate
Type of deployment. Can be "Recreate" or "RollingUpdate". Default is
RollingUpdate.
Possible enum values:
- `"Recreate"` Kill all existing pods before creating new ones. …
```
> Improve description of rollingUpdate for Deployment

- content/zh-cn/docs/reference/access-authn-authz/authentication.md
> [zh-cn]sync authentication.md

- content/zh-cn/docs/contribute/blog/submission.md
- content/zh-cn/docs/contribute/suggesting-improvements.md
content/zh-cn/docs/contribute/blog/submission.md
content/zh-cn/docs/contribute/suggesting-improvements.md
> [zh-cn]sync submission suggesting-improvements

- content/zh-cn/docs/concepts/windows/intro.md
- Fix bullet rendering issues:
```
content/zh-cn/docs/concepts/windows/intro.md
```
See [preview](https://deploy-preview-51300--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/windows/intro/#comparison-with-Linux-similarities)
> [zh] Sync windows/intro.md

- content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
https://github.com/kubernetes/website/pull/51152/files
> [es] Replace external paywall link

- content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_pull.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_config/kubeadm_config_images_pull.md
> [zh-cn]sync kubeadm_config_images_pull.md

- content/zh-cn/blog/_posts/2025-05-02-mutable-csi-node-allocatable.md
```
content/zh-cn/blog/_posts/2025-05-02-mutable-csi-node-allocatable.md
```
See [preview](https://deploy-preview-51292--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2025/05/02/kubernetes-1-33-mutable-csi-node-allocatable-count/)
> [zh] Add 2025-05-02-mutable-csi-node-allocatable.md

- content/zh-cn/blog/_posts/2025-06-10-enhancing-kubernetes-event-management-custom-aggregation.md
content/zh-cn/blog/_posts/2025-06-10-enhancing-kubernetes-event-management-custom-aggregation.md
> [zh-cn]Add blog:2025-06-10-enhancing-kubernetes-event-management-custom-aggregation

- content/en/_index.html
Cleanup "upcoming events" since some events already had passed
Closes: #
> Cleanup "upcoming events"

- content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
xref
- https://github.com/kubernetes/kubeadm/issues/2907
/hold for
- https://github.com/kubernetes/kubernetes/pull/132594
> kubeadm-init.md: update WaitForAllControlPlaneComponents

- content/bn/case-studies/golfnow/index.html
https://github.com/kubernetes/website/pull/51239/files
> [bn] update kubernetes links golfnow index

- content/bn/case-studies/blablacar/index.html
https://github.com/kubernetes/website/pull/51130/files
> [bn] update kubernetes link

- content/en/blog/_posts/XXXXX-pqc-in-k8s.md
This PR mirror the https://github.com/kubernetes/contributor-site/pull/582 blog post from contributor site
> Mirror post quantum cryptography blog

- content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md
> [zh-cn]sync kubectl_cordon

- content/zh-cn/blog/_posts/2025-06-03-start-sidecar-first/index.md
content/zh-cn/blog/_posts/2025-06-03-start-sidecar-first/index.md
> [zh-cn]sync 2025-06-03-start-sidecar-first

- content/zh-cn/docs/reference/kubectl/generated/kubectl_delete/_index.md
> [zh-cn]sync kubectl_delete

- content/zh-cn/docs/reference/using-api/server-side-apply.md
content/zh-cn/docs/reference/using-api/server-side-apply.md
> [zh-cn]sync server-side-apply

- content/zh-cn/examples/pods/config/redis-pod.yaml
content/zh-cn/examples/pods/config/redis-pod.yaml
> [zh-cn]sync redis-pod.yaml

- content/zh-cn/docs/reference/config-api/kubelet-config.v1alpha1.md
content/zh-cn/docs/reference/config-api/kubelet-config.v1alpha1.md
> [zh-cn]sync/improve kubelet-config.v1alpha1.md

- content/zh-cn/docs/concepts/architecture/cri.md
- content/zh-cn/docs/reference/config-api/apiserver-eventratelimit.v1alpha1.md
content/zh-cn/docs/concepts/architecture/cri.md
content/zh-cn/docs/reference/config-api/apiserver-eventratelimit.v1alpha1.md
> [zh-cn]sync/improve cri apiserver-eventratelimit.v1alpha1

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/StreamingCollectionEncodingToJSON.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/StreamingCollectionEncodingToProtobuf.md
```
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/StreamingCollectionEncodingToJSON.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/StreamingCollectionEncodingToProtobuf.md
```
> [zh] Add two feature gates for reference

- content/zh-cn/docs/concepts/cluster-administration/admission-webhooks-good-practices.md
Correct wrong doc text at https://kubernetes.io/zh-cn/docs/concepts/cluster-administration/admission-webhooks-good-practices/#choose-admission-mechanism
> [zh] Fix several translations in admission-webhooks-good-practices

- content/zh-cn/docs/reference/kubectl/generated/kubectl_scale/_index.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_taint/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_scale/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_taint/_index.md
> [zh-cn]sync kubectl_scale kubectl_taint

- content/en/docs/tutorials/kubernetes-basics/_index.md
- content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.md
- content/en/docs/tutorials/kubernetes-basics/update/update-intro.md
- layouts/shortcodes/tutorials/carousel-item.html
- layouts/shortcodes/tutorials/carousel.html
- layouts/shortcodes/tutorials/module.html
- layouts/shortcodes/tutorials/modules.html
- static/css/style_tutorials.css
This PR includes changes to replace embedded HTML code with Hugo shortcodes on pages in the Learn Kubernetes Basics tutorial.
Closes: #
> Replace html-inline code with shortcodes in the  Learn Kubernetes Basics tutorial

- content/pl/_index.html
[pl] sync with PR #50486, #51406
> [pl] sync with PR 51406

- content/pl/docs/contribute/generate-ref-docs/kubectl.md
> [pl] sync with PR 51419

- content/bn/docs/reference/glossary/wg.md
I've localized the wg.md file in Bangla. 
Related issue : #45729
> [bn] Localization of wg.md

- content/bn/_index.html
> [bn] Update _index.html

- content/pl/docs/tutorials/kubernetes-basics/scale/scale-intro.md
[pl] sync tutorials/kubernetes-basics/scale/scale-intro.md with PR #50556
> [pl] sync tutorials/kubernetes-basics/scale/scale-intro.md with PR 50556

- content/zh-cn/docs/tutorials/kubernetes-basics/_index.md
content/zh-cn/docs/tutorials/kubernetes-basics/_index.md
> [zh-cn]sync kubernetes-basics/_index.md

- content/en/blog/_posts/2025-07-18-pqc-in-k8s.md
This PR publish the blog post #51517 
The post is scheduled to be live on 18-07-2025
> Publish Post Quantum Crypto Blog

- content/pl/docs/concepts/overview/working-with-objects/field-selectors.md
the polish translation of docs/concepts/overview/working-with-objects/field-selectors.md
> [pl] docs/concepts/overview/working-with-objects/field-selectors.md

- content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.md
- content/zh-cn/docs/tutorials/kubernetes-basics/update/update-intro.md
content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.md
content/zh-cn/docs/tutorials/kubernetes-basics/update/update-intro.md
> [zh-cn]sync scale-intro update-intro

- content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_pod.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_pod.md
> [zh-cn]sync kubectl_top_pod.md

- content/en/docs/reference/using-api/cel.md
New included utilities are IP, Cidr, K8s format, String version 2 and Semver.
Update API Machinery cel documentation to include the recently added utilities. 
ISSUE: #51159
> Update cel documentation to include new added utilities.

- content/zh-cn/docs/concepts/extend-kubernetes/operator.md
Updated a link and some minor changes:
```
content/zh-cn/docs/concepts/extend-kubernetes/operator.md
```
> [zh] Sync extend-kubernetes/operator.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/OrderedNamespaceDeletion.md
Update the feature status for KEP 5080
Closes: #
> [KEP-5080]update the feature status 

- content/vi/docs/tasks/tools/install-kubectl.md
https://github.com/kubernetes/website/pull/51152/files
> [vi] Replace external paywall link

- content/ko/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
https://github.com/kubernetes/website/pull/51152/files
> [ko] Replace external paywall link

- content/zh-cn/docs/concepts/workloads/controllers/daemonset.md
- content/zh-cn/docs/tasks/manage-daemon/update-daemon-set.md
- content/zh-cn/examples/controllers/daemonset.yaml
- content/zh-cn/examples/controllers/fluentd-daemonset-update.yaml
- content/zh-cn/examples/controllers/fluentd-daemonset.yaml
```
modified:   content/zh-cn/docs/concepts/workloads/controllers/daemonset.md
modified:   content/zh-cn/docs/tasks/manage-daemon/update-daemon-set.md
modified:   content/zh-cn/examples/controllers/daemonset.yaml
modified:   content/zh-cn/examples/controllers/fluentd-daemonset-update.yaml
modified:   content/zh-cn/examples/controllers/fluentd-daemonset.yaml
```
> [zh] Update DaemonSet examples and docs

- content/en/docs/reference/glossary/kubelet.md
> fix wrong reference link of kubelet

- content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md
- content/zh-cn/docs/reference/kubectl/generated/kubectl_uncordon/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_uncordon/_index.md
> [zh-cn]sync kubectl_top_node kubectl_uncordon

- content/zh-cn/docs/reference/config-api/apiserver-webhookadmission.v1.md
- content/zh-cn/docs/reference/config-api/kubelet-config.v1.md
content/zh-cn/docs/reference/config-api/apiserver-webhookadmission.v1.md
content/zh-cn/docs/reference/config-api/kubelet-config.v1.md
> [zh-cn]sync/improve apiserver-webhookadmission.v1 kubelet-config.v1

- content/zh-cn/docs/tasks/configure-pod-container/assign-resources/_index.md
- content/zh-cn/docs/tasks/configure-pod-container/assign-resources/allocate-devices-dra.md
- content/zh-cn/examples/dra/dra-example-job.yaml
- content/zh-cn/examples/dra/resourceclaim.yaml
- content/zh-cn/examples/dra/resourceclaimtemplate.yaml
```
content/zh-cn/docs/tasks/configure-pod-container/assign-resources/_index.md
content/zh-cn/docs/tasks/configure-pod-container/assign-resources/allocate-devices-dra.md
```
> [zh] Add assign-resources/allocate-devices-dra.md

- content/zh-cn/README.md
Sync with en #51648 
```
content/zh-cn/README.md
```
> [zh] update README.md

- content/ja/docs/setup/production-environment/container-runtimes.md
https://github.com/kubernetes/website/pull/51217/files
> [ja] Fix EOL MCR links in CRI and Windows Installation Pages

- content/pt-br/docs/concepts/windows/intro.md
https://github.com/kubernetes/website/pull/51217/files
> [pt] Fix EOL MCR links in CRI and Windows Installation Pages

- content/zh-cn/docs/reference/glossary/cel.md
- content/zh-cn/docs/reference/glossary/device.md
- content/zh-cn/docs/reference/glossary/dra.md
Add zh text to 3 glosssaries:
```
content/zh-cn/docs/reference/glossary/cel.md
content/zh-cn/docs/reference/glossary/device.md
content/zh-cn/docs/reference/glossary/dra.md
```
> [zh] Add glossary: cel, device, and dra

- content/zh-cn/docs/tasks/configure-pod-container/assign-resources/set-up-dra-cluster.md
- content/zh-cn/examples/dra/deviceclass.yaml
```
content/zh-cn/docs/tasks/configure-pod-container/assign-resources/set-up-dra-cluster.md
```
> [zh] Add set-up-dra-cluster.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/WatchList.md
Update the docs to match https://github.com/kubernetes/kubernetes/pull/132704
Closes: #
> Update WatchList to true for 1.34

- content/en/docs/concepts/workloads/controllers/job.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/JobPodReplacementPolicy.md
This PR adds documentation for graduating the JobPodReplacementPolicy feature gate to GA.
KEP: https://github.com/kubernetes/enhancements/issues/3939
> [KEP-3939] - Promote JobPodReplacementPolicy to GA

- content/zh-cn/_index.html
> [zh] Update upcoming events

- content/zh-cn/docs/reference/access-authn-authz/authentication.md
- #51611 introduced a commented mermaid block, which causes the rendering issues on [current authenticating page](https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/authentication/#openid-connect-tokens)
- Also fixed terms like Claim, Required.
See [preview](https://deploy-preview-51674--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/authentication/#openid-connect-tokens)
> [zh] Fix mermaid and terms in authentication.md

- content/hi/_index.html
> [hi] Update upcoming events

- content/pt-br/_index.html
> [pt] Update upcoming events

- content/en/docs/concepts/cluster-administration/system-metrics.md
Prometheus text format link error
fix https://github.com/kubernetes/website/issues/51749
Closes: #
> Fix broken link in "Metrics For Kubernetes System Components" page

- assets/scss/_variables_project.scss
Prepare for aligning more closely with Docsy theme.
Split off from PR https://github.com/kubernetes/website/pull/50665
> Update Docsy variables

- content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
https://github.com/kubernetes/website/pull/51362/files
> [pt] Kubeadm upgrade phase navigation

- content/uk/docs/concepts/extend-kubernetes/operator.md
> [uk] sync with PR 51627

- content/uk/case-studies/_index.html
> [uk] sync with PR 45871

- content/ru/examples/pods/share-process-namespace.yaml
> [ru] sync with PR 41715

- content/ru/docs/tasks/configure-pod-container/assign-memory-resource.md
- content/ru/examples/pods/resource/memory-request-limit-3.yaml
- content/ru/examples/pods/resource/memory-request-limit.yaml
> [ru] sync with PR 32353

- content/ru/examples/application/mysql/mysql-statefulset.yaml
> [ru] sync with PR 36596

- content/ru/examples/application/deployment-scale.yaml
> [ru] sync with PR 37982

- content/ru/docs/contribute/generate-ref-docs/quickstart.md
> [ru] sync with PR 37564

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/DRAAdminAccess.md
- content/en/docs/reference/labels-annotations-taints/_index.md
- https://github.com/kubernetes/enhancements/issues/5018
Closes: #
> kep-5018: DRA Admin Access: move to beta

- content/ja/docs/reference/glossary/node.md
> [ja] sync with PR 48318

- content/en/docs/concepts/policy/resource-quotas.md
Split out from PR https://github.com/kubernetes/website/pull/50662
A small improvement to the ResourceQuota concept page: describe each available kind of quota.
[[preview](https://deploy-preview-51137--kubernetes-io-main-staging.netlify.app/docs/concepts/policy/resource-quotas/)]; compare with [current page](https://k8s.io/docs/concepts/policy/resource-quotas/)
/language en
> Describe kinds of ResourceQuota

- content/zh-cn/examples/pods/security/seccomp/profiles/fine-grained.json
> [zh-cn] sync with PR 45460

- content/zh-cn/docs/tasks/manage-kubernetes-objects/storage-version-migration.md
> [zh-cn] sync with PR 48709

- content/zh-cn/blog/_posts/2022-02-17-updated-dockershim-faq.md
> [zh-cn] sync with PR 45480

- content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
> [zh-cn] sync with PR 51750

- content/en/docs/reference/command-line-tools-reference/feature-gates/KubeletCgroupDriverFromCRI.md
- content/en/docs/reference/command-line-tools-reference/kubelet.md
- content/en/docs/setup/production-environment/container-runtimes.md
KEP https://github.com/kubernetes/enhancements/issues/4033
Closes: #
> 4033: update to GA

- content/en/docs/concepts/workloads/pods/user-namespaces.md
The code changes for this are:
* github.com/https://github.com/kubernetes/kubernetes/pull/132868
* github.com/https://github.com/kubernetes/kubernetes/pull/132902
> docs: Add userns changes in 1.34

- content/en/docs/reference/using-api/api-concepts.md
Documentation https://github.com/kubernetes/enhancements/issues/4988
> Update documentation for KEP-4988 Beta

- content/en/docs/concepts/scheduling-eviction/assign-pod-node.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/ClearingNominatedNodeNameAfterBinding.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/NominatedNodeNameForExpectation.md
Doc update for KEP-5278
Ref: https://github.com/kubernetes/enhancements/issues/5278
> kep-5278: Use NominatedNodeName to express the expected pod placement

- content/en/docs/concepts/storage/persistent-volumes.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/RecoverVolumeExpansionFailure.md
xref https://github.com/kubernetes/enhancements/issues/1790
> Update RecoverVolumeExpansionFailure to stable

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/DRAPrioritizedList.md
Document PrioritizedList graduation to beta in 1.34
https://github.com/kubernetes/enhancements/issues/4816
Closes: #
> [KEP-4816] DRA Prioritized Alternatives to beta documentation

- content/en/docs/tasks/inject-data-application/define-environment-variable-via-file.md
Optimize envfile docs
Updated title to **Env File Syntax** and clarified that this section’s specifications are derived from the .env file.
Closes: #
> [en] Optimize envfile documentation

- content/ru/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
- content/ru/examples/pods/probe/tcp-liveness-readiness.yaml
> [ru] sync with PR 43289

- content/en/docs/concepts/workloads/pods/pod-hostname.md
This is a follow-up to the issue in #51414. 
Closes: #
> Follow up comments in PR 51414

- content/en/blog/_posts/2025-XX-XX-kubectl-kuberc-beta.md
Blog introducing kubectl user preferences
KEP: https://github.com/kubernetes/enhancements/issues/3104
/assign @ardaguclu
for sig-cli review
> 2025-XX-XX [KEP-3104] kuberc blog

- content/en/docs/concepts/cluster-administration/dra.md
Follow-on nits from PR https://github.com/kubernetes/website/pull/51722 to
1. Fix some typos
2. Add promql highlighting to inline promql
3. Add more tooltips
4. Add K8s metrics reference page context (sadly it looks like there aren't page fragments per metric to link directly for each named metric used, if there's some html dark magic I don't understand and I'm wrong there let me know and I can add in more direct links)
Quick link to specific page netlify preview: https://deploy-preview-51818--kubernetes-io-main-staging.netlify.app/docs/concepts/cluster-administration/dra/
Also Closes: #51178
> Good practices dra cluster admin - nits, highlighting and link outs updates

- content/ko/docs/concepts/windows/intro.md
- content/ko/docs/setup/production-environment/container-runtimes.md
https://github.com/kubernetes/website/pull/51217/files
https://github.com/kubernetes/website/pull/51599
> [ko] Fix EOL MCR links in CRI and Windows Installation Pages

- content/ko/docs/contribute/participate/issue-wrangler.md
Description
translate /docs/contribute/participate/issue-wrangler into Korean.
#51453 pr 내부에서 커밋이 꼬여서 새롭게 pr을 올렸습니다.
Issue
https://github.com/kubernetes/website/issues/51375
Closes: https://github.com/kubernetes/website/issues/51375
> [ko] Translate /docs/contribute/participate/issue-wrangler into Korean

- content/en/includes/task-tutorial-prereqs.md
Add iximiuz labs to the list of playgrounds
Closes: #51747
> Add iximiuz labs to the list of playgrounds

- content/zh-cn/docs/concepts/cluster-administration/dra.md
```
content/zh-cn/docs/concepts/cluster-administration/dra.md
```
See [preview](https://deploy-preview-51826--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/dra/)
> [zh] Add cluster-administration/dra.md

- content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
Updated /ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md  to match the English version
Closes: #51203
/language ja
/assign
> [ja] Sync /ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md with English version

- content/en/blog/_posts/2025-08-07-introducing-the-headlamp-ai-assistant/index.md
Fixed shortcode for youtube video embedding on #51844
> Fixed shortcodes on blog post

- content/zh-cn/includes/task-tutorial-prereqs.md
content/zh-cn/includes/task-tutorial-prereqs.md
> [zh-cn]sync task-tutorial-prereqs.md

- content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> [zh-cn]sync node-pressure-eviction.md

- content/zh-cn/docs/tasks/administer-cluster/cluster-upgrade.md
https://github.com/kubernetes/website/pull/51874/files
> [zh] fix typo in cluster-upgrade.md

- content/en/docs/tasks/configure-pod-container/user-namespaces.md
We don't need a debug container, we can just exec into the pod.
> tasks/userns: Don't use a debug container

- data/releases/schedule.yaml
Add August 2025 patch releases to the schedule.
/assign @jimangel @jeremyrickard 
> Add August 2025 patch releases to the schedule

- content/en/blog/_posts/2025-05-22-wg-policy-spotlight.md
made changes to Policy WG Spotlight after [the group got disbanded](https://github.com/kubernetes/contributor-site/pull/534#issuecomment-3013555699).
Refer https://github.com/kubernetes/website/pull/49616 for more info.
> update wg policy spotlight after Policy WG got disbanded

- content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
> [en] fix typo in kubeadm-certs.md

- content/en/blog/_posts/2025-09-01-volume-attributes-class-ga/index.md
Add a blog for https://github.com/kubernetes/enhancements/issues/3751 GA in 1.34
Draft of the blog post: https://docs.google.com/document/d/1OYMpRbM6LUXq32rBugF0mdnIdpHYM4lLgdsnvxWbCTE/edit?resourcekey=0-lXjuU7u553Tf2S_C8A-NcA&tab=t.0
> Add Blog Post for VolumeAttributesClass GA in 1.34

- content/pt-br/docs/tasks/run-application/force-delete-stateful-set-pod.md
Esse PR traz a localização da página https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/ para **PT-BR**.
Adicionado à raiz de **/content/pt-br/docs/tasks/run-application** o arquivo **force-delete-stateful-set-pod.md**, ficando localizado como **/content/pt-br/docs/tasks/run-application/force-delete-stateful-set-pod.md** no repositório.
---
This PR brings the localization of the page https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/ to **PT-BR**.
The file **force-delete-stateful-set-pod.md** was added to the root of **/content/pt-br/docs/tasks/run-application**, and is now located at **/content/pt-br/docs/tasks/run-application/force-delete-stateful-set-pod.md** in the repository.
Closes: #50953
> [pt-br] Add /tasks/run-application/force-delete-stateful-set-pod.md

- content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
> [zh-cn]sync certificate-signing-requests.md

- content/en/docs/concepts/scheduling-eviction/dynamic-resource-allocation.md
Follow-up PR for https://github.com/kubernetes/website/pull/51479#issuecomment-3166293379 
kubernetes/enhancements: https://github.com/kubernetes/enhancements/issues/5075
> [KEP-5075] remove exactly.name field in example

- content/en/case-studies/_index.html
Fixup for PR https://github.com/kubernetes/website/pull/50925
Helps prepare for #41171
> Omit "case studies" from Docsy-rendered main menu

- content/ja/docs/tasks/configure-pod-container/security-context.md
https://github.com/kubernetes/website/pull/51434/files
> [ja] fix typo in security-context.md

- content/de/_index.html
> [de] Update upcoming events

- content/de/docs/setup/best-practices/_index.md
- content/de/docs/setup/best-practices/zertifikate.md
Localizing best-practices/certificates
Closes: #51888
Makes #51894 obsolete
> [DE] Localizing best-practices/certificates - rebased

- content/en/docs/concepts/cluster-administration/node-shutdown.md
Updating the graceful node shutdown documentation following the request at https://kubernetes.slack.com/archives/C0SJ4AFB7/p1755159209760959
```
Another docs ask.
v1.34 will enable graceful shutdown handling by default for Windows nodes.
Given that, can anyone from this SIG help to rewrite https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/ with a each section (level 2 heading) covering Linux and Windows specifics, maybe using tabs?
We try not to have a special "ah, but Windows is different" section of the docs; we'd rather integrate the docs and not assume that everything is Linux by default. (edited) 
```
/milestone v1.34
/sig node windows
> Updating graceful node shutdown page to not assume linux

- content/ko/docs/concepts/workloads/autoscaling.md
Translate concepts/workloads/autoscaling.md into korean
- Follows Korean localization guidelines and terminology
- All Hugo shortcodes and internal links properly localized
Closes: https://github.com/kubernetes/website/issues/49271
> [ko] Translate concepts/workloads/autoscaling.md into korean

- content/zh-cn/case-studies/_index.html
content/zh-cn/case-studies/_index.html
> [zh-cn]sync case-studies/_index.html

- content/en/blog/_posts/2025-07-07-mutable-csi-node-allocatable.md
Blog for KEP 4876 Mutable CSI CSINode Allocatable Graduating to Beta.
See # https://github.com/kubernetes/enhancements/issues/4876
> sig-storage: Mutable CSI Node Allocatable Blog Graduates to Beta

- OWNERS_ALIASES
Creating this PR to request approver access to this repo
cc @divya-mohan0209 @natalisucks @reylejano
> Add SayakMukhopadhyay as approver

- content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.md
https://github.com/kubernetes/website/pull/51564/files
> [zh] Add missing newline

- content/zh-cn/blog/_posts/2024-12-17-api-streaming/index.md
Sync file:
```
content/zh-cn/blog/_posts/2024-12-17-api-streaming/index.md
```
> [zh-cn] sync blog file 2024-12-17-api-streaming/index.md

- content/zh-cn/docs/tasks/debug/_index.md
content/zh-cn/docs/tasks/debug/_index.md
> [zh-cn]sync debug/_index.md

- content/zh-cn/docs/reference/kubectl/introduction.md
> fix(zh-CN): better chinese translation

- content/en/docs/tasks/administer-cluster/kubeadm/adding-linux-nodes.md
Fixes #52001
adding the argument --print-join-command
Closes: #
> chore(kubeadm): improve add-linux-nodes documentation

- content/zh-cn/docs/tasks/administer-cluster/kubeadm/adding-linux-nodes.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/adding-linux-nodes.md
> [zh-cn]sync adding-linux-nodes.md

- content/ru/docs/tasks/tools/install-kubectl.md
> [ru] Fix deprecated kubectl installation instructions

- content/ko/docs/tasks/network/extend-service-ip-ranges.md
Translate [/docs/tasks/network/extend-service-ip-ranges/](https://kubernetes.io/docs/tasks/network/extend-service-ip-ranges/) into Korean
Fixes: #51805 
Closes: #51805
> [ko] Translate /docs/tasks/network/extend-service-ip-ranges/ into Korean

- content/pt-br/docs/setup/best-practices/_index.md
- content/pt-br/docs/setup/best-practices/cluster-large.md
Adds `pt-br` localization for `docs/setup/best-practices/cluster-large.md`.
As it is the first localized page of the best-practices subsection, adds the localized `docs/setup/best-practices/_index.md` as well.
Closes #47220
> [pt-br] Add docs/setup/best-practices/cluster-large.md

- hugo.toml
Update hugo.toml for 1.34 release
> Update hugo.toml for 1.34 release

- content/zh-cn/docs/tutorials/_index.md
content/zh-cn/docs/tutorials/_index.md
> [zh-cn]sync tutorials/_index.md

- content/zh-cn/docs/reference/glossary/cadvisor.md
content/zh-cn/docs/reference/glossary/cadvisor.md
> [zh-cn]sync cadvisor.md

- content/zh-cn/docs/reference/glossary/disruption.md
content/zh-cn/docs/reference/glossary/disruption.md
> [zh-cn]sync glossary/disruption

- content/zh-cn/docs/reference/glossary/cgroup.md
content/zh-cn/docs/reference/glossary/cgroup.md
> [zh-cn]sync cgroup.md

- content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md
https://github.com/kubernetes/website/blob/145a3c022e03b49b267075750b2cbe6fc2737b66/content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md?plain=1#L133
sync with en example
Closes: #52007
> [zh] fix coarse create queue example

- content/zh-cn/docs/concepts/security/pod-security-standards.md
```
content/zh-cn/docs/concepts/security/pod-security-standards.md
```
> [zh] Sync pod-security-standards.md

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAPrioritizedList.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAPrioritizedList.md
> [zh-cn]sync DRAPrioritizedList.md

- content/zh-cn/docs/reference/glossary/event.md
- content/zh-cn/docs/reference/glossary/group-version-resource.md
- content/zh-cn/docs/reference/glossary/limitrange.md
- content/zh-cn/docs/reference/glossary/resource-quota.md
- content/zh-cn/docs/reference/glossary/spec.md
content/zh-cn/docs/reference/glossary/event.md
content/zh-cn/docs/reference/glossary/limitrange.md
content/zh-cn/docs/reference/glossary/resource-quota.md
content/zh-cn/docs/reference/glossary/group-version-resource.md
content/zh-cn/docs/reference/glossary/spec.md
> [zh-cn]sync event limitrange resource-quota group-version-resource spec

- content/hi/examples/controllers/daemonset.yaml
- content/hi/examples/controllers/fluentd-daemonset-update.yaml
- content/hi/examples/controllers/fluentd-daemonset.yaml
https://github.com/kubernetes/website/pull/51626/files
> [hi] Updated fluentd image version in DaemonSet example

- hugo.toml
Updating hugo.toml for release v1.34.
/hold until v1.34 release.
> Updates hugo.toml for v1.31 ahead of v1.34 release

- content/zh-cn/docs/reference/using-api/_index.md
content/zh-cn/docs/reference/using-api/_index.md
> [zh-cn]sync using-api/_index.md

- content/pl/docs/reference/glossary/kube-scheduler.md
- content/pl/docs/reference/glossary/pod-disruption.md
> [pl] sync with PR 50342

- content/pt-br/docs/concepts/extend-kubernetes/api-extension/_index.md
Update page concepts/extend-kubernetes/api-extension/_index.md to include missing content and fix a spelling issue with the Portuguese term "estendendo".
---
Este PR atualiza a página índice da seção Estendendo a API do Kubernetes para refletir a versão mais recente em inglês e corrigir a ortografia da palavra "estendendo".
Closes: #52062
> [pt-br] Update concepts/extend-kubernetes/api-extension

- content/en/blog/_posts/2025-09-08-volume-attributes-class-ga/index.md
Schedules https://github.com/kubernetes/website/pull/51227 for publication on Monday, 8th September, 2025.
> Schedule KEP-3751 blog for publication

- content/fa/partners/_index.html
Localize `/partners/_index.html` [fa]
> [fa] translate /partners/_index.html

- content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md
- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAAdminAccess.md
- content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
content/zh-cn/docs/tasks/administer-cluster/kubelet-credential-provider.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/DRAAdminAccess.md
> [zh-cn]sync container-lifecycle-hooks kubelet-credential-provider DRAAdminAccess

- content/zh-cn/docs/concepts/storage/projected-volumes.md
- content/zh-cn/examples/pods/storage/projected-podcertificate.yaml
content/zh-cn/docs/concepts/storage/projected-volumes.md
> [zh-cn] Sync projected-volumes and its yaml

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WatchList.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/WatchList.md
> [zh-cn]sync WatchList

- content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
- content/zh-cn/docs/concepts/cluster-administration/system-traces.md
- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
content/zh-cn/docs/concepts/cluster-administration/system-metrics.md
content/zh-cn/docs/concepts/cluster-administration/system-traces.md
> [zh-cn]sync system-metrics device-plugins system-traces

- content/id/examples/controllers/daemonset.yaml
sync with upstream https://github.com/kubernetes/website/pull/51626/files
> [id] sync examples/controllers/daemonset.yaml

- content/en/docs/reference/command-line-tools-reference/feature-gates/WinDSR.md
- content/en/docs/reference/command-line-tools-reference/feature-gates/WinOverlay.md
Follow up to https://github.com/kubernetes/website/pull/51505#pullrequestreview-3087638149
Part of https://github.com/kubernetes/enhancements/issues/5100
Closes: #
> Updating windsr/winoverlay feature-gate markdown files for v1.34

- content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletCgroupDriverFromCRI.md
- content/zh-cn/docs/reference/instrumentation/node-metrics.md
- content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md
content/zh-cn/docs/reference/command-line-tools-reference/feature-gates/KubeletCgroupDriverFromCRI.md
content/zh-cn/docs/reference/instrumentation/node-metrics.md
content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md
> [zh-cn]sync KubeletCgroupDriverFromCRI node-metrics implementation-details

- content/id/docs/tasks/manage-kubernetes-objects/kustomization.md
https://github.com/kubernetes/website/pull/51472/files
> [id] Avoid YAML parsing error in kustomization.yaml

- content/zh-cn/docs/concepts/storage/volumes.md
> [zh-cn]sync storage/volumes

- content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
> [zh-cn]sync device-plugins.md

- content/ja/docs/tasks/administer-cluster/extended-resource-node.md
sync content/ja/docs/tasks/administer-cluster/extended-resource-node.md with PR #52083
> [ja] sync extended-resource-node.md

- content/en/blog/_posts/2025-xx-xx-pod-level-resources/index.md
Feature blog PR for Pod Level Resources graduation to beta
https://github.com/kubernetes/enhancements/issues/2837
> Add Pod Level Resources Blog Post

- content/bn/careers/_index.html
Add careers page for Kubernetes in Bengali
#47747
> [bn] Add careers page for Kubernetes in Bengali

- content/id/docs/concepts/configuration/overview.md
> [id] sync with PR #52155

- content/hi/docs/tutorials/hello-minikube.md
hi localization of PR https://github.com/kubernetes/website/pull/51364 to update the hello-minikube image used in the tutorial from k8s.gcr.io/echoserver to registry.k8s.io/e2e-test-images/agnhost
/hold until PR https://github.com/kubernetes/website/pull/51364 merges
> [hi] hi localization of PR 51364 to update hello-minikube image

- content/ja/docs/concepts/services-networking/connect-applications-service.md
https://github.com/kubernetes/website/pull/51751/files
> [ja] Fix broken links to https-nginx example

- content/ja/docs/tasks/administer-cluster/safely-drain-node.md
Translated [/content/en/docs/tasks/administer-cluster/safely-drain-node.md](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/safely-drain-node.md) into Japanese.
Closes: #51081 
/language ja
> [ja] Translated /content/en/docs/tasks/administer-cluster/safely-drain-node.md into Japanese

- content/zh-cn/blog/_posts/2025-09-10-introducing-env-files/index.md
Follow up of https://github.com/kubernetes/website/pull/52202.
Closes: #52257
> sync blog publish date of v1.34 env files blog

- content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/_index.md
> [zh-cn]sync kubectl_cluster-info/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_serviceaccount.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_serviceaccount.md
> [zh-cn]sync kubectl_set_serviceaccount.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_subject.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_subject.md
> [zh-cn]sync kubectl_set_subject.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_annotate/_index.md
> [zh-cn]sync kubectl_annotate/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_api-resources/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_api-resources/_index.md
> [zh-cn]sync kubectl_api-resources/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_selector.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_selector.md
> [zh-cn]sync kubectl_set_selector

- content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_resources.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_set/kubectl_set_resources.md
> [zh-cn]sync kubectl_set_resources.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_debug/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_debug/_index.md
> [zh-cn]sync kubectl_debug/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_expose/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_expose/_index.md
> [zh-cn]sync kubectl_expose/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/kubectl_cluster-info_dump.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cluster-info/kubectl_cluster-info_dump.md
> [zh-cn]sync kubectl_cluster-info_dump.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_edit/_index.md
> [zh-cn]sync kubectl_edit/_index.md

- content/id/includes/task-tutorial-prereqs.md
Sync content/id/includes/task-tutorial-prereqs.md with upstream
https://github.com/kubernetes/website/blob/5622fb7bedbd3253d643f96f00b3fe2a80bd85c3/content/en/includes/task-tutorial-prereqs.md?plain=1#L7
> [id] sync content/id/includes/task-tutorial-prereqs.md

- content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
https://github.com/kubernetes/website/pull/51659/files
> [ko] fix: instrumentation guidelines link in device plugin page

- content/zh-cn/docs/tasks/configure-pod-container/assign-resources/set-up-dra-cluster.md
content/zh-cn/docs/tasks/configure-pod-container/assign-resources/set-up-dra-cluster.md
> [zh-cn]sync set-up-dra-cluster

- content/zh-cn/docs/concepts/storage/storage-limits.md
- content/zh-cn/docs/setup/production-environment/container-runtimes.md
- content/zh-cn/docs/tasks/debug/_index.md
- content/zh-cn/docs/tasks/inject-data-application/define-environment-variable-container.md
content/zh-cn/docs/concepts/storage/storage-limits.md
content/zh-cn/docs/setup/production-environment/container-runtimes.md
content/zh-cn/docs/tasks/inject-data-application/define-environment-variable-container.md
content/zh-cn/docs/tasks/debug/_index.md
> [zh-cn]sync storage-limits container-runtimes define-environment-variable-container debug

- content/zh-cn/docs/reference/node/seccomp.md
- content/zh-cn/docs/tutorials/hello-minikube.md
content/zh-cn/docs/reference/node/seccomp.md
content/zh-cn/docs/tutorials/hello-minikube.md
> [zh-cn]sync seccomp hello-minikube

- content/zh-cn/releases/_index.md
content/zh-cn/releases/_index.md
> [zh-cn]sync releases/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_logs/_index.md
> [zh-cn]sync kubectl_logs/_index.md

- data/releases/schedule.yaml
cc @kubernetes/release-managers
> website: update patch release schedule

- content/es/case-studies/_index.html
sync case-studies/_index.html with upstream
https://github.com/kubernetes/website/blob/main/content/en/case-studies/_index.html
> [es] sync case-studies/_index.html

- content/ja/docs/concepts/storage/volumes.md
https://github.com/kubernetes/website/pull/51608/files
please double check just in case, I may be wrong as I am not a native speaker, thank you (sycn)
> [ja] Fix broken example volume links

- content/en/blog/_posts/2025-08-27-Kubernetes-v1-34-Release/index.md
Fixes typo in v1.34 Release Announcement
> Fix typo in v1.34 Release Announcement

- content/fr/docs/concepts/storage/volumes.md
https://github.com/kubernetes/website/pull/51608/files
> [fr] Fix broken example volume links

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_namespace.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_namespace.md
> [zh-cn]sync kubectl_create_namespace.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/kubectl_top_node.md
```
> [zh] Sync kubectl_top/kubectl_top_node.md

- content/es/docs/tutorials/hello-minikube.md
es localization of PR https://github.com/kubernetes/website/pull/51364 to update the hello-minikube image used in the tutorial from k8s.gcr.io/echoserver to registry.k8s.io/e2e-test-images/agnhost
/hold until PR https://github.com/kubernetes/website/pull/51364 merges
> [es] es localization of PR 51364 to update hello-minikube image

- content/en/docs/reference/access-authn-authz/authentication.md
A PR to improve the existing [Authentication reference page](https://kubernetes.io/docs/reference/access-authn-authz/authentication/). You can compare that to the [_preview_](https://deploy-preview-51914--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/authentication/).
- Reword the part about integration with external identity sources
Split out from PR https://github.com/kubernetes/website/pull/50364
/sig auth
/language en
> Reword explanation of external authn integrations

- OWNERS_ALIASES
Adding @khanhtc1202 and @ntheanh201 as owners/reviewers to the Vietnamese translation team.
Closes: #
> adding khanhtc1202 and ntheanh201 as owners/reviewers to the Vietnamese translation team

- content/vi/docs/reference/glossary/garbage-collection.md
Add Vietnamese translation for docs/reference/glossary/garbage-collection.md
NONE
> [vi] Add Vietnamese translation for Garbage Collection reference

- content/vi/docs/tasks/tools/install-kubectl.md
part of https://github.com/kubernetes/website/issues/52015
> [vi] Update kubectl install steps to pkgs.k8s.io

- content/vi/case-studies/_index.html
> [vi] sync with PR 45871

- content/vi/_index.html
> [vi] Update upcoming events

- content/vi/case-studies/golfnow/index.html
> [vi] sync with PR 51239

- content/vi/docs/concepts/architecture/mixed-version-proxy.md
- Add Vietnamese translation for mixed-version-proxy.md
- Link: https://kubernetes.io/docs/concepts/architecture/mixed-version-proxy/
NONE
> [vi] Add Vietnamese translation for mixed-version-proxy.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_deny.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/kubectl_certificate_deny.md
> [zh-cn]sync kubectl_certificate_deny.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_certificate/_index.md
> [zh-cn]sync kubectl_certificate/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_diff/_index.md
> [zh-cn]sync kubectl_diff/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_delete/_index.md
> [zh-cn]sync kubectl_delete/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cordon/_index.md
> [zh-cn]sync kubectl_cordon/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-users.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-users.md
> [zh-cn]sync kubectl_config_get-users.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_port-forward/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_port-forward/_index.md
> [zh-cn]sync kubectl_port-forward/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_cp/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_cp/_index.md
> [zh-cn]sync kubectl_cp/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_reconcile.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_reconcile.md
> [zh-cn]sync kubectl_auth_reconcile.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_label/_index.md
> [zh-cn]sync kubectl_label/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_patch/_index.md
> [zh-cn]sync kubectl_patch/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_api-versions/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_api-versions/_index.md
> [zh-cn]sync kubectl_api-versions/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_drain/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_drain/_index.md
> [zh-cn]sync kubectl_drain/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_whoami.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_whoami.md
> [zh-cn]sync kubectl_auth_whoami.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_cronjob.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_cronjob.md
> [zh-cn]sync kubectl_create_cronjob.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_quota.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_quota.md
> [zh-cn]sync kubectl_create_quota.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_service.md
> [zh-cn]sync kubectl_create_service.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrolebinding.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_clusterrolebinding.md
> [zh-cn]sync kubectl_create_clusterrolebinding.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_generic.md
> [zh-cn]sync kubectl_create_secret_generic.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_role.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_role.md
> [zh-cn]sync kubectl_create_role.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_docker-registry.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_docker-registry.md
> [zh-cn]sync kubectl_create_secret_docker-registry.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_auth/_index.md
> [zh-cn]sync kubectl_auth/_index.md

- content/en/docs/reference/command-line-tools-reference/feature-gates/ExternalServiceAccountTokenSigner.md
This PR fixes a broken link by fixing a typo.
n/a
> Fix typo on the broken link in the description of feature gate

- content/fr/docs/tutorials/hello-minikube.md
https://github.com/kubernetes/website/pull/51364/files
> [fr] Update image from echoserver to agnhost

- content/zh-cn/docs/reference/kubectl/generated/kubectl_wait/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_wait/_index.md
> [zh-cn]sync kubectl_wait/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_proxy/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_proxy/_index.md
> [zh-cn]sync kubectl_proxy/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_top/_index.md
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_top/_index.md
```
> [zh] Sync kubectl_top/_index.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_set.md
> [zh-cn]sync kubectl_config_set.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-clusters.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/kubectl_config_get-clusters.md
> [zh-cn]sync kubectl_config_get-clusters.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_config/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_config/_index.md
> [zh-cn]sync kubectl_config/_index.md

- content/pl/_index.html
> [pl] sync with PR 52153

- content/vi/docs/reference/glossary/ingress.md
- Add Vietnamese translation for Ingress
- Link: https://kubernetes.io/docs/reference/glossary/?architecture=true&networking=true&extension=true
NONE
> [Vi] Add Vietnamese translation for Ingress.md

- content/vi/docs/reference/glossary/persistent-volume-claim.md
- Add Vietnamese translation for Glossary Persistent Volume Claim
- Link: https://kubernetes.io/docs/reference/glossary/?storage=true
None
> [vi] Add Vietnamese transaltion for glossary Persistent Volume Claim

- content/vi/docs/reference/glossary/pod-disruption.md
- Add Vietnamese translation for Glossary Pod Disruption
- Link: https://kubernetes.io/docs/reference/glossary/?operation=true
None
> [vi] Add Vietnamese transaltion for glossary Pod Disruption

- content/en/docs/concepts/architecture/leases.md
- content/en/docs/concepts/cluster-administration/flow-control.md
> [en] fix small typo in documentation

- content/vi/docs/reference/glossary/immutable-infrastructure.md
- Add Vietnamese translation for "Immutable Infrastructure"
- Link: https://kubernetes.io/docs/reference/glossary/?user-type=true
NONE
Closes: #
> [vi] Add Vietnamese translation for "Immutable Infrastructure"

- content/vi/docs/reference/glossary/cluster-operations.md
- Add Vietnamese translation for cluster-operations.md
- Link: https://kubernetes.io/docs/reference/glossary/
NONE
> [vi] add Vietnamese translation for cluster operations glossary

- content/vi/docs/reference/glossary/rbac.md
Add Vietnamese translation for [RBAC](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/rbac.md)
None
> [vi] Add Vietnamese translation for RBAC

- content/vi/docs/reference/glossary/pod-disruption-budget.md
- Add Vietnamese translation for Glossary Pod Disruption Budget
- Link: https://kubernetes.io/docs/reference/glossary/?operation=true
None
> [vi] Add Vietnamese transaltion for glossary Pod Disruption Budget

- content/vi/docs/reference/glossary/group-version-resource.md
Description
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/group-version-resource.md
> [vi] add Vietnamese translation for glossary Group Version Resource

- content/ja/docs/reference/glossary/toleration.md
Translate content/en/docs/reference/glossary/toleration.md into Japanese
Closes: #50398
> [ja] Translate content/en/docs/reference/glossary/toleration.md into Japanese

- content/bn/case-studies/_index.html
sync case-studies/_index.html with upstream
https://github.com/kubernetes/website/blob/main/content/en/case-studies/_index.html
> [bn] sync case-studies/_index.html

- content/ko/docs/tasks/manage-daemon/create-daemon-set.md
Translate [/docs/tasks/manage-daemon/create-daemon-set](https://kubernetes.io/docs/tasks/manage-daemon/create-daemon-set/) into Korean
Fixes: #52022 
Closes: #52022
> [ko] Translate /docs/tasks/manage-daemon/create-daemon-set into Korean

- content/ko/docs/concepts/policy/limit-range.md
- Update `/ko/docs/concepts/policy/limit-range.md` to match the current English version
ㅤ
+ 행 개수를 일치시켰습니다.
+ `Note` 섹션을 추가 및 번역 했습니다.
Closes: #52230
> [ko] Sync /docs/concepts/policy/limit-range.md with latest EN

- content/zh-cn/docs/concepts/cluster-administration/networking.md
improve `content/zh-cn/docs/concepts/cluster-administration/networking.md`
Closes: #
> [zh-cn] improve cluster networking

- content/zh-cn/docs/reference/kubectl/generated/kubectl_completion/_index.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_completion/_index.md
> [zh-cn]sync kubectl_completion/_index.md

- content/en/docs/reference/_index.md
- content/en/docs/reference/config-api/apiserver-admission.v1.md
- content/en/docs/reference/config-api/apiserver-audit.v1.md
- content/en/docs/reference/config-api/apiserver-config.v1.md
- content/en/docs/reference/config-api/apiserver-config.v1alpha1.md
- content/en/docs/reference/config-api/apiserver-config.v1beta1.md
- content/en/docs/reference/config-api/client-authentication.v1.md
- content/en/docs/reference/config-api/client-authentication.v1beta1.md
- content/en/docs/reference/config-api/imagepolicy.v1alpha1.md
- content/en/docs/reference/config-api/kube-scheduler-config.v1.md
- content/en/docs/reference/config-api/kubeadm-config.v1beta3.md
- content/en/docs/reference/config-api/kubeadm-config.v1beta4.md
- content/en/docs/reference/config-api/kubeconfig.v1.md
- content/en/docs/reference/config-api/kubelet-config.v1.md
- content/en/docs/reference/config-api/kubelet-config.v1alpha1.md
- content/en/docs/reference/config-api/kubelet-config.v1beta1.md
- content/en/docs/reference/config-api/kubelet-credentialprovider.v1.md
- content/en/docs/reference/config-api/kuberc.v1beta1.md
> Config API for v1.34

- content/en/docs/reference/using-api/api-concepts.md
> Document PartialObjectMetadata accept param

- content/vi/docs/reference/glossary/jwt.md
- Add Vietnamese translation for jwt.md
- Link: https://kubernetes.io/docs/reference/glossary/?security=true&architecture=true
Closes: #
> [vi] add Vietnamese translation for jwt glossary

- content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md
```
content/zh-cn/docs/reference/kubectl/generated/kubectl_rollout/kubectl_rollout_undo.md
```
> [zh] Sync kubectl_rollout_undo.md

- content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_priorityclass.md
content/zh-cn/docs/reference/kubectl/generated/kubectl_create/kubectl_create_priorityclass.md
> [zh-cn]sync kubectl_create_priorityclass.md

- content/ja/docs/tasks/configure-pod-container/security-context.md
fix typo in tasks/configure-pod-container/security-context.md
> [ja] fix typo in tasks/configure-pod-container/security-context.md

- content/vi/docs/reference/glossary/istio.md
- Add Vietnamese translation for Istio
- Link: https://kubernetes.io/docs/reference/glossary/?extension=true&architecture=true&networking=true
NONE
Closes: #
> [Vi] Add Vietnamese translation for Istio

- content/en/docs/reference/kubectl/_index.md
- content/en/docs/reference/kubectl/quick-reference.md
Update KYAML output description to remove alpha-specific informationm, as it is now in beta stage.
Ref https://github.com/kubernetes/enhancements/issues/5295
Linked to https://github.com/kubernetes/enhancements/pull/5566/files#r2376196149
CC: @soltysh @lmktfy
> KYAML beta updates on docs

- content/id/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
https://github.com/kubernetes/website/pull/52355/files
> [id] replace cpu-percent with cpu

- hugo.toml
Updating hugo.toml for the 1.35 release.
Closes: #
> Updated  hugo.toml file for v1.35 Release

- content/ja/docs/concepts/security/linux-security.md
Translated [/docs/concepts/security/linux-security.md](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/security/linux-security.md) into Japanese.
Closes: #52546 
/language ja
> [ja] Translated /docs/concepts/security/linux-security.md into Japanese

- content/ko/docs/tasks/manage-daemon/pods-some-nodes.md
Translate [/docs/tasks/manage-daemon/pods-some-nods](https://kubernetes.io/docs/tasks/manage-daemon/pods-some-nodes/) into Korean
Closes: #52117
> [ko] Translate pods-some-nodes into Korean

- content/bn/blog/_posts/2024-05-09-gateway-api-v1.1/index.md
> [bn] sync with PR 50223

- content/en/blog/_posts/2025-10-20-seven-kubernetes-pitfalls-and-how-to-avoid.md
Publish article “7 Common Kubernetes Pitfalls (and How I Learned to Avoid Them)”
[Preview](https://deploy-preview-52630--kubernetes-io-main-staging.netlify.app/blog/2025/10/20/seven-kubernetes-pitfalls-and-how-to-avoid/)
Follows PR https://github.com/kubernetes/website/pull/49249
@kubernetes/sig-docs-blog-owners please review this.
> Publish blog article

- content/fr/docs/reference/glossary/workload.md
> [fr] sync with PR 43217

- content/vi/docs/reference/glossary/logging.md
Add Vietnamese translation for [logging](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/logging.md) 
None
> [vi] Add Vietnamese translation for logging

- content/vi/docs/reference/glossary/master.md
Add Vietnamese translation for [master](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/master.md)
None
> [vi] Add Vietnamese translation for Master
